### ISSUE TITLE
Switch to PyInstaller

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1004]
cx_Freeze is kind-of-dead, and has problems [with Ubuntu](https://bitbucket.org/anthony_tuininga/cx_freeze/issues/153/) and [with Python 3.5](https://bitbucket.org/anthony_tuininga/cx_freeze/issues/156/).

Maybe we should look for an alternative? It seems [py2exe](http://www.py2exe.org/) and [PyInstaller](http://www.pyinstaller.org/) support Python 3 in the meantime. It seems PyInstaller has built-in support for PyQt5 and is multiplatform (py2exe has [a wiki page](http://www.py2exe.org/index.cgi/Py2exeAndPyQt)).

Note those don't seem to be able to generate .msi files, so we'd have to use something like NSIS or Inno Setup instead...

**Comment by tidux** [comment]
PyInstaller is also somewhat broken on newer versions of OSX.  It doesn't detect the icns file or have a way to declare an application as retina-compatible.

**Comment by The-Compiler** [comment]
Fun... thanks for letting me know! Right now I wonder if I still should stick to cx_Freeze despite the pain, as there are various pain-points with switching to something else too (missing installer generation, missing integration with pytest to freeze tests, etc.).

**Comment by The-Compiler** [comment]
[pynsist](http://pynsist.readthedocs.org/en/latest/index.html) sounds interesting as well - it solves the issue by bundling/installing Python rather than freezing the application. Starting with Python 3.5, it can [also embed Python](http://pynsist.readthedocs.org/en/latest/cfgfile.html#bundled-python) with the application.

**Comment by The-Compiler** [comment]
[pyqtdeploy](http://pyqt.sourceforge.net/Docs/pyqtdeploy/introduction.html) would be another thing to look at

**Comment by The-Compiler** [comment]
FWIW, in the meantime I think switching to PyInstaller would be the best idea.

It's running smooth for our OS X packages, so it makes sense to use the same thing on Windows (and possibly Linux, see #1912).

The only missing thing is an [NSIS](http://nsis.sourceforge.net/) installer script which installs the generated files, because PyInstaller doesn't do that, and cx_freeze did.

I'm not strongly attached to NSIS FWIW, but it's open source and the installation compiler is available for Linux, which might be a plus.

The installer should do a clean update from the previous MSI installer, i.e. uninstall that first. It should also create a start menu entry, and maybe register qutebrowser as browser so it can be set as default in Windows' menu for that.

**Comment by The-Compiler** [comment]
After two years, there finally was a [cx_Freeze 5.0 release](http://cx-freeze.readthedocs.io/en/latest/releasenotes.html#version-5-0-november-2016). However, I can't even install it without a compiler and I still think PyInstaller is ahead of it, so I'll blacklist it for now.

**Comment by ozmartian** [comment]
I'd recommend giving Inno Setup a try guys. That is for your Windows installers, after producing a PyInstaller binary. I find its much easier and MUCH lighter, producing smaller sized binaries, It also works fine under Wine so you can skip needing to log into Windows if thats an issue (it is for some) NSIS is the more professional product, the only open source alternative to it and Inno Setup is the WIX Toolset in VS2015 but good luck learning that XML monstrosity, although it is powerful and produces the slickest installers of the lot.

I've been using PyInstaller for over a year, nothing out three comes close to it.. If you'r not doing so already, don't use the stable 3.2 version, clone it from Github and switch from master to the "develop" branch. Its always just as stable but includes fixs for most things you may run into trouble with on stable.

Python 3.6 isn't yet supported though but works for some of my projects. Anything complex starts to have issues though, hopefully resolved ASAP.

**Comment by The-Compiler** [comment]
Working on PyInstaller for Windows now. Seems to work fine after copying the following DLLs over by hand:

- `libEGL.dll`
- `libGLESv2.dll`
- `libeay32.dll`
- `ssleay32.dll`

**Comment by The-Compiler** [comment]
I did some test builds based on the current master, and they seem to work for me! Can other people on Windows please test them too?


[64 bit](https://qutebrowser.org/tmp/win-test/qutebrowser-0.10.1-windows-standalone-amd64.zip)
[32 bit](https://qutebrowser.org/tmp/win-test/qutebrowser-0.10.1-windows-standalone-win32.zip)

**Comment by bitraid** [comment]
They seem to work fine for me too.

**Comment by The-Compiler** [comment]
I cleaned up and merged that branch now, and 9898d80625318532e14009bfc4cbb5bf6fb1984b removed cx_Freeze. A NSIS installer is still open (#2187) but will follow with the next release.

**Comment by The-Compiler** [comment]
And now I have an installer which could use some testing:

[64 bit](https://qutebrowser.org/tmp/qutebrowser-0.11.0-pre-amd64.exe)
[32 bit](https://qutebrowser.org/tmp/qutebrowser-0.11.0-pre-win32.exe)

**Comment by andreatta** [comment]
Works great on Windows 10 (x64) as long as no qutebrowser instance is running, else we get this error message.

```
---------------------------
qutebrowser Setup
---------------------------
Error opening file for writing: 
C:\Program Files\qutebrowser\MSVCP140.dll
Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.
---------------------------
Abort   Retry   Ignore   
---------------------------
```

No problem really, but it would be nice to have the installer recognizing any running instances and give the opportunity to close it.

**Comment by The-Compiler** [comment]
Good idea, but it doesn't seem as straightforward as I'd like - I added it to #2660.

**Comment by bitraid** [comment]
That error happens only when the running instance is on the same directory as the one you are trying to install (locked files). So maybe a warning if the installation directory exists should be better.
Also maybe use solid lzma compression to decrease the installer size?

**Comment by bitraid** [comment]
A good idea would also be to detect if already installed and prompt to uninstall the old version before continuing. See: [http://nsis.sourceforge.net/Auto-uninstall_old_before_installing_new](http://nsis.sourceforge.net/Auto-uninstall_old_before_installing_new)

**Comment by The-Compiler** [comment]
I added the auto-uninstall to #2660 too (please use that for future suggestions, by the way :smile:), and switched to solid lzma in https://github.com/qutebrowser/qutebrowser/commit/54a4a087d48c44c58b50fceb5df52e722ecd2e18
