### ISSUE TITLE
Config errors improvements

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#102]
- The errors shouldn't be hard errors, e.g. when an `user-stylesheet` file is deleted
- We probably should show _all_ errors in a single error message, and then have a "quit" and a "backup and proceed" button.

**Comment by antoyo** [comment]
What about having undefined options?
It happens a lot to me (and probably other developers) because I often switch branches.
I think it should only be a warning and allow to use the browser.
I could fix this.

**Comment by The-Compiler** [comment]
The problem is that with the current way the config is written, when an user would make a typo, it'd lead to the line being removed from the config when saving it.

You can start with `--relaxed-config` to ignore the unknown options, or with `--temp-basedir` to start a second instance with a clean state (which is useful for developing as well sometimes).

**Comment by The-Compiler** [comment]
Done with the new config.
