### ISSUE TITLE
Don't close all windows with :quit?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1089]
Some people are confused by `:quit` closing _all_ windows - maybe `:quit` should only close one window (like `:close`) and have an `--all` switch instead?

**Comment by vyp** [comment]
What about `:qa/:quitall` commands just like in vim?

**Comment by The-Compiler** [comment]
Adding `:qa` as an alias for `:quit --all` (like `:q` for `:quit`) - why not. But I'd rather not add a distinct `:quitall` command: I think having commands with arguments rather than e.g. `:foo`, `:winfoo` and `:tabfoo` is a good thing.

**Comment by vyp** [comment]
Okay cool.

**Comment by Earnestly** [comment]
`:q` in prior art such as vimperator or pentadactyl do only close one tab as well.  I suppose they were striving for a more authentic vim experience.

**Comment by forkbong** [comment]
`:wq` would probably also need to change for consistency. In that case what would be the expected behaviour for `:session-save` and `:w`?

**Comment by Earnestly** [comment]
In other browsers that do this, `:w` writes the page itself.  With full tab-completion for directories and so on.
