### ISSUE TITLE
Auto-save open tabs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#11]
A list of open tabs should be auto-saved from time to time to recover when there's a segfault in Qt.
When sessions are implemented this should also work per session.
The same thing should also work for things like the config.

**Comment by The-Compiler** [comment]
I have a partially working patch here:

```diff
diff --git a/qutebrowser/app.py b/qutebrowser/app.py
index 234d2dd..a9e87a9 100644
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
@@ -266,8 +266,12 @@ class Application(QApplication):
                 message.error('current', "set: {} - {}".format(
                     e.__class__.__name__, e))
 
+        session_manager = objreg.get('session-manager')
         if not self._args.override_restore:
-            self._load_session(self._args.session)
+            if session_manager.exists('_recovery'):
+                session_manager.load('_recovery')
+            else:
+                self._load_session(self._args.session)
         session_manager = objreg.get('session-manager')
         if not session_manager.did_load:
             log.init.debug("Initializing main window...")
@@ -864,6 +868,10 @@ class Application(QApplication):
         elif config.get('general', 'save-session'):
             session_manager.save(sessions.default, last_window=last_window,
                                  load_next_time=True)
+        try:
+            session_manager.delete('_recovery')
+        except sessions.SessionNotFoundError:
+            pass
 
         deferrer = False
         for win_id in objreg.window_registry:
diff --git a/qutebrowser/misc/sessions.py b/qutebrowser/misc/sessions.py
index aeddea9..fbda779 100644
--- a/qutebrowser/misc/sessions.py
+++ b/qutebrowser/misc/sessions.py
@@ -21,6 +21,7 @@
 
 import os
 import os.path
+import functools
 
 from PyQt5.QtCore import pyqtSignal, QUrl, QObject, QPoint, QTimer
 from PyQt5.QtWidgets import QApplication
@@ -50,6 +51,11 @@ def init(parent=None):
     session_manager = SessionManager(parent)
     objreg.register('session-manager', session_manager)
 
+    save_manager = objreg.get('save-manager')
+    save_manager.add_saveable(
+        'recovery', functools.partial(session_manager.save, '_recovery'),
+        changed=session_manager.recovery_dirty, dirty=True)
+
 
 class SessionError(Exception):
 
@@ -75,9 +81,11 @@ class SessionManager(QObject):
     Signals:
         update_completion: Emitted when the session completion should get
                            updated.
+        recovery_dirty: Emitted when the recovery session was changed.
     """
 
     update_completion = pyqtSignal()
+    recovery_dirty = pyqtSignal()
 
     def __init__(self, parent=None):
         super().__init__(parent)
```

What's missing is emitting `recovery_dirty` at the right time - but we also should have some widget to let the user select what to recover, as recovering *everything* will probably just trigger the same segfault again.

As this will be some more work, removing this from v0.3.

**Comment by krobelus** [comment]
This would be nice to have. Maybe just save the default session every auto-save-interval? I think it would make sense since the history is written at this point too.

**Comment by The-Compiler** [comment]
The problem is that it's often a page causing the crash, so *automatically* loading it again will just cause a crash loop until you edit the session file.

I can see two solutions for that:

- Having an UI after the first start after a crash which allows you to select what pages you want to restore
- Simply saving to a `_autosave` session or so so at least you could load it by hand after a crash, but without any better UX yet.

**Comment by krobelus** [comment]
I see. I think the second option would be fine. Currently I have segfaults on github repo pages, so this would be great until it is fixed via QtWebEngine.

**Comment by The-Compiler** [comment]
If you have some emoji font installed (like Google Noto), try if uninstalling that helps with the crashes.

**Comment by The-Compiler** [comment]
Implemented in master - without a selective restore, but saving on successful loads only, which should hopefully not save things causing crashes.

**Comment by MarSoft** [comment]
How is it currently implemented in master? For me it looks like the session is still not auto-saved, and is only saved when saving it manually.
Would be nice to automatically save it under some special name like `_autosave` as suggested above.

Looking at the code it seems that session is already saved to `_autosave` every time any page finishes loading. But for some reason I cannot load that autosaved session, it is just not listed among available sessions.
Is it possible to restore accidentally closed window from autosaved session?

**Comment by The-Compiler** [comment]
The `_autosave` session is marked as "internal" (which it is), and is used to recover things on crashes. You can force loading it with `:session-load -f _autosave`, but I'm not sure if that's what you want.

As for restoring accidentally closed windows, see #1031.

**Comment by pc00per** [comment]
How to autosave on browser close? And then auto reload on browser open? Just like how we used to chrome's "Continue where you left off".

**Comment by The-Compiler** [comment]
@pc00per Use `:wq` or set `auto_save.session`. Nothing to do with this issue, however...

**Comment by pc00per** [comment]
@The-Compiler Thanq vm. I normally have a habit of ctrl-q to close any browser. I can still continue where I left off btw. 👍
