### ISSUE TITLE
<Space> keybindings do not work

### ISSUE THREAD

**Issue by vyp** [qutebrowser/qutebrowser#1120]
From https://github.com/The-Compiler/qutebrowser/issues/1117#issuecomment-156943094.

Using:

```
<unbound>

    sf
    ss
    sl
    sk

set-cmd-text -s :open google
     g
    s

scroll-perc 0
    gg
```

The line after `<unbound>` if **five** spaces. First four spaces for the usual indentation, last space as a literal space to say that any existing `<Space>` binding should be unbound. Similarly, the line below the google command is five spaces and a `g`, to signify a `<Space>g` keybinding. This is all under the `[normal]` mode section.

The problem is that after pressing `<Space>g` in qutebrowser, it does work, but there's a delay. Whereas pressing `s` is instantaneous.

The last `scroll-perc` part is put there because perhaps that has something to do with it? i.e. When determing if there should be a delay, it does not for whatever reason recognise the `<Space>` key being pressed, and hence, when `g` is pressed straight after, it sees this `gg` binding and therefore delays before finally executing `set-cmd-text -s :open google`?

That being said, I haven't tested without the `gg` binding. I will do so (and do some other tests) in a few days when I get a bit more time.

``` shell
$ qutebrowser --version
qutebrowser v0.4.1
Git commit:

CPython: 3.4.3
Qt: 5.4.2, runtime: 5.4.2
PyQt: 5.4.2
```

**Comment by vyp** [comment]
Stumbled on this by accident, if I just press `g` and wait, after a delay, it executes `set-cmd-text -s :open google`. So what I therefore think is *actually* happening is that the `<Space>g` mapping is not working at all. i.e. the `<Space>` is not being picked up at all, but then it does pick up the `g`, and therefore, after a delay due to having other bindings that start with `g` (i.e. `gg`), it executes `set-cmd-text -s :open google`.

**Comment by The-Compiler** [comment]
This works fine with the new config (when binding ` x`, not `<Space>x`).
