### ISSUE TITLE
Wrong scroll position for URLs with fragments opened in background tabs

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#1190]
On [The Wiki](https://wiki.archlinux.org/index.php/Main_page), there are many links to sections using the [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) in the URL. Patrolling the wiki involves opening many such links in background tabs, so I've noticed an issue with the accuracy of scrolling to the ancor position. It seems that every such URL is opened at a completely wrong position when opened in a background tab. Reopening the same URL with `:open <current URL>` opens it at correct position, as well as opening arbitrary sections in the current tab (e.g. by navigating the page's ToC). What has to be done to improve the situation?

**Comment by The-Compiler** [comment]
I've noticed this before too, and unfortunately I have no idea why it happens. It might be some kind of QtWebKit bug.

I can't always reproduce it, though - for example if I open https://wiki.archlinux.org/index.php/List_of_applications and navigate to "Graphical" in the TOC via `;b`, the background tab gets scrolled to the correct location.

**Comment by lahwaacz** [comment]
Well, for me it doesn't. But I think I've also noticed it doesn't happen always, just most of the time. Generally it is problematic for browsers when javascript can change the size of other elements after the page is loaded, but I don't think it's the case here...

**Comment by lahwaacz** [comment]
There is another issue regarding the scroll position on MediaWiki pages. Consider the page https://wiki.archlinux.org/index.php/Install, which is a redirect to https://wiki.archlinux.org/index.php/Help:Reading#Installation_of_packages, i.e. a section of another page. However, when the former link is opened in qutebrowser, it stays at the top of the page. It happens even in foreground, but it may be the same issue as wirh the background loading.

Since MediaWiki version 1.25, redirects involve opening the page corresponding to the old URL (which includes a "redirected from ..." below the page title) and then running a piece of JavaScript code to rewrite the browser's URL to the URL of the target, so reloading the page with the new URL obviously gets me to the desired position. But I doubt that JavaScript is part of the real issue...

**Comment by The-Compiler** [comment]
FWIW, I see the issue with the redirects with Chromium as well. It seems to work fine with Firefox only.

**Comment by epitron** [comment]
I have a theory: what if the size of the elements isn't being calculated correctly when the tab isn't visible? Or what if the background tab is jumping to the fragment before the layout is finished being computed?

A possible workaround could be to force the tab to jump to the anchor when a user switches to the background tab for the first time...

**Comment by The-Compiler** [comment]
It seems like it always works when focusing the background tab *before* it finished loading, and the position is wrong when focusing it after loading.

**Comment by lahwaacz** [comment]
Some Javascript magic to make this work:
```js
location.replace(location.href);
```
If executed when the background tab is visited for the first time, it causes the browser to set the scroll position to the anchor without actually reloading the page.

**Comment by lahwaacz** [comment]
Just noting that the webengine backend has the same issue, so we can rule out the webkit bug. Moreover, when a session is restored after startup with webengine, all pages are loaded at the top, even if the URL contans a fragment identifier.

**Comment by The-Compiler** [comment]
[QTBUG-54172](https://bugreports.qt.io/browse/QTBUG-54172) seems to be the same issue for QtWebEngine FWIW.

**Comment by dkasak** [comment]
I've found an example that seems to never work for me, regardless of whether it is opened in a background or foreground tab (or even when simply following the link in the current tab): https://github.com/The-Compiler/qutebrowser/blob/v0.9.0/qutebrowser/javascript/webelem.js#L69-L106

The lines mentioned in the fragment don't get highlighted and qutebrowser displays the page from the top, not scrolled at all.

**Comment by The-Compiler** [comment]
@dkasak works fine for me. Can you reproduce it with `--temp-basedir`? How exactly are you following the link? What backend and Qt version are you using (see `:open qute:version`)?

**Comment by dkasak** [comment]
Yes, I've tested with `--temp-basedir`.

From `qute:version`:

    Backend: QtWebKit (WebKit 538.1)
    Qt: 5.8.0
    PyQt: 5.8

This is on Arch Linux.

**Comment by The-Compiler** [comment]
Can you try with QtWebEngine (install `qt5-webengine` and either remove `qt5-webkit` or start with `--backend webengine`), or with QtWebKit-NG (install `qt5-webkit-ng`)?

**Comment by dkasak** [comment]
`qt5-webengine` works, though it doesn't scroll the starting line all the way to the top with `f` or `F`, but does with `;b`. I'll test with `qt5-webkit-ng` a bit later.

**Comment by lahwaacz** [comment]
Github links to source code are not a good representative for this bug, because the highlighting relies on javascript and so does probably even scrolling. In webengine, the scroll position of @dkasak's link is correct even when followed in background (with `F` and waiting until the page is loaded before switching to it), but plain non-javascript anchors still have the same bug.

**Comment by dkasak** [comment]
@lahwaacz Do you mean `;b`? `F` switches to the new tab immediately for me and the scroll position is not completely right with webengine. It scrolls so the highlighted lines are at least visible on the screen, but the first line is roughly centered instead of being the first line displayed.

**Comment by lahwaacz** [comment]
I have `tabs->background-tabs` set to `true`, so I guess my `F` behaves like your `;b`...

**Comment by The-Compiler** [comment]
I see the same behavior in Firefox and Chromium. At this point the question is why it scrolls to the line when opening it in a background tab, but that seems like a Qt issue.

**Comment by lahwaacz** [comment]
As I was trying to point out, Github's javascript might call [scrollTo](https://www.w3schools.com/jsref/met_win_scrollto.asp) or something like that...

**Comment by dkasak** [comment]
FWIW, `qt5-webkit-ng` behaves the same as `qt5-webkit`.

**Comment by lahwaacz** [comment]
Arch updated to Qt 5.9 couple of days ago and this issue is becoming even bigger problem for me, because using `:reload -f` or `:open -t <current-url>` no longer work as a workaround to get me to the correct position. If (and only if) the tab was opened in background, there is a short flash at the correct position while reloading, but then the position is changed to the previous position from before I reloaded the page.

At least the issue with moving the window across screens with different resolutions seems to be fixed in 5.9, but that somewhat breaks the relation between this issue and https://github.com/qutebrowser/qutebrowser/issues/2495#issuecomment-290787881 :confused:

**Comment by The-Compiler** [comment]
I think I have a workaround for this, but it's not entirely correct yet. Stay tuned! :wink:

**Comment by The-Compiler** [comment]
Fixed for everything I was able to test, indeed by setting the size of background tabs correctly. 🎉 

Thanks everyone for the help with tracking this down!
