### ISSUE TITLE
Non-latin input in normal mode problems

### ISSUE THREAD

**Issue by derlaft** [qutebrowser/qutebrowser#1207]
I have an installation with multiple keyboard layouts. For example, I have "o" (us) and "щ" (SHCH, ru) on the same button.

What do I have now (normal mode):
- When I press O, :open triggers
- When I press SHCH, nothing happens
  - But, if I press Shift+SHCH, it falls to selected input field (BUG!) (1)
    - Binding to Shift+SHCH works good

What would be great to have:
- When I press O or SHCH :open triggers

I could just add all the keys I have into keys.conf, but what If I had three or more keyboard layouts?

What xev tells about O, SHCH, Shift+SHCH:

```
 KeyRelease event, serial 40, synthetic NO, window 0x3600001,
     root 0xd3, subw 0x0, time 52892543, (784,341), root:(784,379),
     state 0x0, keycode 32 (keysym 0x6f, o), same_screen YES,
     XLookupString gives 1 bytes: (6f) "o"
     XFilterEvent returns: False

KeyPress event, serial 40, synthetic NO, window 0x3600001,
    root 0xd3, subw 0x0, time 52769442, (913,537), root:(913,575),
    state 0x2000, keycode 32 (keysym 0x6dd, Cyrillic_shcha), same_screen YES,
    XLookupString gives 2 bytes: (d1 89) "щ"
    XmbLookupString gives 2 bytes: (d1 89) "щ"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x3800001,
    root 0xd3, subw 0x0, time 53529959, (840,1041), root:(840,1079),
    state 0x2001, keycode 32 (keysym 0x6fd, Cyrillic_SHCHA), same_screen YES,
    XLookupString gives 2 bytes: (d0 a9) "Щ"
    XFilterEvent returns: False
```

**Comment by The-Compiler** [comment]
First of all: I'm mainly working with the information Qt gives me, which is the text a keyboard button is associated with, and you bind a key *to that text*. So I'm not entirely sure if I'm able to change anything about this.

Also, I'm not sure I understand correctly - what do you mean with "if I press Shift+SHCH, it falls to selected input field"?

**Comment by derlaft** [comment]
>Also, I'm not sure I understand correctly - what do you mean with "if I press Shift+SHCH, it falls to selected input field"?

It acts as if I press Shift+SHSH in insert mode. I.e. SHCH appears in the input field.

**Comment by The-Compiler** [comment]
Could you please do the following?

- Start a new qutebrowser instance with `--temp-basedir`
- Press SHCH and Shift+SHCH and then run `:report`

This will send a debug report with the necessary informations in the debug log.

**Comment by derlaft** [comment]
Done

**Comment by derlaft** [comment]
>I'm mainly working with the information Qt gives me, which is the text a keyboard button is associated with, and you bind a key to that text. So I'm not entirely sure if I'm able to change anything about this.

I am not sure, but don't you need QKeyEvent::nativeScanCode()?

**Comment by The-Compiler** [comment]
Relevant log:

```
statusbar  bar:_hide_cmd_widget:390 Hiding cmd widget, queue: deque([])
modes      tabbedbrowser:on_mode_left:509 Left status-input mode, focusing <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>
webview    webview:on_mode_left:491 Restoring focus policy because mode KeyMode.command was left.
modes      modeman:_eventFilter_keypress:195 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False, is_tab False --> filter: True (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
completion completer:update_cursor_part:430 cursor_part 0, spaces False
completion completer:update_completion:307 Updating completion - prefix , parts [''], cursor_part 0
modes      modeman:_eventFilter_keyrelease:215 filter: True
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 No binding found for .
keyboard   basekeyparser:_debug_log:107 Got key: 0x0 / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keyrelease:215 filter: False
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
keyboard   basekeyparser:_debug_log:107 Got key: 0x1000020 / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 No binding found for shift+щ.
keyboard   basekeyparser:_debug_log:107 Got key: 0x429 / text: 'Щ'
keyboard   basekeyparser:_debug_log:107 Giving up with 'Щ', no matches
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keyrelease:215 filter: False
modes      modeman:_eventFilter_keyrelease:215 filter: False
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
keyboard   basekeyparser:_debug_log:107 Got key: 0x1000020 / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 No binding found for shift+щ.
keyboard   basekeyparser:_debug_log:107 Got key: 0x429 / text: 'Щ'
keyboard   basekeyparser:_debug_log:107 Giving up with 'Щ', no matches
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keyrelease:215 filter: False
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 No binding found for shift+щ.
keyboard   basekeyparser:_debug_log:107 Got key: 0x429 / text: 'Щ'
keyboard   basekeyparser:_debug_log:107 Giving up with 'Щ', no matches
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keyrelease:215 filter: False
modes      modeman:_eventFilter_keyrelease:215 filter: False
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 No binding found for .
keyboard   basekeyparser:_debug_log:107 Got key: 0x0 / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keyrelease:215 filter: False
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
keyboard   basekeyparser:_debug_log:107 Got key: 0x1000020 / text: ''
keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
modes      modeman:_eventFilter_keypress:195 handled: False, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True, is_tab False --> filter: False (focused: <qutebrowser.browser.webview.WebView tab_id=0 url='https://duckduckgo.com/'>)
modes      modeman:_eventFilter_keypress:168 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
keyboard   basekeyparser:_debug_log:107 No binding found for shift+:.
```

> I am not sure, but don't you need QKeyEvent::nativeScanCode()?

That might be a possibility, yes - but bindings would be rather awkward. I'll investigate this later.

I still think shift+щ being passed through is a separate bug, though.

**Comment by The-Compiler** [comment]
How important is the "bind scancodes" thing to you? I'd rather not have it to be honest, it's additional complexity for a very rare usecase.

The issue with shift-chars being passed through should be fixed.

**Comment by derlaft** [comment]
I can work-around it with dublicating every single command in my layout, but that's pain.

>it's additional complexity for a very rare usecase.

Why can't you replace keycode with native_keycode when it's normal mode? That's what usually is done when processing keyboard shortcuts, If I am correct.

**Comment by The-Compiler** [comment]
How do other tools (say, vim) handle this? Can you press `щ` there and it gets handled like `o`?

`nativeScanCode` is just that, a scan code, i.e. a number - which means you'd need to map those numbers in your key config (and some syntax will need to be added for that), which surely isn't convenient either.

There's also `nativeVirtualKey` which returns some *other* code, but for both of them I don't think it's possible to convert them to a text, which is ultimately what I need for the config.

**Comment by derlaft** [comment]
By default, vim does nothing, but ```set keymap=russian-jcukenwin``` solves it

**Comment by derlaft** [comment]
>nativeScanCode is just that, a scan code, i.e. a number - which means you'd need to map those numbers in your key config

Isn't that ascii code of the pressed key?

**Comment by The-Compiler** [comment]
> By default, vim does nothing, but ```set keymap=russian-jcukenwin``` solves it

So you're still using the english keymapping, and use vim's config to map that to russian if I understand correctly.

> Isn't that ascii code of the pressed key?

No, it's not - check https://en.wikipedia.org/wiki/Scancode

I'm closing this - I definitely don't want to ship separate keyboard mappings with qutebrowser.

**Comment by derlaft** [comment]
That is very, very sad.

Maybe you can use/copy [the workaround from qt](https://codereview.qt-project.org/gitweb?p=qt/qtbase.git;a=blobdiff;f=src/plugins/platforms/xcb/qxcbkeyboard.cpp;h=260fb46309abfe01e26eaf01f5fac64ed58abbb6;hp=dae3a79628a8e73c7afeae062562dc1cda5e4cd8;hb=2b666d9576210aa98700e219dba6b1bd4f93d793;hpb=cc1435952d796476616f54319c1ddf57eeaf80f7)? See XcbKeyboard::lookupLatinKeysym

**Comment by The-Compiler** [comment]
Hm, interesting - I'll have to check if I can somehow use this via the public Qt API. Reopening for now, but don't expect me to work on this anytime soon - unfortunately there's a lot of stuff which is more important to me right now.

**Comment by derlaft** [comment]
Thank you very much.

**Comment by The-Compiler** [comment]
Unfortunately I can't access that API via PyQt. However, the new config (in the `new-config` branch, probably merged in September) will have a `bindings.key_mappings` setting which at least lets you bind keys to other keys, so you could do the necessary mapping by hand there.
