### ISSUE TITLE
Handle PageUp/PageDown for completion

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1248]

**Comment by The-Compiler** [comment]
As pointed out by @toofar, you can do something like `:bind --mode=command <PgDown> repeat 14 completion-item-focus next` as a workaround.

**Comment by Kenoben** [comment]
Hi, I would like to tackle this as it is an easy issue and I already appear to have code that works (I think).

**Comment by The-Compiler** [comment]
Go ahead! My bandwidth for reviewing PRs is currently a bit limited, but this should be simple enough to squeeze it in :wink:

**Comment by The-Compiler** [comment]
Fixed via #4301
