### ISSUE TITLE
Support for multiple user-stylesheet files

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#135]
The `user-stylesheet` option should support multiple files which then will get merged, e.g. via [cssutils](https://pypi.python.org/pypi/cssutils).

This will also make #29 and scrollbar hiding easier as they'll still work when the user sets his own stylesheet.

**Comment by haasn** [comment]
Minor feature request related to this:

Without thinking too hard about the implementation details, to me as an end-user it would be useful if I could store and edit my per-site stylesheets in individual files, perhaps below a directory to indicate the domain name it applies to.

Some of my style sheets are quite long, and having them as raw files gives me the most flexibility w.r.t how I want to edit, maintain, update and synchronize these style sheets - certainly much better than having some 2000 character long line sitting in a config file. :)

**Comment by The-Compiler** [comment]
Implemented in the `new-config` branch - there's now `content.user_stylesheets` as a list of filenames.
