### ISSUE TITLE
Caret mode does not allow selecting characters in input fields

### ISSUE THREAD

**Issue by phansch** [qutebrowser/qutebrowser#1405]
When I'm using caret mode, it seems like I am not able to select the contents of input boxes on  average websites.

Here's what I do:
1. Type something in a textbox or input field (A new GitHub comment for example)
2. Leave insert mode
3. Enter caret selection mode `v` + `v`
4. Navigate to the input field
5. Try to select single characters inside the input field with `l` or `h`

It just skips over the whole element instead and goes to the next element.
**However**, this works on a page that has a single input tag only and no other elements.

**Comment by amacfie** [comment]
Note that this behavior is the same if you select with the mouse

**Comment by The-Compiler** [comment]
Merging this into #3583.
