### ISSUE TITLE
Help is not discoverable from website

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1490]
There's http://qutebrowser.org/doc/help/ which is the same as `:help`, but it's not linked from anywhere.

**Comment by rumpelsepp** [comment]
And a few links are 404

**Comment by The-Compiler** [comment]
@rumpelsepp FWIW the links should be fixed now

**Comment by rumpelsepp** [comment]
http://qutebrowser.org/doc/help/quickstart.html gives 404. I hope the mobile internet in the subway does not troll me now...

**Comment by The-Compiler** [comment]
narf, indeed - sorry!

**Comment by engelju** [comment]
@The-Compiler how often do the new docs get updated on www.qutebrowser.org? Because the changes from #2048 don't seem to be active yet.. 😬 

Also, I'll open another PR to tackle the actual topic of this issue ("Help is not discoverable"). ☺️

**Comment by The-Compiler** [comment]
It's done manually currently - updated now!

**Comment by engelju** [comment]
So now that /help is within the top menu, I've discovered that the layout will break slightly if the help page is open.

https://qutebrowser.org/doc/help/index.html vs https://qutebrowser.org/index.html
no favicon, helvetica is used instead of open sans, also top menu seems to be more 'spaced out'.

I'll try to find out what the culprit is, and what I can do about it.

**Comment by The-Compiler** [comment]
It looks like the font can't be loaded because it's also using a relative path...

**Comment by The-Compiler** [comment]
@engelju did you find out anything in the meantime? :smile:

**Comment by engelju** [comment]
@The-Compiler: finally got around to take another look at it 😄   Should be fixed now!

While I was at it, I also slightly rearranged the listing of the available docs, and added instructions on how to build the website (as I was struggling with that first). If you don't like them or don't agree, I've split them into different commits, so you should be able to ignore/cherry-pick them. 😉

**Comment by The-Compiler** [comment]
Fixed - thanks @engelju!

**Comment by engelju** [comment]
No worries, glad I could help! :)
