### ISSUE TITLE
Add an autoloaded scripts.js function file (enhancement request)

### ISSUE THREAD

**Issue by sdothum** [qutebrowser/qutebrowser#1521]
One of the things I like about vimb is the scripts.js file whereby javascript functions can be defined and invoked with a keybind "nnoremap &lt;key&gt; :eval! &lt;jsfunction&gt;()&lt;CR&gt;"

Being able to reference loaded js functions would make for an arguably cleaner :jseval (or equivalent) command and readable keys.conf file.

**Comment by The-Compiler** [comment]
You can already use `:jseval` and bind it to a key, so that part is done. As for loading some scripts file, that should be doable, but I'll probably not look at it in the near future.

**Comment by The-Compiler** [comment]
I've recently thought about having some kind of `@world` attribute in GreaseMonkey scripts, this would also help here - cc @toofar

**Comment by The-Compiler** [comment]
This is now possible via the Greasemonkey support, also see #4017.
