### ISSUE TITLE
iframe BDD tests flaky

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1525]
See https://github.com/The-Compiler/qutebrowser/pull/1433#issuecomment-220830022

I'll mark them as skipped for now to avoid failing unrelated builds, but this should be fixed properly. Probably `quteproc.click_element` could be refactored to take any xpath, and that could be used to focus the iframe.

cc @lahwaacz

**Comment by toofar** [comment]
I think I ran into this in #7621. Hopefully the last ones should be unflakified in cb0b51c. Fingers crossed.
