### ISSUE TITLE
keys.conf: <unbound> does not work

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#1553]
I recently got an error complaining about duplicate key chain (for the `<Ctrl-N>` key) in `keys.conf` after pulling from the git master branch, so I attempted to remove the new default binding. Here are my attempts and problems:
1. With `keys.conf` like this:
   
   ```
   [normal]
   
   tab-focus
       K
       <Ctrl-N>
   
   <unbound>
       <Ctrl-N>
   ```
   
   There is no duplicate keys error, but `<Ctrl-N>` opens a new window (i.e. `<unbound>` unbinds the `tab-focus` instead of `open -w`).
2. With `keys.conf` like this:
   
   ```
   [normal]
   
   <unbound>
       <Ctrl-N>
   
   tab-focus
       K
       <Ctrl-N>
   ```
   
   There is the duplicate key chain error.
3. I finally worked around it by binding `open -w` to some "impossible" key:
   
   ```
   [normal]
   
   open -w
       <Ctrl-Shift-ú>
   
   tab-focus
       K
       <Ctrl-N>
   ```

I found an old issue (#781), but it just assumes that `<unbound>` works already (and at that time it was undocumented). Most of the discussion was about the proper transposition of binding commands to keys or keys to commands.

**Comment by The-Compiler** [comment]
I can't say I'm surprised, but I'm going to be honest - I'll probably not fix this until the config revolution :wink:

**Comment by troubas** [comment]
I'm currently getting the error `Duplicate key chain <ctrl-pgdown>`. I've been able to solve it by adding a `ubound` to my `keys.config` as well. It doesn't really matter as I don't really on that key binding anyway. Just figured I'd let you know.

Traceback:
```
20:33:46 ERROR: Duplicate key chain <ctrl-pgdown>!
Traceback (most recent call last):
  File "/home/josh/.local/sources/qutebrowser/qutebrowser/config/config.py", line 185, in _init_key_config
    parent=parent)
  File "/home/josh/.local/sources/qutebrowser/qutebrowser/config/parsers/keyconf.py", line 100, in __init__
    self._load_default(only_new=True)
  File "/home/josh/.local/sources/qutebrowser/qutebrowser/config/parsers/keyconf.py", line 276, in _load_default
    self._add_binding(sectname, keychain, command)
  File "/home/josh/.local/sources/qutebrowser/qutebrowser/config/parsers/keyconf.py", line 394, in _add_binding
    raise DuplicateKeychainError(keychain)
qutebrowser.config.parsers.keyconf.DuplicateKeychainError: Duplicate key chain <ctrl-pgdown>!
```
Happened after a new pull today. I suppose I could figure out in which commit the issue appeared but I suppose that would be a waste of time.

**Comment by The-Compiler** [comment]
@troubas thanks, I opened #1835 now, and found the offending commit.

**Comment by The-Compiler** [comment]
`<unbound>` doesn't exist with the new config anymore.

**Comment by The-Compiler** [comment]
Turns out I lied - there's still a need for `<unbound>` there if you want to unbind a default binding.

**Comment by The-Compiler** [comment]
After looking at it again, this isn't going to be a problem with the new config anymore. Sorry for the noise! 😆

**Comment by The-Compiler** [comment]
Hm, I can't move this card in the GitHub projects interface... I bet it's something with the `<unbound>` in the title!
