### ISSUE TITLE
Borders around tabbar with Breeze Qt theme

### ISSUE THREAD

**Issue by FLHerne** [qutebrowser/qutebrowser#1554]
When using Qutebrowser (0.6.2, Qt 5.6.0), with KDE's [Breeze theme](https://quickgit.kde.org/?p=breeze.git) (version 5.6.4), on Arch Linux, there are borders around the tabbar as visible in [this image](https://i.imgur.com/hqchrRU.png).  
The 1px blue border in that image is drawn by my WM; the orange is 'tabs.bg.bar'.

These also appear with a horizontal tabbar; in all cases there is a 2px border toward the website content and a 1px border on the other three sides.

They do not appear when using the 'Fusion' theme shipped with Qt.

**Comment by The-Compiler** [comment]
As mentioned in IRC, `--qt-style fusion` helps, `--temp-basedir` does not. There's probably some element `TabBarStyle` in `qutebrowser/mainwindow/tabwidget.py` should not draw, but I have no idea what yet...

**Comment by FLHerne** [comment]
(confirmed fixed for me)
