### ISSUE TITLE
QtWebKit-NG

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1571]
# About

qutebrowser works with [annulen/webkit](https://github.com/annulen/webkit) almost out of the box. See [QtWebKit is coming back](http://permalink.gmane.org/gmane.comp.lib.qt.devel/26208) for some details. This might be a nice alternative to QtWebEngine in the future for people who prefer it.

To run:
- Clone the repo
- Apply patches
- Build as per [the wiki](https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux)
# Patches
- [Add version script](http://paste.the-compiler.org/view/raw/2580fbc6)
- [Fix `QWebElement::geometry`](http://paste.the-compiler.org/view/raw/ee9a09f4)
# Issues
- Monospace (like `qute:version`) doesn't render in monospace
- PDF was rendered weird with pdfjs in the testsuite with `--no-xvfb`
- PDFs download instead of using pdfjs sometimes?
- "Scenario: Downloading a pdf via pdf.js button" in `misc.feature` fails with Qt warning "Attempted to download unsupported URL blob:http://localhost:42951/38b20dbe-544b-402c-b19e-bc63d1601347"
- `tests/unit/misc/test_sessions.py` and `tests/unit/browser/test_tabhistory.py` fails:

```
_________________________ ERROR at setup of test_count _________________________

empty_history = <PyQt5.QtWebKit.QWebHistory object at 0x7f374cb0ddd8>

    @pytest.fixture
    def objects(empty_history):
        """Fixture providing a history (and userdata) filled with example data."""
        stream, _data, user_data = tabhistory.serialize(ITEMS)
>       qtutils.deserialize_stream(stream, empty_history)

tests/unit/browser/test_tabhistory.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/py35/lib/python3.5/site-packages/qutebrowser/utils/qtutils.py:193: in deserialize_stream
    check_qdatastream(stream)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

stream = <PyQt5.QtCore.QDataStream object at 0x7f374cb0deb8>

    def check_qdatastream(stream):
        """Check the status of a QDataStream and raise OSError if it's not ok."""
        status_to_str = {
            QDataStream.Ok: "The data stream is operating normally.",
            QDataStream.ReadPastEnd: ("The data stream has read past the end of "
                                      "the data in the underlying device."),
            QDataStream.ReadCorruptData: "The data stream has read corrupt data.",
            QDataStream.WriteFailed: ("The data stream cannot write to the "
                                      "underlying device."),
        }
        if stream.status() != QDataStream.Ok:
>           raise OSError(status_to_str[stream.status()])
E           OSError: The data stream has read corrupt data.

.tox/py35/lib/python3.5/site-packages/qutebrowser/utils/qtutils.py:165: OSError
```

**Comment by bb010g** [comment]
It would be nice to have this in the meantime before QtWebEngine, but I could see supporting both being problematic long term. It's simpler to just stick to one backend.

**Comment by The-Compiler** [comment]
Supporting both was the plan for quite some while already, for various reasons - easier transition, Debian/Ubuntu support, QtWebKit-NG, easier to add a new thing (like Servo maybe) in the future. We'll see how it works out long-term, but that's the current goal.

**Comment by paretje** [comment]
I've been using qtwebkit-ng for about 2 months now, and everything seems fine, except for saving and loading sessions.

The font issue actually seems to be due to a lack of defaults. Just setting the fonts to the fontconfig aliases fixes this:
```
web-family-standard = serif
web-family-fixed = monospace
web-family-serif = serif
web-family-sans-serif = sans
```

And, I guess:
```
web-family-cursive = cursive
web-family-fantasy = fantasy
```

I'm not sure if this would work for non-fontconfig systems, but otherwise it seems quite harmless to do this by default in qutebrowser?

Oh, and in case anyone is interested: I made a (basic) Debian package, based on the packages of qtwebkit and webkitgtk: https://gitlab.com/paretje/qtwebkit.

**Comment by The-Compiler** [comment]
That makes me wonder if this is just another effect of https://codereview.qt-project.org/#/c/168903/...

**Comment by annulen** [comment]
@paretje Some remarks about your package:
* There are some unneeded dependencies, e.g. libharfbuzz, libfontconfig, libfreetype (those are used by Qt, not here), libgnutls28, libnotify, libsoup2.4, libgudev, libxt, geoclue, libsecret
* `EXTRA_CMAKE_ARGUMENTS += -DUSE_LD_GOLD=OFF`- probably has no effects other than slowing fown the build and causing problems with debug (hacks with -g1 are probably useless with gold, as -gsplit-dwarf is used)
* JIT is available on mipsel too

See https://gist.github.com/annulen/309569fb61e5d64a703c055c1e726f71 for gentoo ebuild that is known to work

Also, are there binary packages available for download anywhere?

**Comment by paretje** [comment]
@annulen Thanks for the feedback
- The dependencies were taken from the [upstream Debian package](https://packages.debian.org/source/sid/qtwebkit-opensource-src). Has this changed in qtwebkit-ng, or did Debian already include too many dependencies?
- Compilation of tp2 failed when using the gold linker. I'll try again, and if still fails, I'll investigate and report at https://github.com/annulen/webkit.
- Thanks, I'll update the source package.

Binaries for amd64 are available at http://repo.paretje.be

**Comment by annulen** [comment]
>The dependencies were taken from the upstream Debian package. Has this changed in qtwebkit-ng, or did Debian already include too many dependencies?

No, stuff in that list is not present there and presumably was copied from webkitgtk package

>Compilation of tp2 failed when using the gold linker

That's strange as I' use only gold for development

**Comment by The-Compiler** [comment]
Initial quick-and-dirty patch for sessions which still needs some work (but probably after my exams):

```diff
diff --git a/qutebrowser/browser/webkit/tabhistory.py b/qutebrowser/browser/webkit/tabhistory.py
index 63a973685..cf9cc9f10 100644
--- a/qutebrowser/browser/webkit/tabhistory.py
+++ b/qutebrowser/browser/webkit/tabhistory.py
@@ -21,21 +21,41 @@
 
 
 from PyQt5.QtCore import QByteArray, QDataStream, QIODevice, QUrl
+from PyQt5.QtWebKit import qWebKitVersion  # FIXME can we guarantee WebKit is available here?
 
 from qutebrowser.utils import qtutils
 
 
-HISTORY_STREAM_VERSION = 2
-BACK_FORWARD_TREE_VERSION = 2
-
-
 def _encode_url(url):
     """Encode a QUrl suitable to pass to QWebHistory."""
     data = bytes(QUrl.toPercentEncoding(url.toString(), b':/#?&+=@%*'))
     return data.decode('ascii')
 
 
-def _serialize_item(i, item, stream):
+def _serialize_item_ng(i, item):
+    data = {
+        'children': [],
+        'documentSequenceNumber': i + 1,  # FIXME what to pass here?
+        'documentState': [],
+        'formContentType': '',
+        'itemSequenceNumber': i + 1,  # FIXME what to pass here?
+        'originalURLString': item.original_url.toString(),  # FIXME encoding?
+        'pageScaleFactor': 0.0,
+        'referrer': '',
+        'scrollPosition': {'x': 0, 'y': 0},
+        'target': '',
+        'title': item.title,
+        'urlString': item.url.toString(),  # FIXME encoding?
+    }
+    try:
+        data['scrollPosition']['x'] = item.user_data['scroll-pos'].x()
+        data['scrollPosition']['y'] = item.user_data['scroll-pos'].y()
+    except (KeyError, TypeError):
+        pass
+    return data
+
+
+def _serialize_item_old(i, item, stream):
     """Serialize a single WebHistoryItem into a QDataStream.
 
     Args:
@@ -53,7 +73,7 @@ def _serialize_item(i, item, stream):
 
     ### Source/WebCore/history/HistoryItem.cpp decodeBackForwardTree
     ## backForwardTreeEncodingVersion
-    stream.writeUInt32(BACK_FORWARD_TREE_VERSION)
+    stream.writeUInt32(2)
     ## size (recursion stack)
     stream.writeUInt64(0)
     ## node->m_documentSequenceNumber
@@ -101,6 +121,39 @@ def _serialize_item(i, item, stream):
     stream.writeBool(False)
 
 
+def _serialize_old(items, current_idx, stream):
+    ### Source/WebKit/qt/Api/qwebhistory.cpp operator<<
+    stream.writeInt(2)  # history stream version
+    stream.writeInt(len(items))
+    stream.writeInt(current_idx)
+
+    for i, item in enumerate(items):
+        _serialize_item_old(i, item, stream)
+        user_data.append(item.user_data)
+
+
+def _serialize_ng(items, current_idx, stream):
+    # {'currentItemIndex': 0,
+    #  'history': [{'children': [],
+    #               'documentSequenceNumber': 1485030525573123,
+    #               'documentState': [],
+    #               'formContentType': '',
+    #               'itemSequenceNumber': 1485030525573122,
+    #               'originalURLString': 'about:blank',
+    #               'pageScaleFactor': 0.0,
+    #               'referrer': '',
+    #               'scrollPosition': {'x': 0, 'y': 0},
+    #               'target': '',
+    #               'title': '',
+    #               'urlString': 'about:blank'}]}
+    data = {'currentItemIndex': current_idx, 'history': []}
+    for i, item in enumerate(items):
+        data['history'].append(_serialize_item_ng(i, item))
+
+    stream.writeInt(3)  # history stream version
+    stream.writeQVariantMap(data)
+
+
 def serialize(items):
     """Serialize a list of QWebHistoryItems to a data stream.
 
@@ -137,13 +190,12 @@ def serialize(items):
     else:
         current_idx = 0
 
-    ### Source/WebKit/qt/Api/qwebhistory.cpp operator<<
-    stream.writeInt(HISTORY_STREAM_VERSION)
-    stream.writeInt(len(items))
-    stream.writeInt(current_idx)
+    if qWebKitVersion() == '538.1':  # FIXME better comparison
+        _serialize_old(items, current_idx, stream)
+    else:
+        _serialize_ng(items, current_idx, stream)
 
-    for i, item in enumerate(items):
-        _serialize_item(i, item, stream)
+    for i, item in enumerate(items):  # FIXME easier way?
         user_data.append(item.user_data)
 
     stream.device().reset()
diff --git a/scripts/testbrowser.py b/scripts/testbrowser.py
index 24ce2a130..1abd92bfa 100755
--- a/scripts/testbrowser.py
+++ b/scripts/testbrowser.py
@@ -23,7 +23,7 @@
 import sys
 import argparse
 
-from PyQt5.QtCore import QUrl
+from PyQt5.QtCore import QUrl, QDataStream, QIODevice, QByteArray
 from PyQt5.QtWidgets import QApplication
 
 try:
@@ -49,6 +49,15 @@ def parse_args():
     return parser.parse_args()
 
 
+def dump_history(wv):
+    ba = QByteArray()
+    ds = QDataStream(ba, QIODevice.ReadWrite)
+    ds << wv.history()
+    ds2 = QDataStream(ba)
+    assert ds2.readInt() == 3
+    print(ds2.readQVariantMap())
+
+
 if __name__ == '__main__':
     args = parse_args()
     app = QApplication(sys.argv)
@@ -73,6 +82,7 @@ if __name__ == '__main__':
     wv.loadStarted.connect(lambda: print("Loading started"))
     wv.loadProgress.connect(lambda p: print("Loading progress: {}%".format(p)))
     wv.loadFinished.connect(lambda: print("Loading finished"))
+    wv.loadFinished.connect(lambda: dump_history(wv))
 
     if args.plugins and not using_webengine:
         from PyQt5.QtWebKit import QWebSettings
```

Some testing would be appreciated though if someone feels brave enough :wink:

**Comment by The-Compiler** [comment]
Failing tests with that patch:

- end2end/features/test_downloads_bdd.py::test_downloading_via_pdfjs
-  end2end/features/test_misc_bdd.py::test_downloading_a_pdf_via_pdfjs_button_issue_1214

```
Download error: Protocol "blob" is unknown
```

- end2end/features/test_history_bdd.py::test_opening_a_valid_url_which_turns_out_invalid

```
Timed out after 5000.0ms waiting for {'message': 'QFSFileEngine::open: No file name specified'}.
```

- end2end/features/test_javascript_bdd.py::test_openingclosing_a_modal_window_via_js

```
Timed out after 5000.0ms waiting for {'message': "Changing title for idx 1 to 'about:blank'"}.
```


-  end2end/features/test_misc_bdd.py::test_private_browsing_is_activated_in_qtwebkit_without_restart

```
E       assert 'Local storage status: not working' in 'Local storage status: working'
```

- unit/browser/webkit/test_tabhistory.py::test_urls[1-item1]
- unit/browser/webkit/test_tabhistory.py::test_original_urls[1-item1]

```
>       assert objects.history.itemAt(i).url() == item.url
E       assert PyQt5.QtCore.QUrl('http://example.com/&') == PyQt5.QtCore.QUrl('http://example.com/…')
```

**Comment by throwaway217** [comment]
Sorry if this is not the right place to ask. How usable is qtwebkit-ng currently ? I was thinking of trying it out.

**Comment by The-Compiler** [comment]
Sessions still won't work until I got the patch above in `master` (which should be soon now). Other than that, I don't think there are any major issues.

**Comment by The-Compiler** [comment]
This is now fully/officially supported, with tests running on the CI with QtWebKit-NG.

**Comment by lahwaacz** [comment]
Perhaps it should be mentioned in [README#Requirements](https://github.com/qutebrowser/qutebrowser#requirements) then? :wink:
