### ISSUE TITLE
Command to edit config/data files

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#1587]
`edit {config | bookmarks | quickmarks | keys}` would open the corresponding file in `general->editor` and send the needed update signals when the editor is closed. This is nicer than opening the corresponding file 'manually' in your editor as:
1. Its easier to find the path
2. Qutebrowser will pick up the changes without needing to `:restart`

**Comment by The-Compiler** [comment]
Sounds good, but I'd suggest waiting until after the new config system (which is the next thing I plan to work on after QtWebEngine) until doing the reloading part. Last time someone tried it was a bit problematic :wink:

**Comment by The-Compiler** [comment]
Merging this into #2794.

**Comment by AckslD** [comment]
@The-Compiler I was searching around the issues for how one can edit quickmarks/bookmarks and stumbled upon this. Is that supported? Seems to not be mentioned in #2794 from what I can tell

**Comment by rcorre** [comment]
I vaguely remember this being part of the plan for #882, which fell by the wayside a bit. #882 probably isn't a prereq though, it might be much easier to add an edit command for the existing files.

**Comment by Drew-Daniels** [comment]
I just started using `qutebrowser` today and was looking to see if this functionality was implemented yet, maybe this can be looked into once again?

Love using `qutebrowser` so far btw! Thank you for all the amazing work.

**Comment by The-Compiler** [comment]
It's not, hence the open issue. Appreciate the nice words, but comments like this mostly add noise to open source bugtrackers. That's what the :+1: button is for.
