### ISSUE TITLE
Rename select-on-remove values

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1619]
```
<FLHerne> Hm, that seems inconsistent
<FLHerne> tabs.select-on-remove uses 'left' and 'right' to refer to positioning, never mind vertical tabs
<FLHerne> And 'previous' for 'previously-viewed'
<FLHerne> Whereas :tab-prev means 'left' (or 'up')
```

**Comment by HolySmoke86** [comment]
`tabs.select-on-remove` accepts 3 values, `left`, `right`, and `previous`, which are direct translations of their `QTabBar::SelectionBehavior` enum, `Select{Left,Right,Previous}Tab`, while the navigational commands use `next` and `prev[ious]`. That's a pretty annoying naming clash and I haven't quite wrapped my head around a resolution yet.

Candidates I've considered so far are:

Adding `up` and `down` in addition to allow intuitive options for vertical users:
This doesn't really solve the issue of disconnecting order from direction and gives only minor improvement. Additionally, a user looking at the completion might wonder what the difference between `up` and `left` is.
This can also be reinterpreted to considering the tab list as a stack (which _obviously_ grows downwards :P ).

Using `before` and `after`:
This is direction-agnostic, and would even work with rtl or bottom-up tab lists. It's a little harder to comprehend on first thought than solid directions, though.

Using `next` and `prev` and renaming the current `previous` to something clearly distinct from `prev`:
This obviously introduces the danger of confusing `prev` and `previous` and prompts a new challenge of finding a short, expressive term for "that tab I last used", which "previous" is actually excellent for.
`last` could easily be confused with the "last in list" tab. `prior` could as well be confused with "previous", and is also rather exotic in common language.

Also note that the `tabs.new-tab-position` and  `tabs.new-tab-position-explicit` settings also have `left` and `right` as values and should be taken into consideration in conjunction with this issue.

**Comment by The-Compiler** [comment]
Note `new-tab-position` also uses `last` to mean rightmost/"last in list".

I think `last-used` (or maybe `mru` for "most recently used") would be an unambiguous term to use.

Using `prev` and `next` then sounds good to me, as that's what we already use for `:tab-prev` and `:tab-next` too.

**Comment by code-hunger** [comment]
(when talking about renaming) I'd like to note that it'd probably be better to call it "select-on-close", like in "last-close" (I spend a whole minute staring at the completion suggestions, looking for something "close"-related, until I opened :help and `/`-ing for close)

**Comment by joepvd** [comment]
Can be closed, as https://github.com/qutebrowser/qutebrowser/issues/2037 is merged.

**Comment by The-Compiler** [comment]
Right, thanks @joepvd!
