### ISSUE TITLE
Finer pylint pragmas

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1627]
For some lines, we have a `# pylint: disable=...` on the previous line as there's not enough space to have it on the same line.

I just learned you can do:

``` python
# pylint: disable=no-member
foo.bar
# pylint: enable=no-member
...
```

so we should probably use that in those few cases.

**Comment by lamarpavel** [comment]
To find candidates using vim:

```:bel vimgrep "^[[:space:]]*\# pyling: disable" **/*.py```

I thought I'd try, but I actually have no idea when such a statement makes sense (eg. should apply to the whole block) or not...
Not enough time on my hands to read up on pylint right now.

**Comment by siddhugolu** [comment]
@The-Compiler I'd like to work on this issue, if it's still open.

**Comment by The-Compiler** [comment]
@siddhugolu Please do, I think there are still a few places which do this kind of thing. @lamarpavel's regex above probably helps with finding them (you can also `grep -R '^[[:space:]]*\# pylint: disable' scripts tests qutebrowser`).

**Comment by siddhugolu** [comment]
@The-Compiler Please see the attached pull request. Let me know if there are more changes required.
