### ISSUE TITLE
History completion by both URL and title

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#1649]
Currently the completion works by matching either URL or title, but not both. Sometimes it is useful to write the hostname and then part of the title to search within the results for the given server.

Desired use case:
1. start `qutebrowser --temp-basedir`
2. `:open https://github.com/The-Compiler/qutebrowser/issues/786` (followed by Enter)
3. `:open github history` (without Enter)
4. then the above URL should be matched

**Comment by The-Compiler** [comment]
Sounds good to me - @toofar do you want to take a look by any chance as you added title completion?

**Comment by toofar** [comment]
@The-Compiler  Nope. No input from me sorry I am between proper computing devices at the moment.

**Comment by Ape** [comment]
This is working already in the current master.

**Comment by The-Compiler** [comment]
No, not as described in the issue.
