### ISSUE TITLE
Use Control-D to delete selected history item

### ISSUE THREAD

**Issue by gnosticscrounger** [qutebrowser/qutebrowser#1681]
I would like Control-D to delete history items in the same way it can delete bookmarks. There are times when you just want to clear certain items in your history without resorting to a total wipe and that's where selective deletion would come in handy.

**Comment by The-Compiler** [comment]
This currently is harder to implement as it might sound, as the history is never rewritten completely (qutebrowser simply appends to it). I can see how it would be useful though.

**Comment by lahwaacz** [comment]
It might be tempting to say that what's not being suggested by the completion is not in history, but that's not true at all - the history file is "infinite" and the completion shows only the last 1000 (by default) items.

IMHO these little functionality enhancements are fine, as long as they don't bring potential misunderstanding of other features. I'm afraid that doing this right would mean rethinking the whole history interface.

**Comment by gnosticscrounger** [comment]
Is there a possiblilty for future environmental variables containing information on currently selected items in command mode for use in userscripts ? It could allow users to hack together solutions to these minor niggles while more pressing issues are being worked on (like QtWebEngine).

**Comment by gnosticscrounger** [comment]
Is there a possiblilty for future environmental variables containing information on currently selected items in command mode for use in userscripts ? It could allow users to hack together solutions to these minor niggles while more pressing issues are being worked on (like QtWebEngine).

**Comment by The-Compiler** [comment]
@gnosticscrounger Hmm, I imagine this being harder to implement in an userscript than it is in qutebrowser itself :wink:

**Comment by The-Compiler** [comment]
This should be straightforward to implement once #2295 is in (cc @rcorre) 😄

**Comment by rcorre** [comment]
yup :)

**Comment by The-Compiler** [comment]
Implemented in that PR - closing it so I don't forget to do so, it's not merged yet though.
