### ISSUE TITLE
Getting rid of some rarely customized settings

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1751]
While implementing settings for QtWebEngine, I noticed a few settings which are probably rarely ever customized, and not available for QtWebEngine:
- general
  - [ ] ~~print-element-backgrounds~~
  - [x] site-specific-quirks
- ui
  - [ ] zoom-text-only
  - [ ] frame-flattening
  - [x] css-media-type
- storage
  - [ ] maximum-pages-in-cache
  - [x] object-cache-capacities (maybe just expose a setting for the total cache size)
  - [x] offline-storage-default-quota
  - [x] offline-web-application-cache-quota
  - [x] offline-storage-database (maybe just linked to local-storage)
  - [ ] offline-web-application-storage (ditto)
- content
  - [x] css-regions
  - [ ] ~~javascript-can-close-windows~~
- [ ] ~~Maybe `fonts -> _monospace`, if `Monospace` selects some usable font on all systems with a recent Qt.~~

Maybe it's time to get rid of (some of) them?

**Comment by lamarpavel** [comment]
I remember having `frame-flattening` enabled but after experiencing some weird behaviour on some sites, I set it to false and haven't missed it since.

`site-specific-quirks` on the other hand is set to true, though I have little idea what it does.

**Comment by The-Compiler** [comment]
> `site-specific-quirks` on the other hand is set to true

Yeah, the idea was for it to always be `true` (which is the QtWebKit default).

> though I have little idea what it does.

Me neither :laughing: It seems to be used in various places in WebKit to enable workarounds.

**Comment by lahwaacz** [comment]
> It seems to be used in various places in WebKit to make webkit.org render correctly.

FTFY :sunglasses:

**Comment by rcorre** [comment]
FWIW I've never gotten the urge to set any of these.

**Comment by haasn** [comment]
I can see the appeal of zoom-text-only for high DPI users who don't want blurry images everywhere, but personally I'm fine with just forcing a global minimum font size instead.

Now, what I would actually appreciate is a way to resize everything *except* images (i.e. also resize stuff like fixed-width tables and textareas), but that must be harder to implement.

(Or, perhaps an image upscaler that doesn't produce blurry garbage, but I imagine qutebrowser has no control at all over this)

**Comment by The-Compiler** [comment]
An equivalent to `print-element-backgrounds` just [was added](https://codereview.qt-project.org/#/c/167482/) to QtWebEngine, so I guess we can keep that one.
