### ISSUE TITLE
Add support for startup notification for better integration into desktop environments and window managers

### ISSUE THREAD

**Issue by ThibautMarty** [qutebrowser/qutebrowser#1752]
They are used to properly launch windows on the right workspace when starting and tell the user the application is starting (with a hourglass mouse pointer, icons…)
Though this should be easy to handle with Qt, according to [Gnome developer center](https://developer.gnome.org/integration-guide/stable/startup-notification.html.en):
"Applications with remoting capabilities (where you tell an existing process to open a new window instead of starting a new process) cannot use the built-in mechanism [of the toolkit]."
And I guess Qutebrowser works like that.

See the [reference](https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt)

**Comment by He-Ro** [comment]
Note that this does not only enable the use of the "hour glass" cursor, but also helps the WM configuring the window correctly. For example i3 relies on this feature to place the window on the workspace, where it was started and not the current workspace. See the answer of https://faq.i3wm.org/question/561/what-is-that-thing-called-no-startup-id/

**Comment by ThibautMarty** [comment]
Sure, that what I said with ``They are used to properly launch windows on the right workspace''. It is far more important and annoying than the missing "hourglass cursor" ;).
It seems that there is not that much of i3 + qutebrowser users, or all of them have good enough hardware to not notice the problem ?

**Comment by The-Compiler** [comment]
Looks like this has been [implemented](https://codereview.qt-project.org/c/qt/qtbase/+/54499) in Qt ever since Qt 5.1 and the only missing bit was us declaring support in the `.desktop` file, see #5894. FWIW, I don't think i3 uses the `.desktop` file though - I tried without it using `i3-msg exec "qutebrowser --temp-basedir"` and got the hour glass cursor, so I assume this is working.
