### ISSUE TITLE
<Alt+9> to select last tab instead of ninth

### ISSUE THREAD

**Issue by Markus00000** [qutebrowser/qutebrowser#1753]
In Firefox and Chrome (and possibly IE/Edge) `<Alt+9>` selects the last tab instead of the ninth. I suggest to implement the same behavior so that users’ `<Alt+9>` muscle memory would apply to qutebrowser.

qutebrowser v0.8.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

Edit: I removed the second reason (the ninth tab being difficult to find) as tabs are numbered by default: `title-format (Current: {index}: {title})`

**Comment by The-Compiler** [comment]
No strong opinion on this from my side, I never use `<Alt+n>` myself. Maybe others could chime in?

**Comment by lahwaacz** [comment]
I also don't use this (since `Alt` is a modifier in my i3 configuration), but I don't understand the reasoning. Playing nice with muscle memory of new users would certainly be a good thing, but people might actually want to quickly access the 9th tab. Contrary to this, there is no 0th tab since they are numbered from 1 and 0 is actually to the right of 9 on a standard qwerty keyboard, so `Alt+0` could be used to select the last tab.

**Comment by Markus00000** [comment]
@lahwaacz 

> people might actually want to quickly access the 9th tab

This is a good point. I’ve been wondering why other browsers use 9 instead of 0. Maybe there are keyboard layouts placing 0 *left* to 1 which would make 0 awkward for selecting the *rightmost* tab.

On the other hand, it doesn’t seem to make much of a difference whether 8 or 9 tabs can be accessed directly. For higher indexes one has to use `gm` anyway.

**Comment by The-Compiler** [comment]
`gm` *moves* tabs :wink: Also, a count of 0 is currently ignored, so `0gm` is the same as `gm`.

**Comment by Markus00000** [comment]
@The-Compiler I just noticed my confusion but weren’t fast enough to edit… Thanks!

Did I miss a way to select tabs by number? This might be useful considering that tabs have indexes by default. Something like `17gT`. This would then allow `0gT` to select the last tab while being consistent with `<Alt+0>` if that is accepted. Users having `<Alt>` set as a modifier key like @lahwaacz would still be able to jump to the last tab with this alternate command.

**Comment by The-Compiler** [comment]
`T` should do that, yeah. What does `:bind T` say for you?

**Comment by Markus00000** [comment]
> T is unbound in normal mode

It’s missing in the default `keys.conf`.

**Comment by The-Compiler** [comment]
Oh, indeed! That should be fixed in 54ae106789699a4f0f7e014a322363f79470a6b5.

**Comment by Markus00000** [comment]
Great. So if `tab-focus` did not ignore `0` as a prefix, `0T` could select the last tab. Then `<Alt+0>` could do the same to be (almost) consistent with other browsers.

**Comment by The-Compiler** [comment]
I opened #1758 to make `0` an usable count. Changing the default keybinding for `<Alt-0>` in `qutebrowser/config/configdata.py` should be straightforward - you can open a PR if you want, otherwise I'll take care of it somewhen tomorrow.

**Comment by Link-Satonaka** [comment]
>No strong opinion on this from my side, I never use <Alt+n> myself. Maybe others could chime in?

If there's going to be a default "switch to previously focused tab" in a **vim inspired browser**, the only acceptable answer is the way vim does it: http://vimdoc.sourceforge.net/htmldoc/editing.html#CTRL-^ :P

Actually, qutebrowser is the only "vim-inspired <thing>" I know of that hasn't made use of this keybinding.

**Comment by The-Compiler** [comment]
@Link-Satonaka We're talking about the last as in rightmost here, not the last-used one. For the last-used one, qutebrowser has `<Ctrl-Tab>` bound by default like dwb does (and that doesn't have `<Ctrl-^>` bound) - but I'm open for adding `<Ctrl-6>` and `<Ctrl-^>` too.

**Comment by Link-Satonaka** [comment]
dwb comes up a lot in our discussions of keybindings, and it's pretty clear to me that dwb is a distinctly unique outlier, to the point where I would say such keybindings are 'dwb-like', not 'vim-like'. Between vimperator, pentadactyl, irssi/weechat vim plugins, ranger, vimb, xombrero, and the many other vim-related projects I've tried over the years... dwb definitely bucks an established trend.

I'm not complaining, just making it known that "dwb did this" holds no weight with me ;)

>"last", not last

That being said, whoops, my mistake! The convention here (among everything not dwb :P) would be `g^` and `g$`

**Comment by lahwaacz** [comment]
Well, IMHO "vim-like" should mean that all keybindings are configurable and there are the 3 modes, notably the command mode with the renowned style of keybindings. The defaults are just a minor thing, much lesser compared to whether this should be called "vim-like" or "vi-like".

**Comment by Link-Satonaka** [comment]
@lahwaacz I agree _to a point_; if qutebrowser did not use hjkl navigation and other important defaults, then it's not vim-like, it's simply a browser with modal input. Vim doesn't own modal input.

For vim-like projects, each will interpret how a function in vim should be adapted to whatever the subject is, and each will differ slightly as different needs arise and different interpretations occur. Thus, vim-like projects will each naturally differ a bit. However, the majority of these vim-likes share the same broad strokes and also common interpretations of a vim function as they pertain to common modern UI elements.

I'm also not saying dwb _isn't_ vim-like, but rather a specific branch under vim that is distinct from everything else vim-like.

**Comment by HolySmoke86** [comment]
Was this idea abandoned? There's three different arguments to `tab-focus` (`last`, `-1`, and `0`; the latter undocumented) to indicate the last tab now. I could do a PR if this is still wanted.

**Comment by The-Compiler** [comment]
What part of it exactly? `0T` already does select the last tab now.

**Comment by HolySmoke86** [comment]
I was thinking of adding a default binding of `<Alt-0>` for `tab-focus -1` specifically and, while I'm at it, `<Ctrl-6>` and `<Ctrl-^>` for `tab-focus last`; `g^` (and maybe `g0`, see #1728) for `tab-focus 1`; and `g$` for `tab-focus -1`.

**Comment by The-Compiler** [comment]
@HolySmoke86 Sorry for the late answer! Sounds good to me, though we probably should bind `<Alt-9>` for the last tab for consistency with other browsers (see the discussion above). Want to open a PR?

Also, I'm guessing you mean #2032, not #1728?

**Comment by HolySmoke86** [comment]
Er, actually I meant #1782 
And yes, will do

**Comment by HolySmoke86** [comment]
Hmm, binding `<Alt-9>` will cause a duplicate keychain error with "old" configs. Is there a proven procedure for dealing with this?
I guess alternatively I could extend the configuration so it knows the source of a bind, but I'm afraid that's part of the config revolution milestone, isn't it?

**Comment by The-Compiler** [comment]
@HolySmoke86 There isn't yet, but I definitely need to find a solution for that before the next release, I think this is the third binding for which it happens.... See #1835.
