### ISSUE TITLE
Setting title-format on qute://settings is broken

### ISSUE THREAD

**Issue by Markus00000** [qutebrowser/qutebrowser#1754]
I changed the default value for `title-format` from `{index}: {title}` to `{title}`. Further changes, like adding `{index}` back, are ineffective. Restarting qutebrowser will set the option back to its previous value (`{index}` in my case).

The value can still be changed via `qutebrowser.conf`.

qutebrowser v0.8.2
Qt: 5.7.0 (compiled 5.6.0)
PyQt: 5.6

**Comment by The-Compiler** [comment]
Works fine here - as soon as I tab out of the `title-format` field, the titles are changed.

**Comment by The-Compiler** [comment]
Sorry for the short reply - I was a bit in a hurry there :wink: If you can reproduce this (i.e. setting the title format and tabbing out of the field -> no title changes) could you please do `:report` after it happens?

**Comment by Markus00000** [comment]
Steps to reproduce (they are very specific as I’ve sometimes failed to reproduce the issue when slightly changing the procedure):

- `rm -rf ~/.config/qutebrowser ~/.cache/qutebrowser ~/.local/share/qutebrowser`
- Start qutebrowser
- On `quickstart.html`, scroll down to the *settings page* link and click it
- Type `?title-format<enter>`
- Select the `:` in the text field and replace it with an `X`
- Press `<tab>`
- Title is not changed

If you still cannot reproduce it, I could send a report. Do they contain any potentially sensitive data except *Open Pages* and *Command history*?

**Comment by The-Compiler** [comment]
Can you try reproducing it with `--temp-basedir`? That will basically do the same as the first step, but it won't open the quickstart page.

That's what I tried, and it worked fine for me. However, it might just be the Python-JS bridge which causes some trouble, I think that's not the first time I hear about something like this.

With `--temp-basedir` (or when you simply start a fresh instance with a fresh config) it shouldn't contain anything sensitive, except your username if you count that. Feel free to copy-paste it from the report dialog and send it to me privately at mail@qutebrowser.org instead.

**Comment by Markus00000** [comment]
I could not reproduce it with `--temp-basedir`. I sent you a report without it.

**Comment by The-Compiler** [comment]
Seems indeed like that JS bridge is broken: `[qute://settings:27] TypeError: undefined is not an object (evaluating 'window.qute.set')`

At some point I want to have a cleaner Python <-> JS bridge using [QtWebChannel](http://doc.qt.io/qt-5/qtwebchannel-index.html) which then will also work with the new QtWebEngine backend. Then this will *probably* be solved too.

**Comment by The-Compiler** [comment]
#2332 is probably going to help with this
