### ISSUE TITLE
Global blacklist for URL completion model

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#1768]
My browsing behaviour exhibits the following when reviewing the Arch wiki: I visit many [edit diffs](https://wiki.archlinux.org/index.php?title=ArchWiki:Requests&diff=prev&oldid=444534), which push other more useful entries out of the completion. They are usually visited exactly once, so ideally they would never be suggested by the completion. They are all identifiable by a simple pattern (fixed hostname + `diff=<number>` in the query string), so the logical implementation would be a blacklist based on matching the URLs with regular expressions when they enter the completion model. This should allow to use more useful part of the history within the completion limits (or to have possibly lower `web-history-max-items` value).

**Comment by The-Compiler** [comment]
How do you imagine the UI to look like? A simple list of regexes (?) in the config?

**Comment by lahwaacz** [comment]
Yeah, I guess that would work best, although it's easy to join the matches with disjunctions directly in the regex (but that's probably what makes it a write-only language for long enough expressions).

**Comment by The-Compiler** [comment]
Whoops, seems like @knaggita messed up issue numbers in her branch name and I didn't double-check it - reopening :wink:

**Comment by lahwaacz** [comment]
Oh, that's a bummer :disappointed: 

What about the work in progress flag?

**Comment by The-Compiler** [comment]
I think @knaggita and/or @nanjekyejoannah also wanted to work on this during Rails Girls Summer of Code, but that ended last friday :cry: 

I still hope they'll have the time to finish this and open a PR - @knaggita @nanjekyejoannah what's your plan? :wink:

**Comment by nanjekyejoannah** [comment]
Working to open a PR this week.

**Comment by The-Compiler** [comment]
Hey @nanjekyejoannah, any update on this? If you have something partially working but no time anymore, that's fine as well - feel free to share it as a PR anyways, so someone else can finish this some time :wink:

**Comment by The-Compiler** [comment]
Looking at #2809, there are actually two different use cases here:

- Only hide an URL from the completion, for things like what @lahwaacz mentioned - but keep them in the history (`:history`)
- Hide the URL from both completion and history, like for temporary files, or sites you never want to end up in your history.

With the new completion and new config, this could simply be a per-URL setting like `save_history` with values like `true`, `no_completion` and `false`.

**Comment by The-Compiler** [comment]
I added `completion.web_history.exclude` a while ago.
