### ISSUE TITLE
Avoid encoding parameter in search engine parameter

### ISSUE THREAD

**Issue by antoyo** [qutebrowser/qutebrowser#1772]
Hello.
I would like to have a search engine for Internet Archive, as such:

```
ia = http://web.archive.org/web/*/{}
```

but I cannot use it with the special characters present in an URL, because `qutebrowser` encodes the parameter.
For instance, doing so:

```
:open ia https://github.com/The-Compiler/qutebrowser
```

will go to the following URL: http://web.archive.org/web/*/https%3A//github.com/The-Compiler/qutebrowser

which does not work.

So, it would be nice to have a way to avoid encoding the parameter.

Thanks.

**Comment by The-Compiler** [comment]
There's `{unquoted}` now, thanks to @t-wissmann with #5314.
