### ISSUE TITLE
RFC: Qt 5.2 / Ubuntu Trusty support

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1775]
I wonder when I can drop support for Ubuntu Trusty, as (Py)Qt 5.2 is just a major pain to support:
- Various bad QtWebKit segfaults fixed in Qt 5.3/5.4
- It raises `TypeError` instead of `RuntimeError` with deleted C++ objects, see #1107 
- We have various workarounds for bugs in PyQt/Qt 5.2
- It doesn't disconnect slots from signals emitted by already dead objects, which causes funny stuff like #1107.

I'm tired of it. I want to get rid of it already. Ubuntu 16.04 (the next LTS) is out since a while already (April 2016), and I wish everyone would just upgrade to it (14.04 -> 16.04 is supported by Ubuntu).

However...
- It's [supported upstream](https://wiki.ubuntu.com/Releases) until April 2019
- Travis is using it, so all testing which actually imports qutebrowser needs to be moved to docker containers
- [Searching](http://paste.the-compiler.org/lists/0?search=Ubuntu%2014.04) the crash logs, there are various people using it... Probably at work?

I really don't know what I should do.... gnah. Is there some way to get a more recent Qt/PyQt on Ubuntu 14.04 without going insane?

**Comment by Kingdread** [comment]
I don't think we can realistically support qutebrowser on Ubuntu 14.04 till the end of its LTS period. As far as I can tell, even if 14.04 is officially supported until 2019, it doesn't mean that it will receive feature updates. I think they have a [pretty strict set of guidelines](https://wiki.ubuntu.com/StableReleaseUpdates) to backport features, and they're mostly concerned with security related patches, so we're most likely stuck with Python 3.4 and Qt 5.2.

Especially for a browser I think being up-to-date is important, and browsing with QtWebKit from Qt 5.2 in 2019 sounds like a bad idea. It would be like using Firefox 3.6 today (whose last stable release was in 2012). Most of the websites break, don't display properly, features not working, ...

Travis also seems to be a bad indicator, as the default OS is Ubuntu 12.04 and trusty is still considered "beta", even though it came out 2 years ago and is already superseded by 16.04 as LTS release.

As for the recent Qt on Ubuntu, I'm not sure, as I don't use Ubuntu, but if you want to bypass the package manager, there are [standalone Qt downloads](https://www.qt.io/download-open-source/#section-2) and [wheels for PyQt](https://pypi.python.org/pypi/PyQt5) (though only for 64bit Linux and Python 3.5, which is not available on 14.04...). But there's a [ppa with many Python versions](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes/) which seems to package 3.5 for 14.04, so you could try to
* install Python 3.5 via the ppa
* install PyQt 5.7 via `pip`
* hope that nothing breaks and all Qt modules are available?

So IMHO we should drop it before we spend too much time and nerves supporting it, collecting more and more workarounds in the source. Not dropping it immediately right now, but maybe when the next bigger "work around it or drop it" choice comes along.

**Comment by The-Compiler** [comment]
> so we're most likely stuck with Python 3.4 and Qt 5.2

Correct, otherwise they'd have upgraded already :wink: I'd like to use Python 3.5 features too, but then I'd essentially have to drop Debian/Ubuntu altogether :wink:

> Most of the websites break, don't display properly, features not working, ...

So like with QtWebKit currently? :laughing: 

> Travis also seems to be a bad indicator, as the default OS is Ubuntu 12.04 and trusty is still considered "beta", even though it came out 2 years ago and is already superseded by 16.04 as LTS release.

I agree - but I'd like to continue using Travis for qutebrowser, so things getting more complicated there might be a reason against dropping it.

**Comment by The-Compiler** [comment]
So #1847 / ccce55443f3a391108129c6ffb5472c085bc58b0 just was the next annoyance...

I tried installing PyQt via pip, but of course that doesn't contain QtWebKit. It does however contain QtWebEngine (even the Qt part, I think?), so that might be a nice way forward for Debian/Ubuntu once qutebrowser has a optional dependency on QtWebKit!

**Comment by The-Compiler** [comment]
Let's continue this in #2742 - input much appreciated!
