### ISSUE TITLE
:tab-attach

### ISSUE THREAD

**Issue by haasn** [qutebrowser/qutebrowser#1788]
We have `:tab-detach`, why not `:tab-attached`? (It's basically the opposite: Take the current tab and attach it onto some existing window)

When typing `:tab-attach`, a completion list of currently avialable windows (other than the current) should be shown. Selecting that window (i.e. by ID) would move the current tab to that window instead.

`:tab-detach` followed by `:tab-attach` would effectively be a round-trip (other than the tab perhaps moving to a different place)

**Comment by tjkirch** [comment]
I'd like this too.  I was a bit surprised when I found I could :tab-detach a tab, and then had no way to detach another tab into the same new window.  I can't find a way to group tabs into windows in general.

**Comment by m2habert** [comment]
I really miss this feature:

"tabAttach" functionality is incredibly useful and greatly undercores the advantages of a "Vim-like environment" when dealing with reading/research.

If the browser preserves window ordering across restart (FFx does), you can have a personal strategy of "always keeping win 1 for foo; always keeping win 2 for bar" etc; as well as, given a specific temporary project/research, one can make a mental note of "keeping window 6 and 7 for texts about 'x' ".

It also comes handy when skimming while research for reading later. It is quite common for the user to, when interested in a given subject (like "mmmm, ¿should I move from Vimperator to this new QB novel?"), jump to opening dozens of pages on the matter with the help of google, only to skim the general info and possibly saving part of them for in-depth info later. With tabAttach one can easily move pages between a window for "input", another for "done deal" and a third one for "read thorough later"

**Comment by The-Compiler** [comment]
Abandoned PR from #2783:

```diff
From aa8f2235d7b76fd1c85296ffc7e025e7839b4c10 Mon Sep 17 00:00:00 2001
From: Kaashif Hymabaccus <kaashif@kaashif.co.uk>
Date: Tue, 4 Jul 2017 20:58:41 +0100
Subject: [PATCH] Add :tab-attach, closes #1788

The tests will not pass until qutewm is merged (#1844).
---
 qutebrowser/browser/commands.py     | 26 +++++++++++++++++++
 tests/end2end/features/tabs.feature | 50 +++++++++++++++++++++++++++++++++++++
 2 files changed, 76 insertions(+)

diff --git a/qutebrowser/browser/commands.py b/qutebrowser/browser/commands.py
index 0b448a845b..efa42b2f6d 100644
--- a/qutebrowser/browser/commands.py
+++ b/qutebrowser/browser/commands.py
@@ -526,6 +526,32 @@ def tab_detach(self):
         cur_widget = self._current_widget()
         self._tabbed_browser.close_tab(cur_widget, add_undo=False)
 
+    @cmdutils.register(instance='command-dispatcher', scope='window')
+    def tab_attach(self, win_id: int = None):
+        """Attach the current tab to a different window.
+
+        Args:
+            win_id: The id of the window to attach to, uses the
+                    first-opened window's id if not given.
+        """
+        window = None
+        if win_id is None:
+            window = objreg.window_by_index(0)
+        else:
+            if win_id not in objreg.window_registry:
+                raise cmdexc.CommandError(
+                    "There's no window with id {}!".format(win_id))
+            window = objreg.window_registry[win_id]
+
+        if window.win_id == self._win_id:
+            raise cmdexc.CommandError(
+                "Tab is already attached to that window!")
+
+        url = self._current_url()
+        cur_widget = self._current_widget()
+        window.tabbed_browser.tabopen(url, explicit=True)
+        self._tabbed_browser.close_tab(cur_widget, add_undo=False)
+
     def _back_forward(self, tab, bg, window, count, forward):
         """Helper function for :back/:forward."""
         history = self._current_widget().history
diff --git a/tests/end2end/features/tabs.feature b/tests/end2end/features/tabs.feature
index 8097f390ee..d54e7082aa 100644
--- a/tests/end2end/features/tabs.feature
+++ b/tests/end2end/features/tabs.feature
@@ -660,6 +660,56 @@ Feature: Tab management
         And I run :tab-detach
         Then the error "Cannot detach one tab." should be shown
 
+    # :tab-attach
+
+    # Needs qutewm to run properly
+    # See https://github.com/qutebrowser/qutebrowser/pull/1844
+    @xfail_norun
+    Scenario: Attach tab to first-opened window
+        When I open data/numbers/1.txt
+        And I open data/numbers/2.txt in a new window
+        And I run :buffer "2.txt"
+        And I run :tab-attach
+        And I run :buffer "1.txt"
+        And I run :window-only
+        Then the session should look like:
+            windows:
+            - tabs:
+              - history:
+                - url: about:blank
+                - url: http://localhost:*/data/numbers/1.txt
+              - history:
+                - url: http://localhost:*/data/numbers/2.txt
+
+    # Needs qutewm to run properly
+    # See https://github.com/qutebrowser/qutebrowser/pull/1844
+    @xfail_norun
+    Scenario: Attach tab to arbitrary window
+        Given I have a fresh instance
+        When I open data/numbers/1.txt
+        And I open data/numbers/2.txt in a new window
+        And I run :buffer "1.txt"
+        And I run :tab-attach 1
+        And I run :buffer "2.txt"
+        And I run :window-only
+        Then the session should look like:
+            windows:
+            - tabs:
+              - history:
+                - url: http://localhost:*/data/numbers/2.txt
+              - history:
+                - url: http://localhost:*/data/numbers/1.txt
+
+    Scenario: Attach tab to same window
+        When I open data/numbers/1.txt
+        And I run :tab-attach
+        Then the error "Tab is already attached to that window!" should be shown
+
+    Scenario: Attach tab to nonexistent window
+        When I open data/numbers/1.txt
+        And I run :tab-attach 9999
+        Then the error "There's no window with id 9999!" should be shown
+
     # :undo
 
     Scenario: Undo without any closed tabs
```

like mentioned there, this should be `:tab-{give,take}` instead (see the comments).

**Comment by The-Compiler** [comment]
`:tab-give` / `:tab-take` were merged - thanks @kaashif and @Enzime!

**Comment by psygo** [comment]
Is there a way of using this to move a range of tabs? How would you automate that? I feel like it's pretty normal to start a little bit of research, and then, before you know it, you have 10+ tabs mixed with another environment. Right now, I'm getting around this by doing the same operation N times, which is kind of dumb for sure, I wonder if something like `:tab-give 1-10` would be a nice addition to this API...

**Comment by The-Compiler** [comment]
@psygo see #5040/#6119

**Comment by psygo** [comment]
@The-Compiler, cool pointers, but I wasn't able to find out how it works. Couldn't that kind of regex/range-like syntax be mentioned in the `:help` page &mdash; I couldn't find it there either &mdash;?

**Comment by emanuele6** [comment]
@psygo It's not documented in an `:help` page, because it is still being developed and it is not part of `qutebrowser` yet.
