### ISSUE TITLE
Different colors per completion column

### ISSUE THREAD

**Issue by haasn** [qutebrowser/qutebrowser#1794]
I think it would present a lot of visual clarity to be able to style the completion list's “sections” separately.

For example in pentadactyl, I can very easily visually distinguish between URLs and URL titles based on color alone:

![pentadactyl](https://0x0.st/BbS.png)

I'm lacking this visual feedback in qutebrowser. I think as a rough first approximation it would be fine to give explicit colors to the Nth sections (regardless of what they are), but I think in principle for this to work as well as possible the section order would have to be somewhat consistent between commands (so the URL is always in the same place, the title is always in the same place, etc.)

**Comment by The-Compiler** [comment]
Based on the screenshot, I guess you mean columns when you say sections?

**Comment by haasn** [comment]
Yes, exactyl
