### ISSUE TITLE
Add an option to yank the HTTP basic access authentification credentials with the URL

### ISSUE THREAD

**Issue by ThibautMarty** [qutebrowser/qutebrowser#1848]
We should have an option to `yank` to copy the crendentials with the form:
scheme://user:password@url

**Comment by TriRpi** [comment]
Can you maybe specify the issue a bit more?

**Comment by The-Compiler** [comment]
`:yank url` (or `yy`) doesn't copy the credentials (HTTP username/password) in the URL - @ThibautMarty is asking for an option to `:yank` to include those in the copied URL.

**Comment by arza-zara** [comment]
Now possible with `:yank inline {url:scheme}://{url:auth}{url:host}{url:path}{url:query}`. (#4652)
