### ISSUE TITLE
Add a way to escape replacements in the commandline

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1861]
In #1791 there was some discussion because there's no way to escape replacements like `{url}` in commands.

Moving this to here to make things easier, and so I don't forget that we should find a solution before v0.9.0.

cc @lahwaacz @blyxxyz

**Comment by blyxxyz** [comment]
>Sorry for coming late to this, but I think there should be a way to escape the pseudovariables for replacement - especially if more will be added in the future. I admit that it does not matter for commands that do some validation of the input in arguments, but e.g. :open is frequently used to pass unrecognized input to a search engine. Here the input can be anything (you never know what the compiler or interpreter spits out in the error messages :wink:) and it doesn't make much sense to replace if the result as a whole is not going to be recognized.

I suppose this is only a problem if you enter the text interactively (instead of through a binding like `PP`) because variables don't expand recursively. Variable expansion could be skipped for interactively entered commands.

**Comment by The-Compiler** [comment]
Hmm, that sounds like a clever solution I didn't think of yet.

**Comment by lahwaacz** [comment]
This way, after #1862, you wouldn't be able to do neither `:yank url` or `:yank {url}` interactively. I don't think that's a good strategy.

**Comment by blyxxyz** [comment]
How often would you run `:yank` interactively? All of the original targets have bindings.

**Comment by lahwaacz** [comment]
That's not the right question. If all these commands exist only as targets for bindings, why do we have the interactive command prompt at all? There is most likely a reason why `:yank` is not a hidden command and we should focus on improving functionality here, not impairing it.

**Comment by blyxxyz** [comment]
Maybe a per-command registry option for interactively expanding variables? There can't be that many commands besides `:open` you'd throw random junk like compiler messages in.

**Comment by The-Compiler** [comment]
FWIW, I can't think of more apart of `:open` and `:search` / `/foo`

**Comment by Kingdread** [comment]
Add `:bind` to the list, as you probably want the replacement done when the bound command is called, not when it's bound.

**Comment by blyxxyz** [comment]
`:bind` is registered with `no_replace_variables` so it already doesn't do that, whether you run it interactively or not. That option wouldn't be appropriate for `:open` because you often do want to expand `{url}`.

**Comment by kobezda** [comment]
I think there's no nice way to have `:open` both expand some variables - `{clipboard}`, `{primary}`, and be able to paste arbitrary input to it, without having either:

1. Two commands, `:open` which behaves as it does now and let's say `:nopen` which is like `:open`, but with `no_replace_variables`
2. Some kind of config setting enumerating which variables should be expanded for which commands.

**Comment by The-Compiler** [comment]
But does `:open` really have to expand variables when it's used interactively?

**Comment by lahwaacz** [comment]
> But does `:open` really have to expand variables when it's used interactively?

That depends on which variables there are, or will be. Currently the expansion for `:open` is indeed pretty much useless - instead of `:open {url}` you can press `go` and instead of writing `{clipboard}` or `{primary}` you can press `<Ctrl+v>` or `<Shift+Ins>`.

But making a decision based on whether a command is run interactively would be yet another inconsistency, similar to what I was talking about in the other thread https://github.com/The-Compiler/qutebrowser/issues/1850#issuecomment-246273921. Moreover, more variables may come in the future, which might make sense to expand even when run interactively.

**Comment by The-Compiler** [comment]
This is probably some more work (via #2017) so I decided to remove this from v0.9.0.

**Comment by user202729** [comment]
@The-Compiler #3562 is merged, should this be closed? (and also consider merging the other conflicting PRs, such as #1862 or #1937 )

**Comment by The-Compiler** [comment]
Closing this - @jgkamat is picking up the rest in #4651 and #4652. Thanks everyone (@lahwaacz, @kobezda, @blyxxyz @gebulmer, @jgkamat, and everyone I forgot) for your inputs and PRs!
