### ISSUE TITLE
Implement qute://history

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#1887]
`qute://history` would render your browsing history in a tabular format, similar to what `qute://log` does for your logs.

We can bikeshed on #1885 forever, but I think this is a good idea regardless of what we do with `:open` completion.

@mlochbaum did you want to work on this?

**Comment by mlochbaum** [comment]
I'm somewhere in the middle of implementing it now. I have a working page but it doesn't format times or URLs yet.
