### ISSUE TITLE
Read all resource files into RAM on start?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1943]
qutebrowser accesses various files at runtime:
- HTML templates for error pages, directory browsing, etc.
- javascript files for QtWebEngine, caret browsing, etc.
- probably some more

This causes trouble for people in various situations:
- The files are gone for some reason
- They updated qutebrowser without restarting it, and those files have newer code, but the corresponding Python code running is still older.

We could get around this by simply reading everything into RAM on start. The amount of RAM this needs should be negligible, and we have a defined point where stuff will fail when the files are not there or unreadable.

**Comment by haasn** [comment]
Wouldn't just opening the files at startup and keeping the file handles around (or MMAPing them) solve this without increasing the RAM cost?

**Comment by The-Compiler** [comment]
I guess that'd work too, but no idea how that behaves on Windows and OS X.

Then again, we're talking about 1-2 kilobytes here, so I don't think it'd be a problem.

**Comment by The-Compiler** [comment]
Welp, 50 crash records and counting since v1.1.0 had an incompatible change in the JS/Python API. This should really be fixed by either versioning the API or doing what I intended here.
