### ISSUE TITLE
Document userscript types on Windows

### ISSUE THREAD

**Issue by dnebauer** [qutebrowser/qutebrowser#1946]
Include in userscripts documentation the information that on Windows userscripts can only be `com` and `bat` (and `exe`) files. *nix users will intuitively expect python, perl, ruby (and other) userscripts to execute on Windows platforms that are configured to run such scripts natively from the dos command line.

**Comment by Kissaki** [comment]
#2006 has been merged, please close!?

**Comment by jgkamat** [comment]
Thanks  for the catch! :)
