### ISSUE TITLE
Cannot bind <ctrl-k> in command mode

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#1965]
`bind --mode=command --force <Ctrl-k> rl-unix-filename-rubout`

`Can't find binding '<ctrl-k>' in section 'command'!`

I'm guessing this is because ctrl-k is bound in a `[command,prompt]` section rather than just `[command]`.

**Comment by The-Compiler** [comment]
The new config doesn't have combined sections like `command,prompt` anymore.
