### ISSUE TITLE
:bind should error on unknown special keys

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#1966]
`bind --mode=command <c-k> rl-unix-filename-rubout` should complain that `<c-k>` isn't a known special key (unless `<c-k>` actually means something?).
Also, maybe we should consider `<c-k>` equivalent to `<ctrl-k>` for those familiar with vim :)

**Comment by The-Compiler** [comment]
Off-hand I don't know how it would know what a valid and what an invalid key is...

**Comment by rcorre** [comment]
I was assuming that only certain things between `<` and `>` have a valid meaning. Could `<c-k>` actually mean something? It doesn't seem to interpret it as a keychain. I guess maybe such a thing could come from an alternate keyboard layout?

**Comment by The-Compiler** [comment]
Hmm, right - at least for the part before the `-` we could know, as we handle that in `utils.keyevent_to_string`.

For the key name after `-` we probably can't, as we just use `QKeyEvent(key).toString()` when there's a keypress and then see if a binding matches.

**Comment by rcorre** [comment]
> at least for the part before the - we could know

That's mainly what I was expecting. I agree we can't validate the bit after that.

**Comment by The-Compiler** [comment]
Like pointed out in #3307, binding numbers should be disallowed as well.

**Comment by The-Compiler** [comment]
I ended up allowing numbers anyways, see #3684.
