### ISSUE TITLE
Automatic reload after a local HTML file update

### ISSUE THREAD

**Issue by stroobandt** [qutebrowser/qutebrowser#2065]
For web development purposes, it might be handy to have an option to reload/refresh open local HTML files automatically when these have been updated (by unrelated software).

In brief, something similar to the [Auto Reload](https://addons.mozilla.org/en-US/firefox/addon/auto-reload/) Firefox extension would be highly desirable.

Seen in version `0.8.2`

**Comment by paretje** [comment]
This can be done with a userscript. Using `inotifywait`, you can detect a write, after which you just send `reload`. It won't work however when you are in another tab on write.

**Comment by stroobandt** [comment]
> It won't work however when you are in another tab on write.

That would be rather inconvenient…

**Comment by amacfie** [comment]
workaround: https://github.com/tapio/live-server

**Comment by stroobandt** [comment]
Great suggestion, thanks!

**Comment by loweryaustin** [comment]
I wrote a UserScript for this today that is working very well so far:
https://gist.github.com/loweryaustin/4f4a8c34083c9b3cc0bf69dc73140b0a
