### ISSUE TITLE
[userscript: password_fill] angular js forms auto fill fail

### ISSUE THREAD

**Issue by sim590** [qutebrowser/qutebrowser#2111]
Consider the page at url: https://portailetudiant.uqam.ca/. When using userscript `password_fill` from #873, username and password gets properly filled, but the form cannot be sent with the form showing errors. The only way to work around this is to input some characters with the keyboard in each field. If the field is full, you actually have to remove a character and input it again.

When looking at the form's code:
```html
                  <span>&nbsp;&nbsp;Code permanent</span><br>
                  <input style="width:100%" name="codePermanent" ng-model="user.codePermanent" ng-pattern="/^[A-Za-z]{4}(0[1-9]|[12][0-9]|3[01]|6[3-9]|[78][0-9]|9[0-3]|99)([0,5][1-9]|[1,6][012]|13|63)[0-9]{4}$/" maxlength="12" tabindex="1" placeholder="(ex. : ABDC12034566)" autofocus="" required="" class="ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-maxlength">
                  <!-- ngIf: formMobile.codePermanent.$invalid && formMobile.codePermanent.$dirty && submitted -->

                  <br><br>
                  <span>&nbsp;&nbsp;NIP</span><br>
                  <input style="width:100%" type="password" name="password" ng-model="user.password" ng-pattern="/^[0-9]{5}$/" maxlength="5" tabindex="2" placeholder="(ex. : 12345)" required="" class="ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-pattern ng-valid-maxlength">

```
I saw that it was using AngularJS. I [dig a little more][1] and now I think that the problem is actually related to the AngularJS css classes:
```
ng-pristine
ng-dirty
```
Like if the userscript `password_fill` would not trigger the form to go from `ng-pristine` to `ng-dirty` or something. I may be wrong. I know nothing about javascript...

@t-wissmann Can you comment on this and/or tell if you could edit the userscript to trigger the relevant event if this is truely the solution? Thanks!

[1]: http://stackoverflow.com/a/25025544

### Version

I run qutebrowser with: `env QUTE_QTBUG54419_PATCHED=1 qutebrowser --backend webengine`

```
qutebrowser v0.8.4
Git commit: v0.8.0-1691-g690633b (2016-11-06 00:47:53 +0100)

CPython: 3.5.2
Qt: 5.7.0
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.2.109 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.8.6-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version:

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"

Paths:
runtime: /run/user/1000/qutebrowser
download: /home/simon/Téléchargements
system_data: /home/simon/.local/share/qutebrowser
cache: /home/simon/.cache/qutebrowser
config: /home/simon/.config/qutebrowser
data: /home/simon/.local/share/qutebrowser
```

**Comment by t-wissmann** [comment]
I don't see a general solution here, so I propose that you do a workaround for this specific site only. If you use the `pass` backend, then you could fill this field manually or by a `pass` script.

Also for me, the `password_fill` does not work for all forms (e.g. not if forms hidden in an iframe). That's why I created a [custom pass script](http://thorsten-wissmann.de/p/3e7fa904a600c2505b33eda1d4850492) that copies first the username and then the password to the clipboard. Unfortunately you have to call it explicitly and can not integrate it into `pass` [yet](https://lists.zx2c4.com/pipermail/password-store/2016-October/002414.html)

**Comment by paretje** [comment]
I use this [userscript](https://github.com/paretje/dotfiles/blob/master/.local/share/qutebrowser/userscripts/password_fill_insert) for sites where using the default javascript input method fails. Actually if it would work in your case, `password_fill` could be updated to use a `TextEvent` as well.

**Comment by sim590** [comment]
@paretje: your userscript is a nice workaround, but it would be better if `pssword_fill` was triggering text events as you say. I don't know how to do that off the top of my head. Hope someone comes up with something :smile_cat:.

@t-wissmann: Wouldn't simply injecting JS code with input event trigger be general enough?

**Comment by paretje** [comment]
@sim590: yes, but that would still only solve this issue. There would still be a problem on pages with frames, or for e.g. aliexpress which has a hidden text field for captcha's.

**Comment by t-wissmann** [comment]
@sim590: Yes, it should be indeed possible to simulate the input events directly in javascript [as described here](http://stackoverflow.com/a/12187302/4400896).

@paratje:if the captchas are done right, then there is no way to fill the captcha fields automatically.

**Comment by The-Compiler** [comment]
I unfortunately lack the time to take care of userscripts, so unless someone of you picks this up, nothing will change :wink:

(FWIW, I still intend to have some kind of API for this and some official example plugins as soon as there's a proper plugin API)
