### ISSUE TITLE
Create non-existing directories for downloads

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2120]
A path of `/tmp/foobar/filename` should download to `filename` in `/tmp/foobar` even if that doesn't exist.

A path of `/tmp/foobar/` (with a trailing slash) should download to `/tmp/foobar/suggested_filename.foo` even if `/tmp/foobar` doesn't exist.

To avoid creating directories on typos we could also display a prompt first.

**Comment by sfgasdfsafggfgg** [comment]
nice, I like this behavour

**Comment by laugh-at-me** [comment]
Hi! I am working on this. In fact I am waiting for tox to finish running the test suite, and I'll submit a pull request. Thanks, best regards! Panos
