### ISSUE TITLE
Missing window title

### ISSUE THREAD

**Issue by rafi** [qutebrowser/qutebrowser#216]
I'm using KeepassX for storing and auto-typing passwords, matching the application's window title. KeepassX isn't detecting qutebrowser's window title, and inspecting with `xprop` I've noticed it's missing the `WM_NAME` property. It does have `_NET_WM_NAME`, but Chrome for example has both.
_(I'm using i3 window-manager)_

**Comment by The-Compiler** [comment]
For the record: A change setting `WM_NAME` has been [merged in Qt](https://codereview.qt-project.org/#/c/107853/) as well.
