### ISSUE TITLE
Add option to disable webrtc

### ISSUE THREAD

**Issue by craftyguy** [qutebrowser/qutebrowser#2163]
WebRTC will leak private IPs externally, which is a privacy concern. Is it possible to add an option to disable WebRTC completely?

**Comment by The-Compiler** [comment]
Unfortunately not. I did some research and opened [QTBUG-57505](https://bugreports.qt.io/browse/QTBUG-57505) to try and do something about that, but right now there's nothing I can do...

**Comment by craftyguy** [comment]
Ah, well thank you for checking it out. Hopefully they'll add this functionality in webengine!

**Comment by The-Compiler** [comment]
Looks like it'll be at least configurable at QtWebEngine's compile-time soon: https://codereview.qt-project.org/#/c/183578/

**Comment by The-Compiler** [comment]
Reopening this as there's some good news:

- Starting with Qt 5.9.0, you can [disable it on compile-time](https://codereview.qt-project.org/#/c/183578/) 
- Starting with Qt 5.9.2, you [should be able to](https://codereview.qt-project.org/#/c/200248/) use `--qt-flag=force-webrtc-ip-handling-policy=default_public_interface_only` (and qutebrowser can probably add an option requiring a restart with the new config)
- Starting with Qt 5.11 (if everything goes well), there's an [option to configure it](https://codereview.qt-project.org/#/c/204221/) at runtime.

**Comment by The-Compiler** [comment]
Hmm... looks like `--qt-flag=force-webrtc-ip-handling-policy=default_public_interface_only` worked with Qt 5.9 but doesn't anymore with 5.10 (tested with https://www.privacytools.io/webrtc.html)

**Comment by concatime** [comment]
Any changes from last time?

**Comment by The-Compiler** [comment]
"last time"? But no, if something happens (after Qt and PyQt 5.11 are out), I'll update this issue

**Comment by The-Compiler** [comment]
Just noticed this didn't actually work correctly on Qt 5.11. It's fixed in e927fecbbc12053d2e64deddf4bc89e570f0dcc6 and you can add `force-webrtc-ip-handling-policy=default_public_interface_only` to `qt.args` as a workaround.

**Comment by The-Compiler** [comment]
It looks like with that Qt setting set, private IPs aren't leaked anymore, but public IPs still are - see #4201.
