### ISSUE TITLE
"Focus first input" command / autoselect first hint

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#219]
`gi` in dwb/Vimium. Requested by rafi in IRC.

See also #13 

dwb implementation (js):

``` js
    var p_focusInput = function()
    {
        var i;
        var res = document.body.querySelectorAll('input[type=text], input[type=password], textarea');
        if (res.length === 0)
        {
            return "_dwb_no_input_";
        }
        var styles = document.styleSheets[0];
        styles.insertRule('input:focus { outline: 2px solid #1793d1; }', 0);
        if (!globals.activeInput)
        {
            globals.activeInput = res[0];
        }
        else
        {
            for (i=0; i<res.length; i++)
            {
                if (res[i] == globals.activeInput)
                {
                    globals.activeInput = res[i+1] || res[0];
                    break;
                }
            }
        }
        globals.activeInput.focus();
    }
```

Though probably we should just implement a `--first` flag or so for hints, which automatically selects the first one.

**Comment by magnetophon** [comment]
Another +1!
Hope you guys find a solution!

**Comment by lahwaacz** [comment]
If `gi` should start hint mode with the `input` type, does the editability really matter? Maybe for `--first`, but otherwise there will just be some dead-end hints for the user to ignore, but still less than using plain `:hint`.

**Comment by haasn** [comment]
My 2 cents on this topic: The best way to implement something like this IMO is to provide a hints setting to automatically follow hints if there's only a single match.

In that case, I can use `;gt` to automatically select the input field if there only is one visible on the page, without having to type the hint key associated with it first.

**Comment by Eisfreak7** [comment]
I disagree, that is a different feature.
For  example, to type in this answer, I just hit `gi` (pentadactyl) and immediately was in the answer field. I don't know exactly how it works, but somehow `gi` selects nearly always the "correct" Input, even if there are multiple possible hints like on github.

**Comment by haasn** [comment]
Yes, it's a different functionality but it would still select the right thing automatically often enough for me to consider it a reasonable alternative. (For example while I'm typing this comment, this is the only input box visible on-screen)

In fact, my suggestion ties into another feature on my wish list: automatically follow hints as soon as there is exactly 1 match, eve n dynamically (e.g. say I use hint mode = words and a hint is “bicycle”, as soon as I press “bi” it might already uniquely identify the option so it would get selected right away - saving me a bunch of extra keystrokes)

So implementing that would kill two birds with one stone as far as I'm concerned.

**Comment by lahwaacz** [comment]
> In fact, my suggestion ties into another feature on my wish list: automatically follow hints as soon as there is exactly 1 match

That's already implemented: `:set hints auto-follow true` (and it's even enabled by default)

**Comment by The-Compiler** [comment]
> That's already implemented: `:set hints auto-follow true` (and it's even enabled by default)

It however doesn't do partial matches - it's only controlling whether you need to press enter after a full match.

**Comment by haasn** [comment]
@lahwaacz I had a look at the source code and honestly it seems like the current state is bugged more than anything: Have a look at these lines: https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/hints.py#L832

The way this is written makes it painfully obvious that the original, intended behavior of this function was to always auto-follow as soon as the match was unique (just how I imagine it working), but for some reason (I don't know why), `filter_hints` never ends up getting called as you type except in `number` mode. (This strikes me as especially odd because the extra hints *do* go away as you type! What is filtering them, if not filter_hints?)

**Comment by lahwaacz** [comment]
Well, the funny thing is that the `filter_hints` method is called only for the `number` mode. As this is too off-topic for my taste, I created #1809 for that.

**Comment by lahwaacz** [comment]
Assuming that the "wok in progress" label was related to #1817, this is currently not being worked on.

**Comment by NoctuaNivalis** [comment]
We were discussing this in IRC, and I was shortly possessed by Frankenstein and created following monster: `:jseval --quiet var inputs = document.getElementsByTagName("input"); for(var i = 0; i < inputs.length; i++) { var hidden = false; for(var j = 0; j < inputs[i].attributes.length; j++) { hidden = hidden || inputs[i].attributes[j].value.includes("hidden"); }; if(!hidden) { inputs[i].focus(); break; } }`

Basically, this will (with a very sofisticated heuristic) select the first visible input element on the current page. You can bind it to `z` or anything you want using:

    :bind z jseval --quiet var inputs = document.getElementsByTagName("input"); for(var i = 0; i < inputs.length; i++) { var hidden = false; for(var j = 0; j < inputs[i].attributes.length; j++) { hidden = hidden || inputs[i].attributes[j].value.includes("hidden"); }; if(!hidden) { inputs[i].focus(); break; } }

Finally, a readable version for those who dislike pasting a bunch of random javascript in their browser:

```javascript
// get all HTMLelements with an "input" tag
var inputs = document.getElementsByTagName("input");
for(var i = 0; i < inputs.length; i++) { // for each input tag, do stuff
    // assuming the field is not hidden
    var hidden = false;
    for(var j = 0; j < inputs[i].attributes.length; j++) { // for each attribute of this element
        // if the attributes value contains "hidden", it's probably hidden.
        hidden = hidden || inputs[i].attributes[j].value.includes("hidden");
    }
    if(!hidden) {
        inputs[i].focus(); // grab focus
        break;             // gtfo
    }
}
```

I've only tested this on a few sites, but it should never break anything, it just might not work all the time.

**Comment by haasn** [comment]
@NoctuaNivalis you say “first visible”, but for example running that command right now (scrolled to the bottom of this issue page) selects the search bar at the top of the page instead of the text box down here.

(The `gi` binding I use does not have this issue)

**Comment by NoctuaNivalis** [comment]
Ah yes, it's the first visible on the current (entire) page, not just the viewbox. I don't think you can check actual visibility on the screen with javascript?

**Comment by The-Compiler** [comment]
FWIW here's what I do for hints: https://github.com/The-Compiler/qutebrowser/blob/v0.9.0/qutebrowser/javascript/webelem.js#L69-L106

**Comment by dkasak** [comment]
`--first` sounds like the right idea. Is it still the plan to solve it like that?

**Comment by The-Compiler** [comment]
Still sounds good to me!

**Comment by Ape** [comment]
I was missing this feature from cVim, but now I find that binding `gi` to `hint inputs` is even better.

**Comment by asmbits** [comment]
Is there an option to automatically select a hint if there is only one available? For example If I open ddg.gg and press `hint inputs` there is only one input field and would be great to autoselect it.

**Comment by The-Compiler** [comment]
@asmbits `:set hints.auto_follow always`

**Comment by asmbits** [comment]
that's it, thanks!

**Comment by asmbits** [comment]
@The-Compiler on some sites it doesn't work. For example on google.com, there is only one input field but it is not selected automatically.

**Comment by The-Compiler** [comment]
@asmbits works fine here (with `:hint inputs`).

**Comment by asmbits** [comment]
doesn't work for me though on some sites, https://imgur.com/a/wKm9l, http://p.cmpl.cc/37b6392c

**Comment by GSI** [comment]
This should really be more prominent on a fresh install and have its own one-key keybinding.

I've been using it for a year and cannot remember a single instance where the key would not take me to the input field I actually wanted to focus on.

On my layout it's bound to an index finger key.
