### ISSUE TITLE
Empty space after the last tab

### ISSUE THREAD

**Issue by code-hunger** [qutebrowser/qutebrowser#2202]
Right after the last tab there's an empty space (occupying as much space as a single tab).  
It doesn't exist when there are fewer tabs (right now I have 48 open).

I just opened 50 empty tabs in a new window and there is no space there. Perhaps the tab-icons mess up here (because they force a minimal width for a tab, while the browser thinks a tab is e.g. 4px wide)?

I can post a screenshot but it seems unnecesarry for just an empty silver box.

**Comment by The-Compiler** [comment]
I've seen this some while back, but only with a few pixels. Please post a screenshot so we can be sure we're talking about the same thing.

Also, does it change colors when you change `colors -> tabs.bg.bar`? Can you reproduce it with `--temp-basedir`?

**Comment by code-hunger** [comment]
![mon jan 2 23 21 33 2017](https://cloud.githubusercontent.com/assets/11772321/21596382/0ebe9e7e-d143-11e6-88bb-e37494bfabd4.png)
![mon jan 2 23 23 22 2017](https://cloud.githubusercontent.com/assets/11772321/21596381/0ebe2426-d143-11e6-9d8b-e89ac2c6e2ea.png)
The same happens with `--temp-basedir`.
**But** if I change the startpage to e.g. "blank", the blank space doesn't show up even with 60 tabs. If the startpage is duckduck, the spaces appears when I open the 35th tab. As soon as the number of tabs is <=34, it disappears (all the tabs running duckduck)

If I resize the window and make it shorter the blank space appears on the 27th tab. According to xprop the window is 800 pixels wide.
On fullscreen the window is 1364 pixels wide.

**Comment by code-hunger** [comment]
[[ with --temp-basedir ]] I think I found something interesting. If I open e.g. 20 clones of the `:help` page and then start opening duckduck-s, the blank space appears even further - on the 52th tab. (fullscreen)  
I think this helps because the help-tabs are much shorter due to the lack of icons there:
![image](https://cloud.githubusercontent.com/assets/11772321/21596751/398b2a50-d148-11e6-939a-fd71c783078a.png)

**Comment by The-Compiler** [comment]
Yep, I've definitely seen this happen for a while, and at least back then I wasn't able to figure out what's causing it. I should probably take another look some time with a bit more Qt experience now.

**Comment by The-Compiler** [comment]
Closing this in favor of #2746, as that has more information about why this happens.
