### ISSUE TITLE
OSX .dmg file not available for 0.9

### ISSUE THREAD

**Issue by nathyong** [qutebrowser/qutebrowser#2203]
I've looked around a bit on the releases page and the install page, and there doesn't appear to be an updated .dmg file for the recent 0.9 release of qutebrowser. Does anybody know who the packager for these binaries is, and/or whether we should expect a pre-built binary distribution for 0.9 on OSX?

The alternative is indeed installing the source dependencies and building from source, but qt5 requires the qtWebKit which has a lengthy build time and requires full XCode to be installed. This is a viable, if time-consuming option, but I don't know if support for OSX has been dropped in 0.9.

**Comment by The-Compiler** [comment]
That'd be me :wink:

As mentioned in the [announce mail](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2016-December/000006.html), I can't reach my Mac Mini via SSH, and it'll take a while (maybe until February, because of exams and stuff) before I'm physically there again and can take a look at what's up.

**Comment by nicoNaN** [comment]
I've encountered issues when attempting to follow the instructions to install 0.9 using Homebrew and MacPorts, centered around `PyQt5.QtWebKit` imports. Would be curious if you knew anything regarding these issues here - or if anyone else has had similar problems.

**Comment by The-Compiler** [comment]
@nicoNaN did you build Qt/PyQt from source as per [the instructions](https://github.com/The-Compiler/qutebrowser/blob/master/INSTALL.asciidoc#manual-install-1)? If so, please open a new issue with detailed information about what you did and what's happening.

**Comment by nicoNaN** [comment]
Yes, built from source as per the instructions. I'll give it another shot later today and create a new issue with information and the logs. Thanks for the reply!

**Comment by The-Compiler** [comment]
Good news: Someone in the hackerspace (where the Mac is) got it running again, without me even asking for it 👍 

Bad news: Homebrew updated to Python 3.6, and PyInstaller doesn't support that yet: https://github.com/pyinstaller/pyinstaller/issues/2331 - so no Mac release until either that happens, or I get time to set up a custom Python/PyQt installation.

**Comment by engelju** [comment]
Perhaps it would make sense to mention that there is no 0.9 build yet for OS X on the website (ie. on http://qutebrowser.org/INSTALL.html under "On OS X"), as it can be quite confusing if there's a link to the release page in the OS X-section, but no .dmg available to download for current-ish releases.

I was a victim of this myself... 😅

**Comment by The-Compiler** [comment]
Can someone (or ideally, multiple people) please test [this dmg](https://qutebrowser.org/tmp/qutebrowser-20170219.dmg)? It's the current git master of qutebrowser built with QtWebEngine only. It seems to run fine on my machine as far as I can tell without access to the GUI :wink:

cc @m2habert @edrex

**Comment by edrex** [comment]
This is very exciting, thank you @The-Compiler.

Quickly tested:

 - [x] Youtube (playback, fullscreen)
 - [x] Gmail
 - [x] Facebook

I'll try running this as my daily driver for a few days and report any issues I find, but it seems to be working well for me.

**Comment by The-Compiler** [comment]
It's very interesting that YouTube works. I used PyQt5 from PyPI, which apparently uses Qt installed from the official binaries, which I thought came without proprietary codecs (MP3/h264).

FWIW what I've noticed so far is that error pages don't show any text. I guess some kind of resource is still missing, but I'm probably going to release v0.10.0 with that bug :wink:

**Comment by edrex** [comment]
Stats for nerds says it's streaming webm/vp9:

<img width="648" alt="screen shot 2017-02-19 at 12 14 37 pm" src="https://cloud.githubusercontent.com/assets/14615/23106104/45d15bf2-f69d-11e6-9c01-9356e3094736.png">

Same as Chrome for that video:

<img width="429" alt="screen shot 2017-02-19 at 12 18 00 pm" src="https://cloud.githubusercontent.com/assets/14615/23106124/7e1b32d0-f69d-11e6-8f30-61c6a0409f89.png">

**Comment by edrex** [comment]
on http://www.quirksmode.org/html5/tests/video.html the h264 video doesn't render

**Comment by The-Compiler** [comment]
Ah, nice. I was trying to rebuild QtWebEngine with MP3/h264 support for Windows/Linux/Mac, and at least for Windows I've given up, maybe for the others I'll too. Seeing that YouTube works, I guess it's not that bad :wink:

**Comment by edrex** [comment]
I'm happy to take a crack at building Qt WebEngine with the media codec support if we could use it to set up repeatable OS X builds on TravisCI, and document the build process for new Qt releases. Is it possible to rebuild it while using an official build for the rest of Qt?

**Comment by The-Compiler** [comment]
> if we could use it to set up repeatable OS X builds on TravisCI

What exactly do you mean here?

- qutebrowser test runs for OS X on Travis - those [are full of weird failures](https://travis-ci.org/qutebrowser/qutebrowser/jobs/203525564) I haven't been able to track down so far.
- Building qutebrowser OS X releases on Travis - I'd rather not give Travis access to upload stuff everywhere it needs to be uploaded. But if we have usable, reliable Qt binaries (like currently with PyQt5 from PyPI) it'll make my life much easier on my own Mac as well.

> and document the build process for new Qt releases

I started that, but stashed it when I gave up. I usually do something like:

- Download Qt submodule tars for qtbase, qtdeclarative, qtwebchannel
- In qtbase: `./configure -confirm-licence -opensource -ssl -nomake tests -nomake examples -release && make -j2 && sudo make install`
- In qtdeclarative/qtwebchannel: `/usr/local/Qt-5.8.0/bin/qmake && make -j2 && sudo make install`
- In qtwebengine: `/usr/local/Qt-5.8.0/bin/qmake WEBENGINE_CONFIG+=use_proprietary_codecs && make -j2 && sudo make install`

That last step currently fails on my machine at the very end, and I opened [QTBUG-59014](https://bugreports.qt.io/browse/QTBUG-59014).

> Is it possible to rebuild it while using an official build for the rest of Qt?

Probably, but the build time for qtbase/qtdeclarative/qtwebchannel is nothing compared to QtWebEngine anyways, so I'd just build it all from source. Probably less trouble.

**Comment by m2habert** [comment]
> It's very interesting that YouTube works. 

But sometimes YouTube would work in previous versions, I always assumed that it was due to some new video streaming implementation that was more universal than > It's very interesting that YouTube works. 

But sometimes YouTube would work in QB's previous versions, totally random. I always assumed that it was due to YouTube implementing some new video streaming that was more universal than others.

(downloading new QB right now)

**Comment by tuxlovesyou** [comment]
I may not have much time, but I'd be happy to do a build on my 2016 MacBook
Pro running Sierra.

**Comment by The-Compiler** [comment]
Good news - I got QtWebEngine built now by also (re)building qttools by hand. If everything else works (nothing tested yet), I might actually release a build with those codecs enabled.

**Comment by The-Compiler** [comment]
I just released v0.10.0, including an OS X dmg! (with the PyPI PyQt5 without proprietary codec support though, let's see how that goes for now)

Sorry for the long wait!
