### ISSUE TITLE
Addition of ASCII star icon into the title when the page is bookmarked

### ISSUE THREAD

**Issue by Chinggis6** [qutebrowser/qutebrowser#2209]
It is hard to understand if the page is already bookmarked or not, so I usually end up pressing <kbd>M</kbd> multiple times in order to determine if.

http://xahlee.info/comp/unicode_stars.html

Why not to add a simple star *icon* filled ★ or empty ☆ or even a much more cooler inverted pentagram ⛧ (I'd parallel it to making DGG as the default search engine and homepage) into the title *or some place else*.

Bold enough! :P

**Comment by The-Compiler** [comment]
Why not a real star icon? :wink:

**Comment by The-Compiler** [comment]
Merging this into #3398.

**Comment by pkillnine** [comment]
It would be good to be able to show bookmark status in the statusbar also
