### ISSUE TITLE
insert-text silently fails with backend webengine

### ISSUE THREAD

**Issue by TrilbyWhite** [qutebrowser/qutebrowser#2217]
The insert-text command works reliably for me from command mode or keybinding when using webkit, but fails silently in webengine.  The command is being processed: if the primary selection is empty and I used `insert-text {primary}` I see an error message that the primary selection is empty.  But if there is something in the primary selection (or if I use `insert-text hello`), there is no error, but nothing appears in focused input field or textarea.

I don't know precisely when this problem appeared, but it has been a few weeks at least.  I am using a git build of qutebrowser and have just updated from r10933.59b378e29 to r10971.48d4c9311 with no change in symptoms or any of the below diagnostics.  I believe I was able to paste text previously with backend=webengine, but I can't be sure.  Up until a few days ago my key binding for this was bound to the older `paste-primary`.  When I started investigating I learned of the new `insert-text {primary}` and switched to that.  The below diagnostics are all with `insert-text {primary}` or insert-text with arbitrary text like "hello" or "testing".  Later today I'll get the debug output with `paste-primary` incase there are any differences.

Output from `qutebrowser --backend=webengine --debug` when an attempt is made to insert text on duckduckgo's search field:
```C22:57:06 DEBUG    commands   command:run:509 command called: insert-text ['"testing"']
22:57:06 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.insert_text(<qutebrowser.browser.commands.CommandDispatcher>, '"testing"')
22:57:06 DEBUG    webview    webenginetab:_js_cb_single:418 Got element from JS: {'outer_xml': '<input type="text" name="q" tabindex="1" autocomplete="off" id="search_form_input" class="search__input--adv  js-search-input" value="ddg" autocapitalize="off" autocorrect="off">', 'class_name': 'search__input--adv  js-search-input', 'id': 16, 'value': '', 'rects': [{'left': 361.984375, 'top': 19, 'width': 494.765625, 'height': 38, 'bottom': 57, 'right': 856.75}], 'tag_name': 'INPUT', 'attributes': {'autocomplete': 'off', 'name': 'q', 'type': 'text', 'id': 'search_form_input', 'class': 'search__input--adv  js-search-input', 'autocapitalize': 'off', 'tabindex': '1', 'value': 'ddg', 'autocorrect': 'off'}}
22:57:06 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input type="text" name="q" tabindex="1" autocomplete="off" id="search_form_input" class="search__input--adv  js-search-input" value="ddg" autocapitalize="off" autocorrect="off">'>
22:57:06 DEBUG    webelem    webengineelem:insert_text:103 Inserting text into element <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input type="text" name="q" tabindex="1" autocomplete="off" id="search_form_input" class="search__input--adv  js-search-input" value="ddg" autocapitalize="off" autocorrect="off">'>
22:57:06 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: None
```

@The-Compiler suggested on the [arch linux forums](https://bbs.archlinux.org/viewtopic.php?pid=1681219#p1681219) that the duckduckgo field was also failing for him, but that input fields on [this page](http://www.tizag.com/htmlT/htmlinput.php) were working.  I repeated the test on that page, and unfortunately it fails on that page too for me:
```08:16:08 DEBUG    commands   command:run:509 command called: insert-text ['hello\n']
08:16:08 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.insert_text(<qutebrowser.browser.commands.CommandDispatcher>, 'hello\n')
08:16:08 DEBUG    webview    webenginetab:_js_cb_single:418 Got element from JS: {'id': 1, 'value': '', 'class_name': '', 'tag_name': 'INPUT', 'outer_xml': '<input type="text">', 'rects': [{'top': 636.1875, 'bottom': 657.1875, 'height': 21, 'left': 416.890625, 'width': 154, 'right': 570.890625}], 'attributes': {'type': 'text'}}
08:16:08 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input type="text">'>
08:16:08 DEBUG    webelem    webengineelem:insert_text:103 Inserting text into element <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input type="text">'>
08:16:10 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: None
```

The results are the same with or without any of my own configurations: these debug outputs were both collected after I had moved ~/.config/qutebrowser/.

I've also just searched for any directory matching `*utebrows*` and `*ebengine*` in my home directory and removed the matches .local/share/qutebrowser/, .cache/qutebrowser/, and .qutebrowser/.  This had no impact on the symptoms or debug output.

I've found that I can use Ctrl-V to paste from the clipboard selection.  So for now I'm limping along with that by syncing my primary and clipboard selections.  But this only work with Ctrl-V directly (I assume this is a qt thing) as `insert-text {clipboard}` also fails.

My shift-insert binding to insert the primary selection **does** work in command mode input.  I can yank a webpage url, use a binding for ':open -t ' and press shift-insert to paste the yanked url.  So it seems the failure is limited to webview elements.  I can't help but suspect that it is how qt handles text feilds.  But I'm far outside my experience there.  It seems the code for insert-text is python and/or javascript and I don't see any leads on what to follow up with qt settings, configuration, etc.  But for the record, I have pyqt5 packages at version 5.7 and qt5-webengine and other qt package as version 5.7.1 all from the archlinux repos.

As I write this I realize I was tinkering with getting widevine working with qutebrowser at what may be around when the problem appeared (I don't recall specifically, but certainly both events are in the same month or two window).  I'll be removing any trace of that and repeating some tests.  I can't imagine how that could have an impact, but as I'm running out of suspects ...

(**edit**) I've removed widivine, and all symptoms and diagnostics remain the same - for good measure I also rebootted (to ensure no shared libs from widevine were still loaded).  I also tried reverting the keybinding to `paste-primary` and that seems to have identical debug output (I'm assuming this must just now function as an alias to the new command).

---
xref: original report on [archlinux forums](https://bbs.archlinux.org/viewtopic.php?pid=1681202#p1681202)

**Comment by lahwaacz** [comment]
I'm seeing this as well on 976cd5f881153156f456bef108e21f758140f336, which is two weeks older than Trilby's first commit. It seems that the Javascript part of [insert_text](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/webengine/webengineelem.py#L100-L105) does not work. Unfortunately I don't know (yet) how to work with Javascript in webengine...

**Comment by lahwaacz** [comment]
I started debugging and made these modifications:
```diff
diff --git a/qutebrowser/browser/webengine/webengineelem.py b/qutebrowser/browser/webengine/webengineelem.py
index bf8d06474..c7eb234da 100644
--- a/qutebrowser/browser/webengine/webengineelem.py
+++ b/qutebrowser/browser/webengine/webengineelem.py
@@ -102,7 +102,11 @@ class WebEngineElement(webelem.AbstractWebElement):
             raise webelem.Error("Element is not editable!")
         log.webelem.debug("Inserting text into element {!r}".format(self))
         js_code = javascript.assemble('webelem', 'insert_text', self._id, text)
-        self._tab.run_js_async(js_code)
+        log.webelem.debug("js_code = {}".format(js_code))
+        def cb(*args):
+            log.webelem.debug("callback result: {}".format(args))
+        self._tab.run_js_async(js_code, cb)
 
     def rect_on_view(self, *, elem_geometry=None, no_js=False):
         """Get the geometry of the element relative to the webview.
diff --git a/qutebrowser/javascript/webelem.js b/qutebrowser/javascript/webelem.js
index 84d38b348..d2fb0149c 100644
--- a/qutebrowser/javascript/webelem.js
+++ b/qutebrowser/javascript/webelem.js
@@ -139,6 +139,7 @@ window._qutebrowser.webelem = (function() {
         var event = document.createEvent("TextEvent");
         event.initTextEvent("textInput", true, true, null, text);
         elem.dispatchEvent(event);
+        return elements;
     };
 
     funcs.element_at_pos = function(x, y) {
```
Then I start `./qutebrowser.py --backend webengine --temp-basedir --loglevel debug --logfilter webelem`, enter insert mode and press `Shift+Ins`, which should insert `testing` into the input field on duckduckgo. After three presses the result is:
```
11:46:01 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
11:46:01 DEBUG    webelem    webengineelem:insert_text:103 Inserting text into element <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
11:46:01 DEBUG    webelem    webengineelem:insert_text:106 js_code = "use strict";
window._qutebrowser.webelem.insert_text(0, "testing");
11:46:01 DEBUG    webelem    webengineelem:cb:108 callback result: ([{}],)
11:46:06 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
11:46:06 DEBUG    webelem    webengineelem:insert_text:103 Inserting text into element <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
11:46:06 DEBUG    webelem    webengineelem:insert_text:106 js_code = "use strict";
window._qutebrowser.webelem.insert_text(1, "testing");
11:46:06 DEBUG    webelem    webengineelem:cb:108 callback result: ([{}, None],)
11:46:08 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
11:46:08 DEBUG    webelem    webengineelem:insert_text:103 Inserting text into element <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
11:46:08 DEBUG    webelem    webengineelem:insert_text:106 js_code = "use strict";
window._qutebrowser.webelem.insert_text(2, "testing");
11:46:08 DEBUG    webelem    webengineelem:cb:108 callback result: ([{}, None, None],)
```

1. Why does the webelem ID (`self._id` in the WebEngineElement instance) increase each time, when I'm inserting into the same element?
2. The connection between Python and [var elements](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/javascript/webelem.js#L24) in `webelem.js` is beyond me. According to the log above, the array seems to be initialized with an empty dict (`{}`) and the increasing ID accesses an undefined element on the next calls, hence the `None`.

**Comment by The-Compiler** [comment]
You're right, this definitely needs some explanation. I added a comment: https://github.com/The-Compiler/qutebrowser/commit/16c8c1b1899b97da446343162969f38fae6c6525

`webelem.insert_text` doesn't return anything, so I'm guessing JS just returns the last statement's return value, so `elem.dispatchEvent(event);` - not sure if that's relevant? Though it's definitely an... interesting value. 

The ID increases because `serialize_elem` is pretty dumb and doesn't check if it has serialized the same element before already.

**Comment by lahwaacz** [comment]
Interestingly when I add `console.log(JSON.stringify(elements));` right after `elements[id] = elem;` in the `serialize_elem` function, all I get is an array of empty objects: `[{},{},{}]`

**Comment by The-Compiler** [comment]
What about logging `elem` in `focus_element` in JS? I'm guessing it'll be `{}` there? If so, the question is why...

**Comment by The-Compiler** [comment]
Also, the other question is why we get `[{}, None, None]` for `[{}, {}, {}]` (not `[{}, null, null]`) in Python. I'm guessing either this is some weird JS thing I don't know about, or a QtWebEngine bug.

**Comment by lahwaacz** [comment]
Yep, elem is `{}` in `focus_element`...

**Comment by The-Compiler** [comment]
So I tried to track this down a bit, and I can get the element just fine. With some logging added:

```diff

diff --git a/qutebrowser/javascript/webelem.js b/qutebrowser/javascript/webelem.js
index 6e7209914..6c2b8379e 100644
--- a/qutebrowser/javascript/webelem.js
+++ b/qutebrowser/javascript/webelem.js
@@ -137,6 +137,7 @@ window._qutebrowser.webelem = (function() {
 
     funcs.focus_element = function() {
         var elem = document.activeElement;
+        console.log(elem);
 
         if (!elem || elem === document.body) {
             // "When there is no selection, the active element is the page's
@@ -153,6 +154,10 @@ window._qutebrowser.webelem = (function() {
 
     funcs.insert_text = function(id, text) {
         var elem = elements[id];
+        console.log("insert_text")
+        console.log(elem);
+        console.log(text);
+
         var event = document.createEvent("TextEvent");
         event.initTextEvent("textInput", true, true, null, text);
         elem.dispatchEvent(event);
```

I get:

```
19:32:28 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.insert_text(<qutebrowser.browser.commands.CommandDispatcher>, 'engine')
19:32:28 INFO     js         webview:javaScriptConsoleMessage:289 [:245] [object HTMLInputElement]
19:32:28 DEBUG    webview    webenginetab:_js_cb_single:420 Got element from JS: {'attributes': {'autocapitalize': 'off', 'autocomplete': 'off', 'autocorrect': 'off', 'class': 'js-search-input search__input--adv', 'id': 'search_form_input_homepage', 'name': 'q', 'tabindex': '1', 'type': 'text', 'value': ''}, 'class_name': 'js-search-input search__input--adv', 'id': 2, 'outer_xml': '<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">', 'rects': [{'bottom': 420.90625, 'height': 45.953125, 'left': 145.25, 'right': 607.34375, 'top': 374.953125, 'width': 462.09375}], 'tag_name': 'INPUT', 'value': ''}
19:32:28 DEBUG    webelem    webelem:is_editable:253 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
19:32:28 DEBUG    webelem    webengineelem:insert_text:104 Inserting text into element <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="search_form_input_homepage" class="js-search-input search__input--adv" type="text" autocomplete="off" name="q" tabindex="1" value="" autocapitalize="off" autocorrect="off">'>
19:32:28 INFO     js         webview:javaScriptConsoleMessage:289 [:262] insert_text
19:32:28 INFO     js         webview:javaScriptConsoleMessage:289 [:263] [object HTMLInputElement]
19:32:28 INFO     js         webview:javaScriptConsoleMessage:289 [:264] engine
```

So that part seems to work fine here.

However, it seems like the text event stuff just doesn't work anymore at all?

For example, even [this example](https://gist.githubusercontent.com/flying19880517/3180456/raw/de99075160a03b2bfe4477bd440d461bf08ce4a7/initTextEvent.htm) doesn't work for me in qutebrowser or Chromium.

When going back to what we used before 35e16a8e6ea7ae4aa33a44ccbe4c7ad29f205899:

```diff
diff --git a/qutebrowser/javascript/webelem.js b/qutebrowser/javascript/webelem.js
index 6e7209914..7bbd525fb 100644
--- a/qutebrowser/javascript/webelem.js
+++ b/qutebrowser/javascript/webelem.js
@@ -153,9 +153,24 @@ window._qutebrowser.webelem = (function() {
 
     funcs.insert_text = function(id, text) {
         var elem = elements[id];
+
+        if (elem.selectionStart || elem.selectionStart == '0') {
+            var startPos = elem.selectionStart;
+            var endPos = elem.selectionEnd;
+            elem.value = elem.value.substring(0, startPos)
+                + text
+                + elem.value.substring(endPos, elem.value.length);
+            elem.selectionStart = startPos + text.length;
+            elem.selectionEnd = startPos + text.length;
+        } else {
+            elem.value += text;
+        }
+
+        /*
         var event = document.createEvent("TextEvent");
         event.initTextEvent("textInput", true, true, null, text);
         elem.dispatchEvent(event);
+        */
     };
 
     funcs.element_at_pos = function(x, y) {

```

Things seem to work fine again, but undo is broken again.

@lahwaacz do you know a way to do this with an up-to-date Chromium which doesn't break undo?

**Comment by lahwaacz** [comment]
Maybe I do: http://stackoverflow.com/a/10345596/4180822

The API for `document.execCommand` is still horribly incomplete, but at least seems to work fine in chromium. The only problem might be that undo reverts all consecutive inserts at once and not one by one, but in practice the web inspector won't be involved so there might be some events that separate the undo stack items.

And contrary to the comment on stackoverflow, redo works fine in chromium now.

**Comment by lahwaacz** [comment]
It seems that the `TextEvent` has been [removed](https://bugs.chromium.org/p/chromium/issues/detail?id=330662#c20) from chromium, so in the long term it would be better to use the new input events that should replace it. I don't know how though...

**Comment by The-Compiler** [comment]
Yeah, this seems to work: 👍 

```diff
diff --git a/qutebrowser/javascript/webelem.js b/qutebrowser/javascript/webelem.js
index 6e7209914..377a7575c 100644
--- a/qutebrowser/javascript/webelem.js
+++ b/qutebrowser/javascript/webelem.js
@@ -153,9 +153,8 @@ window._qutebrowser.webelem = (function() {
 
     funcs.insert_text = function(id, text) {
         var elem = elements[id];
-        var event = document.createEvent("TextEvent");
-        event.initTextEvent("textInput", true, true, null, text);
-        elem.dispatchEvent(event);
+        elem.focus();
+        document.execCommand("insertText", false, text);
     };
 
     funcs.element_at_pos = function(x, y) {
```

Pushing after I figured out why this broke without breaking any test.

**Comment by The-Compiler** [comment]
Oh, #2183 is why! 😆 

I want to try this on Qt 5.6 with QtWebEngine first though (for which we don't have a CI job yet...), but I don't have one installed and I'm on a train.

**Comment by The-Compiler** [comment]
I couldn't get Qt 5.6 set up on Arch (only got segfaults...), so until we have some more test jobs on Travis for Qt 5.6 and 5.7.1 (see #2083) I'm just hoping it works there.
