### ISSUE TITLE
QtWebKit import error on macOS 10.12.2 when installing via MacPorts + pip

### ISSUE THREAD

**Issue by nicoNaN** [qutebrowser/qutebrowser#2219]
After installing the dependencies for qutebrowser via MacPorts as per the instructions, I'm not able to run the command `sudo pip3.4 install qutebrowser`. However, `sudo pip install qutebrowser` does work, so I did that. `pip --version` gives `pip 9.0.1 from /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (python 3.4)`.

Here are the contents of `/usr/local/bin/qutebrowser`:
```
#!/opt/local/bin/python3.4

# -*- coding: utf-8 -*-
import re
import sys

from qutebrowser.qutebrowser import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

When running it, I get the following error:

<img width="532" alt="screen shot 2017-01-06 at 1 46 35 am" src="https://cloud.githubusercontent.com/assets/7397825/21709866/76560286-d3b2-11e6-8e0a-994d49badc24.png">

Strangely, `py34-pyqt5` installed no problem via MacPorts.

**Comment by The-Compiler** [comment]
Looks like MacPorts now also has a Qt built without QtWebKit. I have no idea about MacPorts and how to make it build QtWebKit though. FWIW there's a `qt5-qtwebkit` port, but probably you'd need to rebuild PyQt from source after that.

If we can't get this to work, it might be best to just remove the MacPorts installation steps 😆 

@posativ - you added them originally, do you have a clue?

**Comment by posativ** [comment]
I've added MacPorts based on information from IRC IIRC. No idea.

**Comment by nicoNaN** [comment]
@The-Compiler Tried installing the `qt5-qtwebkit` port and rebuilding PyQt from source via Ports. Still no luck - looks like I'll have to patient for a .dmg file :) Thanks for the suggestion anyway!

**Comment by The-Compiler** [comment]
Can you somehow build PyQt with `-verbose` (with `qt5-qtwebkit` installed) and show the output?

**Comment by The-Compiler** [comment]
Any update, @nicoNaN?
