### ISSUE TITLE
Qute cannot have spaces in quickmarks

### ISSUE THREAD

**Issue by Anaphory** [qutebrowser/qutebrowser#2225]
In the process of trying to create a quickmark for “Save to Zotero library” (the Javascript link  `javascript:var d=document,s=d.createElement("script");s.src="https://www.zotero.org/bookmarklet/loader.js";(d.body?d.body:d.documentElement).appendChild(s);void(0);`) I noticed that `:quickmark-add` accepts quoted arguments, but does not write them to the quickmark file in quoted format.
This means that (a) it is not possible to have persistent quickmarks to URLs containing spaces, but even worse (b) trying to create such a quickmark using `:quickmark-add` seems to work, but will be garbled after closing and re-opening the qute instance.

> $ qutebrowser --version
> 16:03:21 WARNING: /usr/lib/python3.6/site-packages/jinja2/filters.py:24: DeprecationWarning: Flags not at the start of the expression \w+(?u)
>   _word_re = re.compile(r'\w+(?u)')
> 
> 16:03:21 WARNING: /usr/lib/python3.6/site-packages/pygments/util.py:27: DeprecationWarning: Flags not at the start of the expression <(.+?)(\s.*?)?>.*?</ (truncated)
>   tag_re = re.compile(r'<(.+?)(\s.*?)?>.*?</.+?>(?uism)')
> 
> qutebrowser v0.9.0
> Git commit: 
> 
> CPython: 3.6.0
> Qt: 5.7.1
> PyQt: 5.7
> 
> sip: 4.18.1
> colorama: no
> pypeg2: 2.15
> jinja2: 2.8.1
> pygments: 2.1.3
> yaml: 3.12
> cssutils: no
> typing: yes
> PyQt5.QtWebEngineWidgets: no
> pdf.js: no
> Webkit: 538.1
> SSL: OpenSSL 1.0.2j  26 Sep 2016
> 
> Style: QFusionStyle
> Platform: Linux-4.8.13-1-ARCH-x86_64-with-arch, 64bit
> Frozen: False
> Imported from /usr/lib/python3.6/site-packages/qutebrowser
> OS Version: 
> 
> --- /etc/os-release ---
> NAME="Arch Linux"
> PRETTY_NAME="Arch Linux"
> ID=arch
> ID_LIKE=archlinux
> 
> Paths:
> config: /home/gereon/.config/qutebrowser
> data: /home/gereon/.local/share/qutebrowser
> system_data: /usr/share/qutebrowser
> cache: /home/gereon/.cache/qutebrowser
> download: /home/gereon/Downloads
> runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
I'm sorry for the late answer on this - the actual bug here is that URLs with spaces are allowed (at least with `:quickmark-add`). At least with `:quickmark-save`, spaces should be always converted to `%20` which works fine. Can you please try the same with your URL?

**Comment by The-Compiler** [comment]
Any update, @Anaphory?

**Comment by The-Compiler** [comment]
Closing this for now.
