### ISSUE TITLE
Regex search for completion?

### ISSUE THREAD

**Issue by JackofSpades707** [qutebrowser/qutebrowser#2232]
This is an enhancement/suggestion

Desired behavior :  

Bookmark : https://syntaxdb.com/ SyntaxDB - Programming Syntax Database [Code]
`:bookmark-load Code`
list the desired bookmark as one of the valid options

Actual behavior :

Instead, I would have to query the context of the URL, for example:
Bookmark : https://syntaxdb.com/ SyntaxDB - Programming Syntax Database [Code]
`:bookmark-load syntax`
Would result in displaying the bookmark correctly

I also noticed that searching through the bookmarks doesn't support regex, Ideally I would be able to search using regex for both the URL and Title fields of the bookmarks.

**Comment by The-Compiler** [comment]
See #1649 / #1654 (which unfortunately had some performance issues). Maybe #2144 will make this possible though.

As for regex-search, I'm not sure how useful that'd be - what would the usecase for that be? How would the user-interface look?

**Comment by The-Compiler** [comment]
ping? :wink:

**Comment by tuxlovesyou** [comment]
Still alive :)  I might be able to do some regex :)

~tuxlovesyou

**Comment by The-Compiler** [comment]
The question still is whether this is useful :wink:

I'm also not sure if it'll be possible to do this with the new sqlite based completion system @rcorre is working on. From [what it sounds like](http://stackoverflow.com/questions/5071601/how-do-i-use-regex-in-a-sqlite-query) it's not possible with sqlite without an extension module, and I'm not sure if that's even possible easily with Qt's sqlite stuff.

**Comment by tuxlovesyou** [comment]
Perhaps we wil have to do a more general query then perform the final regex in Python directly.

**Comment by The-Compiler** [comment]
Yeah, and without a very convincing usecase I'm going to say no to that, sorry. The completion stuff is complex enough as it is. Going to close this for now.

**Comment by rcorre** [comment]
It sounds like the actual issue you gave an example of is #1649, which should be possible with sql-based completion (coming soon to a PR near you!)

Searching by regex seems like overkill. I expect the `open`/`bookmark-load`/`quickmark-load` completion menus to be something I can quickly mash a few keys into and get what I want. I can't imagine wanting to build a regex by hand in there.

For the occasional need to perform a very specific search you could just grep the bookmark file on disk.
