### ISSUE TITLE
Webengine backend with smooth scrolling enabled is jittery while scrolling

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2233]
I [posted this issue](https://bugreports.qt.io/browse/QTBUG-58736) on the Qt bug tracker.

qutebrowser v0.9.0
Git commit: v0.8.0-2066-g282180e76 (2017-01-08 00:21:57 +0000)
Backend: Webengine

To replicate:
- Open Qutebrowser with `--backend webengine`
- Enable smooth scrolling (`:set ui smooth-scrolling true`)

- Scrolling [this example webpage](http://www.openwebdesign.org/design/6389/camp_gear_website/) will be very jittery and not smooth at all.
- However, if that webpage is [within a html frame](http://www.openwebdesign.org/viewdesign.phtml?id=6389), then scrolling the page is very smooth.

**Comment by pkill-nine** [comment]
Interestingly, I find on `qute://help/settings.html` that the jittering stops if I `:set tabs show never`. Other websites, like `store.steampowered.com` are also smoother but still jittery.

**Comment by The-Compiler** [comment]
You mentioned seeing the same in QupZilla, so closing this as a QtWebEngine issue.

**Comment by wezzynl** [comment]
I know that this issue is closed but I just noticed that when I do `:set tabs show never` and directly after that `:set tabs show always` the jitteryness is gone and stays gone. The jitteryness is very apparent as I have a very high key repeat rate. After the "trick", all is well. P.s. running latest git version and on MacOS Sierra 10.12.3.

**Comment by wezzynl** [comment]
Actually. That tab show never/always was just a coincidence. I can reliably get the scrolling to be non-jerky responsive by doing this:

1. Go to a website that has loads of content so you can scroll
2. Use j/k to move down/up
3. Observe it being really jerky and laggy
4. Hit `gg` to jump to the top of the page
5. Use j/k to move down/up
6. Observe smooth, non-laggy and responsive scrolling

**Comment by The-Compiler** [comment]
@wezzynl Can you please also check how things look in [QupZilla](https://qupzilla.com/) for you? They also have a `.dmg` for OS X available.

**Comment by wezzynl** [comment]
Sure. Just tried, QupZilla seems to work fine when using the *arrow* keys. Though I have to also mention that Qutebrowser also works fine when I use the arrow keys, it is only laggy and jerky when using j/k.

**Comment by The-Compiler** [comment]
That's weird... All `hjkl` does is faking arrow keys.

**Comment by dset0x** [comment]
I can observe this too. No difference between arrow keys / j/k / mouse scrolling from what I can tell.

Intel HD Graphics 4600
xf86-video-intel c28e62f94f15c9f5c4fb0744588f08ae18e4a9b5 [with dri,sna,udev,uxa]
X Server 1.18.4 [with glamor]

Ping @pkill-nine

**Comment by pkill-nine** [comment]
Interesting, I find a page spawned from right-clicking a page and clicking "view source" is completely smooth. If I run `:view-source` it's not smooth.

**Comment by The-Compiler** [comment]
@pkill-nine Those are two different source views (Chromium's vs. qutebrowser's one generated with pygments)

**Comment by The-Compiler** [comment]
As tests here seem to be inconclusive and this happens outside of qutebrowser as well, I'm closing this.

**Comment by braham-snyder** [comment]
With either tabs or the status bar visible (or both), I'm getting jumpy scrolling despite `smooth-scrolling` on Mac OS X (El Capitan) and Windows (10) using qutebrowser v0.11.0. 
 
On both platforms, with both the tabs and status bar invisible, scrolling is buttery-smooth. On OS X, QupZilla scrolls smoothly for me (though it has that slow-scrolling Qt bug fixed in 5.9; didn't test QupZilla on Windows, but I could if it helps anyone).

**Comment by The-Compiler** [comment]
#2822 might help - if not, I doubt there's anything qutebrowser can do.

**Comment by The-Compiler** [comment]
Turns out this happens due to QtWebEngine emitting a `scrollPositionChanged` multiple times per scroll with smooth scrolling, which causes all UI things potentially having a scroll position to be redrawn, taking a handful of milliseconds (multiple times).

This should probably help already, but I'd like someone with those problems to test it:

```diff
diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index 4de4bf26f..09df38e82 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -333,9 +333,10 @@ class WebEngineScroller(browsertab.AbstractScroller):
                 perc_y = min(100, round(100 / dy * jsret['px']['y']))
 
             self._at_bottom = math.ceil(jsret['px']['y']) >= dy
-            self._pos_perc = perc_x, perc_y
 
-            self.perc_changed.emit(*self._pos_perc)
+            if self._pos_perc != (perc_x, perc_y):
+                self._pos_perc = perc_x, perc_y
+                self.perc_changed.emit(*self._pos_perc)
 
         js_code = javascript.assemble('scroll', 'pos')
         self._tab.run_js_async(js_code, update_pos_cb)
```

Maybe some more optimizations are needed though.

**Comment by The-Compiler** [comment]
I pushed that now - I'd still be glad if someone could check the difference between `tabs.show` being always/never with that.

**Comment by The-Compiler** [comment]
I've had to revert this as it breaks various tests relying on it. I'll need to take a closer look first.

**Comment by The-Compiler** [comment]
I've now pushed various improvements (hopefully) for this to the latest master. Can someone check how things are now?

**Comment by ainola** [comment]
I'm using qutebrowser-git from the AUR and it appears to be much better, but still not as great as something like VimFX or Vimium. Here's a video of qutebrowser on the left, and Firefox 57+Vimium on the right.

https://drive.google.com/file/d/0BxL0EFrtSPDaVjdVTkJoV3J2YVU/view?usp=sharing
[scroll.mp4.zip](https://github.com/qutebrowser/qutebrowser/files/1403764/scroll.mp4.zip)

**Comment by braham-snyder** [comment]
On OS X El Capitan I see similar results on that same bootstrap site. On sites like Wikipedia, however (video attached, with comparisons to Firefox and Chrome), qutebrowser seems to scroll more smoothly (well, at least usually -- e.g., the final scroll in my attached video is a bit choppy).

[qb_scroll_wikipedia.mov.zip](https://github.com/qutebrowser/qutebrowser/files/1404464/qb_scroll_wikipedia.mov.zip)

**Comment by The-Compiler** [comment]
https://codereview.qt-project.org/#/c/209352/ might also help here - I don't think there's much more qutebrowser can do, so I'm closing this.
