### ISSUE TITLE
Caret mode vs. caret selection mode after search

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#2258]
**Issue (tl;dr):** After searching (`/foo<cr>`) and entering caret mode (`v`), when I move left/right/down/up, I'm actually in caret *selection* mode, even though it says I'm in caret mode. I have to hit `v` another time to actually enter real caret mode.

**Typical use case:** I'm looking at an academic article which is behind a paywall, so I want to yank the DOI number in order to feed it to my custom university search. The DOI text normally looks something like "DOI: XX.XXX/XXXX-XXXXX" or "http://dx.doi.org/XX.XXX/XXXX-XXXXX", etc. It differs from site to site, and often it's not immediately visible to the eye, so searching directly for the number isn't a solution.

**Example** of what I want to do: select "123456789" from the following text...

>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, DOI 123456789, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.

...using the following steps.

1. `/doi<cr>` -- put cursor at the beginning "DOI"
2. `v` -- enter caret mode (not caret selection mode!)
3. `w` -- move to beginning of DOI number
4. `v` -- enter caret *selection* mode
5. `e` -- select DOI number
6. `y` -- yank it

What actually happens, however, is that after step 2, I'm already in caret *selection* mode, even though qutebrowser says "caret mode". So, when I execute step 3, I've actually selected all of "DOI 123456789" instead of just "123456789".

If I press `v` a *second* time (after step 2), then I really am in caret mode, and can continue on with step 3. (Specifically, this works best: `/doi<cr>vvhwvey`.)

**Solution:** I'm assuming this is a bug (if not, please point out what I'm missing!). I can think of two solutions.

1. Enter caret mode (not caret selection mode) after `/foo<cr>v`. (my preference)
2. Change the status bar text to indicate that `/foo<cr>v` puts you in caret *selection* mode, not caret mode.

Thoughts?

**Comment by brianbuccola** [comment]
After reading [#1402](https://github.com/The-Compiler/qutebrowser/issues/1402), it seems that for `/foo<cr>v`, selecting "foo" and entering caret selection mode is the correct/expected behavior.

More generally, selecting text -- either by search or manually with the mouse -- and then hitting `v` puts you into caret selection mode, so that moving around selects more/less text.

Still, I would think that in these cases, the status bar should say "caret selection mode", not "caret mode", no?

**Comment by The-Compiler** [comment]
I think it'd be better to be in caret selection mode (because there is already a selection), but I agree the statusbar text is a bug.

**Comment by user202729** [comment]
It appears to work fine now? (at least for QtWebEngine)
