### ISSUE TITLE
Cannot hide wayland decorations.

### ISSUE THREAD

**Issue by ghost** [qutebrowser/qutebrowser#2267]
Currently setting hide-wayland-decoration to true has no effect.I haven't been using qutebrowser on wayland for a while I'm just trying this now.

**Comment by The-Compiler** [comment]
So even after a restart you still see decorations? On what Qt version?

**Comment by throwaway217** [comment]
Even after restarting the whole system. On 4.8.

**Comment by The-Compiler** [comment]
On what Qt5 version? See `:open qute:version` or `qutebrowser --version` (there's a reason it's in the issue template! :wink:)

**Comment by throwaway217** [comment]
```
% qutebrowser --version
qutebrowser v0.9.1
Git commit:

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.7.1

sip: 4.19
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017
```

I apologize, I am somewhat tired and wrote 4.8

**Comment by The-Compiler** [comment]
Okay - I wonder if this broke in Qt 5.8 somehow, but I don't have a Qt 5.8 ready right now to test with. The changes in Qt seem pretty minimal...

Does anyone else see this happen too on wayland and Qt 5.8? @tidux maybe?

**Comment by tidux** [comment]
I've got Qt 5.8, but my work system doesn't have Wayland.  I'll check on my 
box that does tonight.

**Comment by tidux** [comment]
Confirmed under Qt 5.8 and Sway (Wayland compositor) on Arch with a fresh rebuild from git master.
![2017-01-31-095621_swaygrab](https://cloud.githubusercontent.com/assets/1330562/22477624/a4bd8cdc-e79b-11e6-8f9d-bbb6fbf03eb4.png)

On a related note, the Wayland backend seems to have a different scale for font settings in the UI elements - I had to drop my _monospace font sizes from 8pt to 6pt to get the same pixel sizes compared to running under X11 on the same display.

**Comment by The-Compiler** [comment]
Hmm, odd. If you do  `QT_WAYLAND_DISABLE_WINDOWDECORATION=1 python3 -c "from PyQt5.QtWidgets import QApplication; from PyQt5.QtWebEngineWidgets import QWebEngineView; a = QApplication([]); v = QWebEngineView(); v.show(); a.exec_()"`, does that have a window decoration? If yes, what about `QT_WAYLAND_DISABLE_WINDOWDECORATION=1 python3 -c "from PyQt5.QtWidgets import QApplication, QWidget; a = QApplication([]); v = QWidget(); v.show(); a.exec_()"` ?

**Comment by tidux** [comment]
Those both cause the Wayland compositor to segfault and crash.

**Comment by The-Compiler** [comment]
Err... fun. I'll try to set up wayland and try this out (is there something like Xephyr for it, so I can run wayland in a window under X?), but I'm currently busy with more important stuff, so it's going to take a while.

**Comment by tidux** [comment]
IIRC you can run Weston (the reference Wayland compositor) as a window 
under X11 for testing purposes.

**Comment by The-Compiler** [comment]
So I tried running `weston-launch -- --modules=xwayland.so` in a tty, but no matter what I do, I can't get qutebrowser (or any X application) to run, it just can't open the display. Help? :wink:

**Comment by The-Compiler** [comment]
I also tried `sway` FWIW - it seems to work via xwayland there (without any borders), and not start when I `unset DISPLAY`.

**Comment by tidux** [comment]
XWayland is for X in Wayland, not the reverse.

On February 4, 2017 2:55:19 PM PST, Florian Bruhin <notifications@github.com> wrote:
>So I tried running `weston-launch -- --modules=xwayland.so` in a tty,
>but no matter what I do, I can't get qutebrowser (or any X application)
>to run, it just can't open the display. Help? :wink:
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/The-Compiler/qutebrowser/issues/2267#issuecomment-277484198

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
I'm aware - I did run wayland from a separate tty because it seemed easier to me, but I can't get qutebrowser to start there.

**Comment by The-Compiler** [comment]
I just tried this again after noticing a weston upgrade - however, I still can't get qutebrowser to run inside Weston or sway except via XWayland. There I'd expect to get a window decoration (by Weston), so I'm really not sure how to reproduce this.

**Comment by tidux** [comment]
You need to set an environment variable and launch it from a terminal.
`export QT_QPA_PLATFORM=wayland-egl` if on metal or `=wayland-eglfs` if running your compositor under X.

**Comment by The-Compiler** [comment]
Thanks, that was the missing bit!

It seems like we need to set `QT_WAYLAND_DISABLE_WINDOWDECORATION=1` very early now (before the `QApplication` is created), I think it wasn't that way before Qt 5.8.

So this will have to wait for after the new config (#499), then it might be possible to get values from the config that early.

**Comment by tidux** [comment]
I can confirm that it does obey the environment variable.  Exporting `QT_WAYLAND_DISABLE_WINDOWDECORATION=1` in ~/.zshenv and restarting my compositor worked.

**Comment by tidux** [comment]
Update: I've had better luck with setting `QT_QPA_PLATFORM=wayland` rather than `=wayland-egl`, possibly change test env to work with this.

**Comment by tidux** [comment]
Update: I've had better luck with setting `QT_QPA_PLATFORM=wayland` rather than `=wayland-egl`, possibly change test env to work with this.

**Comment by The-Compiler** [comment]
My Qt wayland library is broken somehow - @tidux, could you try how things look with the latest `master`? If I'm guessing right, the setting will still not work there, but it will with this patch:

```diff
diff --git a/qutebrowser/app.py b/qutebrowser/app.py
index 3f24af721..72ed0ee31 100644
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
@@ -471,10 +471,6 @@ def _init_modules(args, crash_handler):
     objreg.register('cache', diskcache)
 
     log.init.debug("Misc initialization...")
-    if config.val.window.hide_wayland_decoration:
-        os.environ['QT_WAYLAND_DISABLE_WINDOWDECORATION'] = '1'
-    else:
-        os.environ.pop('QT_WAYLAND_DISABLE_WINDOWDECORATION', None)
     macros.init()
     # Init backend-specific stuff
     browsertab.init()
diff --git a/qutebrowser/config/config.py b/qutebrowser/config/config.py
index 89eb4fad3..8e21ee63d 100644
--- a/qutebrowser/config/config.py
+++ b/qutebrowser/config/config.py
@@ -19,6 +19,7 @@
 
 """Configuration storage and config-related utilities."""
 
+import os
 import copy
 import contextlib
 import functools
@@ -689,6 +690,12 @@ def early_init():
 
     configfiles.init()
 
+    # Apply settings which need to be set before QApplication exists
+    if val.window.hide_wayland_decoration:
+        os.environ['QT_WAYLAND_DISABLE_WINDOWDECORATION'] = '1'
+    else:
+        os.environ.pop('QT_WAYLAND_DISABLE_WINDOWDECORATION', None)
+
 
 def late_init(save_manager):
     """Initialize the rest of the config after the QApplication is created."""
```

**Comment by tidux** [comment]
I don't think it's your Qt library that's broken, I think it's that patch to Qutebrowser.  Applying those changes resulted in a segfault and crash.

**Comment by The-Compiler** [comment]
I had to rebuild `qt5-wayland`, now I can test this as well. It seems to work fine in Weston, but indeed segfault in sway. Setting `QT_WAYLAND_DISABLE_WINDOWDECORATION` manually before starting seems to work... 😕

**Comment by The-Compiler** [comment]
@tidux Hmm, are you sure this change is to blame? Without the patch, when opening a few terminals so the qutebrowser window is small enough, and then doing `:restart` a few times, I can reproduce this crash too.
