### ISSUE TITLE
When opening a file with the file browser, try to open it with an installed application instead of prompting to download it

### ISSUE THREAD

**Issue by Elronnd** [qutebrowser/qutebrowser#2280]

**Comment by The-Compiler** [comment]
You'll need to elaborate - are you saying you're pressing `ctrl-x` and you get a second qutebrowser window trying to download it? If so, your `xdg-open` is misconfigured and launching qutebrowser on that file.

If it's not that: `--verbose` :wink:

**Comment by Elronnd** [comment]
No, I go to `file:///home/elronnd/`, and click on `somefile.ext`, and the download menu would pop up.  See [here](http://0x0.st/W90.png)

**Comment by pkill-nine** [comment]
So do you want it to automatically open when navigating to a local file?

**Comment by lahwaacz** [comment]
This is probably the same issue as #1252.

**Comment by The-Compiler** [comment]
Yep, closing as duplicate.
