### ISSUE TITLE
Document chrome:// URLs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2292]
Somewhere (like the contributing file) we should document which chrome:// URLs qutebrowser supports with QtWebEngine.

Seems like those work:

chrome://appcache-internals/
chrome://blob-internals/
chrome://gpu/
chrome://histograms/
chrome://indexeddb-internals/
chrome://media-internals/
chrome://network-errors/
chrome://serviceworker-internals/
chrome://webrtc-internals/
chrome://crash/
chrome://kill/
chrome://hang/ (?)
chrome://gpuclean/ (?)
chrome://gpucrash/ (?)
chrome://gpuhang/ (?)
chrome://ppapiflashcrash/ (?)
chrome://ppapiflashhang/ (?)

**Comment by MikeinRealLife** [comment]
I'll test and add these
