### ISSUE TITLE
png is blurry when not zooming

### ISSUE THREAD

**Issue by Herny64** [qutebrowser/qutebrowser#2297]
Hi,

While zooming into a png i can see every pixel in detail which is ok.
But when i stop zooming the pixels are blurry.
its like a blurr filter on the picture and the filter is deactivated while zooming.
i dunno if this is a feature or a bug
qutebrowser v0.9.1

greetings

**Comment by The-Compiler** [comment]
Those kind of things are handled by the backend. If you're on Archlinux (or something else packaging QtWebEngine), try switching to QtWebEngine or QtWebKit-NG.
