### ISSUE TITLE
Update text field upon saving in editor (without needing to exit editor)

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#2307]
This is extremely profitable for websites that offer live fancy updates, such as http://mathb.in, or various stackexchange websites that offer online rendering/preview of LaTeX texts. 

Currently, what I do with those websites is this:

  1. I enter insert mode in a text field to post something.
  2. I hit Ctrl-i to fire vim.
  3. I write my things, which often includes fancy LaTeX symboks, such as `$$\int_{-\infty}^{+\infty}\big(\Pr(A=x)\Pr(B=x)\big)$$` (try how beautiful it looks in http://mathb.in).
  4. But all that is just in vim, so I cannot see the beautiful preview of what I have done in their websites (plus vim can't show nice previews either!). Therefore I always have to `:wq` in order to simply let the text area in that page to update, so that the website presents the overview.
  5. Then, after the site shows the preview, I re-open vim again by hitting Ctrl-i and continue editting.
  6. Repeat steps from 3 to 5. 

Is there any way to let Qutebrowser update the text field by simply writing it in vim? So as soon as I hit `:w` the website gets the text and therefore presents to me the live preview immediately, without having me to quit and re-open vim every time I want to see the preview?

**Comment by The-Compiler** [comment]
This should be possible using [QFileSystemWatcher](http://doc.qt.io/qt-5/qfilesystemwatcher.html) which uses inotify.
