### ISSUE TITLE
QtWebEngine does not redraw after waking up from suspend

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2310]
Each time I wake my system from suspend, the qutebrowser window (using the QtWebEngine backend) looks like this:
[![screenshot-2017-01-18@12:53:15.png](https://s27.postimg.org/o2p580d2b/screenshot_2017_01_18_12_53_15.png)](https://postimg.org/image/j41mth99b/)

Switching desktops does not help, I have to either go fullscreen or switch tabs or reload the page. Also opening the completion (sub)window does not make a difference.

The desktop is i3 + compton (compton-git-0.1_beta2.86.gb7f43ee-1 from the AUR) in the background and nvidia-375.26-6 drivers. Running on Qt 5.8, but the same issue was even on 5.7, so I guess it's about time to report this. I don't remember exactly when I started to use the webengine backend (maybe November or December), but I have the issue as far as I can remember, so it's not a regression.

**Comment by The-Compiler** [comment]
Now that's what I call modern art! 😉 

This is most likely an issue with QtWebEngine or your graphic driver though.

Can you try without compton? Do you see the same in Chromium? Can you also test with [QupZilla](https://qupzilla.com/) (the 2.x series) please?

**Comment by pkill-nine** [comment]
I also have this issue (though it's not a problem for me, just a minor quirk)

**Comment by lahwaacz** [comment]
I haven't seen this behaviour in other browsers before, but now that I placed 3 other browsers (Chromium, `./scripts/testbrowser.py --webengine` and QupZilla) on the same desktop, it happened to them too. The only difference is that in the other browsers focusing a window triggers the redraw, which is probably why I haven't noticed it before. Killing compton doesn't make a difference.

**Comment by The-Compiler** [comment]
So `testbrowser.py` also redraws when focused?

@pkill-nine on Nvidia graphics too?

**Comment by lahwaacz** [comment]
> So testbrowser.py also redraws when focused?

Yes.

**Comment by pkill-nine** [comment]
@The-Compiler Yes I am on Nvidia, using the proprietary graphics card driver

**Comment by lahwaacz** [comment]
I've also noticed that if there is a blinking cursor or some non-static element visible on the page, then even qutebrowser redraws the window correctly.

**Comment by The-Compiler** [comment]
@lahwaacz Did anything change about this with Qt 5.9.1?

**Comment by lahwaacz** [comment]
No, still the same with Qt 5.9.1...

**Comment by The-Compiler** [comment]
Just stumbled upon this again - I doubt there's anything qutebrowser can do here. Any chance it improved with newer Qt (or graphic driver) versions?

**Comment by toofar** [comment]
The picture in the OP gone but if it is like this:
![suspend_grafics](https://user-images.githubusercontent.com/7419144/71569643-6d958d00-2b35-11ea-8d25-9ab6ea0ba7fd.png)
Then it is still happens on Qt 5.13.2 (nvidia, no compositor) although I swear it looked different on 5.11, like bigger squares with patterns in them. Same behaviour though. Scrolling the page up and down makes it re-draw fine.

**Comment by lahwaacz** [comment]
I didn't have this problem since I moved to Wayland.

**Comment by The-Compiler** [comment]
I don't think there's anything qutebrowser can do here - perhaps it has gone away with newer Qt versions, though?
