### ISSUE TITLE
[webengine] qutebrowser no longer opens links that 'open in a new tab' with standard hint.

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#2311]
Probably a regression in #2273, but I'm not 100% sure. Let me know if you want a bisect.

This bug is on the current master (6e85b738972e589866bb161c4d3d5b73b6b0109f).

Paste this HTML into a file:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Open New Tab</title>
</head>
<body>
<a href="http://qutebrowser.org" target="_blank">Open New Tab</a>
</body>
</html>
```

And open it with qutebrowser. 

Clicking on the link with the mouse opens a new link, as expected.
Running `:hint all tab` and clicking the link opens it in a new tab (as expected)
Running `:hint all` and clicking the link does not open the link anywhere (which is the error).

I'm not sure what the expected behavior would be. The old behavior would open the link in a new tab, but I think that opening the link in the current tab would be acceptable as well. It would be nice to open something though :smile:

This problem is also present in reddit, when 'open links in a new tab' is selected (although I'm not sure if thats the same bug). 

Thanks again for all the time you put into qutebrowser, it's really amazing! :tada: 

```
qutebrowser v0.9.1
Git commit: v0.9.0-240-g6e85b73 (2017-02-09 23:58:06 +0100)
Backend: QtWebEngine

CPython: 3.4.5
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19
colorama: 0.3.3
pypeg2: 2.15
jinja2: 2.9.4
pygments: 2.1.3
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: no
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.6-gentoo-r1-x86_64-Intel-R-_Core-TM-_i7-6700HQ_CPU_@_2.60GHz-with-gentoo-2.3, 64bit
Frozen: False
Imported from /usr/lib64/python3.4/site-packages/qutebrowser
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID="Gentoo"

--- /etc/os-release ---
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"

--- /etc/gentoo-release ---
Gentoo Base System release 2.3

Paths:
cache: /home/jay/.cache/qutebrowser
download: /home/jay/Downloads
system_data: /home/jay/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
config: /home/jay/.config/qutebrowser
data: /home/jay/.local/share/qutebrowser
```

**Comment by lahwaacz** [comment]
I was just about to report the same issue, which happens for me on DuckDuckGo, which also has an option to open search results in a new tab/window.

**Comment by lahwaacz** [comment]
The log says `Clicking via JS click()` in both cases though, so I guess `elem.click()` in JS somehow does not work with `target="_blank"` links...

**Comment by lahwaacz** [comment]
`elem.click()` works fine in Chromium - and in qutebrowser too, provided that `content.javascript-can-open-windows-automatically` is set to `True`. But I think this feature should really not depend on this option... We could detect if the link has the `target="_blank"` attribute and do `_click_href` in that case.

**Comment by jgkamat** [comment]
I don't know too much about html/js, but there might be other ways of 'opening in a new tab' other than just target="_blank". The _click_href would work in this case though (although idk if that would open the link in a current or a new tab).

**Comment by lahwaacz** [comment]
There might be some javascript handlers for actual click events, but if they attempt to open a new tab, with `content.javascript-can-open-windows-automatically` disabled that won't work anyway. I'm not aware of an other way not involving javascript besides `target="_blank"`, but of course we could extend the detection in the future.

**Comment by The-Compiler** [comment]
I tried temporarily setting the setting to `true` before running the JS, but that doesn't seem to help... now qutebrowser falls back on `_click_js` on `target=_blank` links. It suffers from the issues from #2273, but I don't know what I could do about that...

**Comment by The-Compiler** [comment]
You mentioned `_click_href`, which is probably a better idea - whoops!

**Comment by The-Compiler** [comment]
Things should be back to normal now - if you still see some behavior change, please let me know ASAP as I hope to release v0.10.0 soon.

**Comment by jgkamat** [comment]
@The-Compiler 
I still see this issue on reddit when the 'open in new tab' option is set (I'd rather that not get into 10.0). 

I have no idea how to get a simple example like the _blank links, but I think i'ts using javascript somehow.

To test it out, select this 'open in new tab link' in the preferences page, after creating a reddit account:
![2017-02-17-011645_802x300_scrot](https://cloud.githubusercontent.com/assets/4349709/23054590/ce0f5fbe-f4ae-11e6-9f6b-a96496f43cae.png)

And then try to open a link on your frontpage with the hint key (hinting in a new tab works, just like above).

Sorry for not being to provide any more information, I honstly could not understand how the links were being opened in a new tab :cry:

**Comment by The-Compiler** [comment]
Interestingly it works on the second time:

```
14:58:19 DEBUG    webelem    webelem:click:401 Clicking <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a class="title may-blank loggedin outbound" data-event-action="title" href="https://www.youtube.com/watch?v=nccryZOcrUg" tabindex="1" data-href-url="https://www.youtube.com/watch?v=nccryZOcrUg" data-outbound-url="https://out.reddit.com/t3_5ulrgf?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DnccryZOcrUg&amp;token=AQAAtg-nWJR8VXW0qYoMKt2TZ3_Q0IvkAI9HYkgppm1OyEr91asY&amp;app_name=reddit.com" data-outbound-expiration="1487343542000" rel="">Bill Gates: the robot that takes your job should pay tax…'> with click_target ClickTarget.normal, force_event False
14:58:19 DEBUG    webelem    webelem:click:415 Clicking via JS click()
```

```
14:58:21 DEBUG    webelem    webelem:click:401 Clicking <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a class="title may-blank loggedin outbound" data-event-action="title" href="https://www.youtube.com/watch?v=nccryZOcrUg" tabindex="1" data-href-url="https://www.youtube.com/watch?v=nccryZOcrUg" data-outbound-url="https://out.reddit.com/t3_5ulrgf?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DnccryZOcrUg&amp;token=AQAAtg-nWJR8VXW0qYoMKt2TZ3_Q0IvkAI9HYkgppm1OyEr91asY&amp;app_name=reddit.com" data-outbound-expiration="1487343542000" rel="noreferrer" target="_blank">Bill Gates: the robot that tak…'> with click_target ClickTarget.normal, force_event False
14:58:21 DEBUG    webelem    webelem:click:410 target _blank -> Clicking via href
```

I don't get why it uses JS click( the first time, at least yet :wink:

**Comment by The-Compiler** [comment]
So what happens here is that reddit inserts the `target="_blank"` in a javascript click handler, i.e. I don't know about it the first time it's clicked, and thus the JS `click()` is used... Sometimes I hate the web.

**Comment by The-Compiler** [comment]
I now found out how to temporarily allow JS to open windows and used that with `click()`. Let me know how that goes! So far it looks pretty good.

**Comment by jgkamat** [comment]
LGTM! It works fine for me for every case I try, thanks! :tada: 
I'll be running this version, so I'll let you know if I see any other issues.

Thanks again for spending so much time on this! :smile:
