### ISSUE TITLE
Clipboard, ctrl-c and selection

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#2316]
It seems that (with webengine at least) selecting text does not insert it to the clipboard. One has to press 'Ctrl-C' to achieve that behaviour.
Is this a Qt thing? Is it configurable?
Clipboard-on-select is a common behaviour in the Unix world, it would be nice if that'd be configurable.

**Comment by The-Compiler** [comment]
I've never seen *anything* put something into clipboard on select. Do you have an example?

Everything I know puts things into primary selection, like QtWebEngine/qutebrowser does too.

**Comment by Ambrevar** [comment]
Damn, I got confused again: swap `clipboard` for `primary selection` in the OP. :/

**Comment by Ambrevar** [comment]
Hmmm, never mind, seems like it's working. Something fishy is happening on my system...
