### ISSUE TITLE
calc doens't work with viewheight

### ISSUE THREAD

**Issue by chino23** [qutebrowser/qutebrowser#2324]
using calc(100vh -100px) styles are not rendered at all in qutebrowser.

As far as I remember, this used to be a very old bug in webkit and has been fixed.

Isn't the webkit up to date or what is the issue here?

**Comment by The-Compiler** [comment]
As you mention, this is something done by the backends and not something qutebrowser can fix in its code.

> Isn't the webkit up to date or what is the issue here?

That depends - on what OS/distribution are you on, and how did you install qutebrowser?

**Comment by chino23** [comment]
I'm on Gentoo, just emerged qutebrowser. 

Currently compiling qtwebengine to try using that instead, if it fixes the issues.

**Comment by The-Compiler** [comment]
> Currently compiling qtwebengine to try using that instead, if it fixes the issues.

That's one alternative, though I recommend using qutebrowser from git instead until I get to releasing v0.10.0

The other one would be to switch to [the new QtWebKit](https://github.com/annulen/webkit/wiki), though I don't know if Gentoo packages that.

**Comment by chino23** [comment]
the git version has QtWebEngine included?

**Comment by The-Compiler** [comment]
It does not - but it works better with QtWebEngine (especially on Qt 5.8) than v0.9.1 does.

**Comment by chino23** [comment]
ok thanks, i'll give it a shot. Love this browser btw, great job, please keep it up :)

**Comment by chino23** [comment]
oh and yeah, we can compile straight from git on gentoo using 9999 ebuilds which is neat

**Comment by chino23** [comment]
Just to let you know, I've compiled the qutebrowser from git, and also Qt and PyQt 5.7.1
Writing this with --backend webengine, working really well. 

Oh, and the initial problem I opened this bug for is also fixed. Loving it, just deleted firefox :)
