### ISSUE TITLE
clipboard integration broken under wayland and xwayland

### ISSUE THREAD

**Issue by tidux** [qutebrowser/qutebrowser#2325]
Qutebrowser is not passing data from its own clipboard to the Wayland compositor's (Sway's) clipboard, so I can't paste copied data from Qutebrowser into a terminal or any other window.  The only workaround is to paste into another XWayland window like Emacs or an X11-based terminal.  No such workaround exists for the true-Wayland backend.

Output of `qutebrowser --version` follows.
```
qutebrowser v0.9.1
Git commit: v0.9.0-270-gd60e365e3 (2017-02-12 01:06:56 +0100)
Backend: QtWebKit

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.8-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

Paths:
config: /home/tidux/.config/qutebrowser
data: /home/tidux/.local/share/qutebrowser
system_data: /home/tidux/.local/share/qutebrowser
cache: /home/tidux/.cache/qutebrowser
download: /home/tidux/Downloads
runtime: /run/user/1000/qutebrowser
```

**Comment by The-Compiler** [comment]
qutebrowser doesn't really do much clipboard-handling, so chances are you'll see this behavior with any Qt5 based application. 

Can you please try with this?

```python
from PyQt5.QtWidgets import QApplication, QTextEdit
a = QApplication([])
e = QTextEdit()
e.show()
a.exec_()
```

**Comment by tidux** [comment]
I can copy and paste between Qt5 windows doing that (the demo code and a Qutebrowser instance) but can't paste to a Wayland-native Gtk3 window (Termite).

**Comment by The-Compiler** [comment]
This definitely looks like a Qt rather than a qutebrowser issue then.

Can you please open an issue in the [Qt bugtracker](https://bugreports.qt.io/) and link it here?

**Comment by tidux** [comment]
So I just tested this with urxvt instead of a gtk3 application as the non-Qt application on Sway and it works.  It appears there are some known issues with gtk3 under Sway.
