### ISSUE TITLE
Confirm page leave dialogue UI bug

### ISSUE THREAD

**Issue by parchd-1** [qutebrowser/qutebrowser#2326]
The confirm leave dialogues that some webpages show do not fit in with the qutebrowser UI, and their text is not visible.

Run for an example:
https://jsfiddle.net/r2tznftL/

### Version info
qutebrowser v0.9.1
Git commit: v0.9.0-295-g01db59ff3 (2017-02-19 13:15:15 +0100)
Backend: QtWebEngine

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.8-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
OS Version: 

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

**Comment by The-Compiler** [comment]
See [QTBUG-58673](https://bugreports.qt.io/browse/QTBUG-58673). With Qt 5.9 at least some text will show up, but there's still no way for qutebrowser to override it.

**Comment by The-Compiler** [comment]
Submitted a change to Qt to make this possible now: https://codereview.qt-project.org/#/c/187881/

**Comment by The-Compiler** [comment]
A revised version of the change [was merged](http://code.qt.io/cgit/qt/qtwebengine.git/commit/?h=5.9&id=57fee86eb2756a2f102e2bbeb16a443b84a17e01) into Qt now, so this should work automagically with Qt 5.9 now.
