### ISSUE TITLE
Frame support in QtWebEngine

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2329]
Currently various actions (insert mode on click, hints, etc.) don't work inside frames/iframes.

**Comment by The-Compiler** [comment]
We might need [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) for frames to communicate with each other...

**Comment by CmdrSharp** [comment]
Any idea when this might be implemented? I unfortunately don't have the necessary know-how to do a PR here - but the application I was hoping to use this browser for does make heavy use of frames

**Comment by The-Compiler** [comment]
I'm still busy with other things for some while and I usually don't do ETAs, sorry. Unfortunately this is quite complex to solve, as QtWebEngine has no API to run JavaScript in a frame.

**Comment by CmdrSharp** [comment]
That's fine, didn't mean to stress it. I heard something about this working as expected when using the regular WebKit engine - any chance we can get this on the Windows release? The flag for using it didn't work on Windows it seems.

**Comment by The-Compiler** [comment]
You'd need to get https://github.com/annulen/webkit/ to run on Windows with a custom Qt install, and then build PyQt from source against that install. It should be possible (but probably a bit cumbersome, like building things which aren't C# is in general on Windows), but I've never tried. It's not something I have the time for to do with every Qt release, I'm afraid.

**Comment by CmdrSharp** [comment]
Understood - though if it's too cumbersome for you, you can see my position (given much less experience with these languages).

Just as a final question - you don't know of ANY workaround for this issue? Trying to get this to work in an application called Service Now that we use extensively, and Qute Browser seems to be the only option out there for Windows users (apart from the Chrome plugins that I've found varying success with), so I don't want to leave any stone unturned!

**Comment by The-Compiler** [comment]
No, sorry - nothing other than that, or using the mouse (and telling people to stop using frames :P)

**Comment by edrex** [comment]
Just hit this with @sandstorm-io. But they have a legitimate security sandboxing reason to use frames >D

**Comment by edrex** [comment]
So, cause some of the instantiation currently done for the root frame to run per-frame? This postMessage sounds hard unless the command interface is already built for RPC. Where would be some good starting points in the code/tests?

**Comment by edrex** [comment]
From [doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide](http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html#qwebframe-has-been-merged-into-qwebenginepage)

> In Qt WebEngine, frame handling has been merged into the QWebEnginePage class. All child frames are now considered part of the content, and only accessible through JavaScript. Methods of the QWebFrame class, such as load() are now available directly through the QWebEnginePage itself.

Is there something about QtWebEngine vs QtWebKit that forces using postMessage instead of going through Python?

**Comment by edrex** [comment]
How do you load code into the child frames? I guess you would have to bootstrap them with some javascript in the main frame?

**Comment by The-Compiler** [comment]
> So, cause some of the instantiation currently done for the root frame to run per-frame?

I don't understand what you meant here.

> This postMessage sounds hard unless the command interface is already built for RPC.

Right, it's probably not going to be easy, and it might require setting up a bi-directional async communication channel between Python and JS, using [QtWebChannel](http://doc.qt.io/qt-5/qtwebchannel-index.html), as we probably can't just return e.g. matching elements to Python synchronously anymore.

> Where would be some good starting points in the code/tests?

I don't know - I really haven't looked into this yet.

> Ah, QtWebEngine prevents you from accessing the inner frames without using Javascript handlers.

Right.

> How do you load code into the child frames? I guess you would have to bootstrap them with some javascript in the main frame?

You can use a [QWebEngineScript](https://doc.qt.io/qt-5/qwebenginescript.html) with [setRunOnSubFrames](https://doc.qt.io/qt-5/qwebenginescript.html#setRunsOnSubFrames), similarly to how qutebrowser initializes JS stuff already:

https://github.com/qutebrowser/qutebrowser/blob/43aa7423abb931ddcbccc51411f6a8a16bf056b5/qutebrowser/browser/webengine/webenginetab.py#L533-L548

**Comment by jgkamat** [comment]
I tried playing at this for a bit, and I came up with something that sort of half-worked (for hints at least). It seemed to pick up hints fine (and clicking them worked) in iframes, but all the hints were positioned relative to the root page, rather than the iframe, so it was hard to figure out which hints correspond to what. I think that someone might be able to build on this to make a proper implementation. (If @The-Compiler thinks this is an acceptible approach, I could try finishing this up). I think that we can fix the offsets by adding the iframe position to the `client_rect` object before serializing it.

```
diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index 89ba958a7..6468a451b 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -554,6 +554,7 @@ class WebEngineTab(browsertab.AbstractTab):
 
         page = self._widget.page()
         script.setWorldId(QWebEngineScript.ApplicationWorld)
+        script.setRunsOnSubFrames(True)
 
         # FIXME:qtwebengine  what about runsOnSubFrames?
         page.scripts().insert(script)
diff --git a/qutebrowser/javascript/webelem.js b/qutebrowser/javascript/webelem.js
index b5fd936b2..e55cf3a6a 100644
--- a/qutebrowser/javascript/webelem.js
+++ b/qutebrowser/javascript/webelem.js
@@ -60,7 +60,7 @@ window._qutebrowser.webelem = (function() {
                 // nothing to do, caret_position is already null
             } else {
                 // not the droid we're looking for
-                throw err;
+                // throw err;
             }
         }
 
@@ -163,6 +163,7 @@ window._qutebrowser.webelem = (function() {
 
     funcs.find_css = (selector, only_visible) => {
         const elems = document.querySelectorAll(selector);
+        const subelem_frames = document.getElementsByTagName("iframe")
         const out = [];
 
         for (let i = 0; i < elems.length; ++i) {
@@ -171,6 +172,15 @@ window._qutebrowser.webelem = (function() {
             }
         }
 
+        for (let i = 0; i < subelem_frames.length; i++) {
+            let subelems = subelem_frames[i].contentDocument.querySelectorAll(selector);
+            for (let j = 0; j < subelems.length; ++j) {
+                if (!only_visible || is_visible(subelems[j])) {
+                    out.push(serialize_elem(subelems[j]));
+                }
+            }
+        }
+
         return out;
     };
 
```

**Comment by The-Compiler** [comment]
@jgkamat Hmm, it's interesting that that works. Does it work for cross-origin iframes? How is this different from using [window.frames](https://developer.mozilla.org/en-US/docs/Web/API/Window/frames)?

**Comment by jgkamat** [comment]
(re-hashing from IRC) Yup, you're right, I get:
`VM41:254 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://jsfiddle.net" from accessing a frame with origin "http://fiddle.jshell.net". Protocols, domains, and ports must match.`

on this site http://jsfiddle.net/westonruter/6mSuK/. However, I also discovered that vimium (and I'm guessing the other js vim plugins as well) suffer from this, so I think this is acceptable.

windows.frames is the proper way to do this, and it works perfectly with it as well (although it's still crashing on cross-origin frames). Here's an updated patch. I'll try to take this for now, but if someone has js experience and more time, I would be happy to pass it off to them :smile: 

```
 diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index 89ba958a7..6468a451b 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -554,6 +554,7 @@ class WebEngineTab(browsertab.AbstractTab):
 
         page = self._widget.page()
         script.setWorldId(QWebEngineScript.ApplicationWorld)
+        script.setRunsOnSubFrames(True)
 
         # FIXME:qtwebengine  what about runsOnSubFrames?
         page.scripts().insert(script)
diff --git a/qutebrowser/javascript/webelem.js b/qutebrowser/javascript/webelem.js
index b5fd936b2..31ad58e3c 100644
--- a/qutebrowser/javascript/webelem.js
+++ b/qutebrowser/javascript/webelem.js
@@ -60,7 +60,7 @@ window._qutebrowser.webelem = (function() {
                 // nothing to do, caret_position is already null
             } else {
                 // not the droid we're looking for
-                throw err;
+                // throw err;
             }
         }
 
@@ -163,6 +163,7 @@ window._qutebrowser.webelem = (function() {
 
     funcs.find_css = (selector, only_visible) => {
         const elems = document.querySelectorAll(selector);
+        const subelem_frames = window.frames
         const out = [];
 
         for (let i = 0; i < elems.length; ++i) {
@@ -171,6 +172,15 @@ window._qutebrowser.webelem = (function() {
             }
         }
 
+        for (let i = 0; i < subelem_frames.length; i++) {
+            let subelems = subelem_frames[i].document.querySelectorAll(selector);
+            for (let j = 0; j < subelems.length; ++j) {
+                if (!only_visible || is_visible(subelems[j])) {
+                    out.push(serialize_elem(subelems[j]));
+                }
+            }
+        }
+
         return out;
     };
 
```

**Comment by The-Compiler** [comment]
This works now for same-origin frames thanks to @jgkamat! I opened #3569 to track what's still missing.
