### ISSUE TITLE
qute:history improvements

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2333]
From #2281:

> The history page looks great, but IMO one major problem is that browsing the history shortly after midnight splits the links into multiple pages, while links from both days might be related to each other so the split hinders readability of the continuous session. After all, the day ends when I go to sleep, not at 0:00.
>
>There are multiple ways to solve this:
>- Display links from the last 24 hours, i.e. most of the time a subset of 2 days.
>- Set the split point to e.g. 3:00 instead of 0:00 (should be configurable).
>- Examine the history to detect large gaps (inactivity/sleeping periods).
>- Make the number of days per page configurable, via config and links on the page as a nice shortcut to temporarily override the config. See e.g. [MediaWiki's options](https://wiki.archlinux.org/index.php/Special:RecentChanges) for inspiration.
>- Instead of one page per day listing, "extend" the page with links from past days in place. I.e. the URLs would be like `qute://history/?from=2017-02-01&to=2017-02-11`. The page could be reconstructed from scratch for each request or, if you are brave enough, some javascript code could do dynamic loading.
>
>My favourite would be probably a combination of the last two.

---

> I think this [errors with an invalid date] should be a message shown directly in the browser as users might modify the URL manually and get no feedback on errors this way.

cc @lahwaacz @imransobir

**Comment by imransobir** [comment]
I think a combination of displaying links in the last 24 hours, examining history to detect gaps, and dynamically loading more items would be best. Sort of like Chromium's history page. But doing this using the current history_dict would be cumbersome. We should probably wait for #1765 so that history is accessible via SQL.

One more thing, is it possible to get data from a qute endpoint using javascript?

**Comment by The-Compiler** [comment]
> One more thing, is it possible to get data from a qute endpoint using javascript?

There are two different approaches:

- Returning data from another `qute:history/data?...` URL (e.g. as json) and using that from JS (also see #2332)
- Using [Qt WebChannel](http://doc.qt.io/qt-5/qtwebchannel-index.html) which allows to transparently use C++ (and thus Python) QObjects from Javascript - though it's more difficult to set up, and only supported since Qt 5.4 IIRC (we're still supporting 5.3 and 5.2 at the moment too).

**Comment by rcorre** [comment]
Sounds like this wil be resolved if I use `LIMIT` instead of bounding by `atime` in #2295?

**Comment by lahwaacz** [comment]
This was mostly fixed in #2361 already, but the remaining bit is outlined in https://github.com/qutebrowser/qutebrowser/pull/2361#issuecomment-284345769. It's about detecting large gaps of inactivity to improve the visual representation of the list, so I don't think SQL can help with that.

**Comment by imransobir** [comment]
Nevertheless, we should convert to using `LIMIT`, history_data will be much simpler this way.

**Comment by The-Compiler** [comment]
I can't think of a good algorithm for smarter history gap detection which is actually simple enough - so I'm closing this one.
