### ISSUE TITLE
QtWebEngine by default

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2335]
QtWebEngine is almost ready to get the new default engine for qutebrowser. A quick overview:

- [x] OS X: QtWebEngine will be the default in the next release (mainly because I couldn't build a running QtWebKit release since some time)
- [x] Windows: ~~Still needs some work to build binaries with QtWebEngine and switch to PyInstaller - see #1004, #2187, 687f28845361b7fb84142fb63fc461fabc679acf, 9a638b2dba1db56cc152280fa6be0f972aeaf261~~ QtWebEngine will be the default in v0.11.0
- [x] Linux: Many people already use it, and it'd be ready to switch over - but I'd like to wait for Qt 5.9 (scheduled for May) as QtWebEngine had quite a few regressions on 5.8. It's already used when QtWebKit is unavailable though.

**Comment by SirCmpwn** [comment]
#2368 should block this on Linux

**Comment by The-Compiler** [comment]
I did some first test builds for Windows with QtWebEngine - I'd appreciate some help with testing them! See https://github.com/qutebrowser/qutebrowser/issues/1004#issuecomment-294230533

**Comment by The-Compiler** [comment]
Situations where we should probably fall back to QtWebKit by default to not break things:

- Nouveau is used (#2386) - we can force software rendering there (as soon as there is a config option for that), but it might be preferrable performance-wise to use QtWebKit if the user has QtWebKit-NG installed
- `QT_QPA_PLATFORM=wayland-egl` or `QT_QPA_PLATFORM=wayland` is set
- Qt < 5.7.1 is used
- Maybe if Qt == 5.8.0 is used and QtWebKit-NG is available, as that was a pretty buggy release?

**Comment by lahwaacz** [comment]
The Nouveau issue is probably #2368 :wink: 

As for Qt 5.8.0, the bugs are (mostly?) fixed now, so I don't see the point. Also there is no guarantee that future Qt releases will be bug-free and switching the default backend for a specific release would be very confusing for users who used the default QtWebEngine backend previously. I think that the default has to be monotonic with regard to various releases and workarounds (i.e. no back and forth switching). Users will adapt eventually, problems/confusion will be there only around the changes so the fewer changes there are, the easier the adaptation will be.

**Comment by The-Compiler** [comment]
Note that the reason 5.8 works so well on Archlinux is that I poked the maintainer tp [backport](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-webengine#n52) various fixes for QtWebEngine.

With an unpatched 5.8 (which could happen in the future on e.g. Gentoo, which is lagging behind quite a bit with Qt updates), there are a lot of annoying issues which aren't present in 5.7.1 and fixed in 5.9:

- If you open links which use `window.open` and then close the tab in which you clicked the links, all those tabs get grey and unusable
- You can't type special characters with dead keys or compose keys (which can be pretty bad for non-US people)
- You can't use a special IME (which is pretty bad for people typing e.g. Chinese/Japanese)
- Dropdown menus (e.g. `<select>` elements) have the wrong window type and automatically disappear (i.e. are unusable) with most tiling window managers.

I feel like those are just too severe to use QtWebEngine as default on an unpatched Qt 5.8 (and Arch which patches it will quickly update to 5.9 anyways). Note this won't affect people using `--backend webengine` now, only people who are currently on QtWebKit anyways.

The reason I still want to switch to QtWebEngine on Qt 5.7.1 (and not only starting with 5.9) is that that's what Debian Stretch and Ubuntu 17.04 (Zesty) use, and it's unaffected by all those bugs.

**Comment by NoctuaNivalis** [comment]
> If you open links which use window.open and then close the tab in which you clicked the links, all those tabs get grey and unusable

I thought this was just me :open_mouth:

**Comment by lahwaacz** [comment]
That sounds reasonable, so I'm convinced - it's apparently me who needs to adapt. In any case, it might be worth to detect changes of the _current default_ backend (i.e. when qutebrowser is started without `--backend`) and show an informational pop-up or something like that when it changes. This would cover the cases when Debian or Ubuntu deploy Qt 5.8.0, or when you already have Qt 5.8.0 and install QtWebKit-NG later due to some other package, or when there is some seriously buggy Qt release after 5.9.

**Comment by viniciusarcanjo** [comment]
that'd be totally awesome The-Compiler. +1 for this backend state.

**Comment by The-Compiler** [comment]
Note to self: At that point I should also request that [qutebrowser-qtwebengine](https://aur.archlinux.org/packages/qutebrowser-qtwebengine/) in the AUR (which only changes the dependencies) gets deleted.

**Comment by The-Compiler** [comment]
I have a new plan how to handle it:

- The `auto` option for `backend` doesn't exist anymore.
- `backend = webengine` is the default
- When there's a problem (nouveau, wayland, missing dependencies), the user gets an error explaining that the default changed to QtWebEngine, with buttons to switch to software rendering (with nouveau) or switch the backend setting to `webkit`.

Thoughts?

**Comment by guillermohs9** [comment]
Just now I was searching for info about this. I'd like to use QtWebEngine as default, and was about to set up the wrapper script or try the `qutebrowser-qtwebengine` package, but I'm excited to see it as default in the official package.

**Comment by The-Compiler** [comment]
@guillermohs9 You can do `:set backend webengine` with `qutebrowser-git`. All `qutebrowser-qtwebengine` does is adjust the dependencies, it doesn't force using QtWebEngine.

**Comment by guillermohs9** [comment]
@The-Compiler Thanks! I installed the latest version a couple of minutes ago and was importing some of my settings. I'll try that!

**Comment by The-Compiler** [comment]
I now pushed this to the `webengine-by-default` branch, it'd be nice if some people could try it out, as it's kind of hard to test. Interesting scenarios:

- Only QtWebKit available
- Only QtWebEngine available
- neither available
- Running on Wayland
- Running with Nouveau graphics
- Only old/legacy QtWebKit available

In all of those cases, you should get a nice error message suggesting how to solve the issue.

**Comment by The-Compiler** [comment]
I tested it some more and it seems like it works. QtWebEngine is now the default! 🎉
