### ISSUE TITLE
WebEngine fails on XML header with "iso-8859-15" encoding

### ISSUE THREAD

**Issue by ayekat** [qutebrowser/qutebrowser#2337]
When opening [this page](http://isa.epfl.ch/imoniteur_ISAP/!itffichecours.htm?ww_i_matiere=1770703&ww_x_anneeAcad=2016-2017&ww_i_section=249847&ww_i_niveau=&ww_c_langue=en), I get the following error message in a red box:

> **This page contains the following errors:**
>
>     error on line 1 at column 43: Unsupported encoding iso-8859-15
>
> **Below is a rendering of the page up to the first error.**

Looking at the page source, the problematic first line seems to be this:

    <?xml version="1.0" encoding="iso-8859-15" standalone="no"?>
                                              ^ column 43

This error only happens with the WebEngine backend, but not with WebKit.

### Version Info

```
qutebrowser v0.9.1
Git commit: v0.9.0-321-g9b07a9f77 (2017-02-21 08:11:11 +0100)
Backend: QtWebEngine

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.4.50-1-lts-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/ayekat/.local/run/qutebrowser/default/config
data: /home/ayekat/.local/run/qutebrowser/default/data
system_data: /home/ayekat/.local/run/qutebrowser/default/data
cache: /home/ayekat/.local/run/qutebrowser/default/cache
download: /home/ayekat/.local/run/qutebrowser/default/download
runtime: /home/ayekat/.local/run/qutebrowser/default/runtime
```

**Comment by fiete201** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=28748
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=662231

Just as a quick result of google research. cant look into it deeper now.
But I can reproduce it here and will try to look deeper into it latest next week

Best regards
Fritz

**Comment by The-Compiler** [comment]
[Reported to QtWebEngine](https://bugreports.qt.io/browse/QTBUG-59094) now. Thanks for the report and thanks @fiete201 for digging into it!
