### ISSUE TITLE
Clean up tox.ini

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2341]
We currently don't use [factors](http://tox.readthedocs.io/en/latest/config.html#generating-environments-conditional-settings) in our [tox.ini](https://github.com/qutebrowser/qutebrowser/blob/master/tox.ini) so we have quite some duplication in it.

The reason we don't is to be allow Ubuntu Trusty (14.04) users with [tox 1.6](http://packages.ubuntu.com/search?keywords=python-tox&searchon=names&suite=trusty&section=all) to do `tox -e mkenv`.

~~We should instead have a separate config file for the `mkenv` environment (with that as default), so people can do `tox -c misc/tox-mkenv.ini` or so.~~

We can now rely on tox 2.3.1 - Fedora 26, Ubuntu 16.04 and some others use 2.3.1, but we can drop everything that's older.

**Comment by The-Compiler** [comment]
While doing this, we should probably also add e.g. a `py36-pyqt` environment which just takes the latest available PyQt.

**Comment by The-Compiler** [comment]
`py35-mkvenv` and `py36-mkvenv` (which use `/usr/bin/python3.5` or `3.6`) would probably be useful for people who have a Python 3.4 as /usr/bin/python3 (*cough* Gentoo *cough*)

**Comment by The-Compiler** [comment]
Some more ideas of useful things:

- Making `tox -e mkvenv` install PyQt from PyPI by default, and having a `tox -e mkvenv-local` or so instead.
- Having versions of the pylint/etc. environments without a PyPI PyQt, see #3339.

**Comment by ryan-farley** [comment]
At first glance, there doesn't seem to be any support for negative conditionals. Would it be reasonable to have more explicit names to keep pytest in a single env section? For example, py36-pyqtlink-nocov in place of the current py36.

**Comment by The-Compiler** [comment]
Yeah, looks like that hasn't happened yet unfortunately... I'd rather have *some* duplication (but at least the pyXY part handled with factors) but somewhat readable environment names. `-pyqtlink` or so is probably okay (because it's nicely consistent with `-pyqt59` and others), but `-nocov` sounds rather inconvenient.

**Comment by The-Compiler** [comment]
Looks good now - merged with some changes on top:

- 2c2d7fe7349cfef6272e3db9d1a9a52878bde88b copy-pastes the `pylint` commands, as apparently older tox releases shipped in some distributions were unable to substitute them with `{posargs}` in them.
- 7ef64c0f87adecb51017327832e17ef64ea1049e reads `$PYTHON` for all environments (except the `pyXY` ones).

Thanks!

**Comment by The-Compiler** [comment]
I haven't done the part making `tox -e mkvenv`  install from PyPI, but the rest is done. Let's keep it at that for now, as the behavior change might confuse people.
