### ISSUE TITLE
Add custom js for specific domain

### ISSUE THREAD

**Issue by justUmen** [qutebrowser/qutebrowser#2344]
I'm looking for a way to add some javascript code to a specific domain.

Or is there a way to load custom js for all domains ? (like "user-stylesheet" does for css)

I'm waiting for [#135](https://github.com/qutebrowser/qutebrowser/issues/135) for multiple css for individual domains. If this can work for js as well it would be great.

**Comment by The-Compiler** [comment]
I'm merging this into #341, and #499 is relevant for the per-domain part too. Alternatively, #1155 would make this possible too.

> I'm waiting for #135 for multiple css for individual domains.

That issue is not about that. It's about being able to split an user-stylesheet into multiple files. #499 is relevant for per-domain settings.
