### ISSUE TITLE
(feature request) intuitive behaviour of download prompt path completion

### ISSUE THREAD

**Issue by swalladge** [qutebrowser/qutebrowser#2345]
The current behaviour of completion in the download prompt is a bit unintuitive - pressing tab starts cycling through the subdirectories of the current directory shown, even if you have started typing a sub directory name.

I propose that the behaviour should be such that sub directories are filtered as you type, and pressing tab for completion should cycle through the filtered subdirectories.

**Comment by The-Compiler** [comment]
As mentioned in IRC, I thought there was a bug for that already, but I can't find it.

**Comment by swalladge** [comment]
Ah I finally found the issue that covers it: #2104 

Closing this as a duplicate then.
