### ISSUE TITLE
Keybinding (or command) to alter current URL (or previous command) in a specified way

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#2346]
I've been trying to use Duck Duck Go as my primary search engine, but sometimes Google's results are better. So, what happens is that I'll first search for *foo* on DDG...

    :open foo ->
    https://duckduckgo.com/?q=foo

...and then I'll redo the same search on Google, usually by pressing `:<C-p>` to go back to my previous command, then moving leftward until my cursor is before `foo`, and then adding the [DDG bang](https://duckduckgo.com/bang) `!g`...

    :open !g foo ->
    https://encrypted.google.com/search?hl=en&q=foo

...which is rather tedious.

**Question:** Is there an easy way to automate this process --- either with a keybinding/command that adds `!g` to the previous command, or with a keybinding /command that adds `!g` to the DDG URL (in the right spot, of course)?

I know that I can `edit-url` manually with my editor, but is there some way of automatically transforming

    https://duckduckgo.com/?q=foo

into

    https://duckduckgo.com/?q=!g+foo

? (Note that appending `!g` to the very end of the URL is not a general solution because DDG often adds extra stuff like `&xy=bar`).

**Comment by The-Compiler** [comment]
You can write an [userscript](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc) which reads `$QUTE_URL`, does whatever you want with it, and then writes `:open $new_url` to `$QUTE_FIFO`.

**Comment by brianbuccola** [comment]
Amazing! This simple bash script seems to do the trick:

    #!/bin/bash

    new_url=$(echo "${QUTE_URL}" | sed 's/?q=/?q=!g+/')

    echo "open ${new_url}" >> "${QUTE_FIFO}"

Thanks!

**Comment by tuxlovesyou** [comment]
Hats off to sir compiler for making this possible!
