### ISSUE TITLE
Cannot sign into Atlassian & reCaptcha does not load

### ISSUE THREAD

**Issue by mmlac** [qutebrowser/qutebrowser#2348]
Usually logins work, but Atlassian always just says "invalid password" (even though the password is correct, pasting the same pw into firefox on the same page works fine). After a few attempts it tries to load reCaptcha but that just errors out and I don't see any logs about what happened when running qutebrowser --loglevel info --debug.
Is there a JS debug console like Chrome / Firefox have to look at what happened to HTML / CSS requests and js console output / errors? I saw a config field for a file, but where is it? Nothing in /var/log/**

Screenshot:
[![2017-02-23 14_23_22-.png](https://s8.postimg.org/9r09ez745/2017_02_23_14_23_22.png)](https://postimg.org/image/joba81ept/)

$ qutebrowser --versio
qutebrowser v0.9.1
Git commit: 

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.7.1

sip: 4.19
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.8-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

**Comment by The-Compiler** [comment]
Those kinds of issues are usually related to the backend - either switch to the `qt5-webkit-ng` package, or install `qt5-webengine` and either start with `--backend webengine` or uninstall `qt5-webkit`.

You'll need to switch to `qutebrowser-git` though - however, I'll release v0.10.0 very soon (today if everything goes well).
