### ISSUE TITLE
Bookmarks are sorted differently in qute:bookmarks and completion

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2354]
qute:bookmarks sorts by title/name, but completion by the (easily customizable) order from the files where they are stored. I would expect these to have the same order for easier orientation.

**Comment by The-Compiler** [comment]
cc @imransobir

**Comment by imransobir** [comment]
@lahwaacz I don't understand what you mean.

**Comment by lahwaacz** [comment]
If I type `:open` and a space, completion window for the URL pops up. It has 3 sections: quickmarks, bookmarks, history. I meant that quickmarks and bookmarks in the completion window are sorted differently from the qute:bookmarks page.

**Comment by jgkamat** [comment]
:+1:, I sort my bookmarks in a specific order (for completion), so it would be nice to have them be the same in `qute:bookmarks`

**Comment by imransobir** [comment]
Ok, will do this in a few days.
