### ISSUE TITLE
backend configuration option

### ISSUE THREAD

**Issue by shaggytwodope** [qutebrowser/qutebrowser#2357]
Is using the alternate backend (webengine) only supported by -- switches or can it be set via config? I can't seem to find anything pointing me to this info. Apologies if I've overlooked anything.

**Comment by The-Compiler** [comment]
Right - it's basically a chicken-egg-problem, and I don't want to add more complexity to the current config system. Another solution is to remove QtWebKit, then qutebrowser (starting with v0.10.0) will automatically use QtWebEngine.
