### ISSUE TITLE
Do not select the content of a search field

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#2359]
With the upgrade from 0.9 to 0.10 the contend of a search field gets selected on focusing. Example: ![scr](http://i.imgur.com/vU8lbn7.png)
I can't find the way to disable this new thing. Is it possible to keep the content not selected as it used to?
I'm on QtWebKit backend.

**Comment by The-Compiler** [comment]
I can't reproduce this (with QtWebKit-NG though) on https://github.com/qutebrowser/qutebrowser/issues, but I can [on this page](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_form_submit) (not with QtWebEngine).

qutebrowser does not select anything there, but it uses a different way of selecting the field (using `focus()` in JS) which apparently somehow causes this.

**Comment by sudo-nice** [comment]
Thank you!
