### ISSUE TITLE
Disable the automatic "Run :adblock-update" info message on startup

### ISSUE THREAD

**Issue by spcmd** [qutebrowser/qutebrowser#2364]
Every time I start qutebrowser I got a message:

> Run :adblock-update to get adblock lists

I've set `host-blocking-enabled = false` in the config, because I have my own hosts file in /etc + I have privoxy.

I couldn't find a way to disable this message. I searched in the config, in the man page, in the help, here through the issues... Am I missing something? :confused:

**Comment by The-Compiler** [comment]
A `touch ~/.local/share/qutebrowser/blocked-hosts` should make it go away, but I agree it should be hidden when host blocking is disabled.

**Comment by spcmd** [comment]
I created the file, it's okay now, thanks.
