### ISSUE TITLE
QtWebEngine and Nouveau

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2368]
QtWebEngine currently just crashes with Nouveau: https://bugreports.qt.io/browse/QTBUG-41242

Maybe we can find out an user is using Nouveau and force software rendering (set `LIBGL_ALWAYS_SOFTWARE=1`), similar to this patch:

```diff
Index: qtwebengine-opensource-src-5.6.1/src/core/web_engine_context.cpp
===================================================================
--- qtwebengine-opensource-src-5.6.1.orig/src/core/web_engine_context.cpp
+++ qtwebengine-opensource-src-5.6.1/src/core/web_engine_context.cpp
@@ -79,6 +79,8 @@
 #include <QFileInfo>
 #include <QGuiApplication>
 #include <QOpenGLContext>
+#include <QOpenGLFunctions>
+#include <QOffscreenSurface>
 #include <QStringList>
 #include <QVector>
 #include <qpa/qplatformnativeinterface.h>
@@ -144,6 +146,37 @@ bool usingQtQuick2DRenderer()
     return device == QLatin1String("softwarecontext");
 }
 
+QString openGLVendor()
+{
+    QString vendor;
+
+    QOpenGLContext *oldContext = QOpenGLContext::currentContext();
+    QSurface *oldSurface = 0;
+    if (oldContext)
+        oldSurface = oldContext->surface();
+
+    QScopedPointer<QOffscreenSurface> surface( new QOffscreenSurface );
+    surface->create();
+    QOpenGLContext context;
+    if (!context.create()) {
+        qDebug() << "Error creating openGL context";
+    }
+    else if (!context.makeCurrent(surface.data())) {
+        qDebug() << "Error making openGL context current context";
+    } else {
+        const GLubyte *p;
+        QOpenGLFunctions *f = context.functions();
+        if ((p = f->glGetString(GL_VENDOR)))
+            vendor = QString::fromLatin1(reinterpret_cast<const char *>(p));
+    }
+
+    context.doneCurrent();
+    if (oldContext && oldSurface)
+        oldContext->makeCurrent(oldSurface);
+
+    return vendor;
+}
+
 } // namespace
 
 void WebEngineContext::destroyBrowserContext()
@@ -261,7 +294,20 @@ WebEngineContext::WebEngineContext()
 
     GLContextHelper::initialize();
 
-    if (usingANGLE() || usingSoftwareDynamicGL() || usingQtQuick2DRenderer()) {
+    bool disableGpu = qEnvironmentVariableIsSet("QT_WEBENGINE_DISABLE_GPU");
+
+    if (!qEnvironmentVariableIsSet("QT_WEBENGINE_DISABLE_NOUVEAU_WORKAROUND") && openGLVendor() == QStringLiteral("nouveau"))
+    {
+        qWarning() << "Nouveau openGL driver detected. Qt WebEngine will disable usage of the GPU.\n"
+                      "Please consider using the propietary NVIDIA drivers.\n\n"
+                      "Alternatively, you can set the QT_WEBENGINE_DISABLE_NOUVEAU_WORKAROUND\n"
+                      "environment variable before running this application, but this is \n"
+                      "not recommended since this usually causes applications to crash as\n"
+                      "Nouveau openGL drivers don't support multithreaded rendering";
+        disableGpu = true;
+    }
+
+    if (usingANGLE() || usingSoftwareDynamicGL() || usingQtQuick2DRenderer() || disableGpu) {
         parsedCommandLine->AppendSwitch(switches::kDisableGpu);
     } else {
         const char *glType = 0;
```

Also see:

http://python.6.x6.nabble.com/How-to-get-access-to-QOpenGLFunctions-glGetString-from-PyQt-td5207636.html

**Comment by The-Compiler** [comment]
I'm able to get `nouveau` by doing:

```python
import sys
from PyQt5 import QtWidgets, QtOpenGL, QtGui

app = QtWidgets.QApplication(sys.argv)
glw = QtOpenGL.QGLWidget()
glw.glInit()
ctx = QtGui.QOpenGLContext.currentContext()
sf = QtGui.QSurfaceFormat()
vp = QtGui.QOpenGLVersionProfile(sf)
vp.setVersion(2, 0)
vf = ctx.versionFunctions(vp)
print(vf.glGetString(vf.GL_VENDOR))
```

the problem is that this requires a QApplication. Unfortunately, at that point, it seems too late to set `LIBGL_ALWAYS_SOFTWARE=1`. `QTWEBENGINE_CHROMIUM_FLAGS=--use-gl=0` doesn't seem to do anything at all.

Right now, with some restructuring of `earlyinit` and when the backend is set, all we could do is to force QtWebKit when Nouveau is used. I guess we could also set something like `software-rendering = 1` in the `state` file and ask the user to restart... Or wait for the new config system and set it in the config.

**Comment by SirCmpwn** [comment]
You can just read /proc/modules and look for nouveau

**Comment by The-Compiler** [comment]
I doubt it - e.g. with hybrid graphic laptops (or in other scenarios too), I'd expect the module to be loaded but not in use.

**Comment by SirCmpwn** [comment]
bumblebee loads/unloads the relevant module(s)

**Comment by The-Compiler** [comment]
There's a basic error displayed now, which is already much better than crashing. I'd like to add "Switch to QtWebKit backend" and "Use software rendering" buttons with the new config though.

**Comment by The-Compiler** [comment]
Setting `QT_XCB_FORCE_SOFTWARE_OPENGL` ([code](https://github.com/qt/qtbase/blob/v5.9.1/src/platformsupport/glxconvenience/qglxconvenience.cpp#L127-L159)) or passing `--disable-gpu` to Chromium is probably a better solution than `LIBGL_ALWAYS_SOFTWARE`, as it won't disable OpenGL for stuff started from qutebrowser.

**Comment by The-Compiler** [comment]
I now pushed a nicer fix for this to the `webengine-by-default` branch, it'd be nice if some people could try it out, as I don't have Nouveau hardware.

You should get a dialog asking you what to do, and the "force software rendering" button should correctly restart qutebrowser with software rendering turned on.

**Comment by intelfx** [comment]
@SirCmpwn 

> bumblebee loads/unloads the relevant module(s)

I'm just passing by, but this is a very wrong assumption — modern nouveau does not rely on bumblebee and needs to be always loaded for things like power management to work. So, indeed, checking modules is wrong here.

**Comment by SirCmpwn** [comment]
Thanks for clarifying. I don't really know much about how bumblebee works, I just read through some of the source code when I made that assertion.
