### ISSUE TITLE
Don't seem to be able to use a single rgba value for hints.bg 

### ISSUE THREAD

**Issue by panditarevolution** [qutebrowser/qutebrowser#2370]
I'm using qutebrowser v0.9.1 on Fedora 25.

I tried to change the hints.bg color to a single color with transparency, using rgba:

The default works:
    qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 247, 133, 0.8), stop:1 rgba(255, 197, 66, 0.8))

The following does not work and the browser complaints:
    rgba(255, 247, 133, 0.8)

However removing the transparency part works again:
    rgba(255, 247, 133, 1.0)

To achieve a single color with transparency I had to use:
    qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 247, 133, 0.8), stop:1 rgba(255, 247, 133, 0.8))

Is this a bug or a feature or me doing something I shouldn't? :)

**Comment by The-Compiler** [comment]
Looking at the regexes used to validate it:

```python
    num = r'[0-9]{1,3}%?'

    color_func_regexes = [
        r'rgb\({num},\s*{num},\s*{num}\)'.format(num=num),
        r'rgba\({num},\s*{num},\s*{num},\s*{num}\)'.format(num=num),
        r'hsv\({num},\s*{num},\s*{num}\)'.format(num=num),
        r'hsva\({num},\s*{num},\s*{num},\s*{num}\)'.format(num=num),
        r'qlineargradient\(.*\)',
        r'qradialgradient\(.*\)',
        r'qconicalgradient\(.*\)',
    ]
```

This seems like a bug.

**Comment by The-Compiler** [comment]
I relaxed that validation now - you should be able to use values between 0 and 255 instead of floats instead though, if you want to stay on v0.10.0 (or percentages according to the Qt docs, but looking at Qt's code, I'm not sure whether that actually works)
