### ISSUE TITLE
Close message-info/error/warning with Escape key

### ISSUE THREAD

**Issue by spcmd** [qutebrowser/qutebrowser#2371]
Can somehow the messages be closed before timeout? Is there a command for this? I'd like to close them with the Escape key. I know I can set the timeout in the config but I wouldn't like to set it very low value _by default_ (for obvious reasons).

**Comment by The-Compiler** [comment]
Currently there's no option for that.

**Comment by pkill-nine** [comment]
@spcmd there's a `clear-messages` command now, so run `:bind --force <escape> clear-messages ;; clear-keychain ;; search ;; fullscreen --leave` and the escape key will close messages before timeout.

**Comment by spcmd** [comment]
@pkill-nine Works fine, thank you! :+1:
