### ISSUE TITLE
Question about save files dialog.

### ISSUE THREAD

**Issue by Lourens-Rich** [qutebrowser/qutebrowser#2372]
Thank all for this project, but i have a question. Before, we have a original Qt file saver dialog and it was very comfortable for me. I could write full path, used auto complition (in the file name area), and alt + arrow for faster directory change. Today, using mouse for dir chosing are more comfortable becouse it is very faster than use keyboard. For vim-like browser it is like a joke! How i can disable it and if i can't please think about it in the future. Sorry for my terrible English.

**Comment by The-Compiler** [comment]
What do you mean with "before"? Either way, this is a duplicate of #1365.
