### ISSUE TITLE
Pop-ups don't appear

### ISSUE THREAD

**Issue by hughwilliams94** [qutebrowser/qutebrowser#2373]
qutebrowser version -.10.0, webengine backend on Ubuntu 16.04

While trying to use a mopidy web extension for Spotify (Mopidy-Iris) an authentication process constantly fails, complaining that  pop-ups are blocked. If I try the same process in Chromium a pop up window similar to OAuth appears allowing me to authenticate with Spotify. Anyway that I can enable pop-ups in Qutebrowser and authenticate?

**Comment by The-Compiler** [comment]
qutebrowser itself doesn't do any popup-blocking, so it might be something in QtWebEngine causing this.

Can you reproduce it with `--temp-basedir`? If so, can you please reproduce it and do `:report`? (Make sure no tokens or anything are in the log though).

**Comment by hughwilliams94** [comment]
I have just tried with those options enabled and the error was still reported by the website. I have sent over the debugging logs. In chromium I do have to enable the popup in the address bar.

**Comment by The-Compiler** [comment]
Whoops, I somehow forgot about this - does `:set content javascript-can-open-windows-automatically true` help?

**Comment by hughwilliams94** [comment]
This did exactly what I was looking for, sorry i hadn't noticed this option in the settings!

**Comment by The-Compiler** [comment]
Glad to hear! I also opened #2375 to have better (more intuitive) popup blocking, but it's not really a priority.
