### ISSUE TITLE
content->javascript-can-access-clipboard option does not work

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2374]
The `content->javascript-can-access-clipboard` is set to false, i.e. even with If I run `qutebrowser --temp-basedir`. Its description in the completion window says "Whether JavaScript programs can read or write to the clipboard". But when I go to `https://github.com/qutebrowser/qutebrowser`, click on the "Clone or download" button and then on the icon next to the URL (which has tooltip "Copy to clipboard"), I get a "Copied!" message - and indeed that's what happened, the URL landed in the clipboard. Same behaviour with both backends.

Also, I've recently encountered some shitty page which closed all my tabs but itself, which might indicate that `content->javascript-can-close-windows` has similar problem, but I haven't reproduced that again yet.

**Comment by The-Compiler** [comment]
This actually seems to work fine with QtWebKit - while it displays "Copied!", it doesn't actually change the clipboard's content. With [clipboard.js](https://clipboardjs.com/) it marks the text and shows "press ctrl-c to copy" instead. Can you confirm that you get the same behavior?

I can reproduce this with QtWebEngine though, even with this minimal example:

```python
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineSettings
from PyQt5.QtWebKitWidgets import QWebView
from PyQt5.QtWebKit import QWebSettings
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QUrl

app = QApplication([])

QWebSettings.globalSettings().setAttribute(QWebSettings.JavascriptCanAccessClipboard, False)
QWebEngineSettings.globalSettings().setAttribute(QWebEngineSettings.JavascriptCanAccessClipboard, False)

wkv = QWebView()
wkv.setWindowTitle("WebKit")
wkv.show()
wkv.load(QUrl('https://clipboardjs.com/'))

wev = QWebEngineView()
wev.setWindowTitle("WebEngine")
wev.show()
wev.load(QUrl('https://clipboardjs.com/'))

app.exec_()
```

So that seems like a QtWebEngine bug...

**Comment by lahwaacz** [comment]
Hmm, indeed, I get the same behaviour as you with webkit. The "Copied!" message must have confused me there.

**Comment by The-Compiler** [comment]
It looks like Chromium [always allows this if it's resulting from an user input](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/editing/commands/EditorCommand.cpp?l=530&rcl=d2af662cd05d4c85b9d4936b4bb02ef67a952418), so I'll adjust the setting description accordingly.

**Comment by The-Compiler** [comment]
Also submitted a change to Qt now: https://codereview.qt-project.org/#/c/186891/
