### ISSUE TITLE
Fullscreen behavior in unrelated tabs with fullscreen video

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2379]
If I go e.g. to [this page](https://channel9.msdn.com/Events/GoingNative/2013/Interactive-Panel-Ask-Us-Anything), play the video and click the "go to fullscreen" button on it, and then press my browser shortcut for tab navigation, then I end up in some unusual fullscreen mode: the status bar is always hidden and the tabbar disappears a while after switching a tab. Using my window manager shortcut for switching fullscreen does not affect the layout of the widgets inside qutebrowser. It happens with webengine, in webkit I'm not allowed to switch tabs while a video is fullscreen. My window manager is i3.

**Comment by The-Compiler** [comment]
I'm not sure what's the bug here - this is indeed the behavior when a video requests to be fullscreened.

**Comment by lahwaacz** [comment]
Is it intended to hide the tabbar and statusbar on other tabs I switch to from a fullscreen video?

**Comment by The-Compiler** [comment]
Currently the status/tabbar just hide when any tab has requested to enter fullscreen, and show again if no tab is fullscreen.

I guess they could reappear when switching to a different tab, or tab switching could be prevented while showing a fullscreen video - I'm just not convinced that we should bother :wink:

**Comment by lahwaacz** [comment]
Well I've just paused a video without leaving fullscreen, went to mutt and opened some link and qutebrowser opened in a new tab, which is how I noticed this behaviour. At first it was very surprising, then inconvenient because I had to navigate to the video tab and exit fullscreen to restore the "normal" behaviour.

I think that being able to switch tabs while a video is fullscreen is a good thing (otherwise e.g. what would happen if some other program opens a URL?). Instead of preventing that qutebrowser could just automatically exit the fullscreen first, but if it's not too much trouble, I'd prefer if the bars could just reappear when I switch tabs (and of course disappear when I switch back).

**Comment by The-Compiler** [comment]
Hmm, right, I didn't think of that.

Handling fullscreening per-tab would mean we'd also have to store some "the content in this tab is fullscreen" flag for each tab (instead of globally like now), and access that from the statusbar as well when another tab is focused. Might be relatively easy, or not - I'm not sure yet.

But I agree exiting fullscreen when opening a new tab would be a nice alternative otherwise.

**Comment by TrilbyWhite** [comment]
On a related note, I've had trouble getting *out* of fullscreen mode if I forget to leave fullscreen before closing the tab that requested it.  To replicate:

1) Open at least 2 tabs, one on a video site (netflix/youtube)
2) Enter fullscreen via the video controls toggle (button in lower right of a youtube video)
3) Close the video tab (I use 'd'  as a close tab binding)
4) Now the other tab remains in fullscreen, and hitting "esc" does not exit fullscreen

The only way I've found to exit fullscreen mode at that point is to open any video website, play a video, fullscreen it, then exit fullscreen there.  It seems as though qutebrowser "forgets" that it is fullscreened when a fullscreen video tab is closed.

**Comment by agguser** [comment]
I resize qutebrowser to half screen, open two tabs, one is youtube.com. After I enter fullscreen on youtube, the window is automatically resized to fullscreen, then I switch to the other tab, the `window size` still remain fullscreen instead of half-screen! Isn't this a bug?

**Comment by The-Compiler** [comment]
@agguser Perhaps. Right now, only the statusbar/tabbar hiding is handled, but qutebrowser doesn't un-fullscreen the window. I'll need to think about it some more, could you open a separate issue for that?

**Comment by agguser** [comment]
#5283
