### ISSUE TITLE
page number increment fails on some pages.

### ISSUE THREAD

**Issue by sim590** [qutebrowser/qutebrowser#2385]
Using `ctrl-a` increment or `ctrl-x` decrement on the page with url https://gerrit-ring.savoirfairelinux.com/#/c/6126/

outputs:
```
No number found in URL!
```

**Expected behavior**

If using `ctrl-a` key, the current url should be substituted with https://gerrit-ring.savoirfairelinux.com/#/c/6127/

**VERSION**
```
qutebrowser v0.9.1
Git commit: v0.9.0-189-g81a24bdbe (2017-02-22 17:04:57 +0100)
Backend: QtWebEngine

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: no
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.0-1-amd64-x86_64-with-debian-9.0, 64bit
Frozen: False
Imported from /home/simon/prog/qutebrowser/qutebrowser
OS Version: 

--- /etc/os-release ---
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian

Paths:
system_data: /home/simon/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
cache: /home/simon/.cache/qutebrowser
data: /home/simon/.local/share/qutebrowser
config: /home/simon/.config/qutebrowser
download: /home/simon/Téléchargements
```

**Comment by The-Compiler** [comment]
That's because the number is in an anchor there, and incrementing that *usually* isn't what you want (if you're on `https://example.com/article/1#10-tricks-for-qutebrowser` you'd expect to go to `/article/2`).

You can however do `:set general url-incdec-segments `path,query,anchor` to change that.

**Comment by sim590** [comment]
@The-Compiler: Then, the `#` is always present on gerrit urls. I didn't think it was an anchor since it's followed by a `/`. Is it really an anchor in the sense of http url specs?

**Comment by The-Compiler** [comment]
[Yes it is](https://url.spec.whatwg.org/#url-fragment-string):

```
>>> u = QUrl('https://gerrit-ring.savoirfairelinux.com/#/c/6127/')
>>> u.path()
'/'
>>> u.fragment()
'/c/6127/'
```

I'm guessing Gerrit is simply reading that via Javascript and then doing magic.

**Comment by sim590** [comment]
Alright. Thank you for clarification! :smile:
