### ISSUE TITLE
https://bugzilla.gnome.org appears to be crushed

### ISSUE THREAD

**Issue by zzoon** [qutebrowser/qutebrowser#2389]
Hi. I'm using qutebrowser 0.10.0.
First of all, I really appreciate your effort to maintain this project.
This browser makes me very happy and comfortable.

Recently, Gnome's default theme is changed. You can visit https://bugzilla.gnome.org to see.
Unfortunately, this web page appears to be crushed after change.
I'm working on this page everyday, and I really hope using qutebrowser continuously.

I'll be working on firefox for a while until this is fixed, but I'll be waiting for your fix.
Sorry for not being able to help.
Thanks.

Ah, if there's something that I can, for instance, changing preference thing, please let me know.

**Comment by The-Compiler** [comment]
Looks fine here:

![gnome](https://cloud.githubusercontent.com/assets/625793/23494869/92c44700-ff15-11e6-84f7-ad28387cff7e.png)

What backend are you using (see `:open qute:version`) and what OS/distribution are you on?

**Comment by zzoon** [comment]
Ouch, can I change the backend instead of qtwebkit?

Here's mine: I'm  using Ubuntu 16.04
Version info

qutebrowser v0.10.0
Git commit: 
Backend: QtWebKit

CPython: 3.5.2
Qt: 5.5.1
PyQt: 5.5.1

sip: 4.17
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2g  1 Mar 2016

Style: QGtkStyle
Platform: Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5
OS Version: 

--- /etc/os-release ---
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

--- /etc/lsb-release ---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

Paths:
system_data: /usr/share/qutebrowser
cache: /home/zzoon/.cache/qutebrowser
data: /home/zzoon/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
download: /home/zzoon/Downloads
config: /home/zzoon/.config/qutebrowser

**Comment by zzoon** [comment]
My result is the following:

![qute](https://cloud.githubusercontent.com/assets/898344/23495113/3b93f6f2-ff5a-11e6-9acd-dc2100e6e950.png)

**Comment by The-Compiler** [comment]
Yes, that's why I'm asking :wink:

You can use either [QtWebKit-NG](https://github.com/annulen/webkit/wiki) or QtWebEngine (based on Chromium, remove QtWebKit or start with `--backend webengine`), but it might get tricky to do so on Ubuntu.

If you want to use QtWebEngine, your best bet would be to install `python-tox` and do `tox -e mkvenv-pypi` in the qutebrowser repo. That will install a separate copy of Qt 5.8 with QtWebEngine in a Python virtualenv. You can then run `./.venv/bin/qutebrowser`.

Let me know if that works!

**Comment by zzoon** [comment]
Works! Thanks for support :)
