### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by schvabodka-man** [qutebrowser/qutebrowser#2390]
That's really weird that there are no "open in new tab" option on right-click menu(only open in tab). It would be nice if there would be this feature

**Comment by The-Compiler** [comment]
"Open in new window" *does* actually open a new tab.

The context menus are currently not handled by qutebrowser at all, only by the backends - see #349.

**Comment by schvabodka-man** [comment]
So, it would be nice if there would be possibility to open in new window and adequate naming.

**Comment by The-Compiler** [comment]
As said, see #349. As it'd mean we'd have to reimplement the whole context menu, and not many qutebrowser users use the context menu at all, it's not really a priority.

**Comment by lahwaacz** [comment]
FWIW, that's the case only with webkit backend - in webengine there is only a "Follow link" option.
