### ISSUE TITLE
Not running with QtWebengine backend on void linux

### ISSUE THREAD

**Issue by monstergroup42** [qutebrowser/qutebrowser#2392]
I am trying to run qutebrowser (version 0.10) on void linux, but it is showing an error message saying the module PyQt5.QtWebEngineWidgets is missing, even though I installed it. 
![2017-03-02-180227_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3883241/23532713/84ace9a8-ff72-11e6-8af5-f701674b8cdc.png)

**Comment by The-Compiler** [comment]
What exactly did you install? What does `python3 -c "from PyQt5 import QtWebEngineWidgets"` say?

**Comment by NoctuaNivalis** [comment]
@monstergroup42 Did you install from void-packages, or source? If you've installed from the repositories, you should be fine with (at most) the Qt5 packages below (of which IIRC I had to install the webchannel, webengine and quick ones myself):

```
[09:43:31] ~ $ xbps-query -s qt5-
[*] python3-PyQt5-5.7.1_1            Python3 bindings for the Qt5 toolkit
[*] python3-PyQt5-quick-5.7.1_1      Python3 bindings for the Qt5 toolkit - quick module
[*] python3-PyQt5-webchannel-5.7.1_1 Python3 bindings for the Qt5 toolkit - webchannel module
[*] python3-PyQt5-webengine-5.7.1_1  Python3 bindings for the Qt5 toolkit - webengine module
[*] python3-PyQt5-webkit-5.7.1_1     Python3 bindings for the Qt5 toolkit - webkit module
[*] qt5-5.7.1_4                      A cross-platform application and UI framework (QT5)
[*] qt5-declarative-5.7.1_4          A cross-platform application and UI framework (QT5) - Declarative component
[*] qt5-location-5.7.1_4             A cross-platform application and UI framework (QT5) - Location and Positioning components
[*] qt5-plugin-sqlite-5.7.1_4        A cross-platform application and UI framework (QT5) - SQLite plugin
[*] qt5-sensors-5.7.1_4              A cross-platform application and UI framework (QT5) - Sensors component
[*] qt5-webchannel-5.7.1_4           A cross-platform application and UI framework (QT5) - WebChannel component
[*] qt5-webengine-5.7.1_4            A cross-platform application and UI framework (QT5) - WebEngine component
[*] qt5-webkit-5.7.1_1               A cross-platform application and UI framework (Qt5) - WebKit2 component
[*] qt5-x11extras-5.7.1_4            A cross-platform application and UI framework (QT5) - X11 extras
[*] qt5-xmlpatterns-5.7.1_4          A cross-platform application and UI framework (QT5) - XML components
```

If I'm the one doing the next release of qutebrowser on void, I should probably include the webengine backend.

**Comment by monstergroup42** [comment]
@The-Compiler @NoctuaNivalis I realized what the problem was. I had not installed the `python3-PyQt5-webchannel`. It starts now, even thyugh it crashes everytime I try to open a website. But I  think that has got more to do with nouveau and QtWebEngine than qutebrowser itself. Thanks for the help.

**Comment by The-Compiler** [comment]
Right - you can set `LIBGL_ALWAYS_SOFTWARE=1` in your environment to force software rendering though.

**Comment by NoctuaNivalis** [comment]
I've hereby added the package dependencies for QtWebengine as a post-install message to the [new release on void](https://github.com/voidlinux/void-packages/pull/5926).
