### ISSUE TITLE
Use view-source scheme for :view-source

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2395]
With QtWebEngine, we can use Chromium's `view-source:` scheme when using `:view-source`.

This gives us clickable links, and might even help with #1208 (when caret mode is implemented) and #1125.

**Comment by lahwaacz** [comment]
I just noticed that with webengine, "View Page Source" from the context menu opens a different page than the `:view-source` command. However, in one important aspect it behaves differently from the Chromium's `view-source:` page: it appears to always reload the URL instead of taking the already loaded page as-is. The result is that content of editable elements like `<textarea>` is lost as well as results of POST requests. You can reproduce it e.g. on this page with the comment input field or on [ArchWiki's sandbox](https://wiki.archlinux.org/index.php?title=ArchWiki:Sandbox&action=submit) with the "Show preview" button. I tried it on Chromium and it does the right thing, i.e. those things are not lost. The `:view-source` command also takes the page as-is.

**Comment by The-Compiler** [comment]
I can't reproduce this with Chromium 57 - I enter "foobarbaz" here, select "view page source" in the context menu, but I don't find "foobarbaz" anywhere in the source.

**Comment by lahwaacz** [comment]
Oops, you're right - only POST request seem to be the issue and Github does not use them for previews.

**Comment by The-Compiler** [comment]
Reproduced and upstreamed as [QTBUG-59437](https://bugreports.qt.io/browse/QTBUG-59437).

**Comment by lahwaacz** [comment]
Another problem is that `:scroll-perc` does not work on the Chromium's `view-source:` pages.

**Comment by The-Compiler** [comment]
Hmm, right. Looks like we can't inject JS there.

**Comment by The-Compiler** [comment]
While touching that code anyways, it might be possible to move the pygments call to a secondary thread for QtWebKit to fix #2270.

**Comment by mjauvin** [comment]
@The-Compiler did you mean to fix #2770 instead of #2270 above?

**Comment by mjauvin** [comment]
Would it be possible to map WebEngine's "view-source:" scheme to our internal view_source method? And if so, would it be the preferred way of addressing this?

I have a fix for #2770, but if we're going to do the opposite and remap to WebEngine's scheme anyway, I won't bother.

**Comment by mjauvin** [comment]
OK, I found how to use WebEngine's view-source scheme internally for the "view-source" command.

So is that what we want to do? (see below)

```
diff --git a/qutebrowser/browser/commands.py b/qutebrowser/browser/commands.py
index 6ddb72636..d66b791e2 100644
--- a/qutebrowser/browser/commands.py
+++ b/qutebrowser/browser/commands.py
@@ -1513,6 +1513,10 @@ class CommandDispatcher:
             message.error(str(e))
             return
 
+        if tab.backend == usertypes.Backend.QtWebEngine:
+            self._tabbed_browser.openurl(QUrl('view-source:{}'.format(current_url.toDisplayString())), newtab=True)
+            return
+
         def show_source_cb(source):
             """Show source as soon as it's ready."""
             # WORKAROUND for https://github.com/PyCQA/pylint/issues/491
@@ -1527,6 +1531,8 @@ class CommandDispatcher:
             new_tab = self._tabbed_browser.tabopen()
             new_tab.set_html(highlighted)
             new_tab.data.viewing_source = True
+            new_tab.url = lambda requested=False: QUrl(
+                'Source: {}'.format(current_url.toDisplayString()))
 
         tab.dump_async(show_source_cb)
```

**Comment by mjauvin** [comment]
Here's a quick fix for this:
```
diff --git a/qutebrowser/browser/commands.py b/qutebrowser/browser/commands.py
index 6ddb72636..77eeb5012 100644
--- a/qutebrowser/browser/commands.py
+++ b/qutebrowser/browser/commands.py
@@ -1513,6 +1513,11 @@ class CommandDispatcher:
             message.error(str(e))
             return
 
+        if tab.backend == usertypes.Backend.QtWebEngine:
+            url = QUrl('view-source:{}'.format(current_url.toDisplayString()))
+            self._tabbed_browser.tabopen(url, background=True)
+            return
+
         def show_source_cb(source):
             """Show source as soon as it's ready."""
             # WORKAROUND for https://github.com/PyCQA/pylint/issues/491
@@ -1527,6 +1532,8 @@ class CommandDispatcher:
             new_tab = self._tabbed_browser.tabopen()
             new_tab.set_html(highlighted)
             new_tab.data.viewing_source = True
+            new_tab.url = lambda requested=False: QUrl(
+                'Source: {}'.format(current_url.toDisplayString()))
 
         tab.dump_async(show_source_cb)
```
