### ISSUE TITLE
whatsapp web is not working

### ISSUE THREAD

**Issue by hgareeballa** [qutebrowser/qutebrowser#2397]
whatsapp web is not wokring !?

**Comment by NoctuaNivalis** [comment]
It should work (it does for me), could you post the qute-version info here as well?

**Comment by hgareeballa** [comment]
am using the windows version !

**Comment by hgareeballa** [comment]
qutebrowser-0.10.0-amd64.msi

**Comment by hgareeballa** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6079147/23578376/cfa31612-00ee-11e7-99f4-f67250529a07.png)

this is the error i get while trying to open whatsapp page !

**Comment by The-Compiler** [comment]
The Windows binary is currently still based on an older QtWebKit as backend. This is hopefully going to change soon, see #2335.

You might also get around it by doing `:set network user-agent` and selecting a Chromium user-agent there, but other pages (like GitHub) will break.

**Comment by hgareeballa** [comment]
Thanks
