### ISSUE TITLE
Origin http://www.myraseed.com is not allowed by Access-Control-Allow-Origin. 

### ISSUE THREAD

**Issue by hgareeballa** [qutebrowser/qutebrowser#2398]
hi all
am getting above error when i access this site !? in the debug mode,

please help 

thanks

**Comment by NoctuaNivalis** [comment]
Could you provide us with the content of the `:open -t qute:version` page?

**Comment by hgareeballa** [comment]
i just tried it now and its working fine O_o,
am sure it was showing me that message in the console !?

**Comment by The-Compiler** [comment]
I can't reproduce this either - looks more like an issue with the website than with qutebrowser.

**Comment by hgareeballa** [comment]
noted
