### ISSUE TITLE
Easy way to show all keybindings

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#24]
There should be a command or page to show keybindings, to get an easy overview.

**Comment by tomxtobin** [comment]
I think that commit wasn't meant to resolve this issue.

**Comment by The-Compiler** [comment]
Whoops, good catch - thanks! I need to be more careful when pasting other project's changelogs into commit messages...

**Comment by The-Compiler** [comment]
Okay - according to `git log --grep='tox:' --grep='[cC]losed\? #' --all-match` it seems to be the only affected issue at least.

**Comment by sixshotx** [comment]
Do we have a command/keybinding to do this now? I am current using v1.0.4.

**Comment by The-Compiler** [comment]
@sixshotx Nope, there isn't anything like this currently. It should be quite straightforward to do though, do you want to contribute it by any chance? :wink:

**Comment by mjauvin** [comment]
I implemented this, would like to know the best way to submit a PR (not yet that confident with GitHub)

**Comment by The-Compiler** [comment]
There's a `qute://bindings` page opened with `:bind` now - thanks @mjauvin!
