### ISSUE TITLE
Scrolling focus with background tabs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2403]
When opening a tab in the background and closing the foreground tab, scrolling with `hjkl` works, but scrolling with the space bar requires first clicking into the window.

cc @isene

**Comment by The-Compiler** [comment]
From the Arch BBS, a similar issue:

> I'm wondering if this is a bug (on qtwebengine at least): whenever I follow-open a tab in the background, I lose focus on the current tab (e.g. <space> does not work anymore).
Step to reproduce:
> - Open a long page on arch wiki.
> - Check that <space> scrolls down.
> - follow-hint in the background.
> - <space> does not scroll down anymore.

#2320 also might be related.

**Comment by demure** [comment]
I believe that I have run into this issue, though I'm not sure if 'background' applies.

On the latest git pull of qute, using webengine (on debian sid) and my tt-rss page:

I press 'i' to go into insert, press a key to select my next article, and then hit 'v' to open it in a new tab.
In that new tab, I can neither page up/down or hit space to scroll, unless I first click in the body of the tab with my mouse.

**Comment by The-Compiler** [comment]
Thias actually seems like a duplicate of #2320 as well.
