### ISSUE TITLE
javascript: links aren't yankable

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#2404]
On a page with javascript: links such as https://www.comic-rocket.com/help/bookmarklets/, those links aren't yankable with `;y`. Additionally, `Copy Link` entry in right-click menu copies `about:blank` instead.

<img width="879" alt="screen shot 2017-03-05 at 2 54 39 pm" src="https://cloud.githubusercontent.com/assets/14615/23592327/e36ca81e-01b3-11e7-83c0-a270a9dc08d5.png">

qutebrowser v0.10.0 official OS X build.

**Comment by The-Compiler** [comment]
Hinting [filters](https://github.com/qutebrowser/qutebrowser/blob/v0.10.0/qutebrowser/browser/webelem.py#L60) those links as you usually don't want to click them, but I agree with `;y` they should not be filtered.

I opened [QTBUG-59307](https://bugreports.qt.io/browse/QTBUG-59307) for the context menu issue.

**Comment by The-Compiler** [comment]
The "Copy link" entry in the context menu will also be [fixed](https://codereview.qt-project.org/#/c/194065/) in Qt 5.10.
