### ISSUE TITLE
Disable (automatic) video playback?

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#2416]
I recently switched to the webengine backend, in which videos (etc.) play in the browser perfectly fine. However, I'm very used to spawning `mpv` for videos (etc.) when using the webkit backend, and in fact I kind of prefer that method. At the very least, what I don't like is when a video starts playing in a tab automatically, without me hitting "play" or anything.

**Question:** Is there a way to disable video playback altogether, *without* completely obliterating javascript entirely with `:set content allow-javascript false`? Alternatively, is there a way to at least make videos not play until I've pressed "play"? (Years ago, I think I used a Firefox plugin to do this, called flash block or something.)

**Comment by The-Compiler** [comment]
There currently isn't, see #28 and #30.

However, you might be able to do something via the flags from #2377. No idea how exactly though.
