### ISSUE TITLE
adblock-update causes crash

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#2417]
Running `:adblock-update` keeps causing a fatal crash. In case it might be related, I recently switched to webengine and ran `:adblock-update` just fine. However, I decided to go back to webkit for a little while, and that's when the crashes started. Curiously, it now happens with webengine, too.

I tried uninstalling qutebrowser and reinstalling the latest version, but no change.

Info from `qutebrowser --version`:

    qutebrowser v0.10.0
    Git commit: v0.10.0-73-g3cc4f6912 (2017-03-07 06:51:34 +0100)
    Backend: QtWebKit (WebKit 538.1)

    CPython: 3.6.0
    Qt: 5.8.0
    PyQt: 5.8

    sip: 4.19.1
    colorama: no
    pypeg2: 2.15
    jinja2: 2.9.5
    pygments: 2.2.0
    yaml: 3.12
    cssutils: no
    typing: yes
    PyQt5.QtWebEngineWidgets: yes
    PyQt5.QtWebKitWidgets: yes
    pdf.js: no
    SSL: OpenSSL 1.0.2k  26 Jan 2017

    Style: QFusionStyle
    Platform: Linux-4.9.13-1-lts-x86_64-with-arch, 64bit
    Frozen: False
    Imported from /usr/lib/python3.6/site-packages/qutebrowser
    Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
    OS Version: 

    --- /etc/os-release ---
    NAME="Arch Linux"
    PRETTY_NAME="Arch Linux"
    ID=arch
    ID_LIKE=archlinux

    Paths:
    config: /home/brian/.config/qutebrowser
    data: /home/brian/.local/share/qutebrowser
    system_data: /usr/share/qutebrowser
    cache: /home/brian/.cache/qutebrowser
    download: /home/brian/Downloads
    runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
See #2301.
