### ISSUE TITLE
`qutebrowser --version` creates `~/Downloads` directory

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#2418]
I have `download-directory` set to `/tmp`, and yet when I run `qutebrowser --version`, I see

    Paths:
    ...
    download: /home/brian/Downloads
    ...

Curiously, running `qutebrowser --version` actually *creates* this directory. (I noticed that this directory kept appearing in my `$HOME`, but I didn't know the source until just now.) If I `rmdir ~/Downloads` and then `qutebrowser --version`, it gets created again. Notably, running `qutebrowser` without `--version` does not create it.

What's going on?

**Comment by The-Compiler** [comment]
Either our call to `standarddir.download()` creates it (the documentation says it does not), or QtWebEngine/Chromium does somehow. I suspect the latter.

**Comment by The-Compiler** [comment]
Okay, qutebrowser actually calls `_create(path)` in `standarddir.download()`. Either `standarddir` should take the setting into account, or we should remove that from the version output.

**Comment by lahwaacz** [comment]
FWIW the creation of `~/Downloads` can be prevented by setting `XDG_DOWNLOAD_DIR` in the [user-dirs.dirs](https://wiki.archlinux.org/index.php/XDG_user_directories) file or as an environment variable.

**Comment by brianbuccola** [comment]
@The-Compiler Seems reasonable for the version output to include the download path if `download-directory` is set (but not otherwise; or N/A otherwise).

@lahwaacz Wouldn't that also set a specific downloads directory for other applications besides qutebrowser? (Actually, other applications *have* in the past created `~/Downloads`, e.g. when opening a file in some application that uses a GUI file browser, so maybe setting `XDG_DOWNLOAD_DIR` would prevent this across the board.)

**Comment by The-Compiler** [comment]
I don't think setting it as an environment variable works (only the ones [listed here](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support#XDG_Base_Directory_specification) do, others need to be set via user-dirs.dirs)

**Comment by The-Compiler** [comment]
Fixed in the `new-config` branch since I did some work on the `standarddir` module anyways.
