### ISSUE TITLE
[Bug] adblock-update crashes qutebrowser on Linux

### ISSUE THREAD

**Issue by Unip0rn** [qutebrowser/qutebrowser#2422]
also reported with built-in report, then found it reproducable, so here again:

needed to reproduce: qutebrowser
steps to reproduce: :adblock-update
result: crash of qutebrowser

in case that is an issue about this: windowmanager: i3 (vanilla)

qutebrowser --version

qutebrowser v0.10.0
Git commit: 
Backend: QtWebKit

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.11-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

--- /etc/arch-release ---
Arch Linux release

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

Paths:
config: /home/yuno/.config/qutebrowser
data: /home/yuno/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/yuno/.cache/qutebrowser
download: /home/yuno/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
Already [fixed](https://github.com/qutebrowser/qutebrowser/commit/c45019f0a0542ea684e5b57a3c8e34db551bc7bb) - a new release will follow ASAP.
