### ISSUE TITLE
<up>, <down>, <space>, etc.: webkit vs. webengine

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#2428]
I recently noticed a difference between webkit vs. webengine.

With webkit, after opening a page in a new tab, non-vim-like navigation keys like `<up>`, `<down>`, `<space>` (forward 1 page), `<s-space>` (back 1 page), etc. work just fine, as do their vim-like counterparts `j`, `k`, `<c-f>`, `<c-b>`, etc.

However, with webengine, after opening a page in a new tab, the non-vim-like keys do not (always) work, but the vim-like ones do. To use the non-vim-like ones, I need to click inside the main page frame first.

Of course, I don't use the arrow keys to navigate (`j`, `k`, etc. are way better), but I do happen to prefer `<space>` and `<s-space>` over `<c-f>` and `<c-b>`.

Is there any way to make webengine behave like webkit does, i.e. to focus the main page frame of a newly opened tab? Or is there good reason for webengine to behave the way it does?

Here's the most recent example of a page that illustrates the effect:

[Republicans introduce healthcare replacement bill called ‘World's Greatest Healthcare Plan of 2017’](http://www.independent.co.uk/news/world/americas/donald-trump-healthcare-plan-worlds-greatest-2017-obamacare-repeal-replace-a7618861.html)

As a workaround, I've done

    :bind <space> scroll-page 0 1
    :bind <shift-space> scroll-page 0 -1

which works fine.

**Comment by The-Compiler** [comment]
See #2403.

**Comment by brianbuccola** [comment]
I need to get better with my search-fu. (In this case, I have no excuse --- #2403 is the currently the 7th issue from the top.) Sorry!
