### ISSUE TITLE
URL with %20 gets treated as search term

### ISSUE THREAD

**Issue by troubas** [qutebrowser/qutebrowser#2429]
I bookmarked the following URL:
`http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx`

But when I try to open it it doesn't get recognized as url and instead it searches the web.
After a short test I believe it's related to the escape character %20. (replacing it with a space doesn't work either)

**Comment by troubas** [comment]
Using qutebrowser v0.10.1 under Windows

**Comment by The-Compiler** [comment]
Log:

```
11:31:24 DEBUG    commands   command:run:509 command called: bookmark-add ['http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx', 'foo']
11:31:24 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.bookmark_add(<qutebrowser.browser.commands.CommandDispatcher>, 'http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx', 'foo', False)
11:31:24 DEBUG    url        urlutils:get_path_if_valid:360 Checking if 'http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx' is a path
11:31:24 DEBUG    url        urlutils:is_url:245 Checking if 'http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx' is a URL (autosearch=naive).
11:31:24 DEBUG    url        urlutils:is_url:282 Checking via naive check
11:31:24 DEBUG    url        urlutils:is_url:286 url = False
11:31:24 DEBUG    url        urlutils:fuzzy_url:187 URL is a fuzzy search term
11:31:24 DEBUG    url        urlutils:_get_search_url:98 Finding search engine for 'http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx'
11:31:24 DEBUG    url        urlutils:_parse_search_term:85 engine None, term 'http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx'
11:31:24 DEBUG    url        urlutils:fuzzy_url:196 Converting fuzzy term 'http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx' to URL -> https://duckduckgo.com/?q=http%3A//sharepoint/sites/it/IT%2520Documentation/Forms/AllItems.aspx
11:31:24 DEBUG    save       savemanager:mark_dirty:72 Marking bookmark-manager as dirty.
11:31:24 INFO     message    message:info:86 Bookmarked https://duckduckgo.com/?q=http%3A//sharepoint/sites/it/IT%2520Documentation/Forms/AllItems.aspx!
```

It should definitely recognize the explicit scheme there.

**Comment by The-Compiler** [comment]
Looks like the condition in e5b3880b7183e15b891e5e285be79d074d85770b (for #1954) causes this. I'm not sure if we have any way of differentiating whether the user typed ` ` or `%20` though...

**Comment by deewakar** [comment]
@troubas 

> I bookmarked the following URL:
http://sharepoint/sites/it/IT%20Documentation/Forms/AllItems.aspx

The above url is missing a ```.com```,  is your bookmarked url missing it too?

What happens when you try http://sharepoint.com/sites/it/IT%20Documentation/Forms/AllItems.aspx

**Comment by troubas** [comment]
@deewakar 
It's an intranet page =)

I think it didn't occur to me to test with the FQDN. As I no longer work for the company I can't test anymore however should I stumble about another Intranet URL with a %20 I'll make sure to test if I can bookmark it!

**Comment by deewakar** [comment]
> It's an intranet page =)

Ah I see. Never came across those before :smiley: 
I suspect the real problem is not the presence of a %20 but the lack of  a "." in the hostname. So If you have access to any intranet sites (which do not end in .com or something), try to open them. Also set ```url.auto_search``` to **never** if they fail to open normally.
