### ISSUE TITLE
asciidoc2html.py leaves temporary files in /tmp/

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2431]
It might be because [this line](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/asciidoc2html.py#L264) bypasses [this check](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/asciidoc2html.py#L71).

**Comment by The-Compiler** [comment]
That line indeed makes no sense - looks like it was added in 8004508b3c6690e708a19a932c736b685c0d4708 which - based on the commit message - never was intended to be pushed that way.
