### ISSUE TITLE
QuteBrowser's volume is randomly lowered by Pulseaudio

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#2432]
While watching videos on youtube, the volume of qutebrowser (seen by pavucontrol as python3.4) jumps randomly from 100% to 50% or about 30%, without any clue of what could be causing the issue.
Didn't have time to test this on WebEngine, but this happens for sure on WebKit.

Additional notes: I have PulseAudio's flat-volumes disabled and QuteBrowser is the only application with this issue.

PulseAudio version: 10.0
Qt/QtWebKit versions installed: 4.8.7 and 5.7.1

Is there any way I can see what happens when the volume is changed?

Thank you for your work.
[quteversion.txt](https://github.com/qutebrowser/qutebrowser/files/835313/quteversion.txt)

**Comment by The-Compiler** [comment]
I've seen this happen with the microphone volume with QtWebKit, but this definitely is some issue in either QtWebKit or PulseAudio and not qutebrowser.

I suggest you use QtWebEngine instead, or try with QtWebKit-NG ([ebuild](https://gist.github.com/annulen/309569fb61e5d64a703c055c1e726f71)).
