### ISSUE TITLE
QtWebengine: ^ and ¨ keys do not work on AZERTY keyboards

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [qutebrowser/qutebrowser#2437]
Using QtWebengine backend and an [AZERTY keyboard](https://commons.wikimedia.org/wiki/File:KB_France.svg#/media/File:KB_France.svg) (properly configured X-wise), you cannot type in the webpage characters that needs the <kbd>^</kbd> or the <kbd>¨</kbd> key (which actually is typed using <kbd>Maj</kbd> + <kbd>^</kbd>). QtWebkit and Qutebrowser ui elements works fine though.

Expected behaviour (as seen on QtWebkit or any other application):

1. press <kbd>^</kbd> → nothing appears→ press <kbd>e</kbd> → `ê` appears
2. press <kbd>^</kbd> → nothing appears → press <kbd>^</kbd> → `^` appears
2. press <kbd>^</kbd> → nothing appears → press <kbd>r</kbd> → nothing appears

Actual behaviour (as seen on QtWebEngine):

1. press <kbd>^</kbd> → nothing appears → press <kbd>e</kbd> → **nothing appears**
2. press <kbd>^</kbd> → nothing appears → press <kbd>^</kbd> → **nothing appears**
2. press <kbd>^</kbd> → nothing appears → press <kbd>r</kbd> → nothing appears

Tested on different combination of the following:

- Operating system: Manjaro Linux 17.0
- Desktop environment: i3, xfce4, twm
- Qutebrowser versions: [0.10.1 Arch Package](https://gist.github.com/GeoffreyFrogeye/199b848b009a4e79cdf60b0726bdc67d#file-instance1) and [0b5838f9](https://gist.github.com/GeoffreyFrogeye/199b848b009a4e79cdf60b0726bdc67d#file-instance2) (and maybe 0.9 too, I can check that if needed)
- Config files: [all-day config](https://gist.github.com/GeoffreyFrogeye/199b848b009a4e79cdf60b0726bdc67d#file-config), default config
- X11 keymap layout: fr
- X11 keymap variants: oss, azerty, latin9

The `nodeadkeys` X11 keymap variant works but this is because it consider <kbd>^</kbd> and <kbd>¨</kbd> as regular keys so you cannot type characters like `ä` or `ê` with it, only `^` and `¨` (this is not qutebrowser specific).

Random notes:

- When using Chromium with the same version displayed in `qutebrowser --version`, those keys work fine.
- There might be others keyboard layouts that might be impacted but I am no keyboard layout expert.
- This is a burden for french speakers, and is the only reason why I'm not using QtWebengine yet. I'm surprised this issue has not already been reported.
- I might be able to try that on Debian 8 on monday, to figure out wether it's Manjaro specific.

**Comment by The-Compiler** [comment]
Thanks for the detailed report! 👍 

This is a QtWebEngine issue unfortunately, and probably the same as #2317. Switching away to a different tab and back should make things work fine.

Also see [QTBUG-58635](https://bugreports.qt.io/browse/QTBUG-58635) - unfortunately I'm not aware of a workaround being possible in qutebrowser...
