### ISSUE TITLE
Update install instructions

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2440]
The install instructions should be updated for various things:

- [x] The debian experimental section is probably not needed anymore
- [x] Debian Jessie users can install QtWebEngine via a Debian package
- [x] OS X instructions could use QtWebEngine
- [x] tox instructions need to be updated for `tox -e mkvenv-pypi` which uses PyQt from PyPI with QtWebEngine
- [x] `-9999` should be preferred with Gentoo as the package is outdated

**Comment by Penaz91** [comment]
I can take over the Gentoo part

**Comment by Penaz91** [comment]
I created pull request #2504 to satisfy your gentoo needs :+1: 
Hopefully it helps a bit

**Comment by phansch** [comment]
I think the install instructions could also benenfit from a table of contents at the top. Would you mind a PR for that?

**Comment by The-Compiler** [comment]
Good point - though it should probably be autogenerated by asciidoc somehow if that's possible.
