### ISSUE TITLE
Black Screen with WebEngine and Nvidia Driver

### ISSUE THREAD

**Issue by thomas--graf** [qutebrowser/qutebrowser#2441]
Starting qutebrowser with `--backend webengine` results in a *shader compilation failed* warning and a completely black window. The browser is still responsive --- I usually ask for a confirmation before quitting, and I still have to press y to actually close the black window.

I am on Debian Stretch and have the proprietary Nvidia driver installed. The bug seems to be related to an issue where some python/qt programs load mesa's libGL.so instead of nvidia's:

https://bugreports.qt.io/browse/QTCREATORBUG-15922
https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-319-updates/+bug/1241988
https://bugs.launchpad.net/ubuntu/+source/python-qt4/+bug/941826

I also tried `LIBGL_ALWAYS_SOFTWARE=1 qutebrowser --backend webengine`, but apparently that option isn't honored by the nvidia driver. So eventually I replaced mesa's libGL by a symlink to nvidia's and everything works as it should.

```bash
sudo su
cd /usr/lib/mesa-diverted/x86_64-linux-gnu
mv libGL.so.1.2.0 libGL.so.1.2.0_original
ln -s /usr/lib/x86_64-linux-gnu/nvidia/current/libGL.so.375.39 ./libGL.so.1.2.0
```

This workaround should probably be included in the documentatio. But maybe there is something you can do on your end, too. There are reports that this can also be fixed by including `from OpenGL import GL` in the Python code:

https://github.com/spyder-ide/spyder/issues/3226

Unfortunately I couldn't verify that myself. I added the line to `__init__.py`, ran `tox -r -e mkvenv` and then got *No module name 'OpenGL'* even though python3-opengl is installed.

- [qutebrowser version](https://github.com/qutebrowser/qutebrowser/files/837670/version.txt)
- [qt5 packages](https://github.com/qutebrowser/qutebrowser/files/837672/qt5.txt)
- [nvidia packages](https://github.com/qutebrowser/qutebrowser/files/837673/nvidia.txt)
- [python packages](https://github.com/qutebrowser/qutebrowser/files/837706/python.txt)
- [example of error](https://github.com/qutebrowser/qutebrowser/files/837730/error.txt)
- [glx information](https://github.com/qutebrowser/qutebrowser/files/837731/glx.txt)

**Comment by The-Compiler** [comment]
If you use a virtualenv, you'll need to install PyOpenGL there - something like:

`./.venv/bin/pip install PyOpenGL`

**Comment by lahwaacz** [comment]
You might want to take a look at [libglvnd](https://github.com/NVIDIA/libglvnd). Before it was deployed into the Arch Linux repos couple of weeks ago, I think it was impossible to have mesa-libgl and nvidia-libgl installed at the same time - probably due to this kind of issues...

**Comment by thomas--graf** [comment]
Hmm, so that's what those glvnd packages are for. I don't have them installed right now because they conflict with some of the default nvidia packages, but I'll give it a try later today and report back.

**Comment by thomas--graf** [comment]
Also, I installed PyOpenGL into the virtualenv and everything does indeed work the way it should even without the symlinking trick. So now there are at least two workarounds, and possibly a third with the glvnd packages.

**Comment by The-Compiler** [comment]
Could you check if it still works if you put the import on the top of the `init` function in `qutebrowser/browser/webengine/webenginesettings.py`? Then I could add a workaround with a setting or something.

**Comment by thomas--graf** [comment]
Yes, that works too. But it gives the following info message, which does not show up when opengl is instead imported in `__init__.py`

```bash
18:38:34 INFO: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
```

On a different note, I also purged the nvidia drivers from the system and reinstalled them just to make sure the problem wasn't due to an incomplete upgrade from jessie to stretch. I made sure I had all the glvnd  packages installed this time around, but it still didn't change anything.

**Comment by The-Compiler** [comment]
Can you undo your symlink again and confirm that things work on the `gl-workaround` branch? It simply tries to import PyOpenGL unless `QUTE_NO_OPENGL_WORKAROUND` is set as environment variable.

**Comment by thomas--graf** [comment]
Yes, that works. Without the environment variable everything is fine, but if it is set the black screen returns exactly as expected. The info message about `OpenGL_accelerate` is still being shown in the terminal, though.

**Comment by The-Compiler** [comment]
Can you try again and confirm the message is gone?

**Comment by thomas--graf** [comment]
Yup, gone!

**Comment by The-Compiler** [comment]
Thanks for all the testing! I pushed the workaround to master now.

**Comment by thomas--graf** [comment]
Thanks for fixing it so quickly!
