### ISSUE TITLE
Right click menu has no obvious way to close via keyboard

### ISSUE THREAD

**Issue by dset0x** [qutebrowser/qutebrowser#2446]
The context menu can be opened with the keyboard (Menu button), so closing it should be as obvious  (Esc button). Currently the Alt button closes it, which I discovered merely by accident.

v0.10.0-108-g3a88b70 (2017-03-13 09:11:22 +0100)

**Comment by The-Compiler** [comment]
The context menu is currently entirely handled by Qt, so this isn't possible. See #349.

**Comment by dset0x** [comment]
Oops, I didn't search in closed issues. Thanks.

**Comment by The-Compiler** [comment]
That issue is open though :wink:

However it wasn't discoverable by searching for "context menu", I renamed it so it is now.

**Comment by mschilli87** [comment]
I just had the same problem and was about to open an issue (expecting 'This is handled by Qt, so not possible', but would it hurt to ask? :wink:). This issue wasn't easy to find and I couldn't find anything on how  to close the menu via keyboard in #349.

Thanks to @dset0x I learned about the Alt default (unchangable?) binding.
Maybe this could go somewhere more public in the documentation/cheatsheet?

It is really irritating not to find a way to do something without reaching for the mouse when using a keyboard-based browser. Almost as irritating a learning that 'leave the current mode' is not possible by pressing Esc but by pressing Alt instead when using a vim-inspired browser. :wink:

**Comment by The-Compiler** [comment]
I just looked at this again because of #3465 - turns out I was wrong here 😊 I missed the fact that this works in other Qt/QtWebEngine applications, and it's probably something qutebrowser does wrong with key filtering.
