### ISSUE TITLE
Mention longer smooth j/k scrolling in the docs

### ISSUE THREAD

**Issue by dset0x** [qutebrowser/qutebrowser#2447]
I use j/k frequently to scroll through pages, and the default distance is too small.

Looking at the docs I tried binding them to scroll-px, but that doesn't use smooth scrolling when it's enabled. I understand this is a limitation of how scroll-px (and scroll-perc is implemented).

Perhaps
a) This limitation should be mentioned in the docs
b) `repeat 5 scroll up` and `repeat 5 scroll down` should be given as examples for lengthening scrolling distance

**Comment by pkill-nine** [comment]
@dset0x out of interest do you have issue #2233?
