### ISSUE TITLE
Open groups of bookmarks

### ISSUE THREAD

**Issue by bearcatsandor** [qutebrowser/qutebrowser#2463]
I often end up visiting the same groups of pages when i'm performing a specific task.  It would great to be able to save a group of bookmarks such that i could  ':group-open work' and it would open those bookmarks.  Doing a ':group-save work' would save the current window's tabs as a bookmark group.  Similar to how sessions work, but only for the current window.

**Comment by pkill-nine** [comment]
`:session-save --only-active-window` :)

**Comment by bearcatsandor** [comment]
Awesome! I did RTFM before I posted, but it's not in there. At least not in qute://help/commands.html#session-save

**Comment by The-Compiler** [comment]
It was only added recently, i.e. after the latest release :wink:

**Comment by bearcatsandor** [comment]
Whoo! It works (with the Git version). Thank you!
