### ISSUE TITLE
Some keys are missing in cheatsheet

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2466]
There's noting on `v` there.

cc @regines

**Comment by The-Compiler** [comment]
`gt` is missing too.

**Comment by josealberto4444** [comment]
I was taking a look at this issue and realised that `v` and `gt` are already added in the cheatsheet, aren't they?

And I don't understand how `ctrl-d` is used for completion, so I don't know where to add it.

**Comment by The-Compiler** [comment]
Sorry for not answering earlier! It looks like it's indeed in the file in the repo, but the `.png` on qutebrowser.org is outdated...

**Comment by josealberto4444** [comment]
Don't worry. =)

Perfect then, issue solved! Haha.
