### ISSUE TITLE
Add -s argument to `open` to use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#2468]
I really want to open HTTPS by default. I always hit `t` or `o` and put `https://` manually after `:open `. But this is too much work (still nothing compared to using the mouse, which requires moving my entire arm! But nonetheless it is relatively too much work, at least unncessary).

So far I worked around this by defining `t` and `o` to map to `:open -t https://` and `:open https://`, respectively (thanks to The-Compiler for suggesting this quick workaround). So when I type `t` or `o`, I get something like `:open -t https://` pre-filled. This is very nice.

But the problem is when I want to use search engine keywords. `:open -t https://ddgo lol`, where `ddgo` is a search engine keyword to search keyword `lol` in search engine DuckDuckGo, will not work as expected. This is why I think mapping `t` (or `o`) to `:open -t https://` is not a perfect solution, as it causes me to delete the prefixed `https://` every time I want to use a search keyword (which partly defeats the purpose of using a search keyword which is to save time to begin with, as I end up wasting time deleting the `https://`).

I think the real solution is to introduce a new argument to `:open`, perhaps `-s` to force the potocol to be HTTPS. Then, I can map `t` to `:open -t -s` and everything would work peacefully, including my search engine keywords, without needing to delete `https://`.

**Comment by Al-Caveman** [comment]
#2469

**Comment by The-Compiler** [comment]
Can you please open a PR with https://github.com/Al-Caveman/qutebrowser/commit/df93e30ec20dd1b2b4fe163bdb5a69c232fb8c71?

**Comment by Al-Caveman** [comment]
Opened, thank you.
