### ISSUE TITLE
Terminus font not selected

### ISSUE THREAD

**Issue by bitraid** [qutebrowser/qutebrowser#2480]
For some time now, git version would not display the Terminus font, for any of my machines. It was fixed by changing Terminus to "xos4 Terminus" in config file. Anyone else noticed that?

**Comment by The-Compiler** [comment]
Yes - this is a fontconfig change, I had to do the same in other applications as well.

**Comment by lahwaacz** [comment]
See this for details: https://wiki.archlinux.org/index.php/Font_configuration#FreeType_Breaking_Bitmap_Fonts

**Comment by bitraid** [comment]
That explains it, thanks.
