### ISSUE TITLE
Merge section and option for set command

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#2482]
Instead of `:set general private-browsing true`, what about `:set general.private-browsing true`?

I sometimes have trouble remembering what section an option is under (in the above example, I tend to think `private-browsing` is in `network` every time). With this new scheme, you could just type `priv` and have `general.private-browsing` autocompleted. I think it would make finding the setting you want faster and easier, and eliminate a bit of code in the process :grin:

**Comment by The-Compiler** [comment]
Planned for the config revolution (which will probably be the next crowdfunding in my summer holidays!), see #893.

As a workaround, you can use the completion for `:help`.

**Comment by rcorre** [comment]
oops, I did look for similar issues but apparently didn't have the right wording. sounds good!
