### ISSUE TITLE
too small window size when loading pages in the background

### ISSUE THREAD

**Issue by helbling** [qutebrowser/qutebrowser#2495]
Pages loading in the background - for example when doing a middle click on an url with background-tabs = true or when using session-load - have a very small window-size as reported by javascript.
They should have the same window-size as when loaded in the foreground.

Reproduction:
- set background-tabs = true in config
- Go to http://helch.ch/windowsize.html (source see below)
- middle click on rerun link
- switch to tab opened in background
- result looks something like this:
100/30
100/30
100/30
100/30
100/30
1920/1102
1920/1102
1920/1102
1920/1102

So the correct window size appears when i finally switch to the tab, instead of right away.

test page:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>window sizes</title>
    </head>
    <body>
        <a href="./windowsize.html">rerun</a></br>
        <script>
            var count = 0;
            var timer = window.setInterval(function() {
                var p = document.createElement("p");
                p.appendChild(document.createTextNode(window.innerWidth + "/" + window.innerHeight));
                document.body.appendChild(p);
                count++;
                if (count > 100)
                    window.clearInterval(timer);
                }, 100);
        </script>
    </body>
</html>
```

qutebrowser v0.10.1
Git commit: v0.10.0-215-g3b351d906 (2017-03-31 06:18:43 +0200)
Backend: QtWebKit (WebKit 538.1)
CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

**Comment by The-Compiler** [comment]
This looks like a bug in QtWebKit and QtWebEngine to me.

**Comment by annulen** [comment]
We found that tab gets resizeEvent with size (100,30) when it goes inactive, and viewport size of page is adjusted according to this size. So no bug in QtWebKit (and I assume QtWebEngine does the same thing)

**Comment by The-Compiler** [comment]
With this:

```python
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QApplication, QTabWidget, QWidget

app = QApplication([])

w1 = QWidget()
w2 = QWidget()
tw = QTabWidget()
tw.show()

tw.addTab(w1, "widget 1")
tw.addTab(w2, "widget 2")

timer = QTimer()
timer.setInterval(1000)
timer.timeout.connect(lambda: print(w1.size(), w2.size()))
timer.start()

app.exec_()
```

I get 640x480 for w2, and after showing/hiding it, I get the correct size.

**Comment by annulen** [comment]
Same with 2 QWebViews

**Comment by lahwaacz** [comment]
Heh! This is probably the reason behind https://github.com/qutebrowser/qutebrowser/issues/1190. I have a laptop with a smallish screen and a big external monitor, so I've been noticing for quite some time that the "scroll position" on a page is not preserved when I move the qutebrowser window from one screen to the other.

- When moving from big screen to small screen, the browser "scrolls up".
- When moving from small screen to big screen, the browser "scrolls down". This is probably exactly what happens in https://github.com/qutebrowser/qutebrowser/issues/1190 with the 100x30 -> something big change.

**Comment by The-Compiler** [comment]
I reported [QTBUG-59867](https://bugreports.qt.io/browse/QTBUG-59867) now. I'll have to try some workarounds - either we can simply fake a `resizeEvent`, or we might need to briefly show/hide it with `QWidget.setUpdatesEnabled(False)`

**Comment by annulen** [comment]
`setViewportSize` is a thing too

**Comment by The-Compiler** [comment]
not on QtWebEngine though, and I'd prefer a solution which works accross both :wink:

**Comment by jmaratt** [comment]
@The-Compiler Did you ever come up with a solution for this?  I'm running into the same issue now rendering a page in the background that reports a small size initially. Thanks in advance
