### ISSUE TITLE
Setting the default zoom != 100% doesn't work consistently with WebEngine

### ISSUE THREAD

**Issue by Carpetsmoker** [qutebrowser/qutebrowser#2507]
1. Set `ui default-zoom` to a value different than `100%` (I use 120%).
2. Browse the internet, open new tabs!
3. Sometimes the zoom will actually be 100%, and not the expected 120%!

It will happen reasonably reguarly. Maybe once every ~10 new tabs.

Also reported by someone else on IRC (using 140%). This far, I've only noticed this with WebEngine, not WebKit-ng.

**Comment by The-Compiler** [comment]
I don't know of a good solution to this - currently QtWebEngine has its own default zoom handling, and qutebrowser just writes its zoom when loading a page is finished. Maybe the best thing to do here is to add a setting to Qt (i.e. in C++) to set a default zoom.

**Comment by gilbertw1** [comment]
I've been sporadically experiencing this problem and I think I'm pretty close to figuring out exactly what is triggering it. 

First of all I've noticed that at any point if you navigate away from a page before it's finished loading then qutebrowser will have not had a chance to change the zoom level to the user defined default and anything done afterwards in that tab will be stuck at 100% zoom level. I'm guessing that qutebrowser remembers the zoom level based on the current zoom level of the tab whenever a new navigation action is triggered to navigate away from the current page. It's very easy to reproduce this problem by navigating away from a slow loading page (gmail is a great example) before the load has finished.

I've also noticed one other strange bit of behavior that may be a different side of the same problem, I'm not 100% sure. However the following scenario results in a 100% zoom level:

1. Load github.com in new tab
2. Load gmail.com (logged into mailbox)
3. Wait for page to load and zoom to adjust to user defined setting
3. Navigate back in history to github.com

You will notice in the above scenario that the zoom level is now stuck at 100% in the tab. However, if you were to open the github url using `:open` the zoom level would be fine. It's possible that this is a separate bug that only affects the history navigation.

I'm hopeful that now that I have a reasonable understanding of what's happening and the conditions that exhibit this loss of user-defined zoom, that I can look into a way to work around the problem, and at least mitigate it without needing to alter Qt.

**Comment by gilbertw1** [comment]
One option, that's much more of a workaround than a fix, would be to add a configuration setting that forces a reset to the default zoom level anytime a page change happens. Something like `force-default-zoom: true`. This would effectively overwrite the zoom level for a tab anytime a new page is loaded (or is navigated to using `:back` or `:forward`).

**Comment by gilbertw1** [comment]
Quick update ... I've been able to entirely eliminate the problem with the following change:

    modified   qutebrowser/browser/browsertab.py
    @@ -742,6 +742,7 @@ class AbstractTab(QWidget):
             if not self.title():
                 self.title_changed.emit(self.url().toDisplayString())
             self._handle_auto_insert_mode(ok)
    +        self.zoom.set_default()

This is basically calling `zoom.set_default()` at the tail end of `_on_load_finished` in `browsertab`. This is my best estimation of what a `force-default-zoom: true` would look like. 

I'll keep digging and see if improve the way that manually changed zoom levels are tracked vs. the default, and see if I can fix this without resorting to a workaround.

**Comment by gilbertw1** [comment]
I've worked up a pull request that I think will solve this issue without need to resort to any additional settings or workarounds.
