### ISSUE TITLE
Add support for image maps when navigating hints

### ISSUE THREAD

**Issue by ludovicchabant** [qutebrowser/qutebrowser#2508]
Right now an image with different zones for links (yes, like the way we used to make websites back in the early 2000s :) ) is only treated as one big link when you press `f`. Ideally each zone would be a different hint.

For example, go to the [Steve Jacksons Games website](http://www.sjgames.com) and see the links in the top bar.

**Comment by The-Compiler** [comment]
I reopened #299, as this isn't working with QtWebEngine either. Closing this as a duplicate.
