### ISSUE TITLE
Question: Blacklisting certain formats / only allow static images

### ISSUE THREAD

**Issue by throwaway217** [qutebrowser/qutebrowser#2521]
This is not an issue, I'm just putting this here so if other people have the same question they can find it easy. Feel free to close it.

Sometimes gifs,gifv,webm trash loads automatically in some part of the page and heats up my old cpu without reason.

Is there any way I can only allow static image formats to be displayed and block everything else ?

Edit: I'm using the webengine backend.

**Comment by The-Compiler** [comment]
I don't think this is possible to do, unfortunately.
