### ISSUE TITLE
Hide errors/warnings only after pressing some key (e.g. escape)

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#2527]
Currently, errors and warnings disappear after some timeout. I think it would be nice if we disable such timed disappearance, and have triggered disappearence upon pressing certain keys or commands.

Personally, I suggest pressing the escape key as the trigger to hide the errors/warnings. Would be even nicer if this trigger can be defined in the configuration.

**Comment by The-Compiler** [comment]
cc @Carpetsmoker who wanted something similiar IIRC

**Comment by pkill-nine** [comment]
there's a `:clear-messages` command which you can add to the `<escape>` bind, there just needs to be an option to disable message timeout, maybe by making a timeout of 0 be no timeout. for now you could just make the timeout 9999999999.

**Comment by The-Compiler** [comment]
Oh, I totally forgot about that command! I pushed a small change so 0 means "never clear messages" now.
