### ISSUE TITLE
Block mixed active content

### ISSUE THREAD

**Issue by cym13** [qutebrowser/qutebrowser#2528]
Security enhancement
====================

Qutebrowser doesn't block active mixed content. This leaves the user vulnerable to man-in-the-middle attacks against HTTPS websites that use HTTP external resources.

The idea is to recursively block any call to load javascript, css or HTML that isn't done over HTTPS if the main website is itself using HTTPS.

Firefox or Chrome have had this security feature for years and I think Qutebrowser should have it too.

For more details see https://blog.mozilla.org/tanvi/2013/04/10/mixed-content-blocking-enabled-in-firefox-23/

**Comment by The-Compiler** [comment]
This is done by the backends, not qutebrowser itself.

Testing with https://www.bennish.net/mixed-content.html, all content is blocked with QtWebKit-NG and with QtWebEngine.

With the legacy QtWebKit, javascript seems to be blocked but the rest is run - but there's nothing qutebrowser can do about this.

I'd really recommend switching to one of the newer backends - there probably should be some more documentation about this topic (and QtWebEngine will soon be the default on distributions which have it packaged, see #2335).
