### ISSUE TITLE
Browser segfaults on WiFi connection drops

### ISSUE THREAD

**Issue by krzemian** [qutebrowser/qutebrowser#2529]
When connected via wifi (haven't tested with ethernet), open `qutebrowser --backend webengine` (update: just checked, `qutebrowser` with the old backend crashes as well), turn off the network (in my case: switch off Android hotspot), most of the time the browser will crash (it might be that certain websites are affected more often, for example it crashes every time on Todoist.com, but just once every two attempts on facebook.com).
Moreover, right after that launching `qutebrowser --backend webengine` doesn't open the browser (doesn't seem to be the problem if using `qutebrowser` only), as a workaround if I `kill -9 [qutebrowser]` and repeat the command it opens with no problems.
Let me know if you need any additional info.

qute:version
> Version info
> 
> qutebrowser v0.10.1
> Git commit: 
> Backend: QtWebEngine
> 
> CPython: 3.6.0
> Qt: 5.8.0
> PyQt: 5.8
> 
> sip: 4.19.1
> colorama: no
> pypeg2: 2.15
> jinja2: 2.9.6
> pygments: 2.2.0
> yaml: 3.12
> cssutils: no
> typing: yes
> PyQt5.QtWebEngineWidgets: yes
> pdf.js: no
> Webkit: 538.1
> SSL: OpenSSL 1.0.2k  26 Jan 2017
> 
> Style: QFusionStyle
> Platform: Linux-4.10.6-1-ARCH-x86_64-with-arch, 64bit
> Frozen: False
> Imported from /usr/lib/python3.6/site-packages/qutebrowser
> Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
> OS Version:`

**Comment by The-Compiler** [comment]
That's odd - so it doesn't happen with QtWebKit? What do you get when you run qutebrowser in a terminal with `--backend webengine --debug` when it crashes?

**Comment by krzemian** [comment]
My mistake. Checked QtWebKit version and it crashes as well. As for `--backend webengine --debug`, just this:
`[1]    9519 segmentation fault (core dumped)  qutebrowser --backend webengine --debug`

**Comment by The-Compiler** [comment]
Can you please find the crash in `coredumpctl list`, and show `coredumpctl info <PID>` after that?

Also, could you install my Qt debug packages as [mentioned here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc#to-install-my-pre-built-packages) and then get a full stacktrace as [mentioned here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc#getting-the-stack-trace)?

**Comment by The-Compiler** [comment]
Looks like [this Qt bug](https://bugreports.qt.io/browse/QTBUG-58541) - I don't have this issue myself though, and unfortunately there's nothing qutebrowser can do about it.

**Comment by munyari** [comment]
I face this exact issue and this has happened a few times. I'm often a weak connection, so this can make qutebrowser pretty frustrating (although in previous versions it would crash on wake up from suspend, so at least there's progress :smile:)

I'm on Arch Linux. `uname -srvo`:
`Linux 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 GNU/Linux`

qt5-webengine from extra on arch, version 5.8.0-8. 
qutebrowser version:
```
qutebrowser v0.10.1
Git commit: v0.10.0-458-g88545dec4 (2017-05-04 08:36:26 +0200)
Backend: QtWebKit (WebKit 538.1)

CPython: 3.6.1
Qt: 5.8.0
PyQt: 5.8.2

sip: 4.19.2
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.10.13-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/nash/.config/qutebrowser
data: /home/nash/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/nash/.cache/qutebrowser
download: /home/nash/Downloads
runtime: /run/user/1000/qutebrowser
```


I'll try to follow the Qt debug steps when I have time (perhaps this weekend).

**Comment by The-Compiler** [comment]
It's a Qt bug - not much qutebrowser can do about it.
