### ISSUE TITLE
Add option to `:open` that allows to disable mixed-content mode

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#2534]
Currently, if we view HTTPS pages, with some `<img src="http://domain.zone/lol.jpg">`, we might be toast. Sometimes invaluable cookies get sent that way.

My wish is to have this feature:

 - Ability to tell qutebrowser whether to force subsequent URLs to be HTTPS if the main URL (displayed on the status bar) is also HTTPS.

And I think maybe this way:

 - Adding argument `--pure/-p` to `open`.

This is, IMO, better than dropping non-HTTPS child URLs, because at least it tries to see if they are accessible securely over HTTPS.

**Example:** if I open a URL by `:open -p https://domain.zone/`, then if this URL opens a HTML page that subsequently results in retrieving an image over HTTP, say `http://domain.zone/lol.jpg`, then this second URL will be forced into HTTPS, say `https://domain.zone/lol.jpg`, and it better work. If it didn't work over HTTPS, then tough luck and the image will not be shown (no downgrade to HTTP).

But, if the parent page is already over HTTP, say `:open -p http://domain.zone/`, and if the child URL is over HTTPS (e.g. kinda an upgrade), say `https://domain.zone/lol.jpg`, then let it work over HTTPS (without downgrading the child URL to HTTP).

So while the option is named `--pure`, it's more like `--pure-only-if-parent-url-is-https`.

**How to do it:** maybe [this](http://doc.qt.io/qt-5/qwebengineurlrequestinterceptor.html) helps (thanks to The-Compiler for telling me this in the IRC channel).

 - If someone wants to do it, great.
 - If none want to do it, then I'd appreciate suggestions about which files should I look at to introduce this feature (URL interception to force child URLs to become HTTPS only if parent URL is HTTPS).

**Comment by lahwaacz** [comment]
In the QtWebEngine backend, active mixed content is blocked by default (see https://github.com/qutebrowser/qutebrowser/issues/2528) and passive mixed content should be blocked if the page [chooses so](https://www.w3.org/TR/mixed-content/#strict-checking). You can choose to block all mixed content by running qutebrowser with `--backend webengine --qt-flag enable-strict-mixed-content-checking`. Use the test page suggested by @The-Compiler in https://github.com/qutebrowser/qutebrowser/issues/2528 to verify the difference.

**Comment by The-Compiler** [comment]
I don't think this is possible to do with that API, as it's global and not per-tab.

And even if it was, I think this is a quite confusing user interface. I think it'd be better to either have strict mixed content blocking like @lahwaacz mentioned, or have something like HTTPS everywhere  (#335).

**Comment by Al-Caveman** [comment]
I think if we do it this way, then it is usable:

 1. Tab colours, or status bar colours, reflect the type by which content is handled. So we can have a set of colourful tabs, e.g. light green with black text indicates HTTPS with pure/strict-content.
 2. General configuration `url-interception-method = true` will cause qutebrowser to register a URL interceptor method, and then the interceptor will intercept all URLs. However, the interceptor will decide whether to apply strict-contents policies (i.e. changing scheme from HTTP into HTTPS) based on whether the parent URL had the `-p` flag applied to its `:open` command.

IMO.

I personally dislike HTTPSEverywhere. It's too broad, and requires too much house keeping (e.g. maintains lists).

**Comment by lahwaacz** [comment]
Still, with the QtWebEngine backend becoming the new default, I don't see a point in re-implementing the native feature in Python and slowing down the browser.

**Comment by Al-Caveman** [comment]
Yeah I agree it was a bad idea. I've just tested `--qt-flag enable-strict-mixed-content-checking` and it works fine.

Now my question is: where in qutebrowser is this flag passed to PyQt?

I think I can make this as a per tab setting /only/ by passing the flag to PyQt as new tabs are created, right?

**Comment by The-Compiler** [comment]
No. It's passed globally, when the `QApplication` object is created. This means currently it's not possible to add a config for it at all, but it'll be with the new config system - see #2377 and #499.
