### ISSUE TITLE
Autocomplete When Saving Quickmark

### ISSUE THREAD

**Issue by Jumblemuddle** [qutebrowser/qutebrowser#2538]
I like to use quickmarks to save my position in long guides / multi-page articles. It'd be nice to have a way to autocomplete the quickmark title when I'm trying to override my previous one. (Sometimes I'll forget the exact name it was called)

**Comment by The-Compiler** [comment]
I added this to #32 which collects other completions which would be nice.

**Comment by Jumblemuddle** [comment]
Excellent, @The-Compiler. Also, it looks like if I add an overriding quickmark, there are two with the same name in the system until I restart.
I'm guessing it just changes the quickmarks file, but leaves both wherever they're stored in memory.
This didn't used to be the case. (I've recently upgraded and switched to webengine)

**Comment by The-Compiler** [comment]
I think #2295 will help with that.

**Comment by Jumblemuddle** [comment]
Excellent :+1:
