### ISSUE TITLE
resume active downloads after closing the browser

### ISSUE THREAD

**Issue by holytrousers** [qutebrowser/qutebrowser#2540]
hello everyone !
i'm currently using qutebrowser v0.10.1

i just closed the window by accident with an active download.
afterwards, i couldn't find any command to resume it, or to show a list of recently downloaded files.
is it a missing feature or is it me missing some feature ?

**Comment by NoctuaNivalis** [comment]
I'm not sure if this is possible within qutebrowser, but if it's a big download, you could always continue it with `wget -c`. I seem to remember you could set the download command in qb, but I can't find the relevant setting.

**Comment by The-Compiler** [comment]
There's no persistent list of downloads yet - see #1059. In any case, that'd only make it possible to restart old downloads from scratch - not to resume them.
