### ISSUE TITLE
Unable to load page

### ISSUE THREAD

**Issue by TheAquir** [qutebrowser/qutebrowser#2544]
First - I've just discovered this great piece of software - thank you very much! As a keyboard maniac and beginner vimmer I really enjoy using it!

My problem is that I can't open certain websites in the browser, first I thought the issue is the space in the URL but it's not. If I try to open the same page in Chrome for example I get an error message (your connection is not private [...] ERR_CERT_WEAK_SIGNATURE blah blah) but I can proceed...I know this is a real issue with the site but it's available only internally so it's fine.

Can you check this please?

![2017-04-19_123647](https://cloud.githubusercontent.com/assets/15109477/25179521/2a88a0ce-2502-11e7-8168-57a6236882d1.jpg)

```
Version info

qutebrowser v0.10.1
Git commit: v0.10.1 (2017-03-08 06:25:24 +0100)
Backend: QtWebKit

CPython: 3.4.3
Qt: 5.5.1
PyQt: 5.5.1

sip: 4.17
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: no
PyQt5.QtWebEngineWidgets: no
pdf.js: 1.6.210 (bundled)
Webkit: 538.1
SSL: OpenSSL 1.0.1i 6 Aug 2014

Style: QWindowsVistaStyle
Platform: Windows-8-6.2.9200, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\library.zip\qutebrowser
Qt library executable path: C:/Qt/5.5.1/bin, data path: C:/Qt/5.5.1
OS Version: 8, 6.2.9200, , Multiprocessor Free
```

**Comment by The-Compiler** [comment]
The QtWebKit backend (which the current Windows releases use) use OpenSSL for HTTPS. The OpenSSL shipped with Qt is probably configured in a way that it doesn't support whatever algorithm is used here, i.e. there's nothing qutebrowser can do about this failing.

However, the Windows build is soon going to switch to the new QtWebEngine backend (based on Chromium), and there's a chance you'll still be able to override that error - I recently uploaded some test builds you could try:  [64 bit](https://qutebrowser.org/tmp/win-test/qutebrowser-0.10.1-windows-standalone-amd64.zip), [32 bit](https://qutebrowser.org/tmp/win-test/qutebrowser-0.10.1-windows-standalone-win32.zip)

Either way, I really suggest getting that website up to date, if you can influence that happening somehow. It's probably only a matter of time until it's completely inaccessible from other browsers as well.

**Comment by TheAquir** [comment]
Hi,

thanks - I'll give it  try.
And know that the website is "dodgy" - I know it's not the browser's fault - I thought I can set some settings as a workaround.

Have a nice day

**Comment by TheAquir** [comment]
Hi,

just to let you know, it's working with the test build 👍

Cheers

**Comment by The-Compiler** [comment]
Awesome, thanks for the update! If everything goes well, the next release will be built with that backend.
