### ISSUE TITLE
scroll bug

### ISSUE THREAD

**Issue by rezashamdani** [qutebrowser/qutebrowser#2546]
Hi,

I'm notice something odd, sometimes when scrolling from trackpad, the scrolling will be fast as the other browser, but mostly it will be too much slow than it should be.

> qutebrowser v0.10.0
Git commit: v0.10.0 (2017-02-25 21:47:56 +0100)
Backend: QtWebEngine
CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8
sip: 4.19.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.6.210 (bundled)
Webkit: no
SSL: Secure Transport, macOS Sierra (10.12)
Style: QMacStyle
Platform: Darwin-16.5.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.12.4, x86_64

**Comment by The-Compiler** [comment]
You're most likely running into [this Qt bug](https://bugreports.qt.io/browse/QTBUG-58779) which should be fixed with the next Qt release (planned for end of May).
