### ISSUE TITLE
IDN homograph phishing issues

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2547]
There recently was an interesting new [phishing approach](https://www.xudongz.com/blog/2017/idn-phishing/) which uses IDN domains with cyrillic homographs, to register domains which look like the real one. Examples:

- [xn--80ak6aa92e.com](https://xn--80ak6aa92e.com) (Apple with only cyrillic graphs)
- [xn--e1awd7f.com](https://www.xn--e1awd7f.com/) (epic.com with only cyrillic graphs)

As well as some older ideas:

- [xn--pple-43d.com](http://xn--pple-43d.com) (Apple with a cyrillic a-lookalike and ascii "pple")
- [xn--ooe-2fbc60f.com](https://xn--ooe-2fbc60f.com/) (Google with graphs which are subtly different)

# Issues

- The ones which mix cyrillic/latin graphs are easy to protect against, and Firefox/Chromium  do so. Looks like `QUrl.toDisplayString()` does not...
- The cyrillic-only ones are harder. Looks like Firefox is still discussing (?) about what to do, while Chromium [blacklists](https://chromium.googlesource.com/chromium/src/+/08cb718ba7c3961c1006176c9faba0a5841ec792%5E%21/) lookalike chars.
- I've also seen some talk about only showing the decoded version of URLs in the user's favourite language/script
- There should probably be an option to always show the decoded versions. Some users might prefer this, even if it means domains with e.g. umlauts in German look "weird". We could probably make the [QUrl flags](http://doc.qt.io/qt-5/qurl.html#ComponentFormattingOption-enum) we use with `toDisplayString()` configurable. Unfortunately there isn't a "pretty decoded with Punycode" though...
- QUrl completely gives up with the only-cyrillic apple.com above. Copying it gives us `https://www..com/` and QtWebKit (NG) can't load it at all.
- A good reason for #108? Just not sure if I want three ways of representing an URL...
- What to report as Qt bugs here?

# QUrl behavior

```
>>> from PyQt5.QtCore import QUrl
>>> QUrl('https://www.xn--e1awd7f.com/')
PyQt5.QtCore.QUrl('https://www.еріс.com/')
>>> QUrl('https://www.xn--e1awd7f.com/').toDisplayString()
'https://www.еріс.com/'
>>> QUrl('https://www.xn--e1awd7f.com/').toDisplayString(QUrl.FullyEncoded)
'https://www.xn--e1awd7f.com/'
```

# Further reading

- [Chromium fix for cyrillic-only case](https://chromium.googlesource.com/chromium/src/+/08cb718ba7c3961c1006176c9faba0a5841ec792%5E%21/)
- [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=683314)
- [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1332714) and [related FAQ](https://wiki.mozilla.org/Gerv's_IDN_Display_Algorithm_FAQ)
- [Original blogpost](https://www.xudongz.com/blog/2017/idn-phishing/)
- [Wordfence blogpost](https://www.wordfence.com/blog/2017/04/chrome-firefox-unicode-phishing/)
- [Firefox IDN display FAQ](https://wiki.mozilla.org/IDN_Display_Algorithm_FAQ) (not online yet?), [IDN Display Algorithm](https://wiki.mozilla.org/IDN_Display_Algorithm)
- [r/netsec post](https://www.reddit.com/r/netsec/comments/65csdk/phishing_with_unicode_domains/)
- [Wikipedia](https://en.wikipedia.org/wiki/IDN_homograph_attack)
- [Chrome IDN policy](https://www.chromium.org/developers/design-documents/idn-in-google-chrome)
- Safari [seems to have](https://support.apple.com/kb/TA22996?locale=en_US&viewlocale=en_US) an user-configurable whitelist of non-confusable scripts.

cc @Emdek @nowrep because this affects Otter/QupZilla as well.
cc @Carpetsmoker because of some talk on the ML about this
cc @earnestly because I *think* that's what you meant with your question in IRC earlier

**Comment by Emdek** [comment]
I would say that we should from the start try to devise solution as some sort of library (maybe even Qt independent), even if it will end up as set of rules then it would be still best to keep them in single repository.
BTW, have you tried to find such library? Maybe it already exists, it's not just an issue for browsers but also for web hosting services (I've learned about IDN issues for the first time when working for hosting company years ago).

**Comment by The-Compiler** [comment]
@Emdek If anything, this should be fixed in Qt, by making `QUrl::toDisplayString(QUrl::PrettyDecoded)` do the right thing. I won't be using (or contributing to) a new library, for the obvious distribution/deployment issues. As far as I know, no such thing exists yet. There's [uspoof in ICU](http://icu-project.org/apiref/icu4c/uspoof_8h.html), but it seems like browsers still do [additional stuff on top of that](https://cs.chromium.org/chromium/src/components/url_formatter/url_formatter.cc).

Some qutebrowser-specific thoughts I typed before your reply below:

---

I can recommend reading the Firefox bug - it has various interesting points of view on this topic.

Looking at the checks Chromium does about this however, they are both:

- very complicated (I'm not sure I'm able to implement the same without messing up somewhere, and it'd probably need a new dependency to access the low-level bits of the ICU library)
- a heuristic (only blocking a few known look-alike chars - with some 128k chars in Unicode, I wouldn't be surprised if there's more in the future)

However, unlike Firefox/Chrome, qutebrowser can be more relaxed about just showing *both* encoded and decoded variants of the URL in "unclear" cases, as its users are less likely to be confused/"intimidated" by the Punycode version. Something like this in the statusbar:

`https://аррӏе.com/foo/bar (xn--80ak6aa92e.com)`

So the question then becomes: When can we *hide* the Punycode representation? I'm unsure there about what would be reasonable easy to implement, but some first thoughts on this:

- When we only have ASCII letters, obviously
- When we only have latin letters with diacritics (e.g. umlauts), like www.öbb.at (but are those always clearly distinguishible from the normal versions?)
- Maybe when all letters in the hostname are from the same script as the TLD (i.e., http://яндекс.рф is okay, http://яндекс.ru is not)

Firefox also has some "political" thoughts there - they don't want to prefer one script over another. While I appreciate that, I think it's fine for qutebrowser to have a more pragmatic solution here, as the big part of the web is still using non-IDN domains. However, I'd appreciate some input from people using more sites which are using non-latin domains. @amosbird or @kvas-it maybe?

**Comment by NoctuaNivalis** [comment]
I like showing both the encoded and decoded URL, hiding the decoded URL when all encoded characters are within specified ranges. Default range would be ascii (possibly including some other non-confusing ranges), but you could easily mark other scripts (which are usually continuous ranges) as safe for yourself.

**Comment by Emdek** [comment]
@The-Compiler, yeah, some sort of support on ``QUrl`` level would be best and makes sense also in other, non browser centric, uses cases.
I would go for reporting it upstream, unless it was already reported there in the past.

**Comment by Emdek** [comment]
Note, it should be special option or some special method, to not change current behavior, a lot of code might depend on it.

**Comment by Emdek** [comment]
@The-Compiler, it still sounds like something that should be a special case. ;-)

**Comment by kvas-it** [comment]
I'm not currently visiting any websites in non-ascii domains but since you asked, here's my 2 cents:
- I like the idea of showing the encoded version alongside the decoded one in parentheses. It's simple and it converts a security issue into at most an inconvenience (for those who don't want to see the encoded version).
- As for selecting the "safe" ranges, at this moment it seems acceptable to just start with a conservative approach, for example whitelisting ascii and latin-1+A+B supplements (maybe also Chinese, Japanese, Hebrew, Arabic and some other stuff that looks nothing like latin letters). This is unlikely to bother anyone until there are many more IDNs in active use and until that moment a better whitelist or whitelisting approach (that takes care of legitimate Cyrillic names) can be developed.
- This approach will break when people start faking IDNs using other IDNs that look the same: nobody is going to pay attention that the encoded version is different. Hopefully something will be figured out before this threat becomes material.

**Comment by The-Compiler** [comment]
The more I think about it, the less I want to try and decide what's different enough and what isn't. Some examples coming to mind, with latin1:

- `oebb` vs. `œbb`
- `hi` vs. `hì`
- `foo.bar` vs. `foo¸bar`
- `abc` vs. `abç` vs. `ab¢`

And probably some more... In some fonts (and font sizes), those are probably pretty much indistinguishable.

Kinda tending towards the simple but most safe solution here: Simply showing the Punycode variant for everything which isn't ascii.

The next step - if needed, but I'd rather wait for feedback there - is to turn it off for international TLDs.

A third step could be to let the user whitelist things via a regex on the unicode character *name*, so you could configure qutebrowser to not show the Punycode variant if there's only ascii or `LATIN SMALL LETTER [AOU] WITH DIAERESIS` in it. Or `HIRAGANA LETTER .*`.

But those two are optional, I'd rather wait and see if they're needed.


With that, I can then let the Qt/QUrl people figure out what to do about the more complex cases where you want to avoid showing Punycode whenever possible. 😆

**Comment by maximiliankolb** [comment]
from a end-user perspective: i would love a button allowing me to limit the character set to [A-Z] + [a-z] + [0-9] + . + -. anything else should be marked bold and red/ any signal color. this way, people like me only using domains containing only latin characters have a quick and dirty option to prevent phishing attacks. obviously, this does not solve problems for all other users.

**Comment by Emdek** [comment]
@maximiliankolb, optional color sounds like a good idea, simple and effective.

**Comment by The-Compiler** [comment]
That seems too intrusive to me, FWIW. At least in German speaking countries, domains like `bücher.ch` are quite popular, and I can only guess how many people will wonder why that ü is red.

I'm also not sure if it's intuitive enough - if you see `www.apple.com` with "apple" in red, would you know it means "this is probably not apple", or would you just think "well, okay, the main part of the hostname is highlighted somehow"?

If it's something which needs to be turned off by default, then its value is pretty small.

**Comment by Emdek** [comment]
@The-Compiler, there are also other colors, plus regular expression might contain more stuff than simple ASCII letters and numbers (plus few others).

**Comment by maximiliankolb** [comment]
@The-Compiler i see your point, but as a user i'd like to have an option to highlight 'non-normal' characters (like ä, ö, ü, ß & everything else non standard). a red highlight does not mean the site won't work/ be accessible anymore.

**Comment by The-Compiler** [comment]
If you see the Punycode representation, won't that have the same effect? You'll also notice that there are special characters in it that way. And that way, I won't have to answer a "Why is that ö red" bug all few days :wink:

As said above, I really want to have something which we can turn on by default. We could of course do *both*, but I don't see the point in highlighting characters when we have the IDN URL shown.

**Comment by The-Compiler** [comment]
I opened [QTBUG-60364](https://bugreports.qt.io/browse/QTBUG-60364) and [QTBUG-60365](https://bugreports.qt.io/browse/QTBUG-60365) now. A fix for this will follow tomorrow.

**Comment by johnlane** [comment]
@The-Compiler I just installed the latest head and I can see the change you made, however it does not expose [this fake apple link](https://xn--80ak6aa92e.com) which goes to `https://xn--80ak6aa92e.com/` rather than `https://apple.com/`. [This link](https://www.xn--e1awd7f.com/), aparently to `epic.com`, identifies correctly.

**Comment by The-Compiler** [comment]
This is due to to the [Qt bug](https://bugreports.qt.io/browse/QTBUG-60364) with parsing that URL. With the QtWebEngine backend, you see "(invalid URL!)" while hovering, and "(unparseable URL!)" while visiting it. With the QtWebKit backend, you can't visit it at all due to that bug. That's all I can do for that case right now. With Qt 5.9, it shows up as the Punycode version only, once that fix is in.
