### ISSUE TITLE
A way to make favicons bigger without affecting font sizes

### ISSUE THREAD

**Issue by haasn** [qutebrowser/qutebrowser#2549]
Since 58aa1a738d86a7aca5dbc3e5658fe6891ec9b9c1 the favicon size is determined entirely by the font size, with no way to increase it further via padding etc.

But this is somewhat annoying for my use cases, because I'm using a tiny font (4pt) in order to fit as much text as possible into each tab - but this results in a favicon that's absolutely tiny. I would like the ability to make the favicon a bit bigger without (significantly) sacrificing characters.

Not sure what the best way to implement this would be. Perhaps just having a setting to scale the favicon would be enough? Since that would be independent of any specific layout.

ping @Carpetsmoker

**Comment by haasn** [comment]
Note: Just increasing the iconSize in tabbar.py almost has the desired effect, but due to the layouting done in https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/mainwindow/tabwidget.py#L749 etc. this means that the favicon now trails off the bottom edge. It would be better to rewrite the layouting code such that the favicon ends up center-aligned with the text instead, if “blindly increase the favicon size” is an intended solution.

**Comment by Carpetsmoker** [comment]
Could add a `favicon-scale` setting,  I suppose, and change it to something like:

    size = (self.fontInfo().pixelSize() - 1) * config.get('tabs', 'favicon-scale')

The default would be `1`, and you could get your larger favicons by setting it to e.g. `1.5`.

**Comment by haasn** [comment]
Yep, that seems reasonable; although note that the drawing code would also have to be updated as mentioned.
