### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by epmer** [qutebrowser/qutebrowser#2556]
qutebrowser v0.10.1 - Arch Linux
I have a problem with wrong Download directories being recommended. So let's say I press m for ~/images/a/ it works fine but if I then press l for ~/images/b/ it's still set to download directory a. Is this an error in my config or in qutebrowser?
My config looks like this:
```
set storage download-directory ~/images/a ;; hint links download
    ;m

set storage download-directory ~/images/b ;; hint links download
    ;l

set storage download-directory ~/images/c ;; hint links download
    ;p
```

**Comment by The-Compiler** [comment]
You want `:set storage remember-download-directory false` probably.
