### ISSUE TITLE
scrolling does not work on some sites.

### ISSUE THREAD

**Issue by yashar-sb-sb** [qutebrowser/qutebrowser#2557]
scrolling with `j` and `k` keys does not work properly on some sites.

for example search for "how to" in google then use `j` and `k` to scroll. reload using `r` and try again.
It's because `j` and `k` are mimicking up and down arrow key behaviours.

Version info

qutebrowser v0.10.1
Git commit: 
Backend: QtWebEngine

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.10.10-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/yashar/.config/qutebrowser
data: /home/yashar/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/yashar/.cache/qutebrowser
download: /home/yashar/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
I can reproduce this with cursor keys in Chromium, so this seems like an issue with Google's page. You can rebind the keys to use `:scroll-px` instead so they scroll via the Qt API instead of faking key presses, but that fails when there are multiple scrollable elements on a page (which is why it's not the default).
