### ISSUE TITLE
tag_name from WebEngineElement is a dict

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2569]
Got this report twice from the same user, while using the tag editor in the profile settings of https://linux.org.ru (with QtWebEngine with Qt 5.9 runtime, but PyQt 5.8.2 compiled against Qt 5.8.0):

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 448, in _js_cb_single
    callback(elem)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/mouse.py", line 154, in _mousepress_insertmode_cb
    if elem.is_editable():
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webelem.py", line 254, in is_editable
    tag = self.tag_name()
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webengineelem.py", line 91, in tag_name
    return self._js_dict['tag_name'].lower()
AttributeError: 'dict' object has no attribute 'lower'
```

Trying to reproduce this, but I need to figure out how to get to that tag editor first, without being able to read cyrillic 😆

**Comment by The-Compiler** [comment]
Haven't heard from the reporter so far... @kvas-it can you help me out with your Russian by any chance? 😆

**Comment by kvas-it** [comment]
Sure, how can I help.

**Comment by The-Compiler** [comment]
I'm trying to go to the tag editor in the profile settings on https://linux.org.ru

I found some settings:

![image](https://cloud.githubusercontent.com/assets/625793/25505455/0eb02b96-2ba2-11e7-8c92-ef1ba487c62d.png)
![image](https://cloud.githubusercontent.com/assets/625793/25505473/1d2fa2c8-2ba2-11e7-9d10-bf3472e4af75.png)
![image](https://cloud.githubusercontent.com/assets/625793/25505484/31cf38f6-2ba2-11e7-945c-5e497ae82289.png)
![image](https://cloud.githubusercontent.com/assets/625793/25505490/3b82d10a-2ba2-11e7-8aab-7047933de341.png)

but nothing which looks like a tag editor to me...

**Comment by kvas-it** [comment]
There doesn't seem to be anything related to tags in those screenshots.
What exactly is this "tag editor" supposed to do?

**Comment by The-Compiler** [comment]
I have no idea... that's all I got in the crash editor.

The only tag related thing I see is this, when creating a new post:

![image](https://cloud.githubusercontent.com/assets/625793/25519509/5de008f2-2bf8-11e7-9f9c-2a6afa73d75b.png)

But that seems to work fine for me.

**Comment by kvas-it** [comment]
Yes, I suppose this could be called a tag editor. But I guess that's not the one if it's not in the profile settings. I'll register and take a look.

**Comment by kvas-it** [comment]
There are some tags that you enter in the message filtering settings (https://www.linux.org.ru/user-filter). Can it be this?
![user-filter](https://cloud.githubusercontent.com/assets/1179248/25523931/ce9e90a8-2c08-11e7-93bb-a748437e968c.jpg)

**Comment by The-Compiler** [comment]
That is it! When clicking the area from the right to the button, this is what JS serializes:

```json
{
  "id": 0,
  "tag_name": {},
  "outer_xml": "<form action=\"\/user-filter\/favorite-tag\" method=\"POST\">\n  <input type=\"hidden\" name=\"csrf\" value=\"CTAPpLiyHUKJHFKKvvayfA==\">\n<label>\u0422\u0435\u0433: <span role=\"status\" aria-live=\"polite\" class=\"ui-helper-hidden-accessible\"><\/span><input autocapitalize=\"off\" data-tags-autocomplete=\"data-tags-autocomplete\" type=\"text\" name=\"tagName\" id=\"newFavoriteTagName\" size=\"20\" maxlength=\"80\" value=\"\" class=\"ui-autocomplete-input\" autocomplete=\"off\"><\/label>\n  <button type=\"submit\" name=\"add\" class=\"btn btn-default\">\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c<\/button>\n  <\/form>",
  "class_name": "",
  "rects": [
    {
      "top": 299.859375,
      "right": 834,
      "bottom": 366.125,
      "left": 14,
      "height": 66.265625,
      "width": 820
    }
  ],
  "attributes": {
    "action": "\/user-filter\/favorite-tag",
    "method": "POST"
  }
}
```

Logging the tagName from JS: `[object HTMLInputElement]`

**Comment by The-Compiler** [comment]
Oh my... it's because it has a child element named `tagName`, so `.tagName` on it gives us that child element. Gnah, JavaScript.

Thanks for finding the right page @kvas-it, now I only have to find out how to tell JavaScript to give me the right thing.

**Comment by The-Compiler** [comment]
I added a workaround for this and some typechecks for stuff returned from JavaScript. I already found some more funny corner cases - let's wait for crash reports for more 😆

**Comment by kvas-it** [comment]
Let's hope nobody makes a form with both "tagName" and "nodeName" as field
names :D

**Comment by The-Compiler** [comment]
Yeah, that's why there's a fallback with an empty string... nothing more I can do about it.
