### ISSUE TITLE
How to get the version info in a mac

### ISSUE THREAD

**Issue by runjaj** [qutebrowser/qutebrowser#2574]
I have just filled a bug report and noticed that you have this:

""

I think that you should add that if you are using the mac qutebrowser.app, the way to get the version info is to type in a terminal '/Applications/qutebrowser.app/Contents/MacOS/qutebrowser --version'.

**Comment by The-Compiler** [comment]
Or just do `:open qute:version`, which is usually easier. I'd prefer to keep the message short.

**Comment by runjaj** [comment]
Ok. Maybe you could add the :open part to qute:version. I thought it was just :qute:version and it didn't work. But maybe everybody knows it but me, I've been using qutebrowser for just a few days. 

Thanks for such a great work and answering so fast.

**Comment by The-Compiler** [comment]
Good point! I adjusted the text to mention `:open`.
