### ISSUE TITLE
Qt C++ wishlist

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2576]
This is intended to become a list of C++ bugs and feature requests in Qt (QtWebKit/QtWebEngine included) which directly affect qutebrowser in some way.

For now, see the [list of unfixed Qt issues reported by me](https://bugreports.qt.io/browse/QTBUG-59867?jql=reporter%20%3D%20%22Florian%20Bruhin%22%20and%20status%20!%3D%20closed%20order%20by%20created%20desc)

**Comment by jgkamat** [comment]
Looks like this is getting fixed, but for reference [QTBUG-60673](https://bugreports.qt.io/browse/QTBUG-60673)

**Comment by The-Compiler** [comment]
This isn't really actionable, so I'm closing it.
