### ISSUE TITLE
Caret/visual mode with QtWebEngine

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2577]
Is there really no issue for this open yet, or is it just me who can't find it? 😆 

This mostly means porting the Chromium [caret browsing extension](https://cs.chromium.org/chromium/src/ui/accessibility/extensions/caretbrowsing/) ([web store](https://chrome.google.com/webstore/detail/caret-browsing/fklpgenihifpccgiifchnihilipmbffg)) so qutebrowser can run the javascript. It'd be nice if the cursor would be painted with Qt widgets in Python instead of messing with webelements, though.

**Comment by jgkamat** [comment]
Self assigning because I want to work on this eventually, but I'm super busy, so it might be a while before I actually start work on it. If someone else wants to work on it, just let me know and I'll give you what I have and pass it on :)

**Comment by Waples** [comment]
I cannot help, but I'm really, really really waiting for this (trying to have a non-mouse workflow ;))

**Comment by artur-shaik** [comment]
@jgkamat hi, have you any progress? I just thought to look how it can be implemented.

**Comment by jgkamat** [comment]
@artur-shaik , no, sorry,  I haven't started on this yet. As mentioned in the original post, the easiest way to do this would be to port the caret browsing extension to qb, and once that's done, adding bindings to the original caret commands.

**Comment by artur-shaik** [comment]
@jgkamat ok, thanks. Will check it.

**Comment by artur-shaik** [comment]
Ok, some progress on porting chrome extension into qutebrowser. I think, issue can be assigned to me.
![qute_caret_demo](https://user-images.githubusercontent.com/4862907/32839000-0f9adc24-ca3d-11e7-952b-4e2385753484.gif)

**Comment by The-Compiler** [comment]
@artur-shaik GitHub doesn't allow to assign issues to people who aren't member of the qutebrowser organization - but I just sent you an invite since you're clearly qutebrowser's caret mode expert 😆

**Comment by artur-shaik** [comment]
@The-Compiler nice, thanks from caret expert 😄

**Comment by nemanjan00** [comment]
Any progress?

**Comment by jgkamat** [comment]
@nemanjan00 see https://github.com/qutebrowser/qutebrowser/pull/3348, I'm going to link the PR and this issue now.

**Comment by nemanjan00** [comment]
Subscribed to PR. Can't wait to see this implemented... 

Decided to rely less on mouse so I got rid of it completly and this will be huge help for me :D

**Comment by The-Compiler** [comment]
Aaaand it's merged! 🎉
