### ISSUE TITLE
Access public networks

### ISSUE THREAD

**Issue by eyadsibai** [qutebrowser/qutebrowser#2584]
when you try to access public networks sometimes you have to accept an agreement or the terms and conditions of the use before being able to browse.

If I am using qutebrowser it doesn't forward me or open the site to do that.

```qutebrowser v0.10.1
Git commit: v0.10.0-352-g9d2734ff6 (2017-04-16 13:15:15 +0200)
Backend: QtWebEngine (Chromium 53.0.2785.148)

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.24-1-MANJARO-x86_64-with-glibc2.3.4, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=17.0.1
DISTRIB_CODENAME=Gellivara
DISTRIB_DESCRIPTION="Manjaro Linux"

--- /etc/os-release ---
NAME="Manjaro Linux"
ID=manjaro
PRETTY_NAME="Manjaro Linux"

--- /etc/manjaro-release ---
Manjaro Linux

Paths:
config: /home/eyad/.config/qutebrowser
data: /home/eyad/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/eyad/.cache/qutebrowser
download: /home/eyad/Downloads
runtime: /run/user/1000/qutebrowser
```

**Comment by The-Compiler** [comment]
Works fine here, and I don't see how something qutebrowser does would prevent that.

What exactly do you do, and what exactly happens?

**Comment by eyadsibai** [comment]
I try to open a webpage and I get SSL handshake error. Instead of forwarding me to the webpage

**Comment by The-Compiler** [comment]
You'll need to open a non-https page - as far as I know, that's the same in any other browser.

**Comment by eyadsibai** [comment]
thanks I will check next time

**Comment by The-Compiler** [comment]
I just checked with one - looks like Firefox/Chromium show a "WiFi sign-in required" page. As far as I know, that involves talking to Google servers for connectivity checks, which is something I'd rather not have - and I also don't think it's worth the trouble to reimplement this in qutebrowser's code.

**Comment by eyadsibai** [comment]
Sure but any workaround you suggest?

**Comment by The-Compiler** [comment]
Yes - visiting a non-HTTPS page :wink:

http://http.badssl.com/ is an example.
