### ISSUE TITLE
Error after editing content in external editor

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#2590]
Sometimes, but not always, this happens:

- click inside a text area
- execute `open-editor`
- type type type, save, and quit
- get an error, and the text area is empty!

The error doesn't stay on the screen long, so I can't remember what exactly it is (it might be the "Could not get text from focused element" error).

Also, if I try again, sometimes it works (and especially if I refresh the page).

Basically, something's going wrong, but I can't figure out what, which means I can't provide steps to reproduce it (sorry). Next time it happens, I'll at least try to remember the error message. In the meantime...

**Question 1**: Anyone else experience this? I'm using the webengine backend. When I used to use webkit, this never happened, so it could be engine-specific.

**Question 2**: After quitting my editor, qutebrowser deletes the tmp file that contained all the text I wrote, which is extremely frustrating, because it means I've potentially lost a *ton* of text. As a workaround, is there an easy way to disable deletion of tmp files? I don't mind if I have dozens or even hundres of `qutebrowser-editor-xxxxxx` files in `/tmp` -- they don't bother me, and they'll be removed next time I restart my computer anyway.

**Comment by The-Compiler** [comment]
I haven't seen this myself, and there's not much I can do without at least seeing the error, but ideally a full report :wink:

With #2506 those shouldn't get deleted on most errors anymore.

**Comment by brianbuccola** [comment]
I managed to reproduce it by just opening and closing my editor on two different text areas many times, until the error happened. The error is:

> The editor exited with status 1.

But I still can't figure out exactly when or why the error happens. I thought it might have to do with clicking somewhere else in the webpage/exiting insert mode while the editor is still open, but I don't think that's related (that causes no problems usually).

**Comment by NoctuaNivalis** [comment]
I've had a similar problem before. I solved it by switching from (vim inside) urxvtc to st. Probably had something to do with urxvtc being just a client.

**Comment by brianbuccola** [comment]
Thanks. I'm actually using st already. Here's what I've got

```conf
editor = st -e vim "{}"
```

**Comment by NoctuaNivalis** [comment]
`editor = st -e nvim "{}"` here, so it's probably not editor related.

**Comment by brianbuccola** [comment]
OK, this is really weird: it seems to be totally random. Here is what I did.

- execute `open-editor` inside a text area
- type `1`, save, and quit
- repeat the steps, replacing *n* with *n+1*.

I got up to 18 (type `18`, save, and quit), and then the error happened, which meant the text area remained as 17.

I then opened the editor again, typed `18` as before, saved, and quit, and this time it worked. I did nothing differently.

I did this experiment several more times, and I reached different numbers each time:

- 18
- 7
- 8
- 2

I have no idea what is going on.

**Comment by The-Compiler** [comment]
Can you please reproduce it with `--temp-basedir` (with `editor` set appropriately), reproduce it, and then do `:report`?

**Comment by brianbuccola** [comment]
Done.

**Comment by The-Compiler** [comment]
Looks like `st` writes `Couldn't read from shell: Input/output error` and dies. That's [coming from here](http://git.suckless.org/st/tree/st.c#n809). The manpage for `read` says:

```
       EIO    The  process  is a member of a background process group attempting to read from its con‐
              trolling terminal, and either the calling thread is blocking SIGTTIN or the  process  is
              ignoring SIGTTIN or the process group of the process is orphaned. This error may also be
              generated for implementation-defined reasons.
```

(at least for my glibc).

Either way, this seems like a st bug, not a qutebrowser one. I'd suggest using another terminal emulator until #2506 is in.

**Comment by brianbuccola** [comment]
Damn. OK, thanks for taking the time.

It's strange, though, that @NoctuaNivalis was having the same problem with rxvt-unicode, and (presumably) no longer has the problem with st!

**Comment by The-Compiler** [comment]
I'm guessing @NoctuaNivalis had a slightly different problem - qutebrowser reading back the file immediately because urxvtc exits immediately. That would've happened every time though, not just sometimes.

As for the error - I can actually reproduce this by running `st -e vim /tmp/x` in another terminal.

**Comment by brianbuccola** [comment]
That reproduces it for me as well. However, you'll notice that the file `x` appears to get saved appropriately, despite the error from st.

```bash
% ls /tmp/x
ls: cannot access '/tmp/x': No such file or directory
% st -e vim /tmp/x
Couldn't read from shell: Input/output error
% cat /tmp/x
foo
```

So this would explain why qutebrowser sometimes manages to add the content to the text area -- but why not always? That is, if st *always* produces an error, why does qutebrowser *only sometimes* mention it? Shouldn't it either always mention the error, or never?

**Side remark**: If I `touch /tmp/x` first, then `st -e vim /tmp/x` does not return any error. However, I guess this means that qutebrowser does not first create the tmp file, right?

**Comment by The-Compiler** [comment]
I see it coming from st *sometimes*, even if the file already exists:

```
[florian@hooch ~]$ st -e vim /tmp/x
[florian@hooch ~]$ st -e vim /tmp/x
[florian@hooch ~]$ st -e vim /tmp/x
[florian@hooch ~]$ st -e vim /tmp/x
Couldn't read from shell: Input/output error
```

```
[florian@hooch ~]$ touch /tmp/x
[florian@hooch ~]$ st -e vim /tmp/x
Couldn't read from shell: Input/output error
[florian@hooch ~]$ st -e vim /tmp/x
[florian@hooch ~]$ 
```

**Comment by NoctuaNivalis** [comment]
Can't reproduce it in a terminal here, but I modified my st quite a bit.

**Comment by brianbuccola** [comment]
Yeah, `touch` seems to have been a false flag. I'm still getting the error. In fact, I get it every single time. That's annoying, but oh well. I may just use `gvim` instead, for now. Anyway, thanks!

**Comment by 6gk** [comment]
@brianbuccola I know this is a very old thread, but might I ask whether you managed the fix the issue with st? I don't mean using a workaround like gvim btw.

**Comment by brianbuccola** [comment]
@6gk Nope, I switched to gvim and haven't switched back. The error was too costly and annoying.
