### ISSUE TITLE
`navigate next/prev` doesn't handle URLs that don't provide the host address

### ISSUE THREAD

**Issue by pkill-nine** [qutebrowser/qutebrowser#2606]
e.g when `<a href='subpage/page2'>` rather than `<a href='http://hostname.com/subpage/page2'>`

It instead goes to something like `http://hostname.com/subpage/page1/subpage/page2`

**Comment by lahwaacz** [comment]
There is a difference between `subpage/page2` and `/subpage/page2`, according to [this](http://stackoverflow.com/a/21828923/4180822) the former should be relative to the current path so this behaviour seems correct.

**Comment by The-Compiler** [comment]
Probably that website uses `<base>` or the `Content-Base:` header instead of just using `/subpage/page2` - see #739.
