### ISSUE TITLE
Make qutebrowser work better with HDPI displays

### ISSUE THREAD

**Issue by stevenroose** [qutebrowser/qutebrowser#2608]
I have a Dell XPS 15 with 4K display. While almost all applications that I run here (Arch with GNOME Shell) are very well adapted to the hdpi display, qutebrowser is not. Even though I can easily zoom in to 150%, the link tags ("f") are still displayed very small and hard for me to distinguish.

Since I couldn't find anything while searching for "hdpi" in the repo or on Google, I suppose this issue has not come up before.

**Comment by The-Compiler** [comment]
See #1585. Turning on Qt's automatic scaling (the equivalent to `export QT_AUTO_SCREEN_SCALE_FACTOR=1`) caused some trouble for some people, so I turned it off again. If setting that environment variable doesn't make any difference, you can still bump up the fonts in the config, e.g. via `:set fonts hints` for the hints (link tags).
