### ISSUE TITLE
Disable keybindings on certain sites

### ISSUE THREAD

**Issue by munyari** [qutebrowser/qutebrowser#2614]
Apologies if this is an already implemented/requested feature, but I couldn't find anything. It would be great if you could specify keybindings that should be ignored on a given site. Many webapps (such as Github) have their own keybindings that conflict with qutebrowser bindings. This feature is present in tools such as vimium and vimfx.

**Comment by jgkamat** [comment]
There are three things that can help you currently that I know about:

1) `:set input forward-unbound-keys` will forward unbound keys from normal mode to insert mode. You can set this to `all` if you want that behavior.
2) Insert/Passthrough mode. If you enter insert mode `i` or passthrough mode `ctrl-v`, you can temporarily send all your input to the current webpage, until you hit `<esc>`. This is the method I personally use. For example, when I search duckduckgo, I search, then I enter insert mode (to use ddg's hotkeys) and leave insert mode if I want to use qb's keybinds again. 
3) Use `:fake-key` to send keys manually. You can bind any key sequence to a key you want to press via this command.

To get the behavior you are looking for exactly though, you probably need to wait for #499 to finish, which will (probably) allow you to set keybinds per website.

**Comment by The-Compiler** [comment]
I have nothing to add to what @jgkamat said :wink:

**Comment by munyari** [comment]
Thanks @jgkamat!

**Comment by munyari** [comment]
Unfortunately passthrough/insert mode doesn't seem to work. `C-V s` on github doesn't focus the search bar for example.

**Comment by The-Compiler** [comment]
Works fine here.

**Comment by jgkamat** [comment]
@munyari it seems to work for me with the new backend, but it seems to be broken for me on qtwebkit (the old qutebrowser backend). Can you see if that method works on duckduckgo (which has it's shortcuts work on both backends: https://duckduckgo.com/?q=qutebrowser&t=hd&yeg=B&ia=software

(Try pressing `i` or `ctrl-v` and using the `/` shortcut to select the search bar).

If that works for you, qtwebkit is probably not compatible with whatever github is using for it's shortcuts, and I would reccomend using an up to date webkit via `qtwebkit-ng` or the new `webengine` backend.

**Comment by munyari** [comment]
Hmm... Don't know what the issue was before seems to be working now. Thanks again!

**Comment by amzon-ex** [comment]
> Insert/Passthrough mode. If you enter insert mode i or passthrough mode ctrl-v, you can temporarily send all your input to the current webpage, until you hit `<esc>`.

What if one of the key binds on the browser *is* `<esc>`? This is often there in websites for convenience - say to exit a dialog or overlay. Doing a bunch of workaround seems to take away this convenience, don't you think?

**Comment by The-Compiler** [comment]
@amzon-ex that's why the binding to leave insert mode is shift-esc nowadays, and shift-esc in insert mode also sends esc to the website.

**Comment by amzon-ex** [comment]
@The-Compiler 
Ah, great little detail I've missed, thank you!

Could you be kind and also tell me if it is possible to enable passthrough mode by default when the browser starts?

**Comment by The-Compiler** [comment]
@amzon-ex no, but there is `input.forward_unbound_keys`, so you can remove/remap default bindings if you prefer.

**Comment by amzon-ex** [comment]
@The-Compiler 
I see, thanks again. Will try that out. For now, passthrough mode seems like the option for me.
