### ISSUE TITLE
Reposition hint labels when scrolling

### ISSUE THREAD

**Issue by d125q** [qutebrowser/qutebrowser#2616]
Is it possible for hints mode to listen to scroll events so that hint labels can be repositioned appropriately?  The same could be done when a hinted element is moved by the web page.  If no elements are left visible, hints mode should be left.

I am willing to work on this but I might require some guidance (e.g., how to listen to scroll events within Python).

**Comment by The-Compiler** [comment]
See #1928 - there are already signals in Python for changed scroll events, but they're not exposed nicely via the tab API yet. See `scroll_pos_changed` in `qutebrowser/browser/webkit/webview.py` and `scrollPositionChanged` in `qutebrowser/browser/webengine/webenginetab.py` - I might be able to post some more details later, have to leave right now.
