### ISSUE TITLE
Clicking bandcamp play button with hints does nothing

### ISSUE THREAD

**Issue by nicodebo** [qutebrowser/qutebrowser#2619]
## Issue

I can't play music from bancamp.com with the url mode. It only works with the mouse.

## How to reproduce

* For exemple go on the following link <https://ichiro.bandcamp.com/album/610452-ok>
* Activate hint mode and click the play button

## Expected behavior

The music should play.

## Qutebrowser version info

```
qutebrowser v0.10.1
Git commit:
Backend: QtWebKit

CPython: 3.6.1
Qt: 5.8.0
PyQt: 5.8.2

sip: 4.19.2
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.10.13-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version:

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/debz/.config/qutebrowser
data: /home/debz/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/debz/.cache/qutebrowser
download: /home/debz/Downloads
runtime: /run/user/1000/qutebrowser
```

**Comment by The-Compiler** [comment]
Did you install the optional dependencies (`pacman -Qi qutebrowser`)?

**Comment by nicodebo** [comment]
Thank you for your quick reply.
All the gst* dependencies are installed.

Here is the output of the pacman query command:
```
╰─$ pacman -Qi qutebrowser
Name            : qutebrowser
Version         : 0.10.1-1
Description     : A keyboard-driven, vim-like browser based on PyQt5 and QtWebKit
Architecture    : any
URL             : http://www.qutebrowser.org/
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : desktop-file-utils  hicolor-icon-theme  libxkbcommon-x11  python-jinja
                  python-pygments  python-pypeg2  python-pyqt5>=5.2  python-yaml  qt5-base>=5.2
                  qt5-webkit  xdg-utils
Optional Deps   : python-colorlog: colored logging output
                  gst-libav: media playback [installed]
                  gst-plugins-base: media playback [installed]
                  gst-plugins-good: media playback [installed]
                  gst-plugins-bad: media playback [installed]
                  gst-plugins-ugly: media playback [installed]
                  pdfjs: displaying PDF in-browser
                  qt5-webengine: experimental backend [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 6.37 MiB
Packager        : Pierre Neidhardt <ambrevar@gmail.com>
Build Date      : mer. 08 mars 2017 08:59:49 CET
Install Date    : mer. 08 mars 2017 23:54:33 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

I'm not sure if it is relevant but, I can play music well with the hint mode on soundcloud or mixcloud.

**Comment by The-Compiler** [comment]
Hm, it's entirely possible that broke with legacy QtWebKit somehow - how do things look when you install `qt5-webkit-ng` or start with `--backend webengine`?

**Comment by nicodebo** [comment]
I use the webengine backend for my daily use.
Bandcamp does not work, neither with webengine nor qt5-webkit whereas soundcloud work with both.

I didn't try with qt5-webkit-ng. Are they any particular steps I should follow to replace qt5-webkit with qt5-webkit-ng ?

**Comment by The-Compiler** [comment]
Just install qt5-webkit-ng and let it replace qt5-webkit. Other than private browsing not fully working (which will be fixed in the next qt5-webkit-ng release) it's a drop-in replacement.

Now I remember someone had problems with Bandcamp too recently (@commagray I think?), while it's running fine for me. Out of curiosity, are you using PulseAudio?

**Comment by nicodebo** [comment]
I've just installed qt5-webkit-ng, but the sound still does not play with it.
I don't use pulseaudio.

**Comment by The-Compiler** [comment]
When you start in a terminal with `--debug --temp-basedir https://ichiro.bandcamp.com/album/610452-ok`, do you see anything interesting in the output when you try to play it? Can you also do `:report` after that please?

**Comment by nicodebo** [comment]
I don't have any error or warning appearing in the terminal in debug mode when clicking the play button. A report has been sent.

I also tried qutebrowser on another computer and the same issue happen.

Let me know if you want me to try other things.

**Comment by The-Compiler** [comment]
Looks like clicking the play button with hints doesn't work - does anything change when clicking it using the mouse?

**Comment by d125q** [comment]
The same happens using the latest Firefox with [VimFx](https://github.com/akhodakivskiy/VimFx/commits/master).

**Comment by Geemili** [comment]
I get a similar thing on `toggl.com`.  Don't have time for an in depth report right now, but it looks like Toggl doesn't use buttons, but divs that you can click. Don't know if that's important.

**Comment by The-Compiler** [comment]
@nicodebo Oh, you already said "It only works with the mouse." in your original report - sorry, missed that!

@d125q Good to know - I wonder what Bandcamp is doing there...

@Geemili Are hints actually displayed at all there? If not (what I'd expect with `div` elements), see #178.

**Comment by NoctuaNivalis** [comment]
On bandcamp, it's a `a` without a href, with a `div` inside. I haven't looked at the javascript bindings though, it's minified.

**Comment by The-Compiler** [comment]
Relevant logs:

```
09:45:01 DEBUG    webelem    webelem:click:390 Clicking <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a role="button" aria-label="Play/pause"><div class="playbutton"></div></a>'> with click_target ClickTarget.normal, force_event False
09:45:01 DEBUG    webelem    webelem:click:398 Clicking via JS click()
```

**Comment by NoctuaNivalis** [comment]
Oh, it's probably because Qb clicks on the `a` element, but the event listener is the `click` of the `div` inside.

**Comment by The-Compiler** [comment]
This helps:

```diff
diff --git a/qutebrowser/browser/webelem.py b/qutebrowser/browser/webelem.py
index ec523e0e4..13b43359c 100644
--- a/qutebrowser/browser/webelem.py
+++ b/qutebrowser/browser/webelem.py
@@ -294,7 +294,7 @@ class AbstractWebElement(collections.abc.MutableMapping):
     def is_link(self):
         """Return True if this AbstractWebElement is a link."""
         href_tags = ['a', 'area', 'link']
-        return self.tag_name() in href_tags
+        return self.tag_name() in href_tags and 'href' in self
 
     def _mouse_pos(self):
         """Get the position to click/hover."""
```

because it causes qutebrowser to fake a click using Qt events instead:

```
10:17:12 DEBUG    webelem    webelem:click:390 Clicking <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a role="button" aria-label="Play/pause"><div class="playbutton"></div></a>'> with click_target ClickTarget.normal, force_event False
10:17:12 DEBUG    webelem    webelem:is_editable:238 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a role="button" aria-label="Play/pause"><div class="playbutton"></div></a>'>
10:17:12 DEBUG    webelem    webelem:_click_fake_event:324 Sending fake click to <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a role="button" aria-label="Play/pause"><div class="playbutton"></div></a>'> at position PyQt5.QtCore.QPoint(55, 320) with target ClickTarget.normal
```

I'll need to leave right now, but I can push that after checking how it affects the other callers of `is_link`.

cc @jgkamat

**Comment by The-Compiler** [comment]
I think this is something reasonable to do even for the other callers, so I pushed it now.
