### ISSUE TITLE
load tabs lazily ob browser startup

### ISSUE THREAD

**Issue by edio** [qutebrowser/qutebrowser#2620]
I usually have around 100 buffers opened in browser

While using FF+5dactyl this never was an issue, because Firefox loads tabs lazily, only after tab is activated.

qutebrowser eagerly loads all tabs. This causes following issues:

1. slow startup, unresponsive browser during startup
2. huge load (my laptop fans start screaming when I start qutebrowser)
3. all media in all tabs starts playing at once

Afaik, Chrome too already has the feature of loading tabs lazily.

Would be great, to have same behavior in qutebrowser.

**Comment by The-Compiler** [comment]
See #67.
