### ISSUE TITLE
Add --implicit option to :tab-clone

### ISSUE THREAD

**Issue by grensjo** [qutebrowser/qutebrowser#2624]
When a tab is cloned using `gC`, I think the new tab should be considered related to the original tab. This is also how "Duplicate tab" behaves in both Chromium and Firefox/Tab Mix Plus by default – the duplicated tab is added next to the original.

Thus it would be great if `:tab-clone` had an `--implicit` option, just like `:open` has.

**Comment by The-Compiler** [comment]
Sounds good, and it should be quite straightforward to add - want to work on a pull request by any chance? :wink:

**Comment by grensjo** [comment]
Sure, sounds like fun! :)

Do you think the new flag should be added to the default key binding for `gC`?

**Comment by The-Compiler** [comment]
Hmm, good question - I wonder if it'd be better to just drop the `explicit=True` from `:tab-clone` altogether and see if someone complains about it. I agree it'd make more sense to open it next to the current tab by default.

**Comment by grensjo** [comment]
Hmm, that does sound like a cleaner solution. I cannot see any reason why one would want any other behavior, but then again, [you never know](https://xkcd.com/1172/)...

**Comment by The-Compiler** [comment]
Fine with me then - I'll remove it once I'm out of the lecture I'm sitting in, unless you're quicker with a PR 😆

**Comment by The-Compiler** [comment]
I got side-tracked for a bit, but now I removed `explicit=True` from `:view-source` and `:tab-clone` - let's see if anyone complains!

**Comment by grensjo** [comment]
Great!

By the way, I just noticed this issue also exists for `:navigate up --tab`, `:navigate increment --tab` and `:navigate decrement --tab`, for which the new tabs are opened explicitly. This is also inconsistent with `:navigate prev --tab` and `:navigate next --tab`, for which the tabs are implicitly opened.

I created a PR fixing this, see #2628.
