### ISSUE TITLE
Weird tab scroll reset behaviour

### ISSUE THREAD

**Issue by throwaway217** [qutebrowser/qutebrowser#2632]
I abstained from reporting this since it's also present on chromium with any vim plugin enabled but it has become unbearable and I'm wondering if there is any way I can make it stop.

In order to replicate this you can do the following:
- new instance of qutebrowser with webengine
- open a web page that has a link somewhere at the top, example:
https://www.fanfiction.net/s/7406866/1/To-the-Stars
- scroll down
- open a new tab with :open -t
- go back to the first page with shift j or k
- it's at the top again (edited for clarity)

**Comment by The-Compiler** [comment]
What do you mean with "it's not at the top again"? Seems fine to me, the page is still scrolled down as expected.

**Comment by throwaway217** [comment]
>it's not at the top again
Sorry that step is: 
- it's at the top again

Here's a recording:
https://p.lewd.es/tbujn.webm

**Comment by The-Compiler** [comment]
Does `:set ui hide-statusbar false` fix it? If so, this is a duplicate of #2236.

**Comment by NoctuaNivalis** [comment]
I can't reproduce this, could you give us your version info & perhaps all of your ui settings?

**Comment by throwaway217** [comment]
Yes, setting ui hide-statusbar to false solves this. Closing as it's a duplicate.
