### ISSUE TITLE
git troubles

### ISSUE THREAD

**Issue by guest73** [qutebrowser/qutebrowser#2637]
Why "Add your reaction" button in git does not work when opening page in qutebrowser? Is it blocked by addblock or something?

**Comment by The-Compiler** [comment]
What backend are you using (`:open qute:version`)? What distribution are you on? Did you change the user-agent from its default value?

**Comment by guest73** [comment]
Just wanted to edit my previous post but edit button does not work as well.

**Comment by guest73** [comment]
And no, I did not touch user-agent. Don't even know where I can do this.

**Comment by guest73** [comment]
Let's test if I can remove this post.

**Comment by guest73** [comment]
Removal does work though.

**Comment by grensjo** [comment]
I had this problem as well when I was using the QtWebKit backend (which is the default). You could try launching qutebrowser with `qutebrowser --backend webengine` to use the QtWebEngine backend instead, and see if that solves the problem.

**Comment by The-Compiler** [comment]
Looks like GitHub now requires [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) to work correctly. I wonder, do they really [not care](http://caniuse.com/#feat=promises) about not working in Internet Explorer anymore either? 😆 

Apart from switching to QtWebEngine like @grensjo mentioned (which [will soon be the default](https://github.com/qutebrowser/qutebrowser/issues/2335)), you should also be able to install `qt5-webkit-ng` which is a more up-to-date drop-in alternative for `qt5-webkit`.

Note however that (until its [next release](https://github.com/annulen/webkit/issues?q=is%3Aopen+is%3Aissue+milestone%3Av5.9.0-alpha)) private browsing won't work there.

**Comment by guest73** [comment]
Ok, will try your suggestions. Thank you guys.
