### ISSUE TITLE
Javascript can no longer be disabled on the latest git build

### ISSUE THREAD

**Issue by throwaway217** [qutebrowser/qutebrowser#2638]
Even though I have allow-javascript set to false in the config, the latest git build starts with javascript enabled, :set content allow-javascript false only works with --temp-basedir

I'm also on qt5-webengine 5.9beta3 and I upgraded protobuf today around the time this appeared. qt5-webengine 5.8 from the archlinux repos appears to have been rebuilt for protobuf. I don't know if this has anything to do with anything, just adding it here.

Edit: Just tested 0.10.1 with qt5-webengine 5.9beta3, works fine.

Here is my qutebrowser.conf
http://ix.io/tWj

**Comment by The-Compiler** [comment]
Looks like this broke when private browsing was implemented for QtWebEngine. I can reproduce it with:

```
python -m qutebrowser --backend webengine --temp-basedir -s content allow-javascript false 'http://javatester.org/javascript.html' ':open -p http://javatester.org/javascript.html'
```

**Comment by The-Compiler** [comment]
Turns out I'm not the only one confused by Qt's docs there:

https://bugreports.qt.io/browse/QTBUG-57349

submitted a fix now:

https://codereview.qt-project.org/#/c/194842/

a qutebrowser fix should follow later today.
