### ISSUE TITLE
Setting to enable jumping to last opened tab when running `:tab-focus <current tab number>`

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2643]

**Comment by The-Compiler** [comment]
Why?

**Comment by pkillnine** [comment]
This is a customizable behaviour in a lot of tabbed software, such as i3wm and Weechat.

**Comment by The-Compiler** [comment]
Ah, I see. There's already `:tab-focus last` (bound to `Ctrl-Tab`) but I guess having the same behavior when trying to select the active tab makes sense.

Why a config option though, and not just make that the default behavior?

**Comment by pkillnine** [comment]
I guess just because some people might not like that behaviour, also I was thinking of i3wm which makes it optional

**Comment by pkillnine** [comment]
I suppose this could be done without config option, then if someone complains add it in

**Comment by The-Compiler** [comment]
@pkillnine that was fast 😆
