### ISSUE TITLE
'j' not mapping to down-key in Godzilla game

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#2645]
While the infamous Godzilla game of the no-connection error of Webengine recognizes my vim up key 'k' by successfully making Godzilla jump, it unfortunately fails to recognize my vim down key 'j'. Therefore I'm unable to successfully make Godzilla lower his head.

As a result, I'm unable to conveniently dodge the flying Pterosaurs by lowering the head of Godzilla. As a result, Godzilla tends to die more often as depicted in the figure below.

![shit2](https://cloud.githubusercontent.com/assets/8865788/26180708/fae407ce-3b7b-11e7-9db8-873ef596ec60.png)

Another more critical problem is the fact that the down-key is also used to accelerate Godzilla's descend upon a previously successful jump. This is necessary when as Godzilla's running speed increases, and gaps between obstacles shrink. The result of not having the down 'j' key work is Godzilla's death upon landing on a tree.

![shit](https://cloud.githubusercontent.com/assets/8865788/26180537/20dd3f64-3b7b-11e7-9db5-e5f36e8405ab.png)

So far the only solution is to use the down arrow keys only. However, this is very inconvenient, and I see no reason why the convenient 'j' key is not working.

I am using Qt5.7.1-r3, with PyQt5.8.2 and latest Qutebrowser from Git repo.

**Comment by The-Compiler** [comment]
Thanks for the detailed (and funny 😆) report! This is indeed strange - the only explanation I have is that it gets down presses differently somehow. Merging this into #1209 though.

source of the game: https://chromium.googlesource.com/chromium/src.git/+/master/components/neterror/resources/offline.js
