### ISSUE TITLE
Huge history entries starting with data:text/html

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#2646]
qutebrowser v0.10.1
Backend: QtWebEngine

I just ran into an issue the other day. 5-6 of those entries got added to my history file: they all start with

	data:text/html;charset=UTF-8,%3C%21DOCTYPE%20html%20PUBLIC%20%22-

And then contain hexadecimal scribbles for 300kb+. Those entries were "Page not found" pages.

When using the `:open` command and typing some letters, Qutebrowser would become insanely slow when the text would match one of those entries. Which makes sense.

I am not sure what happened and I am not able to reproduce, but it looks like somehow the wrong data got saved instead of the URI. Or maybe that was the URI for some reason.

**Comment by The-Compiler** [comment]
That happened when using `:view-source` on QtWebEngine, and is fixed with 5b1d35bef99a135bd6199cc8283fcde89d4fc1fb.

#2295 will remove old entries during migration. See #1099 for the performance.
