### ISSUE TITLE
Deadkeys (for foreign words with tildes) do not work in textboxes in OSX

### ISSUE THREAD

**Issue by leorockway** [qutebrowser/qutebrowser#2647]
I'm using latest OSX build and I can't write words with tildes. I use Colemak which relies on dead keys, but they don't work in textboxes.

I can't reproduce this on my GNU/Linux (Manjaro).

**Comment by The-Compiler** [comment]
It's an upstream issue in QtWebEngine and will be fixed in the Qt 5.9 release and subsequent qutebrowser release (i.e. in something like 2-4 weeks).

**Comment by The-Compiler** [comment]
@leorockway @m2habert @akz92 @runjaj v0.11.0 is now out with Qt 5.9, so this should be fixed.

**Comment by akz92** [comment]
It's working fine here (macOS 10.12.5). Thanks!

**Comment by leorockway** [comment]
Thank you!

**Comment by runjaj** [comment]
Hi!

Thanks for the email. Now it works pefectly: Á á Ñ ñ Ò ò.

Javier

**Comment by m2habert** [comment]
Same here, great! 

Thanks!
