### ISSUE TITLE
What is the order of hint strings and how do I change it?

### ISSUE THREAD

**Issue by meatich** [qutebrowser/qutebrowser#2649]
The very first hints that pop up are: a, hg, hh, d, gh, hk, jh, kh or something like that. I use Colemak and g, j and l are in the middle of the top row which is painful. Is there a way to redefine the order to use, for example, t, n, e, s?

**Comment by The-Compiler** [comment]
`:set hints chars`

**Comment by meatich** [comment]
Thank you!
