### ISSUE TITLE
Google's new Sign In page Problems

### ISSUE THREAD

**Issue by sfantu** [qutebrowser/qutebrowser#2650]
qutebrowser v0.10.1

Does anyone have this issue.
When i try to sign in I input the email then when I press next I get redirected to the previous page.

**Comment by The-Compiler** [comment]
What backend are you using (from `:open qute:version`) and what distribution are you on?

**Comment by sfantu** [comment]
Backend: QtWebKit (WebKit 538.1)
On Arch Linux

**Comment by The-Compiler** [comment]
You're using the legacy QtWebKit backend - I'd recommend either:

- Switching to the [QtWebKit-NG](https://github.com/annulen/webkit/wiki) backend, a more modern QtWebKit replacement (`qt5-webkit-ng` on Arch). Note however that private browsing won't work yet there.
- or trying the new [QtWebEngine](https://wiki.qt.io/QtWebEngine) backend (based on Chromium) by installing `qt5-webengine` and starting with `--backend webengine`. Note some minor features are still missing there, though.

**Comment by sfantu** [comment]
Yep starting it with the `--backend webengine ` resolves the issue

**Comment by The-Compiler** [comment]
Nothing qutebrowser can do about it then - but QtWebEngine is soon going to be the default after a few remaining issues are fixed.

**Comment by sfantu** [comment]
I've read that is the plan ... but i used qutebrowser just for light browsing so the old engine wasn't a problem. But today i was hacking on one of my projects which used qtwebkit and i had problems so i tried in qutebrowser only to find the same issue. I also have problems with other google services in firefox for example. Google is kinda screwing with the browsers. 
Anyway your doing a great job with qutebrowser.
Thank you.
