### ISSUE TITLE
Use page title for filename with :download

### ISSUE THREAD

**Issue by m2habert** [qutebrowser/qutebrowser#2652]
:download stopped working properly with articles from a page I use all the time: http://www.villagevoice.com/path/to/some/article

It's a minor thing: it downloads the article all right, but names the page with the general /domain url:

    http://www.villagevoice.com.html

Not a big problem, but it used to work neatly in this very same page: page title as the filename.

I guess the page editors changed something since my last visit...

qB v0.10.1
Mac OS 10.11.6

**Comment by The-Compiler** [comment]
To be honest, I'm not even sure why this worked before - I'm not sure where `:download` would've gotten the title from. But indeed it'd probably make sense to use that as filename.

**Comment by m2habert** [comment]
Still works for most pages, though...

**Comment by The-Compiler** [comment]
Do you have a link where it works?

**Comment by m2habert** [comment]
When I use it on this very same page, it outputs "2652" as a filename, which, for my money, is already better than the domain.

And, for instance, here : 
https://www.conversaafiada.com.br/economia/roubalheira-joesleis-tem-registro-1

outputs:

filename :   "roubalheira-joesleis-tem-registro-1"
