### ISSUE TITLE
When starting qutebrowser using "--backend webengine" I get the error "libpng warning: iCCP: known incorrect sRGB profile"

### ISSUE THREAD

**Issue by maxemillianian** [qutebrowser/qutebrowser#2659]
And the browser is unusable (e.g. using the scrolling keys has the effect of changing the orientation of the page; cannot use : commands, etc.).

Any ideas on how to fix?

Thanks,
Max

qutebrowser v0.10.1

**Comment by maxemillianian** [comment]
Nevermind, a computer restart seems to have fixed it...

**Comment by maxemillianian** [comment]
This happened again today. I returned to my computer and qutebrowser was unusable. Scrolling using the j k keys just kind of wobbled the rendered page a little, no up/down movement at all. 

Quitting qutebrowser and restarting it again with "qutebrowser --backend webengine" does not resolve the issue.

Any ideas?

**Comment by The-Compiler** [comment]
That warning is [harmless](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile) and most likely unrelated. What OS/distribution are you on? Can you check whether you get the same behavior in something like [QupZilla](https://qupzilla.com/) (the 2.x series) please? What graphic card driver are you using?

**Comment by maxemillianian** [comment]
I'm on Arch, using Thinpad T61 with integrated intel graphics using official intel drivers. 

I'll download QupZilla and see if the issue also occurs with that browser. 

Thanks!

**Comment by maxemillianian** [comment]
Yes, a similar behavious is immediatly present with QupZilla.

**Comment by The-Compiler** [comment]
That seems like some kind of bug in QtWebEngine or Chromium then... I suggest you also test Chromium, and if things seem fine there, wait for Qt 5.9 (should be released in a week or so). If you still see it with that, can you please [open a Qt bug](https://bugreports.qt.io/) about it?
