### ISSUE TITLE
Improvements for NSIS installer

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2660]
The new NSIS Windows installer needs some small improvements:

- [ ] Use UAC correctly (only when needed)
- [ ] Add a finish page with an option to start qutebrowser (not as admin!)
- [ ] Add option to uninstaller to remove appdata
- [ ] Detect if qutebrowser is still running (see [Check whether your application is running](http://nsis.sourceforge.net/Check_whether_your_application_is_running)) or already installed (see [Auto-uninstall old before installing new](http://nsis.sourceforge.net/Auto-uninstall_old_before_installing_new))

cc @Link-Satonaka

**Comment by bitraid** [comment]
@The-Compiler  - I have some more suggestions for NSIS, and i could help with the ones you like:

1. Proper support for per-machine and per-user installations (See [Installation Context on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/dd765197.aspx)). Doing this right with NSIS can be tricky, but will also take care of the first two proposed improvements. I think the easiest way is to use the [NsisMultiUser plugin by Drizin](https://github.com/Drizin/NsisMultiUser). It's a rewrite of the original `MultiUser.nsh` and also includes and uses the [UAC plug-in](http://nsis.sourceforge.net/UAC_plug-in).
2. Safe uninstall. Blindly erasing a directory recursively is dangerous. Should at least check it's not a system/user directory (e.g. the user chose `C:\Program Files` by mistake), or create a log of installed files and remove only those.
3. Script directive to increase lzma dictionary size for maximum compression. The default size is 8mb, could be increased to 128mb. The lzma codec needs a little more than the dictionary size in ram for decompression, but 10x of that for compression.
4. Script directive for using upx to pack the exe header. If there is a use case for a runtime packer, it's this. Won't save much though, it's a small file.
5. The script could get the version number directly from `qutebrowser.exe`. This will require to embed a [VERSIONINFO resource](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058(v=vs.85).aspx) to the `exe`. Pyinstaller does this by referring to a file containing a VSVersionInfo object. Its class is found in `utils/win32/versioninfo.py` of Pyinstaller's directory.
6. A `VERSIONINFO resource` should also be added to the installer's `exe`. This is supported by NSIS directly with recent versions. Parts of this information is displayed to users by Windows Explorer (e.g. on the `Details` tab of the file `Properties` window, the file pop-up description, the `Tiles` view, etc.), other programs can access it using the `GetFileVersionInfo[Ex]` win32 function, and administrators using powershell: `(Get-Item .\installer.exe).VersionInfo | Select-Object *`.
7. It would also be nice for the version to be displayed on the installer's window.  Maybe replacing the text `Nullsoft Install System vX.YZ` with `qutebrowser vX.Y.Z installer`.
8. Don't use the same icon as the main executable.The default Windows taskbar setting, displays icons without names. It might be confusing if different programs with the same icon, are running at the same time.

**Comment by The-Compiler** [comment]
@bitraid Sorry, I must've missed your comment! All of those sound like very good points. I'm not sure about the custom icon is worth the effort (especially if it potentially results in licensing issues), but the others all sound like good ideas to me.

The Windows installer certainly can use some love - thanks for taking care of that so far! :+1:

**Comment by bitraid** [comment]
Ok, great. I'm onto it!

**Comment by elig0n** [comment]
The Windows installer doesn't detect currently installed path of qutebrowser and offers C:\Program Files\ as default. I use another path for my installations so upgrades are not going with the least intervention. I would love to see the installer autodetect the directory of qutebrowser.
