### ISSUE TITLE
Amazon video - browser not supported

### ISSUE THREAD

**Issue by Haroon89** [qutebrowser/qutebrowser#2662]
Hello I tried watching a video at amazon prime video, but I couldn't get it to work. It said the browser is not supported.

Is there a way to watch amazon prime with qutebrowser?

Regards

**Comment by The-Compiler** [comment]
It should work if you switch to the new QtWebEngine backend (by starting with `--backend webengine`) and have Widevine installed (`qt5-webengine-widevine` on Archlinux). Whether you can easily do that or not entirely depends on what distribution you're using, though...

**Comment by Haroon89** [comment]
Hello, it plays the video now, but I can't see the UI, meaning I can't change the audio/subtitle only play and stop.

**Comment by He-Ro** [comment]
Interestingly at the near end of a video (at least if it is an episode of a series) the UI elements show for me and I can use them. This is likely because at the end of the video one can click to skip to the next episode. But other than that I have the same problem, that the UI elements do not show when moving the mouse over the video. It works as expected in Chromium.

**Comment by The-Compiler** [comment]
Can you check if it looks the same in another QtWebEngine browser, like [QupZilla](https://qupzilla.com/) (the 2.x series)?

**Comment by He-Ro** [comment]
I installed the current qupzilla under Arch Linux, which is version 2.1.2.
There the controlls also do not show when moving the mouse over the video, for example the trailer for this movie: https://www.amazon.de/Pate-dt-OV-Marlon-Brando/dp/B00FYV67P2/.
As in qutebrowser: When clicking on the middle part of the video, where the pause button is supposed to be, then the video pauses and resumes after another click. Also the mouse cursor is not visible, when on top of the video.
Should another bug report be opened for this, or is it not necessary, as it seems to be a QtWebEngine bug?

**Comment by The-Compiler** [comment]
It's indeed a QtWebEngine issue. I can reproduce it, but all works fine with the Qt 5.9.0 RC (to be released tomorrow if nothing goes wrong), so all you'll need to do is wait and update :wink:
