### ISSUE TITLE
private-browsing leads to empty default session

### ISSUE THREAD

**Issue by wes1138** [qutebrowser/qutebrowser#2664]
To reproduce:

1. Turn off private browsing, start qutebrowser.
2. Enable private browsing via `:set general private-browsing true`.  For me,
   status bar color does not change (perhaps this is a hint?).
3. Close qutebrowser by killing last tab (for me it was about:blank, and I
   have the option set to automatically close upon exiting the last tab).
4. Open qutebrowser again.  Note that now the status bar does honor the new
   color settings for private browsing.
5. Close qutebrowser in the same way as before, by killing the about:blank
   tab.
6. At this point, my default session
   `~/.local/share/qutebrowser/sessions/default.yml` has the following
   contents:
  `windows: []`

This is a little unfortunate, as the next time I start qutebrowser, it will
hang, likely because it is faithfully restoring my windowless default session.

I have a feeling there must be something anomalous about my configuration that
is responsible in part for this, but I couldn't figure out many likely
candidates.  If you have trouble reproducing these events, let me know what
else I can share to help.

This is built from git last night, and I think all the dependencies are up to date.  OS is arch linux.  Here is some info:

qutebrowser v0.10.1
Git commit: 2017-05-26-build (2017-05-24 21:53:53 +0200)
Backend: QtWebKit (WebKit 538.1)

CPython: 3.6.1
Qt: 5.8.0
PyQt: 5.8.2

sip: 4.19.2
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017

By the way, the git tag points to a8ffaec34b0023eaa125cfc75c9fb483dfbe6a0c.

**Comment by wes1138** [comment]
Update: I removed all my config, and I still have the same problem.  To get from the default config to a state where this happens, I did the following (not sure if last-close is necessary):

:set tabs last-close close
:set general save-session true
:set general session-default-name default

Hope that helps.

**Comment by The-Compiler** [comment]
The new private browsing is only in since about 2 weeks, so it's entirely possible you're the first one to notice - I can reproduce it :wink:

> 2. Enable private browsing via `:set general private-browsing true`.  For me, status bar color does not change (perhaps this is a hint?).

That's because private browsing is only active for windows opened after it's been turned on.
