### ISSUE TITLE
Enable hardware acceleration with QtWebEngine

### ISSUE THREAD

**Issue by terlar** [qutebrowser/qutebrowser#2671]
Is it possible to enable the hardware acceleration with QtWebEngine in some way?

I could access `chrome://gpu/` where it says it is not enabled. I read that for Chromium you can enable these kind of options under `chrome://flags/` but inside qutebrowser we don't have such a page, is it possible to do somehow with set or some other way?

**Comment by The-Compiler** [comment]
This is done by Qt, there's nothing qutebrowser can do about it. I've heard some talk about the investigating what more they can do with how they render stuff, but I'm not sure what the state there is - I also didn't find an issue in their tracker so far.

**Comment by wesbarnett** [comment]
This seems to enable some hardware acceleration:

    qutebrowser --qt-flag ignore-gpu-blacklist --qt-flag enable-gpu-rasterization

[Source](https://forum.qt.io/topic/82360/problem-with-qt-webengine-hardware-acceleration/2)

[Before](https://i.imgur.com/JZTZKX0.png)

[After](https://i.imgur.com/nIx57T1.png)

**Comment by terlar** [comment]
@wesbarnett Thanks for this finding!

**Comment by The-Compiler** [comment]
Note that there's probably a good reason that Chromium and Qt have those switches/blacklists.

**Comment by rien333** [comment]
Any (recent) information  on this? Is it still not recommended to use those flags, and what might be reasons for auto disabling them?

**Comment by jgkamat** [comment]
Rijnder Wever writes:

> Any (recent) information on this? Is it still not recommended to use those flags, and what might be reasons for auto disabling them?

For me, this causes CPU spikes and stutters when typing on some websites. I
don't think hw acceleration matters too much though, especially if you play
video in a competent player.

**Comment by rien333** [comment]
Agreed, but I had to switch to viewing some videos in my browser because of some DRM stuff that was recently enforced.

**Comment by The-Compiler** [comment]
@rien333 Not really, you'd need to ask the [Chromium devs](https://bugs.chromium.org/p/chromium/issues/detail?id=463440).

**Comment by gitjanfri** [comment]
> This seems to enable hardware acceleration:
> 
> ```
> qutebrowser --qt-flag ignore-gpu-blacklist --qt-flag enable-gpu-rasterization --qt-flag enable-native-gpu-memory-buffers --qt-flag num-raster-threads=4
> ```
> 
> [Before](https://i.imgur.com/JZTZKX0.png)
> 
> [After](https://imgur.com/emuAfdB.png)

I have a project with QT/VS2017/Win10 - where i try put this parameter ? Where i make a list situation ?

**Comment by toofar** [comment]
@gitjanfri You mean you are running qutebrowser from visual studio? Presumably like [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/4097114c-8678-46bb-ba3b-7a2da8514efc/visual-studio-2017-not-passing-command-line-arguments-to-the-application?forum=vsdebug#07d2f8dc-19d6-49c0-af91-5f358ec14a2f). If you are making some other QtWebengine based project you pass, for example, "--ignore-gpu-blacklist" in a list as the argument to the constructor of QApplication.

**Comment by rien333** [comment]
Relevant upstream bug: https://bugreports.qt.io/browse/QTBUG-91677
