### ISSUE TITLE
GitHub dropdown menus won't open

### ISSUE THREAD

**Issue by noobpurple** [qutebrowser/qutebrowser#2674]
If I navigate to any GitHub repo, I can't open the "Branch" dropdown menu or the "Clone or download" dropdown menu. I've tried both using hints and clicking with the mouse, but neither work.

Here's my version info:
https://pastebin.com/raw/TUUuLgpq

**Comment by The-Compiler** [comment]
You're using the legacy QtWebKit backend, seems like GitHub recently broke with that - I'd recommend either:

- Switching to the [QtWebKit-NG](https://github.com/annulen/webkit/wiki) backend, a more modern QtWebKit replacement (`qt5-webkit-ng` on Arch/Najaro). Note however that private browsing won't work yet there.
- or trying the new [QtWebEngine](https://wiki.qt.io/QtWebEngine) backend (based on Chromium) by installing `qt5-webengine` and starting with `--backend webengine`. Note some minor features are still missing there, though.
