### ISSUE TITLE
Multiple paralell sessions

### ISSUE THREAD

**Issue by merspieler** [qutebrowser/qutebrowser#2675]
When I have an open session (eg. with allow-javascript true) and start a new session with `qutebrowser -s content allow-javascript false` I'ld expect that it opens a new session with allow-javascript false in a new window. Instead it opens just another window in the current session with allow-javascript true.

**Comment by The-Compiler** [comment]
You probably want `--basedir` (or `--temp-basedir`) instead, which starts an entirely new qutebrowser instance.
