### ISSUE TITLE
Insertting Special Characters Into Fields

### ISSUE THREAD

**Issue by Jumblemuddle** [qutebrowser/qutebrowser#2677]
# Problem
I'm unable to insert special accented characters.

I can insert ñ however, since it's not 2 keypresses. I'm not sure what's going on.

Accented characters view `' + $key` does work in a terminal for instance.

# Version info

qutebrowser v0.10.1
Git commit: 
Backend: QtWebEngine

CPython: 3.5.3
Qt: 5.8.0
PyQt: 5.8.1

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.7.225 (/nix/store/a6shpqn3dfvhcgm4k6v6sk1rkyy0dx0c-pdfjs-1.7.225/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.27-x86_64-with-glibc2.3.4, 64bit
Frozen: False
Imported from /nix/store/2xrbf5qbkgpgb1c9bq8mw4hxxr03wki6-qutebrowser-0.10.1/lib/python3.5/site-packages/qutebrowser
Qt library executable path: /nix/store/462xkm8xvf9qj15m7y5v3y0c49ywvjja-qtbase-5.8.0/libexec, data path: /nix/store/462xkm8xvf9qj15m7y5v3y0c49ywvjja-qtbase-5.8.0
OS Version: 

--- /etc/os-release ---
NAME=NixOS
ID=nixos
VERSION="17.09.git.ce278c8 (Hummingbird)"
VERSION_CODENAME=hummingbird
VERSION_ID="17.09.git.ce278c8"
PRETTY_NAME="NixOS 17.09.git.ce278c8 (Hummingbird)"

Paths:
download: /home/garrett/Downloads
runtime: /run/user/1000/qutebrowser
cache: /home/garrett/.cache/qutebrowser
config: /home/garrett/.config/qutebrowser
system_data: /nix/store/2xrbf5qbkgpgb1c9bq8mw4hxxr03wki6-qutebrowser-0.10.1/share/qutebrowser
data: /home/garrett/.local/share/qutebrowser

**Comment by The-Compiler** [comment]
That's a QtWebEngine issue, fixed in Qt 5.9 (which is planned to be released today 🎉). So after it's released (and NixOS updates its packages), all should be fine.
