### ISSUE TITLE
Ridiculously garbled text on some websites

### ISSUE THREAD

**Issue by TheGag96** [qutebrowser/qutebrowser#2689]
I'm running v0.10.0-747-ga90429fe6 (newest master commit as I'm posting) on Ubuntu 17.04 64-bit using the webengine backend. I'm getting some [seriously garbled text](https://imgur.com/a/tmehv) on certain websites, but not all of them. This does not happen on other browsers, including Chrome.

**Comment by The-Compiler** [comment]
That looks... interesting indeed! Do you get the same with `--temp-basedir`? What about `python3 scripts/testbrowser.py --webengine www.example.com`? Does `export LIBGL_ALWAYS_SOFTWARE=1` change anything?

**Comment by TheGag96** [comment]
Unfortunately, none of those things change anything...

**Comment by The-Compiler** [comment]
Debian uses its system harfbuzz for font rendering, I bet it's related to that somehow...

Can you try the following please, which uses a binary build of Qt shipped with PyQt?

- Install `python-tox`
- Do `tox -e mkvenv-pypi` in the repo
- Do `./.venv/bin/python3 -m qutebrowser --temp-basedir`
- `:open qute:version` and check that `Imported from` looks correct there.

If you get a SSL error, you might need to check where your Debian has an OpenSSL 1.0 installed, and then do something like `export LD_LIBRARY_PATH=/usr/lib/openssl-1.0` first, as the binary package is built against OpenSSL 1.0.

**Comment by The-Compiler** [comment]
Closing this as it's definitely not a qutebrowser issue - I suggest finding out whether it happens with a PyPI-installed QtWebEngine, and then either opening a Debian [or a Qt](https://bugreports.qt.io/secure/Dashboard.jspa) bug.
