### ISSUE TITLE
Flash applet ignores allow-plugins=false

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2696]
With `content -> allow-plugins` set to `false`, the [Oddcast text-to-speech demo](http://www.oddcast.com/home/demos/tts/tts_example.php) still loads the flash applet. It definitely uses flash because I opened this site in Chromium and I have it set to where I have to right click to run the Flash applet, and it shows it's a Flash applet there.

However flash doesn't load on www.transformice.com

```
Version info:

qutebrowser v0.10.1
Git commit: v0.10.0-884-g1509a2c67-dirty (2017-05-31 19:14:54 +0100)
Backend: QtWebEngine (Chromium 53.0.2785.148)

CPython: 3.6.1
Qt: 5.8.0
PyQt: 5.8.2

sip: 4.19.2
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.11.2-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /home/miles/packages/repos/qutebrowser-custom/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
config: /home/miles/.config/qutebrowser
data: /home/miles/.local/share/qutebrowser
system_data: /home/miles/.local/share/qutebrowser
cache: /home/miles/.cache/qutebrowser
download: /home/miles
runtime: /run/user/1000/qutebrowser
```

**Comment by The-Compiler** [comment]
Works as expected here:

![image](https://cloud.githubusercontent.com/assets/625793/26792888/2e551f22-4a1c-11e7-99fe-e97db01dcad5.png)

If you do `qutebrowser --temp-basedir --backend webengine http://www.oddcast.com/home/demos/tts/tts_example.php` do you still see the applet?

**Comment by pkillnine** [comment]
Yes I do.

**Comment by The-Compiler** [comment]
I don't know what exactly that page does so it only *sometimes* works - but when it does, it's JavaScript and a `<canvas>` element, and not flash (despite the element being called `flashcontainer`...):

![image](https://cloud.githubusercontent.com/assets/625793/26794295/6dd46d2e-4a21-11e7-84f6-18651336412a.png)
