### ISSUE TITLE
Change window title to reflect whether privacy mode is enabled

### ISSUE THREAD

**Issue by craftyguy** [qutebrowser/qutebrowser#2697]
I would like to submit a patch that changes the window title to indicate when privacy mode is set. The reason for this is I use a tiling window manager (i3) that allows me to do all sorts of customizations and neat tricks based on window characteristics, including window title.

I have brianstormed two possible approaches and would like your feedback before I move forward:

Implementation 1:
Add conditional statement to tabbedbrowser.py's update_title_window(), to append a "[Privacy Mode]" string to the end of the parameter for setWindowTitle when self.private is set. This is 'quick and dirty', but the change would apply for all users.

Implementation 2:
Add a new format type to window-title-format, like {priv}, that is only set when privacy mode is enabled. It can be left out of the default window-title-format string in the config file, so existing (and new) users won't have it configured, but could be enabled by users who want some distinction in the window title when privacy mode is enabled.

The second option will require a bit more work on my part to learn about how window-title-format formats are enabled/used, but if you think that's the right way to do this then I have no problem doing so. On the other hand, I know some big changes to the config file structure are coming up very soon, so maybe option 1 is better since it doesn't do anything that could possible conflict with those changes, or require more work for you :smile: 

Please let me know your thoughts!

**Comment by The-Compiler** [comment]
I don't like hardcoded things, so 2) it is :wink:

All you probably need to do is to add some `priv` field to `TabWidget.get_tab_fields` (there's a `tab.private` flag) which is set to either an empty string or some marker, and add that to the allowed fields for `window-title-format` in `configdata.py`.

**Comment by craftyguy** [comment]
The tabwidget stuff is still relevant even though private mode is not handled at the tab level on webengine (but instead at the window level) ?

**Comment by The-Compiler** [comment]
Yes, for two reasons: Most of it is written in a way which would actually support per-tab private browsing (and doing it that way will make it easier to allow that in the future if we want to) - and here, it's simply easier to get the `private` bit from the tab than accessing the corresponding window object :wink:

**Comment by craftyguy** [comment]
got it, thanks!

One more question, I don't know what you want to 'officially' call privacy mode (e.g. google calls it 'incognito'), but I currently have a priv field set to ' [Privacy Mode] ' in get_tab_fields. I'm not sure if that's acceptable 'hardcoding' or if I'll need to implement some configurable option in the configdata to also allow folks to customize the privacy mode field that's used in tabs set to private mode. Thoughts?

**Comment by The-Compiler** [comment]
FWIW qutebrowser calls it *private* mode everywhere, so I'd go for that as well. With #1578 (which I might or might not tackle over the next few weeks) it'd be configurable anyways.
