### ISSUE TITLE
Search suggestions

### ISSUE THREAD

**Issue by Majora320** [qutebrowser/qutebrowser#2705]
It would be nice to have an option to have the open prompt display search suggestions below matching urls, like firefox; I know that google has an api[1] for this, but I'm not aware (off the top of my head) if other search engines like DuckDuckGo do, and different engines are likely to have incompatible formats, so there would likely have to be a seperate implementation for each.

[1]: https://stackoverflow.com/questions/6428502/google-search-autocomplete-api

**Comment by The-Compiler** [comment]
See #32.
