### ISSUE TITLE
user-stylesheet global css delay

### ISSUE THREAD

**Issue by seniorivn** [qutebrowser/qutebrowser#2706]
```qutebrowser v0.10.1
Git commit: 
Backend: QtWebEngine

CPython: 3.6.1
Qt: 5.8.0
PyQt: 5.8.2

sip: 4.19.2
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2l  25 May 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.10.17-2-MANJARO-x86_64-with-glibc2.3.4, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/os-release ---
NAME="Manjaro Linux"
ID=manjaro
PRETTY_NAME="Manjaro Linux"


```
Case:
i'm using global css(user-stylesheet) that makes all pages dark.
Issue:
it's affecting after page boots up, so on every new page openning its blinking from light colors to dark, its the opposite effect than i expected.

**Comment by The-Compiler** [comment]
Is this actually with the QtWebKit backend (as shown in your version info), or is it with `--backend webengine`?

**Comment by seniorivn** [comment]
@The-Compiler 
oh, sorry forgot to mention, yes its with `--backend webengine`

**Comment by The-Compiler** [comment]
Nothing I can do about that until https://codereview.qt-project.org/#/c/148671/ is implemented in Qt, I'm afraid.

**Comment by seniorivn** [comment]
@The-Compiler thanks, will wait.
