### ISSUE TITLE
nss 3.31-2 breaks https on qutebrowser-git

### ISSUE THREAD

**Issue by throwaway217** [qutebrowser/qutebrowser#2710]
More specifically, this build since 3.31-1 works. 

https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nss&id=2bfc730d4a49e588fb43312d06814af945bd966a

**Comment by The-Compiler** [comment]
With QtWebEngine I assume? https://bugs.archlinux.org/task/54387

**Comment by throwaway217** [comment]
Yes :)
