### ISSUE TITLE
Segfault on etoro.com

### ISSUE THREAD

**Issue by arivarton** [qutebrowser/qutebrowser#2712]
After doing a update on Arch Linux, qutebrowser gets a segmentation fault when opening www.etoro.com.
Keep in mind that I'm logged in so you won't get the same problem unless you log in.

Here is a debug log:
https://gist.github.com/arivarton/19d2440bf1f08067838b5730a7524b5f

And my version:
qutebrowser v0.10.1
Git commit: v0.10.0-97-g0b5838f9f (2017-03-08 20:56:30 +0100)
Backend: QtWebKit (WebKit 538.1)

CPython: 3.6.1
Qt: 5.9.0
PyQt: 5.8.2

sip: 4.19.2
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.11.3-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/vidr/.config/qutebrowser
data: /home/vidr/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/vidr/.cache/qutebrowser
download: /home/vidr/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
You're using the legacy QtWebKit backend - I'd recommend either:

- Switching to the [QtWebKit-NG](https://github.com/annulen/webkit/wiki) backend, a more modern QtWebKit replacement (`qt5-webkit-ng` on Arch).
- or trying the new [QtWebEngine](https://wiki.qt.io/QtWebEngine) backend (based on Chromium) by installing `qt5-webengine` and starting with `--backend webengine`. Note some minor features are still missing there, though.

Can you please try if you can reproduce this with that?

**Comment by arivarton** [comment]
Changed to QtWebKit-NG and it works fine now.
