### ISSUE TITLE
Disable opening the qutebrowser introductory/quickstart page if the startpage option is set to an url

### ISSUE THREAD

**Issue by throwaway217** [qutebrowser/qutebrowser#2714]
Just like the title says I think an introductory/quickstart page is uneened after you've used qutebrowser for a lot of time. Plus most of the big browsers don't exhibit this behaviour from what I can recall.

>But dude, it's just a tab and it opens once what you have autism or what

Yes

**Comment by The-Compiler** [comment]
The quickstart page only opens on the first start. Do you do something which prevents it from writing `~/.local/share/qutebrowser/state`?

**Comment by throwaway217** [comment]
Ohh I thought this was a recently introduced behaviour but it seems I misconfigured one the qutebrowser firejail profile. Sorry about this and thank you.
