### ISSUE TITLE
how can one clear the dns cache?

### ISSUE THREAD

**Issue by McKean** [qutebrowser/qutebrowser#2717]
I'm using this Qutebrowser for development and livereloading stuff, so `localhost:3000` might be proxied somewhere else every now and then.
Any ideas how to easily get around this?

Thanks!

**Comment by The-Compiler** [comment]
This is handled internally by QtNetwork/QtWebKit/QtWebEngine, so there's little you can do - your best bet is probably `:restart`.

**Comment by lahwaacz** [comment]
The web inspector has a "Disable cache" checkbox in the "Network" tab. No idea if that includes DNS though...

**Comment by McKean** [comment]
so hey, `:restart` didn't do the trick, but disabling cache on the Network tab did the trick. Thanks!
