### ISSUE TITLE
Add support for 2 character keybindings

### ISSUE THREAD

**Issue by MichaelMackus** [qutebrowser/qutebrowser#2719]
In all my VIM UI's I have the following keybinding:

```vimrc
inoremap jk <Esc>
```

This way I can just type the key sequence `jk` in order to escape out of input fields/other things. Unfortunately, this is pretty hard-grained into my brain nowadays and I instinctively reach for those keys. I've tried researching & editing the configuration in order to replicate this functionality to no avail :(

**Comment by The-Compiler** [comment]
See #1044.
