### ISSUE TITLE
white flashing with webengine backend and custom-colors

### ISSUE THREAD

**Issue by spiderbit** [qutebrowser/qutebrowser#2720]
version 0.9.1

I have a dark theme for websites via custom-colors.css if I use qutebrowser there is no issue, when I use the backend webengine it seems to work much faster on my laptop, but every website first flashes in white and then flashes to the custom colors. Is there a way to not have this white flashing? Some sort of initial frame-background-color or something like that?

basicly the page gets rendered for 1 second in the original css then it switches to my custom colors, this bright flashes are anoying in the evening.

**Comment by The-Compiler** [comment]
There's the `colors -> webpage.bg` setting, but that only applies when the website hasn't overridden its background color.

The CSS indeed only gets applied when the page finished loading, but there's nothing qutebrowser can do about this before [this change](https://codereview.qt-project.org/#/c/148671/) lands in Qt.
