### ISSUE TITLE
userscript:_qute_stylesheet: Uncaught TypeError: Cannot read property 'appendChild' of undefined

### ISSUE THREAD

**Issue by blueyed** [qutebrowser/qutebrowser#2723]
I am seeing the following error when accessing https://travis-ci.com/private_org/private_repo/pull_requests:

> 14:07:36 ERROR: [userscript:_qute_stylesheet:6] Uncaught TypeError: Cannot read property 'appendChild' of undefined

Before there was a warning already:

> 14:07:32 WARNING: [https://cdn.travis-ci.com/assets/vendor-284b882d99e4c1b0d34e3a66b48188d1.js:21] Error

```
% qutebrowser --version
qutebrowser v0.10.1
Git commit: 
Backend: QtWebEngine

CPython: 3.6.1
Qt: 5.9.0
PyQt: 5.8.2

sip: 4.19.2
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.11.5-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/daniel/.local/share/qutebrowser-work/config
data: /home/daniel/.local/share/qutebrowser-work/data
system_data: /usr/share/qutebrowser
cache: /home/daniel/.local/share/qutebrowser-work/cache
download: /home/daniel/.local/share/qutebrowser-work/download
runtime: /home/daniel/.local/share/qutebrowser-work/runtime
```

I assume it comes from https://github.com/qutebrowser/qutebrowser/blob/2ffb10badf723522d82256154716c8cd344dec4a/qutebrowser/browser/webengine/webenginesettings.py#L145-L152 somehow?!

(the `cache` dir does not exist currently (it is a symlink pointing to a non-existing dir), in case that matters)

**Comment by The-Compiler** [comment]
I can reproduce it - looks like `document.getElementsByTagName('head')[0]` returns `undefined`. The HTML (both the thing coming from the server and the replaced one from Travis' JS) does have a `<head>` tag though...

**Comment by blueyed** [comment]
Cool.
Does it only happen with travis-ci.com? (Have not seen it on .org.)

**Comment by The-Compiler** [comment]
I just noticed the [Acid3 test](http://acid3.acidtests.org/) also fails on 99/100 and shows the same errors. When disabling the user stylesheet script:

```diff
diff --git a/qutebrowser/browser/webengine/webenginesettings.py b/qutebrowser/browser/webengine/webenginesettings.py
index 76c2aa4ec..a75568587 100644
--- a/qutebrowser/browser/webengine/webenginesettings.py
+++ b/qutebrowser/browser/webengine/webenginesettings.py
@@ -157,7 +157,7 @@ def _init_stylesheet(profile):
     script.setWorldId(QWebEngineScript.ApplicationWorld)
     script.setRunsOnSubFrames(True)
     script.setSourceCode(source)
-    profile.scripts().insert(script)
+    # profile.scripts().insert(script)
 
 
 def _set_user_agent(profile):
```

it gets to 100/100.
