### ISSUE TITLE
Nitpick: possibly badly named javascript function

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2726]
I don't think [this function](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/javascript/webelem.js#L160-L170) actually focuses an element, it seems to just return the currently focuesed element. If I'm not mistaken, it's used [here](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/webengine/webenginetab.py#L513-L516). Any reason why the javascript function is not named `find_focused` as well?

**Comment by The-Compiler** [comment]
True - others were inconsistent too, without a good reason to be. I renamed them to match the names in `webelem.py` now. Thanks for noticing!
