### ISSUE TITLE
QtWebEngine does not hide text search when a new page is opened in the same tab

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2728]
qutebrowser v0.10.1
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.1
Qt: 5.9.0
PyQt: 5.8.2

sip: 4.19.2
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
SSL: OpenSSL 1.0.2l  25 May 2017

Search for text in the page, go back, then go forward again and the text is searched on that page again (searched text is highlighted).

**Comment by lahwaacz** [comment]
It's not limited to back/forward, which might load the page from cache rather than doing full reload, but the same thing happens even when you open an entirely new page in the same tab.

I think that I started seeing this only after the Qt 5.9 release. Can somebody check that?

**Comment by The-Compiler** [comment]
Yeah, looks like a Qt 5.9 regression. I'll report it there and check if I can add a workaround (clear the search on page load) later.

**Comment by The-Compiler** [comment]
I opened [QTBUG-61506](https://bugreports.qt.io/browse/QTBUG-61506) now.
