### ISSUE TITLE
why not add videos to open link with mpv, we can watch stream , or videos direclty opened with mpv or any other players that would be cool!!

### ISSUE THREAD

**Issue by narutowindy** [qutebrowser/qutebrowser#2729]

**Comment by lahwaacz** [comment]
qutebrowser does not modify the right-click context menu provided by the backend. What you're asking for is possible via `:spawn` or a [userscript](https://www.qutebrowser.org/doc/userscripts.html), both combined with appropriate key bindings for `:hint`.

**Comment by The-Compiler** [comment]
Also see 9. in the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/FAQ.asciidoc) on how to set this up :wink:
