### ISSUE TITLE
How to copy the part of the url of website? 

### ISSUE THREAD

**Issue by narutowindy** [qutebrowser/qutebrowser#2731]
www.domain.com/skdjalsjd/asdjajdkad/asjd/122323123/sdadas 

i want to copy the numeric content from it ?

**Comment by The-Compiler** [comment]
You mean if you are currently on that page? Use `go` to edit the current URL, then copy whatever you want from there.

**Comment by narutowindy** [comment]
link under the cursor url ? how to select them?

youtube page, i want to hower my mouse on to a video, and open that link directly with mpv, i know custom binding, but i dont know how to select the link under the cursor??

**Comment by The-Compiler** [comment]
With the QtWebEngine backend, looks like you can select texts in links while holding down Alt. With QtWebKit this doesn't seem possible.

You can't do that via a binding though - see e.g. #937. You might want to use hints instead, as mentioned in the example in the FAQ.

**Comment by narutowindy** [comment]
How to search in google by copy text fromwebpage  ?

**Comment by The-Compiler** [comment]
By copying the text, doing `:open` and inserting it there?
