### ISSUE TITLE
There was an error while getting hint elements

### ISSUE THREAD

**Issue by edi9999** [qutebrowser/qutebrowser#2735]
This seems to happen on all sites since today : 

my commit id is : a5db21abe92eedab13dfefb44a3ccd5ebc3699ee

**Comment by The-Compiler** [comment]
Did you update without restarting?

**Comment by The-Compiler** [comment]
Closing this for now, as I'm pretty sure that was the issue - let me know if that didn't fix it!

**Comment by edi9999** [comment]
Yes, it is working now indeed

**Comment by MasterSergius** [comment]
Facing this issue with few sites, for example - yaplakal.ru

**Comment by The-Compiler** [comment]
@MasterSergius Works fine here. Can you please open a new issue with more details and version information?

**Comment by MasterSergius** [comment]
After 2 min loading it began to work, next time couldn't reproduce this bug. So, it's hard to describe in details
