### ISSUE TITLE
YouTube videos improperly scaled when using vertical displays

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#2736]
#Basically, when using some weird screen dimensions, such as `1200x1920` (by rotating a `1920x1200` monitor 90 degrees), YouTube videos are scaled inappropriately only in Qutebrowser, but not Chrome. 

I use Qt 5.7.1, PyQt5 5.8.2, and Qutebrowser with the latest git commit.

**Fig. 1** shows a screenshot of my entire vertical monitor where I show Qutebrowser on top, Chrome in the middle, and a weechat IRC terminal at the bottom. What I hope you see in this figure is the layout of my screen, and how Qutebrowser causes YouTube videos to make poor utilization of space.

![remarkable_bug_qutebrowser](https://user-images.githubusercontent.com/8865788/27257957-8de68ac2-53fc-11e7-92ff-e2a9eda3d4df.jpg)
**Fig. 1**

You can also notice in **Fig. 1** that the video is squeezed in Qutebrowser (Ali's head is thinner in Qutebrowser). To further elaborate this, **Fig. 2** super-imposes Chrome's video over Qutebrowser's, such that Chrome's video is made 50% transparent and aligned to the left. You can see that Qutebrowser is not deleting any scenes from the video, but rather squeezing them to the left.

![remarkable_bug_qutebrowser_verticalhorizontal_alignment](https://user-images.githubusercontent.com/8865788/27257928-60fe5cb6-53fb-11e7-8444-bc0b5938c1f3.jpg)
**Fig. 2**

---

**Background on why enhancing handling of vertical monitors is important** 

I have three 1920x1200 monitors that I used to stack side-by-side as normally done by people. But this was too wide and I used to suffer to neck strain as I had to look at extreme left and right directions.

As a solution, I decided to stack the monitors side by side, except for having monitor rotated 90 degrees (vertical). Now, with such a setup, I have achieved:

 - Significantly minimized my neck movements. This is very significant IMO for a 3+ monitor user, specially for users of `vim`-oriented apps who have already eliminated the need of lifting their entire arm to use the mouse. For us (3-monitor users those who also no longer need to move their arms much), the neck movement is the most significant source of burning calories, and this vertical setup brings us the biggest chunk of energy efficiency. 
 - Great for viewing websites. This is due to the fact that many websites make poor use of wide screens. So using vertical monitors makes more optimum use of most websites in the Internet.
 - When full-screen movie viewing is needed, I can rotate the screen back to its original form. But, usually, I do multiple things at the time, and I watch movies as presented in **Fig. 3**.

![remarkable_bug_qutebrowser_nottoobadformovies](https://user-images.githubusercontent.com/8865788/27257993-f8014b62-53fd-11e7-8a90-6868cad2ed62.jpg)
**Fig. 3**

**Comment by Al-Caveman** [comment]
I guess I'll re-test again once Gentoo finally updates its Qt ebuilds.

**Comment by The-Compiler** [comment]
This is most likely fixed by [this fix](https://codereview.qt-project.org/#/c/189182/) in Qt 5.9. As a workaround, you might be able to launch qutebrowser with `--qt-flag use-gpu-in-tests` (no idea why, but it's mentioned in https://github.com/QupZilla/qupzilla/issues/2189)
