### ISSUE TITLE
cmd+leftArrow/rightArrow don't take to start/end of line

### ISSUE THREAD

**Issue by piotryordanov** [qutebrowser/qutebrowser#2740]
`cmd+leftArrow` doesn't take me to start of line in insert mode, neither does `cmd+rightArrow` take me to end of line in insert mode. 
I have the same problem on `QupZilla`.

**Comment by The-Compiler** [comment]
You're probably seeing [QTBUG-54692](https://bugreports.qt.io/browse/QTBUG-54692).

The reporter there says that `Alt-Left/Right` works - does it for you? If so, does `:bind <Meta-Right> fake-key -g <Alt-Right>` (and the same for `Left`) change anything?

**Comment by piotryordanov** [comment]
It's not the `alt` key, rather the `fn` key. (Two different keys on mac :) )

The `fn` key does the job, but not the code you gave me. What's the equivalent of `fn`?

**Comment by The-Compiler** [comment]
No idea - [here's what Qt has](http://doc.qt.io/qt-5/qt.html#KeyboardModifier-enum). If none of that works, I think you're pretty much out of luck until this is fixed in Qt.
