### ISSUE TITLE
No audio whatsoever.

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [qutebrowser/qutebrowser#2748]
I tried everythihng and installed all dependencies and followed the wiki to the letter and cannot get qutebrowser to play audio with or without webengine.

**Comment by lahwaacz** [comment]
Can you play audio in another Qt application?

**Comment by dubbadubbadubbacha** [comment]
Yeah. Audio works in all other programs.

**Comment by lahwaacz** [comment]
What's your `qutebrowser --version`?

**Comment by dubbadubbadubbacha** [comment]
qutebrowser v0.10.1
Git commit: v0.10.0-863-gcb5cd1a91 (2017-06-20 15:20:32 +0200)
Backend: QtWebKit-NG (WebKit 602.1)

CPython: 3.6.1
Qt: 5.9.0
PyQt: 5.8.2

sip: 4.19.2
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.11.6-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
config: /home/jamie/.config/qutebrowser
data: /home/jamie/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/jamie/.cache/qutebrowser
download: /home/jamie/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by lahwaacz** [comment]
Have you followed [this part](https://wiki.archlinux.org/index.php/GStreamer#Installation) of the wiki?

**Comment by dubbadubbadubbacha** [comment]
Yes

**Comment by dubbadubbadubbacha** [comment]
please close this. I fixed it by installing the alsa-plugins package as I am using OSS with ALSA emulation. Thanks for your help.
