### ISSUE TITLE
Support desktop shortcuts

### ISSUE THREAD

**Issue by woho** [qutebrowser/qutebrowser#2749]
It would be great to have support for saving the link of a web page into a shortcut. I would like to store most of my bookmarks in shortcuts that I can put in any folder and open them with a file manager. At this point I could do this by storing mhtml files (which I find to be great feature), but shortcuts would be a more desirable alternative here.

Such functionality is common among other browsers.

As to the implementation, one could add a command like:
"download --shortcut ..." or "download --desktop ...".
Similar to the behavior of the actual download command, a file save dialog should be prompted.

The shortcut would have such a content:

[Desktop Entry]
Version=1.0
Type=Link
URL=[url]
Icon=text-html

**Comment by pkillnine** [comment]
What OS are you on? I think this could be done easily with a userscript :)

**Comment by woho** [comment]
That is great, thank you for pointing this out. I now use this:

```
#!/bin/bash

filename=`zenity --file-selection --save --filename="$QUTE_TITLE.desktop"`

echo "[Desktop Entry]
Version=1.0
Type=Link
URL=$QUTE_URL
Icon=text-html" > "$filename"
```

**Comment by The-Compiler** [comment]
I don't think it makes sense to have this built-in in that case :wink:
