### ISSUE TITLE
adblocker not working in webengine?

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [qutebrowser/qutebrowser#2752]
I noticed that when I use qutebrowser proper without webengine all or most ads are blocked. The same pages under webengine show ads. www.drudgereport.com is the site I tested.

**Comment by lahwaacz** [comment]
I'm not seeing an excessive amount of ads there, even with webengine. Some ads obviously get through (in both webkit and webengine) because the blocker is based on hosts-blocking, see #29.

**Comment by The-Compiler** [comment]
I can see the top banner with QtWebEngine but not QtWebKit FWIW:

![image](https://user-images.githubusercontent.com/625793/27516653-5511a700-59be-11e7-8246-bb56a059c047.png)

However, that's a `<span>` element with base64-encoded background image, so I don't think the adblocker can really block it. With QtWebKit, I don't see it even with the adblocker disabled, so it's probably just something not being supported there.
