### ISSUE TITLE
Copy link command

### ISSUE THREAD

**Issue by nicktelford** [qutebrowser/qutebrowser#2754]
Sometimes, I like to copy a link in order to paste it in another program, or an input field in another tab. It would be nice if there was a way to copy a link directly - presently, I have to open the link, copy it, then go back.

The way I envisage it working is by pressing `yf` and then using the link hints to select the URL to copy.

I hope this is the right place for feature requests, if it isn't, sorry!

**Comment by The-Compiler** [comment]
There's `;y` (`:hint links yank`) for that :wink:

**Comment by nicktelford** [comment]
I can't believe I missed that. Thanks!
