### ISSUE TITLE
Support pdf.js for local files

### ISSUE THREAD

**Issue by Xiretza** [qutebrowser/qutebrowser#2755]
As said in IRC, pdf.js currently doesn't get used for local files because of the lack of a Content-Type header. A simple solution would be to just check the file extension.

**Comment by The-Compiler** [comment]
Should be relatively straightforward, but I'd like to wait until PDFJS is supported with QtWebEngine.

**Comment by Xiretza** [comment]
Crap, already opened in #1252. Sorry.

**Comment by The-Compiler** [comment]
Whoops, sorry! I didn't remember 😆
