### ISSUE TITLE
Web Fonts

### ISSUE THREAD

**Issue by Cysearo** [qutebrowser/qutebrowser#2763]
How can I force web pages to use a set of custom specified fonts instead of loading there own fonts?

**Comment by lahwaacz** [comment]
With the QtWebEngine backend, you can disable loading of remote fonts with `--qt-flag disable-remote-fonts`. The CSS may still specify whatever fonts, so this would work only if you have only a couple of fonts installed.

**Comment by The-Compiler** [comment]
You could also use the `ui -> user-stylesheet` setting to override fonts via CSS.
