### ISSUE TITLE
qutebrowser -V not working in Cron Job.

### ISSUE THREAD

**Issue by JPRuehmann** [qutebrowser/qutebrowser#2764]
Hello I am using the following in a Script.
`ALT=$(qutebrowser -V | grep "^q")`
And it gives me
`qutebrowser v0.10.1`
So far so good
But if I run the script as Cron Job it is empty.
I think it is because the Cron Job has no Frontend.
`CRITICAL: QXcbConnection: Could not connect to display`
Thanks,

**Comment by lahwaacz** [comment]
qutebrowser is a graphical application, so it needs a connection to the X server. At the very least, `DISPLAY` has to be set correctly.

**Comment by The-Compiler** [comment]
You could also use something like [Xvfb](https://en.wikipedia.org/wiki/Xvfb) and [xvfb-run](http://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html). What's your goal, though?

(Also, I'm closing this as it's not a qutebrowser issue - I'm still reading answers, though :wink:)

**Comment by JPRuehmann** [comment]
I wish to automatically update qutebrowser with that script.
```
#!/bin/bash

ZIEL="$PWD"
RECHNER=$(hostname)
ALT=$(qutebrowser -V | grep "^q")
cd /usr/local/
  if [ -d "qutebrowser" ]
    then
      cd qutebrowser
      echo "Sourcen Updaten"
      GIT_PULL=$(sudo git pull | grep -c "Already up-to-date.")
        if [ $GIT_PULL -ge 1 ]
        then
          echo "Already up-to-date."
        fi
    else
      echo "Aktuelle Sourcen Clonen"
      sudo git clone https://github.com/atom/atom.git &>/dev/null
    fi
NEU=$(qutebrowser -V | grep "^q")
MESSAGE="Das Tägliche Qutebrowser Update auf $RECHNER wurde durchgeführt.
alte Version:
$ALT
--------------------------------------
neue Version:
$NEU
--------------------------------------

Qutebrowser github Link: https://github.com/qutebrowser/qutebrowser/commits/master"
sendEmail -f qutebrowser@ruehmann.name -t jan-peter@ruehmann.name -o message-charset=utf8 -u "Daily Qutebrowser Update" -m "$MESSAGE" -s  -xu  -xp 
cd $ZIEL

exit 0
```
with a Cron Job.

**Comment by The-Compiler** [comment]
Sorry for the delay! Since you already have a git repo, I'd suggest simply looking at `git describe` there, or reading the `__version_info__` line from `qutebrowser/__init__.py`.

**Comment by JPRuehmann** [comment]
Thanks this works.
