### ISSUE TITLE
Use Ctrl-Tab to go to previous element

### ISSUE THREAD

**Issue by piotryordanov** [qutebrowser/qutebrowser#2768]
Say I'm on a form. Pressing `<tab>` takes me to the next element (password, for instance.)
But, pressing `<ctrl-tab>` doesn't jump me to the previous element.

I tried looking into spatial keys, but that's not what I was looking for.

Any hints?

**Comment by The-Compiler** [comment]
I've never seen a browser where `ctrl-tab` does this. `Shift-tab` does however - in Chromium, Firefox and qutebrowser :wink:

**Comment by piotryordanov** [comment]
Well, `shift-tab` doesn't work for me :(

**Comment by The-Compiler** [comment]
And `:bind <shift-tab>` says it's unbound? What backend and what Qt version are you on? (`:open qute:version`)? What does `:set input forward-unbound-keys?` say?

**Comment by piotryordanov** [comment]
`<shift-tab>` is unbound :(
`:set input forward-unbound-keys` is in `auto`

I'm on `Qt: 5.9.0`

**Comment by The-Compiler** [comment]
And what backend?

**Comment by piotryordanov** [comment]
`Backend: QtWebEngine`

**Comment by The-Compiler** [comment]
Works fine for me with the same setup. Can you reproduce it with `--temp-basedir`? How exactly are you testing?

**Comment by piotryordanov** [comment]
I'm on mac. Maybe that affects thing?
I tried launching it with `--temp-basedir` and i still can't press `<shift-tab>`
Is there no way of binding it to something? (I can't find that that something should be :P )

**Comment by The-Compiler** [comment]
Looks like various shortcuts [don't work properly](https://bugreports.qt.io/browse/QTBUG-54812) on macOS, so I wouldn't be surprised...

Maybe there's something in JavaScript you could run via `:jseval`, but I have no idea what that would be.

**Comment by piotryordanov** [comment]
What code do I supply to `:jseval` ?

**Comment by The-Compiler** [comment]
> but I have no idea what that would be.

**Comment by piotryordanov** [comment]
So, is there a command that can be run that would select the previous element? Maybe I can bind a custom key to this command.

**Comment by The-Compiler** [comment]
There are some `:move-to-*` commands, but not with QtWebEngine.

**Comment by piotryordanov** [comment]
I'm referring to `qutebrowser`. Are there commands for it?

**Comment by The-Compiler** [comment]
No.

**Comment by piotryordanov** [comment]
:(

**Comment by pkillnine** [comment]
You can do `bind <ctrl-tab> fake-key <shift-tab>`.

**Comment by piotryordanov** [comment]
@pkillnine I tried and it didn't do the job :/ 
(I had to `--force` for it to work)

**Comment by pkillnine** [comment]
Really? it works for me

**Comment by piotryordanov** [comment]
@pkillnine which part? i'm guessing that ur not on mac, right?

**Comment by pkillnine** [comment]
Yeah I'm on Linux

**Comment by The-Compiler** [comment]
If `<Shift-Tab>` doesn't work, `:fake-key <Shift-Tab>` isn't going to work either.

Also, please consider that you send an email to at least 110 people with every comment here. This isn't a chat :wink:
