### ISSUE TITLE
:view-source freezes Qutebrowser until the tab appears

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2770]

**Comment by The-Compiler** [comment]
#2395 will help with QtWebEngine - with QtWebKit, I could theoretically do the rendering in its own thread I guess, but I won't bother :wink:

**Comment by mjauvin** [comment]
This resolves the problem:

```
diff --git a/qutebrowser/browser/commands.py b/qutebrowser/browser/commands.py
index 6ddb72636..6249131ea 100644
--- a/qutebrowser/browser/commands.py
+++ b/qutebrowser/browser/commands.py
@@ -1527,6 +1527,8 @@ class CommandDispatcher:
             new_tab = self._tabbed_browser.tabopen()
             new_tab.set_html(highlighted)
             new_tab.data.viewing_source = True
+            new_tab.url = lambda requested=False: QUrl(
+                'Source: {}'.format(current_url.toDisplayString()))
 
         tab.dump_async(show_source_cb)
```

**Comment by mjauvin** [comment]
I'll open a PR if you consider it's worth it.

**Comment by The-Compiler** [comment]
@mjauvin Huh? That change seems to be unrelated to the freeze happening when there's a lot of source code to format.

**Comment by mjauvin** [comment]
@The-Compiler you are right, I was visiting multiple issues before writing this and I ended-up writing this to the wrong one... I'll remove my comment.
