### ISSUE TITLE
Make hint groups/selectors configurable

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2773]
With the new config we have dictionaries in the config.

With that, we could make hint groups/selectors configurable. Currently those are hardcoded in `webelem.py`:

```python
SELECTORS = {
    Group.all: ('a, area, textarea, select, input:not([type=hidden]), button, '
                'frame, iframe, link, [onclick], [onmousedown], [role=link], '
                '[role=option], [role=button], img'),
    Group.links: 'a[href], area[href], link[href], [role=link][href]',
    Group.images: 'img',
    Group.url: '[src], [href]',
    Group.inputs: ('input[type=text], input[type=email], input[type=url], '
                   'input[type=tel], input[type=number], '
                   'input[type=password], input[type=search], '
                   'input:not([type]), textarea'),
}
```

This would make it possible to add hints for custom elements (if it's a per-url setting), or add new groups like "media" to hint audio/video elements to be opened with mpv.

Also, `:hint` could take a selector instead of a group name too.

**Comment by CmdrSharp** [comment]
Perhaps this could work sort of inverse of how Chrome highlights an element in the Chrome Inspector when highlighting markup? So in this case, you'd hover over an element on a site with your mouse, and have an option to make that element hinted.

**Comment by The-Compiler** [comment]
@CmdrSharp Better late than never I guess... Something like that would be nice, but is probably too complex right now. #674 is somewhat similar FWIW.
