### ISSUE TITLE
Spawning wget in background doesn't download anything

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2774]
With `~/tmp/dn` existing and this as `~/tmp/dnl`:

```bash
#!/bin/bash

url=$1
path=~/tmp/dn
/usr/bin/wget -nc --restrict-file-names=lowercase -E -P "$path" $url &
```

Only `:spawn -d ~/tmp/dnl {url}` works, a normal `:spawn` doesn't seem to do anything. Removing the `&` from the script makes it work, though.

Doing `python3 -c "import subprocess; subprocess.check_call(['/home/florian/tmp/dnl', 'www.heise.de'])"` in a shell seems to work.

**Comment by gebulmer** [comment]
Is this unexpected?

This behaviour is the point of `start` vs `start_detached` I think. With the &, that line of the script immediately returns, and the called process (the bash process) is terminated. 

With `start`, as far as I can see, all child processes get terminated, whereas with `start_detached` they do not, allowing the longer-running `wget` to complete.

**Comment by The-Compiler** [comment]
I'm not sure actually. I wouldn't expect Qt to terminate subprocesses if the parent process finishes, but if that's what `QProcess` does in general, that'd be fine. If I execute that script with `bash` (from zsh), the bash subprocess exits, but `wget` still continues to run.

**Comment by toofar** [comment]
You can put `wait` at the end of the script to make it wait for child processes in the backround!
Although I think this issue can be closed as not a qutebrowser problem...?
