### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by akz92** [qutebrowser/qutebrowser#2792]
I believe there is a memory leak after opening websites that are heavy on graphics. When I open the Google Maps website qute's memory usage jumps from 178mb to 400mb, my notebook starts using it's discrete graphic card, and even after closing the tab the memory usage stays the same and the notebook keeps using the discrete graphic card pointing qute as a dependency. If I close qute the graphics change to the integrated.

My installation details:
```
qutebrowser v0.11.0
Git commit: v0.11.0-8-g725d4a4 (2017-07-04 22:16:21 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.0
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
SSL: Secure Transport, macOS Sierra (10.12)

Style: QMacStyle
Platform: Darwin-16.6.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.12.5, x86_64
```

**Comment by The-Compiler** [comment]
Can you check if you see the same with [QupZilla](https://qupzilla.com/), and if you see the same with Google Chrome or Chromium?

**Comment by akz92** [comment]
Google Chrome also requests discrete graphics when I open Google Maps, but after closing the tab the graphics change back to integrated and the memory is freed.

QupZilla requests discrete graphics when I open the application (and keeps using it), when opening Google Maps the memory usage is increased too, but after closing it the memory if freed.

**Comment by The-Compiler** [comment]
I'll try to reproduce this next Wednesday when I should hopefully meet someone who happens to have a MacBook.

In the meantime, can someone else on macOS check if the same thing happens?

**Comment by The-Compiler** [comment]
So I was able to try this on an early 2013 Retina 13" Macbook Pro with macOS 10.11, but without hybrid graphics (I think?).

With both QupZilla and qutebrowser, the RAM usage climbs from ~200mb to ~900mb on Google Maps, especially when resizing the window.

When closing the tab, it stays on that for a while (2-3 minutes), and then goes back to ~200mb again.

Can you please try comparing qutebrowser and QupZilla again, but take care to not resize the window, and to wait long enough before looking at the RAM usage?

**Comment by akz92** [comment]
I compared them again without resizing the windows and waiting ~5min before looking at the RAM usage and I noticed some details that may help:

On QupZilla when I open Google Maps a new `QtWebEngineProcess` is spawned and it is the responsible for the increase in memory usage. Then main QupZilla process doesn't increase its memory usage. When I close the tab the `QtWebEngineProcess` is killed freeing the memory.

On qutebrowser when I open Google Maps a new `QtWebEngineProcess` is spawned increasing the memory usage in ~200mb, but the main qutebrowser process also increases its memory usage in ~200mb. When I close the tab the `QtWebEngineProcess` is killed freeing the memory, but the main qutebrowser process doesn't free the memory.

In case you have access to a macbook with hybrid graphics, I use this app to keep track of which graphics card is in use: [gfxCardStatus](https://github.com/codykrieger/gfxCardStatus)

**Comment by The-Compiler** [comment]
> On qutebrowser when I open Google Maps a new `QtWebEngineProcess` is spawned increasing the memory usage in ~200mb, but the main qutebrowser process also increases its memory usage in ~200mb. When I close the tab the `QtWebEngineProcess` is killed freeing the memory, but the main qutebrowser process doesn't free the memory.

This is the behavior I see in QupZilla as well. Are you sure you're using the latest release (2.1.2) from [their website](https://qupzilla.com/download#mac)?

**Comment by akz92** [comment]
Yes I'm using 2.1.2 from their website, installed through [Homebrew Cask](https://caskroom.github.io/)

**Comment by The-Compiler** [comment]
I have no idea why the behavior is different for you then... Anyways, I'm closing this in favour of #1476 which tracks some similar issues. I looked at it again yesterday and found out the Python wrappers indeed get kept around for some reason, but the underlying C++ objects seem to get deleted correctly.
