### ISSUE TITLE
Do we have some kind of "Lights Off" in Qutebrowser?

### ISSUE THREAD

**Issue by varmanishant** [qutebrowser/qutebrowser#2799]
This is just a question. I think it would be a nice feature. Any idea how to implement that?

**Comment by The-Compiler** [comment]
I don't know what exactly you mean with "Lights Off", but you can probably achieve it using the `ui -> user-stylesheet` setting. I personally use the dark version of [solarized-everything](https://github.com/alphapapa/solarized-everything-css).

**Comment by varmanishant** [comment]
How about some idea like this? I mean can I just bring an overlay transparent <div></div> with a tinge of gray?

```
<!DOCTYPE html>
<html>
    <head>
	<style type="text/css" media="screen">
	#overlay {
	    position: absolute;
	    top: 0;
	    right: 0;
	    bottom: 0;
	    left: 0;
	    background: #000;
	    opacity: .6;
	    filter: alpha(opacity=60);
	}    
	</style>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width" />
	<title>Filter</title>
    </head>
    <body>
	Body
    <div id="overlay"></div>
    </body>
</html>
```

**Comment by lahwaacz** [comment]
I don't think this problem should be solved in every single application. There are [global solutions](https://wiki.archlinux.org/index.php/Backlight#Color_correction) such as Xflux, Redshift, Clight and most certainly others.

**Comment by The-Compiler** [comment]
If you find a way to do this in CSS without adding a HTML element, you could already do that using the `ui -> user-stylesheet` setting.

If not, either of #30, #35 or #341 would make this possible somewhen in the future.

**Comment by varmanishant** [comment]
@lahwaacz yeah ... however I like the way llpp pdf viewer allows '[' ']' to adjust brightness.
