### ISSUE TITLE
Fatal Error: PyOpenGL missing on ArchLinux package

### ISSUE THREAD

**Issue by rperce** [qutebrowser/qutebrowser#2801]
After updating to 0.11.0, launching qutebrowser produces the following dialog:

> Fatal error: PyOpenGL is required to run qutebrowser but could not
> be imported! Maybe it's not installed?
>
> **The error encountered was:**
> No module named 'OpenGL'
>
> Please search for the python3 version of PyOpenGL in your
> distributions packages, or install it via pip.
>
> **If you installed a qutebrowser package for your distribution,**
> **please report this as a bug.**

I'm running qutebrowser 0.11.0 (`qutebrowser --version` produces the same error message, but the package manager knows) and ArchLinux kernel 4.11.9-1-ARCH:

```bash
$ pacman -Q qutebrowser
qutebrowser 0.11.0-2
$ uname -r
4.11.9-1-ARCH
```

Manually installing [`python-opengl`](https://www.archlinux.org/packages/extra/any/python-opengl/) restores functionality, although `qutebrowser --version` just launches qutebrowser normally instead of outputting version information. Adding that package to the `depends` list in the PKGBUILD should be all that's needed to fix it.

**Comment by The-Compiler** [comment]
It's listed as optional dependency:

```
$ pacman -Qi qutebrowser-git
Name            : qutebrowser-git
# [...]
Optional Deps   : # [...]
                  qt5-webengine: To use --backend webengine [installed]
                  python-opengl: To use --backend webengine [installed]
```

**Comment by The-Compiler** [comment]
Oh, as for "although `qutebrowser --version` just launches qutebrowser normally instead of outputting version information": Do you happen to have a `qutebrowser` wrapper in `$PATH` which doesn't forward `"$@"` correctly? :wink:

**Comment by rperce** [comment]
Ah, I was under the (clearly mistaken) impression that the webengine backend was the primary one now - my bad!

And, hey, I sure do. Good call!

**Comment by The-Compiler** [comment]
It will be with v1.0 somewhen later this year, but not quite yet.

You're not the first to think this, though - what made you think that was the case?

**Comment by rperce** [comment]
I've been using it exclusively for two or three releases and it's SUPER stable, feels and works great, and my (flawed!) wrapper means I never have to type `--backend webengine`. Honestly I've forgotten that the old backend is _still an option_! But there's certainly no *actual* reason I should have believed that :P
