### ISSUE TITLE
Tab history dialog

### ISSUE THREAD

**Issue by elshize** [qutebrowser/qutebrowser#2803]
I was thinking of the following enhancement. Say you browse pages within one website for a while, and at some point you just want to go back to some page, say the main page of the website. Going back with H one by one is just annoying and takes a lot of time if you want to go back, e.g., 10 pages.

I'm thinking it would be nice to be able to toggle a list of the current tab history and select the page you want to go back to. Sort of like when on chrome/firefox when you press and hold the back button. Or it could possibly be something else (any other ides?) that allows you to do this more efficiently.

**Comment by lahwaacz** [comment]
You can type `10H` to apply `H` ten times. And if you can live with an inappropriate warning, you can use something like `99H` to go at the very beginning.

As for the interactive way, see #32.

**Comment by michal-blippar** [comment]
Thanks!

**Comment by elshize** [comment]
Thanks!
