### ISSUE TITLE
New completion: Pass more information to completion handlers

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2814]
Some completion handlers would benefit from getting the already typed arguments, probably even in some parsed form.

cc @rcorre

**Comment by The-Compiler** [comment]
As discussed in https://github.com/qutebrowser/qutebrowser/pull/2848#issuecomment-317324738 (cc @Enzime), one thing which might be needed is the window ID of the completer.

It's probably best to pass some `CompletionInfo` or `CompletionContext` namedtuple to the completion functions (e.g. as a `info`/`context` keyword argument), that way we can easily add new information without having to change the signature of all completion functions.

**Comment by The-Compiler** [comment]
Some initial work on this has been done in the `new-config` branch, but e.g. the window ID isn't in there yet. Probably best to continue on this once `new-config` is in.

**Comment by rcorre** [comment]
I'm gonna say this is closed, as the framework for passing arbitrary data is there. More fields can be added as needed (e.g. `win_id` for #2848)
