### ISSUE TITLE
Use ctypes instead of PyOpenGL for nvidia workaround?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2821]
After some more thinking about the "black screen" issue when using nvidia graphics for some people, I think it could be solved by using ctypes.

@teto @thomas--graf you seemed to be affected by this, can you please try the following?

- Find out the path your qutebrowser sources are, `:open qute:version` will show them as `Imported from:`.
- Make it stop trying to import `OpenGL.GL`:
  - On v0.11.0, edit `browser/webengine/webenginesettings.py` and comment out `from OpenGL import GL`
  - On master, edit `misc/earlyinit.py` and comment out the `modules['OpenGL.GL'] = _missing_str("PyOpenGL")` line (not the `PyQt5.QtOpenGL` one)
- Start qutebrowser and make sure you get a black screen again.
- Now add this instead of the removed line:

## Variant 1

```python
import ctypes
ctypes.cdll.LoadLibrary("libGL.so.1")
```

## Variant 2

```python
import ctypes
ctypes.CDLL("libGL.so.1", mode=ctypes.RTLD_GLOBAL)
```

## Variant 3

```python
import ctypes
import ctypes.util
ctypes.cdll.LoadLibrary(ctypes.util.find_library("GL"))
```

## Variant 4

```python
import ctypes
import ctypes.util
ctypes.CDLL(ctypes.util.find_library("GL"), mode=ctypes.RTLD_GLOBAL)
```

- Tell me what variants worked :wink: If none of that helps, I have some more ideas :wink:

**Comment by thomas--graf** [comment]
Only variant 4 works for me.

**Comment by The-Compiler** [comment]
Hmm, interesting - but nice that it *does* work without PyOpenGL involved! Out of curiosity, what does `python3 -c 'import ctypes.util; print(ctypes.util.find_library("GL"))'` say?

**Comment by thomas--graf** [comment]
`libGL.so.1`

**Comment by The-Compiler** [comment]
huh, so this should be exactly equal to variant 2 then... I mean, I'm fine doing that if that's what it takes, but I don't know why 4 would work but 2 wouldn't.

**Comment by thomas--graf** [comment]
I checked variant 2 again, and it works now. Not sure if I made a copy-paste mistake on the first try. 1 & 3 are still broken, though.

**Comment by The-Compiler** [comment]
Okay, cool! I'll probably drop the PyOpenGL dependency again for v1.0 then.

**Comment by msiraj83** [comment]
@The-Compiler .... fine its work for me..
Thanks

**Comment by XiaoqiChai** [comment]
@The-Compiler 
both variant 2 and 4 work. 
But when I go to conda virtue environment, none of them works.
Can anyone help?
Thanks

**Comment by The-Compiler** [comment]
@XiaoqiChai huh, is this related to qutebrowser? I try to avoid Conda, as it's full of subtle issues :wink:

**Comment by XiaoqiChai** [comment]
@The-Compiler 
I did conda install pyopengl.
