### ISSUE TITLE
New completion and timezone issues

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2830]
@rcorre Let's continue the discussion from #2295 about timezones here, before we break GitHub completely 😆 

I've been looking into it a bit again, and as you say, Unix timestamps are *supposed* to be timezone-unaware, as they're defined as seconds since 1.1.1970 **UTC**.

# Creating timestamps

I've been investigating what's happening on the Python side a bit. Python has timezone-aware and timezone-unaware `datetime` objects. Using `.now()` or `.utcnow()` gives you timezone-*unaware* objects:

```python
>>> import datetime
>>> dt = datetime.datetime
>>> print(dt.now().tzinfo)
None
>>> print(dt.utcnow().tzinfo)
None  # WHYYY Python, would make a lot of sense for this to be UTC-aware...
```

However, `.timestamp()` [treats]( https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp) timezone-unaware timestamps as localtime:

> Naive datetime instances are assumed to represent local time and this method relies on the platform C mktime() function to perform the conversion. Since datetime supports wider range of values than mktime() on many platforms, this method may raise OverflowError for times far in the past or far in the future.

So using `dt.utcnow().timestamp()` takes the current UTC time as local time and then gets a (wrong) timestamp. Using `dt.now().timestamp()` gives us the correct value. However, `dt.now(datetime.timezone.utc).timestamp()` *also* gives us the correct value, without the drawback mentioned above:

```
>>> now, utcnow, utcnow_aware = dt.now(), dt.utcnow(), dt.now(datetime.timezone.utc)
>>> now
datetime.datetime(2017, 7, 20, 12, 42, 47, 51726)
>>> utcnow
datetime.datetime(2017, 7, 20, 10, 42, 47, 51733)
>>> utcnow_aware
datetime.datetime(2017, 7, 20, 10, 42, 47, 51738, tzinfo=datetime.timezone.utc)
>>> now.timestamp()
1500547367.051726  # correct
>>> utcnow.timestamp()
1500540167.051733  # off by 2h
>>> utcnow_aware.timestamp()
1500547367.051738  # correct
```

`time.time()` also returns the same correct value - so I think this part is fine in the PR as-is.

# Using the time module

The `time` module used in some places in the PR is a low-level API. It's fine for `time.time()` I guess, but the `time.mktime` and `time.strptime` calls should probably be replaced by the `datetime` API, using timezone-aware `datetime` objects.

# Parsing timestamps

As you found out, all timestamps are UTC (and were in the old history!), and hopefully correct. The `time` module change might actually change some behavior, not sure.

The only thing remaining is *displaying* them.

## SQL

Looks like we need to add `'localtime'` there so the displayed time is in local time:

```
[florian@hooch ~]$ date
Thu 20 Jul 13:05:22 CEST 2017
[florian@hooch ~]$ echo "select strftime('%H:%M:%S', $(date +%s), 'unixepoch')" | sqlite3
11:05:30
[florian@hooch ~]$ echo "select strftime('%H:%M:%S', $(date +%s), 'unixepoch', 'localtime')" | sqlite3
13:05:40
```

## JavaScript

Looks like `toLocaleTimeString()` converts from UTC to localtime correctly - tried with NodeJS:

```
> d = new Date(1500548853 * 1000);
2017-07-20T11:07:33.000Z

> d.toLocaleTimeString()
'1:07:33 PM'
```

**Comment by The-Compiler** [comment]
Quick update: Adding `localtime` to the `sqlite` query is actually the only thing I need to do to make the tests pass here. I'd still like the `time` module changes (except for `time.time()`), but I won't block the PR because of that.

**Comment by rcorre** [comment]
> Adding localtime to the sqlite query is actually the only thing I need to do to make the tests pass here

You mean without the other changes above? For me, that throws off the times shown when I actually run qutebrowser. I'll take a shot at implementing the changes above.

**Comment by The-Compiler** [comment]
Yes - and you're right. There's still something else wrong, then...

**Comment by The-Compiler** [comment]
https://github.com/qutebrowser/qutebrowser/pull/2295/files/f45acaa9c8104a865b2d5790f6e26ff34cbee77a..0eb347186cf0174166d6452a2420d20b511cecff should fix this.
