### ISSUE TITLE
option to hide tab/title bar if only one tab is visible

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#2838]
I run i3wm (as of a few months ago) and am hoping to start using qutebrowser as my daily browser.

I want a tab-less browser which just opens new links in a new window, and I just found `tabs-are-windows`, which does just that. Great!

The only improvement I would like would be to hide the title bar/tab bar, since the page title is already displayed in the i3 tab:

![1500670547](https://user-images.githubusercontent.com/14615/28482267-7be2810c-6e1c-11e7-9112-02a9324dc909.png)

Provided that I didn't miss a way to do that, some possible approaches:

- a `hide-single-tab` option
- tie this behavior to `tabs-are-windows`. Some people might want to keep the tab strip though, so this might cause more friction.

Since I'm the only one asking for this so far, I'd be happy to work on it when it bugs me enough to motivate.

**Comment by pkillnine** [comment]
`:set tabs show multiple` :D

**Comment by edrex** [comment]
thanks! I think this is fine. Seems like the qutebrowser community could use a dedicated support/FAQs tool like Discourse/Reddit to curate answers to these sorts of questions..

**Comment by The-Compiler** [comment]
There [is a subreddit](https://www.reddit.com/r/qutebrowser/) already, as well as a [mailinglist and IRC channel](https://github.com/qutebrowser/qutebrowser#getting-help).
