### ISSUE TITLE
mappings: some keys don't work with some keyboard layouts

### ISSUE THREAD

**Issue by sim590** [qutebrowser/qutebrowser#2844]
I have the standard `ca (multix)` keyboard configured (Canadian multilangual). In order to produce some characters I have to hit some sequence of keys and I conjecture that it confuses qutebrowser (I don't know what layer).

For e.g., on the one hand, when I want to use `set_mark`, I do the follwoing sequence `altcar+^+space` to produce the character \`. Then, I'd expect to set a mark by following the preceding sequence with a letter. I can confirm that it doesn't work, because when later trying to input `'<letter>`, it says the error `mark is not set`.

On the other hand, if I set the keyboard to english US and do the simple key press of \` followed by a letter, the expected behavior occur. I.e., I can later use `'<letter>` to jump to the mark.

Could it be related to the talks in #2350?

### Version

```
Version info

qutebrowser v0.10.1
Git commit: v0.10.0-873-g5ec94f96f (2017-06-26 21:51:35 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.5.3+
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.11.0-1-amd64-x86_64-with-debian-buster-sid, 64bit
Linux distribution: Debian GNU/Linux buster/sid (debian)
Frozen: False
Imported from /home/simon/prog/qutebrowser/qutebrowser
Qt library executable path: /home/simon/prog/qutebrowser/.venv/lib/python3.5/site-packages/PyQt5/Qt/libexec, data path: /home/simon/prog/qutebrowser/.venv/lib/python3.5/site-packages/PyQt5/Qt

Paths:
system_data: /home/simon/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
download: /home/simon/Téléchargements
config: /home/simon/.config/qutebrowser
cache: /home/simon/.cache/qutebrowser
data: /home/simon/.local/share/qutebrowser
Copyright info

Copyright 2014-2017 Florian Bruhin (The Compiler)

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/ or open qute://gpl.
```

**Comment by The-Compiler** [comment]
Can you run `python3 -m scripts.keytester` in qutebrowser's repo and see what happens in there with that key sequence?

**Comment by sim590** [comment]
I get the following:
```
None

key: 0x1001103
modifiers: 0x40000000
text: ''
```

If I set the keyboard to english US, I can produce:
```
`

key: 0x60
modifiers: 0x0
text: '`'
```

**Comment by The-Compiler** [comment]
Looks like Qt simply sees AltGr + Mode_switch here. I don't think there's a way to support this in qutebrowser though, I'm afraid - the keybindings only seem to work on single keys (with optional modifiers), and I don't think I can get more information about combinations like that from Qt.

**Comment by byllgrim** [comment]
Does this mean that I am forever out of luck with my colemak layout?
The letter ē doesn't work in qutebrowser (I had to paste it from a text editor).
I can type most other letters æáðè.

á is just "altgr + a", it works and scripts.keytester shows it properly.

è is done by first "altgr+r" then "e", but even though it works in the browser, scripts.keytester is absolutely confused by this combination: It insist that my key presses are "altgr+altgr" then "altgr+altgr".

ē is "altgr + m" then "e" and the browser just ignores this. Keytester almost understand it: "altgr + <that horizontal bar>" and then "e".

```
qutebrowser v1.6.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.1
PyQt: 5.12
```
