### ISSUE TITLE
Make current tab font bold

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#2864]
I'd like to more easily spot the currently active tab in the tab bar. I can already set the colors, but I would also like to set the font bold for the active tab, but not the others.

**Comment by kmarius** [comment]
I just tried it out to see how it looks, and I'm not really a fan:

![](http://i.imgur.com/WMYNMxg.png)

First two bars are with the default config, bottom ones are mine. I can make a PR with a new config option, if it is desired.

**Comment by The-Compiler** [comment]
@kmarius As mentioned in the [contribution docs](https://github.com/qutebrowser/qutebrowser/blob/master/CONTRIBUTING.asciidoc) at the top, the new config system will be merged in September, and won't be reviewing PRs for new features until then.

However, can you please just post the patch (e.g. `git show`) here as a code block?

**Comment by kmarius** [comment]
I see. Here is what I did, assuming the text is not bold otherwise. The better option would be loading and setting the font only for the selected tab, and restoring it afterwards.

```
diff --git a/qutebrowser/mainwindow/tabwidget.py b/qutebrowser/mainwindow/tabwidget.py
index c70d4f4ca..d5afc9c84 100644
--- a/qutebrowser/mainwindow/tabwidget.py
+++ b/qutebrowser/mainwindow/tabwidget.py
@@ -557,9 +557,13 @@ class TabBar(QTabBar):
 
             bg_parts = ['tabs', 'bg']
             fg_parts = ['tabs', 'fg']
+            font = p.font()
+            font.setBold(False)
             if idx == selected:
                 bg_parts.append('selected')
                 fg_parts.append('selected')
+                font.setBold(True)
+            p.setFont(font)
 
             if idx % 2:
                 bg_parts.append('odd')
```

**Comment by Ape** [comment]
@kmarius Thanks! This is just what I wanted.

**Comment by jamesbvaughan** [comment]
I'm a fan of the bold font for selected tab titles. Could it be added as an option?

**Comment by The-Compiler** [comment]
There's `fonts.tabs.selected` thanks to @kontheocharis now: #5512
