### ISSUE TITLE
Opening mpv using binded buttons takes too much time

### ISSUE THREAD

**Issue by lazygreed** [qutebrowser/qutebrowser#2866]
Opening mpv using `spawn mpv {url}` and `hint links spawn mpv {hint-url}` can take 
now ~5-10 minutes for open.

**Comment by The-Compiler** [comment]
What happens if you do the same (with the same URL) in a terminal?

**Comment by lazygreed** [comment]
It opens fine via terminal

**Comment by The-Compiler** [comment]
Can you run `qutebrowser --debug --temp-basedir`, run `:spawn mpv {url}` there on some page, and then do `:report` once mpv started please?

**Comment by lazygreed** [comment]
Lol, after 8 minutes I totally lost my internet connection. Now it back and all works fine.
I think all the problems were caused by it.
