### ISSUE TITLE
Do not hover elements when the mouse cursor is not inside qutebrowser window

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#2872]
I would like qutebrowser to unhover elements when I move the mouse cursor outside the qutebrowser window. I think the easiest way to explain what I mean is these steps to reproduce:

1. Hover some HTML element with mouse
   - One with visible hover effects, for example any link
2. Move the mouse away without it touching rest of the page on its way
   - E.g. `xdotool` or resize/scroll the page so that the element is on the edge of the window
3. Notice that the element is still hovered (the hover effects are active)

I often use hotkeys to warp the mouse pointer, so this is causing me some headache.

**Comment by The-Compiler** [comment]
This looks like a QtWebEngine issue, and should go to the [Qt bugtracker](https://bugreports.qt.io/) instead.

**Comment by The-Compiler** [comment]
Nothing qutebrowser can do about this as far as I'm aware.

**Comment by Ape** [comment]
This seems to be fixed with qutebrowser v1.2.1 + Qt 5.10.1.
