### ISSUE TITLE
Keys when using Jupyter Notebooks

### ISSUE THREAD

**Issue by lrargerich** [qutebrowser/qutebrowser#2876]
Hi,
Very simple question: When running Jupyter notebooks inside Qutebrowser the shift-enter key is not running the current cell.
Couldn't find anything online but I think this should be a fairly common issue, unless nobody is using qutebrowser with Jupyter :)
Thanks a lot for the help.

**Comment by pkillnine** [comment]
Try going into insert mode by pressing `i`, and then press shift-enter. If it doesn't work in input mode, then try it in passthrough mode (passes all keybindings except `esc` to the backend) which you press control-v to go into.

**Comment by parchd-1** [comment]
I have used Jupyter notebook a lot in qutebrowser. As pkillnine said, you need to go into insert mode. Sometimes you need to leave the cell and reenter it (possibly with the mouse), but most of the time just pressing "i" should do the trick.

Careful though - accidentally leaving insert mode and hitting a bound key can end in disaster.
