### ISSUE TITLE
Crash on GitHub new file page

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2877]
When clicking between the title and file input (in the log with a `.gitignore` file):

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 298, in <lambda>
    self._follow_selected_cb(jsret, tab))
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 268, in _follow_selected_cb
    elem = webengineelem.WebEngineElement(js_elem, tab=self._tab)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webengineelem.py", line 56, in __init__
    js_dict))
TypeError: Got <class 'dict'> for value from JS but expected (<class 'str'>, <class 'int'>, <class 'float'>): {..., 'value': {}}
```

I can't reproduce this right now, but I could earlier. It happened because it was a form with an input with `name='value'` getting serialized as web element.

We probably should just serialize as little as possible for `form` elements...

**Comment by Penaz91** [comment]
I managed to reproduce the bug successfully while saving a debug log, but it's quite long. Do you think it's ok to attach it here?

**Comment by The-Compiler** [comment]
Thanks for trying! I know what the issue is though, so I don't necessarily need a debug log. If you want to submit it anyways (just in case I can learn something new from it), just hit the "Report" button in the crash dialog.

**Comment by Penaz91** [comment]
Done, Hopefully it helps a bit.

**Comment by The-Compiler** [comment]
Thanks! For my own reference: https://crashes.qutebrowser.org/view/8c1123f6
