### ISSUE TITLE
Simplify getting Chromium version

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2881]
Currently we extract the Chromium version from the UA unconditionally. This can be problematic, especially when some kind of crash happens we don't want to create another QWebEngineView.

Instead, we should do this:

- Have a dict mapping Qt versions to their contained Chromium versions
- Have a test verifying that the dict is correct (i.e. checking it against the UA)
- Use that if possible, only fall back on parsing the UA if the Qt version is unknown
- Only get/parse the UA once, maybe even at startup time.

**Comment by lahwaacz** [comment]
Why is the last point not enough? You could do it on the master QWebEngineView instance before setting the custom UA, without creating another instance. If the UA parsing fails so early, knowing its value is hardly helpful for debugging...

**Comment by The-Compiler** [comment]
The custom UA is currently set globally, and the first QWebEngineView is created after settings are applied (it needs to be, for some settings). But if the startup performance impact of creating a throw-away QWebEngineView is small enough, that should be enough indeed.

**Comment by The-Compiler** [comment]
We do the UA parsing at startup nowadays - seeing that we also need it to get our own UA, there's no point in doing the rest mentioned in the original issue.
