### ISSUE TITLE
PSA: GitHub is broken

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2882]
So it looks like GitHub decided to break based on qutebrowser's user agent when using QtWebEngine... Not only does it display a notice, it also breaks all kinds of functionality (like the branch dropdown, or "New issue" button).

As a workaround, you can set your user agent to something like `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36` (faking a Chrome 59). This seems to make it behave even with Qt 5.7.1 (based on Chromium 49), but apparently breaks Google Docs.

I sent something like this to GitHub support:

> Hi! I'm a user of qutebrowser/qutebrowser, which is a browser based on the QtWebEngine project.
> 
> The latest QtWebEngine release is based on Chromium 56 with security releases backported, and has an user-agent like "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.9.1 Chrome/56.0.2924.122 Safari/537.36".
> 
> It now triggers the "Please note that GitHub no longer supports your web browser." notice, which is problematic for two reasons:
> 
> - The notice actually *breaks* things like the branch selector, but everything works perfectly fine when changing the user-agent to pretend it's Chrome 60... At the very least, things shouldn't be broken for no apparent reason.
> - With that in mind, it'd be nice if the notice was hidden when QtWebEngine/* is in the user agent.
> 
> Note this also affects other QtWebEngine-based browsers such as QupZilla/qupzilla, or OtterBrowser/otter-browser.
> 
> Thanks!

And got this back:

> We recently made some changes to our supported browser policy, and it appears likely that this is an unintended consequence.
>
> I’ve opened an internal issue for our engineering team to investigate, and will let you know as soon as we have any news to share.

You might want to do ~~the same~~ something similar, ideally not with the copy-pasted message :wink:

**Comment by ayekat** [comment]
Even the "reaction" button doesn't work, so I can't even add a thumbs-up emoji on your announcement -.-

Oh, and Preview for comments doesn't work either.

**Comment by lahwaacz** [comment]
Crap, now I clicked _something_ without a label which removed other person's comment... I'll try to add it back when I find the text in the email notification - sorry about that.

**Comment by lahwaacz** [comment]
In any case, more things that are broken:

- Clicking a reaction icon below a post used to add myself to the count, now it apparently removed the post.
- Editing posts
- On a profile page, the tooltip showing the number of commits in a particular day does not appear.

**Comment by The-Compiler** [comment]
Shit happens :wink:

That was @ayekat with:

> Even the "reaction" button doesn't work, so I can't even add a thumbs-up emoji on your announcement -.-
>
> Oh, and Preview for comments doesn't work either.

---

And yeah, probably anything needing JS on GitHub is broken. I guess they just disable their JS entirely when they don't like the user agent string...

**Comment by ayekat** [comment]
> Clicking a reaction icon below a post used to add myself to the count, now it apparently removed the post.

Perhaps this was a coincidence - I removed my own comment because I thought it would not add much to this discussion.

... or at least let's hope it's that.

**Comment by lahwaacz** [comment]
Well, it's possible (although very improbable) that we just clicked at the same time :laughing:

**Comment by TrilbyWhite** [comment]
I'm not even able to add a reaction to posts/issues.  I just came here to see if this issue was addressed, and was glad it was.  I was going to give a thumbs up, or similar, but don't seem to be able to.  So *thumbs up*.

**Comment by The-Compiler** [comment]
Current state:

Qt 5.9 (Chromium 56): Everything seems to work fine again.
Qt 5.8 (Chromium 53): No warning, branch dropdown works, "Filter" button in issue search box is gone.
Qt 5.7.1 (Chromium 49): Warning shown, branch dropdown (and probably everything else needing JS) broken.

Haven't heard back from GitHub support yet.

**Comment by SirCmpwn** [comment]
I just heard back from GitHub, who said they fixed shit. And so far as I can tell, shit has been fixed.

**Comment by SirCmpwn** [comment]
qt 5.9

**Comment by The-Compiler** [comment]
I heard back now as well, and told them about the situation with Qt 5.7.1 (which is packaged at least on Debian stable/testing, Ubuntu 17.04/17.10, and Gentoo).

I mean, I'd even be fine with the banner being shown, but there's really no reason for functionality to break given that it works fine again when changing the UA.

Note that it suffices to pretend to be Chromium 53 in the UA, which might be a better option for people suffering from this. Here's the UA I'd suggest to set as a work-around, for Qt 5.7.1:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.7.1 Chrome/53.0.2785.143 Safari/537.36
```
This at least lies as little as possible (`Chrome/49.0.2623.111` -> `Chrome/53.0.2785.14`).

**Comment by The-Compiler** [comment]
> I'm afraid this is expected currently. As a workaround, would you be able to upgrade to Qt 5.9 ( Chrome 56) ?

...oh well. If you're on Qt 5.7.1 (Debian/Ubuntu/Gentoo), please let GitHub support know that they shouldn't be breaking things without any reason.

**Comment by jgkamat** [comment]
I personally think this highlights a larger problem. 

If GitHub is willing to first block all (webengine) qutebrowser installations, and now block all except arch (and maybe fedora) installations, we might want to look into moving development somewhere more friendly to qutebrowser (to at least have somewhere to turn to if GitHub changes their mind later on). It would be really bad for qutebrowser if GitHub decided one day that they would no longer support any *released* qt versions, and we had no alternative to move to, since most qutebrowser developers use qutebrowser to interact with GitHub. Techically, GitHub still only supports the *latest* version of chrome and safari, which means that qutebrowser will **never** be "supported".

IMO the UA hack is not sufficient, because it essentially greenlights GitHub to re-write the entire site using only (latest) chrome features, which would actually break everyone using the UA hack completely.

**Comment by The-Compiler** [comment]
There are certainly good alternatives to move to, such as [GitLab](https://about.gitlab.com/) (or [BitBucket](https://bitbucket.org/), though I refuse to call that a good alternative).

The code itself also used to be mirrored on [my own git server](http://git.the-compiler.org/) but I stopped pushing updates there because nobody used it and it made my life a bit easier to only have one repo.

However, let's face it - qutebrowser never would be able to get the traction (and contributors) it has somewhere other than GitHub. GitHub just is a great option for visibility, and I don't see that changing anytime soon. I'd only consider moving away as a last resort, and then it doesn't make sense to invest too much time into this until (if at all) that point comes.

I also think they'll keep support at least for a couple of old Chromium releases. I bet there are other reasons people are still using those. And note it's not actually about features only present in newer Chromium releases, it's really just arbitrary.

So yeah, there are only a couple of pragmatic solutions for this (moving away isn't, IMHO):

- The UA hack. If needed, turned on by default for github.com.
- Talking to GitHub support and convincing them to not break things arbitrarily (i.e. keep serving JS even with the warning).
- Convincing people on Debian/Ubuntu/Gentoo releases to [install PyQt from PyPI](https://github.com/qutebrowser/qutebrowser/blob/master/INSTALL.asciidoc#installing-qutebrowser-with-tox) on affected distributions. After all, keeping an old QtWebEngine around **is** a bad thing, also for security reasons.

**Comment by The-Compiler** [comment]
Now QtWebKit got hit too, with this default UA:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) qutebrowser/0.11.0 Version/9.0 Safari/602.1
```

with WebKitGTK/Epiphany, it works:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/604.1 (KHTML, like Gecko) Version/11.0 Safari/604.1 Epiphany/3.24.3
```

with WebKitGTK/Midori, it doesn't (no idea why it'd send `Chrome/18.*` though):

```
Mozilla/5.0 (X11; Linux) AppleWebKit/537.32 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/537.32 Midori/0.5
```

Looks like it's `Version/9.0` this time, and `Version/10.0` makes it work. @annulen, should an up-to-date QtWebKit still claim it's Safari 9.0?

**Comment by annulen** [comment]
>should an up-to-date QtWebKit still claim it's Safari 9.0?

Up-to-date shouldn't, but it needs to be made up-to-date first :)

**Comment by The-Compiler** [comment]
https://github.com/annulen/webkit/pull/596 should fix this for QtWebKit

**Comment by jgkamat** [comment]
Not entirely sure about this, but I think github seems to have disabled the banner completely. For me:

Qt 5.7.1 (Chromium 49): No banner, javascript working again, filter button seems to be working.
Qt 5.7.1 (legacy qtwebkit): No banner, no dropdowns working (which I think was a problem before)

I don't want to test out the other versions, but I suspect they work fine now :tada:

**Comment by The-Compiler** [comment]
Looks like this is fixed for a while now - still no official statement from GitHub, but let's close this and hope it stays this way.
