### ISSUE TITLE
Qutebrowser crashes upon opening (killed by SIGSEGV (core dumped))

### ISSUE THREAD

**Issue by Newexplorer** [qutebrowser/qutebrowser#2885]
Qutebrowser crashes when I try to open it. I installed qutebrowser a few days ago so I probably have the latest version. Qutebrowser worked well before this issue came up.
I ran qutebrowser in debug mode: 
[ub.txt](https://github.com/qutebrowser/qutebrowser/files/1199572/ub.txt)
and I ran qutebrowser with the strace command:
[u.txt](https://github.com/qutebrowser/qutebrowser/files/1199574/u.txt)

My system is:
CPU: Quad core AMD A8-7410 APU with AMD Radeon R5 Graphics (-MCP-) 
speed/max: 1000/2200 MHz 
Kernel: 4.4.0-89-generic x86_64 
Up: 46 min 
Mem: 1253.5/7655.1MB 
HDD: 1000.2GB(6.7% used) 
Procs: 230 Client~Shell 
inxi: 2.2.35
Ubuntu: 16.04 LTS

If you need more information, let me know.

**Comment by The-Compiler** [comment]
Can you please [get a stacktrace using gdb](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc#crashes-which-can-be-reproduced)?

Note that Ubuntu's QtWebKit is very old though, and is soon not going to be supported anymore in qutebrowser. You can instead [install qutebrowser/PyQt via tox](https://github.com/qutebrowser/qutebrowser/blob/master/INSTALL.asciidoc#installing-qutebrowser-with-tox) to get a more up-to-date Qt with QtWebEngine as backend.

**Comment by Newexplorer** [comment]
[gdb.txt](https://github.com/qutebrowser/qutebrowser/files/1199708/gdb.txt)

When I start qutebrowser, I get the Whoops! window, and then it crashes.
This morning I noticed that I couldn't open my session mail (session-load mail).

**Comment by The-Compiler** [comment]
So yeah, this is an issue with the old QtWebKit - nothing qutebrowser can do about that. It probably dies while trying to restore the session, which can be fixed by removing or editing `~/.local/share/qutebrowser/sessions/_autosave.yml`.

**Comment by Newexplorer** [comment]
Yes, that worked.
