### ISSUE TITLE
Keyboard repeat delay and rate affect smooth scrolling behaviour. 

### ISSUE THREAD

**Issue by ahtn** [qutebrowser/qutebrowser#2890]
The rate at which smooth scrolling updates the view seems to depend on key press and repeat events. This means changing your OS keyboard repeat rate and repeat delay will affect the behaviour of smooth scrolling in qutebrowser. In the current implementation this causes a delay when scrolling that is dependent on the keyboard repeat delay, and I find that this makes smooth scrolling feel unresponsive/choppy.

Instead qutebrowser should only look at key down and up events and use an internal setting to control scroll speed which is independ of the OS's keyboard settings.

**Comment by The-Compiler** [comment]
All qutebrowser does is turning smooth-scrolling on/off, so you'd need to report this to QtWebKit and/or QtWebEngine.

**Comment by Ape** [comment]
This doesn't necessarily require changes in QtWebEngine smooth scrolling. Yes, it would be possible to implement it there, but we could also implement this using the existing `scroll-px` and some key bindings.

**Comment by The-Compiler** [comment]
Implementing smooth-scrolling via `:scroll-px` is probably going to be a performance nightmare, though.
