### ISSUE TITLE
Create a qutebrowser duckduckgo cheat sheet

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#2894]
Even though qutebrowser uses ddg as it's default search engine, there is no qutebrowser cheat sheet in duckduckgo! 

I'm currently working on this. This is what I have so far:

![2017-08-08-172609_1651x555_scrot](https://user-images.githubusercontent.com/4349709/29101754-420f5666-7c69-11e7-84d4-ab719253d46a.png)

If you've made goodies before, I'm working on this [on this branch](https://github.com/jgkamat/zeroclickinfo-goodies/tree/jay/qutebrowser-cheatsheet).

Comments/feedback/criticism is appreciated! Ideally I would like to iron out all the content issues before submitting it in a PR to the duckduckgo team.

**Comment by kirkins** [comment]
I'm hoping you'll release this soon because I'm making the switch and often need to reference the documentation.

**Comment by The-Compiler** [comment]
@kirkins FWIW there's already a [cheatsheet image](https://qutebrowser.org/img/cheatsheet-big.png)

**Comment by jgkamat** [comment]
If @The-Compiler gives a +1, I'll go ahead and submit this to DDG. We can always update it later if we miss anything or if we want to add more things, but I wanted to make sure the basics were covered :).

**Comment by jgkamat** [comment]
Also, do you think it's worth it to list all the extended hinting modes here? Right now I'm using `;*`, but that might be ambiguous (and people might actually press a literal `;*`. Maybe I could make it `;<KEY>` or similar.

**Comment by The-Compiler** [comment]
Some comments:

- I think `;<key>` or so is fine, people will hopefully also notice the keyhint thing pop up
- you have `j` and `k` as "scroll down", and then `j` as "scroll up". That should be j for down and k for up.
- Maybe say `<num>T` or so for "select tab"?
- Not sure whether it makes sense to mention `:bookmark-load`, as they're listed with `o` already anyways.
- I haven't checked whether anything important is missing yet.

**Comment by jgkamat** [comment]
All good suggestions:

> you have j and k as "scroll down", and then j as "scroll up". That should be j for down and k for up.
 
entirely my bad :).

> Not sure whether it makes sense to mention :bookmark-load, as they're listed with o already anyways.

agreed, it feels out of place (since this documents keys more than commands).

Here's a new image ([commit here](https://github.com/jgkamat/zeroclickinfo-goodies/commit/8cfaf5bf27d9aafe566c2ad50e48d8ddfaae2dfd)), please let me know if you have any more feedback (after your exams)
![2017-08-15-195101_1619x562_scrot](https://user-images.githubusercontent.com/4349709/29341569-ff7f1270-81d9-11e7-8999-1cdef2d7527f.png)

**Comment by The-Compiler** [comment]
Seems fine to me from a quick look - I guess we can always iterate on it later? Feel free to upload it FWIW.

**Comment by jgkamat** [comment]
Ok, I'll submit this to DDG, just let me know if you notice any issues later on, I'd be happy to maintain it :)

**Comment by jgkamat** [comment]
Merged now, so I'm closing this. Hopefully ddg will push this to everyone soon :smile:
