### ISSUE TITLE
URL percent-encoding in the SQL history

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2903]
There are couple of problems:

- The [add_url](https://github.com/qutebrowser/qutebrowser/blob/49b858e3599a361cf5c994358c6b189dddfb522c/qutebrowser/browser/history.py#L162) method does percent-encoding, but the [parse_entry](https://github.com/qutebrowser/qutebrowser/blob/49b858e3599a361cf5c994358c6b189dddfb522c/qutebrowser/browser/history.py#L192) method does not. So the URLs which were imported from the text file are not percent-encoded, but the newly added URLs are, which leads to "duplicates" if I open an old URL.
- The old history completion called [entry.url.toDisplayString()](https://github.com/qutebrowser/qutebrowser/pull/2295/files#diff-d0e110fc69342b1ed59bb5c1a96b0234L101) when the URL was added to the completion. Now the completion shows URLs as they are in the database, which is inconsistent (see the previous point) and a visual regression (I want pretty URLs in the completion).

cc @rcorre

**Comment by rcorre** [comment]
- I think we probably can just use `toDisplayString()` everywhere, that should simplify things
- I think this should handle "duplicates" -- formatting should now be consistent between old and new history. if you visit a url you visited before, it will have the same primary key and will replace the old entry in the completion table

**Comment by lahwaacz** [comment]
You probably wanted to comment on the pull request rather than here :confused: (though we could still copy-paste our comments and delete the ones here...)

As for the "duplicates", I already have a `spa%20ce`-type URL in the CompletionHistory table, so adding `spa ce` does not hit any primary key constraint and both URLs will coexist forever. The only difference the changes make is that the `spa ce` URL will appear on top, because it has the more recent timestamp.
