### ISSUE TITLE
videos won't play on bitchute

### ISSUE THREAD

**Issue by dvs1** [qutebrowser/qutebrowser#2906]
It seems to download the videos but won't play them.

https://www.bitchute.com/faq
It's based on https://webtorrent.io/faq

OSX 10.11.6
Qt 5.9.1 (brew)
PyQt 5.9.1 (brew)
qutebrowser 0.11.0 (pip3) (webengine)

Thanks for the unique FOSS web browser! 😎

**Comment by The-Compiler** [comment]
You'll need to rebuild Qt and pass the `-proprietary-codecs` option to `./configure` for this to work. Doesn't look like Homebrew has an option for it, unfortunately, but I guess you can edit the Formula.

**Comment by dvs1** [comment]
Thank you! ✌️
