### ISSUE TITLE
Images do not work on medium.com

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#2908]
I noticed that images are not showing up on medium.com articles.

Here is one example: https://medium.com/usevim/what-is-modern-vim-2591f6b1ec04

The left side is qutebrowser and the right side is Chromium: https://x.ape3000.com/projects/qutebrowser/medium_images.png

It seems that this happens with all medium.com articles and rarely on some other sites, too.

**Comment by The-Compiler** [comment]
Works fine here. Can you please show the output on `:open qute://version`?

(There really is a reason the issue template asks you to do so...)

**Comment by Ape** [comment]
The issue happens on 0.11.0:
```
qutebrowser v0.11.0
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017
```

**Comment by The-Compiler** [comment]
What distribution is that on, and how did you install Qt? Can you reproduce it with `--temp-basedir` too?

**Comment by Ape** [comment]
I figured it out. I had added `--qt-flag disable-reading-from-canvas` to my alias. The issue only hapeens with that flag.
