### ISSUE TITLE
white screen in between pages loading

### ISSUE THREAD

**Issue by tklebanoff** [qutebrowser/qutebrowser#2912]
qutebrowser v0.9.1

Hi there,
First off, I want to preface this 'issue' with a word of praise.  Thank you for creating and maintaining this amazing software.  To be honest, this is by far and away the best web browsing experience I have ever encountered.  

There is one thing that I can't seem to find a solution for, and I was wondering if there is a fix.  Here is some background:

I have set my user sylesheet to the following:
::-webkit-scrollbar {
	width: 0px; height: 0px;
}

html, img {
  -webkit-filter: invert(1) hue-rotate(180deg);
  filter: invert(1) hue-rotate(180deg);
}

body {
  background: black;
}

This setup has been working great for a dark mode style of browsing.  I was also able to successfully change the start page to a blank black screen.  

The issue is that sometimes, between pages, there is a flash of white light before the page loads in dark mode.  Most of my browsing is done at night, and this burst of white light can be jarring.  I was wondering: is there a straightforward way to set a user stylesheet for this loading screen?  If not, is there another fix?

Thanks

**Comment by The-Compiler** [comment]
Thank you! 😄 

The best you can do is something like `:set colors webpage.bg black`. Unfortunately, that also turns any website without a background color black, but I guess you could work around that in the CSS somehow...

**Comment by amerlyq** [comment]
Unfortunately, this override doesn't work for any of major sites, e.g. google, stackoverflow or github.
Changes to Qt allowing such overrides (mentioned in #2720) seem abandoned. 
Maybe you know what else we may await/depend, beside mailing to google inc. and begging to disable default enforcing of white color? :)

**Comment by jgkamat** [comment]
@amerlyq, it sounds like you want to set a CSS rule to override sites (I'm not sure if you're talking about the flashing, or the base color). I personally use https://github.com/alphapapa/solarized-everything-css, with a custom theme, and it works pretty well for most sites, but if you only want to change the background page, you should be able to use a much smaller CSS file.

see `content.user_stylesheets`

**Comment by amerlyq** [comment]
Nope, whole this thread and the one I mentioned are about "white flashing"
in-between transition between pages or reloading the same page. Using css
is not enough, as using default background color of webgui.

**Comment by The-Compiler** [comment]
The change mentioned in #2720 is about style sheets only being applied when the page finished loading - in the meantine, this was fixed in qutebrowser differently. I don't think there's anything that can be done about the white flashing before any page is loaded.

**Comment by amerlyq** [comment]
You know, I would be glad even with some ugly crotch, because eyes are
really hurt at night from sudden flashes, even if you expect them. I see
this optional crotch as one off two variants - keep showing previous page
until css applied, if we can control what is shown in qt web engine, or
draw on transition some big black rectangle over whole web frame with one
second timeout, if we can't. It's ugly as hell, but disappearing text is
better then returning white bg.

**Comment by hnicke** [comment]
@amerlyq While setting yp qutebrowser I've stumbled across the same behaviour. For me, changing the backend to 'webkit' helped - no white flashes anymore.
```
:set backend webkit
```

**Comment by amerlyq** [comment]
@hnicke Many thanks! 
After Arch package default's transition to WebEngine instead of deprecated WebKit, I never looked back.
I suppose using WebKit for night browsing is more feasible workaround, than masking whole screen by black squre -- at least until WebKit support isn't removed irrevocably. After all, now I got back Caret mode for free.
However, it would be better if we could prevent showing newly loaded page in WebEngine until CSS applied.

**Comment by The-Compiler** [comment]
> instead of deprecated WebKit

Note that Arch's QtWebKit package is the [updated fork](https://github.com/annulen/webkit/wiki), which is still fully supported. I intend to keep supporting it as long as PyQt/Arch do.

> now I got back Caret mode for free

That'll [soon come to QtWebEngine too](https://github.com/qutebrowser/qutebrowser/pull/3348) :wink:

> However, it would be better if we could prevent showing newly loaded page in WebEngine until CSS applied.

We can't. Loading and drawing of pages is entirely handled by QtWeb(Kit|Engine).

**Comment by aba-hollerer** [comment]
If qtwebengine is being compiled from source one may patch it like so:
```
--- src/webenginewidgets/api/qwebenginepage.cpp
+++ src/webenginewidgets/api/qwebenginepage.cpp
@@ -1070,7 +1070,5 @@
     Q_D(QWebEnginePage);
-    if (d->m_backgroundColor == color)
-        return;
-    d->m_backgroundColor = color;
+    d->m_backgroundColor = QColor(45,45,45);
     d->adapter->setBackgroundColor(color);
 }

```
Just don't use Qt::transparent since all hints and the history/bookmarks popup will be invisible.

**Comment by smartlitchi** [comment]
@aba-hollerer your solution worked but it had the side effect of putting a dark background to webpages that were not designed for it, making the whole thing hard to read

![image](https://user-images.githubusercontent.com/56811153/124761591-3f66e980-df32-11eb-96e5-9a5d6714573e.png)

Any idea how to fix that ?

**Comment by aba-hollerer** [comment]
@smartlitchi it seems like you are missing the colors.webpage.darkmode.enable = True property (see https://www.qutebrowser.org/doc/help/settings.html#colors.webpage.darkmode.enabled).

**Comment by smartlitchi** [comment]
Oh I am using colors.webpage.preferred_color_scheme = "dark" because I didn't want to artificially invert colors instead of using a dark theme when it was provided. I guess it's incompatible with your fix
