### ISSUE TITLE
Follow hint font rendering issue

### ISSUE THREAD

**Issue by mohamed-aziz** [qutebrowser/qutebrowser#2917]
The follow hint text doesn't render well, I'm not sure why

here is a screenshot 

http://imgur.com/a/SSW5q

version:
    Git commit: v0.11.0 (2017-07-04 18:02:34 +0200)

**Comment by Ape** [comment]
What font do you have in your config for `fonts.hints`? Have you tried changing it?

**Comment by mohamed-aziz** [comment]
Yes changing fonts.hints fixes it in fact I have a problem with Monospace font since I patched my fontconfig, Thanks for your help, I did not know you can change the hints font.
