### ISSUE TITLE
Document alternative NixOS installation

### ISSUE THREAD

**Issue by Enzime** [qutebrowser/qutebrowser#2918]
Alternatively, can be installed by adding to `/etc/nixos/configuration.nix`

```
nixpkgs.config.packageOverrides = pkgs: {
    qutebrowser = pkgs.qutebrowser.override { withWebEngineDefault = true; };
};
```

This will also patch qutebrowser to run with `--backend webengine` by default

**Comment by The-Compiler** [comment]
Probably obsolete as soon as there's an option for the backend, which should be in a few weeks.

**Comment by Enzime** [comment]
Setting the default backend isn't that important, the main part is, rather than necessarily installing qutebrowser in your local nix profile, you can install it globally by adding `qutebrowser` to your `environment.systemPackages` in `/etc/nixos/configuration.nix`

**Comment by The-Compiler** [comment]
But that's probably a generic NixOS thing valid for any package? Then I don't see why it should be in our instructions.

**Comment by Enzime** [comment]
The way I see it is just providing to alternative examples of how to install qutebrowser on NixOS.

**Comment by lahwaacz** [comment]
Doesn't the [official documentation](https://nixos.org/nixpkgs/manual/#chap-packageconfig) already contain enough examples? Enhancing the [NixOS section](https://github.com/qutebrowser/qutebrowser/blob/master/INSTALL.asciidoc#on-nixos) with a link to the upstream documentation, along with a link to the [nix file for qutebrowser](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/browsers/qutebrowser/default.nix) would be much more valuable than adding an arbitrary example without any references or exmplanations.

**Comment by The-Compiler** [comment]
@jagajaga @abbradar What's your take on this?

**Comment by jagajaga** [comment]
This shouldn't be in documentation because it's a generic way of adding pkgs to a system profile in Nixos.
