### ISSUE TITLE
question: user settings file

### ISSUE THREAD

**Issue by bounceme** [qutebrowser/qutebrowser#2919]
```
qutebrowser v0.11.0
Git commit: v0.11.0-8-g725d4a4 (2017-07-04 22:16:21 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)
```

I see the config is saved to /Library/..../ on osx.  where is the file where i view/edit simple overrides, externally?

**Comment by bounceme** [comment]
also: how do i remove aliases ? sorry for the trivial questions

**Comment by jgkamat** [comment]
I'm not sure exactly what you are looking for, but I'll try to list a few things that I think you might find helpful. Here's my qute:version for reference:

```
qutebrowser v0.11.0
Git commit: v0.11.0-103-gee1707c4d (2017-07-16 20:20:33 +0200)
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.9.0-3-amd64-x86_64-with-debian-9.1, 64bit
Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
Frozen: False
Imported from /usr/local/lib/python3.5/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
system_data: /home/jay/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
config: /home/jay/.config/qutebrowser
download: /home/jay/Downloads
data: /home/jay/.local/share/qutebrowser
cache: /home/jay/.cache/qutebrowser
```

qute:version tells me that my 'config' directory is /home/jay/.config/qutebrowser. Keybindings are (currently) located at ${CONFIG_DIRECTORY}/keys.conf and settings are located at ${CONFIG_DIRECTORY}/qutebrowser.conf. So on my system, keys are located at `/home/jay/.config/qutebrowser/keys.conf` and config is located at `/home/jay/.config/qutebrowser/qutebrowser.conf`. Does that answer your question?

I'm not sure if there is a built-in command for removing aliases, but you can remove them manually by deleting them from the [aliases section of your qutebrowser.conf](https://github.com/jgkamat/dotfiles/blob/10b5d490e024b31e696f9f85c77560144f06de75/qutebrowser/.config/qutebrowser/qutebrowser.conf#L1053-L1056) and restarting qutebrowser.

**Comment by bounceme** [comment]
thanks, will try this.

>  aliases section of your qutebrowser.conf

did you make that or was it auto-generated? I'd rather have the default runtime, with all defaults, then my own customizations in ${CONFIG_DIR} (without duplicating all the defaults)

**Comment by jgkamat** [comment]
The aliases that I linked to are my personal ones, which I added myself. 

I think the workflow your describing isn't possible (if I'm understanding it properly) since qutebrowser overwrites user defined config files in ${CONFIG_DIR} if you change settings through the normal means (ie: through `:set`). I think the workflow you are looking for will be possible after the new config is implemented (which is being worked on), through the python config. That isn't ready for general use yet though.

**Comment by bounceme** [comment]
maybe my problem is with the osx default config location being in `/Users/x/Library/Preferences/qutebrowser` . i guess i'll just symlink it to ${$XDG_CONFIG_HOME}

**Comment by bounceme** [comment]
https://github.com/qutebrowser/qutebrowser/blob/eaecfe5882f59abaecabb688340c88b8638f4b1b/doc/qutebrowser.1.asciidoc#L121

probably wont have to link it

**Comment by The-Compiler** [comment]
FWIW `XDG_CONFIG_HOME` is only used on Linux. Also see #383.
