### ISSUE TITLE
Allow storing the adblock lists somewhere else

### ISSUE THREAD

**Issue by ahsis** [qutebrowser/qutebrowser#2921]
After the new config lands can you please add a way to chance the path of the downloaded adblock list ?

**Comment by The-Compiler** [comment]
Why?

**Comment by ahsis** [comment]
Well, I have my own custom hosts file made for firejail and I thought instead of symlinking I can just point qutebrowser towards that.

**Comment by The-Compiler** [comment]
You can add `file://` URLs to the adblock filter lists too, though you'd still need to run `:adblock-update` on changes. I don't want to add settings to change the location of all kinds of data files, sorry.
