### ISSUE TITLE
QtWebEngine processes should get stopped on SIGSTOP

### ISSUE THREAD

**Issue by blueyed** [qutebrowser/qutebrowser#2922]
When sending SIGSTOP to the qutebrowser process (`kill -STOP $PID`), all its QtWebEngineProc should get stopped, too.  But they are still consuming CPU.

I am experimenting with stopping CPU intensive apps when they are not focused (https://github.com/awesomeWM/awesome-www/pull/111).

However, the editor being spawned through `Ctrl-E` should not get stopped probably (although it belongs to the same PGID).

```
qutebrowser v0.11.0
Git commit: v0.11.0-336-g629f6a687 (2017-07-27 09:56:34 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.20.0
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017
```

**Comment by The-Compiler** [comment]
QtWebEngine doesn't have any API to interact with subprocesses. Also, SIGSTOP can't be intercepted by any process (like SIGKILL), so there's no way to do this either way.

**Comment by Ape** [comment]
@blueyed You can send the stop signal to all child processes, too.

```lua
function kill_recursive(pid, signal)
    awful.spawn.with_shell("pstree -p " .. pid .. " | grep -o '([0-9]\\+)' | grep -o '[0-9]\\+' | xargs kill -" .. signal)
end
```

**Comment by blueyed** [comment]
@Ape 
Thanks.  I am using `pkill -g` already - but wondered if it could be avoided.

**Comment by blueyed** [comment]
@The-Compiler 
Would it be possible for qutebrowser to stop QtWebEngineProc in inactive tabs?

**Comment by The-Compiler** [comment]
No, qutebrowser has no control over those processes at all (it doesn't even know their PID). It could possibly not create a QWebEngineView at all, or destroy/recreate those, but that'll come with quite some cost.
