### ISSUE TITLE
Debian package depends on OpenGL packages

### ISSUE THREAD

**Issue by NoreSoft** [qutebrowser/qutebrowser#2928]
python3-opengl python3-pyqt5.qtopengl are missing

**Comment by The-Compiler** [comment]
`python3-opengl` is not needed anymore with the git master. `python3-pyqt5.qtopengl` is only needed with QtWebEngine, and already mentioned right below:

> On Debian Stretch or Ubuntu 17.04 or later, it's also recommended to use the
 newer QtWebEngine backend.
> 
> To do so, install `python3-pyqt5.qtwebengine` and `python3-pyqt5.qtopengl`, then
 start qutebrowser with `--backend webengine`.

**Comment by NoreSoft** [comment]
It is needed for the current .deb package

**Comment by The-Compiler** [comment]
Oh, indeed! @fiete201 wouldn't it make more sense to have them as `Suggests:` instead of `Depends:`?

**Comment by fiete201** [comment]
I don't mind whether it is in Depends or Suggests but since there are
other backends than webengine it shoud be Suggests I think. Even If I
only use webengine.
Will be fixed in the next release.

Best regards
Fritz

--

**Comment by The-Compiler** [comment]
There's probably going to be a v0.11.1 release at some point, but with v1.0.0, I'd guess they should indeed be in "Depends:" again, with QtWebEngine being the default backend.

**Comment by mattyw** [comment]
I get the following errors when installing the latest deb https://paste.ubuntu.com/25758235/
```
$ sudo dpkg -i qutebrowser_1.0.2-1_all.deb                                                                                                   
Selecting previously unselected package qutebrowser.
(Reading database ... 1960360 files and directories currently installed.)
Preparing to unpack qutebrowser_1.0.2-1_all.deb ...
Unpacking qutebrowser (1.0.2-1) ...
dpkg: dependency problems prevent configuration of qutebrowser:
 qutebrowser depends on python3-attr; however:
  Package python3-attr is not installed.
 qutebrowser depends on python3-pyqt5; however:
  Package python3-pyqt5 is not installed.
 qutebrowser depends on python3-pyqt5.qtsql; however:
  Package python3-pyqt5.qtsql is not installed.
 qutebrowser depends on python3-pyqt5.qtopengl; however:
  Package python3-pyqt5.qtopengl is not installed.
 qutebrowser depends on python3-pyqt5.qtquick; however:
  Package python3-pyqt5.qtquick is not installed.
 qutebrowser depends on python3-pyqt5.qtwebengine (>= 5.7); however:
  Package python3-pyqt5.qtwebengine is not installed.
 qutebrowser depends on libqt5webenginecore5 (>= 5.7.1); however:
  Package libqt5webenginecore5 is not installed.
 qutebrowser depends on python3-pypeg2; however:
  Package python3-pypeg2 is not installed.
 qutebrowser depends on python3-ruamel.yaml; however:
  Package python3-ruamel.yaml is not installed.
 qutebrowser depends on python3-sip; ho
dpkg: error processing package qutebrowser (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 qutebrowser
```

**Comment by The-Compiler** [comment]
@mattyw Please follow the [install instructions](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#debian-stretch--ubuntu-1704-and-newer) and install the dependencies first.

**Comment by fiete201** [comment]
Or just use apt to install the package since it will resolve the
dependencies for you.

apt install ./qutebrowser_1.0.2-1_all.deb

Best Regards
Fritz

**Comment by The-Compiler** [comment]
This is obsolete with v1.0 now - PyQt5.QtOpenGL is now also always required, even when QtWebEngine is not used.
