### ISSUE TITLE
qutebrowser crashes with gnusocial

### ISSUE THREAD

**Issue by NoreSoft** [qutebrowser/qutebrowser#2931]
Hi,

I'm using the current .deb version of qutebrowser. When I write a queet in gnusocial.de it almost always crashes after some time while in insert mode.

`Thread 1 "python3.5" received signal SIGSEGV, Segmentation fault.
raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.`

gdb tacktrace attached.
[gdb.txt](https://github.com/qutebrowser/qutebrowser/files/1254526/gdb.txt)

**Comment by The-Compiler** [comment]
That's a crash inside QtWebKit, so qutebrowser can't do anything about it - unfortunately, Debian doesn't [package a newer QtWebKit yet](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862452), so your only option is switching to QtWebEngine (see the [install page](https://github.com/qutebrowser/qutebrowser/blob/master/INSTALL.asciidoc#using-the-packages) for details).

If you're on Debian Jessie or Ubuntu 14.04, there isn't an easy way to get QtWebEngine I'm afraid. With Ubuntu 16.04 and 16.10, there's no QtWebEngine in the repos, but you can [install qutebrowser via tox](https://github.com/qutebrowser/qutebrowser/blob/master/INSTALL.asciidoc#tox).
