### ISSUE TITLE
Proxy not working (macOS)

### ISSUE THREAD

**Issue by khinsen** [qutebrowser/qutebrowser#2934]
With `proxy = system` under macOS, qutebrowser does not pick up the system-defined proxy when there is one. It tries direct network access, which because http and https are blocked by the router.

Some more details:
 - macOS 10.12.6
 - two locations, one without a proxy, one with a proxy for http/https/ftp
 - qutebrowser works fine in the "open" location, but fails when a proxy is required
 - I did restart qutebrowser after changing locations.

```
qutebrowser v0.11.0
Git commit: v0.11.0-8-g725d4a4 (2017-07-04 22:16:21 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.0
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
SSL: Secure Transport, macOS Sierra (10.12)

Style: QMacStyle
Platform: Darwin-16.7.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.12.6, x86_64

Paths:
config: /Users/hinsen/Library/Preferences/qutebrowser
data: /Users/hinsen/Library/Application Support/qutebrowser
system_data: /Users/hinsen/Library/Application Support/qutebrowser
cache: /Users/hinsen/Library/Caches/qutebrowser
download: /Users/hinsen/Downloads
runtime: /var/folders/hg/ryp9xp_11fx91lt_xygsyzjc0000gp/T/qutebrowser
```

**Comment by The-Compiler** [comment]
The Qt documentation says:

> On macOS, this function will obtain the proxy settings using the SystemConfiguration framework from Apple. It will apply the FTP, HTTP and HTTPS proxy configurations for queries that contain the protocol tag "ftp", "http" and "https", respectively. If the SOCKS proxy is enabled in that configuration, this function will use the SOCKS server for all queries. If SOCKS isn't enabled, it will use the HTTPS proxy for all TcpSocket and UrlRequest queries.

I'm guessing you configured it that way? What type of proxy is it?

W you run `:debug-console` (hidden) in qutebrowser, and then do this, what do you get?

```python
from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.systemProxyForQuery()[0]; print(p.type(), p.hostName())
```

FWIW, as a workaround you can probably set the proxy directly via `:set network proxy <url>`.

**Comment by khinsen** [comment]
My proxy is https/http/ftp, not SOCKS.

I get `2` for `p.type()` and `''` for `p.hostname()` in the debug console.

When I set proxy explictly to a URL, it works just fine.

**Comment by The-Compiler** [comment]
Okay, so Qt isn't correctly detecting your proxy then - type 2 means "no proxy". From a quick look, this looks like [QTBUG-44774](https://bugreports.qt.io/browse/QTBUG-44774) - nothing qutebrowser can do about that, I'm afraid.
