### ISSUE TITLE
Tab "Suspension"

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#2936]
I think it would be nice to have a feature that suspends inactive tabs, closing the rendering processes that are not being viewed or in a blacklist (like youtube), each tab would be reloaded as soon as it is brought to view.

This would make the browser+rendering processes use a lot less RAM.

Pinned tabs wouldn't be suspended, and it would be possible to have the browser suspend tabs that have been in the background for more than a certain amount of time.

**Comment by The-Compiler** [comment]
Duplicate of #67
