### ISSUE TITLE
Inspector not unbound from tab after closing the inspector

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2938]
When I start qutebrowser with `--enable-webengine-inspector`, the "Inspect Element" button does not appear in the context menu until I actually start the inspector and select the tab to inspect. But when I close the inspector and keep using the tab, the "Inspect Element" button is still there and highlights the element as usual, although the inspector is closed. So the binding between a tab and the inspector is probably not terminated correctly.

**Comment by The-Compiler** [comment]
Nothing qutebrowser can do about that without a better inspector API by QtWebEngine I think.
