### ISSUE TITLE
New features in Qt 5.10

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2939]
Some new Qt 5.10 features related to qutebrowser:

- QtWebEngine
  - [x] [Support for `window.focus()`](https://codereview.qt-project.org/#/c/195023/) (doesn't seem to work)
  - [x] [New HideScrollbars setting](https://codereview.qt-project.org/#/c/200515/) - with that, we should also be able to only inject the stylesheet code when an user stylesheet is actually set. (not going to do this as it also hides scrollbars with multiple scrollable div's)
  - [x] [New `DesktopVideoCapture` and `DesktopAudioVideoCapture` permissions](https://codereview.qt-project.org/#/c/195783/)
    - [x] Though it might be possible to [support it in earlier Qt versions](https://codereview.qt-project.org/#/c/179696/4//ALL,unified) too?
  - Support to pause downloads: #1547 
  - New `QWebEnginePage.download`: #2328
  - [x] [`FocusOnNavigationEnabled` default will change](https://codereview.qt-project.org/#/c/191726/)
  - [x] Also, Qt 5.5 [added a `MouseLock` permission](https://codereview.qt-project.org/#/c/100376/) which I apparently missed. (Split off to #3287)
  - [`QTWEBENGINE_DICTIONARIES_PATH`](https://codereview.qt-project.org/#/c/201422/) (cc @elshize): #3759
- [ ] [New `QProcess::startDetached`](http://blog.qt.io/blog/2017/08/25/a-new-qprocessstartdetached/)
- [x] Check whether Wayland support works better (#2932)
-  HTTP/2 might be stable enough to turn on for QtWebKit: #2657
- [x] [Nouveau should be automatically blacklisted now](https://codereview.qt-project.org/#/c/208664/)

**Comment by laurynas-karvelis** [comment]
I'd say keep the browser simple and less intrusive for people. If I want to use spyware, I just open Chromium. On the other hand, qutebrowser is like first love, it always stays pure and untouched. My two cents are to add config settings to optionally enable such features as DesktopVideo(Audio)Capture/MouseLock etc as enable-able only.

KISS & Suckless! Look at dwm, it's a gem. Right now, qutebrowser is like that.

**Comment by The-Compiler** [comment]
Like the other permissions already, those will probably have a setting you can set to true/false/ask, with the default being ask.

**Comment by rnhmjoj** [comment]
So, about the spell check dictionaries... I have some free time and I'm willing to do it.
How would you keep compatibility with older Qt version? Use `XDG_DATA_HOME` if Qt is 5.10 and fallback to the system path otherwise?

Another issue I have found: the script calls imports `browser.webengine.spell` and then calls `qutebrowser.utils.standarddir` which not initialized, so I had to "manually" read the environment to get the path.

**Comment by The-Compiler** [comment]
I opened #3759 for `QTWEBENGINE_DICTIONARIES_PATH` - let's continue this there :wink:

**Comment by The-Compiler** [comment]
Tried `window.focus()` support, but it doesn't seem to work properly:

```diff
diff --git a/doc/help/settings.asciidoc b/doc/help/settings.asciidoc
index 3479f7301..7feb70426 100644
--- a/doc/help/settings.asciidoc
+++ b/doc/help/settings.asciidoc
@@ -133,6 +133,7 @@
 |<<content.javascript.alert,content.javascript.alert>>|Show javascript alerts.
 |<<content.javascript.can_access_clipboard,content.javascript.can_access_clipboard>>|Allow JavaScript to read from or write to the clipboard.
 |<<content.javascript.can_close_tabs,content.javascript.can_close_tabs>>|Allow JavaScript to close tabs.
+|<<content.javascript.can_focus_window,content.javascript.can_focus_window>>|Allow JavaScript to focus the window.
 |<<content.javascript.can_open_tabs_automatically,content.javascript.can_open_tabs_automatically>>|Allow JavaScript to open new tabs without user interaction.
 |<<content.javascript.enabled,content.javascript.enabled>>|Enable JavaScript.
 |<<content.javascript.log,content.javascript.log>>|Log levels to use for JavaScript console logging messages.
@@ -1745,6 +1746,18 @@ Default: +pass:[false]+
 
 This setting is only available with the QtWebKit backend.
 
+[[content.javascript.can_focus_window]]
+=== content.javascript.can_focus_window
+Allow JavaScript to focus the window.
+
+Type: <<types,Bool>>
+
+Default: +pass:[false]+
+
+On QtWebEngine, this setting requires Qt 5.10 or newer.
+
+On QtWebKit, this setting is unavailable.
+
 [[content.javascript.can_open_tabs_automatically]]
 === content.javascript.can_open_tabs_automatically
 Allow JavaScript to open new tabs without user interaction.
diff --git a/qutebrowser/browser/webengine/webenginesettings.py b/qutebrowser/browser/webengine/webenginesettings.py
index 2c44684e8..bd93ea50d 100644
--- a/qutebrowser/browser/webengine/webenginesettings.py
+++ b/qutebrowser/browser/webengine/webenginesettings.py
@@ -163,6 +163,9 @@ class WebEngineSettings(websettings.AbstractSettings):
             # Qt 5.8
             'content.print_element_backgrounds':
                 ('PrintElementBackgrounds', None),
+            # Qt 5.10
+            'content.javascript.can_focus_window':
+                ('AllowWindowActivationFromJavaScript', None),
             # Qt 5.11
             'content.autoplay':
                 ('PlaybackRequiresUserGesture', lambda val: not val),
diff --git a/qutebrowser/config/configdata.yml b/qutebrowser/config/configdata.yml
index a137489fd..0a23e7015 100644
--- a/qutebrowser/config/configdata.yml
+++ b/qutebrowser/config/configdata.yml
@@ -511,6 +511,14 @@ content.javascript.can_close_tabs:
   supports_pattern: true
   desc: Allow JavaScript to close tabs.
 
+content.javascript.can_focus_window:
+  default: false
+  type: Bool
+  backend:
+    QtWebKit: false
+    QtWebEngine: Qt 5.10
+  desc: Allow JavaScript to focus the window.
+
 content.javascript.can_open_tabs_automatically:
   default: false
   type: Bool
```

dropping it for now, which means everything here is either done or split into another issue.
