### ISSUE TITLE
WebEngine does not highlight visited redirecting links

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#2941]
To reproduce, start qutebrowser with `--backend webengine --temp-basedir` and:

1. go to https://www.archlinux.org/
2. follow the link to "Installation Guide" in the right column and go back, the link will be gray instead of blue
3. follow the link to "Mailing Lists" just below the previous link, it will stay blue when you go back

Using Qt 5.9.1 on Arch. I'm pretty sure it used to work before...

**Comment by jgkamat** [comment]
I can reproduce on qt5.7.1 webengine, FWIW, so I don't think it's related to a newer qt.

**Comment by The-Compiler** [comment]
Might be something in the completion changes causing that, because there the history code was also rewritten. cc @rcorre

**Comment by lahwaacz** [comment]
It also works with webkit, so either something changed in qutebrowser or I just never noticed it since I switched to webengine :disappointed:

**Comment by lahwaacz** [comment]
Hmm, with webengine it doesn't work even on v0.10.1, v0.9.1 and v0.8.4, so it probably never worked.

**Comment by jgkamat** [comment]
I don't think this is related to the new history completion, I'm able to reproduce on qb `v0.9.0` (webengine) as well. :cry:

**Comment by The-Compiler** [comment]
Might be related to #2835 too.

**Comment by lahwaacz** [comment]
No, if I look into the `history.sql` file, both webkit and webengine add the redirecting URL (`https://mailman.archlinux.org/mailman/listinfo/`) into the History table.

**Comment by The-Compiler** [comment]
This looks like a QtWebEngine bug, as qutebrowser actually doesn't do anything about visited links on QtWebEngine. I opened [QTBUG-63579](https://bugreports.qt.io/browse/QTBUG-63579).

**Comment by The-Compiler** [comment]
Looks like there's a fix upstream being reviewed: https://codereview.qt-project.org/#/c/208201/
