### ISSUE TITLE
Show a visual notification when following a hint

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2943]
E.g. with Pentadactyl the hint label would flash Yellow+Green for a second before following.

Also maybe show a visual notification when no hint is followed as a result of entering a keystring which filters all the hints out.

**Comment by lahwaacz** [comment]
Why wait for a whole _second_ when the page might load up in just a couple of milliseconds?

**Comment by pkillnine** [comment]
well it doesn't have to wait

**Comment by The-Compiler** [comment]
Duplicate of #2836

**Comment by mschilli87** [comment]
From what I understood #2836 suggested flashing upon *yanking a hint URL* while this suggest flashing upon *following a hint*.

**Comment by The-Compiler** [comment]
Hmm, right - still makes sense to track them in one issue, since they're very similar. I'll add a comment there.
