### ISSUE TITLE
Playing IMDb videos on Gentoo with webengine

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#2944]
I've installed the live build of Qutebrowser on Gentoo following the recommendations at https://www.qutebrowser.org/INSTALL.html#_on_gentoo (I've installed the gst-plugins).

So far everything works well using webengine, including HTML5 content (Youtube, etc.) except IMDb videos which suggest installing Adobe Flash.

Any clue what I'm missing?

A more general question as I don't know much in that area: is there a way to get info on the required video codecs so that to infer the missing dependency?

**Comment by pkillnine** [comment]
have you installed flash/pepperflash? and have you enabled plugins (`:set content allow-plugins true`)?

**Comment by Ambrevar** [comment]
IMDb videos support HTML5, it works without Flash.  I don't have Flash on my Arch Linux and it works perfectly.

**Comment by pkillnine** [comment]
can you provide a link to the videos that don't work?

**Comment by Ambrevar** [comment]
Well, any, frankly.
From the main page:

http://www.imdb.com/list/ls053181649/videoplayer/vi1159706905?ref_=hm_hp_i_3

**Comment by jgkamat** [comment]
@Ambrevar, can you try enabling proprietary codecs on [qtwebengine](https://packages.gentoo.org/packages/dev-qt/qtwebengine) through the `bindist` flag? I forget whether turning it off or on enables proprietary codecs. It's possible imdb needs H264, which is nonfree in chromium as far as I know.

**Comment by Ambrevar** [comment]
Sounds like a good guess.  As of now, `bindist` is on by me and it does not work.  I could try disabling it.
By the way, `qtwebengine` is the one and only package that takes _hours_ to compile each time.  Is there any way to make this faster on Gentoo, like keeping the build files for one specific package (a bit like the kernel sources)?

**Comment by jgkamat** [comment]
qtwebengine bundles chromium, and chromium takes forever to compile unfortunately :(. 

The only thing I know about is [enabling ccache in portage](https://wiki.gentoo.org/wiki/Handbook:X86/Working/Features#Activating_Portage_ccache_support). I'm not sure if portage supports keeping old build files, but that would help a lot for qtwebengine and other large packages.

**Comment by Ambrevar** [comment]
I did a bit of research.  [Arch Linux' PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-webengine) shows that
`WEBENGINE_CONFIG+="use_proprietary_codecs"` is used.

Now [Gentoo's ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-qt/qtwebengine/qtwebengine-5.7.1-r2.ebuild?id=36332d7cdba4b89dbee52213b76762f42dfa5506) has that line:

	$(usex bindist '' 'WEBENGINE_CONFIG+=use_proprietary_codecs')

So I guess you are right.  I'll rebuild just now.

**Comment by Ambrevar** [comment]
[Hours of emerging later]: Big success!

I've added some comment about it on [Gentoo wiki](https://wiki.gentoo.org/wiki/Qutebrowser#USE_flags).

@The-Compiler: I know it's not your job to document the packaging details of all distros out there, so I'm just pinging you in case you'd find it necessary to mention that very detail on https://www.qutebrowser.org/INSTALL.html#_on_gentoo.

Either way, problem solved!

**Comment by The-Compiler** [comment]
Thanks for trying! I [added a note](https://github.com/qutebrowser/qutebrowser/commit/2598fd8c5d981e3cb0fa771989d89ca2dd288861) since this isn't the first time this came up - but I did read that line wrong and usually told people to turn on `bindist` rather than off :blush: I also linked to the Gentoo wiki - can you take a quick look and let me know if there's anything wrong with what I said there? :wink:

**Comment by Ambrevar** [comment]
All good, thanks!
