### ISSUE TITLE
keys.conf mapping should be reversed

### ISSUE THREAD

**Issue by AndrewBelt** [qutebrowser/qutebrowser#2945]
Not sure if this has been discussed before, but in my opinion the key map should be reversed. Currently, assigning a key command is done with

	scroll down
	    j

Instead, it should be done with

	j
	    scroll down

This prevents accidental duplicate key command errors. "If X is pressed, Y should run" is more intuitive than "To do Y, you should press X" in the context of the key mapping file.

**Comment by lahwaacz** [comment]
It's already being worked on, though in a different way - see #499.

**Comment by AndrewBelt** [comment]
Oh yes, thank you. Looking forward to new-config
