### ISSUE TITLE
keys.conf should not be regenerated when qutebrowser is launched

### ISSUE THREAD

**Issue by AndrewBelt** [qutebrowser/qutebrowser#2946]
Currently, qutebrowser creates missing entries in `keys.conf` instead of leaving them unassigned.

Suppose I don't care about feature Y because I'll never use it, which is mapped by default to key X. If I remove it to avoid the 500ms delay when attempting to press a shorter key command (e.g. hit 't' and other options will appear for 500ms before 't' is actually triggered) or to avoid the risk of accidentally pressing a key and triggering it, it returns back in the config file when I reopen it.

This is very frustrating, as I'm trying to start from scratch with a new key mapping, but the software is destroying my work with the keys.conf file by adding garbage I don't need and creating duplicates.

**Comment by lahwaacz** [comment]
I don't know the details, but I'm sure the new config system will help to solve this - see #499.

**Comment by AndrewBelt** [comment]
Yes, you are correct, it looks like this will be resolved then.

**Comment by The-Compiler** [comment]
FWIW with the current config, it's probably easier to just use the `:bind` and `:unbind` commands. If you edit the config by hand, you'll need to bind them to a special `<unbind>` command.
