### ISSUE TITLE
When viewing source, status bar displays "Invalid URL!"

### ISSUE THREAD

**Issue by ersi-dnd** [qutebrowser/qutebrowser#2948]
When opening the source of a webpage, the status bar screams Invalid URL! where there should be the current URL. The status bar should show the address normally, I think.

qutebrowser v0.11.0
Git commit: v0.11.0-393-g173688c74 (2017-08-14 22:11:12 +0200)
Backend: QtWebKit-NG (WebKit 602.1)

**Comment by jgkamat** [comment]
Maybe it should display `source:webpagename`

For me (webengine) it displays `about:blank`. 

This might be related to https://github.com/qutebrowser/qutebrowser/issues/2395

**Comment by The-Compiler** [comment]
Also see #2595.
