### ISSUE TITLE
Introduce utils functions for OS/platform checks

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2961]
I'm kind of tired juggling around with `sys.platform == 'linux'`, `os.name == 'nt'` and `sys.platform == 'darwin'`. Instead, we should just have `utils.is_linux`, `utils.is_windows` and `utils.is_mac`.

**Comment by kalbhor** [comment]
Hey, if this issue hasn't been resolved, I'd be willing to help!

**Comment by kalbhor** [comment]
I implemented a solution for this in the ```utils.py``` file.

**Comment by Elronnd** [comment]
Issue should be closed.
