### ISSUE TITLE
Setting editor doesn't work properly with new config

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2962]
After `:set editor.command '["gvim", "-f", "{}"]'`, `["[gvim,", "-f,", "{}]"]` is shown as set value, which obviously doesn't work.

Log:

```
13:22:42 DEBUG    commands   command:run:500 command called: set ['editor.command', '["gvim", "-f", "{}"]']
13:22:42 DEBUG    commands   command:run:515 Calling qutebrowser.config.config.ConfigCommands.set(<qutebrowser.config.config.ConfigCommands object at 0x7f04bc081c88>, 0, 'editor.command', '["gvim", "-f", "{}"]', temp=False, print_=False)
13:22:42 DEBUG    config     config:_set_value:398 Config option changed: editor.command = ['[gvim,', '-f,', '{}]']
```

**Comment by NoctuaNivalis** [comment]
I recall encountering this when I tried out the branch before summer. The correct method was IIRC `:set editor.command ["st", "-e", "nvim", "'{}'"]`, resulting in this config part:

```
  editor.command:
  - st
  - -e
  - nvim
  - '{}'
```

**Comment by pylipp** [comment]
`:set editor.command ["st", "-e", "vim", "'{}'"]` did not work for me, I had to do `:set editor.command '["st", "-e", "vim", "'{}'"]'`.

I'm on master.
