### ISSUE TITLE
THE Best browser on the Planet!

### ISSUE THREAD

**Issue by laurynas-karvelis** [qutebrowser/qutebrowser#2968]
Just wanted to thank you for your hard work, all of you! This browser changed my web experience completely. It figuratively blew my socks off! (https://i.imgur.com/TX01AOS.gif)

I bound to you all! Keep up the amazing work! You are deeply respected!

Just donated too!

**Comment by The-Compiler** [comment]
Thank you! 😊 👍 

Reminds me that I probably have some new [Colin Furze](https://www.youtube.com/user/colinfurze) videos I wanted to watch, and instead I'm hacking on the new config system for qutebrowser 😆
