### ISSUE TITLE
New config: Allow initializing objects / importing in config.py

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2969]
To make things like flake8 in editors happy, it'd be nice if one could recreate the config objects, something like:

```python
import configapi
c = configapi.container
config = configapi.config
```

or (involving more real qutebrowser code)

```python
from qutebrowser.config import config as confmod
config = ConfigAPI(confmod.instance, confmod.key_instance)
c = confmod.ConfigContainer(confmod.instance, configapi=config)
```

In a similar vein, importing from `~/.config/qutebrowser` should maybe be possible.

**Comment by jgkamat** [comment]
Perhaps a better way to do this would be to place:

```
from qutebrowser.config.configfiles import ConfigAPI  # noqa: F401
from qutebrowser.config.config import ConfigContainer # noqa: F401
config = config # type: ConfigAPI # noqa: F821
c = c # type: ConfigContainer # noqa: F821
```

into the default config.py. This seems to not produce any errors via flake8 and work for code completion (the completion on `c` seems a little broken, but that's because the ConfigContainer type is weird.

**Comment by The-Compiler** [comment]
FWIW I'd rather not place that in the default `config.py` as it might be rather confusing to people not used to Python, who also typically don't have a flake8/pylint set up in their editor.

However, it makes total sense to document that snippet in the documentation. I just need to think about it some more first, as I'm not sure importing things from `qutebrowser.*` works in all scenarios (e.g. with the frozen applications on macOS/Windows).
