### ISSUE TITLE
New config: Setting fonts.monospace does nothing

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2973]
Setting `fonts.monospace` doesn't change any fonts with the new config, not even after `:restart`.

**Comment by brianbuccola** [comment]
I noticed this when I switched to the new config yesterday. Ended up just doing this, which works:

```python
# Fonts
c.fonts.monospace = "Fira Mono"
c.fonts.completion.entry = "10pt Fira Mono"
c.fonts.completion.category = "bold 10pt Fira Mono"
c.fonts.debug_console = "10pt Fira Mono"
c.fonts.downloads = "10pt Fira Mono"
c.fonts.hints = "bold 13px Fira Mono"
c.fonts.keyhint = "10pt Fira Mono"
c.fonts.messages.error = "10pt Fira Mono"
c.fonts.messages.info = "10pt Fira Mono"
c.fonts.messages.warning = "10pt Fira Mono"
c.fonts.prompts = "10pt Fira Sans"
c.fonts.statusbar = "10pt Fira Mono"
c.fonts.tabs = "10pt Fira Mono"
c.fonts.web.family.fixed = "Fira Mono"
c.fonts.web.family.sans_serif = "Fira Sans"
c.fonts.web.family.serif = "DejaVu Serif"
```

In my case, I also wanted to increase all the default 8pt sizes to 10pt, so for this I need to explicitly set these anyway -- unless there's a better way that I don't know about.

Actually, maybe it would be convenient to have a setting like `fonts.browser.size.default`, set to 8pt default, which can be easily switched to 10pt, which would automatically change all the qutebrowser-specific font sizes like for completions, downloads, messages, status bar, etc.

**Comment by DarkDefender** [comment]
I would also like to add that after the new config changes, I can not change any font besides "fonts.tabs". It doesn't matter what I write in the others. It always falls back to the default font.

I find it really wierd that I can change fonts for the tabs but everything else seems broken.

**Comment by The-Compiler** [comment]
@DarkDefender Works fine here. What do you set them to?

**Comment by brianbuccola** [comment]
Just a guess, but if you reference a variable, then order matters. For example...

```python
c.fonts.statusbar = c.fonts.monospace
c.fonts.monospace = "Fira Mono"
c.fonts.tabs = c.fonts.monospace
```

...in this case, `fonts.tabs` will be set to Fira Mono, but `fonts.statusbar` won't be. Actually, I think qutebrowser will throw an error since it can't assign `fonts.statusbar` to anything, so if you're not getting an error on opening qutebrowser, then this isn't your issue.

Maybe best to just post the relevant part of your config.

**Comment by DarkDefender** [comment]
@The-Compiler Here is an example:

This work for `fonts.tabs`:
```
:set fonts.tabs "lucy tewi" (bitmap font)
:set fonts.tabs Impact Condensed
:set fonts.tabs IPAMonaGothic
```
However, it seems that for everything else than fonts.tabs it will never change the font.
So this does not work:

```
:set fonts.statusbar "lucy tewi"
:set fonts.statusbar Impact Condensed
:set fonts.tabs IPAMonaGothic
```
However I can change font size by just specifying the size like `20pt`. So I know that at least the setting is read.

The fonts I have chosen are just some of what I have installed. I have tried multiple bitmap fonts and true type font. None of them seem to work besides in `font.tabs`.

**Comment by DarkDefender** [comment]
I've also tried with `--temp-basedir` and I still have the same issue. So I think that we can rule out something wierd happening with non standard configuration options.

Here is a gist of the qutebrowser report log: https://gist.github.com/DarkDefender/0596c0552f3e182a7869e1db30c0ffe6

**Comment by The-Compiler** [comment]
You'll need to specify a size and a family, e.g. `"20pt IPAMonaGothic"`.

**Comment by DarkDefender** [comment]
@The-Compiler ok, that works. Why didn't I have to do that for `fonts.tabs` though? It is a bit confusing when it works for one setting but not the others...

**Comment by The-Compiler** [comment]
Because it's treated differently internally, i.e. it's an accident that it works. qutebrowser used to be stricter about validating font values in the config, but unfortunately that meant there were valid values which weren't accepted by it.

**Comment by The-Compiler** [comment]
@DarkDefender See https://github.com/qutebrowser/qutebrowser/issues/115#issuecomment-335906133 for better font validation, but it's a bit more complicated than I thought it'd be, so I'm postponing it :wink:
