### ISSUE TITLE
New config: Order of config.py/autoconfig.yml

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2975]
As discussed with some people in the IRC channel, `autoconfig.yml` being loaded after `config.py` seems wrong - `config.py` should take precedence over `autoconfig.yml`.

When changing the order, however, doing `config.load_autoconfig = False` won't work anymore. The best way brought up to handle this is checking for a file like `~/.config/qutebrowser/no-autoconfig`.

**Comment by NoctuaNivalis** [comment]
I'd stick to loading `config.py` first, and only set missing values from `autoconfig.yml`? Unless `config.load_autoconfig = False`, of course.

**Comment by jgkamat** [comment]
The reason why `config.py` should be loaded after the autoconfig is because it makes building upon the autoconfig possible. For example, I put my DEFAULT searchengine in my autoconfig.yml, since I want to keep things simple.

However, later on, I might want to programatically add a bunch of searchengines, so I add code for that in config.py. Since the code in config.py does not touch the default searchengine, I only need to worry about adding my additions, I don't need to worry about porting my config from autoconfig to config.py. 

I really like this workflow, and I think that most people would natrually use it this way too.

**Comment by The-Compiler** [comment]
A different approach I'd like some feedback on:

- Make `config.load_autoconfig()` a function which loads the autoconfig (at whatever point it's called)
- If no `config.py` exists, the autoconfig is loaded automatically by qutebrowser.
- Otherwise, it's not loaded, and the `config.py` has to take care of it.
- If we create an example `config.py`, it contains a call to `config.load_autoconfig()` (uncommented)

That way, in `config.py` you can decide what takes precedence. It's a behavior change for people who already wrote a `config.py` and didn't set `config.load_autoconfig = False`, but that's probably a few, and people using the git repo are guinea pigs anyways :wink:

**Comment by NoctuaNivalis** [comment]
I'd prefer not this, but something quite similar. The default/example `config.py` should contain:

```python
config.load_yamlconfig("autoconfig.yml")
config.browserconfig_savefile = "autoconfig.yml"
```

- You can load multiple yaml files, no matter what they're called
- You can chose not to provide a savefile, so in-browser settings become temporary

**Comment by The-Compiler** [comment]
Let's continue bikeshedding while we're at it 😆 What about:

```python
config.load_yaml(name="autoconfig.yml", save=True)
```

with those being the default arguments?

(probably with the caveat that `save=True` can only be given once?)

**Comment by cryzed** [comment]
@The-Compiler what you suggested [here](https://github.com/qutebrowser/qutebrowser/issues/2975#issuecomment-331082743) sounds great. [This](https://github.com/qutebrowser/qutebrowser/issues/2975#issuecomment-331092094) does too, although I kind of feel that the "save-parameter" behavior is a bit wonky... maybe there's no better way to decide where to write configuration changes back to.

**Comment by The-Compiler** [comment]
As per Kenneth Reitz' ["Listen to everyone, then disregard it."](https://www.kennethreitz.org/values/) (I really want that page as a poster!), I decided to go the simpler route and simply provide `config.load_autoconfig()` for now.

As for loading YAML data, I'd rather add that as a "recipe" as per #3009. Then users can structure their config in their YAML file like they want, and I can do with the `autoconfig.yml` format whatever I want.
