### ISSUE TITLE
New config regression when bind changes from normal into command mode

### ISSUE THREAD

**Issue by helbling** [qutebrowser/qutebrowser#2989]
I have a binding which changes into command mode by using set-cmd-text. The following commands are run in command mode to position the cursor.

old keys.conf worked:
```
set-cmd-text :open {url:pretty} ;; rl-beginning-of-line ;; rl-forward-word ;; rl-forward-word ;; rl-forward-word ;; rl-forward-word ;; rl-forward-char
    go

```
new config.py:
```
config.unbind('go',  mode='normal');
config.bind('go', 'set-cmd-text :open {url:pretty} ;; rl-beginning-of-line ;; rl-forward-word ;; rl-forward-word ;; rl-forward-word ;; rl-forward-word ;; rl-forward-char',  mode='normal')

```
gives the following error:

> 23:26:37 ERROR: Error while loading config.py
> Traceback (most recent call last):
>   File "/home/helbling/projects/qutebrowser/qutebrowser/config/config.py", line 670, in early_init
>     raise configexc.ConfigFileErrors('config.py', config_api.errors)
> qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
>   While binding 'go': rl-beginning-of-line: This command is only allowed in command/prompt mode, not normal.
> 

The check does not recognize the mode change in the first command.

For my use case, support for something like
`set-cmd-text :open {url:pretty}<home><ctrl-right><ctrl-rlght><ctrl-right><ctrl-right><right>
`would work as well.

qutebrowser v0.11.0
Git commit: v0.11.0-861-g43ff79be0 (2017-09-18 23:07:58 +0200)

**Comment by The-Compiler** [comment]
Fixed by 64b783d9c056045bcb5caa3d9ab8543b54fc4e18 (forgot to reference the issue in the commit).
