### ISSUE TITLE
load_autoconfig still saves autoconfig

### ISSUE THREAD

**Issue by NoctuaNivalis** [qutebrowser/qutebrowser#2993]
The documentation on `qute://help/configuring.html` claims the in-browser configuration will be temporary because `autoconfig.yml` isn't loaded. That's true, but the in-browser configuration is still saved, so when you turn `load_autoconfig` on again, all these "temporary" settings will be used.

Either the documentation should be less misleading, or we shouldn't save the in-browser configuration.

I was looking into the second part while writing #2992 but it seems non-trivial: the `load_autoconfig` value seems only available during startup?

**Comment by The-Compiler** [comment]
The documenation should be updated - I think it's good to save them either way, then you can still change your mind on loading them.
