### ISSUE TITLE
<ctrl-j> binding has no effect on master

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#2995]
On current master, `:bind --force <ctrl-j> scroll down`  does not result in `ctrl-j` scrolling down.

`:bind <ctrl-j>` prints the binding, and `:bind --force <ctrl-k> scroll up` works fine. I can reproduce this in a temp basedir as well.

```
qutebrowser v0.11.0
Git commit: v0.11.0-881-g3f6ff1622-dirty (2017-09-19 14:14:31 -0400)
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.9.0-3-amd64-x86_64-with-debian-9.1, 64bit
Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
Frozen: False
Imported from /home/jay/Code/qutebrowser/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/jay/.cache/qutebrowser
config: /home/jay/.config/qutebrowser
data: /home/jay/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
```

I might take a look at this tomorrow, but I'm not sure where to start looking :P

**Comment by jgkamat** [comment]
This is caused because `<ctrl-j>` is *mapped* to `<return>` by default. 
Clear the entries in `bindings.key_mappings` to have `<ctrl-j>` disconnected from `<return>`

**Comment by The-Compiler** [comment]
Like Parapets mentioned in IRC, maybe it'd make sense if bindings did override mappings?

**Comment by jgkamat** [comment]
I think that bindings overriding mappings would make mappings more confusing, so I don't think its a good idea.

How about a error message when trying to bind a mapped key, instead?

Ie: `<Ctrl-R>` is mapped, please unmap before binding

**Comment by The-Compiler** [comment]
I'm not sure if it'd would be any more confusing - I think it's less likely for people to customize mappings than bindings, and I think it's easier to explain that bindings "win".
