### ISSUE TITLE
SQL insertions when disk is full

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3004]
When e.g. the disk is full, qutebrowser currently crashes - this error should probably be shown somewhere instead of being an exception.

```
21:33:30 DEBUG    sql        sql:__init__:80 Preparing SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
21:33:30 DEBUG    sql        sql:run:99 Running SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
21:33:30 DEBUG    sql        sql:run:102 query bindings: {':atime': 1501446810, ':redirect': False, ':title': 'Profile-sync-daemon - ArchWiki', ':url': 'https://wiki.archlinux.org/index.php/Profile-sync-daemon#Setup_and_installation'}
21:33:30 ERROR    misc       crashsignal:exception_hook:210 Uncaught exception
Traceback (most recent call last):
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/browser/history.py", line 144, in add_from_tab
    self.add_url(url, title)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/browser/history.py", line 166, in add_url
    'redirect': redirect})
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/misc/sql.py", line 214, in insert
    q.run(**values)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/misc/sql.py", line 105, in run
    self.lastQuery(), self.lastError().text()))
qutebrowser.misc.sql.SqlException: Failed to exec query "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)": "database or disk is full Unable to fetch row"
```

- https://crashes.qutebrowser.org/view/d3f95349
- https://crashes.qutebrowser.org/view/4928d796
- https://crashes.qutebrowser.org/view/933b546d
- https://crashes.qutebrowser.org/view/3f44212a

Similarily:

 ```
21:35:53 DEBUG    sql        sql:__init__:80 Preparing SQL query: "CREATE TABLE IF NOT EXISTS History (url , title , atime , redirect )"
21:35:53 DEBUG    sql        sql:run:99 Running SQL query: "CREATE TABLE IF NOT EXISTS History (url , title , atime , redirect )"
21:35:53 DEBUG    sql        sql:run:102 query bindings: {}
21:35:53 ERROR    misc       crashsignal:exception_hook:210 Uncaught exception
Traceback (most recent call last):
  File "/home/miles/path/qutebrowser-custom", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/qutebrowser.py", line 177, in main
    return app.run(args)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/app.py", line 113, in run
    init(args, crash_handler)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/app.py", line 139, in init
    _init_modules(args, crash_handler)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/app.py", line 437, in _init_modules
    history.init(qApp)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/browser/history.py", line 292, in init
    history = WebHistory(parent=parent)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/browser/history.py", line 49, in __init__
    parent=parent)
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/misc/sql.py", line 147, in __init__
    q.run()
  File "/home/miles/packages/repos/qutebrowser-custom/qutebrowser/misc/sql.py", line 105, in run
    self.lastQuery(), self.lastError().text()))
qutebrowser.misc.sql.SqlException: Failed to exec query "CREATE TABLE IF NOT EXISTS History (url , title , atime , redirect )": "database or disk is full Unable to fetch row"
```

- https://crashes.qutebrowser.org/view/8d07a8da

cc @rcorre @pkillnine

**Comment by rcorre** [comment]
Are you suggesting to show an error and keep running? Or a crashdialog?
I assume you're talking about SQL errors in general, and not just full-disk, correct? I don't think we can tell without scraping the string.

**Comment by The-Compiler** [comment]
The problem is that SQL errors can either mean a bug in qutebrowser, or something wrong on the user's machine. Ideally, users would get a crash dialog in the first case, and some kind of error message (maybe just a statusbar error via `message.error()` in the latter case. So I think we should only catch some types of errors - probably "database or disk is full" and maybe "database is locked" from #2930.

> I don't think we can tell without scraping the string.

Looks like there's [QSqlError::nativeErrorCode()](http://doc.qt.io/qt-5/qsqlerror.html#nativeErrorCode) which returns `'13'` (as a string) in this case, and looking at the [sqlite docs](https://sqlite.org/rescode.html#full) that seems to match up with `SQLITE_FULL`.

**Comment by The-Compiler** [comment]
By the way, a good way to reproduce this:

```
$ sudo mount -t tmpfs -o size=80K tmpfs ~/tmpfs
$ python3 -m qutebrowser --basedir ~/tmpfs
```

Might need to experiment with the size a bit - my qutebrowser used 88KB after a fresh start, so 80KB triggered the error for me.

**Comment by The-Compiler** [comment]
Another one we might to handle the same way: "attempt to write a readonly database"

- https://crashes.qutebrowser.org/view/296a589e
- https://crashes.qutebrowser.org/view/8d42e3a1

Makes me wonder whether we should just handle all `TransactionError` types (see [ErrorType](http://doc.qt.io/qt-5/qsqlerror.html#ErrorType-enum)) as error message, but I wonder what's in ther exactly...

**Comment by The-Compiler** [comment]
I refactored the error handling in 5af8a95c829e7a39a87da420e03526fcc15a7cf3 a bit so it logs more details about errors.
