### ISSUE TITLE
Completions cause video stutter

### ISSUE THREAD

**Issue by dgunawar** [qutebrowser/qutebrowser#3008]
```
qutebrowser v0.11.0
Git commit: v0.11.0-864-ge9b8288e4 (2017-09-19 07:08:56 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)
```

Video stutters when completions are happening, didn't notice this before the latest update. Distro is Arch Linux, package is `qutebrowser-git`.

**Comment by jgkamat** [comment]
I would take a look at https://github.com/qutebrowser/qutebrowser/issues/2812. (try making `completion.height` smaller at first), which helped a lot with performance for me.

**Comment by The-Compiler** [comment]
It's probably also because there's just more things to filter for the completion - closing this, as it's not really actionable.
