### ISSUE TITLE
Support TLS client certificates

### ISSUE THREAD

**Issue by duckdalbe** [qutebrowser/qutebrowser#3011]
Some websites require a client-certificate. It would be awesome if qutebrowser could support that. Currently I'm seeing ERR_BAD_SSL_CLIENT_AUTH_CERT with such services.

Most other browsers have a list of certs and by default ask which one should be used, that would work for qutebrowser too, I imagine. Or users could specify a mapping from domains to certificates in the config.

**Comment by The-Compiler** [comment]
See [QTBUG-54877](https://bugreports.qt.io/browse/QTBUG-54877) - apparently they're still looking for someone checking whether the [linked patch](https://codereview.qt-project.org/#/c/198354/) works, especially on macOS and Windows.

**Comment by duckdalbe** [comment]
Thanks for the pointer!

**Comment by The-Compiler** [comment]
Looks like client certificate support [landed](https://codereview.qt-project.org/#/c/198354/) in Qt 5.12, to be [released](https://wiki.qt.io/Qt_5.12_Release) in late November - so there are chances support will be added to qutebrowser somewhen later this year :wink:

**Comment by dg10a** [comment]
It looks like support is available in Qt now. What are the next steps for getting this into qutebrowser?

**Comment by The-Compiler** [comment]
@dg10a Waiting until PyQt (Python wrappers) also are released for Qt 5.12 (apparently in January), and then actually implementing support for it - see #3992.

**Comment by The-Compiler** [comment]
qutebrowser v1.6.0 will come with basic support for client certificates on Qt 5.12 - however, selecting the certificate to send when there are multiple matches isn't implemented yet (see #4587).
