### ISSUE TITLE
Bitmap fonts don't render in web pages, replaced with the default sans-serif font

### ISSUE THREAD

**Issue by benbenolson** [qutebrowser/qutebrowser#3013]
```
qutebrowser v0.11.0
Git commit: v0.11.0-925-gcb57525f6-dirty (2017-09-21 13:43:30 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)
```

I can set `fonts.tabs` to something like `14pt Monospace`, and it'll use the correct bitmap font that I've specified with `fontconfig`. But if I put that same value in `fonts.web.family.fixed`, it ignores it and uses the default sans-serif font instead of the bitmap one. `14pt` is definitely a size that is available in the bitmap font, as it works in other applications (such as `st`), and it says so on their website (the font is GohuFont).

I'm new to `qutebrowser`, so this might just be a configuration issue, but I'm not sure what I'm missing here.

**Comment by The-Compiler** [comment]
The `fonts.web.family.*` settings are a family, without any size - so you'll need to set it to just `Monospace`.

**Comment by benbenolson** [comment]
Oh, right, sorry: I meant that I'm setting `fonts.web.family.fixed` (and all of the other similar settings) to `Monospace`, not `14pt Monospace`. Same issue occurs.

**Comment by The-Compiler** [comment]
All qutebrowser does here is passing the setting [to Qt](http://doc.qt.io/qt-5/qwebenginesettings.html#setFontFamily) (which I think, in turn, just passes it to Chromium) - so unfortunately there really isn't much I can do here if bitmap fonts don't work. You might have more luck with setting `content.user_stylesheets` to a stylesheet which overrides the page's fonts in CSS maybe.

**Comment by benbenolson** [comment]
All right, let me try that out in about an hour. Thanks!

**Comment by benbenolson** [comment]
Yeah, I've made a new stylesheet, and it does globally change the font, but whenever I sent any fonts to a bitmap one, it simply changes it back to my default `sans-serif` font instead.

**Comment by l29ah** [comment]
@benbenolson could you make the bitmap fonts work?
