### ISSUE TITLE
Out Of Memory Error with JS on Bukkit.org

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#3018]
I was reading lazily on a forum page (precisely Bukkit.org) while coding on another PC, all of a sudden I found myself with QuteBrowser closed, crashed, due to what seems to be a process Out Of Memory exception.

For some reason I can't reproduce the issue right now in debug mode, but I'll keep trying.

I attach what I have so far.
[crash.zip](https://github.com/qutebrowser/qutebrowser/files/1325227/crash.zip)
[version.zip](https://github.com/qutebrowser/qutebrowser/files/1325233/version.zip)

I think this could be a problem of QtWebEngine, but I'm not sure.

**Comment by The-Compiler** [comment]
This definitely looks like a QtWebEngine issue - if you can, I suggest [using PyQt from PyPI](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-qutebrowser-with-tox) to get a newer Qt.
