### ISSUE TITLE
Catch Render Crashes Gracefully

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#3019]
It would be nice to have an option for QuteBrowser to show a page along the lines of:

"Oh no, something went wrong"
"The renderer process of this tab crashed"

I find annoying to find myself with the browser disappeared (crashed and closed) without an idea of what happened (besides what I see on the command line)

This came to mind just while I was writing issue #3018.

Thank you for this great software

**Comment by The-Compiler** [comment]
That's already the case with QtWebEngine, and not possible with QtWebKit.
