### ISSUE TITLE
Where is config.py ?

### ISSUE THREAD

**Issue by ersi-dnd** [qutebrowser/qutebrowser#3021]
The new version says that the system to set keybinds has changed and I cannot figure it out. The  :help page says the best way to change keybinds is via config.py file in the config directory, but I cannot find it there. 

Is there a pre-made config.py file so I could sort it out how to change keybinds there?

**Comment by NoctuaNivalis** [comment]
Did a tab open when you first started qb with the new config system installed? If not, it should have. Check out `qute://help/configuring.html`.

**Comment by ersi-dnd** [comment]
I mean that it would be great if there were a config.py already somewhere defining the keybinds, so that the user can study it and change it by trial and error. I personally cannot create a config.py out of thin air, because I don't know python. With a sample file included I would be able to learn maybe, as far as necessary to maintain qutebrowser on my computer.

This one does not seem to be defining configuration settings and keybinds, not that I can see anyway https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/config/config.py

**Comment by The-Compiler** [comment]
> The :help page says the best way to change keybinds is via config.py file

Where does it say so?

> I mean that it would be great if there were a config.py already somewhere defining the keybinds, so that the user can study it and change it by trial and error.

See #2980.

> I personally cannot create a config.py out of thin air, because I don't know python.

Note that you can use `:bind` instead, and that there are examples in [the docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#binding-keys).

**Comment by ersi-dnd** [comment]
@The-Compiler > Where does it say so?

I interpreted it so when I first read "Configuring qutebrowser via the user interface" and then there's the next section "Configuring qutebrowser via config.py" that begins "For more powerful configuration possibilities, you can create a config.py file." 

Why should I be happy with anything less powerful and more cumbersome?

Good that you plan to include a sample config.py later and thank you for all the documentation. Without the documentation I would be completely lost. However, a config.py file that contains all the effective keybinds and is included upon installation is an even better idea, because it is practically documenting itself. In my opinion, the best situation is when the user can configure the app by opening and editing the configuration files. 

Documentation helps, sure, but transparent configuration files are self-documenting.

**Comment by NoctuaNivalis** [comment]
The help file was perhaps not perfectly formulated, both are equally powerful at the moment, but the `config.py` makes it cleaner to keep your configuration version controlled.

Note that this overview of documented settings still exists, on `qute://settings`.

**Comment by The-Compiler** [comment]
> However, a config.py file that contains all the effective keybinds and is included upon installation is an even better idea, because it is practically documenting itself.

Can't really easily install it at installation-time to a sane place, and it actually setting the values proved to be a bad idea (because then qutebrowser can't change defaults). With that, we end up with what's proposed in #2980 :wink:

**Comment by ersi-dnd** [comment]
@The-Compiler 
> Can't really easily install it at installation-time to a sane place, and it actually setting the values proved to be a bad idea (because then qutebrowser can't change defaults). With that, we end up with what's proposed in #2980

I see. Generally apps can have a config in something like /etc or /usr/share and the app uses this config until the user copies the config into .config/qutebrowser and modifies it. So you are saying it doesn't work in this case? Maybe because of the way python is? Well, okay.

**Comment by NoctuaNivalis** [comment]
Let's say it's harder on Windows and OSX.
