### ISSUE TITLE
Subsonic web player occasionally stops playing

### ISSUE THREAD

**Issue by lycurgus** [qutebrowser/qutebrowser#3022]
Occasionally when playing a song via the [Subsonic](https://subsonic.org) web player the player fails to start the next track when one finishes, or randomly stops playing a few seconds into a track. Nothing seems to show in the JS console, or in the terminal with `--debug`, when this happens.

The issue can also be observed on the Subsonic demo site (http://www.subsonic.org/pages/demo.jsp) though I initially saw it in the player for my own instance (same Subsonic version).

Is there anywhere else I can gather information about what's going on to assist investigation?

qutebrowser info:

```
Version info

qutebrowser v0.10.1
Backend: QtWebKit-NG

CPython: 3.6.2
Qt: 5.7.1
PyQt: 5.8.1

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 602.1
SSL: OpenSSL 1.0.2j-fips  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.12.13-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5
OS Version: 

--- /etc/redhat-release ---
Fedora release 26 (Twenty Six)

--- /etc/os-release ---
NAME=Fedora
VERSION="26 (Workstation Edition)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Workstation Edition)"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation

--- /etc/system-release ---
Fedora release 26 (Twenty Six)

--- /etc/fedora-release ---
Fedora release 26 (Twenty Six)

Paths:
config: /home/lycurgus/.config/qutebrowser
data: /home/lycurgus/.local/share/qutebrowser
system_data: /home/lycurgus/.local/share/qutebrowser
cache: /home/lycurgus/.cache/qutebrowser
download: /home/lycurgus/Downloads
runtime: /run/user/1000/qutebrowser

```

**Comment by The-Compiler** [comment]
This looks like some issue with QtWebKit (maybe @annulen wants to take a look?) and not something qutebrowser itself could fix. What you could do is upgrading to qutebrowser v0.11 and checking with the QtWebEngine backend by starting with `--backend webengine` - it might work better there.

**Comment by lycurgus** [comment]
Thanks for the quick response! Unfortunately it looks like it doesn't work at all under QtWebEngine on v0.10 (I get `ERROR: [http://demo.subsonic.org/playQueue.view:703] Uncaught (in promise) NotSupportedError: The element has no supported sources.` when clicking play - and no sound).

It doesn't look like v0.11 is packaged for Fedora yet but I'll keep an eye out and give it another try when it is :)

**Comment by jgkamat** [comment]
hmm, this seems to work for me (webengine 5.7.1), but I'm on a newer version of qutebrowser. It's also possible this site needs proprietary codecs.

**Comment by The-Compiler** [comment]
Yeah, that error looks like Fedora doesn't compile QtWebEngine with support for proprietary codecs - since e.g. Debian does, you might want to open a Fedora bug about that. If you do, please link it here!

**Comment by lycurgus** [comment]
A couple of friends more familiar with Fedora's philosophies suggested that the proprietary codec support might have been unlikely to be added... however I came across qt5-qtwebengine-freeworld in the rpmfusion-free repository, which appears to have been compiled with the relevant support (at least, installing it and launching qutebrowser allows the Subsonic player to work as it didn't before).

At the moment I'm content with that as a solution (and will try again with the "standard" build once qutebrowser v0.11 hits the repos). Thanks for the prompt that got me looking in the direction of the freeworld build :)
