### ISSUE TITLE
Gentoo ebuilds are outdated

### ISSUE THREAD

**Issue by refacto** [qutebrowser/qutebrowser#3023]
The gentoo ebuilds have multiple issues.
1. The stable  versions are *ancient*
2. Qutebrowser now depends on `dev-python/attrs` and python >= 3.5
3. qutebrowser-9999 doesn't reflect the documentation move to doc (That doesn't build anymore)

**Comment by The-Compiler** [comment]
The install page [says so](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#on-gentoo), and nobody here is happy about it either - but nobody here can do something about it. There's are various [Gentoo bugs open](https://bugs.gentoo.org/buglist.cgi?quicksearch=qutebrowser&list_id=3673048), but nobody seems to care about those either... ¯\_(ツ)_/¯

**Comment by jgkamat** [comment]
If you want to try and get in touch with the gentoo qutebrowser maintainer, [here is an old ebuild I made](https://github.com/gentoo/gentoo/pull/4866) for `0.10.1`. It's outdated now though, so it needs more upgrades for `0.11`.

**Comment by Ambrevar** [comment]
I've just published an updated ebuild on the bugtracker, hopefully it gets accepted soon:
https://bugs.gentoo.org/630542

**Comment by mschilli87** [comment]
fyi: `1.0.21` [was added 2017-10-26](https://bugs.gentoo.org/630542#c8).

**Comment by Ambrevar** [comment]
1.0.3 as well.  This issue can be closed I believe.

**Comment by The-Compiler** [comment]
It already is closed :wink:
