### ISSUE TITLE
Up and Down keys don't navigate the popup

### ISSUE THREAD

**Issue by ersi-dnd** [qutebrowser/qutebrowser#3030]
The Up and Down keys used to make the items in Quickmarks/Bookmarks/History/Commands popup accessible. After the config revolution the Up and Down keys stopped working in the popup.

**Comment by The-Compiler** [comment]
They now navigate to the history - see [the docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#migrating-older-configurations) for an explanation.

**Comment by ersi-dnd** [comment]
Tab key focuses the popup. Where can I see how Tab is bound?

**Comment by The-Compiler** [comment]
`:bind --mode command <Tab>` will tell you - by default it's bound to `:completion-item-focus next`.

**Comment by ersi-dnd** [comment]
Thank you.
