### ISSUE TITLE
Documentation: inconsistent types and default values

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3046]
[The documentation](qute://help/settings.html#url.start_pages) says:

> url.start_pages
> The page(s) to open at the start.
> Type: List of FuzzyUrl
> Default: https://start.duckduckgo.com

The default value matches the `autoconfig.yml` side of the config system, but the type is wrong for this side (I could not figure out how to set a list with `:set`, so the acceptable type is just FuzzyUrl).

On the `config.py` side, however, the type is correct but the default value should read as `["https://start.duckduckgo.com"]`.

There may be other settings with similar problems, I'm just still at the _start_...

**Comment by The-Compiler** [comment]
You might want to rebuild your documentation, as [it says](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/settings.asciidoc#urlstart_pages) "List of FuzzyUrl, or FuzzyUrl" currently :wink:

In other words, you can either just supply a single URL, or a list of URLs. With `:set` you'd need to do `:set url.start_pages '["...", "..."]'` if you want to supply a list, but #2794 will probably make this kind of thing easier.

**Comment by lahwaacz** [comment]
Heh, I just built the `qutebrowser-git` package from AUR...

**Comment by lahwaacz** [comment]
Actually, I'm convinced now that my HTML documentation was correct. The problem is that in asciidoc it is written as
```asciidoc
Type: <<types,List of FuzzyUrl, or FuzzyUrl>>
```
and the converter somehow does not like the comma after `FuzzyUrl`.

**Comment by The-Compiler** [comment]
Yep, my bad - sorry for blaming you :wink:! Seems like GitHub doesn't mind it, but asciidoc itself will.

**Comment by The-Compiler** [comment]
Fixed now - I hope that makes things more clear?

**Comment by lahwaacz** [comment]
No problem, I'm glad it ~will be fixed soon~ is fixed already :wink: 

Anyway, to continue my point on the formatting of the default values with a better example, what are your thoughts on formatting list and dict values more like sphinx does? For example, is the default value of [content.javascript.log](qute://help/settings.html#content.javascript.log) this in Python?
```python
{
    "error": "debug",
    "info": "debug",
    "unknown": "debug",
    "warning": "debug",
}
```
I think Pythonists can't really tell from the current format...

**Comment by lahwaacz** [comment]
Also, boolean values should be `True` and `False` instead of `true` and `false` to match Python (but that probably does not match what `:set` accepts...)

**Comment by The-Compiler** [comment]
My goal with the settings documentation was mainly to have a "human-readable" way of showing the defaults. Unfortunately, the way those defaults are expressed in Python and e.g. via `:set` are going to be slightly different. I think the best way to solve that is:

- Having examples in [configuring.asciidoc](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc) on how to set those (I think that part is already fine)
- Having an example in the [types](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/settings.asciidoc#types) section. This already mentions how to set a list/dict from a string, it should probably mention that you can pass a Python dict/list in `config.py`.
- Having a `config-example.py` or `:config-write-py` command (#2980, #2794), i.e. an easy way to get a `config.py` file with the defaults in it in Python syntax.
