### ISSUE TITLE
Don't create autoconfig.yml if it's not loaded from config.py

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3047]
If the user has a `config.py` which does not load the `autocnfig.yml` file, it's useless to create it after using the `:set` or `:bind` commands &ndash; they are supposed to be temporary in this case anyway.

**Comment by The-Compiler** [comment]
It's intended to still create it, and I'd rather keep it that way - that way, after playing with them a bit, you can still decide to persist things. You could probably alias `:set` to `:set -t` (and `:bind` to `:bind -t` with #2988) if you disagree :wink:

**Comment by lahwaacz** [comment]
If I wanted to persist it, I would have to edit `config.py` anyway (either set the setting or load `autoconfig.yml` and deal with all other forgotten settings set this way) so I don't see how always creating the file makes persisting easier.

But anyway, aliasing `set -t` seems to work for me.
