### ISSUE TITLE
Get rid of "force" for :bind?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3049]
I'm wondering how useful `--force` for `:bind` (to override existing bindings), and `force=True` for `config.bind` (in `config.py`) really are.

In the case of `config.py`, it's really in the way for a `:config-source` command, as you can't just source your config file.

Maybe instead existing keybindings should just be overridden by default - what do you think?

**Comment by NoctuaNivalis** [comment]
If the completion always suggests the default binding, you have a "backup". So even if you did accidently overwrite a binding, you can always set it back to the default without removing your whole `autoconfig.yml`. We don't need the force.
