### ISSUE TITLE
Pick backend automatically for tests

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3051]
The end2end tests should detect when only QtWebEngine is available and do the equivalent of `--qute-bdd-webengine`. The default should maybe still be QtWebKit as the tests run noticeably faster.

cc @Enzime

**Comment by The-Compiler** [comment]
This should actually be quite straightforward: In `pytest_configure` in `tests/conftest.py`, do some more checking to decide what backend to pick.

**Comment by pylbrecht** [comment]
Hi, this seems like a good first pick as a new contributor, so I'd like to give that a try.

I already looked into the `pytest_configure()` hooks in `tests/conftest.py` as well as in `tests/end2end/conftest.py`.
Isn't the [`set_backend()` fixture](https://github.com/qutebrowser/qutebrowser/blob/master/tests/conftest.py#L237-L244) in `tests/conftest.py` already solving this issue?

**Comment by The-Compiler** [comment]
@pylbrecht Welcome! No, that fixture doesn't solve the issue - it takes care of setting the `objects.backend` global based on the configured backend (`config.webengine`), but the tests still default to using QtWebKit even if it's unavailable.

The place where this happens is indeed [`pytest_configure()`](https://github.com/qutebrowser/qutebrowser/blob/f2881c7e30be12ac5cceba96003b0482b24ed692/tests/conftest.py#L221-L224), which currently uses either `--qute-bdd-webengine` or the `QUTE_BDD_WEBENGINE` environment variable to pick the backend.

Instead, it should pick QtWebKit if it can be imported, otherwise pick QtWebEngine automatically. Also, `--qute-bdd-webengine` and `QUTE_BDD_WEBENGINE` should probably be replaced by a `--qute-bdd-backend` and `QUTE_BDD_BACKEND` allowing to override the auto-detection.

Finally, it'd be amazing to have a small [`pytest_report_header` hook](https://docs.pytest.org/en/6.2.x/example/simple.html?highlight=pytest_report_header#adding-info-to-test-report-header) to display the backend picked.

I hope this makes things cleaner - if not, please let me know! Missed your message in IRC yesterday.

**Comment by pylbrecht** [comment]
Thanks for elaborating, that makes things a lot clearer!

> but the tests still default to using QtWebKit even if it's unavailable.

For me when running tests via `tox` usually [`QUTE_BDD_WEBENGINE` is set automatically](https://github.com/qutebrowser/qutebrowser/blob/f2881c7e30be12ac5cceba96003b0482b24ed692/tox.ini#L16).
Maybe I'm missing something here, in what scenario would tests default to QtWebKit?

---

Just to make sure I understood things correctly:

Pick QtWebKit
- if both QtWebKit and QtWebEngine are available
- if only QtWebKit is available

Pick QtWebEngine
- as a fallback if QtWebKit is not available
- if explicitly set via `--qute-bdd-backend` or `QUTE_BDD_BACKEND`

> Also, --qute-bdd-webengine and QUTE_BDD_WEBENGINE should probably be replaced by a --qute-bdd-backend and QUTE_BDD_BACKEND allowing to override the auto-detection.

So instead of being a switch, `--qute-bdd-backend` and `QUTE_BDD_BACKEND` should take the backend as a string then?

**Comment by The-Compiler** [comment]
Yes, that environment variable is set via tox when using a prebuilt PyQt. But instead, we should autodetect the backend in the tests and remove that part of the tox.ini, so that it works everywhere. Right now, `--qute-bdd-webengine` needs to be specified manually when e.g. running `tox -e py39` (using the system-wide Qt install) or when running the tests outside of tox, like from editor or IDE integration.

**Comment by The-Compiler** [comment]
Ah, and as for the logic you described, that sounds spot-on, yep!
