### ISSUE TITLE
Have a way to reset bindings to their default

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3059]
After doing `:unbind H`, there's no way to set it to its default without looking it up.

I can see two solutions:

- Something like `:unbind --default H` should exist (`:config-unset` isn't really a good match for bindings).
- The completion should show the default after `:bind H` (similar to what the `:set` completion already does) (@rcorre - we probably need to give completion functions a parsed commandline for this one to work?)

**Comment by lahwaacz** [comment]
Sounds like `--default` should be a parameter for `:bind`, not `:unbind`.
