### ISSUE TITLE
Typical OS X shortcuts not working in input fields

### ISSUE THREAD

**Issue by benjmin-r** [qutebrowser/qutebrowser#3060]
On OS X there are several system wide keyboard shortcuts for navigating within all kinds of text input fields, such as textareas and single line input fields. [Mac Keyboard Shortcuts](https://support.apple.com/en-us/HT201236) lists them under the section 'Document Shortcuts'.

Most of them are currently not supported/honored by qutebrowser. While `Option–Left Arrow` and `Option–Right Arrow` are working (at least for me), especially all `Cmd` related shortcuts are not working, but also the typical emacs-like shortcuts like `Ctrl-A` or `Ctrl-E` are not working.

```
qutebrowser v0.11.0
Git commit: v0.11.0-1138-g9870936 (2017-10-05 23:33:00 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.1
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: Secure Transport, macOS Sierra (10.12)

Style: QMacStyle
Platform: Darwin-16.7.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.12.6, x86_64
```

That said: Thanks for this great software! It's a real lifesaver for me, now that FF & vimperator won't work for much longer!

**Comment by The-Compiler** [comment]
It's a QtWebEngine bug, see [QTBUG-54692](https://bugreports.qt.io/browse/QTBUG-54692). A fix is currently [being reviewed](https://codereview.qt-project.org/#/c/207499/), and will most likely land in Qt 5.10, so this will be fixed with some qutebrowser release in December (after 5.10 is released).
