### ISSUE TITLE
Evaluate python expressions

### ISSUE THREAD

**Issue by fakedrake** [qutebrowser/qutebrowser#3062]
It would be nice to be able to evaluate python expressions while browsing like you could evaluate javascript in vimperator. Not sure if this exists or how easy it is. I would be willing to work on it.

**Comment by jgkamat** [comment]
You might be looking for:

`:debug-console`

or 

`:debug-pyeval`

Although, I'm not exactly sure what your end goal is. Perhaps you would be interesting in writing userscripts?

**Comment by The-Compiler** [comment]
There's also `:jseval` to evaluate javascript in the page's context. `:debug-pyeval` (and `-console`) are kind of non-public, as there's no API guarantee for internal qutebrowser code.
