### ISSUE TITLE
Retain browser mode (insert/passthrough) when switching tabs

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#3065]

**Comment by Ape** [comment]
Should the mode be per tab or just global?

**Comment by The-Compiler** [comment]
A per-tab mode seems unnecessarily complex to me.

**Comment by Ape** [comment]
There are cases where I'm writing something (in insert mode), but I have to switch tabs briefly to lookup a thing. Currently, when I switch back to the tab I'm writing in, I have to remember to go to insert mode. Sometimes it's easy to forget and typing in normal mode might have annoying behaviour (like pressing `d`).

I guess I should just be using external editor more.
