### ISSUE TITLE
Crash watching Netflix, unable to restart: intel_do_flush_locked failed: Input/output error

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#3076]
I was watching Netflix when all of a sudden the video got choppy, froze, and then qutebrowser totally crashed. I was then unable to restart qutebrowser; kept getting the error

```
intel_do_flush_locked failed: Input/output error
```

I figured I probably needed to clear out some cache or something, but I didn't know exactly what, so I just restarted my computer, which fixed things.

Relevant info from `qute:version`:

```
qutebrowser v0.11.0
Git commit: v0.11.0-1044-g0b5af757e (2017-09-28 21:51:07 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.9.54-1-lts-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

I'm using [qt5-webengine-widevine](https://aur.archlinux.org/packages/qt5-webengine-widevine/) to watch Netflix with webengine.

I don't think I can reproduce the problem, or give more info, but just wanted to report it here anyway. (When I restarted qutebrowser, after restarting my computer, there was no option to report the issue, so I guess qutebrowser had no memory of what occurred.)

**Comment by The-Compiler** [comment]
Looks like a graphic driver bug, see e.g. https://askubuntu.com/questions/170668/intel-do-flush-locked-failed-input-output-error/
