### ISSUE TITLE
Captive portal doesn't open when connecting to a public wifi

### ISSUE THREAD

**Issue by anhtuann** [qutebrowser/qutebrowser#3083]
When I connect to the public wifi of my library, qutebrowser doesn't redirect me to the captive portal where I can enter my login infos in order to get internet. 

_Version info_ : 
**qutebrowser v0.11.0
Backend: QtWebEngine (Chromium 56.0.2924.122)
Platform: Linux-4.13.5-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)**

**Comment by The-Compiler** [comment]
This isn't supported by QtWebEngine, so qutebrowser can't implement this. But even if it was, it'd require "phoning home" to some server, which is not something I'd like to do either.

You can simply open a page which doesn't use HTTPS, such as http://http.badssl.com/ and should get redirected.

**Comment by Ape** [comment]
This isn't really the responsibility of your web browser. You might have the browser closed and still need the connectivity for other applications. Yes, you must open some browser to enter the credentials, but the captive portal detection should work before you open a browser.

So instead, you should try something like this:
https://aur.archlinux.org/packages/capnet-assist/

**Comment by anhtuann** [comment]
@The-Compiler I didn't know the trick about querying an http page to get redirected. Should have made some research on it before hand.
