### ISSUE TITLE
'bind y<space> hint links yank' doesn't work, follows hints instead

### ISSUE THREAD

**Issue by pevu** [qutebrowser/qutebrowser#3085]
Using these mappings (normal mode):

	<space> hint
	y<space> hint links yank
	yf hint links yank

`yf` works as expected, but `y<space>` opens the link (behaves like pressing `<space>` without prefix)

	Version info

	qutebrowser v0.11.0
	Git commit: v0.11.0-1252-g96c0cde (2017-10-11 16:26:52 +0200)
	Backend: QtWebEngine (Chromium 56.0.2924.122)

	CPython: 3.5.2
	Qt: 5.9.1
	PyQt: 5.9

	sip: 4.19.3
	colorama: 0.3.9
	pypeg2: 2.15
	jinja2: 2.9.6
	pygments: 2.2.0
	yaml: 3.12
	cssutils: 1.0.2 $Id$
	attr: 17.2.0
	PyQt5.QtWebEngineWidgets: yes
	PyQt5.QtWebKitWidgets: no
	pdf.js: no
	sqlite: 3.16.2
	QtNetwork SSL: OpenSSL 1.0.2j  26 Sep 2016

	Style: QFusionStyle
	Platform: Linux-4.4.0-96-generic-x86_64-with-debian-stretch-sid, 64bit
	Linux distribution: Ubuntu 16.04.3 LTS (ubuntu)
	Frozen: False
	Imported from /home/pao/p/qutebrowser/qutebrowser
	Qt library executable path: /home/pao/p/qutebrowser/.venv/lib/python3.5/site-packages/PyQt5/Qt/libexec, data path: /home/pao/p/qutebrowser/.venv/lib/python3.5/site-packages/PyQt5/Qt

	Paths:
	cache: /home/pao/.cache/qutebrowser
	config: /home/pao/.config/qutebrowser
	data: /home/pao/.local/share/qutebrowser
	runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
You can't mix special keys with alphanumeric ones, see #319.
