### ISSUE TITLE
v1.0.0 release ready!

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3090]
I usually don't open issues to track releases, but I feel like this one warrants a little announcement:

I plan to release v1.0.0 tomorrow (2017-10-12 ~~-11~~), probably without any changes (except packaging/release related) compared to the current git master. If you find a regression or think something *really* has to be in v1.0.0, let me know **now**.

Like mentioned in https://github.com/qutebrowser/qutebrowser/issues/27#issuecomment-334598923, per-domain settings aren't going to make it into v1.0.0. I know it'd be an awesome feature for a v1.0.0 release, but I feel like it's unreasonable to delay it any further. The release has more than enough big new things, and it's huge compared to v0.11 (if this is any indication: `366 files changed, 22337 insertions(+), 20348 deletions(-)`).

Let's finally ship QtWebEngine by default, the new config, and the improved completion :wink:

**Comment by fiete201** [comment]
According to German timezone tomorrow is the 12th of October :-D

**Comment by The-Compiler** [comment]
@fiete201 You're absolutely right. I originally wanted to release at the local [hackerspace](https://ccczh.ch/hackerspace/) to properly celebrate it with a nice bottle of [Club Mate](https://en.wikipedia.org/wiki/Club-Mate), but then I decided to go home as I'm too tired to do a proper release. Turns out that was the right decision 😆

**Comment by thisch** [comment]
Don't you want to create a RC for 1.0.0 and wait for feedback for a few weeks until you release 1.0.0 ?

**Comment by The-Compiler** [comment]
No, a lot of people are using the git master, so I've gotten a lot of feedback already. I don't expect any new insights by releasing an RC, as people are either using their distro packages (and thus won't use an RC), or are using the git master (and thus won't either).

**Comment by bearcatsandor** [comment]
A few weeks ago, you warned against using the git master, as the
configuration structure was changing rapidly.  Is it now "safe" (settled
down enough) to use the git master again? Is there a list of manual changes
to make to our config files to bring it in line with git master?

On Wed, Oct 11, 2017 at 3:27 PM, Florian Bruhin <notifications@github.com>
wrote:

> No, a lot of people are using the git master, so I've gotten a lot of
> feedback already. I don't expect any new insights by releasing an RC, as
> people are either using their distro packages (and thus won't use an RC),
> or are using the git master (and thus won't either).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <http://email.felinesoulsystems.com/c/eJx9jsEOwiAQRL-m3DSlC7YcOHjxP7Z0sSSlVVji70s9aIyJySQ7c5idN1nSxrhOBHsvTGPaHplS012-U8i5UK4GWtPuB7TR0A-mUe018FzGo9uimK0iHGjyHlF1pJzrT1KCl1KZHkhqKRY7M99yA-f6purT_hn9iwCvXGuRVj68eUSyI2FyyBnXaUs7X8Sw7ANP_ZdMkA>,
> or mute the thread
> <http://email.felinesoulsystems.com/c/eJxVjsFuwyAQRL_GvrUiEBo4cHDVJFKUVjlUSdsbC9hGSUzKQu38ffGpqrTS7oy088Yqx6U0tPbqOycHMYzoYkU3_5VHzA7LwYgk82JccrYSslqSzqc-w6MJ17pXT63UjIAVvKULy5gAWFmwLaGEcwKL-qL6lG5YsabElPn7LmIIybfe6OTDMNPygBnQRA_uQefUF6tpXrrDFN7Ecbt345Ycp-m-3nwIvJPPkzWnM3KM7_vnTu9uX6_LA12PP3VU4HQsuagHG-Jc-qr9Zab-AsbEVRc>
> .
>



-- 
Bearcat M. Şándor
Feline Soul Systems LLC
Voice: 872.CAT.SOUL (872.228.7685)
Fax: 406.235.7070

**Comment by The-Compiler** [comment]
@bearcatsandor Yep! See the [later announcement](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2017-September/000023.html) about big changes in v1.0.0 being done.

There's no list of changes, and I don't think it's easy to make one. Apart from the config format changing completely, options were renamed, removed, merged, values changed, etc. However, there's qute://help/configuring.html which documents the new config in detail, and qute://configdiff/old which tells you what was changed in your old config.

**Comment by The-Compiler** [comment]
Aaaand it's done! 🎉

**Comment by nemanjan00** [comment]
Great job! :)

Flagged it out of date in AUR. 
The one in community repo was already flagged.. :)

**Comment by The-Compiler** [comment]
@nemanjan00 VCS packages aren't out of date as long as they build. On top of that, it's already updated to v1.0.0...

**Comment by bitraid** [comment]
Windows builds are v0.11.1???

**Comment by The-Compiler** [comment]
@bitraid What do you mean exactly? Are you referring to the "Git commit:" in the version info?

**Comment by bitraid** [comment]
Ignore that! i was running the previous build by mistake...
