### ISSUE TITLE
Bind to command with trailing space

### ISSUE THREAD

**Issue by bendiksolheim** [qutebrowser/qutebrowser#3092]
Hello,

Playing around with qutebrowser, I am trying to rebind `b` to `set-cmd-text :buffer ` so I can get a list of buffers/tabs by pressing `b`. Note the trailing space here. Binding to just `set-cmd-text :buffer` does not trigger the buffer completion, since that seems to require a space after `:buffer`. However, I can’t seem to find a way to make this trailing space be part of the bound key/command. I have tried the following:

- `bind --force b set-cmd-text :buffer `
- `bind --force b set-cmd-text ':buffer '`
- `bind --force b set-cmd-text ":buffer "`

The first one works, but I need to press `<space>` after pressing `b` to trigger buffer completion. According to #233 (which is old, I know) it should work to surround with `"` to keep the space, but that gives me the error `Invalid command text '":buffer "'.` when pressing `b`. Am I doing something wrong here?

Unsure if this is a bug or not, but here are my version details anyway: https://gist.github.com/bendiksolheim/be38432af71fc107c6e518115d174fc1

**Comment by The-Compiler** [comment]
There's an `-s` argument for `:set-cmd-text` to add a trailing space, i.e. you want `:bind --force b set-cmd-text -s :buffer` (see `:help :set-cmd-text` for details).

**Comment by bendiksolheim** [comment]
You win the internet award for quick response! That works flawlessly – thanks a lot :)
