### ISSUE TITLE
Scrolling suggestions

### ISSUE THREAD

**Issue by nemanjan00** [qutebrowser/qutebrowser#3094]
Version is from v1.0.0 branch

When I press O and type something, I can not use arrows anymore to pick suggestion. 

Are there any other bindings?

**Comment by The-Compiler** [comment]
The default bindings have changed, but Tab/Shift-Tab is still bound. See [the related docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#migrating-older-configurations).

**Comment by nemanjan00** [comment]
Thank you! :)

**Comment by The-Compiler** [comment]
I added it to #2466.
