### ISSUE TITLE
macOs How to enable webinspector

### ISSUE THREAD

**Issue by phm3** [qutebrowser/qutebrowser#3101]
I am not able to pass --help ARG to browser

`open -a qutebrowser.app --args --help` does nothing.

**Comment by The-Compiler** [comment]
Sorry for the late answer! I'm not sure how `open --args` works exactly on macOS. Can you please try doing something like `./qutebrowser.app/Contents/macOS/qutebrowser --help` instead? (The path is from memory, I haven't tested).

**Comment by The-Compiler** [comment]
I don't know what `open` does exactly with `--args`, but looks like printing to the terminal that way isn't possible. However, running the executable directly works.
