### ISSUE TITLE
Next/previous in command window list

### ISSUE THREAD

**Issue by octavz** [qutebrowser/qutebrowser#3109]
I am using version 1.0.1 on OS X, and it appears that nothing works when trying to go up/down with arrows in command window.

Ex. 
`:open ` and then a bunch of history/marks appear in the list, choosing one, before worked with arrows, now it doesn't and I couldn't find any shortcut (Ctrl+P, Ctrl+N), is it an issue or I am missing something.

Thank you

**Comment by The-Compiler** [comment]
Up/Down now navigate through command history, use Tab. See https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#migrating-older-configurations

**Comment by octavz** [comment]
thank you, good job btw.
