### ISSUE TITLE
Spawn with ~ (for HOME) doesn't work

### ISSUE THREAD

**Issue by edi9999** [qutebrowser/qutebrowser#3112]
In my autoconfig.yml , I have : 

      zz: spawn  --userscript ~/dotfiles/qute_pass_fill_fzf

When I hit zz, this fails with error "The process failed to start"

However, when I run `spawn  --userscript ~/dotfiles/qute_pass_fill_fzf`, it works.

Is there some sort of quoting to do in the config ?

**Comment by The-Compiler** [comment]
Works fine here. Note that you shouldn't edit `autoconfig.yml` by hand, create a `config.py` instead.

If it doesn't work when done in a `config.py`, can you please do `:report` so I can take a look at the logs?

**Comment by jgkamat** [comment]
I can't reproduce as well (I have a few scripts doing exactly this). Could you post the output of qute:version and the environment where you installed qutebrowser as well? Maybe $HOME isn't getting set or something...

**Comment by edi9999** [comment]
I didn't edit the config file by hand, I ran 

```
:bind zz spawn --userscript ~/dotfiles/...
```

I'm not on my computer but I will try to unbind/rebind zz and see if it works better and let you know

**Comment by The-Compiler** [comment]
Ah, sorry - "Is there some sort of quoting to do in the config ?" made me assume that was the case.

**Comment by edi9999** [comment]
I have just started my computer and qutebrowser, it seems to be working now.

I'm closing this issue
