### ISSUE TITLE
Qutebrowser doesn't pass the badssl.com test

### ISSUE THREAD

**Issue by bstaletic** [qutebrowser/qutebrowser#3113]
[badssl.com](https://badssl.com/) is a site hosting an intentionally bad ssl certificate so users can test which potentially unsafe connections their browsers accidentally use.

On the [dashboard](https://badssl.com/dashboard) is a summary of what failed.

By the looks of it qutebrowser allowed connection without prompt in two cases:
- [sha1-intermediate](https://sha1-intermediate.badssl.com/)
- [Diffy-Hellman 1024](https://dh1024.badssl.com/)

**Comment by jgkamat** [comment]
Using:
```
qutebrowser v1.0.1
Git commit: v1.0.1 (2017-10-13 09:21:56 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.1
Qt: 5.9.1
PyQt: 5.9
```

I seem to properly get errors (cert warning on the first one, unsupported protocol error on the second). Perhaps you are using an older version of webengine? On my webengine `5.7.1` those sites don't error out as they should.

If you would like a newer version of webengine, you could try installing qutebrowser through tox.

**Comment by gilbertw1** [comment]
The badssl.com dashboard looks good to me. I'm using:

```
qutebrowser v1.0.0
Git commit: v1.0.0 (2017-10-12 09:15:02 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.2
PyQt: 5.9
```

Here's the dashabord output:

![badssl](http://drop.bryan.sh/ISYt9tEqol.png)

Granted it asked me to accept/deny each individual invalid certificate, the output would have been incorrect if I had pressed 'y' to accept the invalid certs.

**Comment by kimat** [comment]
same output as @gilbertw1 on https://badssl.com/dashboard/ after pressing `n` for each certificate prompt.

```
qutebrowser v1.0.1
Git commit: v1.0.1-1-gdb8fa5f-dirty (2017-10-13 10:45:40 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.5.2
Qt: 5.9.1
PyQt: 5.9
```

**Comment by The-Compiler** [comment]
As others mentioned, the tests pass on Qt 5.9. Nothing qutebrowser can do about the behaviour of older Qt versions.
