### ISSUE TITLE
Spellcheck dictionnaires doesn't include fr-CA

### ISSUE THREAD

**Issue by sim590** [qutebrowser/qutebrowser#3114]
Spellchecking dictionnaries list doesn't include `fr-CA` which is french from Canada (Québec) according to the qutebrowser's documentation and neither from [this chromium documentation page][doc]. However, Chromium does provide the `fr-CA` language in its UI (see the screenshot below).

![lang](https://user-images.githubusercontent.com/4147254/31564696-d93799f8-b031-11e7-860b-dca2115f1d89.png)

*Version*
```
qutebrowser v1.0.0
Git commit: v1.0.0-6-g35d5038ab (2017-10-12 22:42:58 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.5.4
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.12.0-2-amd64-x86_64-with-debian-buster-sid, 64bit
Linux distribution: Debian GNU/Linux buster/sid (debian)
Frozen: False
Imported from /home/simon/prog/qutebrowser/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/simon/.cache/qutebrowser
config: /home/simon/.config/qutebrowser
data: /home/simon/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
```

[doc]: https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries.git/+/master/

**Comment by The-Compiler** [comment]
cc @elshize - the repo linked above indeed doesn't have that file... No idea where Chromium is getting it from.

**Comment by elshize** [comment]
Indeed, Chromium provides additional languages for UI, however, those cannot be used to check spelling. It's not only the case for fr-CA but for many others. I downloaded fr-CA and tried to set it up for spell checking but here's what I got:

![image](https://user-images.githubusercontent.com/3026120/31586018-44de1eb2-b199-11e7-9b24-44c7b68b9c38.png)

**Comment by The-Compiler** [comment]
Ah, that explains things. Thanks for investigating, @elshize!
