### ISSUE TITLE
Google.com spawns a late navigation request, making typing queries painful

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#3124]
When surfing on google.com the cursor starts (as it should) inside the search box, but after a few seconds (even while writing the search query) google seems to spawn a navigation request, as reported by the debug logs (I omitted the full URL because it's very long):
`10:05:23 DEBUG    webview    webview:acceptNavigationRequest:296 navigation request: url https://notifications.google.com/ [omitted] type NavigationTypeLinkClicked, is_main_frame False`
Taking the typing cursor away from the search box.

This can happen more than once while typing the query, but usually it's reproducible by navigating to google and just waiting a few seconds

**Comment by The-Compiler** [comment]
What backend, Qt version and qutebrowser version? (There's a reason the issue template asks for this information: So I don't have to...)

**Comment by Penaz91** [comment]
I prepared the file with the version and forgot to attach it, sorry I'm really tired this morning ^^''
[version.zip](https://github.com/qutebrowser/qutebrowser/files/1385266/version.zip)

**Comment by The-Compiler** [comment]
Note to self: That is af3c9a2b9 with Qt 5.9.2 and QtWebEngine :wink:

I still can't reproduce it though, and it doesn't seem like a qutebrowser issue. Maybe you only see it when logged in or something? Do you see it in other browsers as well?

**Comment by Penaz91** [comment]
I am logged on google, yes, Testing with other browsers now.
Might be tied to google's notifications?

**Comment by neeasade** [comment]
I also experience this w/ qt 5.9.2 on release v1.0.1 - qutebrowser --version: https://ptpb.pw/Gg0c

Here's a webm (note the setting insert_mode.auto_load is set to true, you can see the search cursor flash briefly then leave): https://ptpb.pw/s_SX.webm

**Comment by The-Compiler** [comment]
I still can't reproduce it, but since you say you see it in QupZilla as well, this doesn't look like a qutebrowser issue indeed. Might be interesting to see whether you see it in Chromium as well.

**Comment by Penaz91** [comment]
Sorry to kind of necropost this, but I found a weird update about it. This issue seems to not happen on QupZilla 2.2.0 under Windows.

**Comment by The-Compiler** [comment]
This is probably [QTBUG-64082](https://bugreports.qt.io/browse/QTBUG-64082) which was introduced with Qt 5.9.2 and will be fixed with 5.9.3 and 5.10.

**Comment by The-Compiler** [comment]
@Penaz91 That actually also explains why you don't see it in QupZilla 2.2.0 on Windows - that bundles Qt 5.9.1. It looks like QupZilla 2.2.1 also still bundles 5.9.1 and not 5.9.2.

**Comment by Penaz91** [comment]
I can confirm that I'm using Qt 5.9.2 on Linux & QuteBrowser while QupZilla 2.2.1 on Windows bundles Qt 5.9.1.
I can't wait for this bug to be fixed, I get mad at this thing a lot xD

Thank you for keeping on investigating this.
