### ISSUE TITLE
Can't scroll through the bookmarks with arrow keys anymore

### ISSUE THREAD

**Issue by bheadmaster** [qutebrowser/qutebrowser#3125]
Before today's system update, using arrow keys in qutebrowser's commandline scrolled up and down through the "commands" window. Now pressing the 'up' and 'down' arrow keys scrolls through the command history.

I don't have any custom config, I use all the defaults.
I couldn't find anything in the change-log that mentioned this behavior. Is this something that was supposed to be changed in the version 1.0.1? If so, is there a way to change it back to the old behavior?

### Version info

qutebrowser v1.0.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.2
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.13.4-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/lark/.cache/qutebrowser
config: /home/lark/.config/qutebrowser
data: /home/lark/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Comment by Penaz91** [comment]
That's an intended behaviour, now up and down scroll through the command history. You can bind the keys to the old behaviour manually.

**Comment by Penaz91** [comment]
Here's the specific page on the docs:
https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#migrating-older-configurations

**Comment by bheadmaster** [comment]
Thank you!

**Comment by The-Compiler** [comment]
This was indeed missing from the changelog - I hope 392ea8825bb31e6888557df4c9ee18af5e4b7329 makes things more clear!
