### ISSUE TITLE
Version 1.0.0 new config style is a major downgrade

### ISSUE THREAD

**Issue by laurynas-karvelis** [qutebrowser/qutebrowser#3127]
Hi,

I've been using qutebrowser for quite a while now. Been truly loving it's config file, how informative and flexible it is. Using the new qute://settings config subsystem seems like author completely forgot the main idea of this project. It's vim-style browsing experience, hence moving from plain file style config to qute://settings just oddly reminds me of Chrome.

Please bring back the simple plain file-only config. Qutebrowser has it's niche, please don't ruin it to be yet another normie browser just for the sake of it. This is a big deal for me.

I hope my prayers will be heard. Cheers!

**Comment by The-Compiler** [comment]
Huh? `qute://settings` has been around since three years (before the first release), but nobody forces you to use it, neither before the change, nor after it. Please take a look at the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).

**Comment by mschilli87** [comment]
@laurynas-karvelis: Maybe the discussion [here](499#issuecomment-296370647) could help you to understand the history of decisions so far and possibilities for the future.
