### ISSUE TITLE
Be more restrictive about setting bindings.default

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3131]
Making `bindings.default` user-settable probably was a bad idea, I already see reports of people who (most likely accidentally) changed it.

Instead, we might want to:

- either have a `bindings.load_default` bool or so, and remove `bindings.default` from the config
- or only allow to set `bindings.default` to `{}` and nothing else.

**Comment by jgkamat** [comment]
Some more ideas (just throwing them out):

- Throw errors or hide `bindings.default` from set (only allow setting from python config)
- Print a warning to the console if `bindings.default` is set to it's non default value or `{}`

I like `bindings.load_default` the best, but throwing errors seem like a more reasonable option (to avoid people from modifying their config).

**Comment by The-Compiler** [comment]
This seems to affect people with the keyboard refactoring, as they have `bindings.default` in their `autoconfig.yml` and that hardcodes things like `y` and `n` in `prompt` mode (which are now in a `yesno` mode).

I guess I'll need to look at this before v1.2.0, still not sure what the best solution is. Maybe as a stop-gap solution just ignore (and disallow) that setting in `autoconfig.yml` but not `config.py`? That's essentially what @jgkamat proposed above.

**Comment by jgkamat** [comment]
Another thing I'm hoping this will fix is the new bindings causing `bindings.default` to come up for javascript completions over the setting I'm actually going for :P.

![2018-03-07-100530_269x105_scrot](https://user-images.githubusercontent.com/4349709/37099779-3e32ef86-21ef-11e8-9a61-be0ca45725c7.png)

**Comment by Migacz85** [comment]
So where I can find bindings.default settings right now ? I want to swith shift+j with shift+k for tabs. My brain is telling me that switching tabs is different way.

**Comment by The-Compiler** [comment]
@Migacz85 This doesn't seem to be related to this issue at all - see the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).
