### ISSUE TITLE
Feature request: automatically resolve local domain adresses

### ISSUE THREAD

**Issue by pltanton** [qutebrowser/qutebrowser#3135]
It would be handful if qutebrowser will resolve addresses without protocol, but with slash as suffix, like an url.

For example now if I try to `:open local-address-from-corporative-network/` it will open search page, but should be better if it will open page on `http://local-address-from-corporative-network`, like it does in Firefox and Chromium.

**Comment by The-Compiler** [comment]
You probably want `:set url.auto_search dns`.

**Comment by pltanton** [comment]
Amazing! Thanks.
