### ISSUE TITLE
Unhide tab bar when shift is released in "switching" mode

### ISSUE THREAD

**Issue by jamesbvaughan** [qutebrowser/qutebrowser#3141]
Currently, when tabs.show is set to "switching", the tab bar is shown for amount of time specified by tabs.show_switching_delay whenever Shift+j or Shift+k are pressed. This results in the tab bar staying visible after I have switched to the desired tab and don't care to see it anymore if I switch to it before the timeout, and it results in the tab bar being hidden before I have decided which tab to switch to if I press Shift+j or Shift+k and then take longer than the timeout to decide which tab I want to switch to.

For me, the more natural behavior would be for the tab bar to appear when Shift+j or Shift+k are pressed and to disappear when and only when Shift is released.

Hopefully that made sense. Thanks for a rad browser!

(Also, getting this and #1593 implemented would create a wonderful tab switching experience.)

**Comment by The-Compiler** [comment]
This isn't really possible with the model of binding keys to commands like qutebrowser does - you might as well bind `,` and `.` or whatever to switch tabs. I don't really see a way to make it fit I'm afraid.
