### ISSUE TITLE
Close tab with :tab-give/:tab-take regardless what tabs.last_close is set to

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3146]
When `:tab-give`/`:tab-take` is used in a way it closes the last open tab, it should probably close the window no matter what `tabs.last_close` is set to.

cc @forkbong @Enzime

**Comment by Enzime** [comment]
@The-Compiler some people might be interested in keeping that window open e.g. tiling window manager users who want to maintain their layout whilst moving their tabs

**Comment by The-Compiler** [comment]
Hmm, it's a fair point. Let's close this for now, and see if more people complain :wink:
