### ISSUE TITLE
Segmentation fault on start

### ISSUE THREAD

**Issue by animeshb** [qutebrowser/qutebrowser#3151]
I get the following error when I run:

    qutebrowser --backend webengine

> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007fc569d48700 (most recent call first):
>   File "/usr/lib/python3/dist-packages/qutebrowser/utils/version.py", line 413 in opengl_vendor
>   File "/usr/lib/python3/dist-packages/qutebrowser/misc/backendproblem.py", line 163 in _handle_nouveau_graphics
>   File "/usr/lib/python3/dist-packages/qutebrowser/misc/backendproblem.py", line 355 in init
>   File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 427 in _init_modules
>   File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 163 in init
>   File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 137 in run
>   File "/usr/lib/python3/dist-packages/qutebrowser/qutebrowser.py", line 186 in main
>   File "/usr/bin/qutebrowser", line 11 in <module>
> Segmentation fault
> 
> 

Note: the distro is debian buster, though `lsb_release` returns bunsenlabs.

___

#### Version information

qutebrowser v1.0.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.5.4
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QGtkStyle
Platform: Linux-4.13.0-1-amd64-x86_64-with-BunsenLabs-8.9-bunsen-hydrogen, 64bit
Linux distribution: BunsenLabs GNU/Linux 8.9 (Hydrogen) (unknown)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5
OS Version: 

--- /etc/os-release ---
ID=bunsenlabs
ID_LIKE="debian"
NAME="BunsenLabs GNU/Linux"
PRETTY_NAME="BunsenLabs GNU/Linux 8.9 (Hydrogen)"
VERSION="8.9 (Hydrogen)"
VERSION_ID="8.9"

--- /etc/lsb-release ---
DISTRIB_ID="BunsenLabs"
DISTRIB_DESCRIPTION="BunsenLabs GNU/Linux 8.9 (Hydrogen)"
DISTRIB_RELEASE="8.9"
DISTRIB_CODENAME="bunsen-hydrogen"

Paths:
cache: /home/animesh/.cache/qutebrowser
config: /home/animesh/.config/qutebrowser
data: /home/animesh/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Comment by The-Compiler** [comment]
Can you please try v1.0.2?

**Comment by animeshb** [comment]
Installing v1.0.2 has fixed the issue. Thank you for this fantastic software.
