### ISSUE TITLE
Completions not sorted after filtering

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#3156]
From the mailing list:

> Completion is sometimes sorted differently. For example, when I wanted to
> clear downloads, I used to write ":clear" and hit tab, the two results were
> download-clear
> history-clear
> and they were alphabetically sorted. Now, the completions for that are
> search
> history-clear
> download-clear
> config-clear
> and I cannot see what the pattern is, but it's not alphabetically in command
> or command description, for sure. Why is this now happening?

Looks like we lose sorting after filtering. I thought just inserting items in order would be fine, but looks like I need to bring back the `SortFilter`'s `sort` implementation. A bit embarrased I didn't test this :worried:

**Comment by Hi-Angel** [comment]
Would it be possible to sort specifically by latest used? E.g. when I'm typing stuff to `open` I expect the link-completions I visit most often to be on the top. FTR it worked in a similar way in Pentadactyl, and was really comfortable, so you can say it's tested.

**Comment by rcorre** [comment]
@Hi-Angel that should be exactly how `open` completion works for history entries right now. If it doesn't, could you please file a separate issue with repro steps?

If you're talking about `bookmark`/`quickmark` completion, those are presented in the same order they appear in the user's `bookmark`/`quickmark` file, which gives the user control of the order.

**Comment by lahwaacz** [comment]
@rcorre There is a difference between most-recently and most-often used :wink:

**Comment by rcorre** [comment]
Right, so which do you want? :wink: 

> Would it be possible to sort specifically by **latest** used?

Latest?

> I expect the link-completions I visit **most often** to be on the top

Or most often?

The former is implemented, the latter is possible but probably a significant amount of work. Or maybe you're looking for [frecency](https://en.wikipedia.org/wiki/Frecency)?

**Comment by The-Compiler** [comment]
Also see #601.

**Comment by Hi-Angel** [comment]
Yes, `most often visited` to the top.
