### ISSUE TITLE
Focused element is not editable

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#3159]
Disqus input boxes doesn't allow launching editor. E.g. calling editor with <kbd>C</kbd>-<kbd>e</kbd> [in a comment here](http://ergoemacs.org/emacs/xah_ban_emacs_irc.html) results in `Focused element is not editable`.

I've seen this behavior on non-disqus sites too. I haven't found this error been reported..

	$ qutebrowser-bin --version
	qutebrowser v1.0.1
	Git commit: 
	Backend: QtWebEngine (Chromium 56.0.2924.122)

	CPython: 3.6.2
	Qt: 5.9.2
	PyQt: 5.9

	sip: 4.19.3
	colorama: no
	pypeg2: 2.15
	jinja2: 2.9.6
	pygments: 2.2.0
	yaml: 3.12
	cssutils: no
	attr: 17.2.0
	PyQt5.QtWebEngineWidgets: yes
	PyQt5.QtWebKitWidgets: yes
	pdf.js: no
	sqlite: 3.20.1
	QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

	Style: Breeze::Style
	Platform: Linux-4.13.5-1-zen-x86_64-with-arch, 64bit
	Linux distribution: Arch Linux (arch)
	Frozen: False
	Imported from /usr/lib/python3.6/site-packages/qutebrowser
	Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

	Paths:
	cache: /home/constantine/.cache/qutebrowser
	config: /home/constantine/.config/qutebrowser
	data: /home/constantine/.local/share/qutebrowser
	runtime: /run/user/1000/qutebrowser
	system data: /usr/share/qutebrowser

**Comment by The-Compiler** [comment]
Those are non-standard rich text edits - qutebrowser doesn't (and can't) know in a general way how to convert that to plain- and back to rich-text.

**Comment by Hi-Angel** [comment]
@The-Compiler why did you close it? It's still a bug, isn't it?

**Comment by The-Compiler** [comment]
No, it's something impossible to solve (except with site-specific implementations, which I'd rather not do). You can't just edit a non-standard rich text thing in a text editor.

**Comment by Hi-Angel** [comment]
Ok, I don't know details, but I think it's possible to side-step by somehow copying the content from editor to the text-box. I mean, when I'm entering insert mode, I can type there. And I can paste text there too.

So, isn't it possible, for example, to somehow move the text from editor to such a textbox in a way it would've been moved through typing?

**Comment by The-Compiler** [comment]
Not in the general case. What if you have a rich text edit with e.g. bold text? How is that going to be represented in a plain text editor?

Interestingly dwb manages to do this for Disqus comments. That seems to be covered by #2545 though.

**Comment by The-Compiler** [comment]
I just noticed that #2329 is also related. Disqus is running in an iframe, so currently, all qutebrowser knows is that an iframe is focused.

**Comment by edrex** [comment]
Google Hangouts chat/contact list windows too.
