### ISSUE TITLE
Allow prompting for filename only on conflict

### ISSUE THREAD

**Issue by Enzime** [qutebrowser/qutebrowser#3160]
Change settings so that the filename/path can be modified instead of only prompting to overwrite the old file.

Also add a setting to resolve overwrite conflicts through sequential filenames.

**Comment by NoctuaNivalis** [comment]
I assume you mean for downloads? It could be useful to automatically pick a name so you can just hit enter, but I think we'd still need the prompt. It's important to confirm the download before starting it in case a website sends you downloads you might not want.

**Comment by The-Compiler** [comment]
@NoctuaNivalis There is `downloads.location.prompt` already to not display that prompt, which can be useful when launching many downloads after each other.

What @Enzime was talking about (I think) was better handling the case where a filename which already exists is entered. 

I'm merging this into #2103 as it's very similar.
