### ISSUE TITLE
Handle updates of spellchecking dicts

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3166]
Looks like the Chromium dicts were recently updated to 8.0: https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries.git/+/a9bac57ce6c9d390a52ebaad3259f5fdb871210e

`install_dict.py` should probably handle updates and remove older versions, and `spell.find_installed` should take the newest file by default, not just *any* file.

cc @elshize

**Comment by The-Compiler** [comment]
Hmm, wait, at least with `en-US-8-0` it looks like spell checking doesn't work at all?

**Comment by elshize** [comment]
I can investigate it/implement updates in a couple of weeks (I have an important conference deadline coming up this month, which keeps me very busy at the moment).

**Comment by The-Compiler** [comment]
Sure, no hurry! 👍

**Comment by elshize** [comment]
Would we still provide this script once it's also an internal command? I was thinking maybe the script should be called dict and have commands: install, update, list...

**Comment by The-Compiler** [comment]
Yeah, I suppose people will keep using Qt 5.8 and (especially) 5.9 for a while.
