### ISSUE TITLE
memory leak on unplayable youtube video

### ISSUE THREAD

**Issue by vandah** [qutebrowser/qutebrowser#3168]
While browsing the internet I came upon a link to a youtube video. Youtube said the video was unplayable with current setup. So I wanted to copy the URL and play it in a different browser. I pressed go and nothing happened. I tried o too but nothing again. The computer started to be less and less responsive and when I finally managed to switch to other tty and run htop. The qutebrowser was using loads of memory and the numbers kept growing.
The screenshot ilustrates memory usage of qutebrowser with only 2 or 3 open tabs.
![2017-10-19-213148_1920x1080_scrot](https://user-images.githubusercontent.com/13832239/31790739-ca695bca-b516-11e7-9918-42c4ee69eecb.png)

I've also heard from a friend that he came upon a similar issue with a regular youtube video so the problem might be connected with youtube videos.

Version info

qutebrowser v0.11.0
Git commit: 
Backend: QtWebKit-NG (WebKit 602.1)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: no
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.12.13-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
config: /home/vanda/.config/qutebrowser
data: /home/vanda/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/vanda/.cache/qutebrowser
download: /home/vanda/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment]
Is this something you can reproduce, or was it an one-time thing?

**Comment by vandah** [comment]
oh, I noticed a weird thing. I was searching for the video where the problem started and it was actually NOT on youtube. It was on vimeo.com
I tried opening it again and it does not cause problems now.
I have only been using the qutebrowser since yesterday evening so I can't really tell if this is a frequent issue but I will observe it and update this if I come up with a way to reproduce it.

**Comment by The-Compiler** [comment]
This is most likely an issue with either QtWebKit (used as default backend on v0.11) or GStreamer (which QtWebKit uses for video playback) and not qutebrowser itself, so I'm closing this now. If you find a way to reproduce it, let me know though, and I'll forward it to the QtWebKit maintainer.

You might also want to upgrade to qutebrowser v1.0 which is in the Arch repositories and uses QtWebEngine as backend by default, where this issue might not exist.
