### ISSUE TITLE
YouTube video inside iframe fails to fullscreen

### ISSUE THREAD

**Issue by Enzime** [qutebrowser/qutebrowser#3170]
When clicking on YouTube video links on imgur, the videos open within an iframe as opposed to in an external tab. Attempting to open the video in fullscreen mode fails.

Example: https://imgur.com/gallery/00L7Z

**Comment by jgkamat** [comment]
Hmm, this works for me, what backend are you on again?

```
qutebrowser v1.0.1
Git commit: v1.0.1-10-g08b562ea0 (2017-10-14 17:59:50 -0400)
Backend: QtWebEngine (Chromium 49.0.2623.111)
```

![2017-10-19-192959_1920x1080_scrot](https://user-images.githubusercontent.com/4349709/31798815-f8253ad8-b503-11e7-8dbc-126e7cf9515f.png)

![2017-10-19-193003_1920x1080_scrot](https://user-images.githubusercontent.com/4349709/31798816-faf47a80-b503-11e7-948c-ea7353508504.png)

**Comment by The-Compiler** [comment]
Works for me as well. What Qt version, backend and qutebrowser version?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by Enzime** [comment]
I just updated to git master it's working fine now.
