### ISSUE TITLE
Netflix videos don't work anymore

### ISSUE THREAD

**Issue by anhtuann** [qutebrowser/qutebrowser#3172]
I used to be able to watch netflix on qutebrowser but now there is an `Error Code: M7702-1003` (plugin out of date) telling me to update WidevineCDM for Chrome. Netflix still works fine with Firefox, Chrome and Chromium (the latter with widevineCDM plugin put in /usr/lib/chromium)

Is there a way to install that plugin in qutebrowser as well ?

version : 
qutebrowser v1.0.2
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)
CPython: 3.6.2
Qt: 5.9.2
PyQt: 5.9

**Comment by The-Compiler** [comment]
What distribution are you on, and how did you install qutebrowser? Can you try whether you get the same error with a 2.x version of [QupZilla](https://qupzilla.com/)?

**Comment by anhtuann** [comment]
I am using Arch and reading [that conversation on AUR about the issue](https://aur.archlinux.org/packages/qt5-webengine-widevine/). Same error with QupZilla 2.2.0 and QtWebEngine 5.9.2

**Comment by anhtuann** [comment]
After installing [qt5-webengine-widevine](https://aur.archlinux.org/packages/qt5-webengine-widevine/) it was fixed. So the problem isn't from qutebrowser but upstream. I am closing the issue

**Comment by The-Compiler** [comment]
I opened [QTBUG-64071](https://bugreports.qt.io/browse/QTBUG-64071) for this.

As a workaround, on Archlinux you can install [qt5-webengine-widevine](https://aur.archlinux.org/packages/qt5-webengine-widevine/) from the AUR and do `:set qt.args '["register-pepper-plugins=/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so; application/x-ppapi-widevine-cdm"]'` and `:restart` in qutebrowser.

**Comment by rolusterminus** [comment]
As of 12/14/2017, The-Compiler's fix above still works fine. Thank you much.

**Comment by d0ku** [comment]
As of 10/04/2018, still works.

**Comment by The-Compiler** [comment]
Out of curiosity, do you still need to set `qt.args` for it to work (with Qt 5.11) or does it also work without that?

**Comment by d0ku** [comment]
Firstly, I had set `qt.args` and `:restart` , everything worked. When I set `qt.args` to `[]` (my guess was it should set that value empty) and `:restart` everything still works fine. So i would say setting this option is not required anymore, however it would be nice, if someone confirmed that setting `qt.args` to `[]` resets that value.

**Comment by langurmonkey** [comment]
Just tested it. Works after installing `qt5-webengine-widevine` without the workaround.

**Comment by mcbloch** [comment]
Can still confirm, installing above mentioned aur package and doing `:restart` still works.

**Comment by mpgarate** [comment]
I found that `qt5-webengine-widevine` was [removed](https://www.mail-archive.com/aur-requests@archlinux.org/msg30653.html).

Instead, I was able to use netflix after installing the `chromium-widevine` package and restarting qutebrowser.

**Comment by marza91** [comment]
chromium-widevine works here as well, no need to set qt.args at all

**Comment by Yvar192** [comment]
Any fix for Ubuntu based system? The package mentioned here doesnt seem to exist

**Comment by The-Compiler** [comment]
@Yvar192 The [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc) has some install instructions at the bottom - though I'm not sure what Chromium/Widevine version you need to use, I guess it depends on what Ubuntu (and thus what Qt) version.

**Comment by Rockenstien** [comment]
There is new error popping out from Netflix now and i.e
Streaming Error
The title is not available to watch instantly (and that comes for every video i clickon and no my account is fine)
and I have the latest chromium widevine installed and i did set the qt.args . I really want to watch this netflix on this coolest browser

**Comment by d0ku** [comment]
Hi, can you share some more details about which versions you are using? `qutebrowser --version`
I am running 
```
qutebrowser v1.7.0
Git commit:
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.0
PyQt: 5.13.0

chromium-widevine 1:4.10.1440.18-2
```
on up-to-date ArchLinux and Netflix works without any errors whatsoever.

**Comment by Rockenstien** [comment]
I have exactly the same versions as you have mentioned but it doesn't seems to work.
I am getting this error code on netflix M7111-1331

**Comment by Rockenstien** [comment]
Well i don't have any file in my system named /usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so to set qt.args to. Is that causing the problem?****

**Comment by The-Compiler** [comment]
@Rockenstien Try not setting `qt.args` - it shouldn't be required anymore since Qt 5.11.1 or so.

**Comment by bsdb0y** [comment]
@The-Compiler Still not working. Netflix giving `Error Code: M7355`. I have installed Fedora 31 minimal:

uname -a
`Linux localhost.localdomain 5.3.7-301.fc31.x86_64 #1 SMP Mon Oct 21 19:18:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

QuteBrowser version and other info:

```
[xxxx@localhost ~]$ qutebrowser --version 
qutebrowser v1.8.1
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.5
Qt: 5.12.5
PyQt: 5.13.1

sip: 4.19.19
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.2
cssutils: 1.0.2 $Id$
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.30.0
QtNetwork SSL: OpenSSL 1.1.1d FIPS  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.3.7-301.fc31.x86_64-x86_64-with-fedora-31-Thirty_One, 64bit
Linux distribution: Fedora 31 (Thirty One) (fedora)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

```
I tried above mentioned workarounds but no luck, there is no qt-webengine-widevine and chromium-widevine.

**Comment by The-Compiler** [comment]
@bsdb0y Did you install QtWebEngine with proprietary codec support as mentioned in the [installation docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#on-fedora)?

**Comment by bsdb0y** [comment]
> @bsdb0y Did you install QtWebEngine with proprietary codec support as mentioned in the [installation docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#on-fedora)?

Actually, I am not sure as I haven't installed specificially QtWebEngine, manually or from command line. But, it seems that it came with the Qutebrowser installation.

```
[xxx@localhost ~]$ rpm -qR qutebrowser
((qt5-qtwebengine and python3-qt5-webengine) or (qt5-qtwebkit and python3-qt5-webkit))
/usr/bin/python3
python(abi) = 3.7
python3-PyYAML
python3-attrs
python3-jinja2
python3-pyPEG2
python3-pygments
python3-qt5
python3-qt5-webengine
python3-setuptools
python3.7dist(attrs)
python3.7dist(jinja2)
python3.7dist(pygments)
python3.7dist(pypeg2)
python3.7dist(pyyaml)
python3.7dist(setuptools)
qt5-qtbase
qt5-qtdeclarative
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rpmlib(RichDependencies) <= 4.12.0-1
``` 
So, do I need to reinstall the QtWebEngine manually from the mentioned doc?

**Comment by The-Compiler** [comment]
@bsdb0y Yes - you'll need both a working Widevine and a QtWebEngine with proprietary codec support.

**Comment by bsdb0y** [comment]
> @bsdb0y Yes - you'll need both a working Widevine and a QtWebEngine with proprietary codec support.

Sure, @The-Compiler and thanks. I will do it and update the status here.

**Comment by The-Compiler** [comment]
@bsdb0y If you need more help, consider [joining the IRC channel](https://github.com/qutebrowser/qutebrowser#getting-help) - your issue seems unrelated to this (which was an actual bug in QtWebEngine, back in 2017).

**Comment by bsdb0y** [comment]
yeah, sure. And, thanks for the information. My apologies, I thought I can report any netflix related issues, here.

**Comment by Nswayze** [comment]
> I found that `qt5-webengine-widevine` was [removed](https://www.mail-archive.com/aur-requests@archlinux.org/msg30653.html).
> 
> Instead, I was able to use netflix after installing the `chromium-widevine` package and restarting qutebrowser.

This still worked for me in 2020 :+1:
