### ISSUE TITLE
Rapid Hinting for Yank Target

### ISSUE THREAD

**Issue by NoSuck** [qutebrowser/qutebrowser#3174]
The error message says it "makes no sense", but any program that has a clipboard monitoring feature begs to differ!  Rapid yanking would be useful for loading links in a download manager (JDownloader 2, for example) without having to resort to `userscript` or `spawn`.  Users could also make quick URL lists using clipboard managers (parcellite, etc).

Please reconsider.

**Comment by The-Compiler** [comment]
Duplicate of #521

See https://github.com/qutebrowser/qutebrowser/issues/521#issuecomment-120906916

**Comment by NoSuck** [comment]
Thank you.  I saw that issue while searching but overlooked it on account of the title only mentioning modes.
