### ISSUE TITLE
Question regarding -s option

### ISSUE THREAD

**Issue by tempqute** [qutebrowser/qutebrowser#3183]
How do I use the -s option with options that don't have string values like let's say Dict for example.

I'm trying to do:

:-s url.searchengines { 'DEFAULT' : 'https://searx.abenthung.it?q=%21go%20{}&categories=non' } but it doesn't seem to work. Is it because of the first } from {} ?

**Comment by The-Compiler** [comment]
I'm assuming you're trying to launch qutebrowser from a shell like that? You'll need to quote the argument (i.e. `"{ 'DEFAULT' : 'https://searx.abenthung.it?q=%21go%20{}&categories=non' }"`) to prevent it being split (and the quotes being interpreted) by your shell.

**Comment by jgkamat** [comment]
As an example command:

`qutebrowser --temp-basedir -s url.searchengines "{'DEFAULT': 'google.com/{}'}"`

works fine for me. `{}` are interpreted by the shell.

**Comment by tempqute** [comment]
Ohh I should have tried that. Thanks.
