### ISSUE TITLE
I cannot change the minimum font size or the Monospace font

### ISSUE THREAD

**Issue by Hund** [qutebrowser/qutebrowser#3184]
I'm running qutebrowser v1.0.2 with QtWebKit (WebKit 602.1) on Arch Linux. And these settings does noting:

```
fonts.web.size.default_fixed: 13
fonts.web.size.minimum: 8
fonts.web.size.minimum_logical: 9
```

I have restarded the qutebrowser after changing the values.

**Comment by The-Compiler** [comment]
Like mentioned in IRC, they work fine if the website doesn't override them, e.g. on http://paste.the-compiler.org/view/raw/4b8229ed - so qutebrowser is passing them to QtWebKit/QtWebEngine correctly. I assume the website's stylesheet wins.

Setting `fonts.web.size.minimum` to 42 makes everything big though, even on websites - so it looks like everything is working fine.

**Comment by Hund** [comment]
Hm. `fonts.web.size.minimum` did work. I just needed to set it to a much higher value than I anticipated.
