### ISSUE TITLE
Sync protocol(Firefox Sync?)

### ISSUE THREAD

**Issue by schvabodka-man** [qutebrowser/qutebrowser#3188]
Are there any plans on implementing qutebrowser sync different from just syncing files with bookmarks/history/etc on all devices? Are there possibility to see the firefox sync client in qutebrowser(FS is open source, can be self-hosted and pretty nice documented)

**Comment by The-Compiler** [comment]
Duplicate of #485

**Comment by NoctuaNivalis** [comment]
I'm not a fan of dropbox, but perhaps there are open source alternatives. If there are, this is just a matter of symlinking those files to a files in the shared directory.

**Comment by jgkamat** [comment]
Some open source possibilities for syncing config are

- git repos
- [syncthing](https://syncthing.net/)
- [{own,next}cloud](https://nextcloud.com/)

**Comment by lahwaacz** [comment]
Speaking of syncing configs, there should be some auto-reload functionality to apply the new settings whenever git or syncthing or anything modifies the file.

**Comment by The-Compiler** [comment]
@lahwaacz see #155
