### ISSUE TITLE
Win7 VM aborts and flickering crash

### ISSUE THREAD

**Issue by luxpir** [qutebrowser/qutebrowser#3193]
Not sure what's happening, but on the latest release (v1.0.2) on a 64bit VM, trying both the 32 and 64bit installers, and the 64bit standalone I get a flickering crash on start. Sometimes even aborting the VM instance.

Recently upgraded to Win7's SP1 in VM so that the latest Python would install (think I saw it was the 32bit version) and did all reboots etc. to make sure we were up to date, so that I could install qutebrowser. Have already invested a bit of time, then, would like to see it through :)

The error log once read something about the init_profile on line 929 as the latest error.

EDIT: Here's the latest error:

```
Windows fatal exception: code 2147483651

Thread 0x00000914 (most recent call first):
  File "qutebrowser\utils\version.py", line 305 in _chromium_version
  File "qutebrowser\utils\version.py", line 321 in _backend
  File "qutebrowser\utils\version.py", line 331 in version
  File "qutebrowser\misc\crashdialog.py", line 228 in _gather_crash_info
  File "qutebrowser\misc\crashdialog.py", line 510 in _gather_crash_info
  File "qutebrowser\misc\crashdialog.py", line 244 in _set_crash_info
  File "qutebrowser\misc\crashdialog.py", line 472 in __init__
  File "qutebrowser\misc\crashsignal.py", line 98 in handle_segfault
  File "qutebrowser\app.py", line 464 in _init_modules
  File "qutebrowser\app.py", line 163 in init
  File "qutebrowser\app.py", line 137 in run
  File "qutebrowser\qutebrowser.py", line 186 in main
  File "qutebrowser\__main__.py", line 29 in <module>
```

**Comment by luxpir** [comment]
Uninstalled Python 32bit 3.6.3, installed 64bit 3.6 and restarted qutebrowser, got:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	qutebrowser.exe
  Application Version:	0.0.0.0
  Application Timestamp:	597f4a43
  Fault Module Name:	Qt5WebEngineCore.dll
  Fault Module Version:	5.9.1.0
  Fault Module Timestamp:	5953dcc8
  Exception Code:	80000003
  Exception Offset:	000000000015203e
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	16c1
  Additional Information 2:	16c1a9094c08c9aedef94a6cafd1950b
  Additional Information 3:	637c
  Additional Information 4:	637c8d452736e5f7b5f777e40bd7cf89
```

**Comment by luxpir** [comment]
Added Python to path then precompiled standard libs (through Programs > Change)...

Standalone and installed 64bit versions still flicker-die then give same error as above.

**Comment by The-Compiler** [comment]
Can you try a 2.x version of QupZilla and check whether you see the same issue please?

**Comment by luxpir** [comment]
QupZilla servers are *slow*! Can confirm it also flickers and crashes on launch. Then it doesn't let you taskkill /F or use the task man to kill it. Although it does render more of the browser window than Qute managed to...

**Comment by The-Compiler** [comment]
Looks like something wrong with QtWebEngine or the graphic drivers in that VM then - nothing qutebrowser can do about that.

Something you could try is going to `%APPDATA%\qutebrowser\config`, and creating a `config.py` file with `c.qt.force_software_rendering = True`. If that doesn't help, I'm pretty much out of ideas I'm afraid.

**Comment by luxpir** [comment]
Thanks for the suggestions and support - no dice on the config file option, so I'll check back in in a few weeks/months and hope for a solution!
