### ISSUE TITLE
no <EOL> in `:config-write-py --force` generated config.py

### ISSUE THREAD

**Issue by lxhillwind** [qutebrowser/qutebrowser#3195]
qutebrowser version: v1.0.2

Maybe it is better to add \<EOL\> at end of config.py.

I have read the source code of related file (I mean `qutebrowser/config/configfiles.py`), and find that `yield ''` is added at the end of `ConfigPyWriter._gen_header()` and `ConfigPyWriter._gen_options()`, but not `ConfigPyWriter._gen_bindings()`.

**Comment by mschilli87** [comment]
Wasn't this fixed already by https://github.com/qutebrowser/qutebrowser/pull/3196/commits/66c535098928785a2b88e33d314079a343aa1d36?

**Comment by The-Compiler** [comment]
Indeed, thanks!
