### ISSUE TITLE
Feature: Call userscript from authentication dialog

### ISSUE THREAD

**Issue by lucc** [qutebrowser/qutebrowser#3197]
Many websites use html forms for authentication and I can use a userscript to fill in my credentials from my password manager.

But some sites use HTTP Basic Auth and the authentication dialog of qutebrowser does not provide any comparable mechanism (I know of).

It would be nice to be able to launch a userscript from the dialog.  I think the input that the scipt needs would be at least the url that is beeing requested and probably also the parameters of the 401 reply (I only know the realm parameter of basic auth, but digest auth has some more parameters, but I think they are just technical to generate the correct reply).  Maybe also the payload of the 401 reply.

In order to allow the script to fill in the fields there should be some (new?) commands that the script can write to the QUTE_FIFO.

I think it is not possible to open the command line while in prompt mode so maybe we need a button on the prompt that will launch a preconfigured script (the user has to set some option with the script name). Or do any of you know of some other nice way?

(Or we could alternatively add an argument to `:open` in order to provide the credentials up front. Then I could write a userscript which would check the current url and search a password for it and open it with this password again. Then I would try to open the links first and if I am asked for a password I would abort and start my userscript)

**Comment by The-Compiler** [comment]
Things like this came up in the past already for other features - I'd like to avoid shoehorning everything into userscripts, and instead have a plugin API (see #30) capable of doing this kind of thing. This is especially true for authentication stuff, as we can then make sure the relevant plugin API calls are never logged, which is much harder with userscripts and commands.

**Comment by lucc** [comment]
I found that I can fabricate an url that will contain the auth information. It looks like this: https://user:password@domain.tl/path

Now until the plugin interface is available I can have a userscript that will find the relevant password for me and execute a `:open -p` with the new url.

**Comment by NoctuaNivalis** [comment]
Note that this *will* log your password in the command history & qb logs, so you might mail it to @The-Compiler accidently in a bug report, see #2865.
