### ISSUE TITLE
Useful "open" keyboard interaction suddenly missing.

### ISSUE THREAD

**Issue by Pete-Smith** [qutebrowser/qutebrowser#3198]
I upgraded to version 1.0.2 )(through pip) and noticed that I couldn't use the down arrow to scroll into my bookmarks from the O-key open menu. Down appears to do nothing from the ":open" prompt. The up arrow scrolls through the open commands that I have typed directly, the ones in my command history.

This was my go-to way of getting to my bookmarks quickly. Is there a newer, better way?

qutebrowser v1.0.2
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.3
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2g  1 Mar 2016

Style: QFusionStyle
Platform: Linux-4.13.0-16-generic-x86_64-with-Ubuntu-17.10-artful, 64bit
Linux distribution: Ubuntu 17.10 (ubuntu)
Frozen: False
Imported from /usr/local/lib/python3.6/dist-packages/qutebrowser
Qt library executable path: /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/libexec, data path: /usr/local/lib/python3.6/dist-packages/PyQt5/Qt

Paths:
cache: /home/petesmith/.cache/qutebrowser
config: /home/petesmith/.config/qutebrowser
data: /home/petesmith/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

**Comment by Enzime** [comment]
> `<Up>` and `<Down>` in the completion now navigate through command history instead of selecting completion items. Use `<Tab>`/`<Shift-Tab>` to cycle through the completion instead.

See: https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#migrating-older-configurations
