### ISSUE TITLE
Alert bar is displayed in all open windows

### ISSUE THREAD

**Issue by MarSoft** [qutebrowser/qutebrowser#3202]
Sorry if this is already reported, I could not find it.

When I open several `qutebrowser` windows and then try to navigate back the history in one of these windows, given there is no back history available in that window, I see the red bar in the bottom (just above statusbar) which reads `At beginning of history`.

The problem is, this bar appears simultaneously in **all** available windows, instead of just in the active one.
Probably this also applies to different situations when error bar is shown.

```
qutebrowser v1.0.2
Git commit: ed2f473a8 (2017-10-24 22:56:04 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.2
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.13.7-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/mars/.cache/qutebrowser
config: /home/mars/.config/qutebrowser
data: /home/mars/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```

**Comment by The-Compiler** [comment]
This is "intended": There are various places where an error happens which isn't clearly associated to a window - having a way to have some per-window and some global errors would introduce more complexity in a part of the code which is already surprisingly complex.
