### ISSUE TITLE
adblock-update filterlist no longer downloads

### ISSUE THREAD

**Issue by 0e0** [qutebrowser/qutebrowser#3214]
I used this filter list for a long time to block youtube ads
https://raw.githubusercontent.com/kbinani/adblock-youtube-ads/master/signed.txt

I keep qutebrowser updated and some time ago it stopped working, now whenever I try to :adblock-update it says
adblock: 5 read errors for adblock: raw.githubusercontent.com

I tried spoofing my user agent via :set content.headers.user_agent to generic user agents, but it didn't work so I thought maybe adblock-update does not respect the user_agent setting. I'm not sure.

**Comment by The-Compiler** [comment]
qutebrowser [does not support AdblockPlus like filerlists](https://github.com/qutebrowser/qutebrowser/issues/29) yet (and never has) - so I don't see how this could ever have worked.
