### ISSUE TITLE
Bigger pinned tabs

### ISSUE THREAD

**Issue by mkonig** [qutebrowser/qutebrowser#3226]
Currently pinned tabs only take minimum space and are not evenly spaced like normal tabs are. 
This is a wanted feature.
But it would be nice to have a setting so that pinned tabs have the same size as normal tabs.
To distinguish from normal tabs users can use the tabs.title.format_pinned setting to show different content in the tab title.

**Comment by The-Compiler** [comment]
cc @jgkamat
