### ISSUE TITLE
qutebrowser crashes when resizing window

### ISSUE THREAD

**Issue by ksalman** [qutebrowser/qutebrowser#3234]
I just installed qutebrowser 64 bit on Windows and it opens in a tiny window. When I try to maximize or change the window size in any way it crashes.  Here is a log
```
==== Fault log ====
Windows fatal exception: access violation

Current thread 0x00000738 (most recent call first):
  File "qutebrowser\app.py", line 148 in qt_mainloop
  File "qutebrowser\app.py", line 138 in run
  File "qutebrowser\qutebrowser.py", line 186 in main
  File "qutebrowser\__main__.py", line 29 in <module>


==== Timestamps ====
Launch: Thu Nov  2 08:23:26 2017
Crash: Thu Nov  2 08:23:28 2017

==== Version info ====
qutebrowser v1.0.2
Git commit: v1.0.2 (2017-10-17 07:44:14 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.1
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2h  3 May 2016

Style: QWindowsVistaStyle
Platform: Windows-7-6.1.7601-SP1, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 7, 6.1.7601, SP1, Multiprocessor Free

Paths:
cache: C:\Users\ksalman\AppData\Local\qutebrowser\cache
config: C:\Users\ksalman\AppData\Roaming\qutebrowser\config
data: C:\Users\ksalman\AppData\Roaming\qutebrowser\data
runtime: C:\Users\ksalman\AppData\Local\Temp\qutebrowser

==== Config ====
<Default configuration>

```

**Comment by The-Compiler** [comment]
This sounds like some kind of issue with Qt/QtWebEngine or your graphics driver, and is most likely not something qutebrowser can fix. Unfortunately, it's also really hard to debug this kind of issue on Windows...

Can you create a `C:\Users\ksalman\AppData\Roaming\qutebrowser\config\config.py` file with this:

```python
c.qt.force_software_rendering = True
````

and see whether that helps?

**Comment by ksalman** [comment]
I updated my graphics driver and still get the error with or without the config you mentioned. I guess I am out of luck?

**Comment by The-Compiler** [comment]
Out of curiosity, can you try running [QupZilla](https://qupzilla.com/) and check whether you see the same?

**Comment by ksalman** [comment]
Yea, same problem there.

**Comment by ksalman** [comment]
Is it possible to start the browser maximized? =) So I won't have to change the size, and hence not crash.

**Comment by The-Compiler** [comment]
I'm closing this then, as this doesn't seem like a qutebrowser issue.

At least on Linux, you can start with `--qt-arg geometry 1920x1080+0+0` as a commandline argument, but I have no idea whether that works on Windows too.

It's not possible to do the same via the config (I opened #3236 for that), but the main window remembers its size, so you should be fine after closing it once like that.
