### ISSUE TITLE
Can't open private window from command-line when there is already a non-private session

### ISSUE THREAD

**Issue by Larivact** [qutebrowser/qutebrowser#3239]
`qutebrowser -s content.private_browsing true` just opens a regular window when your session is non-private. Perhaps a command-line flag to open a private window could be introduced as other major browser also have one (`--incognito` for Chromium and `--private-window` for Firefox).

**Comment by lahwaacz** [comment]
The way to do this is `qutebrowser ":open -p"`, i.e. tell qutebrowser to open a private window instead of changing a global setting.

**Comment by Larivact** [comment]
Thanks.
