### ISSUE TITLE
Feature to Suggest Keybindings when running them manually 

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#3241]
Emacs has a variable called `suggest-key-bindings`, which display a message like "You can run the command <cmd> with <keys>" when you run commands manually with M-x.

I think it would be nice if qb could display a message like this when running commands from the `:` interface, to help train people to available keys.

I have not looked at this too much, but I think it might be a good beginner issue.

Does anyone have any thoughts? :smile:

```
<cryzed> The-Compiler, here's a random idea: a tutor mode [03:26 PM]
<cryzed> each time someone uses a command for which there is a keybinding
<cryzed> maybe qute could say "hey, you could actually also just do this:"
<jkamat> cryzed: that would be fairly easy to do actually (I think), via the
		 message system :D  [03:27 PM]
<cryzed> jkamat, tell me when you are done :^)
<cryzed> PyCharm has something like that, as a plugin
```

**Comment by The-Compiler** [comment]
Not sure about this - the key bindings showing up in the command completion already seem to help with this enough, and this seems rather annoying to me. @rcorre what do you think?

**Comment by jgkamat** [comment]
Oh, I completely forgot about the keybinds showing up during completion. I guess this would be rather redundant, so I guess this isn't necessary at all. @cryzed do you have any other comments? :P

**Comment by rcorre** [comment]
I think the hints in command completion are enough, though you don't get to see any bindings with flags, or bindings that use `set-cmd-text`. For example, `open` doesn't show as bound to `o`. Still, I'd say a user will notice they are repeating the same command and either check if there is an existing binding or make their own.

**Comment by jgkamat** [comment]
I'm closing this, since I don't think anyone would want it, sorry!
