### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by Zekario** [qutebrowser/qutebrowser#3246]
I'm using version 1.0.2 on Arch Linux.
I'm getting discrepancies in how fonts are rendered between [qutebrowser (bad)](https://transfer.sh/k20XZ/2017-11-05%2007:10:11.png) and [palemoon (good)](https://transfer.sh/Eqlg1/2017-11-05%2007:10:21.png). I *think* this may be because qutebrowser is using fonts given by the website instead of using local ones. Is there a way to make it use only local fonts?

**Comment by The-Compiler** [comment]
You can try `:set qt.args "['disable-remote-fonts']"` to avoid loading web fonts, or play with the `fonts.web.family.*` settings.

If that doesn't help, there's probably not much qutebrowser can do here, as font rendering is handled by the backend (QtWebEngine/QtWebKit).
