### ISSUE TITLE
Make pastebinning version easier

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3256]
`qute://version` could have a pastebin button, and there could be `:version --paste` or so too. Since code to create a paste already exists, this should be relatively straightforward.

**Comment by cbarillas** [comment]
Hello, I am new to contributing to open source projects and would like to help.  How can I help?

**Comment by The-Compiler** [comment]
@cbarillas Welcome! 🎉  This issue requires a bit of JavaScript knowledge (plus a basic grasp of how Qt [signals and slots](http://doc.qt.io/qt-5/signalsandslots.html) work).

If that's not your cup of tea, I'd recommend looking at e.g. #3230 or #3213 which should be more straightforward.

If you haven't yet, I first recommend getting qutebrowser to run on your system, ideally from a git clone. The [instructions here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-qutebrowser-with-tox) are a good start. Then I think it's important to understand what the issue you're working on is about exactly, so play with the related functionality a bit, and if something is unclear, please ask!

You might also want to take a look at the [contribution docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/contributing.asciidoc) - no need to understand everything right away, but there are some helpful hints in there. Finally, I'd recommend you join the [IRC channel](https://github.com/qutebrowser/qutebrowser#getting-help) so you have an easy way to communicate with other developers and ask questions if necessary.

With all that out of the way, work on whatever issue you'll go for (ideally in a separate git branch), and then submit a pull request - check [this guide](https://opensource.guide/how-to-contribute/) for some other information on how to get started.

Hope that helps! If there's anything unclear, feel free to ask! :wink:

**Comment by gebulmer** [comment]
Oh hey this could be closed now

**Comment by The-Compiler** [comment]
Indeed - thanks @gebulmer and @Transfusion! 👍 

@gebulmer For the future, note that you [can mention](https://help.github.com/articles/closing-issues-using-keywords/) something like `Closes #3256` in the body of your PR so issues get auto-closed when it's merged. 😄
