### ISSUE TITLE
Adding a Reader mode

### ISSUE THREAD

**Issue by schvabodka-man** [qutebrowser/qutebrowser#3267]
Are there any plans to add "reading mode" to browser? You know when browser renders page pretty minimalistic and without distractions. Such thing [already exists in qupzilla](https://github.com/QupZilla/qupzilla-plugins/wiki/Readability) which runs on qtwebengine too, so technically this can be done.

**Comment by jgkamat** [comment]
I think that you are looking for the [readability userscript](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/readability), which does what you want. You'll need to set up dependencies properly to use it though.

**Comment by The-Compiler** [comment]
Yeah, this is definitely something for an userscript or a future plugin API.
