### ISSUE TITLE
config.bind() is possibly interfering with a command's quotation marks

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#3274]
qutebrowser v1.0.3
Git commit: af93c0fbc (2017-11-04 17:15:20 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)

Userscript named `shellrun-test`:
```
#!/bin/sh
echo $@ | sh
```

We will test a command using this to see if config.bind eats quotation marks.

The command we will test is `spawn -u shellrun-test echo "message-info \'hello there\'" >> $QUTE_FIFO`

- When I run this directly in the qutebrowser commandline, it correctly shows an info message saying 'hello there'.
- When I bind this directly in the qutebrowser commandline (by running `bind ,x spawn -u shellrun-test echo "message-info \'hello there\'" >> $QUTE_FIFO`) and press the binding ',x', it also correctly shows this info message.
- When however I bind this in the config.py file (by putting in the file `config.bind(',x', 'spawn -u shellrun-test echo "message-info \'hello there\'" >> $QUTE_FIFO')`) and press the binding ',x', it doesn't show the info message and instead shows an error message `message-info: Unrecognized arguments: there`.

This error message is shown also when you run the command without the double-quotation marks: `spawn -u shellrun-test echo message-info \'hello there\' >> $QUTE_FIFO`, so perhaps config.bind is removing them somehow? Even though running 'bind ,x' shows the bound command still has the double-quotation marks.

**Comment by lahwaacz** [comment]
It's not `config.bind` that "eats the quotes", but Python itself. You need to either double-escape the backslashes (i.e. `\\'...\\'`) or use [raw strings](https://stackoverflow.com/a/2081708/4180822) (i.e. `config.bind(',x', r'spawn -u shellrun-test echo "message-info \'hello there\'" >> $QUTE_FIFO')`).

**Comment by pkillnine** [comment]
thanks that was the problem

**Comment by pkillnine** [comment]
just to note: passing r'<command> fixes this issue, but escaping the double-qutotation marks with two `\`'s  doesn't fix this for me, this could potentially be a bug

**Comment by The-Compiler** [comment]
You must've done a mistake somewhere then - the escaping is done by Python before qutebrowser ever sees the string, and those two things (i.e. `r'foo\"bar'` and `'foo\\"bar'`) result in the exactly same string.
