### ISSUE TITLE
Cannot create platform OpenGL context, neither GLX nor EGL are enabled

### ISSUE THREAD

**Issue by alem0lars** [qutebrowser/qutebrowser#3276]
## Failed to start qutebrowser

I've installed qutebrowser 1.0.3. When I try to start the application, the frame is shown but it cannot display any contents.

It outputs a lot of the following messages:

```
15:52:56 WARNING: QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
15:52:56 WARNING: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
```

I'm using NVidia discrete graphics card and Gentoo Linux with Qt5.

## qutebrowser version

```
qutebrowser --version
15:52:56 WARNING: QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
15:52:56 WARNING: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
qutebrowser v1.0.3
Git commit:
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.4
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 16.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.19.3
QtNetwork SSL: OpenSSL 1.0.2m  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.12.12-gentoo-x86_64-Intel-R-_Core-TM-_i7-4710MQ_CPU_@_2.50GHz-with-gentoo-2.4.1, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib64/python3.5/site-packages/qutebrowser
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/alem0lars/.cache/qutebrowser
config: /home/alem0lars/.config/qutebrowser
data: /home/alem0lars/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
```

**Comment by The-Compiler** [comment]
This is most likely an issue with your system or graphics driver - can you check whether you see the same with [QupZilla](https://qupzilla.com/) as well? Also, can you show the output of `glxinfo -B`?

**Comment by alem0lars** [comment]
`optirun glxinfo -B` gives:

```
optirun glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: Quadro K2100M/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 384.90
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5.0 NVIDIA 384.90
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
```

**Comment by The-Compiler** [comment]
What about QupZilla?

**Comment by alem0lars** [comment]
Gives the same problem of qutebrowser

___________________
*Alessandro Molari*

**Comment by The-Compiler** [comment]
Doesn't look like there's anything qutebrowser can do here then. If you did a nvidia driver update lately, make sure you rebooted since then.

Other things you could try is creating a `~/.config/qutebrowser/config.py` with `c.qt.force_software_rendering = True` to enforce software rendering, or `c.backend = 'webkit'` to use the QtWebKit backend (with [this ebuild](https://gist.github.com/annulen/309569fb61e5d64a703c055c1e726f71)).

**Comment by maxf130** [comment]
I just came accross exactly this problem.  In my case I forgot to make my user a member of the 'video' group.

`usermod -a -G video max` 

solved the problem in my case.

**Comment by Ambrevar** [comment]
In my case with a GeForce GT 520M, switching from Nouveau to the proprietary blob worked.

**Comment by jameh** [comment]
leaving this here for anyone else who was on a treasure-hunt for why qutebrowser and nvidia weren't playing nicely. https://bugs.archlinux.org/task/53704 (FTR, other apps were also saying things like BadWindow, couldn't get GLX context)

In my case, the wrong libglx.so was being loaded by the X server, the solution being to point the X server to the libglx.so file provided by the nvidia driver.

**Comment by ilamin** [comment]
Try  installing qt5-linguist
Ubuntu: sudo apt-get install qt5-linguist
Fedora: sudo dnf install qt5-linguist

**Comment by The-Compiler** [comment]
@ilamin qt5-linguist is a tool to manage translation files - this seems completely unrelated to this issue.

**Comment by ilamin** [comment]
Sorry wrong post

**Comment by carlosdelfino** [comment]
I'm having the same problem, and the 3 issues (#3276, #2, #3566) that deal with this theme couldn't help me, I'm having problems with GitBook and Caliber, I use Ubuntu 20.04.

Does anyone have any more ideas on what can be resolved?

**Comment by carlosdelfino** [comment]
resolved when I installed the following packages:

* build-essential
* libgl1-mesa-dev 
* libsdl2-dev
* libfontconfig1
* dbus-x11
* xvfb

**Comment by keithel** [comment]
In case anyone else runs into this scenario (I didn't run into it with the qutebrowser, but another Qt app), this situation can also occur if the `egldeviceintegrations` and/or `xcbglintegrations` plugins are not present in the Qt plugins dir.
