### ISSUE TITLE
File Handlers and Autospawn

### ISSUE THREAD

**Issue by peterjschroeder** [qutebrowser/qutebrowser#3277]
Is there a way to autospawn a program based on a filetype or url?

Examples:

mpv automatically opens url when visiting sites such as youtube.
mailto launches mutt
magnet and torrent links open in transmission-cli
images open in feh
pdfs open in zathura
downloads send to aria2
audio and videos open in mpv

**Comment by The-Compiler** [comment]
If you press `ctrl-x` in the download prompt, the file gets opened via `xdg-open`. As for magnet links, see #2833. Automatically opening stuff outside of downloads sounds like something for a plugin, see #30.

**Comment by peterjschroeder** [comment]
These options happen after clicking the link and require more input by the user.

What I'm looking for is for the link to be intercepted on click and the url passed to the spawn command.

Example:

Something like this in the user's config.

iclick '([-\w]+\.(?:jpg|gif|png))' 'spawn rxvt-unicode feh {url}'

Now in the browser when a jpg, gif, or png link is clicked, the url would be passed to feh for viewing and will do nothing else with the click as the objective is complete.

Link intercepting would cover some instances where plugins would normally be used.

I am currently familiarizing my self with the code to see if I can imp this myself. It should just be a matter of loading all the iclicks from the config into an array. Than finding where the clicking of links happen, check such links against the array, and issue the spawn.

**Comment by jgkamat** [comment]
@peterjschroeder 

I *think* that what you're referring to can be acheived by a userscript.

@pkill9's userscript here comes close to what you want (if I'm understanding it correctly):https://gist.github.com/pkillnine/c730ee294d8c3729209b2d654b53576c

**Comment by peterjschroeder** [comment]
From what I understand of the userscripts, you have to manually execute them.

I found this in the bug reports

https://github.com/qutebrowser/qutebrowser/pull/1155

That is what I'm looking for.

**Comment by The-Compiler** [comment]
> That is what I'm looking for.

See #35 for the related issue.

> Files, I still have to ctrl-x to open (no option to always open?).

That's definitely not going to happen before there are per-domain settings, as it's a security risk otherwise.
