### ISSUE TITLE
Command to temporary disable user css

### ISSUE THREAD

**Issue by schvabodka-man** [qutebrowser/qutebrowser#3282]
Hello. Sometimes there are need in disabling user css temporary, for one site. Can it be made as qutebrowser command(:disable-user-css or something like that), because, sometimes you just need to see "vanilla" version of site without your personal css and disabling it every time in config.py is annoying?

**Comment by The-Compiler** [comment]
You can just do something like `:config-cycle content.user_stylesheets foo.css "" ;; reload'`.
