### ISSUE TITLE
Support linewise scrolling with <C-e> and <C-y> by default

### ISSUE THREAD

**Issue by rlue** [qutebrowser/qutebrowser#3283]
Didn't see any open requests for this particular feature (although admittedly, I only looked cursorily).

Is there any reason these are not available, when `<C-f>` / `<C-b>` / `<C-d>` / `<C-u>` are?

**Comment by The-Compiler** [comment]
Mainly because a website can't really be split up in lines easily :wink:

It looks like Vimperator ignores those bindings altogether, while Chromium + Vimium handle it like `jk`. You can do `:bind <ctrl-e> scroll down` (and the same for `ctrl-y`) to get the same in qutebrowser.

**Comment by rlue** [comment]
Thanks!
