### ISSUE TITLE
HTTPS -> HTTP link on qutebrowser.org

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3289]
On https://qutebrowser.org/, all links in the header use HTTPS except http://blog.qutebrowser.org/ where HTTP is hardcoded. You can use a [protocol-relative URL](https://en.wikipedia.org/wiki/URL#Protocol-relative_URLs) like `//blog.qutebrowser.org/`.

**Comment by The-Compiler** [comment]
There's really no reason to link to `http://` either way, so I moved all qutebrowser.org links to https://. Some day I'll also get around setting up [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) on my server :wink:

**Comment by SirCmpwn** [comment]
Bumping this as http://qutebrowser.org still does not redirect to https://qutebrowser.org
