### ISSUE TITLE
Crash Loading Pages

### ISSUE THREAD

**Issue by reedjosh** [qutebrowser/qutebrowser#3292]
I'm running Sway on Arch Linux

I tried to report this via the automatic bug dialog system, but when trying to send the report it crashes again.

Here's the log that's generated in the auto-report dialog (that I can't send).

[log](https://gist.github.com/reedjosh/eff39235cc2a7e67f156a1dac9420a4b#file-qutebrowser-crash-log)

The crash occurs when following a hint. Sometimes the whole page will load, but then crash. Other times it will crash almost immediately.

This seems to occur most in my school's Canvas pages. Typically when there's a video on the page, but the bug still seems random enough that I haven't been able to determine if the correlation is 100%.

When ran from a console, I get an output that says segfault and then the crash occurs.

Version Info.
```
qutebrowser v1.0.3
Git commit: e72e8b855 (2017-11-14 13:29:58 +0100)
Backend: new QtWebKit (WebKit 602.1)

CPython: 3.6.3
Qt: 5.9.2
PyQt: 5.9.1

sip: 4.19.5
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.13.12-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/jreed/.cache/qutebrowser
config: /home/jreed/.config/qutebrowser
data: /home/jreed/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

This browser is SO great, but I'm almost to the point of installing a back-up to get homework done. : (

Thanks for your support, and the great browser. Please let me know if you need further information.

**Comment by reedjosh** [comment]
Additional info... I've since stopped setting the backend to use wayland. It now freezes instead of seg faulting. I'm not sure how to get logs for this.

**Comment by The-Compiler** [comment]
Those kind of things are usually issues with e.g. graphic drivers unfortunately.

I don't really understand what you mean here:

> I've since stopped setting the backend to use wayland. It now freezes instead of seg faulting.

Your crash logs say that you're using QtWebKit, but QtWebEngine is the default. However, only QtWebKit works natively with wayland.

Can you please...

- See if you have the same kind of issues with [Otter Browser](https://github.com/OtterBrowser/otter-browser) (QtWebKit) and [QupZilla](https://qupzilla.com/) (QtWebEngine)? They're packaged as `otter-browser` (AUR) and `qupzilla` (community).
- Show the output of `glxinfo -B` (part of `mesa-demos`)
- Get a [C++ stacktrace](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc)? Even one without the debug packages would most likely be useful, but if you can spare the disk space, it'd be nice if you can install them first.

**Comment by reedjosh** [comment]
Hey, what I meant was I unset the environment variable QT_QPA_PLATFORM=wayland. Previously I was exporting it in my zshrc before starting sway. Now the setting is blank.

I will try to get you info on the things you've requested shortly. Thanks for your quick response.

**Comment by reedjosh** [comment]
Okay, I've got some of your requested info.

`glxinfo -B`

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)  (0x1916)
    Version: 17.2.5
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 17.2.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 17.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```
Man Otter took a while to build. : (

Packages added by Otter Browser PGKBuild
- qt5-multimedia (package found)
- qt5-svg (package found)
- qt5-tools (package found) [makedepend]

Same freezing behavior as qutebrowser.

I've found a link that will always cause the issue.
https://oregonstate.instructure.com/courses/1681426/files/68170692/download?wrap=1
In Waterfox this redirects to a Canvas site message stating I don't have permissions to access this file. 

While this link will always cause a crash/freeze, it is not the only link type that causes it. Perfectly normal pages that do actually work on Waterfox will cause the same issue, but I haven't found one that will do it every time yet. 

Also I have to kill qutebrowser and otter via `pkill -9 browser`. A normal kill message doesn't get acknowledged.

**Wow!!!** Qupzilla Handles the page fine! So... I don't know that Qupzilla has this issue. 
I've navigated around Canvas a bit with it and have had no issues.

Stack trace to follow...

**Comment by reedjosh** [comment]
So... I've installed your debug packages, and I've ran gdb as requested. Unfortunately qutebrowser doesn't open when I do that, and gdb hangs. 

```
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.6...(no debugging symbols found)...done.
Starting program: /usr/bin/python3.6 -m qutebrowser --debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
11:37:49 DEBUG    init       earlyinit:init_log:260 Log initialized.
```
I then have to kill gdb using `pkill -9 gdb`.

Could you please advise me as to what I'm doing wrong? I will try to research this myself in the meantime.

**Comment by The-Compiler** [comment]
Stuff runs much slower inside gdb, so it's entirely possible it takes a couple of minutes to start. I wouldn't expect it to take longer than 5 minutes though.

If this doesn't work out, can you please do this instead?

- Do `sudo coredumctl list` and find the PID of the latest crash (with python3.6) - use Shift-G to get to the bottom.
- Do `sudo coredumpctl info PID` with the PID from above and show the output.

**Comment by reedjosh** [comment]
Cool, I'll try letting it run for a while to see if qutebrowser eventually starts up. Otherwise, I'll look into coredumpctl.

**Comment by reedjosh** [comment]
So new problem. Let it run long enough and it does eventually start. Unfortunately it just freezes now and I can't get it to crash. 

I tried switching back QT_QPA_PLATFORM=wayland and it still just freezes. 

Since I'm not able to get it to crash anymore, I'm not sure how to get you the GDB output as the freeze freezes GDB as well. The only way I can then close qutebrowser is to kill -9 GDB. : (

**Comment by The-Compiler** [comment]
Can you press ctrl-c in gdb (which should hopefully give you a `(gdb)` prompt), and do `bt` there? Also, can you show the `coredumpctl info` output for one of the past crashes as well?

**Comment by reedjosh** [comment]
Mr. Compiler, how are you so awesome anyway!? 

So, with the qt env var set to wayland, qutebrowser crashes in gdb immediately. I will try to get you the trace for this with and without the variable set, but for now I've gotta run. Will probably be sometime tomorrow.

For now I've got the output of all recent core dumps involving python3.6. 

You can see the amalgam of them [here](https://gist.github.com/reedjosh/b95e2385f4772fa12af4dadc180e5768)... 

The pids correspond to the below output of `sudo credumpctl list | grep python3`
 
```
Sun 2017-11-12 18:28:21 PST    7964  1000  1000   6 present   /usr/bin/python3.6
Sun 2017-11-12 18:31:31 PST    4009  1000  1000   6 present   /usr/bin/python3.6
Sun 2017-11-12 18:31:38 PST    4230  1000  1000   6 present   /usr/bin/python3.6
Tue 2017-11-14 12:50:16 PST   15666  1000  1000  11 truncated /usr/bin/python3.6
Tue 2017-11-14 12:50:33 PST   19046  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 12:50:57 PST   19683  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 12:51:13 PST   20108  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 12:51:38 PST   20667  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 12:51:50 PST   21028  1000  1000  11 truncated /usr/bin/python3.6
Tue 2017-11-14 12:53:13 PST   23019  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 13:12:40 PST     647  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 13:52:20 PST   24733  1000  1000  11 truncated /usr/bin/python3.6
Tue 2017-11-14 13:59:56 PST   30247  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 14:57:28 PST   16893  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 14:57:38 PST   29176  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 14:57:42 PST   29319  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 14:58:55 PST   31188  1000  1000   6 present   /usr/bin/python3.6
Tue 2017-11-14 15:02:17 PST   32212  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 15:05:23 PST    4016  1000  1000  11 present   /usr/bin/python3.6
Tue 2017-11-14 15:10:37 PST    9317  1000  1000  11 present   /usr/bin/python3.6
```
Thanks again!

**Comment by reedjosh** [comment]
Okay... I've got the gdb outputs.
 
With force wayland set.

```
17:25:10 DEBUG    message    message:set_text:261 Follow hint...
17:25:10 DEBUG    statusbar  text:set_text:57 Setting normal text to 'Follow hint...'.
17:25:10 DEBUG    modes      modeman:enter:234 Entering mode KeyMode.hint (reason: HintManager.start)
17:25:10 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: True, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=2 url='https://oregonstate.instructure.com/courses/1669158/pages/week-7-carbon-sequestration-and-climate-c…'>)
17:25:10 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
[New Thread 0x7fff167ff700 (LWP 29495)]
[New Thread 0x7fff15ffe700 (LWP 29496)]
[New Thread 0x7fff157fd700 (LWP 29497)]
[New Thread 0x7fff14ffc700 (LWP 29498)]
[New Thread 0x7ffefe774700 (LWP 29499)]
[New Thread 0x7ffefdf73700 (LWP 29500)]
[Thread 0x7ffefdf73700 (LWP 29500) exited]
17:25:11 DEBUG    js         shared:javascript_log_message:136 [https://pa.tedcdn.com/javascripts/libs.js?3c2b34f3461ab898578d8832e06af9fb:5] Blocked a frame with origin "https://embed.ted.com" from accessing a frame with origin "https://oregonstate.instructure.com". Protocols, domains, and ports must match.

Thread 1 "python3.6" received signal SIGSEGV, Segmentation fault.
0x00007fffe980f88e in XDefaultDepth ()
   from /usr/lib/libX11.so.6

```
[gdb.txt with wayland set](https://gist.github.com/reedjosh/b95e2385f4772fa12af4dadc180e5768#file-gdb_w_wayland_set-txt)






Without wayland set.



```
17:39:39 DEBUG    keyboard   basekeyparser:_debug_log:108 Definitive match for 'hl'.
17:39:39 DEBUG    keyboard   basekeyparser:_debug_log:108 discarding keystring 'hl'.
17:39:39 DEBUG    hints      hints:handle_partial_key:767 Handling new keystring: ''
17:39:39 DEBUG    hints      hints:handle_partial_key:767 Handling new keystring: 'hl'
17:39:39 DEBUG    modes      modeman:leave:296 Leaving mode KeyMode.hint (reason: followed)
17:39:39 DEBUG    statusbar  text:maybe_reset_text:70 Resetting: 'Follow hint...'
17:39:39 DEBUG    statusbar  text:set_text:57 Setting normal text to ''.
17:39:39 DEBUG    webelem    webelem:click:392 Clicking <qutebrowser.browser.webkit.webkitelem.WebKitElement html='<a class="" title="Global_Issue_Paper.pdf" href="https://oregonstate.instructure.com/courses/1681426/files/68170692/download?wrap=1" data-api-endpoint="https://oregonstate.instructure.com/api/v1/courses/1681426/files/68170692" data-api-returntype="File">Rangelands and Global Change</a>'> with click_target ClickTarget.normal, force_event False
17:39:39 DEBUG    webelem    webelem:click:400 Clicking via JS click()
17:39:39 DEBUG    webview    webpage:acceptNavigationRequest:450 navigation request: url https://oregonstate.instructure.com/courses/1681426/files/68170692/download?wrap=1, type NavigationTypeLinkClicked, target ClickTarget.normal override None
17:39:39 DEBUG    webview    browsertab:_set_load_status:689 load status for <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=2 url='https://oregonstate.instructure.com/courses/1669158/pages/week-7-carbon-sequestration-and-climate-c…'>: LoadStatus.loading
17:39:39 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed('loading') (tab 2)
17:39:39 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_started() (tab 2)
17:39:39 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
17:39:39 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.hint (reason load started) as we're in mode KeyMode.normal
17:39:39 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: True, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=2 url='https://oregonstate.instructure.com/courses/1669158/pages/week-7-carbon-sequestration-and-climate-c…'>)
17:39:39 DEBUG    misc       app:on_focus_object_changed:830 Focus object changed: <qutebrowser.browser.webkit.webview.WebView tab_id=2 url='https://oregonstate.instructure.com/courses/1669158/pages/week-7-carbon-sequestration-and-climate-c…'>
17:39:39 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
17:39:39 DEBUG    save       savemanager:mark_dirty:71 Marking cookies as dirty.
[Thread 0x7fff5b7fe700 (LWP 4412) exited]

^C
Thread 1 "python3.6" received signal SIGINT, Interrupt.
0x00007ffff78f2e79 in syscall () from /usr/lib/libc.so.6

```

[gdb.txt without wayland set](https://gist.github.com/reedjosh/b95e2385f4772fa12af4dadc180e5768#file-gdb_wo_wayland_set-txt)

**Comment by The-Compiler** [comment]
Thanks!

Time for some dedective work! :wink: I see at least three different issues here - unfortunately, qutebrowser can't do anything about those...

- The freeze without wayland platform is in `gst_element_change_state` which smells like this QtWebKit/GStreamer issue: https://github.com/annulen/webkit/issues/487 - right now the only fix is either removing `libgsthls.so` from your system (or removing `gst-plugins-bad` entirely), or using QtWebEngine instead.
- The crash with wayland platform is in `QtWaylandClient::QWaylandShmBackingStore::resize()` -> `QImage::constBits()`, which sounds like [QTBUG-63862](https://bugreports.qt.io/browse/QTBUG-63862). I've only seen it happen with sway (not with e.g. Weston), and it might go away once sway uses its own wlroots library instead of wlc: https://github.com/swaywm/sway/issues/1390
- There's a third thing there, probably the crash (rather than freeze) you mentioned without wayland platform. It happens right on startup in `QGuiApplicationPrivate::createPlatformIntegration()` -> `QMessageLogger::fatal()`, i.e. Qt terminated after printing some fatal error message. My guess would be that was when you did run it without `QT_QPA_PLATFORM` set, but without a `DISPLAY` available - but if it ever happens again, the message in the terminal should tell you more.

So yeah, your options are pretty much this:

- Use QtWebKit with XWayland (i.e. without setting the wayland platform), and delete `libgsthls.so`
- Use QtWebEngine with XWayland
- Don't use sway (I know, not really an option :wink:)

**Comment by reedjosh** [comment]
Haha, I was afraid this might be the case. I've logged a bug with Sway (unrelated to this) about two weeks back, and it seems they're mostly not addressing bugs atm because they're waiting for wlroots. 

Seems most of my favorite platforms are in flux. : (

Thanks again for your continued work! I will explore the options available to me.
