### ISSUE TITLE
Add 'always rapid hints' mode

### ISSUE THREAD

**Issue by mkonig** [qutebrowser/qutebrowser#3298]
As a reader of news on the web
I want to be able to browse through many sites without the need of continously pressing 'f'

Currently there is rapid hinting in new tab and new window.
It would be amazing if there would be a kind of rapid hinting in the same tab.
It means the user starts hinting mode and this mode is not left until the user tells so.
In the UI it would mean that after selecting a hint the appropriate action is taken and then hints are
immediately shown again.

**Comment by The-Compiler** [comment]
Merging this into #521.
