### ISSUE TITLE
Using mouse to change fields in Google SPreadsheet while in insert mode makes QB revert to normal mode (using arrow keys does not)

### ISSUE THREAD

**Issue by krzemian** [qutebrowser/qutebrowser#3303]
1. Open https://docs.google.com/spreadsheets/d/1MPjRnFJc_bhom8vGOxGpSh93cWk_ersYXFipvSxs-jY/edit?usp=sharing
2. Focus selection on any a cell
3. Enter insert mode
4. Navigate with arrow keys/keyboard - see it stays in insert mode
5. Use mouse to navigate by clicking on an inactive cell - see it switches to normal mode.

From my experience 5. is counterintuitive and staying in the insert mode would be the preferred way.

Using qb v1.0.3

**Comment by jgkamat** [comment]
I think this can be fixed by `:set input.insert_mode.auto_leave false`

**Comment by NoctuaNivalis** [comment]
It does. If you don't want to use this setting: I usually triple-click on the cells. IIRC the input field is dynamically placed when you click the second time, so we can't really detect it before that.

**Comment by pkillnine** [comment]
This is a comon issue with javascript-heavy webapps. These kinda situations are what passthrough mode (`ctrl-v`) is good for.
