### ISSUE TITLE
Assigning commands to number keys

### ISSUE THREAD

**Issue by betamint** [qutebrowser/qutebrowser#3307]
I'm trying to assign commands to number keys. While the assignment was successful (I guess, since there's no error message in :messages), I can't invoke those commands except that one binded to 0.

Te be specific, I have this in config.py
```python
config.bind('9', 'tab-prev')
config.bind('0', 'tab-next')
```
what I get from pressing 9: count is now 9
what I get from pressing 0: switch to next tab

It seems count override command, and initial 0 doesn't trigger count so it triggers command.

I'm not sure this is intended or not, but since it's possible to assign commands to number keys, it's odd that they can't actually be invoked.

Perhaps it's better to have number keys to do what they are binded to if they are explicitly binded. This will make it impossible to set count to certain numbers (9p will not do p 9 times, if 9 is binded, or if 9p is binded†), and number keys can't be counted (89 should mean "set count to 89" instead of "do what  key 9 is binded to 8 times", if 9 is binded and 8 not). However, these two inconsistensies should not be a problem, but rather a trade-off, for those who are binding number keys.

† In the case of binding 9p as a whole, I don't think it's a good idea and it's not my use case. It's confusing, but as I said, there's a trade-off (who knows what you're dealing with if you're binding 9p?)

version info
```
qutebrowser v1.0.3
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.2
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l-fips  25 May 2017

Style: Breeze::Style
Platform: Linux-4.13.6-1-default-x86_64-with-glibc2.3.4, 64bit
Linux distribution: openSUSE Tumbleweed (opensuse)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5
```

**Comment by The-Compiler** [comment]
I'd rather not support binding numbers without modifiers. However, I agree trying to do so should show an error - I added a comment to #1966 about that.

**Comment by betamint** [comment]
How about a warning instead of error? Because it's now working perfectly in the case of 0. I'm not sure if an error will allow this.

**Comment by The-Compiler** [comment]
Yeah, I guess it'd be fine to allow `0` (i.e. not show an error at all), as it makes no sense to use 0 to enter a count.

**Comment by mschilli87** [comment]
I think a warning wouldn't hurt for `0` bindings either:
What if I bind something (say `undo`) to `0` and then I want to go 20 pages back by typing `20H`?
I guess I would end up unding the last two commands (`20`, as in two times `0` --> two times `undo`) and then go back one page (`H`) which might come as a surprise (*cf.* `19HH` `21HL`).

**Comment by jgkamat** [comment]
At least currently, if `0` is prefixed by a number, it's considered a count. For example, `20` would result in a count=20, but `0` would press the key bound to `0`.
