### ISSUE TITLE
Allow spaces at end of bind targets

### ISSUE THREAD

**Issue by jsrndk** [qutebrowser/qutebrowser#3308]
I'd like to be able to say
`config.bind('O', 'set-cmd-text :open ')`
Note the space after "open". This should put me in a cmd line ready to type the target for open.

This is the behaviour of the default 'o', but I don't know how to replicate that manually (I use the Workman keyboard layout where 'o' is placed on the hjkl keys, so I have to remap over default 'o')

This is maybe related to #2017 .

**Comment by pkillnine** [comment]
use `set-cmd-text --space` or `set-cmd-text -s` to add a space to the end.

**Comment by jsrndk** [comment]
Cool, thanks! Is this documented anywhere?

**Comment by pkillnine** [comment]
yep, `help :set-cmd-text`

**Comment by jsrndk** [comment]
Of course, thanks :-)
