### ISSUE TITLE
Small Website is not scrollable

### ISSUE THREAD

**Issue by thomase1993** [qutebrowser/qutebrowser#3312]
If I press J or K nothing happens on this page: http://www.isatap.org/
The priority of this issue is low for me of course. If you need further infos let me know.

Version is Linux Mint and:
qutebrowser v1.0.3-
Git commit: 3a012ca (2017-11-16 11:21:00 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.5.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.5
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2g  1 Mar 2016

**Comment by The-Compiler** [comment]
For some crazy reason, the site only has a frameset with a frame containing the real page. This means you'll need to click the page first before you can scroll - I see the same behavior in Firefox and Chromium.
