### ISSUE TITLE
Highlighting command window

### ISSUE THREAD

**Issue by yellowhat** [qutebrowser/qutebrowser#3314]
Hi all,
I noticed that there is a strange behavior of the command line.
If I type `:o` it will open a list of the possible command to autocomplete, if I press the `up` or `down` key it will not highlight in yellow the first row and let me choose from the list, this is something that happened some time ago. instead I have to continue typing the command name.
If I type `:o` it will open a list of the possible command to autocomplete, if I type the `tab` key it will highlight in yellow the first row but if I press the `up` or `down` key the selected row will not change.
Same behavior on windows and on gentoo with a live-rebuild.

Thanks

```
Version info

qutebrowser v1.0.3
Git commit: v1.0.3-dirty (2017-11-04 16:48:53 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.1
Qt: 5.9.2
PyQt: 5.9.1

sip: 4.19.4
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.6.210 (bundled)
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2h  3 May 2016

Style: QWindowsVistaStyle
Platform: Windows-7-6.1.7601-SP1, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 7, 6.1.7601, SP1, Multiprocessor Free

Paths:
cache: C:\Users\Yellowhat\AppData\Local\qutebrowser\cache
config: C:\Users\Yellowhat\AppData\Roaming\qutebrowser\config
data: C:\Users\Yellowhat\AppData\Roaming\qutebrowser\data
runtime: C:\Users\Yellowhat\AppData\Local\Temp\qutebrowser
```

**Comment by The-Compiler** [comment]
This is expected, see [this section](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#migrating-older-configurations) in the configuring docs.

**Comment by The-Compiler** [comment]
Since this confused quite a lot of people (certainly more than I expected!), I've now pushed 62f37df573681f54d4d698262dcd1e270a438fbc which changes the default behavior for v1.1 to go to the history when no text was entered, but select completion items if text was entered.

I'd be happy about feedback on whether that improves things!

cc @yellowhat @bheadmaster @octavz @nemanjan00 @Pete-Smith @ersi-dnd

**Comment by cryzed** [comment]
I like this change, feels intuitive!

**Comment by ersi-dnd** [comment]
Yes, certainly better when the arrow keys always do something, even though I already got used to the Tab key.

**Comment by yellowhat** [comment]
Also for me, new default is much better.
