### ISSUE TITLE
Update to an up-to-date flake8

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3320]
We're still using an old flake8 2.6.2 in qutebrowser because of [flake8-putty](https://pypi.python.org/pypi/flake8-putty) never being ported.

However, there's a flake8 3.x compatible [flake8-per-file-ignores](https://github.com/snoack/flake8-per-file-ignores) now, and with https://github.com/snoack/flake8-per-file-ignores/commit/d157db39aab7686d81dc9f8e1ad2e03576598463 it should be powerful enough for us to migrate.

There's probably a lot of new ignores to set though.

**Comment by snoack** [comment]
When we migrated (with our rather large code base) at @adblockplus to flake8 3, we experienced a bulk of newly reported E305. But that was it, and we were able to fix these with `autopep8 -i --select=E305`, which is safe (i.e. doesn't change the resulting bytecode) as it only adds additional blank lines.

However, more recently pycodingstyle (and therefore the most recent versions of flake8) introduced E722. I questioned that change in PyCQA/pycodestyle#703, but addressing E722 (either by adding per-file ignores or by changing the code) should be easy enough.

Besides that, (as opposed to flake8-putty) flake8-per-file-ignores reports its own error (X100) if you ignore any error that doesn't occur in the first place. If you want to disable this behavior you can just configure X100 to be ignored (globally). But generally I'd recommend removing the superfluous ignores instead.

**Comment by ryan-farley** [comment]
I've managed to get this partially working [here](https://github.com/ryan-farley/qutebrowser/commit/af3cd52312be1c284a1d1ef79910f551484a632c). With flake8 and flake8-deprecated alone there really weren't many errors that weren't related to the lack of per-file auto-ignore, the use of now-unsupported `# flake8: disable=` where `noqa` will suffice, or just X100 indications that there weren't any errors to ignore in the first place. It works well enough to investigate further, though I'm not going to even pretend to be qualified to attempt to correct novel stylistic errors. 

Updating flake8-pep3101, there are a few instances of S001:

```
qutebrowser/browser/commands.py:997:37: S001 found module formatter
qutebrowser/browser/commands.py:1017:37: S001 found module formatter
qutebrowser/browser/hints.py:499:21: S001 found module formatter
qutebrowser/browser/hints.py:526:25: S001 found module formatter
qutebrowser/mainwindow/tabwidget.py:587:29: S001 found module formatter
```

The real fun only starts when pydocstyle and flake8-docstrings are no longer constrained. The errors themselves are

- D106: Missing docstring in public nested class
- D107: Missing docstring in `__init__`
- D300: Use """triple double quotes"""
- D401: First line should be in imperative mood; try rephrasing
- D412: No blank lines allowed between a section header and its content
- D413: Missing blank line after last section

with the log [here, for readability](https://gist.github.com/921926919f9f5051455ee83ecb7bb93a).

**Comment by The-Compiler** [comment]
Thanks! I'm loking into updating the rest now as well.

**Comment by The-Compiler** [comment]
Fully updated now - thanks @snoack and @ryan-farley!

I've also [added some more useful plugins](https://github.com/qutebrowser/qutebrowser/commits/master/misc/requirements/requirements-flake8.txt-raw).
