### ISSUE TITLE
Set Ui Userstylsheet

### ISSUE THREAD

**Issue by mbronek7** [qutebrowser/qutebrowser#3325]
Hi,
I have a one simple question I am trying to set "dark mode". I found that it can be done like that:
https://www.reddit.com/r/qutebrowser/comments/665wdb/is_there_a_dark_mode/

so I am trying to do it with the command:
:bind ,n set ui user-stylesheet ~/solarized-everything-css-master/css/solarized-all-sites-dark "" ;; reload
but it doesn't work what am I doing wrong? (I got the info that arguments are unrecognized)
Thanks in advance

**Comment by jgkamat** [comment]
What version of qutebrowser are you using? The config names changed in 1.0, so that command isn't valid on the latest qutebrowser. My first guess is maybe you should try to remove the `""`, I'm not sure what that would do.

Does running the command manually via set (not via a binding) work for you?

**Comment by The-Compiler** [comment]
The updated command for v1.0 would be something like:

```
:bind ,n config-cycle content.user_stylesheets ~/code/solarized-everything-css/css/solarized-all-sites-dark.css "" ;; reload
```

**Comment by mbronek7** [comment]
Thanks
