### ISSUE TITLE
Show the default binding in :bind completion

### ISSUE THREAD

**Issue by forkbong** [qutebrowser/qutebrowser#3331]
I found a forgotten branch on my local repo that shows the default binding along with the current in :bind completion.

If it seems useful I could add/fix some tests and submit a PR, or I could ditch it since there is already `:bind --default`.

Right now the 'current' or 'default' tag is shown in parentheses in the description as seen [here](https://imgur.com/a/FaGdh), but it could also replace the description completely (like :set), or replace the existing binding in the rightmost column.

**Comment by The-Compiler** [comment]
Seems like a nice idea for discoverability! The output in the screenshot seems fine to me. Please submit a PR! 👍 

cc @rcorre

**Comment by rcorre** [comment]
LGTM, I think `(Current/Default) <description...>` looks fine. Also, nice completion color theme :grin:

**Comment by forkbong** [comment]
Thanks! It's [gruvbox](https://github.com/morhetz/gruvbox) btw.
