### ISSUE TITLE
Twitter Videos won't play

### ISSUE THREAD

**Issue by fuzunspm** [qutebrowser/qutebrowser#3334]
qute:version: qutebrowser v1.0.3

on twitter and some websites video playback gives error.

**Comment by The-Compiler** [comment]
I'm guessing you installed PyQt via tox, as [lined out here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-depdendencies-including-qt)? Like mentioned there, that uses a precompiled QtWebEngine which does not include support for proprietary codecs.

**Comment by fuzunspm** [comment]
no i installed it via homebrew on mac

**Comment by The-Compiler** [comment]
Same thing essentially then - you'll need to build Qt from source and (e.g. by editing the Homebrew formula) add the `-proprietary-codecs` switch to `./configure`. That'll build for some hours though, and probably needs at least 8 GB of RAM.
