### ISSUE TITLE
Test environments for non-x86_64 platforms

### ISSUE THREAD

**Issue by ryan-farley** [qutebrowser/qutebrowser#3339]
Given that PyQt only exists to link to native C++ libraries and PyPI only distributes binary wheels for x86_64 architectures, it is currently impossible to run the test suite on anything else (in my case, an impulse-buy cheap ARM Chromebook which turned out to be far more capable than expected). Obviously there are reproducibility benefits to the current setup and the default envlist should not change to accommodate the maybe five or six people in the world who would want to try what I'm doing, nor should CI be cluttered with host dependencies, nor would I expect other people to spend time on implementations, but I still think it's worth asking: would there be any chance at inclusion of alternate environments utilizing `link_pyqt.py`?

**Comment by The-Compiler** [comment]
`tox -e py36` already does that.

**Comment by ryan-farley** [comment]
This works for pytest, but the issue remains for vulture and pylint.

**Comment by The-Compiler** [comment]
Fair point, I added it to #2341 as I don't want to introduce more and more environments before cleaning up the tox.ini to use [conditional settings](http://tox.readthedocs.io/en/latest/config.html#factors-and-factor-conditional-settings).
