### ISSUE TITLE
Use re.fullmatch instead of re.match

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3344]

**Comment by gebulmer** [comment]
If I'm understanding correctly from IRC, all instances of re.match should be checked for their behaviour to see whether or not re.fullmatch would be more appropriate.

In the case of something like r'(.*\D|^)(0*)(\d+)(.*)', which is preffered? Adding an anchor at the end shouldn't change the behaviour.

**Comment by The-Compiler** [comment]
I'd like to get rid of `re.match` completely if possible, as it's really confusing. I'd say all instances should either use `re.fullmatch` (if it needs both anchors), or `re.search` (if it needs none) instead.

**Comment by gebulmer** [comment]
I've started work on this.

PR: #3382
