### ISSUE TITLE
Integration with peff/pass?

### ISSUE THREAD

**Issue by sphaugh** [qutebrowser/qutebrowser#3350]
Would be nice to have password manager support with autofill. Currently I use the clipboard which is probably a security risk.

**Comment by NoctuaNivalis** [comment]
See #30 and #180.

**Comment by pkillnine** [comment]
Also check out the `qute-pass` and `password_fill` userscripts in https://github.com/qutebrowser/qutebrowser/tree/master/misc/userscripts

**Comment by sphaugh** [comment]
Thanks guys! :)
