### ISSUE TITLE
qutebrowser won't start

### ISSUE THREAD

**Issue by martinmksiu** [qutebrowser/qutebrowser#3351]
my qutebrowser won't start upon launch. When I attempt to launch from terminal it gives the following error message. Could anyone point me to the right direction?

Version: 1.0.3
OS: Manjaro Linux

Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==1.0.3', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 186, in main
    return app.run(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 100, in run
    configinit.early_init(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configinit.py", line 67, in early_init
    configfiles.init()
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 448, in init
    state = StateConfig()
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 50, in __init__
    self.read(self._filename, encoding='utf-8')
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/msiu/.local/share/qutebrowser/state', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

**Comment by jgkamat** [comment]
@martinmksiu, I think qutebrowser is having some trouble reading it's config files. Could you try running with `--temp-basedir` (which ignores configuration and state). If that helps, can you try moving ~/.local/share/qutebrowser to a backup folder and try again?

**Comment by martinmksiu** [comment]
thanks a lot @jgkamat that solved the problem!

**Comment by jgkamat** [comment]
Nice, I'm closing this since it's fixed! :smile: I wonder what caused the file to be populated like that though...
