### ISSUE TITLE
Feature Request: flash or change color of tabs with updates

### ISSUE THREAD

**Issue by rperce** [qutebrowser/qutebrowser#3363]
I'm using qutebrowser v1.0.4, built from source.

Tabs with dynamic updates (like Slack or Hangouts or any web-based messenger thing) currently don't seem to appear any different when the content of the page has an update. In Chrome, as a contrast, the tab changes color slightly (sometimes, I think). My preferred solution would be to change the tab background color on update, something like color.tabs.update.bg.

**Comment by jgkamat** [comment]
I suspect this is part of the notification api, which qtwebengine doesn't have support for yet. I *think* that whenever a tab sends a notification, chrome keeps track of which tab created it and increments a counter and flashes the tab.

Notification support seems to be landing in qt5.11 (https://github.com/qutebrowser/qutebrowser/issues/3010), so this is probably a feature that would be a long way off.

I think that it might be better to add a cookie to the tabs format which would contain the number of notifications generated by that tab until it is focused.

**Comment by The-Compiler** [comment]
Right - nothing qutebrowser can do here before there's notification support in QtWebEngine.
