### ISSUE TITLE
Tabs can't update favicon

### ISSUE THREAD

**Issue by rperce** [qutebrowser/qutebrowser#3364]
I'm using qutebrowser v1.0.4, build from source. Full version output at the bottom of the report.

Tabs like gmail or slack change their favicon to note updates to the page---e.g. gmail puts the unread count on the favicon. This behavior doesn't work in qutebrowser.

from qute:version:
```
qutebrowser v1.0.4
Git commit: 45a1989a1 (2017-11-30 01:26:44 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.5.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2g  1 Mar 2016

Style: QFusionStyle
Platform: Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
Linux distribution: Ubuntu 16.04.3 LTS (ubuntu)
Frozen: False
Imported from /home/robertp/qutebrowser/qutebrowser
Qt library executable path: /home/robertp/qutebrowser/.venv/lib/python3.5/site-packages/PyQt5/Qt/libexec, data path: /home/robertp/qutebrowser/.venv/lib/python3.5/site-packages/PyQt5/Qt
```

**Comment by jgkamat** [comment]
I'll admit that I haven't ever seen this before, I suspect this is tied to the notification api as well somehow (https://github.com/qutebrowser/qutebrowser/issues/3010). Is there a sample page which sets the notification count in the favicon? Gmail dosen't seem to do it for me in firefox, it seems to be giving me a normal favicon even though I have unread emails.

**Comment by The-Compiler** [comment]
Does https://mathiasbynens.be/demo/dynamic-favicons work for you? How can I test this? Even though I have unread mails, GMail in Chromium doesn't show anything special: 

![image](https://user-images.githubusercontent.com/625793/33576804-53d4e3ae-d941-11e7-9282-09b38cd6aab3.png)

**Comment by rperce** [comment]
Ah, unread-count-in-favicon is a setting in Labs. That site changes the favicon to the google logo once when I press the button; future presses don't do anything. That appears to be the right thing.

**Comment by rperce** [comment]
FWIW, my slack icon also doesn't ever change to show that I have notifications / unread messages --- it's not just gmail doing something weird

**Comment by jgkamat** [comment]
Ah, this seems to only be supported in the javascript gmail view, which seems to be working for me (I guess I have it in 'on' in labs).

![2017-12-04-162836_240x47_scrot](https://user-images.githubusercontent.com/4349709/33577209-515951e0-d910-11e7-8d59-c427fd9dc2d9.png)

**Comment by The-Compiler** [comment]
And you did turn that feature on in Labs in qutebrowser? Works fine here: 
![image](https://user-images.githubusercontent.com/625793/33577239-ad183988-d942-11e7-9a98-3e3c1c224b70.png)

**Comment by rperce** [comment]
It's turned on, yeah, but: ![nobadge](https://user-images.githubusercontent.com/3652460/33577358-5898261e-d908-11e7-8f60-f59b51d4ff94.png)

**Comment by rperce** [comment]
._. I turned the feature off and back on, and now it shows up. Don't see an option to change the setting for slack, though.

**Comment by rperce** [comment]
Okay, something's definitely screwy with this still tho: 
![wrongbadge](https://user-images.githubusercontent.com/3652460/33578046-c3b1654e-d90a-11e7-991e-77225faf9f21.png)

**Comment by The-Compiler** [comment]
I opened [QTBUG-64967](https://bugreports.qt.io/browse/QTBUG-64967) for this - nothing qutebrowser specific from what it looks.

**Comment by sQVe** [comment]
https://bugreports.qt.io/browse/QTBUG-64967 is supposed to be fixed and merged. I still see this issue with **Slack** though. The favicon is correctly changed when recieving a message but are then never changed back to a _clean state_.

**Comment by The-Compiler** [comment]
@sQVe Can you show your `qute://version` please?

**Comment by The-Compiler** [comment]
@marc-groundctl What Qt version are you on? I suppose you could do a similar workaround automatically via a Greasemonkey script.

**Comment by The-Compiler** [comment]
There's also [QTBUG-70081](https://bugreports.qt.io/browse/QTBUG-70081) which you might be seeing here.

**Comment by marc-groundctl** [comment]
qutebrowser v1.4.2
Git commit: 5aa69027e (2018-09-02 14:55:39 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.5
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.11
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QWindowsStyle
Platform: Windows-10-10.0.17134-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.17134, SP0, Multiprocessor Free


It might be related to 70081, but it isn't the same because my test doesn't have an apple touch icon.  It also happens when the icon and shortcut icon have different URLs.
