### ISSUE TITLE
SQL history completion matches words only in specific order

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3365]
This comment is wrong:
https://github.com/qutebrowser/qutebrowser/blob/6973a703c54783b774079bab40f4d75e64262e17/qutebrowser/completion/models/histcategory.py#L89-L91

To match the behaviour, it should read _"treat spaces as wildcards to match any of the typed words __in the order they were typed__"_. And that is not enough - in fact, if I remember correctly, it is a regression compared to the code from before we had the SQL history.

For example, if I'm looking for some page on the Arch wiki, I may type "ArchWiki" first and start typing the page name. But that won't work, because the titles in the history are "Some page name - ArchWiki". I the same problem even with URLs - first I type the domain and then realize that I need to put in the subdomain to filter out some other subdomain.

**Comment by The-Compiler** [comment]
Isn't this a duplicate of #1651, opened by yours truly? :wink:

**Comment by lahwaacz** [comment]
Heh, so I only remember that I had it fixed in a custom branch, sorry...
