### ISSUE TITLE
Implement URL match patterns

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3369]
Taking this here from #27 to find it easier:

Chromium has its own syntax for [URL match patterns](https://developer.chrome.com/apps/match_patterns), similar to how `@match` (and to some extend `@include`) in GreaseMonkey script works (and also what it uses for its extensions).

It uses simple `*` wildcards, with some limitations on where such a wildcard can appear.

This is much easier to write (e.g. `*://mail.google.com/*`), and most likely is faster to match than regexes are. The implementation seems straightforward enough to re-implement it in Python for qutebrowser (unfortunately, I didn't find anyone who did this kind of thing before).

Related files in Chromium:

- [url_pattern.cc](https://cs.chromium.org/chromium/src/extensions/common/url_pattern.cc)
- [url_pattern.h](https://cs.chromium.org/chromium/src/extensions/common/url_pattern.h)
- [url_pattern_unittest.cc](https://cs.chromium.org/chromium/src/extensions/common/url_pattern_unittest.cc)

Other implementations:

- [Firefox: MatchPattern.cpp](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/MatchPattern.cpp)
- [GreaseMonkey: MatchPattern.js](https://github.com/greasemonkey/greasemonkey/blob/master/third-party/MatchPattern.js)

**Comment by The-Compiler** [comment]
To parse the string into URL parts, we might be able to slightly hack the `urllib.parse` module:

```
>>> import urllib.parse  as up
>>> up.scheme_chars += '*'
>>> up.urlsplit('*://*/*')
SplitResult(scheme='*', netloc='*', path='/*', query='', fragment='')
```

Also, it might be possible to do "stub" implementation of this first, only implementing host patterns before taking care of the rest.

**Comment by lamarpavel** [comment]
What about this: https://wiki.qt.io/New_Features_in_Qt_5.8

It mentions `User scripts now support metadata (@include, @exclude, @match)` under `Webengine`.

**Comment by The-Compiler** [comment]
@lamarpavel That's only for [QWebEngineScript](https://doc.qt.io/qt-5/qwebenginescript.html) and unfortunately not exposed as a general-purpose API.

**Comment by toofar** [comment]
I just noticed that `GreasemonkeyManager.scripts_for()` is using fnmatch for `@match` globbing. So things like `https://*.google.com/foo*bar` (from the official docs) wont work currently (for webkit and old webengine backends) because that is somehow supposed to match when there is no subdomain. So this will be useful for that too.

**Comment by The-Compiler** [comment]
I just stumbled over [this QtWebEngine code](https://github.com/qt/qtwebengine/blob/5.10/src/core/user_script.cpp#L247-L249) saying that `\` and `?` are also special in match patterns, but I don't see that reflected in the docs I linked. Probably something worth looking into.

**Comment by toofar** [comment]
That escaping is for the glob function which handles include and exclude rules, the match rules are handled by the chromium URLPattern https://github.com/qt/qtwebengine/blob/5.10/src/core/renderer/user_resource_controller.cpp#L74

**Comment by toofar** [comment]
It may also be instructive to compare to how `ssl.match_hostname()` [does it](https://github.com/python/cpython/blob/master/Lib/ssl.py#L183). Although only a little bit because that also doesn't support '*.blah' matching 'blah'.

**Comment by The-Compiler** [comment]
The problem with that is that it builds a regex, similar to the GreaseMonkey link above - however, that has much worse performance than "manual" checking like Firefox/Chrome do it. Since this is called for every request and every config option, I'm pretty sure this is going to make a big difference.

**Comment by The-Compiler** [comment]
This is [implemented](https://github.com/qutebrowser/qutebrowser/blob/per-url/qutebrowser/utils/urlmatch.py) and passing [tests](https://github.com/qutebrowser/qutebrowser/blob/per-url/tests/unit/utils/test_urlmatch.py) adopted from Chromium in the `per-url` branch. 

It still has a few rough edges here and there, but it works quite well, so one step closer to #27 we are!
