### ISSUE TITLE
All websites throw untrusted certificate error.

### ISSUE THREAD

**Issue by Numkil** [qutebrowser/qutebrowser#3375]
Hi guys, 

I'm running qutebrowser from source on my fedora machine. This evening I was updating my computer and to update qutebrowser too I did a git pull on the master branch and ran the following command:
tox -r -e mkvenv-pypi as per the documentation.

Ever since doing that I have been unable to reach any website whatsoever because certificate is not trusted. My firefox installation still works. Below here you can see the output from :version
![screenshot from 2017-12-09 22-21-54](https://user-images.githubusercontent.com/5604686/33799619-8930d93a-dd2f-11e7-9864-a2aa514c4999.png)

Do you guys have any idea what the issue might be? Thanks for a response.

**Comment by The-Compiler** [comment]
Can you show the full error you get? What Fedora version do you use?

**Comment by Numkil** [comment]
![screenshot from 2017-12-09 22-57-26](https://user-images.githubusercontent.com/5604686/33799882-7cea7096-dd34-11e7-9021-987500037f91.png)

I am on fedora 26 with stable repositories.

**Comment by The-Compiler** [comment]
Can you please show the output of running `./.venv/bin/python -m qutebrowser --temp-basedir --qt-flag enable-logging --qt-flag v=8 --debug https://www.qutebrowser.org/`?

**Comment by Numkil** [comment]
[log.txt](https://github.com/qutebrowser/qutebrowser/files/1545423/log.txt)

**Comment by The-Compiler** [comment]
Looks like it:

```
09:43:48 DEBUG    webview    webview:acceptNavigationRequest:299 navigation request: url https://www.qutebrowser.org/, type NavigationTypeTyped, is_main_frame True
[16809:16837:1210/094349.060242:ERROR:cert_verify_proc_openssl.cc(212)] X509 Verification error unable to get local issuer certificate : 20 : 1 : 4
09:43:49 DEBUG    webview    webview:certificateError:213 Certificate error: Server's certificate is not trusted.
```

I'm guessing this is some kind of incompatibility between the QtWebEngine shipping with the PyQt binary and your system's libraries. Since Fedora 26 seems to ship with an up-to-date QtWebEngine, you can delete `.venv` and do `tox -e mkvenv` instead, which uses your system-wide Qt install. With that, it should probably work better - if not, let me know!

**Comment by Numkil** [comment]
@The-Compiler I was able to build qutebrowser after deleting .venv and running tox -e mkvenv but the issue has not gone away. Still getting that same error message. Any other ideas?

**Comment by The-Compiler** [comment]
Huh, that's weird. Can you show another `:version` screenshot please? Also, can you try reproducing it with e.g. [QupZilla](https://qupzilla.com/) from the Fedora repos?

**Comment by Numkil** [comment]
@The-Compiler The output from :version looks identical to my first screenshot.
![screenshot from 2017-12-11 08-30-25](https://user-images.githubusercontent.com/5604686/33820130-18b95748-de4e-11e7-939d-e57a47a341ca.png)

I had to do a pip install sip before the mkvenv command worked so I am pretty sure I did the steps correctly. I will test with qupzilla when I get back from work tonight.

**Comment by The-Compiler** [comment]
Hmm, that doesn't look like it's using a Qt from Fedora. You should never use `sudo pip install`, that'll cause a lot of trouble. You might want to do `sudo pip uninstall PyQt5` (and the same with `sip`), make sure it doesn't remove anything crucial, and the install PyQt and sip via Fedora's packages.

**Comment by Numkil** [comment]
@The-Compiler 
I figured it out, it was indeed because I had installed my dependencies  through pip and not through the system libraries. Thanks for helping me out!

Btw I am a huge fan of qutebrowser so keep doing what you do :)
