### ISSUE TITLE
RegistryUnavailableError when closing download prompt after closing window

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3378]
Crash report from some while ago from @edrex, on v1.0.2: https://crashes.qutebrowser.org/view/d658759c

```
13:11:06 DEBUG    modes      tabbedbrowser:on_mode_left:618 Left status-input mode, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='https://[...].slack.com/messages/[...]/convo/[...]/'>
13:11:06 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.prompt (reason aborted) as we're in mode KeyMode.normal
[...]
13:11:06 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 200, in _get_window_registry
    return win.registry
AttributeError: 'NoneType' object has no attribute 'registry'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/mainwindow/prompt.py", line 335, in <lambda>
    maybe=True))
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 109, in leave
    instance(win_id).leave(mode, reason, maybe=maybe)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 99, in instance
    return objreg.get('mode-manager', scope='window', window=win_id)
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 227, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 216, in _get_registry
    return _get_window_registry(window)
  File "/usr/lib/python3.6/site-packages/qutebrowser/utils/objreg.py", line 202, in _get_window_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
```

---

> This is repeatable for me on linux/i3. I'm running in "tabs are windows" mode.
>  
>  - Click "print" button for PDF attachment in GMail
>  - It opens in a new window, and "Save to" dialog pops up
>  - Close that window
>  - Hit "escape" to exit the "save to" dialog which is displayed in the original gmail window as well
>  - Crash
>  
> I wonder if it's repeatable for a normal "save as" dialog when closing the originating window and then exiting the dialog from another. Also if it's related to "tabs are windows"

**Comment by The-Compiler** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by The-Compiler** [comment]
Welp, looks like gitmate.io is commenting as my user?!

**Comment by sils** [comment]
I've added this to https://gitlab.com/gitmate/open-source/gitmate-2/issues/244 ; we're working on making the expectations more clear.

**Comment by edrex** [comment]
I can still reproduce this from an empty basedir with just

```
c.tabs.tabs_are_windows = True
```

in config.py. I'm not sure how to reproduce without this. Seems likely to be the factor.

**Comment by The-Compiler** [comment]
(FYI, I removed some earlier comments talking about a GitMate.io bug here)

This also seems to happen when aborting (?) a download in some crash reports (possibly when closing a download tab and then cancelling the prompt?):

- https://crashes.qutebrowser.org/view/ee77a5f6
- https://crashes.qutebrowser.org/view/03c0c155
- https://crashes.qutebrowser.org/view/f36ab86e
- https://crashes.qutebrowser.org/view/f7ed6f72
- https://crashes.qutebrowser.org/view/f287a2b6
- https://crashes.qutebrowser.org/view/75e65467
- https://crashes.qutebrowser.org/view/7252125a
- https://crashes.qutebrowser.org/view/c13f62d9

**Comment by rcorre** [comment]
Pretty sure I hit the same thing (filed a crash report).

1. `qutebrowser` (opens window 1)
2. `qutebrowser ~/downloads/some.pdf` (opens window 2, both windows have a download prompt)
3. Close window 2 via your window manager (without explicitly closing the download prompt)
4. Press `ESC` in window 1 to close the (now orphaned?) download prompt
5. Crash

I don't have `tabs_are_windows` set.

Step 2 presumably opens a download prompt only if you don't have the js pdf viewer.
