### ISSUE TITLE
Startpage file

### ISSUE THREAD

**Issue by HanaO00** [qutebrowser/qutebrowser#3383]
Hello, for my startpage i use 
startpage = file:///home/myuser/homepage/start.html, but qutebrowser fallbacks to duckduckgo, i use the 1.0.4-1

**Comment by The-Compiler** [comment]
How exactly did you set it? Are you sure that file exists at that location?

**Comment by HanaO00** [comment]
I set that line on my qutebrowser.conf file, and yes the file already exists

**Comment by pkillnine** [comment]
just to note: `url.start_pages` is the page that's loaded when the browser is first opened, `url.default_page` is the page that appears when a new tab is opened without a URL (e.g. `open -t` without a URL)

**Comment by jgkamat** [comment]
@HanaO00 qutebrowser versions newer than 1.0 had a config migration, for more information, see http://qutebrowser.org/doc/help/configuring.html. 

If you set the configuration with the `:set` command, it will be saved to a new file. `qutebrowser.conf` is no longer read for configuration.

**Comment by The-Compiler** [comment]
@HanaO00 Out of curiosity, what made you expect that `qutebrowser.conf` would work? Did you still have it lying around from an older qutebrowser version? Or did you read about it somewhere?

**Comment by HanaO00** [comment]
I have used qutebrowser for a few months, as i understand, qutebrowser.conf is not used now, so i remove it to my home folder ?

For config what i do ? Just type : qute://configdiff/old ?

**Comment by The-Compiler** [comment]
@HanaO00  Sorry for the late answer, that mail got lost in the depths of my inbox :wink: Yeah, you can remove `qutebrowser.conf` after migrating your settings. See the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc) for details about the new config.
