### ISSUE TITLE
Question regarding specific font minimum size

### ISSUE THREAD

**Issue by qutetemp** [qutebrowser/qutebrowser#3387]
Is there a way I can set up a minimum size for this type of font in px ? It doesn't seem to be affected by any font setting.
http://www.gutenberg.org/wiki/Technology_(Bookshelf)#Library_of_Congress_.22Technology.22_list

**Comment by The-Compiler** [comment]
Setting `fonts.web.size.minimum` seems to work fine here - after setting it to e.g. 20, I can't zoom out and make the font smaller than that. Are you seeing something different? If so, with what backend, qutebrowser version, and Qt version?

**Comment by qutetemp** [comment]
Hmm. It no longer seems to be the case or I was mistaken. I recently messed around with the dpi setting for fontconfig.

**Comment by qutetemp** [comment]
https://comfy.moe/getzgo.png
https://comfy.moe/nopzwk.png

Ok, this is definately irking me.
There's no way the font used in the "Sideways View" blog body is the same pixel size as HN comments.

c.fonts.web.size.default_fixed = 14
c.fonts.web.size.minimum_logical = 14
c.fonts.web.size.default = 14
c.fonts.web.size.minimum = 14

There must be something I don't understand.

**Comment by The-Compiler** [comment]
Well, I don't either :laughing: All qutebrowser does is passing those settings to Qt, and that part seems to be working fine...
