### ISSUE TITLE
Feature: Browsing mode in window.title

### ISSUE THREAD

**Issue by Midek** [qutebrowser/qutebrowser#3390]
Currently when browsing with a hidden statusbar it is sometimes confusing to figure out if im in normal, insert or passthrough mode.
There already is an option to put indicator for private mode in title, so it would be nice to have an option to put browsing mode indicator there as well.

Preferably just a single letter indicator so it does not grow too fast, like 'I' for insert mode, 'P' for passthrough, 'C' for carret etc, kinda like surf browser does it.

**Comment by The-Compiler** [comment]
Merging this into #3398.
