### ISSUE TITLE
Black window – no errors reported (v1.0.4)

### ISSUE THREAD

**Issue by davidebaldini** [qutebrowser/qutebrowser#3394]
As I launch qutebrowser I get a solid black window which only displays the text on the tabs' title and on the status bar. The window reacts to keyboard and mouse commands, but otherwise is full black.

No errors are printed on console, only two warnings as shown below.
Qutebrowser and all its dependencies are installed exclusively from Debian testing repository (13/12/2017)

### System details:

Notebook has two video cards with one monitor attached to each; X server joins the two screens in xinerama mode. Xrandr is not available. The video cards are:

* intel gm965 (integrated in notebook)
* displaylink (external thru usb)
<br>

    $ ls -lh /usr/bin/python*
    lrwxrwxrwx 1 root root    9 Mar 16  2015 /usr/bin/python -> python2.7
    lrwxrwxrwx 1 root root    9 Mar 16  2015 /usr/bin/python2 -> python2.7
    -rwxr-xr-x 1 root root 3.8M Aug 13  2016 /usr/bin/python2.7
    lrwxrwxrwx 1 root root    9 Oct 26 21:09 /usr/bin/python3 -> python3.6
    -rwxr-xr-x 2 root root 4.5M Dec  6 11:08 /usr/bin/python3.6
    -rwxr-xr-x 2 root root 4.5M Dec  6 11:08 /usr/bin/python3.6m
    lrwxrwxrwx 1 root root   10 Oct 26 21:09 /usr/bin/python3m -> python3.6m
<br>

    $ glxinfo  # first few lines only
    name of display: :0
    display: :0  screen: 0
    direct rendering: Yes
    server glx vendor string: SGI
    server glx version string: 1.4
    server glx extensions:
        GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_texture_from_pixmap,
        GLX_EXT_visual_info, GLX_EXT_visual_rating, GLX_INTEL_swap_event,
        GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, GLX_SGIS_multisample,
        GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_make_current_read
    client glx vendor string: Mesa Project and SGI
    client glx version string: 1.4

<br>

    $ qutebrowser --version
    23:34:45 WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-davide'
    23:34:45 WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-davide'
    qutebrowser v1.0.4
    Git commit:
    Backend: QtWebEngine (Chromium 56.0.2924.122)
    
    CPython: 3.6.4rc1
    Qt: 5.9.2
    PyQt: 5.9.2
    
    sip: 4.19.6
    colorama: no
    pypeg2: 2.15
    jinja2: 2.10
    pygments: 2.2.0
    yaml: 3.12
    cssutils: no
    attr: 17.2.0
    PyQt5.QtWebEngineWidgets: yes
    PyQt5.QtWebKitWidgets: no
    pdf.js: no
    sqlite: 3.16.2
    QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017
    
    Style: QFusionStyle
    Platform: Linux-3.11.1-SDcard-5620z-i686-with-debian-9.2, 32bit
    Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
    Frozen: False
    Imported from /usr/lib/python3/dist-packages/qutebrowser
    Qt library executable path: /usr/lib/i386-linux-gnu/qt5/libexec, data path: /usr/share/qt5
    
    Paths:
    cache: /home/davide/.cache/qutebrowser
    config: /home/davide/.config/qutebrowser
    data: /home/davide/.local/share/qutebrowser
    runtime: /tmp/runtime-davide/qutebrowser
    system data: /usr/share/qutebrowser

**Comment by The-Compiler** [comment]
Can you please test with `python3 scripts/testbrowser.py --webengine https://www.qutebrowser.org/` in the qutebrowser repository (or [download](https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/scripts/testbrowser.py) the script separately)?

If you can reproduce it there, does `export QT_XCB_FORCE_SOFTWARE_OPENGL=1` change anything?

Also, if you recently did an update (of e.g. your kernel or graphic drivers) and haven't rebooted yet, can you please try that?

**Comment by davidebaldini** [comment]
I downloaded the test script from the link you provided. The black window is reproduced in both the following tests, with the difference from my previous report that no text is displayed (status bar and tabs' titles).

    $ python3 testbrowser.py --webengine https://www.qutebrowser.org/
    QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-davide'
    Loading progress: 10%
    Loading progress: 10%
    Loading started
    Loading progress: 48%
    Loading progress: 67%
    Loading progress: 79%
    Loading progress: 88%
    Loading progress: 100%
    Loading finished
    Loading progress: 100%
    Loading progress: 100%
<br>

    $ export QT_XCB_FORCE_SOFTWARE_OPENGL=1
    $ python3 testbrowser.py --webengine https://www.qutebrowser.org/
    QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-davide'
    Loading progress: 10%
    Loading progress: 10%
    Loading started
    Loading progress: 70%
    Loading progress: 90%
    Loading progress: 100%
    Loading finished
    Loading progress: 100%
    Loading progress: 100%

There were no recent kernel or driver updates, either userspace or kernel level, the computer uptime is fresh.

**Comment by The-Compiler** [comment]
Bummer... Looks like this is some kind of incompatibility between your graphic drivers or Xinerama setup, and QtWebEngine. Unfortunately there isn't much you can do about that, but I suggest [opening a Qt bug](https://bugreports.qt.io/), maybe someone has an idea there.

You might want to try using qutebrowser with QtWebKit instead (by starting with `--backend webkit` initially, and then doing `:set backend webkit`). You should get the [updated fork](https://github.com/annulen/webkit/wiki) (5.212) via [Debian testing packages](https://packages.debian.org/buster/libqt5webkit5) if I'm not mistaken (the older version shipping with Qt 5.9 isn't supported, as it's ancient and was abandoned upstream).

**Comment by davidebaldini** [comment]
I reported the bug at Qt: https://bugreports.qt.io/browse/QTBUG-65196 .
I appreciate any help there as I have no knowledge of python nor Qt.
