### ISSUE TITLE
"Suspended" tabs in history

### ISSUE THREAD

**Issue by apm256** [qutebrowser/qutebrowser#3396]
When `session.lazy_restore` is `true`, "qute://back/*" urls are included in the history. As re-opening such URLs is pointless, perhaps they should not be saved in the history.

**Comment by The-Compiler** [comment]
You mean when going back/forward? This probably would make sense indeed. @seebye do you want to take a look at this?

**Comment by apm256** [comment]
> You mean when going back/forward?

Yes.
For instance, `:open -t qute://back` displays useless suggestions (as we can go back anymore from such urls). This can leads to noisy history search results.

**Comment by seebye** [comment]
Should be fixed with: https://github.com/seebye/qutebrowser/commit/a911094846e438596e5a0656cf6f8f515eb3fd21
