### ISSUE TITLE
feature request: suspended tabs' title customization

### ISSUE THREAD

**Issue by apm256** [qutebrowser/qutebrowser#3397]
Using the `lazy_restore` setting adds a "Suspended: " string to the tab's title.
I would like to replace this indicator with something less intrusive. Perhaps using a 'pinned tabs'-like setting (`tabs.title.format_pinned`)?

**Comment by NoctuaNivalis** [comment]
Perhaps this belongs with #3390?

**Comment by The-Compiler** [comment]
Merging this into #3398.
