### ISSUE TITLE
Fedora 27 package has broken OpenSSL

### ISSUE THREAD

**Issue by TheLastProject** [qutebrowser/qutebrowser#3404]
I'm not sure what you can do about the Fedora, but I feel it's important to note that it's broken when dnf installing it (unless I messed something up on my system). Seems to be the same as what I'm experiencing with my own PyQt project: https://github.com/Pext/Pext/issues/48.
```
$ qutebrowser --version
20:15:35 WARNING: Incompatible version of OpenSSL                           
qutebrowser v1.0.3                    
Backend: QtWebEngine (Chromium 56.0.2924.122)                               

CPython: 3.6.3                        
Qt: 5.9.1                             
PyQt: 5.9                             

sip: 4.19.3                           
colorama: 0.3.7                       
pypeg2: 2.15                          
jinja2: 2.9.6                         
pygments: 2.2.0                       
yaml: 3.12                            
cssutils: 1.0.1 $Id$                  
attr: 16.3.0                          
PyQt5.QtWebEngineWidgets: yes         
PyQt5.QtWebKitWidgets: no             
pdf.js: no                            
sqlite: 3.16.2                        
QtNetwork SSL: no                     

Style: QFusionStyle                   
Platform: Linux-4.14.5-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven, 64bit                                                                        
Linux distribution: Fedora 27 (Twenty Seven) (fedora)                       
Frozen: False                         
Imported from /usr/lib/python3.6/site-packages/qutebrowser                  
Qt library executable path: /home/sylvia/.local/lib/python3.6/site-packages/PyQt5/Qt/libexec, data path: /home/sylvia/.local/lib/python3.6/site-packages/PyQt5/Qt                             

Paths:                                
cache: /home/sylvia/.cache/qutebrowser                                      
config: /home/sylvia/.config/qutebrowser                                    
data: /home/sylvia/.local/share/qutebrowser                                 
runtime: /run/user/1000/qutebrowser   
```

```
$ qutebrowser 
20:46:14 WARNING: Incompatible version of OpenSSL
20:46:14 WARNING: Could not initialize QtNetwork SSL support. If you use OpenSSL 1.1 with a PyQt package from PyPI (e.g. on Archlinux or Debian Stretch), you need to set LD_LIBRARY_PATH to the path of OpenSSL 1.0. This only affects downloads.
```

The app otherwise runs fine, just can't update the adblock list or so.

**Comment by jgkamat** [comment]
> Qt library executable path: /home/sylvia/.local/lib/python3.6/site-packages/PyQt5/Qt/libexec, data path: /home/sylvia/.local/lib/python3.6/site-packages/PyQt5/Qt

@TheLastProject, I think this means your PyQt5 is installed via pip, and not from fedora packages. Can you try uninstalling PyQt5 from pip and reinstalling [the fedora package](https://apps.fedoraproject.org/packages/python3-qt5) instead?

**Comment by TheLastProject** [comment]
Derp, I kept trying to `pip uninstall`, forgot I specifically needed `pip3 uninstall`. My bad, this issue is invalid. Sorry about that and thanks for the help.

For future note of anyone else who runs into this: make sure you `pip3 uninstall PyQt5 sip`. Not uninstalling pip3-installed sip will cause another error:
```RuntimeError: the sip module implements API v12.0 to v12.2 but the PyQt5.QtCore module requires API v12.3```

**Comment by The-Compiler** [comment]
Indeed, this doesn't look like a Qt from the Fedora package.

**Comment by The-Compiler** [comment]
Ah, looks like we just commented in the same second 😆 Glad you got it working, and no worries!

**Comment by reaysawa** [comment]
Same issue happened for me with Ubuntu 18.04. **I was using the PyQt5 from PyPI too.**

Solution was to install the missing OpenSSL1.0 libraries:

`sudo apt install libssl1.0.0 libssl1.0-dev`

which put the libraries under `/usr/lib/x86_64-linux-gnu`, so I didn't even have to include the path in LD_LIBRARY_PATH. Got it working without having to use the distro's packages.
