### ISSUE TITLE
Sound doesn't work

### ISSUE THREAD

**Issue by inclooder** [qutebrowser/qutebrowser#3406]
Hello :)
I've installed qutebrowser on my arch linux and it seems that the sound is not working.
Here is my output from `qutebrowser --version`. 

```
qutebrowser v1.0.4
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.3
Qt: 5.9.3
PyQt: 5.9.2

sip: 4.19.6
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.14.4-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/inclooder/.cache/qutebrowser
config: /home/inclooder/.config/qutebrowser
data: /home/inclooder/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```
Please let me know if you need some more info.

**Comment by The-Compiler** [comment]
Does your sound work elsewhere? Can you try with `qupzilla` please?

**Comment by inclooder** [comment]
@The-Compiler `qupzilla` works fine and also other browsers like chromium and firefox.

**Comment by The-Compiler** [comment]
You can launch it with `--debug`, but since qutebrowser does nothing related to sound (this is all done by the backend), you won't find anything related to it. You are testing with a 2.x version of QupZilla, right?

**Comment by inclooder** [comment]
I don't see anything special in the log and yes the version of QupZilla is `2.2.2-1`.

**Comment by The-Compiler** [comment]
I'm afraid I'm out of ideas then. If you use PulseAudio (which I assume you do on Arch), start `pavucontrol` and check the status for qutebrowser there. I'm closing this now, as qutebrowser itself does nothing related to sound, and this works fine for other people as far as I know.

**Comment by inclooder** [comment]
@The-Compiler 
Qutebrowser was muted in `pavucontrol`, thats strange :thinking: 
It's working now. cheers :+1:
