### ISSUE TITLE
[feature] smart hints

### ISSUE THREAD

**Issue by plexigras** [qutebrowser/qutebrowser#3408]
i would like hints that are more likely to be followed easier to select.

### example

`c.hints.chars = 'ab'`

`example.com/a` with `5` visits would have the hint `[aa]`

`example.com/b` with `3` visits would have the hint `[bb]`

`example.com/c` with `2` visits would have the hint `[ab]`

`example.com/d` with `1` visit would have the hint `[ba]`

**Comment by The-Compiler** [comment]
See #674 and #2644.
