### ISSUE TITLE
Scrolling with small increments causes high CPU usage

### ISSUE THREAD

**Issue by Pbtflakes** [qutebrowser/qutebrowser#3409]
In short, scrolling through pages using the trackpad or by holding down directional keys causes qutebrowser and python3 to use 100% of one of my CPU cores. About 75% of the load is under the python3 process, while the other 25% is from qutebrowser. This is an issue for me, since it drains my laptop battery much faster with regular usage. This issue is with qutebrowser 1.0.3-1.1, and I will update this report once I've tested version 1.0.4-1.1.

OS: openSUSE Tumbleweed, kernel version 4.13.12-1.

**Comment by The-Compiler** [comment]
Can you please try the latest git master too? Also, what OS?

**Comment by Pbtflakes** [comment]
I'm on openSUSE Tumbleweed. Just tried commit e66dce236, it's not quite as much but still around 30% core usage for `python3 qutebrowser.py` and a bit less for the `QtWebEngineProcess`.

**Comment by The-Compiler** [comment]
Good to hear things have improved! I'm afraid I don't think there's much more qutebrowser can do here.

**Comment by jgkamat** [comment]
I also did a profile because I was a bit curious (on master), and most of the time was spent in qt according to it, so I agree...
