### ISSUE TITLE
Greasemonkey scripts

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#341]
Due to Qt limitations those will only run when javascript is turned on for the page.

We might be able to re-use some code from Eric and QupZilla:
http://die-offenbachs.homelinux.org:48888/hg/eric/file/c16a52652af5/Helpviewer/GreaseMonkey
https://github.com/QupZilla/qupzilla/tree/master/src/plugins/GreaseMonkey

**Comment by andor44** [comment]
I have some work put into this, which should be ready for a PR soon after I work out some kinks. Just commenting here to avoid duplication of efforts.

**Comment by lahwaacz** [comment]
Just adding a link to the PR: #664

**Comment by The-Compiler** [comment]
Unfortunately the PR seems pretty dead, and I don't have the time to revive it. With QtWebEngine, it seems like that feature will be built-in anyways: https://codereview.qt-project.org/#/c/148671/

**Comment by lahwaacz** [comment]
Wow, that would be nice!

**Comment by vyp** [comment]
Yup, that would be cool!

**Comment by The-Compiler** [comment]
Note to self: http://userscripts-mirror.org/scripts/show/105153 might help to get the `GM_*` functions if QtWebEngine/Chromium doesn't implement those.

**Comment by moorchegue** [comment]
Any progress on this?

**Comment by pkillnine** [comment]
@moorchegue I think it will be properly implemented when plugin api is created, however that will probably be in a year's time, so hopefully @The-Compiler will accept some commits that implement this for the time being (I've made a patch that blocks youtube video ads, hopefully we can add greasemonkey functionality before the plugin api is created since that will be like next summer I think)

**Comment by The-Compiler** [comment]
I don't think this is necessarily tied to having a plugin API.

It could be implemented with something like a `content.javascript.userscript` setting, and either supporting GreaseMonkey-style `@match` comments (which QtWebEngine [already does](http://doc.qt.io/qt-5/qwebenginescript.html#details) since Qt 5.8), or simply that being a per-domain setting.

Then there's the `GM_*` javascript API, which needs either the [Greasemonkey Emulation](http://userscripts-mirror.org/scripts/show/105153) mentioned above, or something similar to #664 (which was abandoned by the author).

That all being said, I currently have other priorities (new config, v1.0, missing QtWebEngine bits), and that's probably not going to change over the next couple of months. Contributions welcome!

**Comment by The-Compiler** [comment]
Quick overview of what's going on in #3040 (cc @toofar):

# Before merge

- [ ] Add more tests
- [ ] Fixes for latest review
- [ ] Look into frame support for QtWebKit
- [ ] Look into script loading timing with QtWebEngine 5.7.1

# After merge

- [ ] Frame support for QtWebKit (if more complex than anticipated)
- Add some Python support code (via QtWebChannel?):
    - [ ] Cross-origin XHR for `GM_xmlhttpRequest`
    - [ ] Use a real database for `GM_setValue` et al
    - [ ] `GM_openInTab` without limitations?
- [ ] Sandboxing of GreaseMonkey scripts? (see `unsafeWindow` etc.)
- [ ] Add support for `@requires`
   - [ ] Loading from disk
   - [ ] Remote downloading
- [ ] Auto-installing userscripts?
- [ ] Some kind of userscript manager?
- [ ] `isPrivate` for [GM_Info](https://wiki.greasespot.net/GM_info)
- [ ] Stub out `exportFunction` and similar?
   - [ ] Set `scriptHandler` and `version` correctly

**Comment by The-Compiler** [comment]
Initial GreaseMonkey support is in v1.1, see #3238 for possible improvements.
