### ISSUE TITLE
custom home/start page css "leaks" through to other pages

### ISSUE THREAD

**Issue by TrilbyWhite** [qutebrowser/qutebrowser#3411]
This minor issue appeared after the upgrade of qt5-webengine from 5.9.3-1 to 5.10.0-1 on archlinux (other qt5 packages like webchannel and others had the same version increments).

I first noticed several pages had an odd dark background.  I first determined it was pages that did not specify their own background, but even then it wasn't consistent.  I eventually tracked it to pages that were opened in tabs that previously had my default home/start page which is a file on my own computer "blank.html" which had little more than a single css rule `* { background: #202428; }'  When I gave the body element of "blank.html" a distinctive id and changed the css to '#my_unique-ish_id { background: #202428; }' the problem went away.

It would seem that this style rule somehow "leaks" through to pages loaded after it if that rule was not explicitly overriden.  Yet when I viewed the source of such pages, that css rule was not listed - so it is not being treated like user.css/custom.css which is explicitly added to the page - rather I suspect the webview (or similar element) is remembering the previous css that had been set.

This may have some overlap with issue #3377 though it seems a bit different.  For my use I'm content with my unique id on my blank.html page's body element, but perhaps this report will help trace related issues.

**Comment by The-Compiler** [comment]
Hmm, that's odd... Can you show the page source so I can easily try to reproduce it? Also, can you check whether you can reproduce it with e.g. QupZilla?

**Comment by TrilbyWhite** [comment]
Sure.  Blank.html triggering the problem:```<html>
<head>
<link rel="icon" href="file:///home/jmcclure/.config/qutebrowser/cursor.png"/>
<title>&nbsp;</title>
<style type="text/css">* { background: #202428; }</style>
</head>
<body></body>
</html>
```
And avoiding it:```<html>
<head>
<link rel="icon" href="file:///home/jmcclure/.config/qutebrowser/cursor.png"/>
<title>&nbsp;</title>
<style type="text/css">#myhomepage_blank { background: #202428; }</style>
</head>
<body id="myhomepage_blank"></body>
</html>
```
I've found it does not really need to be the start/home page.  Just opening that html file from the local computer is sufficient to trigger it:
1) qutebrowser /path/to/origiinal_blank.html
2) in the same tab navigate to any page that doesn't set a html/body background color
3) the 202428 background will be preserved.

I just tested in qupzilla (2.2.2) and couldn't reproduce the problem there.  A default white background is properly used.  I also just tried putting the "blank.html" on my own server navigating to that page, then to another that does not set a background, and the 202428 is *not* carried over.  So it does seem specific to the html file opened as a file url from the local machine.

**Comment by The-Compiler** [comment]
Hmm, I can't seem to reproduce this. I do get the page with the dark background, but when I do `:open http://t.cmpl.cc/` after that (which has no background set), I get the white background as expected.

Can you reproduce this with `--temp-basedir`?

**Comment by mschilli87** [comment]
I also tried to reproduce:

 1. open the above HTML, got grey page
 2. press `o`
 3. paste above asciidoc link
 4. confirm, got README with white(!) background

**Comment by TrilbyWhite** [comment]
*headdesk* sorry I didn't try this first, but I just moved my ~/.config/qutebrowser folder for a fresh start, and I could not replicate the problem.  So it seems to be something else in there that is contributing to this.  Sorry for the noise.

**Comment by The-Compiler** [comment]
Let me know when you find out what's to blame, though! Seems like quite an odd issue.

**Comment by TrilbyWhite** [comment]
Ok, I did trace it to a single setting - but it makes no sense to me.  With statusbar.hide set to True the dark background persists.  With statusbar.hide not explicitly set, I get the proper white background.

I have a hunch to follow up on: the same 202428 dark grey is used for my status bar background.  I'm going to change that and I'll report back with an edit momentarily.

**Comment by The-Compiler** [comment]
Weird! I can actually reproduce it with `--temp-basedir` by doing `o` `~/tmp/x.html` and then `o` `t.cmpl.cc`. When doing `python3 -m qutebrowser --temp-basedir  ':open ~/tmp/x.html' ':later 1000 open t.cmpl.cc'` however, I can't.

**Comment by The-Compiler** [comment]
So far I have no clue what's going on here. Things I've tried:

- With qutebrowser v0.11 and `--backend webengine`, I can reproduce this.
- In QupZilla and Qt simplebrowser, so far I can't.
- The logs between a good run (with a delay of 200) and a bad one (with a delay of 100) don't differ.
- Disabling our stylesheet injection doesn't help.
- It doesn't reproduce with older Qt versions.

Might be worth trying to bisect it in Qt, but not sure when I'll find the time for it. Weird issue for sure! 😆

**Comment by TrilbyWhite** [comment]
I get the same results as your tests from two posts ago.

It is definitely weird, and begging to be solved for curiosity's sake.  But other than that it's easily avoided.

**Comment by The-Compiler** [comment]
@TrilbyWhite Any chance you can re-test this with Qt 5.11?

**Comment by TrilbyWhite** [comment]
I've seen no change in this with 5.11 (the problem persists).  I also just rebuilt qutebrowser ver 1.3.1.r97.g4614ad506-1 and confirmed it still happens.

**Comment by The-Compiler** [comment]
Did anything change about this with newer Qt versions by any chance?

**Comment by TrilbyWhite** [comment]
Sorry I didn't follow up.  I did just confirm that this is no longer a problem.  Honestly I don't remember seeing the symptoms in a while either, so I'm not sure when it clered up, but it has.

**Comment by The-Compiler** [comment]
Another way to reproduce this:

- Open youtube with `--temp-basedir`
- Turn on dark mode in the youtube menu
- Use `:set`

Reproduces with Qt 5.11, but not Qt 5.12+.
