### ISSUE TITLE
Ignore Keyboard Layout

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#3412]
Hello, first of all thanks for your work on qutebrowser, it has been awesome using such a great piece of software.

I'd like to propose a feature request I used to have on VimFX, which is 'ignore keyboard layout (on normal mode)'. This makes keys such as '`' being available for us with deadkeys layouts.

Is this enough information or maybe I should elaborate?

**Comment by forkbong** [comment]
I don't know if doing that automatically would be possible, but you can already achieve that using `c.bindings.key_mappings`. For example I have this in my `config.py`. 

```python
c.bindings.key_mappings = {
    'Α': 'A', 'α': 'a',
    'Β': 'B', 'β': 'b',
    'Γ': 'G', 'γ': 'g',
    'Δ': 'D', 'δ': 'd',
    'Ε': 'E', 'ε': 'e',
    'Ζ': 'Z', 'ζ': 'z',
    'Η': 'H', 'η': 'h',
    'Θ': 'U', 'θ': 'u',
    'Ι': 'I', 'ι': 'i',
    'Κ': 'K', 'κ': 'k',
    'Λ': 'L', 'λ': 'l',
    'Μ': 'M', 'μ': 'm',
    'Ν': 'N', 'ν': 'n',
    'Ξ': 'J', 'ξ': 'j',
    'Ο': 'O', 'ο': 'o',
    'Π': 'P', 'π': 'p',
    'Ρ': 'R', 'ρ': 'r',
    'Σ': 'S', 'σ': 's',
    'Τ': 'T', 'τ': 't',
    'Υ': 'Y', 'υ': 'y',
    'Φ': 'F', 'φ': 'f',
    'Χ': 'X', 'χ': 'x',
    'Ψ': 'C', 'ψ': 'c',
    'Ω': 'V', 'ω': 'v',
    'ς': 'w',
}
```

Each letter of the greek keyboard layout is mapped to the equivalent english letter.

**Comment by The-Compiler** [comment]
I've looked into this before, and as far as I'm aware it's not possible for qutebrowser to do more than that without implementing a lot of keyboard handling by itself.

**Comment by aleprovencio** [comment]
@forkbong: thanks for the info, but I don't think I can do that for accents like '`' I mentioned right?

@The-Compiler: So is this a QT thing? Maybe you can point me related issues?

**Comment by The-Compiler** [comment]
See #1207 for some context.

**Comment by forkbong** [comment]
@aleprovencio I think that dead keys like these are ignored [here](https://github.com/qutebrowser/qutebrowser/blob/dbb89b1073db8a7a7da6b0e7cb5fae504580febf/qutebrowser/keyinput/basekeyparser.py#L122) so no, you can't use them.

**Comment by aleprovencio** [comment]
Alright, thanks guys.
