### ISSUE TITLE
Neo keyboard layout keys triggers shortcuts in certain input fields

### ISSUE THREAD

**Issue by tjanson** [qutebrowser/qutebrowser#3414]
I’m using the [Neo keyboard layout](http://neo-layout.org/). It has a third layer, e.g., <kbd>Mod3</kbd>+<kbd>F</kbd> yields `=`. This Mod3 modifier is (mis?)interpreted as Alt, i.e., <kbd>Alt</kbd>+<kbd>F</kbd> in qutebrowser; possibly by Qt (as shown by `keytester`). However, [the underlying problem also occurred in vimperator and pentadactyl](https://wiki.neo-layout.org/ticket/172).

In any case, in qutebrowser this leads to two problems:

* Attempting to insert `+=:` triggers the bindings of <kbd>Alt</kbd>+<kbd>B</kbd>, <kbd>Alt</kbd>+<kbd>F</kbd>, and <kbd>Alt</kbd>+<kbd>D</kbd> in command mode. This is easily solved by `config.unbind('<Alt-D>', mode='command')` etc.
* In [CodeMirror](http://codemirror.net/) input areas (and possibly others), the same *effect* (backword / forward / kill word) is triggered. Presumably the <kbd>Alt</kbd>+<kbd>F</kbd> is passed to the JS code of the input area and interpreted by it.

I understand that the root cause of this is not in qutebrowser, so I won’t be mad if you close this as invalid / won’t-fix. However, the problem does not occur in Firefox / Chrome / Safari, and I figure other users might run into this as well.

**Comment by The-Compiler** [comment]
Yeah, I don't think there's anything qutebrowser can do here. [This Qt issue](https://bugreports.qt.io/browse/QTBUG-50786) sounds relevant.

by the way, congrats on being the 2000th closed issue 🎉 😆

**Comment by tjanson** [comment]
Thanks for the link, I’ll check it out.

And thanks for being the savior of Vimperator refugees! Your work is appreciated.
