### ISSUE TITLE
Add rl-backward-delete-char as an instert mode command

### ISSUE THREAD

**Issue by alejandrogallo** [qutebrowser/qutebrowser#3415]
I tried to add the following line into the `[insert]` section of my keys config file

```
rl-backward-delete-char
    <ctrl-h>
```

but qutebrowser tells me that this command is only vald for the prompt mode and not for insert mode.
I am very used to typing `ctrl h` as backspace as in vim, and I would like to do it in qutebrowser too.

Thanks for the project!

**Comment by The-Compiler** [comment]
Duplicate of #68

**Comment by alejandrogallo** [comment]
awesome, thanks!

**Comment by pkillnine** [comment]
Just to note: It looks like you're using an old version of qutebrowser, from version 1.0 onwards it no longer uses `keys.conf`.

**Comment by alejandrogallo** [comment]
Oh, thanks, good to know, I'll update it then!
