### ISSUE TITLE
add the feature of per instance proxy configuration

### ISSUE THREAD

**Issue by JasonYangShadow** [qutebrowser/qutebrowser#3416]
global proxy configuration for all instances is not good. I prefer per instance settings

**Comment by jgkamat** [comment]
@JasonYangShadow, what exactly do you mean by 'per instance'? You might be able to get this by using config.py to turn the setting on/off as you please.

**Comment by JasonYangShadow** [comment]
@jgkamat I mean usually I will open several qutebrowser instances in differrent external monitors. So I would like to set different proxy configurations to different running instances to allow me to seperate the browse mode

**Comment by jgkamat** [comment]
@JasonYangShadow you could try using the `--basedir` feature, it will let you create multiple 'basedirs' for running seperate qutebrowser instances with different configurations. You could make one configuration basedir with your proxy, and one without, for example.

There's a little more information in `qutebrowser --help`.

**Comment by JasonYangShadow** [comment]
@jgkamat cool feature. I will try that, thanks a lot!!
