### ISSUE TITLE
Consistent HTTPS load status 

### ISSUE THREAD

**Issue by ryan-farley** [qutebrowser/qutebrowser#3417]
While perusing [badssl](https://badssl.com) to test a possible patch for #3401 I encountered what I though was a regression but actualylly wasn't: when answer 'yes' to the 'Continue?' prompt, the load will indeed continue with the URL staying yellow in the pogress bar (indicating `LoadStatus.warn`). When the page is reloaded, or visited at a later time, however, the URL goes green instead (so `LoadStatus.success_https`). This is obviously the result of adding a URL exception for the remainder of the session, but (to me at least) the use of 'Continue?' and this behavior implies (to me at least) that the ignore was, in fact, temporary (because it stops at the session end so I need to agree to continue again after a restart) but the length of a session (for me, again) might be measured in days, so it's easy to brush off even a serious past error as a temporary hiccup even if it is a serious long-lasting vulnerability.

This occurs on latest master with both webengine and webkit.

**Comment by The-Compiler** [comment]
Nothing qutebrowser can do about this without a better API from the backends - see [this QtWebEngine bug](https://bugreports.qt.io/browse/QTBUG-51176) which is somewhat related. Currently, the exceptions are automatically handled by QtWebKit/QtWebEngine.
