### ISSUE TITLE
Website is broken with NAT64

### ISSUE THREAD

**Issue by skorpy2009** [qutebrowser/qutebrowser#3429]
Website is still broken with NAT64
https://nat64check.go6lab.si/v6score/measurement-174040/

**Comment by The-Compiler** [comment]
What can I do about that?

**Comment by The-Compiler** [comment]
Works with https://nat64check.ipv6-lab.net/v6score/measurement-25492/ which checks from the Netherlands instead of Slovenia.

Like I said...

> DNS updates take a while to propagate
