### ISSUE TITLE
qutebrowser can't play HTLM5 on Youtube or Twitch.tv on Mac

### ISSUE THREAD

**Issue by Okyougotme** [qutebrowser/qutebrowser#3437]
![screen shot 2017-12-25 at 4 05 45 pm](https://user-images.githubusercontent.com/34583010/34342970-5fecdddc-e98f-11e7-9454-f147d7fdfb40.jpg)
![screen shot 2017-12-25 at 4 06 14 pm](https://user-images.githubusercontent.com/34583010/34342971-60303e4c-e98f-11e7-868a-9dc7460020a4.jpg)
![screen shot 2017-12-25 at 4 06 48 pm](https://user-images.githubusercontent.com/34583010/34342972-60712600-e98f-11e7-8a30-1c6d32e3d0ff.jpg)
![screen shot 2017-12-25 at 4 07 22 pm](https://user-images.githubusercontent.com/34583010/34342973-60b3e4fe-e98f-11e7-8b7c-2731310e33d5.jpg)

Hello I’m new to using qutebrowser and I am having issues viewing HTML 5 Videos from all sites. I attache photos of Youtube.com and Twitch.tv. Installed qutebrowser via Brew. To the best of knowledge, I have the latest qt 5.10.0 installed. I change set: to Allow-Plugins-True, then installed gstreamer-1.0-1.12.4-x86_64-packages. I’m not sure if I missing something. Any help would be appreciated on resolving this issue. 

> run the following (bind to cmd)
- :bind ;h hint links spawn mpv {hint-url}
- :bind OU hint links spawn streamlink -p mpv {hint-url} best
- :bind ;h hint links spawn streamlink -p mpv {hint-url} best

However, mpv does not seem to respond and I get an spawn error.

**Comment by The-Compiler** [comment]
You'd need to recompile Qt with proprietary codec support to get those running - unfortunately, the Qt coming with homebrew by default (as well as the one bundled in the qutebrowser `.dmg`) doesn't have those enabled.

As for spawning mpv, can't say more without seeing the exact error you get. Probably `mpv` is not in your `$PATH` when you spawn qutebrowser, so you'd need to pass the full path.

**Comment by Okyougotme** [comment]
Thanks

**Comment by Okyougotme** [comment]
Where do I locate Qt

**Comment by lazygreed** [comment]
@The-Compiler compiled Qt with proprietary codecs support, but no changes in `.dmg` or `pip3` versions, qutebrowser can't play any streams
```bash
./configure -release -confirm-license -nomake examples -nomake tests -webengine-proprietary-codecs
make -j6
sudo make install
```
![image](https://user-images.githubusercontent.com/9384565/67685386-a9796e00-f99d-11e9-8848-10124c49d0bb.png)

**Comment by The-Compiler** [comment]
@lazygreed Make sure it's actually using the Qt version you expect by checking the path you get in `:version`. The dmg won't work as it ships with its own Qt. If you want to use a pip-installed qutebrowser, make sure you don't have a pip-installed PyQt5 (which again comes with its own Qt) lying around.

**Comment by lazygreed** [comment]
@The-Compiler what i need to use then? or how to recompile it?
Can you please write a short guide? P:

**Comment by The-Compiler** [comment]
@lazygreed You need to use your self-built Qt. To do so, you need to build PyQt against it and then install that in a place your qutebrowser finds it. Can't say much more than that - if you want to build dependencies from source, you're pretty much on your own, as a lot of things depend on your specific setup.
