### ISSUE TITLE
Can't change passthrough background or forground

### ISSUE THREAD

**Issue by Rantahu** [qutebrowser/qutebrowser#3438]
Not sure whats wrong with this code:
```
## Background color of the statusbar in passthrough mode.
## Type: QssColor
c.colors.statusbar.passthrough.bg = solarized['base02']

## Foreground color of the statusbar in passthrough mode.
## Type: QssColor
c.colors.statusbar.passthrough.fg = solarized['base1']
```

Error:
> Errors occurred while reading config.py: 
While getting 'colors.statusbar.passthrough': No option 'colors.statusbar.passthrough' 
Unhandled exception: 'NoneType' object has no attribute 'bg' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/config/configfiles.py", line 406, in read_config_py
    exec(code, module.__dict__)
  File "/home/rantahu/.config/qutebrowser/config.py", line 295, in <module>
    c.colors.statusbar.passthrough.bg = solarized['base02']
AttributeError: 'NoneType' object has no attribute 'bg'

qutebrowser v1.0.3

**Comment by The-Compiler** [comment]
You might want to upgrade to v1.0.4, but the passthrough color settings aren't part of a release yet (they'll be in v1.1.0).
