### ISSUE TITLE
qutebrowser on mac 

### ISSUE THREAD

**Issue by Okyougotme** [qutebrowser/qutebrowser#3439]
Hello,

Where can I find the Qt to recompile to get HTML 5 videos working?
I know now I have to recompile Qt with proprietary codec support to get HTML 5 videos running.
Please help, I visited (the zip file from git) edited the configure.json and Enable support for proprietary codecs [true]. Not really sure what to do. I

**Comment by The-Compiler** [comment]
This is really a question for Homebrew (if you want to install Qt via that, which is probably the easiest way) and not qutebrowser.

I haven't used Homebrew in a while, but I think you can do `brew edit qt5` and then add the `-proprietary-codecs` switch to the `./configure` arguments there. Note that compiling it will take a long time and require at least 8 GB of RAM - also, you'll need to re-do this for every Qt upgrade.

**Comment by Okyougotme** [comment]
![screen shot 2017-12-27 at 12 04 35 am](https://user-images.githubusercontent.com/34583010/34371245-96647cc0-ea99-11e7-896b-deccc3b4b2e6.jpg)

Which complier should I use? Can I use GCC in Terminal to compile or do I need to download Xcode? I’m need to the browser reason for all the questions.
