### ISSUE TITLE
Option to only show favicons for pinned tabs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3440]
See [this Reddit thread](https://www.reddit.com/r/qutebrowser/comments/7lgdt3/favicon_only_for_pinned_tabs/).

I think the best option would be to adjust `tabs.favicons.show` to have some `only-pinned` value or so.

cc @jgkamat

**Comment by Maiestas28** [comment]
@jgkamat Hey I'll take care of this one but I'm gonna need sometime. Like i mentioned before I'm new to Python.

**Comment by toofar** [comment]
I think the easiest approach would be to do jgkamat's first suggestion and change the definition for `tabs.favicons.show` in `qutebrowser/config/configdata.yml` to be allow three values, similar to `tabs.show` just below it in that file. Then you'll have to search for anywhere that `config.val.tabs.favicons.show` is used and change the logic in those places to check if the tab is pinned if the config value is configured such.

**Comment by Maiestas28** [comment]
Hey guys im really sorry i can't figure it out. You guys can fix it. Thank you for the support.
