### ISSUE TITLE
Spikes in network latency with Qutebrowser.

### ISSUE THREAD

**Issue by chcso** [qutebrowser/qutebrowser#3446]
Although this is an odd issue that I can't seem to trace the root from, anytime Qutebrowser is open on Windows, it causes infrequent MAJOR spikes in my network latency across my Windows install. With just duckduckgo opened, this issue has persisted. I believe the problem is only locally contained to the machine, not the entire network as I don't experience lantency on other machines, nor do I experience this on my Linux build.

If any starting points are given towards tracking the problem, I'll immediately check.
```
qutebrowser v1.0.4
Git commit: v1.0.4-1-g940894a13 (2017-11-28 02:11:06 -0800)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.1
Qt: 5.9.3
PyQt: 5.9.2

sip: 4.19.6
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2h  3 May 2016

Style: QWindowsVistaStyle
Platform: Windows-10-10.0.16299-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.16299, SP0, Multiprocessor Free
```

**Comment by jgkamat** [comment]
Could you see if [qupzilla](https://www.qupzilla.com/) has the same issue? FWIW, I don't think any application should be able to cause network spikes like that...

**Comment by The-Compiler** [comment]
This is [QTBUG-40332](https://bugreports.qt.io/browse/QTBUG-40332) - I suppose qutebrowser could add a workaround, but given that it's only an issue on macOS/Windows, I'd rather wait for Qt 5.9.4 / 5.10.1 and it should be fixed there.

In the meantime, you should be able to add `QT_BEARER_POLL_TIMEOUT` with some large value to your environment variables as a workaround.

**Comment by chcso** [comment]
Alright, thanks for the temproary workaround! Wasn't aware it was known bug.
