### ISSUE TITLE
FreeBSD 11.1 - qutebrowser randomly crashes when browsing most sites

### ISSUE THREAD

**Issue by i-bsd** [qutebrowser/qutebrowser#3455]
Version 1.0.4

Any known issues or fixes?

**Comment by The-Compiler** [comment]
With what backend (`:version`)? Can you get a [stacktrace](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc)? (Even one without debugging symbols would be helpful). If you're using QtWebEngine, can you check whether you see issues with another QtWebEngine project such as QupZilla (a v2.x release) as well?

**Comment by i-bsd** [comment]
qutebrowser v1.0.4
Git commit: 
Backend: new QtWebKit (WebKit 602.1)

CPython: 3.6.4
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19.2
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.11
cssutils: 1.0.2 $Id$
attr: 17.3.0
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.0.2k-freebsd  26 Jan 2017

Style: Qt5CTProxyStyle
Platform: FreeBSD-11.1-RELEASE-amd64-64bit-ELF, 64bit
Frozen: False
Imported from /usr/local/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/local/libexec/qt5, data path: /usr/local/share/qt5
OS Version: ?

**Comment by i-bsd** [comment]
Not sure how to get a stacktrace on FreeBSD though.

**Comment by i-bsd** [comment]
22:03:12 DEBUG    sql        debug:__exit__:264 Historycontains took 0.000121 seconds.
22:03:12 DEBUG    sql        sql:run:168 Running SQL query: "SELECT EXISTS(SELECT * FROM History WHERE url = :val)"
22:03:12 DEBUG    sql        sql:run:171 query bindings: {':val': 'https://www.reddit.com/help/useragreement'}
22:03:12 DEBUG    sql        debug:__exit__:264 Historycontains took 0.000121 seconds.
22:03:12 DEBUG    sql        sql:run:168 Running SQL query: "SELECT EXISTS(SELECT * FROM History WHERE url = :val)"
22:03:12 DEBUG    sql        sql:run:171 query bindings: {':val': 'https://www.reddit.com/help/privacypolicy'}
22:03:12 DEBUG    sql        debug:__exit__:264 Historycontains took 0.000123 seconds.
22:03:12 DEBUG    sql        sql:__init__:150 Preparing SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
22:03:12 DEBUG    sql        sql:run:168 Running SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
22:03:12 DEBUG    sql        sql:run:171 query bindings: {':atime': 1514872992, ':redirect': True, ':title': 'FreeBSD', ':url': 'http://reddit.com/r/freebsd'}
22:03:12 DEBUG    sql        sql:__init__:150 Preparing SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
22:03:12 DEBUG    sql        sql:run:168 Running SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
22:03:12 DEBUG    sql        sql:run:171 query bindings: {':atime': 1514872992, ':redirect': False, ':title': 'FreeBSD', ':url': 'https://www.reddit.com/r/freebsd/'}
22:03:12 DEBUG    sql        sql:__init__:150 Preparing SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
22:03:12 DEBUG    sql        sql:run:168 Running SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
22:03:12 DEBUG    sql        sql:run:171 query bindings: {':last_atime': 1514872992, ':title': 'FreeBSD', ':url': 'https://www.reddit.com/r/freebsd/'}
(gdb) set logging on
Copying output to gdb.txt.
(gdb) bt full
No stack.
(gdb) quit

**Comment by i-bsd** [comment]
Following the instructions, I get "No stack".

But these are the last lines of the debug output I see.

**Comment by The-Compiler** [comment]
Hmm, that's odd... I'd expect gdb to at least give you an exit status or tell you something about how the application exited. If you run it in a terminal, what's the exit status (`echo $?`) after the crash? Also, can you check whether you see the same crashes with [otter-browser](https://otter-browser.org/) (which also has a FreeBSD port)? Make sure you run it with QtWebKit and not QtWebEngine though.

**Comment by i-bsd** [comment]
Exit status is 4. What does that indicate?

I'll try otter-browser and get back to you.

**Comment by The-Compiler** [comment]
Hmm, qutebrowser does exit with that status if there were issues during initialization, which definitely isn't the case here.

Can you please try `gdb $(readlink -f $(which python3)) -ex 'break exit' -ex 'run -m qutebrowser'` and then answer `y` when asked "Make breakpoint pending on future shared library load?"? That should hopefully make it possible to find out whether it's really Python (and thus qutebrowser) code exiting or something else.

**Comment by i-bsd** [comment]
Program received signal SIGSEGV, Segmentation fault.bugging symbols found)..0x0000000813201978 in WTFCrash () from /usr/local/lib/qt5/libQt5WebKit.so.5g

**Comment by i-bsd** [comment]
Does that explain anything?

**Comment by The-Compiler** [comment]
It tells me that this isn't an issue with qutebrowser directly, but with WebKit (cc @annulen) - however, you'd still need to somehow get a complete stacktrace to debug this. I'm closing this for now as there's nothing qutebrowser can do here, but if you follow up with more infos, @annulen can most likely tell you more.

**Comment by i-bsd** [comment]
Frustrating.

Well just for reference, otter-browser with WebKit is not crashing. Would a love a solution to this if anyone's got one.

**Comment by The-Compiler** [comment]
Hmm, it's odd that Otter isn't crashing. Still, I'd need a complete stack trace to say more. Maybe you can get a .core file and then get a stacktrace from that with gdb?
