### ISSUE TITLE
Broken links in documentation on GitHub

### ISSUE THREAD

**Issue by ikn** [qutebrowser/qutebrowser#3457]
I see a number of broken internal links when viewing the documentation in `doc/` as rendered on GitHub - links end with `.html`, where the actual targets end with `.asciidoc`.  For example, [configuring](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc) links to `https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/settings.html` (search for 'settings help page'), but should link to `https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/settings.asciidoc`.

Maybe this is just expected, since it seems to all work fine on [the website](https://www.qutebrowser.org/doc/help/configuring.html).  If that's the case, the issue is that `README.asciidoc` links to documentation files on GitHub, but maybe should link to the website instead.

**Comment by mschilli87** [comment]
@ikn: I think this is 'expected': If you check the [raw version of configuring.asciidoc](https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/help/configuring.asciidoc) you will see that the link does not point to github explicitely but is a relative link.
So on the website, where all asciidocs are converted to html, the link works.
On git, they are just plain text files without clickable links, but github converts the currently viewed asciidoc (but only this one) to html, making the relative link point to github, too, but with the target not being converted to html.

I don't really see anything qutebrowser could do about this, other than maybe explicitely linking to the webpage but that would break offline navigation and other things.
If there is a way to improve browsability on github without breaking anything else, I would be willing to implement it, though.

**Comment by ikn** [comment]
I have not used asciidoc before, but it seems a bit weird that you would refer to files expected to be generated by a specific render target in the documentation source code.  Maybe asciidoc only has one render target?

> other than maybe explicitely linking to the webpage but that would break offline navigation and other things.

You mean linking to the website from the readme?  Is the readme something you expect users to render to HTML and then open in a browser without internet access?  It already links to the website at the top anyway.

Okay, the readme isn't in `doc/`, and it's not on the website (I don't think?), so maybe it could be considered not part of 'the documentation'.  It could, for example, just say: "full documentation can be found on the website \<url\>, or viewed offline by rendering the files in the 'doc' folder".

**Comment by The-Compiler** [comment]
It's quite a mess currently. It's going to be fixed by #345 at some point anyways, but maybe there's something that can be done before that.

**Comment by The-Compiler** [comment]
Maybe [asciidoc cross references](http://asciidoctor.org/docs/asciidoc-writers-guide/#cross-references) work everywhere?

**Comment by bengartner** [comment]
I'm working on a fix based on this:
https://asciidoctor.org/docs/user-manual/#navigating-between-source-files

Will be my first PR :)

**Comment by The-Compiler** [comment]
Fixed in #4202 - thanks @bengartner, didn't know that was possible!
