### ISSUE TITLE
"Failed to open file" warning with Qt 5.10

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3459]
After upgrading to Qt 5.10, I noticed this (with e.g. `--temp-basedir`):

```
[0103/104952.523679:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/florian/#14750431 (deleted)
  Error: No such file or directory
```

It looks like it's [coming from Chromium](https://code.woboq.org/qt5/qtwebengine/src/3rdparty/chromium/base/debug/stack_trace_posix.cc.html#617), but I'm not sure what causes it, I can't see it with e.g. QupZilla it seems?

**Comment by lahwaacz** [comment]
I'm also getting a similar warning:
```
[0116/133327.700515:WARNING:stack_trace_posix.cc(648)] Failed to open file: /tmp/.gl4KTWEs (deleted)
  Error: No such file or directory
```

See also the `qutebrowser --version` output in #3447.

**Comment by urbainvaes** [comment]
I'm also getting this warning, with this output of `qutebrowser --version`:

    qutebrowser v1.1.1
    Git commit: 
    Backend: QtWebEngine (Chromium 61.0.3163.140)

    CPython: 3.6.4
    Qt: 5.10.1
    PyQt: 5.10

    sip: 4.19.7
    colorama: 0.3.9
    pypeg2: 2.15
    jinja2: 2.10
    pygments: 2.2.0
    yaml: 3.12
    cssutils: no
    attr: 17.4.0
    PyQt5.QtWebEngineWidgets: yes
    PyQt5.QtWebKitWidgets: yes
    pdf.js: no
    sqlite: 3.22.0
    QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

    Style: QFusionStyle
    Platform: Linux-4.15.5-1-ARCH-x86_64-with-arch, 64bit
    Linux distribution: Arch Linux (arch)
    Frozen: False
    Imported from /usr/lib/python3.6/site-packages/qutebrowser
    Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

    Paths:
    cache: /home/urbain/.cache/qutebrowser
    config: /home/urbain/.config/qutebrowser
    data: /home/urbain/.local/share/qutebrowser
    runtime: /run/user/1000/qutebrowser
    system data: /usr/share/qutebrowser

In my case the browser does not open because of it. Is there a workaround to make it work?

**Comment by The-Compiler** [comment]
> In my case the browser does not open because of it. Is there a workaround to make it work?

That's most likely unrelated to the issue. I'd suggest you drop by in the [IRC channel](https://github.com/qutebrowser/qutebrowser#getting-help) to track down what's happening.

**Comment by The-Compiler** [comment]
Someone else reported this upstream as [QTBUG-68547](https://bugreports.qt.io/browse/QTBUG-68547).

**Comment by legallyrobert** [comment]
Is there any fix for this issue? I followed the issue upstream and found nothing.

Trying to run on a fresh arch install, I've tried both building from source and pacman install.

**Comment by The-Compiler** [comment]
It's a harmless warning.

**Comment by tallero** [comment]
What is the latest stable version of QtWebEngine?

**Comment by The-Compiler** [comment]
@tallero that seems unrelated to this issue, and is something you could easily [look up yourself](https://en.wikipedia.org/wiki/List_of_Qt_releases) (5.11.2)

**Comment by tallero** [comment]
I asked because the upstream [bug](https://bugreports.qt.io/browse/QTBUG-68547) includes a patch which is included in 5.12 Beta 1.

Since QtWebEngine apparently does not have its own official development page on which one can check the latest version page apart from this [repo](https://github.com/qt/qtwebengine), which (is probably a mirror and) has both [5.12](https://github.com/qt/qtwebengine/tree/5.12) and [5.12.0](https://github.com/qt/qtwebengine/tree/5.12.0) branches, I was just wondering if I am just getting an old version from my distro.

The repo even has a 5.11.3 branch!

**Comment by The-Compiler** [comment]
QtWebEngine is released together with Qt itself - the branches are for upcoming versions, you might want to look at the tags instead. The bug already is closed. :wink:

**Comment by tallero** [comment]
Sorry! I thought I could not post in closed bugs!
