### ISSUE TITLE
Answering 'no' to :tab-only prompt with pinned tabs should close non-pinned tabs

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#3461]
If anyone prefers the current behavior of `<no>` when running `:tab-only`, please let me know here!

This will change the behavior of `<no>` to 'close all non-pinned tabs except the current one' instead of 'don't close any tabs'.

```
<hdqn> [20:54:21] :tab-only prompts to close pinned tabs and fails
    completely if denied
<tyil> [20:54:34] The-Compiler: yeah, its weird, bu tall I wanted was
    a working qutebrowser :p
<The-Compiler> [20:54:49] hdqn: I think that's intended
<hdqn> [20:55:05] I suggest at least having a setting for this - I
    expected to keep the current tab and all pinned tabs
<The-Compiler> [20:55:47] jgkamat: what do you think? ^
<hdqn> [20:59:18] 'pinned' is generally considered to mean 'immune to
    auto-moving/sorting/deletion', 'fixed in place', and there is
    literally 0 sane reason to keep :tab-only atomic
<hdqn> [21:00:29] of course I'm aware that I can just submit a PR, so
    I'll leave that here for you guys to consider ^-^
<hdqn> [21:00:50] qb is making my life so much easier <3
<***> Playback Complete.
<jgkamat> hmmmmmmmmm
<jgkamat> hdqn: so you think that if you said 'no' to the prompt, it
    should delete all non-pinned tabs?
<jgkamat> adding a setting would be easy but I don't think it would be
    needed (I don't think people would mind what happened too much). I
    would personally prefer changing the <no> behavior if that's what
    people wanted
<The-Compiler> I don't mind much either way, but I think hdqn has a
    point
<The-Compiler> "oh, I have pinned tabs, now I don't want to close
    anything at all" seems to make less sense to me than "hm, okay, I
    want to keep the pinned ones but still close the rest"
```

**Comment by Maiestas28** [comment]
Hey, this is my first time on Git. Can i contribute and id like some guidance too regarding the project and PR. If this is too advanced for me, let me know.

**Comment by jgkamat** [comment]
@Maiestas28 hey, thanks for dropping by! This issue is not a good place to start, because I've already created a patch to fix it (#3467) (sorry for marking it as a beginner issue).

A very similar issue that hasn't been worked on yet is https://github.com/qutebrowser/qutebrowser/issues/3440, which I think is a great starting point for new contributors, since it's not too complicated. If you would like to work on that issue, I'd be happy to show you where the changes would need to take place.

As for general tips, the [contributing guidelines](https://www.qutebrowser.org/doc/contributing.html) have lots of general getting-started tips for qutebrowser, so I'd reccomend going over them.

If you have any quesions while working, I'd reccomend dropping by #qutebrowser on freenode, or asking questions on the related issue.

**Comment by Maiestas28** [comment]
Thanks for responding man. I really appreciate it.  And yes I’ll look into
#3440.
What coding skills would I need to contribute fin yiu don’t mind me asking
? Can I reach out to you here if anything else or is there any other app or
forum I should just join ?
Thank you.

**Comment by Maiestas28** [comment]
And yes do show me where to go about the #3440 issue. Thanks again.

**Comment by jgkamat** [comment]
@Maiestas28, for tips on starting the #3440 issue, I would start by just looking for usages of `tabs.favicons.show`, which controls showing favicons in general. Once this is implemented, all usages of this variable will probably have to be updated (to handle the third setting), so I would go through them all. The main place I could find which handles where favicons are shown or not is [here](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/mainwindow/tabbedbrowser.py#L618), although, I think there are a couple more places in that file which need to be changed as well. I would suggest making a helper function to determine if a tab should have it's favicon shown. 

You should be able to get the 'pinned status' of a tab with `tab.data.pinned`, there are a couple examples in the same file.

Once you're actually ready to change the setting itself, you would want to look at the [definition of tabs.favicons.show](https://github.com/qutebrowser/qutebrowser/blob/444f0a36dfba2f54a279b0ca8dffd2c601211666/qutebrowser/config/configdata.yml#L1205), and change the type from a boolean to a string (I think). You can find examples of how to do that in other settings in that file.

In addition, we'll have to add the favicon whenever a tab is pinned and remove it when a tab is unpinned (with this setting enabled). I haven't thought this part through, but the function which sets tabs pinned/unpinned is [here](https://github.com/qutebrowser/qutebrowser/blob/444f0a36dfba2f54a279b0ca8dffd2c601211666/qutebrowser/mainwindow/tabwidget.py#L98). I'd try and tackle this bit once you have the basic functionality down.

If you have more questions, I would reccomend getting on the irc channel (#qutebrowser on freenode) or sending a mail to the [mailing list](mailto:qutebrowser@lists.qutebrowser.org). This issue is actually not related to #3440, so its not a good idea to continue the conversation here (if anything, it should happen in the comments under #3440). Asking questions is welcome though, working on a large codebase is quite daunting at first :)

**Comment by Maiestas28** [comment]
Thank you. I’ll do the required.
