### ISSUE TITLE
keybinding/hints/popup on fullscreen youtube.

### ISSUE THREAD

**Issue by Brynildsen** [qutebrowser/qutebrowser#3466]
qutebrowser v1.0.4

I have the timeout setting for my keybinding/hint-popup-info (not sure what it is called) set to 0, and use Escape to kill it again. It is the `c.input.partial_timeout = 0` in my config.py
(The zero setting is used to have better time to look up whatever keybinding I might have forgotten)

When running youtube(and probably other video sites) fullscreen and hitting a key that brings up hint info popup it shows up on top of video as it is supposed to, but when hitting Escape to make it dissapear it also exits fullscreen.

Escape should have first priority on those hints/popups IF they're active and perform that action first, even though Escape also have other functions, such as to exit fullscreen.

Edit: Found out I can make the keybind/hint/popup dissappear in fullscreen video mode by hitting Ctrl+v twice. Should still could be performed by Escape though to keep it intuitive for the user.

**Comment by jgkamat** [comment]
Currently, `<esc>` is bound by default to:

- `:clear-keychain`, which clears partially entered keys.
- `:search`, which clears searches
- `:fullscreen --leave`, which clears fullscreen.

Right now, key input takes place in normal mode, so it's not possible to simply move the fullscreen leave away from the hint clear.

I'm not sure if there's a clean way to implement this, maybe making a new command which combines the above 3 in a 'cascading way'.

**Comment by Brynildsen** [comment]
Found out I can make the hints go away by hitting Ctrl-v twice.. without exiting fullscreen mode. It might be the simplest workaround. I usually bring them up by accident because I use vimkeys to fast forward and set volume etc.. and youtube has some bindings of its own also for things like subtitles etc.. and if you hit a wrong key that is part of a binding, the info pops up.

2xCtrl-v did the trick.

**Comment by The-Compiler** [comment]
Making this work nicer would mean moving away from the simple "a key is bound to commands" model for Escape, which is something I'd rather not do.

**Comment by Brynildsen** [comment]
No prob. As mentioned Ctrl-V can be used as a workaround when dealing with a "player".

I was just expecting it to react like in this example [here](https://i3wm.org/screenshots/#/screenshots/i3-1.png) when scrolling through gallery, and pressing first part of a keybinding which makes it pop up. The Escape button still handles qutebrowser own functions first, and cancels the keybinding popup hint, but without closing down what is being watched in the browser it self. 

Dont waste time on it, just mention it in the documentation and people have a much easier time figuring out themselves. :)
