### ISSUE TITLE
view-source: scheme doesn't load qutebrowser's internal JavaScript

### ISSUE THREAD

**Issue by bheadmaster** [qutebrowser/qutebrowser#3490]
As stated in the title, keybindings for scrolling - gg, G, ctrl+d and ctrl+u - don't work in view-source mode, though 'j' and 'k' work normally. I understand that most users don't scroll that much through source, but it would still be a nice thing to have, and doesn't seem much different from ordinary page scrolling.

***

qutebrowser v1.0.4
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.9.2

sip: 4.19.6
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.14.12-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/lark/.cache/qutebrowser
config: /home/lark/.config/qutebrowser
data: /home/lark/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Comment by jgkamat** [comment]
Hmm, all of these keybinds seem to work for me, (wow, @qutebrowser-bot is magic!), can you test with `--temp-basedir`? I tested with the view-source of this page, on qtwebengine 5.7.1, on a90730bea71a35059be6f203f74dfdbd2475cf24.

**Comment by bheadmaster** [comment]
Oh, right. It works for me as well when I enter it with a "view-source" command. It only stops working when I open the source directly with "open view-source:https://github.com/qutebrowser/qutebrowser/issues/3490".

I don't know if this is bug or not anymore, although it seems redudant to have two ways of browsing the code of a page.

**Comment by The-Compiler** [comment]
The `view-source:` scheme is handled by QtWebEngine while `:view-source` is done by qutebrowser (and still needed for QtWebKit). See #2395 re using the `view-source:` scheme where possible (cc @lahwaacz who also reported this issue there).

Indeed those bindings (and also e.g. hints) don't work, because qutebrowser's JavaScript isn't loaded by QtWebEngine - also reproducible with this:

```cpp
#include <QApplication>
#include <QWebEngineView>
#include <QWebEngineScript>
#include <QWebEngineScriptCollection>
#include <QUrl>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QWebEngineView view;

    QWebEngineScript script;
    script.setInjectionPoint(QWebEngineScript::DocumentCreation);
    // script.setInjectionPoint(QWebEngineScript::DocumentReady);
    script.setSourceCode("console.log('Hello World!');");
    view.page()->scripts().insert(script);

    view.load(QUrl("view-source:https://qutebrowser.org"));
    view.show();
    return app.exec();
}
```

We should probably report that upstream though, and seeing that using `DocumentReady` works, we can probably work around the issue.

**Comment by mjauvin** [comment]
@The-Compiler you mentioned this was working using DocumentReady, so I tried the code below and it fixes the problem (injecting qb js scripts at DocumentReady instead of DocumentCreation):
```
diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index 4129c4a59..2792c2bbd 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -613,7 +613,7 @@ class WebEngineTab(browsertab.AbstractTab):
             utils.read_file('javascript/caret.js'),
         ])
         script = QWebEngineScript()
-        script.setInjectionPoint(QWebEngineScript.DocumentCreation)
+        script.setInjectionPoint(QWebEngineScript.DocumentReady)
         script.setSourceCode(js_code)
 
         page = self._widget.page()
```

**Comment by The-Compiler** [comment]
Yeah - the question is what the implications of doing this globally are; or if we can check whether it's a `view-source` URL at that early stage. Also, we should probably still report this upstream.

**Comment by mjauvin** [comment]
I agree.
I'll dig a bit more and also report this upstream if I can.

**Comment by mjauvin** [comment]
Could be feasible if we called _init_js() within openurl(). Any downside that you see offhand?

**Comment by The-Compiler** [comment]
You'd need to make sure that scripts are still only initialized once. I'd probably prefer just setting it to `DocumentReady` unconditionally instead - but it depends on how much that delays things, and what is delayed exactly. I won't have time to look into it in the next couple of weeks.

**Comment by The-Compiler** [comment]
Reported upstream as [QTBUG-66011](https://bugreports.qt.io/browse/QTBUG-66011) and worked around in qutebrowser now.
