### ISSUE TITLE
Makefile error: install: omitting directory 'scripts/testbrowser'

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#3492]
I can't build 1.1.0 with the Makefile, I get the following error:
```
install: omitting directory 'scripts/testbrowser'
```

The following change in the Makefile seems to do it:
```
-	  scripts/testbrowser_cpp scripts/asciidoc2html.py scripts/setupcommon.py \
+	  scripts/testbrowser scripts/asciidoc2html.py scripts/setupcommon.py \
```

**Comment by The-Compiler** [comment]
Whoops, dang... I fixed this and added a check to the release script to make sure this hopefully doesn't happen again. 😊 Thanks!
