### ISSUE TITLE
No notifications with qtwebengine

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#3493]
```
qutebrowser --temp-basedir --enable-webengine-inspector http://cssdeck.com/labs/gltixsmt
```

 - `content.notifications` defaults to `ask`

Expected behavior: ask permission to show messages, show a message
Observed behavior: "denied" printed to console (shown via `:inspector`)

It seems that notifications aren't implemented yet for webengine. I could poke at it.

**Comment by The-Compiler** [comment]
Notifications aren't implemented yet in QtWebEngine itself. This will hopefully change with Qt 5.11 in May: https://codereview.qt-project.org/#/c/205716/ (see #3010), at least if it gets in before the feature freeze at end of January...

**Comment by wernerb** [comment]
This is now implemented in qt but still missing from qutebrowser

**Comment by The-Compiler** [comment]
@wernerb huh? Wrong, this still isn't implemented in Qt.

**Comment by wernerb** [comment]
Bweh sorry, I stand corrected!

**Comment by firecat53** [comment]
Sorry to necro this, but I see that the above mentioned bug is fixed in qt5-webengine 5.13 which is now released. Will this or is this feature already available in qtbrowser? (Currently not working in qutebrowser 1.6.3). Thanks!

**Comment by The-Compiler** [comment]
@firecat53 No worries! FWIW it already works for me (#4780 is just about improving how notifications are shown). However, the default Qt 5.13 notifications work via a tray icon, so you'll need a system tray running.

**Comment by firecat53** [comment]
So, what do you mean by "notifications work via a tray icon"? I'm running i3 with the system tray provided by i3pystatus, which typically shows tray icons on my computer for things like KeepassXC and Insync but I don't see any sign of qutebrowser notifications. I thought most notifications worked using the 'notify-send' nomenclature. Is there a different notification framework that qutebrowser uses? Thanks!

**Comment by toofar** [comment]
It uses [it's own thing](https://codereview.qt-project.org/c/qt/qtwebengine/+/205716/16/src/webenginewidgets/api/qwebenginenotificationpresenter.cpp). We will surely add our own libnotify based presenter in the future (not even windows uses systray bubbles anymore) but for now it's using the upstream fallback.

**Comment by The-Compiler** [comment]
Sorry, my bad, it doesn't work yet - when I tested it, I had to add a hack because the notification permission wasn't exposed via PyQt yet.

However, it should work (via a systemtray icon) with the current git master as soon as PyQt 5.13 is out (which is hopefully in the next couple of days).

**Comment by arjvik** [comment]
Sorry to bug you, but any update on this? I don't see notifications working.

```
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8

CPython: 3.8.2
PyQt: 5.14.1
```

**Comment by The-Compiler** [comment]
@arjvik Do you have a system tray running?

**Comment by arjvik** [comment]
Yes I do. `nm-applet` and `blueman-applet` show up there.

Thanks for the fast response btw!

**Comment by The-Compiler** [comment]
@arjvik Ah, you're running Qt 5.12. Notification support was added in 5.13.

**Comment by arjvik** [comment]
Dang, ok. I'm using the version of Qt that came with Ubuntu 20.04, and I installed Qutebrowser from the repos. If I install qutebrowser into a virtualenv, would I be able to use a different version of Qt from my system? I'd rather not replace my systemwide Qt because that will break other things.

**Comment by The-Compiler** [comment]
Yep, Qt 5.14 didn't make the deadline for Ubuntu 20.04, so they used the 5.12 LTS - thus, notification support will come to Ubuntu LTS users in April 2022 :wink:

Indeed you can, see the related [install docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#tox). The main drawback is that you won't get proprietary codec support.

**Comment by arjvik** [comment]
2 years? Oh no... :sob:. I'll probably upgrade to 20.10 when that comes out so hopefully Qt 5.14 will be included in those repos.

I will try installing via virtualenv later, thanks!
