### ISSUE TITLE
Unhandled exception: 'caret' when reading config.py

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3494]
When I run `:config-source`, I get this error:
```
ERROR: Errors occurred while reading config.py:
  Unhandled exception: 'caret'
```
What does it mean? Why does the error happen only in `:config-source` and not when starting the browser?

My `config.py` is [here](https://github.com/lahwaacz/dotfiles/blob/a5f2474d5cf297419df88b115072a3e5370c5e8b/.config/qutebrowser/config.py).

**Comment by The-Compiler** [comment]
My first guess is that what's happening is a `KeyError`, but we only print the exception text and not the type:

```python
>>> d = {}
>>> d['caret']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'caret'
```

qutebrowser should definitely print more there!

As for why it's happening: You read the default bindings in `"caret": c.bindings.default["caret"],` and then later in your config do `c.bindings.default = {}` - so the second time your `config.py` runs, you can't read them anymore as they're gone.

**Comment by lahwaacz** [comment]
Oh indeed, thanks for the explanation!
