### ISSUE TITLE
window.print() support

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3495]
We can probably hack in `window.print()` support similar to how QupZilla did it 😆 

https://github.com/QupZilla/qupzilla/commit/d3f0d766fb052dc504de2426d42f235d96b5eb60

**Comment by toofar** [comment]
Heh looks like carewolf suggestion using window.location as RPC a while ago https://github.com/qutebrowser/qutebrowser/issues/27#issuecomment-219070932

**Comment by sarehag** [comment]
I have a suggestion for a solution for this. Will open pull request soon, if the tests pass.

**Comment by The-Compiler** [comment]
Note that we can't prevent sandboxed iframes from using `window.print()` that way: https://www.chromestatus.com/feature/4747009953103872

Chromium and Firefox seem to do that, but e.g. QtWebKit doesn't, so I'm fine with that.
