### ISSUE TITLE
Hints should be followed automatically if all remaining hints point to the same URL

### ISSUE THREAD

**Issue by radgeRayden** [qutebrowser/qutebrowser#3496]
When on number mode most of the time when I write out what I'm trying to follow (instead of the number) I end up having to type a number anyway, since there are duplicate links with the same text. For example, a github project page will contain multiple references to the project link or author page link. Multiple ways to go to the home page of a website, etc.
Now I realize different links will present the same text very often, but I think it's reasonable that if they all share the same URL this is a non issue.

**Comment by The-Compiler** [comment]
See #1955 / #71
