### ISSUE TITLE
Greasemonkey userscripts not starting properly on pages opened with a repeated call of window.open(url)

### ISSUE THREAD

**Issue by nonamethanks** [qutebrowser/qutebrowser#3497]
I couldn't find an easily reproducible version, because my examples on sites I use didn't fail consistently, or require login with privileged accounts, so I wrote an adhoc example that consistently shows this bug.

I have tested it with `qutebrowser --basedir <empty directory>` and with only the following userscript installed thereafter:

```
// ==UserScript==
// @namespace    letstestthis
// @name         Let's Test This
// @match        http://nonamethanks.berry.seedhost.eu/test/test/
// @grant        none
// @run-at       document-idle
// ==/UserScript==

var img = document.getElementById('image');
function TestingThis(){
    img.style.width = 'auto';
    img.style.height = 'auto';
    img.style.maxWidth = '90vw';
    img.style.maxHeight = '100vh';
}
TestingThis()
```

On the page http://nonamethanks.berry.seedhost.eu/test/, for which the source is
` <a onclick="window.open('./test/');window.open('./test/')" href="#" class="ayy">Click here</a> `,
clicking on the link launches two different tabs to http://nonamethanks.berry.seedhost.eu/test/test/.
In these two tabs the userscript won't work properly, and the only image displayed in there won't be resized. However opening the above link manually will show that the userscript does indeed work.
Curiously enough, not even refreshing the tabs make the userscripts work - it's as if it was not loaded at all for those specific tabs.

Also,  "c.content.javascript.can_open_tabs_automatically" needs to be set to True for this reproduction to work. If it's set to false, only one page will be opened, and the userscript will work in there.

This bug is also not limited just to this kind of userscript, seems no userscript at all is loaded in these pages - or at least on another site I tested it with that's what I managed to see.

On both Firefox and Chromium instead the userscript works properly in all cases.
Tested on Qutebrowser v1.1.0, git commit 06075a497, QT 5.10, and QtWebEngine as backend.

**Comment by The-Compiler** [comment]
This might also be related to #3377.

**Comment by toofar** [comment]
This does seem like an issue in qtwebengine. Because this example works with webkit and qutebrowser doesn't decide when to inject scripts or when not to. It is something in webengine, probably the user_resoure_controller. Not sure whether it is a signal not being recieved though or some dependant state not being set right.

**Comment by toofar** [comment]
I've opened a bug with QtWebEngine for this now: https://bugreports.qt.io/browse/QTBUG-66336
Not the most helpful report but enough information to reproduce it is there so hopefully someone picks it up.

**Comment by The-Compiler** [comment]
FWIW if someone here has a bugreports.qt.io account, can't hurt to give that issue a vote :wink:

**Comment by mschilli87** [comment]
@The-Compiler 
>FWIW if someone here has a bugreports.qt.io account, can't hurt to give that issue a vote :wink:

FWIW I didn't a bugreports.qt.io account but figured as I'm using a Qt based browser, it can't hurt either to simply create one. :wink:

**Comment by The-Compiler** [comment]
Can someone try with Qt 5.10.1 (or 5.9.4 / 5.11 Alpha)?

**Comment by nemanjan00** [comment]
I have Qt 5.10.1 and I still have problem with userscripts not loading properly.

**Comment by nonamethanks** [comment]
I can confirm that this issue is fixed for me using the latest master.

**Comment by The-Compiler** [comment]
Yay! Assuming this is fixed then. @nemanjan00 if you still have issues with the latest master, let me know!
