### ISSUE TITLE
Restore windows and pinned tabs after crash

### ISSUE THREAD

**Issue by julkip** [qutebrowser/qutebrowser#3500]
When qutebrowser chrashes and restarts all pinned tabs are unpinned and all tabs from window 1 are opened in window 0 (i assume if you have more than 2 windows all tabs would be opened in window 0).

Version Info

qutebrowser v1.1.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.9.2

sip: 4.19.6
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QGtkStyle
Platform: Linux-4.14.13-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Comment by The-Compiler** [comment]
That's intended - it uses a fail-safe way of restoring things which doesn't rely on storing/parsing sessions internally. That way you don't have the same exact state after a crash, but it's much simpler and thus more likely to work out even after a crash and being in an unknown state.

**Comment by rperce** [comment]
@julkip you may find it helpful to load your pinned tabs and run `:session-save pins`; after a crash you can just `:session-load pins` to get them back and pinned and all.
