### ISSUE TITLE
Sane default keybindings for entering and leaving passthrough mode

### ISSUE THREAD

**Issue by quuz** [qutebrowser/qutebrowser#3502]
`ctrl-v` doesn't make sense as the default binding for entering and leaving passthrough mode. Pasting with `ctrl-v` is common and useful both inside and outside of passthrough mode. I've been using `ctrl-e` instead but there may be better options.

**Comment by The-Compiler** [comment]
`ctrl-v` is the usual way to pass through a keypress literally in vim-like applications (including vim itself), so I'd rather not change the default binding (especially not after so many people getting used to it in many applications).
