### ISSUE TITLE
Make it clearer that autoconfig.yml isn't getting loaded

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3504]
Some people seem to be confused about their `autoconfig.yml` not being loaded when they (often accidentally) created a config.py. Some ideas:

- [x] Check how visible this is in the generated `config.py`
- [x] Also add a comment to `autoconfig.yml`
- [x] Maybe require a confirmation for `:config-write-py`

**Comment by Jan-PieterBaert** [comment]
@The-Compiler anything you want to see added that wasn't added in #4941 and related PRs #4959 and #4974 ?

**Comment by The-Compiler** [comment]
@Jan-PieterBaert See the original issue text :wink: I think `:config-write-py` is okay (it's about the first thing mentioned in the generated config), but `autoconfig.yml` files should have a comment pointing this out as well.

**Comment by The-Compiler** [comment]
Nothing left to do here - thanks @Jan-PieterBaert for all the contributions related to this!

**Comment by Jan-PieterBaert** [comment]
It was fun to do :)
