### ISSUE TITLE
Freeze when page is finished loading

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#3507]
This has been present for a while, but I didn't look at it until now.

Qutebrowser has a short freeze whenever a page finishes loading, [here's a video of what I see](https://www.youtube.com/watch?v=Zlb4ZeQ8QFU&feature=youtu.be).

I've traced this down to being at least partially related to inserting sql entries after a page is done loading (which takes about 0.2s, and there are two insertions).

I'm not sure if it would be feasable to run these sql queries in the background, but I think that would be a nice feature to have.

[Here's a small patch which tries to solve this](http://paste.debian.net/1005933), but this is probably being done the wrong way (we would want to use `async` and `await` perhaps in python3.5), and I'm not sure if it's safe to insert multiple rows non-sequentially into sqlite.

**Comment by The-Compiler** [comment]
I don't think I can reproduce this - what I've seen however, are longer (~5s) hangs happening once in a week or so. I've never been able to track them down though, but at least someone else reported them as well. How did you track down yours?

I don't really understand why your patch works 😆 I'd have thought that `_insert_async` would never run, as there's no asyncio event loop running. Apparently it *does* work though, and run `_insert_async` in its own thread somehow?

I'm also not sure whether everything related in Qt/sqlite is threadsafe - [the docs seem to suggest](https://sqlite.org/threadsafe.html) that sqlite is by default, unless that was disabled at compile time...

cc @lahwaacz @rcorre

**Comment by lahwaacz** [comment]
Does it happen consistently after every page load? Do the two inserts take about the same time or does one take much longer than the other?

**Comment by jgkamat** [comment]
After a little more thourough look at the timing, it actually looks like it's taking about `0.1` seconds on average (times 2). Here's a quick log of the timing per insert call on my computer, when refreshing the ddg home page over and over. It seems to happen on every page load.

```
-------------
0:00:00.113447
0:00:00.150297
-------------
0:00:00.131510
0:00:00.133655
-------------
0:00:00.123169
0:00:00.125256
-------------
0:00:00.098100
0:00:00.125303
-------------
0:00:00.104968
0:00:00.100295
-------------
0:00:00.139670
0:00:00.150273
-------------
0:00:00.121470
0:00:00.133733
-------------
0:00:00.121559
0:00:00.125163
-------------
0:00:00.114977
0:00:00.091922
-------------
0:00:00.138106
0:00:00.133492
-------------
0:00:00.137741
0:00:00.133697
-------------
0:00:00.139432
0:00:00.193092
-------------
0:00:00.107337
0:00:00.125330
-------------
0:00:00.355411
0:00:00.125399
-------------
0:00:00.157408
0:00:00.125306
-------------
```

created with http://paste.debian.net/1005994/.

I also noticed that my hard disk light turns on whenever the page load happens, so it's possible that if you have an SSD this isn't noticable. 

I'm not entirely sure how my patch works either :P , I think it hijacks the default loop that's created in python (which we wouldn't want to do probably). The real asyncio stuff needs it's own event loop.

**Comment by lahwaacz** [comment]
Can you check it again with a `--basedir` placed on a really slow device (e.g. an old USB flash drive) and then in a tmpfs? If it's a disk latency problem, enabling the WAL mode (see https://github.com/qutebrowser/qutebrowser/issues/2930#issuecomment-325199342) would probably help a lot and there is even [PRAGMA synchronous](https://sqlite.org/pragma.html#pragma_synchronous).

**Comment by jgkamat** [comment]
I didn't have a flash drive on hand, but running inside a tempfs solved the problem completely!

I don't have too much experience with sqlite, but I'll take a closer look at the WAL.

**Comment by jgkamat** [comment]
Turns out that I can just run:

`PRAGMA journal_mode=wal;`

on my existing sqlite history file, and doing so almost eliminated the freezes for me. There's still a bit of lag, but it's a lot less now! 

I think it would be a good idea to enable the WAL, if it didn't cause any other problems.

**Comment by rcorre** [comment]
> I think it would be a good idea to enable the WAL, if it didn't cause any other problems

I'm curious if there are any drawbacks to WAL, and whether PERSIST or TRUNCATE might solve the problem as well, as the [docs](https://sqlite.org/pragma.html#pragma_journal_mode) claim that both are optimizations.

Of course, if WAL can actually solve #2930 that would be great...

**Comment by The-Compiler** [comment]
The [WAL docs](https://sqlite.org/wal.html) talk about the drawbacks there are, but I don't think any of them are relevant for us - especially because it just falls back on DELETE if WAL can't be turned on (like on a network filesystem).

I also think we can turn on some further optimizations at that point:

- [locking_mode = EXCLUSIVE](https://sqlite.org/pragma.html#pragma_locking_mode) which avoids needing shared memory, as we don't need the database to be accessible by other applications while qutebrowser runs.
- [synchronous = NORMAL](https://sqlite.org/pragma.html#pragma_synchronous) to have fewer disk writes: "When synchronous is NORMAL (1), the SQLite database engine will still sync at the most critical moments, but less often than in FULL mode. There is a very small (though non-zero) chance that a power failure at just the wrong time could corrupt the database in NORMAL mode. But in practice, you are more likely to suffer a catastrophic disk failure or some other unrecoverable hardware fault. Many applications choose NORMAL when in WAL mode."

**Comment by rcorre** [comment]
`journal_mode=WAL` and `synchronous=NORMAL` sound good to me. I have a _slight_ worry that `locking_mode=EXCLUSIVE` could block a user wanting to access the database while qutebrowser is running. However, if I'm understadning WAL correctly it will still allow read access.

Also, setting `journal_mode` to an unknown value doesn't error for me, so this is probably safe even on pre 3.7 sqlite.

**Comment by rcorre** [comment]
Looks like you can't read synchronously from another process. While writing a patch for this I suspended the browser and tried to check the journal_mode:

```
[rcorre@padavis qutebrowser]$ sqlite3 /tmp/qute-basedir/data/history.sqlite 'PRAGMA journal_mode'
Error: database is locked
```
