### ISSUE TITLE
Completing URL with '&' shows '&amp;'

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3508]
Consider this URL: https://wiki.archlinux.org/api.php?action=query&pageids=12345

After writing `action=query` in the `:open` prompt, it is highlighted correctly. After adding `&` (i.e. the filter is `action=query&`), the URL is changed to `https://wiki.archlinux.org/api.php?action=query&amp;pageids=12345` in the completer and the pattern is still highlighted. After adding anything what follows in the URL, e.g. `action=query&pageids`, the URL is changed back to the original and nothing is highlighted, although the URL still matches the filter as expected.

**Comment by The-Compiler** [comment]
cc @rcorre

**Comment by rcorre** [comment]
The problem is `html.escape` at https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/completion/completiondelegate.py#L207. Removing it resolves this, but presumably could break the html in other cases

**Comment by lahwaacz** [comment]
What if you _add_ another `html.escape` for the pattern?

```python
                text = re.sub(re.escape(html.escape(pattern)).replace(r'\ ', r'|'),
                              repl, html.escape(self._opt.text),
                              flags=re.IGNORECASE)
```
