### ISSUE TITLE
Tabs error indicator color is not shown for Windows builds.

### ISSUE THREAD

**Issue by bitraid** [qutebrowser/qutebrowser#3518]
When a site fails to load, the tab color indicator does not change.
This started happening from build 0.11.0 - only on Windows.
I've tested it on multiple systems running Windows 10 x64, v1603 and 1709.

**Comment by The-Compiler** [comment]
Reproduced with http://httpbin.org/status/404

**Comment by bitraid** [comment]
I just tested it with QT 5.10 and it works fine.

**Comment by bitraid** [comment]
So does build 1.1.2.
