### ISSUE TITLE
[Ubuntu 14.04] Can't install: "No module named virtualenv"

### ISSUE THREAD

**Issue by mhep** [qutebrowser/qutebrowser#352]
After installing all dependencies for Ubuntu I get the following error upon trying to run the `init_venv.py` script:

`/usr/bin/python3: No module named virtualenv`

**Comment by GabrielBB** [comment]
@The-Compiler Oh my God. "make sure python-virtualenv (not python3-virtualenv as the documentation said earlier) is installed." <- I don't know what qutebrowser is but I had this error with another project and that fixed it. I did a lot of google searches and only here I found the solution.

**Comment by ninewise** [comment]
Join qutebrowser. Your problems *will* be solved.
