### ISSUE TITLE
Tab-give should close window if no tabs left

### ISSUE THREAD

**Issue by edi9999** [qutebrowser/qutebrowser#3527]
Currently if I have two windows open, and the second window contains only one tab.

I I go to the second window and write `:tab-give 0` , the tab is "cloned" to the window 0, but doesn't disappear form the window 1.

I would expect the window 1 to be closed when doing this.

**Comment by The-Compiler** [comment]
cc @Enzime

**Comment by Enzime** [comment]
I was thinking we should make a config option for this, as some people might want the window to remain especially with tiling window managers to maintain the layout.

**Comment by zaowen** [comment]
I also found this to be a problem. And would like to fix it.
Would anyone mind if this was assigned to me?

**Comment by The-Compiler** [comment]
@zaowen Go ahead! GitHub doesn't allow assigning issues to non-commiters FWIW.

**Comment by zaowen** [comment]
So, after some research it seems like `tab-give` does attempt to close the old tab but doesn't due to the `tag-last-close` settings option.
Unless the user wants seperate functionality for closing the final tab and giving the final tab away, I don't think this needs to be special cased.

**Comment by The-Compiler** [comment]
I agree the `tabs.last_close` setting is enough for this.
