### ISSUE TITLE
Alt+number macro doesn't work

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#3532]
Steps to reproduce:

1. Open 2 tabs, and switch to the first one.
2. Press <kbd>qq</kbd> to start writing a macro into `q` register
3. Press <kbd>Alt</kbd>+<kbd>2</kbd> to switch to 2-nd tab
4. Press <kbd>q</kbd> to stop writing a macro
5. Switch to the 1-st tab, and press <kbd>@q</kbd> to reproduce the macro

Expected: browser should switch to 2nd tab again
Actual: nothing happens.

Version info:

	qutebrowser v1.0.4
	Git commit: 
	Backend: QtWebEngine (Chromium 61.0.3163.140)

	CPython: 3.6.4
	Qt: 5.10.0
	PyQt: 5.9.2

	sip: 4.19.6
	colorama: no
	pypeg2: 2.15
	jinja2: 2.10
	pygments: 2.2.0
	yaml: 3.12
	cssutils: no
	attr: 17.4.0
	PyQt5.QtWebEngineWidgets: yes
	PyQt5.QtWebKitWidgets: yes
	pdf.js: no
	sqlite: 3.21.0
	QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

	Style: Breeze::Style
	Platform: Linux-4.14.9-1-zen-x86_64-with-arch-Arch-Linux, 64bit
	Linux distribution: Arch Linux (arch)
	Frozen: False
	Imported from /usr/lib/python3.6/site-packages/qutebrowser
	Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

	Paths:
	cache: /home/constantine/.cache/qutebrowser
	config: /home/constantine/.config/qutebrowser
	data: /home/constantine/.local/share/qutebrowser
	runtime: /run/user/1000/qutebrowser
	system data: /usr/share/qutebrowser

**Comment by The-Compiler** [comment]
Works fine here. Can you show a log (either do `:report` or start with `--debug`) please?

**Comment by Hi-Angel** [comment]
Sure, [here it is](http://lpaste.net/8554905616122904576). Btw, what version are you running? Could it just have been fixed?

**Comment by The-Compiler** [comment]
Related log:

```
12:57:23 DEBUG    commands   command:run:489 command called: record-macro
12:57:23 DEBUG    commands   command:run:504 Calling qutebrowser.keyinput.macros.MacroRecorder.record_macro_command(<qutebrowser.keyinput.macros.MacroRecorder object at 0x7f70ca3cc400>, 0, None)
12:57:23 DEBUG    modes      modeman:enter:234 Entering mode KeyMode.record_macro (reason: record_macro)
12:57:23 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: True, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7f7088556798>)
12:57:23 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
12:57:24 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.record_macro - delegating to <qutebrowser.keyinput.modeparsers.RegisterKeyParser supports_chains=False supports_count=False>
12:57:24 DEBUG    keyboard   basekeyparser:_debug_log:107 No special binding found for q.
12:57:24 INFO     message    message:info:86 Recording macro 'q'...
12:57:24 DEBUG    misc       mainwindow:_update_overlay_geometry:297 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7f70885365e8>: PyQt5.QtCore.QRect(0, 714, 1367, 20)
12:57:24 DEBUG    modes      modeman:leave:296 Leaving mode KeyMode.record_macro (reason: valid register key)
12:57:24 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: True, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7f70885565e8>)
12:57:24 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
12:57:25 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
12:57:25 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring only-modifier keyeevent.
12:57:25 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x1000023 / text: ''
12:57:25 DEBUG    keyboard   basekeyparser:_debug_log:107 Ignoring, no text char
12:57:25 DEBUG    modes      modeman:_eventFilter_keypress:188 handled: False, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f70885565e8>)                                                                                                                                                                                                                               
12:57:25 DEBUG    misc       app:on_focus_object_changed:830 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f7088556948>
12:57:25 DEBUG    modes      tabbedbrowser:on_current_changed:636 Current tab changed, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='about:blank'>
12:57:25 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
12:57:25 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
12:57:25 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
12:57:25 DEBUG    modes      modeman:leave:290 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
12:57:26 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: True
12:57:26 DEBUG    misc       app:on_focus_object_changed:830 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f70885564c8>
12:57:26 DEBUG    modes      modeman:_eventFilter_keyrelease:208 filter: False
12:57:27 DEBUG    modes      modeman:_eventFilter_keypress:161 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
12:57:27 DEBUG    keyboard   basekeyparser:_debug_log:107 No special binding found for q.
12:57:27 DEBUG    keyboard   basekeyparser:_debug_log:107 Got key: 0x51 / text: 'q'
12:57:27 DEBUG    keyboard   basekeyparser:_debug_log:107 Definitive match for 'q'.
12:57:27 DEBUG    keyboard   basekeyparser:_debug_log:107 discarding keystring 'q'.
12:57:27 DEBUG    commands   command:run:489 command called: record-macro
12:57:27 DEBUG    commands   command:run:504 Calling qutebrowser.keyinput.macros.MacroRecorder.record_macro_command(<qutebrowser.keyinput.macros.MacroRecorder object at 0x7f70ca3cc400>, 0, None)
12:57:27 INFO     message    message:info:86 Macro 'q' recorded.
```

This looks like `Alt-2` somehow changed tabs for you, but not via the qutebrowser command bound to it (`:tab-focus 2`). What does `:bind <alt-2>` say?

**Comment by Hi-Angel** [comment]
`<alt-2> is bound to 'tab-focus 2' in normal mode`

**Comment by The-Compiler** [comment]
That's odd. After you do `:unbind <alt-2>`, can you still use alt-2 to go to the second tab?

**Comment by Hi-Angel** [comment]
Yep, it works nonetheless.

**Comment by Hi-Angel** [comment]
FWIW I have modified Qutebrowser with this patch https://github.com/airodactyl/qutebrowser/commit/48eb50d7e6160a2439258a62fbe92e9623e61124 Just saying — it doesn't seem to be related, but who knows…

**Comment by The-Compiler** [comment]
Well, something is handling the `alt-number` shortcuts before qutebrowser sees them entirely, and I have no idea what. Any other patches you have? Can you show `find /usr/lib/qt/plugins/ -type f` please?

**Comment by Hi-Angel** [comment]
> Any other patches you have? 

Nope, nothing aside of that.

> Can you show find /usr/lib/qt/plugins/ -type f please

http://lpaste.net/362067

**Comment by Hi-Angel** [comment]
Ok, you know, let's hold off this issue until I upgrade to a latest Qutebrowser, to exclude everything. I can't do that right now, because I don't have backups and such for upgrading, and I'm traveling. I'll come back to it later then.

**Comment by Hi-Angel** [comment]
So, I have latest release *(1.2.1)* now, and it's still present.

> After you do `:unbind <alt-2>`, can you still use alt-2 to go to the second tab?

Yes. I also noted that unbinding a non-existing shortcut results in error "can't find binding…", however repeatedly executing `:unbind <alt-2>` does not result in any messages, as if the bind being kept.

> Can you show `/usr/lib/qt/plugins/ -type f -exec pacman -Qo {} +` please

http://lpaste.net/364431

**Comment by Hi-Angel** [comment]
Apparently it got fixed, works for me
