### ISSUE TITLE
Insert mode in macros doesn't work

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#3533]
Steps to reproduce:
1. Focus the comment box on this page *(or any textbox anywhere for that matter)*, then exit insert mode.
2. Press <kbd>qq</kbd> to start writing a macro into `q` register
3. Press <kbd>i</kbd> to enter insert mode, and type something, or try pasting the text from clipboard.
4. Press <kbd>Escape</kbd> to exit insert mode, and <kbd>q</kbd> to stop writing the macro.
5. Press <kbd>@q</kbd> to reproduce the macro.

Expected: the text you typed/pasted appears in the focused textbox.
Actual: browser enters insert mode, and stops at it.

Version info:

	qutebrowser v1.0.4
	Git commit: 
	Backend: QtWebEngine (Chromium 61.0.3163.140)

	CPython: 3.6.4
	Qt: 5.10.0
	PyQt: 5.9.2

	sip: 4.19.6
	colorama: no
	pypeg2: 2.15
	jinja2: 2.10
	pygments: 2.2.0
	yaml: 3.12
	cssutils: no
	attr: 17.4.0
	PyQt5.QtWebEngineWidgets: yes
	PyQt5.QtWebKitWidgets: yes
	pdf.js: no
	sqlite: 3.21.0
	QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

	Style: Breeze::Style
	Platform: Linux-4.14.9-1-zen-x86_64-with-arch-Arch-Linux, 64bit
	Linux distribution: Arch Linux (arch)
	Frozen: False
	Imported from /usr/lib/python3.6/site-packages/qutebrowser
	Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

	Paths:
	cache: /home/constantine/.cache/qutebrowser
	config: /home/constantine/.config/qutebrowser
	data: /home/constantine/.local/share/qutebrowser
	runtime: /run/user/1000/qutebrowser
	system data: /usr/share/qutebrowser

**Comment by The-Compiler** [comment]
#3453 is the same underlying issue, closing this as duplicate.
