### ISSUE TITLE
Please add tooltip for tab's title!

### ISSUE THREAD

**Issue by agguser** [qutebrowser/qutebrowser#3535]
When the mouse hover a tab, a tooltip containing its full title should be displayed. This will be useful when having a lot of tabs, current showing only favicons and indexes because of little space.

**Comment by jgkamat** [comment]
Some alternatives to this currently are (to avoid using the mouse at all): 

1. Viewing the tab title in the 'window title' (`window.title_format`).
2. Using `:buffer` and viewing the title there
3. Using vertical tabs, so every tab has a fixed space.

That said, if I understand how tabs are being displayed currently, I think this is possible through qt.

**Comment by agguser** [comment]
If `tabs.title.format` accepts HTML, I would set it to `<span title="{title}">{index}: {title}</span>` (`title` must be HTML-attribute-escaped).
