### ISSUE TITLE
Please change tab color when its title change.

### ISSUE THREAD

**Issue by agguser** [qutebrowser/qutebrowser#3536]
When a background tab (e.g. facebook.com) changes its title (e.g. when there is a new notification), color of the tab should be changed (e.g. from grey to red background), to notify user.

**Comment by jgkamat** [comment]
I think this is a duplicate of #3363. 

I don't think changing color on any title change is a good idea, it seems like a hack over tying it to the real notificaiton api.

**Comment by The-Compiler** [comment]
Also see #3421.
