### ISSUE TITLE
feature request: Support basic Authentication in bookmark

### ISSUE THREAD

**Issue by dummys** [qutebrowser/qutebrowser#3537]
be able to store like https://user:pass@mysite.com and when choosing this bookmark, the user/password get filled automatically.

**Comment by mjauvin** [comment]
This would require an encrypted password store backend.

**Comment by The-Compiler** [comment]
Or not, if you don't care about having URL/password in the bookmarks file in plaintext.

**Comment by dummys** [comment]
For me, no problem, its more password for People dont scan website, or dont
see information, but its not critical, I don't care if its plaintext.

**Comment by mjauvin** [comment]
This should definitely be an option, then, with default NOT to save passwords in plaintext.

**Comment by The-Compiler** [comment]
If you don't want passwords in your URLs in the bookmarks file, don't put them there then. A `:bookmark-add` without arguments should probably still strip them, but if added explicitly, it should work.

(Also, you might want to use full-disk encryption anyways :wink:)

**Comment by dummys** [comment]
Yes, my problem is that I 'm ok to store it in pass, but it's not working
on basic auth popup with script.

**Comment by mjauvin** [comment]
@dummys I have a userscript that can authenticate Basic Auth pages, but it requires a PR which has not been merged yet (https://github.com/qutebrowser/qutebrowser/pull/3525) in master.

@The-Compiler :bookmark-add without argument will save the currently opened URL... what if that page has UserInfo in its URL (user:pass) ?

**Comment by The-Compiler** [comment]
@mjauvin 

> A `:bookmark-add` without arguments should probably still strip them

**Comment by dummys** [comment]
@mjauvin cool, then I wait that the PR is merged, thanks.

**Comment by za3k** [comment]
A :bookmark-edit or a way to do :bookmark-add explicitly with basic auth would be useful for this one

**Comment by amacfie** [comment]
@mjauvin @dummys https://github.com/qutebrowser/qutebrowser/pull/3525 has been merged

**Comment by dummys** [comment]
thanks :D

**Comment by The-Compiler** [comment]
Doesn't look like this works so far: When doing `:bookmark-add http://user:passwd@httpbin.org/basic-auth/user/passwd test` and opening it, I still get an auth prompt.

**Comment by dummys** [comment]
ok but why not using .netrc then ? It's better and it works fine.

**Comment by The-Compiler** [comment]
I'd like to support both. `.netrc` files are a rather arcane thing originally intended for FTP servers.

**Comment by dummys** [comment]
sure but it is used by all browsers.

Le mar. 28 sept. 2021 à 09:37, Florian Bruhin ***@***.***> a
écrit :

**Comment by The-Compiler** [comment]
Huh. I'm not aware of any other browser using it. Firefox does not, for example: https://bugzilla.mozilla.org/show_bug.cgi?id=64991

**Comment by dummys** [comment]
chromium does

Le mar. 28 sept. 2021 à 10:32, Florian Bruhin ***@***.***> a
écrit :
