### ISSUE TITLE
Use variables in Makefile

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3538]
The Makefile should probably use `$(PREFIX)`, `$(MANDIR)` and `$(DATADIR)` [variables](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html).

**Comment by gebulmer** [comment]
If we're following the standard recommendations there, I think we should be using `$(datarootdir)` , with `$(man1dir)` etc in terms of that.

What is the `--root` in the `setup.py` call? Is that what `$(prefix)` should be?

**Comment by msultani** [comment]
Has this issue been resolved? If not, I'd like to take a crack at it!

**Comment by jgkamat** [comment]
I don't think this issue is resovled yet, but I personally can't help too much, because I don't know makefile very well.

[this is where qb's makefile is currently](https://github.com/qutebrowser/qutebrowser/blob/master/misc/Makefile). There are some basic variables there currently that you could build off of, but it's probably a good idea to figure out what typical makefiles do.

**Comment by Hackingforlife** [comment]
@The-Compiler,  @msultani , hey there! we are team"Great Hackers" currently participating in a python sprint in Kampala @pyladieskampala. we would like to take on this issue.

**Comment by The-Compiler** [comment]
Hey @Hackingforlife!

Recently, @glatzor introduced `$(PREFIX)` in #3844 already, but it'd still make sense to add `$(MANDIR)` and `$(DATADIR)`. Note that this requires a little Makefile knowledge (or try-and-error) rather than Python.

If you need help, check out the [IRC channel](https://github.com/qutebrowser/qutebrowser#getting-help) - always happy to answer questions! :smile:

**Comment by Hackingforlife** [comment]
Thanks for the information...working on it!

**Comment by Hackingforlife** [comment]
@The-Compiler well, i would like more clarification on the specificy of the makefile knowledge i require for this?

**Comment by The-Compiler** [comment]
- You'll need to know how variables work (which you can see in the change linked above).
- You might need to understand how `$(MANDIR)` and `$(DATADIR)` work in other makefiles (mostly documented in the link in the original issue text)
- You need a way to test it - when creating a `tmp` directory inside the qutebrowser repository, `PYTHONPATH=tmp/lib/python3.6/site-packages/ make -f misc/Makefile PREFIX=tmp install` works for me. That way, you can test whether the files still end in the same location (e.g. by comparing the output of `find tmp` after that) with your change.

**Comment by Hackingforlife** [comment]
@The-Compiler,@glatzor, i would some clarification on code  #3844 , lines 6,7,8 and 9. what were you aiming at?

**Comment by glatzor** [comment]
@Hackingforlife You only need to set the --root option of setup.py if you use an alternative root directory.  If you just change the prefix e.g. from /usr/local to /usr the root dir stays the same.

**Comment by glatzor** [comment]
@The-Compiler Have you thought about moving all build and install logic to setup.py? Mixing build systems doesn't seem to be very elegant. Using python-distutils-extra could be of help (but I am biased here)

**Comment by bamwireku** [comment]
hey here am being disturbed on how to run a makefile. Some help please!!!!!!

**Comment by The-Compiler** [comment]
@glatzor Whoops, I must've missed your comment. I've tried to do some custom stuff in `setup.py` before but it was a pain, so I'd rather not. Seems fine to me to have a `setup.py` for the Python specific stuff (and everything which can land e.g. in a virtualenv when installing), and a Makefile to take care of the other system-wide stuff.
