### ISSUE TITLE
Please add a way to "view source" in external editor

### ISSUE THREAD

**Issue by agguser** [qutebrowser/qutebrowser#3539]
An option to `:view-source` to open source in external editor (`editor.command`) would do. Or is there already a way to do this?

**Comment by The-Compiler** [comment]
I thought there was already an issue for this, but maybe I was thinking of the comment in #1125. There's the [qutebrowser_viewsource](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qutebrowser_viewsource) userscript, but that needs to re-download the page - so yeah, this would be nice to have natively I think.

**Comment by NoSuck** [comment]
In the meantime, you might want to try a binding:  `spawn -d xterm -e bash -c \"curl {url} | vim -\"`

**Comment by gebulmer** [comment]
This could also be closed now - `:view-source --edit` works :+1:

In future I'll write more specifically "Fixes #xxxx" in the PR

**Comment by The-Compiler** [comment]
Indeed, thanks!
