### ISSUE TITLE
:scroll-to-perc broken when document.documentElement.style.height = '100%'

### ISSUE THREAD

**Issue by mjauvin** [qutebrowser/qutebrowser#3541]
*** tested with latest master branch

When opening a website like https://blog.djy.io, the gg, G and <count> G using the ":scroll-to-perc" does not work.

The following patch fixes the problem (but might potentially induce other problems in the page):

```
diff --git a/qutebrowser/javascript/scroll.js b/qutebrowser/javascript/scroll.js
index 7205cb151..e1180da4a 100644
--- a/qutebrowser/javascript/scroll.js
+++ b/qutebrowser/javascript/scroll.js
@@ -23,6 +23,9 @@ window._qutebrowser.scroll = (function() {
     const funcs = {};
 
     funcs.to_perc = (x, y) => {
+        // some pages "hide" their actual height (e.g. https://blog.djy.io)
+        document.documentElement.style.height = 'auto';
+
         let x_px = window.scrollX;
         let y_px = window.scrollY;
```

**Comment by jgkamat** [comment]
I think this is still broken on master, but I don't think this fix is good as 
we're overwriting the stylesheet.

this is fixed by #4715 though
