### ISSUE TITLE
lazy tab loading opens page from history

### ISSUE THREAD

**Issue by AeliusSaionji** [qutebrowser/qutebrowser#3542]
I've been using lazy tab loading, and often a random page from tab history is loaded, rather than the page I left off on.

Were I to exit qutebrowser right now, there's a good chance it would restore at the list of github issues, rather than on this specific issue.

I am able to navigate forward in history to the page where qutebrowser should have restored to.

```
qutebrowser v1.1.1
Git commit:
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.10

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.14.15-1-surface4-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

(initially mentioned in https://github.com/qutebrowser/qutebrowser/issues/67)

**Comment by AeliusSaionji** [comment]
Mentioning @seebye  as requested.

**Comment by PluMGMK** [comment]
Also occasionally happens with WebKit.
```
qutebrowser v1.1.0
Git commit: 
Backend: new QtWebKit (WebKit 602.1)

CPython: 3.6.1
Qt: 5.10.0
PyQt: 5.9.2

sip: 4.19.5
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.2.0
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.5.188 (/home/mgkeyes/.local/share/qutebrowser/pdfjs/build/pdf.js)
sqlite: 3.18.0
QtNetwork SSL: OpenSSL 1.0.2n  7 Dec 2017

Style: QFusionStyle
Platform: Linux-4.15.0-x86_64-Intel-R-_Core-TM-_i7-4790K_CPU_@_4.00GHz-with-glibc2.2.5, 64bit
Linux distribution: Cross Linux From Scratch (unknown)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser-1.1.0-py3.6.egg/qutebrowser
Qt library executable path: /opt/qt5/libexec, data path: /opt/qt5
```

**Comment by seebye** [comment]
It seems like the "visibilitychange" event is sent multiple times.  
Maybe it's related to #3366.  
Should be fixed by replacing  
`document.addEventListener("visibilitychange", go_back);`  
with  
`document.addEventListener("visibilitychange", go_back, {once: true});`  
in qutebrowser/html/back.html

**Comment by The-Compiler** [comment]
I can't really test this as I haven't seen the issue, but let's hope that helps. @AeliusSaionji @PluMGMK please let me know if you still see this happen with the latest git version (or with the next release once that's out).
