### ISSUE TITLE
QtWebEngineProcess should not be spawned for each "suspended" tab (lazy loading)

### ISSUE THREAD

**Issue by agguser** [qutebrowser/qutebrowser#3545]
It seems QtWebEngineProcess is spawned for every tabs, even if not loaded ("suspended"). This consumed much memory if you have a lot of tabs (lazy reading ;-). QtWebEngineProcess should be spawned only when the tab is "activated". Right?

**Comment by The-Compiler** [comment]
qutebrowser has no control over those processes, they are handled by QtWebEngine.

**Comment by agguser** [comment]
Is there a way to have lots of lazy tabs without consuming much memory? `htop` says each "lazy" QtWeb EnginProcess use 1.7% (of my 3.75GB, no swap file, i.e. 65MB per tab), so I cannot have more than 50 tabs. In Firefox, there is no problem having lots of lazy tabs.

**Comment by The-Compiler** [comment]
I do have some ideas about it, which is why #67 is still open. Also see [QTBUG-64450](https://bugreports.qt.io/browse/QTBUG-64450).
