### ISSUE TITLE
Unable to log into any Jenkins

### ISSUE THREAD

**Issue by maxime-michel** [qutebrowser/qutebrowser#3559]
Whether it's on a production instance at work or on a local Jenkins, qutebrowser doesn't seem to want to post the Jenkins log in form. I go to `http://localhost:8080/login`, type correct credentials, but neither the 'log in' button nor the Enter key move the page forward. Which is what they do with Chromium or any other major browser.

It can be reproduced with a stock Jenkins Docker image:

    docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts

I'm not sure how to debug this but I felt I'm probably not the only hacker who's going to miss this at some point.  I use v. 1.1.1 but this was also the case with 1.1.0. Both on Ubuntu and OS X. I've tried to disable host blocking because that's the only parameter I can think of that would alter the behavior compared to Chromium. What else could it be?

**Comment by The-Compiler** [comment]
Is there a public Jenkins instance where I can try this somewhere? Can you reproduce it when you start with `--temp-basedir`? On macOS, are you using the `.dmg` release?

**Comment by maxime-michel** [comment]
Thanks for the fast answer! `--temp-basedir` seems to do the trick!

If you still would like to see it, you could use this instance: https://ci.jenkins-ci.org/login

Yes, I'm using the `.dmg`, not building anything on my own.

**Comment by The-Compiler** [comment]
Just reproduced it with the docker container (sorry, missed that before!) and it works fine here. Since it also works for you with `--temp-basedir`, this is most likely something with your config or cookies. Can you show the contents of `:open qute://configdiff` please?

**Comment by maxime-michel** [comment]
Found it, it's the custom user agent. Jenkins probably stop if it suspects something weird. I have the value from the Arch wiki, I should have paid more attention to the following I guess:

> Changing your user-agent away from the default will prevent some websites from working properly.

In any case, many thanks for the lighting fast help.
