### ISSUE TITLE
Youtube video sets PulseAudio volume to 100%

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#356]
See https://www.reddit.com/r/archlinux/comments/2pcash/qutebrowser_a_keyboarddriven_vimlike_browser/cmvmg1c

I can't reproduce that, but I guess I should open an upstream issue anyways.

**Comment by The-Compiler** [comment]
https://codereview.qt-project.org/#/c/102899/

**Comment by sim590** [comment]
I'm experiencing this right now on qutebrowser v0.3.0.

**Comment by The-Compiler** [comment]
@sim590 The qutebrowser version is irrelevant, as this is not a bug in qutebrowser itself, but in Qt - what version of Qt are you running? (See `:open qute:version`)

**Comment by sim590** [comment]
```
$ qutebrowser --version
qutebrowser v0.3.0
Git commit: 

CPython: 3.4.3
Qt: 5.5.0, runtime: 5.5.0
PyQt: 5.5
```

**Comment by ff2000** [comment]
On Sat, 22 Aug 2015 12:17:58 -0700, Florian Bruhin <notifications@github.com> wrote:
> @sim590 The qutebrowser version is irrelevant, as this is not a bug in qutebrowser itself, but in Qt - what version of Qt are you running? (See `:open qute:version`)

It's not a bug but a feature, and also webkit-gtk suffers from this.
You can workaround the issue by disabling flat-volumes in pulseaudio.
```
$ cat ~/.config/pulse/daemon.conf
flat-volumes = no
```
(There are people that say enabling flat-volumes by default is the real
bug, but - well ;))

**Comment by sim590** [comment]
> ```
> $ cat ~/.config/pulse/daemon.conf
> flat-volumes = no
> ```

This workaround actually worked for me! Thank you @ff2000.
