### ISSUE TITLE
Tabs don't get restarted when the renderer crashes or otherwise abnormally exits

### ISSUE THREAD

**Issue by jcjordyn130** [qutebrowser/qutebrowser#3571]

**Comment by jgkamat** [comment]
I don't know if it's a good idea for this to be done automatically, as it can easily lead into a refresh loop if a bug causes the page to keep crashing... It might be better to upgrade your qtwebengine which will hopefully resolve renderer crashes.

**Comment by jcjordyn130** [comment]
Yep, that's the first thing I did when I discovered chrome://crash made it loop.

**Comment by mschilli87** [comment]
corresponding PR: https://github.com/qutebrowser/qutebrowser/pull/3570

**Comment by The-Compiler** [comment]
Closing this in favor of #3887.
