### ISSUE TITLE
Incorrect rendering after window resize.

### ISSUE THREAD

**Issue by sarg** [qutebrowser/qutebrowser#3578]
<details><summary>Version Info</summary>
<p>

```
Version info

qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.4
Qt: 5.9.2
PyQt: 5.9.2

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.0.2n  7 Dec 2017

Style: QFusionStyle
Platform: Linux-4.14.0-3-amd64-x86_64-with-debian-buster-sid, 64bit
Linux distribution: Debian GNU/Linux buster/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/sarg/.cache/qutebrowser
config: /home/sarg/.config/qutebrowser
data: /home/sarg/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 1:20:46
```

</p>
</details>

I am using a little bit exotic tiling WM - [EXWM](https://github.com/ch11ng/exwm/).
When I open buffer selector (grey rectangle at the bottom of screenshot), it makes other windows shrink vertically. As you can see, Chromium shrinks fine, but Qutebrowser shows black area at the top of the window. The height of the area is equal to the height of the buffer selector. Seems there is a bug in geometry calculations. I have tried to triage the bug myself, but was unsuccessful. 

![screenshot](https://user-images.githubusercontent.com/193264/36059264-d66c2bae-0e45-11e8-8258-7d9085dfea55.png)

**Comment by The-Compiler** [comment]
Can you check whether you see the same behavior with QupZilla (the 2.x version in the Debian sid repos)?

**Comment by sarg** [comment]
Yes, Qupzilla 2.2.5 is also affected.

**Comment by The-Compiler** [comment]
This looks like some issue with exwm and/or QtWebEngine then - I suggest you open a bug in their bugtracker(s). I don't think there's anything qutebrowser can do here, but maybe @Ambrevar has an idea as he seemed to be using exwm as well.

**Comment by Ambrevar** [comment]
I use EXWM indeed, and I have never suffered from this issue.

Can you give a precise recipe? (Versions, what buffer menu, etc.)  If it gets too Emacs-y, we could discuss this on EXWM's issue tracker.

**Comment by sarg** [comment]
@Ambrevar I think this happens when I use ivy.
This is the minimal config to reproduce this behaviour:
```lisp
(require 'exwm)
(require 'ivy)
(require 'exwm-config)
(ivy-mode)
(exwm-config-misc)
```
Start qutebrowser and press `C-x b`

**Comment by Ambrevar** [comment]
I can reproduce with ivy, or more generally when the minibuffer prompt changes, e.g.

```
(completing-read "foo\nbar:" '(foo bar))
```

(with default Emacs).

I think it's an EXWM issue.  Would you mind reporting?

**Comment by Ambrevar** [comment]
Also note that the issue does not occur Gimp.  That's probably worth mentioning.

**Comment by sarg** [comment]
@Ambrevar, sure https://github.com/ch11ng/exwm/issues/364
