### ISSUE TITLE
Qutebrowser not loading urban dictionary website properly

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3586]
Thanks a ton for qutebrowser. Total fan here.

Not sure if this is just me, but I am unable to use the site https://www.urbandictionary.com/ (which works just fine in other browsers). No warning or error message, but huge images of icons and nothing functional loads.

Here are some info about my settings:
qutebrowser v1.1.1
Backend: QtWebEngine (Chromium 61.0.3163.140)
CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.10
Running on 4.15.2-2-ARCH

Thanks!

**Comment by The-Compiler** [comment]
Works fine here. Can you reproduce it when starting with `--temp-basedir`?

**Comment by bheadmaster** [comment]
Works on my machine, with the exact same Qt and qutebrowser version, and distro, as prosoitos.

**Comment by gebulmer** [comment]
huh weird, I have the same issue as in the OP

**Comment by gebulmer** [comment]
We have found the culprit, if d2gatte9o95jao.cloudfront.net gets blocked, that site doesn't display correctly

**Comment by prosoitos** [comment]
Cool! I just removed `d2gatte9o95jao.cloudfront.net` from blocked-hosts and it is now working fine. Any way to prevent it from being added to the list again?

**Comment by prosoitos** [comment]
Never mind. I found the `content.host_blocking.whitelist` option.

Thanks for the quick help! and for all the great work!!! Can't wait to have pdf.js working in qutebrowser!! :)

**Comment by The-Compiler** [comment]
Thanks a lot to @gebulmer to help tracking things down! 👍 

I've sent a mail to the author of the [backlist which is to blame](http://winhelp2002.mvps.org/hosts.htm). I hope they'll remove it soon, otherwise I might add it to the default whitelist...

As for pdfjs, see #2330. Also note that you can hit `ctrl-x` to download files temporarily and open them in your default PDF reader.

**Comment by The-Compiler** [comment]
Looks like it's going to be disabled soon:

> Yes we are aware and that entry has been disabled, and this will reflect in
the next update.

Nothing more to do here, then :wink:

**Comment by prosoitos** [comment]
Yup :) I've definitely been following #2330 eagerly :)

Thanks so much for such a wonderful browser!

**Comment by prosoitos** [comment]
Actually-sorry this is getting totally off topic here-but is there a way to bind the temporary download to a key in normal mode?

Something that could look like `config.bind(';e', 'hint links fill :open-download {hint-url}')` for instance? The only function I could find that allows this temporary download is `:prompt-open-download` and, obviously, it only works in prompt mode.

Just trying to by-pass the prompt. I know it's not that bad at all. But I do look at a lot of pdfs that I don't plan on keeping as part of my workflow and being able to open them from a temp file directly by a single key binding or a single mouse click would be sweet, while waiting for pdf.js

I looked into userscripts, but there doesn't seem to be a function to change mode in the script. So I am not sure how to make use of the `:prompt-open-download` from normal mode.

**Comment by The-Compiler** [comment]
Hmm, `:download` already has `--dest`, I suppose it wouldn't be too hard to add a `--open` as well. Mind opening a new issue for that? I don't see a way to do it right now, though (but I'd encourage you to open a PR if you want to look at it!) :smile:.

**Comment by prosoitos** [comment]
Not sure I have the skills to do this at this point, but I opened a new issue (#3591)

**Comment by The-Compiler** [comment]
@rien333 Works fine here, and `d2gatte9o95jao.cloudfront.net` isn't in my `~/.local/share/qutebrowser/blocked-hosts`. Are you sure your blocklists are up-to-date? (`:adblock-update`)

**Comment by rien333** [comment]
Yes it works now! I guess the previous update I did a week ago or so blocked it.
