### ISSUE TITLE
qutebrowser is slower, unless using --temp-basedir

### ISSUE THREAD

**Issue by bheadmaster** [qutebrowser/qutebrowser#3589]
Sorry for opening such an intangible issue - feel free to delete it if it doesn't belong here - but I've noticed qutebrowser getting slower and laggy, especially when scrolling facebook with a mouse wheel, and browsing or switching videos on youtube (in a playlist). I asked around on forums and someone suggested trying --temp-basedir, which I think has solved the issue, since everything is back on the same old speed I was used to.

Now, I'd usually just add the flag to the keybindings, but using it makes me unable to save bookmarks and settings and such, so I'm curious about what exactly does --temp-basedir do that (IF it) makes things smoother and how can I apply the fix generally (to work without --temp-basedir)?

edit: manpage simply says 
> --temp-basedir 
>     Use a temporary basedir.

which doesn't seem too informative.

***

Version info

qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.10

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.2-2-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-q7tc66td/cache
config: /tmp/qutebrowser-basedir-q7tc66td/config
data: /tmp/qutebrowser-basedir-q7tc66td/data
runtime: /tmp/qutebrowser-basedir-q7tc66td/runtime
system data: /usr/share/qutebrowser

Uptime: 0:05:42

**Comment by The-Compiler** [comment]
What `--temp-basedir` does is using a different (temporary) directory for all of qutebrowser's data (config, cookies, history, cache, etc.). So to find out more, you'd need to find out what of that is causing it to slow down.

My first guess would be the history. If you quit qutebrowser, move `~/.local/share/qutebrowser/history.sqlite` away and start it normally, is it fast as well?

If so, can you please try the latest git version (`qutebrowser-git` in the AUR) with your current history, and see whether things are improved there?

If not, can you move away `~/.cache/qutebrowser`, `~/.local/share/qutebrowser` and `~/.config/qutebrowser` one by one and find out which one of those is causing it to slow down?

**Comment by bheadmaster** [comment]
It is somewhat difficult to measure the differences in my case, mostly because I don't have a reference point except from youtube+facebook combo.

Moving `~/.local/share/qutebrowser/history.sqlite` didn't seem to do anything, neither did moving `~/.cache/qutebrowser`, but moving `~/.local/share/qutebrowser` seems to make a difference. Again, this is mostly my personal measure, as I have no way of figuring out the difference (`speed-battle.com/` doesn't give any useful info on speed difference).

Maybe I shouldn't have opened the issue without any concrete evidence of an issue. I'll try to get some better observations, but it's not like I'm gonna stop using qb over this, so I don't think this is a very high priority issue.

**Comment by gebulmer** [comment]
Most of the cache ought to be in `.local/share/qutebrowser/webengine`, it's worth seeing in there what exactly is taking up the space.

Mine is currently at about half of yours, perhaps there's the odd website or two taking up much more than the rest?

**Comment by The-Compiler** [comment]
The cache isn't stored in `~/.local/share/qutebrowser`, it's in `~/.cache/qutebrowser`.

`~/.local/share/qutebrowser` contains persistent data such as history, cookies, local storage for websites, etc. A tool like [ncdu](https://dev.yorhel.nl/ncdu) should be able to show you what's so big. FWIW, it's 881 MB for me 😆 

As for this issue: It'd be great if you can try to find out what in there seems to be causing it. Can you try only moving `~/.local/share/qutebrowser/webengine` away? If that seems to help, there's most likely nothing qutebrowser can do as that's all done by QtWebEngine.

**Comment by bheadmaster** [comment]
Slight update - it seems that connection speed has a huge influence on browser speed. And I don't mean just loading pages - of course it would be slower - but when a certain tab is loading on a slow internet connection, the whole browser seems to freeze until the tab is loaded. Don't know what causes that or is it fixable but certainly can get annoying on slower connections (I've been on a 100KB/s when this issue happened).

I'm back home on a good connection and everything seems the same as before.

**Comment by The-Compiler** [comment]
That's odd - I'm often on a bad mobile connections in a train, and never noticed anything like this. However, I don't think there's much we can do here, as qutebrowser doesn't do any network related stuff directly (that's all handled by the backend).

I'll close this one for now, as I don't think it's actionable in any way - thanks for digging into it, though! And if you find out more, please let me know.
