### ISSUE TITLE
Feature request: add option to open pdf from temp file directly

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3591]
I know that this is already possible via the prompt thanks to `<Ctl-x>` or `:prompt-open-download`. But it would be nice, for people having to skim through a lot of online pdfs to be able to do this with a single keybind or mouse click, directly from normal mode.

For instance, in the settings, one could choose the default behaviour when selecting or hinting at a pdf link (download vs open from temp file).

Or, if there were a function that would do this from normal mode, it would then be easy to bind it to a key (like `;<letter>` for instance).

**Comment by jgkamat** [comment]
Issue https://github.com/qutebrowser/qutebrowser/issues/3353 may be related as well.
