### ISSUE TITLE
Sites like Google Translate exit insert mode while typing

### ISSUE THREAD

**Issue by bheadmaster** [qutebrowser/qutebrowser#3596]
Steps to reproduce:
- open `https://translate.google.de/`
- press `i` to enter insert mode
- type `a` in the textbox

Behavior I see: Browser exists insert mode immediately even though `esc` was not pressed.
Expected behavior: Browser stays in insert mode.

Can someone also test this, please? Only seen this happen on google translate though. Same thing happens when opening `https://translate.google.de/#de/en/` instead of `https://translate.google.de/` .
***
Version info

qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.10

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.2-2-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/lark/.cache/qutebrowser
config: /home/lark/.config/qutebrowser
data: /home/lark/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:01:31

**Comment by jgkamat** [comment]
Hmm, I can't seem to reproduce this on my machine (qt5.7.1). Maybe this is one of the 5.10 bugs though?

**Comment by The-Compiler** [comment]
It's most likely caused by #3427 as workaround for #3401 (indeed on Qt 5.10 only) - cc @ryan-farley. Not sure if there's anything we can do without breaking that workaround, though.

**Comment by The-Compiler** [comment]
Wait, I can't actually reproduce this on Qt 5.10 either. Does the statusbar still say "-- INSERT MODE --"?

**Comment by gebulmer** [comment]
I could only get it to trigger once, @The-Compiler and @jgkamat can you press 'i' as soon as you see the cursor in the box and then immediately mash letter keys? I think it happened as the x appeared in the box there, which requires timing.

I could be wrong though

**Comment by bheadmaster** [comment]
Weird. It happens for me every time, even if I let the page load completely and wait for a bit before entering insert mode.

Here's screenshots of what I see:
https://imgur.com/a/jDDuV

**Comment by bheadmaster** [comment]
Here's my debug log of starting qutebrowser, reproducing the bug, and closing, if it's of any help.
https://pastebin.com/EBEe8Jur

16:58:11 is when I pressed `i`
16:58:13 is where I entered the `a` into the textbox triggering the bug.

**Comment by bheadmaster** [comment]
`16:58:13 DEBUG    destroy    lineparser:_after_save:81 Saved to /home/lark/.local/share/qutebrowser/cmd-history`
`16:58:13 DEBUG    webview    browsertab:_set_load_status:692 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://translate.google.de/'>: LoadStatus    .loading`
`16:58:13 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed('loading') (tab 0)`
`16:58:13 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_started() (tab 0)`
`16:58:13 DEBUG    modes      modeman:leave:296 Leaving mode KeyMode.insert (reason: load started)`

This part seems relevant - this is what happened when I entered a character in the textbox, I think. I apologize if I am spamming.

**Comment by The-Compiler** [comment]
Thanks! I was able to reproduce it once as well.

**Comment by lrvick** [comment]
Hitting this on 2 machines. Impacts google docs and a number of other textareas. Does not seem to impact all textareas though, as this github input box works fine, but google docs in another tab is unusable.

**Comment by brunoduran** [comment]
It happes to me too when translate "refresh" the translation. If I turn off instant translation the problem dissapears.

**Comment by teon** [comment]
I will add that I have not only issues with Google (gmail/docs) but also GitLab.

Also some pages are "refreshing" in a loop...

**Comment by jgkamat** [comment]
The refreshing loop is a qt5.11 issue, the latest master has a commit trying to work around that.

On June 7, 2018 9:13:51 AM EDT, Robert Olejnik <notifications@github.com> wrote:
>I will add that I have not only issues with Google (gmail/docs) but
>also GitLab.
>
>Also some pages are "refreshing" in a loop...

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Aster89** [comment]
This problem is annoying me as well; if it is of any relevace, in Google Maps I experience the problem (_i.e._ back to command mode without pressing <kbd>Esc</kbd>) only when I empty the search box.

1. hit <kbd>i</kbd> to enter insert mode in the search box of Google Maps
2. write something (insert mode is correctly kept on)
3. hold <kbd>Shift</kbd> and press <kbd>Home</kbd> to select everything was typed at step 2.
4. turning point
a. type something else results in correct behavior (insert mode is not left and further typing fills the box with new text)
b. pressing either <kbd>Backspace</kbd> or <kbd>Delete</kbd> results in wrong behavior (insert mode left and further typing results in undesired commands)

**Comment by lockeadams** [comment]
This issue is still affecting me, any updates?

**Comment by The-Compiler** [comment]
@lockeadams so far nobody has looked at it, and the Qt bug behind it still isn't fixed as far as I know. If there are updates, subscribing to the issue is the best way to know about them.

**Comment by jgkamat** [comment]
Just to increase visibility, please go vote for [QTBUG-65223](https://bugreports.qt.io/browse/QTBUG-65223). I'm pretty surprised it's not fixed yet :(

**Comment by JanKaifer** [comment]
Hi, I'd like to thank you for qute browser - it's awesome. And I also experience this issue, it's pain especially with google docs.

**Comment by JanKaifer** [comment]
After while of tinkering I've found out that this problem only occurs when I'm editting the very first element of paragraph and sometimes when edditing spaces.

I think that this strange behaviour is caused more by google docs than qute browser itself but still might help finding source of this bug.

**Comment by rcorre** [comment]
From closed dupe: This also happens on the project search field of gerrit, e.g. https://codereview.qt-project.org/#/admin/projects/

**Comment by moorchegue** [comment]
Whoops, sorry for the dupe. Tried the wrong issue search keywords prior to creation, I guess.

**Comment by teto** [comment]
It's especially visible on https://www.apertium.org/index.eng.html, it seems QB leaves (then reenters) insert mode regularly (every 500ms) so if you type fast you can actually send a command to QB instead of type some text.

**Comment by lbkvu** [comment]
if you turn off "Auto translate" feature in Google Translate, you can continue typing in Insert Mode without interruption.

**Comment by mickmattes** [comment]
> if you turn off "Auto translate" feature in Google Translate, you can continue typing in Insert Mode without interruption.

How would you turn that off?

**Comment by robertp-indeed** [comment]
There's several pages that cause this issue for me; I've largely figured out what they are at this point so I just use passthrough mode on them now. It's an okay, though slightly clunky, workaround.

**Comment by rcorre** [comment]
@robertp-indeed thanks for mentioning that, I didn't even think of trying passthrough mode! It isn't ideal, but it is better than pressing `i` after every letter (which is what I've been doing, no joke :laughing:)

**Comment by Yrds** [comment]
Maybe i am little late, but `input.insert_mode.leave_on_load` was not mentioned in this issue yet, setting it to `false` fix the problem without having to turning passive mode on.

**Comment by mickmattes** [comment]
@Yrds This is it! This is the solution, thank you! I just wonder, why this "switch" is not mentioned in the default config.

**Comment by The-Compiler** [comment]
@mickmattes mentioned in what default config?

**Comment by mickmattes** [comment]
@The-Compiler the one you get by entering `:config-write-py --defaults`

**Comment by jgkamat** [comment]
mickmattes writes:

> @The-Compiler the one you get by entering :config-write-py --defaults

it is:

> ## Leave insert mode when starting a new page load. Patterns may be
> ## unreliable on this setting, and they may match the url you are
> ## navigating to, or the URL you are navigating from.
> ## Type: Bool
> # c.input.insert_mode.leave_on_load = True

it was added in the last release, so if you generated it before then, it
didn't exist.

**Comment by mickmattes** [comment]
Yep, looks like that's the reason

**Comment by prosoitos** [comment]
Same problem for me on https://melpa.org/#/ (when trying to type in the package search box)

**Comment by mathieufrh** [comment]
I can confirme that `input.insert_mode.leave_on_load = False` helps a lot!

**Comment by The-Compiler** [comment]
This should mostly be solved nowadays (via #4723) by exiting insert mode when a page finished loading. I wrote an explanation of what's going on for Reddit, here it is:

The main problem here is [QTBUG-65223](https://bugreports.qt.io/browse/QTBUG-65223) which means that QtWebEngine (since Qt 5.10) emits its `loadStarted` signals whenever a page changes its URL via JavaScript (which can commonly happen while typing on pages like Google Translate). So qutebrowser can do one of these things:

- Leave insert/hint mode when a page load started - but then it'll also leave it e.g. when typing on Google Translate, which was a bug for a long time.
- Leave insert/hint mode when a page load finished (like it does now).
- Don't leave them at all (which you can do via the `input.insert_mode.leave_on_load` and `hints.leave_on_load` settings). This tends to be rather confusing - when you e.g. enter a search term on Google and press enter, you probably wouldn't expect to still be in insert mode.

I wish there was a better solution (or that bug would finally get fixed) - but so far, I haven't been able to think of one.

**Comment by prosoitos** [comment]
Thank you for this comment. I had not realized that the issue had been fixed and closed and that I could stop having `input.insert_mode.leave_on_load` set to `false` (which, while solving the problem, was indeed confusing).

**Comment by nrdxp** [comment]
Unfortunately this is still an issue for me even with `input.insert_mode.leave_on_load = False` using latest [qt6-v2](https://github.com/qutebrowser/qutebrowser/tree/qt6-v2) branch and qt6 6.3.1

**Comment by The-Compiler** [comment]
@nrdxp Works fine for me. Please open a new issue with the information from the template and detailed reproduction steps.
