### ISSUE TITLE
Logs in end2end tests don't get cleared from previous tests with Qt >= 5.10

### ISSUE THREAD

**Issue by mjauvin** [qutebrowser/qutebrowser#3597]
*happens in current master*

If your Scenarios depend on Log entries, previous Scenario's Logs might still be present because of the ASYNC nature of qutebrowser.

We need to find a way to make sure a Test starts with fresh logs.

**Comment by The-Compiler** [comment]
This isn't actionable in a generic way. All that can be done currently for all tests already is. I'll look into this specific case when reviewing your PR.
