### ISSUE TITLE
Feature request: Escape key shall remove poped-up menu

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#3598]
For working with Qutebrowser I have sometimes (rarely though, but still)*

**Comment by Hi-Angel** [comment]
Омg. I'm sorry, I'm touch-typing from a laptop, and it sent the issue. Let me write it

**Comment by The-Compiler** [comment]
I can already tell that this is probably a duplicate of #3465.

**Comment by Hi-Angel** [comment]
Whoops, you're right, I'm sorry for not searching it, I was absolutely sure that only my problem… :)

**Comment by The-Compiler** [comment]
@The-Compiler - closing issues before they're fully opened!™ 😆

**Comment by mschilli87** [comment]
@Hi-Angel:

Just my 2 cents:

1. [You are not alone.](https://github.com/qutebrowser/qutebrowser/issues/2446#issuecomment-341664407) :wink:
2. While `<ESC>` doesn't do the trick, `<Alt>` does (see issue linked above).

**Comment by Hi-Angel** [comment]
@mschilli87 thanks, unfortunately <kbd>Alt</kbd> don't work for me. Quick pressing right or left <kbd>Alt</kbd> don't do anything. Holding <kbd>Left Alt</kbd> highlights first letters of the menu. Interestingly, the menu has `Reload` point, and if I press <kbd>Alt</kbd>+<kbd>R</kbd>, it reloads the page, and guess what — the menu still hangs over the page after reload!

Archlinux here, Qutebrowser 1.0.4 *(yeah, a bit outdated for boring reasons)*.

**Comment by mschilli87** [comment]
@Hi-Angel not sure what's the difference, both <kbd>Alt</kbd>s work for me on both Gentoo with recent qutebrowser (can't check right now which exactly) and Ubuntu with  qutebrowser v0.11.0 (speaking of outdated).

**Comment by The-Compiler** [comment]
This is a bit offtopic, but important enough to warrant it :wink:

> and Ubuntu with qutebrowser v0.11.0 (speaking of outdated).

That sounds like you're using an old QtWebKit which is full of security holes. You should really find a way to upgrade if you use that to visit untrusted websites.

**Comment by mschilli87** [comment]
Done:

```sh
qutebrowser --version | head -n1
```

```
qutebrowser v1.1.1
```
