### ISSUE TITLE
Icon has a low resolution on Windows

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3601]
![image](https://user-images.githubusercontent.com/625793/36212995-c01ddb5a-11a5-11e8-9eec-25d88d72747e.png)

We can probably add higher-resolution icons to that executable *somehow*.

**Comment by bitraid** [comment]
Thats an easy one: you just have to make a higher resolution ico resourse for pyinstaller. 
 I tried it by converting `misc/qutebrowser-256x256.png` using the online converter: [http://convertico.com](http://convertico.com/)
It looks good!

**Comment by The-Compiler** [comment]
The `.ico` file in the repository (which is used) contains various resolutions. For some reason, PyInstaller/Windows is using the smallest one and scaling that up instead of using a bigger one.

**Comment by bitraid** [comment]
The converted i used makes various resolutions, also. You can choose which ones you want if you like, but the defaults are fine. The file it creates seems to work fine, it includes the 128x128 ico and the 256x256 png, like modern `.exe` seem to have.

**Comment by bitraid** [comment]
I think there is a problem with the `.ico` in the repository. I inserted it in other executables with [resourse hacker](http://www.angusj.com/) and they have the same problem. (Keep in mind the windows icon cache when testing - rename the `exe` to a random name, for the icon to refresh)

**Comment by The-Compiler** [comment]
IIRC I used `icotool` from [icoutils](http://www.nongnu.org/icoutils/) to create it. This can also list icons:

```
$ icotool -l qutebrowser.ico
--icon --index=1 --width=128 --height=128 --bit-depth=8 --palette-size=256
--icon --index=2 --width=16 --height=16 --bit-depth=8 --palette-size=256
--icon --index=3 --width=24 --height=24 --bit-depth=8 --palette-size=256
--icon --index=4 --width=32 --height=32 --bit-depth=8 --palette-size=256
--icon --index=5 --width=48 --height=48 --bit-depth=8 --palette-size=256
--icon --index=6 --width=64 --height=64 --bit-depth=8 --palette-size=256
--icon --index=7 --width=96 --height=96 --bit-depth=8 --palette-size=256
```

I'm wondering whether the order is relevant here. Maybe Windows sees the 128x128 one, decides that it's too big or whatever, and then uses the 16x16 one scaled up. I'm guessing they should be ordered by size decreasing maybe?

**Comment by bitraid** [comment]
I looked on different `.exe` files, and most have their icons by size decreasing (and color depth increasing) order, but not all (and they seem to work). The `.ico` file the online converter produced also has decreasing size order:

```
$mediainfo qutebrowser-256x256.ico
General
Complete name                            : /data/tmp/qutebrowser-256x256.ico
Format                                   : ICO
File size                                : 116 KiB

Image #1
Width                                    : 256 pixels
Height                                   : 256 pixels
Bit depth                                : 32 bits
Stream size                              : 18.2 KiB (16%)

Image #2
Width                                    : 128 pixels
Height                                   : 128 pixels
Bit depth                                : 32 bits
Stream size                              : 66.0 KiB (57%)

Image #3
Width                                    : 64 pixels
Height                                   : 64 pixels
Bit depth                                : 32 bits
Stream size                              : 16.5 KiB (14%)

Image #4
Width                                    : 48 pixels
Height                                   : 48 pixels
Bit depth                                : 32 bits
Stream size                              : 9.41 KiB (8%)

Image #5
Width                                    : 32 pixels
Height                                   : 32 pixels
Bit depth                                : 32 bits
Stream size                              : 4.16 KiB (4%)

Image #6
Width                                    : 16 pixels
Height                                   : 16 pixels
Bit depth                                : 32 bits
Stream size                              : 1.10 KiB (1%)
```
The `.exe` that pyinstaller makes with this one works as expected.

**Comment by bitraid** [comment]
I just tried an `.ico` created with `icotool` and decreasing size order, but still the same problem...

**Comment by bitraid** [comment]
There is a program in `icoutils` called `wrestool` which extracts `.exe` resourses.
If i try it on `qutebrowser.exe` i get this warning, which i don't on other files (last 7 lines):
```
$wrestool -o /dev/nul -x qutebrowser.exe
wrestool: qutebrowser.exe: don't know how to extract resource, try `--raw'
wrestool: qutebrowser.exe: don't know how to extract resource, try `--raw'
wrestool: qutebrowser.exe: don't know how to extract resource, try `--raw'
wrestool: qutebrowser.exe: don't know how to extract resource, try `--raw'
wrestool: qutebrowser.exe: don't know how to extract resource, try `--raw'
wrestool: qutebrowser.exe: don't know how to extract resource, try `--raw'
wrestool: qutebrowser.exe: don't know how to extract resource, try `--raw'
wrestool: qutebrowser.exe: mismatch of size in icon resource `-1' and group (19496 vs 3752)
wrestool: qutebrowser.exe: mismatch of size in icon resource `-2' and group (1384 vs 2216)
wrestool: qutebrowser.exe: mismatch of size in icon resource `-3' and group (1736 vs 1384)
wrestool: qutebrowser.exe: mismatch of size in icon resource `-4' and group (2216 vs 38188)
wrestool: qutebrowser.exe: mismatch of size in icon resource `-5' and group (3752 vs 9640)
wrestool: qutebrowser.exe: mismatch of size in icon resource `-6' and group (5672 vs 4264)
wrestool: qutebrowser.exe: mismatch of size in icon resource `-7' and group (11432 vs 1128)
```

**Comment by bitraid** [comment]
Anyway, [Icon Pro](https://github.com/HerbertLausmann/HL.IconPro) is an open source windows program which also creates working `ico` files.

**Comment by The-Compiler** [comment]
Sorry, I kinda lost track of this - @bitraid, any chance you want to open a PR with an updated `.ico` file (containing the same resolutions as the current one) using Icon Pro?

**Comment by bitraid** [comment]
Actually, it turns out that Windows (Explorer) only uses the sizes 16, 32, 48 and 256 for application icons. It's not a problem of icotool. I'll open a pr with a proper icon.

**Comment by bitraid** [comment]
I think we should include a 32 bit color depth set. It's the native color depth for most screens and it looks better. All major browsers have it (firefox only has 32 bit - ie also has 4 bit!). I'll open a new PR...
