### ISSUE TITLE
homepage and pdf

### ISSUE THREAD

**Issue by HanaO00** [qutebrowser/qutebrowser#3605]
Hello, iconfigure my homepage in qutebrowser like this : 
c.url.default_page = 'file:///home/user/folder/index.html'

And install pdfjs, but homepage and pdf doesn't work, pdf open popup for download

**Comment by The-Compiler** [comment]
You need to configure `url.start_pages` instead, `url.default_page` is the page opened when you do `:open -t` or `-w` without an URL.

pdfjs is not supported with the QtWebEngine backend yet (which is currently the default), see #2330.
