### ISSUE TITLE
Add Read Mode

### ISSUE THREAD

**Issue by NWuensche** [qutebrowser/qutebrowser#3609]
Hello everybody,

it would be so nice if there would be an option to use a read mode for text. It makes reading long texts so much easier!

**Comment by jgkamat** [comment]
I use the [readability userscript](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/readability), which fullfills this need for me perfectly.

**Comment by The-Compiler** [comment]
Yep - no plans to add something like that to the core if there's a userscript which works well 😄
