### ISSUE TITLE
renderer crashes on some khronos.org pages

### ISSUE THREAD

**Issue by craftyguy** [qutebrowser/qutebrowser#3611]
The following page causes the 'renderer process' to crash:
https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glClear.xml

I've tried the latest stable release 1.1.1, and also the latest (as of now) master branch.

Output from opening page with --debug is here: https://craftyguy.net/paste/7Awswoqz

```
qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017
```

**Comment by The-Compiler** [comment]
Reported upstream as [QTBUG-66488](https://bugreports.qt.io/browse/QTBUG-66488).

**Comment by janesma** [comment]
The same page crashes in chromium brower.

**Comment by The-Compiler** [comment]
@janesma Works fine in Chromium for me (64.0.3282.167 on Archlinux).

**Comment by janesma** [comment]
Surprising... Debian unstable has 64.0.3282.119, which still crashes.  I'll try to verify with your version of chromium.

**Comment by The-Compiler** [comment]
I'm guessing it's not the version, but something about how it's been compiled.
