### ISSUE TITLE
confirm_quit=downloads should not prompt with more than one window

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#3615]
(I feel like I have already seen this somewhere...)

With tabs_are_windows and confirm_quit=downloads, Qutebrowser will prompt for confirmation when quitting any window, even if there is more than one open.
I'd expect that it only prompted when only one window was left, because that would interrupt the download.  Otherwise, the prompt is a useless annoyance.

**Comment by The-Compiler** [comment]
That setting is broken with multiple window indeed... I'm tracking related issues in #632 but I should probably rename that to make it more obvious.
