### ISSUE TITLE
Tab freezes when searching for a word on a specific website

### ISSUE THREAD

**Issue by bheadmaster** [qutebrowser/qutebrowser#3616]
Steps to reproduce:

- open the following link in qutebrowser: http://www.wissen.de/rechtschreibung/deklinationstabellen
- close the pop-up if it opens
- type `/einem` and press enter
- the tab should now freeze

It doesn't affect other tabs though, and freezes even when I disable javascript or run it with --temp-basedir.

Can anyone replicate this?

***

Version info

qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.2-2-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/lark/.cache/qutebrowser
config: /home/lark/.config/qutebrowser
data: /home/lark/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:01:09

**Comment by The-Compiler** [comment]
Works fine here. Can you check whether you get the same behaviour with the Qt simplebrowser (in `/usr/share/doc/qt/examples/webenginewidgets/simplebrowser/` when you install `qt5-examples` from the AUR).

You should be able to copy it somewhere writable, then do `qmake && make` to build it.

**Comment by bheadmaster** [comment]
I found `qt5-examples` in `Extra` repo.

The issue doesn't happen with simplebrowser.

**Comment by The-Compiler** [comment]
Weird! Can you start it in a terminal, and do `kill -USR1 pid` when it hangs? It should hopefully print a Python stacktrace then.

**Comment by bheadmaster** [comment]
Sure, this is what I got:

>[~]$ qutebrowser
>[0220/105320.642598:WARNING:stack_trace_posix.cc(648)] Failed to open file: >/home/lark/#7864450 (deleted)
>  Error: No such file or directory
>10:53:21 INFO: Request to script.ioam.de blocked by host blocker.
>10:53:21 INFO: Request to cdn.interactivemedia.net blocked by host blocker.
>10:53:21 INFO: Request to www.google-analytics.com blocked by host blocker.
>10:53:22 INFO: Request to pagead2.googlesyndication.com blocked by host blocker.
>10:53:22 INFO: Request to static.plista.com blocked by host blocker.
>Current thread 0x00007fb45ec9f540 (most recent call first):
>  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 148 in qt_mainloop
>  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 138 in run
>  File "/usr/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 188 in main
>  File "/usr/bin/qutebrowser", line 11 in <module>
>10:53:41 WARNING: Text 'einem' not found on page!

The last line `Text 'einem' not found on page!` only appeared after I closed qutebrowser.
Also, don't know if I mentioned it in the original post, but the rest of the browser works fine, I can switch tabs, other tabs work fine, the only tab that freezes is the one where I search for the word.

**Comment by bheadmaster** [comment]
I managed to reproduce the issue in the simplebrowser!

Opening the link mentioned in the OP and searching for the letter `e` freezes the tab!

**Comment by The-Compiler** [comment]
I can reproduce the same issue in Chromium - so this seems to be some issue with that and/or that page.
