### ISSUE TITLE
tabs.switching_delay doesn't have correct maximum value

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3629]
```
17:57:39 DEBUG    config     config:set_str:400 Setting tabs.show_switching_delay (type Int) to 999999999999999999999999 (converted from '999999999999999999999999')
17:57:39 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabwidget.py", line 351, in _on_config_changed
    self._on_show_switching_delay_changed()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabwidget.py", line 366, in _on_show_switching_delay_changed
    self._auto_hide_timer.setInterval(config.val.tabs.show_switching_delay)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

**Comment by thakkardharmik** [comment]
@The-Compiler Hey I am newbie. Shall I give this a try?

**Comment by jgkamat** [comment]
@thakkardharmik Yup, I think this is a simple starter issue if you're interested in contributing to qb!

You probably want to take a look at [configdata.yml](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/config/configdata.yml#L1326), which has all the configuration settings. 

If you take a look at the other settings in the file, there's the `maxval` key on some of them, which I think should do the job in this case. I'm not sure exactly how to bound the negative side though, which would be nice too :).

**Comment by The-Compiler** [comment]
@thakkardharmik, @AlternateData picked this up in the meantime, see #3733 if you're curious :smile:
