### ISSUE TITLE
sqlite error handling issues

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3630]
I still see a lot of sqlite errors which shouldn't be exceptions in crash logs, even with v1.0.4 or newer.

## Error during init

- [x] https://crashes.qutebrowser.org/view/294a15da
- [x] https://crashes.qutebrowser.org/view/8bb17883
- [x] https://crashes.qutebrowser.org/view/65963f01
- [x] https://crashes.qutebrowser.org/view/67d05979
- [x] https://crashes.qutebrowser.org/view/75dad59c
- [x] https://crashes.qutebrowser.org/view/10eae70c
- [x] https://crashes.qutebrowser.org/view/dfccde68
- [x] https://crashes.qutebrowser.org/view/a9e700ae
- [x] https://crashes.qutebrowser.org/view/bb730255
- [x] https://crashes.qutebrowser.org/view/fd374008
- [x] https://crashes.qutebrowser.org/view/e6b42496
- [x] https://crashes.qutebrowser.org/view/4f0b6c1e and others by the same user (out of memory)
- [x] https://crashes.qutebrowser.org/view/3057b6b4, https://crashes.qutebrowser.org/view/b93db6d3
 ([ ] disk I/O error while setting WAL)
- [ ] https://crashes.qutebrowser.org/view/cf6ec105 and others ("locking protocol" while turning on WAL?)

## Error when inserting

- [x] https://crashes.qutebrowser.org/view/fb775fe0
- [x] https://crashes.qutebrowser.org/view/b2de657e
- [x] https://crashes.qutebrowser.org/view/3d9bccda
- [x] https://crashes.qutebrowser.org/view/5bfc5080
- [x] https://crashes.qutebrowser.org/view/55ae0bf6
- [x] https://crashes.qutebrowser.org/view/b677d5bc
- [x] https://crashes.qutebrowser.org/view/349bfb77
- [x] https://crashes.qutebrowser.org/view/8bd2a64d
- [x] https://crashes.qutebrowser.org/view/29cdad15
- [x] https://crashes.qutebrowser.org/view/a53f67a6 (disk I/O error)
- [x] https://crashes.qutebrowser.org/view/c1d235b5 (disk I/O error)

## Error while selecting

- [x] https://crashes.qutebrowser.org/view/63ec75c8 (no such table, probably the user's fault)
- [x] https://crashes.qutebrowser.org/view/21969b87
- [x] https://crashes.qutebrowser.org/view/f5ea9369 (and others by the same user) 
- [x] https://crashes.qutebrowser.org/view/5f4b6ed5 (database disk image is malformed)

**Comment by rcorre** [comment]
Those crashes ask for a user/password to view them, what are the errors?

**Comment by The-Compiler** [comment]
Almost all of them are `SQLITE_IOERR` (disk I/O error) or `SQLITE_CANTOPEN` (can't open database). I'll add those to `environmental_errors`.

**Comment by The-Compiler** [comment]
All fixed except the `SQLITE_PROTOCOL` one. For that one, I only see [four crash reports](https://crashes.qutebrowser.org/lists?search=locking+protocol) from two users. We get it when running `PRAGMA journal_mode=WAL`, but the [sqlite docs](https://sqlite.org/rescode.html) say:

> The SQLITE_PROTOCOL result code indicates a problem with the file locking protocol used by SQLite. The SQLITE_PROTOCOL error is currently only returned when using WAL mode and attempting to start a new transaction. There is a race condition that can occur when two separate database connections both try to start a transaction at the same time in WAL mode. The loser of the race backs off and tries again, after a brief delay. If the same connection loses the locking race dozens of times over a span of multiple seconds, it will eventually give up and return SQLITE_PROTOCOL. The SQLITE_PROTOCOL error should appear in practice very, very rarely, and only when there are many separate processes all competing intensely to write to the same database.

No idea why that would happen. But since it happens very rarely, let's ignore it for now.
