### ISSUE TITLE
Netflix [qt5-webengine-widevine]

### ISSUE THREAD

**Issue by Waples** [qutebrowser/qutebrowser#3639]
Netflix/widevine doesn't work anymore (maybe for some time, haven't watched netflix in some time).

**Version**:
- qt5-webengine-widevine-1:61.0.3163.100-2-x86_64 *(AUR)*
- Qutebrowser v1.1.1
```
Version info

qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10

sip: 4.19.7
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.4-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

Please specify if you need more info for this.

**Comment by jgkamat** [comment]
Can you check the DRM entry in the [faq](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc), and see if setting the value listed there resolves the issue?

**Comment by Waples** [comment]
Doesn't work, also looks the same situation as I have described before.

**Comment by Waples** [comment]
qt.args doesn't change for some reason; used
```:set qt.args '["ppapi-widevine-path=/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so"]'
:restart
```

**Comment by The-Compiler** [comment]
Do you have a `config.py`? if so, do you [load autoconfig.yml in it](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#loading-autoconfigyml)?

**Comment by Waples** [comment]
adding c.qt.args = ['ppapi-widevine-path=/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so']
to my config.py fixed the issue
