### ISSUE TITLE
`bind` fails to override default binding

### ISSUE THREAD

**Issue by erich-sch** [qutebrowser/qutebrowser#3642]
I tried to do:
```
:bind ;io hint images spawn --userscript ocr
```

But when I try to press the keys it triggers the default binding `;i hint images` and doesn't let me press the `o` key.

Typing:
```
:hint images spawn --userscript ocr
```
Executes the userscript successfully.

I'm currently on qutebrowser v.1.1.1

**Comment by The-Compiler** [comment]
The `;i` binding shadows your `;io` binding, so you'll need to `:unbind ;i` for yours to work.
