### ISSUE TITLE
Having trouble trying to get 4chan x working on qutebrowser

### ISSUE THREAD

**Issue by qutetemp** [qutebrowser/qutebrowser#3644]
I've also opened an issue here: https://github.com/ccd0/4chan-x/issues/1847

4chan-x gets reset everytime I visit a new page.
I've enabled cookie storage, local storage, javascript,cache.appcache.
I think I recall The-Compiler also uses it and I'm making this issue here in hopes I'll get to the bottom of this faster.

**Comment by The-Compiler** [comment]
What does "gets reset" mean exactly? Also, please show your version info from `:version` - there's a reason the issue template asks you for it, so I don't have to :wink:

**Comment by The-Compiler** [comment]
Currently GreaseMonkey scripts use local storage, which won't be saved with private browsing on - a possible way to improve this is tracked in #3238.

> edit2: It works, but takes like a few seconds to load everytime. Is this expected behaviour ?

With QtWebKit, GreaseMonkey scripts can only load after a page finished loading. They load earlier with the default QtWebEngine backend.

**Comment by qutetemp** [comment]
Ok, got it thanks.
