### ISSUE TITLE
Feature Request - SupportRegular Expression Search

### ISSUE THREAD

**Issue by atoponce** [qutebrowser/qutebrowser#3655]
I know that it already supports `:set search.ignorecase` and `:set search.incremental`. It would also be nice to have `:set search.regex` or something similar for regular expression searching on website content. Default could be `false`, requiring you to set it to `true` if you know you need it.

Low priority, but I don't know of any other browser that does this, and this comes up frequently enough in my web browsing, that it would be nice to have.

If this is a duplicate of another issue, let me know. I couldn't find one, although I didn't search too dilligently.

**Comment by The-Compiler** [comment]
This isn't possible until QtWebEngine/Chromium [adds such a feature](https://bugreports.qt.io/browse/QTBUG-50420). In theory, qutebrowser could reimplement page searching in JavaScript entirely, but I doubt it's worth the effort.
