### ISSUE TITLE
Request: Add extra downloads to the new release

### ISSUE THREAD

**Issue by TheVirginianMarxist** [qutebrowser/qutebrowser#3669]
Most of your releases provided .deb and .dmg downloads for Linux and macOS clients and the official website's install guide says to grab the latest .deb download file from release and install it from there but this was not provided and I would prefer to use the latest Qutebrowser version without having to compile the entire thing since it's a huge project with a lot of dependencies namely in QT and Python which is a mess to compile. My only request is that at least the latest release provides a .deb prepackaged binary for ease of installation.

**Comment by jgkamat** [comment]
For the deb downloads, I *think* that's managed by @fiete201, who does this in their spare time (and should be published eventually).

The deb file dosen't actually include any of the dependencies, most of them are pulled from the repo (and you could keep using those dependencies if you install from source), but I completely understand that it's a bit inconvenient.

For the mac os builds, you can see [this post on the mailing list](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2018-March/000039.html).

**Comment by The-Compiler** [comment]
We decided to instead [rewrite the install instructions](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#debian-stretch--ubuntu-1704-and-1710) to get the packages from Debian instead of re-uploading them in qutebrowser's repo.
