### ISSUE TITLE
Webengine slows desktop with compton in XFCE, nvidia card

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [qutebrowser/qutebrowser#3674]
When I use the webengine backend, there is visible lag on the desktop with the browser running with compton.
When I disable vsync in compton the lag goes away but tearing is there.

**Comment by jgkamat** [comment]
I think that this is because on wayland, webengine crashes if you don't force software rendering (so I think it's being forced).

See https://github.com/qutebrowser/qutebrowser/issues/2932 for more information.

**Comment by The-Compiler** [comment]
What Qt version and distribution (`:version`)? Do you see the same behaviour with [QupZilla](https://qupzilla.com/) (aka. Falcon)? If not, do you see it when you do e.g. `QT_QPA_PLATFORM=xcb qupzilla`?

**Comment by dubbadubbadubbacha** [comment]
I am using qt5 5.10. I do not use QupZilla. Also software rendering is disabled in my settings.

**Comment by The-Compiler** [comment]
Can you please test with QupZilla? I'm pretty sure this isn't a qutebrowser-specific issue.

**Comment by dubbadubbadubbacha** [comment]
I just built and tested with qupzilla and I'm getting the same problem.

**Comment by The-Compiler** [comment]
I don't know who's to blame then I'm afraid, but it isn't qutebrowser :wink:
