### ISSUE TITLE
key_mappings doesn't map keys in the middle of a keychain anymore

### ISSUE THREAD

**Issue by jakanaka-evan** [qutebrowser/qutebrowser#3678]
The bindings.key_mappings setting used to unconditionally map keys anywhere in the keychain, but now it only maps the keys that are typed first in the key-chain.

For example if you set
`c.bindings.key_mappings['ä'] = ']'`
in your config.py, typing `ää` used to result in `]]`.
Now it results in `]ä`.

I'm actually thinking about writing a quick fix for this, I'm just not sure how exactly the key_mappings should work.
Currently if you bind `äb` to something, pressing `ä]` would not result in `]]`, as key_mappings would be thought of as "unnecessary". So the philosophy seems to be to only use key_mappings if bindings are not found.

On the other hand I would personally use key_mappings unconditionally for each key (except for insert/pass-through mode insertion). This would make it unable to access any `ä` keybinding, but I see the whole setting as more of an international keyboard layout by-pass. E. g. you use key_mappings to map "weird" keys like `ä, ö, ß` to their corresponding US keyboard key, and then only use ASCII keys in bindings. This would also make it more straight forward to implement.

**Comment by The-Compiler** [comment]
I told you in IRC that it's okay for mappings to be preferred over bindings, but it turns out there was a reason it's not that way: #2995.

**Comment by jakanaka-evan** [comment]
Would it be okay to:
1. try matching the original sequence
2. if a match isn't found, map each key in the sequence with key_mappings and try agan.

This would make "mixed" bindings (e. g. `bind äb]`) hard to access, but i guess covering every such corner case is near impossible to accomplish consistently.

**Comment by The-Compiler** [comment]
Yeah, that approach seems fine to me. I already have a working solution, will push it after implementing another test or two.

**Comment by The-Compiler** [comment]
Just pushed my fix! If that looks different from what you had in mind, or you find some other issues, please let me know ASAP. :smile:

**Comment by jakanaka-evan** [comment]
The only minor problem I can see is that having both `äb` and `]c` bind to something will show only the `äb` binding in the keyhint widget after pressing `ä`, despite `]c` also being reachable just fine. Other than that, it looks fine.
