### ISSUE TITLE
Failed to start with QtWebEngine backend because "cannot import name QtWebEngineWidgets" 

### ISSUE THREAD

**Issue by caonimah** [qutebrowser/qutebrowser#3679]
I'm running 32-bit Arch Linux Arm on a raspberry pi 3, installed Qutebrowser together with qt5-webengine 5.10.1-1 from the Arch repository. But Qutebrowser can't start with QtWebEngine backend because 'QtWebEngineWidgets' cannot be imported. A quick search on duckduckgo and github issues page didn't give me any hints of help.

Maybe Qutebrowser is not officially supported for ARM-based distros, but the Webkit backend is running and I am now using it to submit this bug report. I really appreciate any suggestions about the possible cause of this issue. Thank you!

Here are the details from qute:version

qutebrowser v1.1.2
Git commit: 
Backend: new QtWebKit (WebKit 602.1)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.255.255
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.14.24-1-ARCH-armv7l-with-arch, 32bit
Linux distribution: Arch Linux ARM (unknown)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version:

**Comment by jgkamat** [comment]
I think this error occurs if the PyQt5 you have installed dosen't have qtwebengine support.

I *think* someone has gotten qtwebengine running on arm, but I'm not sure.

On normal arch, I think if you have `qt5-webengine` and `python-pyqt5` installed, it should just work, but it's possible that there might be a packaging issue for arch linux arm. The [optional dependencies here](https://archlinuxarm.org/packages/arm/python-pyqt5) seem to suggest it's supported though.

To test, you can run ` import PyQt5.QtWebEngineWidgets` in a python shell, and see if it passes.

**Comment by caonimah** [comment]
No I can't import PyQt5.QtWebEngineWidgets in python shell. ModuleNotFoundError.
Qutebrowser works perfectly fine on my normal arch. In this Rpi Arch, I also have python-pyqt5 and qt5-webengine installed. 
So your suggestion is to file an issue about the python-pyqt5 package to the Arch Arm repo maintainer?

**Comment by jgkamat** [comment]
Yes, that is my best guess at least (although, I know little to none about packaging). Maybe @The-Compiler has some thoughts as well? :)

**Comment by caonimah** [comment]
OK, thank you. I will do that and see how it works out.
 
BTW, I see WebEngine is the preferred choice and its advantage over Webkit has also been briefly explained in the FAQ. My question is, how much worse is actually the Webkit variant in practice? Is it considered as stable as its webengine counterpart?

I have to say, Qutebrowser is running surprisingly well on my rpi3 so far. So much faster than surf, which I was forced to use for a little while before I could get qutebrowser running with Webkit.

**Comment by jgkamat** [comment]
@caonimah, I don't think webengine is worse than webkit in any way. In fact, in some areas, webkit is better and has a more established feature set. The main difference is the rendering, so some sites may render improperly on webkit (because they may only be supported under chrome), but you could make the argument that those sites are broken anyway. Webkit(-ng) is also planned to be supported for the forseeable future.

I personally am fine using webkit (the new version, which you are using), in many scenarios where webengine won't work, such as in a VM.

**Comment by The-Compiler** [comment]
The ArchlinuxARM [package](https://archlinuxarm.org/packages/armv7h/python-pyqt5) indeed doesn't have QtWebEngine-related files in it. There are lots of posts about it in ArchlinuxARM's forums, but nobody seems to care ¯\_(ツ)_/¯
