### ISSUE TITLE
Decrease size of sideways tabs

### ISSUE THREAD

**Issue by The-Soulless** [qutebrowser/qutebrowser#3685]
Hello, I would like to know if there is anyway to decrease the size of sideways tabs, they're a bit to large for me. I've attached an image showing their size
https://a.doko.moe/ulbgbl.png
Reupload as some AVs dislike doko.moe
https://a.pomfe.co/uloylt.png

**Comment by jgkamat** [comment]
@The-Soulless, I think you can get the behavior you are looking for by customizing `tabs.width`

`:set tabs.width 10%`

**Comment by The-Soulless** [comment]
Exactly what I wanted, thank you for the help and the quick reply

**Comment by jgkamat** [comment]
Perfect, glad you were able to get it working! :)
