### ISSUE TITLE
FAQ suggestion - Is Qutebrowser secure?

### ISSUE THREAD

**Issue by seantdg** [qutebrowser/qutebrowser#3686]
FAQ suggestion - Is Qutebrowser secure?

If a vulnerability is found, firefox and chrome are quick to patch. What is the process to ensure qutebrowser is also patched?

**Comment by seantdg** [comment]
should be an easy ELI5 type answer! :)

**Comment by The-Compiler** [comment]
I wanted to write that for a while, thanks for the reminder :wink: - added as 8. [in the FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc). Let me know what you think!

**Comment by seantdg** [comment]
looks very good - thank you my friend and keep up the good work!
