### ISSUE TITLE
Configurable minimum tab width

### ISSUE THREAD

**Issue by noctuid** [qutebrowser/qutebrowser#3690]
I prefer firefox's behavior where tabs are fixed width so that the tab title is always visible. Being able to configure the minimum width for horizontal tabs would be fine as well.

**Comment by jgkamat** [comment]
Would you prefer a minimum width setting, or a fixed width setting, I think both could be possible.

Do you think the setting should apply to pinned tabs as well? I think that pinned tabs should get an exemption, but I'm not sure exaclty what behavior you're looking for for that.

**Comment by noctuid** [comment]
I'd prefer a minimum width setting personally. I agree that it would be preferable for this setting to not apply to pinned tabs, but I think in that case there should be a separate minimum width setting for pinned tabs as it could be useful when `tabs.pinned.shrink` is false and/or `tabs.title.format_pinned` has been altered.

**Comment by noctuid** [comment]
@jgkamat Thanks!
