### ISSUE TITLE
Page scrolls to first search match when (re)loaded

### ISSUE THREAD

**Issue by Ram-Z** [qutebrowser/qutebrowser#3693]
When a search is active and a page is loaded (either a new page or reload the current page), it will scroll down to the first match of the current search.

Version: http://paste.the-compiler.org/view/fabc31f5

### Steps to reproduce
1. `open https://github.com/qutebrowser/qutebrowser`
2. `/pdf.js<cr>`
3. `gg`
4. `r`

I would expect the page to be reloaded and scrolled to where I last left it (top of page), but the page will scroll down to the bottom, where the first match of "pdf.js" is.

**Comment by jgkamat** [comment]
Hmm, I cant seem to reproduce this on the same commit.

Can you try it in `--temp-basedir` and without the uncommitted changes?

**Comment by The-Compiler** [comment]
I can reproduce this, but only starting with Qt 5.9.
