### ISSUE TITLE
Search button not working on WOW air website

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#3694]
This is a rather specific issue, but given that it does not arise for Falkon (the successor to Qupzilla), I assume that it is specific to qutebrowser, and that maybe it can be fixed.

Steps to reproduce:

1. Go to https://wowair.com/ and pick a country. (I've tried US, Canada, and France.)
2. Select any origin, destination, and dates.
3. Click "Search flights".

Expected behavior: A new page with search results.

Actual behavior: Nothing at all. It's like the button has no functionality.

Also, the same issue arises when using hints: pressing `f` gives me a hint key for the search button, but hitting the hint key does nothing.

In Falkon, everything works as expected.

My qutebrowser info:

    qutebrowser v1.1.1
    Git commit: 7fd0b5236 (2018-02-28 08:11:23 +0100)
    Backend: QtWebEngine (Chromium 61.0.3163.140)

Any ideas?

**Comment by brianbuccola** [comment]
Update: I just ran `qutebrowser --temp-basedir`, and everything worked as expected. So, something is up with my qutebrowser settings, it seems. I'll try to get to the bottom of this.

**Comment by jgkamat** [comment]
`--temp-basedir` clears cookies and cache as well, so it could have something to do with that. I would start by looking at your javascript settings (if you have changed them).

It works fine for me when I give the site javascript.

**Comment by The-Compiler** [comment]
Their JavaScript fails when www.google-analytics.com is blocked by the host blocker:

```
[https://valholl-prd.wowair.com/js/widget.0017.js:1] Uncaught TypeError: l.getAll is not a function
```

Not much qutebrowser can do here really, at least as long as the adblocker is a simple host blocker...

**Comment by brianbuccola** [comment]
Ah, that's too bad. Thanks anyway for solving the mystery!
