### ISSUE TITLE
ESC behaviour in hinting mode

### ISSUE THREAD

**Issue by qutetemp** [qutebrowser/qutebrowser#3696]
ver info: http://ix.io/UV9

Can I make ESC completly exit hinting mode everytime ? Right now it cancels the last pressed key in hinting mode. Strangely I don't remember this being the case a while ago and now this completely throws me off.

**Comment by The-Compiler** [comment]
This shouldn't be happening since c7cccf4ba0ae512254f6be72492e8fa9775da39b (which the commit you're on includes).

Can you reproduce it with `--temp-basedir`? Can you please do `:report` after reproducing this so I can take a look at the logs (make sure to mention this issue, #3696)?

**Comment by qutetemp** [comment]
>edit: Though your version info also shows v1.1.2 - is it possible that you pulled a newer version but didn't restart qutebrowser yet?

That was the case, my bad.
