### ISSUE TITLE
Regression: numkey plus/minus to zoom no longer works

### ISSUE THREAD

**Issue by SirCmpwn** [qutebrowser/qutebrowser#3701]
The +/- keys in the number row of the main key area still works (US layout).

**Comment by The-Compiler** [comment]
Does it still work if you bind `<Num++>` and `<Num+->`? Those are now treated as different keys, but I agree this should be handled better. On a macOS I tried yesterday, for some reason, no binding worked as everything was prefixed with `Num+`...

I guess either that modifier could just be stripped off (so you couldn't bind numpad-keys separately), or qutebrowser should fall back to the non-`Num+` binding if no `Num+` binding exists.

**Comment by SirCmpwn** [comment]
>Does it still work if you bind <Num++> and <Num+->? Those are now treated as different keys, but I agree this should be handled better. On a macOS I tried yesterday, for some reason, no binding worked as everything was prefixed with Num+...

Sorry for the confusion, exactly what should I put in `config.py` to test your question?

**Comment by The-Compiler** [comment]
This should work (though I can't test it as I don't have a numpad):

```python
config.bind('<Num++>', 'zoom-in')
config.bind('<Num+->', 'zoom-out')
```

**Comment by SirCmpwn** [comment]
Yep, that works.

**Comment by SirCmpwn** [comment]
Related: numpad enter no longer completes the download prompt.

**Comment by mschilli87** [comment]
> I guess either that modifier could just be stripped off (so you couldn't bind numpad-keys separately), or qutebrowser should fall back to the non-Num+ binding if no Num+ binding exists.

The fallback-option would bring most advantages I think as it would behave as before/expected out of the box but allow the users to bind more functions by distinguishing between the two if they wanted to.

**Comment by The-Compiler** [comment]
If someone has a chance to test this before I get to it - here's a patch:

```diff
diff --git a/qutebrowser/keyinput/basekeyparser.py b/qutebrowser/keyinput/basekeyparser.py
index 1582a5485..bcb081221 100644
--- a/qutebrowser/keyinput/basekeyparser.py
+++ b/qutebrowser/keyinput/basekeyparser.py
@@ -149,6 +149,10 @@ class BaseKeyParser(QObject):
         # First, try a straightforward match
         match, binding = self._match_key(sequence)
 
+        # Then try without optional modifiers
+        sequence = sequence.strip_modifiers()
+        match, binding = self._match_key(sequence)
+
         # If that doesn't match, try a key_mapping
         if match == QKeySequence.NoMatch:
             mapped = sequence.with_mappings(config.val.bindings.key_mappings)
diff --git a/qutebrowser/keyinput/keyutils.py b/qutebrowser/keyinput/keyutils.py
index a56efeab8..bda8a0294 100644
--- a/qutebrowser/keyinput/keyutils.py
+++ b/qutebrowser/keyinput/keyutils.py
@@ -510,6 +510,12 @@ class KeySequence:
 
         return self.__class__(*keys)
 
+    def strip_modifiers(self):
+        """Strip optional modifiers from keys."""
+        modifiers = Qt.KeypadModifier
+        keys = [key & ~modifiers for key in self._iter_keys()]
+        return self.__class__(*keys)
+
     def with_mappings(self, mappings):
         """Get a new KeySequence with the given mappings applied."""
         keys = []
@@ -519,6 +525,11 @@ class KeySequence:
                 new_seq = mappings[key_seq]
                 assert len(new_seq) == 1
                 key = new_seq[0].to_int()
+            elif key_seq.strip_modifiers() in mappings:
+                new_seq = mappings[key_seq.strip_modifiers()]
+                assert len(new_seq) == 1
+                key = new_seq[0].to_int()
+
             keys.append(key)
         return self.__class__(*keys)
 
```

Please test the following:

- Numpad keys work like the non-numpad variants with the default bindings
- If you add a `Num+...` binding, that takes precedence
- You can add a mapping without `Num+` to `bindings.key_mappings` as well.

**Comment by The-Compiler** [comment]
Hm, nope, that won't work as-is. I found a keyboard with a numpad, though :wink:

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by The-Compiler** [comment]
You're welcome! Should work in all cases (bindings, key mappings, and using it as count) now - let me know if you notice more issues, though.

**Comment by SirCmpwn** [comment]
Tested that your fix works. Thanks again!
