### ISSUE TITLE
Bookmarks : Tags or Groups ?

### ISSUE THREAD

**Issue by slashome** [qutebrowser/qutebrowser#3703]
Hi dear Qutebrowser create (aka The-Compiler) and contributors !

I've just switched to Qutebrowser and I'm very satisfied with it ! I just wonder if there is a way to introduce tags and / or groups for bookmarks/quickmarks.

As I already saw the ~/.config/qutebrowser/bookmarks/urls file, I guess it will not really easy, so I'm just asking :)

Nice job again for this wonderfull browser !

**Comment by The-Compiler** [comment]
Duplicate of #882

**Comment by The-Compiler** [comment]
FWIW @rcorre is currently working on a rewrite of how bookmarks/quickmarks are handled, which I think will include tags.

**Comment by slashome** [comment]
Hi ! Sorry for the duplicate, I've searched for same topic but didn't found it :/
