### ISSUE TITLE
Preview hint mode

### ISSUE THREAD

**Issue by Limero** [qutebrowser/qutebrowser#3708]
## Feature request
Imagus is the only extension that I miss from Firefox. What it does is, when you hover over an image, it previews it in a small window.

I think the best equivalent in qutebrowser would be if a preview hint mode was added. Maybe `;p` would be a good default bind, and `esc` to hide the preview window.

## What it looks like in Imagus
![image](https://user-images.githubusercontent.com/639787/37314384-14194826-2654-11e8-8de9-b304c0717da3.png)

## Link to Imagus
https://addons.mozilla.org/en-US/firefox/addon/imagus/ (Firefox)
https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab (Chrome)

**Comment by The-Compiler** [comment]
I added this to #521 which tracks all kinds of useful hint modes. Note that you can already get this functionality by using a GreaseMonkey script such as [Mouseover Popup Image Viewer](https://greasyfork.org/en/scripts/404-mouseover-popup-image-viewer).
