### ISSUE TITLE
search for a string within the page

### ISSUE THREAD

**Issue by jardous** [qutebrowser/qutebrowser#3709]
I as a user would like to be able to search for a string (RE support would also be nice) in the current page.

I couldn't find this in the docs so I guess that is a missing feature. Would be nice to have.

**Comment by The-Compiler** [comment]
`/foo` (like in vim) or `:search foo` does exactly that.

**Comment by jardous** [comment]
Ah - I have missed that. Thanks a lot. That was quick :)
