### ISSUE TITLE
Do we have Read Mode?

### ISSUE THREAD

**Issue by peet1234** [qutebrowser/qutebrowser#3710]
Hi, Do qutebrowser have  read mode to read only article ?

**Comment by The-Compiler** [comment]
Check the [readability userscript](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/readability) (and the [userscript docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc)).
