### ISSUE TITLE
Regression: error while getting hint elements

### ISSUE THREAD

**Issue by aramiscd** [qutebrowser/qutebrowser#3711]
this bug is present in release 1.2.0 ([paste](http://paste.the-compiler.org/view/c9a6199f)) and on current master ([paste](http://paste.the-compiler.org/view/b1e6e918)).

It is NOT present in release 1.1.2.

When I visit https://www.kuechenstud.io/lagedernation/ `:hint` (key `f`) doesn't work.  I get the error `ERROR: There was an error while getting hint elements`.

[screenshot](http://aramis.auriga.uberspace.de/public/e9da62ec9f7abcd7d7b2a50cd9ed0bdbbc8451943b32bf40797af7ac38c33e65.png)

When I scroll down a bit, it does work.

[screenshot](http://aramis.auriga.uberspace.de/public/ff06b57c182a3c901c3583d0942a2cfcee59c7476bfbbc7d61410878a47aa1df.png)

`:hint links` works.  `:hint images` works.  `:hint inputs` works.  `:hint all` doesn't work.

**Comment by The-Compiler** [comment]
Are you sure it's the scrolling which is making a difference? Can you try if it works if you press `f` only after the page has fully loaded?

**Comment by aramiscd** [comment]
Yes it looks like the scrolling is making the difference.  I can see that the page has fully loaded since I have '{perc}' in `c.window.title_format`.

[screencast](http://aramis.auriga.uberspace.de/public/a2625d81b6adbce1f7920a8aca91145c7dec3f8db2b29ada53e2fe78b962c56f.mp4)

**Comment by The-Compiler** [comment]
Reproduced with Qt 5.9 but not 5.10. JS error:

```
15:17:29 DEBUG    js         shared:javascript_log_message:146 [:162] Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('range') does not support selection.
```

**Comment by The-Compiler** [comment]
Bisected to 7f9d4888fd3370628b5038f8591424f8d822daf7 - cc @jgkamat

**Comment by The-Compiler** [comment]
I'm guessing it's the change from:

```js
        let caret_position = null;
        try {
            caret_position = elem.selectionStart;
        } catch (err) {
            if ((err instanceof DOMException ||
                 (frame !== null &&
                  err instanceof frame.DOMException)) &&
                    err.name === "InvalidStateError") {
                // nothing to do, caret_position is already null
            } else {
                // not the droid we're looking for
                throw err;
            }
        }
```

to:

```js
    function get_caret_position(elem, frame) {
        // With older Chromium versions (and QtWebKit), InvalidStateError will
        // be thrown if elem doesn't have selectionStart.
        // With newer Chromium versions (>= Qt 5.10), we get null.
        try {
            return elem.selectionStart;
        } catch (err) {
            if (err instanceof (frame
                ? frame.DOMException
                : DOMException) &&
                err.name === "InvalidStateError") {
                // nothing to do, caret_position is already null
            } else {
                // not the droid we're looking for
                throw err;
            }
        }
        return null;
    }
```

which causes this somehow. @jgkamat do you have the time to look into this somewhen around this week?

**Comment by jgkamat** [comment]
Yup, I'll try to take a look at this tonight or tomorrow night, although I can't reproduce it right now either (I'll try qt5.9 later today).

**Comment by jgkamat** [comment]
So the issue here is:
```
window.frames[0].document.querySelectorAll("input")[2].selectionStart
```
throws a plain DOMError, rather than a 'frame.DOMError'. I think this might be a bug in chrome (which would explain why it's only visible in qt5.9. I'm going to do more testing, but the quick and dirty fix is to check to see if the error is a plain DOMError, even when we think it's in a frame.

**Comment by The-Compiler** [comment]
I assume you mean `DOMException`? I guess we could just check both, i.e. `err instanceof DOMException or (frame and err instanceof frame.DOMException)` or so?

**Comment by jgkamat** [comment]
yup, that was a typo on my part. I want to do a bit more digging around though before I change it (just to make sure that there's no bug in the frame code causing this). I'll probably submit a PR adding that in an hour or so :)

**Comment by jgkamat** [comment]
So on `5.7.1` we get a `frame.DOMException`, and on 5.10 we get `null` when accessing that variable. Since getting a plain `DOMException` (on 5.9 only) seems like a bug in the js interpreter (rather than a bug in the frame code causing this function to be called with a frame when it's not actually in a frame), I'm going to submit that PR.

**Comment by The-Compiler** [comment]
Would be great to also have an automated test for this if you can find one.
