### ISSUE TITLE
Cannot get accent keys to be entered in text fields with English alternative layout

### ISSUE THREAD

**Issue by mvrozanti** [qutebrowser/qutebrowser#3712]
[Version Info](http://paste.the-compiler.org/view/2e13da6f)

I read about it being a problem with QtWebkit package but that was last year. It's basically the only thing holding me back from ditching Firefox at the moment. 

`python3 -m scripts.keytester` recognizes accent key**press** but text displays as  `''` which I think is empty because a is `'a'` so what I _think_ I should be getting is `'''` but am not.

**Comment by The-Compiler** [comment]
Can you try with Qt 5.10.1 (e.g. [installed via tox](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#tox))? Also, can you try with another QtWebEngine based browser like [QupZilla](https://qupzilla.com/)?

**Comment by The-Compiler** [comment]
@mvrozanti any update on this?

**Comment by The-Compiler** [comment]
So you can also reproduce this with a Qt 5.10.1 (and verified this via `:version`) then? Can you please at least test with `scripts/testbrowser/testbrowser_webengine.py` in the repository (you'll need to pass an URL via the command line)?

**Comment by mvrozanti** [comment]
Sorry for the late responses. I really appreciate the point of this browser but upon further research I see that Waterfox satisfies my needs. 

```
qutebrowser v1.2.0
Git commit: 8e01353 (2018-03-13 14:41:40 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.5.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.5
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2g  1 Mar 2016

Style: QFusionStyle
Platform: Linux-4.10.0-42-generic-x86_64-with-LinuxMint-18.2-sonya, 64bit
Linux distribution: Linux Mint 18.2 (linuxmint)
Frozen: False
Imported from /home/nexor/qutebrowser/qutebrowser
Qt library executable path: /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/libexec, data path: /usr/local/lib/python3.5/dist-packages/PyQt5/Qt

Paths:
cache: /home/nexor/.cache/qutebrowser
config: /home/nexor/.config/qutebrowser
data: /home/nexor/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 0:00:06
```

I see that I'm using Qt 5.9. 

Running `py3 scripts/testbrowser/testbrowser_webengine.py google.com` was also not working. So I guess it was my Qt being out-of-date

**Comment by The-Compiler** [comment]
Indeed, nothing qutebrowser can fix then most likely - thanks for taking a look!
