### ISSUE TITLE
implement vim's "v_o" on caret mode

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#3714]
Hello,
I was just trying the webengine's caret mode and missed the `go to other end` command from vim's visual mode.

Thanks for this great addition by the way :)

**Comment by The-Compiler** [comment]
FWIW if possible, this should probably be implemented for QtWebKit's caret mode as well.

**Comment by beelzebielsk** [comment]
I'd like to take this on, though I'm not familiar with using Qt as a programmer, much less familiar with how qutebrowser uses it. I'm more intent on implementing it for QtWebEngine than for QtWebKit, though.

**Comment by beelzebielsk** [comment]
From a little initial grepping, it looks like I'd have to add a method to `browser/browsertab.py:AbstractCaret` for swapping between the different "ends" of a caret-mode selection. And then I'd have to implement this method on it's concrete subclasses like `browser/webkit/webkittab.py:WebKitCaret` and `browser/webengine/webenginetab.py:WebEngineCaret`. I'm not sure if there's anything further that I'd have to do

**Comment by beelzebielsk** [comment]
It may be a while before someone can get back to me on this. So, I'll post up milestones in my independent research. Someone else can make use of it if I drop this, or it can be critiqued/worked on when someone does find it.

I haven't done any research on how to do this for  `browser/webkit/webkittab.py:WebKitCaret`, but I've done some research on how to do this for   `browser/webengine/webenginetab.py:WebEngineCaret`

It looks like I'd have to add in a function to `caret.js` that reverses the ends of the selection, switching the base and extent (fixed and moving, respectively) ends of the selection with each other. I'd do this using:

    /* Switch the fixed end of the selection with the moving end. */
    funcs.reverseSelection = () => {
        let sel = window.getSelection();
        sel.setBaseAndExtent(
            sel.extentNode, sel.extentOffset, sel.baseNode,
            sel.baseOffset);
    }

Then I'd make a new method in `WebEngineCaret` which calls this function using `_js_call`.

Things I don't know yet:

- Is there anything else I have to do when reversing the selection ends? For instance, some of the caret functions end `CaretBrowsing.finishMove()`.
- How do I expose a function in `WebEngineCaret` for binding to a key?

**Comment by beelzebielsk** [comment]
Here's a demo of it:
![image](https://user-images.githubusercontent.com/16908019/50754195-dc8e1d80-1222-11e9-8643-e08c6a59e3f2.png)

**Comment by beelzebielsk** [comment]
Done. Sorry, I spaced out on that.
