### ISSUE TITLE
Restored tabs from the last session do not show the <title> correctly

### ISSUE THREAD

**Issue by SirCmpwn** [qutebrowser/qutebrowser#3718]
Instead they show the URL, until you refresh.

**Comment by The-Compiler** [comment]
Hmm, I see that even with `:undo` etc. - seems to be a v1.2.0 regression.

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by SirCmpwn** [comment]
I can still reproduce this behavior after updating to the latest version from the master branch. Undo too.

**Comment by The-Compiler** [comment]
Hm, indeed. I can't consistently reproduce this, but right now I can again...

**Comment by The-Compiler** [comment]
Hopefully really fixed in the latest master - let me know if you still see it. Not sure yet whether the next release is going to be v1.2.2 or v1.3.0 though.

**Comment by SirCmpwn** [comment]
Thanks! I'll test it this afternoon.

**Comment by SirCmpwn** [comment]
Fix is good, thanks!
