### ISSUE TITLE
First launch: Quickstart is shown even when URL is passed from commandline

### ISSUE THREAD

**Issue by nils-werner** [qutebrowser/qutebrowser#3720]
I am trying to use Qutebrowser as a windowless "Kiosk mode" browser, that my OS directly boots into. I want the browser to be as dumb as possible, to not do anything clever and not remember any sessions. To that end I am using a read-only Linux installation and have come up with the following `config.py`:

```python
c.tabs.show = 'never'
c.statusbar.hide = True
c.auto_save.session = False
```

and launch the browser using

```
qutebrowser https://www.ccc.de/
```

However, Qutebrowser still shows the Quickstart every time it starts. There are two tabs open: Quickstart (active tab) and CCC (inactive tab, the tab bar is hidden because of my config). Because of the OS being read-only, it has no way of remembering that it isn't started for the first time.

Is there a way of telling Qutebrowser to not do any of the "first time user" or "returning user" session stuff?

**Comment by The-Compiler** [comment]
Check your `~/.local/share/qutebrowser/state` and add something like that to your filesystem. Probably this will suffice:

```ini
[general]
quickstart-done = 1
```

**Comment by nils-werner** [comment]
Yeah, I just realized that too, thanks!
