### ISSUE TITLE
Insert mode Ctrl-A (select all) has unexpected behaviours in editable web page sections

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3721]
How to reproduce:
Open a GitHub repository web page, select a file and click "edit".
While in `insert mode`, press `Ctrl-A`.

Expected behaviour (observed in other browsers):
Have the entire file content selected.

Actual behaviour:
It looks like things are working (the visible text looks selected). However, if the selection is copied and pasted somewhere, 2 problems become visible:

1/ only the visible part of the text was selected (any part accessible through scrolling is ignored)
2/ the line numbers (which did not appear selected on the screen) are also copied and pasted, making the file unusable.

But maybe I am doing something wrong and there is a better way to select writable web content in this situation. (Obviously, what I am describing is not a common GitHub practice, but this happens on other  websites with similar writable windows and the GitHub website example is an easy way to illustrate the problem).

Thanks a lot!!! :)

Config info:
qutebrowser v1.2.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.8-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Comment by The-Compiler** [comment]
Works fine here. Can you try reproducing it with `--temp-basedir` please?

**Comment by prosoitos** [comment]
Damn. It works with `--temp-basedir` :\
I guess I now have to figure out what in my settings is messing things up.
I did change bindings (trying to get as many emacs keybindings as I can :P) and maybe that is it??? I hadn't had issues so far, but using `fake-key` on a binding that I have attributed to something else might be messy...

Here is the relevant part of my config file:

```config.bind('<Ctrl-a>', 'fake-key <Home>', mode='insert') # move to start of line
config.bind('<Ctrl-Shift-a>', 'fake-key <Ctrl-a>', mode='insert') # select all```

Seems to work for everything else...

**Comment by The-Compiler** [comment]
`:open qute://configdiff` might help. That binding shouldn't make a difference as long as you're actually pressing Ctrl-A.

**Comment by The-Compiler** [comment]
Oh, now you edited your post :wink: Well, try without that `Ctrl-a` binding.

**Comment by prosoitos** [comment]
Well, I am pressing Ctrl-Shift-A since that is what I binded to `select all`. And it works elsewhere

**Comment by prosoitos** [comment]
Ya, sorry. I was messing up with the markdown formatting of GitHub comments and it took me several times to get it right :P

**Comment by prosoitos** [comment]
Note that `Ctrl-A` works great to get to the beginning of line.
And I binded `Ctrl-Shift-A` to `select all` in caret mode with the same `fake-key <Ctrl-a>` method and I have no problem at all there. So it is strange that it would work everywhere but create those strange behaviours in the situation I described. Maybe it is something else...

**Comment by prosoitos** [comment]
OK. I removed my keybindings and the problem behaviours persist. It is something else in my setting :(

**Comment by The-Compiler** [comment]
If you can't find the setting which causes this (via `:open qute://configdiff`), can you please do `:report` after reproducing this so I can take a look at the logs?

> Ya, sorry. I was messing up with the markdown formatting of GitHub comments and it took me several times to get it right :P

Let me note that there's a "Preview" tab above the editor :stuck_out_tongue:

**Comment by prosoitos** [comment]
> Let me note that there's a "Preview" tab above the editor

Oooooooooh... Thank you for pointing that out to me :stuck_out_tongue: How to tell a total noob :roll_eyes: And you just saved me 3 edits on this very message :smile:

Re: my issue. Will do.

**Comment by prosoitos** [comment]
I am not sure how `:open qute://configdiff` can help me find the problem (sorry for being stupidly naive). It shows my config, which I already know, but I am not sure how that can help me find which of the settings cause of this problem. I just submitted a report.

Thank you for your time!

**Comment by jgkamat** [comment]
@prosoitos since the problem seems to not be present in `--temp-basedir`, it's most likeley a configuration setting thats causing this problem. Opening `qute://configdiff` lists your changes of the config (from the defaults), so you can begin checking to see which configuration option causes the unexpected behavior.

I would also just run `:fake-key <ctrl-a>` and see if that seems to work as expected (it does for me). 

For me, the bind command `:bind --mode=insert <ctrl-shift-A> fake-key <ctrl-a>` works for me (but I use autoconfig and not config.py).

**Comment by prosoitos** [comment]
That works for me too (see earlier comments).

I guess the reason I wasn't seeing the point of `qute://configdiff` is that I keep all my config in a `config.py`. So I know already what they are and can look at them and play with them easily. But I guess that would be useful if I had made changes directly using the `:set` page and didn't remember what the default vs my changes were.

**Comment by The-Compiler** [comment]
How are you copying the text after selecting? Are you using your `<Alt-w>` (`:yank selection`) binding? Can you try `<Ctrl+c>` instead?

**Comment by prosoitos** [comment]
Yes, I was using `Ctrl+w`, which works just fine in other situations. I just tried with `Ctrl+c` and have no issue :) So the problem was my `Ctrl+w` rebind. I thought that it was fine, but I guess not. At least, not everywhere.

I have now changed it for `config.bind('<Alt-w>', 'fake-key <Ctrl-c>', mode='insert')` and it works just fine :)

Thank you very much @The-Compiler for figuring out where the problem was! :)

**Comment by The-Compiler** [comment]
I think this is just how `:yank selection` works when so much JavaScript magic is involved :wink: Doing `window.getSelection().toString()` returns the same, so I don't think there's anything to be fixed here. Glad to hear you got it working via `:fake-key` though! :smile:

**Comment by prosoitos** [comment]
Yes, this `fake-key` function is sooooooo useful for people who are fussy about their keybindings :smile: Thanks to whoever came up with it! :smile:

**Comment by prosoitos** [comment]
Actually, if I may, on the subject of keybindings and `fake-key`... There is one that doesn't seem to work:

`config.bind('<Ctrl-y>', 'fake-key <Ctrl-v>', mode='command')`

I accepted the fact that it doesn't work and I use `Ctrl-v` when pasting in the command. But if you happen to know why that is, I'd be curious. Let me know also if you'd prefer that I use a different issue for this.

**Comment by jgkamat** [comment]
`fake-key` sends keys to the web page, so the statusbar never gets the `<ctrl-v>`. 

There's already a `:rl-yank` key bound to `<ctrl-y>`, but it only seems to paste out things killed in the readline buffer (do a `<ctrl-w>`, then a `<ctrl-y>`). This mirrors the behavior of readline, but maybe there should be a flag to rl-yank or an extra command to yank from the clipboard instead.

**Comment by prosoitos** [comment]
Oh, I see. I didn't know about this `fake-key` limitation. That makes sense then.

I noticed that, but most (all?) of the time, I want to paste from the clipboard (e.g. a url), so I need to use `Ctrl-v`.

I sure would be happy if there was a command to paste from the clipboard :smile: But I can certainly live with having to use `Ctrl-v` for this. What does `Ctrl-v` actually call? Maybe it is just a question of giving a command name to whatever bit of script runs when `Ctrl-v` is called????

**Comment by The-Compiler** [comment]
Note that there's `:fake-key -g` which sends a fake key to qutebrowser instead of the website. There's no command behind `ctrl-v`, it's just passed to Qt and handled there.

**Comment by prosoitos** [comment]
Oooooh! I didn't know about that! This is fantastic and totally solve my "problem".
I can now use `config.bind('<Ctrl-y>', 'fake-key -g <Ctrl-v>', mode='command')` to paste in the command :smile: 
Very cool. Thank you very much to the both of you for the help (and the great tool).
