### ISSUE TITLE
Run tests in the background

### ISSUE THREAD

**Issue by StefanoChiodino** [qutebrowser/qutebrowser#3723]
I've been trying to run the tests with tox, through pycharm on mac, and I found myself not able to do anything else since a qutebrowser windows kept popping up and stealing the focus, making anything but reading on a second monitor impossible.

**Comment by The-Compiler** [comment]
If you are on Linux, install Xvfb (the testsuite prints "pytest-xvfb could not find Xvfb. You can install it to prevent windows from being shown" in that case). On Windows and macOS, there's nothing that can be done about it as far as I'm aware. You might want to just run the unit tests which don't open windows (`pytest tests/unit -k "not gui"`) in that case.

**Comment by The-Compiler** [comment]
Oh, a couple of tests were broken with `-m "not gui"` - fixed now!
