### ISSUE TITLE
TaskAdd: Multiline Output Fails

### ISSUE THREAD

**Issue by bbugyi200** [qutebrowser/qutebrowser#3726]
As far as I can tell, won't multiline output always result in an error when used as an arg for `message-info` and/or `message-error`.

https://github.com/qutebrowser/qutebrowser/blob/69a013bc82d2ecc485e4b0659c16af7b78606f6d/misc/userscripts/taskadd#L28-L34

Tacking on `| head -1` to the end of the `task` command should fix this.

**Comment by The-Compiler** [comment]
True. I'm not sure if `head -1` is non-standard though, `head -n 1` would probably be better. cc @rcorre

**Comment by rcorre** [comment]
LGTM, just put in a PR when you're ready. Thanks!

**Comment by bbugyi200** [comment]
@rcorre Pull Request: #3728
