### ISSUE TITLE
Different look of hints depending on link target

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#3734]
If I press `f`, hints will show, and if I type them, I will effectively click on the URL that the hint was on. By default, links will have targets (same page, or new tab). But regardless of target, all hints will look the same (same background, text colour, font, etc).

I suggest to have hints colouring based on link targets. E.g. hints that will open links in the same tab to be yellow bg with black fg, while hints that open in a new tab to be with red bg and white fg. Just an example. This way we will be less likely to be surprised what will happen.

I also wish to be the same theming to be honoured when I force all `f` hints to forcefully open in the same tab regardless of link targets, and `F` to open in a new tab regadless of link targets. This way, hints shown by `f` will be with yellow bg and black fg, while hints shown by `F` will be with red bg and white fg (just an example). This way we, the users, will need to remember less states of what did we do in the past.

**Comment by The-Compiler** [comment]
I don't think qutebrowser can do this consistently, as at least for link clicks handled via JS, it can't predict what'll happen. Thus, I'm going to say "no" to this one :wink:
