### ISSUE TITLE
Installation on Ubuntu 17.10 requires qutebrowser-qtwebengine

### ISSUE THREAD

**Issue by jakobkogler** [qutebrowser/qutebrowser#3737]
## Problem description

I wanted to install qutebrowser 1.2.1-1 on a fresh install of Ubuntu 17.10. 
I followed the [instructions](https://www.qutebrowser.org/doc/install.html#_debian_stretch_ubuntu_17_04_and_17_10), downloaded the two `.deb` files from the Debian repository and tried installing them. 

    apt install ./python3-pypeg2_*_all.deb
    apt install ./qutebrowser_*_all.deb

PyPEG2 installed without any problems, but the install of qutebrowser failed, because it was missing the qutebrowser-qtwebengine package. (Sorry, I don't have the exact error message any more)

## Fix 

Since the qutebrowser-qtwebengine package was missing, I also downloaded the package from the Debian repository ([Link](https://packages.debian.org/sid/all/qutebrowser-qtwebengine/download)) and installed qutebrowser and qutebrowser_qtwebengine at the same time with

    apt install ./qutebrowser_*_all.deb

## Comments

I'm not sure if this is actually the desired installation process, or if something broke causing the installer to not find qtwebengine. (I think I remember installing qutebrowser without the fix some months ago.) 
Nevertheless, this should be fixed, or at least described in the installation documentation.

**Comment by The-Compiler** [comment]
That's intended - see #3707.
