### ISSUE TITLE
Switch to StevenBlack host blacklist

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3739]
https://github.com/StevenBlack/hosts seems to be a nicely curated meta-list of "bad" domains. We should probably switch the default blacklist to that, and maybe even remove support for zipped hosts files at that point.

**Comment by gebulmer** [comment]
Had a look at this, don't think we should _remove_ the zip support, as the user may wish to add some lists themselves

Curious error though: 
12:26:24 ERROR: adblock: 1 read errors for adblock: raw.githubusercontent.com
12:26:24 INFO: adblock: Read 56128 hosts from 1 sources.

That obviously needs looking into before a PR
