### ISSUE TITLE
Tooltips on pinned tabs are just numbers

### ISSUE THREAD

**Issue by Lindenk** [qutebrowser/qutebrowser#3741]
Version: 1.2.1

Although this is the minorest of all issues, pinned tabs' tooltips don't seem to keep any information about what web page is actually loaded in the tab.

**Comment by jgkamat** [comment]
Hmm, by default, tooltips show just the content of the tab title (which is why they only show numbers by default). I can definetly see it being useful to have a `tabs.tooltip.format_pinned` or similar, to customize it (and perhaps defaulting to `tabs.title.format`).

**Comment by The-Compiler** [comment]
Not sure if we need another config option for this - I'd prefer if it just always showed `tabs.title.format` or even only the actual page title.
