### ISSUE TITLE
[Feature Request] tabs.show: option to only display a defined relative range of tabs on bar

### ISSUE THREAD

**Issue by Yousuf-Khurshid** [qutebrowser/qutebrowser#3744]
The use case for this would be for someone who primarily uses the buffer command to traverse tabs and likes the tab bar around only when changing tabs or making tab manipulations once issue https://github.com/qutebrowser/qutebrowser/issues/3084 is closed.

In this sort of use case, it's tabs that are closer by that you would like to see so you can make strategic positionings for rapid navigation through the <alt+{number}> bindings. Other tabs would just be visual noise that significantly truncate the webpages' titles once you go beyond ten tabs on a window.

**Comment by The-Compiler** [comment]
This should already be possible using the `tabs.min_width` setting which was added recently.

**Comment by Yousuf-Khurshid** [comment]
Apologies, wasn't keeping up to date well there
