### ISSUE TITLE
[Feature Request] tab-move: add -inc flag to define a move command that increments by a number once you go past a defined tab number

### ISSUE THREAD

**Issue by Yousuf-Khurshid** [qutebrowser/qutebrowser#3745]
The use case for this would be if you would like to continue to use the <alt-{number}> bindings for rapid tab navigation but would prefer if this was used for relative tab switching, using the buffer command instead for absolute positioning navigation. 

This would be represented like this:
:bind <alt-1> tab-move -inc 10 10 1
:bind <alt-2> tab-move -inc 10 10 2
and so on.

By default the -inc flag would increment by 1 and accept negative values as well.

**Comment by The-Compiler** [comment]
You mean the bindings would go to tabs 1-8 still, but if you're after tab 10, they'd do relative movement? I'm sorry, but I'm going to say no to this one - this is just too specific (and feels too "magic") to be useful for other people.

Note that you can already do e.g. `2J` and `2K` for relative movement, and with a future plugin API (#30) you'd be able to write a plugin which does this.
