### ISSUE TITLE
Unable to enter characters with carons in Facebook Messenger / disable spellcheck if unneeded

### ISSUE THREAD

**Issue by proxict** [qutebrowser/qutebrowser#3753]
http://paste.the-compiler.org/view/ccc812b2
In Facebook Messenger I am not able to paste characters with carons like: ď, ť, ň, etc..
It behaves really strangely because I see the characters are typed in the textfield, but they disappear right away.
I use Czech keyboard input (`setxkbmap cz`). I am pressing shift + key with `0x0d` scancode followed by the key I want to palatalize.
For more information about carons, see https://en.wikipedia.org/wiki/Caron

**Comment by The-Compiler** [comment]
Smells like [QTBUG-66046](https://bugreports.qt.io/browse/QTBUG-66046) - I guess we could disable spellchecking entirely though if `spellcheck.dictionaries` is empty, to avoid this.

**Comment by proxict** [comment]
That's pretty unfortunate, I use spellchecking quite a lot, I use 3 languages. Hope it will be fixed in qt soon.

**Comment by NoctuaNivalis** [comment]
I am BTW seeing the same symptons with characters like é when I use the compose key (compose + ' + e). I don't think I have spellcheck enabled though.

**Comment by proxict** [comment]
That's actually what I meant, I just didn't know it's called a compose key. Now I know, thanks :-)

**Comment by The-Compiler** [comment]
qutebrowser now disables spellchecking when no dictionaries are configured, so this will at least work without spellcheck on current Qt versions.
