### ISSUE TITLE
Install dictionaries to standarddir.data() on Qt >= 5.10

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3759]
Moving this here from #2939 as it probably warrants some more discussion.

In Qt 5.10, I [added](https://codereview.qt-project.org/#/c/201422/) a `QTWEBENGINE_DICTIONARIES_PATH` environment variable to Qt, allowing to customize it so installing dictionaries doesn't require root rights.

With that, it'd be possible for qutebrowser to install dictionaries automatically, without having to run a separate script with root permissions.

Here's how things roughly should look, IMHO:

- qutebrowser should set `QTWEBENGINE_DICTIONARIES_PATH` to something like `os.path.join(standarddir.data(), 'dictionaries')` (probably in `qutebrowser/browser/webengine/webenginesettings.py`)
- The `spell.py` script should be patched to use that path on Qt >= 5.10 (and still use the current system-wide path on older Qt versions)
- Ideally, when setting `spellcheck.languages` to a missing dictionary on Qt >= 5.10, instead of showing a warning, qutebrowser should ask whether to download that dictionary (without a separate script).

@rnhmjoj [said](https://github.com/qutebrowser/qutebrowser/issues/2939#issuecomment-375658738):
> Another issue I have found: the script calls imports `browser.webengine.spell` and then calls `qutebrowser.utils.standarddir` which not initialized, so I had to "manually" read the environment to get the path. 

It should be possible for the script to call `standarddir.init()` - reading it manually like in [the NixOS patch](https://github.com/rnhmjoj/nixpkgs/blob/f9dfa0e328d0642735d84825ab889013e3bdb691/pkgs/applications/networking/browsers/qutebrowser/dictionaries-path.patch) won't work on operating systems other than Linux :wink:

@elshize IIRC you said you wanted to take a look at this some while ago - are you okay with @rnhmjoj taking a look?

**Comment by jtojnar** [comment]
Actually, why does a browser install dictionaries? We should let package manager do it.

**Comment by The-Compiler** [comment]
@jtojnar That doesn't really work out across distributions and operating systems.

**Comment by jtojnar** [comment]
Could a compile time flag (like Firefox has for disabling auto-updater) be added?

**Comment by rnhmjoj** [comment]
@The-Compiler I did see there is a `standarddir.init()` but could figure which `args` it needs to be called with. Aniway it won't matter if the script is moved into qutebrowser.

Thanks for the tips! I'm working on it.

**Comment by elshize** [comment]
@The-Compiler yeah, it's fine; I'm a little slow to respond at the time anyway due to work (I do remember I still have a PR open and I will finish that up, hopefully this weekend). I'm sure I can find some other issues to work on once I have some more time ;)
