### ISSUE TITLE
Prompts without any keys

### ISSUE THREAD

**Issue by lahwaacz** [qutebrowser/qutebrowser#3760]
Consider the following simplified `config.py` (in practice, I'm copying default bindings for some modes and setting my own bindings for other modes):
```python
# my bindings
c.bindings.commands = {
    "caret": c.bindings.default["caret"],
    "command": c.bindings.default["command"],
    "hint": c.bindings.default["hint"],
    "prompt": c.bindings.default["prompt"],
    "insert": c.bindings.default["insert"],
    "normal": c.bindings.default["normal"],
    "passthrough": c.bindings.default["passthrough"],
    "register": c.bindings.default["register"],
}

# ignore all defaults
c.bindings.default = {}
```

The issue is that with this config, qutebrowser does not recognize any bindings for prompts so they can't be answered or dismissed other than closing the browser. For example, `qutebrowser --basedir ./qb_test_basedir/ ":history-clear"` shows just "Clear all browsing history?" in the prompt and no keys are offered.

Any idea what's happening here?

```
$ qutebrowser --version
qutebrowser v1.2.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.11-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by The-Compiler** [comment]
In v1.2.0, a new `yesno` binding mode [was added](https://github.com/qutebrowser/qutebrowser/blob/master/doc/changelog.asciidoc#changed-1) (before, bindings from the `prompt` section were used for both `prompt` and `yesno` mode).

FWIW if you remove all default bindings I'd really recommend reading the changelog for upgrades :wink:

**Comment by lahwaacz** [comment]
Oops, thanks...
