### ISSUE TITLE
Charts.js canvas not rendered/displayed

### ISSUE THREAD

**Issue by jaypikay** [qutebrowser/qutebrowser#3768]
I am running qutebrowser v1.2.1. When I am looking at sites using **chart.js** the canvas is empty. Other browsers do render them.

Site tested with: http://www.chartjs.org/
Also local instances of Home Assistant.

**Comment by The-Compiler** [comment]
Seems to work fine here:

![image](https://user-images.githubusercontent.com/625793/37878353-17a7b392-3068-11e8-893e-e9cabb287718.png)

What Qt version and what backend? Can you reproduce it when starting with `--temp-basedir`?

**Comment by jaypikay** [comment]
I am using qutebrowser v1.2.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10.1

Style: QFusionStyle
Platform: Linux-4.15.12-1-ARCH-x86_64-with-arch, 64bit

I ran with --temp-basedir and took a screenshot.

![github_qutebrowser](https://user-images.githubusercontent.com/1150952/37890968-d0daa904-30d2-11e8-848a-be17b1a803cf.png)

**Comment by The-Compiler** [comment]
Can you please reproduce this with `--temp-basedir` and then do `:report` so I can take a look at the logs?

**Comment by jaypikay** [comment]
Done, report should be on its way.

**Comment by The-Compiler** [comment]
Can you try `unset QT_AUTO_SCREEN_SCALE_FACTOR` and `unset QT_STYLE_OVERRIDE` and then try again with `--temp-basedir` in the same shell?

**Comment by jaypikay** [comment]
I have unset these two without any luck and tried it again unsetting all other QT_* variables without any luck, too.

**Comment by jaypikay** [comment]
OK now it is getting weird. Starting the browser after unsetting the QT_* settings, and opening the browser with "--temp-basedir http://www.chartjs.org" I see no graphs. Visiting my home assistance site, I do see graphs rendered. Refreshing the tab of chartjs.org does not fix the graphs, but when I open a new tab an browse to chartjs.org, I see the graphs.

**Comment by The-Compiler** [comment]
Can you check whether you can reproduce the same issue with `falkon` (also in the Arch repos)?

**Comment by jaypikay** [comment]
No charts here with falkon, but charts with chromium.

**Comment by The-Compiler** [comment]
This seems like some kind of issue with QtWebEngine on your system then. IIRC, having a non-integer scale factor causes various trouble unfortunately. If you still have issues with something like `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1`, can you please [open a Qt bug](https://bugreports.qt.io/) about it?

**Comment by jaypikay** [comment]
The ticket is open over at Qt dev. At the moment it is possible to set c.qt.args = ["disable-accelerated-2d-canvas"] as workaround.

**Comment by The-Compiler** [comment]
For future reference, that's [QTBUG-67323](https://bugreports.qt.io/browse/QTBUG-67323).
