### ISSUE TITLE
Broken error page when trying to visit missing sites

### ISSUE THREAD

**Issue by aramiscd** [qutebrowser/qutebrowser#3773]
[version 1.2.1](http://paste.the-compiler.org/view/6f2a31b8)

When I try to visit a non-exisit domain name or to talk to an inactive port, Qutebrowser presents me with an error page that seems completely broken.

[screenshot](http://aramis.auriga.uberspace.de/public/71d7e2f17b3ef6ed5b9fa93fdcd33afa777e8fd36591d8083fe4c379cf98e210.png)

debug output:

```
09:36:04 DEBUG    webview    browsertab:_set_load_status:695 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=31 url='http://asdfasdfasfasdf.de/'>: LoadStatus.error
09:36:04 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed('error') (tab 13)
09:36:04 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_finished(False) (tab 13)
```

**Comment by The-Compiler** [comment]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882805

**Comment by aramiscd** [comment]
Thank you.

**Comment by The-Compiler** [comment]
I just digged into this issue some more and found a workaround - now qutebrowser displays its own error pages in that situation.
