### ISSUE TITLE
A way to store separate sessions, each one having their own cache, cookies, history

### ISSUE THREAD

**Issue by timzul** [qutebrowser/qutebrowser#3775]
Is there any way to do that using session-save/load functions?

**Comment by The-Compiler** [comment]
No, but there's `--basedir` for that.

**Comment by timzul** [comment]
Where can I find more info on using --basedir?

**Comment by The-Compiler** [comment]
`man qutebrowser`, or see https://github.com/qutebrowser/qutebrowser/blob/master/doc/qutebrowser.1.asciidoc#options

**Comment by timzul** [comment]
Thanks a lot! :)
