### ISSUE TITLE
Cannot download webpage - Unknown protocol "chrome"

### ISSUE THREAD

**Issue by jaypikay** [qutebrowser/qutebrowser#3779]
qutebrowser v1.2.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10.1

I want to save the html page `:open chrome://gpu` with `:download`. An error message is shown, that "chrome" is an unknown protocol.

**Comment by The-Compiler** [comment]
This will be fixed via #2328. You can do `:download --mhtml`, though.
