### ISSUE TITLE
Darkreader extension feature in qutebrowser

### ISSUE THREAD

**Issue by seniorivn** [qutebrowser/qutebrowser#3780]
https://github.com/alexanderby/darkreader
what it does is dynamically converts current pages styles to dark versions of it.

I know there are troubles with per domain css inject and fully working css styles(with domain and regexp specifications), but it would be awesome to have.

Would love to know:
- what issues have to be solved before this could happen
- also if someone willing to do that? 
- could we just fork that extension/addon and somehow make it work in qutebrowser?

**Comment by The-Compiler** [comment]
I think this is already covered by existing features and open issues:

- The `content.user_stylesheets` setting (the [solarized-everything](https://github.com/alphapapa/solarized-everything-css/) style works quite well)
- #3636 for making that work per-domain
- #30 for a general plugin API (and plugin ideas)

**Comment by seniorivn** [comment]
@The-Compiler 
#30  definitely what's needed,  but it would be simpler to just reuse the js code, then reimplement it in python.

But it's not just custom stylesheet, its automated darking of the normal stylesheet of the site, and also there is no need for dark theme if web site already has it as a builtin feature.

Anyway, thanks, i get it, better wait for per-domain user_stylesheets, and just write rules for myself

**Comment by The-Compiler** [comment]
That'd require supporting the WebExtensions API, which is also mentioned in #30 (and probably not going to happen in the near future).

**Comment by The-Compiler** [comment]
In case someone finds this via a search, there are some more alternatives nowadays:

- Use Chromium's dark mode using the `colors.webpage.darkmode.*` settings (but note those need a restart to toggle)
- Use a basic Greasemonkey port of Dark Reader from https://github.com/darkreader/darkreader/issues/926#issuecomment-575893299

**Comment by The-Compiler** [comment]
I (finally) added something about this to the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc) (point 21).
