### ISSUE TITLE
Implicitly downcase history completions 

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#3783]
Steps to reproduce:
1. execute `open -t https://upyachka.io/`
2. close the tab
3. type `open -t упячка`

Expected:

The history ought to complete to upyachka.io

Actual:

The history does not show anything, unless the word have been typed in the exact case as it is in title, i.e. `УПЯЧКА`.

Additional info:

Would be nice to only downcase it for matching purposes, i.e. so that the string shown would be kept the same as it is in the history *(e.g. `УПЯЧКА`)*.

	$ qutebrowser --version
	[0329/172350.679325:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/constantine/#1948649 (deleted)
	  Error: No such file or directory
	qutebrowser v1.2.1
	Git commit: 
	Backend: QtWebEngine (Chromium 61.0.3163.140)

	CPython: 3.6.4
	Qt: 5.10.1
	PyQt: 5.10.1

	sip: 4.19.8
	colorama: no
	pypeg2: 2.15
	jinja2: 2.10
	pygments: 2.2.0
	yaml: 3.12
	cssutils: no
	attr: 17.4.0
	PyQt5.QtWebEngineWidgets: yes
	PyQt5.QtWebKitWidgets: yes
	pdf.js: no
	sqlite: 3.22.0
	QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

	Style: Breeze::Style
	Platform: Linux-4.15.12-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
	Linux distribution: Arch Linux (arch)
	Frozen: False
	Imported from /usr/lib/python3.6/site-packages/qutebrowser
	Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

	Paths:
	cache: /home/constantine/.cache/qutebrowser
	config: /home/constantine/.config/qutebrowser
	data: /home/constantine/.local/share/qutebrowser
	runtime: /run/user/1000/qutebrowser
	system data: /usr/share/qutebrowser

	Uptime: 0:00:00

**Comment by The-Compiler** [comment]
The comparisons are already case-insensitive, but it looks like sqlite [needs to be built](https://sqlite.org/lang_expr.html)  with the ICU extension somehow so that works with non-ASCII characters:

> Any other character matches itself or its lower/upper case equivalent (i.e. case-insensitive matching). Important Note: SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE 'Æ' is FALSE. The ICU extension to SQLite includes an enhanced version of the LIKE operator that does case folding across all unicode characters.

I don't think there's anything that qutebrowser can do about this - cc @rcorre

**Comment by The-Compiler** [comment]
Archlinux' `qt5-base` does include sqlite support (and depends on `sqlite`).

**Comment by Hi-Angel** [comment]
Yeah, [I reported a bug](https://bugs.archlinux.org/task/58026?project=1&string=sqlite)
