### ISSUE TITLE
Exiting Insert Mode immediately after opening external editor

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#3784]
Is it possible to leave INSERT MODE exactly when `Ctrl-e` or `Ctrl-g` is triggered?
I constantly find myself continuing to type into the input field, while the real intend is to interact with the page elements.

**Comment by The-Compiler** [comment]
You can do `:bind --mode=insert <Ctrl-E> open-editor ;; leave-mode`.
