### ISSUE TITLE
Changing text with external editor doesn't run JS handlers

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3786]
When e.g. doing `<Ctrl-e>` in a GitLab issue and adding some text, the comment button will stay grayed out.

**Comment by toofar** [comment]
And when eg clicking `Preview` then going back to the editor the changes from the external editor will have been reverted. Looks like gitlab uses [vue-markdown](https://gitlab.com/gitlab-org/gitlab-ce/blob/e4e8e0fc9df9dbd1cc6582ef9932a346e1c376a0/app/assets/javascripts/vue_shared/components/markdown/field.vue).

**Comment by sim590** [comment]
This is somewhat related to #2111.
