### ISSUE TITLE
Documentation need for running development builds

### ISSUE THREAD

**Issue by Rantahu** [qutebrowser/qutebrowser#3795]
Would be nice for newcomers who want to contribute to know how to run a development build on their local copy of the repo.

I suggest adding `python3 -m qutebrowser --temp-basedir` to the contribution doc.

I could make the PR if people agree to this idea.

**Comment by jgkamat** [comment]
This sounds like a good to me! I think this would especially help those who are new to python development in general.

I would add `--no-err-windows` as well, so python errors show up in the console and don't show a error report.

**Comment by Rantahu** [comment]
PR #3798 hopefully works out for you peeps
