### ISSUE TITLE
Ubuntu 16.04 LTS [permission denied]

### ISSUE THREAD

**Issue by YerdnaIzh** [qutebrowser/qutebrowser#3801]
Wrapper script doesn't work. I've done everything mentioned in the installation documentation. But following errors occurs if I try so start qutebrowser:

bash: /usr/local/bin/qutebrowser: Permission denied

I can start qutebrowser in the qutebrowser-folder tho and it runs properly, but it's a pain to navigate to qutebrowser-folder and type ".venv/bin/python3 -m qutebrowser" every time I wanna use it : D

Any idea what I should do? Thank you!

**Comment by jgkamat** [comment]
@YerdnaIzh can you try running 

```
chmod +x /usr/local/bin/qutebrowser
```

This sets the executable bit on the script, so that you (and the shell) can execute it directly with `/usr/local/bin/qutebrowser` rather than `bash /usr/local/bin/qutebrowser`.

**Comment by YerdnaIzh** [comment]
@jgkamat , Ah, yes, thank you very much. It worked! Didn't expect such a fast answer thou. xD
