### ISSUE TITLE
Explicitly allowing JS for a jenkins site does not work

### ISSUE THREAD

**Issue by craftyguy** [qutebrowser/qutebrowser#3822]
If `content.javascript.enabled` is set to false globally, and then explicitly enabled (e.g. with `tSh`) for a Jenkins site, the Jenkins site does not work. If JS is enabled globally, then it works as intended.

To reproduce this:
1) `:set content.javascript.enabled false`
2) visit this public Jenkins test instance: http://dev.jazzteam.org:8080/login?from=%2F
3) `tSh`
4) hit the login button, it works
5) close qb, start it again and visit the page above
6) hit the login button, it no longer works
5) `:set content.javascript.enabled true` (and reload page)
6) hit the login button, it works again

Version info: http://paste.the-compiler.org/view/29c7b2e3

Looking at page source, it looks like all JS is being served from the URL which should have been whitelisted by `tSh`, so I really don't know why this isn't working as intended.

**Comment by jgkamat** [comment]
Hmm, for me, the login button seems to work fine even with js disabled.

Also, after I run `tSh`, the live chat in the bottom right (which does depend on js) does come up, so the toggle seems to be working for me. 

Could you submit your `qute:version` and maybe a debug log as well please? :)

**Comment by craftyguy** [comment]
qute:version is in my original post.

The login button works when JS is disabled (but not when I enable it explicitly for that site). To summarize:

- JS disabled globally, **not** enabled for site with `tSh`: button works

- JS disabled globally, enabled for site with `tSh`: button does **not** work

- JS enabled globally: button works

I'll try to capture a debug log.

It also occurs to me that you may not actually be on the jenkins page, this is the page you should use for reproducing this: http://dev.jazzteam.org:8080/login
I have updated my original post with  the direct url.

**Comment by jgkamat** [comment]
Ah, yes, I think I was re-directed to the wrong page at first.

Hmm, for me, the login button still works (of course with no auth, but I do get an error after a redirect) with js disabled globally, with js enabeld globally, and js disabled globally and enabled per-site with `tSh`.

The message I get in the log is:

```
14:36:08 INFO: content.javascript.enabled = true for *://dev.jazzteam.org/*
```

It's possible this is only reproducable with qt 5.10 maybe? I'm testing on 5.7.1. This is rather odd, as the current per domain settings should only enable/disable js per site, I don't think they do any blocking depending on where the js originated from

**Comment by craftyguy** [comment]
qb is definitely processing the `tSh` for me:

```
11:45:52 DEBUG    keyboard   basekeyparser:_debug_log:89 Definitive match for 'tSh'.                                                                            
11:45:52 DEBUG    keyboard   basekeyparser:_debug_log:89 Clearing keystring (was: tSh).                                  
11:45:52 DEBUG    commands   command:run:486 command called: config-cycle ['-p', '-u', '*://dev.jazzteam.org/*', 'content.javascript.enabled']
11:45:52 DEBUG    commands   command:run:501 Calling qutebrowser.config.configcommands.ConfigCommands.config_cycle(<qutebrowser.config.configcommands.ConfigCommands object at 0x619328eca4a8>, 'content.javascript.enabled', pattern='*://dev.jazzteam.org/*', temp=False, pri
nt_=True)                                                                                       
11:45:52 DEBUG    config     config:_set_value:287 Config option changed: content.javascript.enabled = True                                                                                                         
11:45:52 DEBUG    save       savemanager:mark_dirty:71 Marking yaml-config as dirty.               
11:45:52 INFO     message    message:info:86 content.javascript.enabled = true for *://dev.jazzteam.org/*           
11:45:52 DEBUG    misc       mainwindow:_update_overlay_geometry:295 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x6192c173adc8>: PyQt5.QtCore.QRect(0, 1117, 1909, 25)
11:45:52 DEBUG    commands   command:run:486 command called: reload                                                                                                                                   
11:45:52 DEBUG    commands   command:run:501 Calling qutebrowser.browser.commands.CommandDispatcher.reloadpage(<qutebrowser.browser.commands.CommandDispatcher>, False, None)
11:45:52 DEBUG    webview    tabbedbrowser:on_title_changed:588 Changing title for idx 13 to 'http://dev.jazzteam.org:8080/login'
11:45:52 DEBUG    config     websettings:update_for_url:154 Changed for http://dev.jazzteam.org:8080/login: content.javascript.enabled = True
```

However the button is still not functional.

This gets even weirder though, apparently I can get it to work *sometimes*, but if I restart qb after running `tSh` on the site, then the button no longer works again.

**Comment by craftyguy** [comment]
I have revised the 'steps to reproduce' in my original post with this new information.

**Comment by toofar** [comment]
I also can't reproduce, do you have any error messages from the `js` facility in the log?
Can you try with the `--temp-basedir` passed to qutebrowser?
Also have you set a custom user agent? There was a similar issue here https://github.com/qutebrowser/qutebrowser/issues/3559 but less flaky that was related to that.

**Comment by craftyguy** [comment]
@toofar wow, nice find on the user agent issue. That seems to be the problem here, though it's strange it seems to be somehow related to whether or not javascript is disable globally & enabled explicitly for the jenkins site.
For the record, I was using this user agent (from the Arch wiki) to try and reduce browser fingerprinting:
`Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0`

Setting it to the default user agent seems to get it working again.

Thanks for the help, I really appreciate it!
