### ISSUE TITLE
mattermost shows just a blank page when accessed.

### ISSUE THREAD

**Issue by merspieler** [qutebrowser/qutebrowser#3829]
Version: 1.2.1

Mattermost shows just a blank page when accessed.

**Comment by The-Compiler** [comment]
https://www.macieira.org/blog/2012/05/doesnt-work-doesnt-work/

**Comment by The-Compiler** [comment]
Some questions:

- What page exactly?
- Can you reproduce it with https://demo.mattermost.com/ too?
- What backend and Qt version?
- Can you reproduce it with `--temp-basedir`?
- If you can, can you please do `:report` so I can take a look at the debug logs?

**Comment by merspieler** [comment]
The page i try to use:
https://chat.mycroftai

The mattermost demo behaves the same.

My version info:
https://privatebin.net/?74ee4dcff285f4b0#QIyAw8TE2pZJXSY/IfPRVWqYaw5dBN8F0JbaxdlcM1Q=

It works with --temp-basedir... at first it complains about js disabled. So far my setup and with a temp basedir behaves the same.
When i now enable js for the page using `tsh`, they start to behave differently.

With the temp basedir, it shows the login from, with my setup, it shows only a blank page.

The debug logs:
https://privatebin.net/?6dc167299600fe90#mZZNFOZaymbN8eN2IDjuRpS0G3mB14vKWgSJ8q/I3Qo=

**Comment by The-Compiler** [comment]
I'm blaming one of those settings you have customized:

```
content.local_storage = false
content.private_browsing = true
content.xss_auditing = true
```

If I had to take a guess, I'll say `content.local_storage = false`. However, I'm not sure if that's enabled when it private browsing anyways (especially with older Qt versions), so you might need to turn that off, too.

**Comment by merspieler** [comment]
You are right, the local_storage = true does the trick.

Thanks for your help
