### ISSUE TITLE
Warn the user when he/she tries to refresh and the last request was a POST

### ISSUE THREAD

**Issue by taiite** [qutebrowser/qutebrowser#3830]
qutebrowser doesn't warn the user like firefox does when you hit the refresh button after making a POST request, and silently re-send the form that might have been sent.

Please warn me when I do that, because then i don't know what's going on. ^^'

**Comment by The-Compiler** [comment]
This isn't possible right now, but I opened [QTBUG-67613](https://bugreports.qt.io/browse/QTBUG-67613).

**Comment by taiite** [comment]
Thanks!
