### ISSUE TITLE
YouTube videos missing quality options on this browser

### ISSUE THREAD

**Issue by lluke777** [qutebrowser/qutebrowser#3831]
Qutebrowser doesn't support higher qualities of youtube?  Are there any options to fix this?
`https://support.google.com/youtube/answer/6322658?hl=en`

**Comment by The-Compiler** [comment]
What Qt version, backend and qutebrowser version?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by lluke777** [comment]
qutebrowser v1.2.1
Git commit: 6145786e4 (2018-03-14 20:19:14 +0100)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.1
Qt: 5.10.1
PyQt: 5.10.1

**Comment by The-Compiler** [comment]
How did you install qutebrowser, and Qt? If you installed it via `tox` (or via `pip`), that comes without support for proprietary codecs, which would explain it.

**Comment by jgkamat** [comment]
The prebuilt releases are built without support for proprietary codecs, which youtube seems to need for higher quality videos. If the qt you use it compiled with proprietary codecs, it works fine.

**Comment by bitraid** [comment]
You can play [8K video ](https://www.youtube.com/watch?v=sLprVF6d7Ug) on youtube with the official build of qutebrowser on windows. But it has to be available in `webm` format (`vp9` and `opus`). Some videos (at least the higher resolutions) are only available in `mp4` format, whose codecs (`h264` and `aac`) are proprietary and not included.

**Comment by The-Compiler** [comment]
It's definitely what others said, then - unfortunately, there are no plans to provide builds with proprietary codec support. It's a lot of effort and pain (as it involves building Qt/QtWebEngine from source on Windows), and unclear to me whether I'm even legally allowed to distribute them (linux distributions usually use the system ffmpeg there, which might have some kind of way to do this).
