### ISSUE TITLE
Make builds run with latest PyInstaller

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3842]
With the current PyInstaller git head, it looks like my `build_release.py` script doesn't work anymore, and `QWebEngineProcess` is not found. Probably related to https://github.com/pyinstaller/pyinstaller/pull/3233 and https://github.com/pyinstaller/pyinstaller/pull/3439 somehow?

This is at least on macOS, haven't tested Windows yet.

**Comment by bitraid** [comment]
It seems to still work on Windows. I also tried to run it with 64-bit python (i disabled the lines 404-411) and all went ok, so maybe the bug is fixed now?

**Comment by The-Compiler** [comment]
Hmm, I just released v1.4.0 where this seemed to work fine again.
