### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#385]

**Comment by basedtho** [comment]
hm. does this work? when i press F11, or when i do :fullscreen nothing happens?

**Comment by The-Compiler** [comment]
@basedtho You can do that by chaining something like `fullscreen ;; config-cycle tabs.show never ;; config-cycle statusbar.show never`

**Comment by basedtho** [comment]
thank you! no way to toggle tabs and statusbar?
