### ISSUE TITLE
Some website Picture not show

### ISSUE THREAD

**Issue by peet1234** [qutebrowser/qutebrowser#3865]

**Comment by The-Compiler** [comment]
Sorry, my crystal ball doesn't work properly, so I really need some more information from you :wink:

**Comment by peet1234** [comment]
sorry, here is the webpage links and screen shot
https://www.bomb01.com/article/38868
![2018-04-25-11 41 07](https://user-images.githubusercontent.com/37007880/39226798-e1b1e1ac-487e-11e8-8993-3a3cfa2a1d02.png)

**Comment by toofar** [comment]
I see the pictures (and styling), what Qt version, Qutebrowser version and Qutebrowser backend are you using?
Actually are you running the readability userscript?

**Comment by peet1234** [comment]
Version info

qutebrowser v1.2.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.15.15-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

yes, i'm runing readability script

**Comment by The-Compiler** [comment]
Not showing pictures/styiling is the whole point of the readability script as far as I know :wink: And if it does for some pages but not for others, that's an issue in that library and not qutebrowser.

**Comment by peet1234** [comment]
oh, that is my bad ,so i have to report to readability script. sorry about that.
