### ISSUE TITLE
Ctrl + Tab shortcut doesn't work properly

### ISSUE THREAD

**Issue by lluke777** [qutebrowser/qutebrowser#3867]
Tabs switching shortcut seems to toggle tabs instead switching. It is visible for more than 2 tabs opened in qutebrowser.

qutebrowser v1.2.1
Git commit: 6145786e4 (2018-03-14 20:19:14 +0100)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.1
Qt: 5.10.1
PyQt: 5.10.1

**Comment by The-Compiler** [comment]
That's what it's supposed to do (it's bound to `tab-focus last`).
