### ISSUE TITLE
FocusOnNavigationEnabled causes qutebrowser window to be focused when opening links from outside qutebrowser

### ISSUE THREAD

**Issue by arza-zara** [qutebrowser/qutebrowser#3872]
Introduced in https://github.com/qutebrowser/qutebrowser/commit/fa41af63b67b007a67cbac1b119729d030b9e533, qutebrowser window is now focused when opening links from outside qutebrowser which is inconvenient when opening multiple links.

Run in terminal:
1. qutebrowser
1. qutebrowser http://qutebrowser.org/
->  the existing qutebrowser window is focused

QtWebEngine 5.10.1 (Chromium 61.0.3163.140)

**Comment by The-Compiler** [comment]
What do you have `new_instance_open_target` set to?

**Comment by arza-zara** [comment]
`tab-silent`

**Comment by nonamethanks** [comment]
I have `tab-bg-silent` and can confirm the same behaviour.
