### ISSUE TITLE
Checking for new version fails

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3875]
After doing a crash report:

> There was an error while getting the newest version: Invalid JSON received in reply: Expecting value: line 1 column 1 (char 0)!. Please check for a new version on qutebrowser.org by yourself.

Probably something changed on PyPI?

**Comment by toofar** [comment]
Well https://pypi.python.org/pypi/qutebrowser/json is getting a 301 move permanently to https://pypi.org/pypi/qutebrowser/json. I'm pretty sure QNetworkRequest defaults to not following redirects.

**Comment by brainwane** [comment]
https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi might help.

**Comment by The-Compiler** [comment]
Yeah, adjusting the URL and ideally telling the QNetworkAccessManager to follow redirects (not sure if that was supported on 5.7.1 already though!) should be all that's needed.
