### ISSUE TITLE
Can't install because of unmet dependency on MX Linux 17

### ISSUE THREAD

**Issue by mrbig033** [qutebrowser/qutebrowser#3885]
[My environment](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

I followed [the official instructions](https://www.qutebrowser.org/doc/install.html#_debian_stretch_ubuntu_17_04_and_17_10) to install qutebrowser on Debian Stretch. I'm using MX Linux 17, but it's based on Debian Stable.

##### python3-pypeg2_2.15.2-2 seems to be  installed correctly:
```
$ sudo apt install ./python3-pypeg2_2.15.2-2_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python3-pypeg2' instead of './python3-pypeg2_2.15.2-2_all.deb'
python3-pypeg2 is already the newest version (2.15.2-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
##### the errors:
```
$ sudo apt install ./qutebrowser-qtwebengine_1.2.1-2_all.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'qutebrowser-qtwebengine' instead of './qutebrowser-qtwebengine_1.2.1-2_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 qutebrowser-qtwebengine : Depends: qutebrowser (= 1.2.1-2) but it is not installable
E: Unable to correct problems, you have held broken packages.

$ sudo apt install ./qutebrowser-qtwebkit_1.2.1-2_all.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'qutebrowser-qtwebkit' instead of './qutebrowser-qtwebkit_1.2.1-2_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qutebrowser-qtwebkit : Depends: libqt5webkit5 (>= 5.212) but 5.7.1+dfsg-1 is to be installed
                        Depends: qutebrowser (= 1.2.1-2) but it is not installable
E: Unable to correct problems, you have held broken packages.

$ sudo apt install ./qutebrowser_1.2.1-2_all.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'qutebrowser' instead of './qutebrowser_1.2.1-2_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qutebrowser : Depends: qutebrowser-qtwebengine but it is not installable or
                        qutebrowser-qtwebkit but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by The-Compiler** [comment]
As per the instructions, you need to install the both qutebrowser packages together, not one after another.

**Comment by mrbig033** [comment]
I know it is closed and your instruction worked for me, but where does it say I must install the in the same `apt install`command? Because it says otherwise [here](https://qutebrowser.org/doc/install.html#_debian_stretch_ubuntu_17_04_and_17_10).

**Comment by jgkamat** [comment]
The `apt install ./qutebrowser*.deb` command should expand to both `qutebrowser.deb` and the `qutebrowser-webkit/webengine` package (whichever one is present).

**Comment by mrbig033** [comment]
I must say the documentation is ambiguous. That same syntax is frequently used to make the command version proof, and works when the documentation is read as meaning "take this command and fill in the rest according to the file you downloaded".

Anyway, if I download both webkit and webengine to the same dir (something I did just in case), won't this command install both (or maybe give an error)?

Honestly, the phrasing in that paragraph seems to be meant for programmers or regex engines. Most people are neither.

**Comment by jgkamat** [comment]
> Anyway, if I download both webkit and webengine to the same dir (something I did just in case), won't this command install both (or maybe give an error)?

It should install both, which should be supported.

I do agree it is a bit cryptic, I'll add a comment above that line clarifying it. I couldn't think of a command that would be as simple but work with all the combinations of packages.

**Comment by mrbig033** [comment]
Good thing it would work anyway, but I'd rather avoid having unnecessary packages in my system (even though it would hardly have any kind of negative impact...)

Thanks for answering and being open to improve the docs. Have a great day!
