### ISSUE TITLE
event_target() can be None

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3888]
The assertion in bc9a8dd63f98b7ffab1493b16b96c3db730f4d0c seems to fail sometimes (on Qt 5.10)... I see two scenarios: 

# When handling a click

https://crashes.qutebrowser.org/view/6caa0b4c
https://crashes.qutebrowser.org/view/c5be0d38
https://crashes.qutebrowser.org/view/16dcb415
https://crashes.qutebrowser.org/view/afa29f22
https://crashes.qutebrowser.org/view/5a9eaeed

(and more)

# When using hints

https://crashes.qutebrowser.org/view/e943eb09
https://crashes.qutebrowser.org/view/b0dc067d

(and more)

Not sure what's causing it, and it probably needs some more investigation - for now, I'll replace the assertion with a warning.

**Comment by toofar** [comment]
I hate asserts in production code so damn mutch.

**Comment by The-Compiler** [comment]
I've reported this some while ago as [QTBUG-68727](https://bugreports.qt.io/browse/QTBUG-68727), and fixed the crash with 2b6b4e82a7c65683483032e922a0683e87b5db18.
