### ISSUE TITLE
no hidpi support in file dialog

### ISSUE THREAD

**Issue by nrdxp** [qutebrowser/qutebrowser#3891]
I am running the application 2 times scaling on a 4k laptop via the QT_SCALE_FACTOR=2 environmental variable in my shell startup scripts. I also have QT_AUTO_SCALE_FACTOR=0 to avoid double scaling. I first noticed this issue when uploading my homework to my univeristy website. Whenever a website opens a file dialog to select a file (say to upload), that file dialog is not scaled and is therefore very hard to see on a 4k screen. 

As a sidenote, I noticed a similar issue in qbittorrent so I am not sure if this is a qt bug or one that can be fixed here.

Version Info:

qutebrowser v1.2.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QGtkStyle
Platform: Linux-4.16.6-1-zen-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/eco/.cache/qutebrowser
config: /home/eco/.config/qutebrowser
data: /home/eco/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00

**Comment by The-Compiler** [comment]
Qt uses GTK's file dialog if possible on GTK, so you'll need to set up HighDPI for that as well.

If you did and it still doesn't work, that's indeed some issue with Qt (or possibly GTK) and not qutebrowser.

**Comment by nrdxp** [comment]
good to know I will file a bug in the appropriate place then as I do indeed have gtk setup for hidpi as well. Thank you.
