### ISSUE TITLE
Freeze on startup after erroneous configuration of proxy server

### ISSUE THREAD

**Issue by DrTobe** [qutebrowser/qutebrowser#3893]
When I was playing around with my proxy configuration, I entered `pac+file://C/.../wpad.dat` because the release information on https://blog.qutebrowser.org/qutebrowser-v0100-released.html stated that 

> network -> proxy can also be set to pac+file://... now to use a local proxy autoconfig file (on QtWebKit)

After restarting qutebrowser, it always ended up in a "qutebrowser is not responding" freeze.

I am on windows 10 with qutebrowser v1.2.1 and QtWebEngine (nowadays I already know that pac does not work on WebEngine but anyways I wanted to report the freezing).

As qutebrowser freezes then and the settings-gui can not be reached anymore, this can only be resolved by changing `...\user\AppData\Roaming\qutebrowser\config\autoconfig.yml` manually.

**Comment by The-Compiler** [comment]
Sorry for the late answer! I have no idea what's causing this, but it's probably something in QtWebEngine. Looking at [QTBUG-69281](https://bugreports.qt.io/browse/QTBUG-69281) it might be better in the next Qt release (5.11.3 or 5.12).

**Comment by The-Compiler** [comment]
I released qutebrowser v1.6.0 today which blacklists PAC proxies on QtWebEngine.
