### ISSUE TITLE
downloads shift the entire page down a line

### ISSUE THREAD

**Issue by dkanada** [qutebrowser/qutebrowser#3903]
Clicking on a download link shifts the entire page down which often messes up the next item I was going to click. Maybe moving the download bar below the tabs and having it overlap the page instead might fix the issue? It's not a major problem, just wanted to see if anyone else had the same opinion.

**Comment by The-Compiler** [comment]
You might want to `:set downloads.position bottom`. I don't think making them overlap the page is a good idea, as then elements on the page might be unreachable then.

**Comment by dkanada** [comment]
That makes a lot of sense, and now that I think about it moving the element to the bottom will indeed fix my issue. Thanks!
