### ISSUE TITLE
Google maps not displaying maps

### ISSUE THREAD

**Issue by dnebauer** [qutebrowser/qutebrowser#3905]
Google maps has always worked in qutebrowser. I noticed this morning that while the left hand search panel in google maps is working nornally, the right hand window that displays road and satellite maps is empty - just a blank white rectangle.

version info: http://paste.the-compiler.org/view/55e15a8a

**Comment by The-Compiler** [comment]
Can you reproduce it when starting with `--temp-basedir`?

**Comment by dnebauer** [comment]
Yes, it shows the same bug when started with `--temp-basedir`.

I noticed something this time: when the screen is loading the street map appears and disappears in the blink of an eye, as though a white rectangle was immediately painted over it. The map is still 'there' in some sense, because if I move the cursor over the whited out map area, the cursor's shape changes when it is over an interactive element, which I can then click -- from changes to the window title and other screen elements I can tell this actually changes the underlying map.

I've done everything I can to see whether there is something in google maps' user interface that I inadvertently changed which then caused the strange behaviour I'm seeing. I also tried googling the problem as though it were caused by google maps. Neither approach yielded anything useful. 

Add all that up... and I don't know what it means. This is no big deal for me since I can fire up another browser when I need to use google maps. I can check from time to time to see if this behaviour changes.

**Comment by blawiz** [comment]
I think i solved this issue for me by switching from fbdev to intel driver in xorg, also google map light might work for you as a backup.

**Comment by The-Compiler** [comment]
@dnebauer Can you please check whether you're seeing this with [Falkon](https://packages.debian.org/buster/falkon) as well?

**Comment by dnebauer** [comment]
Exact same behaviour: street map appears then is overlaid by white, but 
I am able to interact blindly with map elements using the cursor.

Excerpts from Florian Bruhin's message of May 13, 2018 6:19 pm:

**Comment by The-Compiler** [comment]
This doesn't look like a qutebrowser bug then - I suggest you wait for Qt 5.11, and if you still see it there, [open a QtWebEngine issue](https://bugreports.qt.io/secure/Dashboard.jspa).
