### ISSUE TITLE
Add a password filling script for lastpass

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#3909]
Lastpass has a cli client [here](https://github.com/lastpass/lastpass-cli), which should make creating a userscript easy. There are already quite a few nice scripts to build off of, [password_fill](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/password_fill), [qute-pass](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-pass), and [qute-keepass](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-keepass).

This issue has a lot of interest from people who use lastpass, but no contributors have stepped up so far (probably because most of us don't use lastpass currently). This should be an easy issue for someone new to qb to tackle, which is why I'm filing it!

password_fill has an interested 'backend' based system, which might make it easy to add new backends, but I found it a bit tough to use in practice. I think it might also be easy to swap out [these three functions](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-keepass#L162-L196) in qute-keepass. It depends on how lpass works, which I don't know anything about.

Let us know if you're interested in tackling this, it's a good entry point into userscripts and would make a lot of people happy :)

**Comment by toofar** [comment]
They also have bookmarklets which can presumably be called via jseval from a bind or alias: https://helpdesk.lastpass.com/bookmarklets/

**Comment by sivasama** [comment]
Can I work on this ?

**Comment by welps** [comment]
Hi, I've submitted an implementation in #3929.
