### ISSUE TITLE
Feature Request: Display match count for text search (e.g., '2 of 12')

### ISSUE THREAD

**Issue by rlue** [qutebrowser/qutebrowser#3910]
I can't imagine I'm the first person who wanted to see this implemented, but I couldn't find it in the existing issues anywhere, and couldn't find an existing config option for it (looked under `search.*`).

When searching for text on a page (_i.e.,_ with `/`), it would be nice to have a visual indication of how many total matches there are, and the position of the current match. That is, something like "2 of 12 matches".

**Comment by jgkamat** [comment]
This would be really useful, but I don't think that qtwebengine [has an api](https://doc.qt.io/qt-5/qwebenginepage.html#findText-1) for this as of now. I think that the other qtwebengine browsers would benefit from this as well, maybe someon should put in a bug report to qt.

**Comment by The-Compiler** [comment]
This is upstream as [QTBUG-50420](https://bugreports.qt.io/browse/QTBUG-50420) - as long as that doesn't happen, nothing qutebrowser can do here.

**Comment by The-Compiler** [comment]
This is actually possible since Qt 5.14 with the [QWebEngineFindTextResult](https://doc.qt.io/qt-5/qwebenginefindtextresult.html) added there.

@phesch perhaps this is something you want to look at (if you're still using qutebrowser), given your work on #5352?

**Comment by phesch** [comment]
Sounds like a good idea. While I'm at it, maybe I can find some more info on #6459 or #5351 (or #6345 - searching in qutebrowser seems to have loads of minor bugs / annoyances :P ).

**Comment by The-Compiler** [comment]
Unfortunately the QtWebEngine search API is rather quirky, so some of those things are a bit hacky indeed. There might be places where they can be improved, but some of those issues might not be fixable at all I think.

**Comment by phesch** [comment]
Yeah, I saw your issue #5652. Maybe the fixes aren't worth it, and more effort should be put into an alternative search engine instead? I remember working on the search code being quite the mess, considering you have to maintain state while waiting for callbacks and such. In fact, thinking back, there may be some concurrency bugs in there as well.

**Comment by The-Compiler** [comment]
Some of its API changed with Qt 6, maybe some things are better there, I didn't take a closer look yet.

I think for "normal" searches we should probably still use the Chromium search, because I expect it to be much faster than the JS one - so the fixes are probably worth it either way.

**Comment by phesch** [comment]
I just had a look at the Qt 6 docs and it doesn't seem like any of the search-relevant functions or types have changed. Anyway, I'll take a look at this over the next few days.

**Comment by The-Compiler** [comment]
One I'm aware of is [QtWebEngine calling the callback with QWebEngineFindTextResult](https://codereview.qt-project.org/c/qt/qtwebengine/+/359136) (instead of a bool and having the signal). There might be more, but I can't see anything off-hand.

**Comment by phesch** [comment]
So since this issue invites a restructuring of the GUI for searching, here are some options I came up with for presenting search-related info in the browser:

1. Integrate the match counter into the status bar next to the URL. The "text not found" message would still be presented as a message, since things could get crowded down there otherwise.
2. Place another full-length bar above the status bar when you start a search that contains all search-related info.
3. Don't go full-length - instead, make it a widget that's only as wide as its contents and place it in one of the four corners of a tab.

What do you think? (No rush, I'm busy studying right now too :) )

**Comment by The-Compiler** [comment]
I think 1. sounds good, and is probably the most simple to implement too. Seems like the natural place I'd look at for such information.
