### ISSUE TITLE
Open command prompt in external editor with `<C-f>`

### ISSUE THREAD

**Issue by erich-sch** [qutebrowser/qutebrowser#3911]
When you enter a command in vim you can press `<C-f>` to edit the command history in a split window, I think it would be nice if qutebrowser could do the same and open the entire command history in an external editor. This is particularly useful when editing a long url but it could also be used to search for a command that you have previously entered.

I think this is a better solution than binding `edit-url` and `edit-command` in normal mode.

**Comment by The-Compiler** [comment]
How would that work exactly? What happens when the history is edited, and what part of the history then lands in the commandline as edited command?

Not really convinced about the benefit this would give over `edito-command` to be honest :wink:

**Comment by erich-sch** [comment]
You could delete everything but one line. That line will be used as the command. I'd then use a vim keybinding such as `inoremap <CR> <ESC>kdggjdGZZ`. This would behave exactly like the command editing mode in vim.

The only benefits I see are:

1. If you want to use `edit-command` and `edit-url` efficiently, you'd create a keybinding for each of them. That would add two more keybindings to normal mode, while it would suffice to only bind one key for command mode.
2. The history search I've already mentioned.

While this feature isn't necessary it would be nice-to-have. I am not really familiar with qutebrowser's source code but I could try to implement this (for my own use, at least) and make a pull-request.

Thanks for that quick response, btw.

**Comment by bitraid** [comment]
What would be really cool is for qutebrowser to have its own vim-like command-line-window. Or at least vi editing mode for command line, like tmux has with `set -g status-keys vi`.

**Comment by The-Compiler** [comment]
I don't think this is something general enough to have in qutebrowser's core - I feel like people would be rather confused about it. However, it should be possible to implement it as a plugin once there's a plugin API (#30).
