### ISSUE TITLE
Bind touchpad button area

### ISSUE THREAD

**Issue by deb75** [qutebrowser/qutebrowser#3916]
Hello,

My laptop has a buttonless touchpad, however you can configure the touchpad corner to send button events (`/etc/X11/xorg.conf.d/70-synaptics.conf`): 
```
         ...
        Option "LTCornerButton" "6"
        Option "RTCornerButton" "7"
        Option "LBCornerButton" "8"
        Option "RBCornerButton" "9"
EndSection
```
The Left Bottom corner already works in qutebrowser as `back` command, but that is funny the Right Bottom corner does not work whereas it should do `forward`.

I could not find in qutebrowser's configuration any way to correct this and how to configure other buttons.

I checked with `xev` that all corners send their corresponding events : "button 6", "button 7", ...

How can I configure these buttons with qutebrowser (version info below) ?

Many thanks for this very nice browser

```
qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5rc1
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.7-custom-x86_64-with-debian-buster-sid, 64bit
Linux distribution: Debian GNU/Linux buster/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5
```

**Comment by The-Compiler** [comment]
This currently isn't possible, see #591.
