### ISSUE TITLE
Segfault in QQuickWindowPrivate::updateDirtyNode()

### ISSUE THREAD

**Issue by knokelmaat** [qutebrowser/qutebrowser#3919]
Qutebrowser chrashes after a few seconds/minutes of browsing. This problem only started recently. Below are the debug messages  from the --debug flag during the crash and the result from qutebrowser --version. I tried reinstalling and resetting the settings. I'm sorry if this is a silly thing on my end, I like using my computer efficiently but my under the hood skills are not yet amazing.
[debug.txt](https://github.com/qutebrowser/qutebrowser/files/2009050/debug.txt)
[version.txt](https://github.com/qutebrowser/qutebrowser/files/2009051/version.txt)

**Comment by The-Compiler** [comment]
That's weird - can you please [run qutebrowser in gdb](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc) in order to get a stacktrace (ideally with the debug packages)?

**Comment by The-Compiler** [comment]
That's weird - can you please [run qutebrowser in gdb](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc) in order to get a stacktrace (ideally with the debug packages)?

**Comment by knokelmaat** [comment]
I followed the guide you linked, installing your prebuilt packages for Arch and running qutebrowser through gdb and... it worked. I am still running it and I don't have any problems. Your packages replaced some of mine (as is described in your guide), maybe they contained the problem?

**Comment by The-Compiler** [comment]
That's weird! Looking at your version info again, you seem to have installed PyQt in `/usr/lib/python3.6/site-packages/PyQt5/` via `sudo pip install` or something, and installing the packages probably fixed things up.

I'm not sure how that happened exactly - if you did use `sudo pip install` at some point, you really shouldn't do that. FWIW, you should be able to remove my `[qt-debug]` repo again and install the normal packages (without `-debug`), and things will hopefully still be fine.

**Comment by knokelmaat** [comment]
I actually did that horribly insecure thing. I had a permission denied error and rather stupidly just ran pip with su instead of --user, all is fixed now and I have again learned a valuable lesson! Thank you for your time and the awesome browser.
