### ISSUE TITLE
Error in manjora linux when installing thru yaourt and when installing thru yaourt "-git"

### ISSUE THREAD

**Issue by Drunkenpanda2000** [qutebrowser/qutebrowser#3928]
When i install thru yaourt or pacman (both clean install) 

I get the error both wen run with with or without sudo.

> No backend librairy found!
> 
> Qutebrowser needs QtWebkit or Qt webengine but neither could be implemented!
> 
> -QtWebkit:libQT5WebKit.so.5:cannot open shared object file: no such file or directory
> -QtWebEngine: libavecodec.so.58:cannot open shared object file: No such file or directory
> 

Version info

> qutebrowser v1.3.0
> Git commit: 046c0a7ea (2018-05-17 17:53:47 +0200)
> Backend: QtWebEngine (Chromium unavailable)
> 
> CPython: 3.6.5
> Qt: 5.10.1
> PyQt: 5.10.1
> 
> sip: 4.19.8
> colorama: no
> pypeg2: 2.15
> jinja2: 2.10
> pygments: 2.2.0
> yaml: 3.12
> cssutils: no
> attr: 18.1.0
> PyQt5.QtWebEngineWidgets: no
> PyQt5.QtWebKitWidgets: no
> pdf.js: no
> sqlite: 3.23.1
> QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018
> 
> Style: Qt5CTProxyStyle
> Platform: Linux-4.14.39-1-MANJARO-x86_64-with-arch-Manjaro-Linux, 64bit
> Linux distribution: Manjaro Linux (manjaro)
> Frozen: False
> Imported from /usr/lib/python3.6/site-packages/qutebrowser
> Using Python from /usr/bin/python
> Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
> 
> Paths:
> cache: /home/drunkenpanda/.cache/qutebrowser
> config: /home/drunkenpanda/.config/qutebrowser
> data: /home/drunkenpanda/.local/share/qutebrowser
> runtime: /run/user/1000/qutebrowser
> system data: /usr/share/qutebrowser
> 
> Uptime: 0:00:00
>

**Comment by Drunkenpanda2000** [comment]
After running sudo pacman -S gst-plugins-{base,good,bad,ugly} gst-libav qutebrowser crashes on startup. and then i get the same error.

**Comment by The-Compiler** [comment]
Looks like either your system isn't fully upgraded (which a `yaourt -Suya` should fix), or there is some bug in Manjaros QtWebEngine package.

**Comment by Drunkenpanda2000** [comment]
Thx for the help much love !!
