### ISSUE TITLE
Random crashes when zoomed in and clicking dropdown box

### ISSUE THREAD

**Issue by slackhead** [qutebrowser/qutebrowser#3932]
qutebrowser v1.3.0
Git commit: 046c0a7ea (2018-05-17 17:53:47 +0200)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.1
PyQt: 5.10.1

I have been having random crashes when clicking on dropdown select box while zoomed in. I also have a minimum font size set.

It's hard to reproduce as it happens randomly. I got a crash log this time which I've attached.
[crash-2018-05-20.log](https://github.com/qutebrowser/qutebrowser/files/2020630/crash-2018-05-20.log)

This isn't just in this qb version. I've had it a few times in the past. It mostly happens on pages on ebay.co.uk.

**Comment by The-Compiler** [comment]
What OS/distribution is this on?

**Comment by slackhead** [comment]
Slackware 64 14.2

uname -a
Linux raven 4.15.12-jabberwok #1 SMP Thu Mar 22 21:28:51 GMT 2018 x86_64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux

**Comment by slackhead** [comment]
This is a different log. Shows a gl error. I'll try using software rendering fora whileto see if it affects anything.

[crash-2018-05-21.log](https://github.com/qutebrowser/qutebrowser/files/2020822/crash-2018-05-21.log)

**Comment by The-Compiler** [comment]
This looks like an issue with your graphics driver or possibly QtWebEngine/Chromium - nothing qutebrowser could do here I'm afraid.
