### ISSUE TITLE
Question regarding automatic url redirection

### ISSUE THREAD

**Issue by qutetemp** [qutebrowser/qutebrowser#3933]
Is there any way I can redirect a domain to another domain ?
Like for example I want to automatically redirect all {string}.reddit.com/{etc} to i.reddit.com/{etc}

**Comment by jgkamat** [comment]
Currently, there's no way to do this built-in. Some people have userscripts which rewrite target urls on the page (for example, youtube->hooktube), but the userscripts that I've seen have been fairly rudementary (and better ones could be made).

You could also override the :open command through the config.py system (unsupported).

**Comment by qutetemp** [comment]
The userscript option isn't really that great for me since I'm on qtwebkit and I'm not sure I understand the second suggestion.
Is it unsupported because it is not possible or is it unsupported because it's not recommended. I know there are aliases but they don't accept patterns ( I might be wrong ) and that would not solve the case of opening links from inside a page.

**Comment by jgkamat** [comment]
er, sorry, I messed up terminology:

There are rewriting greasemonkey scripts (not userscripts), which should work on qtwebkit and webengine (although I haven't tried). Here is [one](https://gist.github.com/Tazeki/4474bc972710872c429e660a6b08681d). The reason why I don't like this approach is that the userscripts I've seen aren't well designed, and don't take into account changes on the page by js. The script would have to set up a [mutationobserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) or something similar.

I think this might be possible to implement, there's no facility for doing this right now. The implementation would probably be similar to this PR: https://github.com/qutebrowser/qutebrowser/pull/3864/files (in that it would have to block a request that matches and fire a new, translated one).

**Comment by qutetemp** [comment]
Yes sorry I think it's actually my fault because I did not provide the reason why qtwebkit is an impediment and I'm under the impression that userscript and greasemonkeys scripts are the same thing. I would very much appreciate if you could provide me with something to read regarding the difference. Aren't greasemonkey scripts just usercripts that target that specific browser addon ?
I'm also under the impression that on qtwebkit userscripts / greasemonkey scripts load after and not before the actual site loads/starts loading.
I've encountered this behaviour with 4chan X some time ago

**Comment by jgkamat** [comment]
Unfortunately "userscript" is an overloaded term:

qutebrowser uses "userscript" in the dwb sense, which is a way of creating simple scripts that control qutebrowser. they are [documented here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc). 

Greasemonkey is a separate concept, which is (outside of qb) sometimes referred to as userscripts, which is essentially js running in the page. There's a good greasemonkey entry in the [faq](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc). Greasemonkey is just a way to run js scripts in the browser.


I think that greasemonkey scripts do run on the [end of page load](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/webkit/webpage.py#L90), but maybe support could be added for other targets like on [webengine](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/webengine/webview.py#L352-L357). Webkit does provide some signals such as domcreation that could be used.

**Comment by qutetemp** [comment]
Thanks for the response. I'll try my hand with a userscript and I'll post here if I succeed.

**Comment by The-Compiler** [comment]
I think this is something which should be exposed via a plugin API (#30) once that exists. Before that (e.g. via a config), I can't think of a good way to expose this and rewrite URLs without plugin code to change the URLs.
