### ISSUE TITLE
Hotspot for zoom mouse cursor is at the wrong place

### ISSUE THREAD

**Issue by slump64** [qutebrowser/qutebrowser#3934]
open this link (or any link with big picture):
http://i0.kym-cdn.com/photos/images/original/001/312/254/f58.png

zoom_in/out cursor is centered around down-right corner, but should be centered around `+`/`-` sign. because of this cursor may appear to be on the tab while holding cursor close to it

version:
http://paste.the-compiler.org/view/e76543dc

**Comment by jgkamat** [comment]
I'm not sure exactly what cursor you're referring to. What is the `+`/`-` sign? When you say "cursor" is that the mouse pointer?

`:zoom-in` and `:zoom-out` seem to work fine for me.

If I click on the image with the mouse, the image seems to zoom in based on where I clicked.

**Comment by slump64** [comment]
as you can see the point of this cursor is on right-bottom corner that's why this inconcistency happens
![image](https://user-images.githubusercontent.com/14310552/40289749-b4e1119a-5ca9-11e8-837e-d708ccb756b2.png)

**Comment by slump64** [comment]
Not sure what the thing with this cursor, i have only 1 cursor theme installed and i know how it zoom cursor looks and works, that is (in chromium it works correctly), so is this a QT thing to make up new cursors or qutebrowser fault?

**Comment by jgkamat** [comment]
Yup, I'm definetly seeing it. It's probably not our fault, since I see it in [falkon](https://community.kde.org/Incubator/Projects/Falkon) as well. Someone should probably file a qtbug about this (it's bugged me as well), but I'm not sure how to describe it. It could be part of qt, or just qtwebengine.

It does work fine with qtwebkit though, so I'm inclined to say its something wrong in qtwebengine.

**Comment by The-Compiler** [comment]
I just took a quick look at this by running qutebrowser in gdb and breaking in `QtWebEngineCore::RenderWidgetHostViewQt::UpdateCursor`. It gets a cursor type of `blink::WebCursorInfo::kTypeZoomOut`, calls `ui::GetCursorBitmap` from Chromium and gets `20/20` as hotspot back (hotspot: The pixel on the cursor where the click actually is). Interestingly, the bitmap is supposed to be 25x25px but gets displayed as 15x15px too...

So this seems to be some issue in either Chromium or QtWebEngine - see https://bugs.chromium.org/p/chromium/issues/detail?id=436993 too.
