### ISSUE TITLE
support follow-selected with <tab> selection

### ISSUE THREAD

**Issue by slackhead** [qutebrowser/qutebrowser#3935]
Version info http://paste.the-compiler.org/view/0a29b429

follow-selected doesn't work for me in normal mode.

I don't know if you recall us talking in IRC months ago about this, but my Return key had never worked on selected links/buttons etc. so I ended up unbinding it to get it to work for that.

Well it looks like the problem is that follow-selected doesn't work for me. If I select a link via Tab and then type :follow-selected nothing happens at all.

Log attached containing the output after using :follow-selected. If you need more let me know.
[debug-2018-05-21.log](https://github.com/qutebrowser/qutebrowser/files/2021039/debug-2018-05-21.log)

**Comment by jgkamat** [comment]
Actually, from the debug log, it looks like you are selecting the text with blue selection (is that correct)?

Does it work with the "orange selection" (the selection created when searching)?

**Comment by slackhead** [comment]
I'm selecting just by hitting Tab in normal mode until a link is highlighted. I tried in caret mode, but that's a different bug - I can't see the cursor in caret mode :)

Using search to highlight text works though.

**Comment by gong-yuan** [comment]
How can I change my subscription email address? I want to first 
unsubscribe and then subscribe using another email address. Thanks!

**Comment by slackhead** [comment]
Why are you asking this in my issue thread???

Click on your profile icon and use the help link at the top.

**Comment by jgkamat** [comment]
ah, that makes a lot more sense, `:follow-selected` dosen't support that method of "selection" currently, it only considers it when a search is being performed. You can use `:fake-key` enter as a substitute in the meantime, but I think it may be possible to add this feature so `:follow-selected` works more reliably. 

I'm guessing it could be a hierarchy, the easiest to implement would be:

1. If searching, click on search result
2. If blue selection exists, click on blue selection
3. If a focused element exists, click on it
