### ISSUE TITLE
prompt mode won't let me type n

### ISSUE THREAD

**Issue by magnetophon** [qutebrowser/qutebrowser#3937]
When there is a prompt popup and I type ``n``, it doesn't show up in the prompt, and I get an error:
``Value needs to be in the format username:password, but no was given``.

qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.6
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.0.2o  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.9-x86_64-with-glibc2.3.4, 64bit
Linux distribution: NixOS 18.09.git.751b66f (Jellyfish) (unknown)
Frozen: False
Imported from /nix/store/gl249qa4jrd2lv1gc3x9x1q3zpsh02jl-qutebrowser-1.3.0/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /nix/store/zf5yja02g8n8dzgs25pqfd8w3myfzgzc-qtbase-5.10.1/libexec, data path: /nix/store/zf5yja02g8n8dzgs25pqfd8w3myfzgzc-qtbase-5.10.1
OS Version: 

--- /etc/os-release ---
NAME=NixOS
ID=nixos
VERSION="18.09.git.751b66f (Jellyfish)"
VERSION_CODENAME=jellyfish
VERSION_ID="18.09.git.751b66f"
PRETTY_NAME="NixOS 18.09.git.751b66f (Jellyfish)"

Paths:
cache: /home/bart/.cache/qutebrowser
config: /home/bart/.config/qutebrowser
data: /home/bart/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 0:00:00

**Comment by The-Compiler** [comment]
Sounds like you have the `n` key bound in prompt mode in your bindings. Earlier versions only used that binding for yes/no prompts, but those got moved to a dedicated `yesno` keybinding section.

**Comment by magnetophon** [comment]
Ah, yes, I had:
```
config.bind('n', 'prompt-accept no', mode='prompt')
config.bind('y', 'prompt-accept yes', mode='prompt')
```

Thanks!
