### ISSUE TITLE
Qutebrowser screen flashes white and then back to what it was. (manjora 17.10 i3)

### ISSUE THREAD

**Issue by Drunkenpanda2000** [qutebrowser/qutebrowser#3945]
Version info

> [drunkenpanda@Diablo ~]$ qutebrowser
> [0524/234930.949155:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/drunkenpanda/#2625687 (deleted)
>   Error: No such file or directory
> [11200:11223:0524/234931.003642:ERROR:gl_implementation.cc(246)] Failed to load /usr/bin/libGLESv2.so: /usr/bin/libGLESv2.so: cannot open shared object file: No such file or directory
> 23:49:31 INFO: Run :adblock-update to get adblock lists.
> [11200:11223:0524/234931.306284:ERROR:gl_surface_qt.cpp(701)] Requested OpenGL implementation is not supported. Implementation: 0
> *** stack smashing detected ***: <unknown> terminated
> Received signal 6
> #0 0x7fde8970f0c6 <unknown>
> #1 0x7fde8838c84c <unknown>
> #2 0x7fde8970f43c <unknown>
> #3 0x7fde9f7b6a80 <unknown>
> #4 0x7fde9f41f86b __GI_raise
> #5 0x7fde9f40a40e __GI_abort
> #6 0x7fde9f4618b8 __libc_message
> #7 0x7fde9f4f280d __GI___fortify_fail_abort
> #8 0x7fde9f4f27c2 __stack_chk_fail_local
> #9 0x7fde883e348c <unknown>
> #10 0x7fde8a15a5e7 <unknown>
> #11 0x7fde8a1677ce <unknown>
> #12 0x7fde8a16a0af <unknown>
> #13 0x7fde8a16b31f <unknown>
> #14 0x7fde8a164b0d <unknown>
> #15 0x7fde8a165398 <unknown>
> #16 0x7fde8a16441e <unknown>
> #17 0x7fde8a166a45 <unknown>
> #18 0x7fde89794e82 <unknown>
> #19 0x7fde8972c4d8 <unknown>
> #20 0x7fde8972d4b8 <unknown>
> #21 0x7fde8972d923 <unknown>
> #22 0x7fde8972ec81 <unknown>
> #23 0x7fde8974d1bb <unknown>
> #24 0x7fde89768196 <unknown>
> #25 0x7fde8976338b <unknown>
> #26 0x7fde9f7ac075 start_thread
> #27 0x7fde9f4e153f __GI___clone
>   r8: 0000000000000000  r9: 00007fde17ffd8c0 r10: 0000000000000008 r11: 0000000000000246
>  r12: 00007fde17ffdb60 r13: 0000000000001000 r14: 0000000000000040 r15: 00007fde6cf74000
>   di: 0000000000000002  si: 00007fde17ffd8c0  bp: 00007fde17ffdca0  bx: 0000000000000006
>   dx: 0000000000000000  ax: 0000000000000000  cx: 00007fde9f41f86b  sp: 00007fde17ffd8c0
>   ip: 00007fde9f41f86b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
>  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.

Below is the weird bug 

> 
> [drunkenpanda@Diablo ~]$ qutebrowser
> [0524/234930.949155:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/drunkenpanda/#2625687 (deleted)
>   Error: No such file or directory
> [11200:11223:0524/234931.003642:ERROR:gl_implementation.cc(246)] Failed to load /usr/bin/libGLESv2.so: /usr/bin/libGLESv2.so: cannot open shared object file: No such file or directory
> 23:49:31 INFO: Run :adblock-update to get adblock lists.
> [11200:11223:0524/234931.306284:ERROR:gl_surface_qt.cpp(701)] Requested OpenGL implementation is not supported. Implementation: 0
> *** stack smashing detected ***: <unknown> terminated
> Received signal 6
> #0 0x7fde8970f0c6 <unknown>
> #1 0x7fde8838c84c <unknown>
> #2 0x7fde8970f43c <unknown>
> #3 0x7fde9f7b6a80 <unknown>
> #4 0x7fde9f41f86b __GI_raise
> #5 0x7fde9f40a40e __GI_abort
> #6 0x7fde9f4618b8 __libc_message
> #7 0x7fde9f4f280d __GI___fortify_fail_abort
> #8 0x7fde9f4f27c2 __stack_chk_fail_local
> #9 0x7fde883e348c <unknown>
> #10 0x7fde8a15a5e7 <unknown>
> #11 0x7fde8a1677ce <unknown>
> #12 0x7fde8a16a0af <unknown>
> #13 0x7fde8a16b31f <unknown>
> #14 0x7fde8a164b0d <unknown>
> #15 0x7fde8a165398 <unknown>
> #16 0x7fde8a16441e <unknown>
> #17 0x7fde8a166a45 <unknown>
> #18 0x7fde89794e82 <unknown>
> #19 0x7fde8972c4d8 <unknown>
> #20 0x7fde8972d4b8 <unknown>
> #21 0x7fde8972d923 <unknown>
> #22 0x7fde8972ec81 <unknown>
> #23 0x7fde8974d1bb <unknown>
> #24 0x7fde89768196 <unknown>
> #25 0x7fde8976338b <unknown>
> #26 0x7fde9f7ac075 start_thread
> #27 0x7fde9f4e153f __GI___clone
>   r8: 0000000000000000  r9: 00007fde17ffd8c0 r10: 0000000000000008 r11: 0000000000000246
>  r12: 00007fde17ffdb60 r13: 0000000000001000 r14: 0000000000000040 r15: 00007fde6cf74000
>   di: 0000000000000002  si: 00007fde17ffd8c0  bp: 00007fde17ffdca0  bx: 0000000000000006
>   dx: 0000000000000000  ax: 0000000000000000  cx: 00007fde9f41f86b  sp: 00007fde17ffd8c0
>   ip: 00007fde9f41f86b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
>  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.

**Comment by The-Compiler** [comment]
That does not look like version info :wink:

**Comment by Drunkenpanda2000** [comment]
i pasted incorectly annyhow i rebooted and then it workt afteter i had to fix the filesystem on boot.
