### ISSUE TITLE
Use Custom File Uploader

### ISSUE THREAD

**Issue by kappanose** [qutebrowser/qutebrowser#3946]
Is is currently possible to use a custom file explorer to upload files on websites?  For example, I want to use ranger to select a file to upload to something like Google Drive.  Is this currently possible?

**Comment by The-Compiler** [comment]
This currently isn't possible, but it came up a few times in the past. Also see #1365.

**Comment by Migacz85** [comment]
That would be awesome feature. In what files / lines of code file picking is triggered on ?

**Comment by jgkamat** [comment]
Have you seen https://github.com/qutebrowser/qutebrowser/pull/4477 yet? I haven't looked at it myself but if you're interested you should test/review the PR :)

**Comment by The-Compiler** [comment]
Fixed via #5987 - thanks @user202729 and @AckslD!
