### ISSUE TITLE
Constant renderer process crashes

### ISSUE THREAD

**Issue by peet1234** [qutebrowser/qutebrowser#3952]
![2018-05-28-11 25 18](https://user-images.githubusercontent.com/37007880/40597419-94063f96-626b-11e8-9211-53b1ea919a0e.png)
www.google.com
youtube
facebook
all crashed

**Comment by The-Compiler** [comment]
What output do you get when starting qutebrowser in a terminal and it crashes?

**Comment by The-Compiler** [comment]
oh, also: What Qt version, backend and qutebrowser version?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by peet1234** [comment]
qutebrowser --version
[0528/114025.156884:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/peet/#4326388 (deleted)
  Error: No such file or directory
qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.10-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/peet/.cache/qutebrowser
config: /home/peet/.config/qutebrowser
data: /home/peet/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00

**Comment by peet1234** [comment]
when run in terminal Show:

**Comment by The-Compiler** [comment]
Can you please `:quit` your existing instance, then again start qutebrowser in a terminal, and show the output you get when the crash happens?

**Comment by peet1234** [comment]
no more crashed, it's normal again.... thanks

**Comment by The-Compiler** [comment]
Well then... ¯\_(ツ)_/¯

**Comment by wedens** [comment]
I think you updated qt with running qutebrowser. I'm pretty sure that is what caused such problem for me. (restarting qutebrowser helped)
