### ISSUE TITLE
Updated widevine

### ISSUE THREAD

**Issue by sQVe** [qutebrowser/qutebrowser#3953]
I cannot tell you enough how much I love this browser, but thank you!

I noticed today after updating qt5-webengine-widevine that Netflix wasn't working today. It worked fine yesterday and I have it configured correctly for qutebrowser.

Is there something I have to change on my end or what's going on?

Cheers!

**Comment by The-Compiler** [comment]
I'm assuming you're on qt5-webengine 5.11? Did you

**Comment by The-Compiler** [comment]
Whoops, didn't intend to close this. :smile:

**Comment by sQVe** [comment]
@The-Compiler That is correct.

**Comment by The-Compiler** [comment]
This looks like the [qt5-webengine-widevine update](https://aur.archlinux.org/cgit/aur.git/commit/?h=qt5-webengine-widevine&id=79dd257f69542c0aca41245e85c774d23c740c74) is broken - it says "update for qt5-webengine 5.11" but the related Qt bug about [not being able to load >61 is still open](https://bugreports.qt.io/browse/QTBUG-64071). I'll add a comment to the AUR package.

**Comment by TrilbyWhite** [comment]
Sorry I just caught the message on the AUR page.  sQVe or anyone else having trouble with qt5-webengine-widevine, feel free to comment on the aur page or contact me directly.  But first note that that package is specifically for systems that do not also have chrome/chromium installed.

**Comment by The-Compiler** [comment]
> But first note that that package is specifically for systems that do not also have chrome/chromium installed.

Do any files conflict with Chromium in the package? As far as I know, it should happily coexist with Chromium as long as QtWebEngine loads the right file (automatically with Qt 5.11, via `ppapi-widevine-path` otherwise).

**Comment by TrilbyWhite** [comment]
I don't think there are any file conflicts.  And it may be that the packages can coexist.  But there'd be no point.  I made the qt5-webengine-widevine package to fill a specific use-case: wanting to watch netflix/amazon on qt5-webengine-widevine *without* also installing chrome/chromium.  Qutebrowser can play netflix just fine without my AUR package if chrome is also installed on the system.

So If there are problems with qt5-webengine-widevine that only occur when chrome is also installed, then the fix is easy: remove qt5-webengine-widevine.

**Comment by sQVe** [comment]
This issue was resolved by the latest update to qt5-webengine-widevine for me!

**Comment by The-Compiler** [comment]
I'm confused - there hasn't been a qt5-webengine-widevine update since the one 5 days ago (where you opened the issue). Is it possible that you still were on Qt 5.10 before, but are on 5.11 now?

**Comment by sQVe** [comment]
@The-Compiler Now I'm really confused too. I ran an system update yesterday and got an update for qt5-webengine-widevine. After that Netflix started to work again. 

But the AUR does say it wasn't updated... Maybe there was some update hickup on my system or something.
