### ISSUE TITLE
Qutebrowser opens 3 sessions for 1 second and then closes.

### ISSUE THREAD

**Issue by Drunkenpanda2000** [qutebrowser/qutebrowser#3956]
Ok sorry to bother you again but after using qutebrowser i can't go back to shitty non qutebrowser browsers.

I had an issue earlier on the same install this was fixed after reboot.
Now i have the same issue again i think and a reboot doesn't help.

Here is what the console trows at me.

> [0528/211315.801453:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/drunkenpanda/#2630939 (deleted)
>   Error: No such file or directory
> [3918:3941:0528/211315.858041:ERROR:gl_implementation.cc(246)] Failed to load /usr/bin/libGLESv2.so: /usr/bin/libGLESv2.so: cannot open shared object file: No such file or directory
> 21:13:15 INFO: Run :adblock-update to get adblock lists.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> [3918:3941:0528/211316.567472:ERROR:gl_surface_qt.cpp(701)] Requested OpenGL implementation is not supported. Implementation: 0
> *** stack smashing detected ***: <unknown> terminated
> Received signal 6
> #0 0x7f9161b590c6 <unknown>
> #1 0x7f91607d684c <unknown>
> #2 0x7f9161b5943c <unknown>
> #3 0x7f9177c00a80 <unknown>
> #4 0x7f917786986b __GI_raise
> #5 0x7f917785440e __GI_abort
> #6 0x7f91778ab8b8 __libc_message
> #7 0x7f917793c80d __GI___fortify_fail_abort
> #8 0x7f917793c7c2 __stack_chk_fail_local
> #9 0x7f916082d48c <unknown>
> #10 0x7f91625a45e7 <unknown>
> #11 0x7f91625b17ce <unknown>
> #12 0x7f91625b40af <unknown>
> #13 0x7f91625b531f <unknown>
> #14 0x7f91625aeb0d <unknown>
> #15 0x7f91625af398 <unknown>
> #16 0x7f91625ae41e <unknown>
> #17 0x7f91625b0a45 <unknown>
> #18 0x7f9161bdee82 <unknown>
> #19 0x7f9161b764d8 <unknown>
> #20 0x7f9161b774b8 <unknown>
> #21 0x7f9161b77923 <unknown>
> #22 0x7f9161b78c81 <unknown>
> #23 0x7f9161b971bb <unknown>
> #24 0x7f9161bb2196 <unknown>
> #25 0x7f9161bad38b <unknown>
> #26 0x7f9177bf6075 start_thread
> #27 0x7f917792b53f __GI___clone
>   r8: 0000000000000000  r9: 00007f9123ffd8c0 r10: 0000000000000008 r11: 0000000000000246
>  r12: 00007f9123ffdb60 r13: 0000000000001000 r14: 0000000000000040 r15: 00007f9142fb0000
>   di: 0000000000000002  si: 00007f9123ffd8c0  bp: 00007f9123ffdca0  bx: 0000000000000006
>   dx: 0000000000000000  ax: 0000000000000000  cx: 00007f917786986b  sp: 00007f9123ffd8c0
>   ip: 00007f917786986b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
>  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> 

Here is the **version Info**

> 
> [drunkenpanda@Diablo ~]$ qutebrowser --version
> [0528/211006.135818:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/drunkenpanda/#2630893 (deleted)
>   Error: No such file or directory
> [3868:3890:0528/211006.197817:ERROR:gl_implementation.cc(246)] Failed to load /usr/bin/libGLESv2.so: /usr/bin/libGLESv2.so: cannot open shared object file: No such file or directory
> qutebrowser v1.2.1
> Git commit: 
> Backend: QtWebEngine (Chromium 61.0.3163.140)
> 
> CPython: 3.6.5
> Qt: 5.10.1
> PyQt: 5.10.1
> 
> sip: 4.19.8
> colorama: no
> pypeg2: 2.15
> jinja2: 2.10
> pygments: 2.2.0
> yaml: 3.12
> cssutils: no
> attr: 18.1.0
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebKitWidgets: no
> pdf.js: no
> sqlite: 3.23.1
> QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018
> 
> Style: Qt5CTProxyStyle
> Platform: Linux-4.14.40-1-MANJARO-x86_64-with-arch-Manjaro-Linux, 64bit
> Linux distribution: Manjaro Linux (manjaro)
> Frozen: False
> Imported from /usr/lib/python3.6/site-packages/qutebrowser
> Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
> 
> Paths:
> cache: /home/drunkenpanda/.cache/qutebrowser
> config: /home/drunkenpanda/.config/qutebrowser
> data: /home/drunkenpanda/.local/share/qutebrowser
> runtime: /run/user/1000/qutebrowser
> system data: /usr/share/qutebrowser
> 
> Uptime: 0:00:00

**Comment by jgkamat** [comment]
> Requested OpenGL implementation is not supported. Implementation: 0

I'm guessing this means that there's something wrong with your drivers? 

can you try running with:

```
qutebrowser -s qt.force_software_rendering true
```

**Comment by The-Compiler** [comment]
Is this on Wayland?

**Comment by Drunkenpanda2000** [comment]
THis is not on wayland. and i'm sorry to say it was again fixed by running yaourt suya.
all tho i am confuzed do i realy have to update my entire system evry day just to get qutebrowser working evry day ? i whould think it whould keep running if nothing changed during 1 install.

**Comment by The-Compiler** [comment]
Well, no idea what you're doing, but since it works for everyone else this is probably something on your system... ¯\\_(ツ)_/¯
