### ISSUE TITLE
hint that for follow hint are not appear on spawn hint

### ISSUE THREAD

**Issue by thyeun** [qutebrowser/qutebrowser#3961]
i facing this issue on once of this [link](https://vidzi.si/jmcdhihdltqr.html)

i have create a spawn hint for watching online movie on mpv

not all link affected, only some of the link are without spawn hint

Result as below for ```follow hint... ```
![screenshot_2018-05-29_18-45-15](https://user-images.githubusercontent.com/1939446/40654443-f6005262-6370-11e8-84a7-1e108f3f246a.jpg)

Result as below for ```spawn hint.... ```
![screenshot_2018-05-29_18-45-48](https://user-images.githubusercontent.com/1939446/40654503-16e4ba7c-6371-11e8-937e-cbb6f16e8580.jpg)

**Comment by The-Compiler** [comment]
Spawning only works with hints which have an URL associated with them, not any clickable element.
