### ISSUE TITLE
SQL error in version 1.3.0

### ISSUE THREAD

**Issue by kfiz** [qutebrowser/qutebrowser#3962]
Hi,
when trying to start qutebrowser I get:
```
Error initializing SQL: Failed to prepare query "PRAGMA journal_mode=WAL": "database disk image is malformed Unable to execute statement"
``` 
System and version info:
```
#qutebrowser --version
[0529/184641.809694:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/louis/#661800 (deleted)
  Error: No such file or directory
qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.11-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/louis/.cache/qutebrowser
config: /home/louis/.config/qutebrowser
data: /home/louis/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```
Since this seems to be database related I tried reinstalling qutebrowser, but that unfortunately did not solve the problem.

Best

Doro

**Comment by jgkamat** [comment]
Hmm, I'm not sure why the history database would get corrupted, sqlite is usually pretty good about this.

Could you try shutting down qutebrowser and moving `~/.local/share/qutebrowser/history.sqlite` to a different directory? The database should be recreated, although, you'd probably have to try to recover the sqlite file to get this history back...

**Comment by The-Compiler** [comment]
Unfortunately, I don't think there's anything qutebrowser can do here - it's sqlite's business to keep the file in a consistent state...

**Comment by iggy** [comment]
Super late to this party, but I found this issue via a google search when I was having this issue.

I ended up fixing it by dumping my history sqlite database to a new one.

```
sqlite3 history.sqlite .dump | sqlite3 history-new.sqlite
mv history.sqlite history.sqlite.bak
mv history-new.sqlite history.sqlite
```

Hopefully for those that don't want to wipe their history this helps a little.
