### ISSUE TITLE
Problem scrolling in YouTube.com

### ISSUE THREAD

**Issue by thezealousfool** [qutebrowser/qutebrowser#3964]
For some reason I am unable to scroll in the YouTube page using j, k or the arrow keys. Pressing space adds space to YouTube's search bar even though not in insert mode.

version: 1.3.1

**Comment by jgkamat** [comment]
This seems like #2668.

Does `:scroll-page` or `:scroll-px` work for you?

**Comment by thezealousfool** [comment]
No neither :scroll-page nor :scroll-px works.

I noticed something similar in the github page too, when the dropdown to select a branch is open. (To reproduce: Go to some repository and expand the branch dropdown. Now pressing on j, k keys moves the branch that is in focus, I cannot scroll the page anymore).

**Comment by thezealousfool** [comment]
I think the fields stay in focus. Even when typing replies in this issue, after I am done typing and I get out of insert mode, the j and k keys move the cursor in the text area and I do not know how to get the focus out of the text area apart from a mouse click on some black space in the page.

**Comment by The-Compiler** [comment]
That's expected because `:scroll down` (what `j` is bound to) simply emulates a down arrow keypress. After e.g. a `:bind j scroll-px 0 20` things work fine here though - are you sure it doesn't work for you?

**Comment by thezealousfool** [comment]
I am sorry. ```:bind j scroll-px 0 20``` did work. Awesome. Why don't you have this as the default rather than the down arrow keypress.

**Comment by The-Compiler** [comment]
Because it has other issues and doesn't work properly for all pages (especially with multiple scrollable elements). See #2668 and #3691 for some more discussion about the whole topic.
