### ISSUE TITLE
Bug: yanking and copying not longer possible after some time

### ISSUE THREAD

**Issue by merspieler** [qutebrowser/qutebrowser#3969]
I had this multiple times... when qb runs for some weeks, somewhen the yanking and copying doesn't work anymore. The only way to copy texts is drag and drop, `Ctrl+C` as well as URL yanking with `yy` or `yY`fails.

`:messages` show me after I try to copy something:
`14:39:22|WARNING|qt|Unknown module:none:0|QXcbClipboard::setMimeData: Cannot set X11 selection owner`

I'm not quite sure if this can be an X11 or i3wm problem as well.

qb version 1.3.0 (as well with earlier versions)
Xorg version 1:7.7+19
i3wm version 4.13
running on Debian Stretch

Restarting qb fixes the problem.

**Comment by The-Compiler** [comment]
See [QTBUG-65145](https://bugreports.qt.io/browse/QTBUG-65145)
