### ISSUE TITLE
Remove guess work from hint links

### ISSUE THREAD

**Issue by mysteryjeans** [qutebrowser/qutebrowser#3974]
It's quite often that I try to follow hints by start typing anchor text. It would be better if hints links start with same letter as the anchor text. I leave that upto you; to use second letter as well to make hints unique or select from a-z.

**Comment by toofar** [comment]
There are three modes for hinting than can be set via `:set hints.mode`: letter, word and number. I haven't played around with the different setups much myself but it looks like; letter is the default one that picks from a set of characters, word tries to pull the first word from the link text and falls back to a dictionary word in the case of duplicates, numbers uses numbers in order but also lets you write in the link (and alt?) text to filter the hinted elements.

**Comment by The-Compiler** [comment]
@toofar is pretty much spot on - so you can already do that with the different hint modes.

**Comment by mysteryjeans** [comment]
Actually I am suggesting about when hint mode is set to letter. Letter seems to be chosen randomly, but it will be better if letter selections starts with first letter of anchor text. For instance "Home" achor will have "ho" hint and "Help" anchor will have "he". Currently word mode chosing words most of the time different then anhor text anyway.

**Comment by mschilli87** [comment]
@mysteryjeans: Did you try `:set hints.mode number`?
You can start typing part of the link text ("ho" or "he" and only matching links will be numberd. Once only a single hint is left (*e.g.* no other link containing "he"), it is automatically followed.
Maybe this is close enough to what you want?

**Comment by jgkamat** [comment]
Also see hints.scatter for why the hints appear to be "randomly" placed. With that off, they are labelled incrementally. It might be possible to write a new ordering pretty easily, its not too hard to tweak that code.

On June 5, 2018 1:50:30 AM EDT, Marcel Schilling <notifications@github.com> wrote:
>@mysteryjeans: Did you try `:set hints.mode number`?
>You can start typing part of the link text ("ho" or "he" and only
>matching links will be numberd. Once only a single hint is left (*e.g.*
>no other link containing "he"), it is automatically followed.
>Maybe this is close enough to what you want?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mysteryjeans** [comment]
@mschilli87 Thanks, I didn't know that. 

@jgkamat Yes, hints scatter was set to true.
