### ISSUE TITLE
Using Qutebrowser to read html email from NeoMutt

### ISSUE THREAD

**Issue by toogad** [qutebrowser/qutebrowser#3982]
Neomutt version: 20180512
Qutebrowser version: 1.13.1
Operating system: Arch Linux, up to date.

I have been using qutebrowser to view html emails on Neomutt. It had been fine until recently, when I open the html email as attachment, qutebrowser displays the html source code instead of rendering as per the code.

Thanks.
kz

**Comment by The-Compiler** [comment]
Chromium disabled mime sniffing for local files (without `.html` extension) for security reasons: https://bugs.chromium.org/p/chromium/issues/detail?id=777737

That change also landed in Qt 5.11, which means qutebrowser will also require a .html extension there.

**Comment by The-Compiler** [comment]
Also see the `nametemplate` setting in the [mailcap docs](https://neomutt.org/guide/mimesupport#3-3-1-%C2%A0optional-fields) which seems to be the solution for this kind of issue :smile:

**Comment by toogad** [comment]
Awesome! Thanks a lot Florian.

kz
