### ISSUE TITLE
Automate bumping version for the release

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3985]
Using e.g. [bumpversion](https://pypi.org/project/bumpversion/) we could automatically increase version numbers and do git commit/tags. It could hopefully also be used to add new versions to qutebrowser.appdata.xml, see #3926.

**Comment by AndyMender** [comment]
This looks like an interesting issue to me :). From my `:version`:

```
        qutebrowser v1.5.0
        Git commit: 8fed1f5fb (2018-10-05 18:58:33 +0200)
        Backend: QtWebEngine (Chromium 65.0.3325.230)
         
        CPython: 3.6.6
        Qt: 5.11.2
        PyQt: 5.11.3
         
        sip: 4.19.13
        colorama: 0.3.9
        pypeg2: 2.15
        jinja2: 2.10
        pygments: 2.2.0
        yaml: 3.13
        cssutils: 1.0.2 $Id$
        attr: 18.2.0
        PyQt5.QtWebEngineWidgets: yes
        PyQt5.QtWebKitWidgets: no
        pdf.js: no
        sqlite: 3.24.0
        QtNetwork SSL: OpenSSL 1.0.2o  27 Mar 2018
         
        Style: QFusionStyle
        Platform: Linux-4.18.0-1-amd64-x86_64-with-debian-buster-sid, 64bit
        Linux distribution: Debian GNU/Linux buster/sid (debian)
        Frozen: False
        Imported from /home/andy/projects/qutebrowser/qutebrowser
        Using Python from /home/andy/projects/qutebrowser/.venv/bin/python3
        Qt library executable path: /home/andy/projects/qutebrowser/.venv/lib/python3.6/site-packages/PyQt5/Qt/libexec, data path: /home/andy/projects/qutebrowser/.venv/lib/python3.6/site-packages/PyQt5/Qt
         
        Paths:
        cache: /home/andy/.cache/qutebrowser
        config: /home/andy/.config/qutebrowser
        data: /home/andy/.local/share/qutebrowser
        runtime: /run/user/1000/qutebrowser
         
        Uptime: 0:31:41
```
I'm assuming `bumpversion` could be used to to modify this line ```        qutebrowser v1.5.0```, but in the Python code? What about the git commit hashes / tags - should they be included in the qutebrowser version or used to generate tagged git branches?

qutebrowser.appdata.xml could easily be modified with `lxml`, I think :).

**Comment by The-Compiler** [comment]
> I'm assuming `bumpversion` could be used to modify this line `qutebrowser v1.5.0`, but in the Python code?

Yep, see [`qutebrowser/__init__.py`](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/__init__.py#L29).

> What about the git commit hashes / tags - should they be included in the qutebrowser version or used to generate tagged git branches?

I don't understand the question. Those are shown mainly for people running qutebrowser from the git repository and not a released version.

> qutebrowser.appdata.xml could easily be modified with `lxml`, I think :).

Would be nice if it could be done via `bumpversion` as well so there's one tool for everything - but if not, I guess doing it in `build_release.py` or so would work as well.

**Comment by AndyMender** [comment]
I believe it can be done via `bumpversion`. We just need to specify a .bumpversion.cfg or setup.cfg file with:
```
[bumpversion]
current_version = 0.2.9
commit = True
tag = True
tag_name = v{new_version} # Python-like .format() string formatting to generate the git tag text
```
Next, we define `VERSION` as an attribute in a central constants file or similar so that all modules pull from that file and don't try to open .bumpversion.cfg or setup.cfg simultaneously. The __init__.py of the top-level `qutebrowser` module would be a perfect candidate here, since later setup.py pulls the constants from it.

Here's my example script which adds a new release using that version into qutebrowser.appdata.xml. Below, a modified appdata.xml `<releases>` block:
```xml
	<releases>
		<release version="1.3.0" date="2018-05-04"/>
		<release version="1.2.1" date="2018-03-14"/>
		<release version="1.2.0" date="2018-03-09"/>
	<release version="1.5.0" date="2018-10-06"/></releases>
```

**Comment by The-Compiler** [comment]
But that script probably won't be run from bumpversion then, right? In other words, it has to be started separately?

**Comment by AndyMender** [comment]
Yes and no, I would say. update_version.py (the script in question) can contain a `subprocess.run()` call to `bumpversion` to increment the version and later other calls needed to populate non-Python files with the new release information (qutebrowser.appdata.xml among others). All of this would be run under the emblem of `build_release.py`. Alternatively, `bumpversion` is run from the command-line prior to running `build_release.py` :).

**Comment by The-Compiler** [comment]
Fair - let's add a `scripts/dev/update_version.py` which calls `bumpversion` then.

**Comment by AndyMender** [comment]
I also modified `__version__` and `__version_info__` using `configparser.ConfigParser`, the same way `bumpversion` reads its own config files:
```python
from configparser import ConfigParser
import os.path

# load .bumpversion.cfg config
config = ConfigParser()
config.read('.bumpversion.cfg')

__author__ = "Florian Bruhin"
__copyright__ = "Copyright 2014-2018 Florian Bruhin (The Compiler)"
__license__ = "GPL"
__maintainer__ = __author__
__email__ = "mail@qutebrowser.org"
__version__ = config['bumpversion']['current_version']
__version_info__ = __version__.split('.')
__description__ = "A keyboard-driven, vim-like browser based on PyQt5."

basedir = os.path.dirname(os.path.realpath(__file__))
```
That way the entire qutebrowser will have access to the correct version when loading.

**Comment by The-Compiler** [comment]
Huh, why would `__init__.py` read stuff from `.bumpversion.cfg`? The whole point of `bumpversion` is bumping the version in files like `__init__.py`.

**Comment by AndyMender** [comment]
Apologies, this was a preliminary solution to have a bit more control over the version bumping process.
The current .bumpversion.cfg looks as follows and properly bumps `__version__` located in qutebrowser/__init__.py and also changes `current_version` in the .bumpversion.cfg INI itself:
```
[bumpversion]
current_version = 1.5.0
commit = True
tag = True
tag_name = v{new_version}

[bumpversion:file:qutebrowser/__init__.py]
parse = __version__ = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
```
An aux `bump_version` function was also added to update_version.py to execute the bumping:
```python
def bump_version(version_leap = "patch"):
    """Update qutebrowser release version in .bumpversion.cfg

    :param version_leap: define the jump between versions ("major", "minor", "patch")
    """

    # make sure the correct version jump was chosen
    if version_leap not in ("major", "minor", "patch"):
        raise ValueError("version_leap takes values of 'major', 'minor' or 'patch' only.")

    # NOTE: this may rely on the python version used to launch the function
    # and whether the wrapper script 'bumpversion' was provided
    subprocess.run(['bumpversion', version_leap, '--allow-dirty'])
```

I left 2 bumps in the tree of this branch on purpose to show that it actually works :).
