### ISSUE TITLE
Any guides on compiling QtWebEngine on windows?

### ISSUE THREAD

**Issue by compl3x** [qutebrowser/qutebrowser#3986]
First, thanks for the effort on this browser, it's really amazing. 
Everything about this browser is right, but many users needs the codecs in order to view some videos. 
I am aware that in order to get the proprietary codecs we need to compile the engine from source. 
Are there any guides that shows how to compile the engine on windows? I tried searching but couldn't find any reliable guide. 
Also, after recompiling the engine, how would I be able to attach it to Qutebrowser, is it just a matter of copy and paste?

**Comment by The-Compiler** [comment]
There are various documents which might be useful:

- https://doc.qt.io/qt-5/windows-requirements.html
- https://doc.qt.io/qt-5/windows-building.html
- https://doc.qt.io/qt-5/qtwebengine-platform-notes.html

To use it with qutebrowser, you'll need to build SIP and [PyQt5](http://doc.qt.io/qt-5/windows-building.html) against the self-built Qt, and then start qutebrowser with that.

Good luck...
