### ISSUE TITLE
Math symbols are not rendered properly

### ISSUE THREAD

**Issue by copyme** [qutebrowser/qutebrowser#3987]
I am on the version 1.3.1 and I have noticed that many math symbols on the Wikipedia pages are rendered as white rectangles. See for example: https://en.wikipedia.org/wiki/List_of_mathematical_symbols and compare with Firefox.

Qutebrowser
![image](https://user-images.githubusercontent.com/456607/41203312-6ef949a4-6cd5-11e8-9467-a20d3938e083.png)

Firefox: 
![image](https://user-images.githubusercontent.com/456607/41203324-9f329a76-6cd5-11e8-8f03-060de88e2102.png)

Is this is a general problem, or it has to do something with my local settings?

Anyway, thanks for this great browser!

**Comment by jgkamat** [comment]
> I am on the version 1.3.1 and I have noticed that many math symbols on the
> Wikipedia pages are rendered as white rectangles. See for example:
> https://en.wikipedia.org/wiki/List_of_mathematical_symbols and compare with
> Firefox.

My best guess for this is that qb uses the system fonts while Firefox uses
built-in ones (by default), so it's possible to have broken fonts in qb but
not Firefox.

My qb seems to display most of these symbols fine, I'm guessing I'm missing
some fonts on the others.

**Comment by The-Compiler** [comment]
The only symbol I don't see is the contradiction one - I see it in Firefox, but it also displays as a box in Chromium. Like @jgkamat says, the issue is likely missing system fonts.

**Comment by copyme** [comment]
Thanks guys I will report this to the package maintainers of my Linux distribution.

**Comment by The-Compiler** [comment]
I don't see this as a bug in the package either. If it was, anything displaying text would have to depend on dozens of font packages to make sure it can display all possible symbols.
