### ISSUE TITLE
KDE plasma integration

### ISSUE THREAD

**Issue by Teyras** [qutebrowser/qutebrowser#3996]
Are there any plans to implement browser integration for KDE Plasma (introduced in Plasma 5.13)? From what I saw, it looks like it requires the browser to register some dbus services and interact with others.

Personally, I would like to see this implemented as some sort of a plugin, but AFAIK that's not supported yet.

**Comment by The-Compiler** [comment]
I agree this would have to be in a plugin, so I added it to #30. No plans from my side to work on it, as I don't use KDE.

Related links:

- https://community.kde.org/Plasma/Browser_Integration
- https://www.youtube.com/watch?v=WGhrR1HsCOM
