### ISSUE TITLE
Private tabs retained and opened in non-private tab after browser crash

### ISSUE THREAD

**Issue by craftyguy** [qutebrowser/qutebrowser#3999]
I've noticed that if I have a private tab open and qutebrowser crashes for any arbitrary reason, when I re-open qutebrowser the website I had previously opened in a private tab loads in a non-private tab. This is really hard to reproduce since it requires qutebrowser crashing, but every time it crashes and I have a private tab open, the site loads in a non-private tab when qutebrowser is re-opened and session restored.

Version info below, but I started noticing this happening since at least 1.3.1 (maybe before that, but I wasn't keeping track)

```
qutebrowser v1.3.2
Git commit: 20763a87c (2018-06-10 17:34:17 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.17.0-mainline-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by jgkamat** [comment]
I think this is a (partial) duplicate of #3979

**Comment by craftyguy** [comment]
@jgkamat Thanks, yea this is a duplicate so I will close. Sorry for the noise!

**Comment by The-Compiler** [comment]
> This is really hard to reproduce since it requires qutebrowser crashing

Let me note that there's a `:debug-crash` command (which is hidden unless started with `--debug` but works either way) :wink:
