### ISSUE TITLE
Youtube playback in h264 only with hardware acceleration

### ISSUE THREAD

**Issue by mysteryjeans** [qutebrowser/qutebrowser#4001]
I am using mpv to playback with vaapi h264 basically by binding "bind ;m hint links spawn mpv --hwdec=vaapi --vo=vaapi {hint-url} --ytdl-format='mp4[height<=720]/best[height<=?720]'". 

However I am thinking to use h264ify extension from chrome can be usefull with hardware acceleration. Or someway to disable webm totally and use  -qt-flags for hardware acceleration.. Need help here!!

[faraz@arch-mac ~]$ vainfo
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD

**Comment by The-Compiler** [comment]
This isn't supported by QtWebEngine (and Chromium, I think). There were attempts to make it work in QtWebEngine, but to my knowledge, it never worked out properly and was abandoned.
