### ISSUE TITLE
Enabling JS for IPv6 Address fails

### ISSUE THREAD

**Issue by merspieler** [qutebrowser/qutebrowser#4006]
When I try to enable js for an IPv6 Address with the default `tsh`binding i get the following error message:
```
ERROR | message | message:error:63 | Error while parsing *://<IPv6 Address>/*: Invalid port: invalid literal for int() with base 10: '<IPv6 Address>'
```

**Comment by merspieler** [comment]
Any update on this?

**Comment by The-Compiler** [comment]
The URL match patterns are ported from Chromium's [match patterns](https://developer.chrome.com/apps/match_patterns) - at the time I implemented/ported them, they didn't support IPv6 addresses in Chromium either.

However, it looks like support for that [was added to Chromium](https://chromium.googlesource.com/chromium/src.git/+/c008bf657dbc01fadc4ff1ea3df21f9cf237569a%5E%21/), incidentally a few hours after you opened this issue :laughing:

So all that needs to be done is porting those changes (and the associated tests) to qutebrowser's [urlmatch.py](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/utils/urlmatch.py) and [test_urlmatch.py](https://github.com/qutebrowser/qutebrowser/blob/master/tests/unit/utils/test_urlmatch.py). I probably won't work on that anytime soon though.

**Comment by merspieler** [comment]
ok...

**Comment by tiemenv** [comment]
If someone is willing to give me some pointers I'd be glad to look into this

**Comment by The-Compiler** [comment]
@tiemenv Have you seen the links in my post above? Basically, the change in the linked commit needs to be ported from C++ to Python.

**Comment by The-Compiler** [comment]
As @DerJesko points out in #4118, parsing IPv6 addresses in `UrlPattern` works fine:

```python
>>> urlmatch.UrlPattern('*://[2001:41d0:2:3b68::1]/*')
qutebrowser.utils.urlmatch.UrlPattern(pattern='*://[2001:41d0:2:3b68::1]/*')
```

so the issue you're actually seeing is with the `tsh` binding, similar to how it handles `file://` URLs incorrectly. I thought there was an issue for that already, but I cn't find it right now.

**Comment by jgkamat** [comment]
Ah, that's true, I only tested the tsu binding(s).

On my server http://[::1]:8080/ {url} is http://[::1]:8080/ and {url:host} is
'::1'. This fails in the actual binding because it's not in square brackest
(I'm guessing).

I'm also not sure if this would be different if it wasn't just my toy server
setup :P

Florian Bruhin writes:

**Comment by lufte** [comment]
> so the issue you're actually seeing is with the `tsh` binding, similar to how it handles `file://` URLs incorrectly. I thought there was an issue for that already, but I cn't find it right now.

@The-Compiler I just ran into this. Does the issue exist after all? I also couldn't find it.

**Comment by The-Compiler** [comment]
@lufte Nope, but I think it's the same underlying issue as this one.
