### ISSUE TITLE
Bug: Error messages appear in all open windows

### ISSUE THREAD

**Issue by mrschyte** [qutebrowser/qutebrowser#4018]
If there are multiple windows open, any generated error message appears in all open windows.
For example pressing `n' will print "No search done yet" in all windows. Error messages should only appear in the relevant window which is almost the focused window most of the time.

> qutebrowser v1.3.3
> Git commit: 
> Backend: QtWebEngine (Chromium 65.0.3325.230)
> 
> CPython: 3.6.5
> Qt: 5.11.1
> PyQt: 5.10.1
> 
> sip: 4.19.8
> colorama: 0.3.9
> pypeg2: 2.15
> jinja2: 2.10
> pygments: 2.2.0
> yaml: 3.12
> cssutils: 1.0.2 $Id$
> attr: 18.1.0
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebKitWidgets: yes
> pdf.js: no
> sqlite: 3.24.0
> QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018
> 
> Style: QFusionStyle
> Platform: Linux-4.17.2-1-ARCH-x86_64-with-arch, 64bit
> Linux distribution: Arch Linux (arch)
> Frozen: False
> Imported from /usr/lib/python3.6/site-packages/qutebrowser
> Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
> 
> Paths:
> cache: /home/user/.cache/qutebrowser
> config: /home/user/.config/qutebrowser
> data: /home/user/.local/share/qutebrowser
> runtime: /run/user/1000/qutebrowser
> system data: /usr/share/qutebrowser

**Comment by The-Compiler** [comment]
That's intended, as for many cases, qutebrowser doesn't know where an error message is coming from (and there isn't always a focused window).

**Comment by edrex** [comment]
This has been a nit for me ever since tabs as windows showed up. It's pretty jarring in a tiling window env like i3/sway, when you have 10+ windows visible across two monitors.

Would you be open to a patch to scope the messages in those cases where it's possible to localize? IDK about sending global confirmations (eg, on quit) only to focused window since that may change, but when an error results from a command typed into a given window, it seems possible to plumb the window context through.

**Comment by The-Compiler** [comment]
Also see #5535 for prompts.

**Comment by slacksystem** [comment]
Regarding this and #5535, and the explanation that many of these dialogs have to show on all windows, how do chrome and chromium, etc, manage to show on only one window, and is it possible to implement that here?

It's quite frustrating when a prompt originating from one window (error or download or especially login) blocks another window where I'm streaming a video. I'm confused as to how this is possible for most other browsers but not here.

**Comment by The-Compiler** [comment]
Chromium can closely tie their low-level API to whatever their UI needs, while with qutebrowser there are more layers in between that constrain how a solution can look like.
