### ISSUE TITLE
Links for archive.org forward to the archived page URL

### ISSUE THREAD

**Issue by slackhead** [qutebrowser/qutebrowser#4023]
qutebrowser v1.3.3
Git commit: d2254ca48 (2018-06-21 23:32:56 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.11.dev1806121437
sip: 4.19.9.dev1806121436

When this link is clicked, or pasted into the :open command qb forwards to the second URL.

http://web.archive.org/web/20060901044205/http://www4.ncsu.edu/~smheath/news14.html

**Comment by The-Compiler** [comment]
Works fine here (note that you need to turn on JavaScript to see the bar at the top). Do you actually see http://www4.ncsu.edu/~smheath/news14.html in the statusbar when this happens?

**Comment by slackhead** [comment]
It seems to be privoxy that's causing it.
