### ISSUE TITLE
Is there something similar to `;k` in Tridactyl

### ISSUE THREAD

**Issue by VincentTam** [qutebrowser/qutebrowser#4027]
Currently, `;k` in Tridactyl kills an element.  Are there anything similar in Qutebrowser?

**Comment by NoctuaNivalis** [comment]
Killing an element as in, removing it's HTML tags and content from the page? No, but it'd be nice to have.

**Comment by toofar** [comment]
I don't think so. It likely doesn't have a selector as useful as what they are using either (`all` says "All clickable elements"). You could maybe call some :jseval command from `hint` but there is no way to get the dom element to it, I think.

Anyway, what I did (you have to use a mouse though!) was grab this chrome extension https://chrome.google.com/webstore/detail/click-to-remove-element/jcgpghgjhhahcefnfpbncdmhhddedhnk?hl=en from some extension downloader site grabed the ctre_content.js file out of it, commented out all of the references to the global `chrome` object than at the end of the file added two lines `ctre.init()` and `unsafeWindow.ctre = ctre` to make the object available from window so I could bind a command or make an alias that called `jseval -w 0 window.ctre.toggle()`. Then add a greasemonkey head to the file and drop it into the greasemonkey folder (details in the qute FAQ)

Here is the diff
```diff
--- /tmp/Click-to-Remove-Element/ctre_content.js	2018-06-29 19:37:32.470303915 +1200
+++ /tmp/qute-basdir-webchannel/data/greasemonkey.all/ctre_content.js	2018-04-07 15:25:18.362864339 +1200
@@ -1,3 +1,11 @@
+// ==UserScript==
+// @name         Click to Remove Element
+// @grant        unsafeWindow
+// @run-at       document-start
+// @include      *
+// ==/UserScript==
+// Modified by removing references to the global chrome object
+// and adding ctre to unsafeWindow
 /*
 	CTRE v1.0.5
 	by @blade_sk
@@ -211,7 +219,7 @@
 		
 		ctre.addOverlays();
 		
-		chrome.extension.sendMessage({action: 'status', active: true});
+		//chrome.extension.sendMessage({action: 'status', active: true});
 	},
 	
 	deactivate: function()
@@ -235,7 +243,7 @@
 		
 		ctre.removeOverlays();
 		
-		chrome.extension.sendMessage({action: 'status', active: false});
+		//chrome.extension.sendMessage({action: 'status', active: false});
 	},
 	
 	toggle: function()
@@ -304,14 +312,18 @@
 		document.addEventListener('keydown', ctre.keyDown);
 		document.addEventListener('keyup', ctre.keyUp);
 		
-		chrome.extension.onMessage.addListener(function(msg, sender, responseFun) {
-			if (msg.action == "toggle") {
-				ctre.toggle();
-				responseFun(1.05);
-			}
-			else if (msg.action == "getStatus") {
-				responseFun(ctre.targetingMode);
-			}
-		});
+		//chrome.extension.onMessage.addListener(function(msg, sender, responseFun) {
+		//	if (msg.action == "toggle") {
+		//		ctre.toggle();
+		//		responseFun(1.05);
+		//	}
+		//	else if (msg.action == "getStatus") {
+		//		responseFun(ctre.targetingMode);
+		//	}
+		//});
 	}
 }
+
+ctre.init();
+// make available globally
+unsafeWindow.ctre = ctre;
```

The source of that extension isn't open source though so don't distribute it withought permission, the author is alright though ;)

**Comment by VincentTam** [comment]
@toofar Thanks for comment.  How do you know that the author of the Chrome extension is alright?  You are the author?

**Comment by toofar** [comment]
No, I emailed them to see if they would consider licensing it under a free licence so I could use it as part of a greasemonkey script with persistence and an expanded UI. They said I could have it under whatever licence I wanted but didn't want it used for commercial purposes, so mixed messages there. I haven't got around to working on it anyway.

**Comment by The-Compiler** [comment]
Merging this into #521.
