### ISSUE TITLE
Disabling javascript is not working

### ISSUE THREAD

**Issue by MarkusBarthlen** [qutebrowser/qutebrowser#4031]
Using the following config.py I try to disable javascript on my machine:

```
# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', False, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', False, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', False, 'qute://*/*')
```
I also have an old qutebrowser.conf file with 

> allow-javascript = false

My versions are as follows:
```

qutebrowser v1.3.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: Qt5CTProxyStyle
Platform: Linux-4.14.48-2-MANJARO-x86_64-with-arch-Manjaro-Linux, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/markus/.cache/qutebrowser
config: /home/markus/.config/qutebrowser
data: /home/markus/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```
How did I come to the conclusion:
I opened twitter.com, a local file with an alert and WhatIsMyBrowser.com.
I also tried 
:config-unset content.javascript.enabled
Am I missing something or should this work (Btw, also observed this on a windows machine some time ago)?

Thank you very much, keep up the good work.

**Comment by jgkamat** [comment]
On July 1, 2018 3:09:53 AM GMT+05:30, MarkusBarthlen <notifications@github.com> wrote:

># Enable JavaScript.
># Type: Bool
>config.set('content.javascript.enabled', False, 'file://*')
>

This setting is commented out (like the others) so it wont have any effect. Also, you probably want to remove the file:// argument as you want this setting to apply globally, right?

Also see these config docs for more information: http://qutebrowser.org/doc/help/configuring.html

You could also use :set (as documented) if you remove the config.py file or load autoconfig.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MarkusBarthlen** [comment]
Thank you for helping me out.
