### ISSUE TITLE
Facebook and messenger accented characters disapear

### ISSUE THREAD

**Issue by eupiteco** [qutebrowser/qutebrowser#4032]
## Description
Whenever I type in textfields at facebook.com or messenger.com, accented characters (áãéç) blinks. They appear for a split second and disappear. I have not seen this behavior in any other sites so far. And in Firefox everything works just fine. I am using a standart US keyboard and us-intl with deadkeys layout.
Any ideia on what is causing this or how can it be solved?

## Qutebrowser version
qutebrowser v1.3.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: Qt5CTProxyStyle
Platform: Linux-4.14.48-2-MANJARO-x86_64-with-arch-Manjaro-Linux, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Comment by The-Compiler** [comment]
This is a Qt bug which has been fixed in Qt 5.11.1: [QTBUG-66046](https://bugreports.qt.io/browse/QTBUG-66046). As a workaround, you should be able to turn off spell checking in qutebrowser.
