### ISSUE TITLE
Qutebrowser briefly displays empty page in XMonad

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#4033]
This is a pretty niche issue, but hopefully someone can help me out. I recently switched (back) to XMonad from dwm, and I noticed immediately that when I switch to a workspace containing Qutebrowser (or switch to the Qutebrowser window from a window in another tab), I very quickly see a blank webpage (all white). See the example gif [here](https://media.giphy.com/media/fWfDbo6FQ1mmGYZNRv/giphy.gif). It's like a very bright flash of light.

A couple notes:

- If I change `colors.webpage.bg` from `white` to any other color, then that is the color I see.
- The issue does *not* happen with other browsers, like Falkon, Firefox, and Chromium.
- The issue does *not* happen with dwm, only with XMonad. Compare the above gif (XMonad) with [another gif](https://media.giphy.com/media/1AdZe0Ten4FG4xozRt/giphy.gif) in dwm.

Any idea what could possibly going on?

For now, I'm doing `set colors.webpage.bg black`, which sort of alleviates the problem, but then many webpages get rendered incorrectly because they're meant to be viewed with a white background.

**Comment by brianbuccola** [comment]
[Here's another gif](https://media.giphy.com/media/fnJQNoo6KDTw79ksC7/giphy.gif) with the background set to `red`, which makes it much more obvious/severe.

**Comment by toofar** [comment]
Do you use a compositor? Just throwing a suggestion out, I have no idea what it could be.

**Comment by The-Compiler** [comment]
I especially don't understand why this wouldn't happen in Falkon. Does it also happen in qutebrowser if you start it with `--temp-basedir`?

**Comment by brianbuccola** [comment]
Shoot, it *does* happen in Falkon. (I had to go to a website with a dark background in order to notice the white flash.) So, it's not specific to Qutebrowser.

Just to reply to your questions:

- No, I don't use a compositor.
- Yes, it does happen with `--temp-basedir` as well.

**Comment by tkerber** [comment]
Can confirm this, both with and without compositor. It is barely noticable for me, i.e. until I switched to the background to red to test it, I had no idea this was happening, and even then it's maybe a single frame for me.

**Comment by The-Compiler** [comment]
I see this as well in XMonad, but not with [herbstluftwm](https://herbstluftwm.org/). Since it doesn't seem to be qutebrowser-specific, I'd suggest to report this to either XMonad or [Qt's bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa).
