### ISSUE TITLE
Overheating with QtWebEngine on Arch Linux

### ISSUE THREAD

**Issue by andrea-berling** [qutebrowser/qutebrowser#4035]
On version 1.3.3, installed on Arch Linux on a Lenovo Thinkpad X220, after spending some time 
navigating the web I've often noticed my fans spinning like crazy, a lot of heat coming from the CPU
and, using top, I've seen that a process called QtWebEngine has a lot of CPU utilization (over 100
percent) and killing qutebrowser made the CPU fans stop spinning and the heat go away (after a
little). Not sure if it's a problem with Qt or with qutebrowser in particular, I just thought it was
helpful to let you know there's this problem.

**Comment by The-Compiler** [comment]
If it's QtWebEngineProcess processes taking CPU, that's an issue with QtWebEngine or the underlying Chromium.

**Comment by toofar** [comment]
You can kill the troublesome `QtWebEngine` process withought killing the whole browser if you are so inclined. It should bring the relevent tab the the "Renderer process crashed" error page. If it is always the same page getting killed that might tell you something. I occasionally see like three of those processes taking a whole core each and when I kill them I find that they are seemingly innocuous pages like the suspended tab page or even one with javascript turned off. I'm still on Qt 5.10.1 though so I am not sure how relevant that is.
