### ISSUE TITLE
Via tox crash: "undefined symbol: PySlice_AdjustIndices"

### ISSUE THREAD

**Issue by martonbalazs** [qutebrowser/qutebrowser#4038]
Hi, I just installed the latest version (1.4.0) from Github on Ubuntu 16.04 LTS via Tox which went fine, but when launching I get errors instead of a working Qutebrowser. Interestingly, Google found my exact error messages: [pastebin](https://pastebin.com/kwsHdDmC) so sorry if someone has already reported this.

**Comment by The-Compiler** [comment]
It looks like PyQt5 5.11.2 has [a bug](https://www.riverbankcomputing.com/pipermail/pyqt/2018-July/040511.html) making it incompatible with Python < 3.5.4. Unfortunately, Ubuntu 16.04 comes with 3.5.1...

I added a `mkvenv-pypi-old` environment to the `tox.ini` which allows you to build an environment with PyQt 5.10 instead.

**Comment by martonbalazs** [comment]
Sorry but a new git clone just as of now still gives the same errors. Thanks for looking at this!

**Comment by The-Compiler** [comment]
Did you do `tox -e mkvenv-pypi-old` rather than `tox -e mkvenv-pypi`?

**Comment by toofar** [comment]
>a new git clone
Ah, did you build a new venv too?

**Comment by martonbalazs** [comment]
Stuuupid me, it works. Apologies. Routine won, thinking lost over here. Thanks a lot!
