### ISSUE TITLE
Qutebrowser and/or webengine leaking out when using socks5 proxy

### ISSUE THREAD

**Issue by slackhead** [qutebrowser/qutebrowser#4041]
qutebrowser v1.4.0
Git commit: 0f037fb41 (2018-07-03 15:44:44 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.11.dev1806121437

sip: 4.19.9.dev1806121436
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.13.0
QtNetwork SSL: OpenSSL 1.0.2o  27 Mar 2018

Slackware 14.2 64bit.

I recently set up some iptables rules to reject anything leaving my system that doesn't go through Tor, Privoxy or 3proxy. Everything else gets rejected and logged. I'm seeing many entries in my syslog like:

Jul  4 15:15:13 raven kernel: [3428383.570853] TCP OUTPUT packet killed: IN= OUT=eth0 SRC=192.168.1.3 DST=23.38.96.107 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=59119 DF PROTO=TCP SPT=38433 DPT=443 WINDOW=0 RES=0x00 RST URGP=0

This resolvs to a23-38-96-107.deploy.static.akamaitechnologies.com. and I see similar entries for other sites I visit like upload-lb.eqiad.wikimedia.org.

Rules:

```
# Tor and Privoxy
$IPT -A OUTPUT -p TCP -m owner --uid-owner tor -j ACCEPT
$IPT -A OUTPUT -p TCP -m owner --uid-owner privoxy -j ACCEPT

# 3proxy and any custom commands run with 'sg -c'
$IPT -A OUTPUT -p TCP -m owner --gid-owner netaccess -j ACCEPT

# Log packets that still don't match
$IPT -A OUTPUT -p TCP -m limit --limit 3/minute --limit-burst 3 \
-j LOG --log-prefix "TCP OUTPUT packet killed: " --log-level 7

# No match, so REJECT
$IPT -A OUTPUT -p TCP -j REJECT
```

**Comment by The-Compiler** [comment]
Can you reproduce this with other QtWebEngine browsers (such as Falkon) and/or with Chromium?

**Comment by slackhead** [comment]
Yes it does that with chromium too. Launching via this command line:

PROXY="socks://127.0.0.1:1080"
PROXYCMD="--proxy-server=http=$PROXY;https=$PROXY"

GTK2_RC_FILES=$HOME/.gtk2chrome \
dbus-launch $HOME/bin/chrome-linux/chrome-wrapper \
  --enable-compact-navigation \
  --enable-plugins \
  $PROXYCMD \
  "$@"

Looks like a Qt bug then.

**Comment by The-Compiler** [comment]
More like a Chromium bug :wink:

**Comment by slackhead** [comment]
Opened an issue on their bug tracker. I can't post the link because I flagged it as a security issue and according to their bug tracker they aren't publically accessible.

**Comment by slackhead** [comment]
Well, I renamed my ~/.config/chromium directory and it seems like it's fixed for both Qutebrowser /and/ Chromium. I'm getting some incoming packets killed, but it seems like nothing is trying to bypass the proxy.

I'm wondering if there's a way of keeping the 3rd party code in qtwebengine from accessing settings etc. meant for the real Chromium browser? It doesn't seem like it should be allowed and should be sandboxed.

Here's a link to the chromium bug page : 

https://bugs.chromium.org/p/chromium/issues/detail?id=860308

**Comment by The-Compiler** [comment]
Probably hard to say without knowing what exactly gets read from there.

**Comment by slackhead** [comment]
I was looking in the wrong log. After removing chromium dir nothing has changed.
