### ISSUE TITLE
Qutebrowser 1.4.0 fails to load /usr/bin/libGLESv2.so

### ISSUE THREAD

**Issue by maxice8** [qutebrowser/qutebrowser#4043]
Don't ask me why it is trying to open in /usr/bin and not in /usr/lib

qutebrowser v1.4.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.6
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: LibreSSL 2.7.4

Style: QFusionStyle
Platform: Linux-4.17.3_1-x86_64-with-glibc2.3.4, 64bit
Linux distribution: void (void)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/terran/var/cache/qutebrowser
config: /home/terran/etc/qutebrowser
data: /home/terran/var/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 0:00:00

Error:

```
$ qutebrowser
[29203:29230:0704/153620.932354:ERROR:gl_implementation.cc(246)] Failed to load /usr/bin/libGLESv2.so: /usr/bin/libGLESv2.so: cannot open shared object file: No such file or directory
[29203:29230:0704/153621.471039:ERROR:gl_surface_qt.cpp(701)] Requested OpenGL implementation is not supported. Implementation: 0
Received signal 11 SEGV_MAPERR 000000000002
```

**Comment by The-Compiler** [comment]
This is a bug in Qt which was fixed in Qt 5.11: [QTBUG-65682](https://bugreports.qt.io/browse/QTBUG-65682). As a workaround, you should be able to symlink the two paths.
