### ISSUE TITLE
Gitlab login throws chrome-error://chromewebdata/ with u2f enabled

### ISSUE THREAD

**Issue by twouters** [qutebrowser/qutebrowser#4049]
After enabling a u2f device on a local Gitlab instance qutebrowser redirects to chrome-error://chromewebdata/ after login (but before 2fa authentication).

This is not reproducible on gitlab.com, but I've been able to reproduce it on Debian's gitlab instance:

## Steps to reproduce

- register a guest account on https://signup.salsa.debian.org/register/guest/
- login on https://salsa.debian.org/users/sign_in and enable 2FA in account settings
- logout/login and notice that this still works as expected
- login using chromium or another u2f enabled browser and add your u2f device in account settings
- logout/login will work in firefox and chromium - probably others too - but at least qutebrowser fails.
- remove the u2f device from 2FA to be able to login again

## version info

```
qutebrowser v1.4.0
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.17.3-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by toofar** [comment]
I think this is https://bugreports.qt.io/browse/QTBUG-54720

**Comment by twouters** [comment]
This is not a request to support u2f/fido

**Comment by twouters** [comment]
This used to work - prior to qt 5.11 I think.

**Comment by toofar** [comment]
Oh, great. Any chance you could try to reproduce with falkon?

**Comment by The-Compiler** [comment]
I'm guessing the page tries to open an URL with a custom scheme (say, `fido://` or `u2f://` or whatever?), and then [QTBUG-63378](https://bugreports.qt.io/browse/QTBUG-63378) happens. qutebrowser has a workaround which prevents the infinite loading loop, but there's not anything more it can do.

**Comment by twouters** [comment]
As far as I could tell, there's an extension being loaded in the background using chrome-extension:// url.
It's weird that this issue doesn't happen on gitlab.com though...

**Comment by twouters** [comment]
Haven't checked the details yet, but it might be an option to do register a noop extension handler for chrome-extension:// urls?

**Comment by twouters** [comment]
fyi - falkon enters the dreaded infinite loading loop

**Comment by The-Compiler** [comment]
I'm not sure if that would change anything - but can you please try this?

```patch
diff --git a/qutebrowser/browser/webengine/webenginequtescheme.py b/qutebrowser/browser/webengine/webenginequtescheme.py
index 12ab6af31..2434a8889 100644
--- a/qutebrowser/browser/webengine/webenginequtescheme.py
+++ b/qutebrowser/browser/webengine/webenginequtescheme.py
@@ -37,6 +37,7 @@ class QuteSchemeHandler(QWebEngineUrlSchemeHandler):
         if qtutils.version_check('5.11', compiled=False):
             # WORKAROUND for https://bugreports.qt.io/browse/QTBUG-63378
             profile.installUrlSchemeHandler(b'chrome-error', self)
+            profile.installUrlSchemeHandler(b'chrome-extension', self)
 
     def requestStarted(self, job):
         """Handle a request for a qute: scheme.
@@ -49,7 +50,7 @@ class QuteSchemeHandler(QWebEngineUrlSchemeHandler):
         """
         url = job.requestUrl()
 
-        if url.scheme() == 'chrome-error':
+        if url.scheme() in ['chrome-error', 'chrome-extension']:
             # WORKAROUND for https://bugreports.qt.io/browse/QTBUG-63378
             job.fail(QWebEngineUrlRequestJob.UrlInvalid)
             return
```

**Comment by The-Compiler** [comment]
Nice, didn't think of that! I commited it.

**Comment by twouters** [comment]
:+1:
