### ISSUE TITLE
Display HTTP error reason on error pages

### ISSUE THREAD

**Issue by blueyed** [qutebrowser/qutebrowser#4056]
Currently with a response like "HTTP/1.1 503 Service Unavailable: Back-end server is at capacity" you will only see:

```
This page isn’t working
example.com is currently unable to handle this request.
HTTP ERROR 503
```

It would be very nice it the reason (after the code) could be displayed, preferably in an additional line, and maybe with a `Reason: ` prefix.

This is often used to provide additional information, which is useful in general - even it would be just the default (e.g. "Not Found" for 404s).

**Comment by The-Compiler** [comment]
Those error pages are coming from Chromium.

**Comment by blueyed** [comment]
And there is no way to override / extend them?
Or do you think it makes sense to take this upstream?

**Comment by The-Compiler** [comment]
> And there is no way to override / extend them?

No, see e.g. [QTBUG-61100](https://bugreports.qt.io/browse/QTBUG-61100).

> Or do you think it makes sense to take this upstream?

I suppose you could open a Chromium issue, but I doubt it'd gain much traction.
