### ISSUE TITLE
Bookmark syncing options

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#4057]
Hello guys,
what are you using for syncing your qutebrowser's bookmarks/quickmarks with something like an android app?
I've done some research and found that most (all?) of the server apps only have desktop clients that work as plugins of chromium or firefox.
Am I missing something?

**Comment by The-Compiler** [comment]
I don't think anyone has built something for that so far - also see #3188, #485 and #30.

**Comment by rpietro** [comment]
@aleprovencio probably not what you have in mind, but I use stow and git to version the quickmarks file. You could also save it to dropbox.

**Comment by aleprovencio** [comment]
You're correct @rpietro. Since I don't keep as many bookmarks, the solution I've found is to make a startpage, shared on nextcloud so it works on all my devices. Nevertheless, I still think it would be nice having something that syncs with floccus,  nextcloud bookmarks, etc. The "bomb" though is somehow also sync the quickmark name with Firefox's keyword bookmarks, so I'm able to use them on the mobile for instance.

**Comment by dotMavriQ** [comment]
I agree with aleprovencio, qutebrowser would be my go to if only I could sync bookmarks with my nextcloud.

**Comment by mickmattes** [comment]
The nextcloud bookmark plugin has a [REST Api](https://github.com/nextcloud/bookmarks/blob/master/API.md)
So writing a script to send bookmarks to it should not be too hard
Also, if you use one of the [third party apps](https://github.com/nextcloud/bookmarks#third-party-clients) for Android, you have your beloved bookmarks across devices...

**Comment by mickmattes** [comment]
Just in case someone is interested, I created a keybind `,m` (book**m**ark) which executes the following command:
```
jseval javascript:var win = window; var doc = document; var title = encodeURIComponent(doc.title); var location = encodeURIComponent(doc.location); var left = ((win.screenX || win.screenLeft) + 10); var top = ((win.screenY || win.screenTop) + 10); var endp = 'https://<insert-your-server-url-here>/index.php/apps/bookmarks/bookmarklet?output=popup&url=' + location + '&title=' + title; var specs = 'left=' + left + ',top=' + top + ',height=500px,width=550px,resizable=1,alwaysRaised=1'; var command = win.open(endp, 'bkmk_popup', specs); win.setTimeout(function() { command.focus() }, 300);
```
Install the _bookmark_ plugin for nextcloud and replace `<insert-your-server-url-here>` with your server URL and it should work. At least it does for me ;-)

Additionally I have installed the app "Nextcloud bookmarks" on Android. It is for free, if you install it via _f-droid_.
