### ISSUE TITLE
Qute-lastpass script doesn't work on google forms, for one

### ISSUE THREAD

**Issue by andrea-berling** [qutebrowser/qutebrowser#4058]
The qute-lastpass script doesn't insert the password in the right field in many forms. The most notable I've had this problem with are the Google login and the EA login page (reached from the Battlefield 3 Battlelog). I think the problem lies in the method with which the password and email are entered: according to the USAGE comment in the script it works by simulating the insertion of the username in a text field (the first one it finds?), then the pressing of the tab button to switch to the password field followed by the insertion of the password. I get that this can work on websites like Github, where the login page contains only the username and the password text fields, but it doesn't work anymore on websites with more than those text fields, like on a site where the login is done from the main page where there is also a search text field, or where those fields appear at different points in time, like with Google's login. If i may suggest a fix I would recommend that instead of using this method the username and password insertion should be done by manipulating the DOM elements of the page themselves.
I wanna say though that even if this is not yet perfect I still appreciate the work behind it and I'm very grateful to the writer of the lastpass userscript for making my browsing life a little more convenient.

**Comment by The-Compiler** [comment]
cc @welps

**Comment by welps** [comment]
I'll see if I can handle this request this weekend, thanks.

**Comment by andrea-berling** [comment]
I wrote a "fix" myself, I'll probably upload it as a pull request tomorrow. Still having some issues with JS though

**Comment by The-Compiler** [comment]
Like explained in #4071, I'll look for a proper solution for this once it's possible to write password fill scripts via the extension API, also see #180.
