### ISSUE TITLE
Settings help webpage seems to have been down for several days

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4064]
I seem unable to reach https://www.qutebrowser.org/doc/help/settings.html for some reason (error message `ERR_NAME_NOT_RESOLVED`).

Not sure if it is down for maintenance or another issue or if I am doing something wrong, but I thought that I would mention it, in case.

**Comment by The-Compiler** [comment]
That's odd - I switched domain providers a few days ago, so I suppose this somehow broke it for you, but I don't understand why.

Can you show the output of `dig www.qutebrowser.org A` please?

**Comment by prosoitos** [comment]
```
; <<>> DiG 9.13.0 <<>> www.qutebrowser.org A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35246
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.qutebrowser.org.		IN	A

;; AUTHORITY SECTION:
qutebrowser.org.	517	IN	SOA	ns.inwx.de. hostmaster.inwx.de. 2018071102 10800 3600 604800 3600

;; Query time: 1 msec
;; SERVER: 142.58.98.5#53(142.58.98.5)
;; WHEN: Thu Jul 12 14:08:40 PDT 2018
;; MSG SIZE  rcvd: 105
```

**Comment by prosoitos** [comment]
mmm... weird.

If I type in the address or follow the link, it doesn't work. If I type in part of the address (e.g.  https://www.qutebrowser.org/doc/help), it doesn't work either.

But if I google qutebrowser, then click on `help`  I can get to that partial address. However, it breaks down when I click on "Documentation of settings".

These inconsistencies and the fact that you just changed provider are reassuring: it might just need a bit of time before fully working.

**Comment by The-Compiler** [comment]
It shouldn't need longer than 72h or so though, and it's been roughly two weeks. Does https://blog.qutebrowser.org/ work for you? If so, can you show `dig blog.qutebrowser.org A` as well?

**Comment by prosoitos** [comment]
Yes, it does work.

```
; <<>> DiG 9.13.0 <<>> blog.qutebrowser.org A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60463
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 11

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;blog.qutebrowser.org.		IN	A

;; ANSWER SECTION:
blog.qutebrowser.org.	887	IN	A	94.23.58.104

;; AUTHORITY SECTION:
qutebrowser.org.	490	IN	NS	ns.inwx.de.
qutebrowser.org.	490	IN	NS	ns5.inwx.net.
qutebrowser.org.	490	IN	NS	ns2.inwx.de.
qutebrowser.org.	490	IN	NS	ns4.inwx.com.
qutebrowser.org.	490	IN	NS	ns3.inwx.eu.

;; ADDITIONAL SECTION:
ns.inwx.de.		274	IN	A	192.174.68.104
ns.inwx.de.		274	IN	AAAA	2001:67c:1bc::104
ns2.inwx.de.		274	IN	A	176.97.158.104
ns2.inwx.de.		274	IN	AAAA	2001:67c:10b8::104
ns5.inwx.net.		107	IN	A	108.59.8.65
ns5.inwx.net.		107	IN	AAAA	2604:9a00:2010:a013:1::1
ns3.inwx.eu.		107	IN	A	46.165.212.97
ns3.inwx.eu.		107	IN	AAAA	2a00:c98:2100:a006:3::1
ns4.inwx.com.		333	IN	A	95.211.1.145
ns4.inwx.com.		333	IN	AAAA	2001:1af8:4400:a048:1::1

;; Query time: 2 msec
;; SERVER: 142.58.98.5#53(142.58.98.5)
;; WHEN: Thu Jul 12 14:17:43 PDT 2018
;; MSG SIZE  rcvd: 404
```

**Comment by prosoitos** [comment]
Oh, and now, I can get to the settings page with the clicking path I described above and which was previously not working. I tried this yesterday and earlier today and it broke down each time before reaching the settings page. So now, I can finally get to where I wanted to, but it is a tortuous way.

I still can not get to that page (nor to the main help page) directly by following the full link or typing in the full address.

**Comment by The-Compiler** [comment]
Hmm, interesting! I can actually reproduce the issue when asking Google's DNS service (`dig www.qutebrowser.org A @8.8.8.8`. I'll try adding an explicit `www.` record, though I don't understand why it's needed (I'd expect it to be covered by `*.qutebrowser.org`)

**Comment by The-Compiler** [comment]
I've added that now, let me know if it helps! At least with 8.8.8.8 it seems to work now. I also contacted the hoster's support, because I don't understand why it's needed.

FWIW, you should also be able to view that help locally with `:help`.

**Comment by prosoitos** [comment]
Yup :slightly_smiling_face: It works!

Thank you!!!

**Comment by prosoitos** [comment]
> FWIW, you should also be able to view that help locally with :help.

Oh! I hadn't realized that. This is great! Thanks for the tip! (I have to go to the settings page every now and then to remind myself of some keybindings that I don't use frequently and haven't remapped).

**Comment by The-Compiler** [comment]
`:help bindings.default` should take you right there, and note that you also can see the keybinding for commands in the command completion. Good to hear that things work now!
