### ISSUE TITLE
Google Login to clockify.me doesn't work anymore

### ISSUE THREAD

**Issue by th3voic3** [qutebrowser/qutebrowser#4066]
Hi,

recently the login to clockify.me/login via Google stopped working.
I get redirected to the Google Login page in a new tab, Login, the tab closes and then nothing.
In console output with temp-basedir it only says that a WebDialog was requested, but that it's unsupported.

qutebrowser v1.4.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QGtkStyle
Platform: Linux-4.17.5-1-ck-broadwell-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Comment by The-Compiler** [comment]
Does it work when you start with `--temp-basedir`? Does `:set content.cookies.accept all` make any difference?

**Comment by th3voic3** [comment]
`:set content.cookies.accept all` did it

**Comment by The-Compiler** [comment]
Looks like that needs access to cross-origin cookies then. Third party cookies are filtered by default with qutebrowser v1.4 and Qt 5.11.
