### ISSUE TITLE
[macOS] hide_decoration makes window nonresizable

### ISSUE THREAD

**Issue by koekeishiya** [qutebrowser/qutebrowser#4067]
As mentioned in my comment in #3750, there has been a regression with the `window.hide_decoration` option on macOS. The original functionality would let the titlebar be hidden and still have the browser window be resizable.

In v1.4.0 and later, the titlebar is removed as intended, but the window can no longer be resized.
The last working version was v1.3.3. This appears to have been the result of some change in Qt.

Version Info:
```
qutebrowser v1.4.1
Git commit: 75d153d6d (2018-07-11 17:16:50 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.11
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: Secure Transport, macOS 10.14

Style: QWindowsStyle
Platform: Darwin-18.0.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.14, x86_64
```

**Comment by The-Compiler** [comment]
I can't see any difference on KDE FWIW.

**Comment by The-Compiler** [comment]
https://codereview.qt-project.org/#/c/221493/ looks like the culprit:

> Cocoa: Restore resizable window mask setting to 5.9 behavior
> 
> This should be tied to the CustomizeWindowHint flag:
> if that flag is set we start out without NSResizableWindowMask
> and possibly add it later on if WindowMaximizeButtonHint
> is set.

So I guess we just need to set the `Qt.WindowMaximizeButtonHint` [flag](http://doc.qt.io/qt-5/qt.html#WindowType-enum) (and possibly other buttons as well?) for it to work again?

**Comment by rien333** [comment]
> So I guess we just need to set the Qt.WindowMaximizeButtonHint flag (and possibly other buttons as well?) for it to work again?

That seems to have been the intention, but in practice this (and many other combinations) never achieved the desired effect of a resizable window with it's decoration hidden. I believe that this is caused by the fact that there is not further check for `Qt.WindowMaximizeButtonHint` in the function that handles `NSWindow` flags in the [diff](https://codereview.qt-project.org/#/c/221493/3/src/plugins/platforms/cocoa/qcocoawindow.mm) corresponding to the commit message you mention. However, such a check _is_ made on the more recent [Qt github]():
```C
NSUInteger QCocoaWindow::windowStyleMask(Qt::WindowFlags flags) {
...
const bool resizeable = !(flags & Qt::CustomizeWindowHint); // Remove zoom button by disabling resize
// Select base window type. Note that the value of NSBorderlessWindowMask is 0.
NSUInteger styleMask = (frameless || !resizeable) ? NSBorderlessWindowMask : NSResizableWindowMask;
...
if (flags & Qt::WindowMaximizeButtonHint)
    styleMask |= NSResizableWindowMask;
```

So could this be an oversight in Qt? (I have a different theory as well but this seems to be more likely)

**Comment by The-Compiler** [comment]
That seems to be https://codereview.qt-project.org/#/c/232846/ which will make it to Qt 5.11.2. So probably not much we can do other than waiting for that?

**Comment by rien333** [comment]
Probably, yes. One way around is special native macOS window creation code as in for example the [Qt "TrueFramelessWindow"](https://github.com/dfct/TrueFramelessWindow/blob/master/winnativewindow.cpp) project, but might  involve quite some code for this specific case, although maybe someone more knowledgeable in Qt(/c++?) can make it manageable for our purposes. I'm going to have a little try at it because basically the only thing that needs to be done is setting the `NSResizableWindowMask` flag, but waiting also seems like an okay solution.

**Comment by The-Compiler** [comment]
Maybe that can be done via [PyObjC](https://pypi.org/project/pyobjc/) somehow. FWIW any solution that requires qutebrowser compiling native C++ or Objective C code is not acceptable I'm afraid.

**Comment by koekeishiya** [comment]
Probably have to wait til they fix this in Qt (5.11.2?). To set the required flag, you need to be able to access the underlaying *NSWindow* object. I haven't used Qt so I have no idea if they have a way of exposing the underlaying window object, but I doubt that they do.

What you really want to have happen in the end, is the following line:
```
    NSWindow *window = (NSWindow *) w; // get this from somewhere
    [window setStyleMask: [window styleMask] | NSWindowStyleMaskResizable];
```

**Comment by The-Compiler** [comment]
There's [QWidget::winId](https://doc.qt.io/qt-5/qwidget.html#winId) - not sure how to get a `NSWindow` from that though.

**Comment by koekeishiya** [comment]
I took a quick look at the project @rien333 referenced above, and they seem to do the following:

```
    NSView *nativeView = reinterpret_cast<NSView *>(winid);
    NSWindow* nativeWindow = [nativeView window];
```

Where *winid* is from:

```
    // On OS X / Linux, the widget can handle everything itself so just create Widget as normal
    Widget w;
    w.winId();
```

and *Widget* is defined as:

```
class Widget : public QMainWindow
```

Not sure if any of this helps, but either way you would probably need a bridge to some Cocoa (objc compiled) function that does this operation. I understand if you want to wait for a Qt update to sort this out.

**Comment by brorbw** [comment]
Is there a fix for this yet?

**Comment by The-Compiler** [comment]
@brorbw No, which is why the issue is still open.

**Comment by brorbw** [comment]
Alright. Someone might have found at temporary fix for this issue. 
@koekeishiya this is, however not the only program where I have experinced this behaviour. Disableing the titlebar(window decoration) in the Helium browser for macOS, yeilds the same problem, the window is moveable, but not scaleable with chunkwm. Which leads me to believe that this isn't entirely the fault of Qt or qutebrowser.

**Comment by rien333** [comment]
@brorbw older versions (e.g. 1.3.0) hide the titlebar just fine, so given the above discussion this is almost certainly a Qt issue.

**Comment by Kwask94** [comment]
:( I'm having the same problem

**Comment by The-Compiler** [comment]
qutebrowser v1.5.0 is now out, which bundles PyQt 5.11.3 and Qt 5.11.2. How do things look there?

**Comment by brorbw** [comment]
No, the issue is still present.

**Comment by brorbw** [comment]
I can add that the window is completely ignored by chunkwm @koekeishiya

**Comment by koekeishiya** [comment]
@The-Compiler With that version the titlebar is no longer hidden;  the minimize and close buttons are greyed out however. Window can be moved and resized.

**Comment by The-Compiler** [comment]
I suspected as much - we're back to square one then, I have no idea how to create a resizable window without a titlebar.

**Comment by kklot** [comment]
v1.6.0 on Mac cannot resize as well, movable with [Spectacle](https://github.com/eczarny/spectacle) app.

**Comment by spangenberg** [comment]
> v1.6.0 on Mac cannot resize as well, movable with [Spectacle](https://github.com/eczarny/spectacle) app.

Same with v1.6.1

**Comment by koekeishiya** [comment]
Issue is still relevant in v1.6.3. Can be moved through the accessibility API, but not resized.

**Comment by RichardWLaub** [comment]
Running into this on v1.7.0 when trying to manage with [yabai](https://github.com/koekeishiya/yabai).

**Comment by a2u** [comment]
Same with v1.10.1. 
Does not work with [yabai](https://github.com/koekeishiya/yabai).

**Comment by johnnypea** [comment]
Still doesn't work with v1.12.0 :(.

**Comment by Nokodoko** [comment]
2020 (the year we wish we could all skip over), issue is still present (tested with Caitlina w/ yabai).

**Comment by rien333** [comment]
Complaining here isn't likely to achieve all that much. When this issue first arose, it was because of a change in Qt, iirc. If you really  want to get this fixed, someone has to contact the Qt project about this. For hints on what sort of changes to request to the Qt peeps, see the original PR (https://github.com/qutebrowser/qutebrowser/pull/3750) and the comments at the start of this thread.

**Comment by Nokodoko** [comment]
Hello and thanks for the response! Certainly wasn't my intention to come
across as complaining, more necro-bumping and confirming that the window
management with decorations off is still an issue.

I also appreciate you pointing me in the direction of the original PR. I
will admit that I did read it prior to posting, but did not take the
initiative to follow through with reaching out to the QT team. I'm working
on that now (happy to contribute in any way I can, as Qutebroswer is an
amazing project!).

Best!

**Comment by rien333** [comment]
No problem, and thanks for helping look into this issue. I was just hoping to point out that from what I remember, Qt was more or less the source of this problem.

**Comment by d-miketa** [comment]
@Nokodoko, have you been able to make any progress?

**Comment by The-Compiler** [comment]
The v2.2.0 release sets `NSRequiresAquaSystemAppearance = False` in `Info.plist`. @ftpd mentioned that the `hide_decoration` option doesn't work at all anymore since then - can someone confirm?

**Comment by d-miketa** [comment]
> The v2.2.0 release sets `NSRequiresAquaSystemAppearance = False` in `Info.plist`. @ftpd mentioned that the `hide_decoration` option doesn't work at all anymore since then - can someone confirm?

Works for me on MacOS 11.2.1, apart from the bug covered throughout this thread.

**Comment by BR00l** [comment]
Hello, and sorry for the bumping, but do we have any info if this will be fixed soon?
I cant stand the decoration when tiling with yabai, makes me sad.

**Comment by The-Compiler** [comment]
No news so far. This is a regression in Qt, and it's unclear whether qutebrowser even can fix it in a non-hackish way. I'm afraid I'm not really familiar with macOS stuff at all and don't use macOS as a daily driver myself, so this isn't exactly on the top of my priorities.

**Comment by BR00l** [comment]
Oh well, I guess I ll have to try the hackish road. Thank you for the blazing fast reply.

**Comment by Nokodoko** [comment]
Hello, I took a step away from all things programming for a while (so I missed this note). At the moment I no longer have a mac machine and will need to get catilina running in a vm or a hackintosh in order to re-check if this is a long standing issue (apologies for the necro-bump as well)

**Comment by ejiek** [comment]
@Nokodoko I do have an intel powered mac machine but almost no Qt & qutebrowser development experience.
We can get on a jitsi call for example for you not go into a hustle of running macOS in a VM.

**Comment by BR00l** [comment]
Sorry for bumping this, but I just wanna ask ... there is no hope anymore, is it ?

**Comment by The-Compiler** [comment]
@BR00l depends on whether someone with the appropriate macOS knowledge picks it up. We can't predict the future.

**Comment by The-Compiler** [comment]
Good news, finally:

- This got fixed in Qt 6.3: [macOS: Handle window titlebar buttons independently from style mask (I2c1a9564) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/371279)
- I now also merged a workaround (thanks @ktprograms!) for older Qt versions

I don't plan on including this in v2.5.3 due to the added dependency, and there won't be a v2.6.0 most likely - however, you can try the `qt6-v2` branch with the Qt fix in it, see #7202 for details.

**Comment by najjt** [comment]
Sorry if this is not the appropriate place to write this, but I am having a little trouble with hiding window decorations on macOS. I am new to qutebrowser so there could be something I've missed, but I am having the same problem that the OP had when I set `window.hide_decoration = True`. 

Version Info:

```
qutebrowser v3.1.0
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

CPython: 3.12.0
PyQt: 6.6.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.17.2
yaml: 6.0.1
adblock: 0.6.0
objc: 10.0
PyQt6.QtWebEngineCore: 6.6.0
PyQt6.sip: 6.7.12
pdf.js: 4.0.269 (bundled)
sqlite: 3.44.0
QtNetwork SSL: OpenSSL 3.0.11 19 Sep 2023

Style: QMacStyle
Platform plugin: cocoa
OpenGL: Apple, 2.1 Metal - 88
Platform: macOS-14.2.1-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/Frameworks/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/Frameworks/PyQt6/Qt6/libexec, data path: /Applications/qutebrowser.app/Contents/Frameworks/PyQt6/Qt6
OS Version: 14.2.1, x86_64
```

**Comment by The-Compiler** [comment]
Tentatively reopening given the above comment. Won't be able to test on macOS 14 any time soon though, so it'd be good to hear if anyone has the same problem still.

**Comment by reedjosh** [comment]
@The-Compiler 

Re:

> Tentatively reopening given the above comment. Won't be able to test on macOS 14 any time soon though, so it'd be good to hear if anyone has the same problem still.

I am still seeing this issue in macOS 14.

**Comment by koekeishiya** [comment]
I consider this issue to be resolved, as the original problem of the NSWindow stylemask being set incorrectly is fixed and the yabai workaround is a common case for software on macOS.
