### ISSUE TITLE
open-editor command doesn't work for some text fields

### ISSUE THREAD

**Issue by phealeyh** [qutebrowser/qutebrowser#4068]
qutebrowser version: 1.4.0

Problem:

Hi,

There are a few text fields that I seem to not be able to write to. For example, when I try to open-editor on the 'edit file' section of my file within a git repo, it doesn't let me write any text to it.

![2018-07-14-003524_1277x652_scrot](https://user-images.githubusercontent.com/8462246/42697230-e6da4cf6-86fd-11e8-90a7-73b07dd126db.png)

Here is the associated c.editor.command variable within config.py:
![2018-07-14-003701_660x78_scrot](https://user-images.githubusercontent.com/8462246/42697377-4cdbc0fc-86fe-11e8-80eb-918c98910daa.png)

**Comment by The-Compiler** [comment]
Merging this into #2215 as it's probably the same underlying issue.
