### ISSUE TITLE
Open/Close tabs is slow when many tabs are open

### ISSUE THREAD

**Issue by Ram-Z** [qutebrowser/qutebrowser#4069]
The more tabs are open the slower it gets to open/close new tabs, especially at the beginning of the tablist.

Steps to reproduce:
1. Open many tabs: `$ qutebrowser -T $(seq 50)`
2. Go to tab 1: `:buffer 1`
3. Delete it: `d`

The same goes when opening a new tab at that position with `tabs.new_position = next`.

Opening and closing tabs at the end of the list remains fast, however many tabs are open. I suppose the tablist is saved in a contiguous sequence container that needs to move all subsequent elements when one is added or removed in the middle.

http://paste.the-compiler.org/view/869eccb3

**Comment by jgkamat** [comment]
Hi,

I'm actually semi-actively working on this even though I don't think there was
an issue for it, I'm going to submit a PR that helps with this with extreme
amounts of tabs (~200).

Your situation might be different though, so could you submit a profile?

You should be able to get one by running the "./scripts/dev/run_profile.py"
script, and submitting the "callgraph file" which is placed in the temporary
directory. Ideally, you would submit the callgraph after repeating slow
actions, to help us find what parts of the code are slow.

Right now, I think that the config system is the slowest part of the path for
that amount of tabs, and I have a couple of ways of fixing it.

1. Add a cached_val object to the config variable, which automatically caches
it: https://github.com/jgkamat/qutebrowser/tree/jay/configcache-perf
2. Optimize the config system itself. I don't think this is actually worth it,
this is the only situation I think it's going to matter in.
3. Create a new object which is just a wrapper around a simple dict, which
highly used code paths can use to query cached versions. This isn't part of
the config system at all, and so it can be very simple and has little chances
of causing other problems.
4. Cache config values "manually" by storing them as variables, and updating
those variables on config change.

I personally really like #3, even though I have something done for #1 already.
@The-Compiler, could you pick one of the solutions above (or propose a
different one)? Once that's done, I can start writing polished patch to fix
this.

Also see https://github.com/qutebrowser/qutebrowser/pull/3582 for the previous
attempt of this.

Ram-Z writes:

> The more tabs are open the slower it gets to open/close new tabs, especially at the beginning of the tablist.
>
> Steps to reproduce:
> 1. Open many tabs: `$ qutebrowser -T $(seq 50)`
> 2. Go to tab 1: `:buffer 1`
> 3. Delete it: `d`
>
> The same goes when opening a new tab at that position with `tabs.new_position = next`.
>
> Opening and closing tabs at the end of the list remains fast, however many tabs are open. I suppose the tablist is saved in a contiguous sequence container that needs to move all subsequent elements when one is added or removed in the middle.
>
> http://paste.the-compiler.org/view/869eccb3
>
>

**Comment by Ram-Z** [comment]
Here's a link to the callgraph profile: https://rmz.io/i/qutebrowser_callgraph.profile

I opened a new instance of qutebrowser with 50 tabs through the profiler, then went to tab 1 and closed every tab.

**Comment by jgkamat** [comment]
For you, it seems like config is the main bottleneck to me, so I'll work on a way to cache config values once we make a decsion from the above.

![2018-07-14-094637_916x773_scrot](https://user-images.githubusercontent.com/4349709/42724999-6f5b89aa-876c-11e8-9c0a-008dd3da2c93.png)

**Comment by noctuid** [comment]
I have this issue with more like 20-30+ tabs; IIRC some other functionality slows down, and qutebrowser becomes basically unusable. I'm guessing the issue is the same for me, but I can trying profiling things at some point as well.

**Comment by jgkamat** [comment]
A profile would be very helpful, just to see if your issue is different than the one I'm seeing. If that's too much work for some reason, you could try out the [half-finished branch I made](https://github.com/jgkamat/qutebrowser/tree/jay/pinned-statistics-cache), which should have similar performance to implementing config caching properly, and see if that "solves" the issue.

**Comment by jgkamat** [comment]
Let me know if anyone still sees performance issues with tabs on master (and tell me what you were doing, number of tabs, etc). 

Right now, the only slowdown I see is when closing tabs with low number indexes (because every tab needs to have it's title updated). I might take a look at that as well, but the situation should be a lot better than it was a while ago :)
