### ISSUE TITLE
How to paste into text fields?

### ISSUE THREAD

**Issue by mschenck0** [qutebrowser/qutebrowser#4077]
I'm probably missing something, but after I've yanked a url, how can I paste it into a textfield?

**Comment by The-Compiler** [comment]
Like (almost) everywhere else:

- If it's in primary selection, middle click or shift-insert (in insert mode)
- If it's in the clipboard, ctrl-v (in insert mode)

**Comment by mschenck0** [comment]
Thanks.

**Comment by rpietro** [comment]
@mschenck0 my solution is a bit unorthodox: I switched the keys so that it can be more vim-like, so that I get into insert mode with i and back into normal mode with esc, also releasing ctrl-v so that it can paste under any mode.

**Comment by The-Compiler** [comment]
>  I switched the keys so that it can be more vim-like, so that I get into insert mode with i and back into normal mode with esc

Huh? Those are default bindings :wink:
