### ISSUE TITLE
Part of the page visible on screen changes when window's width is changed

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#4079]
I don't think this is a bug.

I often open a terminal while I'm surfing on the web (for instance because I want to rewrite on the terminal a command I'm reading on StackOverflow) and, since I use i3wm, what happens is that the terminal takes the right half the screen and qutebrowser window is left with the left half of the screen. **All this is ok, since I use a big screen, I hate the mouse, and so on.**

The "problem" is that the percentage relative to the part on the web page displayed on screen is not hold fixed, so the portion of displayed page is changed if the webpage wraps the text depending on the width of the window (e.g. Wikipedia).

One possibility would be to keep fixed the first line displayed on screen.

**Comment by The-Compiler** [comment]
This is the same from Chromium, and QtWebEngine (and thus qutebrowser) inherits that behaviour from there.

**Comment by The-Compiler** [comment]
I'm not saying it shouldn't be changed - but qutebrowser can't do so, it'd have to be changed in Chromium and then trickle down to qutebrowser (via QtWebEngine). qutebrowser doesn't do any drawing of websites itself.

**Comment by jgkamat** [comment]
I think it could be possible to hack this in with qb through js and listening to window size changes, but I agree it would be a lot better to have it implemented properly in chromium. This bugs me too fwiw
