### ISSUE TITLE
The ability to change audio/mute tab widget content

### ISSUE THREAD

**Issue by nemanjan00** [qutebrowser/qutebrowser#4088]
![2018-07-21-213617_414x150_scrot](https://user-images.githubusercontent.com/448151/43039466-32db67bc-8d2e-11e8-83e5-b6f3225bf43b.png)

It would be great to be able to change this. 

I made my changes by editing the code and using custom font.

**Comment by The-Compiler** [comment]
#1578 will make that possible - no plans to make it customizable before that.
