### ISSUE TITLE
Completly black screen on Void LInux after system update

### ISSUE THREAD

**Issue by krinistof** [qutebrowser/qutebrowser#4093]
Hi!
I use Void Linux now for a while and I updated the system via `xbps-install -Su`
This wasn't the first time I done this. Before the update it worked flawlessly, withount any problem.
Now if I start the program, it only outputs warnings about:

    11:10:35 WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-krinistof'
    11:10:35 WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-krinistof'

But those aren't so dramatic. They are the same as before when it worked.

The window appears, but that is. It is a black square without anything in it.
As I try to interact with it it respondes the same. On the console it outputs errors, and as i tested it makes all of it's job.

The funny thing is if I run it with sudo it works. (as well as now i write this from it :thinking: )
And as sudo it outputs the same warnings on the console.

For debuging:

	qutebrowser v1.4.1
	Git commit: 
	Backend: QtWebEngine (Chromium 61.0.3163.140)
	
	CPython: 3.6.6
	Qt: 5.10.1
	PyQt: 5.10.1
	
	sip: 4.19.8
	colorama: no
	pypeg2: 2.15
	jinja2: 2.10
	pygments: 2.2.0
	yaml: 3.12
	cssutils: no
	attr: 18.1.0
	PyQt5.QtWebEngineWidgets: yes
	PyQt5.QtWebKitWidgets: no
	pdf.js: no
	sqlite: 3.24.0
	QtNetwork SSL: LibreSSL 2.7.4
	
	Style: QFusionStyle
	Platform: Linux-4.17.9_1-x86_64-with-glibc2.3.4, 64bit
	Linux distribution: void (void)
	Frozen: False
	Imported from /usr/lib/python3.6/site-packages/qutebrowser
	Using Python from /usr/bin/python3
	Qt library executable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5
	
	Paths:
	cache: /home/krinistof/.cache/qutebrowser
	config: /home/krinistof/.config/qutebrowser
	data: /home/krinistof/.local/share/qutebrowser
	runtime: /tmp/runtime-krinistof/qutebrowser
	
	Uptime: 0:00:00

**Comment by The-Compiler** [comment]
See https://github.com/void-linux/void-packages/issues/1033

**Comment by krinistof** [comment]
Thanks for so fast respose and help! :grin:
