### ISSUE TITLE
Getting current scroll percentage in userscript

### ISSUE THREAD

**Issue by Jumblemuddle** [qutebrowser/qutebrowser#4095]
Is there a way to get the current scroll percentage in a userscript?
I'm trying to write some incremental reading tools, and I need to be able to save the current position on a page and return to it later.

I can return with
```
#!/usr/bin/env bash
echo "later 500 scroll-to-perc 50" >> $QUTE_FIFO
```
The `later 500` isn't ideal. Is there a way to run a command when the page is loaded?
I'm calling `qutebrowser $URL `:spawn --userscript $userscript` for my 'return to position', so the page isn't loaded completely when the script is run.

Having the ability to read the current percentage is needed for this to work. Perhaps there's another way to retrieve current information other than the environment variables? Something to pass to `$QUTE_FIFO`?

**Comment by The-Compiler** [comment]
> I need to be able to save the current position on a page and return to it later.

That sounds a lot like `:set-mark` and `:jump-mark` :wink:

> Is there a way to run a command when the page is loaded?

No. Things like that will be possible with a proper Python plugin API (#30), but I'd rather not shoehorn them into userscripts.

**Comment by Jumblemuddle** [comment]
Thanks! I clearly wasn't looking hard enough. Marks are persistent across
sessions then?

**Comment by The-Compiler** [comment]
No, they aren't persisted.
