### ISSUE TITLE
[[Hack]]  Creating a cross-window/tab set of jump-marks

### ISSUE THREAD

**Issue by m2habert** [qutebrowser/qutebrowser#4098]
(this is not an issue per se, but I thought it could be referenced as a tip or concept for further discussion/help.)

 I'm always lost buried in a mess of windows and tabs that always seems to outgrow any organization scheme I come up with, so any mark/memory/ref resource is a bonus.

qB's present mark/jump list feature comes in handy for reading, but my main issue is "loosing tabs", therefore a cross-window solution would be more helpful.

I tinkered a bit with the :bind command and found out that:
                                                                                        
    config.bind('m∀', 'set-cmd-text :bind `∀ set-cmd-text :buffer ')

 (where '∀' is 'any char)... does work, i.e. : that one could bind a char to bind a second char to a ":buffer {string}" command.

In other words, if I want to mark a page, lets say, a "github alot issues" page... I could type <ma> and type "alot issues" + <CR> and qB would nicely bind '\`a' to ":buffer alot issues". Then, wanting to easily jump back to "¿where the hell is that issues page?", all I'd need to do would be to type "`a" + [return] .

So, choosing "w" and "," as my alternatives "m" and '`' respectively, I proceeded to update my config with 26 "config.bind" lines, one for each letter of the alphabet. This ends up beeing great for 2 reasons:

1) for the very specific, like the example used above;

2) and for the generic, like marking <,y> to ":buffer youtu" (as I probably have an youtube page somewhere waiting for a leisure time in which I can finally watch those videos I've searched and don't even remember what the subject was about anymore)

And, the best of it all, when you press ",", qB nicely shows up ALL your jump marks (see pic).

![image](https://user-images.githubusercontent.com/7454005/43368672-39228ba0-9337-11e8-9050-4bf847d42d0a.png)

**Comment by The-Compiler** [comment]
I'm going to close this, as it's not an issue, like you say :wink: FWIW for the future, the subreddit or mailinglist are probably better places for this kind of thing.
