### ISSUE TITLE
Lots of duplicate URLs in history.sqlite

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#4099]
I'm not sure what's the right place for the report — sqlite or qutebrowser.

On "cold start" of qutebrowser, pressing <kbd>O</kbd> *(aka `open -t`)*, then typing, results in some-seconds freeze. I figured it has something to do with history being loaded from the disk, so I checked the file, and sure enough, its size is 22MiB. Grepping a url string shows there's a lot of duplicates in the database, it's likely the reason it's so bloated.

# Steps to reproduce:

1. In qutebrowser, execute `https://duckduckgo.com/?q=test`, then close it.
2. Repeat step 1 once more.
3. Close qutebrowser so it would dump the history on disk.
4. execute in terminal

		$ strings ~/.local/share/qutebrowser/history.sqlite | grep -e 'https://duckduckgo.com/?q=test'

# Expected:

No more than one line in result *(possibly none at all if the string is stored as a trie data structure)*

# Actual

Multiple `https://duckduckgo.com/?q=test` lines in the output.

--------

qutebrowser --version:

```
ATTENTION: default value of option vblank_mode overridden by environment.
qutebrowser v1.4.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: Breeze::Style
Platform: Linux-4.17.9-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/constantine/.cache/qutebrowser
config: /home/constantine/.config/qutebrowser
data: /home/constantine/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

**Comment by The-Compiler** [comment]
If you visit a site multiple times, it's going to be in the history multiple times, that's intended.

You also can't just really inspect it using `strings` - there are things like indices for that table (which speeds up things). Doesn't mean that the whole data is read from disk all at once (it's not).

**Comment by Hi-Angel** [comment]
You could store the time of the visit for every url instead of a whole url thingy. Some urls take really a lot of space. Look at this one for example: `https://www.google.ru/search?ei=AsNZW9rXDcWd6AS-5p-wBQ&q=+undefined+symbol%3A+_nss_mymachines_initgroups_dyn&oq=+undefined+symbol%3A+_nss_mymachines_initgroups_dyn&gs_l=psy-ab.3...6240.15749.0.16635.3.3.0.0.0.0.116.298.1j2.3.0....0...1c.1.64.psy-ab..0.1.104...35i39k1.0.NHyDenn3ltw`.

**Comment by The-Compiler** [comment]
Which then makes it very expensive to build the history in the format it's needed, which makes things slower rather than faster again.

**Comment by jgkamat** [comment]
We might be able to "preload" the database into memory to fix the lag on the
first usage (moving the loading to the start of qb rather than after the
completion is opened), but I'm not sure if that would be worth the effort.

**Comment by Hi-Angel** [comment]
> We might be able to "preload" the database into memory to fix the lag on the
first usage (moving the loading to the start of qb rather than after the
completion is opened)

It would just move the lag from one place to another, i.e. it would boot longer.

**Comment by Hi-Angel** [comment]
Trick: my `history.sqlite` was 77M in size, and I just reduced it to 67M by simply running rebuild on the database. To do it, execute:

```
 λ sqlite3 history.sqlite                   
SQLite version 3.34.0 2020-12-01 16:14:00
Enter ".help" for usage hints.
sqlite> VACUUM;
```
…and press ^D when it finishes.
