### ISSUE TITLE
bookmark all tabs, bookmaks export

### ISSUE THREAD

**Issue by p-r-y-l** [qutebrowser/qutebrowser#4104]
also try to add support for gesture with roller mouse, clickpad, and nipple button laptops

**Comment by The-Compiler** [comment]
> bookmark all tabs

That sounds like you'd want to use sessions instead.

> bookmaks export

It's a plaintext file.

> also try to add support for gesture with roller mouse, clickpad, and nipple button laptops

I have no idea what you mean exactly. Mouse gestures? Might be possible as a plugin at some point, but it's not something I'd like in the core given that qutebrowser's focus is on the keyboard.
