### ISSUE TITLE
Most bizarre typing issue in Twitter

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4108]
Disclaimer: this may not be a problem in qutebrowser. I honestly have no clue where the problem might be.

On occasions (rarely on Facebook and commonly on Tweeter), while I am in insert mode and typing, letters are sent to the beginning of the line (instead of being inserted at the cursor's position) or flipped around with the cursor moving backward.

**Comment by The-Compiler** [comment]
Weird! The only thing coming to mind is that Unicode has some... interesting special characters such as [U+202E](https://www.fileformat.info/info/unicode/char/202e/index.htm) (right-to-left-override) which when typed/pasted, changes the writing direction.

Is it possible that you somehow accidentally type/paste that character before that happens?

Relevant [XKCD](https://xkcd.com/1137/):

![image](https://user-images.githubusercontent.com/625793/43662090-face99d4-9764-11e8-890c-6cdef4a851e5.png)

**Comment by prosoitos** [comment]
Mmm... if this is not a known problem in qutebrowser, I must indeed do something. This never happens on GitHub or other sites though.

I don't think this is it, but how can I type or insert that unicode character??

**Comment by The-Compiler** [comment]
Nope, this is the first time I've heard of it, and I use Twitter (which I assume you meant?) in qutebrowser myself.

I have no idea how to type it (especially accidentally) - it's just the only thing I can think of so far... You can copy it from http://www.unicode-symbol.com/u/202E.html though (funnily enough, it also reverses the page title :laughing:).

**Comment by prosoitos** [comment]
Euh, yes, right, Twitter :stuck_out_tongue: 

Mmm... ok. I guess I will close the issue. Whatever I am doing seems to have nothing to do with qutebrowser...

**Comment by The-Compiler** [comment]
Let me know if you ever find out though! Interesting issue for sure...

**Comment by jgkamat** [comment]
This is probably not going to help too much, but I haven't seen this at all in
qb, and I use Facebook quite regularly. I don't use twitter myself though.

That said, I don't have any non-english fonts or tools installed, so maybe
it's related to that in some way? Sorry for not being more helpful...

Marie-Helene Burle writes:

**Comment by The-Compiler** [comment]
Another shot in the dark: Do you have some Greasemonkey script in `~/.local/share/qutebrowser/greasemonkey/` which could be causing this? Or any special input method (something like fcitx, or an on-screen keyboard)?

**Comment by prosoitos** [comment]
Still no improvement on this front. Letters jumping all over the place whenever I type in Twitter (and nowhere else) :disappointed: I set up a new machine and same problem (but very similar setup, so I guess, not all that surprising).

I have a silly question which will make the process of writing tweets a little less awkward: I know how to launch an editor, but how do I insert the text back on the webpage? I couldn't find the keybinding for this in the help pages, so I usually copy, then paste.

Thank you!

**Comment by prosoitos** [comment]
Indeed. It works very well here. Not working on Twitter though (for me). Not sure what is going on on Twitter, but it is hard for me to write anything on that site :laughing:

**Comment by prosoitos** [comment]
I am reopening this now as it might be a similar sort of problem than #4600 and #4579 (though, I realize that this might be a QtWebEngine and not a qutebrowser issue).

**Comment by prosoitos** [comment]
Actually, following the comments on those other issues, I added `'insert': {'<Ctrl-a>': 'nop',}` to my previous code, so that I now have:

```py
c.bindings.commands = {
    'normal': {'<tab>': 'nop',},
    'insert': {'<tab>': 'nop',},
    'insert': {'<Ctrl-a>': 'nop',}
}
```

and it *seems* that the problem is also resolved!

**Comment by prosoitos** [comment]
What is puzzling me (though it is great) is that while the crazy unwanted jumping to the start of the line seems to have stopped, I can jump at the start of the line, in insert-mode, with `<Ctrl>-a`.

Will close this and the other 2 issues after a little more testing.

Though, those are obviously workarounds and there is still something going on with QtWebEngine and my WM sending those keys when it shouldn't.

**Comment by prosoitos** [comment]
Actually, out of curiosity, I tried with only the first line and it works just as well. It doesn't make sense at all, but

```py
c.bindings.commands = {
    'normal': {'<tab>': 'nop',}
}
```

is sufficient to solve the problem.

Anyway, even if it is still very unclear what is going on, the workaround does the trip, so I am closing this for now.
