### ISSUE TITLE
Question:  Qutebrowser's necessary fonts

### ISSUE THREAD

**Issue by vinnyA3** [qutebrowser/qutebrowser#4110]
Are there specific fonts that Qutebrowser needs to run?  The reason I ask:  I switched linux distros yesterday, then proceeded to install Qutebrowser.  Here, I noticed that the *xorg-fonts* package was needed--without it, Qutebrowser crashed on startup.

The *xorg-fonts* package comes with a bunch of fonts that I don't necessarily need, so can I forgo installing it by only using a select few font packages?

---

**qutebrowser version**:  1.4.1

**Comment by The-Compiler** [comment]
qutebrowser itself doesn't have any font handling, so that crash probably happened somewhere inside QtWebEngine/Chromium. No clue what it needs precisely, I suppose it just needs to find *some* font.

**Comment by jgkamat** [comment]
FWIW, when I install qb on a really fresh machine, I usually install terminus
(the default font for the interface) and liberation (for the webview). I think
I do remember getting crashes if no fonts were installed at all, so
The-Compiler is probably correct on that.

**Comment by vinnyA3** [comment]
Hmm, I'll hunt down those fonts when I get the chance.  Not a big deal, was just curious really.  Thanks for the input @The-Compiler @jgkamat

**Comment by The-Compiler** [comment]
Yay, this issue just helped me to get the tests for Qt 5.10 to run again on Travis, which randomly broke at some point (#4055). There (Ubuntu), installing `ttf-dejavu-core` didn't help, but installing `xfonts-base` now did the trick! Qt 5.11 (and also 5.7.1 and 5.9) seems to work fine without that, though...

**Comment by vinnyA3** [comment]
That's great!  I kind of feel like I contributed something :smile: .  For me, installing the core dejavu package solved the font issue (xfonts-base isn't in the main Void Linux repos).

**Comment by The-Compiler** [comment]
Just found a related Qt issue: https://bugreports.qt.io/browse/QTBUG-51772

**Comment by The-Compiler** [comment]
Huh, and now it started failing again on Travis... :confused: Weird!

**Comment by vinnyA3** [comment]
That's weird.  Why would the tests randomly break ?  :thinking: I'm glad it works from a user perspective though
