### ISSUE TITLE
multiple tabs open from a single page

### ISSUE THREAD

**Issue by rpietro** [qutebrowser/qutebrowser#4111]
The answer is probably obvious but I am new to qutebrowser and couldn't find it anywhere: is there a way to keep the focus on one tab while you open links on multiple tabs (wihout moving the focus to those tabs). This is different from "F," where the focus changes to the new tab. 

In surfingkeys this is achieved through "cf" but I don't know how to get this to work in qutebrowser. 

Btw, the project is absolutely phenomenal, thanks for working on this.

**Comment by The-Compiler** [comment]
`F` respects the `tabs.background` setting, but you can also use `;b` to force background tabs, or `;r` for rapid hinting (which doesn't leave hint mode after following a hint).
