### ISSUE TITLE
importer.py may fail on chrome bookmarks import

### ISSUE THREAD

**Issue by jZhangTk** [qutebrowser/qutebrowser#4114]
The importer.py failed on me at `assert 'type' in bm, bm` (currently line# 336). The reason being is there's an entry `"sync_transaction_version": "186"` in my chrome bookmarks, which is a string and doesn't have the `type` key.

I have a simple fix for it - adding `if isinstance(bm, dict):` before asserting type in bm, like
```
        def bm_tree_walk(bm, template):
            """Recursive function to walk through bookmarks."""
            if isinstance(bm, dict):
                assert 'type' in bm, bm
                if bm['type'] == 'url':
                    if urllib.parse.urlparse(bm['url']).scheme != 'chrome':
                        print(template.format(**bm))
                elif bm['type'] == 'folder':
                    for child in bm['children']:
                        bm_tree_walk(child, template)
```
(I'm not a Python developer. Let me know if this makes sense)

**Comment by The-Compiler** [comment]
This looks right the right fix! However, I usually like to exit early for error conditions, i.e. something like:

```python
if not isinstance(bm, dict):
    return
```

Do you want to open a PR with that, or should I just apply it directly?

cc @ryan-farley who implemented this, though I suppose `sync_transaction_version` didn't exist back then.

**Comment by jZhangTk** [comment]
I can create a PR, though this is my first time contributing to a public repo. Is there guide line I should follow? (I have done a lot of development on bitbucket private repos, but never contribute to gibhub public repo)

**Comment by mschilli87** [comment]
@jZhangTk: I guess your experience will do. Check the [contribution guide](https://www.qutebrowser.org/doc/contributing.html) for some helpful advice.
