### ISSUE TITLE
[BUG] 1.41 Windows standalone release crashes when attempting downloads.

### ISSUE THREAD

**Issue by ykhurshid** [qutebrowser/qutebrowser#4116]
I tried downloading from Github twice and also a hint mode download command.

Here is my version information
https://paste.the-compiler.org/view/ff226852

**Comment by The-Compiler** [comment]
"crashes" how exactly?

**Comment by ykhurshid** [comment]
It closes the browser window and brings up the crash dialog. I have reported the logs.

**Comment by The-Compiler** [comment]
Looking at the reports, this happens because you tell it to download to `D:\` which (I think?) doesn't exist. Then qutebrowser crashes when trying to create it, because of #2570.

**Comment by ykhurshid** [comment]
I just attempted the 1.40 standalone release and same story.
I believe qutebrowser is making an assumption about what directory I am allowed to download to. I am in a public library for some much needed context.

I believe the download prompt is trying to first switch to the C directory and since I am not allowed access to that, it is crashing.

**Comment by The-Compiler** [comment]
I missed this bit:

> The download location prompt never shows up.

Looking at the log more closely, it seems like Qt detects `D:\` as default download directory, and then tries to create it (and fails), despite it already existing. As a workaround, you should be able to set `downloads.location.directory` to something else (a folder somewhere).

Still, merging this into #2570 as many of the logs there look similar to yours.

**Comment by ykhurshid** [comment]
That worked! Thanks for the workaround. :smile:

**Comment by The-Compiler** [comment]
Thanks for pointing me into the right direction so I found out what's actually causing this :wink: Should be fixed now for v1.5.0.
