### ISSUE TITLE
Can we replace `mapfile` in password_fill?

### ISSUE THREAD

**Issue by jZhangTk** [qutebrowser/qutebrowser#4121]
In userscript `password_fill`, it uses `mapfile` (at line# 315 right now).
```
mapfile -t files < <(printf '%s\n' "${files[@]}" | sort | uniq )
```

Since `mapfile` doesn't work on Mac, can we replace it with something else like
```
while IFS= read -r line; do
    file+=("$line")
done < <(printf '%s\n' "${files[@]}" | sort | uniq )
```

And I noticed it was using `files`, but it is not referenced anywhere afterward, so I think it should be `file`. Let me know if I missed anything.

(I can create a PR for the change. Please let me know if the change is good.)

**Comment by The-Compiler** [comment]
Fun, looks like macOS 10.11 (El Capitan) has an ancient bash 3.2.57 from 2007... :worried: 

I think that change looks fine, but I don't understand why it'd need to be `file` - there are multiple files in that array after all.

cc @t-wissmann

**Comment by jZhangTk** [comment]
Yeah, Mac still uses ancient bash... 🤷‍♂️ 

I think here is trying to remove duplicates, so singular should make sense. And When I tried `files` (in my modified code), it didn't fill anything. As soon as I changed it to `file`, it started to work.

**Comment by t-wissmann** [comment]
I think the change itself looks fine, but I can't guarantee for anything... I mean there are reasons why bash introduced mapfile at some point.

The mapfile here removes duplicate files form the files array. And yes, one should accumulate them in the array `files` and that array needs to be emptied. So I assume the correct code snipped is:
```
{
files=( )
while IFS= read -r line; do
    files+=("$line")
done
} < <(printf '%s\n' "${files[@]}" | sort | uniq )
```
And a quick test with ```files=( a a b c d d d efg )``` looks positive.

**Comment by jZhangTk** [comment]
Ah, yeah, once I empty `files`, it started to work with files.

I also tried to install bash 4.4.23 (through homebrew). It comes with `mapfile` now.

However, I still get the same error (line 315: mapfile: command not found) when I run the script inside qutebrowser.

Even with
```
#!/usr/bin/env -S PATH="${PATH}:/usr/local/bin" bash
```
it still can't recognize `mapfile` (it solved lpass not found though). Any idea?

**Comment by jgkamat** [comment]
JZ writes:

> However, I still get the same error (line 315: mapfile: command not found) when I run the script inside qutebrowser.

This is because mac os mangles your system path in GUI apps.

> Even with
>
> #!/usr/bin/env -S PATH="${PATH}:/usr/local/bin" bash
>
> it still can't recognize mapfile (it solved lpass not found though). Any idea?

This won't help because the updated bash is probably not in /usr/local/bin,
it's probably wherever homebrew put it.

Easy fix is to run it from a terminal, but the proper one is to fix Mac OS
path inheritance from .profile.

**Comment by jZhangTk** [comment]
This solved the issue (with the order switch, the new bash finally takes the control)
```
#!/usr/bin/env -S PATH="/usr/local/bin:${PATH}" bash
```

Though I tried many different things with .profile, .launchd.conf, /etc/paths to set PATH (I prefer fixing in this way), none of them worked for me. @jgkamat do you have any idea or reference that I can check out?

**Comment by jgkamat** [comment]
Afaik, the gui env does not inherit from .profile (which is standard) on mac, instead you have to edit a different XML file. I haven't tried this myself but this is all the info I could find.

https://serverfault.com/a/16736

On August 10, 2018 8:08:30 AM PDT, JZ <notifications@github.com> wrote:
>This solved the issue (with the order switch, the new bash finally
>takes the control)
>```
>#!/usr/bin/env -S PATH="/usr/local/bin:${PATH}" bash
>```
>
>Though I tried many different things with .profile, .launchd.conf,
>/etc/paths to set PATH (I prefer fixing in this way), none of them
>worked for me. @jgkamat do you have any idea or reference that I can
>check out?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jZhangTk** [comment]
Thanks @jgkamat . That method seems to be outdated, though I finally found a way. Running the command below solved my issue.
```
sudo launchctl config user path $PATH
```

I think we can close this issue now.
