### ISSUE TITLE
Using :set with a config.py overwrites old autoconfig.yml

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4124]
From IRC:

- Have a autoconfig with user changes.
- Not be using a config.py
- Qutebrowser is open

- Create config.py with infomation from theme repo (+clone repo into config folder)- https://github.com/evannagle/qutebrowser-dracula-theme
  - *Does not contain*:  config.load_autoconfig()

- Restart Qutebrowser
  - Theme is 'active'
  - autoconfig is not read, user settings are not loaded

- Use the :set command - (tabs.position) 
  - autoconfig is overwritten with blank user settings + the setting for tabs.position

**Comment by Jan-PieterBaert** [comment]
what kind of solution would you like here?

**Comment by The-Compiler** [comment]
Good question... Let's first check what possible solutions we can think of! I can think of a couple which would also prevent confusion about `autoconfig.yml` files not being loaded, which is still something that occurs from time to time despite all the changes we (well, mostly you!) have made to prevent that.

- Require a `config.py` to always explicitly say `config.load_autoconfig(False)` if it doesn't want to load `autoconfig.yml`. If neither `config.load_autoconfig()` (with an argument defaulting to `True`) nor `config.load_autoconfig(False)` is called, *don't* load the autoconfig (for backwards compatibility) but issue a config error (which will not prevent qutebrowser from starting, but be annoying enough so people fix it and take a conscious decision.
- Show an error when `:set` and friends are used (without `-t`) and `autoconfig.yml` is not loaded. Might be the most "natural" one, but is a bit cumbersome for people who don't use `autoconfig.yml` and just use `:set` for temporary settings. Also there's no solution for `:bind` because no `:bind -t` exists.

Alternatively, if we'd really just want to prevent this issue, we'd somehow need to load the `autoconfig.yml` values but not apply them, just so they can be saved properly later. But this makes things even more intricate than they already are (with `config.py` settings, `autoconfig.yml` settings and temporary settings), so I'd really rather not do that.

Any opinions/comments?

**Comment by The-Compiler** [comment]
Ah, of course there's another one:

- Don't write to `autoconfig.yml` if it hasn't been loaded

but then you can get into scenarios where people use `:set` and such (and possibly spend a lot of time configuring things) only to discover their changes didn't actually get saved because they happened to have a `config.py` lying around - so I don't think this is a good idea.

**Comment by andrewcarlotti** [comment]
How about combining that las suggest with a new config setting:
- If `autoconfig.yml` hasn't been loaded, then don't write to it. Additionally, show a warning to the user unless `warn_no_autoconfig` is set to `False` - e.g. `Warning: autoconfig.yml has not been loaded, so this setting change will not be saved. To disable these warnings, set warn_no_autoconfig=False`.

**Comment by Jan-PieterBaert** [comment]
@andrewcarlotti the warning could also be disabled by loading the autoconfig, right?

**Comment by andrewcarlotti** [comment]
Yes - the "if `autoconfig.yml` hasn't been loaded" was intended to apply to the second sentence too.

**Comment by Jan-PieterBaert** [comment]
Yes, that sounds good, and I presume the default for that config option is `True`

**Comment by Jan-PieterBaert** [comment]
I'll open a PR for this

**Comment by The-Compiler** [comment]
Sorry for the somewhat late answer, but I don't understand the benefit of having a config option instead of my initially proposed `config.load_autoconfig(False)` for this - it seems to me that it'd only be confusing, as you can't set it via `:set` because it'll be temporary, so it won't actually help with getting rid of the error message. Also it adds a new config option rather than using an (IMHO) very natural extension of a function we already have.

**Comment by Jan-PieterBaert** [comment]
I think I read past your initial proposal, but that one does seem better, I'll rewrite and open a pr for `config.load_autoconfig(False)`

**Comment by andrewcarlotti** [comment]
I was considering the case where someone might not want to reload config.py mid-sessions but wants to hide the warnings straight away. That's a fairly narrow case though, and hiding the warnings in this one case is sufficiently unimportant that I now think it wouldn't be worth adding another way to silence them.

**Comment by Pelerin88** [comment]
Hi there form the future :) It's 2026 and the problem is still here and I still get this PR on web search.

So what's the deal: I have set `config.load_autoconfig(False)` as I want to use Python-only approach. But the `autoconfig.yml` is still generated automatically when I call `:set`. So I just need to disable its generation and that is what helped me:

``` python
# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)
# Makes autoconfig.yml immutable so no changes are written on :set
from qutebrowser.config import configfiles
configfiles.YamlConfig._mark_changed = lambda self: None
```
---

As for discussion above here are my thoughts:

Writing `autoconfig.yml` is totally pointless when the file is not being used/loaded...

The fact the `:set` command automatically writes the file means it does more than it's supposed to do - the classic "functions with side effects" problem. That means when I call `set` I expect it **only** sets the value in current runtime, at least by default (though it might have an option `-w` to write the file for convenience).

So when I need to write my changes to the disk then I'd like to have a separate command like `:config-[write|save]`.

Thus if I don't want to use `autoconfig.yml` I could just skip loading it and never save.

**Comment by Pelerin88** [comment]
@The-Compiler kindly notification ⤴️

**Comment by The-Compiler** [comment]
The ping is completely uncalled for (I obviously am subscribed to the repo), and this only coming up again 6 years later tells me there isn't a real problem here.
