### ISSUE TITLE
Private mode data isn't cleared after private windows are closed

### ISSUE THREAD

**Issue by HiTuX** [qutebrowser/qutebrowser#4125]
Usualy, I open my email in private mode `open -p gmail.com`, so no password will be stored. 

What I expect from a private mode is that all session information (history, commands, cache, passwords, ....) will not be saved OR will be cleared after closing "private windows".  However, I noticed that qutebrowser did not clear passwords and cache of private mode if it is in not totally closed (close all tabs and windows private and non-pivate). If there are non-private windows openend, after closing only private windows, I can get to my mail `open -p gmail.com` without reentring username and password ;( !!!!!!!!!

```
qutebrowser v1.4.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: Qt5CTProxyStyle
Platform: Linux-4.14.56-1-lts-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Artix Linux (unknown)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Artix
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Artix"

--- /etc/os-release ---
NAME="Artix"
PRETTY_NAME="Artix Linux"
ID=artix
ID_LIKE=artixlinux

Paths:
cache: /home/hk/.cache/qutebrowser
config: /home/hk/.config/qutebrowser
data: /home/hk/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 19:28:23
```

**Comment by The-Compiler** [comment]
Looking at Chromium, incognito mode data is shared between multiple incognito windows, but indeed is cleared as soon as all of those are closed.

Not sure yet to what extend we can clear that data - it might be sufficient to use a different `QWebEngineProfile` object for the private profile once all existing windows are closed.
