### ISSUE TITLE
Qutebrowser is broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by notthebee** [qutebrowser/qutebrowser#4135]
Hi. I decided to check out the new LTS version of Ubuntu, but unfortunately the qutebrowser package from the official repos does not work: it crashes upon launching. [Here's the full traceback](https://pastebin.com/R8100DiN)

I will appreciate any feedback.

**Comment by The-Compiler** [comment]
You're running KDE neon and not Ubuntu 18.04. KDE neon isn't intended as a general-purpose Linux distribution, and software which isn't part of KDE isn't supported by them. This happens because it ships an old qutebrowser version (from Ubuntu) but a much newer Qt version.

**Comment by notthebee** [comment]
I see. Thank you for the awesome browser by the way!

**Comment by ipstone** [comment]
I kept havng issues running qutebrowser on ubuntu 18.04, I am running default ubuntu. I kept having: ```qutebrowser
08:01:06 WARNING: WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail.
Segmentation fault (core dumped)```

**Comment by jgkamat** [comment]
Isaac Pei writes:

> I kept havng issues running qutebrowser on ubuntu 18.04, I am running default ubuntu. I kept having: qutebrowser 08:01:06 WARNING: WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail. Segmentation fault (core
> dumped)

See qutebrowser/qutebrowser#2932, probably you're running wayland on a very
old qt that won't support it.
