### ISSUE TITLE
Update list of similar projects in the README

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4141]
Looks like some projects which were active aren't anymore - also see e.g. https://github.com/lusakasa/saka-key/issues/171

**Comment by The-Compiler** [comment]
Also might want to add [webmacs](https://github.com/parkouss/webmacs) and [Next](https://github.com/next-browser/next) (though I still hear the latter is rather buggy, apparently?)

**Comment by clp** [comment]
I will look into this issue as a first contribution to an outstanding project.
The saka-key project might still be seeking a maintainer; but it does have a recent fix merged in July, so I would not call it Inactive yet.
I will check the projects listed in the README.
The two projects mentioned in the above comment seem appropriate to add to the Active list.
