### ISSUE TITLE
[Windows] Webpages that should be displayed as HTML are downloaded instead

### ISSUE THREAD

**Issue by jcjordyn130** [qutebrowser/qutebrowser#4142]
I'm on Windows 10 x64 1803, using qutebrowser v1.4.1 from git commit 75d153d6d (downloaded from the releases), and I'm using the qtwebengine 65.0.3325.230 backend.

I only have this problem on windows, FreeBSD and Linux both don't exhibit the problem.

What happens is that randomly webpages that should be displayed as HTML are downloaded.

**Comment by The-Compiler** [comment]
Do you have an example?

**Comment by The-Compiler** [comment]
Can you do `:report` after it happens so I can take a look at the logs?

**Comment by jcjordyn130** [comment]
I tried to report it but the reporter failed with a abrupt closed connection, so here: https://privatebin.net/?7c9fe248e19d632e#W2AypDeBG9OCQna/4StFiixsnXZ8ST+8xEaa0zui09M=

**Comment by jcjordyn130** [comment]
Just note it took a while to get it to happen

**Comment by The-Compiler** [comment]
Reports should be fixed. Not sure what's going on there. I can see the download getting started, but that's coming from QtWebEngine. Any chance you can check whether you run into similar issues with [Falkon](https://www.falkon.org/) as well?

**Comment by jcjordyn130** [comment]
To answer your question, this happens with falkon as well.

**Comment by The-Compiler** [comment]
Yeah, this is a QtWebEngine issue then. One more thing to try would be whether it happens in Google Chrome as well... Either way, nothing qutebrowser can do here. This is the first time I hear about an issue like that FWIW.
