### ISSUE TITLE
Web app does not work

### ISSUE THREAD

**Issue by rpietro** [qutebrowser/qutebrowser#4145]
This is more of a curiosity than a request for a feature: why doesn't  the [enhance](https://www.enhance.computer/) site work?

**Comment by The-Compiler** [comment]
Their JS does this:

```javascript
$(() => {
	var isChrome = !!window.chrome && !!window.chrome.webstore
	if (!isChrome) {
		$('body').html(
			'Sorry, your browser is not supported for <i>ENHANCE.COMPUTER</i>. Try again using desktop Chrome.'
		)
		window.pause()
	} else {
		socket.emit('new game')
		reset()
	}
})
```

(funnily enough, `window.pause()` doesn't seem to exist on any browser...)

**Comment by The-Compiler** [comment]
I hoped to be able to trick it using GreaseMonkey:

```javascript
// ==UserScript==
// @name enhance
// @run-at document-start
// @match https://www.enhance.computer/
// ==/UserScript==
console.log("Hello World?");
window.chrome = {webstore: true};
```

but that doesn't seem to work either - maybe `document-start` is too early and `document-end` is too late? @toofar do you have an idea why that doesn't work?

**Comment by toofar** [comment]
You can try using `unsafeWindow`[0] instead of `window`. Also add an `// @grant unsafeWindow` line to the metadata (not that we require it...).

[0] https://wiki.greasespot.net/UnsafeWindow

**Comment by The-Compiler** [comment]
Hah, yep, dumping this into `~/.local/share/qutebrowser/greasemonkey/enhance.user.js` seems to make it start at least:

```js
// ==UserScript==
// @name enhance
// @run-at document-start
// @match https://www.enhance.computer/
// @grant unsafeWindow
// ==/UserScript==
unsafeWindow.chrome = {webstore: true};
```
