### ISSUE TITLE
Slow startup compared to chrome based browsers, safari, firefox etc

### ISSUE THREAD

**Issue by bbtdev** [qutebrowser/qutebrowser#4149]
On MacOS every browser opens instantly, except qutebrowser ( about 4 seconds). Of course, it sounds like a first world problem, but when you are used to everything being snappy, you notice it.

Is this something can be improved or desire to improve?

**My specs:** 2,2 GHz Intel Core i7, 16 GB 1600 MHz DDR3, SSD, Retina
**qutebrowser version:**
qutebrowser v1.4.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

Chrome opens instantly (firefox, safari as well), no daemons, I made two videos, chrome app is closed, I show the activity monitor to prove it.

1.How fast chrome opens and how fast qutebrowsers opens:
https://im5.ezgif.com/tmp/ezgif-5-884c977c97.gif

2. I open qutebrowser, then I open chrome, chrome loads first:
https://im5.ezgif.com/tmp/ezgif-5-8a8f6f13b5.gif

startup profile:
https://i.imgur.com/3uwvwMy.png
https://filebin.net/xecercs5cuoxu11u

**Comment by jgkamat** [comment]
Another issue (not sure if it's related or not), is that `config.bind` seems to be very slow. This is probaby related to copying dicts (that was the bottleneck when I was investigating the tab performance issues, before I decided we should probably just cache the values completely).

```
<Padawan> you are right, the more config.binds i uncomment the more it slows down
```

**Comment by The-Compiler** [comment]
See #2967 and #153 - don't think we need another issue for this, even if there are likely multiple factors contributing to a slow startup.
