### ISSUE TITLE
Disabling sound completely on qutebrowser ?

### ISSUE THREAD

**Issue by edi9999** [qutebrowser/qutebrowser#4154]
Hello, I would like to know if it is possible through the config to disable sound completely either on all windows or just a given domain ?

It would be useful to me as some sites have some annoying sounds, and I would even prefer my browser not to make any sound.

**Comment by The-Compiler** [comment]
`:tab-mute` / `<Alt-m>` does so if your Qt version supports it.

**Comment by The-Compiler** [comment]
Hmm, reconsidering this, it might make sense to be able to disable sound for a given domain via a setting.

**Comment by jgkamat** [comment]
Maybe this could go under #3636? Either way, I think this would be pretty easy to add.

**Comment by The-Compiler** [comment]
I don't think this fits in with #3636 as the stuff there is mostly related to [QWebEngineUrlRequestInterceptor](https://doc.qt.io/qt-5/qwebengineurlrequestinterceptor.html), while this would just be a per-url setting to mute a page.

**Comment by cauimsouza** [comment]
Can somebody give me some pointers on where to start and also which file should I be looking at to work on it? This would be my first contribution.

**Comment by The-Compiler** [comment]
@cauimsouza The main place to look at is the `WebEngineAudio` class in `browser/webengine/webenginetab.py`:

https://github.com/qutebrowser/qutebrowser/blob/59e7adc1e622e1d439073b629b648b0bbaa375c6/qutebrowser/browser/webengine/webenginetab.py#L633-L652

You'll need to change `AbstractAudio` in `browser/browsertab.py` so it takes the `tab` object as first argument, similar to how other classes do (and adjust the places where `AbstractAudio`, `WebKitAudio` and `WebEngineAudio` are created accordingly).

Then you should be able to do something like `self.url_changed.connect(self._on_url_changed)` in `WebEngineAudio._connect_signals`, and add a `_on_url_changed` method which gets the value from the config via `config.instance.get('content.mute', url=url)` or so.

Finally, add an entry for the new setting in the [configdata.yml](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/config/configdata.yml) file and you should be good to go!

Hope that helps, if you run into trouble, I suggest you join our [IRC channel](https://github.com/qutebrowser/qutebrowser#getting-help) where people are happy to help!

**Comment by cauimsouza** [comment]
Thank you, @The-Compiler ! I'll start working on this.
