### ISSUE TITLE
[bug] when I try open some links by using "f" or ";b", qutebrowser not only open the links and do some other actions

### ISSUE THREAD

**Issue by supremew** [qutebrowser/qutebrowser#4157]
version :+1: 
qutebrowser v1.4.1
Git commit: 2d54cdaec (2018-08-23 21:31:21 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.5
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.0.2n  7 Dec 2017

example: 
there is a link which has a "abd" hint in "https://news.baidu.com", I type the "abd", qutebrowser may close the current tab. sometimes, it will close more tabs; 
I set the "hints.chars" to "ehjklzx", will have a nicer user experience , but qutebrowser still do some unexpected actions.

Sorry, my English is too bad. I hope you can understand what I mean.

**Comment by supremew** [comment]
Ok, I try it.

**Comment by supremew** [comment]
[log.txt](https://github.com/qutebrowser/qutebrowser/files/2320319/log.txt)
I do the ":report" command, qutebrowser is crashed. so I paste it here.

**Comment by The-Compiler** [comment]
The log shows that there was another `d` keypress after `fd` which closed the tab. Do you maybe have a very fast key repetition delay configured or something? You might want to set `hints.auto_follow_timeout` which ignores keypresses for a given delay after a hint is followed.

I don't think there's any qutebrowser issue here - either there's something on your system actually generating two keypresses, or it's some kind of Qt bug (but this is the first time I hear about something like this).
