### ISSUE TITLE
Dead link in FAQ pointing to stacktrace guide

### ISSUE THREAD

**Issue by clp** [qutebrowser/qutebrowser#4158]
qutebrowser v1.4.1
Git commit: 65ca15e (2018-08-21 11:48:16 -0700)
Backend: QtWebEngine (Chromium 61.0.3163.140)

In FAQ doc here:
https://qutebrowser.org/doc/faq.html
The **Troubleshooting:My issue is not listed** section (near bottom of file) has a link called 'guide' that points to this URL:
	https://qutebrowser.org/doc/doc/stacktrace.html
That link responds w/ a 404 error.

This URL, with only one 'doc/' in the path, responds with **Getting stacktraces on crashes**:
	https://qutebrowser.org/doc/stacktrace.html

Notes.
The qutebrowser/doc/faq.asciidoc source file specifies the link w/ this code:
	`link:stacktrace.asciidoc[guide]`
and I guess that it is inserting two 'doc/' elements in the path.

Saw this problem in FAQ page at qb web site, and at github.

**Comment by bitraid** [comment]
The code in `doc/faq.asciidoc` has changed in 2d54cda, but as you can see in my comments there, i still find the link in `:help` broken.

**Comment by The-Compiler** [comment]
Fixed in #4202 - thanks @bengartner!
