### ISSUE TITLE
Opening multiple pages based on a single search engine

### ISSUE THREAD

**Issue by rpietro** [qutebrowser/qutebrowser#4160]
I currently have the following lines in my config.py, one for each of the italian, american, french and german kindle stores. this works, but would it be possible to create a script where I add one set of terms (say the author's name) and then I get one tab for each search run on each of the countries?

```
'kindle': 'http://www.amazon.com/s/ref=nb_sb_noss_2?rh=n%3A133140011%2Ck%3Ahello&keywords={}',
'kindle.fr': 'https://www.amazon.fr/s/ref=nb_sb_noss?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Ddigital-text&field-keywords=hello&rh=n%3A672108031%2Ck%3A[]',
'kindle.de': 'https://www.amazon.de/s/ref=nb_sb_noss_2?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Ddigital-text&field-keywords=[]',
'kindle.it': 'https://www.amazon.it/s?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Ddigital-text&field-keywords=[]',
```

**Comment by The-Compiler** [comment]
You could write a [userscript](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc) which sends four `:open` commands to qutebrowser with the respective search engines.

Something like:

```bash
#!/bin/bash
echo ":open kindle $@" > "$QUTE_FIFO"
echo ":open kindle.fr $@" > "$QUTE_FIFO"
# ...
```

and then spawn that with `:spawn -u /path/to/script searchterm`, or even add an alias for it. Didn't test it though.

**Comment by rpietro** [comment]
@The-Compiler you're way too fast, man. thanks a ton, this script not only solves this problem but the general structure will help me do a bunch of other things. I will also go over userscripts in detail.
