### ISSUE TITLE
Missing hints 

### ISSUE THREAD

**Issue by rpietro** [qutebrowser/qutebrowser#4161]
This might be a bug: on the left panel of https://web.whatsapp.com/ , names without a photo will not get a hint, meaning that hey have to be clicked with the mouse. Interestingly, this is still the case when names are shown as part of a group -- see name at the bottom where that person still gets a hint since he does have a phone but the photo is not shown because he is speaking in a group:

![qtbughid](https://user-images.githubusercontent.com/693031/44630997-ef6b1a00-a933-11e8-8014-4e974779341d.png)

**Comment by The-Compiler** [comment]
I added this to #178 - the issue is that those are just `<div>` elements, and images get hints (but probably shouldn't, see #825).
