### ISSUE TITLE
[macOS] [Settings] [Proxy] [System] off by default - how to turn on in settings?

### ISSUE THREAD

**Issue by rprimus** [qutebrowser/qutebrowser#4167]
<details>
<summary>System Info:</summary>

#### System Info

ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

```
: ; ./qutebrowser --version
qutebrowser v1.4.1
Git commit: 75d153d6d (2018-07-11 17:16:50 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.11
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: Secure Transport, macOS High Sierra (10.13)

Style: QWindowsStyle
Platform: Darwin-17.7.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.13.6, x86_64

Paths:
auto config: /Users/rprimus/Library/Preferences/qutebrowser
cache: /Users/rprimus/Library/Caches/qutebrowser
config: /Users/rprimus/.qutebrowser
data: /Users/rprimus/Library/Application Support/qutebrowser
runtime: /var/folders/fm/9pykqrss0gj78whx2sk8_8s80000gn/T/qutebrowser

Uptime: 0:00:00
```
<hr>
</details>

Discovered `qutebrowser` from [here](https://spyware.neocities.org/articles/qutebrowser.html).

The first thing I checked was the proxy settings and operation.   Following on from https://github.com/qutebrowser/qutebrowser/issues/2934, I decided to test myself.

```
>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.systemProxyForQuery()[0]; print(p.type(), p.hostName())
2
```
The above  will *always* return 2, as there is no `QNetworkProxyQuery` object in the request.

From the [QT documentation](https://doc.qt.io/qt-5/qnetworkproxyfactory.html#queryProxy):
```
QList<QNetworkProxy> QNetworkProxyFactory::queryProxy(const QNetworkProxyQuery &query = QNetworkProxyQuery())
```
Providing a request object:
```
>>> from PyQt5.QtNetwork import QNetworkProxyFactory, QNetworkProxy, QNetworkProxyQuery; from PyQt5.QtCore import QUrl; p = QNetworkProxyFactory.systemProxyForQuery(QNetworkProxyQuery(QUrl("https://inch.com")))[0]; print(p.type(), p.hostName(), p.port())
3 localhost 8118
```
So, `systemProxyForQuery` does successfully query the system proxy settings,  however, `qutebrowser` was still not `respecting` these settings.

```
>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.usesSystemConfiguration(); print(p)
False
```
It appears that this is off by default.  When this setting was toggled,  `qutebrowser` then used 
the configured system proxy.

```
>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.setUseSystemConfiguration(True); print(p)
None
>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.usesSystemConfiguration(); print(p)
True
```

Without having to resort to configure this manually each time `qutebrowser` is started:

1.  Is there a way to have this setting easily toggled?
2.  Can this be included in `qute://settings` as a toggle?

**Comment by jgkamat** [comment]
R Primus writes:

> ```
>>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.systemProxyForQuery()[0]; print(p.type(), p.hostName())
> 2
> ```
> The above  will *always* return 2, as there is no `QNetworkProxyQuery` object in the request.

That's quite odd, for me:

[jay@laythe ~]$ export http_proxy=socks5://localhost:9150                                                                                                                                           [11011]  8:47PM
[jay@laythe ~]$ python3                                                                                                                                                                             [11012]  8:47PM
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.systemProxyForQuery()[0]; print(p.type(), p.hostName())
1 localhost
>>> from PyQt5.QtNetwork import QNetworkProxyFactory, QNetworkProxy, QNetworkProxyQuery; from PyQt5.QtCore import QUrl; p = QNetworkProxyFactory.systemProxyForQuery(QNetworkProxyQuery(QUrl("https://inch.com")))[0]; print(p.type(), p.hostName(), p.port())
1 localhost 9150
>>>

(and the proxy works for me in qb)

>
> From the [QT documentation](https://doc.qt.io/qt-5/qnetworkproxyfactory.html#queryProxy):
> ```
> QList<QNetworkProxy> QNetworkProxyFactory::queryProxy(const QNetworkProxyQuery &query = QNetworkProxyQuery())
> ```
> Providing a request object:
> ```
>>>> from PyQt5.QtNetwork import QNetworkProxyFactory, QNetworkProxy, QNetworkProxyQuery; from PyQt5.QtCore import QUrl; p = QNetworkProxyFactory.systemProxyForQuery(QNetworkProxyQuery(QUrl("https://inch.com")))[0]; print(p.type(), p.hostName(), p.port())
> 3 localhost 8118
> ```
> So, `systemProxyForQuery` does successfully query the system proxy settings,  however, `qutebrowser` was still not `respecting` these settings.
>
> ```

It looks like systemProxyForQuery is given a query in qb:

>>     def queryProxy(self, query):
>>         """Get the QNetworkProxies for a query.
>>         Args:
>>             query: The QNetworkProxyQuery to get a proxy for.
>>         Return:
>>             A list of QNetworkProxy objects in order of preference.
>>         """
>>         proxy = config.val.content.proxy
>>         if proxy is configtypes.SYSTEM_PROXY:
>>             # On Linux, use "export http_proxy=socks5://host:port" to manually
>>             # set system proxy.
>>             # ref. http://doc.qt.io/qt-5/qnetworkproxyfactory.html#systemProxyForQuery
>>             proxies = QNetworkProxyFactory.systemProxyForQuery(query)

>>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.usesSystemConfiguration(); print(p)
> False
> ```
> It appears that this is off by default.  When this setting was toggled,  `qutebrowser` then used
> the configured system proxy.
>
> ```

Weird, for me it's enabled by default (even without a proxy enabled):

[jay@laythe ~]$ b a python3                                                                                                                                                                         [11017]  8:50PM
Python 3.7.0 (default, Jul 15 2018, 10:44:58)
[GCC 8.1.1 20180531] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.usesSystemConfiguration(); print(p)
True

>>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.setUseSystemConfiguration(True); print(p)
> None
>>>> from PyQt5.QtNetwork import QNetworkProxyFactory; p = QNetworkProxyFactory.usesSystemConfiguration(); print(p)
> True
> ```
>
> Without having to resort to configure this manually each time `qutebrowser` is started:
>
> 1.  Is there a way to have this setting easily toggled?
> 2.  Can this be included in `qute://settings` as a toggle?

Maybe qutebrowser should force that on by default. I know very little about
the proxy api (maybe it has bad side-effects), so I'm not sure what the proper
way to do it would be. I would think that qt would have a rationale for
turning this off by default, so we should probably look into that some more to
avoid breaking things. Unless there's a clear 'setting' here, I'm not sure if
we should add a setting to do this (we could, for example, always enable this
when running with system proxy, if there's no side effects).

As a hack for now, you could probably stick that toggle into a config.py file,
so it's run on every startup.

**Comment by rprimus** [comment]
Fri Aug 31 05:37:01 BST 2018

A default `config.py` was created using `:config-write-py` (file created in `~/.quotebrowser/config.py`).

Adding `from PyQt5.QtNetwork import QNetworkProxyFactory; QNetworkProxyFactory.setUseSystemConfiguration(True)` at the end of the file has no effect.

**Comment by AKXX** [comment]
mine is working as I set `http_proxy=localhost:8118` in ~/.pam_environment

**Comment by The-Compiler** [comment]
Merging this into #2492.
