### ISSUE TITLE
unable to completely set HTTP accept header

### ISSUE THREAD

**Issue by ExpandingMan** [qutebrowser/qutebrowser#4169]
with
```python
c.content.headers.custom = {"accept": "text/html, */*; q=0.01 gzip, deflate, br en-US,en;q=0.5"}
```
my accept header is reading as
```
text/html, */*; q=0.01 gzip, deflate, br en-US,en;q=0.5 gzip, deflate, br en-US,en
```
So it seems as if qutebrowser is always appending the string `" gzip, defalte, br en-US,en"` to the accept header.

Is there a way to explicitly set the *entire* accept header?

By the way [this site](https://panopticlick.eff.org/) from EFF is useful for testing this.

I'm on version 1.4.1.

Thanks all.

**Comment by The-Compiler** [comment]
Testing with this, it looks fine here:

```
qutebrowser --temp-basedir -s content.headers.custom '{"accept": "text/html, */*; q=0.01 gzip, deflate, br en-US,en;q=0.5"}' httpbin.org/headers
```

but on panopticlick I indeed get the same value as you.

I've also looked at the header being sent with [mitmproxy](https://mitmproxy.org/) and it's indeed the correct `text/html, */*; q=0.01 gzip, deflate, br en-US,en;q=0.5`, so I'm tempted to call this some kind of panopticlick bug.

**Comment by NoctuaNivalis** [comment]
Panopticlick just appends your `Accept-Encoding` and `Accept-Language` to it, yes?

**Comment by ExpandingMan** [comment]
Also checked [here](https://browserleaks.com/ip), seems you are right, panopticlick is not only reporting the wrong header it is also misinforming users as to the frequency of their header as a result.

Thanks all.
