### ISSUE TITLE
phishing possibility due to the way url shortening is done

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#4170]
this url, and maybe any long url, is shortened in such a way that "indiatimes.com" becomes just "indiatimes. ..." without the tld.  this makes fishing easier. 

example url:
https://economictimes.indiatimes.com/news/defence/indian-army-carries-out-drills-in-counter-terrorist-environment-in-russia/200-member-indian-contingent/slideshow/65589215.cms

**Comment by jgkamat** [comment]
For me, this appears to happen in firefox as well if the window is small. I'm
not sure if we can solve this easily...

Toraboran Caveman writes:

**Comment by Al-Caveman** [comment]
i tried with firefox, and firefox does not ommit the tld, it looks something like this: https://economictimes.indiatimes.com/.../65589215.cms -- which is correct imo (note tld visible).

**Comment by jgkamat** [comment]
ah, I was shrinking the page too much and getting something like this
https://s25.postimg.cc/4je6iuuxb/2018-08-29-180638_505x273_scrot.png

I'm still not sure if we can implement this though, I'm pretty sure qt handles
the shortening but maybe there's some tweakables to it that allow it to be
optimized for urls.

Toraboran Caveman writes:

**Comment by The-Compiler** [comment]
Well caught, and an easy fix! :wink:
