### ISSUE TITLE
Cannot enter character from meta-layer in normal mode

### ISSUE THREAD

**Issue by hitsfromdabong** [qutebrowser/qutebrowser#4171]
I use an optimized keyboard layout called AdNW. It is similar to Dvorak, but also includes an additional layer where all the special characters are mapped in a convenient and ordered manner. See:
![image](https://user-images.githubusercontent.com/42746238/44791958-26933280-aba3-11e8-8cb6-378c45c19ab5.png)

On my implementation I use "Alt" as the modifier. (As I run macOS I then use Karabiner-Elements to switch Caps and Alt.)

Now, when I'm in Normal mode and I want to enter a command I press Alt + s, which should give me ':' in my layout. But qutebrowser doesn't react at all. Same goes for '/' to search. When switching to an English layout there is no problem.

In Input mode as well as when accessing the command line e.g. with the 'o' command there are no problems typing special characters.

My guess at the error would be that in Normal mode qutebrowser only recognizes input from the standard and the <Shift> layers.

**Comment by The-Compiler** [comment]
Sorry, seems like I forgot about this one! I'm guessing qutebrowser sees `Alt+:` in that case, you can confirm that's what's happening by running `python3 -m scripts.keytester` in the qutebrowser repo.

I don't think there's anything qutebrowser can improve here - with normal keyboard layouts, `Alt+:` and `:` should indeed be two different bindings.

**Comment by hitsfromdabong** [comment]
Yeah, you probably right there.

However, as qutebrowser is designed to be controlled in a vim-manner, no functionality would be lost ignoring the Alt key altogether. Would it be much work to add such an option?

**Comment by The-Compiler** [comment]
It'd mean that bindings involving the Alt key (some of them default bindings) would break, or shadow other bindings.
