### ISSUE TITLE
Lower priority for 404 pages in history

### ISSUE THREAD

**Issue by blueyed** [qutebrowser/qutebrowser#4172]
After opening https://github.com/qutebrowser/qutebrowser/404, `:open` will display this link on top - although it was a page that was not found.

While it should be still in the history, it should get a lower priority.

I think all pages with status codes not starting with 2 should get this, although something like 500 might be working on the next try again - so rather only assign a lower prio to 404 maybe in the beginning then.

**Comment by blueyed** [comment]
@jgkamat 
I am not sure about it either, but it is just a quick idea I had.

Reloading is much easier via <kbd>r</kbd> / `:reload` already, or <kbd>:</kbd> <kbd>Ctrl</kbd>-<kbd>p</kbd>.

Is the history just sorted by last-access currently?

**Comment by The-Compiler** [comment]
I currently don't want to go away from the current time-based sorting (indeed only by last-access), but see #601 which explores some other ways how sorting could be improved in the future.

Note that there's no API to get the detailed status code, all we can tell is whether there was an error or not.
