### ISSUE TITLE
Is it possible to have per domain cookies retention policies with QtWebEngine?

### ISSUE THREAD

**Issue by maxf130** [qutebrowser/qutebrowser#4174]
As the title says: Is it possible to only retain cookies from some domains?  

I'm dimmly aware that such things might be possible with QtWebKit, but not necessarily with QtWebEngine.  Can somebody confirm that?

If so, is this a limitation of QtWebEngine or of qutebrowser?

Many Thanks

Max

**Comment by The-Compiler** [comment]
It's possible with Qt >= 5.11, but not implemented yet - see #3636.

**Comment by toofar** [comment]
If you mean to be able to make the `content.cookies.accept` setting have a defferent value for different domain then not right now. No-one has gotten around to implementing it yet. I don't think it would be hard to add though, there is some discussion of it in #3636, the comments at the bottom are more up to date than the main issue text.

The things to change would be for webengine in `qutebrowser/browser/webengine/cookies.py` change `config.val.content.cookies.accept` to `config.instance.get('content.cookies.accept', url=request.origin)` and for webkit in `qutebrowser/browser/webkit/cookies.py` change the config.val bit similarly but used the passed in URL and change that method to support no-3rdparty and filter the cookie list appropriately, probably.

**Comment by The-Compiler** [comment]
To clarify: *Accepting* cookies per-domain is possible. Accepting them globally but only *storing* them selectively isn't.

**Comment by gerion0** [comment]
How is the whitelist possible?

I tried
```
  content.cookies.store:
    '*://*.github.com/*': true
    '*://*.google.com/*': true
    global: false
```
but this did not work. Get a failure at qutebrowser start, that per domain settings for cookies are not possible.

**Comment by The-Compiler** [comment]
@gerion0 possible as in "possible to implement" - but still not implemented so far.
