### ISSUE TITLE
"copy as curl" command

### ISSUE THREAD

**Issue by blueyed** [qutebrowser/qutebrowser#4176]
It would be useful to have a command that would generate and copy a curl command to get the current tab's web page from the command line.

There is a related issue to get this via dev tools (https://github.com/qutebrowser/qutebrowser/issues/1625), but I think it makes sense to have it without using `--enable-webengine-inspector`, and as a command itself.

I've quickly looked at https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc to see if it could be done as a userscript already, but it appears things like "POST data" and other things like "headers" are not available there.

To be clear: it should not just handle GET requests, but simulate what qutebrowser really did to get the page.  The following is an example of what Sentry generated to reproduce a web request:

```
curl \
 -X POST \
 --compressed \
 -H "Accept: application/json; version=1.0" \
 -H "Accept-Encoding: gzip" \
 -H "Connection: keep-alive" \
 -H "Content-Length: 117" \
 -H "Content-Type: application/x-www-form-urlencoded" \
 -H "Host: api.lock8.me" \
 -H "User-Agent: okhttp/3.9.0" \
 -H "X-Forwarded-For: X.X.X.X" \
 -H "X-Forwarded-Port: 443" \
 -H "X-Forwarded-Proto: https" \
 --data "user=username&password=%5BFiltered%5D" \
 "https://api.example.com/login/"
```

**Comment by The-Compiler** [comment]
You can do this in the dev tools, which don't need `--enable-webengine-inspector` anymore since Qt 5.11. There's no API to expose this via a command (but also see #1504 which goes in a similar direction).

**Comment by Holzhaus** [comment]
Well, you could use the `QWebEngineUrlRequestInterceptor` class to get the `QWebEngineUrlRequestInfo` objects of all requests.
Here's a patch to do that: https://github.com/Holzhaus/qutebrowser/commit/e2687a8462a5bb9d67703a710b304833c0a013aa

However, it looks like even though you can manipulate HTTP headers you can't not read them (but I don't know Qt that well to be honest).

**Comment by The-Compiler** [comment]
Sure, you can also do `--debug --debug-flag log-requests` already to log those, but that's not really enough info to get the current page as curl commandline.
