### ISSUE TITLE
`:open \ something` opens first result of `:open something` - intended behavior?

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#4177]
This is not bug report. Anyway I use [this version](https://paste.the-compiler.org/view/052c9b5e), which should be the current one from official repo.

As I pointed out in a minor comment at [this answer](https://stackoverflow.com/a/51789076/5825294), I noticed by pure chance that entering `:open \ something` is equivalent to running `:open something` **and then** opening the first result of the search. Is this an intended, undocumented behavior? I don't find it very useful, but I bet someone does.

**Comment by The-Compiler** [comment]
The same happens when you enter `\ something` [on DuckDuckGo](https://duckduckgo.com/) - it's a DuckDuckGo feature.
