### ISSUE TITLE
Way to stop animations?

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4182]
Is there a way to stop all gif and other animations in qutebrowser? (e.g. some kind of equivalent to one of these tools https://www.pcmag.com/article/345706/how-to-stop-animated-gifs-from-auto-playing-in-your-browser).

Thank you!

**Comment by The-Compiler** [comment]
I've looked at a couple of things, but found nothing unfortunately.

- The [Animation Policy](https://chrome.google.com/webstore/detail/animation-policy/ncigbofjfbodhkaffojakplpmnleeoee?hl=en) addon listed there ([source](https://cs.chromium.org/chromium/src/ui/accessibility/extensions/animation/popup.js?sq=package:chromium&dr&g=0)) is quite simple and uses the `chrome.accessibilityFeatures.animationPolicy` API, but that's not available in qutebrowser.
- The [Gif Jam](https://chrome.google.com/webstore/detail/gif-jam-animation-stopper/bclnijbemellankmoaafepibbboobalb?hl=en) addon ([source](https://github.com/adamfur/GifJam)) seems to be much more complex, essentially implementing a little GIF parser in JavaScript... I suppose doing that as a Greasemonkey script instead could be possible (but I'm not 100% sure), and would make it work in qutebrowser, but it'd be a bit of work.
- There doesn't seem to be an existing script for this [for Greasemonkey](https://wiki.greasespot.net/User_Script_Hosting) from what I can tell from a quick search. There [is one for TweetDeck](https://yal.cc/tweetdeck-no-gif-autoplay/) but that code seems to be specific to there.
- There also doesn't seem to be a [Chromium commandline switch](https://peter.sh/experiments/chromium-command-line-switches/).

So I guess the best you can do right now is setting the `content.autoplay` option, which at least disables autoplay for videos.

**Comment by prosoitos** [comment]
OK. Thank you for your quick reply. And thanks for pointing out the `content.autoplay` option. It is mostly gif that I was hoping to stop and I guess those won't be blocked by it(?)

**Comment by The-Compiler** [comment]
Yeah, I think it'll only affect videos (and "GIFs" which are actually videos, like on imgur).

**Comment by The-Compiler** [comment]
FWIW I added this to #5439 (and opened a [Qt bug](https://bugreports.qt.io/browse/QTBUG-86154)) since I think it should be relatively easy to add a toggle for this to QtWebEngine.

**Comment by prosoitos** [comment]
Great! Thanks!
