### ISSUE TITLE
hidpi - issue with config, won't start - is this a quick fix?

### ISSUE THREAD

**Issue by hook-s3c** [qutebrowser/qutebrowser#4184]
Fresh install Ubuntu 16.04, Python 3.5.2, XPS 13 9350

visited qute://settings and updated the hi-dpi value above to true;

```
cat ~/.config/qutebrowser/autoconfig.yml
# DO NOT edit this file by hand, qutebrowser will overwrite it.
# Instead, create a config.py - see :help for details.

config_version: 2
settings:
  colors.statusbar.url.error.fg:
    global: orange
  qt.highdpi:
    global: true
```

```
.venv/bin/python3 -m qutebrowser           
Fontconfig error: failed reading config file
21:54:49 INFO: Run :adblock-update to get adblock lists.
21:54:50 WARNING: Error while loading geometry.

(python3:29504): Gdk-WARNING **: python3: Fatal IO error 2 (No such file or directory) on X server :0.
```

**Comment by The-Compiler** [comment]
I've never seen that happen, but it looks like some issue with Qt (or even GTK, which IIRC is used for things like native file dialog) - also see e.g. https://github.com/daniruiz/flat-remix/issues/72

Nothing qutebrowser can do about this I'm afraid...

**Comment by hook-s3c** [comment]
Actually, that can't be it - I `ln -s`'ed the svg files and the error still occurs - looking further up the trace there are other files missing, but these don't break to exit
