### ISSUE TITLE
being "stuck" in a search bar

### ISSUE THREAD

**Issue by mahaaaham** [qutebrowser/qutebrowser#4196]
Hi,

  I'm not sure if this is a bug of if I haven't iunderstand something so, I apologise if it is the case.

  When I'm, for example, in google, in the "search bar" and I want to quit it, I don't know of to "quit" the bar without the mouse. This is a problem because I'm forced to either use the mouse (and click anywhere in the page) or use "ctrl-f ctrl-g" to scroll the page: I can't use j and k for this because I'm in the bar and they are used to go left and right in.

  So.. is there a shortcut or a command that I haven't found to do this?  It is annoying because Iin some websites, the cursus begins to be in a search bar, and so I have to quit it if I want to navigate with "jklm".

Thanks for all, qutebrowser is awesome.

here are the informations about my version of qute-browser
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.8
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 16.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.9.0-7-amd64-x86_64-with-debian-9.5, 64bit
Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/maha/.cache/qutebrowser
config: /home/maha/.config/qutebrowser
data: /home/maha/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 1:36:14

**Comment by The-Compiler** [comment]
Currently the easiest way is using the mouse indeed - #2668 has some discussion on this already, and some of the open PRs by @jgkamat will hopefully help with this.

**Comment by rpietro** [comment]
@mahaaaham I tab out of it, it works

**Comment by mschilli87** [comment]
@rpietro: Unless you have a dropdown with suggestions, then even after leaving insert mode via <kbd>Esc</kbd>, <kbd>Tab</kbd> will cycle through that list instead of removing focus from the search bar.
