### ISSUE TITLE
Register qute:// URL with Chromium on Qt 5.12

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4198]
As soon as we can, we should register the `qute://` URL scheme with Chromium on Qt 5.12:

https://bugreports.qt.io/browse/QTBUG-70420
https://bugreports.qt.io/browse/QTBUG-70421

We already have some related code with will break on Qt 5.12 without the scheme being registered.

This also should allow us to mark `qute://` as a local-only scheme as an additional protection against #4198.

**Comment by The-Compiler** [comment]
I just pushed basic registering of schemes - however:

- The download button on PDF.js is still broken
- `:view-source` works despite me not passing that scheme flag

So that still needs some investigation.

**Comment by jgkamat** [comment]
It looks like the qute scheme isn't registered in the tests:

https://api.travis-ci.org/v3/job/492231616/log.txt

**Comment by The-Compiler** [comment]
> It looks like the qute scheme isn't registered in the tests

That's because that's on Archlinux with Qt 5.12 but PyQt 5.11, so we don't have the API to register it. Given that Archlinux updated its PyQt5, this should go away with the next rebuild of the Docker image.

**Comment by The-Compiler** [comment]
Oh, looks like the issues I had at the beginning of January also were due to me trying with an older PyQt. All seems fine now, including the PDF.js download button!
