### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by thamma** [qutebrowser/qutebrowser#4203]
Hey fellow qb users,

I implemented notification hooks to send notification for finished downloads. I think hooks in generel could be useful, but I assume that's something the plugin API should take care off.

What's the state of the plugin API at the moment? Do you think hooks could be a temporary solution for some features that the plugin API would provide? What do you think about that?

**Comment by jgkamat** [comment]
Yup, the way I understand it, hooks would be a natural part of the plugin api (using qt signals/slots). How are you exposing the hook currently?

**Comment by thamma** [comment]
Currently, the hooks are hardcoded subprocess calls. Obviously, this is subject to change.

I take a lot of inspiration from [git hooks](https://git-scm.com/book/pl/v2/Customizing-Git-Git-Hooks). Each hook is one executable file. This allows the user to have freedom of programming languages (be it python scripts or simple bash calls to notify-send) using shebang. Arguments (for instance name of the downloaded file or download progress) can easily be provided. The filename indicates what event triggers the hook. For example: [download_finished](https://github.com/qutebrowser/qutebrowser/files/2363680/download_finished.txt)

Of course they would be trivial to implement using the plugin API. But currently there is no such thing.

**Comment by thamma** [comment]
Browsing the project some more, i discovered @The-Compiler's intention to tackle the plugin API in the upcoming semester as a [student research project (german)](https://wiki.hsr.ch/StefanKeller/wiki.cgi?SA_HS18_Bruhin_Schwab_Aufgabenstellung).

**Comment by thamma** [comment]
I doubt these hooks would require complex information in the first place. Otherwise, JSON would likely be a suitable solution. Anyway, this won't be an issue due to the likely soon to be upcoming plugin API.

Good point on the download watcher.

Linking to [issues/30](https://github.com/qutebrowser/qutebrowser/issues/30) for future reference, I think we can close this issue.
