### ISSUE TITLE
Shortener

### ISSUE THREAD

**Issue by rpietro** [qutebrowser/qutebrowser#4205]
I know this is pretty basic, but I have been trying to write a userscript for a while without getting anywhere: the goal is to assign the ss keybinding to shorten the current url using bitly (for the lack of a better one). One of the many things I tried was a script file called shortener (permission set with `chmod +x`) with:  

```
#!/bin/bash
echo "open -t https://api-ssl.bitly.com/v3/shorten?format=txt&access_token=
    mytoken%&longURL=QUTE_URL" >> {clipboard}
```

where mytoken was obtained with:

`curl -u "username:pwd" -X POST "https://api-ssl.bitly.com/oauth/access_token"
` 

I then added the following line to config.py:

> config.bind('ss', 'spawn --userscript shortener')

I don't get an error when opening qutebrowser, also no error when issuing the shortcut, but I don't get a shortened url in my clipboard.

I tried a number of different options for {clipboard}, not sure if ss is free (I don't know how to check if a binding is or not taken), and the script is also probably broken at other places. 

Any thoughts? thanks

**Comment by jgkamat** [comment]
qutebrowser dosen't provide an api for writing to the clipboard through userscripts. I think that script will write the literal string `open -t https://api-ssl.bitly.com/v3/shorten?format=txt&access_token=
    mytoken%&longURL=QUTE_URL` to a file called `{clipboard}`.

First, create a curl or wget command which shortens a URL stored in `QUTE_URL`. This might be something like:

```
curl -u "username:pwd" -X POST "https://api-ssl.bitly.com/shorten-me/URL=$QUTE_URL"
```

Then, pass it to a command line utility to put it onto the clipboard:

```
curl -u "username:pwd" -X POST "https://api-ssl.bitly.com/shorten-me/URL=$QUTE_URL" | xclip -sel clip -i
```

`{expansions}` are only done in the qutebrowser command mode, so they are only useful for getting information to your scripts via arguments. So you could `:spawn myscript.sh {url}` with expansions.

**Comment by R3load** [comment]
In `longURL=QUTE_URL`, 'QUTE_URL' is a string, not a variable reference.

**Comment by The-Compiler** [comment]
Closing this as it looks like it should work after those changes :wink: I agree with @jgkamat, would be cool to have this in the `userscripts` folder, with the API key in a variable or something!

**Comment by rpietro** [comment]
thanks everybody for your responses. addressing @jgkamat 's suggestion, here is the final working code for the userscript:

```
#!/bin/bash
curl https://is.gd/create.php\?format\=simple\&url\=$QUTE_URL | xclip -sel clip -i 
```

and the keybinding:

`config.bind('ss', 'spawn --userscript shortener')`

@The-Compiler I can send this as a pull request if you think that a version without an API key would be useful.
