### ISSUE TITLE
discourse icons (fonts?) not loading properly

### ISSUE THREAD

**Issue by ExpandingMan** [qutebrowser/qutebrowser#4209]
They render as little empty boxes.

I'm sorry I can't give a much more useful description.  `:messages` is empty.  Here is my version
```
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0i  14 Aug 2018

Style: Qt5CTProxyStyle
Platform: Linux-4.18.6-1-MANJARO-x86_64-with-arch-Manjaro-Linux, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/expandingman/.cache/qutebrowser
config: /home/expandingman/.config/qutebrowser
data: /home/expandingman/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```
Here's a picture:
![2018-09-10-102726_140x111_scrot](https://user-images.githubusercontent.com/11379353/45304127-69c79c80-b4e5-11e8-9a42-b20b8ff55656.png)

Looks normal in other browsers.

**Comment by The-Compiler** [comment]
Can you reproduce this with `--temp-basedir`?

**Comment by ExpandingMan** [comment]
Hm, that seems to work.  It could be something in my config?  I didn't change anything since that happened (... I don't think).

You can find my config [here](https://github.com/ExpandingMan/dotfiles/blob/master/.config/qutebrowser/config.py).

Thanks!

**Comment by The-Compiler** [comment]
```python
c.content.headers.user_agent = "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
c.content.headers.custom = {"accept": "text/html, */*; q=0.01 gzip, deflate, br en-US,en;q=0.5"}
c.content.canvas_reading = False
```

Pretty sure it's one of those - can you find out which?

**Comment by mschilli87** [comment]
@ExpandingMan: You could try to rename you cache and data directories to make sure it's config related.

**Comment by ExpandingMan** [comment]
Ah, it's the accept header.  Note that I actually had to reload qutebrowser to restore the icons, doing `:config-source` and reloading the page didn't do it for some reason.

I feel rather silly for not having thought that might be the issue before posting this, however I was about 95% sure that I was using the exact same headers on another machine and discourse was working fine.  A change in discourse perhaps?

Regardless, I wanted to do some anti-fingerprinting as a hobby project, but haven't gotten around to yet and don't yet know what the hell I'm doing, so clearly I don't have it set up quite right yet (at least one of those is a firefox header, but apparently it interacts badly with something else the website reads from me).

Anyway, thanks all!
