### ISSUE TITLE
xdotool shift key not working with qutebrowser

### ISSUE THREAD

**Issue by bouncepaw** [qutebrowser/qutebrowser#4212]
Version: https://paste.the-compiler.org/view/8494ca96

There are keyboard shortcuts on https://soundcloud.com (online music service). For example, when you press `l` (lowercase L), current track is liked; when you press `shift+l`, the track is repeated in a loop. 

Consider qutebrowser window ID is `0x0060001f` (I have found it with `wmctrl -l`). When I do this: `xdotool key --window 0x0060001f l`, the track gets liked, but when I do this: `xdotool key --window 0x0060001f shift+l`, the track doesn't get repeated. I double-checked, the problem is on qutebrowser's side, because `shift` works in other programs.

**Comment by The-Compiler** [comment]
Works fine here with the same versions. Can you do `:report` so I can take a look at the logs please?

**Comment by jgkamat** [comment]
Timur Ismagilov writes:

> There are keyboard shortcuts on https://soundcloud.com (online music service). For example, when you press l (lowercase L), current track is liked; when you press shift+l, the track is repeated in a loop.

This is a bit unrelated to this issue, but you may be interested in :fake-key
which lets you rebind keys sent to the webpage. The xdotool method should work
too though.

**Comment by The-Compiler** [comment]
FWIW both `shift+l` and `L` work fine for me.

**Comment by bouncepaw** [comment]
Well, it seems like the problem is on i3wm's side, because on dwm everything works fine. Sorry for inconvience, I'll close the issue.

> This is a bit unrelated to this issue, but you may be interested in :fake-key which lets you rebind keys sent to the webpage. The xdotool method should work too though.

:fake-key is cool, thanks for telling about it.

> Shouldn't the key name be L for xdotool? That's usually the right way to pass <shift+{letter}> keys, I'd expect xdotool to behave in the same manner.

I tried it and it works fine too.

> Works fine here with the same versions. Can you do `:report` so I can take a look at the logs please?

That's pointless now.
