### ISSUE TITLE
Allow turning off counts

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4213]
A qutebrowser with emacs-like bindings is [almost possible](https://gitlab.com/jgkamat/qutemacs/blob/master/qutemacs.py) - however, typing number keys in insert mode isn't possible as they're always handled even if unbound. There should probably be a setting to prevent that from happening.

**Comment by jgkamat** [comment]
A workaround that works for now is to, for example, `:bind 1 fake-key 1`

**Comment by toofar** [comment]
historically related https://github.com/qutebrowser/qutebrowser/issues/3307

**Comment by pylbrecht** [comment]
I will take a shot at this.

Taken from IRC, so I don't forget:
> the place to look would be qutebrowser/keyinput/basekeyparser.py - probably just have a setting to disable counts and then abort early in _match_count if it's set or so.
