### ISSUE TITLE
Add New Installation Method- Docker Container

### ISSUE THREAD

**Issue by o-vexler** [qutebrowser/qutebrowser#4217]
Hi, 
I really love using qutebrowser, thought it would be great to have it easily installed on Linux with a Docker container. 

I will be glad to contribute to this project with a Docker image. 
Just forked the project and started working on it :)

**Comment by o-vexler** [comment]
The PR is right here: #4219 :beers:

**Comment by The-Compiler** [comment]
I don't think Docker is the right tool for graphical applications with persistent config files - I also don't see the benefits over existing install methods (like virtualenv and Flatpak), so I'm closing this one. I'd be fine with a PR adding install instructions if someone else steps up to maintain a Dockerfile, though!
