### ISSUE TITLE
Is there a way to specify print properties? 

### ISSUE THREAD

**Issue by JonathanReeve** [qutebrowser/qutebrowser#4238]
I notice that every time I print something (to PDF, in my case), I have to click "properties" and set the page margins and everything else in the resulting dialog box. That is, it doesn't seem to remember the print properties settings from one print to another. I noticed there's the setting `content.print_element_backgrounds`, but I can't seem to find other settings, for, e.g., margins. I would've also guessed that I could set these with an `@media print { @page { margin: 1in; } }` declaration, but unless I'm doing it wrong, that doesn't seem to have any effect. 

Is there a way to set print properties once, and have them stick? Via config file would be ideal. Then I could print HTML files from the commandline, maybe.

**Comment by The-Compiler** [comment]
You should be able to set them in CUPS' default settings, not sure how that'd work with printing to PDF, though. See [various Qt bugs](https://bugreports.qt.io/issues/?jql=text%20~%20margins%20and%20component%20%3D%20webengine) as for setting them from CSS.

Given that there's a lot of things to configure (and it also differs a bit from printer to printer), I'd rather not expose all that via qutebrowser settings.
