### ISSUE TITLE
Alt-[1-8] behaves differently when Tab is already focused

### ISSUE THREAD

**Issue by nepumuk-fs** [qutebrowser/qutebrowser#4248]
### Summary
Pressing Alt-[1-8] multiple times results in alternating the tab focus between tab [1-8] and the tab focused before.
### Steps to reproduce
1. Open / Load more than one tab in the same window, e. g. 10 tabs.
2. Choose a number out of {1; 2; 3; 4; 5; 6; 7; 8}.
3. Press Alt-[chosen number] multiple times.
3. a) I. If the tab isn't focused before pressing Alt-[chosen number], it will be focused then.
3. a) II. After pressing Alt-[chosen number] for the second time the tab focused before the one you switched to with Alt-[chosen number] will be focused again.
3. a) III. Pressing Alt-[chosen number] will result in alternating between the two tabs last focused.
3. b) I. The chosen tab is/was already focused and another was focused before: The tab focus bevahes as described in 3. a) II., III. respectively.
3. b) II. The chosen tab is/was already focused and no other was focused before: Error message that no tab was focused before the previous one (no bug behaviour, but listed for completeness).
4. Now choose two numbers out of {1; 2; 3; 4; 5; 6; 7; 8} being related to tabs 1 to 8.
5. a) Focus the second tab. Then focus the first tab.
5. b) Press Alt-[first-number]. The tab focus will change to the second tab.
5. c) Press Alt-[second-number]. The tab focus will change to the first tab again.
6. a) Close as many tabs as necessary to have between one and nine (1 to 8) tabs opened.
6. b) Nearly the again with two numbers: Choose the number of the last tab. The second number will be 9.
6. c) Focus any tab except the one with the highest tab number.
6. d) Press Alt-9. The tab focus changes to the last tab as expected.
6. e) Press Alt-[chosen-number]. The tab focus will change to the "any tab".
6. f) This can be repeated as often as desired.
7. Press Alt-9 multiple times: The focus of the tabs remains with the last tab as expected.### What is the current *bug* behavior?
Focusing the same tab with Alt-[number] results in alternating between the tab with the chosen number and the (pre-)last focused tab.
Somehow, Alt-9 gives always the last tab no matter which tab is focused and wether Alt-9 is pressed multiple times.
### What is the expected *correct* behavior?
Pressing Alt-[1-8] should keep the focus on the chosen tab when pressed multiple times, too, like Alt-9 focusses always the last tab, no matter how often Alt-9 is pressed (Alt-99 would mean "Alt-9, Alt-9", e. g.)
### Possible fixes
Maybe some code of "reaction to pressing Alt-9" could be copied...?

###Version of my qutebrowser
From my terminal:
**$ qutebrowser --version**
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.11.2

**Comment by The-Compiler** [comment]
Alt-9 not having that behavior is the real bug here, which is now fixed. You can rebind those keys to pass `--no-last` to `:tab-focus` to disable this.

**Comment by The-Compiler** [comment]
Going to the last tab with Alt-9 and doing nothing with Alt-0 is also what Chrome/Firefox do, so I'd like to keep consistent with that.
