### ISSUE TITLE
Can't switch to another tab using keyboard if in "insert Mode".

### ISSUE THREAD

**Issue by justUmen** [qutebrowser/qutebrowser#4249]
```
qutebrowser v1.4.2
Git commit:
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.6
Qt: 5.9.5
PyQt: 5.10.1
```

If in "insert mode", I can't go to another tab with Alt + 1-9, is that a bug or a feature ?

**Comment by The-Compiler** [comment]
That's intended, but you can bind those keys yourself with e.g. `:bind --mode=insert <Alt+1> tab-focus 1`.

**Comment by justUmen** [comment]
That's a quick answer thanks !
So I guess the "insert mode" is browser based, not tab based.
Is it possible to have some pages always being in insert mode ? (by urls ?)

**Comment by The-Compiler** [comment]
Yeah, it's window-based. There's the `tabs.mode_on_change` setting which controls what happens when switching tabs.

> Is it possible to have some pages always being in insert mode ? (by urls ?)

Currently not, I added it to #3636.

**Comment by justUmen** [comment]
Amazing, keep up the great work ! I'll try to use qutebrowser as my main browser for a while. ;)

**Comment by The-Compiler** [comment]
Do you mean "Open link in new tab", which already exists?
