### ISSUE TITLE
Add a way to show cert details

### ISSUE THREAD

**Issue by MaximilianKindshofer** [qutebrowser/qutebrowser#4253]
I did not find a way to show the details of a SSL Certificate.

It would be nice to have a way to see the details of a certificate to see who issued it for which domain, get the fingerprint etc

**Comment by The-Compiler** [comment]
This isn't possible until QtWebEngine exposes an API to do so - see [various related Qt issues](https://bugreports.qt.io/browse/QTBUG-66681) about it.
