### ISSUE TITLE
Accelerated scrolling

### ISSUE THREAD

**Issue by leungbk** [qutebrowser/qutebrowser#4256]
In Firefox, accelerated scrolling can be configured by going to `about:config` and changing `mousewheel.acceleration.factor` and `mousewheel.acceleration.start`. Is it possible to do something similar with Qutebrowser?

**Comment by jgkamat** [comment]
The easy way to get more control over scrolling is to use :scroll-page or
:scroll-px instead of the default scrolling methods, which let you configure
how much you scroll by.

You can also run :scroll with a count to scroll more in one go.

Brian Leung writes:

**Comment by leungbk** [comment]
Thanks for your response. Accelerated mousewheel scrolling is a bit different in that rotating the mousewheel a given number of notches in a short time interval can produce a greater amount of screen movement than would be observed for the same angular displacement over a longer time interval. `:scroll-page` is nice, but sometimes my hands get a bit worn out from sustained keyboard scrolling. Running `:scroll` with a count is less convenient for me than accelerated mousewheel scrolling since I can adjust my scrolling speed with my mouse based on how far down a page I am. It would be convenient to have accelerated mousewheel scrolling separately implemented in Qutebrowser.

**Comment by jgkamat** [comment]
If you want to customize mousewheel scrolling, there should be tools to do
that on your system level, so it applies everywhere, and not just in
qutebrowser. I found imwheel which seems to work for me, but maybe changing
changing the value through evdev or xinput would be cleaner.

http://imwheel.sourceforge.net/
https://askubuntu.com/questions/255890/how-can-i-adjust-the-mouse-scroll-speed

Brian Leung writes:
