### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by D3faIt** [qutebrowser/qutebrowser#4259]
Hi

Since the day I installed qutebrowser on my linux laptop, I wanted to install it on my work laptop as well (Windows 10).
So far, I have **never** been able to get it online, except if I specify the ip address in the hosts file. local servers also work.
The current configured proxy is a .pac url. It should be configured via the system, not the application.

## Troubleshooting

I have tried changing content.proxy to `pac+http://example.com/file.pac`. It is exactly the same url as configured in `Internet Properties => Connections => LAN Settings => Use automatic configuration script`, but it doesn't work

`content.proxy_dns_requests true` did not help either

Changing to another network (eg, guest wifi) solves the issue, but that's not what I want.

Chrome works, Edge works, Firefox works, Internet Explorer works.

Pinging google.com with CMD does **not** work, but nslookup google.com **works**, but outputs the ip from the work network, rather than the original. (if that helps to see the whole picture)

## Question

Are there any solution for this problem? Or maybe a workaround? (like a local proxy or something)

**Comment by The-Compiler** [comment]
There's no PAC support for QtWebEngine currently, see #2492. I'm not sure if it'll be picked up if you set the proxy to `system`. Could you check whether it works in [Falkon](https://www.falkon.org/)?

**Comment by D3faIt** [comment]
Hmm

It works on Falkon

![2018-09-28 07_50_41-google - falkon](https://user-images.githubusercontent.com/8147434/46190551-4ded3480-c2f4-11e8-9443-146b4c9ab406.png)

**Comment by JonathanReeve** [comment]
I don't know if this is this same issue, but I've also been having what appear to be DNS issues, and only on Qutebrowser. Some sites will just fail to load, but only sometimes: if I reload a site about 30 times, it will eventually load. Sometimes DuckDuckGo will fail to load entirely, but then Google will work. Other times, GitHub won't load at all, but if I try again in 5 minutes, it does. I have no idea what could be happening here. No problems on Chromium.

**Comment by JonathanReeve** [comment]
I just tried starting Qutebrowser with --temp-basedir and it's seeing the same issues. Will try Falkon too, soon.

**Comment by lrvick** [comment]
On 2 different laptops qutebrowser stops resolving DNS requests for me after running it for a while. Only a reboot seems to fix it.

**Comment by jgkamat** [comment]
It would be nice if people provided their `:version` so that we could form a correlation about these issues. I haven't seen any DNS issues across 5 different distros with different qt/qutebrowser versions. 

I also suspect there are two issues being wrongly merged here.

Maybe these are related to windows packaging, if so - maybe trying an older build of the windows binary could give some clues. I don't have any windows machines for testing unfortunately.

**Comment by JonathanReeve** [comment]
```
Version info
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.0.2p  14 Aug 2018

Style: Qt5CTProxyStyle
Platform: Linux-4.14.74-x86_64-with-glibc2.3.4, 64bit
Linux distribution: NixOS 19.03pre155123.32bcd72bf28 (Koi) (unknown)
Frozen: False
Imported from /nix/store/w9rcqpcmzqp4g9wi07h48zmin6kjwx09-qutebrowser-1.4.2/lib/python3.6/site-packages/qutebrowser
Using Python from /nix/store/1c4zshbxizcsvyj46fwf5jj10h41wf6i-python3-3.6.6/bin/python3.6m
Qt library executable path: /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1/libexec, data path: /nix/store/24v34kyz7zkv4iw673i170r8dv4zgz3p-qtbase-5.11.1
OS Version: 

--- /etc/os-release ---
NAME=NixOS
ID=nixos
VERSION="19.03pre155123.32bcd72bf28 (Koi)"
VERSION_CODENAME=koi
VERSION_ID="19.03pre155123.32bcd72bf28"
PRETTY_NAME="NixOS 19.03pre155123.32bcd72bf28 (Koi)"

Paths:
cache: /home/jon/.cache/qutebrowser
config: /home/jon/.config/qutebrowser
data: /home/jon/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /nix/store/w9rcqpcmzqp4g9wi07h48zmin6kjwx09-qutebrowser-1.4.2/share/qutebrowser

Uptime: 1 day, 10:47:16

```

**Comment by JonathanReeve** [comment]
Strangely, I rebooted, and the problem appears to have fixed itself here, too. Not sure what caused, or is causing that, but it got to the point where about half of domains wouldn't resolve. Really annoying.

**Comment by JonathanReeve** [comment]
The problem still persists, as far as I can tell, but rebooting fixes it *temporarily*. (Sorry I wasn't more clear about that.) Thus I don't think this issue should be closed quite yet. Unless there's been some change recently that fixes it? I have no idea what could be causing this.

**Comment by The-Compiler** [comment]
Indeed there seem to be two different issues here:

- For QtWebEngine proxy support, indeed some stuff isn't working properly - see #2492 for that.
- As for those DNS issues, I suspect there's nothing qutebrowser can do - those are either issues on your system, or in QtWebEngine (or the underlying Chromium). The only time qutebrowser does its own DNS requests is if you set `url.auto_search` to `dns`, but that shouldn't break websites from being loaded (if anything, websites would be loaded as search terms instead).
