### ISSUE TITLE
$QUTE_URL contains the current url instead of the selected

### ISSUE THREAD

**Issue by Awlexus** [qutebrowser/qutebrowser#4267]
I tried to execute a userscript that would use the selected url, but it always uses the current url instead. 
This is how I set up the shortcuts:
```python
config.bind(',yta', 'hint links spawn --userscript yta')
config.bind(',yta', 'hint links spawn --userscript yta', mode='hint')
```
And this is how I tried to access it:
```bash
notify-send "Url is $(echo $QUTE_URL)" # Always outputs the current url
```

Version:
```
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2 (compiled 5.11.1)
PyQt: 5.11.2

sip: 4.19.12
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.25.1
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.9-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

```

**Comment by The-Compiler** [comment]
If you use `:hint` with the `spawn` target, it just runs `:spawn` with the given arguments. It's a bit unfortunate that `:spawn --userscript` even works there, but I'm not sure we should disallow it.

To run userscripts from hints with the variables set properly, use `hint links userscript yta` instead.

**Comment by jcguu95** [comment]
Great! I just got this problem and it's solved in this thread. Thanks.

**Comment by The-Compiler** [comment]
@jcguu95 I'm not sure what you mean precisely - maybe you want to open a pull request adjusting the [relevant docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc)?
