### ISSUE TITLE
Problem displaying AngularJS apps

### ISSUE THREAD

**Issue by mrpewpew** [qutebrowser/qutebrowser#4268]
Recently, I got display problems on a few websites. One example is the ovh dashboard. Here is what I see in qutebrowser vs what I should see (in Firefox)
![ovh_qutebrowser](https://user-images.githubusercontent.com/38474825/46246155-7e6ac680-c3f9-11e8-823c-ad9e6ab4be19.png)
![ovh_firefox](https://user-images.githubusercontent.com/38474825/46246162-875b9800-c3f9-11e8-9c84-5d9c6a83354d.png)

After inspecting the web page, it appears to be an AngularJS app (`data-ng-app` tag). It's a recent bug since I was able to display that web page a few days ago.

Did anything change in the last few days that would explain this issue ?
 
```
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)
```

**Comment by The-Compiler** [comment]
Indeed. Can you show your `qute://configdiff` page?

**Comment by mrpewpew** [comment]
```
bindings.commands = {"normal": {"K": "tab-next", "J": "tab-prev", "j": "scroll-page 0 0.3", "k": "scroll-page 0 -0.3", "m": "spawn mpv --ytdl-raw-options=format=\"best[height<=480]\" {url}", "M": "hint links spawn mpv --ytdl-raw-options=format=\"best[height<=480]\" {hint-url}"}}
completion.cmd_history_max_items = 500
content.default_encoding = utf-8
file://*: content.javascript.enabled = true
chrome://*/*: content.javascript.enabled = true
qute://*/*: content.javascript.enabled = true
fonts.completion.category = 8pt monospace
fonts.completion.entry = 8pt monospace
fonts.monospace = Hack, "xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal
fonts.statusbar = 8pt monospace
fonts.tabs = 8pt monospace
fonts.web.size.default = 12
fonts.web.size.default_fixed = 10
qt.highdpi = true
tabs.last_close = startpage
url.searchengines = {"DEFAULT": "https://duckduckgo.com/?q={}", "g": "https://www.google.com/search?hl=en&q={}", "gf": "https://www.google.com/search?hl=fr&q={}"}
zoom.default = 80%
```

**Comment by The-Compiler** [comment]
Hmm, nothing too odd in there. Can you try quitting qutebrowser and moving `~/.config/qutebrowser` away, and if that doesn't help, try `~/.local/share/qutebrowser` or `~/.cache/qutebrowser`?

**Comment by mrpewpew** [comment]
It was a cache thing, the problem disappeared after removing the cache folder. Thanks !
