### ISSUE TITLE
logo is pixelated, gnome3, qutebrowser v1.4.1

### ISSUE THREAD

**Issue by iambumblehead** [qutebrowser/qutebrowser#4270]
Attached are screenshots from gnome3 desktop. The logo is pixelated wherever it is rendered in gnome3.

![qutebrowser-icon-gnome3](https://user-images.githubusercontent.com/2058705/46254362-0628f300-c443-11e8-828d-fb1ca9d0d508.png)

**Comment by The-Compiler** [comment]
What distribution is this, and how did you install qutebrowser?

**Comment by iambumblehead** [comment]
The distribution is Ubuntu and qutebrowser was installed through the "Ubuntu Software" (apt)

![screenshot from 2018-09-30 00-02-28](https://user-images.githubusercontent.com/2058705/46254426-4d63b380-c444-11e8-90ce-2d5397df4c10.png)

**Comment by The-Compiler** [comment]
This looks like Ubuntu takes the 16x16 (or 32x32?) icon and scales it up. The Debian package does contain the icon in much higher resolutions (up to 128x128) as well, so I'm not sure what's going on there.

**Comment by iambumblehead** [comment]
[This guide shows that icons][0] should go in /usr/share/icons/hicolor by default.

Here are listed the icons found for qutebrowser and gvim (the icon for which is very sharp and clear), I do not see an svg icon listed for qutebrowser,
```bash
~$ ls /usr/share/icons/hicolor/*/apps/gvim*
/usr/share/icons/hicolor/48x48/apps/gvim.png  /usr/share/icons/hicolor/scalable/apps/gvim.svg
~$ ls /usr/share/icons/hicolor/*/apps/qute*
/usr/share/icons/hicolor/128x128/apps/qutebrowser-128x128.png  /usr/share/icons/hicolor/32x32/apps/qutebrowser-32x32.png
/usr/share/icons/hicolor/16x16/apps/qutebrowser-16x16.png      /usr/share/icons/hicolor/48x48/apps/qutebrowser-48x48.png
/usr/share/icons/hicolor/24x24/apps/qutebrowser-24x24.png      /usr/share/icons/hicolor/512x512/apps/qutebrowser-512x512.png
/usr/share/icons/hicolor/256x256/apps/qutebrowser-256x256.png  /usr/share/icons/hicolor/64x64/apps/qutebrowser-64x64.png
```

This machine is a Dell XPS 13 with a high resolution screen and maybe an svg icon would be needed for better results.

[0]: https://developer.gnome.org/integration-guide/stable/icons.html.en

**Comment by The-Compiler** [comment]
That'd be a Debian packaging bug then. Can you try whether things look better if you download https://github.com/qutebrowser/qutebrowser/blob/master/icons/qutebrowser.svg and save it to `/usr/share/icons/hicolor/scalable/apps/qutebrowser.svg` please?

**Comment by iambumblehead** [comment]
@The-Compiler I'll do it... just a moment I'll update this comment with the result

**Comment by fiete201** [comment]
Hi,

first of all thanks for reporting and testing!

Can you please install these 2 packages and tell me if the issue is fixed then?
https://paste.xinu.at/m-CU1HcAL/

Just download and `sudo apt install ./qutebrowser-qtwebengine_1.4.2-2_all.deb ./qutebrowser_1.4.2-2_all.deb`

**Comment by iambumblehead** [comment]
@fiete201 yes, the icon is sharp after installing those

**Comment by fiete201** [comment]
Thanks for testing

`qutebrowser_1.4.2-2_amd64.changes ACCEPTED into unstable`

New version was uploaded into unstable and should land in testing in some days.
