### ISSUE TITLE
MacOS .app has a different $PATH when launched from terminal

### ISSUE THREAD

**Issue by jgillman** [qutebrowser/qutebrowser#4273]
Apologies if this has been posted before, I found closed $PATH-related issues, but none that seemed fitting.

When I launch qutebrowser from the command line in MacOS the PATH includes everything I would expect and I'm able to correctly `spawn mpv {url}` and stuff like that. When I launch qutebrowser from the .app the PATH is extremely short and I can't `spawn` anything that's not built into the system.

I'm running 10.13.6 and installed qutebroswer with Homebrew.

### PATH when launched from command line

```
PATH = /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jgillman/perl5/bin:/Users/jgillman/bin:/Users/jgillman/.dotfiles/bin:/usr/local/lib/node_modules:/Users/jgillman/node_modules/.bin:/Users/jgillman/.dotfiles/fzf/bin:/usr/local/sbin:/usr/local/opt/fzf/bin
```

### PATH when lauched from .app

```
PATH = /usr/bin:/bin:/usr/sbin:/sbin
```

This all makes sense since launching it from the command line would inherit the environment from which it was launched, but it's annoying that it's not included when launched from the app. Not sure if that's a fixable thing, or if the solution is to always launch from the terminal.

**Comment by The-Compiler** [comment]
Nothing that qutebrowser can do about that - you'll need to find a way to set a system-wide path on macOS, or just use full paths with `:spawn`.

**Comment by jgkamat** [comment]
There are quite a lot of issues about this already, but I'll try to write everything that I know in one place for search-ability.

This is a problem because the path from `.profile` is not propogated to gui applications in mac os. There are some ways you [can set the PATH in mac os](https://serverfault.com/questions/16355/how-do-i-set-the-global-path-environment-variable-on-os-x), but I don't know how much success you'll have with that.

Workarounds:

1. Launch from the terminal, as you are doing now, to inherit the terminal's path
2. Use config.py to append the path values you want before the browser starts
3. Use absolute paths to any executables you run, instead of relying on PATH.

**Comment by jgillman** [comment]
Thanks @jgkamat! Sorry for the extra noise but I appreciate the compiled workarounds.

Would it be worth adding this as a "known" in the FAQ or Troubleshooting sections? idk how often this "issue" comes up.

**Comment by jgkamat** [comment]
This does come up quite a lot, so I would be fine with adding an entry to the FAQ personally. I don't have access to a Mac OS machine though, so I can't test/validate anything, so I can't be the one to write it :P

**Comment by jgillman** [comment]
PR incoming 😉

**Comment by Bounga** [comment]
I found another way to address this bug that I think is much better and will work for any GUI app.

You can add the extra needed paths in `/etc/launchd.conf` like so:

```
setenv PATH /usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```
Feed launchd with added values (it will be automatic after a restart, the following command is only necessary if you don't want to reboot):

```sh
egrep "^setenv\ " /etc/launchd.conf | xargs -t -L 1 launchctl
```

you can now restart your Dock and Spotlight:

```sh
killall Dock
killall Spotlight
```
Now every GUI app you launch inherit of this PATH env variable, either you launch it by clicking the icon in `Applications` folder or using Spotlight!

**Comment by tbsmn** [comment]
I have the same problem here. Can someone help me how to find the extra needed PATH?

Also with MacVim I have a very similar problem maybe the solution of @Bounga would fix this too. That would be awesome.

**Comment by The-Compiler** [comment]
@tbsmn Something like `which mpv` in a terminal should tell you where that binary is.

**Comment by tbsmn** [comment]
Thank you for that fast reply!
mpv is in `/usr/local/bin/mpv`

But @jgillman has two PATH depending how qutebrowser ist started.
> ### PATH when launched from command line
> ```
> PATH = /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jgillman/perl5/bin:/Users/jgillman/bin:/Users/jgillman/.dotfiles/bin:/usr/local/lib/node_modules:/Users/jgillman/node_modules/.bin:/Users/jgillman/.dotfiles/fzf/bin:/usr/local/sbin:/usr/local/opt/fzf/bin
> ```
> 
> ### PATH when lauched from .app
> ```
> PATH = /usr/bin:/bin:/usr/sbin:/sbin
> ```

 How can I get these?

**Comment by The-Compiler** [comment]
The easiest way is probably `:debug-pyeval os.environ['PATH']`.

**Comment by Bounga** [comment]
> Thank you for that fast reply!
> mpv is in `/usr/local/bin/mpv`
> 
> But @jgillman has two PATH depending how qutebrowser ist started.
> 
> > ### PATH when launched from command line
> > ```
> > PATH = /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jgillman/perl5/bin:/Users/jgillman/bin:/Users/jgillman/.dotfiles/bin:/usr/local/lib/node_modules:/Users/jgillman/node_modules/.bin:/Users/jgillman/.dotfiles/fzf/bin:/usr/local/sbin:/usr/local/opt/fzf/bin
> > ```
> > 
> > 
> > ### PATH when lauched from .app
> > ```
> > PATH = /usr/bin:/bin:/usr/sbin:/sbin
> > ```
> 
> How can I get these?

You should follow the instructions I added above.

This is related to how Mac OS application launcher (understand clicking the app icon or use spotlight) handle the PATH. It uses it’s own PATH variable that is set by launchd. 

When you start an app from the term it inherits from the term PATH. 

This is not true when using app launcher (which I can understand technically).

**Comment by tbsmn** [comment]
Thank you @The-Compiler and @Bounga this worked perfectly!

**Comment by zedkaido** [comment]
Opening `qutebrowser` from the `terminal` works but it's a bit inconvenient.
Instead, you can just set `os.environ['PATH']` in your `config.py`:
```python
import os
os.environ['PATH'] = '/Users/xusr/go/bin:/Users/xusr/.local/go/bin:/Users/xusr/.local/n/bin:/Users/xusr/.local/bin:/Users/xusr/.local/scripts:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/xusr/.nvm/versions/node/v16.17.1/bin:/Users/xusr/go/bin'
```
And simply set it to your usual `$PATH` value:
```bash
echo $PATH | pbcopy
```

**Comment by michaelfortunato** [comment]
For me, I just installed Bitwarden GUI and put in my `config.py`
```py
config.bind("<space>zp", "spawn open -a Bitwarden")
```
Which more than gets the job done!
