### ISSUE TITLE
What is the recommended way to change stylesheets at runtime (darkmode)?

### ISSUE THREAD

**Issue by iambumblehead** [qutebrowser/qutebrowser#4275]
I found a [related thread here,][0] but am wondering if there is a better solution. I'd like something that I could add to my config.py that might let me cycle through or enable/disable stylesheets.

[0]: https://github.com/qutebrowser/qutebrowser/issues/3325

**Comment by The-Compiler** [comment]
Better in what way? https://github.com/qutebrowser/qutebrowser/issues/3325#issuecomment-346248225 is still accurate, and you can use `config.bind()` to bind keys in config.py ([docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#binding-keys))

**Comment by iambumblehead** [comment]
thank you the following in config.py is working
```python
config.bind(',n', 'config-cycle content.user_stylesheets ~/software/solarized-everything-css/css/darculized/darculized-all-sites.css "" ;; reload')
```
