### ISSUE TITLE
':navigate up' should strip queries from URL

### ISSUE THREAD

**Issue by lyeoh** [qutebrowser/qutebrowser#4280]
Similar to #1318, `:navigate up` should take

`https://example.com/foo/?query=bar` to `https://example.com/foo`

since queries are specific to each page, and some websites use `https://example.com/?query=bar` whose parent is `https://example.com`.

I'd submit a pull request but I'm not sure whether [`url`](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/commands.py#L656) should be replaced with `url.adjusted(QUrl.RemoveQuery)` for all the options `up`, `increment`, and `down`, or if `up` should be handled independently.

**Comment by The-Compiler** [comment]
A few lines before the one you linked, `url = self._current_url().adjusted(QUrl.RemoveFragment)` is done - I think doing `QUrl.RemoveFragment | QUrl.RemoveQuery` instead there should be fine.

**Comment by steils** [comment]
It seems the issue is not resolved. Right now `:navigate up` replaces `https://example.com/foo/?query=bar` with `https://example.com` (and `https://example.com/foo?query=bar` with `https://example.com`).

I.e. with `count=1` it strips the queries and navigates up at once.

Can the issue be reopened?

**Comment by steils** [comment]
Alternatively we can leave it as it is, then I suggest to add a separate command `:navigate strip` from stripping queries from the current URL: https://github.com/qutebrowser/qutebrowser/pull/4438
It may seem a bit redundant though.

**Comment by The-Compiler** [comment]
@steils I don't follow. An issue about `:navigate up` **not** stripping queries should be reopened because it strips queries, and you want to fix that by adding a command to strip queries?

I'm confused - can you explain on what your goal is? :slightly_smiling_face:

**Comment by steils** [comment]
@The-Compiler Sorry if I'm not clear enough.
In the original message it is written that `:navigate up` should do:
`https://example.com/foo/?query=bar` => `https://example.com/foo`
but after https://github.com/qutebrowser/qutebrowser/pull/4282/commits/1b8e1a9ea4627b250a38f27e5a97e6e2583db922 it does:
`https://example.com/foo/?query=bar` => `https://example.com`.

Yes, it strips queries now, but it strips _too much_. My goal is to be able to do `https://example.com/foo/?query=bar` => `https://example.com/foo` either with `:navigate up` or a separate command :-)

**Comment by The-Compiler** [comment]
@steils Ah, I see! That probably just was a typo by @lyeoh, as the whole point of `:navigate up` is to remove a path part - before 1b8e1a9 it did `https://example.com/foo/?query=bar` => `https://example.com?query=bar`.

I'm fine with adding a `:navigate strip`, but out of curiosity, what kind of page would you use it for?

**Comment by steils** [comment]
@The-Compiler 
> I'm fine with adding a `:navigate strip`

Thanks! I'll check those failing tests and resend the PR then.

> but out of curiosity, what kind of page would you use it for?

Lots of them in the Internet. Like this:
https://www.facebook.com/nixcraft/photos/a.431194973560553/2383397745006923/?type=3&eid=ARBGKvPZdmbIQUi_GoiD1S_pkasiCyI2CeB8FUcfAyZ9SXoeQCkBlnOe8e1uPxlLsxghtFOenFVD0zvJ&__xts__%5B0%5D=68.ARApbbft3G7g6pvbtNsN_MBOuENHUdv2K0n7m5hudOhhamp9ZS5abD2S7r4BNOu9EaDUipUKQvDSbFmRf6IeoFzyJrG3G_7Qt9ATRHGQ9bUq_wG1aI-obz7pvX6W5RZTLo-NKtIadfwMHNO1XFRwIZnJuyZgXDkkQ772tfYv50f-IDkVRFnCCsJ8MZRjmd9H8iQ0n5bM6T2f32Y4vMgG-CGnKn0FeUg8-gzkictQuf2BUbpqIPiQY7_vYeUhZQYEAS0wu5KPSa0rVQgITMfw9rvIwneWNnIwwS-ehRdizf50Svfsec4yKpsll2s3d1rsu8ST10eomyrorSOcOj7sMjbHAA&__tn__=EEHH-R

It's a real link in Facebook. Generally when I want to send a link to a friend I'd like to remove all this nonsense from the URL: https://www.facebook.com/nixcraft/photos/a.431194973560553/2383397745006923

Another example: https://github.com/mgorny?tab=repositories (=> `https://github.com/mgorny`)

In case of labels it could be any page on Wikipedia like https://en.wikipedia.org/wiki/History_of_the_Byzantine_Empire#Rise_of_the_Ottomans_and_fall_of_Constantinople (=> `https://en.wikipedia.org/wiki/History_of_the_Byzantine_Empire`)

**Comment by The-Compiler** [comment]
Thanks for the examples! Yeah, I now agree that seems like an useful thing to have. Note you don't have to resend the PR, you can just push new commits to your `gs` branch and the PR will automatically update.
