### ISSUE TITLE
Google Drive documents reloads forever

### ISSUE THREAD

**Issue by VictorBjelkholm** [qutebrowser/qutebrowser#4284]
```
[1002/163259.962505:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glnKuoh1 (deleted)
  Error: No such file or directory
qutebrowser v1.4.2
Git commit:
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2 (compiled 5.11.1)
PyQt: 5.11.2

sip: 4.19.12
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.25.1
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.9-arch1-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable pa
```
When opening documents in Google Drive via qutebrowser, it seems they are stuck in a reload-bug and continuous to reload forever. Seems the reload happens as soon as the reload is done, and never stops, making it impossible to do anything in the editor itself.

Test document: https://docs.google.com/document/d/1EmSok0UXnr9CpzCTkWxfqDt7paaDlM3vApq3FAE9l-8/edit

Only seems to happen when logged in to Google, as starting with `qutebrowser -T` doesn't reproduce the issue.

**Comment by VictorBjelkholm** [comment]
Oh, actually, I changed the permissions so anyone can edit the document above, and now can be reproduced with new basedir as well. Seems to be related to documents you can edit only.

**Comment by The-Compiler** [comment]
So you can reproduce this with `--temp-basedir`? I do see a couple of initial loads, but then all seems to work fine.

**Comment by jgkamat** [comment]
I can't reproduce as well

**Comment by VictorBjelkholm** [comment]
Yeah, that's true, leaving the page running for 30 seconds seems to finish the loads and eventually I can edit. Sorry for the noise.
