### ISSUE TITLE
Specify path to config.py on cli / via environment

### ISSUE THREAD

**Issue by xaverdh** [qutebrowser/qutebrowser#4285]
As far as I can see, there is no way to pass a custom path for config.py to qutebrowser.
This is desirable, because it allows, e.g. system wide configuration by creating a wrapper or similar.

I know that its possible to specify the base directory, but it makes sense to seperate configuration
(which may be system wide) from bookmarks, cached data, etc. which probably should be a per user thing.

**Comment by The-Compiler** [comment]
Duplicate of #4132
