### ISSUE TITLE
pdfjs buttons do not display properly

### ISSUE THREAD

**Issue by twosheds-jackson** [qutebrowser/qutebrowser#4289]
I'm very happy that pdfjs support has been added for QtWebEngine, but the buttons do not display properly on my system. They are clickable, functional, and their hover-over text is properly displayed, but the buttons themselves are not visible. See the attached screenshot:

![screenshot](https://user-images.githubusercontent.com/42011922/46435749-17188380-c725-11e8-8a4f-e878838d03cd.png)

Qutebrowser, QtWebEngine, and pdfjs are all from the Arch Linux repository. Version information:

qutebrowser v1.5.0
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2 (compiled 5.11.1)
PyQt: 5.11.2

sip: 4.19.12
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.10.100 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

**Comment by The-Compiler** [comment]
Does it work with `--temp-basedir`? If so, can you show `:open qute://configdiff`?

**Comment by The-Compiler** [comment]
Odd. If you start with `qutebrowser --temp-basedir -s content.pdfjs true --debug http://static.musictheory.net/pdf/blank.pdf`, do you see this as well? If so, can you please do `:report` so I can take a look at the logs?

**Comment by twosheds-jackson** [comment]
The buttons are still not visible, and I'm noticing in the log that it's not able to find the images. The log:
[log.txt](https://github.com/qutebrowser/qutebrowser/files/2443755/log.txt)

**Comment by The-Compiler** [comment]
And e.g. `/usr/share/pdf.js/web/images/toolbarButton-zoomIn.png` does exist on your system?

**Comment by The-Compiler** [comment]
Ah, nevermind, I still had a newer (bundled) version of PDF.js on my system. I can reproduce it with the Arch package.

**Comment by Foxboron** [comment]
I have added a fix in the package and published `1.10.100-2` for pdfjs.

**Comment by twosheds-jackson** [comment]
Upon closer inspection, the permissions of the images in /usr/share/pdf.js/web/images/ appear to be the culprit. They're only readable by root. I expect the Arch pdfjs package is at fault here.

**Comment by The-Compiler** [comment]
Hey, @Foxboron, where did you get that time machine from? :wink:

**Comment by Foxboron** [comment]
We have a secret DeveloperWiki. It lists some cheat codes....

**Comment by The-Compiler** [comment]
I've also reported this at https://github.com/mozilla/pdf.js/issues/10132 - I'll also update qutebrowser to log clearer error messages if this happens.
