### ISSUE TITLE
closing tab or opening it in background shows tab bar with tabs.show = never

### ISSUE THREAD

**Issue by asmbits** [qutebrowser/qutebrowser#4295]
Updated to new version. I dont use tab bar at all but now it always appears anytime I close tab or open a new tab in background.

**Comment by The-Compiler** [comment]
Whoops, this is probably because https://github.com/qutebrowser/qutebrowser/blob/v1.5.0/qutebrowser/mainwindow/tabwidget.py#L218-L237 doesn't check whether it was visible in the first place... cc @jgkamat

**Comment by jgkamat** [comment]
Ah, that seems right, I forgot to check for that case, sorry. I'll submit a PR fixing it in ~3 hours if @The-Compiler dosen't beat me

**Comment by The-Compiler** [comment]
The fix seems easy:

```diff
diff --git a/qutebrowser/mainwindow/tabwidget.py b/qutebrowser/mainwindow/tabwidget.py
index 9a8fdbc64..398f9a826 100644
--- a/qutebrowser/mainwindow/tabwidget.py
+++ b/qutebrowser/mainwindow/tabwidget.py
@@ -225,8 +225,9 @@ class TabWidget(QTabWidget):
         non-visible. To avoid flickering, disable repaint updates whlie we
         work.
         """
-        toggle = self.count() > 10
         bar = self.tabBar()
+        toggle = self.count() > 10 and bar.isVisible()
+
         if toggle:
             bar.setUpdatesEnabled(False)
             bar.setVisible(False)
```

but it'd be great to also have a test, and I'm going to bed :wink:
