### ISSUE TITLE
External protocols not working

### ISSUE THREAD

**Issue by Targuinius** [qutebrowser/qutebrowser#4299]
Since updating to qutebrowser 1.4.2, I can no longer use nxm:// links, used by nexusmods.com. It used to be buggy, because it tried to open it in qutebrowser itself instead of the external application, but I have a bind "spawn cmd /c start {url}", that will open these links correctly.

Now, I get a page "chrome-error://chromewebdata/", instead of for example "nxm://skyrim/mods/78942/files/1000221856", so this bind also no longer works.

[My current version](https://paste.the-compiler.org/view/b20c2279)
I hadn't updated in a while, so before 1.4.2, I used 1.3.2, I believe.

To reproduce, go to a nexusmods mod (eg https://www.nexusmods.com/skyrim/mods/78942?tab=files), then click "mod manager download", but I believe you need an account to use the mod manager links.

**Comment by The-Compiler** [comment]
It's a Qt bug, see https://bugreports.qt.io/browse/QTBUG-63378
