### ISSUE TITLE
messenger: nothing displayed with custom colors

### ISSUE THREAD

**Issue by rotsix** [qutebrowser/qutebrowser#4302]
Hi

Here is my `:version`: https://paste.the-compiler.org/view/4d6e0e9e

And here is the problem:

When using Messenger (on both facebook.com/messenger and messenger.com), if you have custom colors on a discussion, it will not display anything, and going back to a default colored discussion doesn't fix it until you reload without cache (with 'R'  - `reload -f`).

Tell me if you need anything,
Regards,
rotsix

**Comment by The-Compiler** [comment]
Can you reproduce this when starting with `--temp-basedir`? If so, can you please show `:open qute://configdiff`?

**Comment by rotsix** [comment]
You're right, no problem with `--temp-basedir`, any idea where it could come from?

**Comment by rotsix** [comment]
Here is my config.py: https://ptpb.pw/Aw52.py

**Comment by rotsix** [comment]
Fixed, this came from the modified user-agent..
Restoring to default one (empty) solved my problem, now I close :)

**Comment by The-Compiler** [comment]
Claiming to be Firefox when it isn't really Firefox is a bad idea...

**Comment by rotsix** [comment]
Yep, but had an issue one day, and someone told me to set the user-agent on Firefox and it worked, so I used to keep it on
