### ISSUE TITLE
qute://pdfjs URLs can't be saved in sessions

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4303]
_Originally posted by @user202729 in https://github.com/qutebrowser/qutebrowser/issues/2330#issuecomment-427582068_:

> (Possible issue: Using temporary URL for pdfjs means it doesn't work when the browser is closed&reopened. For example with `ZZ`. Ideally the original URL should be displayed)

**Comment by user202729** [comment]
Ideally the PDF viewer should not open in a new tab (i.e., the URL points to the PDF, not the viewer), which will also fix #4262 .

However `QWebEngine` doesn't appear to allow this (there is no `unsupportedContent`, only `downloadRequested`)

As a workaround, I suggest having a `original_url` field (so the URL looks like this `qute://pdfjs/web/viewer.html?original_url=file:///name.pdf&filename=tmpzzz_name.pdf&file=` and the viewer redirects to the `original_url` if the temporary file is not found.
