### ISSUE TITLE
Trouble setting terminus as a monospaced font for some elements

### ISSUE THREAD

**Issue by cancercufasole** [qutebrowser/qutebrowser#4307]
qute:version: https://paste.the-compiler.org/view/1e3086bd
config: http://ix.io/1ovZ
terminus from the archlinux repos

I cannot seem to be able to set terminus as a monospaced font for various font settings except for tabs.
If I use --temp-basedir then :set statusbar.position top and :set font.statusbar "xos4 Terminus" ( even though in this case it's already terminus ) it will default to some other font.

**Comment by The-Compiler** [comment]
Do you have a screenshot?

**Comment by cancercufasole** [comment]
yes
https://my.mixtape.moe/uhmwks.png

**Comment by cancercufasole** [comment]
I'm closing this since I tried the config on another system with the same packages and I could not replicate it. 
I'm suspecting it's some dpi fuckery on my laptop/current config.
