### ISSUE TITLE
Performance regressions in 1.5.0

### ISSUE THREAD

**Issue by SirCmpwn** [qutebrowser/qutebrowser#4308]
I apologise for not having more detailed information yet. I've noticed since upgrading that a lot of things are slower in qutebrowser - the command entry lags behind my typing when there are lots of items to complete, and when I have enough tabs open (>8 or so) the whole window flashes white for almost half a second when a new tab is opened.

**Comment by The-Compiler** [comment]
The window flashing is already fixed in the latest git master (0caff547aa6972adc208e851c29835be52282fe6). I'm not aware of any big changes to the completion, so I'll need more information there.

**Comment by SirCmpwn** [comment]
Oh, I'm dumb, this is clearly because of the `completion.web_history.max_items` change. Glad that the flashing issue is unrelated & fixed.
