### ISSUE TITLE
Getting actual url of a download

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#4318]
Some sites don't provide a direct link to a file, but generate it after pressing a button. At that moment qutebrowser starts downloading with its internal downloader. Is it possible to obtain the actual url that qutebrowser downloads from?
I need it to use another downloader which can continue unfinished downloads and do other things.

---
I'm not sure, but https://github.com/qutebrowser/qutebrowser/issues/2343 looks like a more generalized way to solve the issue, right?

**Comment by The-Compiler** [comment]
You can do `:prompt-yank` (`Alt+y`) in the download prompt to get the URL there.

**Comment by sudo-nice** [comment]
Thanks! Having `c.downloads.location.prompt = False` I didn't even know about that.
