### ISSUE TITLE
File browser navigation

### ISSUE THREAD

**Issue by einhander** [qutebrowser/qutebrowser#4319]
It would be great if download-upload file browser supports vim-like navigation, like it done in ranger file manager.

**Comment by The-Compiler** [comment]
How would that work, seeing that you also can enter a path?

**Comment by einhander** [comment]
Like it done in ranger, or use insert mode.

**Comment by The-Compiler** [comment]
I'd rather not implement vim-like navigation there, I think the current way of entering parts of a path and tabbing is much more efficient.

**Comment by einhander** [comment]
Did you ever tried to navigate in mixed langudes folder, with more then ten characters long?
It's really painfull.

**Comment by The-Compiler** [comment]
How so? Type a letter or two and hit the tab key.

**Comment by einhander** [comment]
It's more like this:
Type letter, switch languge, tab, switch languge, tab, slash, swith languge, letter, tab,  slash  and so on.

**Comment by mschilli87** [comment]
How about instead of introducing new complexity in qutebrowser to support this and all other use cases to introduce a way to spawn an external file browser (just like qutebrowser's form editor does not re-implement vim but <kbd>Ctrl</kbd>+<kbd>E</kbd> can give me just this, notepad, or even emacs)? :wink:

**Comment by einhander** [comment]
@mschilli87  I like your idea,  if Ctr+E will spawn ranger (or other FM) to navigate the desired directory, it will be more than enough.

**Comment by einhander** [comment]
@The-Compiler Thank you, I'll try your advice.

**Comment by NoctuaNivalis** [comment]
Confirming these bindings work pretty good:

```python
config.bind("<Alt+j>", "prompt-item-focus next", mode="prompt")
config.bind("<Alt+k>", "prompt-item-focus prev", mode="prompt")
config.bind("<Alt+l>", "fake-key -g /", mode="prompt")
config.bind("<Alt+h>", "rl-unix-filename-rubout", mode="prompt")
```
