### ISSUE TITLE
Segfault with webengine on youtube

### ISSUE THREAD

**Issue by yschaeff** [qutebrowser/qutebrowser#4326]
**Version info (see `:version`)**: 
1.5.0
https://paste.the-compiler.org/view/0110e49d

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes

**Description**
Since the upgrade to 1.5.0 Qutebrowser crashes with a segfault on a lot of content rich / flashy websites. Most notably on Youtube when trying to play a video. My guess is that it is not because of a qutebrowser change since I also upgraded many other packages. A downgrade to the previous version still made the browser crash in the same way. (I can no longer downgrade now, old version is removed from package manager)

Starting with webkit backend resolves the issue for me.

qutebrowser -d --backend webengine -T --nocolor 2> segv
https://pastebin.com/JZeq0ic2

**How to reproduce**
On webengine backend, go to youtube.com and click a video

**Comment by jgkamat** [comment]
This smells like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910317 to me.

**Comment by toofar** [comment]
It's possible http://snapshot.debian.org/ could help with downgrades but not sure what would need to be downgraded, that bug report mentions one library but not very convincingly.
