### ISSUE TITLE
Global config file e.g. "/etc/qutebrowser/config.py"

### ISSUE THREAD

**Issue by nrdxp** [qutebrowser/qutebrowser#4327]
I am building up a configuration to switch to nixos (currently on arch) and one of the biggest issues I am having is with qutebrowser only reading its config locally. If I try to set the config file into nixos' /etc/ directory and use the XDG_CONFIG_HOME variable I still have issues because this directory is not writable and qutebrowser complains and refuses to start.

I am currently working around this by using my shell initialization script to make the etc directory writable but this is a bit of a hack.

Instead of messing with the XDG_CONFIG_HOME I feel it would be much cleaner if there were a global configuration file that qutebrowser could source. This way each user could still have their own local config that would override the global if they chose, while any changes to the global configuration could still be written to the local config directory, keeping the global config pristine.

An additional alternative which would work similarly would be to simply add the ability to specify the config file to load from the command line whilst still writing changes to the current local config dir. Whichever the developers would prefer.

**Comment by toofar** [comment]
There is a PR up for being able to specify the config.py location https://github.com/qutebrowser/qutebrowser/pull/4286

**Comment by The-Compiler** [comment]
You can also do `config.source('/etc/qutebrowser/config.py')` or whatever in your per-user `config.py`, see ["Importing other modules"](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#importing-other-modules).

I'd rather not read a file in `/etc` by default I think.
