### ISSUE TITLE
Processes hang after exit

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#4337]
**Version info**:
qutebrowser v1.5.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.10.100 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.12-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:
Did not test because I cannot reproduce the issue consistently.

**Description**
I often find `qutebrowser` processes in my system even if I don't have the browser open. Seems that the process does not always exit when I close the browser. If I don't clean up the processes manually, multiple "dead" processes may accumulate. The processes still consume non-trivial amounts of memory.

It seems that this issue happens only after extended periods of browsing. I cannot reproduce it by opening and then soon closing the browser.

I remember this also occuring on some versions before 1.5.x.

**Comment by jgkamat** [comment]
I've seen this too, but only twice (and I haven't been able to reproduce after that). Maybe the next time it happens, someone should try to get some strace output or using [gdb to find out what the python process is doing](https://wiki.python.org/moin/DebuggingWithGdb).

**Comment by The-Compiler** [comment]
How do you quit qutebrowser? Do you also see `QtWebEngineProcess` processes?

**Comment by Ape** [comment]
I have `tabs.last_close` set to `close` and close the browser pressing `d` to close the last tab.

**Comment by The-Compiler** [comment]
This sounds like [QTBUG-49804](https://bugreports.qt.io/browse/QTBUG-49804).
