### ISSUE TITLE
Command: Add to saved session

### ISSUE THREAD

**Issue by rakanalh** [qutebrowser/qutebrowser#4338]
Hello,

I like the fact that i can use the command: `session-save -o [session-name]` to save tabs for pages that i'd like to read later on. What i am missing right now is, if i have a saved-session that doesn't have a window open, i can't use `tab-give` or `tab-take`, so it would be very nice if a command such as `session-append` which takes the current tab and appends it to a saved session.

Thank you.

**Comment by The-Compiler** [comment]
Duplicate of #3853
