### ISSUE TITLE
Render Process Crashed immediately upon startup - qutebrowser literally unuseable

### ISSUE THREAD

**Issue by LucaSeem2000** [qutebrowser/qutebrowser#4345]
**Version info (see `:version`)**:

_*N.B.:* This issue occurs with both the [Void Linux](https://voidlinux.org) package, and also if I clone the git repo and run `qutebrowser.py` from there._

I also use musl libc, *I do not use glibc*.

***Cloned Directly from GitHub Repository***
```
$ ./qutebrowser.py -V
qutebrowser v1.5.1
Git commit: 8a6226901 (2018-10-16 12:30:19 +0200)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.6
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.25.2
QtNetwork SSL: LibreSSL 2.7.4

Style: QFusionStyle
Platform: Linux-4.18.14_1-x86_64-with-libc, 64bit
Linux distribution: void (void)
Frozen: False
Imported from /home/luca/qutebrowser/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/luca/.cache/qutebrowser
config: /home/luca/.config/qutebrowser
data: /home/luca/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):

Yes, in both versions.

**Description**

I start up qutebrowser, and the webpage renders and a flash of the webpage appears, but then immediately the browser turns white, and errors appear in the title bar.

I have attached a log file which includes the output of
`$./qutebrowser.py -l vdebug &> log`
where `qutebrowser.py` is from the cloned GitHub repository specified above.

Note that this file is about 7.3 MB.
[log.txt](https://github.com/qutebrowser/qutebrowser/files/2483053/log.txt)

**How to reproduce**
For my system, the error is reproduceable 100% of the time.

I will obviously readily provide any more information.

**Comment by The-Compiler** [comment]
That seems to be some issue with QtWebEngine on musl/Void, see e.g. https://github.com/void-linux/void-packages/issues/2368
