### ISSUE TITLE
Exiting video player exits fullscreen

### ISSUE THREAD

**Issue by Heife** [qutebrowser/qutebrowser#4349]
**Version info (see `:version`)**:
qutebrowser v1.5.1
Git commit: c7a21b37e-dirty (2018-10-10 08:23:17 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.10.100 (bundled)
sqlite: 3.24.0
QtNetwork SSL: Secure Transport, macOS 10.14

Style: QMacStyle
Platform: Darwin-18.0.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.14, x86_64

**Description**
On MacOS, when exiting fullscreen mode in any video player the whole browser will exit fullscreen mode. 
**How to reproduce**
Go to any video playing site. E.g youtube.com
Fullscreen the video
Exit the fullscreen

**Comment by toofar** [comment]
It also does this on linux under Xorg.

**Comment by jgkamat** [comment]
I noticed this too, thanks for reporting.

The code to fix this is [here](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/mainwindow/mainwindow.py#L516-L521).

Weirdly, it seems to have been introduced in 559059d244ccf95c56bd1c6f982f700ce13aa038, which was added in #3482, a PR which was trying to solve this problem...

**Comment by helbling** [comment]
I can confirm the bug.
In 559059d and cd20c329 I got rid of the state variable window.state_before_fullscreen as the behaviour seemed to be correct at the time.
This is definitely no longer the case and we need to revert these commits.

First tests look good.
I will prepare a pull request.
