### ISSUE TITLE
Change 'bot' to 'btm'.

### ISSUE THREAD

**Issue by def14nt** [qutebrowser/qutebrowser#4350]
Just a small annoyance, but I was a bit confused with the meaning of `bot` in the bottom bar. In my opinion, the word `btm` is obviously bottom, but `bot` had me thinking it was running some sort of script.

**Comment by The-Compiler** [comment]
"bot" is used in vim and probably pretty much any vim-like browser out there. I also find "btm" harder to understand. So I'm going to say no to that one :wink:

**Comment by jgkamat** [comment]
Shameless plug for [qutenyan](https://gitlab.com/jgkamat/qutenyan) which is much clearer than any non nyan-based scrolling indicator
