### ISSUE TITLE
[request] possible headless mode?

### ISSUE THREAD

**Issue by nrdxp** [qutebrowser/qutebrowser#4365]
I would like to run :adblock-update from the command line without an x-display running for scripting purposes. I know there is the --nowindow flag but this still requires an x display to at least be running.

I know chrome has a builtin headless mode but when I run  'qt-flag headless' it seems to have no effect. Would there be a simple way to do this with either backend? Or is my conceptualization of this incorrect?

**Comment by jgkamat** [comment]
Are you just trying to update adblock lists on a timer? Why not just run it in the existing instance (if one is runnung). I'm not sure what the use case of this is...

**Comment by sudoforge** [comment]
why not just use [`hostsctl`][0] to block advertisers and more at the system level instead of using a browser-specific solution?

[0]: https://github.com/pigmonkey/hostsctl
