### ISSUE TITLE
Error when following a hint label containing `;;`

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#4368]
https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/keyinput/modeparsers.py#L295 will create a command containing `;;` in that case.

Fix: We can either

* Escape the special characters (is there any existing function that does this?)
* Make `bindings` property of `BaseKeyParser` a dict from keys to *parsed command object*, not a *command string* -- that way there would probably be some performance improvement too (no need to parse commands)

**Comment by The-Compiler** [comment]
There isn't a way to escape `;;` right now (see #1861). I guess the second option sounds reasonable, but I probably won't be able to review any bigger refactorings right now (see those two announcements: [one](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2018-September/000051.html), [two](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2018-October/000053.html)).

**Comment by user202729** [comment]
@The-Compiler Yes there is, using backslashes. Replacing `s` with `s.replace(';', '\\;')` works fine -- but there are also other meta characters (backslashes, quotes, ...)
