### ISSUE TITLE
Kindle cloud reader

### ISSUE THREAD

**Issue by rpietro** [qutebrowser/qutebrowser#4369]
qutebrowser v1.4.2
Backend: QtWebEngine

This used to work perfectly. Way to reproduce it is to try to log in to https://read.amazon.com/ . Log in works, but then the app won't show the books, with a msg saying "error saving app." I tried ':set content.cookies.accept all' but it didn't make a difference. Also tried to close and reopen qutebrowser. I then moved to Private Mode, logged in in the exact same way I did before, and the app worked perfectly. Could this be related to cache?

**Comment by The-Compiler** [comment]
That does sound like something related to your cookies or other persistent data. Does it work when closing qutebrowser and moving `~/.local/share/qutebrowser` away? if not, what about `~/.cache/qutebrowser`?

**Comment by rpietro** [comment]
I was about to try that and things just went back to normal without doing anything. One of those situations where I wish I still had the problem so that we could investigate further. I will keep an eye on this and will try both approaches if the issue comes back.
