### ISSUE TITLE
Hidden elements get hint labels in pastebin

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#437]
On e.g. http://paste.the-compiler.org/view/a76e0750 when the window is resized so the menu collapses, the hidden elements get hint labels:

![hintfail](https://cloud.githubusercontent.com/assets/625793/5603941/76eb66ca-939d-11e4-869d-629c109667e2.png)

**Comment by ff2000** [comment]
On e.g. forums.gentoo.org I also see issues with hinting, don't know if it the same:
![Bug Screenshot](https://lh3.googleusercontent.com/BCNv5Y-KxPxvOx8uE1mGWi52TQN7Ykmc8Xpf-7Bb0w=w537-h207-p-no)
The "forumpointer" arrow gets a hint label though it is no link.

**Comment by The-Compiler** [comment]
In the pastebin it looks like this:


```html
<div class="nav-collapse collapse" style="height: 0px;">
							<ul class="nav">
																<li><a href="http://paste.the-compiler.org/" title="Create A New Paste">Create</a></li>
								<li><a class="active" href="http://paste.the-compiler.org/lists" title="Recent Pastes">Recent</a></li>
								<li><a href="http://paste.the-compiler.org/trends" title="Trending Pastes">Trending</a></li>
								<li><a href="http://paste.the-compiler.org/api" title="API">API</a></li>
								<li><a href="http://paste.the-compiler.org/about" title="About">About</a></li>
							</ul>
						</div>
```

And the `height: 0px` for the parent element causes it to not be shown.

**Comment by The-Compiler** [comment]
I don't think it's possible to do anything about this without a big performance hit.
