### ISSUE TITLE
Print command produce raster PDF file

### ISSUE THREAD

**Issue by einhander** [qutebrowser/qutebrowser#4374]
**Version info (see `:version`)**:
qutebrowser v1.5.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.1
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.18.0-2-amd64-x86_64-with-debian-buster-sid, 64bit
Linux distribution: Debian GNU/Linux buster/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/einhander/.cache/qutebrowser
config: /home/einhander/.config/qutebrowser
data: /home/einhander/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 2:44:57
**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
yes
**Description**
Print command produce raster PDF file.
I don't know is it bug or feature.
But raster PDF files have a lot of disadvantages: slow printing, unselectable text, it cannot be printed in high quality etc.

**How to reproduce**
Type :print select print to PDF.

UPD: it happens with all pages, with pdf.js too.

**Comment by user202729** [comment]
Does that happen when you use PDF.js "print" button?

**Comment by einhander** [comment]
It happens with all pages, with pdf.js too.

**Comment by user202729** [comment]
Probably because of https://stackoverflow.com/questions/50349969/qwebenginepage-print-to-pdf-doesnt-print-selectable-text-in-the-pdf-like-google .

**Comment by einhander** [comment]
You are probably right. Is some workarounds available to produce selectable pdfs.

**Comment by The-Compiler** [comment]
Works for me when using `:print --pdf` instead.

**Comment by einhander** [comment]
Thank you @The-Compiler `:print --pdf` produce selectable pdf.
