### ISSUE TITLE
Remove support for OS X El Capitan

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4380]
It looks like Apple doesn't release [security updates](https://support.apple.com/en-us/HT201222) for OS X 10.11 (El Capitan) anymore since 10.13 (Mojave) is out, and Homebew [also dropped it](https://brew.sh/2018/10/23/homebrew-1.8.0/).

Qt 5.12 in December is most likely also going to drop it, so I'd like to follow that and require macOS Sierra for the next feature release.

**Comment by The-Compiler** [comment]
Just tried running Qt 5.12, and indeed, it only runs on 10.12 (Sierra) or newer. Just opened a ticket to upgrade my Mac Mini.

**Comment by qvtqht** [comment]
What is the last version of qutebrowser which will run on El Capitan? I'm currently using a machine with El Capitan which I cannot upgrade.

**Comment by The-Compiler** [comment]
@qvtqht See the [changelog](https://qutebrowser.org/doc/changelog.html) - support was dropped in v1.6.0. You could perhaps get v1.14.1 to work if you build a `.dmg` yourself with Qt 5.11:

- Edit `tox.ini`, and in `[testenv:build-release]`, replace `-r{toxinidir}/misc/requirements/requirements-pyqt.txt` to use `requirements-pyqt-5.11.txt` instead
- Set up Python and tox on your machine
- Run `tox -e build-release`

**Comment by qvtqht** [comment]
Thanks, I'll give it a try.
