### ISSUE TITLE
Browser stops redrawing when any window is out of focus on wayland.

### ISSUE THREAD

**Issue by Philz69** [qutebrowser/qutebrowser#4389]
Under wayland, the browser stops redrawing and does not respond to input if one of the windows is not visible. The browser does not completely hang, as audio does not freeze. 
I should mention it works as expected when launched without QT_QPA_PLATFORM=wayland.

As soon as one of the windows goes out of view, the debug lug mentions this:
`DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None`
And then absolutely nothing happens until the windows are brought back to view.

I dont know if this is related, but when initially opening a new window, the log mentions:
`WARNING: Wayland does not support QWindow::requestActivate()`
but it is never mentionned again. 

Steps to reproduce:

- Open qutebrowser in workspace 1,
- Open a new window,
- Switch one of the two windows to a non visible workspace,

Steps to unfreeze:

- Bring both windows into visible workspaces again.

I am launching qutebrowser with
```
QT_QPA_PLATFORM=wayland
QUTE_SKIP_WAYLAND_CHECK=1
```
And I am using Sway ( I tried with both the latest commit and 1.0 Beta ) 

Here is the version info:
```
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.1
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.4.0
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.10.100 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/phil/.cache/qutebrowser
config: /home/phil/.config/qutebrowser
data: /home/phil/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```

**Comment by jgkamat** [comment]
To me at least, this seems like a bug in qtwebengine wayland support. Can you
check to see if Falkon exhibits the same problem (there's an option to open
new windows in its menu)? I don't think the debug log entry should matter in
this case.

Philz69 writes:

> Under wayland, the browser stops redrawing and does not respond to input if one of the windows is not visible. The browser does not completely hang, as audio does not freeze.
> I should mention it works as expected when launched without QT_QPA_PLATFORM=wayland.
>
> As soon as one of the windows goes out of view, the debug lug mentions this:
> `DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None`
> And then absolutely nothing happens until the windows are brought back to view.
>
> I dont know if this is related, but when initially opening a new window, the log mentions:
> `WARNING: Wayland does not support QWindow::requestActivate()`
> but it is never mentionned again.
>
> Steps to reproduce:
>
> - Open qutebrowser in workspace 1,
> - Open a new window,
> - Switch one of the two windows to a non visible workspace,
>
> Steps to unfreeze:
>
> - Bring both windows into visible workspaces again.
>
> I am launching qutebrowser with
> ```
> QT_QPA_PLATFORM=wayland
> QUTE_SKIP_WAYLAND_CHECK=1
> ```
> And I am using Sway ( I tried with both the latest commit and 1.0 Beta )
>
>
> Here is the version info:
> ```
> qutebrowser v1.5.2
> Git commit:
> Backend: QtWebEngine (Chromium 65.0.3325.230)
>
> CPython: 3.7.1
> Qt: 5.11.2
> PyQt: 5.11.3
>
> sip: 4.19.13
> colorama: 0.4.0
> pypeg2: 2.15
> jinja2: 2.10
> pygments: 2.2.0
> yaml: 3.13
> cssutils: no
> attr: 18.2.0
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebKitWidgets: yes
> pdf.js: 1.10.100 (/usr/share/pdf.js/build/pdf.js)
> sqlite: 3.25.2
> QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018
>
> Style: QFusionStyle
> Platform: Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch, 64bit
> Linux distribution: Arch Linux (arch)
> Frozen: False
> Imported from /usr/lib/python3.7/site-packages/qutebrowser
> Using Python from /usr/bin/python3
> Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
>
> Paths:
> cache: /home/phil/.cache/qutebrowser
> config: /home/phil/.config/qutebrowser
> data: /home/phil/.local/share/qutebrowser
> runtime: /run/user/1000/qutebrowser
> system data: /usr/share/qutebrowser
> ```

**Comment by Philz69** [comment]
You are right, this is a qtwebengine issue! Thank you!

**Comment by jgkamat** [comment]
Philz69 writes:

> You are right, this is a qtwebengine issue! Thank you!

FWIW, if you report a bug to qt, please link the issue here as well, so people
can follow it in the tracker there :)

**Comment by The-Compiler** [comment]
This sounds like https://bugreports.qt.io/browse/QTBUG-69077

**Comment by edrex** [comment]
Glad to see this is known. I hit it in both qutebrowser and falkon, and didn't realize it was the same issue.

**Comment by The-Compiler** [comment]
That fix got reverted, but a proper fix now got [merged](https://codereview.qt-project.org/#/c/251380/) for Qt 5.12.4.
