### ISSUE TITLE
Support URL patterns in content.cookies.* settings

### ISSUE THREAD

**Issue by lufte** [qutebrowser/qutebrowser#4393]
I've noticed some sites need to store 3rd party cookies in order to work, but I don't want to allow all sites to do that.

Doesn't seem that hard to implement from what I could see. I'm willing to work on it if you think it could be useful.

Also, I'm aware of the current situation regarding contributions; no rush :snail:

**Comment by lufte** [comment]
Nevermind, it's already here #3636

**Comment by The-Compiler** [comment]
> Doesn't seem that hard to implement from what I could see. I'm willing to work on it if you think it could be useful.

Definitely would be! Would be nice if you could also look into writing a test for it, though.

> Also, I'm aware of the current situation regarding contributions; no rush :snail: 

Thanks for letting me know! :+1:
