### ISSUE TITLE
60 Hz instead of the actual display refresh rate

### ISSUE THREAD

**Issue by YaLTeR** [qutebrowser/qutebrowser#4397]
**Version info (see `:version`)**: https://paste.the-compiler.org/view/3e0e4247

**Does the bug happen if you start with `--temp-basedir`?** (if applicable): Yes

**Description**
qutebrowser is assuming a 60 Hz display regardless of the actual display refresh rate. This leads to stuttering, unsmoothness and incorrect vsync. On the image below I have https://vsynctester.com open in Firefox and qutebrowser, observe how Firefox is correctly updating at 144 Hz while qutebrowser is updating at 60 Hz.

![image](https://user-images.githubusercontent.com/1794388/47711627-b195b500-dc46-11e8-8b4b-d79b9f5f860b.png)

**How to reproduce**
Open https://vsynctester.com and check the FPS / refresh rate it displays.

**Comment by The-Compiler** [comment]
I can't find it anymore right now, but I looked at this some while ago, and this turned out to be a QtWebEngine/Chromium issue.

**Comment by YaLTeR** [comment]
Maybe there's a way to override the check and force a certain refresh rate? There's a setting like that in Firefox, I used it in the past because it had similar issues.

**Comment by fiete201** [comment]
can you try reproduce that with chrome please?

**Comment by YaLTeR** [comment]
Chromium has a slightly differently manifesting issue: vsynctester FPS is super unstable and jumps from 48 to 72 randomly:
![image](https://user-images.githubusercontent.com/1794388/47714090-f290c800-dc4c-11e8-89a6-7e29bc200712.png)

**Comment by fiete201** [comment]
So this issue might be related to the chrome engine. As long as it doesn't work flawlessly over there we can't do anything about it since qutebrowser is based on the chrome enginge.

**Comment by YaLTeR** [comment]
I'd like to revive this because it turns out that on Wayland (with sway) chromium (running through XWayland) actually gets the correct refresh rate (144 Hz or 120 Hz, I can even switch it at runtime), while qutebrowser (on Wayland via the `wayland-egl` backend or on XWayland via the whatever the default backend is on Arch Linux) still assumes 60 FPS.

![image](https://user-images.githubusercontent.com/1794388/54487410-c053d000-48a6-11e9-87b1-1b16ded883bc.png)

**Comment by jgkamat** [comment]
Ivan Molodetskikh writes:

> I'd like to revive this because it turns out that on Wayland (with sway) chromium (running through XWayland) actually gets the correct refresh rate (144 Hz or 120 Hz, I can even switch it at runtime), while qutebrowser (on Wayland via the `wayland-egl` backend or on XWayland via the whatever the default backend is on Arch Linux) still assumes 60 FPS.
>
> ![image](https://user-images.githubusercontent.com/1794388/54487410-c053d000-48a6-11e9-87b1-1b16ded883bc.png)


Can you test kde falkon instead? Unfortunately I can't test anything as I
don't have any high refresh rate monitors.

**Comment by YaLTeR** [comment]
Falkon seems to have the same issue.

**Comment by jgkamat** [comment]
Ivan Molodetskikh writes:

> Falkon seems to have the same issue.

There's probably nothing we can do about that then, you should report a bug to
qtwebengine.

**Comment by The-Compiler** [comment]
[[QTBUG-76006] WebEngine assumes 60Hz refresh rate - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-76006)

**Comment by wernerb** [comment]
The related chromium issue is resolved. The problem still persists though even though qt webengine 5.14 is used currently with qutebrowser.

**Comment by The-Compiler** [comment]
> The related chromium issue is resolved. The problem still persists though even though qt webengine 5.14 is used currently with qutebrowser.

The [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=535392) was fixed for Chromium 79, while Qt 5.14 is based on Chromium 77, so that makes sense.

However, Qt 5.15 is scheduled to be released in mid-May, so there's a chance this will be fixed there.

**Comment by gavtroy** [comment]
Unfortunately the issue persists in Qt 5.15 Beta4 too.

**Comment by fuzunspm** [comment]
same issue here with wayland/sway. All other browsers are working at 144hz except qutebrowser.

qutebrowser v1.11.0
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Comment by The-Compiler** [comment]
@fuzunspm When you say "all other browsers", I assume you didn't test anything else using QtWebEngine, such as KDE Falkon?

**Comment by wernerb** [comment]
I have tested qutebrowser-git and Falkon with both being locked to 60hz. It seems indeed an upstream QT bug

**Comment by The-Compiler** [comment]
Anyone here who can run the current QtWebEngine 5.15 branch (e.g. `dev-qt/qtwebengine 5.15.2_p20210205` on Gentoo) and has the hardware available to test this? There's [some little hope](https://bugreports.qt.io/browse/QTBUG-76006?focusedCommentId=552913&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-552913) this works there.

**Comment by temax6** [comment]
I still have this issue, how would I go about testing/fixing it? There seems to be no updates on this issue anywhere, but this is the one thing stopping me from only using qutebrowser.

**Comment by AidanJ** [comment]
Are there any workarounds yet to get the actual refresh rate? I only managed to do so by using the disable-frame-rate-limit flag which causes a high cpu usage

**Comment by The-Compiler** [comment]
@AidanJ not that I'm aware of.

**Comment by helloitsian** [comment]
Running into this issue. Any updates on this?

**Comment by The-Compiler** [comment]
@helloitsian As mentioned above, this is an [upstream issue](https://bugreports.qt.io/browse/QTBUG-76006), so you'll need to check there for updates. Not from what it looks like, though.

**Comment by vide0hanz** [comment]
According to the upstream tracker this was apparently solved on 25 Sep '23.

I am currently running qutebrowser v3.0.2 with PyQt 6.6.1 and can see that my 165hz display is indeed getting detected on chrome://gpu/

Not sure if any of this is significant.

**Comment by YaLTeR** [comment]
Just tried it again, qutebrowser-3.1.0-2.fc39.noarch. I also see all my monitors correctly in `chrome://gpu`, yet it's still locked to 60 Hz unfortunately.

**Comment by Banzayka** [comment]
If upstream issue has been closed almost a year ago, any ideas why it is still 60hz?

**Comment by The-Compiler** [comment]
I don't know, and I don't have the hardware to test this. My next laptop will likely change that - but I'll order it on Monday and, depending whether it's in stock or not, it might take some months until it's here.

If someone has a clear reproducer for this, I'd suggest reproducing it with e.g. the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py) and then reporting it upstream to Qt.

**Comment by vide0hanz** [comment]
For clarifcation, is there anything specific you'd like me to reproduce and report to upstream Qt? Here is part of the output of `chrome://gpu` with that script (the button to download the full report to a file doesn't work here).

[Vsync Tester](https://www.vsynctester.com/) is locked at 60hz.

Graphics Feature Status
=======================
*   Canvas: Hardware accelerated
*   Canvas out-of-process rasterization: Disabled
*   Direct Rendering Display Compositor: Disabled
*   Compositing: Hardware accelerated
*   Multiple Raster Threads: Enabled
*   OpenGL: Enabled
*   Rasterization: Hardware accelerated
*   Raw Draw: Disabled
*   Skia Graphite: Disabled
*   Video Decode: Hardware accelerated
*   Video Encode: Software only. Hardware acceleration disabled
*   Vulkan: Disabled
*   WebGL: Hardware accelerated
*   WebGL2: Hardware accelerated
*   WebGPU: Disabled

Driver Bug Workarounds
======================
*   clear_uniforms_before_first_program_use
*   count_all_in_varyings_packing
*   disable_post_sub_buffers_for_onscreen_surfaces
*   enable_webgl_timer_query_extensions
*   exit_on_context_lost
*   disabled_extension_GL_KHR_blend_equation_advanced
*   disabled_extension_GL_KHR_blend_equation_advanced_coherent
*   disabled_extension_GL_MESA_framebuffer_flip_y

Problems Detected
=================
*   WebGPU has been disabled via blocklist or the command line.
    Disabled Features: webgpu

*   Accelerated video encode has been disabled, either via blocklist, about:flags or the command line.
    Disabled Features: video_encode

*   Clear uniforms before first program use on all platforms:
    (http://crbug.com/124764), (http://crbug.com/349137)
    Applied Workarounds: clear_uniforms_before_first_program_use

*   Mesa drivers in Linux handle varyings without static use incorrectly:
    (http://crbug.com/333885)
    Applied Workarounds: count_all_in_varyings_packing

*   Disable partial swaps on Mesa drivers (detected with GL_VERSION):
    (http://crbug.com/339493)
    Applied Workarounds: disable_post_sub_buffers_for_onscreen_surfaces

*   Disable KHR_blend_equation_advanced until cc shaders are updated:
    (http://crbug.com/661715)
    Applied Workarounds: disable(GL_KHR_blend_equation_advanced),
        disable(GL_KHR_blend_equation_advanced_coherent)

*   Expose WebGL's disjoint_timer_query extensions on platforms with site isolation:
    (http://crbug.com/808744), (http://crbug.com/870491)
    Applied Workarounds: enable_webgl_timer_query_extensions

*   Some drivers can't recover after OUT_OF_MEM and context lost:
    (http://crbug.com/893177)
    Applied Workarounds: exit_on_context_lost

*   Disable GL_MESA_framebuffer_flip_y for desktop GL:
    (http://crbug.com/964010)
    Applied Workarounds: disable(GL_MESA_framebuffer_flip_y)

**Comment by vide0hanz** [comment]
Version Information
===================
Data exported              : 2024-08-29T13:31:39.562Z
Chrome version             : testbrowser_webengine.py/
Operating system           : Linux 6.10.1-arch1-1
Software rendering list URL: https://chromium.googlesource.com/chromium/src/+/9ad2fa676cb2a404642791e0e4818170cb4adbd8/gpu/config/software_rendering_list.json
Driver bug list URL        : https://chromium.googlesource.com/chromium/src/+/9ad2fa676cb2a404642791e0e4818170cb4adbd8/gpu/config/gpu_driver_bug_list.json
ANGLE commit id            : unknown hash
2D graphics backend        : Skia/118 7754f9f8257ad0872b7bb04d969452b74bb0c0bc
Command Line               : ./testbrowser_webengine.py --browser-subprocess-path=/usr/lib/qt6/QtWebEngineProcess --application-name=testbrowser_webengine.py --disable-setuid-sandbox --disable-speech-api --disable-blink-features=EyeDropperAPI --enable-features=NetworkServiceInProcess2,TracingServiceInProcess --disable-features=ConsolidatedMovementXY,InstalledApp,EyeDropper,BackgroundFetch,WebOTP,WebPayments,WebUSB --use-gl=desktop --in-process-gpu --create-default-gl-context --gpu-preferences=WAAAAAAAAAAoAAAEAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAFAAAAAJAAAASAAAAAAAAABQAAAAAAAAAFgAAAAAAAAAYAAAAAAAAABoAAAAAAAAAHAAAAAAAAAAeAAAAAAAAACAAAAAAAAAAIgAAAAAAAAAEAAAAAAAAAAAAAAABAAAABAAAAAAAAAAAAAAAA0AAAAQAAAAAAAAAAIAAAAOAAAAEAAAAAAAAAAEAAAADgAAABAAAAAAAAAACAAAAA0AAAAQAAAAAAAAAAgAAAAOAAAAEAAAAAAAAAAKAAAADgAAABAAAAAAAAAACQAAAA0AAAAQAAAAAAAAAAkAAAAOAAAACAAAAAAAAAAIAAAAAAAAAA==

Driver Information
==================
Initialization time             : 81
In-process GPU                  : true
Passthrough Command Decoder     : false
Sandboxed                       : false
GPU0                            : VENDOR= 0x0000 [AMD], DEVICE=0x0000 [AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 18.1.8, DRM 3.57, 6.10.1-arch1-1)], DRIVER_VENDOR=Mesa, DRIVER_VERSION=24.1.6 *ACTIVE*
Optimus                         : false
AMD switchable                  : false
GPU CUDA compute capability major version: 0
Pixel shader version            : 4.60
Vertex shader version           : 4.60
Max. MSAA samples               : 8
Machine model name              : 
Machine model version           : 
GL implementation parts         : (gl=desktop-gl,angle=none)
Display type                    : 
GL_VENDOR                       : AMD
GL_RENDERER                     : AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 18.1.8, DRM 3.57, 6.10.1-arch1-1)
GL_VERSION                      : 4.6 (Compatibility Profile) Mesa 24.1.6-arch1.1
GL_EXTENSIONS                   : GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_framebuffer_multisample_advanced GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_packed_pixels GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_sparse_texture2 GL_ARB_sparse_texture_clamp GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_blend_equation_separate GL_ATI_draw_buffers GL_ATI_fragment_shader GL_ATI_meminfo GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_EXT_debug_label GL_EXT_demote_to_helper_invocation GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_semaphore GL_EXT_semaphore_fd GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_IBM_multimode_draw_arrays GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_INTEL_blackhole_render GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_framebuffer_flip_y GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_const_bandwidth GL_MESA_texture_signed_rgba GL_MESA_window_pos GL_NVX_gpu_memory_info GL_NV_ES1_1_compatibility GL_NV_alpha_to_coverage_dither_control GL_NV_blend_square GL_NV_compute_shader_derivatives GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_primitive_restart GL_NV_shader_atomic_int64 GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_NV_vdpau_interop GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays
Disabled Extensions             : GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_MESA_framebuffer_flip_y
Disabled WebGL Extensions       : 
Window system binding vendor    : SGI
Window system binding version   : 1.4
Window system binding extensions: GLX_ARB_context_flush_control GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_no_config_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_gl_interop GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync
Direct rendering version        : DRI3
Reset notification strategy     : 0x8261
GPU process crash count         : 0
gfx::BufferFormats supported for allocation and texturing: R_8: not supported,  R_16: not supported,  RG_88: not supported,  RG_1616: not supported,  BGR_565: not supported,  RGBA_4444: not supported,  RGBX_8888: not supported,  RGBA_8888: not supported,  BGRX_8888: not supported,  BGRA_1010102: not supported,  RGBA_1010102: not supported,  BGRA_8888: not supported,  RGBA_F16: not supported,  YVU_420: not supported,  YUV_420_BIPLANAR: not supported,  YUVA_420_TRIPLANAR: not supported,  P010: not supported

Compositor Information
======================
Tile Update Mode: One-copy
Partial Raster  : Enabled

GpuMemoryBuffers Status
=======================
R_8               : CAMERA_AND_CPU_READ_WRITE, SCANOUT_CPU_READ_WRITE, SCANOUT_FRONT_RENDERING
R_16              : Software only
RG_88             : Software only
RG_1616           : Software only
BGR_565           : GPU_READ
RGBA_4444         : Software only
RGBX_8888         : GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE, SCANOUT_FRONT_RENDERING
RGBA_8888         : GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE, SCANOUT_FRONT_RENDERING
BGRX_8888         : GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE, SCANOUT_FRONT_RENDERING
BGRA_1010102      : SCANOUT, SCANOUT_CPU_READ_WRITE, SCANOUT_FRONT_RENDERING
RGBA_1010102      : SCANOUT, SCANOUT_CPU_READ_WRITE, SCANOUT_FRONT_RENDERING
BGRA_8888         : GPU_READ, SCANOUT, SCANOUT_CPU_READ_WRITE, SCANOUT_FRONT_RENDERING
RGBA_F16          : Software only
YVU_420           : GPU_READ, SCANOUT_VEA_CPU_READ, VEA_READ_CAMERA_AND_CPU_READ_WRITE
YUV_420_BIPLANAR  : SCANOUT_CAMERA_READ_WRITE, SCANOUT_CPU_READ_WRITE, SCANOUT_VEA_CPU_READ, SCANOUT_FRONT_RENDERING, VEA_READ_CAMERA_AND_CPU_READ_WRITE
YUVA_420_TRIPLANAR: Software only
P010              : Software only

Display(s) Information
======================
Info                          : Display[0] bounds=[1440,732 2560x1440], workarea=[1440,732 2560x1440], scale=1, rotation=0, panel_rotation=0 external detected
Color space (all)             : {primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}
Buffer format (all)           : RGBA_8888
Color volume                  : {name:'srgb', r:[0.6400, 0.3300], g:[0.3000, 0.6000], b:[0.1500, 0.3300], w:[0.3127, 0.3290]}
SDR white level in nits       : 203
HDR relative maximum luminance: 1
Bits per color component      : 8
Bits per pixel                : 24
Refresh Rate in Hz            : 165
Info                          : Display[1] bounds=[0,0 1440x2560], workarea=[0,0 1440x2560], scale=1, rotation=90, panel_rotation=90 external detected
Color space (all)             : {primaries:BT709, transfer:SRGB, matrix:RGB, range:FULL}
Buffer format (all)           : RGBA_8888
Color volume                  : {name:'srgb', r:[0.6400, 0.3300], g:[0.3000, 0.6000], b:[0.1500, 0.3300], w:[0.3127, 0.3290]}
SDR white level in nits       : 203
HDR relative maximum luminance: 1
Bits per color component      : 8
Bits per pixel                : 24
Refresh Rate in Hz            : 165

Video Acceleration Information
==============================
Decoding: 
Encoding:

Vulkan Information
==================

Device Performance Information
==============================

Log Messages

**Comment by The-Compiler** [comment]
Can you try with `QUTE_QT_WRAPPER=PyQt5 qutebrowser --temp-basedir https://vsynctester.com` and see if it happens there as well? Also please take a look at `:version` and verify that you're running QtWebEngine 5.15.4 or newer (but not Qt 6).

**Comment by vide0hanz** [comment]
Same issue there too.

My primary instance of qutebrowser:
```
qutebrowser v3.2.1
Git commit:
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

CPython: 3.12.5
PyQt: 6.7.1
```

With the wrapper you suggested:
```
qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 5.15.17
  based on Chromium 87.0.4280.144
  with security patches up to 123.0.6312.58 (plus any distribution patches)
  (source: UA)
Qt: 5.15.14

CPython: 3.12.5
PyQt: 5.15.11

Qt wrapper: PyQt5 (via QUTE_QT_WRAPPER)
```

**Comment by The-Compiler** [comment]
That's odd, because from what I can gather, that's the reproducer that upstream claimed they fixed, with the version they fixed it in.

Probably best to open a new upstream bug with that information from above. I won't do so myself until I actually have a way to try reproducing this, I'm afraid.

**Comment by gavtroy** [comment]
It was never working, even after some internal fixes were made. There is an open upstream bug here https://bugreports.qt.io/browse/QTBUG-123640

**Comment by The-Compiler** [comment]
Ah, perfect, didn't have that on my radar.

**Comment by RobertCraigie** [comment]
could this issue be re-opened to track when the upstream issues are fixed and available in qute?

**Comment by The-Compiler** [comment]
No, there's nothing actionable for qutebrowser left to be done here. Note that outside of Windows/macOS releases, qutebrowser won't decide which Qt version you're running, that's left to your distribution.
