### ISSUE TITLE
qutebrowser hangs with webkit backend

### ISSUE THREAD

**Issue by dubbadubbadubbacha** [qutebrowser/qutebrowser#4399]
I need this backend for bitmap fonts and because it consumes far less resources on my old computer. I find it freezes on certain websites and I can't terminate unless I pkill it.

**Comment by The-Compiler** [comment]
Sounds like a QtWebKit and not a  qutebrowser issue. If I had to guess I'd say https://github.com/annulen/webkit/issues/487 but hard to tell with so little info.
