### ISSUE TITLE
:navigate doesn't increment numbers in anchors or querys

### ISSUE THREAD

**Issue by marc-groundctl** [qutebrowser/qutebrowser#4402]
**Version info (see `:version`)**:
qutebrowser v1.5.1
Git commit: c7a21b37e (2018-10-10 08:23:17 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.10.100 (bundled)
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QWindowsVistaStyle
Platform: Windows-10-10.0.17134-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.17134, SP0, Multiprocessor Free

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes

**Description**
`:navigate increment` appears to only affect numbers in the path, not in the query or anchor.

**How to reproduce**

Ensure "query" is in `url.incdec_segments`.
Navigate to `http://0.0.0.0/?number=2`
Run `:navigate increment`
It complains that there is no number in the URL, but the query clearly contains a number.

**Comment by jgkamat** [comment]
I can reproduce this, I'm not sure why the tests in
https://github.com/qutebrowser/qutebrowser/pull/985 didn't see this.

marc-groundctl writes:

> **Version info (see `:version`)**:
> qutebrowser v1.5.1
> Git commit: c7a21b37e (2018-10-10 08:23:17 +0200)
> Backend: QtWebEngine (Chromium 65.0.3325.230)
>
> CPython: 3.7.0
> Qt: 5.11.2
> PyQt: 5.11.3
>
> sip: 4.19.13
> colorama: 0.3.9
> pypeg2: 2.15
> jinja2: 2.10
> pygments: 2.2.0
> yaml: 3.13
> cssutils: 1.0.2 $Id$
> attr: 18.2.0
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebKitWidgets: no
> pdf.js: 1.10.100 (bundled)
> sqlite: 3.24.0
> QtNetwork SSL: OpenSSL 1.0.2k  26 Jan 2017
>
> Style: QWindowsVistaStyle
> Platform: Windows-10-10.0.17134-SP0, 64bit
> Frozen: True
> Imported from C:\Program Files\qutebrowser\qutebrowser
> Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
> Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
> OS Version: 10, 10.0.17134, SP0, Multiprocessor Free
>
> **Does the bug happen if you start with `--temp-basedir`?** (if applicable):
> Yes
>
> **Description**
> `:navigate increment` appears to only affect numbers in the path, not in the query or anchor.
>
> **How to reproduce**
> 
> Ensure "query" is in `url.incdec_segments`.
> Navigate to `http://0.0.0.0/?number=2`
> Run `:navigate increment`
> It complains that there is no number in the URL, but the query clearly contains a number.

**Comment by lyeoh** [comment]
Yes I didn't realise #850 had already been resolved. I'll move the fragment-stripping line.
