### ISSUE TITLE
Copy download path

### ISSUE THREAD

**Issue by erewhon-smith** [qutebrowser/qutebrowser#4404]
When I download files on the web, I like to copy the path using `;y` and then move to a terminal and `wget` it into the folder where I want it.
The only problem is this doesn't work when the file is behind a password protected site. Any thoughts on how to handle this?
One nice feature would be to have a binding that copies the path of a download to the clipboard. Then you could move to your terminal and `cp` the file anywhere else.
Thanks for the fantastic program that is qutebrowser.

**Comment by jgkamat** [comment]
erewhon-smith writes:

> The only problem is this doesn't work when the file is behind a password protected site. Any thoughts on how to handle this?

This seems like more of a problem with wget than qutebrowser. I'm sure there's
a flag to pass authentication to wget. It looks like wget reads from netrc, so
if you define a netrc file, it might just work.

> One nice feature would be to have a binding that copies the path of a download to the clipboard. Then you could move to your terminal and cp the file anywhere else.

This is probably easy to implement, but I'm not sure how useful it would be
(and/or how many people would use it)

**Comment by The-Compiler** [comment]
There's already `:download-open` which can take an executable, which then gets called with the download path as argument.

On Linux, you can do something like `:download-open bash -c 'xclip -sel clipboard <<< "$1"' _` so the argument gets piped to xclip which then puts it into the clipboard. Something similar is likely available on other platforms as well.

**Comment by erewhon-smith** [comment]
Thank you @The-Compiler. I hadn't thought of that.
The only problem is this copies a newline character at the end of the path. Any thoughts on how to copy to the clipboard without newline?

**Comment by The-Compiler** [comment]
Looks like xclip has an `-r` argument which strips a final newline

**Comment by erewhon-smith** [comment]
That works like a charm. Thanks again @The-Compiler!

**Comment by sanaptejas** [comment]
why not just write a script that uses wget and tsp (task-spooler) and use that script.
