### ISSUE TITLE
Out of memory: Kill process 23094 (QtWebEngineProc) ...

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#4413]
I'm not sure if this is specific to qutebrowser, but today for the second time, my laptop has almost completely locked up due to memory loss. I say "almost completely" because if I touch my mouse, then after many seconds, it will eventually move; however, the machine is functionally frozen.

The second time this happened (just now), I managed to get to a terminal fast and type `free -h`, which told me I had 105Mi of memory free.

I also managed, slowly, to switch to tty2 and log in, which eventually produced messages (to stdout) telling me that my core temp was above threshold and then that I was out of memory. I can see these messages by checking `journalctl`:

```
Nov 06 22:15:25 arch kernel: CPU2: Core temperature above threshold, cpu clock throttled (total events = 1)
Nov 06 22:15:27 arch kernel: CPU0: Package temperature above threshold, cpu clock throttled (total events = 1)
Nov 06 22:15:28 arch kernel: CPU1: Package temperature above threshold, cpu clock throttled (total events = 1)
Nov 06 22:15:29 arch kernel: CPU3: Core temperature above threshold, cpu clock throttled (total events = 1)
Nov 06 22:15:29 arch kernel: CPU3: Package temperature above threshold, cpu clock throttled (total events = 1)
Nov 06 22:15:30 arch kernel: CPU2: Package temperature above threshold, cpu clock throttled (total events = 1)
...
Nov 06 22:21:00 arch kernel: Out of memory: Kill process 23096 (QtWebEngineProc) score 344 or sacrifice child
Nov 06 22:21:00 arch kernel: Killed process 23096 (QtWebEngineProc) total-vm:2422904kB, anon-rss:34224kB, file-rss:0kB, shmem-rss:320680kB
```

As you can see, `QtWebEngineProc` seems to have been the culprit, and it took about 6 minutes before it got killed. Then everything turned back to normal: I went back to tty1, and qutebrowser was (and still is) happily running (it didn't crash or anything).

I ran `:report` and filed a report. Unfortunately, I can't say what exactly caused it or how to reproduce it, but like I mentioned, this also happened once earlier today.

Version info:

```
qutebrowser v1.5.0
Git commit: 7d08714a9 (2018-10-03 16:07:38 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)
```

**Comment by The-Compiler** [comment]
The Linux OOM killer does take quite some time to kick in. If it kills the QtWebEngineProcess, you'll just end up with a "renderer process killed" error page in that tab. Nothing qutebrowser can do about that, though :wink:

**Comment by brianbuccola** [comment]
So do you think it was just a certain offending tab that couldn't render something? Is it just a coincidence that this happened to me for the first time today and then *again* on the same day?

**Comment by The-Compiler** [comment]
> So do you think it was just a certain offending tab that couldn't render something?

No idea. If I'm running out of memory because of qutebrowser/QtWebEngine, all tabs get killed usually.

> Is it just a coincidence that this happened to me for the first time today and then again on the same day?

Depends on what you mean by coincidence. Maybe you had something else particularly memory-hungry running today. Or you had more tabs than usual open today.

**Comment by brianbuccola** [comment]
I also see that I have a qutebrowser uptime of >5 hours (I haven't restarted it since before the last freeze happened...), so maybe there's just something fishy going on under the hood, and a restart will clear things out.

**Comment by bitraid** [comment]
@brianbuccola your CPU is overheating, you should have that checked out (fan/cooling system) before permanent physical damage is done to the system.

**Comment by The-Compiler** [comment]
@bitraid Huh? That's not overheating, that's the CPU throttling before it's overheating. Pretty normal to see that with 100% CPU utilization (at least for laptops).

**Comment by bitraid** [comment]
I've only seen that message on overheating cpu's, i might be wrong...
