### ISSUE TITLE
`c.content.private_browsing = True` not working

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#4416]
**Version info (see `:version`)**: latest git.

i login to utube, `:q`, open qb, open utube, i see i'm logged in.

**Comment by The-Compiler** [comment]
Works fine here. Is your status bar grey? What Qt version and backend ("latest git" isn't very informative...)?

**Comment by Al-Caveman** [comment]
says true.

qutebrowser v1.5.2
Git commit: 08278138c (2018-11-03 07:54:37 +0100)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.1
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.4.0
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /home/caveman/Documents/dev/qutebrowser/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/caveman/.cache/qutebrowser
config: /home/caveman/.config/qutebrowser
data: /home/caveman/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Comment by Al-Caveman** [comment]
oops, wasn't latest git.  just pulled and can't reproduce again.  maybe solved.
