### ISSUE TITLE
"permission denied: 'whle reading: [Ernno 13] ~/.config/qutebrowser/autoconfig.yml'

### ISSUE THREAD

**Issue by evanescente-ondine** [qutebrowser/qutebrowser#4417]
Can't show version, it says:
```
12:31:11 WARNING: QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
No protocol specified
12:31:11 CRITICAL: QXcbConnection: Could not connect to display :0
Fatal Python error: Aborted

Current thread 0x00007fea80297700 (most recent call first):
  File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 823 in __init__
  File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 104 in run
  File "/usr/lib/python3/dist-packages/qutebrowser/qutebrowser.py", line 194 in main
  File "/usr/bin/qutebrowser", line 11 in <module>
Abandon

```
I  could install it before but I had to reinstall  (upgrade gone wrong) and now this.  Nothing appears when it pops up, of course. If only that thing didn't have that many dependencies !

**Comment by The-Compiler** [comment]
As in #4414, this isn't a qutebrowser issue. Qt is abandoning because it can't connect to your display. You'll need to fix that first...

**Comment by The-Compiler** [comment]
Also, the error message at the top still looks like you're running qutebrowser as root - I asked why in #4414 but never got an answer.

**Comment by evanescente-ondine** [comment]
Ok. Had to purge manually the config folder, which wasn't being done with apt purge blabla.
It's fine now. I guess all of this comes from having damn too many dependencies, for something meant to be keyboard-driven. I don't get why it should be used by root either... but whatever. Sorry to have annoyed you :-). Great software.

**Comment by evanescente-ondine** [comment]
Personally, I have nothing using QT outside QB and my environment is full fonctionnal (and I didn't do it on purpose). Usually with "keyboard-driven" people think "suckless" and lightweight, and though QT is common it's not very light.
I'm no compiler, just curious, but do you think it would be technically possible to recast a program with the same features, with a simpler/faster toolkit (though not that pretty) ?

**Comment by The-Compiler** [comment]
That'd be a complete rewrite, and there are projects like that (e.g. vimb), see the [list of similar projects](https://github.com/qutebrowser/qutebrowser#similar-projects). I'm not interested in that, however. My philosophy with qutebrowser has always been to prefer functionality (and e.g. a modern secure rendering engine with QtWebEngine) over being overly lightweight.

**Comment by jgkamat** [comment]
> Personally, I have nothing using QT outside QB and my environment is full fonctionnal (and I didn't do it on purpose). Usually with "keyboard-driven" people think "suckless" and lightweight, and though QT is common it's not very light.
> I'm no compiler, just curious, but do you think it would be technically possible to recast a program with the same features, with a simpler/faster toolkit (though not that pretty) ?

Pretty much any gui browser that supports js will have to depend on external
rendering libraries (which usually means a heavy toolkit) nowadays. If you
want something lightweight, you probably want to look into w3m, lynx, eww, or
other text-based browsers. Even the suckless browser - surf, has the same
issues.
