### ISSUE TITLE
Sessions and cache

### ISSUE THREAD

**Issue by Etn40ff** [qutebrowser/qutebrowser#4423]
One possible usage of sessions is to group together few pages one is interested in getting news from once in a while and load them when needed. Unfortunately, because of page caching, when a session is loaded the content of the page displayed may be outdated. Would it be possible to implement a `--force` toggle for `:session_load` like in `:reload`? Alternatively would it be possible to add an option to `:reload` to reload all tabs in a window?

**Comment by The-Compiler** [comment]
I don't think there's a way qutebrowser can control how the cache is used when loading sessions. As for reloading all tabs in a window, see #267.

**Comment by Etn40ff** [comment]
Thanks for the fast reply
