### ISSUE TITLE
Wrap messages

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4427]
Messages aren't wrapped when their text is too long:

![image](https://user-images.githubusercontent.com/625793/48582097-e763ba80-e923-11e8-826a-6f81d5887d67.png)

**Comment by user202729** [comment]
Setting `self.setWordWrap(True)` in `Message.__init__` works, but has another problem - the height of the message may be too large:

![screenshot from 2018-11-19 19-50-12](https://user-images.githubusercontent.com/25191436/48708826-37999000-ec36-11e8-9ab3-a38bb97d397a.png)

**Comment by The-Compiler** [comment]
I don't follow - that seems fine from the screenshot?

**Comment by user202729** [comment]
This screenshot may be more apparent (that the top and bottom padding is too large):

![image](https://user-images.githubusercontent.com/25191436/48709023-d4f4c400-ec36-11e8-8f55-47514f6b624d.png)
