### ISSUE TITLE
qutebrowser does not start on arm64

### ISSUE THREAD

**Issue by kralan** [qutebrowser/qutebrowser#4429]
qutebrowser 1.5.2 on debian buster arm64
does not start.

Output on console:
```
12:01:23 CRITICAL: Could not initialize GLX
Fatal Python error: Aborted

Current thread 0x0000007f8c5a8010 (most recent call first):
  File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 823 in __init__
  File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 104 in run
  File "/usr/lib/python3/dist-packages/qutebrowser/qutebrowser.py", line 194 in main
  File "/usr/bin/qutebrowser", line 11 in <module>
Aborted
```
Output of glxinfo -B:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: VMware, Inc. (0xffffffff)
    Device: llvmpipe (LLVM 6.0, 128 bits) (0xffffffff)
    Version: 18.1.9
    Accelerated: no
    Video memory: 3926MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 6.0, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.1.9
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 18.1.9
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.1.9
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
falkon browser, which uses the same engine AFAIK, starts and works on the same machine.

Can I provide any more specific information?

**Comment by The-Compiler** [comment]
Hmm, that's odd, because that message is coming from Qt. I'm not sure why Falkon would work but qutebrowser wouldn't.

Does `--version` work, or does that crash as well? If it does, what Qt version do you see there, and do you see the same in "About Falkon" with Falkon?

**Comment by kralan** [comment]
`qutebrowser --version` crashes with the same message.
About Falkon says: 

> Application version 3.0.0
> QtWebEngine version 5.11.2
> © 2010-2018 David Rosca
> https://kde.org
> Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.0.0 Chrome/65.0.3325.230 Safari/537.36

**Comment by The-Compiler** [comment]
Can you try editing `/usr/lib/python3/dist-packages/qutebrowser/misc/backendproblem.py` and commenting out the calls to `_nvidia_shader_workaround()` and `_handle_nouveau_graphics()` in lines 395/396 (with a `#`)? If that changes anything, can you please find out which of the two is responsible?

**Comment by kralan** [comment]
Commented out both lines, still crashes with the same message.

**Comment by kralan** [comment]
`python3 scripts/testbrowser/testbrowser_webengine.py qutebrowser.org` yields `Could not initialize GLX`.
Which -dev package dependencies would I need to install in order to `qmake testbrowser`?

**Comment by The-Compiler** [comment]
You'll at least need `qt5-qmake`, not sure what else.

**Comment by kralan** [comment]
Yes, I got `qmake` but it complains `qmake: could not find a QT installation of '''`. It would seem I need a few dependencies. Any hints which?

**Comment by The-Compiler** [comment]
Nope - I don't use Debian much, no idea how Qt is split up there.

**Comment by The-Compiler** [comment]
It seems like something is wrong with the graphics on your system - though I have no idea what, or why Falkon works. Maybe https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913287 is relevant somehow as well?

Anyways - since `testbrowser_webengine.py` doesn't work (which is about as minimal as it gets), this doesn't seem like something qutebrowser could do anything about. I'm out of ideas on what could be the culprit, though.

**Comment by kralan** [comment]
Thank you very much for your time and your quick response.

**Comment by kralan** [comment]
As an additional observation:
While `./testbrowser qutebrowser.org` (the C++ version) shows an empty window, `./testbrowser http://qutebrowser.org` shows your website ok.
Still, `testbrowser.py` shows `Could not initialize GLX`, no matter which address.

**Comment by The-Compiler** [comment]
Oh, right, the `./testbrowser qutebrowser.org` one was my bad, it only takes complete URLs.

If you add this to the top of `testbrowser_webengine.py` at the top (before the other imports):

```python
libgl = ctypes.util.find_library("GL")
ctypes.CDLL(libgl, mode=ctypes.RTLD_GLOBAL)
```

I assume that doesn't change anything? Does adding `from OpenGL import GL` change anything (after installing `python3-opengl`)?

**Comment by kralan** [comment]
```
python3 ~/scripts/testbrowser/testbrowser_webengine.py http://qutebrowser.org
Traceback (most recent call last):
  File "/home/alan/scripts/testbrowser/testbrowser_webengine.py", line 22, in <module>
    libgl = ctypes.util.find_library("GL")
NameError: name 'ctypes' is not defined
```
prepending `import ctypes` does not help: 
```
python3 ~/scripts/testbrowser/testbrowser_webengine.py http://qutebrowser.org
Traceback (most recent call last):
  File "/home/alan/scripts/testbrowser/testbrowser_webengine.py", line 24, in <module>
    libgl = ctypes.util.find_library("GL")
AttributeError: module 'ctypes' has no attribute 'util'
```

**Comment by The-Compiler** [comment]
My bad - you'll need `import ctypes` and `import ctypes.util` before that.

**Comment by kralan** [comment]
No combination of the above [suggestions](https://github.com/qutebrowser/qutebrowser/issues/4429#issuecomment-439618837) helps -> `Could not initialize GLX`.
The problem seems to reside on the python side, as C++ appears to work?

**Comment by kralan** [comment]
The linking issues are beyond my expertise. Thank you for your thoughts and effort, anyway.

**Comment by dumol** [comment]
Looks like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=913287 indeed. If anyone wonders, the fix doesn't appear to have made it to Debian 10. 

Seems to be the reason why qutebrowser is broken on Debian 10 arm64.

**Comment by The-Compiler** [comment]
@dumol There should be a workaround for this one in qutebrowser since a long time - what qutebrowser version are you running, and what output are you getting precisely?

**Comment by dumol** [comment]
@The-Compiler Thanks for the quick reply!

I'm trying 1.6.1, as packaged in Debian 10.
```
dumol@pine64:~$ apt show qutebrowser
Package: qutebrowser
Version: 1.6.1-2
Priority: optional
Section: web
Maintainer: Fritz Reichwald <reichwald@b1-systems.de>
Installed-Size: 4,910 kB
Provides: x-www-browser
Depends: libqt5core5a (>= 5.7.1), libqt5sql5-sqlite, python3-attr, python3-pkg-resources, python3-pypeg2, python3-pyqt5, python3-pyqt5.qtopengl, python3-pyqt5.qtquick, python3-pyqt5.qtsql, python3-ruamel.yaml, python3-sip, qutebrowser-qtwebengine | qutebrowser-qtwebkit, python3-jinja2, python3-pygments, python3-yaml, python3:any
Suggests: libjs-pdf, python3-colorlog
Homepage: https://qutebrowser.org
Tag: uitoolkit::qt
Download-Size: 1,748 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian buster/main arm64 Packages
Description: Keyboard-driven, vim-like browser based on PyQt5
 qutebrowser is a keyboard-focused browser with a minimal GUI. It's
 based on Python and PyQt5 and was inspired by other browsers/addons
 like dwb and Vimperator/Pentadactyl.
 .
 qutebrowser supports two different rendering engine backends:
 QtWebKit and QtWebEngine.
```
The output is:
```
dumol@pine64:~$ qutebrowser
17:23:21 CRITICAL: Could not initialize GLX
Fatal Python error: Aborted

Current thread 0x0000ffff9bcd0010 (most recent call first):
  File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 819 in __init__
  File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 105 in run
  File "/usr/lib/python3/dist-packages/qutebrowser/qutebrowsep
```
As the initial reporter wrote, Falkon somehow works…

**Comment by The-Compiler** [comment]
@dumol Does `QUTE_SKIP_LIBGL_WORKAROUND=1 qutebrowser` or the same with `QUTE_SKIP_NOUVEAU_CHECK=1` change anything?

**Comment by dumol** [comment]
@The-Compiler No, sorry, no change at all.

For completion, related GLX info:
```
dumol@pine64:~$ glxinfo -B
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: VMware, Inc. (0xffffffff)
    Device: llvmpipe (LLVM 7.0, 128 bits) (0xffffffff)
    Version: 18.3.6
    Accelerated: no
    Video memory: 1992MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 7.0, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 18.3.6
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

**Comment by dumol** [comment]
Same issue on Debian 11 Bullseye (currently, the _testing_ version), which has `qutebrowser` 1.13.0 packaged.

Again, `falkon` works with the same QT 5 WebEngine package (5.14.2 for Debian Bullseye).

Might be something related to missing hardware acceleration for the Pine64 board. I'm using the 5.4.43 kernel from Armbian 20.05.2.

**Comment by toofar** [comment]
I get a couple more warnings before the abort:
```
22:09:07 WARNING: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
22:09:07 WARNING: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
22:09:07 CRITICAL: Could not initialize GLX
```
That actually rings some bells from when I was using plasma on postmarkos, maybe this has a weird display format.
This is debian sid, an almost fresh install, on a pinebook pro with the special snowflake manjaro kernal, I have yet to try the mainstream one. I haven't attempted to investigate any further than installing whatever is packaged and running it. I was surprised that I could reproduce it since it worked fine on armv7hf last I tried (eeepc701).

**Comment by toofar** [comment]
I installed the linux kernel headers and mali-midgard-dkms and it launches now. There is still an error from apt about not being able to build against my kernel version even though it did, I guess it is just confused. I tried all the qt.force_software_rendering options before that and none of them change the behaviour. I'm surprised that it wouldn't run without proper drivers when X11 does but that seems to be the case. [This](https://wiki.debian.org/MaliGraphics) helped but also lists packages that don't seem to be available anymore.

**Comment by darkgeek** [comment]
Just found a [workaround](https://bugreports.qt.io/browse/QTBUG-64645) for this issue: set the environment variable `export QT_XCB_GL_INTEGRATION=none`, and then launch `qutebrowser` will make it work, at least for 1.6.1 on Debian buster.
