### ISSUE TITLE
Hide/Edit platform informations

### ISSUE THREAD

**Issue by concatime** [qutebrowser/qutebrowser#4437]
Hi.
Even with a custom User-Agent, https://ipleak.net/ is able to detect `Platform: Linux x86_64`.
It would be really nice if we can change this behaviour.
Thank you.

**Comment by jgkamat** [comment]
If you disable JS, this dosen't seem to work. So disabling JS should get you
the behavior you want.

Issam Maghni writes:

**Comment by mschilli87** [comment]
@concatime: I guess https://github.com/qutebrowser/qutebrowser/issues/2160#issuecomment-264670678 applies here, too. Luckily, https://github.com/qutebrowser/qutebrowser/issues/30 [is next](https://github.com/qutebrowser/qutebrowser/projects/3) on the big list. :wink:

**Comment by The-Compiler** [comment]
@mschilli87 is pretty much right - though you don't need to wait for #30: You might be able to write a GreaseMonkey script based on [this StackExchange answer](https://security.stackexchange.com/questions/146895/how-can-you-change-platform-os-that-is-detected-by-javascript-in-firefox) to patch the JS property. If that doesn't work, there isn't anything qutebrowser can do unfortunately.

**Comment by The-Compiler** [comment]
Also, let me note that there's lot of other information a website can get when JS is enabled - with it disabled things might look better, but it's still very hard (also see [this explanation](https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#Why-isnt-passive-browser-fingerprinting-including-passive-cookies_in-Chromes-threat-model)).

**Comment by concatime** [comment]
Until then, we should NOT use an User-Agent with a different platform.
> Warning: Changing the user agent without changing to a corresponding platform will make your browser nearly unique.

[Source](//wiki.archlinux.org/index.php/Firefox/Privacy#Change_user_agent_and_platform).
