### ISSUE TITLE
Crash in _check_valid_utf8 when typing emojis

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4439]
When using [rofimoji](https://github.com/fdw/rofimoji) to e.g. type "Helmet With White Cross, Type-1-2" in normal mode, qutebrowser crashes:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyutils.py", line 82, in _check_valid_utf8
    s.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83c' in position 0: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 929, in eventFilter
    return handler(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 902, in _handle_key_event
    return man.handle_event(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 353, in handle_event
    return handler(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 173, in _handle_keypress
    match = parser.handle(event, dry_run=dry_run)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 99, in handle
    match = super().handle(e, dry_run=dry_run)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 167, in handle
    txt = str(keyutils.KeyInfo.from_event(e))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyutils.py", line 316, in __str__
    key_string = _key_to_string(self.key)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyutils.py", line 201, in _key_to_string
    _check_valid_utf8(result, key)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyutils.py", line 85, in _check_valid_utf8
    .format(data, s, e))
ValueError: Invalid encoding in 0xd83c -> \ud83c: 'utf-8' codec can't encode character '\ud83c' in position 0: surrogates not allowed
```

U+D83C is an [invalid surrogate](https://www.fileformat.info/info/unicode/char/d83c/index.htm), but seems to be [used in emoji](https://thekevinscott.com/emojis-in-javascript/) somehow.

Note this isn't about nothing happening when trying to insert emoji that way - there's [QTBUG-65765](https://bugreports.qt.io/browse/QTBUG-65765) for that.

**Comment by user202729** [comment]
https://stackoverflow.com/a/38147966/5267751

In short:

* It's likely to be a bug in PyQt or rofimoji to return the string `'\ud83c\udf00'` instead of `'\U0001f300'`.
* It's possible to workaround it with `.encode('utf-16', 'surrogatepass')`.

By the way:

* d83c is a valid surrogate, just not a valid unicode codepoint.
* I also found https://stackoverflow.com/questions/18894938/pyqt-and-utf-16-surrogates which also suspects that it's a PyQt bug, but I'm not sure.

**Comment by The-Compiler** [comment]
Got two more reports the past couple of days - on Archlinux and Linux Mint 18.2, both Qt 5.11.2, PyQt 5.11.3. However, those versions are out for a while already, so it's either just bad luck, or something changed in some other place...

**Comment by cincodenada** [comment]
Okay, so I didn't have time but I dug anyway and it looks like `QtKeySequence::toString()`, which is what is ultimately used, explicitly returns UTF-16. This isn't documented anywhere I could find, but it definitely does so in the code:
https://github.com/qt/qtbase/blob/d20aa0d50d6dfc2dc1b88cc912425a28df6437de/src/gui/kernel/qkeysequence.cpp#L1333-L1344

So, I think anything that uses the output of `QtKeySequence::toString()` should assume UTF-16, not UTF-8. I can test that theory and put together a PR probably this week.

**Comment by user202729** [comment]
After taking another look, Qt consider the emoji 2 keys, and the string is not valid even in utf-16.

Because currently it's not possible to bind characters not in BMP anyway, a simple "fix" would be ignoring those keypress events.

**Comment by The-Compiler** [comment]
Fixed via #4656.

**Comment by The-Compiler** [comment]
Relevant Qt issues and changes:

- [[QTBUG-72776] QKeyEvent key() only returns value of first surrogate for characters in Supplementary Planes - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-72776)
- [[QTBUG-65765] Unable to insert emoji in input fields using xdotool - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-65765)
- [qxkbcommon: UCS-4-encode surrogate characters in QKeyEvent::key() (I9d1f4e34) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/251703)

**Comment by The-Compiler** [comment]
Looks like the fix above got picked up again and merged - it's in Qt 6.2.3 once qutebrowser has Qt 6 support.

**Comment by pacholik** [comment]
Will this change be reverted for qutebrowser on Qt6?

**Comment by The-Compiler** [comment]
@pacholik What makes you ask? The workaround shouldn't hurt anything.

**Comment by pacholik** [comment]
Well, we still can’t insert emojis.路 (I mean 🤷)

**Comment by The-Compiler** [comment]
That is still a Qt issue, unrelated to the workaround. I opened [[QTBUG-114870] Cannot type emoji characters requiring surrogates - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-114870).

**Comment by user202729** [comment]
The new issue is probably duplicate of https://bugreports.qt.io/browse/QTBUG-65765 . 

That one is closed, but note that the last comment says...

```
Wait for https://github.com/jordansissel/xdotool/issues/295 got fixed first.
```

If I recalled correctly rofimoji uses xdotool under the hood anyway so no difference.

**Comment by The-Compiler** [comment]
I saw that, but IMHO it was reported against the wrong component (this is now clearly a QtWebEngine specific problem, probably when translating Qt key events into Chromium key events). Also given that it works elsewhere in Qt, and in Chromium, and everywhere else, I really don't think xdotool is to blame for that.

**Comment by pacholik** [comment]
Oh, so it’s still not resolved in Qt? That’s a bummer.

It’s not _xdotool_ thing, I don’t use that. I write emojis straight from keyboard https://gitlab.com/pacholik1/keyboards/-/blob/master/uscz

**Comment by The-Compiler** [comment]
That's what it looks like, yes. I tried deactivating the workaround (and also with the minimal testbrowser), and I see the same behavior of the wrong character being typed. It looks like those were actually two independent bugs, and only the first one (causing qutebrowser to crash, which we could work around) got fixed.
