### ISSUE TITLE
can i open mpv with the context menu

### ISSUE THREAD

**Issue by Joseph65** [qutebrowser/qutebrowser#4441]
just a question is it possible to open a youtube link with mpv by right click context menu

**Comment by neeasade** [comment]
this would become possible with https://github.com/qutebrowser/qutebrowser/issues/349

**Comment by Joseph65** [comment]
and with a hint is it possible to open mpv url

**Comment by toofar** [comment]
There is an FAQ entry titled "How do I play Youtube videos with mpv?" about passing URLs to mpv from hints https://qutebrowser.org/doc/faq.html
