### ISSUE TITLE
Overleaf: broken login screen

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#4442]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/457bc7e3

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
--temp-basedir does not work on my setup.

**Description**
Overleaf won't redirect to the main page after login, does not show any error though.
Going directly to https://overleaf.com manually seems to work.

**How to reproduce**
https://www.overleaf.com/login

**Comment by The-Compiler** [comment]
What do you mean with "--temp-basedir does not work on my setup."? Does it make any difference if you update to v1.5.2 or do `:set content.cookies.accept all`?

**Comment by mike402** [comment]
Just tried 1.5.2, does the same.

By "--temp-basedir does not work on my setup." I mean I see no difference in behaviour when I start qutebrowser with this option, all my settings and cookies etc. are still there.

**Comment by The-Compiler** [comment]
Do you have some kind of wrapper script which doesn't pass arguments through properly?

**Comment by The-Compiler** [comment]
It probably is something in your config then. Can you paste your `qute://configdiff` page please?

**Comment by The-Compiler** [comment]
@mike402 Any update on this?

**Comment by mike402** [comment]
Indeed, it was caused by the accept header string like https://github.com/qutebrowser/qutebrowser/issues/4384#issuecomment-433202100

Sorry about the false report.
