### ISSUE TITLE
Per domain userstyles and userscripts stored in ~/.js

### ISSUE THREAD

**Issue by ralesi** [qutebrowser/qutebrowser#4444]
I see mentioned in the issues discussion of per domain user styles and user scripts; however, I wonder if it is possible to reference a file system similar to what is used in dotjs, to store the applicable user scripts and user styles for each domain and sub domain.

**Comment by toofar** [comment]
The "per-domain"-ified settings are actually using [URL match patterns](https://developer.chrome.com/apps/match_patterns) so having a file system structure would be strictly less expressive than that. I hate to say "wait for the plugin API" when I don't know for sure what it will be but I imagine it will have page load triggers and a way to inject scripts (which could add styles) so could easily handle such a thing.

**Comment by The-Compiler** [comment]
Once stylesheets support domain patterns, you could also have a bit of Python in your `config.py` which reads them from those folders and sets the values accordingly.
