### ISSUE TITLE
KeyboardInterrupt caused segfault

### ISSUE THREAD

**Issue by apnewberry** [qutebrowser/qutebrowser#4458]
I can't reproduce this, but it did happen. I opened qutebrowser in the terminal, then quit it using C-c. You can see the ^C annotation at `XX:54:14`, followed by `Segmentation fault`. Trying it again, it just closes cleanly.

```
$ qutebrowser
XX:34:02 WARNING: Incompatible version of OpenSSL
XX:34:02 WARNING: Could not initialize QtNetwork SSL support. If you use OpenSSL 1.1 with a PyQt package from PyPI (e.g. on Archlinux or Debian Stretch), you need to set LD_LIBRARY_PATH to the path of OpenSSL 1.0. This only affects downloads.
[1205/233403.760882:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glKgqGyB (deleted)
  Error: No such file or directory
[1205/233403.762799:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/user/#153676 (deleted)
  Error: No such file or directory
XX:34:04 INFO: Run :adblock-update to get adblock lists.
[7824:7851:1205/233405.541058:ERROR:nss_util.cc(727)] After loading Root Certs, loaded==false: NSS error code: -8018
^CXX:54:14 INFO: SIGINT/SIGTERM received, shutting down!
XX:54:14 INFO: Do the same again to forcefully quit.
Segmentation fault

$ qutebrowser --version
[1205/235658.687497:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glHbCXSP (deleted)
  Error: No such file or directory
XX:56:58 WARNING: Incompatible version of OpenSSL
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.6
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.4.0
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: no

Style: QFusionStyle
Platform: Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: Ubuntu 18.04.1 LTS (ubuntu)
Frozen: False
Imported from /home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/qutebrowser
Using Python from /home/user/.envs/dotfiles-_bp8OBTv/bin/python3
Qt library executable path: /home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/PyQt5/Qt/libexec, data path: /home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/PyQt5/Qt

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 0:00:00
 

```

**Comment by jgkamat** [comment]
I don't think we can do anything about it without a stacktrace

https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc

apnewberry writes:

> I can't reproduce this, but it did happen:
>
> ```
> $ qutebrowser
> XX:34:02 WARNING: Incompatible version of OpenSSL
> XX:34:02 WARNING: Could not initialize QtNetwork SSL support. If you use OpenSSL 1.1 with a PyQt package from PyPI (e.g. on Archlinux or Debian Stretch), you need to set LD_LIBRARY_PATH to the path of OpenSSL 1.0. This only affects downloads.
> [1205/233403.760882:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glKgqGyB (deleted)
>   Error: No such file or directory
> [1205/233403.762799:WARNING:stack_trace_posix.cc(699)] Failed to open file: /home/user/#153676 (deleted)
>   Error: No such file or directory
> XX:34:04 INFO: Run :adblock-update to get adblock lists.
> [7824:7851:1205/233405.541058:ERROR:nss_util.cc(727)] After loading Root Certs, loaded==false: NSS error code: -8018
> ^CXX:54:14 INFO: SIGINT/SIGTERM received, shutting down!
> XX:54:14 INFO: Do the same again to forcefully quit.
> Segmentation fault
>
> $ qutebrowser --version
> [1205/235658.687497:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.glHbCXSP (deleted)
>   Error: No such file or directory
> XX:56:58 WARNING: Incompatible version of OpenSSL
> qutebrowser v1.5.2
> Git commit:
> Backend: QtWebEngine (Chromium 65.0.3325.230)
>
> CPython: 3.6.6
> Qt: 5.11.2
> PyQt: 5.11.3
>
> sip: 4.19.13
> colorama: 0.4.0
> pypeg2: 2.15
> jinja2: 2.10
> pygments: 2.2.0
> yaml: 3.13
> cssutils: no
> attr: 18.2.0
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebKitWidgets: no
> pdf.js: no
> sqlite: 3.24.0
> QtNetwork SSL: no
>
> Style: QFusionStyle
> Platform: Linux-4.15.0-39-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
> Linux distribution: Ubuntu 18.04.1 LTS (ubuntu)
> Frozen: False
> Imported from /home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/qutebrowser
> Using Python from /home/user/.envs/dotfiles-_bp8OBTv/bin/python3
> Qt library executable path: /home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/PyQt5/Qt/libexec, data path: /home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/PyQt5/Qt
>
> Paths:
> cache: /home/user/.cache/qutebrowser
> config: /home/user/.config/qutebrowser
> data: /home/user/.local/share/qutebrowser
> runtime: /run/user/1000/qutebrowser
>
> Uptime: 0:00:00
>
>
> ```

**Comment by apnewberry** [comment]
I can't find one. If it happens again I'll try to collect more info.
