### ISSUE TITLE
Dragging tabs multiple positions doesn't work

### ISSUE THREAD

**Issue by benoncoffee** [qutebrowser/qutebrowser#4461]
**Version info (see `:version`)**:
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.1
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.26.0
QtNetwork SSL: OpenSSL 1.1.1a  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.19.4-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/ruben/.cache/qutebrowser
config: /home/ruben/.config/qutebrowser
data: /home/ruben/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:13:38

**Description**
I noticed that dragging tabs no longer works. When I have > 2 tabs open and f I left-click on a tab, hold the mousebutton, and move the mouse pointer to the left or right across multiple open tabs, the tab I drag just moves a single position to the right or left. That is, if I drag it to the left it will switch places with the tab on the left (same for dragging to the right), even if I drag the tab further than that. The icons of the tabs glitch as well: The icon of the tab I am dragging gets duplicated to the tab I am dragging across (it gets updated to the right icon when I switch to that tab again).

I know that the behaviour used to be different, but I do not know the last version in which this works (I often update my packages).

**How to reproduce**
Open eleven different tabs, and try dragging the leftmost tab all the way to the right, or the rightmost tab all the way to the left.

Edit: Before, I claimed that three tabs was enough to reproduce the issue. This is *not* the case.

**Comment by The-Compiler** [comment]
Works fine here. Can you reproduce with `--temp-basedir`?

**Comment by jgkamat** [comment]
This was fixed by #4381 , which should be in the next major release.

**Comment by The-Compiler** [comment]
That shouldn't matter with only three tabs like described in the issue, no?

**Comment by benoncoffee** [comment]
My apologies, it works fine with three tabs. It start being an issue with more than 10 tabs. It didn't come to mind that the number of tabs would be a factor, and I figured three tabs would be the smallest case in which the issue could be demonstrated. I should have actually tested it before reporting though.

In any case, good to see that the maintainers are so resposive. Keep up the good work :)
