### ISSUE TITLE
Deutsche Bank online banking does not work

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#4462]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/65dc65d3

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
yes

**Description**
What is supposed to be online banking is showing a blank page indefinitely.

**How to reproduce**

https://meine.deutsche-bank.de/trxm/db/

**Comment by The-Compiler** [comment]
That URL doesn't load for me in Chromium/Firefox either, so this doesn't seem to be a qutebrowser issue.

**Comment by The-Compiler** [comment]
Oh, after waiting for a minute or so, it loads fine:

![image](https://user-images.githubusercontent.com/625793/49687680-c77c7c80-fb06-11e8-8dd2-34002304442b.png)

Is that different from what you're seeing?

**Comment by mike402** [comment]
It seems to have worked one of 20 or so tries, and after I closed the
tab that did work, it won't work again...

Also all those tabs don't have any address in the status bar, and
trying to yank their URL says "invalid URL".

**Comment by The-Compiler** [comment]
Do you see the same behavior in another browser as well? To me it seems more like they're having some kind of server issues.

**Comment by mike402** [comment]
Sorry, I will only be able to check at work, on Monday. But yes, it
could be, because somehow it started working again...

**Comment by mike402** [comment]
It works now, even with the "reduce fingerprinting" settings. Seems they did have server problems there.
