### ISSUE TITLE
Poor Performance, and crashes 

### ISSUE THREAD

**Issue by 191205** [qutebrowser/qutebrowser#4464]
**Version info (see `:version`)**:
**Version**: Recent install of Qutebrowser-Git 
**Os** : Arch linux
**Hardware** : IMac 2016

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
I haven’t tested that yet, but i think it has nothing to do with the issue 
**Description**
Hay, I’m big fan and hard core supporter of qutebrowser, I appreciate all the work put into it, it made my browsing experience feel natural, with overall making my transition to mouse-free environment joyful aside from being possible !!

I’ve used qutebrowser on macos and haven’t faced any problems . but when I transferred to linux, qutebrowser became unusable to the point where i’m looking for replacement. 

The issue is with software rendering and QtWebKit rendering. 

When I start qutebrowser it tells that QtWebEngine failed because i’m using Nouveau graphics and offers me two ways to fix it

when i force QtWebKit it doesn’t work and when i go with the second fix the browsing experience is really bad , pages does not load, crashes in network and so on 

is there a workaround, another fix or any recommendation for this “Nouveau graphics” issue 

thanks 
sam

**Comment by The-Compiler** [comment]
Software rendering indeed can be a quite big performance impact, and QtWebKit is unfortunately rather buggy compared to QtWebEngine (and seems unmaintained).

There are some plans to change that in Qt 5.13 (May 2019), see https://bugreports.qt.io/browse/QTBUG-71126 - nothing qutebrowser itself can do there, though.
