### ISSUE TITLE
IPv6 does not work with Teredo

### ISSUE THREAD

**Issue by MarSoft** [qutebrowser/qutebrowser#4465]
**Version info (see `:version`)**:
```
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.1
Qt: 5.11.2
PyQt: 5.11.3
```

**Does the bug happen if you start with `--temp-basedir`?** (if applicable): yes.

**Description**
My ISP does not provide IPv6 support. I configured Miredo as a workaround. Now IPv6 works fine in Firefox and console utilities like `curl`.
But when I try to open IPv6 site in Qutebrowser (e.g. ipv6.google.com) I get an error: `NAME_NOT_RESOLVED`.
**The same issue happens in `Chromium 70.0.3538.110`**, so the problem is not specific to Qutebrowser but follows from the underlying engine. But I think maybe we could do a workaround for it somehow, or maybe change some default config etc.

**How to reproduce**

1. Make sure you don't have "native" or tunnelled IPv6
2. Install and run `miredo`
3. Try to open http://ipv6.google.com/

Here is the upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=259940
It dates from 2013 and still is not fixed. Looks like Google is ignoring this issue, just like many many other issues. That is why I decided to write here.

**Comment by The-Compiler** [comment]
Nothing qutebrowser can change about this I'm afraid.
