### ISSUE TITLE
Move from pkg_resources and (Py)Qt resources to importlib resources

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4467]
Looks like Python 3 has [pkgutil.get_data()](https://docs.python.org/3.5/library/pkgutil.html#pkgutil.get_data) to access resources. We might be able to use that instead of `pkg_resources` which has some issues (like https://github.com/pypa/setuptools/issues/510).

**Comment by konstantint** [comment]
Consider using [this](https://importlib-resources.readthedocs.io/) instead.

**Comment by merwok** [comment]
FTR:
- pkgutil.get_data is in all current Python versions (I think it dates from PEP 302); it is not guaranted to work for all packages (depending on the importer used: classic filesystem vs zipfiles vs other sources)

- importlib-resources is a recent project with a few functions made to replace pkg_resources

**Comment by The-Compiler** [comment]
There's also [importlib_resources](https://importlib-resources.readthedocs.io/en/latest/) nowadays.

**Comment by The-Compiler** [comment]
From https://github.com/pypa/setuptools/issues/510:

> In particular, the `importlib.resources` and `importlib.metadata` stdlib packages (and their `_`-separated backports) attempt to satisfy the most common use-cases around metadata (including fast entry point parsing) and package resource retrieval. At the same time, this project is deprecating egg-based installs and easy_install.
> 
> As a result, use of the `pkg_resources` package for these use-cases is discouraged and the module is largely deprecated.

So we should indeed switch to `importlib.resources` (if on Python >= 3.7) and `importlib_resources` (otherwise, PyPI backport). There's a migration guide here: https://importlib-resources.readthedocs.io/en/latest/migration.html

**Comment by The-Compiler** [comment]
For `pkg_resources.parse_version`, I initially thought we could just use `tuple([int(part) for part in version.split('.')])` - however, that handles trailing zeroes differently to what we'd expect:

```python
>>> import pkg_resources
>>> v1 = pkg_resources.parse_version('1.2.0')
>>> v2 = pkg_resources.parse_version('1.2')
>>> v1 < v2
False
>>> v1 > v2
False
>>> v1 == v2
True
```

```python
>>> (1,2,0) < (1,2)
False
>>> (1,2,0) > (1,2)
True
>>> (1,2,0) == (1,2)
False
```

So, some additional normalization would be needed there - however, via #3785 I just realized we can use [QVersionNumber](https://doc.qt.io/qt-5/qversionnumber.html) instead of hand-rolling something:

```python
>>> v1q, _suffix = QVersionNumber.fromString('1.2.0')
>>> v2q, _suffix = QVersionNumber.fromString('1.2')
>>> v1q == v2q
False
>>> v1q < v2q
False
>>> v1q > v2q
True

>>> v1q.normalized() > v2q.normalized()
False
>>> v1q.normalized() < v2q.normalized()
False
>>> v1q.normalized() == v2q.normalized()
True
```

cc @coiby

**Comment by coiby** [comment]
> For `pkg_resources.parse_version`, I initially thought we could just use `tuple([int(part) for part in version.split('.')])` - however, that handles trailing zeroes differently to what we'd expect:
> 
> ```python
> >>> import pkg_resources
> >>> v1 = pkg_resources.parse_version('1.2.0')
> >>> v2 = pkg_resources.parse_version('1.2')
> >>> v1 < v2
> False
> >>> v1 > v2
> False
> >>> v1 == v2
> True
> ```
> 
> ```python
> >>> (1,2,0) < (1,2)
> False
> >>> (1,2,0) > (1,2)
> True
> >>> (1,2,0) == (1,2)
> False
> ```
> 
> So, some additional normalization would be needed there - however, via #3785 I just realized we can use [QVersionNumber](https://doc.qt.io/qt-5/qversionnumber.html) instead of hand-rolling something:
> 
> ```python
> >>> v1q, _suffix = QVersionNumber.fromString('1.2.0')
> >>> v2q, _suffix = QVersionNumber.fromString('1.2')
> >>> v1q == v2q
> False
> >>> v1q < v2q
> False
> >>> v1q > v2q
> True
> 
> >>> v1q.normalized() > v2q.normalized()
> False
> >>> v1q.normalized() < v2q.normalized()
> False
> >>> v1q.normalized() == v2q.normalized()
> True
> ```
> 
> cc @coiby

I know you told me somewhere `tuple([int(part) for part in version.split('.')])` is not enough but I forgot where it is. I didn't find  this post util finishing one to replace `pkg_resources.parse_version`. In case it interests someone, I'll paste the code here  which has passed the `test_version_check` test in tests/unit/utils/test_qtutils.py,
```py
def parse_version(version):
    """Parse version string.

    This is a replacement of pkg_resources.parse_version
    """
    parts = [int(part) for part in version.split('.')]
    while parts[-1] == 0:
        parts.pop()
    return tuple(parts)
```

**Comment by The-Compiler** [comment]
@coiby This will fail when there's a non-numeric suffix, such as when using qutebrowser with an in-development PyQt version. `QVersionNumber` will still work in that case:

```
>>> from PyQt5.QtCore import PYQT_VERSION_STR, QVersionNumber
>>> PYQT_VERSION_STR
'5.15.2.dev2009281246'
>>> v, _suffix = QVersionNumber.fromString('5.15.2.dev2009281246')
>>> v == QVersionNumber(5, 15, 2)
True
```

**Comment by coiby** [comment]
> @coiby This will fail when there's a non-numeric suffix, such as when using qutebrowser with an in-development PyQt version. `QVersionNumber` will still work in that case:
> 
> ```
> >>> from PyQt5.QtCore import PYQT_VERSION_STR, QVersionNumber
> >>> PYQT_VERSION_STR
> '5.15.2.dev2009281246'
> >>> v, _suffix = QVersionNumber.fromString('5.15.2.dev2009281246')
> >>> v == QVersionNumber(5, 15, 2)
> True
> ```

Thank you for pointing out the limitation of that simple version. I'm going to improve my existing patches including #5495 to get them merged. If  @eli-schwartz or anyone else has  started doing of job of replacing pkg_resources using QVersionNumber, I'm going to start it since #5495 depends on this.

**Comment by eli-schwartz** [comment]
I've never dealt with QVersionNumber myself, so if you're ready to work on it, go right ahead.

(packaging.version has the advantage of being guaranteed-identical behavior since it's literally the same code, but imported from its canonical location rather than importing it from the copy which pkg_resources imports. But if qutebrowser wishes to take advantage of the opportunity to use QVersionNumber, then sure.)

**Comment by coiby** [comment]
> I've never dealt with QVersionNumber myself, so if you're ready to work on it, go right ahead.
> 
> (packaging.version has the advantage of being guaranteed-identical behavior since it's literally the same code, but imported from its canonical location rather than importing it from the copy which pkg_resources imports. But if qutebrowser wishes to take advantage of the opportunity to use QVersionNumber, then sure.)

Thank you for sharing your thoughts on this!

In #5495, I also wanted to use packaging
> The second question is about the replacement of pkg_resources.parse_version. After looking at packaging's implementation of parse_version, I'm not sure borrowing tuple([int(part) for part in version.split('.')]) from old setuptools is sufficient. I also find that pkg_resources.parse_version is actually a wrapper of packaging.version. For newer version of Python, we can use packaging directly. For older version of Python, we need to install packaging since it's only directly accessible from pkg_resources

 but @The-Compiler thought it's a bit of overkill
>  Definitely -1 to adding an external dependency just to parse version numbers.

Fortunately we have QVersionNumber now which I think is a better idea.

**Comment by eli-schwartz** [comment]
It's not much of an overkill since pkg_resources doesn't publicly support the extern.* imports, and on some systems (arch!) it already depends on the system `packaging`, but you can do a fallback import to `pkg_resources.extern.*` which is admittedly still slow.

Some versions of pkg_resources actually dropped the extern code and did normal dependencies...

Either way, the state of things today is that qutebrowser depends on the packaging module as a transitive dep; raising it to an explicit dep doesn't make things worse.

Desiring to completely remove it is a valid goal; IMHO "because adding a new dep is bad" is not a valid rationale...

**Comment by The-Compiler** [comment]
I replaced `pkg_resources.parse_version` with `QVersionNumber` in 46e6839e21d9ff72abb6c5d49d5abaa5a8da8a81, so the only remaining bits are `pkg_resources.resource_{filename,string}` now. Taking the freedom to hide the comments above related to version parsing as resolved.

**Comment by The-Compiler** [comment]
From a quick look at replacing the resources part, it looks to me like `resource_filename` is [rather problematic](https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename):

> `resource_filename()` is one of the more interesting APIs because it guarantees that the return value names a file on the file system. This means that if the resource is in a zip file, `pkg_resources` will extract the file and return the name of the temporary file it created. The problem is that `pkg_resources` also *implicitly* cleans up this temporary file, without control over its lifetime by the programmer.

It looks like `importlib.resources` provides a context manager instead, which is the proper way to solve it, but problematic for our usecase with `data_url` and `resource_url` in jinja templates because we don't know when Qt will load the resource.

We can get rid of `data_url` entirely after #5832 is in (and it only needs the filename to guess the mimetype, but we actually already have that in `path`). As for `resource_url`, that will likely need to be rewritten to serve the resources as a stream via `qute://resource/foo.png` or so, which then can use the equivalents of `resource_stream()` or `resource_string()`.

The only remaining place where `resource_filename` is used is then `utils.preload_resources`, which is mainly there as a fix for #1943. I'm not actually sure if this was a good idea after all, it might be better to drop it entirely and replace it with some kind of version check at least for the Python/JS API.

Finally, while we're at it, it'd probably be good to review existing `utils.read_file` calls -  I'd like to split them into `utils.resource_text` and `utils.resource_bytes` or so, and some of those might benefit from using the file streaming API rather than reading the entire resource? Maybe it'd be good to rethink the API a bit based on the new `importlib.resources` API anyways.

**Comment by eli-schwartz** [comment]
If pkg_resources.resource_string() got dropped in favor of importlib.resources.files() on python 3.9, would you prefer to fall back on pkg_resources since it is still used in resource_filename, or add a dependency on `importlib_resources; python_version < "3.9"` for the backport?

**Comment by The-Compiler** [comment]
@eli-schwartz Given that the plan is to get rid of `pkg_resources` entirely for 2.0.0, we'll need the `importlib_resources` backport anyways, so it seems fine to start using it now rather than later (given that `master` is headed towards 2.0).

**Comment by eli-schwartz** [comment]
And yes, you do need 3.9 for the files() API or else you cannot traverse e.g. `javascript/history.js` in subdirectories, without adding `javascript/__init__.py` to turn it into a pointless package.

**Comment by The-Compiler** [comment]
Huh, you mean the backport doesn't support that? We'll definitely continue to support 3.7/3.8 for a while. Doesn't hurt to turn that into a package though, if that's needed.

**Comment by eli-schwartz** [comment]
```
if sys.version_info >= (3,9):
    # has a files() API
    import importlib.resources as importlib_resources
else:
    # needs the backport in order to get at the files() API
    import importlib_resources
```

**Comment by The-Compiler** [comment]
Ah, I didn't realize that [the `files()` API was only added in 3.9](https://docs.python.org/3.9/library/importlib.html#importlib.resources.files) - note we'll need the backport for 3.6 anyways (which we also still support), but also requiring it on 3.7 and 3.8 doesn't hurt much I think.

**Comment by eli-schwartz** [comment]
Yeah, basically just pointing out it might look funny due to version checking instead of try/except, but it's intentional

**Comment by eli-schwartz** [comment]
^^ implemented

**Comment by The-Compiler** [comment]
As for PyInstaller support, I hoped I could do this with #5946 merged:

```diff
commit 976c648a131c687d488bec38967bf4a032125b1f (HEAD -> dev, origin/dev)
Author: Florian Bruhin <me@the-compiler.org>
Date:   Tue Dec 8 21:54:23 2020 +0100

    Remove PyInstaller handling for utils.read_file

diff --git a/qutebrowser/utils/utils.py b/qutebrowser/utils/utils.py
index 331bf5f96..1b3b09ac1 100644
--- a/qutebrowser/utils/utils.py
+++ b/qutebrowser/utils/utils.py
@@ -209,24 +209,12 @@ def read_file(filename: str, binary: bool = False) -> Any:
     if not binary and filename in _resource_cache:
         return _resource_cache[filename]
 
-    if hasattr(sys, 'frozen'):
-        # PyInstaller doesn't support pkg_resources :(
-        # https://github.com/pyinstaller/pyinstaller/wiki/FAQ#misc
-        fn = os.path.join(os.path.dirname(sys.executable), filename)
-        if binary:
-            f: IO
-            with open(fn, 'rb') as f:
-                return f.read()
-        else:
-            with open(fn, 'r', encoding='utf-8') as f:
-                return f.read()
-    else:
-        p = importlib_resources.files(qutebrowser) / filename
+    p = importlib_resources.files(qutebrowser) / filename
 
-        if binary:
-            return p.read_bytes()
+    if binary:
+        return p.read_bytes()
 
-        return p.read_text()
+    return p.read_text()
 
 
 def resource_filename(filename: str) -> str:
@@ -239,6 +227,8 @@ def resource_filename(filename: str) -> str:
         The absolute filename.
     """
     if hasattr(sys, 'frozen'):
+        # PyInstaller doesn't support pkg_resources :(
+        # https://github.com/pyinstaller/pyinstaller/wiki/FAQ#misc
         return os.path.join(os.path.dirname(sys.executable), filename)
     return pkg_resources.resource_filename(qutebrowser.__name__, filename)
 
```

but PyInstaller errors out. Will need to investigate later, but this doesn't block the PR anyways as we can just keep that in for the moment.

**Comment by The-Compiler** [comment]
Turns out PyInstaller's built-in `importlib.resources` support actually works, but the data files need to be in a `qutebrowser` subdirectory. However, that conflicts with the `qutebrowser` executable name on macOS... I'll leave the current code in for the moment.

**Comment by The-Compiler** [comment]
`pkg_resources` is now fully gone - thanks to @eli-schwartz and @coiby for getting the ball rolling! PyQt's resource system is still used for the icons, but I split that off to #6062 - that can wait until after v2.0.0.

**Comment by coiby** [comment]
@The-Compiler Good job! This saves another commit for #5495 .
