### ISSUE TITLE
hjkl and arrows scrolling no longer work in many cases

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#4469]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/3f7d0307

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
yes

**Description**
It is no longer possible to scroll many sites with hjkl and arrows. I think this started happening with the update to 1.5.2

Sometimes if you open the same page in a new tab it works for a while.

On Google image search I see that hjkl move the focus within the search results instead.

**How to reproduce**
http://www.atpforum.eu/forum/technical-subjects/-062-radio-navigation/10684-urgent-vor-rmi
also Google image search

**Comment by jgkamat** [comment]
Michael Danilov writes:

> Version info (see :version):
> https://paste.the-compiler.org/view/3f7d0307
>
> Does the bug happen if you start with --temp-basedir? (if applicable):
> yes
>
> Description
> It is no longer possible to scroll many sites with hjkl and arrows
>
> On Google image search I see that hjkl move the focus within the search results instead.
>
> How to reproduce
> http://www.atpforum.eu/forum/technical-subjects/-062-radio-navigation/10684-urgent-vor-rmi
> also Google image search

This works for me in both cases in --temp-basedir. The google image case is a
little weird since it hijacks the up/down keys, but it still ends up working
in the end.

**Comment by The-Compiler** [comment]
On Google Images, this likely was the case for a longer time and is expected. The forum works fine for me. Also, there isn't anything related that changed in qutebrowser recently, so this is probably something on your side.
