### ISSUE TITLE
Qt 5.12: Name error in QLocalServer::listen on macOS

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4471]
https://travis-ci.org/qutebrowser/qutebrowser/jobs/466626800

`tests/unit/misc/test_ipc.py::TestSendOrListen::test_correct_socket_name` seems to fail with `QLocalServer::listen: Name error (error 2)`

**Comment by Numkil** [comment]
This is probably related. After upgrading to qt 5.12 on mac I can't use qutebrowser anymore.
![screen shot 2018-12-12 at 09 25 41](https://user-images.githubusercontent.com/5604686/49884881-34a94e00-fe36-11e8-87e7-c37554808fa6.png)

**Comment by The-Compiler** [comment]
@Numkil Oh, fun. I suggest using the `.dmg` for now, which bundles its own copy of Qt.

**Comment by The-Compiler** [comment]
Also see #888 - there the maximum length was 104 chars, and `/private/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/qutebrowser/ipc-0b49f78f3a9f8e420b07ebfd15916435` (on Travis) is just one character above that... Did how Qt names temporary directories on macOS change in Qt 5.12 in some way?

**Comment by The-Compiler** [comment]
I can't find any change in Qt about this, it just seems to use [NSTemporaryDirectory](https://developer.apple.com/documentation/foundation/1409211-nstemporarydirectory?language=occ). My best bet would be that Qt changed its minimum macOS version, and based on that (and whatever XCode library it was built with, or something), macOS changed its behavior?
