### ISSUE TITLE
Scroll widget affects scrolling performance

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#4475]
Turning the scroll widget (`statusbar.widgets`) off results in a noticeable increase in scrolling performance when using a touchpad or touchscreen. We should find some way to make the scrolling widget have a smaller impact, maybe by running setText in the background (since it's not essential we're correct all the time there).

We probably should add a benchmark for the entire scroll hook as well, as for smooth-scrolling, it's important for that to be as fast as possible.

**Comment by edrex** [comment]
Wow, this solves the choppy scrolling issue which has been the biggest usability issue for me since I first tried qutebrowser! Honestly, the default scrolling (with the widget on) is super painful.
