### ISSUE TITLE
Support Libre js

### ISSUE THREAD

**Issue by LinArcX** [qutebrowser/qutebrowser#4485]
Hello. I am reading this awesome article :
https://www.gnu.org/philosophy/javascript-trap.html
Stallman offer to Run Libre js along with your browser. Is it possible to use it (for example as a Plugin ) in qutebrowesr?

**Comment by mschilli87** [comment]
@LinArcX: AFAIK, librejs is available as webextension. Unfortunately, support for this API is currently not planned for qutebrowser. See https://github.com/qutebrowser/qutebrowser/issues/30 for details. Once the python-based plugin-API is there (hopefully 'soon'), porting librejs would become an option and I'd support any effort in this direction any way I can.

**Comment by LinArcX** [comment]
Thank you so much.

**Comment by The-Compiler** [comment]
FWIW this kind of thing won't be possible using the Python API, as there's no way to access response content. See e.g. https://bugreports.qt.io/browse/QTBUG-61071

**Comment by fine2006** [comment]
In the current situation, is it possible to intergrate librejs?

**Comment by The-Compiler** [comment]
@fine2006 See the bug I linked above. It's still open, so, no.
