### ISSUE TITLE
Copying link to Github issue comment doesn't work

### ISSUE THREAD

**Issue by jcrd** [qutebrowser/qutebrowser#4487]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/cf3eee5d

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes.

**Description**
"Copy link" in the ellipsis dropdown menu of Github issue comments doesn't copy anything to the clipboard. It also doesn't receive hints when `f` is pressed.
![image](https://user-images.githubusercontent.com/44040597/50313068-7c982880-0467-11e9-8645-4ec2562fa492.png)

Copying the link works in Chromium.

**How to reproduce**
1. Select "Copy link" with mouse
2. Run `xclip -o -selection clipboard`

**Comment by The-Compiler** [comment]
That seems to be some kind of Qt issue, I opened https://bugreports.qt.io/browse/QTBUG-72714.

**Comment by rakanalh** [comment]
Issue still exists though i have `qt5-webengine 5.12.4-1` which is a recent version installed.

**Comment by The-Compiler** [comment]
@rakanalh You need to set `content.javascript.can_access_clipboard` - it's supposed to be unneeded when copying happens as response to e.g. a click, but that doesn't seem to work properly.
