### ISSUE TITLE
Allow Side Tabs

### ISSUE THREAD

**Issue by HeathNaylor** [qutebrowser/qutebrowser#4495]
I have found that side tabs which can be siblings, or children and which can be rearranged are vastly more powerful than the standard horizontal tab systems. Firefox has an extension that handles it the best I have seen:

https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
![image](https://user-images.githubusercontent.com/10814256/50489218-a00d2700-09c3-11e9-93ab-9654b253eaaa.png)

It would be very nice if we could decide on a method of adding this to Qutebrowser as well. Thoughts?

**Comment by The-Compiler** [comment]
You can already `:set tabs position left`, and there's #927.

**Comment by qazip** [comment]
@The-Compiler, is it also possible to change the height of the tabs, specially when using `:set tabs position left`?

**Comment by The-Compiler** [comment]
@qazip It's calculated based on `fonts.tabs.unselected` and `tabs.padding`.
