### ISSUE TITLE
Revocer last session that accidentally override by new session tabs. 

### ISSUE THREAD

**Issue by LinArcX** [qutebrowser/qutebrowser#4496]
#### Current Behavior
Currently if you save some tabs under a name with __session_save__ command, it will override previous history.

#### Expected Behavior
It's better to remember all sessions history. i mean they must be "read-only" and not be modified by newest changes. maybe someone(like me) accidentally save some tabs under a name and previous tabs Are destroyed forever!

#### Steps to reproduce
1. open some tabs and save them under a name like: __example__ with: __session_save__ command.
2. open new tabs and repeat step 1.
3. last tabs override and no chances to recover previous closed tabs that save under same name.

**Comment by The-Compiler** [comment]
I disagree with this - it might be possible to do this kind of thing as an extension soon (#30), but having this as the default behavior sounds too confusing to me.

Also see #3853 which allows adding tabs to existing sessions.

**Comment by toofar** [comment]
They are just text files too so you can keep them in version control if you are worried about clobbering them by mistake.

**Comment by ninewise** [comment]
Maybe a patch that warns you before overwriting existing sessions could be considered?
