### ISSUE TITLE
widevine and MacOS

### ISSUE THREAD

**Issue by edganiukov** [qutebrowser/qutebrowser#4505]
So far I Netflix, Spotify, etc doesn't work on MacOS. I think this is due to widevine (https://bitmovin.com/demos/drm says my browser doesn't support everything but `video/webm`).
Is there a way to make it work on MacOS? Or, probably, someone made it already.

**Comment by The-Compiler** [comment]
You'll need two things for Widevine to work:

- Proprietary codec support. The prebuilt versions of qutebrowser don't come with those - this isn't going to change on Windows, but it might change on macOS: #4127. Right now, you'd need to run qutebrowser from source with a Qt install with proprietary codecs enabled (like Homebrew's)
- Widevine itself. Apparently, it's possible to copy it from Chrome's .dmg, see [this blog post](http://blog.qt.io/blog/2016/06/03/netflix-qt-webengine-5-7/).
