### ISSUE TITLE
Website: background-color not defined

### ISSUE THREAD

**Issue by tastytea** [qutebrowser/qutebrowser#4510]
**Description**

On https://www.qutebrowser.org/, the text color is defined but no background color. This leads to gray text on gray background for me.

> body {
> 	font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
> 	-webkit-text-size-adjust: none;
> 	color: #333333;
>     overflow-y: scroll;
> }

![screenshot_2019-01-06t14 10 13](https://user-images.githubusercontent.com/3681516/50736347-7b2f6580-11b4-11e9-9672-b21d0b99a316.png)

**How to reproduce**

Configure your browser to use white text on black
background as fallback.

**Comment by jgkamat** [comment]
tastytea writes:

> Configure your browser to use white text on black
> background as fallback.

This isn't qb's problem, but a problem with the website, I think this is
easily fixable though.
