### ISSUE TITLE
Customize CSS of dev tools (web inspector)

### ISSUE THREAD

**Issue by shioyama** [qutebrowser/qutebrowser#4516]
I've searched everywhere and can't seem to find an answer to this question, so out of desperation decided to ask here: is there any way to modify the css for the web inspector (to increase the font size, for one thing) ?

I see [here](https://stackoverflow.com/questions/15964612/changing-customizing-safaris-web-inspector-font) that this seems to be possible in Safari/webkit, but not sure that that translates to webengine (which is what I am using).

Any help much appreciated, keep up the great work!

**Comment by toofar** [comment]
I'm pretty sure the answer is no. Chromium might offer a way to theme it but I don't think QtWebEngine offers us a way to (and if they do qutebrowser doesn't know about it). You miiight be able to patch the request interceptor to [redirect](https://doc.qt.io/qt-5.11/qwebengineurlrequestinfo.html#redirect) the requests for `chrome-devtools://devtools/*` to your own patched copy of the resources but no-one here has any experience with that.

**Comment by shioyama** [comment]
Hmm... ok, that's too bad. I'll wait a bit more to see if anyone else has other suggestions, then close this I guess. Thanks!

**Comment by jgkamat** [comment]
You can change between a built-in dark and light theme in the inspector
settings, as you would in chrome. Not sure how to customize the inspector more
than that though.

**Comment by shioyama** [comment]
Yeah, I switched to dark but doesn't really help much. Thanks though! I'll close this.
