### ISSUE TITLE
:set content.images false hides images in inspector

### ISSUE THREAD

**Issue by olmokramer** [qutebrowser/qutebrowser#4517]
**Version info (see `:version`)**:

```
qutebrowser v1.5.2
Git commit: cbb6ae860 (2018-12-15 18:21:51 +0100)
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.0
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.0.943 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.26.0
QtNetwork SSL: OpenSSL 1.1.1a  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.19.12-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/olmo/.cache/qutebrowser
config: /home/olmo/.config/qutebrowser
data: /home/olmo/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:11:19
```

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):

Yes, it also happens when I start qb with `qutebrowser --temp-basedir -s content.images false`.

**Description**

When `content.images` is set to `false` globally it also hides images in the inspector, rendering it unusable as it uses a lot of icons that are not accompanied by text, as shown in this image:

![qb-inspector](https://user-images.githubusercontent.com/3612514/50895392-46b2e800-1406-11e9-8758-9158dca6ac8d.png)

When you `:set content.images true` the images will become visible.

I tried `:set --pattern qute://*/* content.images true`, and also with `chrome://*/*` as a pattern, hoping that would solve it, but it didn't. Am I not using the correct protocol there?

**How to reproduce**

1. Run qb with `qutebrowser --temp-basedir -s content.images false`
2. Open the inspector with <kbd>wi</kbd>
3. Execute `:set content.images true` in qb
4. The images now appear in the inspector

**Comment by olmokramer** [comment]
I just see an empty page when I `:open -t chrome-devtools://devtools/bundled/inspector.html`, even after `:set -u chrome-devtools://* content.images true`. The latter command also doesn't affect the inspector window, but I suppose that's what you explained about it not being an AbstractTab?

IMO images in the inspector should just always be shown. I suppose the images are available locally so there's not really a reason to avoid them.

**Comment by Eluminae** [comment]
I can relate this is still an open issue.

**Comment by The-Compiler** [comment]
@toofar Thanks for the inspiration! I pushed something based on that in 07e532e.
