### ISSUE TITLE
Feature request: regular expressions in page search

### ISSUE THREAD

**Issue by qwertea** [qutebrowser/qutebrowser#4521]
Pretty self explanatory. cVim had this and I got pretty used to it, it would be nice to see this feature in qutebrowser.

**Comment by The-Compiler** [comment]
Duplicate of #1500

**Comment by qwertea** [comment]
Apologies. It's been nearly three years, is there any progress on the QtWebEngine side or is it still hopeless?

**Comment by The-Compiler** [comment]
More importantly, there's been no progress in Chromium, see https://bugs.chromium.org/p/chromium/issues/detail?id=687552 for a similar feature request there.

This would still require re-implementing finding entirely in JavaScript, which is slow and brittle, and not something I'm willing to do. It might be available as an extension (#30) at some point, if someone writes it.
