### ISSUE TITLE
Invert colors on the logo

### ISSUE THREAD

**Issue by actionless** [qutebrowser/qutebrowser#4531]
![2019-01-19--1547874767_217x93_scrot](https://user-images.githubusercontent.com/1655669/51422597-9be2bc80-1bb1-11e9-91ba-3688a86cade9.png)

since browser called "qute" [cute] i guess pink color could serve well:

![2019-01-19--1547874767_217x93_scrot](https://user-images.githubusercontent.com/1655669/51422678-08aa8680-1bb3-11e9-93e1-c44fd5880507.png)

or mb python-ish colors:

![2019-01-19--1547874767_217x93_scrot](https://user-images.githubusercontent.com/1655669/51422646-5f639080-1bb2-11e9-9dad-bee70d03efe4.png) 

yellow letters on blue background would remind old IE logos and could be a nice jokingly reference, but still looks too relative to qbittorent, so i wouldn't try this:

![2019-01-19--1547874767_217x93_scrot](https://user-images.githubusercontent.com/1655669/51422762-c71adb00-1bb4-11e9-8ad7-cbac30076164.png)

(i wouldn't use Qt-green color since it could give the impression what it's a browser of Qt components)

otherwise it's just too easy to mis-click since they're next menuitems to each other and even have the same amount of letters

**Comment by The-Compiler** [comment]
That's not even the "official" qutebrowser logo, no idea where that's coming from.

**Comment by actionless** [comment]
then today you've learned about icon themes.

the point what whatever it's offical or not -- it's qb letters inside blue circle

it wouldn't look so funny if they wouldn't be one after another in the Internet applications submenu and have the same length

i mean there are so many shapes and colors, why to be stubborn and having the same logo identity as another previously popular app:

![2019-01-19-073857_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/51423243-59bf7800-1bbd-11e9-9dd3-f8426573fe9b.png)

**Comment by The-Compiler** [comment]
I'm well aware of icon themes, I'm just not sure why you think it's useful to talk about something qutebrowser has quite little influence on rather than the actual logos:

![image](https://user-images.githubusercontent.com/625793/51423497-5d54fe00-1bc1-11e9-82b9-3b16373ce703.png) ![image](https://user-images.githubusercontent.com/625793/51423507-9ab98b80-1bc1-11e9-9a88-c3e761472a8d.png)

Maybe still somewhat problematic in 16x16px, but still IMHO more distinctive than in the icon theme.

Stubborn or not - you don't just change an icon which has been around for over four years (with some small modifications three years ago) without causing confusion as well - especially when there are things like stickers and t-shirts around with it.

A concrete proposal which actually looks nice might convince me otherwise, but other than that, I'm not interested in any changes to the current icon.

**Comment by actionless** [comment]
i'm not implying what your logo identity copied or inspired by qbittorrent's, but rather stating what it by accidence have too much similarities (and not only with logo but in menu positioning)

i think the least intrusive way could be just changing the colors or scale of the elements without changing the element themselves:


![](https://user-images.githubusercontent.com/625793/51423497-5d54fe00-1bc1-11e9-82b9-3b16373ce703.png)  ![51423507-9ab98b80-1bc1-11e9-9a88-c3e761472a8d](https://user-images.githubusercontent.com/1655669/51424092-7f527e80-1bc9-11e9-8b27-b32ee6e1790b.png) 

![51423507-9ab98b80-1bc1-11e9-9a88-c3e761472a8d--2](https://user-images.githubusercontent.com/1655669/51424093-8a0d1380-1bc9-11e9-8648-f43bb4235f20.png) ![51423507-9ab98b80-1bc1-11e9-9a88-c3e761472a8d--3](https://user-images.githubusercontent.com/1655669/51424094-8da09a80-1bc9-11e9-9248-498dbfdbd506.png)

**Comment by jgkamat** [comment]
On January 19, 2019 12:40:13 AM CST, Yauhen Kirylau <notifications@github.com> wrote:
>then today you've learned about icon themes.
>
>the point what whatever it's offical or not -- it's qb letters inside
>blue circle

Shouldnt this be a bug report to that icon theme then? I dont see how we could (or want) to change an icon theme.

> but rather stating what it by accidence have too much similarities (and not only with logo but in menu positioning)

I dont think its a reasonable goal to avoid similarlities with other logos. The space of logos that are useful is pretty small, and almost every distinctive shape has been taken (some of the examples look vaguely like the python logo to me), unless we change the logo to white noise.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by actionless** [comment]
> unless we change the logo to white noise

that would be fine unless some other, let's say popular internet messenger called Qwhitenoise, would having logo with the same idea and residing next to QuteBrowser in most of the app menus

**Comment by actionless** [comment]
>  I dont see how we could (or want) to change an icon theme.

the think about icon themes: what they usually trying to do is to take recognizable logo identity (let's say "Puprle Pidgin" in Pidgin messenger or "Blue Box" in Dropbox) and stylize to their own graphical style

so what i am trying to say, what in your official logo you have stylized "qb" letters inside blue circle differently than qBitttorrent did on their, but identity itself is very similar. so then other people stylizing those two identitys in the same style (like icon themes do) -- the difference between those two identity getting almost lost.

**Comment by jgkamat** [comment]
On January 19, 2019 1:41:55 PM CST, Yauhen Kirylau <notifications@github.com> wrote:
>
>>  I dont see how we could (or want) to change an icon theme.
>
>the think about icon themes: what they usually trying to do is to take
>recognizable logo identity (let's say "Puprle Pidgin" in Pidgin
>messenger or "Blue Box" in Dropbox) and stylize to their own graphical
>style

I dont think this is generally true; Amexia, a popular (and fantastic) icon set for android, has a single icon for all web browsers, and tweaks the colors themselves to make them distinguishable. If qutebrowser got an amexia icon, it wouldn't have a 'qb' anywhere, and if qbittorrent did it would probably get the same peer-to-peer icon syncthing gets.

Icon themes are free to do whatever they want, ie: you can publish an icon set with nothing but pink 'qb' circles if you wish. I've seen sets going from plain colors to ponies to pop stars.

>so what i am trying to say, what in your official logo you have
>stylized "qb" letters inside blue circle differently than qBitttorrent
>did on their, but identity itself is very similar. so then other people
>stylizing those two identitys in the same style (like icon themes do)
>-- the difference between those two identity getting almost lost.

This might solve one case (after many years, when the icon sets update, if they do at all), but all it takes is one more application to have a similar icon in the icon set you happen to be using for the problem to come back. I dont think reprinting the stickers and tshirts is worth it. FWIW, I'm happy that any icon set has qutebrowser in it at all, and theres no need for us to give them any more work by having an unstable logo to mimic :).

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by actionless** [comment]
>  but all it takes is one more application to have a similar icon in the icon set you happen to be using for the problem to come back

but that would be a problem of that new application to solve, not yours


> I dont think reprinting the stickers and tshirts is worth it.

from other side -- people who already bought t-shirts and stickers would have a reason to do it again ;-)

but anyway i'm not insisting on anything, just wanted to give my 50 cents on keeping logo identity recognizable despite styling context of the logo

so thanks for patient answers and best wishes with the further development!
