### ISSUE TITLE
Prompt before any redirect

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#4534]
I want to get prompted before any redirection happens.  This way people can't abuse me by giving me a relatively friendly link that's going to a trusty server (e.g. google's URL shortener), but then get automatically redirect into some private server where the person gets my details such as IP, etc.

**Comment by FlyingWombat** [comment]
I am in favor of a setting to toggle this behavior.
Similarly, a setting for "prompt before pop-up" would be good.

**Comment by jgkamat** [comment]
FWIW, there are a lot of places where directs happen in normal browsing, eg:

website.com -> http://www.website.com -> https://www.website.com

so I think this would become unusable quickly.

Either way, I don't think we can block redirects, I don't see anything in
http://doc.qt.io/qt-5/qwebengineurlrequestinfo.html

**Comment by Al-Caveman** [comment]
the internet is a very sad  place.  we should grow some balls and create a w3c alternative.  there is no reason we r kissing mr. berners-lee's ass.  http/html/css/js is all batshit needless craziness.

**Comment by The-Compiler** [comment]
It could be possible to implement this via `QWebEnginePage::acceptNavigationRequest`, but this seems much too niche/annoying to have in the core (and is not something I've ever seen any other browser do). I added it to a possible extension use-case to #30 though.
