### ISSUE TITLE
Proxy settings not working with autoconfig.yml

### ISSUE THREAD

**Issue by troubas** [qutebrowser/qutebrowser#4537]
Hi @The-Compiler , long time =)

I remember moving away from qutebrowser due to some performance issues. I'm back now because none compares in ease and consistency of use with the keyboard - also currently CPU usage is minimal so this seems fixed =).
Nice to see we've surpassed version 1 and merged the new config. Great Work!

I have an issue with my proxy settings. Setting the Proxy in autoconfig.yml (by changing it on qute://settings/)

```
settings:
  content.proxy:
    global: socks://localhost:9050/
```
do not work as expected (proxy is set to system on start).

However, setting `c.content.proxy = "socks://localhost:9050/"` in config.py works.

I'm not sure whether I'm doing something wrong, this is a bug or maybe even intentional..
It has been a nuisance figuring out what's going wrong so I figured I'd let you know - also in case somebody else is fighting with the same issue.

With love

**Comment by The-Compiler** [comment]
If you have a `config.py`, you'll need to load `autoconfig.yml` from it if you want it to be loaded - see the [relevant docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#configpy-autoconfig).

**Comment by troubas** [comment]
Doh, jep that fixed it. Thanks!
