### ISSUE TITLE
Userscript written in bash fails to start

### ISSUE THREAD

**Issue by draganczukp** [qutebrowser/qutebrowser#4546]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/02009913
**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes
**Description**
I have an userscript written in bash, [link](https://gist.github.com/9122fde6816c8b0308f3c00ddc347acb), that sends the currently open website to my phone with qdbus and KDE-Connect.
Running it with `:spawn --userscript /full/path/to/send-to-kdeconnect {url}` gives an error saying `Error while spawning command: The process failed to start`, but running it with `:spawn --userscript /bin/bash /full/path/to/send-to-kdeconnect {url}` works fine.
The script has permission to execute (`chmod +x`) and has a `#/bin/bash` at the begging so it should work, and running it directly from terminal with `./send-to-kdeconnect "https://google.com"` works as expected
**How to reproduce**

1.Download [this script](https://gist.github.com/9122fde6816c8b0308f3c00ddc347acb) and save it anywhere.
2. Run it with `:spawn --userscript /full/path/to/send-to-kdeconnect "https://google.com"`

**Comment by The-Compiler** [comment]
Your script has `#/bin/bash` rather than `#!` :wink:
