### ISSUE TITLE
Option to bind keys for :open and file save dialog

### ISSUE THREAD

**Issue by JadElClemens** [qutebrowser/qutebrowser#4550]
Coming from emacs/evil (especially completion frontends like helm and ivy, and I can only imagine these binds come from vim in the first place) it would be nice to have the option to bind certain keys, particularly C-{hjkl}, to move up/down (and in/out of folders in the file save dialog) aside from the arrow keys.

**Comment by toofar** [comment]
To be clear we are talking about the same things, the dialogs for :open and for file save look totally different right?
For the open dialog you can bind key combos like so `:bind --mode=command <Ctrl+j> completion-item-focus next` and for the file save dialog it should be in prompt mode like `:bind --mode=prompt <Ctrl+j> prompt-item-focus next`. I'm not sure how to navigate hierarchies in prompt mode.

**Comment by JadElClemens** [comment]
I actually managed to get this working with a similar method, using fake-key --global instead, but your method is probably better (in that is uses builtin functions instead of faking keypresses).

I still haven't figured out how to navigate the folder hierarchy in prompt mode. For <Ctrl-L> I'll probably just insert a '/' and for <Ctrl-H>, rl-unix-filename-rubout.

<Ctrl-L> seems sort of hacky and doesn't work if the cursor isn't placed at the end of the line (though I could just rl-end-of-line first). Anyways, I'll close this becasue all the functionality I want is technically possible.

**Comment by JadElClemens** [comment]
#

**Comment by JadElClemens** [comment]
Just for posterity (for anyone looking to replicate this), here are my binds.
`
command:
<Ctrl-h> command-item-focus prev-group
<Ctrl-j> command-item-focus next
<Ctrl-k> command-item-focus prev
<Ctrl-l> command-item-focus next-group

prompt:
<Ctrl-h> rl-end-of-line;; rl-unix-filename-rubout
<Ctrl-j> prompt-item-focus next
<Ctrl-k> prompt-item-focus prev
<Ctrl-l> rl-end-of-line;; fake-key -g /
`
