### ISSUE TITLE
Make `tab-focus last` work in different way with counts.

### ISSUE THREAD

**Issue by WloHu** [qutebrowser/qutebrowser#4552]
This is feature from VimFx' command `tab_select_most_recent`:
- w/o counts it focuses last focused tab - this is implemented in qute;
- **with counts it focuses to [count]th last focused tab** - requires "tab focus stack".

Rationale:
- count for `tab-focus last` doesn't work in any special way than for `tab-focus` so there is room for that change;
- I have lots of tabs opened and when I do long jumps sometimes I don't remember title text in tab to fast-switch to it by filtering title but I remember that it was 4th last focused.

**Comment by jgkamat** [comment]
WloHu writes:

> This is feature from VimFx' command `tab_select_most_recent`:
> - w/o counts it focuses last focused tab - this is implemented in qute;
> - with counts it focuses to [count]th last focused tab - requires "tab focus stack".

Some people will want to keep the current behavior, although I personally
prefer tab stacking too. I would personally love to have <Ctrl-o> and <Ctrl-i>
for tabs (although others seem to want them for the page: #2642).

The best solution I can come up with now is new special arguments `last_stack`
and `next_stack` (or maybe, we should make a new command for this entirely).

For implementation, we can't store indexes (as an index can change), so we can
probably store references to tabs. We can limit the size of the stack to
prevent leaking too much, and we can drop entries 'above us' in the stack if
focusing a new tab.

Should be relatively easy, but this will be touching a lot more code. I'll see
if I can look a this once the PR queue is trimmed down.

**Comment by toofar** [comment]
> I wonder what :buffer uses for managing them.

It stores indexes but not for long. It only builds the completion model when the relevant completion shows and re-builds while open in same cases (like a tab closing).
