### ISSUE TITLE
qutebrowser shows blank page

### ISSUE THREAD

**Issue by dawidpotocki** [qutebrowser/qutebrowser#4554]
**Version info (I did write it down by hand, but it should be correct)**:

```
CPython: 3.6.8
Qt: 5.11.3
PyQt: 5.11.3

sip: 4.19.13
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.0.0 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.26.0
QtNetwork SSL: LibreSSL 2.8.3

Style: QGtkStyle
Platform: Linux-4.19.18_1-x86_64-with-glibc2.6.4, 64bit
Linux distribution: void (void)
Frozen: false
Imported from /usr/bin/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library exectable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5

Path:
cache: /home/dawid/.cache/qutebrowser
config: /home/dawid/.config/qutebrowser
data: /home/dawid/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/bin/qutebrowser

```

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):

Yes, it does.

**Description**

qt5-webengine just shows blank white page with nvidia340 driver on Void Linux (glibc, not musl). Everything is "rendered correctly", because I can select things and drag them to see them, just qutebrowser doesn't show page by itself. If that matters, I use i3-gaps as my window manager.

![aig9ks2stknwq-xyuvt-jsvtozy2](https://user-images.githubusercontent.com/38681822/51954176-11009c80-24a4-11e9-935f-17203dac767e.png)

Falkon (which AFAIK also uses qt5-webengine) and qutebrowser with `--backend webkit` works without any problems.

When I execute `qutebrowser` from commandline it just spams with this:

```
[3126:3157:0130/151617.998346:ERROR:gl_context_glx.cc(182)] Failed to create GL context with glXCreateContextAttribsARB.
[3126:3157:0130/151617.998381:ERROR:gles2_command_buffer_stub.cc(305)] ContextResult::kFatalFailure: Failed to create context.
[3126:3157:0130/151617.999977:ERROR:gl_context_glx.cc(182)] Failed to create GL context with glXCreateContextAttribsARB.
[3126:3157:0130/151618.000008:ERROR:gles2_command_buffer_stub.cc(305)] ContextResult::kFatalFailure: Failed to create context.
[3126:3157:0130/151618.004316:ERROR:gl_context_glx.cc(182)] Failed to create GL context with glXCreateContextAttribsARB.
```

I don't see any of these messages using `--backend webkit`.

**How to reproduce**

* Install Void Linux (glibc)
* Install `nvidia340` driver
* Open qutebrowser

###### btw, thanks creating such awesome browser, I can't live without it! :)

**Comment by The-Compiler** [comment]
It's weird that Falkon works but qutebrowser does not. How about `python3 scripts/testbrowser/testbrowser_webengine.py qutebrowser.org` inside the qutebrowser repository?

**Comment by dawidpotocki** [comment]
It works correctly: 
![4lkx3za](https://user-images.githubusercontent.com/38681822/51978925-88f4b400-24f0-11e9-9aa9-48eba56d2d2f.png)

**Comment by jgkamat** [comment]
A bit of a shot in the dark, but can you try exporting the
'QUTE_SKIP_WAYLAND_CHECK' and 'QUTE_SKIP_NOUVEAU_CHECK' env variables to '1'
and trying again?

See this snippet for reference:

https://github.com/qutebrowser/qutebrowser/blob/ba940f7f87155b9e669755ff101c4bea9127e594/qutebrowser/misc/backendproblem.py#L194

**Comment by dawidpotocki** [comment]
Okay so... I had to reinstall Void on my computer (because I messed up packages pretty badly today 🤷, I had problems with qutebrowser before that happened) and everything seems to run fine now and I have exactly the same configuration (same software, same configs). I guess I should close the issue?
