### ISSUE TITLE
Black screen on void

### ISSUE THREAD

**Issue by 14u2ponder** [qutebrowser/qutebrowser#4557]
I basically installed it from the repo, I am using ratpoison as my windows manager and I installed xorg minimal.

I would love to try this browser if anybody knows how to get it to work.
By the way I did install Firefox and it works.
In qutebrowser all I get is a black screen.

**Comment by jgkamat** [comment]
> I basically installed it from the repo, I am using ratpoison as my windows manager and I installed xorg minimal.
>
> I would love to try this browser if anybody knows how to get it to work.
> By the way I did install Firefox and it works.
> In qutebrowser all I get is a black screen.

Could you provide the output of :version or qutebrowser --version?

Maybe something broke in void recently: https://github.com/qutebrowser/qutebrowser/issues/4554

**Comment by 14u2ponder** [comment]
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.8
Qt: 5.11.3
PyQt: 5.11.3

sip: 4.19.13
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.26.0
QtNetwork SSL: LibreSSL 2.8.3

Style: QFusionStyle
Platform: Linux-4.19.18_1-x86_64-with-glibc2.3.4, 64bit
Linux distribution: void (void)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/kevin/.cache/qutebrowser
config: /home/kevin/.config/qutebrowser
data: /home/kevin/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00

**Comment by 14u2ponder** [comment]
I am pretty sure that since I didn't install the full xorg or something that I have some dependency issues. Please help.

**Comment by 14u2ponder** [comment]
The only reason I say dependency issue is that I'm on void and I'm using such a minimal install. If you think that it is nouveau I trust you.

**Comment by 14u2ponder** [comment]
I tried falkon. Same issue. Ratpoison says falkon has finished....but a black screen

**Comment by 14u2ponder** [comment]
By the way, I am using amdgpu, not an nvida card if that makes a difference.

**Comment by 14u2ponder** [comment]
figured out my problem was that I had not installed xorg-fonts. as a result i could not get any chormium based browser to work, not only qutebrowser. now everything works fine

**Comment by toofar** [comment]
Did you also get an error message like `[4046:4046:0100/000000.200411:FATAL:FontCache.cpp(420)] Check failed: false.` on the console? There are #4055 and #4110 which were also solved by installing that package but the symptom they describe was a renderer or process crash, not just a black screen. Maybe it has changed slightly with 5.12?
