### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by 14u2ponder** [qutebrowser/qutebrowser#4559]
Is the adblocking builtin or do you have to enable it some kind of way and it appears that I can create a bookmark, but how to I open the bookmarks menu?

**Comment by mschilli87** [comment]
@14u2ponder:

> Is the adblocking builtin or do you have to enable it some kind of way [...]?

From the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc):
> *9. Is there an adblocker?*
> 
> There is a host-based adblocker which takes /etc/hosts-like lists. A "real" adblocker has a big impact on browsing speed and RAM usage, so implementing support for AdBlockPlus-like lists is currently not a priority.

The corresponding settings start with `content.host_blocking`.

From the help (`:help` in qutebrowser):

> **` content.host_blocking.enabled`**
> Enable host blocking.
> Type: Bool
> Default: `true`
> 
> **`content.host_blocking.lists`**
> List of URLs of lists which contain hosts to block.
> 
> The file can be in one of the following formats:
> * An /etc/hosts-like file
> * One host per line
> *A zip-file of any of the above, with either only one file, or a file named hosts (with any extension).
> Type: List of Url
> Default:
> * `https://www.malwaredomainlist.com/hostslist/hosts.txt`
> * `http://someonewhocares.org/hosts/hosts`
> * `http://winhelp2002.mvps.org/hosts.zip`
> * `http://malwaredomains.lehigh.edu/files/justdomains.zip`
> * `https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext`
> 
> **`content.host_blocking.whitelist`**
> List of domains that should always be loaded, despite being ad-blocked. Domains may contain * and ? wildcards and are otherwise required to exactly match the requested domain. Local domains are always exempt from hostblocking.
> Type: List of String
> Default:
> * `piwik.org`

Also, you might want to check out the `:adblock-update` command.

---
@14u2ponder:
> [...], but how to I open the bookmarks menu?

What 'menu' are you referring to?
If you run `:open` (default binding: <kbd>O</kbd>), bookmarks should show in in the completion list (in a separate category labelled *Bookmarks*.
To add/delete booksmarks there are the `:bookmark-add` (default binding: <kbd>Shift</kbd>+<kbd>M</kbd>) and `:bookmark-del` command, respectively. There also is `:bookmark-load`.

**Comment by ninewise** [comment]
`:open qute://bookmarks/` is sort of a menu
