### ISSUE TITLE
Error creating ssl context () when running adblock-update

### ISSUE THREAD

**Issue by RadicalEd360** [qutebrowser/qutebrowser#4560]
**Version info (see `:version`)**:
qutebrowser v1.5.2

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
yes

**Description**
adblock-update fails to download the file saying Error creating ssl context, some ssl images fail to download for same reason but display just fine.

**How to reproduce**
i cannot get it to not produce this error
i run :adblock-update and it fails

**Comment by jgkamat** [comment]
Radical Edward writes:

> adblock-update fails to download the file saying Error creating ssl context, some ssl images fail to download for same reason but display just fine.

Have you tried the OpenSSL workaround listed in the install docs?

https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-dependencies-including-qt

**Comment by 14u2ponder** [comment]
Honestly I wouldn't even worry about ad blocking. The feature isn't really that create and it doesn't really block a whole lot, nor does it remove the ads from the dom so the pages with a lot of ads look kinda broken. I actaully just turned mine off, which isn't ideal but it isn't all that bad.

**Comment by RadicalEd360** [comment]
@jgkamat i did not know about that, however i did try it, i linked the libraries into a folder and exported the variable, however it still gives me the error sadly.

@14u2ponder it has a pop-up telling me to run adblock_update everytime i start the browser and its kind of annoying, i just need 1 successful run to get rid of it, unless anyone knows another way

**Comment by jgkamat** [comment]
Radical Edward writes:

> @jgkamat i did not know about that, however i did try it, i linked the libraries into a folder and exported the variable, however it still gives me the error sadly.

Could you pastebin your :version?

> i just need 1 successful run to get rid of it, unless anyone knows another way

The message is not shown if you disable adblocking completely, or if you
populate the host list yourself.

https://github.com/qutebrowser/qutebrowser/blob/fcd969206692310337c8ec7c1f81c03d75a205b1/qutebrowser/components/adblock.py#L170

**Comment by RadicalEd360** [comment]
Version info: https://pastebin.com/y5N8xmYc

> The message is not shown if you disable adblocking completely, or if you
populate the host list yourself.
that was a good idea, i looked in settings and seen the url the hosts list was being hosted at, i downloaded the hosts list and put it in /var/www/html and set the setting to ["http://localhost/hosts"] and then ran :adblock-update and it worked but on exit it would forget the hosts and ask me to rerun it so i reran it and then i entered the :save command to make the changes stay and it solved that problem.

however is still get the SSL command when trying to use the :download command on imagefiles, but can download them fine using the right click menu. Im currently looking in the settings for a way to set the download command to aria2c

**Comment by jgkamat** [comment]
Radical Edward writes:

> however is still get the SSL command when trying to use the :download command on imagefiles, but can download them fine using the right click menu. Im currently looking in the settings for a way to set the download command to aria2c

> Version info
> qutebrowser v1.5.2
> Git commit:
> Backend: QtWebEngine (Chromium 65.0.3325.230)
>
> CPython: 3.5.3
> Qt: 5.11.2
> PyQt: 5.11.3
>
> Linux distribution: Debian GNU/Linux 9 (stretch) (debian)

How are you running Qt/PyQt5 on Debian Stretch? Stretch ships qt 5.7. From the
other point of view, how are you running python 3.5 on debian testing/sid?
Testing/sid is currently shipping python 3.7.

https://packages.debian.org/stretch/pyqt5-dev
https://packages.debian.org/buster/python3

Did you create a franken-debian?

**Comment by RadicalEd360** [comment]
you could say its a franken debian yeah lol

im runnin AntiX, its a distro built on debian free of systemd, it shares repos with sid/stretch (set on live install) along with mx linux.
 https://antixlinux.com/

its heavily customized with lots of drivers set up and its built in such a way that it will boot on the oldest of systems, even a dell latitude d430, non-pae, 256mb ram. Brings them back to life!
ive been using it on my laptop with herbstluftwm for a while now its really nice. (ive upgraded to a lenovo thinkpad t430 i7-3520M with 8gb ram)

**Comment by jgkamat** [comment]
Radical Edward writes:

> im runnin AntiX, its a distro built on debian free of systemd, it shares repos with sid/stretch (set on live install) along with mx linux.
>  https://antixlinux.com/

On a clean install of AntiX, I don't see any issues with :adblock-update.

On a clean install, I also don't have a mix of testing/stable packages, I just
have testing packages. I think your system is broken, packages from stable are
not built to work alongside packages from testing (which leads to these kinds
of errors).

I don't think we can do anything to fix this though.

**Comment by The-Compiler** [comment]
Closing this now as this clearly is some issue with your system and not qutebrowser - you'll need to make sure that Qt loads the OpenSSL (1.0 or 1.1) it was compiled against.
