### ISSUE TITLE
Cannot select the text 

### ISSUE THREAD

**Issue by kuator** [qutebrowser/qutebrowser#4566]
**Version info (see `:version`)**:
❯ $ qutebrowser --version
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.7
Qt: 5.9.5
PyQt: 5.10.1

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.15.0-45-generic-x86_64-with-LinuxMint-19-tara, 64bit
Linux distribution: Linux Mint 19 (linuxmint)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/evakuator/.cache/qutebrowser
config: /home/evakuator/.config/qutebrowser
data: /home/evakuator/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes
**Description**
When I want to select all text with Ctrl-A, nothings happens
**How to reproduce**

![gif](https://user-images.githubusercontent.com/25168308/52530907-6dcb4500-2d37-11e9-85a8-91536855a3bb.gif)

**Comment by The-Compiler** [comment]
That's odd, no issues here. Can you please try with [KDE Falkon](https://www.falkon.org/) which also should be in the Linux Mint repos (as `falkon`)? Any change when you try in passthrough mode (`ctrl-v`) instead?

**Comment by kuator** [comment]
@The-Compiler, hello, so, I went to my .profile and commented the lines with my xkb config.
And replaced them with setxkbmap commands. Now, it's working. But I'd like to have settings in config
rather than profile.
```
#XKB_DIR="$HOME/.config/xkb"
#XKB_SYMBOL_FILE="my-symbols"
#XKB_KEYCODE_FILE="my-keycodes"


#setxkbmap -layout "us+$XKB_SYMBOL_FILE(xcape-special)" \
#    -keycodes "evdev+$XKB_KEYCODE_FILE(xcape-special)" \
#    -option "" -print \
#    | xkbcomp -I"$XKB_DIR" - "${DISPLAY%%.*}" >/dev/null 2>&1


setxkbmap -option caps:swapescape
setxkbmap -option ctrl:ralt_rctrl
setxkbmap -option grp:ctrl_alt_toggle
setxkbmap -layout us,ru
xset r rate 220 40

```

**Comment by The-Compiler** [comment]
That still seems like an issue with Qt, not qutebrowser. Can you please try with Falkon? Also, can you try in a normal Qt text field, like the one shown when you do `:report`?

**Comment by kuator** [comment]
No, it's not working with report field either

**Comment by The-Compiler** [comment]
That's some kind of Qt bug then.
