### ISSUE TITLE
Sites that capture mouse cursor don't give it back once they're closed, nor when the tab is changed.

### ISSUE THREAD

**Issue by nonamethanks** [qutebrowser/qutebrowser#4571]
**Version info (see `:version`)**:
v1.5.2

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes

**Description**/**How to reproduce**
https://keithclark.co.uk/labs/css-fps/
Open this link, do "y" once it asks you to capture the mouse. 
Try opening a new tab and moving the mouse around, or shifting to an old one if you had it open.

In my machine the cursor disappears until I completely close all qutebrowser windows.

Also, unlike in firefox and chromium, the Esc key does not give you back the cursor, not even with passthrough mode.

**Comment by toofar** [comment]
I'm guessing you are on Qt5.12 (please post more version info than just the qutebrowser version) because it doesn't prompt me for mouse capture on any the the demos there.

**Comment by jgkamat** [comment]
I can reproduce on qt5.12 but not on 5.11 (in qutebrowser and falkon), seems like a qt bug.

**Comment by The-Compiler** [comment]
Possibly related: https://codereview.qt-project.org/c/qt/qtwebengine/+/298465

**Comment by The-Compiler** [comment]
Looks like this works fine with Qt 5.15, and support for older versions is now dropped.
