### ISSUE TITLE
Missing pyqtwebengine dependency in qutebrowser-git PKGBUILD

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#4574]
**Version info (see `:version`)**:

```
qutebrowser v1.5.2
Git commit: fcd969206 (2019-01-27 12:46:43 -0800)
Backend: QtWebEngine (Chromium unavailable)

CPython: 3.7.2
Qt: 5.12.1
PyQt: 5.12
```

**Does the bug happen if you start with `--temp-basedir`?** (if applicable): Yes.

**Description**

Qutebrowser fails to start with the QtWebEngine backend "because QtWebEngine could not be imported". See [this image](https://i.imgur.com/gZ5gJCy.png).

**How to reproduce**

This happened after I upgraded the following packages (Arch Linux):

```
[2019-02-13 08:01] [ALPM] upgraded pyqt5-common (5.11.3-4 -> 5.12-2)
[2019-02-13 08:01] [ALPM] upgraded python-sip-pyqt5 (4.19.13-1 -> 4.19.14-1)
[2019-02-13 08:01] [ALPM] upgraded python-pyqt5 (5.11.3-4 -> 5.12-2)
[2019-02-13 08:01] [ALPM] upgraded python2-sip-pyqt5 (4.19.13-1 -> 4.19.14-1)
[2019-02-13 08:01] [ALPM] upgraded python2-pyqt5 (5.11.3-4 -> 5.12-2)
```

Downgrading `python-pyqt5` fixes the issue, i.e. Qutebrowser starts normally.

**Comment by The-Compiler** [comment]
How did you install qutebrowser?

**Comment by brianbuccola** [comment]
From the AUR (https://aur.archlinux.org/packages/qutebrowser-git/), normally using [aurutils](https://aur.archlinux.org/packages/aurutils/) with the `--chroot` option. But I also just rebuilt the package using plain `makepkg -csif`, and I'm still getting the same error.

**Comment by The-Compiler** [comment]
You'll also need to install `python-pyqtwebengine` (it was split off from `python-pyqt5` with the 5.12 release). I'll update the PKGBUILD today.

**Comment by brianbuccola** [comment]
Ah OK, thanks. That explains why, as I just discovered, the (already-built) official package `qutebrowser` works fine, just not the git one.

**Comment by The-Compiler** [comment]
Took me a bit longer since I had to get https://github.com/qutebrowser/qt-debug-pkgbuild to build before I could test the updated PKGBUILD, but it's up now!
