### ISSUE TITLE
Updating user_agent in configdata.yml

### ISSUE THREAD

**Issue by hseg** [qutebrowser/qutebrowser#4575]
Judging by `git blame` output, it seems the `user_agent` entry hasn't been updated in a while.
Nor does `ua_fetch.py` seem to be called at any point of the build process, and it doesn't seem to appear as a step in the installation instructions.

This is problematic for me, since I A) prefer to hew as close to upstream packaging as possible to avoid headaches and B) the outdated user agents cause websites to display "no support" warnings.

Any of the above-mentioned methods would suffice, though I'm partial to inserting this step in `setup.py`,
since `make install` shouldn't be making such changes, and expecting packagers to do so is a bit sloppy.
Of course, a different solution would be to make this act like `:adblock-update`, with some cache file containing this, but that feels like a little too much engineering.

**Comment by jgkamat** [comment]
hseg writes:

> Judging by `git blame` output, it seems the `user_agent` entry hasn't been updated in a while.
> Nor does `ua_fetch.py` seem to be called at any point of the build process, and it doesn't seem to appear as a step in the installation instructions.

Currently, we run the update script manually whenever we feel it's out of date
to update the completion. It is a little old, so maybe we should update it.

> Any of the above-mentioned methods would suffice, though I'm partial to inserting this step in `setup.py`,
> since `make install` shouldn't be making such changes, and expecting packagers to do so is a bit sloppy.
> Of course, a different solution would be to make this act like `:adblock-update`, with some cache file containing this, but that feels like a little too much engineering.

I don't think this is a good idea, as it would mean installing qutebrowser on
different days can give a different final binary.

**Comment by The-Compiler** [comment]
I wonder if those completions are a good idea to begin with - they caused various people to pick a Firefox UA, which usually causes more trouble than it's worth. Maybe we should only offer a completion for some recent Chrome release anyways?

**Comment by hseg** [comment]
Don't know about that, but I've been using one of the
autocompletions to get around WhatsApp's UA sniffing.
That+a userscript to try to remove the sniffing code.
Neither works on its own, though. Weird.

On 14 February 2019 13:12:55 GMT+02:00, Florian Bruhin <notifications@github.com> wrote:
>I wonder if those completions are a good idea to begin with - they
>caused various people to pick a Firefox UA, which usually causes more
>trouble than it's worth. Maybe we should only offer a completion for
>some recent Chrome release anyways?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qutebrowser/qutebrowser/issues/4575#issuecomment-463589170

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hseg** [comment]
Fair point. Reproducible builds are important. How about making it a step in release engineering?

On 14 February 2019 4:22:34 GMT+02:00, Jay Kamat <notifications@github.com> wrote:
>
>hseg writes:
>
>> Judging by `git blame` output, it seems the `user_agent` entry hasn't
>been updated in a while.
>> Nor does `ua_fetch.py` seem to be called at any point of the build
>process, and it doesn't seem to appear as a step in the installation
>instructions.
>
>Currently, we run the update script manually whenever we feel it's out
>of date
>to update the completion. It is a little old, so maybe we should update
>it.
>
>> Any of the above-mentioned methods would suffice, though I'm partial
>to inserting this step in `setup.py`,
>> since `make install` shouldn't be making such changes, and expecting
>packagers to do so is a bit sloppy.
>> Of course, a different solution would be to make this act like
>`:adblock-update`, with some cache file containing this, but that feels
>like a little too much engineering.
>
>I don't think this is a good idea, as it would mean installing
>qutebrowser on
>different days can give a different final binary.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qutebrowser/qutebrowser/issues/4575#issuecomment-463459719

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
