### ISSUE TITLE
PAC support: Both 'url' and 'host' params that are passed into 'FindProxyToURL' function are empty.

### ISSUE THREAD

**Issue by h-ayat** [qutebrowser/qutebrowser#4577]
Reproducing is easy, create an empty PAC file, like this :
```
function FindProxyForURL(url, host){
    url();  // or host(). note that this line creates an error, which prints contents of URL or host
    return 'DIRECT';
}
```
and put the file somewhere like
```
/path/to/config.pac
```
And finally fireup qutebrowser (make sure that you see logs) and activate PAC file like this :
```
:set content.proxy pac+file:///path/to/config.pac
```
Then load anything and watch the logs.

Version Info:
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.1
PyQt: 5.12

sip: 4.19.14
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.27.1
QtNetwork SSL: OpenSSL 1.1.1a  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.20.7-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)

**Comment by The-Compiler** [comment]
I've never really investigated PAC support for QtWebEngine (#2492) so I'm not sure if this ever worked. From a quick look, QtWebEngine calls our `QNetworkProxyFactory::queryProxy` with `query.url()` always being an empty URL - so this might be a QtWebEngine bug as well.

**Comment by The-Compiler** [comment]
Merging this into #2492.
