### ISSUE TITLE
Qt 5.12: Existing download filenames are uniquified wrongly

### ISSUE THREAD

**Issue by us91** [qutebrowser/qutebrowser#4580]
**Version info (see `:version`)**:
qutebrowser v1.5.2

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
I think this is independent of basedir

**Description**
Downloaded file is using the name from the link the first time it is downloaded. The second time, it is using the name with a space appended after the basename part. The third time it asks for permission to overwrite the second version (the filename with a space at the end). I cannot see what is the logic of this. It seems to be a bug for me.

**How to reproduce**
Download the same file three times, and answer Y when asked to overwrite.

**Comment by jgkamat** [comment]
us91 writes:

> Downloaded file is using the name from the link the first time it is downloaded. The second time, it is using the name with a space appended after the basename part. The third time it asks for permission to overwrite the second version (the filename with a space at the end). I cannot see what is the logic of this. It seems to be a bug for me.

I cannot reproduce. Also, can you provide the full version information.

**Comment by user202729** [comment]
It may be the server that sends the "space-appended" name on second or later download attempts.

**Comment by The-Compiler** [comment]
I can reproduce this with Qt 5.12. Smells like a bug there... :worried: 

https://codereview.qt-project.org/#/c/247517/ sounds suspicious.

**Comment by The-Compiler** [comment]
Actually, we might be to blame:

https://github.com/qutebrowser/qutebrowser/blob/2214fd63b5ebdaa6a0e3a8d32817f8859d72c12e/qutebrowser/browser/webengine/webenginedownloads.py#L172-L183

**Comment by user202729** [comment]
@The-Compiler That might be the case, if Qt 5.12 changes the format from `foo(1)` to `foo (1)`.

**Comment by The-Compiler** [comment]
Yup, that was it!
