### ISSUE TITLE
Blank browsing history page

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4584]
**Version info:**

qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.1
PyQt: 5.12

sip: 4.19.14
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.0.943 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.27.1
QtNetwork SSL: OpenSSL 1.1.1a  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.20.8-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**

Yes

**Description**

Exactly same problem as was the case in #4257.

qutebrowser was updated 1.5.2-3 -> 1.5.2-4 in Arch Linux on Feb 12 and it might be when this broke (?). It might have also been with the change 1.5.2-1 -> 1.5.2-3 on Feb 11 (?). Or maybe more likely with the update of Qt5 5.12.1-1 -> 5.12.1-2 on Feb 10 (?).

@The-Compiler you told me to try the master branch to see if this got fixed. Silly noob question: what is an easy way to do this? qutebrowser-git in the AUR does not seem to be up to date, so I am not sure how to install qutebrowser from a git repo in Arch.

Thanks!

**Comment by toofar** [comment]
If you already have a recent one installed (for the systemwide dependancies) then 

    git clone https://github.com/qutebrowser/qutebrowser.git
    cd qutebrowser
    python3 -m qutebrowser -T

should work. If it complains about dependancies do `tox -e mkvenv` then run it from in the venv.

**Comment by The-Compiler** [comment]
I just updated qutebrowser-git yesterday :wink: However, for -git (or other version control system) packages in the AUR, they just display the version when the package was updated - but it doesn't matter, as building the package will always build the last commit (and update the version number locally while building).

**Comment by prosoitos** [comment]
Oh, I see. I did not know this and only looked at the "Last Updated" date. Good to know!

Will install and report.

**Comment by prosoitos** [comment]
Yup :slightly_smiling_face: The last version fixes the browsing history page. So I will close this.

Thank you! :slightly_smiling_face:

**Comment by prosoitos** [comment]
I am having this issue again.

**Comment by prosoitos** [comment]
Arg. Sorry for the noise. v1.6.3 fixed it.
