### ISSUE TITLE
Cannot access site https://mail.sfu.ca after login

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4586]
**Version info**

qutebrowser v1.5.2
Git commit: b3e1bac11 (2019-02-16 23:19:28 +0100)
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.1
PyQt: 5.12

**Does the bug happen if you start with `--temp-basedir`?**

Yes

**Description**

I can't access my emails through my University outlook website at https://mail.sfu.ca. I can access the login page, but after I enter my credentials, I get a `HTTP ERROR 440` page. I mentioned this at the end of #4208 as I then thought that there might be a link, but there isn't.

This has been going on since I started using qutebrowser. It is extremely low priority for me as I barely ever go to that site (I use mu4e) and when I really need to, I can use another browser. But I thought that I would open an issue about it because something is going on and it may affect others.

I realize that it is hard for anyone to try to reproduce...

FWIW, I have no issue accessing my emails on that site with Falkon.

**Comment by The-Compiler** [comment]
So this is (sometimes) broken for a couple of hours or so, right? And in such a moment, you can't access it with `--temp-basedir`, but Falkon does work?

Fun... I don't think there's anything I could do without getting an account to test with or something, which I suppose isn't going to happen. FWIW I've never had any issues with my university's Outlook Web, nor do I remember hearing from anyone else with the same issue.

Note to self: https://github.com/qutebrowser/qutebrowser/issues/4208#issuecomment-433289419 is the start of the previous discussion.

**Comment by prosoitos** [comment]
> So this is (sometimes) broken for a couple of hours or so, right?

No, I can **never** accessed it. I never have.

As I said, it is totally low priority for me and I am mentioning it for you. It does not bother me at all. But since I just installed Falkon, I tried it out of curiosity and since it works without any problem on it, I thought that I would mention it because something seems to be going on.

**Comment by The-Compiler** [comment]
@prosoitos Do you still see this with up-to-date Qt/qutebrowser versions?

**Comment by prosoitos** [comment]
Ah! I am not a student anymore and I lost access to my university email address (and that's the only site where I had this problem). So unfortunately I cannot test it. Sorry!

**Comment by The-Compiler** [comment]
Congratulations (I assume!) :tada: Closing this then as nobody was ever able to reproduce it - still no idea what's going on there, I'm afraid.

**Comment by prosoitos** [comment]
Yes, no point keeping an issue open for something that isn't affecting anyone :smile:
