### ISSUE TITLE
"Printing failed" and produces blank pdf file when printing to a file

### ISSUE THREAD

**Issue by sanjayankur31** [qutebrowser/qutebrowser#4599]
**Version info (see `:version`)**:
Version info
qutebrowser v1.5.1
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.2
Qt: 5.11.3
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.4.0
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 4.2
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.26.0
QtNetwork SSL: OpenSSL 1.1.1a FIPS  20 Nov 2018

Style: Adwaita::Style
Platform: Linux-4.20.7-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine, 64bit
Linux distribution: Fedora 29 (Workstation Edition) (fedora)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/asinha/.cache/qutebrowser
config: /home/asinha/.config/qutebrowser
data: /home/asinha/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes, seems to.

**Description**
When using the `:print` command to print a web page to a file, printing fails. I get a red bar with "printing failed", and when run from a terminal, it says: `19:15:05 ERROR: Printing failed!`

The print dialog box does come up, and it does produce an empty pdf file.

**How to reproduce**

At the moment, open any page and try to print it to a file.

I thought it could be Qt issue, but I tried printing in Falkon and it works there, so I'm not sure.

**Comment by jgkamat** [comment]
I can reproduce on qt5.11 (gentoo, debian, fedora) but not on qt 5.12. Maybe
this is a bug in older versions of PyQt.

I also get this error:

Failure to generate QImage from invalid or empty PDF document.

Which seems to come from a check in this file:

http://code.qt.io/cgit/qt/qtwebengine.git/plain/src/core/printing/pdfium_document_wrapper_qt.cpp


Also, for the record, --pdf works fine.

**Comment by sanjayankur31** [comment]
> I can reproduce on qt5.11 (gentoo, debian, fedora) but not on qt 5.12. Maybe this is a bug in older versions of PyQt. 

But wouldn't Falkon also give the error if it was a Qt issue?

>I also get this error: Failure to generate QImage from invalid or empty PDF document. Which seems to come from a check in this file: http://code.qt.io/cgit/qt/qtwebengine.git/plain/src/core/printing/pdfium_document_wrapper_qt.cpp Also, for the record, --pdf works fine.

Ah, great! I'll use that for the time being :clap:

**Comment by jgkamat** [comment]
Ankur Sinha writes:

>> I can reproduce on qt5.11 (gentoo, debian, fedora) but not on qt 5.12. Maybe this is a bug in older versions of PyQt.
>
> But wouldn't Falkon also give the error if it was a Qt issue?

Falkon isn't written in Python, and dosen't use PyQt5. The docs for the
printing api have some caveats with object lifecycle, which is why I thought
it was a possibility.

**Comment by The-Compiler** [comment]
Closing this given it's some kind of (Py?)Qt bug most likely and Qt 5.11 support is being dropped (#3839).
