### ISSUE TITLE
PyQt 5.12 on Tumbleweed

### ISSUE THREAD

**Issue by yellowhat** [qutebrowser/qutebrowser#4601]
Hi,
I am using this git version https://build.opensuse.org/package/show/home:yellowhat46/qutebrowser of qutebrowser on OpenSUSE Tumbleweed.
With the recent update of Qt to 5.12 and python 3.7 qutebrowser is not working anymore.
If I try to run it I get this error:
```
cannot import name "QtWebEngineWidgets" from "PyQt5" (/usr/lib64/python3.7/site-packages/PyQt5/init.py)
```

Is this releated to [4591](https://github.com/qutebrowser/qutebrowser/issues/4591) issue?
Also I saw on https://travis-ci.org/qutebrowser/qutebrowser that there is not test for the combination PyQt 5.12 and python 3.7.

Thanks

**Comment by The-Compiler** [comment]
The QtWebEngine part of PyQt5 got split into its own package upstream, I guess OpenSUSE did the same and you'll need to install some PyQtWebEngine package.

It's intentional that not every combination is tested on Travis, that'd take too long without any real benefit.

**Comment by yellowhat** [comment]
I have installed the package: libqt5-qtwebengine, but I cannot find any PyQtWebEngine package.

Thanks

**Comment by The-Compiler** [comment]
That sounds like an OpenSUSE-bug then. I just looked at their `python3-qt5-5.12-1.1.x86_64.rpm` package and it doesn't contain `/usr/lib64/python3.7/site-packages/PyQt5/QtWebEngine.so`, and there indeed isn't any `python3-qt5-webengine` package or anything.

**Comment by yellowhat** [comment]
ok I will fill a bug. Thanks

**Comment by yellowhat** [comment]
Just for reference this is the OpenSUSE bug raised:

https://bugzilla.suse.com/show_bug.cgi?id=1126269

Thanks

**Comment by jgkamat** [comment]
yellowhat writes:

> Hi,
> I am using this git version https://build.opensuse.org/package/show/home:yellowhat46/qutebrowser of qutebrowser on OpenSUSE Tumbleweed.
> with the recent update of Qt to 5.12 and python 3.7 qutebrowser is not working anymore.
> If I try to run it I get this error:
> ```
> cannot import name "QtWebEngineWidgets" from "PyQt5" (/usr/lib64/python3.7/site-packages/PyQt5/init.py)
> ```

You should report this to the owner of that package, that error occurs when
your PyQt5 dosen't have webengine compiled in/available.

There are some issues with qt5.12 but this isn't one of them.
