### ISSUE TITLE
Fix parsing of hue percentages in QtColor

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4605]
In 66cc5f5ea493b4e1cab4053647db74e88924cd46, a broken parsing of e.g. `hsv(100%, 100%, 100%)` was introduced for bug-compatibility with Qt.

That was fixed in Qt 5.13, so we should probably fix it now as well:
https://bugreports.qt.io/browse/QTBUG-70897
https://codereview.qt-project.org/#/c/241815/

cc @rcorre

**Comment by rcorre** [comment]
Should the fix be conditional on `qVersion()`, or are you thinking we should just fix it unconditionally?

**Comment by toofar** [comment]
It doesn't look like the fix upstream is is being backported to 5.11 or 5.12 so I'm pretty sure it needs to be conditional.

**Comment by The-Compiler** [comment]
I'd just do it unconditionally - yeah, that makes it inconsistent with what Qt does with earlier Qt versions, but it's easier and makes qutebrowser's behavior consistent between different Qt versions.
