### ISSUE TITLE
search site with duckduckgo

### ISSUE THREAD

**Issue by bluepurplegreen** [qutebrowser/qutebrowser#4609]

**Comment by bluepurplegreen** [comment]
It would be nice to be able to search the current site with a search engine.

Something like the following would be good.
c.url.searchengines = {'d': 'https://duckduckgo.com/?q=site%3A{domain}+{}&ia=web'}

**Comment by jgkamat** [comment]
From IRC:

> <jgkamat> Guest81008: you can bind something to set-cmd-text -s :open site:{url:host}

The expansion does not happen for searchengines, though.

**Comment by bluepurplegreen** [comment]
Thanks!
