### ISSUE TITLE
Failed parsing of X-XSS-Protection headers causing ServiceWorker fail to load resources

### ISSUE THREAD

**Issue by Merri** [qutebrowser/qutebrowser#4610]
**Version info (see `:version`)**:
```
qutebrowser v1.5.2
Git commit: a42f37a0c (2018-10-26 10:20:24 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)
```

**Description**

Loading Verkkokauppa.com fails after first visit to the site when it's service worker kicks in. This behavior does not occur with other Chromium-based browsers.

Unfortunately we don't have the human resources to look into this more than to file this bug. However if you find the bug to be in our end we'll be glad to fix it :)

**How to reproduce**

1. Visit https://www.verkkokauppa.com
2. Close the tab or qutebrowser
3. Visit the site again
4. In console you have error:  `Error parsing header X-XSS-Protection: 1; report=https://verkkokauppa.report-uri.com/r/t/xss/enforce: insecure reporting URL for secure page at character position 10. The default protections will be applied.` and multiple lines of `Failed to load resource: net::ERR_FAILED`.
5. The site is unable to load it's CSS and JavaScript and you get a style-free white screen with massive SVG icons.

**Comment by The-Compiler** [comment]
Works fine here, with qutebrowser v1.6.0 - seems like 5fdcaefbbe8100806d780d32d872a8a244009b03 fixed this.
