### ISSUE TITLE
allow fake-key to send keys to another tabs 

### ISSUE THREAD

**Issue by Yrds** [qutebrowser/qutebrowser#4617]
I don't know how difficulty is this but this is a useful feature. Could be using count to define the tab-index or using optional parameters

Example:

Tabs:
1: Youtube
2: Github

To pause a video playing on tab 1

`1 :fake-key <Space>` using count
or
`:fake-key -t 1 <Space>` optional parameters

**Comment by jgkamat** [comment]
Yuri Santos writes:

> I don't know how difficulty is this but this is a useful feature. Could be using count to define the tab-index or using optional parameters

I think this should be possible, but I haven't tried it to be sure (we grab
the current tab in the fake_key function unless we are using global).

Note, you can sort-of get this by doing

:tab-focus <num> ;; fake-key <space> ;; tab-focus last

> To pause a video playing on tab 1
>
> `1 :fake-key <Space>` using count
> or
> `:fake-key -t 1 <Space>` optional parameters

I don't like this interface though. Ideally, we would have a way to select
tabs from any window, not just the current one (and ideally, we could do this
across any command that operates on a tab object, such as userscripts). Maybe
there's something we can add to cmdutils to add some sort of 'context'
argument, and make some sort of wrapper (like with-current-buffer in emacs).

So, maybe:

:with-tab 0/1 fake-key <space>
:with-tab 1 fake-key <space>
<count, 1> :with-tab fake-key <space>

I don't think that's too great though, either. Getting the interface right is
probably the hardest part of this issue.

**Comment by jgkamat** [comment]
Also, this is related to and/or a possible duplicate of

https://github.com/qutebrowser/qutebrowser/issues/267

**Comment by Yrds** [comment]
@jgkamat 

Thanks for the response.

:tabdo or :with-tab seems way more complete than my request. 

> :tab-focus <num> ;; fake-key <space> ;; tab-focus last

will use this for now

since this is a duplicate, i will close that issue and follow #267
