### ISSUE TITLE
more information on the "override existing quickmarks" dialog

### ISSUE THREAD

**Issue by bluepurplegreen** [qutebrowser/qutebrowser#4618]
When the "override existing quickmark?" dialog box comes up how about it telling you what the quickmark is that would be overridden?

**Comment by jgkamat** [comment]
bluepurplegreen writes:

> When the "override existing quickmark?" dialog box comes up how about it telling you what the quickmark is that would be overridden?

Here's the source for it

https://github.com/qutebrowser/qutebrowser/blob/9cccb612fcb0b2d7375ef6b7a30cfac48d8a4d25/qutebrowser/browser/urlmarks.py#L184-L187

Seems pretty easy to add, although it will probably need texts fixed as well
