### ISSUE TITLE
Feature request: Actually close all tabs in a direction

### ISSUE THREAD

**Issue by Irubataru** [qutebrowser/qutebrowser#4621]
I originally came to suggest closing tabs in a direction, but then found #46. But reading the issue discussion is seems as if it wasn't actually that. There might be a different issue on this, and if I didn't find it I am sorry.

Anyway, could I request what #46 originally requested? I find the ability to close all tabs in a direction (usually right) very useful because I have a tendency of putting all my temporary tabs to the right, and when I am done with whatever search I am doing, calling one function for cleanup is easier than closing them one by one.

I am sure there is an easy way of implementing this with a script or something, but maybe it would be a useful function to have.

**Comment by jgkamat** [comment]
Jonas Rylund Glesaaen writes:

> I find the ability to close all tabs in a direction (usually right) very useful because I have a tendency of putting all my temporary tabs to the right, and when I am done with whatever search I am doing, calling one function for cleanup is easier than closing them one by one.

I think this could be covered by a flag/options to the command in #267, or by
a plugin if/when there's an api to get tabs.

I agree that this is very useful though :]

**Comment by arza-zara** [comment]
There is already `:tab-only --prev/--next`.

**Comment by Irubataru** [comment]
Ah, yes that seems to do what I want, thanks. Sorry for not seeing that, it was a bit unintuitive. I'll close this.
