### ISSUE TITLE
Desktop file introduced in v1.6.0 is invalid

### ISSUE THREAD

**Issue by Fnux** [qutebrowser/qutebrowser#4623]
**Version info (see `:version`)**: 1.6.0

**Description**: the provided (see 0e547414af8771d939aaf5d41ac1cdd25648c258) desktop file does not respect the [Desktop Entry Specification](https://freedesktop.org/wiki/Specifications/desktop-entry-spec/).

**How to reproduce**:

```
qutebrowser/qutebrowser-1.6.0 » desktop-file-validate misc/qutebrowser.desktop 
misc/qutebrowser.desktop: error: action group "Desktop Action new-window" exists, but there is no matching action "new-window"
misc/qutebrowser.desktop: error: action group "Desktop Action preferences" exists, but there is no matching action "preferences"
```

*Note:* `desktop-file-validate` is provided by the *desktop-file-utils* package (on Fedora).
*Note:* related to [RHBZ#1683073](https://bugzilla.redhat.com/show_bug.cgi?id=1683073), as I catched the error when upgrading the fedora package.

**Comment by Fnux** [comment]
@tallero ^

**Comment by tallero** [comment]
Sorry, yesterday I forgot to commit the fix. It seems to me that @jkamat's commit solve this issue, am I right?

**Comment by Fnux** [comment]
Yes, thank you.
