### ISSUE TITLE
Scrolling lags when pomodoro timers tick

### ISSUE THREAD

**Issue by byllgrim** [qutebrowser/qutebrowser#4625]
**Version info (see `:version`)**: qutebrowser v1.6.0

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):

**Description**
Running a pomodoro timer in one window makes scrolling in other windows super painfull and laggy.
It is possibly because qutebrowser runs under a single process.
More specifically, only when the scrolled window is the only one visible on screen (as in sway/i3 tags)

**How to reproduce**

Either of these sites:
https://justpomodoro.org/
https://tomato-timer.com/

Press play on the timer.

Open another window of qutebrowser in another tag (on sway wm as far as I've tested). Scrolling will be super laggy in this other window.
If both windows are visible (e.g. moved to the same tag), or if the window with the timer changes navigates to another site, the laging disappears.

**Comment by The-Compiler** [comment]
> It is possibly because qutebrowser runs under a single process.

It doesn't by default.

I can't reproduce the issue. Can you please show your full version info, and try reproducing with `--temp-basedir`? Can you check whether you see the same issue with e.g. KDE Falkon?

**Comment by The-Compiler** [comment]
Ah, I can actually reproduce this with `--temp-basedir` in sway - but I see it in Falkon as well. So this is some issue in either QtWebEngine or sway.
