### ISSUE TITLE
Cookies/Cache Not Saved

### ISSUE THREAD

**Issue by brandonllocke** [qutebrowser/qutebrowser#4631]
version: 1.1.1

Description:
I am on Ubuntu 18.04 and installed the version from the repos. I then installed the version using tox, but could not continue to use that version due to the lack of x264 playback (I work for an online streaming company that requires I be able to run video). I went back to the repo version, but now I am running into an issue where cookies and cache aren't being saved. For instance, changing the color interface on DuckDuckGo resets every time the browser is restarted. Another example is that my Google account never knows that it's been previously logged in and requires both the email and password on each new session.

I am sure there is more information that I need to provide and I'd be happy to provide it if at all possible, but perhaps it's just a stupid issue that someone knows how to fix. Thank you!

Things Attempted:
Cleared all folders of data: .cache/qutebrowser, .config/qutebrowser, .local/share/qutebrowser, /usr/share/qutebrowser, /run/user/1001/qutebrowser

**Comment by jgkamat** [comment]
Brandon L. Locke writes:

> I am on Ubuntu 18.04 and installed the version from the repos. I then installed the version using tox, but could not continue to use that version due to the lack of x264 playback (I work for an online streaming company that requires I be able to run video). I went back to the repo version, but now I am running into an issue where cookies and cache aren't being saved. For instance, changing the color interface on DuckDuckGo resets every time the browser is restarted. Another example is that my Google account never knows that it's been previously logged in and requires both the email and password on each new session.
>
> I am sure there is more information that I need to provide and I'd be happy to provide it if at all possible, but perhaps it's just a stupid issue that someone knows how to fix. Thank you!

Can you provide the output of :version and also if the problem occurs under
--temp-basedir with :restart (you will need to wait 30 seconds or more to save
cookies due to https://bugreports.qt.io/browse/QTBUG-58675 ).

Also see https://github.com/qutebrowser/qutebrowser/issues/2263

**Comment by brandonllocke** [comment]
Version info

qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.7
Qt: 5.9.5
PyQt: 5.10.1

sip: 4.19.7
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.0-1034-oem-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: Ubuntu 18.04.2 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/blocke/.cache/qutebrowser
config: /home/blocke/.config/qutebrowser
data: /home/blocke/.local/share/qutebrowser
runtime: /run/user/1001/qutebrowser

Uptime: 0:00:25

**Comment by brandonllocke** [comment]
And... as is normally the case with these things.... a restart after deleting these folders seems to have fixed it. It is now back to working normally. I still have no idea why it was doing that, but I appreciate the help!
