### ISSUE TITLE
Hints type number: filter target should include the link's title attribute 

### ISSUE THREAD

**Issue by mariusor** [qutebrowser/qutebrowser#4634]
When using `hints.mode: number` it would ne helpful if in the cases where a link's content is not textual (in case of an image) we could still filter it by the `title` attribute, or by the child image's `alt` attribute.

I've been looking at the documentation but I couldn't find something about this.

**Comment by jgkamat** [comment]
Marius Orcsik writes:

> When using `hints.mode: number` it would ne helpful if in the cases where a link's content is not textual (in case of an image) we could still filter it by the `title` attribute, or by the child image's `alt` attribute.
>
> I've been looking at the documentation but I couldn't find something about this.

from the hints.mode documentation:

> number: Use numeric hints. (In this mode you can also type letters from the hinted element to filter and reduce the number of elements that are hinted.)

I'm not sure what it filters by at the moment, but at least on this issue
page, it seems to filter links based on their name to me.

**Comment by toofar** [comment]
Filtering hints by text is done [here](https://github.com/qutebrowser/qutebrowser/blob/f5c6ac37692a9da6682027ecac3215f36fce7fac/qutebrowser/browser/hints.py#L846). That code is apparently only reached in number hint mode even though it isn't at all clear from the code in that method (the check for mode seems to be a left over of a previous implementation) or the calling code. It just uses `str(elem)` with returns the [text content](https://github.com/qutebrowser/qutebrowser/blob/3e816f5f8b5cca756e6def06e941b81ce45ddea4/qutebrowser/browser/webengine/webengineelem.py#L84). That filter_hints method would need to be changed to do further filtering based on element attributes.

Although how would you know the value of the images title or alt attributes anyway?
