### ISSUE TITLE
Fatal error: PyQt5.Qml

### ISSUE THREAD

**Issue by aidam38** [qutebrowser/qutebrowser#4636]
I'm encountering this weird error. I'm on Void Linux glibc 64-bit and I get this error with all past 4 or 5 releases of qutebrowser and all other Qt5 applications works. I've tried reinstalling `python3-PyQt5-quick` and `python3-PyQt5-networkauth` packages. When I completely remove the `quick` package, I get a different error (that it couldn't be found).

```
Fatal error: PyQt5.QtQml is required to run qutebrowser but could not be imported! Maybe it's not installed?

The error encountered was:
/usr/lib/python3.6/site-packages/PyQt5/QtNetwork.so: symbol _ZN17QPasswordDigestor15deriveKeyPbkdf2EN18QCryptographicHash9AlgorithmERK10QByteArrayS4_iy version Qt_5 not defined in file libQt5Network.so.5 with link time reference

Please search for the python3 version of PyQt5.QtQml in your distributions packages, or see https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc

If you installed a qutebrowser package for your distribution, please report this as a bug.
```

**Comment by toofar** [comment]
It looks like `QPasswordDigestor` is new in 5.12, is you QtNetwork older than QtQml?

**Comment by aidam38** [comment]
I forgot to mention, the current version of Qt5 on Void Linux is 5.11.

@toofar There is no package called QPasswordDigestor and I can't find an equivalent. There is not even a QtQml package (it is included in th `python3-PyQt5-quick` package). Should I maybe install something using pip3?

**Comment by toofar** [comment]
I think it is in the QNetwork library ([note](https://doc-snapshots.qt.io/qt5-5.12/qpassworddigestor.html) the "QT += network" hint).

**Comment by aidam38** [comment]
```
[*] qt5-networkauth-5.11.3_5                    Cross-platform application and UI framework (QT5) - NetworkAuth component
```
I've search for `network` and `QT`, but I've only found this application, which does not solve my issue.

**Comment by The-Compiler** [comment]
That sounds like a Void Linux packaging bug. I assume you get the same issue with `python3 -c "from PyQt5 import QtNetwork"`, or the same with QtQml instead of QtNetwork?

**Comment by aidam38** [comment]
Yes.
```
$ python3 -c "from PyQt5 import QtCore,QtQml"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/python3.6/site-packages/PyQt5/QtNetwork.so: symbol _ZN17QPasswordDigestor15deriveKeyPbkdf2EN18QCryptographicHash9AlgorithmERK10QByteArrayS4_iy version Qt_5 not defined in file libQt5Network.so.5 with link time reference
```

**Comment by toofar** [comment]
Well this isn't a qutebrowser issue and we are no void experts. You should probably head over here and ask: https://github.com/void-linux/void-packages/issues
If you look here though https://doc-snapshots.qt.io/qt5-5.12/qpassworddigestor.html it says it was introduced in 5.12 so it looks very much like your PyQtQml has been built differently.

**Comment by The-Compiler** [comment]
Might also want to try `python3 -c 'from PyQt5 import QtCore; print(QtCore.__file__)'` to make sure it's actually Void's PyQt being at fault, and not some different installation being picked up or something.

**Comment by aidam38** [comment]
When I run your command, I get:
```
/usr/lib/python3.6/site-packages/PyQt5/QtCore.so
```
