### ISSUE TITLE
Not playing videos in Udemy.com

### ISSUE THREAD

**Issue by NatHarari** [qutebrowser/qutebrowser#4642]
**Version info (see `:version`)**:
1.5.1
**Does the bug happen if you start with `--temp-basedir`?**:
Yes.
**Description**
I love Qutebrowser and want to use it for learning python videos at Udemy.com. Unfortunately, it isn't playing them at all. If it did, it would be my main browser. :D 
**How to reproduce**
https://www.udemy.com

**Comment by The-Compiler** [comment]
What OS/distribution are you on, and how did you install qutebrowser?

**Comment by NatHarari** [comment]
I'm on Mac OS X 10.14.3, and I installed it with a prebuilt binary from the release page.

**Comment by jgkamat** [comment]
Nathaniel Harari writes:

> I'm on Mac OS X 10.14.3, and I installed it with a prebuilt binary from the release page.

I think you don't have proprietary codecs. See the proprietary codecs section
of the mac os install docs

https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#on-macos

**Comment by NatHarari** [comment]
Thanks! I took a look, but I'm really unsure as to how to do that. Do I install it with 'brew install qt5'? Or is it the install listed here: https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-OS-X ?

**Comment by jgkamat** [comment]
Nathaniel Harari writes:

> Thanks! I took a look, but I'm really unsure as to how to do that. Do I install it with 'brew install qt5'? Or is it the install listed here: https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-OS-X ?

I have no idea how macs work, but this issue may be helpful

https://github.com/Homebrew/brew/issues/3623

You probably don't want to build qtwebkit unless you want to use qtwebkit specifically.

**Comment by jgkamat** [comment]
This isn't an issue in qutebrowser (but lacking proprietary codecs), so closing.
