### ISSUE TITLE
Include info for Windows 10 users in editor.command documentation

### ISSUE THREAD

**Issue by nancym** [qutebrowser/qutebrowser#4648]
I just spent a bunch of time figuring out how to set my editor.command to gvim on Windows 10. This is what worked for me in `config.py`:

```
c.editor.command = ['gvim.bat', '-f', '{file}', '-c', 'normal {line}G{column0}l']
```

It would be useful if the docs, e.g. [qutebrowser.org/doc/help/settings.html#editor.command](http://qutebrowser.org/doc/help/settings.html#editor.command) mentioned that the default `gvim` needs to be changed to `gvim.bat` on Windows 10 (assuming `gvim.bat` is on the path).

**Comment by jgkamat** [comment]
n writes:

> It would be useful if the docs, e.g. [qutebrowser.org/doc/help/settings.html#editor.command](http://qutebrowser.org/doc/help/settings.html#editor.command) mentioned that the default `gvim` needs to be changed to `gvim.bat` on Windows 10 (assuming `gvim.bat` is on the path).

I don't think this is a general case. If the gvim binary was named 'gvim', the
tip would no longer apply. The name probably depends on how you installed it.

**Comment by nancym** [comment]
You're right that `gvim.bat` is not the general case on Windows. Maybe the docs could include something like this:

> Note that on Microsoft Windows the full filename of the editor, including the filename extension, must be specified, for example gvim.bat or code.cmd.

It seems that qutebrowser knows about the PATH environment variable but does not know about the PATHEXT environment variable.

**Comment by jgkamat** [comment]
n writes:

>> Note that on Microsoft Windows the full filename of the editor, including the filename extension, must be specified, for example gvim.bat or code.cmd.

I don't think this is a general rule as well. Even on windows, the extension
may be removed (ex: running the cygwin version of gvim). I think that any
variant of "the editor command must exist on the path" goes without saying.
This reminds me of the mac os issues, where the path given to qutebrowser is
mangled, and there's nothing we can do about it.

> It seems that qutebrowser knows about the PATH environment variable but does not know about the PATHEXT environment variable.

We don't handle launching the process or maintaining the path at all, we just
use QProcess to start it.

https://doc.qt.io/qt-5/qprocess.html

https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/misc/guiprocess.py#L163

**Comment by The-Compiler** [comment]
Merging this into #5340.
