### ISSUE TITLE
1.6.1 doesn't include Windows installer

### ISSUE THREAD

**Issue by bradrn** [qutebrowser/qutebrowser#4659]
As the title suggests, the new 1.6.1 release doesn't include a Windows installer. Is this intentional or an error?

**Comment by jgkamat** [comment]
bradrn writes:

> As the title suggests, the new 1.6.1 release doesn't include a Windows installer. Is this intentional or an error?

The-Compiler is probably building it now, the windows binaries are usually
delayed slightly.

**Comment by The-Compiler** [comment]
Don't consider a release finished until I sent out the notification email :wink:

**Comment by The-Compiler** [comment]
Well, looks like the GitHub API hates me today so I had to upload them by hand rather than letting the release script do it, but they're there now.

**Comment by bradrn** [comment]
Thanks!

> Don't consider a release finished until I sent out the notification email 😉

What notification email is this? I've never heard of it.

**Comment by The-Compiler** [comment]
See the mailinglists [in the readme](https://github.com/qutebrowser/qutebrowser#getting-help) - if you only want (release) notifications without occasional user discussions, subscribe to the [qutebrowser-announce list](https://lists.schokokeks.org/mailman/listinfo.cgi/qutebrowser-announce).
