### ISSUE TITLE
wl-clipboard wait for qutebrowser focus to paste 

### ISSUE THREAD

**Issue by Eluminae** [qutebrowser/qutebrowser#4663]
Hello there,

I got a problem with wl-clipboard on sway wm.

The scenario is simple:

- Workspace 1 : Qutebrowser
- Workspace 2 : termite (terminal emulator)

-> In qutebrowser, I Ctrl+c some text
-> I switch to workspace 2, then Ctrl+Shift+v => nothing happen, freeze
I have to switch back to workspace 1 then come back to 2 to see my yanked content pasted into my terminal.

This problem occur only on qutebrowser so I guess it is a qutebrowser bug not sway, not wl-clipboard.

```
$ qutebrowser -V
qutebrowser v1.6.0
Git commit:
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.2 (compiled 5.12.1)
PyQt: 5.12

sip: 4.19.14
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QFusionStyle
Platform: Linux-5.0.2-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/eddie/.cache/qutebrowser
config: /home/eddie/.config/qutebrowser
data: /home/eddie/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

```
$ sway -v
sway version 1.0
```

```
$ wl-copy -v
wl-clipboard 1.0.0
Copyright (C) 2019 Sergey Bugaev
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

```
$ uname -r
5.0.2-arch1-1-ARCH
```

**Comment by Eluminae** [comment]
Precision, the problem DO NOT occur on the exact similar configuration on i3wm.

**Comment by jgkamat** [comment]
Eddie Barraco writes:

> Hello there,
>
> I got a problem with wl-clipboard on sway wm.
>
> The scenario is simple:
>
> - Workspace 1 : Qutebrowser
> - Workspace 2 : termite (terminal emulator)
>
> -> In qutebrowser, I Ctrl+c some text
> -> I switch to workspace 2, then Ctrl+Shift+v => nothing happen, freeze
> I have to switch back to workspace 1 then come back to 2 to see my yanked content pasted into my terminal.

Where are you copying from? Does the problem occur on kde falkon? I don't
think we handle ctrl-c specially at all.

**Comment by Eluminae** [comment]
I just highlight text with mouse then I press Ctrl+c.
Caret selection mode + Enter got exacty the same bahavior and the same problem.

**Comment by The-Compiler** [comment]
Please try with KDE Falkon like @jgkamat says - I doubt this is a qutebrowser specific issue. Maybe even other (non-QtWebEngine) Qt apps are affected as well.

**Comment by Eluminae** [comment]
Aha, KDE Falkon got the same problem ! What should we do ?

**Comment by The-Compiler** [comment]
Does it work when qutebrowser/Falkon is visible while pasting?

**Comment by Eluminae** [comment]
If the two are on the same workspace, it works perfectly.

**Comment by The-Compiler** [comment]
I'm pretty sure you're seeing [QTBUG-69077](https://bugreports.qt.io/browse/QTBUG-69077) then - since qutebrowser/Falkon is blocked, it also doesn't fill the clipboard I guess, and thus wl-copy blocks.

**Comment by Eluminae** [comment]
Yeah it seems to be that bug. I got crazy problems when I have two instance of qutebrowser on different workspace too.
Ty for all guys, you rocks. Kiss
