### ISSUE TITLE
slack workaround?

### ISSUE THREAD

**Issue by ExpandingMan** [qutebrowser/qutebrowser#4669]
As of yesterday slack no longer works for me on qutebrowser.  I absolutely 100% blame slack (which I despise) for this as I get the feeling that it is deliberately preventing itself from working.  However, I'm wondering if there is a workaround if that's the case?

Does anyone else have this issue and have any ideas?  One issue is that, I have one machine with Ubuntu 18.10 on which QtWebEngine is still using a 65 version of chromium.  I will check if my manjaro machine uses a more up to date version of chromium.  I'm not even sure if slack is allowed to know my chromium version, so I'm wondering if a simple user agent string hack would be a fix.

**Comment by The-Compiler** [comment]
Works fine for me with Qt 5.12 and the default user agent. Can't really say more without knowing your Qt version and whether it works with `--temp-basedir`.

**Comment by ExpandingMan** [comment]
Sorry, here's my version info.  I didn't post it before because at the moment I'm at work on a machine with an ancient version of Ubuntu (16.04) that they force me to use
```
qutebrowser v1.6.0
Git commit: 32f8349 (2019-02-25 13:50:59 +0100)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.5.2
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.0.2g  1 Mar 2016

Style: QFusionStyle
Platform: Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial, 64bit
Linux distribution: Ubuntu 16.04.6 LTS (ubuntu)
```
When I get home to my real computers I can report what things look like on a machine that isn't stuck in the past (on which slack was also not working).

**Comment by jgkamat** [comment]
Probably this is slack blocking older user agents. You can fake your user
agent by tweaking content.headers_user_agent. I would suggest setting it to:

'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99999.0.3578.98 Safari/537.36'

for slack at least, so they never bug you about it again (as they do this
quite regularly, at least back when I was using slack). Feel free to contact
support as well, but they didn't seem to care about any issues when I tried.

**Comment by ExpandingMan** [comment]
Thanks @jgkamat's user agent string works!

The fact that slack was deliberately sabotaging itself only deepens my hatred of it.

**Comment by The-Compiler** [comment]
I added a comment to #4445 which is a similar kind of issue.

**Comment by The-Compiler** [comment]
Since we're finding more and more pages which need a custom UA or other hacks, I opened a separate issue: #4810.

**Comment by rlue** [comment]
> You can fake your user
agent by tweaking content.headers_user_agent. I would suggest setting it to:
>
> 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99999.0.3578.98 Safari/537.36'

FYI this breaks certain sites that rely on CloudFlare CDN (_e.g.,_ medium.com). Seems the highest major version you can set without getting blocked is 99.

**Comment by The-Compiler** [comment]
The user_agent setting supports domain patterns, so I'd recommend only changing it for pages which really need a changed UA, not globally.

**Comment by epheo** [comment]
Hi @The-Compiler 
Why should we specify the UA on a per case basis instead lying constantly ?
I can't think about any good reason for a website to reject a browser based on its UA nowadays, mostly since 99% of them are still using Mozilla as first identification 20 years after it disappears...

Also, thanks a lot for everything.

**Comment by rcorre** [comment]
I started getting this for slack.

`:set content.headers_user_agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99999.0.3578.98 Safari/537.36'` does not help. It seems to want chrome v112, https://slack.com/help/articles/115002037526-System-requirements-for-using-Slack.

```
qutebrowser v3.0.0
Git commit: b11ead8f4-dirty on HEAD (2023-08-18 14:15:48 +0000)
Backend: QtWebEngine 6.5.1, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.1

CPython: 3.11.5
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: no
yaml: 6.0.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: no
sqlite: 3.43.0
QtNetwork SSL: Secure Transport, macOS Ventura (13.6)

Style: QMacStyle
Platform plugin: cocoa
OpenGL: None
Platform: macOS-13.6-arm64-arm-64bit, 64bit
Frozen: False
Imported from /Users/rrc/src/qutebrowser/qutebrowser
Using Python from /opt/homebrew/opt/python@3.11/bin/python3.11
Qt library executable path: /opt/homebrew/share/qt/libexec, data path: /opt/homebrew/share/qt
OS Version: 13.6, arm64

Paths:
auto config: /Users/rrc/Library/Preferences/qutebrowser
cache: /Users/rrc/Library/Caches/qutebrowser
config: /Users/rrc/.qutebrowser
data: /Users/rrc/Library/Application Support/qutebrowser
runtime: /private/var/folders/w4/qxlysshn0pg9h4d5sxcpmnrm0000gn/T/qutebrowser

Autoconfig loaded: no
Config.py: /Users/rrc/.qutebrowser/config.py has been loaded
Uptime: 0:00:11
```

**Comment by toofar** [comment]
I got a full page "not supported" error page this morning too. I'm on 6.6.0 which actually ships with 112 based though, so maybe their user agent matching is a bit strict. Here is my normal user agent (from https://httpbin.org/headers):

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) qutebrowser/2.5.2 QtWebEngine/6.6.0 Chrome/112.0.5615.213 Safari/537.36

Note that that has two extra segments compared to the chrome one. I got in by removing those two extra segments and setting the chrome major version to 118 (arbitrary version bump). But now I can't get it to kick me back out so I'm not actually sure which of the three things I changed (qute segment, Qt segment, chrome version) made it happy. I'll try again next time.

`:set -u app.slack.com content.headers.user_agent 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/118.0.5615.213 Safari/{webkit_version}'`

**Comment by rcorre** [comment]
That works! Thanks @toofar, you made my day!

**Comment by prosoitos** [comment]
Worked for me too but stopped working today.

**Comment by lewisbrown** [comment]
>Worked for me too but stopped working today.

Same

**Comment by Duologic** [comment]
I've replaced `{upstream_browser_key}` with hardcoded `Chrome`, seems to work.

**Comment by rcorre** [comment]
I'm finding that running the exact command @toofar posted still works:

```
set -u app.slack.com content.headers.user_agent 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/118.0.5615.213 Safari/{webkit_version}'
```

However, I've tried to put that in my config.py, and it doesn't seem to work:

```
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/118.0.5615.213 Safari/{webkit_version}', 'app.slack.com')
```

Yet as soon as I run that `:set` command again manually, it starts working again.
Am I doing something wrong with url-based config.py settings?

**Comment by The-Compiler** [comment]
@Duologic `{upstream_browser_key}` is always hardcoded to `Chrome` if you're using the QtWebEngine backend (which you most likely are, see `:version`).

@rcorre Those two commands should do the exact same. You could compare the `:config-diff` output maybe?

Given all that's been said here by @prosoitos / @lewisbrown / @Duologic / @rcorre, I feel like the most likely explanation is that Slack is doing some A/B testing, where with one request you might land in a group that works, but when refreshing or whatever (even if no setting actually changed!) you land in a different group and it breaks again.

**Comment by Duologic** [comment]
> Yet as soon as I run that :set command again manually, it starts working again.

This was the action I'm doing too, could it be that the user agent is not always consistently passed along? Just a guess, A/B testing also makes sense.

**Comment by prosoitos** [comment]
Slack changed their UI yesterday. So I think that indeed, they might have been engaged in a lot of testing just before releasing it.

**Comment by prosoitos** [comment]
Now that the new UI is released, hopefully things will calm down.

**Comment by xav-ie** [comment]
Just fyi, if you are trying to relogin, it will be redirecting you to your company slack page `company.slack.com` so I found this to work better:
`set -u *.slack.com content.headers.user_agent 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/118.0.5615.213 Safari/{webkit_version}'`
