### ISSUE TITLE
Renderer process crashes on 1.6.1 with pages that worked on 1.6.0

### ISSUE THREAD

**Issue by al3xandru** [qutebrowser/qutebrowser#4670]
**Version info (see `:version`)**:
```
qutebrowser v1.6.1
Git commit: 055e82709 (2019-03-20 07:23:17 +0100)
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.2
PyQt: 5.12.1

sip: 4.19.15
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.0.943 (bundled)
sqlite: 3.26.0
QtNetwork SSL: Secure Transport, macOS Mojave (10.14)

Style: QMacStyle
Platform: Darwin-18.2.0-x86_64-i386-64bit, 64bit
```

**Does the bug happen if you start with `--temp-basedir`?**:
No.

**Description**
Opening the page below results in a renderer process crashed error.

**How to reproduce**

http://nautil.us/issue/70/variables/what-makes-music-special-to-us

**Comment by al3xandru** [comment]
Something is very odd.  Now almost every page is leading to this error.

**Comment by al3xandru** [comment]
Removing the cache directory seems to solve the issue. 

I guess the issue can be closed.

**Comment by The-Compiler** [comment]
I've seen something similar myself (but only on web.telegram.im), on Linux with 5.12.0.

I guess you don't happen to still have the cache directory around, right?

**Comment by mrjnox** [comment]
Same issue for me today when `qt5-base`, `qt-webengine`, et al. were updated by pacman.

Moving the cache directory elsewhere fixed it.

```qutebrowser v1.6.2
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.3
Qt: 5.12.4 (compiled 5.12.3)
PyQt: 5.12.2
```
