### ISSUE TITLE
Can't scroll inside Apollo Docs website

### ISSUE THREAD

**Issue by davidsierradz** [qutebrowser/qutebrowser#4680]
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/d9fdfbb0

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

Can't scroll the webpage.

**How to reproduce**

Go to [Welcome - Apollo Docs](https://www.apollographql.com/docs/)

Thanks for this awesome browser BTW.

**Comment by jgkamat** [comment]
Seems like a duplicate of https://github.com/qutebrowser/qutebrowser/issues/1354

Also see https://github.com/qutebrowser/qutebrowser/pull/3691

**Comment by The-Compiler** [comment]
Looks like an issue with that website - it's not possible to scroll via keyboard in Firefox or Chromium either.

**Comment by jgkamat** [comment]
Florian Bruhin writes:

> Looks like an issue with that website - it's not possible to scroll via keyboard in Firefox or Chromium either.

Just for the record, vimium can scroll in that website, as it dosen't rely on
the native keyboard scrolling.

**Comment by davidsierradz** [comment]
Also [tridacty](https://github.com/tridactyl/tridactyl) can.
