### ISSUE TITLE
tarballs get un(g)zipped

### ISSUE THREAD

**Issue by AloisMahdal** [qutebrowser/qutebrowser#4684]
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/7cb7ae47

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

Trying to download a tarball (`some_file.tar.gz`) will result in the file being transparently "stripped" of the gzip compression -- only plain TAR file is saved.

**How to reproduce**

    touch file1
    touch file2
    tar -czf files.tar.gz file1 file2
    md5sum files.tar.gz
    # (upload files to some HTTP file server)
    qutebrowser http://url.to/the/files.tar.gz
    # (confirm download location)
    file location/of/files.tar.gz
    md5sum location/of/files.tar.gz

The file still "looks like" tarball but the type is `POSIX tar archive (GNU)` instead of `gzip compressed data...`.  And of course the MD5 is also different.

**Comment by AloisMahdal** [comment]
I tried the same file servers with Firefox and curl and in both cases the file is transferred untouched.

**Comment by AloisMahdal** [comment]
(BTW thanks for qutebrowser -- such a brilliant browser :-))

**Comment by The-Compiler** [comment]
Pretty sure that's still a broken server - works fine for me with e.g. https://github.com/qutebrowser/qutebrowser/archive/v1.6.1.tar.gz

Do you have a public example URL? If not, can you please:

- Show the headers you see with `curl --head` on that URL
- If possible, try in Chromium
- If it works there, try in KDE Falkon

**Comment by AloisMahdal** [comment]
I tried it with my public file server (Apache on current Debian) and turns out it does not trigger the issue. 
But at least 2 different servers in company internal network can reproduce it.  Here are headers from one of them:

    HTTP/1.1 200 OK
    Date: Wed, 27 Mar 2019 21:23:11 GMT
    Server: Apache
    Last-Modified: Wed, 27 Mar 2019 21:22:42 GMT
    ETag: "99cd9788-86-5851a09bf4a6c"
    Accept-Ranges: bytes
    Content-Length: 134
    Connection: close
    Content-Type: application/x-gzip
    Content-Encoding: x-gzip

For comparison, here's headers from my public server, where qutebrowser behaves normally:

    HTTP/1.1 200 OK
    Date: Wed, 27 Mar 2019 21:27:47 GMT
    Server: Apache/2.4.25 (Debian)
    Last-Modified: Wed, 27 Mar 2019 21:21:27 GMT
    ETag: "86-5851a0545a370"
    Accept-Ranges: bytes
    Content-Length: 134
    Content-Type: application/x-gzip

Looks like `Content-Encoding: x-gzip` triggers this.

And yes, chromium-browser is also affected.

**Comment by The-Compiler** [comment]
Nothing qutebrowser can do about this I'm afraid - and yep, it is a broken server, with `Content-Type: application/x-gzip` it's [asking](https://tools.ietf.org/html/rfc2616#section-14.11) the browser to unpack it.

**Comment by AloisMahdal** [comment]
While Firefox does something to work around this, I too prefer browsers to behave according to standards.  So yeah, qutebrowser is right. :-)

Thanks, I'll report the broken servers.
