### ISSUE TITLE
Consider having one global Qt stylesheet

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4686]
The change in #4637 made me wonder: Maybe we can have one big Qt stylesheet (probably even in a `.css` file) with appropriate class selectors, instead of having small stylesheet snippets all over the place?

Would probably make things simpler (especially the stylesheet logic in `config.py`) *and* faster.

@jgkamat what do you think?

**Comment by The-Compiler** [comment]
This also seems like a performance issue - with this config.py:

```python
import signal

def set_colors(*args):
    for i in range(40):
        c.colors.statusbar.normal.fg = '#fff'

signal.signal(signal.SIGUSR1, set_colors)
```

sending an USR1 hangs for a bit, and profiling shows that it's mostly stylesheets that are to blame.

**Comment by user202729** [comment]
I'm not sure about whether it can be faster. However the render step may be slower when #4808 is merged, because it's necessary to render a large style sheet instead of a small one even when just a config option change.

**Comment by jgkamat** [comment]
user202729 writes:

> I'm not sure about whether it can be faster. However the render step may be 
> slower when #4808 is merged, because it's necessary to render a large style 
> sheet instead of a small one even when just a config option change.

Didn't mirror this over before, but these are my thoughts on improving 
config-set with this issue.

http://paste.debian.net/plain/1084074

You only win on saving calls to setStyleSheet and other function call 
overhead, while everything else stays the same. With hints, setStyleSheet and 
object construction was very expensive, but in this profile, jinja and the 
config system is taking up the most time for me. #4808 is part of the right 
solution imo.

**Comment by The-Compiler** [comment]
Closing this since #4808 has been merged.
