### ISSUE TITLE
Renderer process crashes (mac mojave)

### ISSUE THREAD

**Issue by kklot** [qutebrowser/qutebrowser#4688]
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/bec3288f

**Does the bug happen if you start with `--temp-basedir`?**:

No idea, installed with the `.dmg`

**Description**

Renderer process crashed for all pages, including duckduckgo startpage

Things were fine with 1.6.0 a minute before, happened immediately after update.

**How to reproduce**

Open any links

**Comment by The-Compiler** [comment]
I assume you upgraded from v1.6.0? It's some kind of Qt bug, and deleting the cache directory (shown in `:version`, if that works) should make it go away.

**Comment by The-Compiler** [comment]
I assume you upgraded to v1.6.1? It's some kind of Qt bug - if you move the cache directory (shown in `:version`, if that works) it should work. Would you be willing to share your cache directory so I can debug this? So far I can't reproduce it myself.

**Comment by kklot** [comment]
Lovely, remove the cache solved it, thanks!

**Comment by The-Compiler** [comment]
A couple of people have seen this, but as long as I can't reproduce this (ideally by someone sharing their cache directory), there's little I can do.

**Comment by rickyson96** [comment]
@The-Compiler this happens to me too when I upgraded to v1.6.1 by using `brew cask upgrade`.
At first, i think this happened because I installed qutebrowser using brew, so I uninstalled the brew version and I install it using `pip install qutebrowser`, but the problem persists

Here is the `qutebrowser --version`:
```
qutebrowser v1.6.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.0
Qt: 5.12.2
PyQt: 5.12.1

sip: 4.19.15
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.26.0
QtNetwork SSL: Secure Transport, macOS Mojave (10.14)

Style: QMacStyle
Platform: Darwin-18.2.0-x86_64-i386-64bit, 64bit
Frozen: False
Imported from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qutebrowser
Using Python from /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
Qt library executable path: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/libexec, data path: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt
OS Version: 10.14.3, x86_64

Paths:
auto config: /Users/styletheory/Library/Preferences/qutebrowser
cache: /Users/styletheory/Library/Caches/qutebrowser
config: /Users/styletheory/.qutebrowser
data: /Users/styletheory/Library/Application Support/qutebrowser
runtime: /private/var/folders/q1/48f8d0d164x6hsqsn3rbzbgr0000gn/T/qutebrowser

Uptime: 0:00:00
```

**Comment by The-Compiler** [comment]
@rickyson96 Did you try removing `/Users/styletheory/Library/Caches/qutebrowser` like mentioned above?

**Comment by rickyson96** [comment]
removing the cache solve the problem, as well as using `--temp-basedir`.
