### ISSUE TITLE
All pages are rendered as blank, potentially from a crashed renderer

### ISSUE THREAD

**Issue by davidisaaclee** [qutebrowser/qutebrowser#4690]
**Version info (see `:version`)**:
```
qutebrowser v1.6.1
Git commit: 055e82709 (2019-03-20 07:23:17 +0100)
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.2
PyQt: 5.12.1

sip: 4.19.15
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.0.943 (bundled)
sqlite: 3.26.0
QtNetwork SSL: Secure Transport, macOS Mojave (10.14)

Style: QMacStyle
Platform: Darwin-18.2.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.14.3, x86_64

Paths:
auto config: /Users/david/Library/Preferences/qutebrowser
cache: /Users/david/Library/Caches/qutebrowser
config: /Users/david/.qutebrowser
data: /Users/david/Library/Application Support/qutebrowser
runtime: /private/var/folders/j8/c_fkjysj6j9_vwg0f5lthrjr0000gn/T/qutebrowser

Uptime: 0:00:00
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Attempting to load seemingly any page results in a white viewport – I have tried https/http, a variety of websites, and built-in qutebrowser pages (e.g. `:version`, `:messages`, settings). Other UI from qutebrowser is visible (e.g. tab bar, command prompt, link hints). I can copy and seemingly interact with the invisible page.

Starting qutebrowser from command line, the following is printed repeatedly:

```
[74598:80643:0330/211732.659216:ERROR:gl_context_cgl.cc(136)] Error creating context.
[74598:80643:0330/211732.659235:ERROR:gles2_command_buffer_stub.cc(262)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
```

Glancing through the report generated when I reported this as a bug via `:report`, I saw this line which seemed relevant:

```
20:15:59 ERROR    webview    tabbedbrowser:show_error_page:811 Renderer process crashed
```

**How to reproduce**

`:open duckduckgo.com`

**Comment by jgkamat** [comment]
Sounds like a duplicate of https://github.com/qutebrowser/qutebrowser/issues/4688

**Comment by davidisaaclee** [comment]
Yes, it does – however, deleting my cache directory (`/Users/david/Library/Caches/qutebrowser`, as reported by `qutebrowser --version`) does not fix the problem.

**Comment by The-Compiler** [comment]
This smells like a different issue than #4688, especially when it happens with `--temp-basedir`. Judging from the commandline output, it's QtWebEngine having some kind of issues with your graphics.

What hardware is this on? Anything special with your graphics stack?

Does starting with `-s qt.force_software_rendering chromium` help? If not, what about `qt-quick` or `software-opengl` instead of `chromium`?

**Comment by davidisaaclee** [comment]
Thanks for the suggestion about graphics stack – that led me to what seems to be the source of the problem. I have an external GPU attached to my MacBook Pro for use with Boot Camp; to my knowledge, macOS was not using it. Unplugging the eGPU fixed the problem.

for the record,
`chromium` - renders correctly
`qt-quick` - renders  correctly
`software-opengl` - does not render (same issue as described)
