### ISSUE TITLE
Selection reversing fails on macOS

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4694]
Looks like Travis wasn't running for #4513 and I didn't notice it broke on macOS...:

```
_ TestReverse.test_repetition_of_movement_results_in_empty_selection[webengine] _
self = <test_caret.TestReverse object at 0x119d88d30>
caret = <qutebrowser.browser.webengine.webenginetab.WebEngineCaret object at 0x119f400d8>
selection = <test_caret.Selection object at 0x119f2eb70>
    def test_repetition_of_movement_results_in_empty_selection(self, caret, selection):
        selection.toggle()
        caret.move_to_end_of_line()
        caret.reverse_selection()
        caret.move_to_end_of_line()
>       selection.check("")
tests/unit/browser/test_caret.py:383: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <test_caret.Selection object at 0x119f2eb70>, expected = ''
    def check(self, expected, *, strip=False):
        """Check whether we got the expected selection.
    
        Since (especially on Windows) the selection is empty if we're checking
        too quickly, we try to read it multiple times.
        """
        for _ in range(10):
            with self._qtbot.wait_callback() as callback:
                self._caret.selection(callback)
    
            selection = callback.args[0]
            if selection:
                if strip:
                    selection = selection.strip()
>               assert selection == expected
E               AssertionError: assert 'one two three' == ''
E                 - one two three
tests/unit/browser/test_caret.py:62: AssertionError
```

@beelzebielsk do you happen to have a Mac to investigate by any chance?

**Comment by beelzebielsk** [comment]
Sorry, I don't.

**Comment by beelzebielsk** [comment]
That's... huh. Interesting. While we're at it, does it break on windows?

**Comment by beelzebielsk** [comment]
Is this the only test that fails?

**Comment by jgkamat** [comment]
It dosen't seem to be broken on linux or windows or any of the other tests.
I'm not sure why it's broken only on mac os, I don't think it will be possible
to triage without a mac to test on, though.

**Comment by beelzebielsk** [comment]
I may be able to borrow a mac from a friend. One that they're not currently using at the moment. Can't promise anything, though.

**Comment by The-Compiler** [comment]
FWIW I do have access to a Mac (thanks to MacStadium's opensource initiative), but I'm unfortunately not allowed to give out access to others. I can take a quick look at what's going on, but can't commit to more than that the next couple of weeks.

**Comment by The-Compiler** [comment]
So when I do `v$o$` (that is `:toggle-selection`, `:move-to-end-of-line`, `:reverse-selection`, `:move-to-end-of-line` on macOS by hand, indeed the text is still selected. It seems like `$` still moves the right (rather than the left) cursor to the end of the line. Other motions like `w` seem to work fine, so I'll probably just adjust the test to use `w` (`:move-to-next-word`) instead.

However, I still want to find out why this is happening! I think what `$` does under the hood is essentially `window.getSelection().modify("extend", "right", "lineboundary")` so this smells like a Chromium bug (or intended platform difference?).

**Comment by The-Compiler** [comment]
Equivalent JS code:

```js
const sel = window.getSelection();
sel.modify("extend", "right", "lineboundary");  // $
sel.setBaseAndExtent(sel.extentNode, sel.extentOffset, sel.baseNode, sel.baseOffset);  // o
sel.modify("extend", "right", "lineboundary");  // $
```

And indeed, this works on Chromium in Linux but doesn't in Chrome on macOS. Let's fix the test and leave it at that. :laughing:
