### ISSUE TITLE
not responding on launch

### ISSUE THREAD

**Issue by tonitch** [qutebrowser/qutebrowser#4700]
Hello, I'v got a probleme and I have no clue why.

When I launch qutebrowser on my computer manjaro bspwm (comunity), qutebrowser launch and after a second, sort of crash and I can't do anything anymore...

I tried to launch it by console and the console also crash... I can't even ctrl-c to stop it

(freesed to the screenshot...)

I don't really know if I can provide you more informations... but hope you can help me in any way... I love this browser so much

ps: I'm french so I'm sorry for my english!
![2019-04-04-132439_987x1065_scrot](https://user-images.githubusercontent.com/26271060/55552233-29c44300-56dd-11e9-94ea-0255796cff8f.png)

**Comment by The-Compiler** [comment]
Can you try launching in the console with `--debug`? Are you on Intel graphics by any chance?

**Comment by tonitch** [comment]
[qutebrowser.log](https://github.com/qutebrowser/qutebrowser/files/3043772/qutebrowser.log)

here is the log of `Qutebrowser --debug` and I'v an nvidia card with propietary driver (not sure... maybe the free one) and amd ryzen V for cpu...

**Comment by The-Compiler** [comment]
Probably some graphic driver bug then... Can you try launching with `-s qt.force_software_rendering chromium` (or `qt-quick` or `software-opengl` instead of `chromium`) and see if that helps?

**Comment by tonitch** [comment]
that didn't do anything :/

**Comment by jgkamat** [comment]
Can you try the flags again but add --temp-basedir as well? (Try it first
without any extra flags, and then try the software rendering overrides).

**Comment by tonitch** [comment]
this appear with only --temp-basedir 
![2019-04-04-183245_473x282_scrot](https://user-images.githubusercontent.com/26271060/55572532-15e20680-5708-11e9-8393-40badbcd8941.png)

**Comment by tonitch** [comment]
I properly reinstall qtwebengine and now, this window didn't apear anymore, but the problem still occurs...
I think the browser is locked in "qtwebkit" mode but I don't know how to repair :/ any help?

**Comment by The-Compiler** [comment]
Closing this then! The hang with QtWebKit is probably some WebKit issue.

**Comment by motevets** [comment]
asdf
