### ISSUE TITLE
Spawn userscript while in visual mode

### ISSUE THREAD

**Issue by ElModdy** [qutebrowser/qutebrowser#4709]
I would like to pass the highlited text to a userscript but while I'm in "visual" mode I can't access the command so I can't spawn a userscript.
Is there a way to spawn a userscript while in "visual" mode with some text highlited?

**Comment by The-Compiler** [comment]
You can add a keybinding to do so, e.g. `:bind --mode=caret <Ctrl-U> spawn --userscript foo` (untested)
