### ISSUE TITLE
Copy url of current page to clipboard

### ISSUE THREAD

**Issue by raelb** [qutebrowser/qutebrowser#4711]
If I am not mistaken there does not exist a quick way to copy the url of current page to the clipboard. (one needs to type`go`, select url, then copy.) It would be very useful if there was a quick shortcut to achieve this.
Thanks

**Comment by The-Compiler** [comment]
`yy` (`:yank`) does so.

**Comment by raelb** [comment]
Thanks. Perhaps obvious for a vim user (which I am not..)
I did a search on https://www.qutebrowser.org/doc/help/commands.html for `copy` and the term was not found.
Perhaps changing the text:
`Yank something to the clipboard or primary selection.`
to
`Yank (copy) something to the clipboard or primary selection.`
may be helpful to others...

**Comment by The-Compiler** [comment]
Thanks for the suggestion! It was already mentioned as yank/copy in the [cheatsheet](qute://help/img/cheatsheet-big.png), but indeed not in the command list - [fixed](https://github.com/qutebrowser/qutebrowser/commit/345cae3a6313b0ff9fc9befd42c58583116c56f2)!

**Comment by Ddystopia** [comment]
What can I do for url to be decoded? 
Example:
Copies:
https://ru.wikipedia.org/wiki/LR-%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80
I want:
https://ru.wikipedia.org/wiki/LR-анализатор

**Comment by toofar** [comment]
@Ddystopia you should be able to do `:yank pretty-url` for that example. For more complicated stuff you'll need to write a userscript to transform it more.

**Comment by gnuchanos** [comment]
copy url good but ctrl+c works only in :commands  here why?
i every time copy text and paste in command window and copy again!
