### ISSUE TITLE
Is it possible to "freeze" a tab temporarily?

### ISSUE THREAD

**Issue by d-nnis** [qutebrowser/qutebrowser#4713]
Hi qute-folks!

Is there a way to temporarily "freeze" or hibernate a tab? This would come in handy for websites which are resource/CPU-hungry on a low-profile computer.
I find myself closing tabs of websites I know I will come back to later - only to free resources/ unload the CPU.

Or does this already happen on the side of qutebrowser, when a website is out of focus?

Thanks for any hints!

**Comment by arza-zara** [comment]
It's not yet supported. It's discussed in issue #67 and Qt issue [#74166](https://bugreports.qt.io/browse/QTBUG-74166), and there's PR #4037.
