### ISSUE TITLE
Running on mac requires admin rights?

### ISSUE THREAD

**Issue by gulkily** [qutebrowser/qutebrowser#4718]
I have been using a computer on which I am a guest with no admin rights.

1. I downloaded the latest .dmg from the Releases page.

2. I mounted it.

3. I tried to launch qutebrowser.app directly from the DMG.

At this point, I got a message that it is not blessed somehow by Apple, so I need to go into the Security control panel and press "Open Anyway". I can't do this without admin rights.

I was able to download and run another program in a similar manner. so it is not an issue of not being able to run programs.

**Comment by The-Compiler** [comment]
What happens if you right-/ctrl-click it and select "open"? Not sure if that requires admin rights as well, but that's what I used so far to open unsigned applications on macOS so far.

**Comment by gulkily** [comment]
Thank you very much for the quick response!

I will try it next chance I get and get back to you.

**Comment by gulkily** [comment]
I tried the context menu --> Open way, and it did not seem to work.

The exact complaint that macOS has is that the program is from an "unidentified developer".

I imagine this means that some monetary and paperwork tribute has not been paid to Apple.

**Comment by gulkily** [comment]
![Screen Shot 2019-04-16 at 2 32 57 PM](https://user-images.githubusercontent.com/1530699/56235197-f24a8480-6054-11e9-928f-05e51796c038.png)
![Screen Shot 2019-04-16 at 2 32 46 PM](https://user-images.githubusercontent.com/1530699/56235198-f24a8480-6054-11e9-8170-1e7899bce173.png)
![Screen Shot 2019-04-16 at 2 32 32 PM](https://user-images.githubusercontent.com/1530699/56235199-f24a8480-6054-11e9-9c7d-311e7efe4346.png)

**Comment by The-Compiler** [comment]
> I imagine this means that some monetary and paperwork tribute has not been paid to Apple.

Yep, $99 per year. I'm afraid this is not something I'm willing to pay out of pocket, especially seeing that this is the first time this is an issue in almost three years of macOS support. Sorry!

**Comment by bitraid** [comment]
I don't use macOS myself, but a couple of ways that used to work (serurity got stricter) are:

Removing the quarantine flag (from a terminal in qb app path): 
`xattr -d com.apple.quarantine "./qutebrowser.app"`

Or

Adding an exception to Gatekeeper:
`spctl --add "./qutebrowser.app"`
