### ISSUE TITLE
Remote command

### ISSUE THREAD

**Issue by ElModdy** [qutebrowser/qutebrowser#4720]
Hi, 
I would like to send a command from a bash script to qutebrowser to save the current session, if exists, and then load a new one.
I tried two things:
1.
```
 qutebrowser ":session-save -c"
 qutebrowser ":session-load -c $session"
```
The problem with this one is that qutebrowser load the new session before saving the previous one.

2. 
```
 qutebrowser ":session-save -c ;; session-load -c $session"
```
The problem with this one is that if no session is loaded in qutebrowser it prompts an error and it doesn't execute the second command.

**Comment by The-Compiler** [comment]
As for 1.: There's currently no way to wait until a command is finished when chaining them - see #3007. You can probably get away with adding a quick sleep between sending the commands.

As for 2.: That was a bug, qutebrowser should continue to run other commands - I fixed this in the commit above.

**Comment by ElModdy** [comment]
When will you rebuild the Arch package with this commit?

**Comment by The-Compiler** [comment]
I don't build the Arch package, but I suppose it'll be updated when v1.7.0 is released. No idea yet when that will be. FWIW you can use `qutebrowser-git` in the meantime. However, this is likely to have the same issues as your soluton 1 (loading the session before the old one is fully saved) as well.

**Comment by ElModdy** [comment]
The git one has been updated the same date as the "normal" one.
I will use the first solution with a sleep in between for now.
Thanks for the support.

**Comment by The-Compiler** [comment]
That's not how AUR git packages work. They get the newest git master commit whenever you build them, but you are responsible for rebuilding them.

**Comment by ElModdy** [comment]
I use `yay` to build the AUR package and that's what yay says:
### qutebrowser-git ( AUR )
![git](https://user-images.githubusercontent.com/18534491/56207687-aa752e80-604f-11e9-9c65-ce66f682f413.png)
### qutebrowser
![gitno](https://user-images.githubusercontent.com/18534491/56207695-ad701f00-604f-11e9-90b7-a698e413d015.png)

**Comment by ElModdy** [comment]
I'm really sorry for the stupid question but am I missing something?

**Comment by The-Compiler** [comment]
No worries! VCS packages (-git/-svn/etc.) don't get their PKGBUILD updated with every commit - that would cause a lot of unnecessary upgrades in the AUR.

Instead, whenever you build them, they get updated to whatever the latest commit is. However, it's your responsibility to update them from time to time - e.g. using `yay -Suy --devel`, or by telling yay to always update devel packages with `yay --devel --save`.

**Comment by ElModdy** [comment]
Thank you very much for the precious information.
I downloaded the AUR package and it works perfectly.
