### ISSUE TITLE
Session-save -o does not save the active window.

### ISSUE THREAD

**Issue by Shaaah** [qutebrowser/qutebrowser#4724]
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/9db1a89e

**Does the bug happen if you start with `--temp-basedir`?**:

No, the bug requires persistant sessions

**Description**

`:session-save -o test` should save only the active window. Instead it saves the first opened window. I lost quite a few sessions like this, I first assumed it was a problem with private windows, but it looks like it isn't.

**How to reproduce**

Open two windows, browse two different pages, "session-save -o test" on the second window that was opened.

e : close all qutebrowser windows and open it up again

session-load test opens a session of the first window that was opened

**Configuration file**

```
#Loading the Autoconfig file for other settings
#config.load_autoconfig()
c.auto_save.session = True
c.bindings.key_mappings = { '<Ctrl+Enter>': '<Ctrl+Return>', '<Enter>': '<Return>' }
c.colors.hints.fg = '#EEDD77'
c.colors.hints.bg = '#111111'
c.colors.hints.match.fg = '#00FF00'
c.colors.keyhint.fg = '#FFFFFF'
c.colors.keyhint.suffix.fg = '#00FF00'
c.colors.keyhint.bg = 'rgba(0, 0, 0, 75%)'
c.colors.tabs.bar.bg = '#444466'
c.content.autoplay = False
c.content.windowed_fullscreen = True
c.content.host_blocking.enabled = True
c.content.plugins = True
c.content.xss_auditing = True
c.completion.web_history.max_items = -1
c.downloads.location.suggestion = 'both'
c.downloads.position = 'bottom'
c.fonts.completion.entry = '10pt monospace'
c.fonts.hints = 'bold 11pt monospace'
c.hints.border = '2px solid #EEDD77'
#c.hints.chars = 'qsdfghjklm'
c.hints.chars = 'azertyuiopqsdfghjklmwxcvbn'
c.hints.uppercase = False
#c.keyhint.delay = 250
c.scrolling.smooth = True
c.tabs.position = 'left'
c.tabs.select_on_remove = 'last-used'
c.tabs.last_close = 'close'
c.tabs.favicons.scale = 1.0
c.tabs.width = '8%'
###############################
#Cleaning up previous bindings#
###############################
strUBindList=["M","m",'<Ctrl+h>']
#,"mo","mO","mm","mM","mp","mP","mù","m%","mv","mV",'<Ctrl+b>','<Alt+b>','ta','tA','gM','<Escape>','<Ctrl+j>','<Ctrl+k>','<Ctrl+l>','<Ctrl+x>','ys','<Alt+&>','<Alt+é>','<Alt+">',"<Alt+'>",'<Alt+(>','<Alt+->','<Alt+è>','<Alt+_>','<Alt+ç>','<Alt+à>'
for strUBind in strUBindList:
    config.unbind(strUBind)
###############################

##########################################
#Open videos with Streamlink, MPV and VLC#
##########################################
#MPV Best quality
config.bind('mo','hint links spawn mpv {hint-url} --title=\"${media-title} - Qutebrowser\" --force-window=yes')
config.bind('mO','spawn mpv {url:pretty} --title=\"${media-title} - Qutebrowser\" --force-window=yes')
#MPV 1080
config.bind('mm','hint links spawn mpv --ytdl-format=bestvideo[height<=1080]+bestaudio {hint-url} --title=\"${media-title} - Qutebrowser\" --force-window=yes')
config.bind('mM','spawn mpv --ytdl-format=bestvideo[height=1080]+bestaudio {url:pretty} --title=\"${media-title} - Qutebrowser\" --force-window=yes')
#MPV low quality
config.bind('mp','hint links spawn mpv --ytdl-format=bestvideo[height=480]+bestaudio {hint-url} --title=\"${media-title} - Qutebrowser\" --force-window=yes')
config.bind('mP','spawn mpv --ytdl-format=bestvideo[height=480]+bestaudio {url:pretty} --title=\"${media-title} - Qutebrowser\" --force-window=yes')
#Streamlink
config.bind('mù','hint links spawn streamlink {hint-url}')
config.bind('m%','spawn streamlink {url:pretty}')
#VLC
#config.bind('mv','hint links spawn vlc.exe {hint-url} --input-title-format="Qutebrowser"')
#config.bind('mV','spawn vlc.exe {url:pretty} --input-title-format="Qutebrowser"')
##########################################

##################################################
#Remapping the number keys to fit a French layout#
##################################################
config.bind('<Alt+&>','tab-focus 1')
config.bind('<Alt+é>','tab-focus 2')
config.bind('<Alt+">','tab-focus 3')
config.bind("<Alt+'>",'tab-focus 4')
config.bind('<Alt+(>','tab-focus 5')
config.bind('<Alt+->','tab-focus 6')
config.bind('<Alt+_>','tab-focus 8')
config.bind('<Alt+è>','tab-focus 7')
config.bind('<Alt+ç>','tab-focus 9')
config.bind('<Alt+à>','tab-focus 10')
##################################################
#Opening Bookmarks
config.bind('<Ctrl+b>','set-cmd-text -s :bookmark-load')
config.bind('<Alt+b>','set-cmd-text -s :bookmark-load -t')
#Toggling adblock settings
config.bind('ta',r'config-cycle -t -p content.host_blocking.enabled ;; reload')
config.bind('tA',r'config-cycle -p content.host_blocking.enabled ;; reload')
#Binding gM to move tab to last place
config.bind('gM','tab-move ;; tab-move -')
config.bind('gD','hint all download')
#Ctrl H/J/K/L to scroll a page in their respective directions with a little slack for headers and footers
config.bind('<Ctrl+j>','scroll-page 0 0.93')
config.bind('<Ctrl+k>','scroll-page 0 -0.93')
config.bind('<Ctrl+h>','scroll-page -0.93 0')
config.bind('<Ctrl+l>','scroll-page 0.93 0')
#Rebinding the shortcut to open completed download as the old one is depreciated or inexistant?
config.bind('<Ctrl+x>','download-open')
#Yank selected text in normal mode
config.bind('ys','yank selection')
config.bind('yi','hint images yank')
##########################
# Giving and Taking tabs #
##########################
config.bind('!g','tab-give') 
config.bind('!t1','set-cmd-text :tab-take 0/')
config.bind('!t2','set-cmd-text :tab-take 1/')
config.bind('!t3','set-cmd-text :tab-take 2/')
config.bind('!to','set-cmd-text :tab-take ')
####################
#Command mode binds#
####################
#Unbinding#
###########
strUBindCommandMList=['<Tab>','<Shift-Tab>','<Ctrl-Tab>','<Ctrl-Shift-Tab>','<Up>','<Down>']
for strUBindCommand in strUBindCommandMList:
    config.unbind(strUBindCommand,mode='command')
##########

config.bind('<Ctrl-Space>','rl-unix-line-discard',mode='command')
#
config.bind('<Ctrl+k>','command-history-prev',mode='command')
config.bind('<Ctrl+h>','rl-backward-kill-word',mode='command')
config.bind('<Ctrl+j>','command-history-next',mode='command')
config.bind('<Ctrl+l>','rl-kill-word',mode='command')
#
config.bind('<Alt+k>','completion-item-focus --history prev',mode='command')
config.bind('<Alt+h>','completion-item-focus prev-category',mode='command')
config.bind('<Alt+j>','completion-item-focus --history next',mode='command')
config.bind('<Alt+l>','completion-item-focus next-category',mode='command')
```

**Comment by jgkamat** [comment]
Shaaah writes:

> **How to reproduce**
>
> Open two windows, browse two different pages, "session-save -o test" on the second window that was opened.
>
> session-load test opens a session of the first window that was opened

I cannot reproduce with:

1. qutebrowser --basedir /tmp/qbtest
2. :open -w jgkamat.gitlab.io
3. :session-save -o my-website
4. :quit
5. qutebrowser --basedir /tmp/qbtest
6. :session-load my-website

And I cannot reproduce with auto_save.session set either.

**Comment by The-Compiler** [comment]
Same here, I get the (second) window which was focused back, as expected.

@Shaaah can you please reproduce this and do `:report` (ideally once before quitting and once after) so I can take a look at the logs?

**Comment by Shaaah** [comment]
I sent a :report with the reference to this github issue (4724)

The reproduce steps were wrong .... sorry for wasting your time.

The updated steps to reproduce 100% I totaly tried it this time:

Open two windows, browse two different pages, "session-save -o test" on the second window that was opened.

close all qutebrowser windows **and reboot** open qutebrowser

session-load test opens a session of the first window that was opened

...

Additionaly I tried 

1. qutebrowser --basedir /tmp/qbtest
2. :open -w tralala
3. :session-save -o bugtreport
4. terminate qb (NOT :quit)
4.5 reboot
5. qutebrowser --basedir /tmp/qbtest
6. :session-load my-website

Still doesn't work.

Sooooo. I figured that since I use i3, I have the bad habit of using the "kill" shortcut provided with i3 to close qutebrowser windows. Maybe that's the problem?

**Comment by Shaaah** [comment]
Finally figured it out when messing with sessions.

Steps to reproduce : 

1. \# qutebrowser --basedir ~/.local/test
2. :set auto_save.session = true
3. :open -w twitter.com 
4. :session-save 1 
5. :q 
6. :open reddit.com
7. :q 
8. \# qutebrowser --basedir ~/.local/test
9. :session-load 1 
10. You land on reddit.com instead of twitter.com

There are two ways around this : 

- set auto_save.session = false
- saving sessions with the -t option

There should at least be a warning about the consequences of setting auto_save.session to true in the settings page description. It made me think the sessions were completely busted for a long time.

**Comment by The-Compiler** [comment]
@Shaaah The steps above still load Twitter for me. Only when quitting/loading a second time, Reddit is loaded, because by default, `auto_save.session` saves to the session which was last loaded. Is this the same you're seeing (in which case your steps above are incorrect)?

**Comment by The-Compiler** [comment]
@Shaaah Any update on this? Is this something you're still seeing?

**Comment by Shaaah** [comment]
@The-Compiler I can still reproduce (removing the '=' in the step :set auto_save.session = true ) but the documentation is clearer than it was before, so I don't think I would make the configuration mistake again.

Otherwise, I stoped using auto_save.session so this is not an issue for me anymore.

<3
