### ISSUE TITLE
"Error while spawning editor: The process failed to start.", fixed after restart (ENOMEM)

### ISSUE THREAD

**Issue by blueyed** [qutebrowser/qutebrowser#4725]
**Version info (see `:version`)**: qutebrowser v1.6.1

I see the following error occassionally when using `Ctrl-e` in a text field:

> Error while spawning editor: The process failed to start.

Restarting qutebrowser then usually fixes it.

I use `editor.command = ["vim-in-term", "{}"]`, where `vim-in-term` is basically:
```sh
#!/usr/bin/env zsh
exec urxvt -e zsh -i
```

1. this should not happen in the first place
2. it should provide more information, e.g. the command being run, and anything else there might be.

strace shows this:
```
access("/home/user/.dotfiles/usr/bin/vim-in-term", X_OK) = 0
pipe2([877, 887], O_CLOEXEC)            = 0
eventfd2(0, EFD_CLOEXEC)                = 890
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f91bfa878d0) = -1 ENOMEM (Cannot allocate memory)
close(890)                              = 0
close(877)                              = 0
close(887)                              = 0
```
And indeed I am currently a bit short on memory, but mainly due to qutebrowser using 22% of my 16GB already:
```
MiB Mem :  15913.6 total,    179.0 free,   9136.6 used,   6598.0 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2277.4 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                
 2089 user    20   0 9273744   3.4g 644692 S   6.3  22.0  60:49.74 qutebrowser            
```
Since a lot of it is buff/cache, it should be available in general still.

FWIW, `vim-in-term` works outside of qutebrowser.

(It is not possible to change the log level during runtime, is it? - since this could provide more info then maybe)

**Comment by jgkamat** [comment]
Daniel Hahler writes:

> 1. this should not happen in the first place
> 2. it should provide more information, e.g. the command being run, and anything else there might be.

Unfortunately we launch processes from Qt and they only seem to give some very
generic codes and nothing very helpful. I don't think we should be using this
api, fwiw:

http://doc.qt.io/qt-5/qprocess.html#ProcessError-enum

>
> strace shows this:
> ```
> access("/home/user/.dotfiles/usr/bin/vim-in-term", X_OK) = 0
> pipe2([877, 887], O_CLOEXEC)            = 0
> eventfd2(0, EFD_CLOEXEC)                = 890
> clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f91bfa878d0) = -1 ENOMEM (Cannot allocate memory)

I don't think we (or qt) can do much to fix a ENOMEM from clone. My best guess
is checking memory overcommit settings. When this happens, are other programs
able to start (even large ones)? Maybe you could try forcing a memory
compaction as well: /proc/sys/vm/compact_memory.

I don't think I'm skilled enough to debug this much futher, but it might be
interesting if you posted your /proc/meminfo when this happens, along with any
possible related messages in dmesg.

> close(890)                              = 0
> close(877)                              = 0
> close(887)                              = 0
> ```
> And indeed I am currently a bit short on memory, but mainly due to qutebrowser using 22% of my 16GB already:
> ```
> MiB Mem :  15913.6 total,    179.0 free,   9136.6 used,   6598.0 buff/cache
> MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2277.4 avail Mem
>
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
>  2089 user    20   0 9273744   3.4g 644692 S   6.3  22.0  60:49.74 qutebrowser

This seems a bit high, in my testing I've only seen the qb process go up to
1gb at the highest. Can you post your full :version output? If possible, it
would be nice to get some tracemalloc diff snapshots as well (in case there is
a memory leak in the python code).

http://www.gitlab.com/jgkamat/dotfiles/blob/master/qutebrowser/.config/qutebrowser/pyconfig/qute-tracemalloc.py

If you find a certain action that when repeated causes RSS to reliably
increase, let me know. Note that for things like opening tabs, RSS will
increase but probably won't shrink when the tabs are closed (but the memory
will be re-used when more is needed), due to python's memory model.

> ```
> Since a lot of it is buff/cache, it should be available in general still.

This isn't 100% true, for example, if qutebrowser was started in a memory
constrained cgroup or had some other sort of limit it was running against (eg:
max virtual memory) it could throw this same error.

> FWIW, `vim-in-term` works outside of qutebrowser.

Does something like:

import subprocess; subprocess.run("gvim")

work in :debug-console when the :spawn method dosen't work?

> (It is not possible to change the log level during runtime, is it? - since this could provide more info then maybe)

Everything that's not VDEBUG (I think) gets logged by default. You can access
it with :messages debug. Don't think that will help here though.

**Comment by blueyed** [comment]
> I don't think we (or qt) can do much to fix a ENOMEM from clone. My best guess
is checking memory overcommit settings. When this happens, are other programs
able to start (even large ones)?

I do not see problems with any other programs.

(Apart from having noticed that both Squid and Varnish behaved strange in Docker containers; Squid tried to allocate a massive amount of memory (160GB?), and Varnish busy-looped over some fd - both could be worked around using some `--ulimit "nofile=5000:10000"` with docker-run)

> ENOMEM from clone

It looks like the sum of RES + SHR is close to 4GB, which might be some limit?

> This seems a bit high, in my testing I've only seen the qb process go up to
1gb at the highest. Can you post your full :version output? If possible, it
would be nice to get some tracemalloc diff snapshots as well (in case there is
a memory leak in the python code).

I have 215 tabs currently, and suspend / use it for days without restart.

```
qutebrowser v1.6.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.3
Qt: 5.12.2
PyQt: 5.12.1

sip: 4.19.16
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.1.266 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QFusionStyle
Platform: Linux-5.0.7-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 3 days, 4:36:43
```

Running it from `:debug-console` also fails with `OSError: [Errno 12] Cannot allocate memory`.

Compacting memory did not help.

**Comment by blueyed** [comment]
> I have 215 tabs currently

But most of them are suspend - some of them fail to load now when trying to load them, but e.g. I've seen no problems with regular usage, i.e. new tabs etc.

**Comment by blueyed** [comment]
`/proc/meminfo`:
```
MemTotal:       16295484 kB
MemFree:         1107576 kB
MemAvailable:    2386124 kB
Buffers:          295276 kB
Cached:          5011344 kB
SwapCached:            0 kB
Active:          9837940 kB
Inactive:         964248 kB
Active(anon):    9112064 kB
Inactive(anon):   415900 kB
Active(file):     725876 kB
Inactive(file):   548348 kB
Unevictable:     3517668 kB
Mlocked:           30020 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               116 kB
Writeback:             0 kB
AnonPages:       9013248 kB
Mapped:          1015148 kB
Shmem:           4034416 kB
KReclaimable:     347492 kB
Slab:             530116 kB
SReclaimable:     347492 kB
SUnreclaim:       182624 kB
KernelStack:       24576 kB
PageTables:       111216 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8147740 kB
Committed_AS:   32864924 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:             7840 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      497944 kB
DirectMap2M:    14053376 kB
DirectMap1G:     3145728 kB
```

**Comment by jgkamat** [comment]
Unfortunately I don't have any good leads on this so far. The only other easy
thing I can think of is to look and see if dmesg yells about anything when
this happens. My first guess is still a cgroup or other method that's limiting
memory size.

I don't know if I can properly interpret the results, but sarnold suggested
using a kernel tracer to trace the syscall. Hopefully the tracer will still
output when the error occurs, and we can see exactly where in the kernel the
error happened. Unfortunately this requires some special tooling, namly
funcgraph from brendangregg's perf tools. It's available in debian under
perf-tools-unstable, I'm not sure if anyone packaged it properly for arch
though. It also has the possibility of causing a kernel panic (according to
the manpage).

http://www.github.com/brendangregg/perf-tools/blob/master/kernel/funcgraph
http://packages.debian.org/buster/perf-tools-unstable

Once you have it installed, you should be able to grab qb's PID and run a
trace on the clone syscall. Ideally you would only get a single function call
to minimize the size. Here's my invocation.

sudo funcgraph-perf -P -p 20387 '__x64_sys_clone' | tee ~/jay-clone

The resulting file for me is 2mb (with a single call). It's possible to get
the same result with just plain ftrace, but I couldn't find the right
incantation.

**Comment by blueyed** [comment]
Here is my funcgraph output: 
[t.log](https://github.com/qutebrowser/qutebrowser/files/3100061/t.log)
It looks quite different from yours (I've removed the prefix with the pid, and diffed them), but I am not sure what to look for really.. :)

**Comment by blueyed** [comment]
Nothing in `dmesg`, and not running it in Docker.

**Comment by blueyed** [comment]
With regard to improving the error message: I assume qutebrowser is seeing then `QProcess::FailedToStart` only? (via https://doc.qt.io/qt-5/qprocess.html#ProcessError-enum)

**Comment by jgkamat** [comment]
Daniel Hahler writes:

> With regard to improving the error message: I assume qutebrowser is seeing then QProcess::FailedToStart only? (via https://doc.qt.io/qt-5/qprocess.html#ProcessError-enum)

Yup, unfortunately that's all we get from that api, if we wanted more detailed
errors we should use python to launch processes instead (which sounds like a
good idea to me at least). Not sure if the api can be kept the same or not
though.

According to that trace (not sure if this is correct of course), it seems like
it's failing in __vm_enough_memory, which checks if you have enough virtual
memory allocation (not physical memory). Your virtual memory is at 32 gb (when
you only have 16gb of free physical memory, which seems a little high to me at
least. For testing, you could try setting vm.overcommit_memory to 1 (always
overcommit) instead of the default, 0 (overcommit according to a heuristic),
and if that works, you can try enabling some swap space instead (if you don't
like that setting). Unfortunately, I don't understand the heuristic well
enough to figure out where the cutoff would be on your system. Let me know if
vm.overcommit_memory -> 1 doesn't help.

Unfortunately we probably can't do anything do reduce virtual memory usage
ourselves due to python/chrome's sloppy approach to memory management, other
than just reducing the amount of memory used.

**Comment by blueyed** [comment]
`vm.overcommit_memory -> 1` fixed it!

> Your virtual memory is at 32 gb (when
you only have 16gb of free physical memory, which seems a little high to me at
least

Yeah.  How can you control this?
It also appears to be related to Squid trying to allocate so much memory in Docker without using `--ulimit "nofile=5000:10000"` as a workaround to docker-run..

I've used to have swap, but disabled it when running short of disk space, and thought that 16GB should be enough RAM always.  This was ~1 month ago, and I am seeing the issue with qutebrowser failing to open the editor since around then also I guess.

I've tried `echo 2 | sudo tee /proc/sys/vm/overcommit_memory`, but that killed my X session instantly (should have done `echo 100 | sudo tee /proc/sys/vm/overcommit_ratio` before probably).

But this was also not really satisfying, .. with `overcommit_memory = 1` and not using the workaround of passing `--ulimit "nofile=5000:10000"` to docker-run it will freeze the system for minutes until Squid gets killed:

> Killed process 6024 (squid) total-vm:595607524kB, anon-rss:4165380kB, file-rss:52kB, shmem-rss:64kB 

Thanks for all your help and info so far!

As for qutebrowser: I am down to ~170 tabs now, but it appears to behave worse now: it takes ~6s to display the initial window (displaying "loading …" for all tabs until then in the tasklist entry) (which is normal/OK), but did not display the current tab after 5 minutes still (blank page).  After opening this page, it eventually displayed "Unable to load page

> Error while opening data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf-8 sts%3D4 sw%3D4 et%3A%0A--%3E%0A%0A%3Chtml%3E%0A %3Chead%3E%0A %3Cmeta charset%3D%22utf-8%22%3E%0A %3Ctitle%3EError loading https%3A%2F%2Fdjangopackages.org%2Fgrids%2Fg%2Fauthentication%2F%3C%2Ftitle%3E%0A …
> Renderer process was killed

Using the "try again" button then in a shorter:

> Unable to load page
> Error while opening https://djangopackages.org/grids/g/authentication/
Renderer process was killed

At lot of suspended tabs fail like this now, but not all.

Opening new tabs works however in general.

I am using the default memory settings after a reboot now, but upgraded linux to 5.0.8-arch1-1-ARCH.

**Comment by jgkamat** [comment]
Daniel Hahler writes:

> `vm.overcommit_memory -> 1` fixed it!

Nice! At least we know what's causing it to fail now 😅

> Yeah.  How can you control this? [...]
> I've tried `echo 2 | sudo tee /proc/sys/vm/overcommit_memory`, but that killed my X session instantly (should have done `echo 100 | sudo tee /proc/sys/vm/overcommit_ratio` before probably).
> But this was also not really satisfying, .. with `overcommit_memory = 1` and not using the workaround of passing `--ulimit "nofile=5000:10000"` to docker-run it will freeze the system for minutes until Squid gets killed:

Sorry, I probably should have warned about the possibility of that happening
when messing around with these settings, the OOM killer probably went into
overdrive and killed almost everything :C.

In general, there is a reason why the heuristic tries to prevent extreme
overallocations, it makes it more likely that a program can decide to actually
start using the memory its allocated and force a program to be killed. The
best solution is to try to reduce your virtual memory usage. Unfortunately I
know basically nothing about squid and what that ulimit workaround does, so I
probably can't help there (but the amount it's requesting seems a little
extreme to me). Figuring out what's going on with squid is probably the best
starting point (both to avoid OOMs on your system and fixing this issue).

If you want to control the overcommit threshold yourself manually (without
disabling it completely), first play with vm.overcommit_ratio until the
'CommitLimit' field in /proc/meminfo is the amount of *virtual* memory limit
you want. By default, this is 50% of system memory (maybe + swap), which will
prevent 50% of your system memory from being allocated to programs. Most
likely, you'll want to set it to >250 or so, as your Virtual memory seems to
be hovering around 32GB. Once you're happy with the limit (and ensured that
'Committed_AS' is LESS than the limit), you can switch vm.overcommit_memory to
2 to start using the limit (hopefully with fewer issues...).

> I've used to have swap, but disabled it when running short of disk space, and thought that 16GB should be enough RAM always.  This was ~1 month ago, and I am seeing the issue with qutebrowser failing to open the editor since around then also I guess.

The reason why I suggested swap is only because the amount of space available
in swap is added to the 'free virtual memory' given by the heuristic, so it's
an easy way to increase the limit a bit indirectly without playing with
settings. Setting the limit yourself manually does the same thing (minus
adding the swap) with the downside of the limit not changing dynamically
anymore.

That algorithm is here if you're interested:
http://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/mm/util.c#n669

> As for qutebrowser: I am down to ~170 tabs now, but it appears to behave worse now: it takes ~6s to display the initial window (displaying "loading …" for all tabs until then in the tasklist entry) (which is normal/OK), but did not display the current tab after 5 minutes still (blank page).  After opening this page, it eventually displayed "Unable to load page
> [...]
>> Renderer process was killed

If you see this error, I would check dmesg to see if anything OOMed (that will
be logged to dmesg). If not, this sounds like a qt/webengine/chrome bug
unfortunately and is out of my scope again, but it might be useful to install
debugging symbols and get a stacktrace if you continue seeing it: http://www.github.com/qutebrowser/qutebrowser/issues/4010#issuecomment-398658074

https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc

I personally have started seeing these on restore occasionally since qt5.11,
and I've been too busy to triage that myself.

**Comment by The-Compiler** [comment]
I don't think we can do anything about the error occurring - it seems to come from your system, and not anything qutebrowser/Qt is doing wrong :wink:

As for the error output: Using the `subprocess` API isn't really an option, as we need asynchronous ways of handling process output/exit/etc. However, `QProcess::errorString()` actually exists (inherited from `QIODevice`) and does provide much better output. As of 93153dbbcdc464a72bb049778a53776b7df53b20, qutebrowser is now using that! I never realized that existed until I took a closer look again now...

**Comment by blueyed** [comment]
Just for reference: I've investigated and found that the Squid issue is caused by having `LimitNOFILE=infinity` in `/etc/systemd/system/docker.service` (via an old version of that file - they use `LimitNOFILE=1048576` by now).  Apparently Squid (and Varnish) use the number of available file descriptors for allocating memory or something like that.
So it is not really related to the issue with qutebrowser I guess.

**Comment by blueyed** [comment]
I am getting the error now again.

> I don't think we can do anything about the error occurring - it seems to come from your system, and not anything qutebrowser/Qt is doing wrong

Well, it could use less memory in the first place maybe? ;)

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND       
 6862 daniel    20   0 7937284   2.0g 811748 T   0.0  12.8  48:47.36 qutebrowse
```

At least this now shows that it is not due to being close at 4gb.

I've adjusted overcommit_ratio then (to prepare for the suggested vm.overcommit_memory=2).
```
% echo 300 | sudo tee -a /proc/sys/vm/overcommit_ratio
% cat /proc/meminfo|grep -i commit
CommitLimit:    48886284 kB
Committed_AS:   40754368 kB
```

The editor still failed to start.

I've closed a bunch of stuff then (to not lose it again due to X being killed), resulting in the editor to launch again.
```
CommitLimit:    48886284 kB
Committed_AS:   32605868 kB
```

Unfortunately I do not have the full `/proc/meminfo` from before, but now it looks like this:
```
MemTotal:       16295428 kB
MemFree:         3041088 kB
MemAvailable:    3491420 kB
Buffers:          190616 kB
Cached:          4430464 kB
SwapCached:            0 kB
Active:          8240188 kB
Inactive:         526132 kB
Active(anon):    7804440 kB
Inactive(anon):   306816 kB
Active(file):     435748 kB
Inactive(file):   219316 kB
Unevictable:     3577952 kB
Mlocked:           20776 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                36 kB
Writeback:             0 kB
AnonPages:       7723352 kB
Mapped:          1155652 kB
Shmem:           3963040 kB
KReclaimable:     353396 kB
Slab:             555948 kB
SReclaimable:     353396 kB
SUnreclaim:       202552 kB
KernelStack:       27200 kB
PageTables:       109268 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    48886284 kB
Committed_AS:   32549608 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:            16896 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:     1515800 kB
DirectMap2M:    15132672 kB
DirectMap1G:     1048576 kB
```

**Comment by The-Compiler** [comment]
> Well, it could use less memory in the first place maybe? ;)

See #1476, but most cases where qutebrowser (i.e. Python code) uses much RAM have been fixed already. Most of it is due to QtWebEngine/Chromium.

**Comment by blueyed** [comment]
Happens again now.  This is quite annoying, since I have to copy things back and forth then.

Meanwhile I have enabled swap again, since I've read that not using swap is bad in general.. I am using systemd-swap, currently using 100/500M there.

**Comment by blueyed** [comment]
For the record: I was seeing this error now also after restarting qutebrowser (~280 tabs), while it started happening before only after a while.  qutebrowser took ~2 mins of CPU to display the first page in this case also..!

I am now down to 20 tabs..:)

**Comment by The-Compiler** [comment]
Maybe related somehow: https://development.qt-project.narkive.com/274cXU2c/qprocess-fork-failure-and-overcommit
