### ISSUE TITLE
Execute command before quitting

### ISSUE THREAD

**Issue by ElModdy** [qutebrowser/qutebrowser#4726]
Hi, is there a way to execute a command before quitting.
I send the quit message from i3 with the kill command and I would like to save the current session before quitting.

**Comment by jgkamat** [comment]
ElModdy writes:

> Hi, is there a way to execute a command before quitting.
> I send the quit message from i3 with the kill command and I would like to save the current session before quitting.

Perhaps you want auto_save.session.

If you really need a command, why not run a command over IPC before quitting
qb.

I'm not sure what the i3 kill command does, but if it sends a SIGKILL that's
not ideal either (you can easily get corruption and/or data loss).

**Comment by ElModdy** [comment]
you are right. Thanks for the reply
