### ISSUE TITLE
Problem rendering a single webpage

### ISSUE THREAD

**Issue by ColorOfSilence** [qutebrowser/qutebrowser#4740]
**Version info (see `:version`)**: verson 1.6.1
https://paste.the-compiler.org/view/57d6f206

**Does the bug happen if you start with `--temp-basedir`?**: No, it does not

**Description**
I have had an issue with qutebrowser for a while where it will not load the duckduckgo homepage or any duckduckgo pages. I have it as my homepage for whenever I open qutebrowser or when I type `:home`, every other page loads correctly it is just that one page.

![2019-04-28-143335_1916x1052_scrot](https://user-images.githubusercontent.com/7514699/56870400-ad630e00-69c3-11e9-9fb6-9efe25cab588.png)
![2019-04-28-143341_1916x1052_scrot](https://user-images.githubusercontent.com/7514699/56870412-da172580-69c3-11e9-9af1-a63dd3b37a66.png)

These are the errors that it produces, but when I run `qutebrowser --temp-basedir` it is able to open the page correctly

**Comment by The-Compiler** [comment]
Can you try quitting qutebrowser and moving `~/.cache/qutebrowser` away?

**Comment by ColorOfSilence** [comment]
@The-Compiler that seems to have fixed it thanks, would it be safe to delete the contents of '~/.cache/qutebrowser`?

**Comment by The-Compiler** [comment]
Yep! I have similar issues since Qt 5.12 with web.telegram.im, and sometimes the issue suddenly comes back - I still have no idea what causes it so far, but it doesn't seem like a qutebrowser-specific thing...

**Comment by adem** [comment]
For what it's worth, I have the same issue with web.telegram.org, however, I didn't know about the other domain web.telegram.im, which works fine and seems to be an unofficial version of the former (this caught me off guard because it looks exactly the same).
