### ISSUE TITLE
Launching keyhint widget causes 100% usage of one CPU core

### ISSUE THREAD

**Issue by wfrced** [qutebrowser/qutebrowser#4742]
That's how it was for as long as I can remember, reproducible with all of my hardware (pressing _g_ or _;_ is enough). I don't think that's an intended behavior.

**Comment by The-Compiler** [comment]
What Qt and qutebrowser version? Can you reproduce it with `--temp-basedir`?

**Comment by wfrced** [comment]
qutebrowser v1.6.1
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.3 (compiled 5.12.2)
I'm on Wayland if it makes a diiference.
Sorry, I can't reproduce it with --temp-basedir, really should've checked. But the only non-default keyhint-related setting is keyhint.delay=0.

**Comment by wfrced** [comment]
Sorry for the noise. I've noticed that the browser is much snappier with ``--temp-basedir``. Turns out, software rendering was enforced for some reason, and I have a gradient fill keyhint widget, which kills the CPU.

**Comment by wfrced** [comment]
Actually, disregard the upper post, it's not the fault of software rendering.
The problem still occurs, and the culprit is ``keyhint.delay=0``. CPU usage is inversely proportional to delay - 0 ms leads to 100% usage, 10 ms brings it down to ~50%, 100 ms brings it to 5% on start (goes down to usual 2% the second after).

**Comment by The-Compiler** [comment]
Ah, indeed - looks like we set up `self._show_timer` in `keyhintwidget.py` to show the keyhint widget (delayed), but we never stop it after it's shown.

cc @rcorre
