### ISSUE TITLE
jk scrolling does not work for a particular site

### ISSUE THREAD

**Issue by meshde** [qutebrowser/qutebrowser#4744]
**Version info (see `:version`)**: 
https://paste.the-compiler.org/view/34c0947e

**Does the bug happen if you start with `--temp-basedir`?**: 
Yes

**Description**
Scrolling with`jk` does not work on https://dev.botframework.com/
 
**How to reproduce**

Open qutebrowser and visit https://dev.botframework.com/

**Comment by jgkamat** [comment]
#4715 fixes this for :scroll-page/px, don't think we can easily fix this for
the default scrolling

**Comment by The-Compiler** [comment]
Works fine after clicking the page to focus the correct element - same with keyboard scrolling in Chromium and Firefox, so this is the page's fault.

**Comment by Warkst** [comment]
Sorry to comment on this after it has been closed, but I felt it was so small and relevant to this thread that it didn't merit creating a separate issue, so here goes: is there a way to reset the focus using keystrokes?

**Comment by toofar** [comment]
If by reset the focus you mean clear focus from a input box you can [bind some keys to blur](https://github.com/qutebrowser/qutebrowser/issues/2668#issuecomment-310517541) if you mean to focus different parts of the page there is [a PR in the works](https://github.com/qutebrowser/qutebrowser/pull/4715).

**Comment by Warkst** [comment]
I meant focus different parts of the page, and I understand from your reply this is not yet possible but probably will be in the near future. Thanks!
