### ISSUE TITLE
Direct or indirect Jack 2 support

### ISSUE THREAD

**Issue by bearcatsandor** [qutebrowser/qutebrowser#4748]
The only thing that keeps my Firefox open is access to jack.  Since qutebrowser uses gstreamer, and I have jack set as my default audio sink, why doesn't qutebrowser utilize it?

What would it take to get qutebrowser using jack directly or through gstreamer?

**Comment by The-Compiler** [comment]
This is entirely implemented by the backend (QtWebEngine/Chromium or QtWebKit). FWIW with QtWebEngine I don't think it uses GStreamer at all.

**Comment by The-Compiler** [comment]
FWIW according to [this Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=42458), adding JACK support isn't planned, but using `pulse-jack` via Pulseaudio should work.
