### ISSUE TITLE
Mac fullscreen is not full

### ISSUE THREAD

**Issue by kklot** [qutebrowser/qutebrowser#4749]
**Version info (see `:version`)**:
1.6.1
**Does the bug happen if you start with `--temp-basedir`?**:
?
**Description**
Maximize window leaves a blank space where the title bar was.
**How to reproduce**
Set the OSX menu bar to auto hide and show, then maximize the browser.

**Comment by jgkamat** [comment]
Kinh Nguyen writes:

> **Does the bug happen if you start with `--temp-basedir`?**:
> ?

If you pass the --temp-basedir argument to qutebrowser can you still
reproduce?

> **Description**
> Maximize window leaves a blank space where the title bar was.

Can you reproduce with kde falkon as well?

**Comment by kklot** [comment]
Yes it happens with 

`/Applications/qutebrowser.app/Contents/MacOS/qutebrowser --temp-basedir`

But if we openned already one instant (click the icon), then run 

```
/Applications/qutebrowser.app/Contents/MacOS/qutebrowser
18:19:40 INFO: Opening in existing instance
```
maximize, then the browser has the full screen.

Sorry I don't know about `kde falkon`

**Comment by The-Compiler** [comment]
@kklot Is this something you still see with up-to-date Qt/qutebrowser versions?

**Comment by kklot** [comment]
no, it works great with v1.12.0. thanks.

**Comment by The-Compiler** [comment]
Closing this then!
