### ISSUE TITLE
how to set editor.command on Windows 10 to prevent :The process failed to start

### ISSUE THREAD

**Issue by CubicHarmony** [qutebrowser/qutebrowser#4754]
Hello-
So I'm not sure if this is an issue or my own ignorance about how to use qutebrowser, but I'm having trouble with using Ctrl + E in insert mode, i.e (I think) opening gvim to edit the text box that's selected.
My editor.command is currently set to
`'["gvim", "-f", "{file}", "-c", "normal {line}G{column0}l"]'`
I don't know what's the path variable or something by that name is for gvim, but what I do know is that when I type `gvim` in cmd (I'm using Windows 10), that gvim opens. I'd expect that something similar would happen with Ctrl + E, but all I'm getting is
`message:error:58 Error while spawning editor: The process failed to start.`
Again, not sure if issue or if I'm just a newbie who's putting in the wrong path variable or arguments, but any help would be appreciated.

**Comment by bitraid** [comment]
It seems that you had selected the "Create .bat files" option when you installed gvim. You can confirm this by running `where gvim` in cmd, and getting `C:\Windows\gvim.bat`. This allows gvim to be started from command line but it doesn't add the executable to the system's `PATH` variable (so it could easily be called from other programs).
If this is the case, then you should: 
 - either update the `PATH` variable:
Run `SystemPropertiesAdvanced.exe`, click `Environment Variables...` , double click the `Path` item of the `System variables` list, click `Browse..`, find and select gvim's program directory. Click `OK` on everything and restart qutebrowser.
- or change the command to contain the full path to gvim, for example: `'["C:\\Program Files\\Vim\\vim81\\gvim", "-f", "{file}", "-c", "normal {line}G{column0}l"]'`

**Comment by CubicHarmony** [comment]
Thank you! It appears that you were totally correct, and now my issue is fixed. Thanks again!
