### ISSUE TITLE
High cpu usage on pages with animated gifs

### ISSUE THREAD

**Issue by w7gqvo32ik3gnev3** [qutebrowser/qutebrowser#4757]
ok, first of all I do not mean to offend anybody, it's just an example:
https://files.catbox.moe/10viqo.png

--version : http://ix.io/1I6n
--temp-basedir : same thing 

I'm on a x220, is this expected behaviour on webengine ?

**Comment by The-Compiler** [comment]
Rendering is done by QtWebEngine, so there isn't really anything qutebrowser can do here.
