### ISSUE TITLE
[RFE] In-page search autocompletion

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#4758]
Problem: currently when one wants to highlight a word *(e.g. a variable in diff when doing code-review)*, one either needs to manually type a possibly quite long word, or copy-paste it with mouse which is time-consuming and conflicts with keyboard-only style that Qutebrowser promotes.

Solution: when searching for text inside page, matches are being highlighted as one types. It would be great if these matches + the text till word-boundary were popping up in autosuggestions.

**Comment by user202729** [comment]
You can copy-paste using caret mode.

**Comment by Hi-Angel** [comment]
> You can copy-paste using caret mode.

Then again, you need to place it first to a word location.

**Comment by jgkamat** [comment]
![image](https://i.imgur.com/cuP5jIN.gif)

**Comment by The-Compiler** [comment]
I don't think we need anything other than caret mode here.

**Comment by Hi-Angel** [comment]
> I don't think we need anything other than caret mode here.

Why? Isn't it a better user facing solution? Compared to autocompletion caret mode is clearly awkward: you have to quit search typing, then enter the mode, then start moving the caret; oh wait, here you realize that you want to add some more symbols to the search, so you need to start search again, and maybe enter the word or get the last search from the history…

Caret mode is clearly just a hack.

**Comment by jgkamat** [comment]
Konstantin Kharlamov writes:

> you have to quit search typing, then enter the mode, then start moving the
> caret; oh wait, here you realize that you want to add some more symbols to
> the search,

Can't you do this with 'w' or '$' in caret mode (to extend the selection)

> so you need to start search again,

why?

> and maybe enter the word or get the last search from the history…

Couldn't you just do this before entering caret mode? Assuming you are trying
to copy some text, if you change your mind about which text you want to copy
mid-operation, it makes sense to restart the operation, to me at least. I have
been using caret mode in qb daily for over a year now and I have never changed
my mind or needed to restart searching for what I wanted to copy.

> Caret mode is clearly just a hack.

Completions seem like a hack to me in this scenario. We would need to scan the
entire page's text and get it into python, and then filter it by the current
string. Completion and searching is already really slow, and I don't feel like
this would add any value for the extra computation required. I also have never
seen anything like this before, most likely because it would be very expensive
to implement. The only way I see this being feasible is if the completion was
just a dictionary (this is how libreoffice works, as far as I know) and not
the page text.

**Comment by Hi-Angel** [comment]
> Konstantin Kharlamov writes:
> you have to quit search typing, then enter the mode, then start moving the caret; oh wait, here you realize that you want to add some more symbols to the search,
> Can't you do this with 'w' or '$' in caret mode (to extend the selection)
>> so you need to start search again,
> why?
>> and maybe enter the word or get the last search from the history…
> Couldn't you just do this before entering caret mode? Assuming you are trying to copy some text, if you change your mind about which text you want to copy mid-operation, it makes sense to restart the operation, to me at least. I have been using caret mode in qb daily for over a year now and I have never changed my mind or needed to restart searching for what I wanted to copy.

I was imagining myself typing part of a word thinking it's unique, pressing enter, and finding that word isn't unique and caret is set to the wrong match. But I might be wrong. If you say you didn't have such problem, then maybe such situation indeed unlikely to happen. Probably I need to use that for a while and see how it goes.

>> Caret mode is clearly just a hack.
> Completions seem like a hack to me in this scenario. We would need to scan the entire page's text and get it into python, and then filter it by the current string. Completion and searching is already really slow, and I don't feel like this would add any value for the extra computation required. I also have never seen anything like this before, most likely because it would be very expensive to implement. The only way I see this being feasible is if the completion was just a dictionary (this is how libreoffice works, as far as I know) and not the page text.

Well, I was thinking that QtWebEngine already knows places with matches since it higlight ts them as you type. So one just needs to get locations of these matches, and extend to the word boundary.

**Comment by The-Compiler** [comment]
> Well, I was thinking that QtWebEngine already knows places with matches since it higlightts them as you type. So one just needs to get locations of these matches, and extend to the word boundary.

There isn't any API to get those locations (see [QTBUG-50420](https://bugreports.qt.io/browse/QTBUG-50420)) - and even if there was, that probably wouldn't allow to get the words/selection behind it easily.

**Comment by jgkamat** [comment]
Konstantin Kharlamov writes:

> Well, I was thinking that QtWebEngine already knows places with matches since it higlight ts them as you type. So one just needs to get locations of these matches, and extend to the word boundary.

Even if we lived in a perfect world where we could change everything, this is
still quite expensive. In this thread, which is comparatively tiny compared to
some web pages (before I post this) the letter 'a' gives 326 matches. For
every one of these matches we would need to search to the word boundary
character by character. This could be worked around by only starting after 'n'
characters, but this can still get very expensive on some pages (although, the
search itself will probably be more expensive for short matches).

However, we can't change any of that, the only api we get is
QWebEnginePage::findText. We don't even get an api for finding out how many
matches there are at the moment. We're also (for the most part) stuck in
python where normally cheap operations like 'scan to end of word' are very
expensive.

http://doc-snapshots.qt.io/qt5-5.12/qwebenginepage.html#findText

**Comment by user202729** [comment]
@jgkamat Even if it's expensive, if it's done in a smart way people won't notice it. (By doing it asynchronously, for example)

However, we actually can do it by getting the whole page's content and do the match in Python...

**Comment by user202729** [comment]
There are only 2 options: scrape the whole page and parse them in Python, or modify Qt. The second option will probably not be implemented. The first option is slower.

> Even if we lived in a perfect world where we could change everything, this is
still quite expensive.

1. Even if it's expensive, if it's done in a smart way people won't notice it. (By doing it asynchronously, for example)
2. It's just (asymptotically) as expensive as the search itself.
3. Vim [has the feature](https://stackoverflow.com/questions/8456813/vim-supertab-autocomplete-when-searching-with)...
