### ISSUE TITLE
qt5ct 0.38-1 -> 0.39-1 caused mouse wheel scrolling to move by very small steps

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4759]
**Version info (see `:version`)**: qutebrowser-git 1.6.0.r0.g32f8349fb-1

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

It suddenly started to take a huge number of mouse wheel spins to move pages up and down. Timing seems to coincide with qt5ct 0.38-1 -> 0.39-1, though I have no idea if it may be related.

I don't have any issue with my mouse wheel scrolling in other applications nor in Falkon.

**Comment by prosoitos** [comment]
Might be time to let go of the mouse altogether :P I know it isn't the qutebrowser spirit to rely on it...

**Comment by The-Compiler** [comment]
No idea what could be going on here I'm afraid. Can you try downgrading qt5ct (probably doing something like `pacman -U /var/cache/pacman/pkg/qt5ct-0.38-1-x86_64.pkg.tar.xz` if the package is still there) and see if that changes anything?

**Comment by prosoitos** [comment]
Yes, downgrading qt5ct fixed the problem.

**Comment by prosoitos** [comment]
Note that the scrolling does work. It just is that for each wheel rotation the page moves very little. So scrolling this way is impractical. I could adjust the options of my mouse but it would then move in jumps way too big in all other applications.

**Comment by The-Compiler** [comment]
Apparently someone [also saw issues](https://sourceforge.net/p/qt5ct/tickets/63/) and [there is a fix](https://sourceforge.net/p/qt5ct/code/531/) - can you try `qt5ct-svn` from the AUR maybe?

**Comment by The-Compiler** [comment]
Ah, wait, that issue was when upgrading from 0.37 to 0.38, and was fixed in 0.39...

**Comment by The-Compiler** [comment]
Hmm, could you show the output of `ls -R ~/.config/qutebrowser/qsettings/` please, and the content of anything that sounds qt5ct-specific?

**Comment by prosoitos** [comment]
> Apparently someone also saw issues and there is a fix - can you try qt5ct-svn from the AUR maybe?

Ya, my issue is different and is with 0.39.

> Hmm, could you show the output of ls -R ~/.config/qutebrowser/qsettings/ please, and the content of anything that sounds qt5ct-specific?

The output of `ls -R ~/.config/qutebrowser/qsettings/` is: `QtProject.conf`

But weirdly, I have 2 QtProject.conf... I am not sure that is normal:

- $HOME/.config/QtProject.conf with an mtime of May 3
- $HOME/.config/qutebrowser/qsettings/QtProject.conf with an mtime of March 16

Here is the one in .config:

```
[FileDialog]
history=file:///, file:///home/marie, file:///home/marie/.config/tox, file:///home/marie/parvus/mydoc/dl, file:///home/marie/parvus
lastVisited=file:///
qtVersion=5.12.3
shortcuts=file:///, file:///home/marie, file:///home/marie/parvus, file:///home/marie/parvus/mydoc, file:///home/marie/parvus/writing, file:///home/marie/parvus/mydoc/dl, file:///home/marie/parvus/mydoc/image, file:///home/marie/parvus/mydoc/image/avatar, file:///home/marie/parvus/mydoc/image/icon, file:///home/marie/parvus/mydoc/image/pic, file:///home/marie/parvus/mydoc/image/id, file:///home/marie/parvus/mydoc/image/desktop, file:///home/marie/parvus/mydoc/image/comic
sidebarWidth=162
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail

[Qt]
filedialog=@ByteArray(\0\0\0\xbe\0\0\0\x4\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0'file:///home/marie/parvus/coding/r/test\xff\xff\xff\xff\0\0\0\0)
```
and the one in .config/qutebrowser/qsettings:

```
[FileDialog]
history=file:///home/marie/parvus/prog/doc/contribution/autokey/lib, file:///home/marie/parvus/Dropbox/Public, file:///home/marie/parvus/mydoc/agenda, file:///home/marie/parvus/mydoc/image/avatar, file:///home/marie/parvus/mydoc/dl
lastVisited=file:///home/marie/parvus/mydoc/dl
qtVersion=5.12.1
shortcuts=file:, file:///home/marie, file:///home/marie/parvus, file:///media, file:///home/marie/parvus/mydoc, file:///home/marie/parvus/mydoc/agenda, file:///home/marie/parvus/prog, file:///home/marie/parvus/mydoc/dl, file:///home/marie/parvus/mydoc/image, file:///home/marie/parvus/mydoc/image/comic, file:///home/marie/parvus/mydoc/image/desktop, file:///home/marie/parvus/mydoc/image/id, file:///home/marie/parvus/mydoc/image/pic, file:///home/marie/parvus/mydoc/image/icon, file:///home/marie/parvus/mydoc/image/avatar
sidebarWidth=198
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2$\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x81\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
```

**Comment by prosoitos** [comment]
I have this environment variable in my .xinitrc file:

`export QT_QPA_PLATFORMTHEME="qt5ct"`

**Comment by prosoitos** [comment]
Still struggling with this issue. On "normal" pages, I can scroll with the keyboard, so it does not matter. But, am I missing something, or is keyboard scrolling not working on pdf open in pdfjs and on websites built with bookdown such as this one for instance: https://geocompr.robinlovelace.net/intro.html?

**Comment by prosoitos** [comment]
(I am not any more able to scroll on the bookdown websites with `qutebrowser --temp-basedir`).

**Comment by prosoitos** [comment]
Actually, I think that the problem on those websites is that the focus is not on the main window by default: clicking on the page allows keyboard scrolling. But that has to be done on each new page, so the mouse is very necessary while navigating such sites (which then makes keyboard scrolling not very natural).

**Comment by jgkamat** [comment]
Marie-Helene Burle writes:

> Actually, I think that the problem on those websites is that the focus is
> not on the main window by default: clicking on the page allows keyboard
> scrolling. But that has to be done on each new page, so the mouse is very
> necessary while navigating such sites (which then makes keyboard scrolling
> not very natural).

This is fixed by #4715 (I checked on the linked site) with scroll-page/px,
both in that it selects the larger pane automatically and you can select the
smaller pane with ;s.

Mouse scrolling shouldn't be broken though either.

**Comment by prosoitos** [comment]
Ah, great! Thank you for this @jgkamat :slightly_smiling_face: That will already make things A LOT nicer!!

**Comment by prosoitos** [comment]
On those websites created by bookdown (e.g. https://geocompr.robinlovelace.net/read-write.html), `scroll up/page-up/etc.` do work, but `scroll-to-perc` and `scroll-page` don't (even after manually selecting the larger pane).

**Comment by jgkamat** [comment]
Marie-Helene Burle writes:

> On those websites created by bookdown (e.g. 
> https://geocompr.robinlovelace.net/read-write.html), `scroll 
> up/page-up/etc.` do work, but `scroll-to-perc` and `scroll-page` don't (even 
> after manually selecting the larger pane).

This is also fixed by #4715 (both automatically selecting the right pane and 
scrolling both left/right pane).

**Comment by prosoitos** [comment]
Wonderful! Thank you @jgkamat. I look forward to trying it out!

**Comment by prosoitos** [comment]
I finally found the problem here. I am not sure why I seem to be the only one affected though.

I realized that it is actually not just qutebrowser, but all my programs relying on qt5 that are affected. And running `qt5ct -h` opens a GUI to set various things, including the number of mouse wheel scroll lines. Bumping that up fixes this in qutebrowser and all the other qt5 dependant programs... It was as simple as that.

I am not sure why I got affected by the update. Maybe it reset the value to 1 from some other value? (I never set any value myself though).

In any event, this had nothing to do with qutebrowser (sorry for the noise...) and I now found a fix. So I will close this issue.

**Comment by The-Compiler** [comment]
No worries, thanks for the follow-up!

**Comment by prosoitos** [comment]
Actually, since downgrading qt5ct was fixing the problem and re-upgrading creating it again, it probably was not a setting reset to the default. It more looks like a different default in qt5ct. But then, it is very weird that nobody else was affected.

Anyhow, the reason remains mysterious to me, but at least, I finally got this inconvenience out of the way :slightly_smiling_face:
