### ISSUE TITLE
[Bug] Segfaults occur at random due to PulseAudio

### ISSUE THREAD

**Issue by jcjordyn130** [qutebrowser/qutebrowser#4760]
**Version info (see `:version`)**:
```
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.6.8
Qt: 5.12.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.0.2r  26 Feb 2019

Style: QGtkStyle
Platform: Linux-5.0.7-114.current-x86_64-with-glibc2.3.4, 64bit
Linux distribution: Solus 4.0 Fortitude (unknown)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5
OS Version: 

--- /etc/os-release ---
NAME="Solus"
VERSION="4.0"
ID="solus"
VERSION_CODENAME=fortitude
VERSION_ID="4.0"
PRETTY_NAME="Solus 4.0 Fortitude"

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Solus
DISTRIB_DESCRIPTION="Solus"
DISTRIB_RELEASE=4.0
DISTRIB_CODENAME=fortitude

--- /etc/solus-release ---
Solus 4.0

Paths:
cache: /home/jordyn/.cache/qutebrowser
config: /home/jordyn/.config/qutebrowser
data: /home/jordyn/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 0:00.0
```

**Does the bug happen if you start with `--temp-basedir`?**:
It does.

**Description**
Qutebrowser will randomly segfault for an unknown reason.
GDB Stacktrace: 
[gdb.txt](https://github.com/qutebrowser/qutebrowser/files/3148887/gdb.txt)
Debug Log: 
[qutebrowser.txt](https://github.com/qutebrowser/qutebrowser/files/3148890/qutebrowser.txt)

**How to reproduce**
It happens on a lot of sites, but the main one I tested with was www.quora.com.
You just go to a site and scroll for a while and it'll segfault.

**Comment by The-Compiler** [comment]
Can you please show the full version info?

**Comment by jcjordyn130** [comment]
From looking at the traceback I can see that it crashes whenever there is no default device available and it tries to get the default devices' ID.  This bug is also reproducible in Google Chrome.

**Comment by The-Compiler** [comment]
Nothing that qutebrowser could fix then - this needs to be fixed in either Chrome or Pulseaudio.
