### ISSUE TITLE
importer.py output different to the format of urls file

### ISSUE THREAD

**Issue by guillermogf** [qutebrowser/qutebrowser#4762]
I'm quite new to qutebrowser, so this might very well be just that I haven't got the hang of bookmarks yet.

As far as I know, bookmarks are stored in the .config/qutebrowser/bookmarks/urls file with one bookmark per line and the url first followed by the name of the bookmark. However, importer.py gives the bookmarks with the inverse order, i.e., name of the bookmark followed by the url, which makes it more difficult to import bookmarks as you have to process the output.

Am I missing something? BTW, I'm using v 1.6.1 installed from the Debian package for Testing and I've tried both the importer.py script installed in /usr/share/qutebrowser/scripts and downloading the script from GitHub.

**Comment by The-Compiler** [comment]
IIRC the script outputs them in the quickmarks format by default - see the `--help` output.

**Comment by guillermogf** [comment]
That was it! Thanks for the quick answer!
