### ISSUE TITLE
Export proxy information to userscripts

### ISSUE THREAD

**Issue by Tsutsukakushi** [qutebrowser/qutebrowser#4769]
There are times when userscripts need to make network requets, such as to retrieve csrf tokens to make posts etc.

It would be great if qutebrowser exported all of the proxy information to the userscripts so they could be used. Currently there is no way (that I know of) to make userscripts use same proxy as the browser itself.

Good names for the exported variables would be:

```
QUTE_PROXY_HOST
QUTE_PROXY_PORT
QUTE_PROXY_TYPE
QUTE_PROXY_USER
QUTE_PROXY_PASSWORD
```

**Comment by The-Compiler** [comment]
I added this to #937 - however, network requests from userscripts are still problematic anyways, since you don't get the cookies qutebrowser has. IMHO, a proper solution would be allowing to make requests from a proper extension API (#30).

**Comment by jgkamat** [comment]
Tsukiko Tsutsukakushi writes:

> It would be great if qutebrowser exported all of the proxy information to the userscripts so they could be used. Currently there is no way (that I know of) to make userscripts use same proxy as the browser itself.

Can't you just set the proxy information in an environment variable and use
the system proxy? Maybe something like:

export http_proxy=socks5://localhost:9150

>
> Good names for the exported variables would be:
>
> ```
> QUTE_PROXY_HOST
> QUTE_PROXY_PORT
> QUTE_PROXY_TYPE
> QUTE_PROXY_USER
> QUTE_PROXY_PASSWORD
> ```

I don't think we should expose even more things to userscripts, it's quite
bloated already. This information should be constant too (it's part of the
config), so why not read it from autoconfig.yml, or write it somewhere if you
use config.py, and read that in your userscript.

If you want something a little cleaner you could probably define a custom
command and read the values through the config api normally.

**Comment by Tsutsukakushi** [comment]
>Can't you just set the proxy information in an environment variable and use
the system proxy? Maybe something like:

This would be an issue if I want to change the proxy from inside qutebrowser, that wouldn't reflect on the userscripts.

>so why not read it from autoconfig.yml, or write it somewhere if you
use config.py, and read that in your userscript.

This would not reflect on runtime change of the config.

>however, network requests from userscripts are still problematic anyways

Sometimes they are just required. There is no way around that.

>since you don't get the cookies qutebrowser has

Surely those could be exposed via a tmp file like the webpage itself is?

>I don't think we should expose even more things to userscripts

Userscripts are pretty much the best thing about qutebrowser. Artificially limiting their usefulness just because exporting couple variables is "bloated" is fucking retarded.

**Comment by The-Compiler** [comment]
> Surely those could be exposed via a tmp file like the webpage itself is?

No, because qutebrowser doesn't handle cookies itself, and can't access them easily - you could probably read them from QtWebEngine/Chromium's sqlite database, but why not have a proper solution instead of a pile of hacks...

> Sometimes they are just required. There is no way around that.

Sometimes a proper extension API is a better idea than shoehorning everything into userscripts :wink:

> Userscripts are pretty much the best thing about qutebrowser. Artificially limiting their usefulness just because exporting couple variables is "bloated" is fucking retarded.

Yeah, I'm sure this is the right way to get people to implement things you want... Not.

**Comment by jgkamat** [comment]
Not really eager to continue this anymore but:

Tsukiko Tsutsukakushi writes:
>>so why not read it from autoconfig.yml, or write it somewhere if you
> use config.py, and read that in your userscript.
>
> This would not reflect on runtime change of the config.

For autoconfig.yml, why wouldn't it? Get your userscript to run :save if you
really need it synced immediately.
