### ISSUE TITLE
Bump up maximum line length

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4770]
I'd like to avoid [bikeshedding](https://shed.bike/) too much over this, but I'd still like some other opinions!

I think the [PEP 8 line length limit](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) of 79 chars is a bit too extreme - especially with type annotations (#1456) it's getting pretty tight. So why not bump it up a bit? There's various values which I think make sense:

- 88 chars, because [the black formatter uses that](https://github.com/python/black#line-length)
- 100, because it's a nice round number :wink:
- 115 or so is the maximum I'm willing to go - that means I can still display two files side-by-side on my screen, and GitHub still shows the files everywhere without scroll bars.

Any preferences, @toofar @jgkamat @user202729 @rcorre and other regular contributors? Otherwise I'll probably configure linters to allow 100 and then reformat things over time (e.g. when adding type annotations).

**Comment by user202729** [comment]
Not very related, but you can save a bunch of columns with `from typing import <stuff>` instead of using `import typing` then add `typing.` everywhere.

Compare:

```
import typing
[...]
    def __init__(self, *attributes: typing.Any,
                 converter: typing.Callable = None) -> None:
```

and

```
from typing import Any, Callable
[...]
    def __init__(self, *attributes: Any, converter: Callable = None) -> None:
```

Some of them may conflict with `collections.abc`. Actually they can be used as ABC as well, but pylint doesn't understand them.

**Comment by toofar** [comment]
Ohh, that's new and strange. Does this mean "don't break long lines until you approach 100 characters" or "if you can't get a long line to split elegantly in 80 characters feel free to leave to 100".

**Comment by The-Compiler** [comment]
> Not very related, but you can save a bunch of columns with `from typing import <stuff>` instead of using `import typing` then add `typing.` everywhere.

True. I usually don't like importing things from other modules like that - it makes it hard to see what's coming from the current module vs. what's defined somewhere else. But I guess for `typing` stuff it'd be okay.

> Ohh, that's new and strange. Does this mean "don't break long lines until you approach 100 characters" or "if you can't get a long line to split elegantly in 80 characters feel free to leave to 100".

The latter I guess. You can still break lines earlier where convenient (e.g. in tests, I sometimes have one line with fixtures and one line with parametrized arguments), but that's not really a change from before - it's just the hard limit that'd increase.

**Comment by jgkamat** [comment]
In my opinion, the longer the better. I view wrapping as something that should
be handled by editors and other source code viewers and not forced in the
file.

**Comment by user202729** [comment]
@jgkamat
1. Editors don't handle this very well (for example, GitHub diff view doesn't indent wrapped lines), and the wrapped code won't look very pretty either (not conform to PEP8 or something like that). *of course there are smarter code viewers, but they may not be very logical in bad cases*.
2. Using the same logic, you can use the editor to wrap the code.

**Comment by rcorre** [comment]
I'm fine bumping it as high as you like. I'm a fan of [go's mentality](https://github.com/golang/go/wiki/CodeReviewComments#line-length):

> In other words, break lines because of the semantics of what you're writing (as a general rule) and not because of the length of the line

This issue is much more important to me:

> I usually don't like importing things from other modules like that - it makes it hard to see what's coming from the current module vs. what's defined somewhere else

I could waste a lot more time trying to track down ambiguous imports than I would trying to parse long lines. If we decide to allow this for `typing`, I wouldn't want it to become a general trend.

**Comment by user202729** [comment]
@The-Compiler @rcorre Re ambiguous import:

I find the information whether something is imported or in the current module not very useful, as usually I'd want to see it's definition.

Also if it's imported, you can use `gd` in vim to go to it's import line.

And there's something that is just unnecessary long - `tabbedbrowser.TabbedBrowser` for example.

-----

On an unrelated note, it's really hard to figure out what's the type of objects obtained from `objreg`.

**Comment by The-Compiler** [comment]
FYI, bumped the maximum line length for pylint up to 88 now, so that people can use black for new code if they want to. At some point I'll probably reformat all the existing code via black (after most PRs are in).

**Comment by The-Compiler** [comment]
I think this can be closed - I'm gradually rewrapping code as I'm doing related changes, and if we're going to rewrite everything, that'll likely be part of #1455.
