### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by zwykl3** [qutebrowser/qutebrowser#4771]
1. Keys
- How increase size text? little more, 110%, reset to default
 How setup minimal font size
- How jumping text like vi, half size up or down? ^D jump size not page 
- f show links, is possible to prevent using f for links?
for example on main page i use ff and jump to link. sometimes this is not good idea. (autorepeat)

2. Copy
- How copy the text. Normal text. I need select (mouse or V select line, acapit) and yanki
and put to terminal

3. Is possible using this browser in terminal?

**Comment by ninewise** [comment]
1. `+` for zoom, `=` for default. `ctrl-d` and `crtl-u` should work for scrolling half pages. You can set the used characters for hint with `:set hint.chars`.
2. You can select text with mouse, go to insert mode and `ctrl-v`. Alternatively, you can use caret mode (see docs).
3. You can control this browser from a terminal/script (`qutebrowser "open -t asdf"`), but it always opens in it's own window.

You might want to checkout the cheatsheet on the site, or surf to `qute://bindings` for more keybindings.

**Comment by The-Compiler** [comment]
> How setup minimal font size

You might want the `zoom.default` setting. I think @ninewise answered the rest already.

**Comment by zwykl3** [comment]
1. please dont use f as link
2. indest mode is not good idea on vi insert mode are not copy mode
3. I think qutebrowser-curses similar https://github.com/browsh-org/browsh but native
