### ISSUE TITLE
What hapenes when  f links are smales than f

### ISSUE THREAD

**Issue by zwykl3** [qutebrowser/qutebrowser#4772]
![Zrzut ekranu 2019-05-11 o 15 23 57](https://user-images.githubusercontent.com/50232890/57570357-384efa00-7401-11e9-903c-92e1ead582a3.png)
numbers are smalest than focus links and I cant read it.

P.S. How open link in a new tab in a background?

**Comment by The-Compiler** [comment]
There's no solution for that yet, see #71.

> P.S. How open link in a new tab in a background?

Using `;b`, or `<Ctrl-B>` while in hint mode.
