### ISSUE TITLE
Renderer process crashed

### ISSUE THREAD

**Issue by jandamm** [qutebrowser/qutebrowser#4777]
**Version info (see `:version`)**:
1.6.1-1.6.2

**Does the bug happen if you start with `--temp-basedir`?**:
I use a bundled app on a Mac.

**Description**
qutebrowser cannot render many websites.
When I open `https://start.duckduckgo.com/` I get the message `Unable to load page` `Error while opening https://start.duckduckgo.com/` `Renderer process crashed`.
Same error happens for our custom jira instance.

**How to reproduce**
For me installing 1.6.1 or 1.6.2 and opening duckduckgo is enough.
https://start.duckduckgo.com/
When I rollback to 1.6.0 it works just fine.

**Comment by The-Compiler** [comment]
It's some QtWebEngine bug - moving `/Users/USERNAME/Library/Caches/qutebrowser` away should help.

If you're comfortable with sharing your cache, please let me know via mail@qutebrowser.org - until someone does, I can't really do anything about this issue.

**Comment by YarekTyshchenko** [comment]
Right, just hit this in Jira, I can reproduce pretty reliably, what do I need to do to capture all the logging information?

**Comment by jandamm** [comment]
@YarekTyshchenko removing `~/Library/Caches/qutebrowser` did just work fine for me.
Have you tried it?

**Comment by YarekTyshchenko** [comment]
Happens when I go to "Link Issue" , then focus the issue search box, and type one or two characters. as soon as the spinner appears, Bam, crash.
```
12:54:15 DEBUG    js         shared:javascript_log_message:149 [https://jira-frontend-prod-eu-1.eu-west-1.prod.public.atl-paas.net/assets-brotli/commons.8b5812c8c7bbae3a2201.8.js:12] Non supported locale in tenant context: en_GB

<--- Last few GCs --->

[538:0x5655575e6b50]    96433 ms: Scavenge 144.2 (173.1) -> 137.9 (177.6) MB, 2.4 / 0.1 ms  idle task 
[538:0x5655575e6b50]    96982 ms: Scavenge 150.2 (178.6) -> 143.1 (184.6) MB, 2.7 / 0.1 ms  idle task 
[538:0x5655575e6b50]    97393 ms: Scavenge 157.0 (184.6) -> 143.5 (186.1) MB, 1.4 / 0.0 ms  allocation failure 
[538:0x5655575e6b50]   100855 ms: Scavenge 157.7 (187.6) -> 146.1 (188.6) MB, 1.3 / 0.1 ms  idle task 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xf27304a389 <String[33]: https://xxxxxxx.atlassian.net>
    4: new constructor(aka e) [https://jira-frontend-prod-eu-1.eu-west-1.prod.public.atl-paas.net/assets-brotli/async-issue-view~vendor.47f6accbcd8c0f49d112.8.js:44] [bytecode=0x3dbea5e7ea89 offset=197](this=0x36e40425a3f9 <e map = 0x3ac60ca39fc1>,t=65536)
    5: arguments adaptor frame: 0->1
    8: new constructor(aka e) [https://jira-frontend-prod-eu-1.eu-wes...

12:54:15 DEBUG    misc       app:on_focus_object_changed:488 Focus object changed: <qutebrowser.mainwindow.mainwindow.MainWindow>
12:54:15 DEBUG    misc       eventfilter:eventFilter:80 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7efb9c69b3a8>: removed child <PyQt5.QtCore.QObject object at 0x7efbe4509ca8>
12:54:15 DEBUG    misc       eventfilter:eventFilter:56 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7efb9c69b3a8> got new child <PyQt5.QtWidgets.QWidget object at 0x7efbe4509ca8>, installing filter
12:54:15 ERROR    webview    tabbedbrowser:show_error_page:937 Renderer process crashed
```

**Comment by YarekTyshchenko** [comment]
@jandamm This happens with `--temp-basedir`, so I assume clearing the cache would have no effect

**Comment by The-Compiler** [comment]
@YarekTyshchenko Can you please open a new issue and show your `:version` information there?

**Comment by YarekTyshchenko** [comment]
Opened #5270
