### ISSUE TITLE
Use typing.TYPE_CHECKING

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4778]
So far, we've avoided using `typing.TYPE_CHECKING` (and used a self-defined `MYPY = False; if MYPY:` instead).

This was because Ubuntu 16.04 [Python version](https://packages.ubuntu.com/xenial/python3) is 3.5.1. However, it looks like that's just the package version, and it actually ships 3.5.2 according to `python3 -V` - and that does have `typing.TYPE_CHECKING`...

So yeah, let's start using that, and adjust `checkpyver.py` to check for >= 3.5.2 instead of .0.

**Comment by mschilli87** [comment]
I can confirm that on my Ubuntu 16.04 machine:

```sh
apt-cache policy python3
```

```
python3:
  Installed: 3.5.1-3
  Candidate: 3.5.1-3
  Version table:
 *** 3.5.1-3 500
        500 http://de.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

```sh
which python3
```

```
/usr/bin/python3
```

```sh
dpkg -S $(which python3)

```

```
python3-minimal: /usr/bin/python3
```

```sh
apt-cache policy python3-minimal
```

```
python3-minimal:
  Installed: 3.5.1-3
  Candidate: 3.5.1-3
  Version table:
 *** 3.5.1-3 500
        500 http://de.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

```sh
python3
```

```
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

```python
>>> import typing
>>> typing.TYPE_CHECKING
```

```
False
```

```python
>>> typing.TYPE_CHECKING = True
>>> typing.TYPE_CHECKING
```

```
True
```

**Comment by The-Compiler** [comment]
On a second thought, I guess we could continue supporting older 3.5 versions anyways and just patch it in in `earlyinit.py` if it is missing.

**Comment by The-Compiler** [comment]
Also, while we're at it, we should check if we can get rid of the pylint disable now - I think with astroid 2.2.0 pylint should use typed_ast everywhere.

**Comment by user202729** [comment]
@The-Compiler Isn't it obvious that we can? Otherwise what's the point of `disable=useless-suppression`? I suppose that is so that pylint of both old and new version would not complain?

**Comment by The-Compiler** [comment]
@user202729 In general, qutebrowser only supports the versions noted in the requirements files (in other words, people should run via `tox`).

The problem with older astroid/pylint versions was, that it knew about type comments when running with Python 3.5/3.6, but not when running with 3.7 (because for a long time, `typed_ast` didn't support 3.7). That's why those comments are there - so it doesn't complain when e.g. I run it locally with 3.7, and also doesn't when running on Travis with 3.6.

With astroid 2.2.0, typed_ast is now used with Python 3.7 as well, which is why we should be able to get rid of those, and have it work with all Python versions.

**Comment by user202729** [comment]
By the way, because of some magic (https://github.com/PyCQA/pylint/blob/b4721fb339c4f4f0b4e39a9d0cb3223b523ac0b2/pylint/checkers/variables.py#L63) in Pylint code, there won't be any warning if we simply change the variable name from `MYPY` to `TYPE_CHECKING`. That way we don't have to mess with the `typing` built-in module.

**Comment by The-Compiler** [comment]
I'd still rather just use `typing.TYPE_CHECKING` instead of having `TYPE_CHECKING = False` everywhere.
