### ISSUE TITLE
Download prompts for YouTube videos

### ISSUE THREAD

**Issue by ebzzry** [qutebrowser/qutebrowser#4779]
Is it just me who sees download prompts when going to pages like [http://wiki.shoryuken.com/Skullgirls/Mechanics/Advanced_Mechanics](http://wiki.shoryuken.com/Skullgirls/Mechanics/Advanced_Mechanics). When I go that page, I get several popups asking me to download something.

**Comment by The-Compiler** [comment]
I can't reproduce. Does it happen with `--temp-basedir` as well? Can you show your version info (`:version`)?

**Comment by bitraid** [comment]
I can reproduce it. It seems that the page is embedding its youtube videos using the old (deprecated) Flash object, and qutebrowser prompts to downoad the `swf` file (flash player) of each video.

**Comment by ebzzry** [comment]
That’s interesting. Also, I can’t view the embedded videos. I can, however, with Firefox and Chrome.

Is there a way to make the notifications go away?

**Comment by The-Compiler** [comment]
I can't reproduce with JS turned on either. Still waiting for an answer to my questions above :wink:

**Comment by bitraid** [comment]
Actualy js doesn't have to be enabled. @The-Compiler what happens if you try open http://www.youtube.com/v/F86Q4juJgmc ?
The (old style) link is from the page:
```html
<object width="700" height="430"><param name="movie" value="http://www.youtube.com/v/F86Q4juJgmc"></param><embed src="http://www.youtube.com/v/F86Q4juJgmc" type="application/x-shockwave-flash" wmode="transparent" width="700" height="430"></embed></object>
```

**Comment by bitraid** [comment]
```
qutebrowser v1.6.2
Git commit: 197c0b1c2 (2019-05-06 19:36:52 +0200)
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.3
PyQt: 5.12.2

sip: 4.19.17
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.0.943 (bundled)
sqlite: 3.26.0
QtNetwork SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QWindowsVistaStyle
Platform: Windows-10-10.0.14393-SP0, 64bit
Frozen: True
Imported from C:\msys64\win64\qutebrowser\qutebrowser
Using Python from C:\msys64\win64\qutebrowser\qutebrowser.exe
Qt library executable path: C:/msys64/win64/qutebrowser/PyQt5/Qt/bin, data path: C:/msys64/win64/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.14393, SP0, Multiprocessor Free
```
I've also tried with latest master on archlinux with the same results.

**Comment by toofar** [comment]
I see it on v1.6.1 (dirty) Qt & PyQt 5.11.3, plugins turned off. Also with them turned on and I do apparently have a flash player (from 2011? I'm going to delete that now) but I doubt it is set up right.

**Comment by bitraid** [comment]
I looked it up alittle and and found out that chrome and firefox automatically rewrite the old youtube flash-embeds found in webpages:
https://news.slashdot.org/story/16/10/13/0510243/chrome-54-arrives-with-youtube-flash-embed-rewriting-to-html5
https://www.ghacks.net/2016/01/16/firefox-to-convert-old-youtube-flash-code-to-html5-video/

**Comment by ebzzry** [comment]
> I can't reproduce. Does it happen with `--temp-basedir` as well? Can you show your version info (`:version`)?

Yes, it still happens with `--temp-basedir`.

Here’s the version information: https://paste.the-compiler.org/view/a3a21f46

**Comment by The-Compiler** [comment]
No idea why it doesn't happen to me then... Can someone of you please reproduce it with `--temp-basedir` and then do `:report` so I can take a look at the logs?

**Comment by user202729** [comment]
I can reproduce the issue when I run `qutebrowser --temp-basedir z.html` with the html file contains

```
<object width="700" height="430"><param name="movie" value="http://www.youtube.com/v/F86Q4juJgmc"></param><embed src="http://www.youtube.com/v/F86Q4juJgmc" type="application/x-shockwave-flash" wmode="transparent" width="700" height="430"></embed></object>
```

@The-Compiler Do you see any error in the inspector? Can you see the video? (for example in the html file above)

**Comment by The-Compiler** [comment]
Ah, I can reproduce it when uninstalling `pepper-flash` (apparently disabling it isn't enough). Same happens in Qt's simplebrowser, so apparently a Qt bug?

**Comment by The-Compiler** [comment]
I opened [QTBUG-75807](https://bugreports.qt.io/browse/QTBUG-75807).

There isn't any way to ignore those downloads, but as a workaround, you can install pepper flash.

**Comment by bitraid** [comment]
@The-Compiler, that doesn't happen on every site with flash content though. Chrome used to have the same problem if flash was disabled from the advanced settings. Now it just converts the youtube flash-object embeds to iframes on the pages that still use them (so disabling flash doesn't matter).

**Comment by ebzzry** [comment]
> I opened [QTBUG-75807](https://bugreports.qt.io/browse/QTBUG-75807).
> 
> There isn't any way to ignore those downloads, but as a workaround, you can install pepper flash.

If pepper flash is not available on my system, are there other workarounds?

**Comment by The-Compiler** [comment]
@ebzzry I'm not aware of any. What system is that?

**Comment by bitraid** [comment]
@ebzzry You can use the [YouTube HTML5 everywhere](https://userscripts-mirror.org/scripts/show/116935) greasemonkey script. It doesn't works perfect, you still get one (1) download prompt, but then the page loads ok and you can also play the videos.

**Comment by ebzzry** [comment]
> @ebzzry I'm not aware of any. What system is that?

I’m using NixOS.

**Comment by ebzzry** [comment]
> @ebzzry You can use the [YouTube HTML5 everywhere](https://userscripts-mirror.org/scripts/show/116935) greasemonkey script (js must be enabled). It doesn't work perfect, you still get one (1) download prompt, but then the page loads ok and you can also play the videos.

Thanks! T
