### ISSUE TITLE
shift-O

### ISSUE THREAD

**Issue by bialy10Ok** [qutebrowser/qutebrowser#4784]
When I open web page url I have trouble with chose good adress.
Is possible add home, end keys for chose url?

second trouble, is possible show /add/delete bookmark web page on top of web page?
similar star, bookmark icon in firefox

or add

**Comment by The-Compiler** [comment]
> When I open web page url I have trouble with chose good adress. Is possible add home, end keys for chose url?

Do you mean in the completion list? What would they do?

> second trouble, is possible show /add/delete bookmark web page on top of web page?

See #3398

> or add

Huh?

**Comment by user202729** [comment]
PageUp/PageDown in completion list is implemented in PR 4301. Currently Home/End are not supported, but pressing Shift+Tab or Up at the beginning of the list moves to the end.
