### ISSUE TITLE
HiDPI scaling and envvars

### ISSUE THREAD

**Issue by lovesegfault** [qutebrowser/qutebrowser#4786]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/366b2957
**Does the bug happen if you start with `--temp-basedir`?**:
Yes.
**Description**
For Qt applications, the recommended method for managing HiDPI settings is thorough environment variables. Namely, the following are useful:

* `QT_SCREEN_SCALE_FACTORS`
* `QT_AUTO_SCREEN_SCALE_FACTOR`
* `QT_FONT_DPI`
* `QT_SCALE_FACTOR`

I have `QT_AUTO_SCREEN_SCALE_FACTOR=1`, which in theory should automagically handle the scaling for me. While this works fine on, say, Virtualbox on qutebrowser it does not. What I mean by that is the UI as a whole seems unaffected by this. 

Attempting to manually set the scaling factor causes qutebrowser to fail to launch, as such:
```
~ [I] ➜ QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser
00:52:31 WARNING: Error while loading geometry.
Gdk-Message: 00:52:31.184: python3.6: Fatal IO error 2 (No such file or directory) on X server :0.
```

Also, manually setting `QT_SCREEN_SCALE_FACTOR=2` with `QT_AUTO_SCREEN_SCALE_FACTOR=0` makes no difference, which suggests that screen scaling is somehow being ignored?

**How to reproduce**
See tiny UI.
![image](https://user-images.githubusercontent.com/7243783/57759281-7de41f00-76ae-11e9-9493-29e4c4b536e9.png)

My `.Xresources`
```
Xft.dpi: 200
Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb
rofi.dpi: 200
```

**Comment by The-Compiler** [comment]
Does starting with `--temp-basedir -s qt.highdpi true` change anything?

FWIW launching `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser --temp-basedir` works fine for me, and scales like expected. Can you check how things look with [Falkon](https://www.falkon.org/) please?

`QT_SCREEN_SCALE_FACTOR` doesn't exist. You probably mean `QT_SCREEN_SCALE_FACTORS` (plural) which takes a list of factors (one per screen). See the [Qt HighDPI docs](https://doc.qt.io/qt-5/highdpi.html).

**Comment by The-Compiler** [comment]
Wait, looking at your screenshot, the website is actually scaled up, right? Could you show a screenshot without scaling as well?

**Comment by lovesegfault** [comment]
Falkon looks fine (no envvars apart from `QT_AUTO_SCREEN_SCALE_FACTOR=1`)
![image](https://user-images.githubusercontent.com/7243783/57765390-319edc00-76ba-11e9-9532-2f328ec7e472.png)

**Comment by lovesegfault** [comment]
`QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser --temp-basedir`
![image](https://user-images.githubusercontent.com/7243783/57765467-6317a780-76ba-11e9-816c-450d2c329581.png)

**Comment by lovesegfault** [comment]
`QT_AUTO_SCREEN_SCALE_FACTOR=1 qutebrowser --temp-basedir`
![image](https://user-images.githubusercontent.com/7243783/57765570-8e01fb80-76ba-11e9-82a6-82680ff072fe.png)
Doesn't scale (`-s qt.highdpi true` makes no difference)

**Comment by The-Compiler** [comment]
Huh, so with `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser --temp-basedir`  you get the expected scaling, but without the `--temp-basedir` you get `Gdk-Message: 00:52:31.184: python3.6: Fatal IO error 2 (No such file or directory) on X server :0.`, right?

No idea what's going on there. Can you try moving `~/.config/qutebrowser` away and see if that makes it work?

**Comment by lovesegfault** [comment]
>  but without the --temp-basedir you get `Gdk-Message: 00:52:31.184: python3.6: Fatal IO error 2 (No such file or directory) on X server :0.`, right?

Correct:

```
QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser
02:41:00 WARNING: Error while loading geometry.
Gdk-Message: 02:41:00.756: python3.6: Fatal IO error 2 (No such file or directory) on X server :0.
```

> Can you try moving `~/.config/qutebrowser` away and see if that makes it work?

Let's see :)

**Comment by lovesegfault** [comment]
After moving the config away `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser` launches fine, alas with borked fonts.

**Comment by toofar** [comment]
Since `Error while loading geometry` is logged right before it, maybe there  is an issue with loading an old stored geometry whith the scaling factor had changed?

**Comment by lovesegfault** [comment]
Note that it doesn't, however, change the status of which envvar combinations work for scaling. Only `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser` scaled the UI correctly.

**Comment by lovesegfault** [comment]
Apparently the error is caused by setting `qt.highdpi` to true. It needs to be off otherwise we get that weird `Gdk-Message: 02:41:00.756: python3.6: Fatal IO error 2 (No such file or directory) on X server :0.`

**Comment by The-Compiler** [comment]
Setting `qt.highdpi` to true just sets `QT_AUTO_SCREEN_SCALE_FACTOR=1` internally, so that'd be the opposite of the environment variables causing the same crash above?!

I'm quite confused at this point, and that X error is coming from Qt itself, not qutebrowser.

As for the borked fonts: Setting `fonts.monospace` to remove Terminus should help, apparently Terminus is pretty bad at HighDPI stuff.

**Comment by lovesegfault** [comment]
I worked around this by:
1. Setting my fonts to something better
2. Disabling qt.highdpi
3. Patching `Exec` lines in `qutebrowser.desktop` to look like such: `Exec=env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 qutebrowser`
4. Nuking `$HOME/.cache/qutebrowser`

After those steps it both works and seems to scale properly.

I think a lot of the weirdness came from the geometry cache being invalidated when the DPI settings change.

**Comment by steils** [comment]
Just for the record. I am having the same issue. Using the same workaround. Additionally I have to set all the UI font sizes to 5pt, because they seem to be scaled twice (even with `qt.highdpi=false`, `QT_AUTO_SCREEN_SCALE_FACTOR=0` and `.cache/qutebrowser` cleaned).
qutebrowser 1.7.0, Qt 5.12.5, PyQt 5.13.1, Python 3.6.9.

**Comment by steils** [comment]
(same with qutebrowser 1.8.0)

**Comment by rien333** [comment]
For anyone experiencing HiDPI scaling issues: [Qt 5.14](https://wiki.qt.io/New_Features_in_Qt_5.14) saw some HiDPI improvements, and seemingly also some new env variables.

**Comment by steils** [comment]
> For anyone experiencing HiDPI scaling issues: [Qt 5.14](https://wiki.qt.io/New_Features_in_Qt_5.14) saw some HiDPI improvements, and seemingly also some new env variables.

+1. Everything is all right for me now with QT_AUTO_SCREEN_SCALE_FACTOR=1 or qt.highdpi=true.
qutebrowser v1.8.3, Qt: 5.14.0, PyQt: 5.14.0.

**Comment by a-m-joseph** [comment]
> For anyone experiencing HiDPI scaling issues: [Qt 5.14](https://wiki.qt.io/New_Features_in_Qt_5.14) saw some HiDPI improvements, and seemingly also some new env variables.

Here's an explanation I wrote: https://github.com/qutebrowser/qutebrowser/issues/5211#issuecomment-583682944

It's still really confusing and a big mess, but at least in Qt 5.14 the confusing mess actually works.

**Comment by The-Compiler** [comment]
Closing this as I don't think there's anything qutebrowser can do here.
