### ISSUE TITLE
Font rendering issue in Twitter

### ISSUE THREAD

**Issue by mysteryjeans** [qutebrowser/qutebrowser#4787]
**Version info (see `:version`)**: v1.6.2

**Does the bug happen if you start with `--temp-basedir`?**: Yes

Please see attached screenshots, there is a difference for rendering Urdu font "Noto Naskh Arabic UI" as compare to Chromium on Arch Linux LTS kernel.

![Chromium-2019-05-15-232600_856x352_scrot](https://user-images.githubusercontent.com/1826883/57802265-02967200-776f-11e9-9b8b-12c625539a50.png)
![qutebrowser-2019-05-15-233644_859x366_scrot](https://user-images.githubusercontent.com/1826883/57802307-1215bb00-776f-11e9-87b2-5f9b29d55889.png)

Arch doesn't render Urdu font fine unless I have set default font for Urdu lang with this font config: 
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="pattern">
        <test name="lang" compare="contains">
            <string>ur</string>
        </test>
        <test qual="any" name="family">
            <string>sans-serif</string>
        </test>
        <edit name="family" mode="prepend" binding="strong">
            <string>Noto Naskh Arabic UI</string>
        </edit>
    </match>
    <match target="pattern">
        <test name="lang" compare="contains">
            <string>ur</string>
        </test>
        <test qual="any" name="family">
            <string>serif</string>
        </test>
        <edit name="family" mode="prepend" binding="strong">
            <string>Noto Naskh Arabic UI</string>
        </edit>
    </match>
</fontconfig>
```
This makes both qutebrowser and chromium to render Urdu lang in twitter, however twitter's only specify lang="ur" and leaves browser to fall back via "sans-serif". 

**How to reproduce**
First need to create font config `/etc/fonts/conf.d/90-noto-urdu.conf` given Noto is already instead than navigate to this [tweet](https://twitter.com/zartajgulwazir/status/1128725369178161153).

**Comment by The-Compiler** [comment]
How does it look in KDE Falkon (available via the `falkon` package)?

**Comment by mysteryjeans** [comment]
Issue is appearing in Falkon browser as well, tested on both i3wm & KDE.

**Comment by The-Compiler** [comment]
This is a Qt issue then - my guess is that the font rendering improved compared to the slightly older Chromium version in QtWebEngine. Unfortunately I can't test it, as the rendering is even more broken here I think (but looks fine in Chromium):

![image](https://user-images.githubusercontent.com/625793/57808847-91ea5800-7764-11e9-9ecf-c6321cc10689.png)

You could try Qt 5.13 in the [KDE-Unstable](https://wiki.archlinux.org/index.php/Official_repositories#kde-unstable) repository to find out if that improves things - but unfortunately, it's a bit of a bumpy road (you probably need to rebuild pyqt5 and things like qt5-styleplugins for qutebrowser to work again).

If it does work there, there's not much you can do other than wait - but Qt 5.13 should be out in a couple of weeks!

If it does not work there, please [open a Qt bug](https://bugreports.qt.io/secure/Dashboard.jspa) about it (with project Qt, component WebEngine).

**Comment by mysteryjeans** [comment]
I should wait then and keep an eye for Qt 5.13. 

If it wasn't for qutebrowser; I would be using firefox. So thank you a lot
