### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by ebzzry** [qutebrowser/qutebrowser#4789]
Why do I get that message when I visit the site [https://www.quicklisp.org/beta/releases.html](https://www.quicklisp.org/beta/releases.html)?

**Comment by The-Compiler** [comment]
The server [sends an incomplete certificate chain](https://www.ssllabs.com/ssltest/analyze.html?d=www.quicklisp.org).

This might or might not work depending on the tools used (e.g. wget doesn't work for me either) and whether the certificate is already cached somewhere. Either way, it's something they need to fix server-side. I opened https://github.com/quicklisp/quicklisp-projects/issues/1681.

**Comment by ebzzry** [comment]
Yes, [indeed](https://www.sslshopper.com/ssl-checker.html#hostname=quicklisp.org).
