### ISSUE TITLE
 Why my browser not identyfy as qutebrowser?

### ISSUE THREAD

**Issue by bialy10Ok** [qutebrowser/qutebrowser#4790]
?

How disable 3-th part cookies

**Comment by jgkamat** [comment]
bialy10Ok writes:

> Why my browser not identyfy as qutebrowser?

What?

> How disable 3-th part cookies

content.cookies.accept might be the setting you're looking for, or content.cookies.store.

**Comment by mschilli87** [comment]
@jgkamat:
> @bialy10Ok writes:
>> Why my browser not identyfy as qutebrowser?
> What?

My best guess is `content.headers.user_agent`.
