### ISSUE TITLE
Set color of intermediate screen shown while switching tabs or when a tab loads

### ISSUE THREAD

**Issue by Skyfold** [qutebrowser/qutebrowser#4791]
When you switch between tabs or when first loading a tab the screen displays a white background for a milisecond. I assume this is because something needs to be displayed while the tab is being loaded. However, this means you get a bright flash of light when switching between tabs that are not white. For example, if you use "solarized-everything-css" to darken all websites then that white light before a tab load is hard on your eyes. What I would like is a setting that lets me set the color of this intermediate screen.

If by chance there is a way to do this that I have not yet found, please enlighten me.

**Comment by The-Compiler** [comment]
There's the `colors.webpage.bg` setting, but IIRC a small white flash still remains - it's coming from Chromium, and so far nobody has found a way to make it go away I think.

**Comment by Aster89** [comment]
It seems that `colors.webpage.bg` solves the issue. I don't see any white flash. Maybe my eyes have a low frame rate, ahahah.
