### ISSUE TITLE
qutebrowser crashes when closing a tab with the webkit backend

### ISSUE THREAD

**Issue by ohch6Eho** [qutebrowser/qutebrowser#4796]
**Version info (see `:version`)**:
http://ix.io/1JGS
**Does the bug happen if you start with `--temp-basedir`?**:
yes
**Description**
Sometimes when I close a tab qutebrowser crashes.
**How to reproduce**
I don't know how to reproduce this because I can't pinpoint what might cause it. Sometimes I try repeating the conditions before the crash and nothing happens.
**gdb.txt**
http://ix.io/1JGT

I feel like this is not enough information. What more can I do ?

**Comment by ohch6Eho** [comment]
http://ix.io/1JHv

I managed to replicate the bug with the debug packages.

**Comment by ohch6Eho** [comment]
This bug appears when gstreamer is not fully installed( for example gst-plugins-base is installed as a dependency for another package). qutebrowser crashes that are related to sites that display media might be related to this. I solved it by installing gst-plugins-good, gst-plugins-bad, gst-plugins-ugly and gst-libav.

**Comment by The-Compiler** [comment]
Nothing qutebrowser can do here - this seems like a bug in GStreamer (or possibly QtWebKit) based on the stacktrace.

**Comment by buttjake** [comment]
This seems solved in alpha3.
