### ISSUE TITLE
Drop Python 3.5 support?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4800]
Splitting this off from #3839:

---

Random thought: Would this also allow us to drop Python 3.5 support without affecting anything other than Debian stable?

That'd be quite nice. Two things in [What's New in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html) are big:

- Support for [f-strings](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals)
- Support for [variable type annotations](https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations) (#1456)

---

Back then, @glatzor and @barthalion said that Python 3.5 is still required for Flatpak - I assume this has changed in the meantime?

As for f-strings, [pyupgrade](https://pypi.org/project/pyupgrade/) can be useful to rewrite existing code.

**Comment by barthalion** [comment]
Freedesktop SDK on top of which latest GNOME and KDE runtimes are built ships with python 3.7 so we're good on that front.

**Comment by The-Compiler** [comment]
Hmm, though Ubuntu 16.04 LTS / Linux Mint 18 (both supported until 2021) would be affected. They wouldn't be able to install qutebrowser via tox easily anymore, and would probably first need to get Python 3.6 via pyenv or so.

**Comment by ykgmfq** [comment]
Linux Mint comes with Flatpak installed and the Flathub repo pre-configured. It should be as easy as clicking *Install* [here](https://flathub.org/apps/details/org.qutebrowser.qutebrowser). Ubuntu users would need to install Flatpak from the official [PPA](https://flatpak.org/setup/Ubuntu/) and get qutebrowser via the command line.

**Comment by The-Compiler** [comment]
FWIW the [upstream EOL](https://devguide.python.org/#status-of-python-branches) for Python 3.5 is 2020-09-13.

**Comment by The-Compiler** [comment]
Another useful tool: [ilevkivskyi/com2ann: Tool for translation type comments to type annotations in Python](https://github.com/ilevkivskyi/com2ann)

**Comment by The-Compiler** [comment]
As another data point against keeping Ubuntu 16.04 support for much longer, see https://github.com/qutebrowser/qutebrowser/pull/5337/files/d684bd9240370dd92674fed98cbe786edf242634..955f9c4e93c6c9bac9a7511c3dbb5a8759898900 and the related discussions there around its sqlite-Version.

**Comment by The-Compiler** [comment]
Some TODOs for things which could probably be refactored with Python 3.6:

- `WebKitElements` and `WebEngineElements` probably don't need to override `__init__` anymore just so that mypy knows the type of `self._tab`.

**Comment by The-Compiler** [comment]
Python 3.5 is now dropped, so we can finally start using [variable annotations](https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations) and [f-strings](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals) :tada: :sparkles: 

Closing this, see #3020 for the remaining tidbits.

**Comment by The-Compiler** [comment]
FYI, I'm also dropping support for Python 3.6.0 due to various small issues - it's unlikely to be in use anywhere, and 3.6.1+ is still supported.
