### ISSUE TITLE
Switching tabs with `tabs.show` set to `switching` leaves white space on the right of the window

### ISSUE THREAD

**Issue by Radvendii** [qutebrowser/qutebrowser#4802]
**Version info (see `:version`)**:
v1.5.2
https://paste.the-compiler.org/view/6035c06f

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When I switch tabs, it quickly resizes the window smaller then larger as the tab bar takes up space. However, sometimes the window never resizes bigger again even though the tab bar goes away, leaving an unfilled white space on the right side of the window. If I switch to another tab and back a couple of times, that usually solves the problem.

**How to reproduce**

1. Set `tabs.show` to `switching`
2. Open multiple tabs
3. Switch back and forth until it happens

---

Issue #1593 would solve this problem, but this seems like an easier to solve problem which is actually a bug, as opposed to a feature request.

**Comment by The-Compiler** [comment]
v1.5.2 is quite old, you might want to upgrade! I can't reproduce any resizing issues, but I'm pretty sure those would be bugs in QtWebEngine and not qutebrowser - thus, I don't think there's anything other than #1593 that qutebrowser could do here.
