### ISSUE TITLE
Cannot download/save current page while offline

### ISSUE THREAD

**Issue by gulkily** [qutebrowser/qutebrowser#4803]
**Version info (see `:version`)**:
qutebrowser v1.5.1
Git commit: c7a21b37e-dirty (2018-10-10 08:23:17 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
A page that has been loaded cannot be saved if the connection goes away.
This works in other browsers, so I expected it to work in qb as well.

**How to reproduce**
1. Open a simple static HTML page. I tested it with http://hike.qdb.us/
2. Disconnect from network
3. Press g,d (or use :download)

Expected: Page is saved to disk as file. Prompt for filename if specified in settings.

Actual: "Download" fails.

**Comment by user202729** [comment]
Download as mhtml (with flag `-m`) works.

**Comment by The-Compiler** [comment]
This is because those are two different network stacks at the moment - see #2328.

**Comment by gulkily** [comment]
Thanks for telling me about -m.
