### ISSUE TITLE
Compose key not working in docs.google.com

### ISSUE THREAD

**Issue by Etn40ff** [qutebrowser/qutebrowser#4805]
**Version info**:
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.5
Qt: 5.11.3 (compiled 5.11.1)
PyQt: 5.10.1

sip: 4.19.13
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 5.1
cssutils: 1.0.1 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.25.3
QtNetwork SSL: OpenSSL 1.0.2q  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.14.83-gentoo-x86_64-Intel-R-_Core-TM-_i7-5600U_CPU_@_2.60GHz-with-gentoo-2.6, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib64/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3.6
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Compose key combinations (e.g Compose+`+e) do not work inside docs.google.com but work fine on other websites (here for example). They also work as expected in other browsers (chromium) on docs.google.com .

**Comment by The-Compiler** [comment]
Looks like a QtWebEngine bug - I opened an upstream issue: [[QTBUG-76041] Compose key does not work on Google Docs - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-76041?jql=text%20~%20%22compose%22%20and%20component%20%3D%20webengine)

**Comment by The-Compiler** [comment]
Looks like this is Google Docs' fault. I opened #4810 with this and other site-specific quirks. According to [[QTBUG-69652] Dead keys don't work on Google Docs - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-69652), you can change your user-agent to something which doesn't include `Chrome/...` to work around it.

**Comment by The-Compiler** [comment]
Looks like the site-specific quirk broke due to changes on Google's side. I haven't found a way to make it work again, unfortunately, so I removed the quirk.

**Comment by The-Compiler** [comment]
There's a new quirk in git master (and part of soon-to-be-released v2.2.2) which seems to work again.
