### ISSUE TITLE
Seperate color variables for selected completion match and unselected completion match

### ISSUE THREAD

**Issue by olav35** [qutebrowser/qutebrowser#4816]
There is a variable colors.completion.match.fg which i use to specify the color of the matched phrase in the completion view. This variable is used both in the selected and unselected alternatives. I think there should be two seperate options, one for the selected alternative and one for the unselected alternative that way it would be easier to maintain a contrast between the background of each alternative and the matched text.

I have two colors that i want to use in my colorscheme $foreground and $background. Everything which is unselected (unselected alternative and tabs for instance) should have $background as background and $foreground as foreground. Everything which is selected should have $foreground as background and $background as foreground. That way i can easily see what is selected and what is not.
If i set colors.completion.match.fg to $background it will have contrast with the background in seleced alternatives, but not in unselected alternatives and if i set it to $foreground it will be oposite.
![2019-05-29-100008_640x777_scrot](https://user-images.githubusercontent.com/24797093/58550543-3ca35180-820e-11e9-8eac-775102989340.png)
![2019-05-29-125043_640x777_scrot](https://user-images.githubusercontent.com/24797093/58551448-52197b00-8210-11e9-8b57-bc89de850e18.png)

For now i have to workaround this by choosing a color which contrasts both of the colors. 
![2019-05-29-124847_640x777_scrot](https://user-images.githubusercontent.com/24797093/58551305-fa7b0f80-820f-11e9-8ad1-7a2afe67ba20.png)

**Comment by The-Compiler** [comment]
Fixed via #4818 - thanks @olmokramer!

**Comment by olmokramer** [comment]
Oh hey I didn't even know this issue existed. And it is so recent as well. What a coincidence. You're welcome :)
