### ISSUE TITLE
Allow suspending a tab on command

### ISSUE THREAD

**Issue by Architector4** [qutebrowser/qutebrowser#4822]
With `session.lazy_restore` enabled, on restart all tabs are suspended with "qute://back/" prefix.
Would it make sense to add a "tab-suspend" command that does just that but for a single tab?
I personally would benefit from this by suspending a heavy on resources tab without actually closing it.

**Comment by arza-zara** [comment]
Yes, see issue #67 and PR #4037.

**Comment by toofar** [comment]
`:open about:blank` does almost the same as that PR in terms of unloading if you need something sooner ;)

**Comment by Architector4** [comment]
> Yes, see issue #67 and PR #4037.

Those don't seem to be what I'm thinking about. I'm looking for a way to suspend any tab at my own discrepancy by typing, for example, `:tab-suspend 5` to suspend the 5th tab as if I had just restarted the browser and opened every other tab except 5th.

**Comment by arza-zara** [comment]
> Those don't seem to be what I'm thinking about. I'm looking for a way to suspend any tab at my own discrepancy by typing, for example, `:tab-suspend 5` to suspend the 5th tab as if I had just restarted the browser and opened every other tab except 5th.

Sounds like `:tab-unload` in #4037.

**Comment by Architector4** [comment]
Oh. Yes, it does. But that patch is about reimplementing the entire suspend/discard system, and also just happens to bring the `:tab-unload` as added functionality ontop of that.
I'm requesting just the `:tab-unload` command that would work right now with the current `qute://back/` system used in the browser.

**Comment by The-Compiler** [comment]
I don't think it makes sense to implement this on top of the current tab unloading if there's a rewrite upcoming.
