### ISSUE TITLE
Cannot figure how to use user script

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#4823]
# Problem
I have tried out using user scripts, but in vain.

# What I've done
I followed the official description found here https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc

1. I wrote a bash script and put it in "~/.local/share/qutebrowser/userscripts/"
```
#!/bin/bash
echo "open -t http://www.dict.cc/?s=$QUTE_SELECTED_TEXT" >> "$QUTE_FIFO"
```
2. I have given the file the most freedom by chmod to 777.
3. In qutebrowser's command line prompt, I typed in
```
spawn thescript
```
and got an error, which asks me to see ```:message```
4. In ```:message```, I got
> 19:00:41 | ERROR | message | message:error:58 | Command exited with status 1, see :messages for details.

As another example, I have also tried
```
:spawn echo "a" >> ~/a.txt
:spawn bash echo "a" >> ~/a.txt
```
and got
> 19:02:35 | ERROR | message | message:error:58 | Command exited with status 126, see :messages for details.
> 19:02:35 | ERROR | procs | guiprocess:on_finished:127 | Process stderr: /usr/bin/echo: /usr/bin/echo: cannot execute binary file

Did I miss something?

**Comment by jgkamat** [comment]
jcguu95 writes:

> 1. I wrote a bash script and put it in 
> "~/.local/share/qutebrowser/userscripts/"
> ```
> #!/bin/bash
> echo "open -t http://www.dict.cc/?s=$QUTE_SELECTED_TEXT" >> "$QUTE_FIFO"
> ```
> 2. I have given the file the most freedom by chmod to 777.
> 3. In qutebrowser's command line prompt, I typed in
> ```
> spawn thescript
> ```
> and got an error, which asks me to see ```:message```
> 4. In ```:message```, I got
>>>> 19:00:41 | ERROR | message | message:error:58 | Command exited with 
>>>> status 1, see :messages for details.

Have you tried an absolute path? :messages debug might be interesting as well.

In this case, you might be able to just bind to this and avoid the userscript 
completely:

open -t http://www.dict.cc/?s={primary}

> As another example, I have also tried
> ```
> :spawn echo "a" >> ~/a.txt
> :spawn bash echo "a" >> ~/a.txt
> ```
> and got
>>>> 19:02:35 | ERROR | message | message:error:58 | Command exited with 
>>>> status 126, see :messages for details.
>>>> 19:02:35 | ERROR | procs | guiprocess:on_finished:127 | Process stderr: 
>>>> /usr/bin/echo: /usr/bin/echo: cannot execute binary file

This version works for me:

:spawn bash -c 'echo "a" >> ~/a.txt'

**Comment by The-Compiler** [comment]
Can you run `echo` in a normal bash shell?

**Comment by jcguu95** [comment]
> Can you run `echo` in a normal bash shell?
@The-Compiler Yes it does. Bash shell works perfectly on my laptop.

> :spawn bash -c 'echo "a" >> ~/a.txt'
@jgkamat This works for me too! Inspired by this, I have tried the variations. This time I do look into ":messages debug"; I missed this since this does not pop up in the qb prompt.

## Try and Errors
### 1
> :spawn test
> 
06:27:39 | DEBUG | message | message:_log_stack:41 | Stack for error message:   File "/usr/bin/qutebrowser", line 11, in <module>     load_entry_point('qutebrowser==1.6.2', 'gui_scripts', 'qutebrowser')()   File "/usr/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 194, in main     return app.run(args)   File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 144, in run     ret = qt_mainloop()   File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 154, in qt_mainloop     return q_app.exec_()   File "/usr/lib/python3.7/site-packages/qutebrowser/misc/guiprocess.py", line 122, in on_finished     "details.".format(self._what.capitalize(), code))   File "/usr/lib/python3.7/site-packages/qutebrowser/utils/message.py", line 53, in error     stack = ''.join(traceback.format_stack())
-- | -- | -- | -- | --
06:27:39 | ERROR | message | message:error:58 | Command exited with status 1, see :messages for details.

### 2
> :spawn /home/me/.local/share/qutebrowser/userscripts/test


06:28:43 | DEBUG | message | message:_log_stack:41 | Stack for error message:   File "/usr/bin/qutebrowser", line 11, in <module>     load_entry_point('qutebrowser==1.6.2', 'gui_scripts', 'qutebrowser')()   File "/usr/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 194, in main     return app.run(args)   File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 144, in run     ret = qt_mainloop()   File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 154, in qt_mainloop     return q_app.exec_()   File "/usr/lib/python3.7/site-packages/qutebrowser/misc/guiprocess.py", line 122, in on_finished     "details.".format(self._what.capitalize(), code))   File "/usr/lib/python3.7/site-packages/qutebrowser/utils/message.py", line 53, in error     stack = ''.join(traceback.format_stack())
-- | -- | -- | -- | --
06:28:43 | ERROR | message | message:error:58 | Command exited with status 1, see :messages for details.
06:28:43 | DEBUG | misc | mainwindow:_update_overlay_geometry:305 | new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7f52bc4bf5e8>: PyQt5.QtCore.QRect(0, 698, 1281, 85)
06:28:43 | ERROR | procs | guiprocess:on_finished:127 | Process stderr: /home/jin/.local/share/qutebrowser/userscripts/test: line 2: : No such file or directory
06:28:43 | DEBUG | modes | modeman:_handle_keyrelease:219 | filter: True

**Comment by The-Compiler** [comment]
> Process stderr: /home/jin/.local/share/qutebrowser/userscripts/test: line 2: : No such file or directory

That looks like an issue with your script. How does that `test` script look like?

**Comment by jcguu95** [comment]
Exactly looks like this (copied and pasted):
```
#!/bin/bash
echo "open -t http://www.dict.cc/?s=$QUTE_SELECTED_TEXT" >> "$QUTE_FIFO"
```

**Comment by The-Compiler** [comment]
- What happens if you run `/home/jin/.local/share/qutebrowser/userscripts/test` in a shell?
- What gets displayed if you do `echo $PATH` in a shell, vs. doing `:debug-pyeval os.environ['PATH']` inside qutebrowser?
- What does `python3 -c 'import subprocess; subprocess.run(["echo", "foo"])'` in a shell say?
- What about `:debug-pyeval __import__('shutil').which('echo')`?

**Comment by jcguu95** [comment]
```
$ /home/jin/.local/share/qutebrowser/userscripts/test
/home/jin/.local/share/qutebrowser/userscripts/test: line 2: : No such file or directory

$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/jin/.scripts/cron:/home/jin/.scripts/statusbar:/home/jin/.scripts/i3cmds:/home/jin/.scripts/tools:/home/jin/.scripts/:

$ python3 -c 'import subprocess; subprocess.run(["echo", "foo"])'
foo
```

And finally 
`debug-pyeval __import__('shutil').which('echo')` in the qb prompt generates a page that consists of
'/usr/bin/echo'

**Comment by The-Compiler** [comment]
Ah, right - you'll need to spawn it with `:spawn -u` (`--userscript`) for `$QUTE_FIFO` to be defined.

**Comment by jcguu95** [comment]
@The-Compiler Right! I did RTFM, but I thought "--userscript" is something to be replaced by my script.

Also, something is not quite right on my laptop: I edited my test script by taking the variables away, but without `-u` it still gets errors. I would say using `-u` is a better way in general if one wants to use userscripts, which should be put in ~/.local/share/qutebrowser/userscripts

Another nagging thing is that `:spawn bash echo "a" >> ~/a.txt` does not work.. Though we already have another solution `:spawn bash -c 'echo "a" >> ~/a.txt'`.. but it is just good to know.

Anyways, thank you very much for your patience and help. I feel happy and content.

**Comment by The-Compiler** [comment]
> I edited my test script by taking the variables away, but without `-u` it still gets errors.

Can't say much without seeing the updated script and the exact errors.

> Another nagging thing is that `:spawn bash echo "a" >> ~/a.txt` does not work.. Though we already have another solution `:spawn bash -c 'echo "a" >> ~/a.txt'`.. but it is just good to know.

This is because `bash` takes a bash script as its first argument, and `echo` isn't a bash script. If you run `bash echo "a" >> ~/a.txt` inside a shell, you're going to get the same error.

**Comment by jcguu95** [comment]
##### The updated userscript 'test'
```
#!/bin/bash
echo "something" >> ~/a.txt
```
##### Error `:spawn test' (without `-u`)
08:05:47 | DEBUG | message | message:_log_stack:41 | Stack for error message:   File "/usr/bin/qutebrowser", line 11, in <module>     load_entry_point('qutebrowser==1.6.2', 'gui_scripts', 'qutebrowser')()   File "/usr/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 194, in main     return app.run(args)   File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 144, in run     ret = qt_mainloop()   File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 154, in qt_mainloop     return q_app.exec_()   File "/usr/lib/python3.7/site-packages/qutebrowser/misc/guiprocess.py", line 122, in on_finished     "details.".format(self._what.capitalize(), code))   File "/usr/lib/python3.7/site-packages/qutebrowser/utils/message.py", line 53, in error     stack = ''.join(traceback.format_stack())
-- | -- | -- | -- | --
08:05:47 | ERROR | message | message:error:58 | Command exited with status 1, see :messages for details.

##### `:spawn echo "something" >> ~/a.txt`
This, however, does not give any error. But the file "~/a.txt" failed to be written.

**Comment by The-Compiler** [comment]
> Error :spawn test (without -u)

Without `-u`, qutebrowser only looks in the `$PATH`, not `~/.local/share/qutebrowser/userscripts/`, so you'd need to use the full path.

> This does **not** give any error. However, the file "~/a.txt" failed to be written.

That's because `:spawn` in qutebrowser isn't a shell, so `>>` doesn't have any special meaning. If you need bash features, you'll need to use `bash -c`.

**Comment by jcguu95** [comment]
Now it is all clear! Thank you very much (I love qutebrowser)!
