### ISSUE TITLE
Dynamical Environment Variable

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#4827]
I was trying to write a user script for qb to track my time usage on it. More specifically, I would like the script to keep track of which site I am on per second. It would be turned on right after qb is.

The main problem is that the environment variables seem like to be static. In my case, for example, `$QUTE_URL` is set to be what it is at the moment the script is called; it does not change as my switch focus to other page (or tab).

#### Script
```
#!/bin/bash
while true; do
    echo "$QUTE_URL" >> ~/log.txt
    sleep 1
done
```
#### Output
```
https://duckduckgo.com/
https://duckduckgo.com/         ## even if I have switched to www.youtube.com, say
.
.
```

### Question
Is it possible to make the variable dynamical? Did I miss something? Also, I found a list of environment variables on the [official page](https://qutebrowser.org/doc/userscripts.html), but how could I make sure that those are all possible environment variables?

**Comment by The-Compiler** [comment]
Environment variables can only be set when a process is started (in general, not related to qutebrowser) - for what you want to do, you'd probably need to wait until there's a proper extension API (see #30).



> Also, I found a list of environment variables on the [official page](https://qutebrowser.org/doc/userscripts.html), but how could I make sure that those are all possible environment variables?

By trusting the documentation not to lie, or by double-checking with the output of `env` in a userscript.

**Comment by user202729** [comment]
Currently, qutebrowser prints some debug information with `--debug` which (I think) includes which page you are on. You can try to use that, but I doubt that would work.

**Comment by The-Compiler** [comment]
You could probably also call `:session-save` to some YAML file in your script and then parse that FWIW.

**Comment by jcguu95** [comment]
@user202729  Thank you for your suggestion! I looked into it but seems that it does not contain everything I want. I also followed @The-Compiler 's suggestion and wrote a script that logs the seconds I spent on all URLs!

I haven't had much experience, so the style might be bad. But anyway, here it is:
```
#!/bin/bash

## This is a bash script that will be run by qutebrowser at its launch!
## It tracks the time spent and the URL (in second) on the focused tab.
## Also, it only tracks while qutebrowser is focused. (while grep -q "^-active: true" "$Session" is true)

SessionTime=$(date "+%F-%T-[%z]")
SavingDirectory="$HOME/Cloud/Dropbox/workspace/program/qutebrowser-userscripts"
Log="$SavingDirectory/usage-log-$SessionTime.txt"
Session="$SavingDirectory/session.tmp.yaml"

while true; do
	echo "session-save $Session" >> "$QUTE_FIFO"

	Url="$(
	cat "$Session" |
	sed -n '/^  - active:/,/^  - history:/ p' |
	sed -n '/^[ \t]*y:/,/^[ \t]*url/ p' |
	sed '/^[ \t]*url/! d' |
	sed 's/^[ \t]*url: //')"

	grep -q "^- active: true" "$Session" && ## so the following if loop only works while qutebrowser is active
	if grep -q "$Url" "$Log"; then
		# It's not going to work if I use s/.. # Note that we must escape here: not even `sed -n "/"$Url"/.." works!`
		EscapedUrl=$(echo "$Url" | sed "s_\/_\\\/_g")
		OldAccumuTime=$(cat "$Log" | sed -n "/$EscapedUrl/ s/ .*//p")
		NewAccumuTime=$(($OldAccumuTime+1))
		sed -i "s/^$OldAccumuTime $EscapedUrl/$NewAccumuTime $EscapedUrl/" "$Log"
	else	echo -e "1 $Url" >> "$Log"
	fi

	sleep 1
done
```

## Question
Now I am pretty happy about this program, but I would like it to autostart at the launch of qutebrowser. Can I hook this user-script in `config.py` and ask qb to start it automatically?
