### ISSUE TITLE
Force full screen

### ISSUE THREAD

**Issue by reschl** [qutebrowser/qutebrowser#4828]
Currently qutebrowser only provides a toggle for full screen. Thereby it is not possible to just start it in full screen mode independent of the state it is in. For example, chromium provides "--fullscreen" to start in full screen mode.

For qutebrowser the feature could be added as "--force" for the available :fullscreen.

If this feature get's accepted I would be happy to provide a PR.

**Comment by The-Compiler** [comment]
There's already `:fullscreen --leave` to only leave fullscreen, so for symmetry with that I'd probably call it `:fullscreen --enter`. Other than that, sounds simple enough, go ahead!

**Comment by gfxwebdev** [comment]
Qutebrowser use :fullscreen switch as toggle, which means if once used there is no necessary using again (if we want stay in fullscreen mode each time we will firing up Qutebrowser).
For example... After installing process of Qutebrowser, and first running it from CLI we probably use something syntax as follow (assuming we go to github url):
`qutebrowser www.github.com`
and our window with already CLI terminal should show github site in the default size of qutebrowser window (meaning: usual window size NO FULLSCREEN). Now.. If we want to set fullscreen we just click ":" and taping "fullscreen --enter" (and hit ENTER button on our keyboard of course). Now the window with Qutebrowser should fill whole space on our Desktop GUI system and stay it as long as we need.
HOWEVER... If we want return to usual size of window we should again click on ":" and just type "fullscreen" (and hit ENTER).
I have no idea why "--leave" doesn't work in my system (Debian), but who knows.. maybe it is single case.

Above explained situation works on my computer. Cheers!
