### ISSUE TITLE
Userscripts at launch

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#4830]
### Question
1. Is it possible to run userscripts at launch automatically by configuring config.py?
2. One thing might be helpful but I also did not find a way to do: is there something like `{<CR>}` that will expand to an `return` stroke in the command line?

### My attempt
I have checked the [Configuration Page](https://qutebrowser.org/doc/help/configuring.html), the [Command Page](https://qutebrowser.org/doc/help/commands.html), and the [Settings Ref Page](https://qutebrowser.org/doc/help/settings.html). I also searched keywords like "auto", "at launch", "userscripts" in `Issues`.

Thank you.

**Comment by user202729** [comment]
`<enter>` may work.

**Comment by jgkamat** [comment]
jcguu95 writes:

> 1. Is it possible to run userscripts at launch automatically by configuring 
> config.py?

I don't think this is easily doable at the minute. You could call the spawn 
python function directly, but that's not properly supported.

Also another thing to note is that config.py is run very early, so userscripts 
might not successfully be able to run at that point.

> 2. One thing might be helpful but I also did not find a way to do: is there 
> something like `{<CR>}` that will expand to an `return` stroke in the 
> command line?

maybe you can send the :command-accept command

**Comment by jcguu95** [comment]
@user202729 Sorry, I should have been more specific. What I want to do is to bind a short keystroke to a userscript without pressing <enter> (I'm lazy). In my case,
```
config.bind('aw',"set-cmd-text -r :spawn bash -c 'vocab --add {primary}' <ENTER>")
```
I hope that `<ENTER>` expands to the return keystroke automatically once I press `'aw'`. I have tried
```
config.bind('aw',"set-cmd-text -r :spawn bash -c 'vocab --add {primary}' :fake-key<ENTER>")
```
which should fail obviously.. I cannot think of another way round.


@jgkamat said:
> maybe you can send the :command-accept command
As I have pointed out up there, I have also tried (mimicking the `set-cmd-text` syntax)
```
config.bind('aw',"command-accept :spawn bash -c 'vocab --add {primary}'")
config.bind('aw',"command-accept -r :spawn bash -c 'vocab --add {primary}'")
config.bind('aw',"set-cmd-txt :spawn bash -c 'vocab --add {primary}' command-accept")
```
but none of them worked..

**Comment by The-Compiler** [comment]
@jcguu95 `:set-cmd-text` is a command to set the text of the commandline. If you want to run the `:spawn` command directly, bind to that command: `config.bind('aw',"spawn bash -c 'vocab --add {primary}'")` (also, I don't see why you need the `bash -c` there - quite the contrary, this would break with special characters or even allow websites to inject commands (by cleverly selecting more than the visible selection displays).

**Comment by jcguu95** [comment]
@The-Compiler That idea works! Thank you.
I don't really know since I am pretty new with computer.. My `vocab` script is actually a shell script. While executed as a userscript for qutebrowser, I assume a shell is opened for that command anyway. That way, special characters or even bad commands can leak in. Please correct me if I am wrong. My second (this) problem has been solved, but it is nice to know more about what qutebrowser really does here. Thanks again :)

**Comment by The-Compiler** [comment]
> My `vocab` script is actually a shell script. While executed as a userscript for qutebrowser, I assume a shell is opened for that command anyway. That way, special characters or even bad commands can leak in. Please correct me if I am wrong.

Nope, if your shell script accesses variables like `$1` for its arguments, no special evaluation of the content takes place (unless you use `eval` or so, but that's usually a bad idea). Consider a script like:

```bash
#!/bin/bash
notify-send "$1"
```

If you spawn that with `:spawn myscript $HOME` you're going to see a notification which displays a literal `$HOME`, because no shell is involved when passing the arguments, and bash running the script just takes the passed argument literally.

However, if you do `:spawn bash -c 'myscript $HOME'`, you spawn a bash shell which interprets `$HOME` and then starts your script in a second bash instance, with something like `/home/yourname`.

Similarly, if you run `bash -c 'vocab --add {primary}'`, a page could trick you into selecting something like `word $(rm ~/important-file)` (but with the second part hidden via some stylesheet trickery), which your `bash -c` will happily run.

**Comment by The-Compiler** [comment]
As for running userscripts at launch: This currently isn't possible - like @jgkamat mentioned, you might be able to do something in `config.py`, but probably things aren't set up properly at the time it runs.

This should be possible when there's a proper extension API (#30), also via autocmds (#35) which are easy to implement once the extension API is there.
