### ISSUE TITLE
ublock Origin support

### ISSUE THREAD

**Issue by cdmjr** [qutebrowser/qutebrowser#4832]
Can we add ublock origin support in this? or do you have plans adding it in the future? It is a powerful adblocker.

**Comment by The-Compiler** [comment]
See #29 and #30.

**Comment by autoteelar** [comment]
hmm maybe theres a way to use ublock origins source code to improve the current adblocking or add the ability for users to pick and block elements, not really suggesting anything just discussing and brainstorming whats possible and what is not.

**Comment by The-Compiler** [comment]
@autoteelar see https://www.reddit.com/r/qutebrowser/comments/qbdtes/even_though_extensions_arent_yet_supported_would/hhdsghd and #6480.
