### ISSUE TITLE
Keyerror crash on certain pages

### ISSUE THREAD

**Issue by DarkDefender** [qutebrowser/qutebrowser#4836]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/075d2cc4
**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When entering certain webpages, qutebrowser crashes with:
```
==== Exception ====
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/qutebrowser/browser/webengine/webview.py", line 262, in acceptNavigationRequest
    navigation_type=type_map[typ],
KeyError: 6    
``` 

**How to reproduce**
1. Open qutebrowser
2. Open the webpage: https://steelseries.com/gaming-headsets/arctis-pro
3. qutebrowser crashes.

**Comment by jgkamat** [comment]
This is due to the new navigation navigation type for requests in qt 5.14. Not 
sure why this dosen't default to other.

**Comment by jgkamat** [comment]
Made a basic patch which should fix this, but I cannot actually test it at the 
minute so I'm not submitting it.

http://paste.debian.net/plain/1087038

**Comment by DarkDefender** [comment]
Just for my initial quick testing, that patch seems to do the trick! Thank you! :D

**Comment by The-Compiler** [comment]
I pushed that patch because it looks good - can't test on Qt 5.14 at the moment either (too little disk space thanks to a Windows VM taking up 100 GB, I'll nuke it as soon as my bachelor thesis is over), but it seems simple enough.

Thanks @DarkDefender and @jgkamat!
