### ISSUE TITLE
Do you plan on changing the web engine used due to Chrome's changes?

### ISSUE THREAD

**Issue by cdmjr** [qutebrowser/qutebrowser#4838]
It would be tedious if you removed all the chrome-related technologies inside your browser, but IMO it would be better if you used something like Firefox's technologies. It cares about privacy and its users.

**Comment by The-Compiler** [comment]
If someone maintains something to hook up Firefox (or Servo) Python/Qt, maybe. Until that happens, nope. Also, note that you can already use qutebrowser with QtWebKit instead.

**Comment by The-Compiler** [comment]
To clarify: I don't plan to drop QtWebEngine support as long as it's supported upstream, the only thing which would be a possibility is adding a third backend - but since there is no such project on the horizon so far, there's no point in thinking about it.
