### ISSUE TITLE
Add prefers-color-scheme CSS media feature to qutebrowser settings

### ISSUE THREAD

**Issue by Jan-PieterBaert** [qutebrowser/qutebrowser#4840]
It would be nice if https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme was configurable in the settings.

**Comment by The-Compiler** [comment]
qutebrowser can't support that before underlying QtWebEngine/Chromium does. Looks like support [was added](https://caniuse.com/#feat=prefers-color-scheme) in Chromium 76 ([related bug](https://bugs.chromium.org/p/chromium/issues/detail?id=889087)).

I'd hope that Chromium 76 gets integrated with Qt 5.14 (November/December 2019), until then, there's nothing qutebrowser can do. After that, maybe passing the corresponding commandline switches will work, but maybe QtWebEngine needs to add a setting to set it first.

**Comment by The-Compiler** [comment]
I added this to #4616 - let's see how things look when Qt 5.14 is closer.

**Comment by The-Compiler** [comment]
Looks like we can't support this before Qt does - I opened [[QTBUG-79347] Setting for dark mode / prefers-color-scheme - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-79347)

**Comment by The-Compiler** [comment]
Oh, that was quick - Qt 5.14 is adding support here: https://codereview.qt-project.org/c/qt/qtwebengine/+/278374

**Comment by rien333** [comment]
@The-Compiler now that Qt 5.14 has been out for a while, this should be theoretically possible to implement in qutebrowser, right? (also, I noticed that you didn't add this to https://github.com/qutebrowser/qutebrowser/issues/4616 as an explicit Qt feature, but that might be intentional)

**Comment by The-Compiler** [comment]
Indeed! I added the change to #4616. There isn't much qutebrowser needs to do though - dark mode should be picked up from the OS automatically. You can add `force-dark-mode` to the `qt.args` setting though, and maybe qutebrowser should expose that as a separate setting.

**Comment by rien333** [comment]
All right, was hoping for something easy like that.

**Comment by The-Compiler** [comment]
I added a `colors.webpage.force_dark_color_scheme` option in https://github.com/qutebrowser/qutebrowser/commit/6fdf0426d7fb7fd2cfbcc8bfc23975abb38a53cd.

**Comment by Jan-PieterBaert** [comment]
awesome, thanks :smiley:

**Comment by The-Compiler** [comment]
Turns out there also is a newer `--force-dark-mode` switch in Chromium, which actually sets some blink feature flags: https://bugs.chromium.org/p/chromium/issues/detail?id=985961

I'll need to think how to best expose this to qutebrowser settings, maybe even backing out the `force_dark_color_scheme` option because a different way of organizing them might make sense.

**Comment by rien333** [comment]
Interesting, thanks for looking into this. It seems like the chromium setting you mentioned can actually force websites to display in dark mode by inverting colors, and [exposes a variety of modes to do so](https://bugs.chromium.org/p/chromium/issues/detail?id=985961#c2):

```
...
Version 5 Simple, no image inversion, HSL-based inversion:
darkMode=3,
darkModeImagePolicy=1,

Version 6 Simple inversion of non-image elements, selective image inversion:
darkMode=4,
darkModeImagePolicy=2,
```

Any change of qutebrowser inheriting this feature/features? (as for an accompanying  qutebrowser setting, maybe allow the user to select a few of these modes?)

**Comment by The-Compiler** [comment]
Yeah, you can already use it via `qt.args` (or `--qt-flag`) - I added some explanations to https://github.com/qutebrowser/qutebrowser/issues/2377#issuecomment-577689021.

The question is how to best organize those settings, and what to do with `colors.webpage.force_dark_color_scheme` before the v1.10.0 release. I'd like some opinions on that!

What do you think about renaming `colors.webpage.force_dark_color_scheme` to `colors.webpage.dark.prefers_color_scheme_dark` or so? It clearly conveys that the setting is about the `prefers-color-scheme: dark` CSS query, and it starts a `color.webpage.dark` group which then we could use for the new settings in the future, e.g. `colors.webpage.dark.force.enabled`, `colors.webpage.dark.force.image_policy`, etc.

**Comment by rien333** [comment]
> What do you think about renaming colors.webpage.force_dark_color_scheme to colors.webpage.dark.prefers_color_scheme_dark or so? 

Yeah, renaming it like that makes sense, especially because nothing is "forced". The suboptions also make sense to me, it would be nice to offer specific controls like that.

**Comment by The-Compiler** [comment]
> Yeah, renaming it like that makes sense, especially because nothing is "forced".

By default, whether to use `prefers-color-scheme: dark` or `light` is auto-detected based on the respective operating system. The setting (which maps to the `--force-dark-mode` Chromium flag) forces `prefers-color-scheme: dark` no matter what Chromium detects from the OS.

Ideally we could say `dark`, `light` or `auto`, but forcing light doesn't seem to be available.

**Comment by The-Compiler** [comment]
I've been thinking about the naming some more, and I think I won't try to group the `prefers-color-scheme` setting with the filter settings from #2377.

Here's what I had in mind originally:

```
colors.webpage.dark.prefers_color_scheme_dark
colors.webpage.dark.filter.enabled  # force -> filter
colors.webpage.dark.filter.image_policy
...
```

but I don't think a category named "dark" is very expressive, and the "prefers_color_scheme_dark" setting is kind of the oddball in there, since it's the only one not related to the dark filter. Also, the "dark" repetition is weird.

So here's what I'll probably go with:

```
colors.webpage.prefers_color_scheme_dark
colors.webpage.dark_filter.enabled
colors.webpage.dark_filter.image_policy
...
```

So for v1.10.0, I'll rename `force_dark_color_scheme` to `prefers_color_scheme_dark`, that definitely seems like a clearer name.

@mschilli87 I'd be interested in your opinion, master of `configdata.yml` consistency :wink:

**Comment by mschilli87** [comment]
@The-Compiler 

> So here's what I'll probably go with:
> 
> ```
> colors.webpage.prefers_color_scheme_dark
> colors.webpage.dark_filter.enabled
> colors.webpage.dark_filter.image_policy
> ...
> ```

LGTM :wink:  

I think (at least given reasonable descriptions) it should be fairly easy to figure out what each setting is doing.

**Comment by The-Compiler** [comment]
Renamed! Closing this again then, will track the `dark_filter` settings as part of #2377.
