### ISSUE TITLE
Userscript when downloading PDF

### ISSUE THREAD

**Issue by deb75** [qutebrowser/qutebrowser#4843]
Hello,

I would like to use an external pdf reader instead of pdf.js. Of course, I could disable this one and download the PDF file, then open it in a shell or whatever.

I would like to develop a more integrated approach, I think it could be done with a userscript that would be launched automatically when downloading a file.

I would like the script to check if it is a PDF file, then if it is open it, and lastly propose to save it elsewhere away from the download dir.

Is it possible to trigger a script as soon as a dowload starts ? and how can I retrieve the file name within the script ?

Regards

**Comment by The-Compiler** [comment]
It sounds like what you want is more suited for a proper plugin API, see #30.

However, note that you can use `:prompt-open-download` (ctrl-x) already to open a download with the default application when the download is finished, or bind your own key to run `:prompt-open-download somecommand`.
