### ISSUE TITLE
Groups of tabs

### ISSUE THREAD

**Issue by deb75** [qutebrowser/qutebrowser#4844]
Hello,

I wonder if it would be possible to group tabs. The idea behind is sometimes I use qutebrowser for working, sometimes for myself, and I would appreciate to group all tabs opened for my work, hide them, open some tabs within another group, hide them and make those from my work visible again.

If you think it is feasible, let me know what should be done, I could look into it.

Regards

**Comment by The-Compiler** [comment]
To some extent, you can already use sessions to do so. For some more ideas, see #4558, #4074, #927, #49.
