### ISSUE TITLE
Cannot replace tab in existing instance from command line

### ISSUE THREAD

**Issue by kralan** [qutebrowser/qutebrowser#4846]
I am looking for a way to replace the current tab with an URL passed by the command line:
* `qutebrowser www.testurl.com` opens the URL in a new tab
* `qutebrowser :open www.testurl.com` replaces the current tab with a start page (duckduckgo), then opens the URL in a new tab

Typing `:open www.testurl.com` in the browser window works as expected.

Is this a bug or am I just missing a magic CLI option?

Regards,
kralan

Versions:
qutebrowser v1.6.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.3
Qt: 5.11.3
PyQt: 5.11.3

**Comment by The-Compiler** [comment]
You're not quoting your arguments correctly - running `qutebrowser :open www.testurl.com` tells qutebrowser to run `:open` (opening the start page) and then open `www.testurl.com`.

What you want is probably `qutebrowser ':open www.testurl.com'` to tell your shell to pass the command as a single argument.
