### ISSUE TITLE
--temp-basedir with default config file

### ISSUE THREAD

**Issue by tcpaiva** [qutebrowser/qutebrowser#4854]
Hi

I love how I am able to create temporary profiles in qutebrowser using the "--temp-basedir" option. I have noticed that the new profile will not follow the rules that I already set in the config file (for example, I use zoom.default to 125, which makes my reading in the new instances much harder without it). Is there a way, for example to say:

    qutebrowser --temp-basedir -f ~/.config/qutebrowser 

where `-f` is an option that I created just for sake of this question representing the default configuration pointer. I couldn't find anything like that in the documentation.

**Comment by The-Compiler** [comment]
Currently the best you can do is using `--basedir` with some file structure and copy the config there. #4286 adds a `--config.py` option which allows the same with a `config.py` file (but not the whole config dir).

**Comment by tcpaiva** [comment]
I think I don't have this option available in my version (Ubuntu 18.10). Is there any ppa available for newer versions of qutebrowser? Or do you know if Ubuntu 19.04 would be enough? 

Can you please confirm, before I start digging further on this, if it is possible to use `--temp-basedir` and `--config-py` at same time? From your answer I assume that yes, it is possible.

If not, to automate this procedure, I can think a way to assemble a script to combine the `--basedir` option with `mktemp` command (or something in these lines). The `--temp-basedir` option is not that useful in my case if the browser itself is not usable.

**Comment by jgkamat** [comment]
Thiago Costa de Paiva writes:

> I think I don't have this option available in my version (Ubuntu 18.10). Is 
> there any ppa available for newer versions of qutebrowser? Or do you know if 
> Ubuntu 19.04 would be enough?

That patch is not even on master yet, you'll need to apply it manually

**Comment by tcpaiva** [comment]
Sharing my solution for now, in case someone else needs a similar approach. It is a wrapper script to create a temporary directory, copy qutebrowser configuration to that folder, and point it when launching the browser. Oh, and the script also removes the folder when that instance of the browser is closed.

    #!/bin/sh
    TEMPDIR=$(mktemp -d)
    cp -r $HOME/.config/qutebrowser/* ${TEMPDIR}/
    qutebrowser --basedir=${TEMPDIR}
    rm -r ${TEMPDIR}
