### ISSUE TITLE
List Background Userscripts

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#4858]
I wrote a script and hope it can automatically starts at launch, but it is currently impossible according to [this issue](https://github.com/qutebrowser/qutebrowser/issues/4830). Alternatively, I should launch it myself, but should also avoid launching it more than one time. Is it possible to list all userscripts that are running in the background?

**Comment by The-Compiler** [comment]
You should see them in the process monitor of your choice (e.g. htop).
