### ISSUE TITLE
pattern based stylesheets

### ISSUE THREAD

**Issue by fruitloop** [qutebrowser/qutebrowser#4859]
Hi,
i'm trying to get several custom css styles working.
I have different stylesheets for different sites (domains would work as well)
I tried a setup like this:

```
with config.pattern('*://*.strava.com/*') as p: c.content.user_stylesheets = ['~/css/strava.css']
with config.pattern('*://*.youtube.com/*') as p: c.content.user_stylesheets = ['~/css/youtube.css']
```
whith almost works but it only works for the last entry (youtube in this example) the strava.css does no longer get loaded.

Is there a way to get this done? maybe with a pattern parameter for user_stylesheets?
I'd even take some kind of solution where I pack some if/else blocks togethehr if there is any 
way to check for the current url from within the config. Something like this?:

```
if "strava.com" in <some_variable>: c.content.user_stylesheets = ['~/css/strava.css']
else if "youtube.com" in <some_variable>: c.content.user_stylesheets = ['~/css/youtube.css']
```
I found #961 and #27 which both are closed though it seems that this is not exactly solved yet.

**Comment by The-Compiler** [comment]
See #3636 and #3854 (but that doesn't work properly yet).

**Comment by aitzkora** [comment]
Hi have you a example to use the result of "not work properly yet" #3854 when we want to have a pattern based custom stylesheet ?
we have to write code like 
```python  
with config.pattern('*://*.pattern.com/*') as p: c.content.user_stylesheets = ['mystyle.css']
```
or another method is recommended ?
Thanks in advance for your reply.

**Comment by The-Compiler** [comment]
@aitzkora That sounds about right, if you have that PR merged locally. I haven't tested it in a while though.

**Comment by aitzkora** [comment]
thanks, may be I'll give a try, because this feature is very useful to save my eyes :-)

**Comment by The-Compiler** [comment]
You could also use qutebrowser's greasemonkey feature as a workaround, see https://github.com/qutebrowser/qutebrowser/pull/3854#issuecomment-545174068
