### ISSUE TITLE
Select sentence by clicking

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#4867]
### Current State
The current state of my qutebrowser: as I click on a word twice, qb selects the word; as I click on a word three times, qb selects the whole paragraph containing that word.

### Wondering
I wonder if it is possible to select the 'sentence' that contains a certain word by clicking? By a 'sentence' I mean the string surrounded by consecutive periods. Kindle has this feature, and I think it will be pretty nice if we have that on qutebrowser too.

Please let me know if I should be more specific. Thank you.

**Comment by jgkamat** [comment]
jcguu95 writes:

> ### Wondering
> I wonder if it is possible to select the 'sentence' that contains a certain 
> word by clicking? By a 'sentence' I mean the string surrounded by 
> consecutive periods. Kindle has this feature, and I think it will be pretty 
> nice if we have that on qutebrowser too.

You might be able to find a greasemonkey script which does what you want. 
Otherwise, see #591

**Comment by jcguu95** [comment]
Mouse binding is a good idea! Though we should still need a function/script behind this that selects the selected sentence.

**Comment by jgkamat** [comment]
jcguu95 writes:

> Mouse binding is a good idea! Though we should still need a function/script 
> behind this that selects the selected sentence.

You should be able to use jseval to make your own fairly easily, given the 
location of the click. In fact, you could probably already do this already 
with greasemonkey and a click listener.

**Comment by jcguu95** [comment]
Hmm.. I am pretty new in programming. Would you mind throwing more buzzwords about jseval/greasemonkey at me? I will do the rest of the searching. Thank you!
