### ISSUE TITLE
Disable tabs

### ISSUE THREAD

**Issue by rakanalh** [qutebrowser/qutebrowser#4876]
Hello,

Since tabs on restarting Qutebrowser are disabled (not sure if that's a default behaviour), it would be nice to add an option to disable tabs but keep them around until the tab is selected for it to display.

**Comment by jgkamat** [comment]
Rakan Alhneiti writes:

> Hello,
>
> Since tabs on restarting Qutebrowser are disabled


For me, tabs are still enabled (?) on restart.

> (not sure if that's a default behaviour), it would be nice to add an option
> to disable tabs but keep them around until the tab is selected for it to
> display.

My best shot in the dark is auto_save.session + session.lazy_restore

**Comment by rakanalh** [comment]
Ahh, must have expressed things in the wrong way. 

> Since tabs on restarting Qutebrowser are disabled

I meant that each tab URL isn't loaded until the tab is clicked then it starts loading the page. I would assume here `session.lazy_restore` is doing it's job.

My suggestion is to add a command such as `:tab-disable` which basically clears the current tab's content and navigates to a "disabled" page until the tab is re-clicked again.

**Comment by The-Compiler** [comment]
See (the remaining parts of) #67, and #4037.
