### ISSUE TITLE
session.lazy_restore does not work

### ISSUE THREAD

**Issue by agguser** [qutebrowser/qutebrowser#4881]
After updating my system (Arch Linux; qt5-webengine is updated to 5.13.0-1, but no update for qutebrowser as it is already latest version, 1.6.3-1), qutebrowser does not "lazy load" tabs on startup anymore, all tabs are loaded at once. Don't know why.

**Comment by toofar** [comment]
```
07:21:05 DEBUG    webview    browsertab:_set_load_status:921 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='qute://back/#Version info'>: LoadStatus.success
07:21:05 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_status_changed(<LoadStatus.success: 2>) (tab 1)
07:21:05 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_finished(True) (tab 1)
07:21:05 DEBUG    sessions   sessions:save:295 Saving session _autosave to /tmp/qute-basdir-nolazy/data/sessions/_autosave.yml...
07:21:06 DEBUG    webview    browsertab:_set_load_status:921 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='qute://back/#Version info'>: LoadStatus.loading
07:21:06 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 1)
07:21:06 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_started() (tab 1)
```
but why 😢
Okay, it doesn't break #4037 at least, probably the javascript then...

**Comment by The-Compiler** [comment]
Hmm, maybe https://bugreports.qt.io/browse/QTBUG-69360 regressed in some way in Qt 5.13?

**Comment by toofar** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) implies that in the visibility state event handler you should be able to check `document.visibilityState` to get the *current* visibility state. Here I have a version page and an about blank (which is the background one), hidden is `document.hidden`. The code is just:
```javascript
console.log(`${window.location.href}: visibility on load (${document.visibilityState} and hidden=${document.hidden})`)
document.addEventListener("visibilitychange", (...args) => {
  console.log(`${window.location.href}: visibility change ${args} (${document.visibilityState} and hidden=${document.hidden})`)
})
```
```
08:02:46 DEBUG    js         shared:javascript_log_message:146 [qute://back/:48] qute://back/#about%3Ablank: visibility on load (visible and hidden=false)
08:02:46 DEBUG    js         shared:javascript_log_message:146 [qute://back/:48] qute://back/#Version%20info: visibility on load (visible and hidden=false)
08:02:47 DEBUG    js         shared:javascript_log_message:146 [qute://back/:49] qute://back/#about%3Ablank: visibility change [object Event] (hidden and hidden=true)
08:02:47 DEBUG    js         shared:javascript_log_message:146 [qute://back/:49] qute://back/#Version%20info: visibility change [object Event] (hidden and hidden=true)
```
Which seems broken but the test case on 69360 reports:
````
hidden: true, visibilityState: hidden
hidden: false, visibilityState: visible
```
So why is it telling us that views aren't hidden when they are created? Same with opening that acme page in a background tab, it claims it was visible to start with but switching away and then back it correctly picks up that it was hidden in the interim. I'll have a crack at making a reproducer the same way we open background tabs tomorow, if noone else already has. Oh no, that's not the best example. It has the same behaviour on 5.11...

**Comment by toofar** [comment]
Well here is a reproducer. I'm not sure how convincing it is. I am confused as to why (on <5.13) we have to focus the backround tabs first and then switch away from from them or else they report as visible. Might have to look into the QTabWidget a bit more. Run it with `--enable-logging --log-level=0` and on 5.11 (and presumably 5.12) it reports that on load the "about:blank?2" view is hidden and the other one is visible. On 5.13 it says they are both visible.
```C++
#include <QWebEngineView>
#include <QApplication>
#include <QTabWidget>
#include <QUrl>

int main(int argc, char **argv)
{
    QString html(""
    "<html>\n"
    "  <body>\n"
    "    <div id=\"log\" style=\"width: 100%; height: 100%;\"/>\n"
    "  <script>\n"
    "    function report (details) {\n"
    "      let msg = `${window.location.href}: ${details} (${document.visibilityState} and hidden=${document.hidden})`\n"
    "      console.log(msg)\n"
    "      let log = document.getElementById('log')\n"
    "      let d = new Date()\n"
    "      log.innerHTML += `${d.toISOString()} ${msg} <br/>`\n"
    "    }\n"
    "    report('visibility on load')\n"
    "    document.addEventListener('visibilitychange', (...args) => {\n"
    "      report('visibility change')\n"
    "    })\n"
    "  </script>\n"
    "  </body>\n"
    "</html>\n"
    "");
    QApplication app(argc, argv);

    QTabWidget tabs;
    tabs.resize(400, 600);
    tabs.show();

    QWebEngineView view(&tabs);
    view.resize(400, 600);
    view.show();
    tabs.insertTab(0, &view, QString("0"));
    tabs.setCurrentIndex(0);

    QWebEngineView view2(&tabs);
    view.resize(400, 600);
    view.show();
    tabs.insertTab(1, &view2, QString("1"));
    tabs.setCurrentIndex(1);

    view.setHtml(html, QUrl("about:blank?1"));
    view2.setHtml(html, QUrl("about:blank?2"));

    tabs.setCurrentIndex(0);
    return app.exec();
}
```

**Comment by tobip** [comment]
Same problem here on Manjaro Linux.

Is there a possibility to increase the priority to fix this bug?
Because for me it makes quetbrowser unusable, when loads of tabs are running in the background on my notebook using half of the cpu.

**Comment by The-Compiler** [comment]
@tobip It's probably a Qt rather than a qutebrowser bug and I personally don't use lazy tabs. Your best bet is hoping that #4037 fixes it or that someone steps up to take a look.

**Comment by JonnyHaystack** [comment]
For what it's worth, this makes qutebrowser borderline unusable for me too.

**Comment by agguser** [comment]
My workaround (on Linux):
- `~/.zshrc`
```zsh
qlazy() {   # make qutebrowser tabs lazy (by converting session URLs to "about:blank#…")
   perl -C -i -lpe '$a = 1 if /^    - active:/; s/^(      url: )(about:blank#)?(.*)/$a = 0, $2 ? $& : "$1about:blank#$3"/e if $a' ~/.local/share/qutebrowser/sessions/default.yml
   #~ qutebrowser
   }
```
- `~/.config/qutebrowser/config.py`
```python
config.bind('<Ctrl-R>', r'jseval -q location.replace(((u, p) => u.match("^"+p) ? u.replace(p, "") : p+u)(location.href, "about:blank#"))')   # toggle tab laziness
```

Steps:
1. run `qlazy`
2. open qutebrowser
3. <kbd>Ctrl-R</kbd> on tab to toggle its laziness.

**Comment by toofar** [comment]
I believe there are actually two webengine issues here, one pre-existing and one due to the changed behaviour with 5.13. I'll raise a bug or two with them but not only can we work around it but due to one of the bugs our background tabs have been reporting (in JS) as being in the foreground at least since 5.11. I linked a patch above which I believe fixes which lets us actually load non-active tabs from session in the background now. I just need to find time to add a proper integration test to catch future changes in this area (work has been keeping me very busy lately).
Try `:open -b javascript:window.setTimeout(function(){document.write(''+document.hidden)},0)` with and without the patch.

**Comment by blueyed** [comment]
For reference: with https://github.com/qutebrowser/qutebrowser/issues/4922 I've noticed that there is a difference still between CPU usage due to this (`:set session.lazy_restore true` caused more CPU usage for the tab(s) not being activated yet).

**Comment by JonnyHaystack** [comment]
It looks like this is working again for me. Not sure what has changed though

**Comment by The-Compiler** [comment]
@JonnyHaystack I've asked Archlinux to backport the [proper Qt fix](https://github.com/qt/qtwebengine/commit/1c33a4a6) for this issue.

**Comment by agguser** [comment]
Seem the problem has been fixed, so this issue should be closed.

**Comment by JonnyHaystack** [comment]
This bug is back again :cry:

**Comment by The-Compiler** [comment]
@JonnyHaystack It's a different issue - see the `qute://warning/sessions` page which showed up at the first start on Qt 5.15 and #5359 (though I just noticed the text there is wrong - the fix isn't part of the v1.12.0 release).

**Comment by JonnyHaystack** [comment]
Ah, my mistake sorry. I don't remember seeing that warning

**Comment by amacfie** [comment]
@toofar 
> https://termbin.com/qkit should do it. Now for tests so we can catch if it breaks again.

Link is down?
