### ISSUE TITLE
Hints leave visual artifacts 

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#4883]
**Version info (see `:version`)**:

qutebrowser v1.6.3
Git commit: 1489cc761 (2019-06-30 14:18:26 +0200)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.12.3

I'm running arch linux, fully updated. The problem also seemed to be present on Qt 5.12 before 5.13 rolled out recently.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Whenever I start hinting and then quit out of it, visual artefacts of the hints remain on the screen. See the attached image. They'll follow along if I scroll through the page. I've been seeing some other artefacts for a while now  too, but they were more subtle. Mostly just small stripes. I can try and post a screenshot and reproduction steps for those stripes as well if I encounter them again. It also happens with compton turned off, if that is relevant. 

![2019-07-02-1562074812](https://user-images.githubusercontent.com/10417027/60519061-0eb89d80-9ce3-11e9-9bbb-8cf4fc6ce6ad.png)

**How to reproduce**
The problem seems to occur more often with slightly more "complex" websites, although I've seen it all over. To reproduce it, I can go to facebook.com, start hinting (e.g. by pressing `f`), quit out of it and then artifacts of the hints remain on the screen. The effects seems to be slightly more severe if I scroll a little when the hints are active. They will go away after a screen update, caused by a resize, for example.

**Comment by The-Compiler** [comment]
I can't reproduce this, and your screenshot seems to be broken somehow :wink:

Does it also happen with `--temp-basedir -s qt.force_software_rendering chromium`? If so, what about `qt-quick` or `software-opengl` instead of `chromium`?

**Comment by rien333** [comment]
Fixed the screenshot, sorry. Gonna check your suggestion now.

**Comment by rien333** [comment]
All software rendering modes called with `--temp-basedir -s qt.force_software_rendering` exhibit the same behavior. qt-quick seems to get rid of them more quickly though, after a little bit of scrolling. If nobody can reproduce, then this is probably my gpu config or something, although I haven't touched that in a while. (it still happens with compton off, btw)

**Comment by The-Compiler** [comment]
When you press e.g. `;` and wait until the keyhint popup shows up, then hide it again via esc: Do you get such artifacts as well?

**Comment by rien333** [comment]
Nope, the keyhint popup window does not leave any strange results behind and works normally. I'll try if I can find any other UI elements that leave weird artifacts.

**Comment by The-Compiler** [comment]
This smells like a QtWebEngine bug of some sorts - maybe it doesn't correctly mark the affected regions for repainting or something... However, I have no idea why it wouldn't happen for the keyhint widget or the completion in that case.

**Comment by rien333** [comment]
hm, I just downgraded from the latest git build to the latest stable release (1.6.3), and this problem goes away. So it might not be a problem with QtWebEngine after all?

**Comment by jgkamat** [comment]
Rijnder Wever writes:

> hm, I just downgraded from the latest git build to the latest stable release 
> (1.6.3), and this problem goes away. So it might not be a problem with 
> QtWebEngine after all?

Can you try bisecting to the first broken commit? Maybe it's related to 
71006ad

**Comment by rien333** [comment]
Yeah I'll try bisecting when I have a bit of time! It's probably not related to  71006ad (which is from March), given that my problem seemed to have been introduced between the latest HEAD and version 1.6.3 (which was released ~27 days ago)

**Comment by jgkamat** [comment]
Rijnder Wever writes:

> given that my problem seemed to have been introduced between the latest HEAD 
> and version 1.6.3 (which was released ~27 days ago)

1.6.3 is not cut from master, its cut from the 1.6.x branch

**Comment by rien333** [comment]
After bisecting, I've found that the commit that introduced the problem is 2dd8966fdcf11972062c540b7a787e4d0de8d372. I started qutebrowser with `python -m qutebrowser -T` in my repo copy, so it used my system-wide qt-libraries.

**Comment by jgkamat** [comment]
Rijnder Wever writes:

> After bisecting, I've found that the commit that introduced the problem is 
> 2dd8966.

Unfortunately I don't think I'll be able to fix that (other than just 
reverting that commit) because I think it should be fine, and I cant repro on 
any of my machines. However, it does pin down this to be something related to 
qstylesheets, which will be useful to anyone trying to triage this futher. The 
odd thing is that the only change for webengine in that commit is changing how 
the background color of the tabbar is set, not the webview.

> I started qutebrowser with python -m qutebrowser -T in my repo copy, so it
> used my system-wide qt-libraries.

Could you try with qt 5.12.3 and see if the issue persists?

**Comment by rien333** [comment]
Well, no idea what fixed this, but today qutebrowser 1.7.0 dropped in the arch repo's and the problem is not present anymore. Maybe it was a weird combination of some dependencies and the commit I bisected it to (https://github.com/qutebrowser/qutebrowser/commit/2dd8966fdcf11972062c540b7a787e4d0de8d372) .

**Comment by rien333** [comment]
Nevermind, a reboot brought back the issue oddly enough.

**Comment by The-Compiler** [comment]
I'm also quite confused about that commit introducing it.

Especially since the issue seems flaky in some way, can you please verify again that it goes away when you do `git checkout 2dd8966fdcf11972062c540b7a787e4d0de8d372~1` and comes back with `git checkout 2dd8966fdcf11972062c540b7a787e4d0de8d372`?

If that's the case, can you please try the following:

- `git checkout 2dd8966fdcf11972062c540b7a787e4d0de8d372~1 -- qutebrowser/mainwindow/tabwidget.py`
- Edit `qutebrowser/config/configdata.yml` to change `type: QssColor` back to `type: QtColor` under `colors.tabs.bar.bg`

Thanks!

**Comment by rien333** [comment]
Cool, gonna try that. For now I just revert the commit before I build:
```bash
git revert --no-edit --strategy=recursive -Xours 2dd8966fdcf11972062c540b7a787e4d0de8d372
```
The merge strategy parameters are not totally correct, but I haven't encountered any problems issues by reverting the commit in this way.

**Comment by miseran** [comment]
I'm having the same issue since upgrading to 1.7. Taking the steps suggested by @The-Compiler above appears to fix it. Also, the issue seems to only occur when using fractional DPI scaling, i.e. `export QT_SCALE_FACTOR=1.25`.

**Comment by The-Compiler** [comment]
@miseran thanks for the hint (hah!) - I can reproduce with `QT_SCALE_FACTOR=1.25 python3 -m qutebrowser --temp-basedir reddit.com` indeed.

**Comment by rien333** [comment]
Ah that it explains it! I do have that env var set.

**Comment by rien333** [comment]
Not fixed in Qt 5.13.1 unfortunately.

**Comment by rien333** [comment]
Might be fixed in master (+ a few Qt updates later)? @miseran do you still have this  issue with the newest commit from qutebrowser  and Qt 5.13.2?

**Comment by miseran** [comment]
Yes, the issue still occurs on master, with Qt 5.13.2.

**Comment by The-Compiler** [comment]
FWIW I cannot reproduce this anymore with the Qt 5.14 beta.

**Comment by rien333** [comment]
Fixed in Qt 5.14.

**Comment by rien333** [comment]
Indeed, fixed in Qt 5.14.

**Comment by The-Compiler** [comment]
Someone else just reported this as well - I'd like to see if we can work around it somehow (without reverting the commit entirely).

**Comment by rien333** [comment]
Can this be closed yet?

**Comment by The-Compiler** [comment]
I'd rather keep it open for now, since people will probably still use Qt versions older than 5.14 for a while (on LTS distributions and such) and some kind of workaround should be possible.

**Comment by The-Compiler** [comment]
Support for Qt < 5.15 is now removed.
