### ISSUE TITLE
qutebrowser doesn't warn that it's blocking popups

### ISSUE THREAD

**Issue by lufte** [qutebrowser/qutebrowser#4885]
**Version info (see `:version`)**:
```
qutebrowser v1.6.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.3
Qt: 5.11.3
PyQt: 5.11.3

sip: 4.19.14
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-4.19.0-5-amd64-x86_64-with-debian-10.0, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/lufte/.cache/qutebrowser
config: /home/lufte/.config/qutebrowser
data: /home/lufte/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes
**Description**

I was using a site that relies on opening windows/tabs from javascript to work, which I didn't know. Since I was getting no warning that qutebrowser was blocking that (due to the `content.can_open_tabs_automatically` setting that I found later), I thought the site was broken. 

Is it possible to raise a message/warning stating that a popup window is being blocked? 
**How to reproduce**

Just open any site that opens windows from javascript without user interaction, for example
```
<html>
<script>
window.open('https://qutebrowser.org')
</script>
</html>
```

**Comment by The-Compiler** [comment]
This isn't possible I'm afraid - see [[QTBUG-69768] Allowing popups interactively - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-69768)

**Comment by lufte** [comment]
I see, what a shame. Thanks anyway!
