### ISSUE TITLE
per-url toggle javascript.enabled not remembered after restart

### ISSUE THREAD

**Issue by davidsierradz** [qutebrowser/qutebrowser#4889]
**Version info (see `:version`)**:
```
qutebrowser v1.6.3
Git commit: 88f5433d3 (2019-07-02 11:15:13 +0200)
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.3
Qt: 5.12.4 (compiled 5.12.3)
PyQt: 5.12.2

sip: 4.19.17
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.1.266 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: Qt5CTProxyStyle
Platform: Linux-5.1.15-1-MANJARO-x86_64-with-arch-Manjaro-Linux, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```
**Does the bug happen if you start with `--temp-basedir`?**:

No, I'm guessing because I have `c.content.javascript.enabled = False` in my `config.py`

**Description**

With javascript disabled by default with `c.content.javascript.enabled = False`, if I want to permanently enable a site's javascript I should be capable of toggle the setting with `tSH`, but after restarting the browser, the site goes back to disabled javascript (as default).

From the FAQ, I think this should work (?):

```
How can I get No-Script-like behavior?

To disable JavaScript by default:

:set content.javascript.enabled false
The basic command for enabling JavaScript for the current host is tsh. This will allow JavaScript execution for the current session. Use S instead of s to make the exception permanent. With H instead of h, subdomains are included. With u instead of h, only the current URL is whitelisted (not the whole host).
```

**How to reproduce**

1. Set `c.content.javascript.enabled = False` in `config.py`
2. Go to https://www.whatismybrowser.com/detect/is-javascript-enabled
3. JavaScript is disabled
4. Run `tSH` to enable JavaScript
5. Restart browser
6. Go to same site
7. JavaScript is disabled (should be enabled)

Thanks

**Comment by The-Compiler** [comment]
Do you load `autoconfig.yml` in your `config.py`? See https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#loading-autoconfigyml

**Comment by davidsierradz** [comment]
I didn't, thanks!
