### ISSUE TITLE
Mouse hovering stopped working over GitHub reactions

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4890]
**Version info (see `:version`)**: 1.6.3.r492.g093fe765f-1

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

**How to reproduce**

Put your mouse above a thumb up or other reaction on a GitHub issue. The name(s) of the author(s) of the reaction should appear (and used to appear), but haven't done so for the past few weeks.

**Comment by The-Compiler** [comment]
See [[QTBUG-75894] QtWebEngine claims to not support hover via CSS queries - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-75894) - I managed to fix it in Qt, but the fix landed in Qt 5.13.1 (planned for mid-August).

**Comment by prosoitos** [comment]
Oh great. Thank you!

**Comment by alexjp** [comment]
@The-Compiler ,should this be working ?

I don't seem to have mouse hover on github both on reactions and on profile pics ( hovering over the profile pic or nick/name ).

I am using:
```
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from override)
Qt: 6.5.2

CPython: 3.10.12
PyQt: 6.5.1
```

latest commit ( I usually follow git commits )

**Comment by mschilli87** [comment]
@alexjp: I guess opening a new discussion rather than replying to a similar bug that was fixed years ago would have been better. However, I can confirm that I get mouseover popups in any of the three cases you described.

I am on older versions though:

```
qutebrowser v2.5.2
Git commit: 29f4bec18 on qt6-v2 (2023-01-30 15:12:38 +0100)
Backend: QtWebEngine 6.3.1, based on Chromium 94.0.4606.126 (from api)
Qt: 6.3.1

CPython: 3.11.2
PyQt: 6.3.1
```

So maybe this is a recent regression.

**Comment by The-Compiler** [comment]
This is most definitely unrelated to this issue, yeah. Works fine for me on the same versions though.

Makes me wonder if it's somehow connected to [this funny issue](https://www.reddit.com/r/qutebrowser/comments/159zxm1/cursor_is_pointeronly_if_mouse_exits_right_or/) (which I can reproduce, but also doesn't trigger what @alexjp describes for me):

> If my mouse leaves the qutebrowser window via the right or bottom edge, then re-enters the window, the cursor no longer changes when hovering over links or in text areas etc.. If I exit the window via the left or top edge, it fixes the problem.

**Comment by alexjp** [comment]
@mschilli87 @The-Compiler sorry if adding here and not opening a new issue was a mistake. If wanted, I can do that!

Weird that both aren't being able to reproduce. Any ideas of what info I should log to help know what is happening ?
