### ISSUE TITLE
Allow to select Media device in the promp

### ISSUE THREAD

**Issue by vexii** [qutebrowser/qutebrowser#4892]
the Media devices promp that allows websites to record video/audio don't allow you to select what device to use. normaly this is not a problem, but on my thinkpad when using the dock the mic changes index (i also use usb mics from time to time) and the first video device is the inferred camara, rendering it useless for communication

**Comment by The-Compiler** [comment]
See [[QTBUG-70077] QtWebEngine should provide a list of capture devices - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-70077)
