### ISSUE TITLE
colors.hints.match.fg doesn't work with rgb values

### ISSUE THREAD

**Issue by UnicodeAlt255** [qutebrowser/qutebrowser#4893]
**Version info (see `:version`)**
qutebrowser v1.6.3
Git commit: 4b402de3d (2019-07-05 12:10:00 +0200)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.12.3

sip: 4.19.17
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/user/.local/share/qutebrowser/user/cache
config: /home/user/.local/share/qutebrowser/user/config
data: /home/user/.local/share/qutebrowser/user/data
runtime: /home/user/.local/share/qutebrowser/user/runtime
system data: /usr/share/qutebrowser

Uptime: 0:02:52

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
`colors.hints.match.fg` doesn't work with rgb values.

**How to reproduce**

`qutebrowser --temp-basedir`
`:set colors.hints.match.fg "rgb(242, 119, 112)"`

It should be red, but the color appears black.

`:set colors.hints.match.fg red` works fine.

**Comment by toofar** [comment]
`:set colors.hints.fg "rgb(242, 119, 112)"` works for me. Without the quotes it complains unrecognized arguments.

**Comment by UnicodeAlt255** [comment]
> `:set colors.hints.fg "rgb(242, 119, 112)"` works for me. Without the quotes it complains unrecognized arguments.

`colors.hints.match.fg != colors.hints.fg`

**Comment by user202729** [comment]
Reproduced.

The problem is that it's used directly as a HTML color value (in `browser/hints.py`). `#ff0000` works as a workaround.
