### ISSUE TITLE
Qt5 icon themes not properly used?

### ISSUE THREAD

**Issue by billop** [qutebrowser/qutebrowser#4897]
**Version info (see `:version`)**:
```
Version info
qutebrowser v1.6.3
Git commit: 4fdfdf95d (2019-07-06 19:30:04 +0200)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.12.3

sip: 4.19.17
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: Qt5CTProxyStyle
Platform: Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/user/.local/share/qutebrowser/user/cache
config: /home/user/.local/share/qutebrowser/user/config
data: /home/user/.local/share/qutebrowser/user/data
runtime: /home/user/.local/share/qutebrowser/user/runtime
system data: /usr/share/qutebrowser

Uptime: 0:03:11
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qt5 icon themes do not work properly in the download prompt.
The blue folder icon is visible only while clicking. Compared to a well-established Qt5/KDE application such as Krita, this is not how it should be.

##### Breeze
![krita-breeze](https://user-images.githubusercontent.com/12755239/60760112-bf28e900-9fe4-11e9-9a25-add1dbf6890b.png)

##### Papirus
![krita-papirus](https://user-images.githubusercontent.com/12755239/60760113-c3ed9d00-9fe4-11e9-9e2d-7411e9ab886f.png)

##### Breeze
![qutebrowser-breeze](https://user-images.githubusercontent.com/12755239/60760158-bd135a00-9fe5-11e9-9a3e-1c9ab7a0e706.gif)

##### Papirus
![qutebrowser-papirus](https://user-images.githubusercontent.com/12755239/60760159-c1d80e00-9fe5-11e9-85fd-1024dc93e185.gif)

##### Breeze
![qutebrowser-temp-breeze](https://user-images.githubusercontent.com/12755239/60760161-c997b280-9fe5-11e9-9448-010070e813bf.gif)

##### Papirus
![qutebrowser-temp-papirus](https://user-images.githubusercontent.com/12755239/60760163-cdc3d000-9fe5-11e9-857c-357d328fe228.gif)

**How to reproduce**

Install and set a Qt5 icon theme (I tested breeze and papirus).
In qutebrowser, download something and look at the prompt's icons.

**Comment by The-Compiler** [comment]
That's odd. Do you know if this is a Qt 5.13 specific issue, or do/did you see this on Qt 5.12 as well?

**Comment by UnicodeAlt255** [comment]
I haven't used Qt 5.12. Due to mitigating #4903 by disabling qt5ct theming for qutebrowser, I don't run into this issue anymore, although I hope by the time #4903 disappears for me this won't happen either.

**Comment by billop** [comment]
I have no idea why but I don't get this issue anymore.

**Comment by The-Compiler** [comment]
I wonder if this is the same as https://bugs.kde.org/show_bug.cgi?id=177642
