### ISSUE TITLE
Add per-site option for notifications

### ISSUE THREAD

**Issue by Jan-PieterBaert** [qutebrowser/qutebrowser#4898]
Add an option, similar to the option to enable/disable javascript on certain sites, but this time to allow/ask/block notifications

**Comment by jgkamat** [comment]
Jan-Pieter Baert writes:

> Add an option, similar to the option to enable/disable javascript on certain 
> sites, but this time to allow/ask/block notifications

I don't use qt 5.13 yet so I can't test it, but dosen't this already exist as 
content.notifications

**Comment by The-Compiler** [comment]
Yup, it does.
