### ISSUE TITLE
Wayland mouse cursor - scaling and theme

### ISSUE THREAD

**Issue by nostdm** [qutebrowser/qutebrowser#4900]
**Version info**:
```
qutebrowser v1.6.3
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QWindowsStyle
Platform: Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/admin/.cache/qutebrowser
config: /home/admin/.config/qutebrowser
data: /home/admin/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 2:39:14
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

**Window manager:** Sway
**Compositor:** Wayland
**Distro:** Archlinux

When using the qutebrowser together with a Wayland compositor there appear to be two issues with the mouse cursor:

1. The cursor has a 1x resolution while the system is scaled 2x resulting in a pixelated cursor.

2. The cursor theme is not the standard DMZ theme. Since Wayland clients are responsible for painting the mouse cursor, the cursor theme rendered by Qutebrowser doesn't seem to use the standard theme when hovering over hyperlinks or buttons. Normally the cursor would change to a hand-like cursor that looks like this: [DMZ Cursor Theme](http://img05.deviantart.net/c6ca/i/2007/145/c/e/dmz_aa_by_firstfooter.png) but instead it shows up as an oddly shaped left-to-right-tilted hand icon (can't easily take a screenshot of the cursor but it looks like some sort of oldschool cursor theme).

How would I go about changing the cursor theme to standard DMZ and also fixing the cursor scaling for a HiDPI display?

**How to reproduce**

1. Install Sway wayland compositor.
2. Set sway scaling to 2x for HiDPI displays
3. Install Qutebrowser from distro repository
4. Launch Qutebrowser

**Comment by The-Compiler** [comment]
This doesn't sound qutebrowser-specific - do you see the same with other QtWebEngine projects like [KDE Falkon](https://www.falkon.org/)?

**Comment by nostdm** [comment]
Yes, just installed Falkon from Arch repositories and the same thing happens with the cursor. Would this mean that it's a QtWebengine issue?

**Comment by nostdm** [comment]
I managed to fix the issue by installing a DMZ (black) cursor theme under ~/.icons/default/. I think the issue was that I didn't have any cursor themes installed at all and so Qt would fall back on it's own theme which wasn't scaled properly. Closing issue.
