### ISSUE TITLE
Segfault on tab close with qt5-webkit 5.212.0alpha3

### ISSUE THREAD

**Issue by buttjake** [qutebrowser/qutebrowser#4901]
stacktrace: http://ix.io/1O4V

How to reproduce:

1. go to https://megatools.megous.com/
2. close that tab

Works with --temp-basedir, I'm using the latest commit.

**Comment by The-Compiler** [comment]
That looks like a crash deep inside QtWebKit - can you please report it at https://github.com/qtwebkit/qtwebkit/issues instead? FWIW I can't reproduce it.

cc @annulen

**Comment by annulen** [comment]
Cannot reproduce as well. Reported crash happens deep inside GStreamer, which is used for media elements

**Comment by buttjake** [comment]
This might be the same bug as: https://github.com/qutebrowser/qutebrowser/issues/4796 because if you install the gstreamer plugins it's no longer present. The segfaults I used to get thanks to gstreamer on some sites are no longer present but instead appeared on some other sites it was not present before.

However if both of you cannot replicate it that means it's something on my end.
@The-Compiler Can you please try to replicate it with only gst-plugins-base installed or no gstreamer at all when you have some time ? ( I would like to know if it's specific to Arch and from what I recall I remember you mentioning you also use it )

**Comment by The-Compiler** [comment]
I can reproduce on Archlinux when I uninstall `gst-plugins-{good,bad}` indeed.

**Comment by buttjake** [comment]
@annulen Can you try again when you can without `gst-plugins-{good,bad}` if you're not using Arch ?

**Comment by annulen** [comment]
I tried on Gentoo and couldn't reproduce (maybe it was on a different site, I don't remember exactly, but it was similar bug)

But I can try to make experimental patch which you could test yourself, or if you give me vm or container image where it reproduces I could try to fix it there

**Comment by The-Compiler** [comment]
FWIW I can build a patched Archlinux package if needed.

**Comment by buttjake** [comment]
> But I can try to make experimental patch which you could test yourself, or if you give me vm or container image where it reproduces I could try to fix it there
Only if you'd end up merging it and the work you put in is useful for qt-webkit, keeping gst installed is no big deal in the end.
