### ISSUE TITLE
crash at browsing

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#4905]
**Version info (see `:version`)**:
see crash report.

**Does the bug happen if you start with `--temp-basedir`?**:
dunno.

**Description**
browser sometimes crashes.   it happens like, 2-3 times a day.  i **guess** it has to do with my per-domain configuration, but not sure.

**How to reproduce**
dunno.  maybe check the crash report output to figure out what happened.

-------
==== Fault log ====
Fatal Python error: Aborted

Thread 0x00007f5237a02680 (most recent call first):
  File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 154 in qt_mainloop
  File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 144 in run
  File "/usr/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 194 in main
  File "/usr/bin/qutebrowser", line 11 in <module>

==== Timestamps ====
Launch: Wed Jul 10 22:15:11 2019
Crash: Wed Jul 10 22:15:11 2019

==== Version info ====
qutebrowser v1.6.3
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.1.16-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/caveman/.cache/qutebrowser
config: /home/caveman/.config/qutebrowser
data: /home/caveman/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00

==== Config ====
aliases = {"javascript-off": "set -t content.javascript.enabled false", "javascript-on": "set -t content.javascript.enabled true", "night-off": "config-unset -t content.user_stylesheets", "night-on-all": "set -t content.user_stylesheets night-all.css", "night-on-wiki": "set -t content.user_stylesheets night-wiki.css", "proxy-none": "set -t content.proxy none", "proxy-ssh": "set -t content.proxy socks://localhost:8080/", "proxy-tor": "set -t content.proxy socks://localhost:9050/", "q": "close", "qa": "quit", "w": "session-save", "wq": "quit --save", "wqa": "quit --save"}
bindings.commands = {"insert": {"<Escape>": "enter-mode normal ;; jseval --quiet document.activeElement.blur()"}, "normal": {"$": "scroll-to-perc --horizontal 100", "0": "scroll-to-perc --horizontal 0", "<Ctrl+n>": "tab-next", "<Ctrl+p>": "tab-prev", "f": "hint all current", "m": "spawn mpv {url}"}}
colors.completion.category.bg = rgba(0,0,0,0)
colors.completion.category.border.bottom = rgba(0,0,0,0)
colors.completion.category.border.top = rgba(0,0,0,0)
colors.completion.category.fg = white
colors.completion.even.bg = rgba(0,0,0,.8)
colors.completion.fg = lightgray
colors.completion.item.selected.bg = rgba(0,0,0,0)
colors.completion.item.selected.border.bottom = white
colors.completion.item.selected.border.top = rgba(0,0,0,0)
colors.completion.item.selected.fg = white
colors.completion.match.fg = orange
colors.completion.odd.bg = rgba(0,0,0,0)
colors.completion.scrollbar.bg = rgba(0,0,0,0)
colors.completion.scrollbar.fg = rgba(255,255,255,.4)
colors.messages.error.bg = rgba(50,0,0,.7)
colors.messages.error.border = rgba(0,0,0,0)
colors.messages.error.fg = white
colors.messages.info.bg = rgba(0,0,0,.8)
colors.messages.info.border = rgba(0,0,0,0)
colors.messages.info.fg = white
colors.messages.warning.bg = rgba(202,126,0,.7)
colors.messages.warning.border = rgba(0,0,0,0)
colors.messages.warning.fg = black
colors.statusbar.command.bg = rgba(50,0,0,1)
colors.statusbar.command.fg = white
colors.statusbar.command.private.bg = black
colors.statusbar.command.private.fg = white
colors.statusbar.normal.bg = rgba(50,0,0,1)
colors.statusbar.normal.fg = white
colors.statusbar.private.bg = black
colors.statusbar.private.fg = white
colors.tabs.even.bg = black
colors.tabs.even.fg = gray
colors.tabs.odd.bg = black
colors.tabs.odd.fg = gray
colors.webpage.bg = black
completion.scrollbar.width = 6
content.cookies.accept = no-3rdparty
content.headers.user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko)Chrome/71.0.3578.98 Safari/537.36
content.javascript.enabled = false
https://mail.protonmail.com/*: content.javascript.enabled = true
https://cave.mn/*: content.javascript.enabled = true
https://*.alibaba.com/*: content.javascript.enabled = true
https://*.amazon.co.uk/*: content.javascript.enabled = true
content.private_browsing = true
content.user_stylesheets = night-all.css
editor.command = ["urxvt", "-e", "nvim", "{file}"]
hints.min_chars = 2
hints.mode = number
qt.args = ["enable-strict-mixed-content-checking", "autoplay-policy=user-gesture-required"]
spellcheck.languages = ["en-US"]
tabs.background = true
url.default_page = about:blank
url.searchengines = {"DEFAULT": "https://duckduckgo.com/?kae=d&kp=-2&kz=1&k1=-1&kaj=m&kaq=-1&kap=-1&kak=-1&kax=-1&q={}", "alibaba": "https://www.alibaba.com/trade/search?SearchText={}", "aliexpress": "https://www.aliexpress.com/wholesale?SearchText={}", "amazon": "https://www.amazon.com/s?k={}", "bible": "http://biblehub.net/search.php?q={}", "ddg": "https://duckduckgo.com/?kae=d&kp=-2&kz=1&k1=-1&kaj=m&kaq=-1&kap=-1&kak=-1&kax=-1&q={}", "ebay": "https://www.ebay.com/sch/i.html?_nkw={}", "gs": "https://scholar.google.co.uk/scholar?q={}", "gw": "https://www.google.co.uk/search?q={}&hl=en", "ip": "http://{}.ip-adress.com", "maps": "https://www.google.com/maps/place/{}", "sp": "https://www.startpage.com/do/asearch?cmd=process_search&prf=a745d9a940a157783db556532f7b9a67&query={}", "yt": "https://www.youtube.com/results?search_query={}"}
url.start_pages = about:blank

==== Environment ====
LC_CTYPE = en_US.UTF-8
PATH = /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
XDG_RUNTIME_DIR = /run/user/1000
XDG_SEAT = seat0
XDG_SESSION_CLASS = user
XDG_SESSION_ID = 1
XDG_SESSION_TYPE = tty
XDG_VTNR = 1

**Comment by The-Compiler** [comment]
Please get a C++ stacktrace of the issue - see https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc

**Comment by The-Compiler** [comment]
@Al-Caveman Any update?

**Comment by Al-Caveman** [comment]
yes, not much (crashes + restarts).  not planning to debug it (unless someone pays me).

**Comment by The-Compiler** [comment]
Ok, same then.

**Comment by Al-Caveman** [comment]
more info:  it crashes when u have javascript disabled globally, open a nasty site that needs javascript, then run javascript on it.

works with some sites.  maybe if u repeat, u'll see it eventually.

**Comment by Al-Caveman** [comment]
i still didn't debug, but i reproduced this with my case twice:

1.  disable javascript.
2.  start qutebrowser.
3.  enable javascript.
4.  visit https://sputniknews.com/sport/201909201076854869-russian-hockey-mma-takedown-khabib/
5.  wait until all stuff load and do their things.
6.  crash.

**Comment by The-Compiler** [comment]
@Al-Caveman How exactly do you disable/enable javascript?

**Comment by user202729** [comment]
Check if any of your binary executable are corrupted. Similar symptom happened to me when my hard drive is corrupted last time. (If you're using a HDD, try running smartctl to see if there's any problem.)

**Comment by Al-Caveman** [comment]
@The-Compiler  by commands `javascript-off` and `javascript-on`, which are defined in the config above.  the related snippet is:

```
aliases = {"javascript-off": "set -t content.javascript.enabled false", "javascript-on": "set -t content.javascript.enabled true" ...
```

@user202729 running that now... (and yes, using archlinux and HDD)

**Comment by The-Compiler** [comment]
So if you use `:set -t`, how do you turn javascript off without qutebrowser being started? Do you have `content.javascript.enabled = false` set in your config and then start qutebrowser and use your `:javascript-on` command?

**Comment by Al-Caveman** [comment]
@The-Compiler ya.  `content.javascript.enabled = false` as in my config in 1st post (my full config is in 1st post).

**Comment by Al-Caveman** [comment]
the `-t` one is only for the alias.  the alias is executed like a command, e.g. `:javascript-on` or `:javascript-off`.  this way as i interactively enable/disable javascript, it will not change the state of qutebrowser in the future when i restart it.

qutebrowser starts with another config line that says `content.javascript.enabled = false`.  this is not an alias, and not with `-t`.  every time quotebrowser starts, it starts with javascript disabled.  then i interactively enable/disable by the aliases above.
