### ISSUE TITLE
Window not rendered after toggling client side decorations off under wayland

### ISSUE THREAD

**Issue by Emantor** [qutebrowser/qutebrowser#4908]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/7958af59

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Window is not rendering any longer after switching to client side decorations with the wayland backend.

**How to reproduce**
Use sway to toggle border on qutebrowser. After toggling client side decorations off, the window does not seem to be rendered any longer and is instead transparent.

**Comment by The-Compiler** [comment]
How do I toggle the border in sway? Do you see the same issue with [KDE Falkon](https://www.falkon.org/)?

**Comment by Emantor** [comment]
`swaymsg border toggle` should toggle between the different border styles, one of which is csd if qutebrowser is started with the `QT_QPA_PLATFORM=wayland-egl` environment variable set.

**Comment by Emantor** [comment]
It does reproduce with falkon, this maybe a qt problem than.

**Comment by The-Compiler** [comment]
Indeed, I opened [[QTBUG-77030] Quick window stops rendering when turning on/off client side decorations - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-77030)
