### ISSUE TITLE
Qutebrowser open chrome-extension while view pdf 

### ISSUE THREAD

**Issue by peet1234** [qutebrowser/qutebrowser#4910]
**Version info (see `:version`)**:
Version info
qutebrowser v1.6.3
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.12.3

sip: 4.19.17
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.1.266 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: Qt5CTProxyStyle
Platform: Linux-4.19.56-1-MANJARO-x86_64-with-arch-Manjaro-Linux, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/peet/.cache/qutebrowser
config: /home/peet/.config/qutebrowser
data: /home/peet/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Does the bug happen if you start with `--temp-basedir`?**:
no
**Description**
when i want to view or download pdf file , qutebrowser will open chrome-extension 
![2019-07-15_11-07](https://user-images.githubusercontent.com/37007880/61195568-099c1b00-a6f3-11e9-82e9-111c6d3db74a.png)

**How to reproduce**

**Comment by The-Compiler** [comment]
It's a Qt 5.13 feature - I'll disable it for now until qutebrowser can add proper support for it. As a workaround, you can disable `content.plugins`.

Can you share what URL that is exactly? You should see the PDF, not some weird error (without text) like that.

**Comment by peet1234** [comment]
> It's a Qt 5.13 feature - I'll disable it for now until qutebrowser can add proper support for it. As a workaround, you can disable `content.plugins`.
> 
> Can you share what URL that is exactly? You should see the PDF, not some weird error (without text) like that.

Sorry , I can't share The URL , they have customer's information in there. 
btw disable content.plugins working `
