### ISSUE TITLE
Nouveau support with Qt 5.13

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4912]
Looks like the Nouveau workaround might be unneeded with Qt 5.13?

https://bugreports.qt.io/browse/QTBUG-71126

**Comment by mentalisttraceur** [comment]
This would be great - last time I tried qutebrowser on a Linux box with nouveau drivers, the forced software rendering seemed to be intolerably slow. (I imagine it does not get much optimization effort, and is presumably more of a checkbox than a priority for the upstream development, but maybe there were other confounding factors.)

**Comment by freed00m** [comment]
If it was merged to 5.13 and we are running with Qt 5.13, how can we try this?? I still have to run on software/xwayland.

**Comment by The-Compiler** [comment]
@freed00m You should be able to run with `QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1 qutebrowser --temp-basedir`. Let me know how that goes, and if you get GPU acceleration (see e.g. `:open chrome://gpu`)!

**Comment by The-Compiler** [comment]
@freed00m Huh, wait a second - this issue is unrelated to Wayland. The Wayland check is automatically disabled on Qt >= 5.11.2 already. Unless you're using Nouveau on Wayland?

**Comment by freed00m** [comment]
@The-Compiler Yes I am using Nouveau on Wayland and skipwayland and qpa platform are already set.

I thought this is related to wayland / nouveau. I am running wayland with amd open source drivers quite fine.

**Comment by The-Compiler** [comment]
@freed00m This is about Nouveau in general (with X or Wayland), so I'm confused by the "I still have to run on [...] xwayland" in your message. You'd still need to use software rendering, xwayland or not.

You shouldn't need `QUTE_SKIP_WAYLAND_CHECK=1` if you're on Qt >= 5.11.2, but you might want to test with `QUTE_SKIP_NOUVEAU_CHECK=1` instead.

**Comment by freed00m** [comment]
@The-Compiler 

Ok, I have tried to run qutebrowser on two machines, one with amd card and one with nvidia nouveau.

The distributions are same and packages are same versions, even environment variables such as QT_WAYLAND_DISABLE_WINDOWDECORATION and QT_QPA_PLATFORM.

Didn't know about skip nouveau check, will try right away. :)

**Comment by freed00m** [comment]
@The-Compiler with the skip nouveau variable it launches and runs fine :) thx

Though the chrome://gpu says that I don't have HW accel

```
Data exported | 2019-09-09T11:43:56.105Z
-- | --
Chrome version | qutebrowser/1.7.0
Operating system | Linux 5.2.13-1-MANJARO
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/5540b58bbc57c34c02929d9c7997fed8b4737efb/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/5540b58bbc57c34c02929d9c7997fed8b4737efb/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | unknown hash
2D graphics backend | Skia/73 636ee33902ddc27fd9683d250ceb23f65467488b-
Command Line | /usr/bin/qutebrowser --reduced-referrer-granularity --browser-subprocess-path=/usr/lib/qt/libexec/QtWebEngineProcess --disable-setuid-sandbox --enable-threaded-compositing --disable-zero-copy --disable-gpu-memory-buffer-compositor-resources --disable-gpu-memory-buffer-video-frames --enable-features=AllowContentInitiatedDataUrlNavigations --disable-features=SurfaceSynchronization --disable-features=SurfaceSynchronization,VizDisplayCompositor --disable-features=SurfaceSynchronization,VizDisplayCompositor,MojoVideoCapture --disable-features=SurfaceSynchronization,VizDisplayCompositor,MojoVideoCapture,UserActivationV2 --disable-features=SurfaceSynchronization,VizDisplayCompositor,MojoVideoCapture,UserActivationV2,BackgroundFetch --disable-features=SurfaceSynchronization,VizDisplayCompositor,MojoVideoCapture,UserActivationV2,BackgroundFetch,UsePdfCompositorServiceForPrint --create-default-gl-context --use-gl=egl --in-process-gpu --gpu-preferences=KAAAAAAAAACiAAAAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --use-gl=egl

```

**Comment by The-Compiler** [comment]
Looks like hardware acceleration with Nouveau is disabled in Chromium for all versions nowadays: https://chromium-review.googlesource.com/c/chromium/src/+/1231938/

So even if qutebrowser removed the check, Chromium would still disable hardware rendering anyways.

Do you see any difference in the output between:

```
QT_QPA_PLATFORM=wayland qutebrowser --temp-basedir -s qt.force_software_rendering chromium chrome://gpu
```

and

```
QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1 qutebrowser --temp-basedir chrome://gpu
```

(you should get no startup warning in either case)?

**Comment by freed00m** [comment]
Correct but what worries me is the Feature status

for `QT_QPA_PLATFORM=wayland qutebrowser --temp-basedir -s qt.force_software_rendering chromium chrome://gpu`

```
Graphics Feature Status
Canvas: Software only. Hardware acceleration disabled
Flash: Software only. Hardware acceleration disabled
Flash Stage3D: Software only. Hardware acceleration disabled
Flash Stage3D Baseline profile: Software only. Hardware acceleration disabled
Compositing: Software only. Hardware acceleration disabled
Multiple Raster Threads: Disabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Out-of-process Rasterization: Disabled
Hardware Protected Video Decode: Disabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Disabled
Surface Control: Disabled
Surface Synchronization: Disabled
Video Decode: Software only. Hardware acceleration disabled
Viz Service Display Compositor: Disabled
WebGL: Disabled
WebGL2: Disabled
```


for `QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1 qutebrowser --temp-basedir chrome://gpu`

```
Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Flash: Unavailable
Flash Stage3D: Unavailable
Flash Stage3D Baseline profile: Unavailable
Compositing: Unavailable
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Out-of-process Rasterization: Unavailable
Hardware Protected Video Decode: Unavailable
Rasterization: Unavailable
Skia Renderer: Disabled
Surface Control: Disabled
Surface Synchronization: Disabled
Video Decode: Unavailable
Viz Service Display Compositor: Disabled
WebGL: Unavailable
WebGL2: Unavailable
```

**Comment by freed00m** [comment]
@The-Compiler If I won't set the QUTE_SKIP_NOUVEAU_CHECK=1 the seccond command will fail with the warning

**Comment by The-Compiler** [comment]
I removed the workaround for Qt >= 5.10 where Qt should handle this properly by itself. However, I guess unless the Nouveau driver gets fixed properly, there's no way around software rendering.
