### ISSUE TITLE
Cannot create quickmark with the letter `n` or `y`

### ISSUE THREAD

**Issue by Awlexus** [qutebrowser/qutebrowser#4916]
**Version info**:
https://paste.the-compiler.org/view/7de4105d

**Description**
When I try to save a quickmark which contains either the letter `n` or`y` it immediatelly closes the dialog and creates a quickmark for `no` or `yes`, depending on the letter entered

**Comment by The-Compiler** [comment]
Works fine for me. Can you reproduce with `--temp-basedir`? Can you show your `qute://configdiff`? Sounds like you bound `n` and `y` in prompt mode (which they aren't by default).

**Comment by Awlexus** [comment]
Here is my configdiff: https://pastebin.com/JAQLqSE6

I cannot start qutebrowser with `--temp-basedir`. It immediatelly brings up a error dialog, because I'm using Nouveau graphics

**Comment by The-Compiler** [comment]
That configdiff confirms my suspicion: You seem to have added bindings for `y` and `n` in prompt mode.

**Comment by Awlexus** [comment]
I also just notices that I describe the big slighly wrong earlier. Updated the issue

**Comment by Awlexus** [comment]
Ok, I'm confused where that comes from, but thanks for pointing me to the solution

**Comment by The-Compiler** [comment]
Do you use a `config.py`? If so, paste that and I might be able to help debug it :wink:

**Comment by Awlexus** [comment]
I already removed the statements, I just don't know where it came from 😅
