### ISSUE TITLE
Passthrough mode, help text always shows <Shift+Escape> even after rebind.

### ISSUE THREAD

**Issue by freed00m** [qutebrowser/qutebrowser#4921]
qutebrowser v1.6.3
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

**Description**

If the binding for passthrough leave is changed, then it is not reflected in the help text.

**How to reproduce**

Go to passthrough mode and read the help text.

**Comment by The-Compiler** [comment]
How can I reproduce this exactly? This works as expected:

```
qutebrowser --temp-basedir ':unbind --mode=passthrough <Shift+Escape>' ':bind --mode=passthrough <Ctrl+x> leave-mode' ':later 1000 enter-mode passthrough'
```

![image](https://user-images.githubusercontent.com/625793/61539368-aa644080-aa3b-11e9-973f-b4fae879a70d.png)

**Comment by freed00m** [comment]
ouh, that works well,

I am using only config.py

config.bind('<Ctrl+q>', 'enter-mode passthrough')
config.bind('<Ctrl+q>', 'leave-mode', mode='passthrough')

**Comment by The-Compiler** [comment]
With that as a `config.py`, indeed I still see "Shift-Escape" in the message - but that's because it was never unbound, and still works fine! With that config, both Ctrl+q *or* Shift+Escape should work.

**Comment by freed00m** [comment]
Shift+Escape should work ?

, hmm I don't know why it doesn't maybe because i am in VirtualBox, I will attempt to reproduce this on my home linux machine.

**Comment by The-Compiler** [comment]
Yep, because you never do `config.unbind('<Shift+escape>', mode='passthrough')`.

You can do `python3 -m scripts.keytester` inside the qutebrowser repository to see what keypress qutebrowser gets when you press Shift+Escape.

However, the message should probably show all bindings if multiple ones are defined.

**Comment by freed00m** [comment]
Glad something positive came out of it.

I tried the keytester and realized I have a HW / SW issue with my keyboard and the Shift+Escape sequence is actualy Shift+°, :O on different keyboard this works fine.

That's what I get if I use prebuild DIY keyboards from china :D sorry again.

**Comment by The-Compiler** [comment]
That sounds odd :laughing: No worries!
