### ISSUE TITLE
Can I specify the "monospace" family for all web pages?

### ISSUE THREAD

**Issue by dgmulf** [qutebrowser/qutebrowser#4924]
Is there a way of achieving this, through a custom stylesheet or otherwise, without having to globally modify the alias using fontconfig?

**Comment by toofar** [comment]
There is the `content.user_stylesheets` (list of string file paths) which you can use to inject CSS into all pages. Have fun with CSS specifity though!

**Comment by The-Compiler** [comment]
You can also use the `fonts.web.family.*` setting to specify alternative fonts if the website only specified a font family. If the website specifies a specific font, you'll need to override it via a stylesheet.
