### ISSUE TITLE
Can't view options for <datalist> elements

### ISSUE THREAD

**Issue by kalekundert** [qutebrowser/qutebrowser#4927]
**Version info:**
qutebrowser v1.6.3
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.0.943 (/home/kale/.local/share/qutebrowser/pdfjs/build/pdf.js)
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.2.0-arch2-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/kale/.cache/qutebrowser
config: /home/kale/.config/qutebrowser
data: /home/kale/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 6:48:47

**Description**
``<input>`` elements with associated ``<datalist>`` elements seem to confuse the logic for whether or not to enter insert mode.  For example, ``<input type="text">`` elements always enter insert mode when clicked on, even though this makes it impossible to click on the button that would display the datalist dropdown menu.  Similarly, ``<input type="time">`` elements don't enter insert mode even when the text in the input field (as opposed to one of the control buttons) is clicked on, which requires the user to manually enter insert mode.

I'd also just be happy to know if there's a work-around for the ``<input type="text">`` case, since that's definitely the more problematic behavior.  In other words, is there a way to forcibly prevent qutebrowser from entering insert mode?

**How to reproduce**
This site has demos of various ``<datalist>``-linked ``<input>`` fields: https://demo.agektmr.com/datalist/

**Comment by The-Compiler** [comment]
This has nothing to do with insert mode, but QtWebEngine doesn't support datalist: [[QTBUG-54433] Support of datalist - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-54433). You're right that insert mode should be entered for time fields though.
