### ISSUE TITLE
Reuse the default page when open a new tab

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#4930]
I have a request similar to https://github.com/qutebrowser/qutebrowser/issues/677, but with the default page. Every time I run in the terminal `qutebrowser --target {auto,tab,tab-bg,tab-silent,tab-bg-silent} URL`, I end up with a least two tabs, one of which is the `default_page`.
I think, it always would be logical to reuse that default page, because it's pretty easy to open it if needed, but when it stays, it consumes the precious space in the tab bar and messes with the tabs navigation.

**Comment by The-Compiler** [comment]
I'm confused by this. Why would the default page even open? The only reason why it would be opened is if you run `:open` without any argument, but that doesn't seem to be the case here. Do you have a `qutebrowser` wrapper script doing something odd?

**Comment by sudo-nice** [comment]
Let me explain more. I have this setting in config.py:
```
c.url.default_page = 'file:///home/user/.config/qutebrowser/start.html'
```
where "start.html" is just a blank page to fit the desktop color.
Now, if I run `qutebrowser URL`, I'll end up with two tabs open, one is "start.html", and the other is "URL".

My propose is to reuse the tab with "start.html" with the URL.

**Comment by The-Compiler** [comment]
Like I said, this shouldn't happen (and doesn't, for me or probably anyone else). What does `which qutebrowser` say?

**Comment by sudo-nice** [comment]
> What does `which qutebrowser` say?

`qutebrowser: aliased to qutebrowser --loglevel critical`

> Why would the default page even open?

I think, there's a misunderstanding here. I run `qutebrowser URL` when qutebrowser is already running. That's why there was the default page already opened. So, the full sequence looks this:

1. Have qutebrowser opened with one tab, which holds the default page.
2. Run in the terminal `qutebrowser URL`.
3. Have qutebrowser with two opened tabs now:
![scr](https://i.imgur.com/KvOcCfc.png)

### Additional info
I tried to comment out the `config.py` and `autoconfig.yml` files with no effect.
qutebrowser v1.7.0

**Comment by toofar** [comment]
You should be able to work around this by running `qutebrowser ":open URL"` instead.

**Comment by sudo-nice** [comment]
@toofar thank you!
That would work in some cases, but that makes it impossible to keep qutebrowser in background:

```
# "--target tab-silent" is ignored:
qutebrowser --target tab-silent ":open example.org"
```

**Comment by The-Compiler** [comment]
Do you mean `url.start_pages` by any chance? If you never run `:open` without argument (or something like Ctrl-T), there's no reason for the `default_page` to be open.

**Comment by sudo-nice** [comment]
@The-Compiler you're right! Sorry, I didn't notice first that I have both set:

```
c.url.default_page = 'file:///home/user/.config/qutebrowser/start.html'
...
c.url.start_pages = 'file:///home/user/.config/qutebrowser/start.html'
```

**Comment by The-Compiler** [comment]
Okay, that clears the confusion up finally! I'm merging this into #677 though, as they are very similar.

**Comment by sudo-nice** [comment]
Thank you!
