### ISSUE TITLE
make option to save url of a download as file attribute

### ISSUE THREAD

**Issue by nsklaus** [qutebrowser/qutebrowser#4932]
hi,
first things first, thanks for doing qutebrowser. it's really nice.

now a little feature request:
when i download stuffs, sometimes i like to keep a track of where did i get that from.
it would be nice if qutebrowser could have an option to enable/disable setting the `user.xdg.origin.url` attribute of files that gets downloaded.
i can always do that manualy myself like shown below, but it's a bit painful to have to do that everytime.
```
 # list attributes of a given file: 
xattr -l myfile

# add attribute to the file
 xattr -w user.xdg.origin.url download_link myfile

# now list again
xattr -l myfile
user.xdg.origin.url: https://some_site/article/irssi
```

that's it..
keep up the good work !

**Comment by The-Compiler** [comment]
It's set correctly for me. What Qt version and backend are you using (see `:version`) and how exactly are you downloading things?

**Comment by nsklaus** [comment]
```
qutebrowser v1.6.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
```

**Comment by The-Compiler** [comment]
Huh, it's weird that disabled JS would make a difference here. What could make a difference is how you trigger the download (clicking/hints/`:download`)

**Comment by nsklaus** [comment]
i've just tried disabling javascript, reloaded the page, downloaded a pic, checked the file attribute, and it was there.
weird. well, it didn't work yesterday, but maybe i jumped to quickly at reporting.
i'll test things more before creating issues again.

**Comment by The-Compiler** [comment]
No worries! I'll close this in the meantime then, but let me know if you find out more!
