### ISSUE TITLE
cannot edit my own issues in github using qutebrowser

### ISSUE THREAD

**Issue by nsklaus** [qutebrowser/qutebrowser#4933]
**Version info** :
qutebrowser v1.6.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

**Does the bug happen if you start with `--temp-basedir`?**:
no, the bug does not happen

**Description**
i cannot seem to be able to edit my own issue on github. 
i tried with keyboard and mouse. 

**How to reproduce**
i just made a feature request [here](https://github.com/qutebrowser/qutebrowser/issues/4932) on this repo,
then i wanted to edit my text a bit.. 
you have the '3 dots' button on the upper right of the post,
i activate it, the menu pops up, i can see two choices, i select "edit", 
and nothing happens. i cannot edit my issue.

**Comment by jgkamat** [comment]
nsklaus writes:

> **Does the bug happen if you start with `--temp-basedir`?**:
> no, the bug does not happen

If the bug dosen't happen in --temp-basedir, there may be something in your 
config, data, or cache directory causing the issue. Could you try moving those 
one at a time and seeing which one is the issue? If it's config, you will want 
to bisect your config. The locations can be found in :verison

**Comment by nsklaus** [comment]
@jgkamat
ok, i've just tried, i moved each dir away, one at a time, 
the problem is with the config.
i have no idea how to do a bisect, though. can you tell me ?

**Comment by jgkamat** [comment]
nsklaus writes:

> i have no idea how to do a bisect, though. can you tell me ?

You can do that by removing half of your config at a time, trying to find the 
config change that causes the issue. Can you pastebin your qute://configdiff ?

**Comment by nsklaus** [comment]
the cause was javascript disabled.
sorry for the disturbance.
