### ISSUE TITLE
Add `-p, --private` option to `tab-give`

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#4935]
When `tab-give` is issued without a *`win-id`* argument, the current tab gets detached into a new window. It would be nice to have a `-p, --private` option that would make the new window private.

**Comment by The-Compiler** [comment]
Out of curiosity, what's your usecase for this? If it was open previously non-privately, it's already in your history and such anyways, no?

**Comment by brianbuccola** [comment]
It's less about history and more about cookies. Typical use case is:

- open a link to a news article (non-privately)
- see a big banner blocking the article saying "You have 0 free articles left! Please subscribe!"
- re-open the link in a private window, and read for free

:smiley:

(FWIW, I do support and subscribe to several newspapers and journals, but there's just too many to pay for all of them.)

**Comment by The-Compiler** [comment]
I see! I usually use `:open -p {url}` for that, so I'm not sure if `:tab-give` really needs support for it. In the future, `:tab-give` might make it possible to move tabs without needing to reload the content, but that won't work when making a non-private tab private.

**Comment by brianbuccola** [comment]
Ah, good point. So maybe I'll just use this:

```
:open -p {url} ;; tab-close
```

**Comment by Zeadar** [comment]
Sorry to rudely butt in but woudn't it be more approperiate with a clear-cookies {url} function for this usecase?

**Comment by brianbuccola** [comment]
For this particular use case, yes, probably, and I would certainly love to have such a command for independent reasons. (Right now, if I need to clear the cookies for a particular site, I open up the site, run `:inspector`, and clear the site data/cookies.)

However, I could imagine cases where you want to re-open the current page privately without clearing the cache. For example, sometimes I'll google something (while logged into google), and decide that I actually want to see the non-personalized results, and for that I'll re-run the search in private mode. (You can also change your google search settings, but this seems to be more cumbersome because then you have to remember to change them back.)

**Comment by The-Compiler** [comment]
@Zeadar See #58 for that, but clearing cookies for a specific URL might not be possible to implement (at least not without having to restart qutebrowser).

**Comment by toofar** [comment]
I think it would be possible. https://doc.qt.io/qt-5/qwebenginecookiestore.html
You can delete cookies, which isn't particularly useful on its own but you can register for `cookieAdded` then call `loadAllCookies()` to get a list of them all and if adding a filter then calling `loadAllCookies()` works to filter them that could be useful too.

**Comment by wangw469** [comment]
> It's less about history and more about cookies. Typical use case is:
> 
> * open a link to a news article (non-privately)
> * see a big banner blocking the article saying "You have 0 free articles left! Please subscribe!"
> * re-open the link in a private window, and read for free
> 
> 😃
> 
> (FWIW, I do support and subscribe to several newspapers and journals, but there's just too many to pay for all of them.)

I just found most of thoes "You have 0 free articles left! Please subscribe!" depends on javascript to function, and it's much more convinent to pass these paywall like this:
:set --pattern=*://www.economist.com content.javascript.enabled false

No need to open new private tab.
Since this command can be saved in autoconfig.yml by :w, we only need to set once for each news sites, back up the autoconfig.yml, then use everywhere.

Hope this helps:)
