### ISSUE TITLE
Qutebrowser crashing when asking for notification permission in a private session

### ISSUE THREAD

**Issue by SilverFishCat** [qutebrowser/qutebrowser#4938]
Expected behavior:
The browser shows a notification permission dialog whether it's on private or non private session, and doesn't crash.

Actual behavior:
If on a private session, it crashes qutebrowser. On a regular session, the dialog shows up but is dismissed when a different window is selected.

How to reproduce:
1) Open a new private session
2) Open a tab for some website with notification (for me this happens with mastodon)

==== Exception ====
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 833, in _on_feature_permission_requested
    abort_on=[self._tab.abort_questions])
  File "/usr/lib/python3.7/site-packages/qutebrowser/browser/shared.py", line 240, in feature_permission
    option=option)
  File "/usr/lib/python3.7/site-packages/qutebrowser/utils/message.py", line 165, in confirm_async
    question = _build_question(**kwargs)  # pylint: disable=missing-kwoa
  File "/usr/lib/python3.7/site-packages/qutebrowser/utils/message.py", line 101, in _build_question
    raise ValueError("Need 'url' given when 'option' is given")
ValueError: Need 'url' given when 'option' is given

==== Timestamps ====
Launch: Fri Jul 26 23:20:03 2019
Crash: Sat Jul 27 00:03:39 2019

==== Version info ====
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.2.228 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.2.2-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Uptime: 0:43:35

==== Commandline args ====
--json-args {"basedir": null, "config_py": null, "version": false, "temp_settings": [], "session": null, "override_restore": true, "target": null, "backend": null, "enable_webengine_inspector": false, "json_args": null, "temp_basedir_restarted": null, "loglevel": "info", "logfilter": null, "loglines": 2000, "debug": false, "json_logging": false, "color": true, "force_color": false, "nowindow": false, "temp_basedir": false, "no_err_windows": false, "qt_arg": null, "qt_flag": null, "debug_flags": [], "command": [*a bunch of old tabs from the last crash*], "url": []}

note: This crash is only present on v1.7.0. previous version was not affected.

**Comment by The-Compiler** [comment]
I still can't reproduce this - but can you please verify that 068f3ded896aa70cbc644674803cdeb6389d6561 fixes it (e.g. by testing with qutebrowser-git)?

**Comment by SilverFishCat** [comment]
Crash not present on 068f3ded8, but neither on the previous commit e08f3da1e. I'll try and see if I can pinpoint the exact commit.

**Comment by SilverFishCat** [comment]
No crash on 068f3de, while it crashes on the previous commit e08f3da1e.
