### ISSUE TITLE
Tooltip popup has white text on white background

### ISSUE THREAD

**Issue by Zeadar** [qutebrowser/qutebrowser#4940]
**Version info (see `:version`)**:
1.7.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Since version 1.7.0 (qt 5.13.0) the tooltip text on youtube uses the qt5 foreground colour while still using a light colour as background.

**How to reproduce**
Set qt5 theme to a dark theme (with white text) and hover mouse pointer over a youtube video title.

![bNCadYc](https://user-images.githubusercontent.com/5130012/62000158-a89c1c00-b0d0-11e9-9cbe-481cac097265.png)
![c1764X2](https://user-images.githubusercontent.com/5130012/62000160-b356b100-b0d0-11e9-9074-8de8ede91935.png)

**Comment by The-Compiler** [comment]
Merging this into #4520
