### ISSUE TITLE
Remove all binds?

### ISSUE THREAD

**Issue by Plupuu** [qutebrowser/qutebrowser#4942]
I'm sorry if this already exists, but I didn't find anything about it. Is there any way to remove all binds so that I can edit / add everything manually?

I want to remove everything so that I can add what I want. Is there any way I can do this?

**Comment by The-Compiler** [comment]
See the [configuring documentation](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#binding-keys):

> To suppress loading of any default keybindings, you can set `c.bindings.default = {}`.
