### ISSUE TITLE
Version pastebin button doesn't work

### ISSUE THREAD

**Issue by Jan-PieterBaert** [qutebrowser/qutebrowser#4950]
**Version info (see `:version`)**:
```
qutebrowser v1.7.0
Git commit: c14f64619 (2019-07-30 12:30:10 +0200)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.2.228 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.2.5-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/jan-pieter/.cache/qutebrowser
config: /home/jan-pieter/.config/qutebrowser
data: /home/jan-pieter/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 4:16:23
```
**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When clicking the "Yank pastebin URL for version info"-button it gives "Failed to pastebin version info: Error transferring https://paste.the-compiler.org/api/create - server replied: Service Not Available" as error

**How to reproduce**
Go to the version information and then click the "Yank pastebin URL for version info"-button

**Comment by jgkamat** [comment]
Works for me (generated via the button):

http://paste.the-compiler.org/view/a1048848

Is http://paste.the-compiler.org/ blocked on your machine?

**Comment by Jan-PieterBaert** [comment]
Now it seems to work, could have been a temporary problem
