### ISSUE TITLE
Readability script - Enlarge page margin

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#4951]
Feel free to close if this is too subjective, but I think the readability of pages is greatly improved if there is a little bit of margin to them. A quick look around other readability scripts shows way more margin than the current output of the userscript has, see e.g. the examples in https://www.maketecheasier.com/tools-make-websites-easier-read/. The current readability userscript  leaves almost no margin. 

Instead of the plain `<body>` tag used now, this can be easily fixed with something like: 
```html
<body style="margin:20;padding:20">
```
Because this is so simple, I might start working on a PR now.

**Comment by The-Compiler** [comment]
No opinion on this myself - feel free! cc @rsteube @kchr who contributed to that userscript previously.

**Comment by rsteube** [comment]
Yes feel free - i once thought of simply using the style of http://bettermotherfuckingwebsite.com/

**Comment by rien333** [comment]
@rsteube Yes, that website is partly what I had in mind when opening this issue.
