### ISSUE TITLE
Fresh install on Void Linux, nothing loads (render process crashed?)

### ISSUE THREAD

**Issue by ElDifinitivo** [qutebrowser/qutebrowser#4952]
I just installed qutebrowser in a fresh install of Void Linux and have had trouble getting it to work. 
[This pastebin](https://pastebin.pl/view/903e575f) contains the output of `qutebrowser --debug` and it seems from what I could tell the render process is crashing (username is obfuscated). The info in this post is run with my custom config, but I also tried it with `~/.config/qutebrowser` removed and the same issue arose.

```
>>> qutebrowser -V
18:36:29 WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-$USERNAME'
18:36:29 WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-$USERNAME'
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.6.9
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: LibreSSL 2.9.2

Style: QFusionStyle
Platform: Linux-4.19.64_1-x86_64-with-libc, 64bit
Linux distribution: void (void)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/$USERNAME/.cache/qutebrowser
config: /home/$USERNAME/.config/qutebrowser
data: /home/$USERNAME/.local/share/qutebrowser
runtime: /tmp/runtime-$USERNAME/qutebrowser
system data: /usr/share/qutebrowser

**Comment by jgkamat** [comment]
Does it work in --temp-basedir ?

**Comment by The-Compiler** [comment]
Do you use musl libc? See https://github.com/void-linux/void-packages/issues/2368

**Comment by ElDifinitivo** [comment]
Ah, didn't see that. Yeah I'm using the musl version. I go from issues with nouveau to musl, I can't escape :P I'll keep on eye on that thread and mess around on my end, see if I can get it to work with software rendering or something for the time being.

**Comment by The-Compiler** [comment]
This is something Void/QtWebEngine will need to fix.

**Comment by stef** [comment]
i fixed this in alpine linux using this patch: https://github.com/alpinelinux/aports/pull/11922
