### ISSUE TITLE
Buffer delete a tab from the top of the list makes following deletions inaccurate

### ISSUE THREAD

**Issue by jcmuller** [qutebrowser/qutebrowser#4958]
**Version info (see `:version`)**: v1.7.0

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
Given you have multiple tabs
and execute `:buffers` or `gt`
when you delete a tab from the top of the list
then the tab is gone
and the list open is shortened by one
*but* the list isn't reordered to take the new indexes into account.

This makes following tab deletions incorrect

**How to reproduce**
- open a few tabs
- `:buffers`
- Highlight an entry from the top
- `Shift-Delete`
- The tab is gone, and the tab indexes are recalculated
- The list isn't updated.
- Delete another tab. 
- The wrong tab will be deleted.

Delete:
![Screenshot_2019-08-09_10-06-39](https://user-images.githubusercontent.com/208500/62784883-75bd3500-ba8d-11e9-8b0c-5b3df7cdfbde.png)
Result:
![Screenshot_2019-08-09_10-07-33](https://user-images.githubusercontent.com/208500/62784927-88376e80-ba8d-11e9-8786-40a2138127d0.png)

Delete:
![Screenshot_2019-08-09_10-08-23](https://user-images.githubusercontent.com/208500/62784990-a9985a80-ba8d-11e9-99ff-ad733344f114.png)
Result:
![Screenshot_2019-08-09_10-09-02](https://user-images.githubusercontent.com/208500/62785027-b9b03a00-ba8d-11e9-8d3e-e439eee1c187.png)

**Comment by arza-zara** [comment]
See https://github.com/qutebrowser/qutebrowser/issues/2986.
