### ISSUE TITLE
Arch user

### ISSUE THREAD

**Issue by SealedJoy** [qutebrowser/qutebrowser#4961]
No issues :)

**Comment by mschilli87** [comment]
Was it *really* necessary to email **this** to [171 people](https://github.com/qutebrowser/qutebrowser/watchers)? :roll_eyes:

**Comment by The-Compiler** [comment]
@mschilli87 Given that the original post was an empty issue template (and this is the first time @SealedJoy ever opened an issue on GitHub), assume it happened by accident. No real harm done, also keep in mind your comment also was mailed to all those people :wink:

**Comment by mschilli87** [comment]
@The-Compiler: You are right. nitpick: my comment was only emailed to people that did not unsubscribe from the issue after reading the first comment. :wink: 
@SealedJoy: Sorry for over-reacting. Don't feel discouraged by grumpy people like me. :wink:

**Comment by SealedJoy** [comment]
@The-Compiler @mschilli87 The bug I thought i'd found turned out to be a manifest of my own incompetence, as did the Opened issue! 
As you mentioned - first time opening an issue and I wasn't sure how to cancel it - tried to conclude it by editing as "no Issues" anyway i'll be sure not to spam you all in future ;) 

thanks for the work on the awesome browser, it has become my go-to !

**Comment by SealedJoy** [comment]
@mschilli87 and not at all, someones got to tell the newbies when they've done messed up :) i didn't even realise this sent to such a big mailing list. My apologies to all.
