### ISSUE TITLE
No Object.values?

### ISSUE THREAD

**Issue by yujiri8** [qutebrowser/qutebrowser#4962]
**Version info (see `:version`)**: v1.7.0-56-g3158700dd, also happened with checking out exactly v1.7.0 (Edit: full output [https://pastebin.com/Xt401Z4n](https://pastebin.com/Xt401Z4n))

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Object.values doesn't seem to be recognized. I wrote a Javascript app that uses it and it worked fine for several other people in different browsers (including Chromium and Firefox), but in Qutebrowser I see `TypeError: Object.values is not a function. (In 'Object.values()', 'Object.values' is undefined)`.
According to [Mozilla's reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values) the method is a standard available in all major browsers except Internet Explorer.

**How to reproduce**
Either load a page that uses it or open dev tools and do `Object.values`. I see "undefined" whereas `Object.keys` is there.

**Comment by jgkamat** [comment]
Can you reproduce in kde falkon? Can you pastebin your :version?

On August 11, 2019 4:07:26 PM PDT, Ryan Westlund <notifications@github.com> wrote:
>**Version info (see `:version`)**: v1.7.0-56-g3158700dd, also happened
>with checking out exactly v1.7.0
>
>**Does the bug happen if you start with `--temp-basedir`?**: yes
>
>**Description**
>Object.values doesn't seem to be recognized. I wrote a Javascript app
>that uses it and it worked fine for several other people in different
>browsers (including Chromium and Firefox), but in Qutebrowser I see
>`TypeError: Object.values is not a function. (In 'Object.values()',
>'Object.values' is undefined)`.
>According to [Mozilla's
>reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values)
>the method is a standard available in all major browsers except
>Internet Explorer.
>
>**How to reproduce**
>Either load a page that uses it or open dev tools and do
>`Object.values`. I see "undefined" whereas `Object.keys` is there.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yujiri8** [comment]
Oh, sorry, I didn't even notice the thing mentioning :version. Here's the pastebin: [https://pastebin.com/Xt401Z4n](https://pastebin.com/Xt401Z4n)

**Comment by yujiri8** [comment]
I'll try out Falkon tomorrow, it's really late here.

**Comment by yujiri8** [comment]
Forgot that paste was from the development build. Installing Qutebrowser from standard FreeBSD repo: [https://pastebin.com/3EvkkK3P](https://pastebin.com/3EvkkK3P) (there are a few notable differences, but the issue is still there).

Also, I ended up trying Falkon tonight (the install was a lot faster than I expected). Object.values is there in Falkon.

**Comment by yujiri8** [comment]
What about you? Am I the only one seeing this?

**Comment by The-Compiler** [comment]
You're using QtWebKit according to your version output, which probably predates `Object.values()`.
