### ISSUE TITLE
Write only clipboard access

### ISSUE THREAD

**Issue by JonnyHaystack** [qutebrowser/qutebrowser#4965]
It would be nice to be able to give JavaScript write-only access to the clipboard instead of the boolean `content.javascript.can_access_clipboard`. This way we could be able to copy things through JavaScript while preventing sites from accessing occasional sensitive data that might be in the clipboard. Sometimes it's unavoidable to copy/paste something sensitive, as undesirable as that is.

I understand this may not be easy, but is it possible?

Also,

>With QtWebEngine, writing the clipboard as response to a user interaction is always allowed.

This doesn't seem to be entirely true because, for example, copying the link to a line of code in GitHub doesn't work with it set to false.

**Comment by The-Compiler** [comment]
This needs to be fixed in QtWebEngine - I opened [[QTBUG-77450] Issues with clipboard permissions - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-77450).

Note that you can set `content.javascript.can_access_clipboard` with URL patterns to only allow it for GitHub.

**Comment by The-Compiler** [comment]
Upstream change for the user gesture part: [WIP: Respect user_gesture for writing to clipboard (If0bbd971) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/270355)

**Comment by amerlyq** [comment]
So, basically upstream allows any site to add any crap into my clipboard now?

I hate it when after copying single word or url from page some sites add literally paragraph of self-marketing information there. That's sick.

Can we somehow disable that completely, like in firefox `dom.event.clipboardevents.enabled` ?
https://www.ghacks.net/2014/01/08/block-websites-reading-modifying-clipboard-contents-firefox/

**Comment by The-Compiler** [comment]
> Can we somehow disable that completely, like in firefox `dom.event.clipboardevents.enabled` ?

Not that I'm aware of, unfortunately (from Chromium's side).
