### ISSUE TITLE
Better Printing

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#4967]
Hi qb community,

I was reading an article which is quite long, and wanted to save as a pdf by printing it down and read it later. I used qutebrowser's `:print` function, and it gave me a nearly 50MB pdf file with wrong format (some words are cut). Reluctantly, I pulled out my `chrome` browser, which rendered me a pdf file smaller than 1MB with the right format.

It might not be the most urgent/important feature the qb community is crying for, but it would be nice if it can handle printing better in the future :)

Cheers!

PS. the article I was reading is [Augmenting Human Intellect: 
A Conceptual Framework By Douglas C. Engelbart](http://dougengelbart.org/content/view/138) for reproducing the issue.

**Comment by The-Compiler** [comment]
Printing is handled by Qt and other underlying libraries. If I click "use system printing dialog" in Chromium, I see the cut off words as well.

Using `:print --pdf` uses Chromium's PDF stuff more directly - there I get a smaller PDF but still with cut words, I remember seeing various related Qt issues. Maybe things will improve with Qt 5.14 (can't test right now, need to rebuild QtWebEngine first), but either way, nothing qutebrowser can fix.

**Comment by jcguu95** [comment]
`:print --pdf` gives the error
```
4:30:51 | ERROR | message | message:error:58 | print: Argument --pdf/-f: expected one argument
```

**Comment by The-Compiler** [comment]
You'll need to pass a filename, e.g. `:print --pdf ~/output.pdf`.

**Comment by The-Compiler** [comment]
Reproduced with what's going to be Qt 5.14 as well, so I opened an upstream issue: [[QTBUG-77519] Content cut off when printing to PDF (wrong page format?) - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-77519)
