### ISSUE TITLE
Paste reads clipboard twice

### ISSUE THREAD

**Issue by pacien** [qutebrowser/qutebrowser#4968]
<details> 
  <summary><strong>Version info (see :version)</strong>: qutebrowser v1.6.2</summary>
<pre>
qutebrowser v1.6.2
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.4
Qt: 5.12.0
PyQt: 5.11.3

sip: 4.19.13
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.10.100 (/nix/store/y9g1nxinxlmwckaicm4vh2wi1qmmyk3l-pdfjs-1.10.100/build/pdf.js)
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.0.2r  26 Feb 2019

Style: QFusionStyle
Platform: Linux-4.19.63-x86_64-with-glibc2.2.5, 64bit
Linux distribution: NixOS 19.03.173298.1f22d5b6f87 (Koi) (unknown)
Frozen: False
Imported from /nix/store/gflfkw0ainpzl8s2sv862wgc917lsdvc-qutebrowser-1.6.2/lib/python3.7/site-packages/qutebrowser
Using Python from /nix/store/96p42644i76jqgdkxjgyl3f0c8n8k16j-python3-3.7.4/bin/python3.7
Qt library executable path: /nix/store/67n8idcnf9damrrjl4j5yaxwdlniq84g-qtbase-5.12.0/libexec, data path: /nix/store/67n8idcnf9damrrjl4j5yaxwdlniq84g-qtbase-5.12.0
OS Version: 

--- /etc/os-release ---
NAME=NixOS
ID=nixos
VERSION="19.03.173298.1f22d5b6f87 (Koi)"
VERSION_CODENAME=koi
VERSION_ID="19.03.173298.1f22d5b6f87"
PRETTY_NAME="NixOS 19.03.173298.1f22d5b6f87 (Koi)"
LOGO="nix-snowflake"

Paths:
cache: /home/kea/.cache/qutebrowser
config: /home/kea/.config/qutebrowser
data: /home/kea/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /nix/store/gflfkw0ainpzl8s2sv862wgc917lsdvc-qutebrowser-1.6.2/share/qutebrowser
</pre>
</details>

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

Qutebrowser reads the clipboard twice instead of once to paste text on X11.

This is annoying when using an external password manager which relies on clipboard access to know when to clear it.

Both the primary (middle-click) and secondary (ctrl+v) clipboards are impacted.

Chromium seems to have the same issue, while Firefox doesn't.

**How to reproduce**

This requires using X11.

0. Run `echo "hi" | xclip -selection clipboard -loop 1 -verbose` in a terminal.
0. Open any webpage with a text field in qutebrowser.
0. In _insert mode_, paste in the text field using either a keyboard shortcut or the context menu.
0. __The clipboard is read, but no text is pasted.__

Retry with `-loop 2` and notice that the text is now pasted.

**Comment by The-Compiler** [comment]
This needs to be fixed in Chromium then, nothing qutebrowser can do about it.

**Comment by The-Compiler** [comment]
Looks like this is not considered a bug from Chromium's side: https://bugs.chromium.org/p/chromium/issues/detail?id=778686

**Comment by Jan-PieterBaert** [comment]
It seems Firefox also does this, so I think it's unavoidable.

**Comment by pacien** [comment]
> It seems Firefox also does this, so I think it's unavoidable.

Pasting in Firefox 68.0.1 in text fields in pages works fine with `-loop 1`.

**Comment by Jan-PieterBaert** [comment]
I'm on Firefox 68.0.2 and there it doesn't work with `-loop 1`.
Btw you can just run `echo "test" | xclip -selection -clipboard -verbose` and then look at the number of requests when pasting.
