### ISSUE TITLE
Renderer process crashed https://cloud.google.com/vision/

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#4972]
**Version info (see `:version`)**:
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Crash on this URL. Under wayland but same with QPA_PLATFROM=xcb

**How to reproduce**

qutebrowser --temp-basedir https://cloud.google.com/vision/
19:19:42 ERROR: Renderer process crashed

**Comment by jgkamat** [comment]
I cannot reproduce, so maybe this is a qt 5.13/14 issue

Can you pastebin your complete :version ?

**Comment by edrex** [comment]
Seems likely
https://paste.the-compiler.org/view/130e1acc

**Comment by The-Compiler** [comment]
I can reproduce and opened [[QTBUG-77671] Renderer process crash on Google Cloud Vision page - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-77671).

**Comment by The-Compiler** [comment]
Fixed for Qt 5.13.2/5.14: https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/271404
