### ISSUE TITLE
qute-pass errors trying to write to a system directory

### ISSUE THREAD

**Issue by vendion** [qutebrowser/qutebrowser#4975]
Version info: https://paste.the-compiler.org/view/2d387adf

**Description**

When trying to use `qute-pass` from this repo, there is an error stating to check the output of `:messages` for details, when checking that log I see the following error:

```
Process stderr:
unable to cache TLDs in file /usr/local/lib/python3.6/site-packages/tldextract/.tld_set: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/tldextract/.tld_set'
Traceback (most recent call last):
  File "/home/vendion/.local/share/qutebrowser/userscripts/qute-pass", line 216, in <module>
    sys.exit(main(arguments))
  File "/home/vendion/.local/share/qutebrowser/userscripts/qute-pass", line 157, in main
    for target in filter(None, [extract_result.fqdn, extract_result.registered_domain, extract_result.ipv4]):
AttributeError: 'ExtractResult' object has no attribute 'fqdn'
```

Not exactly sure why it is trying to write information to that path rather than somewher under _$HOME/.config/qutebrowser_, but it seems odd to expect that path to be user writable.

Also small note but the script points to what seems to be the old repo for the script
```
Dependencies: tldextract (Python 3 module), pass, pass-otp (optional). For
issues and feedback please use: https://github.com/cryzed/qutebrowser-
userscripts. WARNING: The login details are viewable as plaintext in
qutebrowser's debug log (qute://log) and might be shared if you decide to
submit a crash report!
```
when it seems that the script was at somepoint moved from that repo to here

**Comment by The-Compiler** [comment]
The warning about caching is unrelated, see https://github.com/john-kurkowski/tldextract#note-about-caching (I suppose qute-pass could adjust the cache path though).

Not sure about the exception. According to its [changelog](https://github.com/john-kurkowski/tldextract/blob/master/CHANGELOG.md), the `fqdn` property was added in tldextract 2.1.0, maybe you're using an older version?

**Comment by vendion** [comment]
It would seem as though I do in fact have a very stale copy of the
tldextract library installed. I have messaged the package maintainer for my
OS informing them of the very outdated package.

**Comment by vendion** [comment]
After updating tldextract to version 2.1.1 this error no longer happens.
