### ISSUE TITLE
Can't use GitHub

### ISSUE THREAD

**Issue by VincentTam** [qutebrowser/qutebrowser#4977]
**Version info (see `:version`)**:

qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.8
Qt: 5.9.5
PyQt: 5.10.1

sip: 4.19.7
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: Ubuntu 18.04.3 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /tmp/qutebrowser-basedir-x5n8rn7q/cache
config: /tmp/qutebrowser-basedir-x5n8rn7q/config
data: /tmp/qutebrowser-basedir-x5n8rn7q/data
runtime: /tmp/qutebrowser-basedir-x5n8rn7q/runtime
system data: /usr/share/qutebrowser

Uptime: 0:02:00

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

![browsing GitHub with qutebrowser](https://i.stack.imgur.com/66k4H.gif)

I can't edit and preview GitHub comments and upload images.  This is quite inconvenient.

I've tried doing the same thing in Firefox, and it worked, so I'm sure that it's the problem of qutebrowser.

P.S. The above GIF image was uploaded to Stack Exchange, and then linked manually using normal Markdown syntax.

**How to reproduce**

Link to the affected site: Any pages on GitHub displaying posts that I can edit.

**Comment by VincentTam** [comment]
Message from terminal:
```
qutebrowser --temp-basedir
[28892:28978:0823/054635.178679:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[28892:28978:0823/054635.178761:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[28892:28978:0823/054635.178824:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
[28892:28978:0823/054635.181775:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[28892:28978:0823/054635.181832:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: ocsp.digicert.com
[28892:28978:0823/054635.181888:ERROR:nss_ocsp.cc(591)] No URLRequestContext for NSS HTTP handler. host: crl4.digicert.com
05:47:15 ERROR: No search done yet.
05:47:17 INFO: Zoom level: 100%
Gtk-Message: 05:50:03.921: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by jgkamat** [comment]
Vincent Tam writes:

> I can't edit and preview GitHub comments and upload images.  This is quite 
> inconvenient.

> qutebrowser v1.1.1
> Git commit:
> Backend: QtWebEngine (Chromium 56.0.2924.122)
>
> CPython: 3.6.8
> Qt: 5.9.5
> PyQt: 5.10.1

It seems to me like github broke their website on older browsers - not much 
qutebrowser can do about that (other than stop using github).

**Comment by VincentTam** [comment]
> It seems to me like github broke their website on older browsers - not much
qutebrowser can do about that (other than stop using github).

Would you make the first step and migrate your project to GitLab?  Or would you stop using qutebrowser when browsing this repo?

**Comment by jgkamat** [comment]
Vincent Tam writes:

> Would you make the first step and migrate your project to GitLab?  Or would 
> you stop using qutebrowser when browsing this repo?

It's not my decision to make. FWIW, I already have all my larger projects 
(including my integration/fork) there. Gitlab is a lot better than github at 
this sort of thing (qt 5.7.1 still works fine there), but there's no reason 
they couldn't cause the same issue down the line. The only real advantage is 
that we can patch gitlab to fix issues if needed.

**Comment by The-Compiler** [comment]
Works fine with Qt 5.10 (based on Chromium 61) or newer. With Qt 5.9 (Chromium 56) it fails with:

```
[https://github.githubassets.com/assets/github-bootstrap-b49c75cf.js:1] Uncaught SyntaxError: Unexpected token ...
```

This is probably due to GitHub using [Spread syntax in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals), support for which was [added in Chromium 60](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility) (it's also experimental, though!).

Given that Chromium 60 was released in July 2017, I don't think GitHub is to blame for using that features (but it being experimental is a bit odd). I'll contact their support and see what they say.

(Also, no plans for moving away from GitHub - it'd also not fix the actual issue.)

@VincentTam What you could do is [using a tox install](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#tox) instead so you get a newer Qt version. While Qt 5.9 is still [receiving security fixes](https://blog.qt.io/blog/2017/05/11/introducing-long-term-support-qt-5-9/), the Chromium version behind it is getting quite old, so over time, issues with other sites will likely appear as well.

**Comment by VincentTam** [comment]
> Gitlab is a lot better than github at this sort of thing (qt 5.7.1 still works fine there), but there's no reason they couldn't cause the same issue down the line.

@jgkamat

# :+1: for saying that GitLab is better than :octocat:

@The-Compiler Thanks for your advice.  I'm exploring this now.

**Comment by The-Compiler** [comment]
Looks like this wasn't intentional:

> Thanks for writing in to report this, I'm sorry for the trouble. It does look like there's a wider issue affecting JavaScript at the moment. I've escalated this to our engineering team and, while we don't have an ETA, we'll report back once this is resolved.

**Comment by The-Compiler** [comment]
Fixed on GitHub's side:

> We've just deployed a fix which should have resolved the JavaScript issues. If you are still having problems after clearing your cache, please get back to us so we can take a closer look.

(Still doesn't work with Qt 5.7, but that's based on Chrome 49 from early 2016 and might've been broken before - also see #3839)

**Comment by VincentTam** [comment]
@The-Compiler Thanks for all the communications work that you've done!  qutebrowser is a great browser! :smiley:

**Comment by toofar** [comment]
It is also possible to load polyfill scripts via the greasemonky support, not sure if there is one for the particular feature in question here though.

**Comment by huyhoang8398** [comment]
I cannot load the github page in qutebrowser
![image](https://user-images.githubusercontent.com/25379882/162204384-dbe00a50-1086-4026-971a-390dd42476b9.png)
