### ISSUE TITLE
Opening saved files - issues

### ISSUE THREAD

**Issue by piperfw** [qutebrowser/qutebrowser#4978]
As I understand when opening a download `xdg-open` is used, as discussed in [#1211](https://github.com/qutebrowser/qutebrowser/issues/1211). This often doesn't result in a desired result e.g. If I attempt to open a file with a `.sh` extension is just prompts me to re-download the file. Is this expected behaviour?

In [#1211](https://github.com/qutebrowser/qutebrowser/issues/1211) it is also discussed how optional parameter to `:download-open` can be used to specify a program. If I attempt to open the same `.sh` file with `vim` I am presented (in vim) with a 'swap file warning' notifying me that another program may be editing the file (see attached). Any suggestions for working around this?

[swap_error.txt](https://github.com/qutebrowser/qutebrowser/files/3533597/swap_error.txt)

**version information**
qutebrowser v1.7.0i
Backend: QtWebEngine (Chromium 73.0.3683.105)

**Comment by The-Compiler** [comment]
> As I understand when opening a download `xdg-open` is used, as discussed in [#1211](https://github.com/qutebrowser/qutebrowser/issues/1211). This often doesn't result in a desired result e.g. If I attempt to open a file with a `.sh` extension is just prompts me to re-download the file. Is this expected behaviour?

You'll need to configure xdg-open to open them accordingly. If it doesn't know how to open something, it falls back to opening it in your browser.

> In [#1211](https://github.com/qutebrowser/qutebrowser/issues/1211) it is also discussed how optional parameter to `:download-open` can be used to specify a program. If I attempt to open the same `.sh` file with `vim` I am presented (in vim) with a 'swap file warning' notifying me that another program may be editing the file (see below). Any suggestions for working around this?

That looks like you already do have vim open with the same file. FWIW `:download-open termite -e "vim {}"` works fine for me.

**Comment by piperfw** [comment]
Thank you, I cleaned up all vim processes and re-tried and it opens without issue.

Is the action of clicking on a download in the downloads bar the same as running `download-open`? It would be handy if I could change this to e.g. always open in `vim`.

**Comment by The-Compiler** [comment]
> Is the action of clicking on a download in the downloads bar the same as running `download-open`? It would be handy if I could change this to e.g. always open in `vim`.

Yup. Why not [configure](https://wiki.archlinux.org/index.php/XDG_MIME_Applications) `xdg-open` to open `text/x-shellscript` files in vim? Then you'll have the same behavior on all applications on your machine.

**Comment by piperfw** [comment]
Good idea. I don't have a desktop environment so didn't think this would straightforward but now see on the Wiki that `perl-file-mimeinfo` should be installed in this case.

**Comment by The-Compiler** [comment]
Where do you see `perl-file-mineinfo`? It's not on that wiki page and seems like an unrelated perl library to me. FWIW most qutebrowser users (myself included) use xdg-open without any desktop environment.

**Comment by piperfw** [comment]
Oh okay, have you had success in editing it? I was put off by "Because of the complexity of the xdg-utils version of xdg-open, it can be difficult to debug when the wrong default application is being opened" [here](https://wiki.archlinux.org/index.php/Default_applications#xdg-open) but will have a go at changing it after work today.

`perl-file-mineinfo` is discussed on that page but also [xdg-open](https://wiki.archlinux.org/index.php/Xdg-utils#xdg-open) "If you want xdg-open to use XDG MIME Applications without a desktop environment..."

**Comment by The-Compiler** [comment]
Ah, interesting - I don't have that installed but xdg-open still works without any trouble. Using `xdg-mime` to set applications worked fine for me, but I usually edit `~/.config/mimeapps.list` by hand - FWIW here's my current one:

```ini
[Default Applications]
application/pdf=org.pwmt.zathura.desktop
x-scheme-handler/mailto=neomutt.desktop;
x-scheme-handler/http=org.qutebrowser.qutebrowser.desktop;
x-scheme-handler/https=org.qutebrowser.qutebrowser.desktop;
application/vnd.openxmlformats-officedocument.wordprocessingml.document=libreoffice-writer.desktop;
```

where `~/.local/share/applications/neomutt.desktop` is similar to what you'd probably write for vim (or just use `gvim`):

```
[Desktop Entry]
Type=Application
Name=NeoMutt
Icon=email
Exec=neomutt-termite
StartupNotify=true
Categories=Internet;
```

and a `neomutt-termite` helper script:

```bash
#!/bin/bash
termite -e "neomutt '$@'"
```

**Comment by piperfw** [comment]
V. useful info, thanks. Just had a quick go and after a few changes have had success with the desktop entry

```
[Desktop Entry]
Name=Vim-urxvt
Exec=urxvt -e vim %u
#Exec=/usr/share/applications/vim-urxvt
Type=Application
Categories=Utility;TextEditor;
StartupNotify=false
```
The helper script is nice but I couldn't think of why there'd be multiple arguments so I decided not to use (note that I had to specify the full path to the script for it to work). 

Hopefully shouldn't take too long to sort out all my default applications now! I wonder if you can use patterns e.g. `video/*` in `mimeapps.list`...

Edit: Looks like you can!

**Comment by edrex** [comment]
Quick tip: I'm not in kde or gnome so xdg-open kind of sucks.

I dropped this rifle wrapper xdg-open replacement in ~/bin and now qutebrowser opens downloads with rifle:
https://gist.github.com/Xender/0036526699ab970c1b6d

Cheers :)

**Comment by The-Compiler** [comment]
Huh? I'm using xdg-open without any desktop environment just fine, see my comment above.

**Comment by edrex** [comment]
i just have had a lot of issues with the xdg-open script over the years, and prefer rifle.
