### ISSUE TITLE
Single-tab donor window should be closed after tab-take

### ISSUE THREAD

**Issue by jhultman** [qutebrowser/qutebrowser#4979]
Hi, thanks for your work on qutebrowser -- it's one of my favorite open source projects.

I often use `tab-take` to move tabs between windows, but it doesn't work quite as I would expect when the donor window only has one tab. I would prefer that the donor be closed after donating its last tab, but instead the window is kept alive and a duplicate tab is sent to the "taker." Is there any particular reason the donor is kept alive? Here's a little example of what I mean.

Scenario:
![tab-take](https://user-images.githubusercontent.com/27909223/63604611-3ff27300-c59a-11e9-96ba-0a5d0f40bfa8.png)

Actual:
![tab-take-actual](https://user-images.githubusercontent.com/27909223/63604623-45e85400-c59a-11e9-9726-73b79141a7a4.png)

Expected:
![tab-take-expected](https://user-images.githubusercontent.com/27909223/63604668-61ebf580-c59a-11e9-8b21-6116fd1d947a.png)

**Comment by The-Compiler** [comment]
It's consistent with what happens when you try to close the last tab in a window normally (i.e. via `d`). If you prefer the window to be closed in such cases, you can set `tabs.last_close` to `close`.

**Comment by jhultman** [comment]
Awesome, thanks!
