### ISSUE TITLE
Abitlity to Auto dismiss certificate error prompts ?

### ISSUE THREAD

**Issue by freed00m** [qutebrowser/qutebrowser#4980]
Hi,

I use qutebrowser as my main browser and this single behavior is the single worst annoyence I have while using it.

I have some domains blocked via OpenDNS and It's pain to be asked on every little cross origin asset or ad domain component stuff that its certificate does not match.

In my entire 2 years I have never said "yes" on certificate is not trusted and I have seen over a thousands of these prompt.

There could be good differentiation for cross origin domains and host domain behavior on the certificate check.

**Comment by The-Compiler** [comment]
See #3418 - note you can already set `ssl_strict` to `true` (instead of `ask`) for those domains.

**Comment by The-Compiler** [comment]
Oh, and you could probably also block those domains using qutebrowser's host blocker instead (or in addition to the DNS blocking)
