### ISSUE TITLE
Change qutebrowser layout from bash

### ISSUE THREAD

**Issue by Migacz85** [qutebrowser/qutebrowser#4983]
Hi I have this nifty little scripts:

![image](https://user-images.githubusercontent.com/25789997/63684846-d2428300-c7f5-11e9-8b84-b7faf34da706.png)

conigured to switch between dark/light mode in qutebrowser. They working great. However I was thinking it is possible to run this script externaly from bash outside qutebrowser?

Thanks

**Comment by ninewise** [comment]
It is; you can run `qutebrowser ':config-cycle content.user_stylesheets ...'`.

**Comment by Migacz85** [comment]
Brilliant, that was easy :-) Thank you very much!.
