### ISSUE TITLE
links don't work

### ISSUE THREAD

**Issue by tonnerkiller** [qutebrowser/qutebrowser#4988]
I'm on MacOS Mojave 10.14.5 with the latest qutebrowser binary package download.

When I open http://tagesschau.de and hit `f` to go to an article, I don't always get a link.

The link-letters are placed at the article image. In case there is only a text article, clicking on the image would lead me to the article, but if there's also a video or an audio available clicking the image would start that media and not bring me to the respective article which is also available.

Using a mouse I could also click on the article title or on `mehr` to get to the article, but these don't get link-letters upon pressing `f`.

**Comment by The-Compiler** [comment]
Looks like they use a normal link:

```html
<a href="/ausland/brasilien-waldbraende-103.html">
<p class="dachzeile">Waldbrände in Brasilien</p>
<h4 class="headline">"Das ist ein Friedhof"</h4>
<p class="teasertext">Brasiliens Präsident Bolsonaro liefert im Kampf gegen die Feuer im Amazonasgebiet kaum Ergebnisse. G7-Hilfsgelder lehnt er ab - dabei warnen Umweltschützer vor gewaltigen Auswirkungen der Brände. <em>Von Anne Herrberg.</em>
|&nbsp;<strong>mehr</strong>
</p>
</a>
```

but Chromium thinks it has a size of 0x0px:

![image](https://user-images.githubusercontent.com/625793/63767544-494b4a80-c8ce-11e9-94d3-7a63c7b82151.png)

Adding this to #178.
