### ISSUE TITLE
Focus object changed

### ISSUE THREAD

**Issue by annata83** [qutebrowser/qutebrowser#4998]
![error](https://user-images.githubusercontent.com/18301363/64140577-42936a80-cddb-11e9-816c-f9a39a0721fd.png)

Log: 
[qute.txt](https://github.com/qutebrowser/qutebrowser/files/3567537/qute.txt)

**qutebrowser-1.7.0-1
OS: Arch Linux x86_64
Shell: bash 5.0.7**

**Comment by The-Compiler** [comment]
Huh? I don't see any issue here.

**Comment by annata83** [comment]
wait a minute!.. what you mean? it doesn't start.

**Comment by toofar** [comment]
Someone put a bit of effort into clearly explaining the situation in that error dialog. Have you tried pressing the "Force software rendering" button? The chromium bits of webengine apparently doesn't work so good on Nouveau. There is a not that it _might_ work on 5.13, not sure if anyone has tested that. You can try setting the `QUTE_SKIP_NOUVEAU_CHECK=1` environment variable but that could very well lead to less clearly explained errors.

**Comment by annata83** [comment]
Honestly, I couldn't figure it out, of course, I try your suggestions with no luck. Using qutebrowser-git from AUR now!.
Thanks anyway.

**Comment by arza-zara** [comment]
Do you have ~/.config/qutebrowser/config.py file? If you do, try adding `config.load_autoconfig()` or `c.qt.force_software_rendering = 'chromium'`.

> &lt;hpfmn&gt; is it a known issue that qutebrowser doesn't work on nouveau+wayland?
> &lt;The-C0mpiler&gt; hpfmn: no
> &lt;The-C0mpiler&gt; hpfmn: what backend, qutebrowser version, and Qt version? (:version)
> &lt;The-C0mpiler&gt; hpfmn: also, what does "doesn't work" mean?
> &lt;hpfmn&gt; The-C0mpiler: I'm using an up to date archlinux installation
> &lt;hpfmn&gt; and not work means it says that it likes to use software rendering, but clicking on the software rendering button just brings up the dialog again
> &lt;hpfmn&gt; "Failed to start with the QtWebEngine backend"
> &lt;The-C0mpiler&gt; hpfmn: do you have a config.py and not load autoconfig.yml from it?
> &lt;hpfmn&gt; The-Compiler: ok removing the config.py worke
> &lt;hpfmn&gt; *worked
> &lt;hpfmn&gt; and now I added the load_autoconfig() -&gt; now it also works with config.py
> &lt;hpfmn&gt; thx
