### ISSUE TITLE
Duplicate dock icons when qutebrowser is running and pinned to the dock (Gnome).

### ISSUE THREAD

**Issue by dbeley** [qutebrowser/qutebrowser#5001]
**Version info (see `:version`)**:
1.7.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
On gnome 3.32.2, when qutebrowser is pinned to the dock, the qutebrowser icon is displayed twice when qutebrowser is running.

**How to reproduce**
Pin qutebrowser to the Gnome dock and run it. The icon is appearing twice : one will be the pinned icon, the other one the running instance (at least on my machines). It has been tested on two computers running arch and gnome 3.32.2

Adding `StartupWMClass=qutebrowser` to the org.qutebrowser.qutebrowser.desktop file correct the issue. It's just a simple change (link to my commit on my fork) : https://github.com/dbeley/qutebrowser/commit/413aafb652dad5f944e9a11468a97b30024f4d70

**Comment by Jan-PieterBaert** [comment]
feel free to make a pull request to fix this issue :)

**Comment by The-Compiler** [comment]
Looks correct and simple enough, so I cherry-picked it to 6a72704b90b560383da641b9c6808542e7dbec84 - thanks for the analysis and the fix, @dbeley!
