### ISSUE TITLE
dictcli.py: Found a dictionary with a malformed name

### ISSUE THREAD

**Issue by f380cedric** [qutebrowser/qutebrowser#5002]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/6474bbe6
**Does the bug happen if you start with `--temp-basedir`?**:
Unrelated
**Description**
When two language versions exist, it should determine the lastest one to pick. However, the regex seems to be malformed. Indeed, when two versions exists, this line is executed to determine if previous one is older than current one:

https://github.com/qutebrowser/qutebrowser/blob/f2b38a6c268f587937d3e5500178f587fa76e084/scripts/dictcli.py#L172

The `spell.version` method extract the version from filename with this regex:

https://github.com/qutebrowser/qutebrowser/blob/f2b38a6c268f587937d3e5500178f587fa76e084/qutebrowser/browser/webengine/spell.py#L32

and the filename is extracted from chromium upstream json with this regex:

https://github.com/qutebrowser/qutebrowser/blob/f2b38a6c268f587937d3e5500178f587fa76e084/scripts/dictcli.py#L145-L147

the extension _.bdic_ is excluded from filename but is required in `spell.version`.

```python3
python3 dictcli.py install en-US
Found a dictionary with a malformed name: sh-3-0
Found a dictionary with a malformed name: sh-4-0
Traceback (most recent call last):
  File "dictcli.py", line 284, in <module>
    main()
  File "dictcli.py", line 267, in main
    languages = available_languages()
  File "dictcli.py", line 181, in available_languages
    if latest_yet(code2file, code, filename):
  File "dictcli.py", line 172, in latest_yet
    return spell.version(code2file[code]) < spell.version(filename)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

```
**How to reproduce**
 - exec `dictcli.py install <code>`

**Comment by The-Compiler** [comment]
Could you give #4987 a try?

**Comment by f380cedric** [comment]
Just did. I patched files _qutebrowser/browser/webengine/spell.py_,  _qutebrowser/browser/webengine/webenginesettings.py_ and _scripts/dictcli.py_ on 1.6.3 and dictcli.py was able to install the corresponding bdic (but patching dictly.py seems to be enough).
