### ISSUE TITLE
External command hooks for tabs and the address bar

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#5003]
Add config parameters that allow us to specify external commands to execute every time the following events happen:

* A tab is selected as active/viewed.
* A tab is created.
* A tab is closed.
* A URL is hovered on by the mouse (or hints).
* Page is scrolled.

With the following information passed to the commands (perhaps JSON as fed via STDIN):

* Tabs titles.
* Items in the status/address bar.

Why?

* This will allow us to hide tabs, and status bars, and, instead, integrate them into the GUI elements of our desktop environment.  E.g. I could export it into the tasks bar, or i3status.

**Comment by The-Compiler** [comment]
See #30
