### ISSUE TITLE
Referer set to same-domain not working

### ISSUE THREAD

**Issue by q3cpma** [qutebrowser/qutebrowser#5004]
Hello
**Version info (see `:version`)**:
```
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.6.6
Qt: 5.12.3
PyQt: 5.12.2

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.1
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.0.2r  26 Feb 2019

Style: Qt5CTProxyStyle
Platform: Linux-5.2.11-gentoo-x86_64-AMD_Ryzen_7_2700X_Eight-Core_Processor-with-gentoo-2.6, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib64/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3.6
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /tmp/runtime-user/qutebrowser
```
**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
Setting `content.headers.referer` to `same-domain` doesn't seem to work. Tested with https://ipleak.net/
Setting it to never works.

**How to reproduce**

**Comment by q3cpma** [comment]
Search "ipleak" on duckduckgo.com and follow the link, duckduckgo.com will be sent in the referer header field. Startpage doesn't trigger this (maybe it is stripped in some way).

**Comment by The-Compiler** [comment]
From the documentation:

> `same-domain`: Only send the Referer for the same domain. This will still protect your privacy, but shouldn’t break any sites. **With QtWebEngine, the referer will still be sent for other domains, but with stripped path information.**

**Comment by q3cpma** [comment]
Oh I see. Well, I guess it's never for now.

**Comment by The-Compiler** [comment]
Starting with Qt 5.12.4/5.13.1, qutebrowser could likely fully strip the referer, see #4793 for that.
