### ISSUE TITLE
onfido photo-based identity document verification system doesn't work

### ISSUE THREAD

**Issue by mrpewpew** [qutebrowser/qutebrowser#5006]
**Version info (see `:version`)**: v1.7.0

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Trying to verify my identity with a passport scan using [onfido](https://onfido.com/) gives me an error message : Connection lost. I had to use another browser to complete the process with success.

**How to reproduce**
It may be hard to reproduce since you will need to verify your identity on specific websites.

**Comment by The-Compiler** [comment]
That sounds like a problem with your connection rather than qutebrowser. I guess now that you completed that process you can't try again, correct?

**Comment by mrpewpew** [comment]
Actually I tried a few times with qb these past few days before using another browser. The probability of getting a connection error each time except that last one is pretty low. And you're right, I can't try it again now that it succeeded.

**Comment by The-Compiler** [comment]
I submitted a support request in the hope that they have a demo instance I could try. If that doesn't happen, there's nothing I can do.

**Comment by The-Compiler** [comment]
They linked me to a demo instance at https://latest-onfido-sdk-ui-onfido.surge.sh/ - I just completed the verification process there and it works for me without any issues. Could you please try as well?

If it works for you there too, could you please share what provider you signed up with?

**Comment by The-Compiler** [comment]
Also, your version information is incomplete - what Qt version and backend are you using?

**Comment by mrpewpew** [comment]
I am using QtWebEngine (Chromium 73.0.3683.105) and Qt: 5.13.0. The demo instance seems to work so I guess onfido wasn't at fault. I tried to sign in on [blablacar](https://www.blablacar.fr/), a French carpool website.

**Comment by The-Compiler** [comment]
So I tried to sign up just to see how far I'd come - and that's broken, even in Chromium:

![image](https://user-images.githubusercontent.com/625793/64568479-26537880-d35b-11e9-8e2d-72a6dbcba4f4.png)

I'm almost certain this is some server-side issue with blablacar.
