### ISSUE TITLE
whatsapp web

### ISSUE THREAD

**Issue by rndd-AK** [qutebrowser/qutebrowser#5010]
Hi! This app is awesome!!! But I still have to use firefox to use whatsapp web. Do you have any plans about this platform or not ?

**Comment by The-Compiler** [comment]
It's a server-side WhatsApp bug which breaks it, but nobody there cares. You should get around it by changing your user-agent, see #4445 and #4810.

**Comment by The-Compiler** [comment]
I now pushed a fix for known-broken sites (WhatsApp, Google login, etc.) to the `user-agent` branch. If you're affected by one of those, could you please try that branch without any custom user agent set? Thanks!
