### ISSUE TITLE
Cannot mix commands split on ;; and commands take ;; literally

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#5011]
**Version info (see `:version`)**:

Latest master.

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

When command `open ;; later 1000 message-info a ;; message-info b` is run, it's expected that both `message-info a ;; message-info b` are run after 1 second because `later` should take `;;` literally, however `message-info b`is run immediately.

Note:

* `open ;; later 1000 "message-info a ;; message-info b"` does not work.
* `open ;; later 1000 execute "message-info a ;; message-info b"` could work if there's a command called `execute`. Vim suggests using that command to force split on non-splittable command.
* `open ;; later 1000 message-info a ;; later 1000 message-info b"` Works but the odd which the commands are executed is unreliable.

**Comment by The-Compiler** [comment]
See #1850 and #2017.
