### ISSUE TITLE
Taobao captcha does not work

### ISSUE THREAD

**Issue by darkgirl** [qutebrowser/qutebrowser#5019]
**Version info (see `:version`)**:
v1.7.0

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
when i tried to use this software to login https://www.taobao.com
sometimes, this website come out a slider, but it can not slide

![11112](https://user-images.githubusercontent.com/28688741/64902847-9ce8d100-d6e1-11e9-8702-3e019e371901.PNG)

**How to reproduce**

you can register an account and try it. if the slider did not appear , you can input a wrong password Dozens of times, the slider will come out. if you do not want to register, you can use
my account:  想蜕变的蝉子 and input a wrong password Dozens of times.

Thanks

**Comment by The-Compiler** [comment]
I looked at this some months ago when someone mentioned the same issue in the qutebrowser IRC channel. It's some issue with the QtWebEngine rendering engine and/or server-side with Taobao. However, they're doing a lot of weird stuff (like checking WebRTC, WebMIDI, etc.) and have obfuscated JavaScript, so it's impossible to find out what's going on.

**Comment by darkgirl** [comment]
thanks for the explain.

i also did some test using a lot of version of qt, and i found version 5.9.8 can pass taobao validation. 
and i noticed an error: Uncaught (in promise) DOMException: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute. 

i found some document about this error. it looks like chrome changed SDP format from Plan B to Unified Plan. but in the script of taobao page they still use 
var servers = {iceServers: [{urls: "stun:stun.services.mozilla.com"}]}; 
and the behavior of Qtwebengine also not like chrome , it can not run this kind of webrtc script correctly. but i do not know where i can found the code of webrtc of QtWebEngine. if you can help me find it or help me report this to Qt group, it will help a lot.

thank you very much

**Comment by The-Compiler** [comment]
Oh wow, great work tracking this down! Do you have a minimal example script which works fine with Chromium and Qt 5.9.8 but not with an up-to-date Qt? Then I'd be happy to report this to them.

QtWebEngine doesn't have any WebRTC-related code (other than exposing some settings), it's all implemented by the [Chromium snapshot](https://github.com/qt/qtwebengine-chromium/tree/73-based) it's based on. You can report bugs [in their bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa), but if you have something to reproduce this I can report it as well.

**Comment by darkgirl** [comment]
Ok, i will try it. but i am not good at js, so this may take me some time
