### ISSUE TITLE
Fail working with a particular site

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#5024]
I download lots of academic paper from projecteuclid, but recently I found the site broken: it renders me a plain text file instead of a pdf file. I thought it was just temporary. However, I tried downloading with Firefox, and the [site](https://projecteuclid.org/euclid.pja/1195522081) renders well.

I understand this is just a minor issue, since most of the users here do not care about reading academic papers. But it might be worth knowing..

Thank you!

**Version info (see `:version`)**:
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.1 (compiled 5.13.0)
PyQt: 5.13.0

sip: 4.19.18
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.2
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.2.13-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Comment by The-Compiler** [comment]
See [[QTBUG-78114] [REG 5.13] PDF files are downloaded twice - can't download project euclid files - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-78114)
