### ISSUE TITLE
Scale not updated on output change (sway, wayland)

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#5026]
**Version**: https://paste.the-compiler.org/view/76940584

**Description** Window scale doesn't update in several circumstances:

 - External display is disconnected, moving workspace to hidpi laptop display
 - External display is reconnected, restoring workspace from laptop to standard resolution external display
 - Display scale changed

The third circumstance I just noticed, and it makes reproducing easy, hence the report.

**How to reproduce**

```
$ swaymsg -t get_outputs 
$ swaymsg output eDP-1 scale 3
```

This happens with or without `QT_AUTO_SCREEN_SCALE_FACTOR=1`.

Related:

- https://github.com/qutebrowser/qutebrowser/issues/4786
- https://github.com/qutebrowser/qutebrowser/issues/1585

**Comment by The-Compiler** [comment]
Can you try reproducing this with e.g. KDE Falkon?

**Comment by edrex** [comment]
Oh, good call. Same with falkon (and it effect the whole window, so I guess same with any QT5 app). Is there some known upstream issue with this you know of?

**Comment by edrex** [comment]
Anyway it's not qutebrowser :)

**Comment by edrex** [comment]
BLOOP https://bugreports.qt.io/browse/QTBUG-78327

**Comment by edrex** [comment]
@The-Compiler I'm attempting to test the upstream patches and I've rebuilt qt5-base and qt5-wayland. Am I correct that I need to rebuild pyqt too? what about webengine?

**Comment by The-Compiler** [comment]
@edrex You only need to rebuild qt5-base, nothing else. Qt modules are individual libraries (.so files) which keep a stable binary interface (ABI), so for most changes it's enough to recompile whatever module the change was in.
