### ISSUE TITLE
Window sometimes looks badly aliased

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#5028]
This happens occasionally and I'm not sure what triggers it, page content or something about the graphics environment.

Moving the window between different-scale displays (sometimes?) fixes the glitch. Not sure if it's wayland-specific. Also I think sometimes it just spontaneously pops back to looking good, with no input. Is this reported anywhere else?

This is what it looks like:

![Screenshot-2019-09-17-00:57:17](https://user-images.githubusercontent.com/14615/65022964-c6267e80-d8e6-11e9-8014-c6aca594f530.png)

**Comment by edrex** [comment]
Possible this is another qt bug (I don't run other qt apps regularly and since it's intermittent I'd have to sample for awhile to confidently rule that out). If anyone has seen the same in other QT apps that would be helpful.

**Comment by edrex** [comment]
I think this might be just another manifestation of #5026, will close when confirmed

**Comment by The-Compiler** [comment]
@edrex How are things looking?

**Comment by edrex** [comment]
not using qutebrowser regularly atm, so I'll just close this. thanks for the ping.
