### ISSUE TITLE
Bitwarden password fill userscript

### ISSUE THREAD

**Issue by JonnyHaystack** [qutebrowser/qutebrowser#5030]
There are password fill scripts for LastPass, KeePass, etc but none for Bitwarden. Bitwarden is very popular and I feel like a lot of people would benefit from having a password fill script for it as well.

I've actually already done this and I'm about to create a PR. I'm just creating this issue to stay in line with the contribution guidelines :)

**Comment by arza-zara** [comment]
Closed in #5031, thanks.
> I've actually already done this and I'm about to create a PR. I'm just creating this issue to stay in line with the contribution guidelines :)

Probably not required if you have the PR ready though, the guideline is for preventing duplicate work.
