### ISSUE TITLE
Hints + paragraphs = mouseless copy action

### ISSUE THREAD

**Issue by grigorievich** [qutebrowser/qutebrowser#5035]
The typical piece of information I tend to copy on the web is a text block.
Selecting w/ mouse is painful.
Now, I am not familiar w/ web, but a paragraph should maybe not be too difficult to identify.
If this is so, pairing paragraph identification with hints could diminish mouse use.

Thoughts?

**Comment by jgkamat** [comment]
grigorievich writes:

> The typical piece of information I tend to copy on the web is a text block.
> Selecting w/ mouse is painful.

Can't you do this with caret mode?

**Comment by The-Compiler** [comment]
Like @jgkamat said, there's caret mode - see #1453 for the rest.

**Comment by grigorievich** [comment]
@jgkamat 

> caret mode

well, it's one of those few things where mouse feels faster. Maybe it's just lack of practice on my part. But the proposed way appears to be both fast and comfortable. And the fine trimming can be done in an editor, if needed, without ever having to customize the bindings for caret.

**Comment by jgkamat** [comment]
grigorievich writes:

> well, it's one of those few things where mouse feels faster. Maybe it's just 
> lack of practice on my part. But the proposed way appears to be both fast 
> and comfortable. And the fine trimming can be done in an editor, if needed, 
> without ever having to customize the bindings for caret.

You could probably implement this fairly easily if you really wanted to, as 
long as you were able to convert the paragraphs to plaintext in js. However, I 
find myself often wanting to select multiple paragraphs, or text that's not in 
paragraphs, or (most often) a single word or line, which I can do in caret 
mode faster and more precisely than with the mouse. You could probably add an 
'end to paragraph' binding for caret mode as well, if you want to select 
paragraphs a lot.

**Comment by grigorievich** [comment]
@jgkamat

True, selecting multiple paragraphs is also a problem.

Maybe I don't get something, but caret starts at the beginning of the page. Trying to select your response here, for instance, took quite a bit of motion. The thread The-Compiler has linked addresses this though.

**Comment by mrossinek** [comment]
@grigorievich May i point out that the selection can also start from the last match of a searched word. That way you can quickly jump to a specific section of a page.

Note also that you can use `o` to jump the cursor to the other end of the selection to change that end. Just like in vim: `vim -c "help v_o"`

**Comment by grigorievich** [comment]
@mrossinek well, that even makes it kind of usable. Thanks!

**Comment by Philipp0205** [comment]
SurfingKeys has implemented this with a hint for ever word of the page, then the user can use "p" to select the line or "pp" to select the whole paragraph. 

Wordhints look messy for a second but are a very good way to place the caret in the right place.
