### ISSUE TITLE
Add mode for url.auto_search to search unless entering a url with scheme

### ISSUE THREAD

**Issue by danielnelson** [qutebrowser/qutebrowser#5038]
I would like to request the addition of a new `url.auto_search` mode that uses the default search unless a proper URL, with the scheme, is entered.

This would be useful to me because I often search for terms with a dot in them, which the `naive` setting attempts to open as a URL.  When using the `never` setting instead I frequently forget to add my searchengine name, get a "invalid URL" error and need to reenter my search.

Examples that would use search engine:
```
:open github.com/qutebrowser/qutebrowser
:open howdy
:open url.auto_search
```

Examples that would open as a URL:
```
:open https://github.com/qutebrowser/qutebrowser
:open http://example.org
```

**Comment by user202729** [comment]
Alternatively it's possible to make the algorithm smarter (e.g. "weird" dot suffix should not be treated as URL unless explicit URL is given, which is what some browser does), or redirect to search engine page when the page is not found (similar to DNS option)

**Comment by arza-zara** [comment]
Opening `github.com/qutebrowser/qutebrowser` with search engine sounds weird and inconvenient. In #5056 I made the naive URL detector a bit less naive so that for example search strings containing a dot and an underscore are detected as not URLs.

**Comment by danielnelson** [comment]
My thought is that since `github.com/qutebrowser/qutebrowser` is not a URL it shouldn't be treated as one, but also because we should have predicable behavior between search and lookup.  Increasing the complexity of the heuristic would't be helpful to that goal.

I also search at least 10x more often than going directly to a URL, and when I do go directly to a URL it is usually from my history or bookmarks and is well formed.  The penalty for searching is also much lower than the penalty for going to an invalid URL, since I can just click on the first search result in the former case.
