### ISSUE TITLE
Indicate current mode in tab 

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#5041]
Not sure if people like this idea, but one of my only uses for the statusbar is mode indication. It could therefore be handy to relegate mode indication to the visual appearance of individual tabs, so clearing up a bit of screen space. Of course, this only makes sense when you have per tab modes enabled (i.e. `c.tabs.mode_on_change = restore`?).  

Aside from more vertical screenspace, it can give people a visual indication  of what they were doing inside a  particular tab. 
 
A theoretical implementation could involve providing a new format that outputs (colored) single letters in `c.tabs.title.format`, for example "[ i ] " for insert mode. Alternatively, a new option could be provided that changes the tab background/foreground colors based on the current mode.

**Comment by arza-zara** [comment]
I agree. See #3398.
