### ISSUE TITLE
Disable Tab Title?

### ISSUE THREAD

**Issue by panyi0622** [qutebrowser/qutebrowser#5042]
I think it's really annoying when hovering. With Firefox, I can disable it and even element titles inside webpages. 
Thanks!

**Comment by toofar** [comment]
By element titles do you mean tooltips? And you want to disable them globally?

**Comment by panyi0622** [comment]
> By element titles do you mean tooltips? And you want to disable them globally?

Yes, disabling tab-titles is enough, but it's really great to disable all of them

**Comment by panyi0622** [comment]
> > By element titles do you mean tooltips? And you want to disable them globally?
> 
> Yes, disabling tab-titles is enough, but it will be really great to disable all of them

**Comment by panyi0622** [comment]
> By element titles do you mean tooltips? And you want to disable them globally?

Yes, it will be great to disable all of them.

**Comment by toofar** [comment]
Apparently they themed via some Qt mechanism, see the discussion on this issue: https://github.com/qutebrowser/qutebrowser/issues/4520
Without actually having looked into whether you can disable them you could probably make their background, foreground and border transparent.

**Comment by panyi0622** [comment]
Yes, I could just change their color by qt5ct. Thank you!
