### ISSUE TITLE
How to assign classname to qutebrowser window?

### ISSUE THREAD

**Issue by igorhub** [qutebrowser/qutebrowser#5043]
Hi!

I’m trying to create several qutebrowser windows with different classnames. I see that parameter `--qt-name` was introduced for this purpose. It has since been removed. Perhaps, I could use `--qt-arg`, but it’s unclear how (I have no experience with qt).

**Comment by ninewise** [comment]
You can use `--qt-arg name asdf`. Check [FAQ](https://qutebrowser.org/doc/faq.html) number 19 for more info.

**Comment by igorhub** [comment]
Thank you!

That’s exactly what I needed. I had read FAQ before, but somehow missed this item. Feeling a bit embarrassed now.

**Comment by ninewise** [comment]
No trouble, it's easy to overlook.
