### ISSUE TITLE
Keep old page, when (re)loading has a timeout

### ISSUE THREAD

**Issue by gerion0** [qutebrowser/qutebrowser#5044]
I often have the situation when surfing with mobile net that a page load takes a lot of time or is not successful at all. Sometimes, only a few requests timeout, so the page text is visible but some other resources (pictures etc.) are missing. My workaround then is to reload the whole site.

However, when the reload (or load of a new page) fails, the old page is cleared and a warning is displayed that the connection had a timeout. Can you implement the warning in the same style as a javascript question, so the old page content remains?

**Comment by toofar** [comment]
Possible dup of https://github.com/qutebrowser/qutebrowser/issues/3918

**Comment by gerion0** [comment]
This is a different aspect of the problem, but should be fixable with the same mechanism.

**Comment by The-Compiler** [comment]
See that and also #2176.
