### ISSUE TITLE
macOs $PATH not loaded?

### ISSUE THREAD

**Issue by pniedzwiedzinski** [qutebrowser/qutebrowser#5050]
**Version info (see `:version`)**:
```
qutebrowser v1.8.1
Git commit: 396622097 (2019-09-27 13:35:02 +0200)
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.4
Qt: 5.12.5 (compiled 5.12.4)
PyQt: 5.12.3

sip: 4.19.19
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.2
cssutils: 1.0.2 $Id$
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: 2.1.266 (bundled)
sqlite: 3.28.0
QtNetwork SSL: Secure Transport, macOS Mojave (10.14)

Style: QMacStyle
Platform: Darwin-18.7.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.14.6, x86_64

Paths:
auto config: /Users/pniedzwiedzinski/Library/Preferences/qutebrowser
cache: /Users/pniedzwiedzinski/Library/Caches/qutebrowser
config: /Users/pniedzwiedzinski/.qutebrowser
data: /Users/pniedzwiedzinski/Library/Application Support/qutebrowser
runtime: /private/var/folders/s4/rskg4_p557dcpgpnwy3fx58r0000gn/T/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:02:09

```
**Does the bug happen if you start with `--temp-basedir`?**:
How to do that on mac?

**Description**
I have a userscript (qute-lastpass) with shebang: `#!/usr/bin/env python3` and it works great.
I set qutebrowser as my main browser and now when I open qutebrowser with link and try to run this script it seems that PATH is not loaded. I've got an error `env: python3: No such file or directory`.

Also I have no idea how to name this issue, so if someone has a better idea for the title I would appreciate help. 

**How to reproduce**

- Make sure qutebrowser is closed.
- `open http://example.com`
- `:spawn --userscript qute-lastpass`
- You can see error in `:messages`

**Comment by jgkamat** [comment]
Patryk Niedźwiedziński writes:

> **Description**
> I have a userscript (qute-lastpass) with shebang: `#!/usr/bin/env python3` 
> and it works great.
> I set qutebrowser as my main browser and now when I open qutebrowser with 
> link and try to run this script it seems that PATH is not loaded. I've got 
> an error `env: python3: No such file or directory`.

This is a bug in Mac, qutebrowser cannot do anything to fix that: 
http://www.stackoverflow.com/questions/460835/how-to-set-the-path-as-used-by-applications-in-os-x

The easiest workaround is starting qutebrowser from the terminal.

See http://www.github.com/qutebrowser/qutebrowser/pull/4274

**Comment by pniedzwiedzinski** [comment]
Ok, thanks
