### ISSUE TITLE
content.cookies.accept: "Ask" setting

### ISSUE THREAD

**Issue by Slider-Whistle** [qutebrowser/qutebrowser#5051]
A cookie setting that makes a yes/no dialogue appear in regards to whether you want to accept any particular incoming cookie a website tries to set, or, a little more conveniently, whether a new domain should be whitelisted totally.

Also, I don't think "all" and "never" are intuitive opposites to eachother, but it's fine since you're shown the valid values when you get it wrong anyway.

**Comment by The-Compiler** [comment]
This unfortunately isn't possible - when deciding whether cookies are allowed, we're in Chromium's IO thread, where no GUI stuff can happen.
