### ISSUE TITLE
Inspector almost unreadable on HiDPI monitor on Arch Linux

### ISSUE THREAD

**Issue by sambanks** [qutebrowser/qutebrowser#5053]
Qutebrowser: 1.7.0-1
Arch Linux: Latest
AwesomeWM: 4.3-1

**Description**
When running qutebrowser with a zoom value (eg 200%) on a monitor in a mixed resolution setup `:inspector` results in a non zoomed inspector. When you are using a high value such as 200% this results in inspector being unreadable unless it is moved to a lower resolution monitor.

Is there a zoom value we can pass through to dev tools?

Cheers
Sam

**Comment by ninewise** [comment]
Duplicate of #3190?

**Comment by sambanks** [comment]
Apologies, closing..
