### ISSUE TITLE
qutebrowser is black i cant read the page

### ISSUE THREAD

**Issue by stefy20026** [qutebrowser/qutebrowser#5058]
**Version info (see `:version`)**:
archlinuxarm armv7h (raspberry pi 3b)
community/qutebrowser 1.8.1-1
    A keyboard-driven, vim-like browser based on PyQt5
Nome                      : qutebrowser
Versione                  : 1.8.1-1
Descrizione               : A keyboard-driven, vim-like browser based on PyQt5
Architettura              : any
URL                       : https://www.qutebrowser.org/
Licenze                   : GPL
Gruppi                    : Nessuno
Fornisce                  : Nessuno
Dipenda da                : python-attrs  python-jinja  python-pygments  python-pypeg2
                            python-pyqt5  python-yaml  qt5-base  python-pyqtwebengine
Dipendenze opzionali      : gst-libav: media playback with qt5-webkit backend
                            gst-plugins-base: media playback with qt5-webkit backend
                            [installato]
                            gst-plugins-good: media playback with qt5-webkit backend
                            [installato]
                            gst-plugins-bad: media playback with qt5-webkit backend
                            gst-plugins-ugly: media playback with qt5-webkit backend
                            pdfjs: displaying PDF in-browser
                            qt5-webkit: alternative backend
Richiesto da              : Nessuno
Opzionale per             : Nessuno
Conflitti con             : Nessuno
Sostituisce               : Nessuno
Spazio richiesto          : 7,76 MiB
Pacchettizzatore          : Arch Linux ARM Build System <builder+xu2@archlinuxarm.org>
Data di creazione         : sab 28 set 2019, 16:33:02
Data di installazione     : gio 3 ott 2019, 19:33:00
Motivo dell'installazione : Installato esplicitamente
Script di install         : No
Convalidato da            : Firma
**Does the bug happen if you start with `--temp-basedir`?**:
yes
**Description**

i can see only top bar and bottom bar and f show letters but foreground and background are black, i have the same problem on falkon.
**How to reproduce**

**Comment by jgkamat** [comment]
> **Description**
>
> i can see only top bar and bottom bar and f show letters but foreground and 
> background are black, i have the same problem on falkon.

Can you pastebin your :version? Are you using wayland?

**Comment by stefy20026** [comment]
At the moment im using xorg xinitrc (not sway)


 qutebrowser -V
qutebrowser v1.8.1
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.1
PyQt: 5.13.1

sip: 4.19.19
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.2
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-4.19.75-2-ARCH-armv7l-with-arch, 32bit
Linux distribution: Arch Linux ARM (unknown)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
LOGO=archlinux

Paths:
cache: /home/alarm/.cache/qutebrowser
config: /home/alarm/.config/qutebrowser
data: /home/alarm/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/alarm/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:02

**Comment by The-Compiler** [comment]
If you see this with Falkon as well, it's an issue with either QtWebEngine/Chromium or your graphic drivers.

Things you could try:

- `QUTE_SKIP_LIBGL_WORKAROUND=1 qutebrowser --temp-basedir`
- `qutebrowser --temp-basedir -s qt.force_software_rendering chromium`
- The same but with `software-opengl` or `qt-quick` instead of `chromium`
- Checking for error messages when launching in a terminal

**Comment by edrex** [comment]
I'm seeing this on sway also, only in the last week or so.

For me it only happens after resume from sleep. I'm also seeing a lot of delay creating new windows and redrawing after a resize, maybe related.

**Comment by edrex** [comment]
Upstream (i think): https://bugreports.qt.io/browse/QTBUG-78461

**Comment by edrex** [comment]
@The-Compiler tested with all the permutations you gave, all but qt-quick show the issue.

Console output is identical for each failing case:

```
❯ qutebrowser --temp-basedir                                        
22:10:37 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:37 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:10:38 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:38 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:38 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:03 WARNING: QPaintDevice::metrics: Device has no metric information
22:12:03 WARNING: QPaintDevice::metrics: Device has no metric information
22:12:03 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:04 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:04 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:04 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:04 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:05 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:05 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
22:12:08 WARNING: QQuickWidget: Cannot render due to failing makeCurrent()
QQuickWidget::invalidateRenderControl could not make context current
```

For qt-quick, the non-failing case:

```
❯ qutebrowser --temp-basedir -s qt.force_software_rendering qt-quick                                                          
22:10:37 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:37 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:38 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:38 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:38 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:38 WARNING: QPaintDevice::metrics: Device has no metric information
22:10:38 WARNING: QPaintDevice::metrics: Device has no metric information
22:12:03 WARNING: QPaintDevice::metrics: Device has no metric information
22:12:03 WARNING: QPaintDevice::metrics: Device has no metric information
22:12:03 WARNING: QPaintDevice::metrics: Device has no metric information
```

(still ten of the "no metric info" message)

**Comment by The-Compiler** [comment]
@edrex That's a Qt 5.14 regression, and @stefy20026 is on Qt 5.13.1 - what Qt version are you using?

**Comment by edrex** [comment]
The issue I was having is after suspend/resume and seems to match QTBUG-78461 pretty well, but maybe it's not the same as @stefy20026's.

I can no longer reproduce, after rolling qt5-webengine back and then forward

```
sudo pacman -U /var/cache/pacman/pkg/qt5-webengine-5.13.1-1-x86_64.pkg.tar.xz
sudo pacman -U /var/cache/pacman/pkg/qt5-webengine-5.13.1-3-x86_64.pkg.tar.xz
```

I had done a custom build of 5.13.1 awhile back, but I had uninstalled and updated the package since then so :man_shrugging:.

**Comment by edrex** [comment]
@stefy20026 just out of curiousity, can you see if rolling back and forward as above makes the issue go away?

**Comment by edrex** [comment]
Gah, nevermind it's still happening. It's not every suspend/resume cycle so I have no way to get a definitive negative result.

**Comment by edrex** [comment]
I think I found the commit that introduced this, see https://bugreports.qt.io/browse/QTBUG-78461#comment-480482

@stefy20026, can you try rolling back to qt5-webengine 5.13.1-2 and see if that fixes your issue? Something like

```sudo pacman -U /var/cache/pacman/pkg/qt5-webengine-5.13.1-2-*.pkg.tar.xz```
