### ISSUE TITLE
QR code like screen rendering issue

### ISSUE THREAD

**Issue by Brixy** [qutebrowser/qutebrowser#5060]
```
qutebrowser v1.8.1
MacOS 10.14.6 (install using the .dmg file)
```

In qutebrowser I have often seen screens like this:

![screenshot](https://user-images.githubusercontent.com/1643010/66194457-c7043200-e694-11e9-888c-f04a5a2465cc.png)

It is not a problem concerning specific websites. Reloading the screen always helps. It rather seems to appear arbitrarily.

I cannot reproduce it ‘on demand’

**Comment by The-Compiler** [comment]
Can you try setting `qt.force_software_rendering` (to either `chromium`, `qt-quick` or `software-opengl`) for a while and see if that changes anything?

**Comment by Brixy** [comment]
Thank you!

I started with

```
c.qt.force_software_rendering = 'software-opengl'
```

As soon as it happens again I’ll give feedback here.

**Comment by lufte** [comment]
I used to see that in the past but I think that for the last two versions I have not seen it anymore. I'm running v1.7.0 at the moment.

**Comment by Brixy** [comment]
With `software-opengl` it happened again. I’ll give feedback after using `qt-quick` and `chrome`.

> I used to see that in the past but I think that for the last two versions I have not seen it anymore. I'm running v1.7.0 at the moment.

@lufte Thanks for comment. I am using `v1.8.1`.

**Comment by Brixy** [comment]
`qt-quick` seems to have solved the problem completely. (Switching to `chrome` now no for testing purposes.)

Does this help you in any way? I do not know the technical background.

**Comment by The-Compiler** [comment]
I don't know what those options do precisely either - but it might help with opening an upstream bug report about it.

**Comment by Brixy** [comment]
Sorry—I somehow missed your reply, @The-Compiler.

Just to confirm: The `chrome` settings solves the issue, too.

**Comment by The-Compiler** [comment]
I don't think there's anything qutebrowser can do here - perhaps it has gone away with newer Qt versions, though?
