### ISSUE TITLE
Can't bind command

### ISSUE THREAD

**Issue by GhostValk** [qutebrowser/qutebrowser#5068]
I'm trying to bind a command in qutebrowser, and somehow it doesn't work. I'm defining `config.bind(':bd', 'tab-close')`, but when i use `:bd` and press enter it says "no such command". Command bindings has always worked for me in vim, vifm and all the other vi-like apps, so, no idea what could it be.

Any idea?

**Comment by The-Compiler** [comment]
`:bind` binds keys to commands only - you probably want the `aliases` setting instead, e.g. `c.aliases[':bd'] = 'tab-close'`.

**Comment by The-Compiler** [comment]
My bad, that should be `c.aliases['bd'] = 'tab-close'`, not `:bd`

**Comment by GhostValk** [comment]
Worked flawless, thanks a lot.
