### ISSUE TITLE
User Agent for specific websites

### ISSUE THREAD

**Issue by GhostValk** [qutebrowser/qutebrowser#5069]
I don't know if this function is already implemented, but if not, i'd like to suggest an option to set an specific user agent for a certain domain, so i can use one  agent globally but load some specific websites with another.

Thanks in advance, qutebrowser is the best thing EVER.

**Comment by The-Compiler** [comment]
It is, you can set the user_agent option with a domain pattern.

**Comment by GhostValk** [comment]
Thanks, i haven't been able to find documentation on how to set it up, any hint on where it is?

**Comment by The-Compiler** [comment]
See the [configuration documentation](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc) (search for "pattern"), as well as `:help :set` and `:help content.headers.user_agent`. If you have ideas on how to make things more visible, please let me know!

**Comment by GhostValk** [comment]
Sorry to keep posting on this issue, but i haven't been able to set this to work properly..

I'm trying to set a mobile agent for a domain (instagram in this case) and another one for everything else, however, i can't manage to get it working.

In the config file i have these two lines:

`config.set('content.headers.user_agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1', '*://www.instagram.com/*')`
`c.content.headers.user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15"`

However, i'm not sure if the pattern is not right, or the config line, or what could it be. Any idea?

**Comment by The-Compiler** [comment]
That seems fine to me. Note that the user agent the website sees via JavaScript (rather than the HTTP header) is always the global one, so that might be the issue here.

**Comment by GhostValk** [comment]
Well, if i set in the second line the UA from the first one, it works perfect, all sites open up with the mobile Agent, looks like the problem is that the condition is never triggered or the user agent doesn't change "on request" of the trigger.

**Comment by The-Compiler** [comment]
It does - you can see it e.g. in the network tab of `:inspect`. Looks like Instagram only looks at the user agent exposed via JavaScript though.

**Comment by The-Compiler** [comment]
@elig0n I added a quick explanation and links to it in 8a61bd635aaa17ee50118bafaa67b2134e695e09.
