### ISSUE TITLE
Open multiple bookmarks

### ISSUE THREAD

**Issue by q3cpma** [qutebrowser/qutebrowser#5073]
Hello,

I think this would improve the quality of life very much, especially since bookmark folders (any arborescent or tag based system) aren't here (for now?). Maybe copy vi's visual mode, but that would limit the selection to adjacent entries; which isn't that bad and makes it simpler to use.

**Comment by The-Compiler** [comment]
You can already use Ctrl-Enter with `:open -t` to do that, or chain multiple `:bookmark-load` commands with `;;` (and use an alias or keybinding).
