### ISSUE TITLE
Most of my browser is transparent

### ISSUE THREAD

**Issue by Manmohan-manoj** [qutebrowser/qutebrowser#5075]
I just installed qutebrowser on my fresh manjaro, opacity of my browser is very low and everything is transparent. When I put something black behind the browser it looks normal.
 
in the screenshot i put a terminal behind half the screenshot for demonstration
![Screenshot_2019-10-13_19-44-30](https://user-images.githubusercontent.com/26947508/66713190-0cc3a780-edc5-11e9-848c-47da629af062.png)

**Comment by The-Compiler** [comment]
That's weird! Could you check whether [Falkon](https://www.falkon.org/) looks the same? Also, can you reproduce this with `--temp-basedir`?

**Comment by davafons** [comment]
I'm having the same issue here (Manjaro user too)

Installed __Falkon__, and it looks the same.

Running `qutebrowser --temp-basedir` still gives the same issue.

**Comment by The-Compiler** [comment]
This doesn't look like a qutebrowser issue then. Are you using nvidia drivers? I found this: https://forum.manjaro.org/t/rendering-issue-with-nvidia-cards/105484

You might want to play with the `qt.force_software_rendering` setting and see if that helps.

**Comment by Manmohan-manoj** [comment]
@The-Compiler  Thank you
