### ISSUE TITLE
Tests are not included in PyPI distribution

### ISSUE THREAD

**Issue by ddevault** [qutebrowser/qutebrowser#5081]
**Version info (see `:version`)**: 1.8.1

These are helpful when packaging qutebrowser for distributions.

**Comment by The-Compiler** [comment]
I'm not against including them per se, but I doubt they'll be useful for distribution packages. They generally require the latest releases of pytest and various plugins (I'm also a maintainer of pytest and various of the plugins, so this is unlikely to ever change). They also take a long time to run, require a GUI, etc. etc.

**Comment by ddevault** [comment]
As the maintainer of qutebrowser for Alpine, I'm willing to put in the effort to get the tests working. I've done similarly hard tests, like ones which require postgresql or redis to be running for example.

**Comment by GuillaumeSeren** [comment]
Hey,
I help maintain the gentoo package for qutebrowser, and I am looking at enabling tests,
actually we were using the source from the 'Source release' like https://github.com/qutebrowser/qutebrowser/releases/download/v1.11.1/qutebrowser-1.11.1.tar.gz

But after checking the content it does not ship the tests, so I plan to use the 'Source code' (https://github.com/qutebrowser/qutebrowser/archive/v1.11.1.tar.gz) which contain the tests, those names were a bit confusing but at least the tarball exist.

Despite the source origin, is there anything really special to take care of, I know it needs X to run,
but this can be emulated with xvfb, I will report here once I finished maybe it can help.

**Comment by The-Compiler** [comment]
> But after checking the content it does not ship the tests, so I plan to use the 'Source code' (https://github.com/qutebrowser/qutebrowser/archive/v1.11.1.tar.gz) which contain the tests, those names were a bit confusing but at least the tarball exist.

Those archives are auto-generated by GitHub - so you will not have any PGP signatures, you will need to generate autogenerated files (part of the release) to not end up with a broken installation (right now that mainly means running `asciidoc2html.py`), and you might need to take care which scripts you install and which (development scripts) you don't.

I'll take a look at including `tests/` and `pytest.ini` in the next release tarball, I *think* those should be the only files from the repo needed to run them.

As for running the tests, you will need the dependencies listed here: https://github.com/qutebrowser/qutebrowser/blob/master/misc/requirements/requirements-tests.txt

Note that only the exact versions pinned there are supported, and those versions usually track the latest available upstream releases. I likely won't be willing to support any older versions of those tools and plugins.

**Comment by The-Compiler** [comment]
Tests will now be in the tarball for v1.12.0 (except a couple of tests for development scripts). I've also edited `requirements-tests.txt-raw` to point out which dependencies are really needed and which are optional. Note that you will need to run pytest with `--qute-bdd-webengine` (or set the `QUTE_BDD_WEBENGINE=1` environment variable) as end2end tests are still using QtWebKit by default, see #3051.

**Comment by GuillaumeSeren** [comment]
Hey @The-Compiler ,
thank you very much for the feedback.
