### ISSUE TITLE
fix NSS directory creation

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#5082]
Hi,
the NSS which qutebrowser makes use of, closed this [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=818686) which means by now they can follow the XDG basedir specification.

Unfortunately with qutebrowser, it still creates the '~/.pki' (on home folder), maybe due to qutebrowser itself or any dependencies of it.

Can you please investigate that?

**Comment by The-Compiler** [comment]
Looks like Chromium does that: https://bugs.chromium.org/p/chromium/issues/detail?id=902758

**Comment by aleprovencio** [comment]
Thank you @The-Compiler
