### ISSUE TITLE
hint doesn't set $QUTE_URL

### ISSUE THREAD

**Issue by ElModdy** [qutebrowser/qutebrowser#5089]
**Version info**:
1.8.1
**Description**
```hint links userscript <usercscript>```
 doesnt't set $QUTE_URL to the hint link.

**Comment by The-Compiler** [comment]
With this userscript:

```bash
#!/bin/bash
notify-send "$QUTE_URL"
```

and the command you mentioned, I get a notification with the URL as expected.

**Comment by ElModdy** [comment]
`config.py`
```
config.bind(';', 'hint links userscript downloader')
```
`downloader`
```
#!/bin/bash
. constants.env
echo "download -d ${PATH_PROJECT}res/ ${QUTE_URL}" >> "$QUTE_FIFO"
```

**Comment by The-Compiler** [comment]
Works fine for me. Can you reproduce this with `--temp-basedir` and then do `:report` so I can take a look at the logs please?

**Comment by ElModdy** [comment]
I have no idea what I did but it started working
