### ISSUE TITLE
How to help improve adblocker?

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#5090]
I find the adblocker very useful, sometimes some ads still slip through though. I wonder if there's a way for the users to help improve the adblock list? Say to implement a way so that the users can report ad-site easily?

**Comment by toofar** [comment]
qutebrowser doesn't maintain any adblock lists, it is configured [by default](https://qutebrowser.org/doc/help/settings.html#content.host_blocking.lists) to pull down [this one](https://github.com/StevenBlack/hosts). But you can change that yourself to a different one (or mutliple). Also you can maintain a personal list in `~/.config/qutebrowser/blocked-hosts` that'll be read in addition to the third party one.
