### ISSUE TITLE
Need keybindings for frames

### ISSUE THREAD

**Issue by DonPiotr** [qutebrowser/qutebrowser#5091]
Hi!
I need some key bindings to switch between frames.
I know that frames are not popular this days, but thay are.
Thanks for qutebrowser.
Piotr

**Comment by jgkamat** [comment]
See #4715, and use :hint scrollable

On October 27, 2019 6:11:22 PM PDT, DonPiotr <notifications@github.com> wrote:
>Hi!
>I need some key bindings to switch between frames.
>I know that frames are not popular this days, but thay are.
>Thanks for qutebrowser.
>Piotr

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
Also see #521.
