### ISSUE TITLE
Tabs taking too long to open

### ISSUE THREAD

**Issue by GhostValk** [qutebrowser/qutebrowser#5095]
When i first downloaded qb, the new tabs opened almost instantly, but now, every time i open a new tab, it takes like 5 seconds to open, keeping qb frozen in the meantime. It's not a high priority issue, but it's still annoying. This happens regardless of having 1 or 10 tabs already open.

I've tried deleting the cache, starting with a temp folder and with no `config.py`, but it's the same.

Any idea of what could it be?

**Comment by jgkamat** [comment]
Can you try in qutebrowser -T and pastebin your :version?

On October 29, 2019 7:57:18 AM PDT, GhostValk <notifications@github.com> wrote:
>When i first downloaded qb, the new tabs opened almost instantly, but
>now, every time i open a new tab, it takes like 5 seconds to open,
>keeping qb frozen in the meantime. It's not a high priority issue, but
>it's still annoying. This happens regardless of having 1 or 10 tabs
>already open.
>
>I've tried deleting the cache, starting with a temp folder and with no
>`config.py`, but it's the same.
>
>Any idea of what could it be?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by toofar** [comment]
You didn't say if using -T helped. Do you have `auto_save.session` set to true? If so there might be some line lines the the yaml file which do slow it down.

**Comment by GhostValk** [comment]
No, no change, but i did a bit of -big- cleaning in the caches, recreated the config.py from a blank file and now is working fine :) If something comes up i'll open the thread again, thanks!

**Comment by The-Compiler** [comment]
In #5103 you mentioned that you're only seeing this when opening qutebrowser via the GUI - this sounds a lot like #4943, are you seeing the same? Could you try the changes I mentioned in my comment there (which the original reporters never did)?

**Comment by GhostValk** [comment]
Well, a small clarification, in #5103 the point of my question was the signal to open a url, not the slow tab opening. I'm gonna try right away the suggestions and post back.

**Comment by GhostValk** [comment]
Ok, tried switching to the small `Info.plist` and no change, exactly the same behaviour (it's basically the same of #4943 , qutebrowser quite frozen at start and when opening new tabs regarding on how many already open).

(Respecting #5103 , you gave me an idea, i'm specifically using a shiny server for my work and i think i can try bypassing the bug by forcing shiny to use `qutebrowser` instead of `open`.)
