### ISSUE TITLE
insert-text in command mode.

### ISSUE THREAD

**Issue by user-b** [qutebrowser/qutebrowser#5100]
**My code:**
```
c.aliases['opent'] = 'open -t' # This single-word alias makes easier to navigate  after any of 'open/open -t' 
c.aliases['edit-search'] = ';;'.join([
    'set-cmd-text :',
    'command-history-prev',
    'rl-beginning-of-line',
    'rl-forward-word',
])
config.bind("e", "edit-search")
config.bind("t", "set-cmd-text -s :opent ")
```

**Goal:** 
Make a single `edit-search` alias working exactly the same for `open` and `open -t` with or without a search engine keyword.

Calling edit-search after any of these commands (where `google` is a search engine keyword):
`:open hello`
`:open google hello`
`:open -t hello`
`:open -t google hello`

should always bring this new command:

`:open <cursor_is_here> hello`

**Problem**
Getting rid of the search engine (if any) is maybe too difficult but the `opent` alias could be replaced with just `open` if we have a insert-text function working in command mode.

**Comment by jgkamat** [comment]
MyName writes:

> **Goal:**
> Make a single `edit-search` command working exactly the same for `open` and 
> `open -t` with or without a search engine keyword.

Are you just trying to re-search with different engines? My idea for this is

http://www.github.com/qutebrowser/qutebrowser-extensions/issues/2

But to implement it right now it will require hot-patching because there's no 
hooks in qutebrowser or advice system in python

> **Problem**
> Getting rid of the search engine (if any) is maybe too difficult but the 
> `opent` alias could be replaced with just `open` if we have a insert-text 
> function working in command mode.

You might be able to use 'fake-key -g', although I'm not sure how this would 
help. I think at some point there was discussion on adding set-cmd-text 
--insert in addition to the current --append

**Comment by user-b** [comment]
I din't really understood your issue and I dont know how `fake-key -g` could help, sorry.

But yes, i'm trying to get a "re-search with different engine" functionality.

Ideally it should be something linke this:

`c.aliases['change-search-engine'] = 'set-cmd-text :open ' + jseval("get_first_input_text.js")`

**Comment by The-Compiler** [comment]
Agreed that this is something for a future extension API (also see #30). FWIW I also don't understand how an insert-text functionality in command mode would help for your use-case.
