### ISSUE TITLE
Qutebrowser doesn't follow the system standard of anti-aliasing/font smoothing 

### ISSUE THREAD

**Issue by ReneFroger** [qutebrowser/qutebrowser#5104]
**Version info (see `:version`)**:
qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)
Style: QFusionStyle
Platform: Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: Ubuntu 18.04.1 LTS (ubuntu)
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

In Google Chrome, I have set the anti-aliasing and font smoothing off in the settings.
And I removed any font smoothing with the following:

```
sudo rm /etc/fonts/conf.d/10-antialias.conf
sudo /etc/fonts/conf.avail/10-antialias.conf
```
This works like a charm. The fonts in Google Chrome looks crispy without font aliasing. And every application on my system behaves in the same way (no anti-aliasing)
However, when I start Qutebrowser, I see the text is anti-aliased and smoothed, which frustates me.

Seems Qutebrowser is not using the system fonts. Is there any way to 'tell' qutebrowser to not use anti-aliasing? I found nothing about this in the documentation.

**Comment by jgkamat** [comment]
Do you see the same issue in kde falkon?

**Comment by ReneFroger** [comment]
> Do you see the same issue in kde falkon?

I just installed KDE Falkon to test it, and I can confirm Falkon does have the same issue too.

**Comment by ReneFroger** [comment]
To get a better idea, I made screenshots in Google Chrome and Qutebrowser:

 
![image](https://user-images.githubusercontent.com/5211845/68513803-411f6c00-027c-11ea-94fd-0c341afb5c1f.png)

**Comment by The-Compiler** [comment]
This isn't a qutebrowser bug then. You might want to test with a newer Qt version (such as 5.13 or the soon to be released 5.14), and if you still see the issue there, [open a Qt bug](https://bugreports.qt.io/secure/Dashboard.jspa).

**Comment by wedens** [comment]
Qt is not very good at using fontconfig. I've noticed issues with font priorities (especially with emoji fonts) that occur only in Qt applications :/

**Comment by The-Compiler** [comment]
@wedens With what Qt version? I remember seeing various improvements in those areas over the last couple of releases.

**Comment by wedens** [comment]
@ReneFroger you can try overriding fontconfig settings in  `$XDG_CONFIG_HOME/fontconfig/conf.d`

**Comment by wedens** [comment]
@The-Compiler 5.12.*

**Comment by ReneFroger** [comment]
@wedens thanks for your suggestion. Seems my setup doesn't know the variable `$XDG_CONFIG_HOME`, so I tried `~/.config/fontconfig`, but that map doesn't exist. When looking around with `find .-type d -name 'fontconfig'`, I found nothing. 

Where should I look into?

**Comment by wedens** [comment]
@ReneFroger 
```sh
mkdir -p ~/.config/fontconfig/conf.d
touch ~/.config/fontconfig/conf.d/10-no-antialias.conf
```
insert this content in `~/.config/fontconfig/conf.d/10-no-antialias.conf` file:
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <match target="pattern">
    <edit mode="append" name="antialias">
      <bool>false</bool>
    </edit>
  </match>
</fontconfig>
```
log out and log back in or just restart the computer

**Comment by ReneFroger** [comment]
I got solved it in the another way. 

Install qt5ct with `sudo apt install -y qt5ct`. 
Then `export QT_QPA_PLATFORMTHEME=qt5ct` and start `qt5ct`. Select your font and disable anti-aliasing.

**Comment by ReneFroger** [comment]
@wedens, thanks for your reply, your help is really appreciated.

I'll try your solution now.
