### ISSUE TITLE
Sudden session corruption

### ISSUE THREAD

**Issue by wedens** [qutebrowser/qutebrowser#5105]
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/d1b21bb9

**Description**

I was using qutebrowser as usual and suddenly all new and existing tabs turned into this gibberish 
https://paste.the-compiler.org/view/45b5bc02

`~/.local/share/qutebrowser/sessions/default.yml` file contains the same gibberish under`url` and `title` keys for all tabs (the file is 55M now!). So, I've lost all my ~60 tabs with no way to recover.

I don't have any way to reproduce it.

**Config**:
(I've omitted irrelevant options like colors, bindings)
```
c.auto_save.session = True
c.session.lazy_restore = True
c.content.host_blocking.enabled = False
c.content.plugins = True
c.content.webgl = False
c.content.headers.user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.105 Safari/537.36"
c.content.webrtc_ip_handling_policy = "default-public-interface-only"
c.content.cookies.accept = "no-3rdparty"
# c.tabs.select_on_remove = "last-used"
c.tabs.background = True
c.tabs.last_close = "blank"
c.scrolling.smooth = True
c.url.start_pages = ["about:blank"]
c.url.default_page = "about:blank"
c.editor.command = ["emw", "+{line}:{column}", "{file}"]
c.content.autoplay = False
```

**Comment by The-Compiler** [comment]
Do you get back to the sites you were on by using `:back` (H)?

**Comment by wedens** [comment]
> Do you get back to the sites you were on by using :back (H)?

No. Qutebrowser becomes unusable in this state (veeeeeeeery slow). 

But I suppose it could be possible, as I've noticed that this gibberish is the second entry for each tab in the session file. I was able to extract most urls of previously opened tabs from the file (with some noise from previous pages).

**Comment by user202729** [comment]
This is just a typical double-OOM error page. Just click the "try again" (or press H) twice.

By the way, I think it's known issue that when an error page crashes, it should not show another error page (because the memory required may not be immediately available. Cannot find it.

**Comment by wedens** [comment]
> Just click the "try again" (or press H) twice.

Pressing "try again" didn't work. I was able to try it on a couple of tabs and then qutebrowser almost hangs (probably due to those very long strings in each tab?)

**Comment by user202729** [comment]
It's weird that qutebrowser is "very slow" with plenty of RAM available. You can try restarting it (I don't know if there's a leak or something similar, but some users report increasing RAM usage)

**Comment by The-Compiler** [comment]
There are two things going on here:

- The error page leads to a very long URL - see #3918
- The double renderer crash (which wasn't tracked in an issue before I think) - I opened #5108
