### ISSUE TITLE
Tooltips text not shown, just an empty box

### ISSUE THREAD

**Issue by tobip** [qutebrowser/qutebrowser#5106]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/60823304

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Hovering the mouse over a link, the tooltip showing the "title" tag is only an empty box missing the text. 
![vlcsnap-2019-11-09-08h08m37s143](https://user-images.githubusercontent.com/3918330/68524586-160f3980-02c9-11ea-92ea-1a8f7a3d6041.png)

It does work in other browsers on my system (testet Firefox and Chromium)

**Comment by arza-zara** [comment]
See #4520.
