### ISSUE TITLE
set "search scrollbar" colors

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#5107]
Hi,
there's this scrollbar which is spawned upon a search action and shows on it occurrences of search matches.  I don't seem to find a way to configure its colors, so is there or can we have one?

Thanks

**Comment by The-Compiler** [comment]
That's not possible as far as I'm aware - the scrollbar is coming from QtWebEngine/Chromium, and I'm not aware of a way to customize how it looks (not even in Chromium).

**Comment by The-Compiler** [comment]
You got me curious so I digged into Chromium's code - the colors are indeed [hardcoded](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/scroll/scrollbar_theme.cc?l=164-169&rcl=3f36f07b4c7d4834f1f0d6076ce99bc46097e121) there.

**Comment by aleprovencio** [comment]
:(
Thanks for clarifying it.

**Comment by The-Compiler** [comment]
Oh, reading your post again I might need to clarify something: You *can* customize the scrollbar itself, just not the search highlights. You can do so by styling `::-webkit-scrollbar` ([docs](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)) via a CSS file given to `content.user_stylesheets`. Note however that won't work with sites which disallow injecting CSS.

**Comment by aleprovencio** [comment]
That's awesome, it should do just what I intended.
Will test it soon, thanks again and keep up the brilliant work!

**Comment by jgkamat** [comment]
Here is an example: 
http://gist.github.com/olmokramer/5eabbce5dfbfbdafcbcbd497b02ffb17

**Comment by aleprovencio** [comment]
Guys, just tested, it does work, thanks lots
