### ISSUE TITLE
how to permanently disable notifications?

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#5109]
is there any way to permanently tell qutebrowser to never ask me about site notifications, and automatically -internally- do the `n` for me? 

sites keep prompting me if i want to enable notifications. and this creeps me out because i have no idea how this new generation nonsense works. so i keep saying `no`.

any thoughts/advise?

**Comment by The-Compiler** [comment]
`:set content.notifications false`
