### ISSUE TITLE
Option to remove window id in tab-focus view

### ISSUE THREAD

**Issue by afreakk** [qutebrowser/qutebrowser#5114]
When using `tabs_are_windows` option, the id of the window is noisy when using `gt` command.
Example:
![image](https://user-images.githubusercontent.com/2227028/69134741-43719980-0ab8-11ea-9975-1ef2fb30dbfa.png)
The issue is that every listing is padded with window-id bar, so it takes a lot more vertical space than needed.

**Comment by The-Compiler** [comment]
I think the main takeaway here is that the column size should be smaller, which essentially is the same issue as #693. Depending on how that ends up being implemented, it might also be able to hide columns completely.

**Comment by afreakk** [comment]
Id like an option to hide the row that only shows the window ID.
Because when you use `tabs_are_windows` option, you get 2 rows for every tab, I'd like 1 row for every tab/window.

**Comment by The-Compiler** [comment]
Ah, I misunderstood, sorry! That seems totally reasonable - I don't think that even needs a setting, should probably just be the default behavior with `tabs_are_windows`.

**Comment by The-Compiler** [comment]
Fixed via #5150 - thanks @jyscao!
