### ISSUE TITLE
Copy image address does not copy entire URL on Mac

### ISSUE THREAD

**Issue by gulkily** [qutebrowser/qutebrowser#5116]
1. On MacOS, open a page with image(s)
2. Right-click on an image
3. Choose "Copy image address"
4. Paste into a text editor

Expected: Entire URL is copied, e.g. "http://www.example.com/image.gif"

Actual: Only the path after the domain is copied, e.g. "/image.gif"

Reproduced most recently on 1.8.1

**Comment by The-Compiler** [comment]
Reproduced with the qutebrowser logo on https://www.qutebrowser.org/ - on macOS only. Seems to be a Qt bug, as qutebrowser doesn't handle the context menu at all.

I can reproduce with Qt 5.13 as well. Should probably try with the Qt simplebrowser example to make sure it's reproducible there as well, though.

**Comment by The-Compiler** [comment]
Reported upstream as [[QTBUG-80243] macOS: "Copy image address" doesn't copy full URL - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-80243)

**Comment by The-Compiler** [comment]
FYI, there should be a fix for this in Qt 5.15.1: [Only add file url if it references a local file (I2cd41635) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/305115)
