### ISSUE TITLE
Is it possible to add time and date and/or a bash script to statusbar.widgets?

### ISSUE THREAD

**Issue by 3ruce** [qutebrowser/qutebrowser#5117]
It would be great if you could add the time and/or date to the status bar, either via a specific widget or a bash script that could be called...

Is this sort of thing possible at the moment?

I'm running 1.6.1 on Debian 10, installed via apt and the version in the repo...

**Comment by The-Compiler** [comment]
This currently isn't possible - however, it's already listed as a possible use-case for a future Python extension API, see #30.
