### ISSUE TITLE
Keyhint duration setting?

### ISSUE THREAD

**Issue by karthink** [qutebrowser/qutebrowser#5119]
Is there a way to set the keyhint duration? I mean this dialog:

![2019-11-25-100916_433x421_scrot](https://user-images.githubusercontent.com/8607532/69566831-d7d27500-0f6c-11ea-91f7-cde1e4c32fba.png)

In the documentation I can see commands to set the font and the delay for the keyhint but not its duration. It's tough to parse the list when there are many options.

**Comment by arza-zara** [comment]
`input.partial_timeout`

**Comment by karthink** [comment]
Thank you.
