### ISSUE TITLE
h264/h265 playback

### ISSUE THREAD

**Issue by GhostValk** [qutebrowser/qutebrowser#5121]
Hi!

I'm trying to enable playback of videos on twitter and similar sites, which now is -somehow- not working ("The media could not be played."). I'm not sure if it's a problem with the Qt version, or any flag given when installing it (i'm on osx, so it uses the default qt installation).

I have Qt  5.13.2 installed via `homebrew`, but qb uses 5.12 (i don't know either if it's possible to manually set a `qt` path)

Any idea of what could it be?

**Comment by The-Compiler** [comment]
I'm assuming you use the dmg? From the [documentation](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#on-macos):

> The binary release ships with a QtWebEngine built without proprietary codec support. To get support for e.g. h264/h265 videos, you’ll need to build QtWebEngine from source yourself with support for that enabled.

**Comment by GhostValk** [comment]
Indeed i am, so, i must build qb from source and QtWebEngine too?

**Comment by The-Compiler** [comment]
There's nothing to build with qutebrowser - it looks like Homebrew's Qt comes with proprietary codec support, so you might be able to start qutebrowser with that from a terminal (see the section after my link in the install docs). Also see #4127.

**Comment by GhostValk** [comment]
I guessed it could be fixed with something like that, thanks!

Could you be a bit more specifc on how to find that? I've been searching the "install docs" and haven't been able to get the flag to start it with homebrew qt.

**Comment by The-Compiler** [comment]
You could install qutebrowser [via pip](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#manual-install-1), or [use tox](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-dependencies-system-wide-qt) - I can't say much more than that really, I'm not using macOS myself.

**Comment by GhostValk** [comment]
Wait, i'm not following.. you said: "you might be able to start qutebrowser with that from a terminal (see the section after my link in the install docs)"

How can i specify which qt version to use when starting qutebrowser?

Now, for the last answer, so, i should specify the qt version to use when INSTALLING? So i have to reinstall it using, let's say, pip and there specify the qt version? How do i do that?

**Comment by The-Compiler** [comment]
Which Qt installation is used depends on your Python installation - you install PyQt for a given Python installation, and that PyQt is built against a given Qt installation.

If you use the .dmg, that ships with its own copy of Python and Qt. If you want to use Homebrew's Qt, you'd need to install PyQt via Homebrew and then use the Homebrew-installed Python to install/run qutebrowser.

**Comment by GhostValk** [comment]
Well, so far, i tried installing it from ´pip´, but i'm getting this error after a couple packages are installed:

`
Installing collected packages: qutebrowser
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/usr/local/bin/qutebrowser'
`

However, it looks like it gets installed anyway, since if i try to install it again it says it's already installed (however, no binary is symlinked to /usr/local/bin/)

`
pip3 install qutebrowser
Requirement already satisfied: qutebrowser in /usr/local/lib/python3.7/site-packages (1.8.2)
`

How can i start it afterwards?

**Comment by The-Compiler** [comment]
You'd run the `/usr/local/bin/qutebrowser` binary normally - no idea why it isn't getting installed, possibly some macOS system integrity stuff. You could probably try running `python3.7 -m qutebrowser`.

**Comment by GhostValk** [comment]
I can't run that binary since it doesn't exist. Nothing is getting installed to bin/.

The output of python -m qutebrowser is:

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 41, in <module>
    from qutebrowser.misc.checkpyver import check_python_version
ModuleNotFoundError: No module named 'qutebrowser.misc'; 'qutebrowser' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 39, in <module>
    import qutebrowser
  File "/usr/local/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 45, in <module>
    from .misc.checkpyver import check_python_version
ImportError: attempted relative import with no known parent package
`

I think it wasn't installed properly.

**Comment by The-Compiler** [comment]
No idea what's going on there I'm afraid - you might have more luck with an install based on tox/virtualenv as it doesn't require writing to system-wide folders.

**Comment by GhostValk** [comment]
Well, no luck either with tox. I guess i'll have to stick with no videos for a while. Thanks a lot man, i'll post back if i get it to work.

**Comment by GhostValk** [comment]
After a lot of testing, reinstalling, and etc. i managed to install ´pyqt5´ and qb from python 3.7. It gets linked and everything "seems" to be ok, but when trying to run qb, a message pops up:

`
qutebrowser needs QtWebKit or QtWebEngine, but neither could be imported!
The errors encountered were:
QtWebKit: cannot import name 'QtWebKit' from 'PyQt5' (/usr/local/lib/python3.7/site-packages/PyQt5/__init__.py)
QtWebEngine: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/local/lib/python3.7/site-packages/PyQt5/__init__.py)
`

Any idea of what could it be?

**Comment by GhostValk** [comment]
Answer to mysefl, managed to fix it!

`pip3 install PyQtWebEngine`

And working flawlessly, with homebrew Qt/pyqt. However, videos are still not playing in twitter (same behaviour as before).

**Comment by The-Compiler** [comment]
> Answer to mysefl, managed to fix it!
> 
> `pip3 install PyQtWebEngine`
> 
> And working flawlessly, with homebrew Qt/pyqt. However, videos are still not playing in twitter (same behaviour as before).

Nope. If you install PyQt5/PyQtWebEngine via pip, you get (another) pre-built version of Qt rather than Homebrew's Qt (you can verify that by checking the Qt path in `:version`)

> Edit: Looks like QtWebEngineWidgets is deprecated, here they propose a solution:
> 
> https://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5

QtWebKit is deprecated (though [maintained independently from Qt again](https://github.com/annulen/webkit/)), not QtWebEngine.

**Comment by The-Compiler** [comment]
Ah, looks like the last PyQt upgrade for Homebrew causes this: https://github.com/Homebrew/homebrew-core/pull/46598

There, PyQt was upgraded to a newer version (which splits PyQt and PyQtWebEngine), but apparently nobody packaged PyQtWebEngine for Homebrew since then (and the PyQt package doesn't include it either). You might want to report that to Homebrew, or maybe ask in that PR for clarification.

**Comment by GhostValk** [comment]
If i uninstall pip pyqt, and install/try to run qb with homebrew qt/pyqt installed only, i'm getting the following error:

`
10:28:38 WARNING: Could not find the Qt platform plugin "cocoa" in ""
10:28:38 CRITICAL: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Fatal Python error: Aborted
Current thread 0x00000001158c35c0 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/qutebrowser/app.py", line 828 in __init__
  File "/usr/local/lib/python3.7/site-packages/qutebrowser/app.py", line 105 in run
  File "/usr/local/lib/python3.7/site-packages/qutebrowser/qutebrowser.py", line 200 in main
  File "/usr/local/bin/qutebrowser", line 8 in <module>
fish: 'qutebrowser' terminated by signal SIGABRT (Abort)
`

Not sure if it's part of the same or another problem.

Do you know a previous homebrew pyqt that worked with qb?

**Comment by The-Compiler** [comment]
The one before the update I linked might work - but this is really something Homebrew should fix.

**Comment by GhostValk** [comment]
Yeah, i know, i'm gonna see if i can install a previous version with homebrew.

**Comment by GhostValk** [comment]
Well, i'm gonna try building out of homebrew, which version would you recommend? 5.12 or 5.13?

**Comment by The-Compiler** [comment]
In general I'd recommend 5.13, but there PyQtWebEngine was split off, so you would need to write a separate Formula first (or like I said, report this to Homebrew). I feel like we're starting to go in circles :wink:

**Comment by jasonsun0310** [comment]
I have managed to build Qt and QtWebEngine from ground up and then build PyQt PyQtWebEngine w.r.t to them and installed a fully functional qutebrowser with H264 support on Mac Catalina 10.15.4 (the lastest version). It takes me about two days because the latest Qt git source does not build well with the current PyQtWebEngine. So I had to check out an older version. There are some errors during the Qt building process due some minor QT make file bugs.

**Comment by The-Compiler** [comment]
@jasonsun0310 Given that qutebrowser is not a Homebrew formula (it's available via Brew Cask) I don't see how that's possible. License-wise I have no idea, I do think you'll need to acquire licenses to redistribute them in binary form. Maybe write some kind of write-up/how-to instead?

**Comment by happyjake** [comment]
Replace QtWebEngineCore.framework in .app with homebrew's QtWebEngineCore.framework. It works for me.
```shell
rm -rf dist/qutebrowser.app/Contents/Resources/PyQt6/Qt6/lib/QtWebEngineCore.framework
cp -R /opt/homebrew/Cellar/qt/6.3.1/lib/QtWebEngineCore.framework dist/qutebrowser.app/Contents/Resources/PyQt6/Qt6/lib/
```

**Comment by metziger23** [comment]
> Replace QtWebEngineCore.framework in .app with homebrew's QtWebEngineCore.framework. It works for me.
> 
> ```shell
> rm -rf dist/qutebrowser.app/Contents/Resources/PyQt6/Qt6/lib/QtWebEngineCore.framework
> cp -R /opt/homebrew/Cellar/qt/6.3.1/lib/QtWebEngineCore.framework dist/qutebrowser.app/Contents/Resources/PyQt6/Qt6/lib/
> ```

This worked for me as well. Thank you very much!
