### ISSUE TITLE
tab on top and status bar bottrom are hide or no show always

### ISSUE THREAD

**Issue by enrico20026** [qutebrowser/qutebrowser#5122]
I like to hide status and tab and title windows, to get more space available for the page:
But, connection is slow and when im on raspberry the desktop is also slow, a status message (working on tab nr ..., processing action ...) can help,  because otherwise i dont know what's going on, and i have time to do worst, when i start a [t] + [;] + [m]  to run mpv from  a link, a temporary status message would help, just to not repeat the request 2 or 3 time.

**Comment by The-Compiler** [comment]
See #2157 for the statusbar. As for running mpv, you can use `spawn -v` rather than `spawn`.
