### ISSUE TITLE
Multiple placeholders in url.searchengines

### ISSUE THREAD

**Issue by MDingas** [qutebrowser/qutebrowser#5123]
The feature is really cool as is, but I think it would be helpful if many different placeholders were supported.

For example, one can currently do 
`
"r": "https://www.reddit.com/r/{}"`

and "r linux" would map to "https://www.reddit.com/r/linux".

But say i'd also like to have a shortcut for searching something in a specific subreddit. One could imagine such a syntax:

`"r" : "https://www.reddit.com/[r/{}]/[search/?q={}&restrict_sr=1"]`

and "r linux # ubuntu" would map to "https://www.reddit.com/r/linux/search/?q=ubuntu&restrict_sr=1

The curvy brackets would be filled by the parameters by the order they appear in, and everything inside the square brackets would be nullified if the specific parameter wasn't provided. The field separator, for example #, would be useful to objectively separate that string goes where, in cases where a multi-word parameter is needed (like searching something up on a search engine).

As such one could:

- Go to the base url with "r"
- Go to a subreddit's main page with "r arg1"
- Go to the search page of a subreddit with "r arg1 # arg2"

I've also come across a similar challenge with youtube for example. In some cases i'd like to go to a specific channel, in another i'd just want to search for a term in the main search bar. In that case, however, it would make more sense to create two different binds. However, in the example above, some feature that could allow mapping many parameters to different places in the url could be quite helpful.

**Comment by The-Compiler** [comment]
I feel like this is trying to squeeze too much into the searchengine syntax. For more complex cases like yours, it'd probably be more beneficial to use a future Python extension API (see #30) to define a custom command. Then you can handle arguments and add/remove parts of the URL without having to invent a mini-language/-syntax for it.
