### ISSUE TITLE
IP with port doesn't open as URL anymore

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5125]
Since 5008b3b1648617e9651770dc878a7f9544b7b17c, opening something like `192.168.0.118:8083` causes a search instead of opening the IP as URL.

@arza-zara could you please take a look?

**Comment by The-Compiler** [comment]
We do this currently:

```python
    if not utils.raises(ValueError, ipaddress.ip_address, urlstr):
        # Valid IPv4/IPv6 address
        return True
```

which catches cases like `192.168.0.118` but not `192.168.0.118:8083`. Maybe we should just use `url.host()` (or `host`) instead of `urlstr` there?

**Comment by arza-zara** [comment]
> Maybe we should just use `url.host()`

I guess so, except `host()` converts some stuff to IP addresses, so I added an additional substring check. `isNull()` check seemed unnecessary so I removed it. See #5139.
