### ISSUE TITLE
Qute-lastpass prompts for password 5 times when try to cancel when not logged in

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#5130]
**Version info (see `:version`)**:

Latest master.

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Because https://github.com/qutebrowser/qutebrowser/blob/81b3ef937ebf202670c1561429552874ed51d32a/misc/userscripts/qute-lastpass#L123
invokes the lpass binary 5 times and doesn't break the loop when the user cancel, the user would have to press escape 5 times when they want to cancel.

**How to reproduce**

* Log in with `lpass login`.
* Make the lpass client "forget password" (kill the agent, wait for an hour, set `LPASS_AGENT_DISABLE=1, or reboot the computer, one of them should work)
* Try to invoke the user script from the browser. It should now prompt for the password.
* Now try to cancel it. You need to press esc 5 times.

**Comment by The-Compiler** [comment]
cc @welps

**Comment by welps** [comment]
I'll take a look.

**Comment by welps** [comment]
Provided fix in #5134
