### ISSUE TITLE
Low colors using hardware acceleration with AMD GPU

### ISSUE THREAD

**Issue by Yaroslav-95** [qutebrowser/qutebrowser#5133]
**Version info (see `:version`)**:
qutebrowser v1.8.2
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.8.0
Qt: 5.13.2
PyQt: 5.13.2

sip: 4.19.19
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.13.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: Qt5CTProxyStyle
Platform: Linux-5.4.1-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

*Some extra info: I am using an AMD RX 5700 XT GPU, with mesa 19.2 stable, and open source AMDGPU drivers.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
For some reason I am getting low colors (16-bit-like colors) on qutebrowser using QtWebEngine and hardware acceleration. If I use software acceleration, colors are fine, but many sites will work sluggishly, and WASM sites won't even work at all.
How it looks like with hardware acceleration:
![image](https://user-images.githubusercontent.com/30291149/70054642-ff6ab280-15e8-11ea-9cf6-cffdc7f85368.png)
How it should look like:
![image](https://user-images.githubusercontent.com/30291149/70054769-3640c880-15e9-11ea-8047-07544c3b1c18.png)

I really like qutebrowser, and for me in terms of usability it's the best browser out there. Unfortunately this bug has been bugging me (pun intented just a little) lately, since sometimes I need to access sites that make use of WebGL/WASM, but the colors just look off with hardware acceleration.

**Comment by The-Compiler** [comment]
Can you reproduce this with [KDE Falkon](https://www.falkon.org/)? Also, what about Chromium?

**Comment by Yaroslav-95** [comment]
Chromium is fine. Falkon has the same issue as qutebrowser, so I suppose it's a bug with QtWebEngine. Also, I forgot to mention one detail, I am running qutebrowser on wayland (sway), however, on my laptop with an intel GPU it works just fine (also on sway/wayland).

**Comment by The-Compiler** [comment]
Yep, that looks like a QtWebEngine bug then - please report it in the [Qt bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa).
