### ISSUE TITLE
Renderer process crashes on Riot IM webapp

### ISSUE THREAD

**Issue by gjabell** [qutebrowser/qutebrowser#5137]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/8d809d5c

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Opening the Riot IM webapp crashes the renderer process.

**How to reproduce**

[riot.im/app](https://riot.im/app) (or any other site running Riot's webapp).

**Comment by The-Compiler** [comment]
Works fine for me. Can you check whether you see the same issue with [KDE Falkon](https://pkgs.alpinelinux.org/package/edge/community/x86_64/falkon)?

**Comment by gjabell** [comment]
Hmm, might be a musl issue then. I'll try with Falkon when I have a sec

06.12.2019 12:25:06 Florian Bruhin <notifications@github.com>:

**Comment by gjabell** [comment]
Same issue with Falkon, also confirmed with some people on the alpine IRC channel that it's an issue on their end too.

**Comment by The-Compiler** [comment]
Closing this then - since Qt upstream doesn't support musl, I'm guessing you're on your own.
