### ISSUE TITLE
'No module named 'PyQt5' error on install

### ISSUE THREAD

**Issue by dilgreen** [qutebrowser/qutebrowser#5138]
Hi, just attempted install on MacOs (10.13.6/ Macbook15"2011), using:
```
$ brew install qt5
$ pip3 install qutebrowser
```
These went fine, but I got this message on launch: 

> Fatal error: PyQt5.QtCore is required to run qutebrowser but could not be imported! Maybe it's not installed?

Thanks for looking!
[Screenshot 2019-12-08 12 12 33](https://user-images.githubusercontent.com/5934679/70389279-1cbaca80-19b5-11ea-93f0-77b5405aee88.png)

**Comment by dilgreen** [comment]
It may be that this comment buried in the brew output is related:

> We agreed to the Qt open source license for you. If this is unacceptable you should uninstall.
> qt is keg-only, which means it was not symlinked into /usr/local, because Qt 5 has CMake issues when linked.
> If you need to have qt first in your PATH run:
>  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
> For compilers to find qt you may need to set:
>  export LDFLAGS="-L/usr/local/opt/qt/lib"
>  export CPPFLAGS="-I/usr/local/opt/qt/include"

**Comment by dilgreen** [comment]
performed the 'PATH' instruction: successfully, but it didn't fix the issue (same quiebrowser error message).

**Comment by rien333** [comment]
What about installing qutebrowser via brew?

**Comment by The-Compiler** [comment]
You will need to install PyQt5 as well - e.g. via Homebrew, however, it looks like Homebrew doesn't have a QtWebEngine package anymore. You might need to build it from source.

**Comment by dilgreen** [comment]
> What about installing qutebrowser via brew? This might make more sense than pip, given that qutebrowser has non-python dependencies, like Qt.

idk - I imagine that the official install instructions would use homebrew for both if it were practical?

**Comment by dilgreen** [comment]
> You will need to install PyQt5 as well - e.g. via Homebrew, however, it looks like Homebrew doesn't have a QtWebEngine package anymore. You might need to build it from source.

OK, will go for that and see - tx for the help - I was reporting for the package builders, as the error message asked me to, though (not just for help) so perhaps the issue shouldn't be closed?

**Comment by The-Compiler** [comment]
Hmm, the Homebrew install instructions should probably be reworded. A pip install deliberately doesn't install PyQt5, because that comes with a binary build of Qt, and in that situation it'd be better to just use the precompiled .dmg/.exe in most scenarios.

**Comment by dilgreen** [comment]
Indeed it seems that this package is not doing well! I just installed PyQt5, no problem, with:
```
 python3 -m pip install PyQt5
```
But now Quteb fails with this:

```
qutebrowser needs QtWebKit or QtWebEngine, but neither could be imported!
The errors encountered were:
QtWebKit: cannot import name 'QtWebKit' from 'PyQt5' (/usr/local/lib/python3.7/site-packages/PyQt5/__init__.py)
QtWebEngine: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/local/lib/python3.7/site-packages/PyQt5/__init__.py)
```

**Comment by The-Compiler** [comment]
If you want to pip install it, you need to install `PyQtWebEngine` as well - but why not just use the `.dmg` at that point?

**Comment by dilgreen** [comment]
Indeed I will .. Tx

**Comment by dilgreen** [comment]
I'm up and running tx.

**Comment by supremew** [comment]
This seems to be due to the use of sip5 when compiling pyqt5. I had this problem when I installed pyqt5 with sip5 two days ago.

Later, I used the code generated by Sip4 to compile and install pyqt5 and pyqtweb engine.

Specific steps:
1. Compile and install the latest Sip4. * ***
2. Compile and install pyqt5
3. Compile and install pyqtweb engine
4. Compile and install qutebrowser

**Comment by The-Compiler** [comment]
@supremew That sounds like some unrelated issue - also I'm running with sip5 just fine.

**Comment by dzzxjl** [comment]
i meet the same issue

**Comment by The-Compiler** [comment]
@dzzxjl Without any details, there's nothing I can say. The only reason this issue is still open is because I want to adjust the docs a bit.

**Comment by hkbiet** [comment]
Is this done ?

**Comment by The-Compiler** [comment]
@hkbiet Adjusting the docs? No, otherwise the issue would be closed.

**Comment by The-Compiler** [comment]
I updated the Homebrew instructions in 59ac5b6b690963e514220886a60a1c5b47aa1188.
