### ISSUE TITLE
qt5-debug packages out of date (icu)

### ISSUE THREAD

**Issue by PhilSmith31** [qutebrowser/qutebrowser#5141]
**Version info**:
5.13.2

**Description**:
The qt5-debug packages should be rebuilt, linking against the new and maintained icu version 65.x.
They still need icu64 packages installed.

**Reproduce**:
Reproducable for sure on Arch Linux:
"error while loading shared libraries: libicui18n.so.64: cannot open shared object file: No such file or directory"
will appear on programs relying on qt5.

**Comment by The-Compiler** [comment]
Duplicate of https://github.com/qutebrowser/qt-debug-pkgbuild/issues/25
