### ISSUE TITLE
qute-pass is incompatible with gopass'es multiple password mounts

### ISSUE THREAD

**Issue by bascht** [qutebrowser/qutebrowser#5142]
**Version info (see `:version`)**:
v1.8.1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
While `gopass` is widely compatible with `pass`, it offers the possibility to mount multiple password stores (e.g. for shared team secrets). The `qute-pass` way of traversing the password store directly doesn't cut it, as it will list only a single password store.

**How to reproduce**

Open a site that occurs in multiple password stores and trigger `qute-pass`. It will only offer passwords from `PASSWORD_STORE_DIR`.

**Comment by wildente** [comment]
i've created some modifications to the qute-pass userscript with basic gopass support in #5170
