### ISSUE TITLE
Google blocks "unknown" browsers from signing in

### ISSUE THREAD

**Issue by AndrewBelt** [qutebrowser/qutebrowser#5144]
**Version info (see `:version`)**: v1.8.3, actually git commit 02c3f02ed

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

When signing into Google (Gmail, Youtube, Google Docs, Google Drive, and anything using Google's sign-in), it fails with

>You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.
Try using a different browser. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)

This means that once you sign out of Google (or lose your cookies or install Qutebrowser for the first time), you cannot access any of these Google services.

This change was noticed here. https://www.reddit.com/r/kde/comments/e7136e/google_bans_falkon_and_konqueror_browsers/

**How to reproduce**

Attempt to log into Google by clicking Sign In at https://www.google.com/ or directly at https://accounts.google.com/signin/v2/identifier.
Once your password is authenticated, the form fails to continue, stopping at
![2019-12-11-172621_472x520_scrot](https://user-images.githubusercontent.com/338179/70665911-95cb5380-1c3b-11ea-9e50-696e17340bf8.png)

**Comment by AndrewBelt** [comment]
I have just read https://www.reddit.com/r/qutebrowser/comments/e6r2g8/unable_to_log_into_google_account/ and https://lists.schokokeks.org/pipermail/qutebrowser/2019-December/000676.html.

I originally attempted a workaround by setting my user agent to Google Chrome on Windows, but it didn't work. I suppose more advanced browser fingerprinting is used by Google's sign-in page.

However, I set my user agent to Firefox 71 on Windows, obtained from https://techblog.willshouse.com/2012/01/03/most-common-user-agents/, and I can now log in.
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
```
I suppose it works because if Google's sign-in form sees a Chrome user agent, it expects a different browser fingerprint, so it rejects it. But maybe it's more lenient on the fingerprint match if it sees a Firefox user agent.

**Comment by The-Compiler** [comment]
Note that setting that UA globally is a bad idea - it'll break stuff on various other websites. You might want to try setting it with a `https://accounts.google.com/*` URL pattern - or ideally, even only `https://accounts.google.com/signin` or so, if that works. Please let me know what works and what doesn't, as I still can't reproduce this with my own Google account.

**Comment by pylipp** [comment]
With `:set c.content.headers.user_agent 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 https://accounts.google.com/*'` I can log in to my Google account.
Using [this](https://i.imgur.com/KRKvOpJ.png) found on [reddit](https://www.reddit.com/r/linux/comments/eah6z5/google_now_bans_some_linux_web_browsers_from/fard0s2?utm_source=share&utm_medium=web2x)

**Comment by The-Compiler** [comment]
@pylipp See the comment above yours

**Comment by pylipp** [comment]
Sorry, meant to comment in response of you asking about whether setting the UA to a specific URL instead of globally setting worked.
I think the difference is that I'm on Linux while @AndrewBelt is on Windows.

**Comment by The-Compiler** [comment]
@pylipp That sets your user agent to that string including the URL. You probably meant `:set -u https://accounts.google.com/* content.headers.user_agent 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0' (also, why 57 rather than something newer like 70.0?)

**Comment by AndrewBelt** [comment]
@pylipp No, I'm on Linux. I just happened to choose a Firefox 70 Windows user agent, but I could have chosen anything that Google's Sign-in supports.

**Comment by pylipp** [comment]
I see, the `-u` option is what 'This setting supports URL patterns' refers too - TIL, thanks! 
Also putting FF 70 is sensible.

**Comment by The-Compiler** [comment]
I just wrote a more detailed explanation for what's going on with the Google Accounts issue: #5182

@AndrewBelt I also edited your original post with a link to give this some more visibility. I hope that's okay!
