### ISSUE TITLE
in Qt 5.13.2, Can't load flash pepper plugin

### ISSUE THREAD

**Issue by supremew** [qutebrowser/qutebrowser#5146]
qutebrowser v1.8.3
Git commit: 02c3f02ed-dirty (2019-12-09 00:38:10 +0100)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.5.3
Qt: 5.13.2
PyQt: 5.13.2

sip: 4.19.19
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.13.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.0j  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.15.0-30deepin-generic-x86_64-with-Deepin-15.11-stable, 64bit
Linux distribution: Deepin 15 (unknown)
Frozen: False
Imported from /usr/local/lib/python3.5/dist-packages/qutebrowser-1.8.3-py3.5.egg/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /opt/Qt5/libexec, data path: /opt/Qt5
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID=Deepin
DISTRIB_RELEASE="15.11"
DISTRIB_DESCRIPTION="Deepin 15.11 "
DISTRIB_CODENAME=stable

--- /etc/os-release ---
PRETTY_NAME="Deepin 15"
NAME="Deepin"
VERSION_ID="15.11"
VERSION="15.11"
ID=deepin

Paths:
cache: /home/deepin-mew/.cache/qutebrowser
config: /home/deepin-mew/.config/qutebrowser
data: /home/deepin-mew/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

When I open a webpage using the flashplugin, the following error will appear:
```
[ERROR:flash/platform/pepper/pep_module.cpp(143)] Browser does not support interface PPB_TCPSocket_Private;0.5|PPB_TCPSocket_Private;0.4|PPB_TCPSocket_Private;0.3.
```

I found the cause of the problem in  [https://bugreports.qt.io/browse/QTBUG-78280](https://bugreports.qt.io/browse/QTBUG-78280)  , so I modified the **qutebrowser/config/configinit.py**  file. Revised as follows:

original source
```
        'content.headers.referer': {
            'always': None,
            'never': '--no-referrers',
            'same-domain': '--reduced-referrer-granularity',
        }
```

source after modification
```
        'content.headers.referer': {
            'always': None,
            'never': '--no-referrers',
            'same-domain': '--reduced-referrer-granularity',
           # modified by deepin-mew
           'same-domain':'--enable-pepper-testing',
        }
```

Qutebrowser seems to be used to pass QT parameters, but I have tried it. It may not be the right way to use it, so I want to modify it to meet my current use..

**Hope to give more advice or find a good solution as soon as possible**

**Comment by The-Compiler** [comment]
You can add that flag to the `qt.args` setting. I'd rather not do so by default, given the unknown security implications. Also note your change above breaks the `content.headers.referer` setting.
