### ISSUE TITLE
how to view "cid:..." linked images in qutebrowser?

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#5149]
say i got a html document with this in it:

```
  <img src="cid:image001.jpg@01D53404.AB2686C0">
```
how to make qutebrowser display it?  e.g. any way to slap that content inside the html document (e.g. put it in the header) without me needing to modify the `src="cid:..."` uri?

i know one way is to encode the image by changing that uri into `src="content:IMAGE_BASE64_DUMP_HERE"`.  but i wonder if there r even lazier ways in terms of reducing modifications needed in this html doc so that qutebrowser can render it?

ideally, it would be great to not need to modify that html file, at all, and -instead- only tell qutebrowser _"hey qutie, here is the base64 of that `cid:...` uri, go figure!  kthx byeee!"_.

**Version info (see `:version`)**:

    qutebrowser v1.8.1
    Git commit: 
    Backend: QtWebEngine (Chromium 73.0.3683.105)

    CPython: 3.6.9
    Qt: 5.13.2
    PyQt: 5.13.2

    sip: 4.19.19
    colorama: no
    pypeg2: 2.15
    jinja2: 2.10.3
    pygments: 2.4.2
    yaml: 5.1.2
    cssutils: no
    attr: 19.3.0
    PyQt5.QtWebEngineWidgets: yes
    PyQt5.QtWebEngine: 5.13.2
    PyQt5.QtWebKitWidgets: no
    pdf.js: no
    sqlite: 3.30.1
    QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

    Style: QFusionStyle
    Platform: Linux-5.4.2-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i5-3570K_CPU_@_3.40GHz-with-gentoo-2.6, 64bit
    Linux distribution: Gentoo/Linux (gentoo)
    Frozen: False
    Imported from /usr/lib64/python3.6/site-packages/qutebrowser
    Using Python from /usr/bin/python3.6
    Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

**Comment by toofar** [comment]
That looks like how multipart mime (email) messages refer to inline attachements in multipart/related containers. I don't think web browsers are expected to support mail files. If that is that case I would suggest to write a script or userscript to transform them, all the mime parsing stuff is in the standard library but you would also have to parse the html and look for cid links to replace.

**Comment by The-Compiler** [comment]
Also there isn't anything qutebrowser-specific about this - if you find something that works in Chromium, it'll likely work in qutebrowser as well.
