### ISSUE TITLE
Hitting 10T registers as 0T or T, while 11T registers as it should

### ISSUE THREAD

**Issue by sim590** [qutebrowser/qutebrowser#5158]
**Version info (see `:version`)**:

```
qutebrowser v1.6.2
Git commit: 091f5acd0 (2019-05-28 09:45:31 +0200)
Backend: QtWebEngine (Chromium 69.0.3497.128)
```

**Does the bug happen if you start with `--temp-basedir`?**:

In fact, it doesn't happen when using `-T` optional flag...

**Description**

Title is self explanatory.

**How to reproduce**

1. Open at least 11 tabs
2. Issue `1T`, then `10T` and notice that the tab has now changed to tab number 2 (contrary to expectations).
3. Issue `1T`, then `11T` and notice that the tab has now changed to tab number 11 (as expected).

**Comment by user202729** [comment]
Duplicate of #3927.

**Comment by sim590** [comment]
Oh! You are right! I should have though of that. I indeed mapped `0` to some function. Thanks. I'm closing this issue.
