### ISSUE TITLE
Private session and custom config

### ISSUE THREAD

**Issue by yellowhat** [qutebrowser/qutebrowser#5161]
Hi,
I would like to have a private mode with a `temp-basedir` that uses part of my `config.py` file.
For example I would like to have a different set of start pages or different other options from the standard qutebrowser.
So inside `config.py` I have:
```
if c.content.private_browsing:
    start_pages = ['example1.com']
else:
    start_pages = ['example2.com']
c.url.start_pages = start_pages
``` 
I was expecting that running:
```
qutebrowser --temp-basedir -s content.private_browsing True --config-py ~/.config/qutebrowser/config.py
```
would modify the `c.content.private_browsing` to `True` __before__ reading `config.py`, but in reality is the opposite; infact I can see that the (wrong) `start_pages` are opened in private tabs (from the tab title).

I know that I can simply point to a different `config_private.py` or a different `base_dir` with another `config.py`.

But I would like to have one single `config.py`, as the number of difference would be very low.

Another possible solution would be:
- to check the `basedir` location, but I am not able to find that variable in the `config.py` context
- pass an argument with a value to Python, but I do not know how to do it

Any ideas?

Thanks

**Comment by toofar** [comment]
I think it is on purpose that the temporary settings (from -s or --set) on the command lines override what is set in config.py, thus they have to be applied afterwards. You can get the command line arguments like this (but it may stop working in a future version):
```python
import sys
from qutebrowser.qutebrowser import get_argparser
parser = get_argparser()
args = parser.parse_args(sys.argv[1:])
temp_settings = dict(args.temp_settings)
if temp_settings.get("content.private_browsing"):
    print("private mode")
print(f"basedir: {args.basedir}"
```

**Comment by yellowhat** [comment]
Thank you very much.
That is exactly what I needed.
