### ISSUE TITLE
What happens if I run 'qutebrowser -B /home/user/path/to/dir' ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [qutebrowser/qutebrowser#5166]
If I run qutebrowser like this:  `qutebrowser -B /home/user/path/to/dir`

then would all of the browsing data, cache, cookies, configs and etc go under the `/home/user/path/to/dir` directory ? 

Does qutebrowser create any file on the disk outside of the `/home/user/path/to/dir` directory ?

**Comment by toofar** [comment]
Apart from the folders created by [this upstream bug](https://bugreports.qt.io/browse/QTBUG-62957) (which I don't believe are actually used for anything) yes, all writes should be confined to that directory.

**Comment by The-Compiler** [comment]
There's probably also some stuff in /tmp getting touched FWIW.
