### ISSUE TITLE
Digraph/Text expansion Support 

### ISSUE THREAD

**Issue by ottopiramuthu** [qutebrowser/qutebrowser#5167]
Coming from Vim, digraphs (listed with `:dig`) can be used to have special characters in insert mode. For example: 
- `<Ctrl-K>u:` inserts ü 
- `<Ctrl-K>e'` inserts é
- `<Ctrl-K>D*` inserts Δ

It would be nice to have this functionality in Qutebrowser. 
Some other requests:
- allowing binding `Ctrl-K`'s function to another key
- having a digraphs dictionary in the config file to add customs or change existing ones
- allowing this to work for longer strings of characters and not just digraphs

**Comment by The-Compiler** [comment]
You can already do this with normal bindings:

```
:bind --mode=insert <Ctrl-K>u: insert-text ü
:bind --mode=insert <Ctrl-K>e' insert-text é
:bind --mode=insert <Ctrl-K>D* insert-text Δ
```
