### ISSUE TITLE
Modify CSP Headers

### ISSUE THREAD

**Issue by Jumblemuddle** [qutebrowser/qutebrowser#5168]
I'd like to use the https://web.hypothes.is/ bookmarklet, however on pages with restrictive CSP headers (GitHub), it won't work.
Some people have used things like https://github.com/FirefoxBar/HeaderEditor to modify the CSP headers to allow the bookmarklet. (https://medium.com/@delahera/hypothesis-web-annotation-mobile-358db1f9ec46#4090)

It'd be great if Qutebrowser allowed editing of headers (CSP specifically) through some mechanism.

**Comment by The-Compiler** [comment]
This isn't possible with the QtWebEngine API - this Qt bug has some related discussion:

[[QTBUG-61071] Need intercept and change traffic. - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-61071)
