### ISSUE TITLE
best qutebrowser alternative as of late 2019?

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#5169]
**Version info (see `:version`)**: v1.8.1.

**If applicable: Does the issue happen if you start with `--temp-basedir`?**:  sry not applicable.

**bg:** i'm contemplating treason to defect into another browser, but not sure if there is anything nice out there in a vimmy way.  ideally i want to defect into something nice, like chormium, with all the plugin goodies (e.g. uBlock), gpu accel, etc, and yet nice vim interface so that i avoid touching any mice.

**q:** any recommendations on where should i defect to?

**Comment by The-Compiler** [comment]
The readme has a [list of alternatives](https://github.com/qutebrowser/qutebrowser#similar-projects).
