### ISSUE TITLE
Qb freezes my system

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#5178]
**Description**

I got my new laptop and installed arch and qutebrowser as usual. However, this time qb behaves differently. It freezes my system often: window manager stops responding, I cannot change workspace, cursor does not move; however, music keeps playing. While it happens, there's no way to fix it except shutting off the system brute-force. I thought it was because my laptop is too old (thinkpad T61 with intel centrino pro), but it can do whole lots of stuff in firefox.

Currently, I don't have a good way to reproduce. All I know is that opening youtube and reddit makes qutebrowser unstable, and the freeze follows quickly.

It might relate to this [post](https://github.com/qutebrowser/qutebrowser/issues/5163), but things are great in chromium and firefox.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Version info (see `:version`)**:
qutebrowser v1.8.3
Git commit:
Backend: QtWebEngine (Chromium 77.0.3865.129)

CPython: 3.8.1
Qt: 5.14.0
PyQt: 5.14.0

sip: 5.0.1
colorama: no
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.4.8-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/USER/.cache/qutebrowser
config: /home/USER/.config/qutebrowser
data: /home/USER/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/USER/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:01

**CPU info**
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Duo CPU     T7500  @ 2.20GHz
stepping	: 11
microcode	: 0xb6
cpu MHz		: 1223.063
cache size	: 4096 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority dtherm ida
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4390.52
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Core(TM)2 Duo CPU     T7500  @ 2.20GHz
stepping	: 11
microcode	: 0xb6
cpu MHz		: 1211.708
cache size	: 4096 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm lahf_lm pti tpr_shadow vnmi flexpriority dtherm ida
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4390.52
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**Comment by The-Compiler** [comment]
- Can you try to reproduce this with [KDE Falkon](https://www.falkon.org/)
- Are you sure things work fine with Chromium?
- Do you have `xf86-video-intel` installed? If so, can you uninstall it? That uses the modesetting driver instead - I'm not sure if that works on a rather old CPU though.

**Comment by jcguu95** [comment]
Thanks for the response.

>     * Can you try to reproduce this with [KDE Falkon](https://www.falkon.org/)?
> 
>     * Are you sure things work fine with Chromium?
> 
>     * Do you have `xf86-video-intel` installed? If so, can you uninstall it? That uses the modesetting driver instead - I'm not sure if that works on a rather old CPU though.

1. Sure. It freezes the system soon after I opened `reddit.com`, `github.com`, and `youtube.com` too. 

2. Since I still can't find a definite way to reproduce, I cannot be 100% sure. All I can say is that Chromium has not frozen my system yet at all. On the other hand, qb and falkon are very unstable here.

3. I believe that I do not have it installed. `sudo pacman -S xf86-video-intel` does not mention any "reinstalling".

**Comment by The-Compiler** [comment]
I suggest you report this to the [Qt bug tracker](https://bugreports.qt.io/secure/Dashboard.jspa) then (with component webengine) - nothing qutebrowser can do here, as it looks like a problem with QtWebEngine and/or your graphic drivers.

Alternatively, I guess you could try *installing* `xf86-video-intel` and see if things get more stable that way.

**Comment by The-Compiler** [comment]
Oh, another thing you could try is playing with the `qt.force_software_rendering` option which will bypass your graphic drivers to varying degrees. Note that setting it will require a restart of qutebrowser.

**Comment by tiborsimko** [comment]
Just a note to say that playing with `qt.force_software_rendering` has helped me with similar `xf86-video-intel ` related issues observed in the past...

```console
$ pacman -Q xf86-video-intel
xf86-video-intel 1:2.99.917+899+gf66d3954-1
$ grep force ~/.config/qutebrowser/config.py
c.qt.force_software_rendering = 'software-opengl'
```

**Comment by jcguu95** [comment]
@tiborsimko  your comment is tremendously helpful! It has been my nightmare (for just one day ha) and now qb is working as in the past. Would you mind sharing a bit how you came up with that solution? I'm not a pro but would try to be more independent. Thank you.

**Comment by The-Compiler** [comment]
Note that `qt.force_software_rendering` will probably give you less performance, so it might or might not be a suitable permanent solution.

**Comment by jcguu95** [comment]
I see :( I'm not capable of coming of with a better solution at this point. Anyway, it is still faster and better than any other browsers.

**Comment by FAETHER** [comment]
Well I did not expect opengl software rendering to be this slow. Just typing letters in this box has like 5 seconds delay to update. Feels like less then 1 fps deal here. I am not satisfied with this solution, so if the problem is really with the driver I will revert back to an older version and see if that helps.

**Comment by FAETHER** [comment]
Start by uninstalling xf86-video-intel. And I'll report laster if that solves anything.

**Comment by FAETHER** [comment]
Okay so driver uninstall did not solve anything.

**Comment by eike-fokken** [comment]
Did someone file a bug with qt? I can't find one but would like to make sure before I file a new one.

**Comment by The-Compiler** [comment]
@eike-fokken At least for the freeze I'm aware of, that's definitely a bug in the Intel driver and also affects other applications (although rarely) - see e.g. https://gitlab.freedesktop.org/drm/intel/issues/673. Nothing Qt can do here I'm guessing.

You might want to try uninstalling Debian's equivalent of `xf86-video-intel` if you haven't yet, and also upgrade to a kernel > 5.5 if possible.

**Comment by eike-fokken** [comment]
Oh thanks, then I'll just wait for the new kernel to trickle down to
debian testing.

Uninstalling xf86-video-intel on debian unfortunately doesn't fall back
to some generic driver but instead breaks X. As the freeze usually only
happens once a day for me I was not bothered enough to find out how to
change the driver correctly.
