### ISSUE TITLE
This browser or app may not be secure when trying to login to GMail

### ISSUE THREAD

**Issue by cdosborn** [qutebrowser/qutebrowser#5181]
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/fd47e978

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

![image](https://user-images.githubusercontent.com/3847314/71914731-3a13bd80-3148-11ea-9471-506a80a93689.png)

**How to reproduce**
Try to login to gmail. I tested with 2FA enabled/disabled w/o luck.

**Comment by The-Compiler** [comment]
Duplicate of #5144

**Comment by The-Compiler** [comment]
I just wrote a more detailed explanation for what's going on: #5182
