### ISSUE TITLE
Google Sign-In issues (fix and workaround available!)

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5182]
Given that information about this is a bit scattered at the moment, I'm opening (and pinning) this issue in the hope that it's easier to find that way. Here's what's going on:

# Explanation

- Mid 2019, Google started blocking various smaller browsers from logging in to a Google account. This initially only affected few people, but seems to be rolled out to many Google accounts now (but not all of them, my own accounts are still unaffected...)
- Google claims that you're using *"a browser [...] that doesn't allow us to keep your account secure"*. There's not much further rationale available for that claim - all I'm aware of is a blogpost titled ["Better protection against Man in the Middle phishing attacks"](https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html) where this originally was announced and a [Google Help Center entry](https://support.google.com/accounts/answer/7675428?hl=en) which also mentions that this change is targetting automation testing frameworks and browsers embedded in a different application. The change seems to affect much more than that - also see a [Bleepingcomputer article](https://www.bleepingcomputer.com/news/google/google-now-bans-some-linux-web-browsers-from-their-services/) and related Reddit discussions ([/r/kde](https://www.reddit.com/r/kde/comments/e7136e/google_bans_falkon_and_konqueror_browsers/), [/r/privacy](https://www.reddit.com/r/privacy/comments/eaaceg/google_now_bans_some_linux_web_browsers_from/) and others).
- It looks like Google tries to block the QtWebEngine library which could indeed be used to build applications using a Google account by letting the user sign in and then "stealing" the cookie instead of e.g. using OAuth to log in and some API. It looks like blocking various browsers (including qutebrowser) just is collateral damage.

# Fix and workaround

- Fortunately, it was discovered that setting the user agent to Firefox bypasses whatever weird check Google is doing.
- With qutebrowser v1.9.0 (2019-01-08), a `content.site_specific_quirks` option was added (see #4810 and #5157 for details). With it enabled (which is the default), qutebrowser sends a Firefox user agent for the Google Accounts page (and other problematic pages like WhatsApp), thus fixing the issue.
- As a workaround, you can get the equivalent of that fix by running `:set -u https://accounts.google.com/* content.headers.user_agent 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'` (needs v1.2.0 or newer)

# 2021 Update

According to some people, this might be coming back - but not all Google Accounts seem to be affected, or at least not to the same degree. If you're seeing this with your account, please answer here!

**Comment by The-Compiler** [comment]
Also, let me add my personal opinion on this, from an earlier [mailinglist mail](https://lists.schokokeks.org/pipermail/qutebrowser/2019-December/000676.html):

> I wouldn't be surprised if Google just blocks pretty much everything other than Chrome and maybe Firefox. It's ridiculous, but it's yet another sign showing that maybe it isn't a good thing to make yourself dependent on Google - you're absolutely at their mercy, and they don't exactly have a good track record.
> 
> I've once tried helping someone who only got an internal server error when trying to open an important attachment of an older mail in GMail. We contacted Google Support, and as you'd predict, nothing happened.
> 
> Given that Google really doesn't care about its users, your only option is ~~either switching browsers~~, or moving away from Google. I did the latter years ago[*]. Seeing what's going on here, this absolutely was the right decision, but I'm aware this isn't something everyone can realistically do...
> 
> [*] At least for stuff like Calendar and Mail. I still use Youtube (mostly via mpv/youtube-dl), Google Play and sometimes Maps (mostly switched to Openstreetmap/OSMand).

**Comment by JonnyHaystack** [comment]
Sorry for being possibly a bit off-topic, but out of interest what replacements do you use for GMail and Google Calendar?

**Comment by The-Compiler** [comment]
- GMail: [uberspace](https://uberspace.de/en/) - other providers I've seen people use are (in no particular order) [Posteo](https://posteo.de/en), [Protonmail](https://protonmail.com/) and [Tutanota](https://tutanota.com/).
- Google Calendar: I host a [Nextcloud](https://nextcloud.com/) instance on uberspace ([guide](https://lab.uberspace.de/guide_nextcloud.html)) and use [DAVx⁵](https://www.davx5.com/) to sync it with Android.

**Comment by JonnyHaystack** [comment]
Thanks! I'll check out all of those

**Comment by The-Compiler** [comment]
For anyone watching this issue: I just released qutebrowser v1.9.0 with the fix.

**Comment by jb55** [comment]
> Sorry for being possibly a bit off-topic, but out of interest what replacements do you use for GMail and Google Calendar?

I run [radicale](https://radicale.org/) and sync with DAVx⁵ as well. radicale works great! I haven't had any issues with it.

**Comment by The-Compiler** [comment]
I don't want to turn this into a conversation about Google, but either way: I just read [Why I quit using Google – Kyle Piira](https://www.kylepiira.com/2020/01/09/why-i-quit-google/) which is a nice (even if horrifying) post which lists some more alternatives.

**Comment by ashwinmahantha** [comment]
I am a new user of Qutebrowser. I installed Qute on Ubuntu 18.04 using apt-get. 
Version: qutebrowser v1.1.1
1. By when can I get a fix to this issue via apt?
2. :set -u https://accounts.google.com/*... Where do I enter this command? Entering it after hitting ':' in Qutebrowser gives error: Unrecognized arguments -u Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by The-Compiler** [comment]
@ashwinmahantha 

1. Once Ubuntu 20.04 is out in April and you do a system upgrade to that.
2. Support for per-domain settings (which this uses) was added in qutebrowser v1.2.0, so this won't work on v1.1.1 (which is from January 2020).

**Comment by facebookegypt** [comment]
I have the same problem when I try to test the console project using webbrower control from Visual Studio [Not the default windows browser]

**Comment by The-Compiler** [comment]
FWIW looks like [there's a chance](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html) this will break again when Google changes their behavior on January 4th. Right now our workaround still works even with the mentioned header, but with Google, you never know what'll change.

Their "browser guidlines" are hypocritical to say the least:

> The browser must not provide automation features. This includes scripts that automate keystrokes or clicks

*cough* [ChromeDriver](https://chromedriver.chromium.org/) *cough*

**Comment by chaorace** [comment]
I encountered this issue today on the google accounts sign-in, despite having `content.site_specific_quirks` set to true. Strangely, the headers fix still worked when I tried that instead. I'm on a recent git commit, so maybe it's a regression affecting the site specific quirks feature?

```
qutebrowser v1.14.1
Git commit: 21b20116f on master (2021-01-19 19:14:55 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
```

**Comment by The-Compiler** [comment]
@chaorace Oh no... :worried: 

Can you reproduce this with `qutebrowser --temp-basedir accounts.google.com` as well?

I have two Google accounts (`@gmail.com` and `@the-compiler.org` via Google Workspace), and currently see this:

- GMail, quirks enabled: I get a captcha, but can then log in normally
- GMail, quirks disabled: "This browser or app may not be secure" after entering username
- Workspace, quirks enabled: Captcha
- Workspace, quirks disabled: Captcha (!)

Can you elaborate what you mean exactly with "the headers fix still worked when I tried that instead" exactly?

**Comment by chaorace** [comment]
Regarding the "headers fix", I'm referring to this snippet you included in the issue description:
`:set -u https://accounts.google.com/* content.headers.user_agent 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'`

I experienced the issue on a fresh system install (as in a brand new disk, not just qutebrowser). I can't seem to replicate it on my primary disk, now that I'm attempting to do that. That _could_ be related, more likely a red herring imo.

In any case, I'll be hopping back onto my fresh install later today and will see if I can get the issue to reproduce once more from there.

**Comment by The-Compiler** [comment]
On the system where it breaks with the default setup, can you try if this is broken as well:

```
:set -u https://accounts.google.com/* content.headers.user_agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 Edg/80.0.3987.163"
```

If it is, but the Firefox UA you used above helps, that'd be an easy fix. If that's the case, can you try with an updated Firefox UA too please?

```
:set -u https://accounts.google.com/* content.headers.user_agent "Mozilla/5.0 ({os_info}; rv:84.0) Gecko/20100101 Firefox/84.0"
```

(leave the `{os_info}` in there, qutebrowser should replace it with the correct content)

My expectation is that the Edge UA won't help (because that's what the site-specific quirk is doing), but the new Firefox one would still help.

**Comment by The-Compiler** [comment]
@chaorace Any update on this? If the workaround needs adjustments, I'd really like to do them before the next release (which might happen soon-ish).

**Comment by chaorace** [comment]
Sorry for the delayed response. I just can't seem to reproduce the issue anymore. I even tried navigating back to the exact same URL in my history and that worked just fine. (this is all whilst using temp-basedir, of course).

I can only guess it's some crazy Google heuristic or (more likely) some kind of flub on my end. All's well that ends well, I suppose?

**Comment by The-Compiler** [comment]
That's just how things are with Google... I remember back when this started (late 2019/early 2020) it was quite flaky for a while as well. Let's hope it keeps working now! If that's not the case, please let me know though.

**Comment by amirography** [comment]
I have just experienced this with google. Any info that I can give to you that helps?

**Comment by budRich** [comment]
I just wanted to say this happened to me right now as well. I first tried disabling the site quirk-setting, but got to the same page. Found this issue thread, and tried the Firefox useragent (last one posted by The-Compiler):  
`:set -u https://accounts.google.com/* content.headers.user_agent "Mozilla/5.0 ({os_info}; rv:84.0) Gecko/20100101 Firefox/84.0"`  

It worked.

However, I also have 2fA enabled on my google account, and usually when i log in from a new browser, i get sent the activation in a couple of seconds. Now after waiting over a minute i needed to tell them to send a new activation code (which went through immediatly). And now i am "in", so all good.

---

I haven't scrolled through the whole thread. But my guess why this seems to happen "randomly" are that google tests all chromium based browsers to see it is using the latest version of chromium. I believe google has means of verifying ones identity "under the hood" (in the cookie jar), and those who don't get the same issue as i had to today, Google might have verifiied their identity already, this browser check stuff is probably the last step in the chain. But then again, i am just guessing, since we will never know.

---

Now that i think about it, this actually happened to me a couple of months back with the Vivaldi browser. Who in a new update back then added options to turn off built in (and hidden) extensions in chromium/(vivaldi), like the PDFviewer, chromecast and Hangouts. I remember one of those "extensions" had the same effect as this issue, not being able to sign in to google. The extension is called "CryptoToken".

**Comment by martonbalazs** [comment]
Thanks, I had the issue and the workaround worked. Very worrying though. E.g., not sure if related, my comments on Youtube are disappearing while they stay if I make them under Firefox.

**Comment by RainbowAsteroids** [comment]
I was having the same issue, but using the command you recommended worked.

**Comment by michaelskyba** [comment]
Might be redundant at this point to mention, but I can also reproduce this.

With ``--temp-base-dir``, it fails, but using ``:set -u https://accounts.google.com/* content.headers.user_agent 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0'`` fixes it.

**Comment by saemideluxe** [comment]
I had the same problem just starting today. Using ```:set -u https://accounts.google.com/* content.headers.user_agent "Mozilla/5.0 ({os_info}; rv:84.0) Gecko/20100101 Firefox/84.0"``` solved the problem (even in the same session).

**Comment by The-Compiler** [comment]
I could reproduce with one of my Google accounts (though not another...). I updated the workaround to use an updated Firefox UA and released v2.3.1 with it.

**Comment by a-m-joseph** [comment]
Hey, I'm glad to see you fighting the good fight here, but this will break, and soon.  It only works for Firefox 90 because it's so new.  Google gathers fingerprint data from each release of (what they consider to be) a major browser and clusters the results.  Once they have enough results to partition the real Firefox 90 from qutebrowser, this will break.  That will happen very very soon.

Google published a paper explaining exactly how they do this:

https://research.google/pubs/pub45581.pdf

Unfortunately what you're doing here is only going to work for a few weeks after each release of Edge or Firefox.

Sorry to bear bad news.  It's pretty evil what Google is doing here.

**Comment by The-Compiler** [comment]
@a-m-joseph Evidence seems to suggest otherwise, given that:

- Specifying an older Firefox version works just as well
- We've been using this workaround successfully (originally with Firefox rather than Edge) since January 2020

**Comment by mentalisttraceur** [comment]
Seems like @a-m-joseph might've been onto something? I'm seeing this breaking again on a version of qutebrowser where it worked relatively recently.

**Comment by The-Compiler** [comment]
@mentalisttraceur See the August 2021 update above. v2.0.2 is from February.

**Comment by mentalisttraceur** [comment]
Thanks. I was assuming my Linux distro had a reasonably recent version. Guess not.

**Comment by francisco-simoes** [comment]
My version is v2.0.2 as well, so I ran `:set -u https://accounts.google.com/* content.headers.user_agent "Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0"` as suggested in the update. But that had no effect...

**Comment by The-Compiler** [comment]
@francisco-simoes Just tested on v2.0.2 and the workaround works fine here. How are you logging in precisely?

**Comment by francisco-simoes** [comment]
I tried logging in on Youtube and in https://account.google.com/. Both failed.

**Comment by The-Compiler** [comment]
That's odd. If you don't mind, can you try with my Google Account, `florianbruh`? At least here, I get an error immediately after entering the account name, so I suppose you could (try to) reproduce too.

**Comment by francisco-simoes** [comment]
Just tried with florianbruh@gmail.com. Same exact error as before.

**Comment by The-Compiler** [comment]
Weird. Can you do `:config-diff` and confirm you see this exact line?

```
https://accounts.google.com/*: content.headers.user_agent = Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0
```

If that's the case, could you reproduce with `--temp-basedir` (ideally with my account) and do `:report` so I can take a look to see if I notice anything in the debug logs?

**Comment by francisco-simoes** [comment]
I do not, and in fact there is no line starting with `https://accounts.google.com....`. Although I did run the `:set ...` command.

**Comment by The-Compiler** [comment]
Well, then it has not been set correctly. I don't recall this happening before. This is with `--temp-basedir`? How exactly do you run the set command, manually? Do you get any error from it?

**Comment by francisco-simoes** [comment]
I tried a couple more times and now it worked. I suspect I had mistyped/miscopied something. Sorry for troubling you with something possibly trivial. Thanks for the awesome work, cheers!

**Comment by toprak** [comment]
I do not know if it helps only [saemideluxe](https://github.com/saemideluxe)'s solution worked on me not 90 nor other peoples

**Comment by toofar** [comment]
I wonder if we still need the workaround for this? We currently have a quirk which is active by default which sets a user agent of [firefox 90](https://github.com/qutebrowser/qutebrowser/blob/a7a2420/qutebrowser/browser/webengine/webenginesettings.py#L433). I wonder if we should do one of:

1. update that UA to a later firefox one (eg rv:109.0 ... Firefox/118)
2. remove the quirk

If anyone wants to test (2) you should be able to add "ua-google" to the `content.site_specific_quirks.skip` setting. And removing any other domain specific user agent override you have for `https://accounts.google.com/*`.
I tested logging into gmail on my work account and it worked fine, but I don't think I could reproduce the issue in the first place anyhow.

**Comment by TechLionDev** [comment]
Still get the issue even on latest,
```
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

CPython: 3.12.6
PyQt: 6.7.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: no
sqlite: 3.46.1
QtNetwork SSL: OpenSSL 3.3.2 3 Sep 2024

Style: Breeze::Style
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 24.2.3-arch1.1
Platform: Linux-6.10.10-arch1-1-x86_64-with-glibc2.40, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.12/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/jeremiahis/.cache/qutebrowser
config: /home/jeremiahis/.config/qutebrowser
data: /home/jeremiahis/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/jeremiahis/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
```

**Comment by The-Compiler** [comment]
@TechLionDev "The issue" as in you get the "You are trying to sign in from a browser or app that doesn't allow us to keep your account secure." error message from Google? I've not seen that in a while, what I see right now is just not being logged in at all, but that seems like a separate issue. Though, it's probably still just Google being broken.

**Comment by TechLionDev** [comment]
Yes, "you are trying to sign in from a browser or app that doesn't allow us to keep your account secure"

**Comment by scresante** [comment]
I have also experienced this problem and the original workaround from Aug 2021, updated with a newer firefox string works. `:set -u https://accounts.google.com/* content.headers.user_agent "Mozilla/5.0 ({os_info}; rv:130.0) Gecko/20100101 Firefox/130"` fixes the problem for me.

**Comment by The-Compiler** [comment]
@scresante Thanks for the hint, that's very helpful as things still work fine for my account! I updated the initial post and included an updated workaround in qutebrowser v3.3.1 which was released today.

**Comment by Ezall2001** [comment]
`The v3.3.0 release contains an updated workaround and should work out of the box`
I am on qutebrowser v3.6.3. I still need to set the user agent to work

**Comment by aaronliu0130** [comment]
I'm also on 3.6.3, and for some reason not even either user agent work for me.

**Comment by Dvbnhbq** [comment]
I have the same issue.
qutebrowser v3.7.0
Git commit: b0a7967f1 on master (2026-04-03 14:13:15 +0000)
Backend: QtWebEngine 6.5.2
  based on Chromium 108.0.5359.220
  with security patches up to 114.0.5735.133 (plus any distribution patches)
  (source: api)
Qt: 6.5.2

CPython: 3.10.12
PyQt: 6.5.2

**Update:** this worked `:set -u https://accounts.google.com/* content.headers.user_agent "Mozilla/5.0 ({os_info}; rv:135.0) Gecko/20100101 Firefox/135"`
🙂
