### ISSUE TITLE
Noisy browsing

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#5189]
I found something interesting some time ago, wondering if it would make a good feature request: a tab that randomly browses the web to make it harder for social media and advertisers to profile you. There seems to already be a plugin, but looks like it is not compatible:

https://noiszy.com

**Comment by The-Compiler** [comment]
I think this is something too specific to have in the core. I added it to the plugin ideas in #30 though.

**Comment by mike402** [comment]
Agreed, no problem.

**Comment by ninewise** [comment]
This could be implemented with an external/user script, too, I guess. Just have a separate window (same qb instance) in the background (if your window manager supports this), in which you keep opening random urls.
