### ISSUE TITLE
Domain specific cookie blocking

### ISSUE THREAD

**Issue by skuzzymiglet** [qutebrowser/qutebrowser#5190]
I've tried to block cookies like this:

```
with config.pattern("*://medium.com/*") as p:
    p.content.cookies.store = False
```

But it doesn't work. It would be nice if cookies could be blocked according to a url pattern like this

**Comment by ninewise** [comment]
It's not implemented, yet. See #4395 for a related PR, #4174 for a related issue and #3636 for an overview of URL-patterned settings.
