### ISSUE TITLE
can't set content.javascript.enabled for site with FQDN

### ISSUE THREAD

**Issue by hmht** [qutebrowser/qutebrowser#5192]
**Version info**:
- 1.9.0 is affected
- 1.8.2 is not affected

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**How to reproduce**
1. visit https://travis-ci.com/
2. observe that the `<noscript>` block is show depending on the value of content.javascript.enabled, which can be toggled for this site by typing `tsh`
3. visit https://travis-ci.com./
4. observe that typing `tsh` has no effect
5. notice that the setting for https://travis-ci.com./ is applied to https://travis-ci.com/ instead.

**Comment by hmht** [comment]
duplicate

**Comment by The-Compiler** [comment]
for future reference: duplicate of #5191, that is :wink:
