### ISSUE TITLE
problem with hinting links on new google search links.

### ISSUE THREAD

**Issue by yashar-sb-sb** [qutebrowser/qutebrowser#5194]
recently google made some changes to it's search results page and since then, hinting does not work on it's search results page.

**Comment by The-Compiler** [comment]
Works fine for me. Can you reproduce this with `--temp-basedir`? If so, can you do `:report` so I can take a look at the logs?

**Comment by The-Compiler** [comment]
Also, can you please show your version information? There's a reason the issue template asks for those things...

**Comment by yashar-sb-sb** [comment]
Sorry,
It has been resolved on the 1.9.0 version.
