### ISSUE TITLE
Default font size variable

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#5198]
I think it would be useful to have a `default_size` variable for fonts, much like `default_family` (previously `monospace`).

Use case: pretty much all of the various fonts are configured by default to be `10pt default_family` (`10pt monospace`), but my preferred font looks better in 12pt (OK, maybe it's my eyes...), which means my config file has to include the whole gamut of fonts:

```python
c.fonts.default_family = "Misc Tamsyn"
c.fonts.completion.category = "bold 12pt default_family"
c.fonts.completion.entry = "12pt default_family"
c.fonts.debug_console = "12pt default_family"
c.fonts.downloads = "12pt default_family"
c.fonts.hints = "bold 12pt default_family"
c.fonts.keyhint = "12pt default_family"
c.fonts.messages.error = "12pt default_family"
c.fonts.messages.info = "12pt default_family"
c.fonts.messages.warning = "12pt default_family"
c.fonts.prompts = "12pt default_family"
c.fonts.statusbar = "12pt default_family"
c.fonts.tabs = "12pt default_family"
```

It'd be easier to just have:

```python
c.fonts.default_family = "Misc Tamsyn"
c.fonts.default_size = "12pt"
```

Not only is this shorter, but I don't have to worry about if/when a qutebrowser font gets added, gets deleted, or gets renamed, since it no longer has to appear in my config.

**Comment by The-Compiler** [comment]
Sounds like a good idea!

**Comment by The-Compiler** [comment]
This is one of the things I've needed multiple times myself (e.g. when giving workshops), yet somehow never thought of it. Definitely fits in well with the `default_family` setting coming in v1.10.0 as well, so I added it!

**Comment by brianbuccola** [comment]
Glad I could help, even if you did all the work. :grin:

**Comment by brianbuccola** [comment]
Glad I could help, even if you did all the work. :grimacing: Thanks!
