### ISSUE TITLE
qutebrowser 1.9.0 QtWebEngine 5.13.2 Renderer process crashed

### ISSUE THREAD

**Issue by novel** [qutebrowser/qutebrowser#5200]
**Version info (see `:version`)**:

```
qutebrowser v1.9.0
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

CPython: 3.7.6
PyQt: 5.13.1

sip: 4.19.19
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.1
yaml: 5.2
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d-freebsd  10 Sep 2019

Style: QFusionStyle
Platform: FreeBSD-13.0-CURRENT-amd64-64bit-ELF, 64bit
Frozen: False
Imported from /usr/local/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/local/bin/python3.7
Qt library executable path: /usr/local/libexec/qt5, data path: /usr/local/share/qt5
OS Version: FreeBSD kloomba 13.0-CURRENT FreeBSD 13.0-CURRENT #91 r356657: Sun Jan 12 15:10:38 +04 2020     root@romashka:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64 amd64

Paths:
cache: /home/novel/.cache/qutebrowser
config: /home/novel/.config/qutebrowser
data: /home/novel/.local/share/qutebrowser
runtime: /tmp/runtime-novel/qutebrowser

Autoconfig loaded: no
Config.py: /home/novel/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Opening duckduckgo front page crashes renderer process:

```19:13:42 ERROR: Renderer process crashed```

Backtrace is here, though it's not extremely helpful because there's no debugging present: 
https://people.freebsd.org/~novel/misc/qutebrowser190_qtwebengine5132_backtrace.txt

**How to reproduce**

Open duckduckgo.com.

Creating that mainly to get help on additional steps forward. Actually, I'm not sure it's qutebrowser bug, probably the issue is with qtwebengine. I can also reproduce the issue with qutebrowser 1.8.3.

I'll try to rebuild qtwebengine with debug symbols, but meanwhile I appreciate any ideas.

**Comment by novel** [comment]
Yes, `falkon` crashes in a similar way.

**Comment by The-Compiler** [comment]
Yep, looks like a QtWebEngine/FreeBSD issue then - closing this as there's nothing qutebrowser can do here.
