### ISSUE TITLE
Whatsapp Web User-Agent

### ISSUE THREAD

**Issue by GhostValk** [qutebrowser/qutebrowser#5210]
Hi!

For some reason (probably some whatsapp update), i'm no longer able to use the desktop version of whatsapp (whatsapp web). I remember when i started using qb i had to try quite some user agents to get it working and i was wondering if you guys know one that works now.

**Comment by The-Compiler** [comment]
What Qt version, backend and qutebrowser version (see `:version`)? Does it work with `--temp-basedir`?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by GhostValk** [comment]
No template did pop up when i created the new message.

Qt: 5.14.0
PyQt: 5.14.1

**Comment by The-Compiler** [comment]
> No template did pop up when i created the new message.

I guess you clicked "feature request" rather than "bug report" or "support" then.

> Qt: 5.14.0 / PyQt: 5.14.1

...what qutebrowser version?

> Yes, with `-temp-basedir` it works

Can you show `:open qute://configdiff` please? (Though it might not be that, some WhatsApp issues only happen when logging in a second time rather than signing up)

**Comment by GhostValk** [comment]
I clicked "New Issue". Qb versión is 1.9, but it was still in 1.8, i just upgraded it to see if it was fixed, but no.

Output from that command is:

`auto_save.session = true
bindings.commands = {"normal": {"1": "tab-focus 1", "2": "tab-focus 2", "3": "tab-focus 3", "4": "tab-focus 4", "5": "tab-focus 5", "6": "tab-focus 6", "7": "tab-focus 7", "8": "tab-focus 8", "9": "tab-focus -1", "<Alt+m>": "tab-move -", "<Alt+n>": "tab-move +", "<Left>": "back", "<Right>": "forward", "f": "hint all tab", "g": "set-cmd-text -s :open ", "h": "back", "j": "tab-prev", "k": "tab-next", "l": "forward", "mpv": "spawn --userscript /Users/Ghost/Desktop/Call.sh {clipboard}", "t": "set-cmd-text -s :open -t"}}
colors.tabs.bar.bg = black
colors.tabs.even.bg = black
colors.tabs.even.fg = #33ff33
colors.tabs.odd.bg = black
colors.tabs.odd.fg = #33ff33
completion.open_categories = ["history"]
completion.shrink = true
completion.web_history.max_items = 10
content.cookies.accept = all
content.cookies.store = true
content.headers.user_agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
*://www.instagram.com/*: content.headers.user_agent = Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1
content.pdfjs = true
content.plugins = true
content.proxy = system
fonts.hints = bold 20pt monospace
fonts.monospace = "Roboto Mono for Powerline"
fonts.statusbar = 12pt monospace
fonts.tabs = 12pt monospace
input.insert_mode.auto_enter = false
input.insert_mode.auto_leave = true
input.insert_mode.auto_load = false
input.insert_mode.leave_on_load = true
input.insert_mode.plugins = false
new_instance_open_target = tab
statusbar.hide = false
statusbar.position = bottom
statusbar.widgets = ["tabs", "keypress", "url", "scroll", "history", "progress"]
tabs.max_width = 100
tabs.min_width = 70
tabs.position = left
tabs.width = 10%
zoom.default = 100%`

I think the problem is in the UA, what's the user agent for default --temp-basedir qb instance=

**Comment by The-Compiler** [comment]
You can do `:config-unset content.headers.user_agent` to get the default back; or you can use the `:set` completion to see it.

However, it shouldn't matter much with v1.9.0 as that includes a workaround for exactly this issue - are you sure you are in fact running the new version after the update (and it didn't just open a new window in the old one)?

**Comment by GhostValk** [comment]
Yeah, totally sure, and still, bug was also present in 1.8x, it started like today when reloading whatsapp webpage.

Changing UA doesn't do anything, still not warking.

**Comment by The-Compiler** [comment]
Well, I can reproduce with v1.8.0 and it works fine in v1.9.0 here. Does anything change if you hit Shift-R to force a reload?

**Comment by GhostValk** [comment]
I got it fixed. After changing User Agent back to default i deleted the cache and then opened qb and worked fine. I'm guessing maybe the UA is somehow stored in the cache.

Regarding the same, not sure if you remember, but i asked some time ago about the site-specific ua not working for me, i'm guessing maybe something similar is happening, i think after you open some sites for the first time, the user-agent you are using gets saved in the cache for that website, and regardless of you switching it later, it reads it from the cache (not for all sites thou, fb and google work fine when switchnig it).

**Comment by GhostValk** [comment]
Sadly the problem persists, after reloading the page a couple times in these 2 days, suddenly stopped working and the previous fix is not working anymore. Maybe whatsapp is doing some changes in the web version.

**Comment by GhostValk** [comment]
I did some testing, commented every single setting i modified in `config.py`, deleted the caché and started both normal qb and qb with `--temp-basedir`, so they both were basically the same and the one with `--temp-basedir` works while the normal qb doesn't. I checked `:version`, user agent and it's exactly the same in both.

<img width="1440" alt="Screen Shot 2020-01-31 at 12 18 50" src="https://user-images.githubusercontent.com/7433150/73550897-3233fa00-4424-11ea-8031-49cea43b8737.png">


What differences are between normal qb and ob with the flag `--temp-basedir` other than the config file?

**Comment by The-Compiler** [comment]
I was able to reproduce now. Forcing a reload with Shift-R fixes it, but I now also pushed a site-specific quirk which does essentially that.

>  but i asked some time ago about the site-specific ua not working for me, i'm guessing maybe something similar is happening

The Instagram thing is unrelated - like I described there, the UA a website gets via JavaScript always is the global one.

> i think after you open some sites for the first time, the user-agent you are using gets saved in the cache for that website, and regardless of you switching it later, it reads it from the cache 

Something like that seems to be happening for WhatsApp Web.

> What differences are between normal qb and qb with the flag --temp-basedir other than the config file?

You don't have state like cookies. This issue only happens when visiting the WhatsApp Web site when already registered via the QR code, not with the registration itself.

**Comment by GhostValk** [comment]
Well, after a couple reopenings and cache deletings i managed to get it working again. I'm gonna dig into some way of deleting whatsapp cookies from the browser to made somi kind of autofix.

Thanks a lot!

**Comment by The-Compiler** [comment]
FWIW as a workaround, you can put this in a `greasemonkey/whatsapp.user.js` file inside qutebrowser's data directory (see `:version`):

```js
// ==UserScript==
// @include https://web.whatsapp.com/
// ==/UserScript==
if (document.body.innerText.replace(/\n/g, ' ').search(/whatsapp works with.*to use whatsapp.*update/i) !== -1)
	navigator.serviceWorker.getRegistration().then(function (r) { r.unregister(); document.location.reload() });
```

**Comment by GhostValk** [comment]
Ohhh, didn't know you could run greasemonkey scripts in qb, great! Thanks a lot!

**Comment by 3ruce** [comment]
OK, so on Debian Buster, adding the `greasemonkey/whatsapp.user.js` file and the user agent below did the trick...

```Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36```

`qutebrowser --version` shows

```
qutebrowser v1.6.1
Git commit:
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.3
Qt: 5.11.3
PyQt: 5.11.3
```
