### ISSUE TITLE
QT_SCALE_FACTOR causes huge window contents offset on Wayland

### ISSUE THREAD

**Issue by a-m-joseph** [qutebrowser/qutebrowser#5211]
**Version info (see `:version`)**: See below (after screenshot), pastebin-yank failed

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

With QT_SCALE_FACTOR set on Wayland the window contents are offset from the origin by a large amount which appears to be proportional to the QT_SCALE_FACTOR.  See screenshot.

This is a bit of a problem because the only other way to get the font sizes to be readable is by setting the default zoom, but that results in the page rendering with the wrong DPI (at 100% zoom) until it is completely loaded, and then a very jarring reflow to the default DPI.  It's very hard to use like that. 

Tested on both Linux-amd64-radeon and Linux-arm64-libmali, both under sway.

**How to reproduce**
Start sway, then invoke
`export QT_SCALE_FACTOR=2.5; qutebrowser --temp-basedir`

![screenshot-20200128-160303](https://user-images.githubusercontent.com/54836058/73316722-b601a280-41e8-11ea-8d7f-8a3c12111047.png)

**version**
qutebrowser v1.6.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.3
Qt: 5.12.5
PyQt: 5.12.3

sip: 4.19.19
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.3.5+-x86_64-with-debian-10.1, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /tmp/sway-user/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:39

**Comment by a-m-joseph** [comment]
Also verified with:

```
qutebrowser v1.9.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.5

CPython: 3.7.3
PyQt: 5.12.3

sip: 4.19.19
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.3.5+-x86_64-with-debian-10.1, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /tmp/sway-user/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:11
```

**Comment by The-Compiler** [comment]
Qt 5.12 doesn't support fractional scale amounts. Can you try with Qt 5.14? Also, do you see the same with KDE Falkon?

**Comment by a-m-joseph** [comment]
> Qt 5.12 doesn't support fractional scale amounts.

The issue occurs with QT_SCALE_FACTOR=2 as well

> Can you try with Qt 5.14?

I've been trying to do that, unsuccessfully.  Debian experimental released qtbase-5.14 yesterday, but their qtwebengine/pyqt packages are still at 5.12.  So I've built Qt 5.14 from source, but I still need to get pyqt and the rest of qt (i.e. beyond qtbase) built.  Ye gads there is a massive amount of code here...

> Also, do you see the same with KDE Falkon?

Sadly KDE has a hard dependency on systemd+dbus, which conflict with our infrastructure here.  I'd need to bring up a completely new machine.  Is there some non-KDE browser I can try instead?

**Comment by The-Compiler** [comment]
I don't think KDE Falkon requires anything from KDE.

**Comment by a-m-joseph** [comment]
Well after much suffering I managed to build Qt 5.14.1 from source (holy cow there is a lot of stuff in there).  **The bug does not manifest when built this way.**

So, I'm closing this issue.

Debian experimental is still at Qt 5.12, so if anybody using Debian stumbles across this, here's the quickest way to get things working: qmake breaks checkinstall, so you have to build a package by hand.  Use the instructions [here](https://askubuntu.com/questions/1014619/a-working-version-of-checkinstall) with qt-everywhere-src-5.14.1.tar.xz.  I've attached updated debian/rules and debian/control files below (both are very low-quality, but they work).

> I don't think KDE Falkon requires anything from KDE.

Perhaps not.  However Debian thinks it does: package "faklon" [depends](https://packages.debian.org/sid/falkon) on all the KDE (libkf5) packages, which depend on systemd+dbus.  Perhaps this is an unnecessary dependency in Debian.  In any case: thank you so much for making a browser that can work without all that stuff!

debian/control
```
Source: qt-everywhere-src
Section: unknown
Priority: optional
Maintainer: unknown <user@unknown>
Build-Depends: debhelper-compat (= 12), autotools-dev
Standards-Version: 4.4.1
Homepage: <insert the upstream URL, if relevant>

Package: qt5
Architecture: amd64
Provides: libqt5core5a (=5.12.4), libqt5dbus5 (=5.12.4), libqt5designer5 (=5.12.4), libqt5gui5 (=5.12.4), libqt5help5 (=5.12.4), libqt5network5 (=5.12.4), libqt5opengl5 (=5.12.4), libqt5positioning5 (=5.12.4), libqt5printsupport5 (=5.12.4), libqt5qml5 (=5.12.4), libqt5quick5 (=5.12.4), libqt5quickwidgets5 (=5.12.4), libqt5sql5 (=5.12.4), libqt5sql5-sqlite (=5.12.4), libqt5test5 (=5.12.4), libqt5waylandclient5 (=5.12.4), libqt5waylandcompositor5 (=5.12.4), libqt5webchannel5 (=5.12.4), libqt5webengine-data (=5.12.4), libqt5webengine5 (=5.12.4), libqt5webenginecore5 (=5.12.4), libqt5webenginewidgets5 (=5.12.4), libqt5widgets5 (=5.12.4), libqt5xml5 (=5.12.4)
Description: <insert up to 60 chars description>
 <insert long description, indented with spaces>
```

debian/rules
```
#!/usr/bin/make -f
export DH_VERBOSE = 1

%:
	dh $@

override_dh_auto_make:
override_dh_auto_test:
override_dh_dwz:

override_dh_auto_build:
	export QT5PREFIX=/usr/
	export DEB_HOST_MULTIARCH=x86_64-linux-gnu
	make -j16

override_dh_auto_configure:
	sed -i 's/python /python3 /' qtdeclarative/qtdeclarative.pro \
	                             qtdeclarative/src/3rdparty/masm/masm.pri
	export QT5PREFIX=/usr/
	export DEB_HOST_MULTIARCH=x86_64-linux-gnu
	./configure -prefix $QT5PREFIX                        \
	            -sysconfdir /etc/xdg                      \
	            -confirm-license                          \
	            -opensource                               \
	            -system-harfbuzz                          \
	            -system-sqlite                            \
	            -nomake examples                          \
	            -no-rpath \
	            -opengl desktop \
	            -prefix "/usr" \
	            -bindir "/usr/lib/qt5/bin" \
	            -libdir "/usr/lib/${DEB_HOST_MULTIARCH}" \
	            -docdir "/usr/share/qt5/doc" \
	            -headerdir "/usr/include/${DEB_HOST_MULTIARCH}/qt5" \
	            -datadir "/usr/share/qt5" \
	            -archdatadir "/usr/lib/${DEB_HOST_MULTIARCH}/qt5" \
	            -plugindir "/usr/lib/${DEB_HOST_MULTIARCH}/qt5/plugins" \
	            -importdir "/usr/lib/${DEB_HOST_MULTIARCH}/qt5/imports" \
	            -translationdir "/usr/share/qt5/translations" \
	            -hostdatadir "/usr/lib/${DEB_HOST_MULTIARCH}/qt5" \
	            -sysconfdir "/etc/xdg" \
	            -examplesdir "/usr/lib/${DEB_HOST_MULTIARCH}/qt5/examples" \
	            -plugin-sql-mysql \
	            -plugin-sql-odbc \
	            -plugin-sql-psql \
	            -plugin-sql-sqlite \
	            -no-sql-sqlite2 \
	            -plugin-sql-tds \
	            -system-sqlite \
	            -system-zlib \
	            -system-libpng \
	            -system-libjpeg \
	            -system-doubleconversion \
	            -system-pcre \
	            -openssl \
	            -verbose \
	            -optimized-qmake \
	            -qpa xcb \
	            -xcb \
	            -glib \
	            -icu \
	            -accessibility \
	            -compile-examples \
	            -no-directfb \
	            -no-use-gold-linker

override_dh_auto_install:
	dh_auto_install -Smakefile -- -j16 INSTALL_ROOT=$(CURDIR)/debian/qt5/
```

**Comment by a-m-joseph** [comment]
Another note, ``QT_SCREEN_SCALE_FACTORS`` (note the trailing "S" -- "FACTORS", not "FACTOR", even if you only have one) is completely different from ``QT_SCALE_FACTOR``.

``QT_SCALE_FACTOR`` is a transform applied in the final backbuffer-to-scanout blit.  Font edges get fuzzy when you use this for magnification.

``QT_SCREEN_SCALE_FACTORS`` is an inverse transform stacked on the logical-pixel-to-millimeters transform for purposes of calculating sizes (such as font sizes).  Using this to scale fonts will not produce fuzzy edges.

Most users just want a simple "override the DPI value my monitor provided, because it's wrong" environment variable.  Unlike GTK, QT doesn't have anything whose name suggests it might do this.

I think QT have bungled their HiDPI usability situation pretty badly here.  It's a mess.
