### ISSUE TITLE
tr and wr to open current page in a new tab/window

### ISSUE THREAD

**Issue by treeshateorcs** [qutebrowser/qutebrowser#5213]
subj

**Comment by user202729** [comment]
What's the issue? You can bind it yourself use `tab-clone` command.

**Comment by The-Compiler** [comment]
Also there's already `gD` (as in "detach") and `gC` (as in "clone").

**Comment by treeshateorcs** [comment]
ah, okay

nobody told me that those existed when i asked on irc
