### ISSUE TITLE
fonts.default_size doesn't work with fonts.hints

### ISSUE THREAD

**Issue by bitraid** [qutebrowser/qutebrowser#5214]
**Version info (see `:version`)**:
```
qutebrowser v1.9.0
Git commit: 03b06616f (2020-01-28 13:47:21 +0100)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1 (compiled 5.14.0)
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
`fonts.default_size` doesn't apply to the default value of `fonts.hints`: `bold default_size default_family`
It does work though, if the value starts with `default_size` (removing `bold` or any other attribute) - something that doesn't happen with other font settings. 

**How to reproduce**
Having fonts to their default values, changing the `fonts.default_size` value, has no effect on `fonts.hints` size, unless the bold attribute is removed:
`set fonts.default_size 20pt`
`set fonts.hints 'default_size default_family'`

**Comment by The-Compiler** [comment]
Thanks for the report - was good to fix this before v1.10.0 is out!
