### ISSUE TITLE
Weird font height relatively to input field

### ISSUE THREAD

**Issue by ichirou2910** [qutebrowser/qutebrowser#5215]
**Version info (see `:version`)**: v1.9.0

**Does the bug happen if you start with `--temp-basedir`?**: Yes.

**Description**
Font height is kinda weird. It's like, higher than normal, Noticibly when you are in a textbox and you see the cursor is lower than the text displayed there or the text nearly meet the upper border of the box (Image included).
**How to reproduce**
Go to any input text box. So far I haven't met any webpages without this issue.
Edit: The whole webpage text content got "padded up", not just in the textbox
Edit 2: I'm using i3 gaps on Arch Linux. Will upload neofetch if needed.
![image](https://user-images.githubusercontent.com/51302893/73564214-a789e400-4491-11ea-8283-94d38e4c8e6b.png)

**Comment by The-Compiler** [comment]
Can you check if you see the same with KDE Falkon?

**Comment by ichirou2910** [comment]
I'm using i3 gaps. Guess I will take a try. Just that I want to stay with i3

**Comment by ichirou2910** [comment]
So I haven't tried KDE Falkon, but I tried on my laptop (which run Arch + i3 too) and it works fine there. Do you have any idea? Is it somehow related to font?

**Comment by The-Compiler** [comment]
You can use KDE Falkon on i3 just fine. This is the first time I see something like this and I've no idea what's happening, but it's probably not something related to qutebrowser.

**Comment by The-Compiler** [comment]
Any update, @ichirou2910?

**Comment by ichirou2910** [comment]
Oh no I'm really sorry I forgot this. So I just installed Falkon on both my PC and my Laptop for quick testing. Again, laptop displayed just fine while on PC not. So I think this most probably is not qute's problem. Rn I can't think of any other reason. Please tell me if you have any idea.

**Comment by The-Compiler** [comment]
Yeah, looks like an issue related to your Qt/QtWebEngine setup somehow. No idea where to start debugging this though - I'd probably check `qt5ct` (if you use that), and `~/.config/fontconfig/`.
