### ISSUE TITLE
Compiling qtbrower with proprietary codecs in MacOS

### ISSUE THREAD

**Issue by psa-anddev** [qutebrowser/qutebrowser#5216]
Hi, 
I've been using qtbrowser for a while and I love it. However, I'd like to be able to watch other video sources apart from Youtube. Looking at other issues and at the documentation in the project, it is not clear as to what to do to get this working. 

I have tried the same things using both pip and git to check the repository and every time I get the same issues. However, if I run the dmg (installed through brew), it works perfectly. 

I start in my terminal with my default configuration. When I first start qutebrowser using python (it doesn't matter whether I used git or pip) I first get an error saying the cocoa plugin could not been found. In order to solve this issue, I set the variable `QT_PLUGINS_PATH` to my plugins folder in qt (which has been installed using brew). 

After that, if I have an instance of qutebrowser opened and I use pyton to execute qutebrowser, it opens just fine but it opens a window in the existing instance. If I close the opened instance of qutebrowser and I try to start a new instance using Python, I get a dialog saying qutebrowser needs web engine or web kit but it can find neither. When I clicked the ok button, it closes. 

I have tried installing PyQt 5 and PyQtWebEngine using pip 3, however, it still cannot find web engine. I was wondering if there was something I forgot. Could you give me a little help? Thank you in advance.
**Version info (see `:version`)**:
1.9.0
**If applicable: Does the issue happen if you start with `--temp-basedir`?**:

**Comment by The-Compiler** [comment]
If you install PyQt5/PyQtWebEngine via pip (using the binary), you will end up with a pre-built Qt which also comes without proprietary codec support.

Unfortunately, Homebrew's recent [PyQt upgrade](https://github.com/Homebrew/homebrew-core/pull/46598/files) seems to have removed PyQtWebEngine. I'm not sure if that was deliberate, but that means using Homebrew to install PyQt won't work.

I'm not sure if Homebrew's Qt still comes with proprietary codec support - but if so, you should be able to install that, then [build PyQt from source](https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#building-and-installing-from-source), then do the same with PyQtWebEngine. I can't really help with that though, as that's not something I've ever done on macOS.
