### ISSUE TITLE
QUTE_URL not set in userscript spawned with `hint inputs userscript`

### ISSUE THREAD

**Issue by olmokramer** [qutebrowser/qutebrowser#5217]
**Version info (see `:version`)**:

```
qutebrowser v1.8.3
Git commit: e9e08eccf-dirty (2019-12-30 12:43:46 +0100)
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

CPython: 3.8.0
PyQt: 5.13.2

sip: 4.19.19
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.13.2
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.3.200 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.4.2-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/olmo/.cache/qutebrowser
config: /home/olmo/.config/qutebrowser
data: /home/olmo/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/olmo/.config/qutebrowser/config.py has been loaded
Uptime: 33 days, 22:46:53
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

The documentation for the `:hint` command says

    userscript: Call a userscript with $QUTE_URL set to the link.

Only while writing this I realized that "the link" is supposed to be the link on the hinted element, and probably `QUTE_URL` is not set because inputs do not link anywhere.

Still, having the current URL would be useful in scripts spawning from a `:hint inputs`. My use case is this: I have a script to fill in password forms that tries to detect the correct password to use based on the current page's URL (similar to the `qute-pass` userscript) that I ran from a keybinding:

    :bind gl spawn --userscript my-password-script --username --password

This worked fine and well, but I found it rather annoying that I had to

1. Select the correct input (`gi` does not always work)
2. Press `<Esc>` to go to normal mode
3. Run the userscript

So I want to do this all in one go with

    :bind gl hint inputs userscript my-password-script

but now `my-password-script` does not get any `QUTE_URL` environment variable.

BTW I also tried 

    :bind gl hint inputs userscript my-password-script --username --password {url}

but it seems that the `userscript` hint target does not parse its arguments and I get an error that the script `my-password-script --username --password {url}` could not be found...

Is there any way to pass extra information to a script called from `:hint <group> userscript`?

**How to reproduce**

1. Run
```
qutebrowser --temp-basedir https://duckduckgo.com
```
2. Save this script in `$TMP_BASEDIR/data/userscripts/env` and make it executable
```py
#!/usr/bin/env python3
import os
open('/tmp/qute-env', 'w').write('\n'.join(os.environ.keys()))
```
3. In the temporary qutebrowser session, run
```
hint inputs userscript url
```
4. Open the file `/tmp/qute-env` and no `QUTE_URL` is present.

**Comment by The-Compiler** [comment]
I think your step 3. should probably say `hint inputs userscript env` rather than `url`, no?

I added this to #937, so I'm going to close this one. I was about to suggest using `{url}` as commandline argument instead, but that doesn't work currently because of #3400...

**Comment by olmokramer** [comment]
Oh yeah that's right, I meant `env` instead of `url`. Thanks for spotting that and for considering this in general :)

**Comment by harmtemolder** [comment]
@olmokramer I'm trying the same thing, but can't get it to work because `hint inputs userscript <script>` does not actually activate the selected input. Did you ever get this to work?

**Comment by olmokramer** [comment]
> @olmokramer I'm trying the same thing, but can't get it to work because `hint inputs userscript <script>` does not actually activate the selected input. Did you ever get this to work? 

I haven't used qutebrowser in a while and don't remember if I got this to work. I'm sorry I can't be of more help.

**Comment by harmtemolder** [comment]
For anyone encountering this same use-case:

If I'm fast enough with picking an input, this seems to work:

```python
config.bind("<z><h><l>", "hint inputs;; spawn --userscript qute-pass --password-only")
```

Related discussions:

- https://github.com/qutebrowser/qutebrowser/discussions/8019
- https://github.com/qutebrowser/qutebrowser/discussions/8176
