### ISSUE TITLE
Scroll shortcut

### ISSUE THREAD

**Issue by skuzzymiglet** [qutebrowser/qutebrowser#5224]
In `youtube.com`, `j` and `k` send up/down to the player. It would be nice to have scroll shortcuts such as `Shift-j` and `Shift-k` to avoid the need for mouse/trackpad scrolling

**Comment by The-Compiler** [comment]
Shift and j/k already switch tabs. However, there is the :scroll-px command you can bind to, which will always scroll in those cases (but currently has issues when there are multiple scrollable elements on a page).
