### ISSUE TITLE
datadome blocks qutebrowser

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5226]
https://datadome.co/ ("Global AI-powered real-time bot protection"™) seems to block qutebrowser with the default settings.

Affected pages I'm aware of:

- https://www.blablacar.fr/
- https://www.toppreise.ch/
- https://datadome.co/ itself
- https://www.thefork.com/
- https://www.laredoute.com/
- https://www.rueducommerce.fr/
- http://www.editus.lu/
- https://directvelo.com/
- https://www.cairn-int.info/
- https://www.francemarches.com/
- https://www.interencheres.com/
- https://www.lequotidiendumedecin.fr/

**Comment by The-Compiler** [comment]
Datadome claimed to have fixed this, but nothing changed (bonus: "Following your feedback, we have worked in order not reduce the risk of false-positive with qutebrowser." :confused:)

Meanwhile, it took me some 3 minutes to find out how to circumvent it: `:set -u datadome.co content.headers.user_agent 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}'` (i.e., remove `{qt_key}/{qt_version}`).

I'll give them another day or two to try and fix it on their end, and if that doesn't work out, I'll push a workaround myself.

**Comment by The-Compiler** [comment]
Datadome claims to have fixed this properly. It seems to work fine for me, but I've heard about other users still having issues. If people reading this want to do me a favor: Can you test accessing the pages above with v1.10.0 and `--temp-basedir` and tell me how things look?

**Comment by toofar** [comment]
They all loaded fine for me on master with a temp basedir and no proxies or anything.

**Comment by The-Compiler** [comment]
Thanks for the test! I'm assuming this is fixed then.

**Comment by The-Compiler** [comment]
Well, I already feared that this will come back. It did, just much faster than I would've guessed. Talking to them again since I'd rather not have a hardcoded list of their customers in qutebrowser's source, but hey, if that's what it takes...

**Comment by vincowl** [comment]
Seems to be back : cannot access the following site : [https://www.darty.com](https://www.darty.com)
Here is my config :
```
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.4 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.6.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: no
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.13.216 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022
```
