### ISSUE TITLE
Make fullscreen notification overlay timeout configurable

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5227]
Currently, the `FullscreenNotification` hide timeout is hardcoded to 3s (in `webenginetab.py` which creates the object).

Instead, it should be configurable, including a value (probably 0 or -1 or None, depending on how other settings do this) to not show it at all.

Also, it might be good to rename `content.windowed_fullscreen` to `content.fullscreen.window` if we name this something like `content.fullscreen.overlay_timeout`.

See https://www.reddit.com/r/qutebrowser/comments/ezxjtl/how_to_hide_fullscreen_notification/

**Comment by cristoferfb** [comment]
Is anyone working in this issue?

**Comment by svetelna** [comment]
Hello, 
I already looked into the problem. Could I start working on this task?

**Comment by The-Compiler** [comment]
Hey @svetelna! Recently, @cristoferfb asked on the mailinglist and here whether this is okay to take, but looks like that comment is deleted now. @cristoferfb could you clarify whether you started working on this, or whether this is okay to take?

**Comment by svetelna** [comment]
Hello again, can I start since no response was given?

**Comment by The-Compiler** [comment]
Sure, please go ahead! :+1:

**Comment by svetelna** [comment]
Should I expect some problems with migrating config (from content.windowed_fullscreen to content.fullscreen.window)?
Are there any special steps for migration to take? On webpages I read, that qutebrowser does not do automated migration, but I ask only to be sure.

**Comment by The-Compiler** [comment]
qutebrowser does migrate `autoconfig.yml` files (written when using `:set` or other configuration via the user interface), it just doesn't migrate `config.py` files.

For a simple rename, all you'll need to do is having something like this in `configdata.yml`:

```yaml
content.windowed_fullscreen:
  renamed: content.fullscreen.window
```

**Comment by svetelna** [comment]
Thank you! I see now.

**Comment by svetelna** [comment]
#5297
