### ISSUE TITLE
pressing PgDn key works flawlesly while "scroll-page 0 1" fails on some sites

### ISSUE THREAD

**Issue by freed00m** [qutebrowser/qutebrowser#5230]
Hi,

I have problems with scroll-page doesn't work on certain pages like https://material.angular.io

What does work is however just scroll up and down so I binded multiple of them toghether but feels so wrong.

```
#config.bind('j', 'scroll-page 0  0.5') # Doesn't work on some pages
config.bind('j', 'scroll down ;; scroll down ;; scroll down ;; scroll down ;; scroll down ;; scroll down ;; scroll down ;; scroll down ;; scroll down ;; scroll down')
#config.bind('k', 'scroll-page 0 -0.5') # Doesn't work on some pages
config.bind('k', 'scroll up ;; scroll up ;; scroll up ;; scroll up ;; scroll up ;; scroll up ;; scroll up ;; scroll up ;; scroll up ;; scroll up')

```

**Version info (see `:version`)**:
https://paste.the-compiler.org/view/9fa95a1c

**If applicable: Does the issue happen if you start with `--temp-basedir`?**:
It is the same

**Comment by The-Compiler** [comment]
See #1354 - this will be fixed by #3691/#4715.
