### ISSUE TITLE
Picture in picture mode doesnt work for mp4 videos

### ISSUE THREAD

**Issue by GasparVardanyan** [qutebrowser/qutebrowser#5248]
**Version info (see `:version`)**:
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Picture in picture mode doesnt work for mp4 videos.

**How to reproduce**

Open any mp4 video in qutebrowser and try to enable the "Picture in picture" mode.

**Comment by The-Compiler** [comment]
Reported upstream: [[QTBUG-82390] Support "picture in picture" mode for videos - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-82390)
