### ISSUE TITLE
Any idea on how to integrate qutebrowser into emacs with EAF

### ISSUE THREAD

**Issue by QiangF** [qutebrowser/qutebrowser#5253]
EAF bridges the gap between emacs lisp and python, it is also built on top of the qt platform. 
It's even has a browser implemented. But looks like the browser in EAF lacks a lot of functionalities compared to this project. 

Emacs now have almost everything to look like an operating system, like window manager (EXWM), systemd replacement (systeme), terminal (emacs-libvterm). It will be be nice if we can get tightly integrate qutebrower into that system.

Here is the link to eaf
https://github.com/manateelazycat/emacs-application-framework/wiki/Keybindings

**Comment by The-Compiler** [comment]
No idea - you tell me what it needs to be able to integrate qutebrowser, then I might be able to answer how far qutebrowser can provide that.

**Comment by manateelazycat** [comment]
I'm author of EAF, EAF browser has include vimium and many other features.

I recommend close this issue.

Thank you created Qutebrowser, EAF browser draw a lot of features quteborwser
