### ISSUE TITLE
Can't paste images from clipboard / expose JavascriptCanPaste

### ISSUE THREAD

**Issue by cristoferfb** [qutebrowser/qutebrowser#5256]
**Version info**:
qutebrowser v1.10.1
Git commit: df45e7401 (2020-02-22 10:27:28 +0100)
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

**Description**
Can't paste a image from clipboard in qutebrowser, I try this coping from gimp, when paste gimp crash. I also test it with Photoshopea an online image editor, in this case nothing happen. It works fine in Brave (Chromium).

**How to reproduce**
1.- Open an image with a image editor.
2.- Use the select tool for select a part of the image.
3.- Copy that with ctrl+c.
4.- paste it in a Facebook comment input or any other input field with image compatibility.

**Comment by The-Compiler** [comment]
Can you try copying from something other than Gimp, and ideally pasting in some other Qt application? I've seen Gimp crash when pasting images into Telegram Desktop, so I doubt this is a qutebrowser bug.

**Comment by cristoferfb** [comment]
I done new tests with qtwebbrowser.                  

Paste from Gimp to qtwebbrowser: works
Paste from Photoshopea to qtwebbrowser: works
Paste from qutebrowser to qtwebbrowser: works
Paste from qtwebbrowser to qutebrowser: not work

In the last test I try to paste to this github comment and it give me the next error message: "Something went really wrong, and we can't process that file"

**Comment by The-Compiler** [comment]
Can you try with KDE Falkon (might be called "qupzilla" on older distributions) as well? It's closer to what qutebrowser uses.

**Comment by The-Compiler** [comment]
I still don't see a difference between Falkon and qutebrowser. I first thought I saw one with GitHub comments, but it looks like GitHub is [having issues](https://www.githubstatus.com/) right now.

With [Photopea](https://www.photopea.com/) (which is probably what you mean when you say "Photoshopea"?) indeed nothing happens, but nothing happens with Falkon either. This is probably something which should be reported to Qt upstream.

I haven't found an example where it's possible to make Gimp crash. Do you have a page (not Facebook) where I can try? Also, what pages did you test with Falkon exactly?

**Comment by cristoferfb** [comment]
Sorry my mistake I try to say Photopea.

Ok I did several test and I get an inconsistency in the behaviour:

1.- Open an image in GIMP
2.- Use the select tool for select a part of the image
3.- Copy it with Ctrl+C
4.- Open 2 Qutebrowsers (I open this Issue page in both)
5.- Try to paste the copy select in the issue comment section in the first Qutebrowser window: it works
6.- I try does the same in the second window getting crash gimp.

Gimp error:

```
The program 'gimp' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 82229 error_code 3 request_code 18 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(script-fu:32202): LibGimpBase-WARNING **: 17:57:59.798: script-fu: gimp_wire_read(): error
```

recomendation: search "wallpapers" in DuckDuckGo select one and take a screenshot  of it (I think it is importat because I try a lot with a black image and never get the crash but with a complex image pattern is more posible to get crash)

I did new test with Falkon and get the same inconsistency.

As you say it can be a Qt bug.

**Comment by The-Compiler** [comment]
Reopening this for now, as I'd at least like to report the Photopea issue to Qt.

**Comment by The-Compiler** [comment]
Photopea seems to work fine if the `JavascriptCanPaste` attribute is set - probably should add a setting for that.

**Comment by chaorace** [comment]
If anyone happens to encounter this issue before the setting gets added, you can manually set the attribute needed with a little config hack:

```
from PyQt5.QtWebEngineWidgets import QWebEngineSettings
from qutebrowser.browser.webengine import webenginesettings

webenginesettings.default_profile.settings().setAttribute(QWebEngineSettings.JavascriptCanPaste, True)
```

**Comment by The-Compiler** [comment]
If you do this, please be aware of its security implications - I haven't tried, but I'd expect this to result in all websites being able to read your clipboard (and e.g. passwords stored there or whatever).

Also, adding the "easy" tag here because adding a new setting for this should only be a couple of lines, namely in `qutebrowser/browser/webengine/webenginesettings.py` (`WebEngineSettings._ATTRIBUTES`) and `qutebrowser/config/configdata.yml` (the setting definition).

If you want to try submitting a PR for this, @chaorace, that'd be most welcome! That'd then also allow setting the setting per-domain rather than globally.

**Comment by Lembrun** [comment]
I can reproduce the gimp crash when pasting from it to github comment,(took this one [https://wonderfulengineering.com/wp-content/uploads/2014/07/Landscape-wallpapers-15.jpg](url)) it seems to happens when you select ~40-50% of the image (or it's a border thing ?).

I'll see what I can do for the per-domains settings
