### ISSUE TITLE
Various issues with twitch.tv 

### ISSUE THREAD

**Issue by SigurdSigursdsson** [qutebrowser/qutebrowser#5260]
**Version info**:
qutebrowser v1.10.1
Git commit: df45e7401 (2020-02-22 10:27:28 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)
Qt: 5.9.5

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Hi, I am new using qutebrowser, I encountered following issues:

1. When I attempt to :open on certain page on twitch.tv e.g. `:open https://www.twitch.tv/jorbs/videos/`, I am almost immediatelly redirected to the twitch main page ([https://www.twitch.tv/](url)).
2. When I try to log in to my twitch acount, I am also redirected to the twitch main page and I am not logged in.

**How to reproduce**
See Description

**Comment by toofar** [comment]
Can you run with `--temp-basedir --debug` and paste what it logs to stdout after it first mentions the URL you open? Also what distro/OS are you on?

**Comment by The-Compiler** [comment]
I initially couldn't reproduce, but after reproducing 2. with Qt 5.9.3, I now can also reproduce 1.

I can't test Qt 5.10 and 5.11 right now, but with Qt 5.12, the issue goes away. So I'm guessing this is somehow caused by something in the old Chromium version Qt 5.9 comes with.

Relevant part of the log shows nothing interesting:

```
13:36:53 DEBUG    webview    browsertab:_set_load_status:930 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='https://www.twitch.tv/jorbs/videos/'>: LoadStatus.loading
13:36:53 DEBUG    webview    browsertab:_on_navigation_request:992 navigation request: url https://id.twitch.tv/oauth2/authorize?client_id=<REDACTED>&lang=en&login_type=l…, type Type.link_clicked, is_main_frame True
13:36:53 DEBUG    webview    browsertab:_on_navigation_request:992 navigation request: url https://www.twitch.tv/passport-callback#access_token=<REDACTED>&scope=chat_logi…, type Type.link_clicked, is_main_frame True
13:36:53 DEBUG    webview    browsertab:_set_load_status:930 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='https://www.twitch.tv/jorbs/videos/'>: LoadStatus.success_https
13:36:53 DEBUG    signals    signalfilter:_filter_signals:88 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://www.twitch.tv/passport-callback#access_token=<REDACTED>&scope=chat_login+user_read+user_subscriptions+user_presence_friends_read&state=%7B%22origin%22%3…) (tab 1)
13:36:54 DEBUG    signals    signalfilter:_filter_signals:88 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://www.twitch.tv/')) (tab 1)
```

**Comment by The-Compiler** [comment]
Okay, looks like I can reproduce with Qt 5.10 and 5.11 as well. Doesn't look like there is a workaround. Yet another data point for https://github.com/qutebrowser/qutebrowser/issues/3839#issuecomment-583280160 I guess!

Nothing qutebrowser can do here - @SigurdSigursdsson you'd need to upgrade your Qt version, or use an [install via virtualenv](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#tox).
