### ISSUE TITLE
Userscript can't recognize $QUTE_URL while executed with bind

### ISSUE THREAD

**Issue by unmd101** [qutebrowser/qutebrowser#5276]
**Version info (see `:version`)**:  qutebrowser v1.10.1

**If applicable: Does the issue happen if you start with `--temp-basedir`?**: No

**Description**: When executing userscript with bind I get error: ```ERROR: '{QUTE-URL}' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:{QUTE-URL}" ) to search YouTube```. Despite of it, ```:spawn ytmd {url}``` works fine. 

Script that I'm trying to execute:  
```
#!/usr/bin/sh
youtube-dl -i \
    -o '$HOME/Music/%(title)s.%(ext)s' \
    --add-metadata \
    --audio-quality 0 \
    "$1" && notify-send "Track downloaded."
```
And the bind looks like this:
``` config.bind('Alt-x', 'spawn ytmd {url}')```

Thanks for any help in advance.

**Comment by The-Compiler** [comment]
Are you sure your bind looks like this and doesn't use `{QUTE-URL}` instead of `{url}`. That `QUTE-URL` string is in your error message but nowhere in qutebrowser's sources, so it must be coming from you in some way.

**Comment by unmd101** [comment]
> Are you sure your bind looks like this and doesn't use `{QUTE-URL}` instead of `{url}`. That `QUTE-URL` string is in your error message but nowhere in qutebrowser's sources, so it must be coming from you in some way.
Just reloaded my X session, now it works as expected. Thank you and sorry for taking your time.
