### ISSUE TITLE
Sound not working on Archlinux

### ISSUE THREAD

**Issue by marcosdsanchez** [qutebrowser/qutebrowser#5282]
**Version info**:
https://paste.the-compiler.org/view/1e07fc31

**Does the bug happen if you start with `--temp-basedir`?**: YES

**Description** 

No sound when viewing videos in YouTube or Vimeo. `pavucontrol` shows "chromium" as if it were producing sound but nothing is heard. No problem with sound in other apps or in Firefox. All sound dependencies are installed.

Software installed: https://gist.github.com/marcosdsanchez/f6b4c483d9e4fcdf277906778b07be7d

**How to reproduce**
Go to https://www.youtube.com/watch?v=CfW845LNObM or https://vimeo.com/jobs

**Comment by The-Compiler** [comment]
Works fine here. Can you show a screenshot from pavucontrol? Can you reproduce it with `falkon` as well?

**Comment by marcosdsanchez** [comment]
Thanks for your quick answer.

> Can you show a screenshot from pavucontrol?

![2020-03-11-105005_1294x1403_scrot](https://user-images.githubusercontent.com/45263/76423862-28d47080-6386-11ea-80e6-207b63066a4b.png)

> Can you reproduce it with falkon as well?

The bug is reproducible with `Falkon` browser as well. In that case, pavucontrol also shows that `Falkon` is producing sound but nothing is heard.

Note that the problem seems to be specifically with videos, other sounds like when receiving a message in `web.whatsapp.com` work just fine.

**Comment by The-Compiler** [comment]
This isn't a qutebrowser issue then, and must be something on your system - unfortunately, I can't reproduce and I have no idea how to debug something like that. You might want to double-check that the "output devices" tab also shows sound and that nothing is muted in `alsamixer`. Also, you might want to try with Chromium as well.

**Comment by marcosdsanchez** [comment]
Thanks for your help. Chromium is also affected by the problem. `alsamixer` does not show anything muted. It's really strange indeed. I'd appreciate if you have any more tips on things to check.

**Comment by marcosdsanchez** [comment]
In case it helps for people reading this issue killing pulseaudio and restarting it for some reason fixes the problem...

```
$ pulseaudio -k
$ pulseaudio --start
```

Problem keeps reappears on machine restart.

**Comment by Borroot** [comment]
Sound is also not working for me Arch Linux, killing and restarting pulseaudio does not do the trick for me. I have put a post on the Arch forum asking for help, but maybe you also have some ideas.

https://bbs.archlinux.org/viewtopic.php?id=260330
