### ISSUE TITLE
Add option to disable qute://log

### ISSUE THREAD

**Issue by josephtheengineer** [qutebrowser/qutebrowser#5285]
Warning in the qute-pass script  
```
WARNING: the passwords are stored in qutebrowser's
           debug log reachable via the url qute://log
```
Is this a security issue? If so is there a way to simply disable qute://log, or maybe a way to hide something from qute://log?

**Comment by The-Compiler** [comment]
It's only a security issue if you leave your machine unattended (but then you probably have bigger things to worry about). The main worry is that the log is part of crash reports if you submit one without editing/disabling the log (but still, only a very small set of people has access to those).

You can launch qutebrowser via `--loglines 0` to disable logging entirely, though. Note that will make things much more difficult if you actually run into trouble though, and it'll also break `:messages`.
