### ISSUE TITLE
Add settings to configure loglevels

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#5286]
**Version info**:

```
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1
```

Also on master (c7b0023dcd576f7e7d6223f94a4ced5f2932afc5).

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

I was looking into using the `qute-pass` userscript and wanted to prevent passwords from showing in the logs.
#5285 suggests `--loglines 0`, which does work, but I was looking for a way to prevent DEBUG logs (which is where the password would typically show up).

Passing `--loglevel info` is only respected by the console logger, the `RAMHandler` is hardcoded to `logging.NOTSET`.
Is this intentional, or should it respect `--loglevel`?

**How to reproduce**

Run `qutebrowser --loglevel info qute://log` and see the `DEBUG` logs.

**Comment by The-Compiler** [comment]
From #5289:

> Getting back to #5286: At least originally, that was intended - there wasn't really any reason to modify the internal log level.

I don't think it makes sense for `--loglevel` to affect the RAM handler loglevel by default - I suppose most people (or at least I) mainly want it to affect the console output.

Not sure what to do about this then - what do you think?

**Comment by rcorre** [comment]
I'm thinking a config option would be the nicest way to persist this, rather than having to add a flag everywhere you use qutebrowser (the latter seems like it could have a lot of possibilities ... `$BROWSER`? desktop entry? CLI invocation?).

Maybe:

```
c.logging.level.ram = 0 # or a string like "critical"?
c.logging.level.console = 0
```

I think that's the safest, easily-doable approach for enabling password manager integration, anyways.

I still like idea 3 from #5289, of being able to set specific userscripts as silent, but the async bit is tricky.

**Comment by The-Compiler** [comment]
Sounds good! I used to be against it because I suspect that it'll make crash reports less useful in general, but I guess I can deal with that - and more power to the users! Definitely +1 for strings rather than integers, though.

As for #5289, should we close the current PR then, given that that approach likely isn't feasible, at least not before we have some way to know when a command has ended (#3007)?

**Comment by rcorre** [comment]
Hmm, the challenge here is that logging inits before config...

**Comment by The-Compiler** [comment]
Good point... I suppose it'd suffice to set the log levels as soon as the config is available? Then there might be some extra messages being logged at the very beginning, but at least after that, the correct loglevel is set.
