### ISSUE TITLE
Logins don't save

### ISSUE THREAD

**Issue by konkywill** [qutebrowser/qutebrowser#5291]
**Version info**:
qutebrowser v1.10.1
Git commit:
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
Sites such as youtube and reddit logout once qutebrowser is closed
**How to reproduce**
N/A (Happened on install)

**Comment by The-Compiler** [comment]
On Reddit you said:

> Qutebrowser saves logins on my Manjaro partition and on my Arch partition, but not on my gentoo partition, they are all using the same /home partition

Sharing a data directory between different Qt versions is not supported (by QtWebEngine, or rather the underlying Chromium). You'll need to use separate directories, or make sure you're running the same Qt version everywhere (i.e. update to Qt 5.14 on Gentoo).
