### ISSUE TITLE
(Feature Request) Javascript Manager

### ISSUE THREAD

**Issue by danrobi11** [qutebrowser/qutebrowser#5296]
Javascript on/off not enough
Embedded javascript manager something like Eolie would be very nice: https://flathub.org/apps/details/org.gnome.Eolie
Thx for qute, I really like it. Lightweight, run well. Good job :+1:

**Comment by toofar** [comment]
@danrobi11 what does the javascript manager in Eolie do?

**Comment by The-Compiler** [comment]
So I spent some 5 minutes clicking around in Eolie, and I still have no idea what you mean. I don't see anything else than an on/off toggle there. Some more words and maybe a screenshot would surely help!

**Comment by danrobi11** [comment]
@The-Compiler I made a video to show you the Eolie js manager:
https://open.lbry.com/@Danrobi:b/Eolie-js-manager2:9

**Comment by The-Compiler** [comment]
See existing discussions about this in #2626 and #28.
