### ISSUE TITLE
hints: allow hints to be the same every time you visit the same page

### ISSUE THREAD

**Issue by jkulhanek** [qutebrowser/qutebrowser#5298]
It would be nice if the hints were the same every time the user visited the same webpage. E.g, when navigating to google.com, the pagination would have the same hints. The random generator for generating the hints could be seeded by the parent object's id or something like this.
Another useful thing would be to have the length of the hint depend on the priority of the particular link.

**Comment by The-Compiler** [comment]
There is no random generator involved - the hints are different because there is a different amount of hintable elements on the page. Changing this would either involve clever heuristics (somewhat covered by #2644 I think), or a way to manually assign hints (see #674).
