### ISSUE TITLE
Renderer process crashes with Zoom

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#5311]
**Version info**:
qutebrowser v1.10.1
Git commit: 793961350 (2020-03-23 20:30:02 +0100)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Renderer process crashes within seconds of joining a conference call on Zoom.

---
OS: 5.5.10-arch1-1

**Comment by The-Compiler** [comment]
I can't reproduce with the test conference call you get after signing up (on Arch Linux, same Qt version).

If you run with `--temp-basedir` in a terminal, what output do you get when the renderer process crash happens? Could you try to reproduce it with KDE Falkon as well?

**Comment by billop** [comment]
I had this issue a while ago but after updating everything just now (Arch Linux, sway-git, qutebrowser-git), I don't get this issue anymore.

**Comment by The-Compiler** [comment]
Oh, I just found out you can use https://zoom.us/test without an account, that makes things easier to test... Could maybe other people give it a try as well?

@prosoitos Maybe updating your system will help too?

**Comment by The-Compiler** [comment]
@prosoitos Any update?

**Comment by andys8** [comment]
Starting zoom from qutebrowser was working fine for me today (and in the past).

**Comment by billop** [comment]
Happened once today for me on latest commit as of today and latest Arch Linux, but I can't reproduce it. I suspect the test meeting may not trigger this issue.

**Comment by zimawho** [comment]
It systematically crashes for me too. My zoom meetings are password protected, not sure if it has anything to do with the problem but I wanted to add that bit of information anyway. Archlinux updated yesterday.  

```
qutebrowser v1.11.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2
```

**Comment by zimawho** [comment]
I tried today with `--temp-basedir` and it still crashed. Here is the log. 
```
[77810:77836:0505/182447.009665:ERROR:database.cc(1598)] Cookie sqlite error 1032, errno 0: attempt to write a readonly database, sql: DELETE FROM cookies WHE
RE name=? AND host_key=? AND path=?
[77810:77836:0505/182447.009766:ERROR:database.cc(1598)] Cookie sqlite error 2067, errno 0: UNIQUE constraint failed: cookies.host_key, cookies.name, cookies.
path, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, is_secure, is_httponly, samesite, last_access_utc, ha
s_expires, is_persistent, priority) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```

**Comment by Holzhaus** [comment]
Might be coincidence, but last time this happened when other participants enabled their video.

**Comment by prosoitos** [comment]
Sorry for my *very* late reply...

The crashes I had were also with participants having their video on. I installed the Zoom app, so I haven't tried in quite some time. So not sure where this stands at this point. I will now use Zoom only with the app because I need options which are not available in their web version anyway.

**Comment by The-Compiler** [comment]
Does anyone still see this with Qt 5.15?

**Comment by Holzhaus** [comment]
I'll test again next week. I installed chromium and used that to join Zoom meetings in the last weeks.

**Comment by Holzhaus** [comment]
Zoom now works fine for me with Qt 5.15.0 and qutebrowser 1.12.0.

**Comment by The-Compiler** [comment]
Cool! Assuming this was fixed somewhere in QtWebEngine/Chromium then. If anyone still sees this with Qt 5.15, please holler!
