### ISSUE TITLE
Terminus (TTF) as a font

### ISSUE THREAD

**Issue by d4ve01f** [qutebrowser/qutebrowser#5315]
Hi, I'm on archlinux and I install Terminus TTF from the AUR,
but I do not understend how to set it up on qutebrowser..
Can you help me?

**Comment by The-Compiler** [comment]
Where exactly do you want it as font?

**Comment by d4ve01f** [comment]
It’s possibile set it up everywhere? I mean tabs, url , etc

**Comment by traverseda** [comment]
Qutebrowser lets you set a *font-family* for a bunch of variables. My understanding is that it gets font-family information through fontconfig. You can [set terminus as the default monospace font](https://unix.stackexchange.com/questions/106070/changing-monospace-fonts-system-wide) or you can create a new font family that contains just terminus, maybe a `monospace-terminus` font family?

Then you just [set the fonts like any other setting](https://www.qutebrowser.org/doc/help/settings.html#fonts.statusbar).

It's a bit more arcane than just setting a font name unfortunately.

**Comment by d4ve01f** [comment]
It works perfectly, how can I set the anti aliasing?

**Comment by traverseda** [comment]
https://wiki.archlinux.org/index.php/Font_configuration#Anti-aliasing

**Comment by The-Compiler** [comment]
A font family *is* a font name! See e.g. https://en.wikipedia.org/wiki/Font_family:

> A font family is typically a group of related fonts which vary only in weight, orientation, width, etc., but not design. For example, Times is a font family, whereas Times Roman, Times Italic and Times Bold are individual fonts making up the Times family. Font families typically include several fonts, though some, such as Helvetica, may consist of dozens of fonts.

So all you should need to do is setting `fonts.default_family` to `Terminus (TTF)` (or `xos4 Terminus` with the `terminus-font` package).
