### ISSUE TITLE
How about wpewebkit?

### ISSUE THREAD

**Issue by traverseda** [qutebrowser/qutebrowser#5316]
[Wpewebkit](https://wpewebkit.org/) is a webkit fork focused on embedding. I figured I'd let you know it exists, even if it doesn't end up being that useful.

It seems like qtwebengine is potentially holding back a number of features. For example the venerable #30 . I've used [cog](https://github.com/Igalia/cog)/wpewebkit in some professional contexts. So far it works great, I also notice that cog appears to support webextentions.

It might be entirely out of scope to switch out the rendering engine for something else, but if that was practical there seems like there would be some big benefits to using the wpewebkit fork.

This might be a better issue for upstream, as it might be able to simplify the qtwebengine build?

**Comment by The-Compiler** [comment]
>  I also notice that cog appears to support webextentions.

That would pretty much be the only reason to use it, if it was true. Do you have some more details on that?

> It might be entirely out of scope to switch out the rendering engine for something else

Note you can already use qutebrowser with QtWebKit rather than QtWebEngine.

> This might be a better issue for upstream, as it might be able to simplify the qtwebengine build?

Given that Qt switched from QtWebKit (i.e. WebKit) to QtWebEngine (based on Blink/Chromium): Probably not.

**Comment by traverseda** [comment]
After playing around with it for a bit, it seems to have some pretty big rendering engine issues that would make it unsuitable regardless.

**Comment by The-Compiler** [comment]
FWIW I assume you meant WebKit's [Web Extensions](https://blogs.igalia.com/carlosgc/2013/09/10/webkit2gtk-web-process-extensions/) which have nothing to do with the extension API called WebExtensions (IIRC, WebKit's use of the name predates the extension API). They're just a way of running custom code in the browser process.
