### ISSUE TITLE
Cache and cookies

### ISSUE THREAD

**Issue by ReK2Fernandez** [qutebrowser/qutebrowser#5321]
I found how to remove history but cant RTFM anywhere how to remove cache and cookies. I by mistake loaded a site I do not trust.. and want to delete it all with out deleting my settings. I removed ~/.cache/qutebrowser but my cookies are still there etc.

**Comment by wedens** [comment]
You can run `:inspector` command, open "Application" tab and either delete specific cookies in "Cookies" menu or "Clear storage" to clear everything.

Also see https://github.com/qutebrowser/qutebrowser/issues/58

**Comment by ninewise** [comment]
Since it's a bit lost in the comments on #58, you can find and
remove Cookies and other local data on your data path (usually
`~/.local/share/qutebrowser`, check yours with `:version`). Removing
`cookies` and `webengine` there should do. You can also edit the
`history.sql` (but that I'd advice against). To be sure, shut down
qutebrowser before doing this (especially when removing the cache like
you did).

**Comment by Pound-Hash** [comment]
> You can run `:inspector` command, open "Application" tab and either delete specific cookies in "Cookies" menu or "Clear storage" to clear everything. Unfortunately, AFAIK, you can only do that with the site open.
> 
> Also see #58

The `:inspector` command no longer works. Is there an alternative?

**Comment by ninewise** [comment]
Yes, it was renamed to `:devtools`.

**Comment by Pound-Hash** [comment]
> Yes, it was renamed to `:devtools`.

But I don't see anything in there about cookies or cache.

**Comment by mschilli87** [comment]
@Pound-Hash 
> But I don't see anything in there about cookies or cache.

I do, after clicking on 'Application' as descibed in [the original answer](https://github.com/qutebrowser/qutebrowser/issues/5321#issuecomment-607610030) [quoted by you](https://github.com/qutebrowser/qutebrowser/issues/5321#issuecomment-1028443904).

Also note that this is not qutebrowser specific. So if you need additional help, I suggest you read [the Chrome DevTools documentation for the Chromium Project](https://www.chromium.org/teams/devtools/) before asking your remaining questions, if any, at [the corresponding mailing list](https://groups.google.com/a/chromium.org/g/chromium-discuss).

**Comment by qwerty-in-me** [comment]
> The `:inspector` command no longer works. Is there an alternative?

t'would be :devtools now, in the three dots menu you'll find the Aplications section
