### ISSUE TITLE
Segmentation fault while opening some sites

### ISSUE THREAD

**Issue by unmd101** [qutebrowser/qutebrowser#5324]
**Version info (see `:version`)**:  qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

CPython: 3.8.2
PyQt: 5.14.1

sip: 5.1.1
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.1.3
yaml: 5.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform: Linux-5.5.13-arch2-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**If applicable: Does the issue happen if you start with `--temp-basedir`?**: No

**Description**: Opening [tjournal.ru](https://tjournal.ru) and [dtf.ru](https://dtf.ru) causes segmentation fault.

**Log:**

```
Fatal Python error: Segmentation fault
Thread 0x00007f915c0a2740 (most recent call first):
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 134 in qt_mainloop
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 124 in run
  File "/usr/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 201 in main
  File /usr/bin/qutebrowser", line 11 in <module>
```

---

*(edited by @The-Compiler to fix links and formatting)*

**Comment by The-Compiler** [comment]
Does quitting qutebrowser and moving `~/.local/share/qutebrowser/webengine/Service Worker/` away (don't delete it yet!) help?

Also, are you on Wayland?

**Comment by unmd101** [comment]
> Does quitting qutebrowser and moving `~/.local/share/qutebrowser/webengine/Service Worker/` away (don't delete it yet!) help?
> 
> Also, are you on Wayland?

No, I'm on X11. And moving the Service Worker folder away actually helped. Thank you so much :)

**Comment by The-Compiler** [comment]
It'll likely come back at some point I'm afraid - but it's a duplicate of #5279 then.

**Comment by unmd101** [comment]
> It'll likely come back at some point I'm afraid - but it's a duplicate of #5279 then.

Yeah, it's still crashes, but I've managed to fix it in some clumsy way by adding this to my qutebrowser execution bind in sxhkd:
`rm -rf $HOME/.local/share/qutebrowser/webengine/Service\ Worker`
