### ISSUE TITLE
Unable to create new GitHub repository in qutebrowser

### ISSUE THREAD

**Issue by smadurange** [qutebrowser/qutebrowser#5327]
Version information:

qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

CPython: 3.8.2
PyQt: 5.14.1

sip: 5.1.1
colorama: no
pypeg2: 2.15
jinja2: 2.11.1
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1e  17 Mar 2020

Style: QFusionStyle
Platform: Linux-5.5.13-arch2-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False

** This issue does not happen when qutebrowser is run with `--temp-basedir`.

Problem description:

When I try to create a new repository on GitHub using web interface, after I type the name of the repository, GitHub tries to validate the name of the repository (I can see the spinner before the green tick I usually see if the name if valid for the repo). Instead of seeing the green tick, I get the error message "Something went wrong". When I look at the developer tab, I see a console error:
`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`.
`Failed to load resource: the server responded with a status of 406 (Not Acceptable)`

I guess this is a configuration issue on my setup but I'm not sure which configuration it is that I need to change. Thanks.

**Comment by The-Compiler** [comment]
I'm guessing you set some weird `Accept` header in `content.headers.custom`. If it's not that, can you show your `:open qute://configdiff` please?

**Comment by smadurange** [comment]
@The-Compiler  Yes, I believe I changed the accept header. I did `:config-clear` and even tried restarting the machine but it doesn't seem to revert to default settings.

How can I restore the default settings?

My config diff is:

```
content.headers.accept_language = en-US,en;q=0.5
content.headers.custom = {"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"}
url.default_page = https://www.qwant.com
url.searchengines = {"DEFAULT": "https://www.qwant.com/?q={}"}
url.start_pages = https://www.qwant.com
```

**Comment by smadurange** [comment]
Couldn't remember the old configuration, so just uninstalled qutebrowser, deleted .cache/qutebrowser, .config/qutebrowser and .local/share/qutebrowser and did a fresh install.

**Comment by The-Compiler** [comment]
FWIW `:config-clear` without `--save` doesn't remove stored settings. You probably had a `autoconfig.yml` and/or `config.py` lying around in your `~/.config/qutebrowser`.
