### ISSUE TITLE
Support TLSv1.3

### ISSUE THREAD

**Issue by petabyteboy** [qutebrowser/qutebrowser#5329]
Chrome >= 70 and Firefox >= 63 support TLSv1.3 and I just noticed qutebrowser doesn't. Going to a website that does not support TLSv1.2 gives me:

```
... uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

https://caniuse.com/#feat=tls1-3

**Comment by The-Compiler** [comment]
What versions of qutebrowser and Qt are you on, and what's the "website that does not support TLSv1.2"?

FWIW https://browserleaks.com/ssl shows TLS 1.3 support for me with Qt 5.14.

**Comment by petabyteboy** [comment]
Oops, I only checked that I was running the latest qutebrowser version, but not th Qt version. My distribution (NixOS) ships qutebrowser v1.10.1 with Qt 5.12.7. I will look into this downstream.
The website is https://nix-matrix.nyantec.com/.

Closing since the issue is not with qutebrowser but with the packaging.

**Comment by The-Compiler** [comment]
Qt 5.12 is based on Chromium 69, so indeed you'd need Qt 5.13 or newer for TLS v1.3.
