### ISSUE TITLE
segmentation fault with --backend=webengine

### ISSUE THREAD

**Issue by edio** [qutebrowser/qutebrowser#5330]
**Version info**:
```
qutebrowser v1.10.1
Git commit: 
Backend: new QtWebKit (WebKit 602.1)
Qt: 5.14.1

CPython: 3.8.2
PyQt: 5.14.1

sip: 5.1.2
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.1
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QStyleSheetStyle
Platform: Linux-5.5.13-arch2-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-wd_g1ix_/cache
config: /tmp/qutebrowser-basedir-wd_g1ix_/config
data: /tmp/qutebrowser-basedir-wd_g1ix_/data
runtime: /tmp/qutebrowser-basedir-wd_g1ix_/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:04
```

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
```
qutebrowser -T --backend=webengine
```
Consistently results in segfaults.

Unlike #5313, disabling javascript and webgl does not solve the issue.

It seems, that the issue appeared after system upgrade. I tried rolled back qt5 libraries (version info includes rolled back versions) but it didn't help.

**How to reproduce**
reproducible on fresh ArchLinux under X, otherwise n/a

EDIT: Just read guidelines on segfault reporting. Working on providing debug data.

**Comment by edio** [comment]
Can't use the libraries compiled with debug symbols because those are of version 5.14.0 and my system is on 5.14.2 already and I can't rollback easily.

However I noticed, that systemsettings app from KDE also crashes with segfault. And looks like the source of it is the Intel's driver.

```
systemsettings5[23233]: segfault at 24 ip 00007fe4eb4807be sp 00007fffd939adf0 error 6 in iris_dri.so[7fe4ea9df000+dba000]
```

I'll try LTS kernel and will comment with the results

**Comment by The-Compiler** [comment]
Yep, pretty sure that's something specific to your system. Indeed the debug packages are outdated currently, as the server I used to build them isn't available anymore. Now that PyQt 5.14.2 arrived on Archlinux as well, I hope I'll find a way to update them.

**Comment by edio** [comment]
Switching to modesetting driver (apparently I was using xf86-video-intel) resolved both KDE's systemsettings and qutebrowser segfaults.
Closing the issue.
Sorry for bothering.
