### ISSUE TITLE
content is not scaled correctly between different screen resolutions

### ISSUE THREAD

**Issue by d-nnis** [qutebrowser/qutebrowser#5332]
**Version info**:
Version info
qutebrowser v1.10.1
Git commit: 7fef6a9c8 (2020-02-15 14:17:18 +0100)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

CPython: 3.7.6
PyQt: 5.14.1

sip: 5.1.1
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.1
pygments: 2.5.2
yaml: 5.3
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: 2.2.228 (bundled)
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QWindowsVistaStyle
Platform: Windows-10-10.0.18362-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.18362, SP0, 

Paths:
cache: C:\Users\ThinkPad\AppData\Local\qutebrowser\cache
config: C:\Users\ThinkPad\AppData\Roaming\qutebrowser\config
data: C:\Users\ThinkPad\AppData\Roaming\qutebrowser\data
runtime: C:\Users\ThinkPad\AppData\Local\Temp\qutebrowser

Autoconfig loaded: yes
Config.py: C:\Users\ThinkPad\AppData\Roaming\qutebrowser\config\config.py has been loaded
Uptime: 0:16:41

**Does the bug happen if you start with `--temp-basedir`?**:
Bug is reproducable with --temp-basedir

**Description**
When dragging qutebrowser window from screen a) with resolution 3840x2160 to screen b) with 1650x1050 the content is slightly off.
Clickable content is lower, the status-bar too.

Screen a): with option --temp-basedir
![grafik](https://user-images.githubusercontent.com/1454499/78483088-9043cd00-7746-11ea-81b5-5f06478e611b.png)

Screen b): same content
![grafik](https://user-images.githubusercontent.com/1454499/78484021-d0a34b00-7746-11ea-82d8-0815b3dfd418.png)

**How to reproduce**

S.o.

Possibly related to Issue #3531
Did not find the option Aero peek or the "composition"-option.

**Comment by The-Compiler** [comment]
I suspect this is some kind of bug in Qt, so I don't think there's much qutebrowser will be able to do.

Does setting `qt.highdpi` to `true` (and then `:restart`) change anything? Can you check whether you see some similar issue with [KDE Falkon](https://www.falkon.org/download/) as well?

**Comment by The-Compiler** [comment]
@d-nnis Any update?

**Comment by d-nnis** [comment]
Hey @The-Compiler forgot to write it down: This behaviour is indeed reproducible with KDE Falkon: The content is slightly off when you dragging the window to a screen with a different resolution.

highdpi to true with a restart shows the same "offset"-behaviour qith qutebrowser.

**Comment by The-Compiler** [comment]
Thanks for the follow-up! I'm closing this then, as I don't think there's anything qutebrowser can do about this. I plan to investigate what's going on exactly one day, but this doesn't really have any priority for me, and I suppose that will happen as part of #3531.

I suspect this is Windows-specific, but I don't have a multi-screen Windows setup where I could try to reproduce this right now I'm afraid.

If this affects Qt/QtWebEngine applications on Windows in general, I suspect this is already reported in the [Qt Bugtracker](https://bugreports.qt.io/) somewhere, but with some 125k tickets in total, it can be hard to find the right one sometimes :laughing: 

I plan to release qutebrowser v1.10.2 with Qt 5.14.2 somewhen this or next week - if you're lucky, something improved there. If not, Qt 5.15 (scheduled for mid-May) might be worth another try.

**Comment by d-nnis** [comment]
Thank you!
