### ISSUE TITLE
Cannot open pdf file:

### ISSUE THREAD

**Issue by ThomasLiA** [qutebrowser/qutebrowser#5341]
I cannot download pdf files from projecteuclid.

The problem occurs, e.g., in case of the button "PDF File" on https://projecteuclid.org/euclid.rmjm/1250126649. When following this link, I am prompted to download some xml file, but not the pdf.

The behaviour is the same when starting without a customised configuration file.

Any help would be appreciated.

**Version info**:
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Comment by The-Compiler** [comment]
See [[QTBUG-78114] [REG 5.13] PDF files are downloaded twice - can't download project euclid files - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-78114?jql=text%20~%20euclid)
