### ISSUE TITLE
YouTube player's controls not appearing

### ISSUE THREAD

**Issue by tallero** [qutebrowser/qutebrowser#5345]
**Version info**:
```
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.2
PyQt: 5.14.2

sip: 5.1.2
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.1
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform: Linux-5.6.3-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```
**Does the bug happen if you start with `--temp-basedir`?**:
No, does not happen.

**Description**
Youtube player's controls do not appear.

**How to reproduce**
Open a Youtube URL.

I tried to delete (done backup first) `~/.cache/qutebrowser`, `~/.local/share/qutebrowser/webengine/`, `~/.local/share/qutebrowser/cookies`.

**Comment by The-Compiler** [comment]
Can you show `:open qute://configdiff` please?

**Comment by lfos** [comment]
Enabling `content.canvas_reading` fixed it for me.

**Comment by WlarusFromDaSpace** [comment]
Firefox seems to also have problems related to youtube controlls. https://bugzilla.mozilla.org/show_bug.cgi?id=1628947
Maybe these two are related?

**Comment by tallero** [comment]
I woke up today and everything was working again. Thanks for the tips, anyway.

OT: what about the recent QT announcement? Do I need to search for alternatives?

**Comment by The-Compiler** [comment]
> OT: what about the recent QT announcement? Do I need to search for alternatives? It would be really sad, I really appreciate qute.

Right now it's basically [what KDE says](https://mail.kde.org/pipermail/kde-community/2020q2/006098.html) vs. [what Qt says](https://www.qt.io/blog/qt-and-open-source). I've asked both sides for clarification ([KDE](https://mail.kde.org/pipermail/kde-community/2020q2/006121.html), [Qt](https://lists.qt-project.org/pipermail/interest/2020-April/034891.html)) and I'm waiting to see how things turn out. Until there's something clear on the table, there isn't much for me to comment on. As soon as that happens, I'll send out an announcement via the usual channels (like the [qutebrowser-announce mailinglist](https://lists.schokokeks.org/mailman/listinfo.cgi/qutebrowser-announce) and [Reddit](https://www.reddit.com/r/qutebrowser/)). Right now, all we can do is wait and hope for the best.

Also, I'd like to avoid using this issue for more discussion about that topic - if people would like to discuss, please do so on e.g. Reddit.

**Comment by tallero** [comment]
Ok. Meantime the issue re-appeared on itself.

**Comment by The-Compiler** [comment]
So, what about your `qute://configdiff`? Do you have `content.canvas_reading` set to `false`?

**Comment by tallero** [comment]
Mmmh, apparently I disabled that option the other day when I was trying to enable mpv autoplay as a workaround for the problem. 

Just disabled it and it works again! Sorry for the waste of time!
