### ISSUE TITLE
Keep tabs showing up until release all keys when tabs.show is set to 'switching'

### ISSUE THREAD

**Issue by Yrds** [qutebrowser/qutebrowser#5346]
The Problem:

tabs.show_switching_delay is helping a lot to keep tabs showing when looking for tabs, but sometimes there is a dozen of tabs and it's hard to have a exact value to 'tabs.show_switching_delay' option in this cases that theres is no need to trigger tabs again.

The solution:

Create an option to tabs.show_switching_mode with options `delay` and `key_release`.
The `release_key` value is to keep tabs showing up until release the bind key for switching tabs.
For example, pressing Shift+J to switch a tab -> keeps tabs showing until release Shift.

My concerns about this solution:

This feature could not be useful for people that use only one key binding for switching tabs, so i think this idea needs some brainstorming

**Comment by ninewise** [comment]
Dupplicate of #3141. Same concern was raised there, no solution found.
