### ISSUE TITLE
Performance in USB linux installation

### ISSUE THREAD

**Issue by cristoferfb** [qutebrowser/qutebrowser#5360]
Hi, I use Alpine linux from a USB, I am notice some performance stucks when a page is loading, I am asking for know if Qutebrowser does some I/O to file while a page is loading and if it can be avoid for get work directly in memory. I notice too a more common frecuency of render crashes.

**Version info**: https://paste.the-compiler.org/view/f3e974b3

**Comment by user202729** [comment]
Yes, the history database is updated whenever a page is loaded. Also there are some cache (`~/.cache/qutebrowser`, `~/.local/share/qutebrowser/webengine`, `

You can try moving/linking some directories/files to /tmp or a persistent ram disc.

**Comment by jgkamat** [comment]
See #4545

**Comment by The-Compiler** [comment]
Yep, #4545 will probably help with the disk I/O.

As for the renderer process crashes, IIRC QtWebEngine is rather unstable with musl libc (which is unsupported upstream), despite [a lot of patching](https://git.alpinelinux.org/aports/tree/community/qt5-qtwebengine?h=master) done from Alpine's side.

There are various other issues in QtWebEngine which could cause those, though - see #5313 (wayland-specific) or #5279 (related to service workers).
