### ISSUE TITLE
Allow to cycle through tabs

### ISSUE THREAD

**Issue by xaltsc** [qutebrowser/qutebrowser#5366]
As far as I know, no `:tab-*` command allow to cycle through tabs, that is, when using `:tab-next` on the last tab, I would like to be able to go to the first one, or when using `:tab-prev` on the first, go to the last one.

This could be either implemented as an option for `:tab-next`/`:tab-prev` or as a motion for `:tab-focus`.

**Comment by arza-zara** [comment]
`:set tabs.wrap true`

**Comment by The-Compiler** [comment]
Note that that's the default, so if those commands don't wrap around, you probably set that to `false` at some point.

**Comment by xaltsc** [comment]
My bad, thanks!
