### ISSUE TITLE
dictcli.py uses wrong directory: /usr/share/qt5

### ISSUE THREAD

**Issue by andys8** [qutebrowser/qutebrowser#5367]
**Version info**:
https://paste.the-compiler.org/view/d918a777

**Description**

This commit says the `dictcli.py` should use the data dir.

https://github.com/qutebrowser/qutebrowser/commit/663d1a4d2f2f9d1797a8bb3c745e954f9f3ab4ab

> On Qt 5.10 or newer, dictionaries are now read from the qutebrowser data
  directory (e.g. `~/.local/share/qutebrowser`) instead of `/usr/share/qt`.
  Existing dictionaries are copied over.

Running `dictcli.py` tries to create file in `/usr/share/qt5/qtwebengine_dictionaries` but should create file in `~/.local/share/qutebrowser`. Qutebrowser will not find it and warn because of missing dictionary. Copying the directory to data dir solves the issue (workaround).
```
./scripts/dictcli.py install en-US
Installing en-US: English (United States)
Downloading https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries.git/+/master/en-US-9-0.bdic?format=TEXT
[Errno 13] Permission denied: '/usr/share/qt5/qtwebengine_dictionaries/en-US-9-0.bdic'
```

Not sure about `QTWEBENGINE_DICTIONARIES_PATH` though. It's empty on my system.

**How to reproduce**

Run `./scripts/dictcli.py install en-US`

Relates to #4003

**Comment by The-Compiler** [comment]
It looks like you have a virtualenv with a newer Qt, but are using the system Python/Qt to run the script. You will need to run it with `/home/as/Dev/repository/qutebrowser/.venv/bin/python3` instead.

**Comment by andys8** [comment]
Oh, thanks. Can confirm `.venv/bin/python3 ./scripts/dictcli.py install en-US` is working.

For ubuntu/debian users it would be great if there would be an easier installation (ppa) where webengine is not super old (chromium 55) and an easier way to install dictionaries (#4003).

**Comment by The-Compiler** [comment]
Agreed. However, distribution packages are done by people other than me - so far, nobody has stepped up to maintain a PPA so far.

**Comment by The-Compiler** [comment]
FWIW I pushed a [commit](https://github.com/qutebrowser/qutebrowser/commit/d07773784006337388ad6ab9bf45ac743b95d9ec) which improves the error message to suggest using the virtualenv's Python.
