### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by davidmogar** [qutebrowser/qutebrowser#5372]
**Version info**:
qutebrowser v1.10.2
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

Notifications are not displayed even when I'm allowing them to show through the dialog. Also, answers to this dialog apply only to the current session and I have to allow them again (Y) next time I run qutebrowser, or allow notifications for every single site with `content.notifications`.

**Comment by The-Compiler** [comment]
> Notifications are not displayed even when I'm allowing them to show through the dialog.

Notifications are displayed by Qt using a system tray widget - I'm guessing you don't have a system tray running.

> Also, answers to this dialog apply only to the current session and I have to allow them again (Y) next time I run qutebrowser, or allow notifications for every single site with `content.notifications`.

If you use a capital `Y`, the answer will be remembered in `autoconfig.yml` and you won't need to do that manually. If you have a `config.py`, you'll need to [load autoconfig.yml from it](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#loading-autoconfigyml) for that to happen.
