### ISSUE TITLE
Reduce CPU usage

### ISSUE THREAD

**Issue by maximbaz** [qutebrowser/qutebrowser#5375]
**Version info**:

```
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.2
PyQt: 5.14.2

sip: 5.1.2
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.4.456 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform: Linux-5.6.4-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/maximbaz/.cache/qutebrowser
config: /home/maximbaz/.config/qutebrowser
data: /home/maximbaz/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/maximbaz/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

I'd like to explore the possibility of reducing CPU usage by qutebrowser. From #4214 I understand that usage by QtWebEngine and usage by the python process are more or less unrelated, and we can mostly work on optimizing the python process.

I noticed that python process takes up a considerable CPU consumption, averaging to ~10% (depending on the website) when I'm idling, not doing anything to the page, not scrolling, there is no dynamic content - and that feels like maybe a bit too much.

-----

To start on this, I might have found a perfect example where CPU usage is extremely high: 

https://yourbias.is

![image](https://user-images.githubusercontent.com/1177900/79902330-9b1e8300-8411-11ea-8a08-6048f3e77992.png)

To be honest, even QtWebEngine eats a lot more comparing to Chromium:

![image](https://user-images.githubusercontent.com/1177900/79902085-29463980-8411-11ea-8a25-cdd548c8d657.png)

Ideally I would like us to address both processes, but I can understand that there isn't much we can do here to optimize QtWebEngine itself.

But even if website is doing something funky, why python process eats so much CPU? It isn't responsible for page rendering, is it?

I tried to run `./scripts/dev/run_profile.py` from the cloned repo, but it doesn't tell me much, or I dont know what to look for :)

Any pointers and thoughts are appreciated!

![image](https://user-images.githubusercontent.com/1177900/79902887-7aa2f880-8412-11ea-951b-d2060a6508d2.png)

![image](https://user-images.githubusercontent.com/1177900/79902951-94dcd680-8412-11ea-891c-d1e5ecd54e85.png)

**Comment by The-Compiler** [comment]
I doubt there's anything qutebrowser can do here:

With [KDE Falkon](https://www.falkon.org/) (another QtWebEngine-based browser), the CPU usage looks very similar to qutebrowser:

![image](https://user-images.githubusercontent.com/625793/79904196-9dcea780-8414-11ea-8e33-c5cd84a98a2f.png)

![image](https://user-images.githubusercontent.com/625793/79904468-f9993080-8414-11ea-9924-8ce0b8392c2e.png)

With Chromium, that CPU usage is in the GPU process instead, which indeed (as far as I know) is part of the main/GUI process with QtWebEngine:

![image](https://user-images.githubusercontent.com/625793/79904610-3cf39f00-8415-11ea-8f42-1cc5859f0e8f.png)

Sure, there's a small difference to QtWebEngine there, but that's something QtWebEngine would need to solve. Given that the website clearly is doing something funky, I'm not sure it's worth to even report it.

Your profile also confirms that there's almost no Python code running, at least after initialization is done.

**Comment by maximbaz** [comment]
Could you clarify why python process is showing up as 50% in htop, if there is almost no python code running?

**Comment by The-Compiler** [comment]
Because that's just the main/GUI process, similar to the Chromium browser process. There's Python running there, and there's Qt's C++ code running there. While things like layouting etc. are done in the subprocesses (like with Chromium), the actual final rendering is done by Qt in that process.

**Comment by jgkamat** [comment]
I would disagree personally with that assesment, qutebrowser adds significant overhead compared to both falkon and chromium. I tried running falkon, qb, and chromium on that site:

![1587497740](https://user-images.githubusercontent.com/4349709/79906536-d0ed4880-83cc-11ea-878b-ee18d5137f89.png)

qutebrowser: 15.1 + 11.1 + 10.5 -> 36.7%
falkon: 11.8%
chromium: 6.5 + 5.9 + 2.6 = 15%

chrome is probably a little off here because it's from another distro and I have ~10 other tabs open, but it dosen't change the outcome too much.

Moreover, there *is* python code always running, which is mostly in the event filter:
```
7   19288  19288  4.544    -> /usr/lib64/python3.6/site-packages/qutebrowser/browser/eventfilter.py.eventFilter
7   19288  19288  4.544    <- /usr/lib64/python3.6/site-packages/qutebrowser/browser/eventfilter.py.eventFilter
7   19288  19288  4.544    -> /usr/lib64/python3.6/site-packages/qutebrowser/keyinput/eventfilter.py.eventFilter
7   19288  19288  4.544    <- /usr/lib64/python3.6/site-packages/qutebrowser/keyinput/eventfilter.py.eventFilter
7   19288  19288  4.544    -> /usr/lib64/python3.6/site-packages/qutebrowser/keyinput/eventfilter.py.eventFilter
7   19288  19288  4.544    <- /usr/lib64/python3.6/site-packages/qutebrowser/keyinput/eventfilter.py.eventFilter
7   19288  19288  4.544    -> /usr/lib64/python3.6/site-packages/qutebrowser/browser/eventfilter.py.eventFilter
7   19288  19288  4.544    <- /usr/lib64/python3.6/site-packages/qutebrowser/browser/eventfilter.py.eventFilter
```

**Comment by jgkamat** [comment]
Actually, one of the QtWebEngine processes is from falkon too, so qutebrowser and falkon are much closer:

![1587498640](https://user-images.githubusercontent.com/4349709/79907618-c16eff00-83ce-11ea-9587-6ed0b1097c65.png)
![1587498627](https://user-images.githubusercontent.com/4349709/79907621-c2079580-83ce-11ea-97be-4b183c6e4520.png)

But from my testing, qutebrowser is still taking more CPU than falkon, and much more than chrome.

**Comment by The-Compiler** [comment]
@jgkamat It looks like you're attributing Falkon's QtWebEngineProcess (the highlighted one, guessing from the PID) to qutebrowser which would result in that conclusion, which then would be wrong however :wink: Also, the Chromium browser process doesn't seem to be listed at all in your screenshot, though maybe that's not relevant.

If my guess based on the PID is right, that'd be:

qutebrowser: 11.1 + 10.5 -> 21.6%
falkon: 11.8 + 15.1 -> 26.9%
chromium: 6.5 + 5.9 + 2.6 + ? = 15% (?)

> Moreover, there is python code always running, which is mostly in the event filter:

I haven't said there's no Python code running. Here's what the event filter does when e.g. moving the mouse:

```
[...]qutebrowser/keyinput/eventfilter.py:88    line         try:
[...]qutebrowser/keyinput/eventfilter.py:89    line         if not self._activated:
[...]qutebrowser/keyinput/eventfilter.py:91    line         if not isinstance(obj, QWindow):
[...]qutebrowser/keyinput/eventfilter.py:94    line         return False
```

When completely idle, I see that happening around once all 5-10 seconds. Surely that can't be the cause for 20-30% CPU usage, especially when the same is happening in a different codebase as well :wink:

**Comment by jgkamat** [comment]
> When completely idle, I see that happening around once all 5-10 seconds. Surely that can't be the cause for 20-30% CPU usage, especially when the same is happening in a different codebase as well wink

[out.txt](https://github.com/qutebrowser/qutebrowser/files/4512359/out.txt)


For me at least, I'm getting at least 1000 calls per second on those functions (it's probably actually significantly higher than this, as turning on profiling slows down those calls). And considering each one of these calls is waking up the python interpreter (and the fact that even trivial operations in the interpreter are very slow), I wouldn't be surprised if it made a difference of 5-10% on idle.

**Comment by The-Compiler** [comment]
@jgkamat I split that off into #5376 because that's not something connected to the website mentioned by @maximbaz. Would be great if you could answer my questions there.

> I wouldn't be surprised if it made a difference of 5-10% on idle.

Yet in your screenshot above, Falkon seems to be taking 5% more CPU than qutebrowser, no?

**Comment by jgkamat** [comment]
> Yet in your screenshot above, Falkon seems to be taking 5% more CPU than qutebrowser, no?

It seems like that page has animations occurring every so often, and those animations seem to be triggering to the CPU spikes, so when you take a sample can cause a lot of variation. In order to smooth that out somewhat I measured cpu over a minute and averaged it with pidstat:

[out.txt](https://github.com/qutebrowser/qutebrowser/files/4512461/out.txt)

```
Average:      UID       PID    %usr %system  %guest   %wait    %CPU   CPU  Command
Average:     1000      1324   13.87    2.98    0.00    0.04   16.85     -  qutebrowser
Average:     1000      1574   17.93    1.39    0.00    0.02   19.33     -  QtWebEngineProc
Average:     1000      1635   12.02    3.13    0.00    0.07   15.15     -  falkon
Average:     1000      1827   19.00    1.22    0.00    0.02   20.22     -  QtWebEngineProc
```

qutebrowser: 16.85 + 19.33 = 36.18
falkon: 15.15 + 20.22 = 35.37

However, it still seems like the falkon->chromium savings (at the time of writing at least) is much much larger than the qutebrowser->falkon savings.

**Comment by maximbaz** [comment]
For reference, I went through the [list of chromium flags](https://peter.sh/experiments/chromium-command-line-switches/) and added to qutebrowser those that seem to be relevant to GPU processing; not sure how many of them are actually supported, but things are a lot more "greener" on `chrome://gpu` and CPU impact on yourbias.is is noticeably lower than 50% / 50%.

![image](https://user-images.githubusercontent.com/1177900/79916679-6dddcf00-8429-11ea-808f-8fe057ca5a08.png)


```
c.qt.args += [
    "ignore-gpu-blacklist",
    "enable-accelerated-2d-canvas",
    "enable-gpu-memory-buffer-video-frames",
    "enable-gpu-rasterization",
    "enable-native-gpu-memory-buffers",
    "enable-oop-rasterization",
    "enable-zero-copy",
]
```

**Comment by toofar** [comment]
Good point, I also have "ignore-gpu-blacklist", "enable-gpu-rasterization", "enable-native-gpu-memory-buffers", "num-raster-threads=4" which I don't remember setting. And the nvidia proprietary graphics driver. And config.summary for webengine says nothing much interesting
```
Qt WebEngine Build Tools:
  Use System Ninja ....................... yes
  Use System Gn .......................... no
  Jumbo Build Merge Limit ................ 8
  Developer build ........................ no
  QtWebEngine required system libraries:
    fontconfig ........................... yes
    dbus ................................. yes
    nss .................................. yes
    khr .................................. yes
    glibc ................................ yes
  QtWebEngine required system libraries for qpa-xcb:
    x11 .................................. yes
    libdrm ............................... yes
    xcomposite ........................... yes
    xcursor .............................. yes
    xi ................................... yes
    xtst ................................. yes
  Optional system libraries used:
    re2 .................................. no
    icu .................................. no
    libwebp, libwebpmux and libwebpdemux . no
    opus ................................. no
    ffmpeg ............................... no
    libvpx ............................... no
    snappy ............................... no
    glib ................................. yes
    zlib ................................. no
    minizip .............................. no
    libevent ............................. no
    jsoncpp .............................. no
    protobuf ............................. no
    libxml2 and libxslt .................. no
    lcms2 ................................ no
    png .................................. no
    JPEG ................................. yes
    harfbuzz ............................. no
    freetype ............................. yes
Qt WebEngineCore:
  Embedded build ......................... no
  Full debug information ................. no
  Pepper Plugins ......................... yes
  Printing and PDF ....................... yes
  Proprietary Codecs ..................... yes
  Spellchecker ........................... yes
  Native Spellchecker .................... no
  WebRTC ................................. yes
  Geolocation ............................ yes
  WebChannel support ..................... yes
  Use v8 snapshot ........................ yes
  Kerberos Authentication ................ no
  Extensions ............................. yes
  Support qpa-xcb ........................ yes
  Use ALSA ............................... yes
  Use PulseAudio ......................... no
```

**Comment by The-Compiler** [comment]
I split that off into its own issue as well: [Investigate Chromium GPU flags · Issue #5378 · qutebrowser/qutebrowser](https://github.com/qutebrowser/qutebrowser/issues/5378)

In general, I don't feel confident with blindly enabling them by default in qutebrowser - there's probably a good reason for them being set in QtWebEngine/Chromium (most of them override Chromium defaults!). However, it might be good to try to understand (perhaps with some help from QtWebEngine upstream) what they do exactly, and if any of those can be safely enabled by default.

**Comment by duarm** [comment]
> For reference, I went through the [list of chromium flags](https://peter.sh/experiments/chromium-command-line-switches/) and added to qutebrowser those that seem to be relevant to GPU processing; not sure how many of them are actually supported, but things are a lot more "greener" on `chrome://gpu` and CPU impact on yourbias.is is noticeably lower than 50% / 50%.
> 
> ![image](https://user-images.githubusercontent.com/1177900/79916679-6dddcf00-8429-11ea-808f-8fe057ca5a08.png)
> 
> ```
> c.qt.args += [
>     "ignore-gpu-blacklist",
>     "enable-accelerated-2d-canvas",
>     "enable-gpu-memory-buffer-video-frames",
>     "enable-gpu-rasterization",
>     "enable-native-gpu-memory-buffers",
>     "enable-oop-rasterization",
>     "enable-zero-copy",
> ]
> ```

Out of topic, but I encourage everyone to try these flags if the perfomance is not good, opening 4 tabs on some sites, I suspect ad heavy ones, reduced qutebrowser's fps to 1, these flags help a ton
