### ISSUE TITLE
Proxy auto switch

### ISSUE THREAD

**Issue by davidmogar** [qutebrowser/qutebrowser#5381]
I use SwitchyOmega extension on Chrome to be able to define a socks5 proxy. One good thing I get with this extension is the possibility of using an specif proxy fora host wildcard. That way, all the traffic to urls pointing to my work domain go through the defined proxy.

Is anything like this possible in qutebrowser? If yes, how? If not, any smart alternative?

**Comment by The-Compiler** [comment]
Right now, that's not possible - see #2492 and #3636.

The only thing you could do right now is commenting out the `QNetworkProxyFactory.setApplicationProxyFactory` calls in `qutebrowser/browser/network/proxy.py` and set the `auto_proxy` environment variable to a [PAC](https://en.wikipedia.org/wiki/Proxy_auto-config) file. That's not supported though, and will break other things (like setting the `content.proxy` setting without the need for a restart).
