### ISSUE TITLE
Stops visually updating on a virtual linux machine

### ISSUE THREAD

**Issue by Irubataru** [qutebrowser/qutebrowser#5383]
**Version info**:
```
qutebrowser v1.10.2
Git commit: ec3a319a6 (2020-04-22 13:20:49 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.7.5
PyQt: 5.14.2

sip: 5.1.2
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform plugin: xcb
Platform: Linux-5.3.0-46-generic-x86_64-with-Ubuntu-19.10-eoan, 64bit
Linux distribution: Ubuntu 19.10 (ubuntu)
Frozen: False
Imported from /home/glesaaen/.usr/qutebrowser/qutebrowser
Using Python from /home/glesaaen/.usr/qutebrowser/.venv/bin/python3
Qt library executable path: /home/glesaaen/.usr/qutebrowser/.venv/lib/python3.7/site-packages/PyQt5/Qt/libexec, data path: /home/glesaaen/.usr/qutebrowser/.venv/lib/python3.7/site-packages/PyQt5/Qt

Paths:
cache: /home/glesaaen/.cache/qutebrowser
config: /home/glesaaen/.config/qutebrowser
data: /home/glesaaen/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Autoconfig loaded: yes
Config.py: /home/glesaaen/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:21
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
So I have ubuntu installed on a virtualbox using awesome as my window manager and I have a lot of issues with qutebrowser simply stopping to render update pages. It generally happens when I have too many tabs open (more than 8 so not that many), and then I either have to close the browser and repoen it, close some tabs and force reopen the one I want to use (yank the url, close the tab, open a new tab and paste the url). When it stops rendering it either goes completely blank, or it stops updating when I scroll even though the scroll counter is increasing/decreasing.

I also get artefacts like these
![screenshot](https://user-images.githubusercontent.com/5611071/80203688-d85c5e00-8627-11ea-8080-4ce6d77c51a9.png)

I understand that this can be an issue with the VM, that I do not have enough video memory etc (I set it to virtualbox max), but since I do not see these issues with e.g. firefox I was wondering if there was something else going on.

I tried both installing qutebrowser from apt and with cloning the repo and using virtualenv (which is what I am on now), but I am seeing the same behaviour.

**Comment by The-Compiler** [comment]
That sounds more like an issue with either QtWebEngine or Virtualbox, and probably isn't something qutebrowser can fix.

Can you try if you see something similar after using [KDE Falkon](https://www.falkon.org/) for a while as well? Also, could you try the three different settings of `qt.force_software_rendering` and see if they change anything (note they require a restart of qutebrowser)?

**Comment by Irubataru** [comment]
So I tried setting `qt.force_software_rendering` and it got a lot better immediately. It didn't seem to matter which one I chose, as long as I chose one of them. Does that make sense? I only did a quick test tabbing around with 10+ tabs, and when I set it back to None and reopened it froze within seconds.

I wasn't sure where to ask because as far as I understand qutebrowser does not handle the rendering, but I am very happy I asked here anyway. I'd happily provide logs etc if there is anything else you want to know, but for now it seems to be working great. Thanks a lot! :heart:

**Comment by The-Compiler** [comment]
Yeah, this would probably be something for [Qt's bugtracker](https://bugreports.qt.io/), but to report it there, you'd probably first need to reproduce it with the "simplebrowser" example that comes with QtWebEngine.

The setting values all work a little bit differently internally - I think setting it to `chromium` probably has the smallest performance impact, but I'm not sure.

Closing this as I don't think there's anything qutebrowser can do here - glad to hear that the setting has helped though! :tada:
