### ISSUE TITLE
visual hints

### ISSUE THREAD

**Issue by xcapegoat** [qutebrowser/qutebrowser#5384]
Visual hints show a hint for all sentences (all text) on the page, from which one sentence may be selected in visual mode.

I understand you're over loaded with requests, but unless I need to RTM or improve my method somehow, the method to get a visual selection feels slow, for example: 

-I can search, but this may if I'm not careful throw me to the top of the page (distracting) before pressing n to return, where it's not necessarily certain how many "next searches" I'll have to do.

-caret mode stats reliably in qutebrowser, but it sometimes starts in a place which it seems to get stuck on.

Tridactyl has visual hint mode (perhaps in the beta). I moved here as it seems more stable than my last experience with it many years ago. And the fast completion. I love this browser.

**Comment by The-Compiler** [comment]
(mostly) duplicate of #1453
