### ISSUE TITLE
Scroll buffer list with j and k

### ISSUE THREAD

**Issue by xcapegoat** [qutebrowser/qutebrowser#5387]
Sometimes I want to just scroll lists without holding a modifier or typing to search. Is this possible in qutebrowser? (Theoretically?)

I've thought of using dmenu or rofi. That is another thing, it would be good if the tabs switched as you went through the list. But I don't think that can be done with dmenu etc. Thanks for reading.

**Comment by The-Compiler** [comment]
> Scroll buffer list with j and k

You could `:bind j tab-next` (but would then find another keybinding for scrolling).

> I've thought of using dmenu or rofi.

You'd still need to type something to search there, though? I know of various people who used something like that in a script which runs `:session-save` and interprets the resulting YAML, but I don't know of a ready-made script off-hand.

> That is another thing, it would be good if the tabs switched as you went through the list.

I assume you mean with the `:buffer` completion? See #2733.

**Comment by xcapegoat** [comment]
I actually made a script last night to pipe the list from session-save to dmenu, will have a go with that later.

I meant buffer completion for using the binds as well. Setting j and k to tab next will only switch buffers in normal mode, and not the buffer completion list (is that its name?) i.e. :buffer. 

I was wondering if it's a possibility code wise, or if its somehow blocked. I am not an experienced programmer, but sometimes I try to to add little bits to projects, with varying success.

**Comment by The-Compiler** [comment]
You could bind those keys as well without any code changes, but then how are you going to enter `j` and `k` in the commandline?

**Comment by xcapegoat** [comment]
Ah, so I can. I had read "command: Entered when pressing the : key in order to enter a command. **Note that single keys can’t be bound in this mode.**" Perhaps I've misunderstood.

Maybe create a userscript that binds the j k keys (to completion-item-focus history next/prev) and opens the buffer list, and another to do :open after rebinding the keys to defaults?
