### ISSUE TITLE
I can't play drm content with qutebrowser, Please help me

### ISSUE THREAD

**Issue by supremew** [qutebrowser/qutebrowser#5388]
qutebrowser v1.10.2
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.2
PyQt: 5.14.2

sip: 5.1.2
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: 2.4.456 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
Platform: Linux-5.6.6-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/archlinux/.cache/qutebrowser
config: /home/archlinux/.config/qutebrowser
data: /home/archlinux/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:09:37

I have two computers, I can play drm content in one after I install the chromium-widevine from the AUR. But in the other one I can't play after I install the chromium-widevine.

**Comment by supremew** [comment]
Well, I solved the problem by accident. After I set the **user_Agent** to the default value of qutebrowser ('Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}'), I solved this problem.

**Comment by logicalbhanu** [comment]
> Well, I solved the problem by accident. After I set the **user_Agent** to the default value of qutebrowser ('Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}'), I solved this problem.

could you tell me how you have install chromium-widevine in your system, i am using qutebrowser in my virtual environment in linux mint 20.1.

**Comment by The-Compiler** [comment]
@logicalbhanu If you have Qt installed in a virtualenv, you don't have any proprietary codec support, so I doubt Widevine will work.
