### ISSUE TITLE
Tab switching improvement

### ISSUE THREAD

**Issue by atchim** [qutebrowser/qutebrowser#5392]
My request is for a better system for switching tabs. Currently I can only switch between 2 tabs. I was thinking that switching tabs could be like in Vivaldi browser. Let me show an example.

I open the browser with only one tab (tab 'a'). Then the scenario is like this:

```
                       ↓
tab_switching_stack = [a]
```

Consider the down arrow meaning the showed tab and the last element of the stack beeing the focused one. So if I press and release Control + Tab it would do nothing because there is only one tab.

Following with the example, if open another tab (tab 'b') not beeing in background (let's suppose I pressed Shift + O) then the scenario would be like this:

```
                          ↓
tab_switching_stack = [a, b]
```

So if I press and release Contrl + Tab as tab 'b' is focused, it would focus tab 'a' and the scenario would be like this:

```
                          ↓
tab_switching_stack = [b, a]
```

Now let's suppose that I open another tab (tab 'c'). So the focus gone to tab 'c' and the scenario would be like this:

```
                             ↓
tab_switching_stack = [b, a, c]
```

This way, if I press and hold Contrl and if I also press Tab then the showed (not the focused) tab would be tab 'a',
```
                          ↓
tab_switching_stack = [b, a, c]
```
and if I (still holding Control) press Tab again the showed screen would be tab 'b',
```
                       ↓
tab_switching_stack = [b, a, c]
```
and I if I (still holding Control) press Tab once again the sowed tab would be back to tab 'c'.
```
                             ↓
tab_switching_stack = [b, a, c]
```

Continuing with the example, lets say that the Control key is still pressed (this is, it wasn't been released), if I press Tab twice
```
                       ↓
tab_switching_stack = [b, a, c]
```
and then I release the Control key then the tab focused would be tab 'b' and the scenario would be like this:

```
                             ↓
tab_switching_stack = [a, c, b]
```

As you can see it cycles around tabs. The tab switching stack keeps intact while the Control key is not released once it was pressed and the user is able look around tabs until choose one and release the Control key. Is important to say that may some users won't want to see tabs while pressing Tab. In this case would be nice to have an option to don't show tabs while cycling and consequently the tab just will be shown when the user release the Control key.

An important case is if the user open a tab in background. This way the background tab won't enter in the tab switching stack but instead it would go to background tabs stack. For example, let's say that we have tabs 'a', 'c' and 'b' and both were already focused, and then we open a tab 'd' in background. Then the scenario would be like this:

```
                             ↓
tab_switching_stack = [a, c, b]

background_tabs_stack = [d]
```

Once when tab 'd' get focused then it would enter in the tab switching stack.

I think that this cycling tabs system would ease the navigation experience of a lot of users. Note: my installed version of qutebrowser is 1.8.3.

**Comment by toofar** [comment]
This was implemented recently: https://github.com/qutebrowser/qutebrowser/pull/4801
You need to change the bindings of <Ctrl+Tab> and <Ctrl+Shift+Tab> to be "tab-focus stack-prev" and "tab-focus stack-next".

The one difference from what you describe is that
> The tab switching stack keeps intact while the Control key is not released once it was pressed and the user is able look around tabs until choose one and release the Control key.

Isn't implemented due to how key event dispatching is implemented. The tab stack gets modified as you cycle it.

**Comment by atchim** [comment]
Sorry for posting this. I searched if someone had already posted something similar to this proposal, but I didn't find it. Also the version I'm using is old because I couldn't install it from source (even following the installation tutorial) and so I'm using the most recent version of qutebrowser in Funtoo Linux which is 1.8.3.
