### ISSUE TITLE
AltGr-Combos not working on german keyboard-layout in insert-mode (1.11.0)

### ISSUE THREAD

**Issue by mborejdo** [qutebrowser/qutebrowser#5399]
**Version info**:
qutebrowser v1.11.0
Git commit: 6cb0cfc85 (2020-04-27 16:29:25 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
qutebrowser 1.11.0 (windows 10) does not allow entering some special character-combinations using AltGr on my german keyboard-layout. Eg. trying to Enter "@" (AltGr + q) does nothing. using "@" in commandline-mode works as expected

**How to reproduce**
Start qutebrowser 1.11.0 on windows 10 with a german keyboard-layout and try to enter "@" in insert-mode

qutebrowser 1.10.0 works as expected and allows using AltGr.

**Comment by The-Compiler** [comment]
Can you check if you see the same behavior with [KDE Falkon}(https://www.falkon.org/) please?

**Comment by The-Compiler** [comment]
Ah, looks like this issue and fix:

- [[QTBUG-83710] Unable to input some character in web view - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-83710)
- [Fix AltGr on Windows (Iaf5a33c0) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/299142)

Can you check whether `:set qt.force_platform windows:altgr` and `:restart` fixes things?

**Comment by mborejdo** [comment]
setting the value works around the problem. I can happily type @ again :-)

**Comment by The-Compiler** [comment]
Thanks for testing! I'm guessing the fix will make it to Qt 5.14.1, but should be easy to have a workaround until then. Just not sure what else that `:altgr` option changes, but I'll try to find out.

**Comment by The-Compiler** [comment]
Hm, it only seems to make Qt set the `AltGr` modifier in those cases, but I'm not sure how that influences e.g. qutebrowser's own keybindings. I'll need to think about it some more.

**Comment by Figuera** [comment]
I am having the same problem but the proposed workaround is not working for me.

Typing in the command line altgr works as normal, in any input box or for qutebrowser binding altgr does nothing.

**Comment by The-Compiler** [comment]
@Figuera Can you show your `:version` information?

**Comment by Figuera** [comment]
qutebrowser v1.13.0
Git commit: 74ba8f3dc-dirty on HEAD (2020-06-26 08:31:20 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.7.7
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: 2.4.456 (bundled)
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QWindowsVistaStyle
Platform plugin: windows
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 436.30
Platform: Windows-10-10.0.19041-SP0, 64bit
Frozen: True
Imported from D:\apoem\AppData\Local\qutebrowser\qutebrowser
Using Python from D:\apoem\AppData\Local\qutebrowser\qutebrowser.exe
Qt library executable path: D:/apoem/AppData/Local/qutebrowser/PyQt5/Qt/bin, data path: D:/apoem/AppData/Local/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.19041, SP0, 

Paths:
cache: C:\Users\apoem\AppData\Local\qutebrowser\cache
config: C:\Users\apoem\AppData\Roaming\qutebrowser\config
data: C:\Users\apoem\AppData\Roaming\qutebrowser\data
runtime: C:\Users\apoem\AppData\Local\Temp\qutebrowser

Autoconfig loaded: no
Config.py: C:\Users\apoem\AppData\Roaming\qutebrowser\config\config.py has been loaded
Uptime: 11:20:09

**Comment by The-Compiler** [comment]
The bug fix above ended up being merged in Qt 5.15.1, so I'm guessing when that's released (planned for August) this issue will go away. Closing this, as apparently the workaround doesn't work for everyone and an upstream fix is coming soon.
