### ISSUE TITLE
qute-pass supplies name/domain rather than username

### ISSUE THREAD

**Issue by karlh626** [qutebrowser/qutebrowser#5400]
**Version info**:
qutebrowser v1.11.0
Git commit: 8fed0ed6e-dirty (2020-04-27 15:51:41 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2
CPython: 3.7.7
PyQt: 5.14.2

sip: 5.1.2
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: 2.3.200 (bundled)
sqlite: 3.31.1
QtNetwork SSL: Secure Transport, macOS Mojave (10.14)

Style: QMacStyle
Platform plugin: cocoa
Platform: Darwin-18.7.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.14.6, x86_64

**Description**
In the past I used *qute-pass* on my linux system without problems.
Recently, I setup *qute-pass* on my osx laptop by binding ",l" to "spawn --userscript <path>/qute-pass"

When I try to use qute-pass to fill in username and password info using information provided by pass, it supplies the name of the password store (url) rather than the username inside of that password file then it enters the password correctly into the second (password field) like it should.

In OSX I am using the precompiled binary but the latest version of qute-pass located in the repository.

The fact that it is entering the correct password into the 2nd field leads me to believe that qute-pass is interacting with pass without a problem.

I am just not sure why it is not retrieving the username from the same location.  The pass file containing this information is using the following format:

```
<password>
----
username: <username>
password: <password>
url: <url>
```
I have tried switching between using "*username:*" and "*user:*" neither of which made any difference.

Any insight into what could be causing this would be appreciated.

**Comment by lufte** [comment]
qute-pass assumes you are using a `/domain/username.gpg` style, where the content (or at least the first line) of each file is the password. It looks like your files are named after the domain and not the username. 
I believe you can make it work with your files but you will have to invoke the userscript with some flags. Take a look at the [source code](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-pass) where it explains everything.

**Comment by The-Compiler** [comment]
Thanks @lufte for the explanation!

**Comment by chrisgsadler** [comment]
I have hit the same problem. The pass docs kind of suggest the format above.  I had trouble from the source code working out which switches to apply. Has anyone got this to work? If so, can they supply the switches they used? Thanks!

**Comment by lufte** [comment]
> I have hit the same problem. The pass docs kind of suggest the format above. I had trouble from the source code working out which switches to apply. Has anyone got this to work? If so, can they supply the switches they used? Thanks!

@chrisgsadler: If your file looks like @karlh626's and we assume the name of the file is the domain, something like this works for me: `spawn --userscript qute-pass -U secret -u 'username: (.+)'`.

* `-U secret` tells qute-pass that the username is inside the secret file and not in its path.
* `-u 'username: (.+)'` tells qute-pass what regular expression to use to obtain the username from the file content.

**Comment by chrisgsadler** [comment]
Thank you very much @lufte !  I had got part of the way there but couldn't quite get the perl regex to match properly.  Very much appreciated!

**Comment by The-Compiler** [comment]
I added some docs to explain this to the userscript: 0119f87fc215cf0a81159706e4831feff3f8b2ca
