### ISSUE TITLE
Using :open -s should only ever rewrite a http to https

### ISSUE THREAD

**Issue by zander** [qutebrowser/qutebrowser#5401]
**Version info**:
qutebrowser v1.10.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.7

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**

Using :open -t -s tries to move to https even when the protocol was not http.

**How to reproduce**

Type this: `open -s -t qute://settigns`
and notice how the browser goes to https://settings instead.

The usecase is that you can bind 'o' to `set-cmd-text open -s -t` which would be really nice if it didn't require users specifically typing 'qute://' to go and remove the -s. It could be smart enough to avoid this kind of link not being able to open.

**Comment by The-Compiler** [comment]
Seems like a good idea and was an easy fix, so consider it done! :wink:

**Comment by The-Compiler** [comment]
FWIW, this request lead to me finding out about #5403, so thanks for that! :laughing:
