### ISSUE TITLE
Proxy Server Name Resolution

### ISSUE THREAD

**Issue by gholamifrd** [qutebrowser/qutebrowser#5405]
**Version info**:
qutebrowser v1.10.1
Git commit:
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.2
PyQt: 5.14.2

sip: 5.1.2
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.1
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
When using a MITM proxy (for instance Burp Suite), then if you open the URL `http://burp/` in qutebrowser it won't resolve this host to the actual address which is `http://127.0.0.1:8080`.
I don't know how the other browsers do it but in chromium or firefox it works (domain name `burp` automatically resolves to the said address when proxy is set).
maybe there are other ways to manually resolve this address to desired IP but they require using revesre proxy settings that I believe Burp Suite is already doing so. It would be nice to have the same behaviour as the other browsers since I'd really love to use qutebrowser for pentesting.
BTW, Installing the certificate won't make any difference.
**How to reproduce**
Use Burp Suite as a MITM proxy then navigate to `'http://burp/`

**Comment by The-Compiler** [comment]
Can you test whether you see this in other QtWebEngine browsers such as [KDE Falkon](https://www.falkon.org/) as well?

**Comment by gholamifrd** [comment]
I tested it with Falkon browser and it behaves the same as the qutebrowser.

**Comment by gholamifrd** [comment]
I think I have found what the problem is. other browsers like chromium or firefox send all requests trhough the proxy including local requests. However qutebrowser seems to not send local requests to the proxy and trying to resolve them itself. So maybe this is another QtWebengine proxying issue.

**Comment by The-Compiler** [comment]
It works fine in Falkon when setting `http_proxy`. Merging this into #2492, because, like you say, proxy support with QtWebEngine is kind of in a bad state right now anyways.
