### ISSUE TITLE
New command variable for root domain

### ISSUE THREAD

**Issue by lufte** [qutebrowser/qutebrowser#5408]
I would find it useful to have something like `{url:rootdomain}` or `{url:apexdomain}` for enabling javascript on a per domain basis, and not on a per subdomain basis. If I'm on blog.qutebrowser.org and decide to enable javascript on it, there's a pretty good chance I want to trust all of *.qutebrowser.org and not just the blog. Currently there is no way of doing so without a userscript, but a new variable would allow it.

**Comment by The-Compiler** [comment]
Seems like a good idea - I added it to #901.
