### ISSUE TITLE
Openning external application links

### ISSUE THREAD

**Issue by mysteryjeans** [qutebrowser/qutebrowser#5411]
Browser doesn't open external application links like "zoommtg://..." please check for screenshot.

![2020-05-06-201300_1920x1080_scrot](https://user-images.githubusercontent.com/1826883/81194671-5d575800-8fd6-11ea-8ad0-2440ec356371.png)

**Comment by The-Compiler** [comment]
- What happens if you use the "click here" link?
- What happens if you run `xdg-open` with that `zoommtg://` link?
- Does it work when you set `content.unknown_url_scheme_policy` (aded in v1.11.0) to `allow-all`?

**Comment by mysteryjeans** [comment]
- What happens if you use the "click here" link? -> Opens Zoom
- What happens if you run xdg-open with that zoommtg:// link? -> Opens Zoom
- Does it work when you set content.unknown_url_scheme_policy (aded in v1.11.0) to allow-all?  -> Now automatically opens zoom when clicked on the https meeting link

**Comment by The-Compiler** [comment]
By default, QtWebEngine (and thus qutebrowser) only allows external links to be opened as a response to an user gesture, like clicking a link. You can set `content.unknown_url_scheme_policy` to change that though (I'd recommend only setting it for `*.zoom.us` rather than globally).
