### ISSUE TITLE
Accessing qutebrowser internal state within config file/user script

### ISSUE THREAD

**Issue by ipod825** [qutebrowser/qutebrowser#5415]
I am wondering if there's any plan to expose a set of API to the config file/user script to get the internal states of qute itself (for e.g. current tab number, current stastusbar hidden etc.)

Currently user script can issue command to qute via QUTE_FIFO, but sometimes we might need branch conditioned on some internal states. For example, I have the following mapping:
```python
 '<F11>': 'config-cycle statusbar.hide ;; config-cycle tabs.show switching always ;; fullscreen',
```
As the default `fullscreen` command does not automatically hide statusbar and tabs, I toggle them manually. However, I found that after clicking `fullscreen` button in streaming sites such as YouTube and closing the tab without pressing `<esc>` to exit the fullscreen mode, I end up in fullscreen mode in the new tab (with statusbar and tabs visible). But then I need to issue the `fullscreen` command manually instead of using the `<F11>` mapping. Otherwise, I'll hide my statusbar and tabs as a side effect.

All this can be solved by checking the current status of statusbar and tabs in the `<F11>` mapping.

**Comment by The-Compiler** [comment]
See #30
