### ISSUE TITLE
Possible to redirect domain?

### ISSUE THREAD

**Issue by tamis-laan** [qutebrowser/qutebrowser#5416]
I'm looking to redirect a domain in my browser, i.e. www.domainA.com -> www.domainB.com. 

I tried doing this through /etc/host/ but it doesn't work. Apparently browsers implement there own dns service, i'm guessing qutebrowser does too? 

Is there someway to do this through qutebrowser directly?

**Comment by The-Compiler** [comment]
This will be possible in a future plugin API, see #30. In the meantime, you can do something like this in a `config.py`, though it's completely unsupported:

```python3
from PyQt5.QtCore import QUrl
from qutebrowser.api import interceptor

def intercept(info: interceptor.Request):
    if info.request_url.host() == 'www.youtube.com':
        new_url = QUrl(info.request_url)
        new_url.setHost('www.invidio.us')
        try:
            info.redirect(new_url)
        except interceptors.RedirectFailedException:
            pass

interceptor.register(intercept)
```

**Comment by tamis-laan** [comment]
thnx, I added config.py to ~/.config/qutebrowser/ and it works! The problem now is that it prevents autoconfig.yml to be loaded and all my preveaus settings are gone.

**Comment by The-Compiler** [comment]
You might want to take a look at the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).

**Comment by tamis-laan** [comment]
thnx got things going! The scary part is that the reason I asked is because I wanted to redirect youtube.com to invidio.us !!!!

**Comment by The-Compiler** [comment]
Hehe :wink: That's probably one of the more common reasons people want to redirect hosts.

**Comment by billop** [comment]
Just for any future visitors:

I think it should be:
```python
        except interceptor.interceptors.RedirectException:
```
rather than
```python
        except interceptor.RedirectException:
```
