### ISSUE TITLE
Please implement langmap

### ISSUE THREAD

**Issue by revulent** [qutebrowser/qutebrowser#5424]
For those who don't know, langmap is a variable in [n]vim that remaps keys in normal mode so that people who use alternate keyboard layouts can still benefit from the convenient keyboard bindings without having to go to the trouble of remaping every command by hand. Right now this is the only feature keeping me from using qutebrowser.

**Comment by The-Compiler** [comment]
You can already do this by doing something like `:bind --mode=insert a fake-key b`.

**Comment by revulent** [comment]
The above did not work for me so I wrote this in my config.py. Probably a better way to do this but i'm not a real programmer. 

this is equivalent to `set langmap=qq,dw,re,wr,bt,jy,fu,ui,po,\\;p,aa,ss,hd,tf,gg,y\\;,nh,ej,ok,il,zz,xx,mc,cv,vb,kn,lm,QQ,DW,RE,WR,BT,JY,FU,UI,PO,:P,AA,SS,HD,TF,GG,Y:,NH,EJ,OK,IL,ZZ,XX,MC,CV,VB,KN,LM,^h
`

The dictionary "layoutlowerinverted" corresponds to the lowecase entries you would put in langmap. Should not be hard to adjust for any other layout. 
[config.txt](https://github.com/qutebrowser/qutebrowser/files/4606919/config.txt)

**Comment by The-Compiler** [comment]
Ah, sorry, I somehow read this as insert mode rather than normal mode! For normal mode, you can use the `bindings.key_mappings` setting.

**Comment by revulent** [comment]
I think my attempt at implementing this in config.py might have exposed a bug. For some reason not all the keybindings were being applied so I tested it by putting these lines at the end of my config.py

`
c.bindings.commands['normal']['jj'] = 'yank'
print(c.bindings.commands['normal'].setdefault('jj'))
`
it prints "yank" at the console but pressing jj does nothing in normal mode

**Comment by revulent** [comment]
also qute://help/settings.html#bindings.key_mappings returns "Your file was not found"

**Comment by The-Compiler** [comment]
> it prints "yank" at the console but pressing jj does nothing in normal mode

What does `:bind j` say? If it says `scroll down` (the default binding), then you'll need to unbind that, so that it doesn't shadow the `jj` binding.

FWIW this works fine:

```python
c.bindings.commands['normal'] = {
  'jj': 'yank',
  'j': None,
}
print(c.bindings.commands['normal'].setdefault('jj'))
```

> also qute://help/settings.html#bindings.key_mappings returns "Your file was not found"

How did you install qutebrowser? From #5429 it seems like you're on Gentoo, but running qutebrowser v1.11.1 which isn't packaged on Gentoo yet?

**Comment by revulent** [comment]
Gentoo has a lot of flexibility in terms of the version you want to install. portage (gentoo's package manager) allows you to build from git.

`:bind j` Does in fact tell me that 'j' is bound to scroll down. Now that I understand what qutebrowser is doing, I think I can make it work.

**Comment by The-Compiler** [comment]
So I'm guessing `/usr/lib/python3.7/site-packages/qutebrowser/html/doc/settings.html` does not exist on your system? The Gentoo -9999 ebuild [does call](https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/qutebrowser/qutebrowser-9999.ebuild#n47) the `asciidoc2html.py` script which should generate that. So if that doesn't exist, there's something wrong with either the ebuild, that script, or your system.

**Comment by revulent** [comment]
that would be correct. the entire doc directory is missing. If that's a gentoo issue, i'll report it to them

**Comment by The-Compiler** [comment]
Can you show the output when you build that package?

**Comment by revulent** [comment]
[portageoutput.txt](https://github.com/qutebrowser/qutebrowser/files/4611918/portageoutput.txt)

**Comment by revulent** [comment]
I got this to work the way i wanted. `layout` is a dictionary that works the way the LANGMAP variable does in (n)vim. Should be trivial to adapt for any other layout
[config.txt](https://github.com/qutebrowser/qutebrowser/files/4612206/config.txt)

**Comment by The-Compiler** [comment]
Sorry for the late answer - regarding the missing docs, that indeed seems like a Gentoo packaging bug, though I don't know what's going on exactly. Looking at the output it seems like those docs are built, but perhaps not installed/packaged correctly?
