### ISSUE TITLE
Keybinds using --mode command should work the command line

### ISSUE THREAD

**Issue by slackhead** [qutebrowser/qutebrowser#5425]
qutebrowser v1.10.1
Git commit: 47470e972 (2020-04-15 21:07:28 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

My thought is that when doing say:
bind --mode command p fake-key &lt;ctrl-a&gt;
it ought to apply to the command line itself, but instead pressing `p' selects all the text on the page (with the command line open).

One idea might be to select and copy all the text in a history completion URL using fake-keys.  This might be one of those xy problems, where it would be useful to have a way to copy an URL in completion history without opening it in a page, but still shouldn't using --mode command actually apply to the CLI?

I've seen a few other threads about doing things like paste from clipboard, or other kinds of bindings with --mode command, but not a general idea behind it unless I missed it.

E.G.:

https://github.com/qutebrowser/qutebrowser/issues/4550
https://github.com/qutebrowser/qutebrowser/pull/5326

Thoughts?f

**Comment by slackhead** [comment]
It looks like using fake-key --global works.

**Comment by The-Compiler** [comment]
Like documented in `:help :fake-key`, using `:fake-key` without `--global` always sends the key to the website.

**Comment by The-Compiler** [comment]
Ah, and as for:

> where it would be useful to have a way to copy an URL in completion history without opening it in a page

Press `Ctrl-C` (`:completion-item-yank`) :wink:
