### ISSUE TITLE
Split content.media_capture setting

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5427]
The `content.media_capture` setting currently controls `QWebEnginePage.MediaAudioCapture`, `QWebEnginePage.MediaVideoCapture` and `QWebEnginePage.MediaAudioVideoCapture`. This should be split into three different settings (probably with a migration which sets all three for existing settings).

**Comment by ykahveci** [comment]
I'll try to do this. Would be my first-time contribution to a project on GitHub though, so wish me luck!

**Comment by The-Compiler** [comment]
Good luck! :+1: Let me know if you need help.

**Comment by ykahveci** [comment]
@The-Compiler Could you close this? #5595 did it.

**Comment by The-Compiler** [comment]
@ykahveci Thanks for the reminder! For future contributions, note that you can mention something like "Closes #5427" in your pull request description or commit message ([docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) for GitHub to do that automatically when the PR is merged.

**Comment by ykahveci** [comment]
Thanks I couldn't figure that out on GitHub im relatively new to contributing, as you may have noticed

**Comment by The-Compiler** [comment]
No worries! :+1: Nothing wrong with that, it happens sometimes even to people who know it exists, and closing issues manually works just as well.
