### ISSUE TITLE
Error message when setting tabs.title.format_pinned in config file

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#5428]
**Version info**:

qutebrowser v1.11.1
Git commit: e46ae39eb (2020-05-07 18:04:15 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**:

n/a

**Description**

I wanted to get rid of the index in pinned tabs. So I put in my config.py file:

```py
c.tabs.title.format_pinned = {audio}
```
and got this:

![2020-05-10_20:23:38](https://user-images.githubusercontent.com/4634851/81523508-d9b5a800-9302-11ea-969a-1bb96d86db54.png)

I tried with `id` as a test and I got a similar error message.

If I customize it in `qute://settings/` for the current session, it works without any problem.

**Comment by toofar** [comment]
It looks like you just need to put it in a string in your config.py. So `{audio}` tries to initialize a set with the object called `audio` in it and complains that it can't find it. `"{audio}"` sets it to a string that qutebrowser formats later.

**Comment by prosoitos** [comment]
Ah! Thank you!! Sorry about the noise.
