### ISSUE TITLE
bindings.key_mappings not working as expected

### ISSUE THREAD

**Issue by revulent** [qutebrowser/qutebrowser#5429]
**Version info**:
https://paste.the-compiler.org/view/03143de7

**Does the bug happen if you start with `--temp-basedir`?**:
NA
**Description**
It seems that only some of the remappings are being applied. I've attached my config.py
For example, 'o' does not scroll up, and 'jj' does not yank when it should based on the contents of c.bindings.key_mappings.
I also tried with version 1.10.1 to the same result.

**How to reproduce**
[config.txt](https://github.com/qutebrowser/qutebrowser/files/4611496/config.txt)

Use the attached config

**Comment by The-Compiler** [comment]
Hmm, right, using `key_mappings` probably won't work for your purpose - if there is a binding with the same key, the binding takes precedence. For what you've described in #5424, you'd indeed need to rebind the keys. When rebinding them, you'll also get the correct bindings shown (e.g. in the completion or when pressing a part of a key chain and waiting), so I don't think using `bindings.key_mappings` on top of the default bindings is something that should be supported.
