### ISSUE TITLE
Blurry page when switching between outputs with different scale

### ISSUE THREAD

**Issue by akobel** [qutebrowser/qutebrowser#5432]
**Version info**:
qutebrowser v1.11.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2
(from Arch Linux repo, all up-to-date)

**environment**:
Wayland with sway 1.4
two outputs:
- 1: HDMI with 1920x1080, scale=1
- 2: eDP with 2560x1440, scale=2
```
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_QPA_PLATFORMTHEME=gnome
QT_QPA_PLATFORM=wayland-egl;wayland;xcb
QT_WAYLAND_FORCE_DPI=96
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_ENABLE_HIGHDPI_SCALING=0
QT_FONT_DPI=96
QT_SCALE_FACTOR=1
```
(but none of those seems to matter)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Moving the qutebrowser from display 1 (scale=1) to display 2 (scale=2) results in blurry display (probably linear interpolation, upsampling everything by a factor of two).
It doesn't matter on which display qutebrowser has been started.
Switching to a different tab and back renders fine again; changing the geometry (size) of the window, too. However, simply reloading the tab does *not* help.

Apparently, moving the window to the other screen alone does not incur a redraw operation despite the change in the window size.

If the window is floating and partially on both screens, redrawing (i.e., switch tabs) gives sharp representation on the screen which on the left (according to the wayland output settings); probably top-left, but I don't have enough displays to check. This is contrary to sway's default behavior of using the higher resolution, IIUC.

**How to reproduce**
Open any page in qutebrowser and move the window between displays of different scale.

**Comment by The-Compiler** [comment]
Can you check if you see the same issue with KDE Falkon?

**Comment by akobel** [comment]
Confirmed, it's the same behavior.

For the sake of completeness: Other Qt apps seem to be fine, e.g., the nextcloud client GUI. Firefox (Wayland) is fine, too; Chromium is on Xwayland right now, but I should have the ozone variant built within a couple of hours if it helps...

**Comment by The-Compiler** [comment]
Sounds like an issue with either QtWebEngine or Chromium then, probably nothing qutebrowser can fix - but it'd certainly be interesting if Chromium on Wayland has the same issue (just to know whether you'd need to report this to Chromium or to QtWebEngine).

**Comment by akobel** [comment]
Chromium Ozone (81.0.4044.138, from Arch Linux AUR) does *not* show the problem.
So the issue is with QtWebEngine, then?

**Comment by The-Compiler** [comment]
Yep, indeed. You might want to test with Qt 5.15 (which should be released on the 19th), and if it still doesn't work there, open a bug in [Qt's bugtracker](http://bugreports.qt.io/) (project Qt, component WebEngine).
