### ISSUE TITLE
Can't set "style=" attribute for web-fonts as in: c.fonts.web.family.cursive

### ISSUE THREAD

**Issue by jumper149** [qutebrowser/qutebrowser#5434]
I have a problem with setting `c.fonts.web.family.cursive`: When I try to specify the `style` of the chosen font, it doesn't get applied. I have searched all over the internet to see if maybe my syntax is wrong, but couldn't find anything. I particularly tried this syntax among some others:

```python
c.fonts.web.family.cursive = 'Liberation Sans:style=Italic'
```

This is also how `fc-list` formats font names.

The expected behaviour would be: The Italic variant of the font is displayed.
The actual behaviour is: The font of the basename (here: Liberation Sans) is displayed.

The same problem applies to all these:

```python
c.fonts.web.family.standard =
c.fonts.web.family.cursive =
c.fonts.web.family.fantasy =
c.fonts.web.family.fixed =
c.fonts.web.family.sans_serif =
c.fonts.web.family.serif =
```

**Version info (see `:version`)**
```
qutebrowser v1.11.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.2
PyQt: 5.14.2

sip: 5.1.2
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QGtkStyle
Platform plugin: xcb
Platform: Linux-5.6.11-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/jumper/.cache/qutebrowser
config: /home/jumper/.config/qutebrowser
data: /home/jumper/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/jumper/.config/qutebrowser/config.py has been loaded
Uptime: 0:03:48
```

**If applicable: Does the issue happen if you start with `--temp-basedir`?**:
I don't think that is applicable here.

**Comment by jumper149** [comment]
I have tried around a bit more with:

```python
c.fonts.web.family.cursive = 'italic Liberation Sans'
```

I got (in `:messages`):

```
03:59:19 | ERROR | message | message:error:59 | Errors occurred while reading config.py:   While setting 'fonts.web.family.cursive': Invalid value 'italic Liberation Sans' - may not include a style
-- | -- | -- | -- | --
```

**Comment by The-Compiler** [comment]
qutebrowser passes those values to QtWebEngine, which then passes them to Chromium. Chromium doesn't seem to have a way to set a style, but those setters (e.g. `SetStandardFontFamily` in [third_party/blink/public/web/web_settings.h](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/public/web/web_settings.h) aren't documented very well.

FWIW here's a script you could use to test:

```python3
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineSettings
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QUrl

app = QApplication([])

settings = QWebEngineSettings.globalSettings()
settings.setFontFamily(QWebEngineSettings.SansSerifFont, 'Liberation Sans')

view = QWebEngineView()
view.load(QUrl('https://en.wikipedia.org/'))
view.show()

app.exec_()
```

If you find a setting that works, I could make that possible in qutebrowser as well (if it isn't yet) - but I wasn't able to find one. I'm guessing Chromium really only allows a font family there, taking the style from the website.
