### ISSUE TITLE
youtube playback controls disappeared

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#5437]
**Version info**:
https://paste.the-compiler.org/view/23218c44

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Playback controls have stopped appearing for youtube videos around April 2020 (both "normal" and "background" player when browsing youtube).

**How to reproduce**
https://youtube.com

**Comment by The-Compiler** [comment]
Weird, no issues here. Can you reproduce this with `--temp-basedir` again and then do `:report` so I can take a look at the logs?

**Comment by The-Compiler** [comment]
From the report, you are launching qutebrowser with `--qt-flag disable-reading-from-canvas` - does it work if you don't do that?

**Comment by mike402** [comment]
Whoa, I even forgot I had it in the first place! Removing It helps -- thanks!

Shame that canvas can not be enabled/disabled on per-site basis, or false info given to whichever would use it to fingerprint.

**Comment by The-Compiler** [comment]
I see the same with `chromium --disable-reading-from-canvas`, so nothing qutebrowser can do there. I opened #5439 to contribute some settings to QtWebEngine upstream for things we currently control via commandline flags.

**Comment by hyiltiz** [comment]
I had the same issue, so I `set content.canvas_reading` to its default value `true` and restarted. It now works. Thought it was related to `jblock`, but apparently works with `jblock` enabled.
