### ISSUE TITLE
Command for opening dev tools

### ISSUE THREAD

**Issue by C0DK** [qutebrowser/qutebrowser#5438]
My only reason, currently, for utilizing a non-qutebrowser browser is that i need to utilie the dev tools from time to time. I, accidentially, somehow at one point made a keyboard combo that opened it,  after looking for a long time at documentation, i realized it was `wi` - however that was really difficult to figure out.. Would be nice to have it as a command as well i.e  `devtools` or something.

**Comment by C0DK** [comment]
oic it `inspect` - maybe a better hint, so it is accessible by typing `dev` would be nice though.

**Comment by mschilli87** [comment]
There is `:inspect` which is bound to <kbd>w<kbd></kbd>i</kbd> by default. Is that what you are looking for?

**Comment by The-Compiler** [comment]
I was wondering about renaming `:inspector` to `:devtools` anyways - partially because I can never remember whether it's `:inspect` or `:inspector`, and partially because both Chromium and Firefox call them "developer tools" nowadays (what started as an inspector is now much more). Any opinions about that?

**Comment by C0DK** [comment]
maybe just change the description to something like `toggle the web inspector & developer tools`, so any search will find it. the name of it doesn't matter much to me IMO.

**Comment by The-Compiler** [comment]
FWIW I ended up renaming it to `:devtools` as the general consensus seems to be that the inspector is just the first tab of the devtools. Not merged to `master` yet though, I'm working on some more devtools improvements first.
