### ISSUE TITLE
tsH can unintentionally enable JS for all websites / update urlmatch code to Chromium's

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#5440]
**Version info**:

```
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**

It seems that if you hit `tsH` at the wrong time, qutebrowser can enable JS for all websites.
In `:messages`, I see:

```
content.javascript.enabled = true for *://*./*
```

This came up on the mailing list a while ago, and I don't think we ever got to the bottom of it.

**How to reproduce**

- `:set content.javascript.enabled false`
- `:open https://www.whatismybrowser.com/detect/is-javascript-enabled`
- Verify the above website says "No"
- `:open about:blank`
- `tsH`
- `:open https://www.whatismybrowser.com/detect/is-javascript-enabled`
- Verify the above website says "Yes"

**Comment by The-Compiler** [comment]
Hm, that makes some sense. The `tsH` binding enables JS for `*://*.{url:host}/*`, so if `{url:host}` is empty, it would indeed result in that. One way I can reproduce it is by using it on `about:blank`:

```
23:06:49 DEBUG    keyboard   basekeyparser:_debug_log:196 Definitive match for 'tsH'.
23:06:49 DEBUG    keyboard   basekeyparser:_debug_log:196 Clearing keystring (was: tsH).
23:06:49 DEBUG    commands   command:run:541 command called: config-cycle ['-p', '-t', '-u', '*://*./*', 'content.javascript.enabled']
23:06:49 DEBUG    commands   command:run:555 Calling qutebrowser.config.configcommands.ConfigCommands.config_cycle(<qutebrowser.config.configcommands.ConfigCommands object at 0x7f1b8b3a7370>, 'content.javascript.enabled', pattern='*://*./*', temp=True, print_=True)
23:06:49 DEBUG    config     config:_set_value:323 Config option changed: content.javascript.enabled = True
23:06:49 INFO     message    message:info:82 content.javascript.enabled = true for *://*./*
```

Not sure how to best fix it, though! Either those bindings need to go via some command instead of being "direct" bindings, or the part filling the template string needs to fail if the host is blank (but that's then kinda inconsistent with the rest)...

**Comment by The-Compiler** [comment]
Ah, another possibility (and perhaps the easiest solution) would be to make the host `*.` invalid for patterns. Makes me wonder how Chromium's URL patterns handle that case.

**Comment by The-Compiler** [comment]
I just found the [mail](https://lists.schokokeks.org/pipermail/qutebrowser/2020-February/000716.html) again - there, @lufte initially said `*://*/*` but then corrected that to `*://*./*` - so I believe this is indeed what was happening there. Nice find, @rcorre!

**Comment by The-Compiler** [comment]
The actually relevant changes in Chromium are these:

- [Canonicalize URLPattern hosts](https://chromium.googlesource.com/chromium/src/+/b32af8c5a5f828415c028e6a4725d3349003def1)
- [Support IPv6 in URLPatterns](https://chromium.googlesource.com/chromium/src/+/c008bf657dbc01fadc4ff1ea3df21f9cf237569a)
- [Remove wildcard TLD support from URLPatterns](https://chromium.googlesource.com/chromium/src/+/35f8e3712967bb475b8afbac870168c302713ab0)
- [Update URLPattern handling of whitespace in hosts](https://chromium.googlesource.com/chromium/src/+/e5ead0f9034ffbce864a23f06f9e93d2cfda3e7f)
- Various changes regarding invalid/path-less URLs:
  - [Correctly reject pathless candidates](https://chromium.googlesource.com/chromium/src/+/ec5bd1165643c1b9b9c1adab50b5ece8c6be3e80)
  - [Fix handling pathless-but-valid URLs](https://chromium.googlesource.com/chromium/src/+/5295b198386ee0773b2cd8ae032a5d3cd44c7fe8)
  - [Revert URLPattern wildcard to again match some invalid URLs](https://chromium.googlesource.com/chromium/src/+/6fbca674993246cd03d7c32c57529596a4baa6c8)
  - [Revert "Revert URLPattern wildcard to again match some invalid URLs"](https://chromium.googlesource.com/chromium/src/+/757854e199e159523e7789de5cb2f6ba49b79b63)
