### ISSUE TITLE
Feature Request: Please add styling options for disabled context menu entries

### ISSUE THREAD

**Issue by bunwayenterprises** [qutebrowser/qutebrowser#5441]
At the moment we have four options for the context menu:

- background
- foreground
- selected background
- selected foreground

I suggest it would be helpful if possible to add:

- disabled background
- disabled foreground

The use case for this is to make it obvious which context entry menus are selectable and which are not.

For instance:

1. Open a new page
2. Right click the page to get the context menu
3. Since it's a new page the "Forward" option is disabled
4. The "Forward" option looks like a selectable option but is actually disabled. It would be good to have this be dimmed to a different colour to communicate its disabled status.

Similar to the below.

![image](https://user-images.githubusercontent.com/52430572/82118419-75478c80-97cb-11ea-808f-26c6f28b6af5.png)

**Comment by mschilli87** [comment]
Not sure if qutebrowser actually does anything about this. For me at least, disabled options *are* greyed out.

Fun fact: It appears the context menu is so aggressive in swallowing keys (I can't even navigate within my window manager while it is open) that it makes it impossible to take a screenshot of said menu. :smile:

**Comment by bunwayenterprises** [comment]
@mschilli87  - Interesting that you mention that the default scheme shows the entries as disabled. I commented out my colours used and it is indeed the case that the disabled entries are showing with a disabled style.

However, as an illustration, if you change your settings to the following to test you can see that the disabled options don't style differently to the enabled options:

```
c.colors.contextmenu.menu.bg = '#ffffff'
c.colors.contextmenu.menu.fg = '#000000'
c.colors.contextmenu.selected.bg = '#000000'
c.colors.contextmenu.selected.fg = '#ffffff'
```

**Comment by mschilli87** [comment]
Just tried: They actually do. Note that they never switch to black background as they cannot be selected, so if I hover over them they stay grey on white while active options switch from black on white to white on black.

**Comment by rien333** [comment]
I'm in the same boat as @bunwayenterprises. For me, there is no visual difference between non-interactable, and interactable context menu options. What OS are you on @mschilli87? (I'm on Arch Linux with Qt 5.14.2)

**Comment by mschilli87** [comment]
@rien333: Gentoo with Qt: 5.14.2 (qutebrowser v1.10.1).

**Comment by bunwayenterprises** [comment]
@rien333 @mschilli87 - Currently on Nixos 20.03 Stable with Qt 5.12.7 (qutebrowser v1.11.1)

**Comment by bunwayenterprises** [comment]
Here's some screenshots using the colours specified in my previous comment as an example of how qutebrowser renders the context menu when styled with non-default colours.

I couldn't capture the pointer but you can see the flow of moving the pointer down the list from 'Back > Forward > Reload'.

You can see that 'Forward' looks to be enabled the same as other elements but it's not actually selectable and doesn't style differently when using non default colours - and therefore looks to be selectable.

![image](https://user-images.githubusercontent.com/52430572/82320838-0450e080-9a28-11ea-94f0-07e796b28f9b.png)
![image](https://user-images.githubusercontent.com/52430572/82320858-0dda4880-9a28-11ea-92c2-8911e21bb2d5.png)
![image](https://user-images.githubusercontent.com/52430572/82320874-13379300-9a28-11ea-98d7-168eff3cf56f.png)

**Comment by mschilli87** [comment]
As I said: For me it looks the same but with 'Forward' being grey on white instead of black.

**Comment by The-Compiler** [comment]
Looks like @bunwayenterprises mentioned here as well. Should be trivial to add a styling option for disabled items as well, I'll have a quick look.
