### ISSUE TITLE
insert-text does not work with iframes

### ISSUE THREAD

**Issue by juanibiapina** [qutebrowser/qutebrowser#5442]
**Version info**:
https://paste.the-compiler.org/view/0943b162

**Description**
Using `insert-text` doesn't target the correct input field.

**How to reproduce**
Go to reddit.com and click Login. Click the username field to go into insert mode and try to use `insert-text username` in the login field, for instance:

```
:bind --mode=insert <ctrl-i> insert-text username
```
This doesn't work. Typing does work, which makes me think there's a bug in `insert-text`.

If you click the reddit search bar before opening the login screen popup, the `username` text actually gets inserted there, while typed characters get inserted in the correct place.

`fake-key` works properly.

**Comment by The-Compiler** [comment]
What do you mean with "targets the wrong field" exactly? It looks like the text doesn't get inserted at all?

Logs:

```
13:59:56 DEBUG    commands   command:run:556 Calling qutebrowser.components.misccommands.insert_text(<qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://www.reddit.com/'>, 'username')
13:59:56 DEBUG    webview    webenginetab:_js_cb_single:764 Got element from JS: {'attributes': {'class': 'AnimatedForm__textInput', 'data-empty': 'true', 'id': 'loginUsername', 'name': 'username', 'placeholder': 'Username', 'type': 'text'}, 'caret_position': 0, 'class_name': 'AnimatedForm__textInput', 'id': 5, 'outer_xml': '<input id="loginUsername" class="AnimatedForm__textInput" type="text" name="username" placeholder="Username" data-empty="true">', 'rects': [{'bottom': 168.5, 'height': 48, 'left': 1007.8125, 'right': 1399.8125, 'top': 120.5, 'width': 392}], 'tag_name': 'INPUT', 'text': '', 'value': ''}
13:59:56 DEBUG    webelem    webelem:is_editable:240 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="loginUsername" class="AnimatedForm__textInput" type="text" name="username" placeholder="Username" data-empty="true">'>
13:59:56 DEBUG    webelem    webengineelem:insert_text:161 Inserting text into element <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input id="loginUsername" class="AnimatedForm__textInput" type="text" name="username" placeholder="Username" data-empty="true">'>
```

Using `:jseval document.execCommand("insertText", false, "Hello World")` (which is what `:insert-text` does under the hood) doesn't fill it either FWIW. I noticed `document.execCommand` is deprecated, so perhaps there's a better way for qutebrowser to do this?

**Comment by juanibiapina** [comment]
Right, it doesn't work at all. But if you previously select another field, like the search bar, before opening the Login screen, the text will be inserted into the search bar even though the login field is targeted.

**Comment by The-Compiler** [comment]
Ah, I figured out what's happening: The login overlay is an iframe, and qutebrowser runs `document.execCommand` on the page's main frame, not the iframe. I'm merging this into #3569.

**Comment by juanibiapina** [comment]
Awesome!
