### ISSUE TITLE
tab-focus stack-prev/stack-next causes errors

### ISSUE THREAD

**Issue by LiteracyFanatic** [qutebrowser/qutebrowser#5444]
**Version info**:

qutebrowser v1.11.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes, although I'm also using `-C` to load the following configuration settings:

```
config.bind('<Backspace>', 'tab-focus stack-prev')
config.bind('<Tab>', 'tab-focus stack-next')
```

**Description**
I recently added bindings to make use of the `tab-focus stack-prev/stack-next` commands. Now navigating to a new page causes the following error to display: `Could not find requested tab!`. Note that I don't actually have to make use of the mentioned bindings for the error to appear.

**How to reproduce**

1. Start qutebrowser.
2. `:open $SOME_URL`. Page opens but error is displayed.
3. `:back`. Same error appears again.

**Comment by jgkamat** [comment]
Sounds like a duplicate of #4579

**Comment by LiteracyFanatic** [comment]
Looks like you're right. Switching to a binding which doesn't use the tab key fixes it. Thanks!
