### ISSUE TITLE
Switching between two alternate tabs

### ISSUE THREAD

**Issue by andreasmhallberg** [qutebrowser/qutebrowser#5448]
There is a command, `tab-prev`, to go up in the list of tabs, and another, `tab-next`, to go down. It would be very useful to have a similar thing to alternate buffers in vim, with a command to switch to the previously viewed tab, so you can easily go back and forth between two tabs.

**Comment by The-Compiler** [comment]
There's `:tab-focus {last,stack-prev,stack-next}`.

**Comment by andreasmhallberg** [comment]
Gotcha. Cheers.

**Comment by The-Compiler** [comment]
Do you have any suggestions on how to make this more visible? Out of chance, you're the second person asking about this today (unless it's you who asked the same on Reddit as well).

**Comment by tiborsimko** [comment]
**A.** Perhaps the `last` value is not advertised enough in the `tab-focus` command, e.g. the quick help says:

```
:tab-focus      Select the tab given as argument/[count].
```

This seems to focus too much on jumping around tabs based on numbers, as it were. Perhaps the text could mention "last" explicitly there.

**B.** Perhaps people expect to see a dedicated `tab-last` command going along with the visible `tab-prev` and `tab-next` commands, similarly to e.g. Tmux's `last/next/previous` command trio for jumping around windows? There is `<Ctrl-Tab>` and `<Ctrl-^>` but if someone is trying to explore available tab-related commands by doing `:tab` and seeing what is offered, then they don't see anything about those. Having an explicit `tab-last` command would help with that.

**Comment by McKean** [comment]
just stumbled on this after searching for this fro quite a while. Before posting an issue I thought I'll give it one more try. Maybe include the following words somehow: `toggle` `tabs` `between` `previous` maybe by including an example?

**Comment by The-Compiler** [comment]
Forgot about this for a while, but I opened a separate issue now: #5678
