### ISSUE TITLE
Change window title of the DevTools window

### ISSUE THREAD

**Issue by emanuele6** [qutebrowser/qutebrowser#5451]
I noticed that the DevTools window has the same WM_CLASS as the browser window:
```
WM_CLASS(STRING) = "qutebrowser", "qutebrowser"
```
I think it would be useful to have it be something different, e.g.:
```
WM_CLASS(STRING) = "devtools", "qutebrowser"
```
"instance=devtools" "class=qutebrowser".

**Comment by The-Compiler** [comment]
Qt doesn't seem to have an API to set `WM_CLASS` for individual windows. Also note that the [ICCCM](https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.5) says:

> A string that names the particular instance of the application to which the client that owns this window belongs.

Thus, I don't think "devtools" would be a sensible value for that.

What's your goal exactly? Would it help to set the window title (`WM_NAME` / `_NET_WM_NAME`) to "qutebrowser devtools" or so?

**Comment by wedens** [comment]
I suppose a goal is to make it floating or apply some other layout in tiling WM. Currently,  you can't tell apart qutebrowser itself and inspector window.

> Would it help to set the window title (WM_NAME / _NET_WM_NAME) to "qutebrowser devtools" or so?

In the case I mentioned, it'll help (e.g. in i3 wm value of WM_NAME / _NET_WM_NAME can be used in `title` criteria).

**Comment by emanuele6** [comment]
> Thus, I don't think "devtools" would be a sensible value for that.

`firefox` uses `instance="Navigator"` for the browser window and `instance="Devtools"` for the devtools window, that's not the case for `chromium` though.

I was just looking for a reliable way to identify the devtool window.
As said by @wedens, this can be used either for applying special rules with window managers e.g. `Kwin`, `dwm`, `bspwm`, etc.  
But I can also be used by programs like `picom` to apply a certain transparency the devtools window or something like that.  
It could also be used in general for scripting using tools like `xdo` or `xdotool`:
```bash
# hide the devtools window
xdo hide -N qutebrowser -n DevTools
# unhide the devtools window
xdo show -N qutebrowser -n DevTools
# move the devtools window to desktop number 2 (BSPWM)
bspc node "$(xdo -N qutebroser -n DevTools | head -1)" -d ^2
# type "console.log(window)" in the devtools window
xdotool search --all --class qutebrowser --classname DevTools type --window %1 'console.log(window)'
# send a Return key to the devtools window
xdotool search --all --class qutebrowser --classname DevTools key Return
# move the devtools window to a specific location and change its size (200x200+100+100)
xdotool search --all --class qutebrowser --classname DevTools windowmove 100 100 windowsize 200 200 
```

> Would it help to set the window title (WM_NAME / _NET_WM_NAME) to "qutebrowser devtools" or so?

That could be a solution even though it's usually harder to check for the `WM_NAME` of a window since some programs don't support it (e.g. `bspwm` rules).

The devtools window's `WM_NAME` is already distinguishable though since it's just `qutebrowser`: the `WM_NAME` of browser windows is `<title_or_url> - qutebrowser`.

> Qt doesn't seem to have an API to set WM_CLASS for individual windows.

I understand: if it's too complex to do, don't need to do it; it's not a big deal.
