### ISSUE TITLE
Can't insert unicode characters using ctrl+shift+u

### ISSUE THREAD

**Issue by nadrad** [qutebrowser/qutebrowser#5452]
**Version info**:

qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.5
Qt: 5.12.4
PyQt: 5.12.3

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 5.1.2
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.3.0-51-generic-x86_64-with-Ubuntu-19.10-eoan, 64bit
Linux distribution: Ubuntu 19.10 (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

I can insert unicode characters in all applications in my system, except for qutebrowser. I press ctrl+shift+u, followed by the character code, and a space, and the string is replaced with the character. In qutebrowser, the initial ctrl+shift+u doesn't seem to be registered, and the rest is entered as a normal string; e.g., I get ```20ac ``` instead of ```€```.

This is the case for both the insert mode and the passthrough mode, and happens in every type of input field / text area in every website I've tested. 

**How to reproduce**

In Linux, open any webpage that has an input field (e.g., duckduckgo) and use the insert mode or passthrough mode to write into the field. Then press ctrl+shift+u, followed by a code such as ```20ac```, and then a space.

**Comment by The-Compiler** [comment]
Can you try if you see the same with KDE Falkon?

**Comment by nadrad** [comment]
I have the same problem in Flakon!

**Comment by The-Compiler** [comment]
Probably a QtWebEngine issue then, I remember various related fixes there. Unfortunately, Qt 5.12.4 is quite old (5.12.8 is the newest LTS release, 5.14 the current one, 5.15 planned for next week).

You might want to try if you see the same issue with a newer Qt [installed via a virtualenv](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#tox), and if so, report this in the [Qt bugtracker](http://bugreports.qt.io/).

**Comment by fturco** [comment]
I also can't insert unicode characters in qutebrowser with the ctrl+shift+u method. I'm using qutebrowser-1.11.1 and Qt 5.14.2 on a Gentoo Linux system.

**Comment by The-Compiler** [comment]
@fturco Can you test Falkon as well? Do you know what's handling those Ctrl-Shift-U shortcuts?

**Comment by fturco** [comment]
I have the same problem with Falkon 3.1.0.

I don't know what's handling those shortcuts. I feel I can exclude my window manager (i3) because its shortcuts are all based on the Windows key, which I don't use when trying to insert a Unicode character in qutebrowser/falkon.

**Comment by The-Compiler** [comment]
One possibility might be [ibus](https://wiki.lyx.org/Tips/UnicodeInputUsingCtrl-Shift-U). I tried installing `ibus`, starting `ibus-daemon --daemonize --replace` and setting `QT_IM_MODULE=ibus` (without using `im-config` as mentioned on that page, and without installing anything else). After doing that, Ctrl-Shift-U works just fine for me in qutebrowser with Qt 5.14 and Qt 5.12 for me.

**Comment by fturco** [comment]
I prefer to avoid installing ibus on my system, if possible, because it requires a few dependencies I don't like. Is ibus mandatory for inserting unicode characters using ctrl+shift+u?

**Comment by The-Compiler** [comment]
I have no idea! I'm confused - can you insert characters like that in other applications on your system, @fturco?

**Comment by fturco** [comment]
I have three Qt applications on my system: qutebrowser, keepassxc, and electrum. The ctrl+shift+u shortcut doesn't work in any of them, so my problem is not specific to qutebrowser.

I'm not sure, but it seems the ctrl+shift+u shortcut is a GTK thing (and possibly an ibus thing, too). Since I don't have GTK or ibus installed on my system, this could be normal behaviour.

See https://wiki.gentoo.org/wiki/Input_methods/key_sequence.

Anyway I almost never need to use this feature, so it's not a big deal for me.
