### ISSUE TITLE
Pressing the menu key shouldnt make a menu popup if the key is set to changing keyboard layout

### ISSUE THREAD

**Issue by teoet6** [qutebrowser/qutebrowser#5453]
in my .xinitrc I have the following line:
setxkbmap -layout us,bg -option grp:menu_toggle &
on most other programs pressing the menu key just changes my input layout, but in qutebrowser pressing the menu key will also create a menu popup.

The issue presists with --temp-basedir

qutebrowser v1.11.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Comment by The-Compiler** [comment]
What Qt version, backend and qutebrowser version? Can you reproduce with `--temp-basedir`?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by teoet6** [comment]
I edited the post.

**Comment by The-Compiler** [comment]
Works fine for me with the same Qt version. Can you check whether you see the same issue with e.g. KDE Falkon?

**Comment by teoet6** [comment]
Yep. The popup menu appears in falkon as well.

**Comment by The-Compiler** [comment]
Not a qutebrowser issue then - might be this Qt issue:

[[QTBUG-82856] qtwebengine ignores xkb settings. - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-82856)
