### ISSUE TITLE
Keeping the same QtWebEngineProc on tab-move

### ISSUE THREAD

**Issue by skuzzymiglet** [qutebrowser/qutebrowser#5454]
Google Chrome does this: the renderer doesn't change when you move a tab - videos keep playing, no reload is done. I think this would be a great feature in qutebrowser, but I'm not sure how you'd implement it

**Comment by The-Compiler** [comment]
`:tab-move` does keep the renderer as well.

**Comment by skuzzymiglet** [comment]
Oh sorry, I meant tab-give, editing now

**Comment by The-Compiler** [comment]
In that case, see #2636.
