### ISSUE TITLE
Map <ctrl+i> to <tab> to cycle through command completions

### ISSUE THREAD

**Issue by alejandrogallo** [qutebrowser/qutebrowser#5455]
**Version info (see `:version`)**:

```
qutebrowser v1.10.2
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)
Qt: 5.9.1
```

I wanted to know if it is possible to map `<ctr+i>` to the effect of pressing
`<tab>` to cycle through the options in `command` mode.
I have in my `config.py` the following:

```python
cmap = lambda x, y: config.bind(x, y, mode="command")

cmap("<Ctrl+i>", "fake-key <tab>")
```

but this only enters a tab in some active buffer in the webpage
where the cursor sits.

**Comment by The-Compiler** [comment]
qutebrowser normally binds keys to commands rather than binding them to other keys. If you run `bind --mode=command <Tab>`, you can see how it's bound to `completion-item-focus next`, so bind `<Ctrl+i>` to that.

**Comment by alejandrogallo** [comment]
That's awesome, thanks! Maybe it would be a good idea to set this binding default, since it is so in vim and emacs alike :)

**Comment by The-Compiler** [comment]
Why not, I guess! I added it to `bindings.key_mappings` by default, so it'll behave like `<Tab>` in all modes (except insert/passthrough).
