### ISSUE TITLE
Getting number of matched patterns when searching a page

### ISSUE THREAD

**Issue by Shellcat-Zero** [qutebrowser/qutebrowser#5464]
I haven't been able to find anything in the documentation regarding this, but is it possible to display the number of matched patterns when searching for strings with `/`?  Thanks.

**Comment by The-Compiler** [comment]
This should be possible to implement starting with Qt 5.14 (e.g. as a widget in the statusbar or so). FWIW you also see a visual overview of the matches in the scrollbar.

**Comment by The-Compiler** [comment]
Duplicate of #3910, and implemented in #6670.
