### ISSUE TITLE
Provide Caret Mode Documentation

### ISSUE THREAD

**Issue by chaorace** [qutebrowser/qutebrowser#5468]
Currently, there is very little information about using caret mode. `:help caret` yields almost no results, just the `toggle-selection` command. The README and FAQ also make no mention of the mode.

The expected behavior would be for all major modes to be outlined in the README, with supplementary ` :help`  pages demonstrating basic functionality & usage where non-obvious

**Comment by The-Compiler** [comment]
There is some documentation about available modes, though I agree it's a bit hard to find:

- You press `v` to enter caret mode - `:bind v` (or `:help bindings.default`) reveals that the underlying command is `:enter-mode caret`
- `:help :enter-mode` says: "See `:help bindings.commands` for the available modes"
- `:help bindings.commands` does explain all modes.

I agree it'd be good to have more "topic" help pages, and more manual/tutorial-style documentation in addition to the setting/command references. That's something that will happen after switching the documentation toolchain to Sphinx, see #345.
