### ISSUE TITLE
Weird kerning problems on some pages.

### ISSUE THREAD

**Issue by barudaret** [qutebrowser/qutebrowser#5471]
**Version info**:

I gotchu man, I'll paste the whole thing...

```
qutebrowser v1.11.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2 (compiled 5.14.1)

CPython: 3.7.7
PyQt: 5.14.1

sip: 4.19.21
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: 2.1.266 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
Platform: Linux-5.5.13-gentoo-x86_64-x86_64-AMD_FX-tm-8350_Eight-Core_Processor-with-gentoo-2.6, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3.7
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/tasso/.cache/qutebrowser
config: /home/tasso/.config/qutebrowser
data: /home/tasso/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/tasso/.config/qutebrowser/config.py has been loaded
Uptime: 0:06:13
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yep

**Description**

Looks like in the [once-only page](https://malisper.me/once-only), text is getting smushed together...
but in the [Spacemacs documentation pages](https://www.spacemacs.org/doc/DOCUMENTATION.html#orgheadline76), there's the opposite problem.  Text is spaced too much.

**How to reproduce**

Go to the links I put in the **Description** section
here's some screenshots... qb and firefox side by side:
![screenie](https://user-images.githubusercontent.com/32847759/83097263-86f72280-a05c-11ea-9e6f-6d0cf90d620a.png)
![screenie2](https://user-images.githubusercontent.com/32847759/83097267-88284f80-a05c-11ea-988f-dddc9867af61.png)

EDIT: I /had/ brave browser installed a little while ago too.  I've removed it, but yeah in brave, those pages rendered the same as they do in firefox.  I figure it's worth mentioning, since brave is chromium-based like qb is.

**Comment by The-Compiler** [comment]
Can you check if you see the same in KDE Falkon (another QtWebEngine-based browser)?

**Comment by skuzzymiglet** [comment]
The title looks fine for me in Falkon **and** qutebrowser v1.11.1, even with `--temp-basedir`. My sysem default font is IBM Plex Mono.

**Comment by barudaret** [comment]
The notion of a system default font is unfamiliar to me.  What is your OS?  If you are a linux user, how does ‘system default font’ work?

**Comment by skuzzymiglet** [comment]
Actually, I'm not sure it matters. I think it's just loading in Lora or Georgia

**Comment by barudaret** [comment]
Same hiccup in falkon:
![screenie](https://user-images.githubusercontent.com/32847759/83194887-34fedd00-a0ee-11ea-98c8-d1c30dea13b2.png)

**Comment by The-Compiler** [comment]
Not a qutebrowser issue then (and FWIW, I can't reproduce either). You might want to check if it really doesn't happen in Chromium/Brave with your current configuration, and if it doesn't, [open a Qt bug report](https://bugreports.qt.io/secure/Dashboard.jspa).
