### ISSUE TITLE
Can't type accented characters in Google Docs

### ISSUE THREAD

**Issue by devendr4** [qutebrowser/qutebrowser#5472]
**Version info**:
qutebrowser v1.11.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes
**Description**

Whenever I try to type an accented character (á,é,í,ó,ú) in Google Docs qutebrowser just ignores it, but its only on that specific web page because I can type accented characters everywhere else

**How to reproduce**
Try to type accented characters in any document from www.drive.google.com

**Comment by The-Compiler** [comment]
Does it work if you go to https://docs.google.com instead? If so, does `:set -u drive.google.com content.headers.user_agent "Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0"` help?

**Comment by devendr4** [comment]
Changing the user agent worked thank you!

**Comment by The-Compiler** [comment]
I added a site-specific quirk for drive.google.com as well (it was previously only active for docs.google.com), so qutebrowser will do that automatically in the v1.12.0 release. Thanks for the quick response!
