### ISSUE TITLE
Animated PNGs flicker

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5473]
See e.g. https://fedi.absturztau.be/notice/9vXqjPfwUX7PwhVCq0 - happens with Falkon as well, but not with Chromium. Should report it upstream.

**Comment by The-Compiler** [comment]
Huh, for some odd reason, it looks fine in simplebrowser. Needs some more investigation then...

Also, there are some logs:

```
libpng warning: size in first frame's fcTL must match the size in IHDR
libpng warning: Skipped (ignored) a chunk between APNG chunks
[...]
```

Same happens here as well: https://upload.wikimedia.org/wikipedia/commons/1/14/Animated_PNG_example_bouncing_beach_ball.png

**Comment by The-Compiler** [comment]
Hmm, I can't reproduce with a binary Qt build.

However, according to `ldd`, both Archlinux' Qt and the binary Qt use the system libpng `1.6.37-2`:

binary:

```
$ ldd libQt5WebEngine.so.5 | grep -i png                                                     
	libpng16.so.16 => /usr/lib/libpng16.so.16 (...)
```

**Comment by GpGebbia** [comment]
Hi, this only happen in archlinux. The libpng package in their repos is patched with this: https://downloads.sourceforge.net/sourceforge/libpng-apng/

I remember seeing a similar bug report about chromium, but I don't remember where. Anyway recompiling libpng without that patch seems to fix the issue.

**Comment by The-Compiler** [comment]
@GpGebbia Ah, thanks for the pointer! I reported it to Arch: https://bugs.archlinux.org/task/67105

**Comment by The-Compiler** [comment]
FWIW this was [fixed](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/libpng&id=d4972c77c4b9b5555d229b49de3db87738818543) in Archlinux' libpng 1.6.37-3 where the custom apng patch was dropped.
