### ISSUE TITLE
:debug-key does not appear in autocomplete

### ISSUE THREAD

**Issue by LiteracyFanatic** [qutebrowser/qutebrowser#5478]
**Version info**:

qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
While the new command `:debug-key` seems to work fine, it does not appear in the list of autocomplete suggestions.

**Comment by The-Compiler** [comment]
That's intentional, all `:debug-*` commands don't appear there unless qutebrowser is launched with `--debug`.

**Comment by LiteracyFanatic** [comment]
Ah, ok. Learn something new every day I guess.
