### ISSUE TITLE
qutebrowser not launching after Qt 5.15 update

### ISSUE THREAD

**Issue by JonnyHaystack** [qutebrowser/qutebrowser#5489]
**Version info**:

1.12.0-1 package from Arch Linux repos. I can't run the :version command because I can't launch the browser.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
After installing Qt updates on Arch Linux mere minutes ago, I am unable to launch qutebrowser. Running qutebrowser from a shell yields the following output:
```
~
❯ /usr/bin/qutebrowser

(python3:4927): Gtk-WARNING **: 18:19:15.890: Unable to locate theme engine in module_path: "adwaita",

(python3:4927): Gtk-WARNING **: 18:19:15.890: Unable to locate theme engine in module_path: "adwaita",
Fatal Python error: Segmentation fault

Current thread 0x00007f089ff09740 (most recent call first):
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 478 in __init__
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 92 in run
  File "/usr/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 203 in main
  File "/usr/bin/qutebrowser", line 11 in <module>
zsh: segmentation fault (core dumped)  /usr/bin/qutebrowser
```

**How to reproduce**

Install Qt 5.15 and try launching qutebrowser I guess

**Comment by The-Compiler** [comment]
Are you using qt5-styleplugins(-git)? If so, does it help to uninstall that?

**Comment by JonnyHaystack** [comment]
Yes, I use qt5-styleplugins. Uninstalling that fixes that problem, but now I don't have my GTK/Qt theme in qutebrowser.

**Comment by The-Compiler** [comment]
From what I've heard somewhere, other Qt applications like KeePassXC are affected as well - can you confirm?

**Comment by The-Compiler** [comment]
Ah, found those mails again: https://lists.archlinux.org/pipermail/arch-dev-public/2020-June/thread.html

So this doesn't look like a qutebrowser issue.

**Comment by maximbaz** [comment]
@The-Compiler hey, for me after qt5 upgrade on Arch qutebrowser launches, but tabs widget is not being rendered at all (I dont see any tab, basically, and how many there are), and pressing `:` also either doesn't do anything, or opens an empty menu where I cannot see anything, just background color. It seems just a rendering issue though, for example I can switch to previous/next tab with `Shift+J/K`. I commented out my entire `config.py` and still reproduce. Any ideas? I know that it's somehow special to my setup (another person confirmed that they don't reproduce the issue), but I can't imagine what can be the case... Do you have any ideas for me to try? I dont have qt5-styleplugins installed.

**Comment by The-Compiler** [comment]
@maximbaz huh, odd! Can you please open a new issue with the full `qutebrowser --version` output and a screenshot?
