### ISSUE TITLE
Installing Qutebrowser on Arch Fails

### ISSUE THREAD

**Issue by AVCADO** [qutebrowser/qutebrowser#5493]
I'm trying to install Qutebrowser on my arch machine.
When I run `makepkg -si`,  it outputs
```
==> ERROR: Canot find the fakeroot binary.
```
Any help?

**Comment by The-Compiler** [comment]
Why not use `qutebrowser` from the `[community]` repo? Either way, to use `makepkg` you will need to have `base-devel` installed, see: https://wiki.archlinux.org/index.php/makepkg#Usage

**Comment by AVCADO** [comment]
if i try running `sudo pacman -S qutebrowser`, it 404s.

**Comment by The-Compiler** [comment]
Your package database is outdated then - first update the database and your system using `-Suy`, see https://wiki.archlinux.org/index.php/Pacman#Upgrading_packages
