### ISSUE TITLE
binding to save a picture, what's the correct way ?

### ISSUE THREAD

**Issue by bonnefoi** [qutebrowser/qutebrowser#5496]
I want to be able to save a picture displayed in the browser with a single key, so I have simulated a right-clic, followed by some move and a left-click.

I've defined a binding as follows:
```bind z spawn sh -c 'xdotool click 3 mousemove_relative 5 5 click --delay 50 3'```
Is there a better way :
- to ask for saving a ressource ;
- and/or to simulate clicking buttons on the mouse.

**Comment by arza-zara** [comment]
Bind to `hint images download`.

**Comment by bonnefoi** [comment]
Thanks !
