### ISSUE TITLE
renderer crashes with qt-webengine

### ISSUE THREAD

**Issue by cpu012** [qutebrowser/qutebrowser#5497]
**Version info**:
qutebrowser v1.12.0
Git commit: 
Backend: new QtWebKit (WebKit 602.1)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.32.2
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: nouveau, 3.3 (Compatibility Profile) Mesa 20.0.7
Platform: Linux-5.4.44-1-lts-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/shloimy/.cache/qutebrowser
config: /home/shloimy/.config/qutebrowser
data: /home/shloimy/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/shloimy/.config/qutebrowser/config.py has been loaded
Uptime: 0:06:09

**Does the bug happen if you start with `--temp-basedir`?**:
no

**Description**
renderer crashes when: using duckduckgo with a settings profile, visiting a website with a lot of javascript, probably more that I didn't notice. changing the backend to webkit fixed this.

**How to reproduce**
set backend to webengine, and visit duckduckgo.com, change some settings and save as profile, restart qutebrowser.

**Comment by cpu012** [comment]
##wrong version info

qutebrowser v1.12.0
Git commit:
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.32.2
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: nouveau, 3.3 (Compatibility Profile) Mesa 20.0.7
Platform: Linux-5.4.44-1-lts-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/shloimy/.cache/qutebrowser
config: /home/shloimy/.config/qutebrowser
data: /home/shloimy/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/shloimy/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:52

**Comment by The-Compiler** [comment]
So I launched `qutebrowser --basedir /tmp/ddg`, went to https://duckduckgo.com/settings and turned instant answers off, infinite scroll on, and changed the region to Switzerland. Then I used "Save and exit" at the bottom. After `:wq` and restarting qutebrowser with `--basedir /tmp/ddg`, no issues.

Can you reproduce the issue when doing that?

**Comment by cpu012** [comment]
it might be one of the duckduck go issues

**Comment by cpu012** [comment]
`--basedir /tmp/ddg' did not fix this, 
I first noticed this issue when I started editing the `c.url` section in config.py,
after going back to what it was before that, the issue remained

**Comment by cpu012** [comment]
`--basedir /tmp/ddg' did not fix this, 
I first noticed this issue when I started editing the `c.url` section in config.py,
after going back to what it was before that, the issue remained

**Comment by cpu012** [comment]
running with `--basedir /tmp/ddg` did not fix this, I first noticed this issue when I started editing the `c.url` section in config.py,
after going back to what it was before that, the issue remained

**Comment by The-Compiler** [comment]
Well, I still can't reproduce. If you do the exact steps I mentioned above, do you see the crash?

**Comment by cpu012** [comment]
I did reproduced this and `:report`ed it,
I noticed that some of the settings that when I didn't turn on some of the settings that's only compatible with webengine (e.g. c.colors.webpage.*) not turning those settings on fixed this.

**Comment by The-Compiler** [comment]
This is caused by `colors.webpage.darkmode.policy.images = smart`, see #5505. FWIW I'd suggest turning off that setting for now (rather than switching to QtWebKit), given the QtWebKit security issues.
