### ISSUE TITLE
Issues on plnkr.co

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#5503]
**Version info (see `:version`)**: v1.12.0

**If applicable: Does the issue happen if you start with `--temp-basedir`?**: Yes

[This project on plnkr.co](https://plnkr.co/edit/uPT6BgeTqbIPiU4W?open=lib%2Fscript.js), there's a simple calculator app with some tests.

If I click on the refresh live preview button (the symbol of the two arrows chasing each other in cyrcle, just below _Preview_ title of the omonimus pane) and wait, the tests don't actually run and, indeed, the tab with the calculator does not open.

If, instead, just after clicking that button I hold down a key in normal mode (well, a key which does not really interact with the page, like <kbd>k</kbd>, but clearly not <kbd>d</kbd>), then then tab with the calculator opens up, and the tests run (if I don't close the tab too early).

I guess this is a tricky think to get working, but I guess it's a good chance for the improvement of this browser.

I've recorded the strange behavior, the video should be available from [my dropbox](https://www.dropbox.com/s/hhf6uk9uxt8xr05/qutebrowserReport.mkv?dl=0).

**Comment by The-Compiler** [comment]
By default, JavaScript is only allowed to open new tabs if there was a user interaction. Works fine after `:set -u plnkr.co content.javascript.can_open_tabs_automatically true`.
