### ISSUE TITLE
Qutebrowser frequently crashing

### ISSUE THREAD

**Issue by Spounka** [qutebrowser/qutebrowser#5507]
**Version info**:
qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 5.3.0
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.4.2
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g FIPS  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.0.7
Platform: Linux-5.6.16-300.fc32.x86_64-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Fedora 32 (MATE-Compiz) (fedora)
Frozen: False
Imported from /usr/local/lib/python3.8/site-packages/qutebrowser-1.12.0-py3.8.egg/qutebrowser

**Does the bug happen if you start with `--temp-basedir`?**:
No it doesn't happen

**Description**
qutebrowser, since 1.12, starting doing frequent crahes when opening certain tab

**How to reproduce**
i have google search engine enabled as default search engine
i open in a new tab facebook or twitter
it just closes and when opened again it shows bug report page

**Comment by The-Compiler** [comment]
Can you please show `coredumpctl info` right after the crash happens?

**Comment by Spounka** [comment]
i seem to have solve the issue by degrading PyQt version to 5.13, i no longer have these crashes
seems to be a Qt issue i suppose ?

**Comment by The-Compiler** [comment]
Yeah, but I'd still like to find out what the issue is exactly, so I can report it upstream.
