### ISSUE TITLE
QtWebEngine overloads cpu when visiting certain sites

### ISSUE THREAD

**Issue by ykonstant1** [qutebrowser/qutebrowser#5509]
**Version info**:
qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
When I visit the site https://old.reddit.com/r/VirtualYoutubers/ , the QtWebEngine process starts cosuming all the cpu resources resulting in system lag and constant fan spinning.  This does not stop until I navigate away from the site.  Possibly, the animated banner has something to do with the lag.

**How to reproduce**
Visit https://old.reddit.com/r/VirtualYoutubers/

**Comment by The-Compiler** [comment]
Nothing qutebrowser can fix - I see the same CPU usage with KDE Falkon, and almost the same (if also counting the separate GPU process) in Chromium as well. Also see #5375.

**Comment by ykonstant1** [comment]
I understand; I would appreciate any directions to the right place to ask about this bug.  It does not seem that the website is doing anything wrong; a simple animated banner should not consume so many resources (and it does not in Firefox).

**Comment by The-Compiler** [comment]
Probably either the [Chromium bugtracker](https://bugs.chromium.org/p/chromium/issues/list) or, if the gap between Chromium (with both processes) and QtWebEngine is higher on your system, perhaps the [Qt bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa).

**Comment by ykonstant1** [comment]
Thank you very much!

**Comment by The-Compiler** [comment]
You're welcome! Please post a link to the bug report(s) here if you submit something, as I'm curious how it turns out!

**Comment by ykonstant1** [comment]
I finally managed to open a bug report at the Qt bug tracker.  

https://bugreports.qt.io/browse/QTBUG-85433

We'll see.
