### ISSUE TITLE
Crash when using qutebrowser with qtwebkit 5.14

### ISSUE THREAD

**Issue by pierg75** [qutebrowser/qutebrowser#5517]
**Version info**:

https://paste.the-compiler.org/view/539cadb3

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
On Fedora there's an update for the qtwebkit to the version 5.14 from 5.13.
Using this version, the browser keeps crashing.

**How to reproduce**

On Fedora 32, enable the testing repositories, update qtwebkit (a yum update should just do it if the testing repo are enabled) and then start the browser.
I have the gdb output as per the stacktrace instructions, not really sure where to upload it (it's pretty big, ~280K).

**Comment by pierg75** [comment]
About the first one, I have manually rebuilt version 1.12.0 and the crash indeed disappeared. I'll check if someone can update it on Fedora.
About the second backtrace, it's from the same crash, started qutebrowser with the debug options and temp-dir, then closed the report window and just issued a 'bt' from gdb.
If you think it will be useful, I still have the full gdb 'bt' output.

**Comment by The-Compiler** [comment]
I added it to #5385, but it might just be that we don't really do a clean shutdown when there was an exception - so I'm closing this one now.
