### ISSUE TITLE
Youtube page not working

### ISSUE THREAD

**Issue by enderger** [qutebrowser/qutebrowser#5519]
**Version info**:
https://paste.the-compiler.org/view/6dc03165

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When running on NixOS, it appears as though qutebrowser refuses to follow certain links on any effected site. The only one I've identified so far is the https://youtube.com page.

**How to reproduce**
0. Use the stable nixpkg to install qutebrowser
1. Go to https://youtube.com 
2. Click on any of the links on the page. This happens both in the search bar and on video links.

**Note**
This does not effect pages opened in a new tab. This may suggest that it effects something with SPWAs.

**Comment by The-Compiler** [comment]
Works fine for me with Qt 5.12 (on Arch, though). Can you please reproduce this with `--temp-basedir` and then do `:report` so I can take a look at the logs?

**Comment by enderger** [comment]
I have tried basedir and it did not fix. I’ll get the log, but I think it has something to do with the NixPkg as the OS is... a special snowflake.

**Comment by wedens** [comment]
I don't have such problems with qutebrowser 1.12.0 (Qt: 5.12.7) from nixpkgs. The only way nixpkgs can "break" something in qutebrowser is by using older/newer Qt version than qutebrowser expects.

**Comment by enderger** [comment]
Ok, well after finding breakage after breakage with NixOS I've decided to just move off it. Maybe with a bit more time it could work, but honestly my system has been known to be quite annoying when it comes to different distros. I'll close this issue because it likely is my computer not liking the combination of different factors.
