### ISSUE TITLE
:debug-keytester not in browser's commands list

### ISSUE THREAD

**Issue by IsaacElenbaas** [qutebrowser/qutebrowser#5522]
**Version info**:

qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Description**
Love this feature, but it is not in the browser's command list.

**Comment by Jan-PieterBaert** [comment]
If I'm not mistaken it's only in the browser's command list when you enable debugging

**Comment by ninewise** [comment]
Indeed. Start qutebrowser with `--debug` should get you the completion.
