### ISSUE TITLE
How to switch to new tab automatcally ?

### ISSUE THREAD

**Issue by bonnefoi** [qutebrowser/qutebrowser#5523]
I've not found a setting to switch automatically to a new tab that has been created by thecurrent tab.
How could I proceed ?

**Comment by The-Compiler** [comment]
Depends on how the tab is created exactly - you might want to check the `tabs.background` setting or use ctrl-shift-click (or `:hint all tab-fg` / `;f` for hints).

**Comment by bonnefoi** [comment]
I was asking for the tabs open by a page like google search for example.

**Comment by The-Compiler** [comment]
See my answer above then.

**Comment by bonnefoi** [comment]
my tabs.background setting is set to false

**Comment by The-Compiler** [comment]
How exactly are you opening those tabs then?

**Comment by bonnefoi** [comment]
I've set it to true and it works...
So if I put the option "open new tabs in the background" to true, the window automatically open by my current page (like the search in Google with the option "open each selected result in a new browser window" selected) get in front...
It's very confusing...

**Comment by bonnefoi** [comment]
but it works...

**Comment by The-Compiler** [comment]
You're probably seeing #3231 then.

**Comment by bonnefoi** [comment]
Yes :)
Thanks for your support !
I've switched entirely to qutebrowser so I'm very picky to issue.

Next stop -> getting "reader mode" working.
