### ISSUE TITLE
Inspector in qutebrowser seems outdated and sometimes causes qutebrowser to crash.

### ISSUE THREAD

**Issue by GasparVardanyan** [qutebrowser/qutebrowser#5530]
**Version info**:

qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Opening images with 'broken' icons from inspector's 'Network' page sometimes causes qutebrowser to crash.

**How to reproduce**
1. Open some video from youtube.
2. press **wi**
3. Open the 'Network' page.
4. Press **Ctrl+R**
5. Open some image with 'broken' icon, as in this screenshot: https://imgur.com/a/6JZ6SmQ
When I launch qutebrowser from terminal, after crashing I get this message:
```
zsh: trace trap (core dumped)  qutebrowser --temp-basedir
```

**Also...**
Also I have another problem related to qutebrowser's inspector. In chromium's inspector in the top-left side there is a button to enable 'mobile' mode: https://i.stack.imgur.com/UWiaj.png (the icon before 'Elements', just found some image from the web).

**Comment by GasparVardanyan** [comment]
Also... color picker (https://imgur.com/a/4nsaiQH) doesn't work.

**Comment by toofar** [comment]
The crash when looking at requests is probably https://github.com/qutebrowser/qutebrowser/issues/5513, the last two things you mention both make changes to the browser's UI so they were probably stripped out for webengine which doesn't contain the UI related parts of chrome. If you go to the release notes from the three dot menu > Help it links to the release notes for the same chrome version as qutebrowser reports so I don't think it is outdated.

**Comment by The-Compiler** [comment]
What do you mean with "doesn't work" for the color picker? Seems to work fine here.

**Comment by toofar** [comment]
If you try it on chrome, while the picker is open, if you move your mouse over the page it'll be a magnifier circle that lets you click individual pixels.

**Comment by The-Compiler** [comment]
I opened a Qt bug for the missing features: [[QTBUG-85171] Missing features in inspector/devtools - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-85171)

**Comment by The-Compiler** [comment]
FWIW if you happen to use Archlinux, the crashes were [fixed](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/qt5-webengine&id=fc7cbcf3af5fe895e7f19a2b8ce6333c150c362c) in qt5-webengine 5.15.0-3 which backports the upstream fix.

**Comment by GasparVardanyan** [comment]
Yes, I use ArchLinux, thank you, and thank you for this project, qutebrowser is a great web browser!
