### ISSUE TITLE
Middle click + "back" (in context menu) should open previous page in new tab

### ISSUE THREAD

**Issue by basedtho** [qutebrowser/qutebrowser#5531]
I just checked Firefox and it does just that, but Chrome doesn't. Still I think this is how it should be from the UI/UX point of view

P.S. Same with "reload" - reload in a new tab

**Comment by The-Compiler** [comment]
The context menu is handled by Qt - there are some plans for a custom context menu in #349, but I don't think it's possible to know how an action was triggered in that menu (without handling the user inputs manually, which I'd rather not do).
