### ISSUE TITLE
asciidoc2html.py incompatible with Python3.5

### ISSUE THREAD

**Issue by pylipp** [qutebrowser/qutebrowser#5532]
**Version info**:

qutebrowser v1.12.0
Git commit: eaff6e82d (2020-06-01 15:57:24 +0200)
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.9

**Does the bug happen if you start with `--temp-basedir`?**:
Irrelevant.

**Description**
Using Python 3.5.3 to run the `asciidoc2html.py` script.

```
> python3 scripts/asciidoc2html.py
Traceback (most recent call last):
  File "scripts/asciidoc2html.py", line 294, in run
    asciidoc.build()
  File "scripts/asciidoc2html.py", line 78, in build
    self._build_docs()
  File "scripts/asciidoc2html.py", line 101, in _build_docs
    with open(modified_src, 'w', encoding='utf-8') as modified_f, \
TypeError: invalid file: PosixPath('/tmp/tmp9cr_witm/tmp/faq.asciidoc')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/asciidoc2html.py", line 308, in <module>
    main(colors=True)
  File "scripts/asciidoc2html.py", line 304, in main
    run(asciidoc=args.asciidoc, website=args.website)
  File "scripts/asciidoc2html.py", line 296, in run
    asciidoc.cleanup()
  File "scripts/asciidoc2html.py", line 71, in cleanup
    shutil.rmtree(self._homedir)
  File "/usr/lib/python3.5/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)
TypeError: lstat: illegal type for path parameter
```

**How to reproduce**

```
git clone https://github.com/qutebrowser/qutebrowser
cd qutebrowser
git checkout v1.12.0
python3.5 scripts/asciidoc2html.py
```

I couldn't find information about whether the script was intended to be incompatible with Python 3.5. If so, it could be stated on the installation page? (just noticed that [this section](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#building-the-docs) is partly outdated because the `mkvenv.py` script already builds the docs)

**Comment by The-Compiler** [comment]
Until we drop Python 3.5 entirely (#4800) that *is* supposed to work. I suspect it broke during a recent change, #5290 - @ju-sh can you take a look, if you have the time?

**Comment by ju-sh** [comment]
Sorry I had missed converting `pathlib.Path` objects to `str` in some places. I made some changes at https://github.com/qutebrowser/qutebrowser/pull/5534
