### ISSUE TITLE
mkvenv.py script fails to (auto-)install PyQt5 >5.13

### ISSUE THREAD

**Issue by pylipp** [qutebrowser/qutebrowser#5533]
**Version info**:

Irrelevant.
**Does the bug happen if you start with `--temp-basedir`?**:
Irrelevant.
**Description**
I'm using the `mkvenv.py` script to install qutebrowser.
**How to reproduce**

```
git clone https://github.com/qutebrowser/qutebrowser
cd qutebrowser
git checkout v1.12.0
python3 scripts/mkvenv.py
```
Relevant error output:

```
==================== Installing PyQt from binary ====================
No proprietary codec support will be available in qutebrowser.
venv$ pip install -r misc/requirements/requirements-pyqt.txt --only-binary PyQt5,PyQtWebEngine
Collecting PyQt5==5.15.0 (from -r misc/requirements/requirements-pyqt.txt (line 3))
  Could not find a version that satisfies the requirement PyQt5==5.15.0 (from -r misc/requirements/requirements-pyqt.txt (line 3)) (from versions: 5.7.1, 5.8, 5.8.1.1, 5.8.2, 5.9, 5.9.1, 5.9.2, 5.10, 5.10.1, 5.11.2, 5.11.3, 5.12, 5.12.1,
5.12.2, 5.12.3, 5.13.0, 5.13.1, 5.13.2, 5.14.0)
No matching distribution found for PyQt5==5.15.0 (from -r misc/requirements/requirements-pyqt.txt (line 3))
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Subprocess failed, exiting
```

So apparantly PyPI (?) does not provide PyQt5==5.15.0. 
I then tried `python3 scripts/mkvenv.py --pyqt-version 5.14`
Similar error:
```
Collecting PyQt5==5.14.2 (from -r misc/requirements/requirements-pyqt-5.14.txt (line 3))
  Could not find a version that satisfies the requirement PyQt5==5.14.2 (from -r misc/requirements/requirements-pyqt-5.14.txt (line 3)) (from versions: 5.7.1, 5.8, 5.8.1.1, 5.8.2, 5.9, 5.9.1, 5.9.2, 5.10, 5.10.1, 5.11.2, 5.11.3, 5.12, 5.12.1, 5.12.2, 5.12.3, 5.13.0, 5.13.1, 5.13.2, 5.14.0)
No matching distribution found for PyQt5==5.14.2 (from -r misc/requirements/requirements-pyqt-5.14.txt (line 3))
```

Using `--pyqt-version 5.13` and `--pyqt-version 5.12` works.

EDIT: PyQt5==5.15.0 is provided by PyPI, however it can only be fetched by pip without the  `--only-binary` option (then the package as tar-archive is downloaded).

**Comment by The-Compiler** [comment]
I'm a bit confused by:

> You are using pip version 10.0.1, however version 20.2b1 is available.

Because the script *does* upgrade pip before installing the package.

What OS/distribution is this on? Can you show the full mkvenv.py output as well as the first two lines shown when you run `python3`?

**Comment by pylipp** [comment]
Indeed, I can't reproduce this either on another machine (using Python 3.6.10 and `python3 scripts/mkvenv.py`; installs PyQt5==5.15.0).
On the first machine (Debian 9) I use Python3 installed via guix, and this somehow messed up the correct pip installation etc. Sorry about the alert, I'll close this and only get back if I was to exclude all problems unrelated to qutebrowser.

**Comment by mschilli87** [comment]
@pylipp: Did you make sure to use using Guix's `pip` and not Debian's?

**Comment by The-Compiler** [comment]
The script basically calls `.venv/bin/python3 -m pip install -U pip` and then `.venv/bin/python3 -m pip install PyQt5` - so that *should* definitely be the same pip which just was upgraded... If you have the time, @pylipp, I'd still like to debug this and see if there's anything the script could improve in this case.
