### ISSUE TITLE
Home directory spam

### ISSUE THREAD

**Issue by Yaroslav-95** [qutebrowser/qutebrowser#5538]
**Version info**:
qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
qutebrowser seems to create the directories `database-incognito`, `shared_proto_db` and `VideoDecodeStats` at random at `~/`. It isn't very nice when programs spam your home directory. This kind of directories should go into `~/.cache` or `~/.local/share` (or `$XDG_CACHE_HOME` or `$XDG_DATA_HOME`).

For now my "solution" is to create a cron job that checks and deletes these folders every 10 minutes, but this is more of a hack than an actual solution.

**How to reproduce**
N/A

**Comment by The-Compiler** [comment]
It's not qutebrowser doing this, see [[QTBUG-62957] QtWebEngine creates ~/databases-incognito directory on linux - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-62957)

**Comment by The-Compiler** [comment]
FWIW on Archlinux, this is [fixed](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/qt5-webengine&id=fc7cbcf3af5fe895e7f19a2b8ce6333c150c362c) in qt5-webengine 5.15.0-3 which backports the upstream fix.
