### ISSUE TITLE
Segmentation fault on Debian

### ISSUE THREAD

**Issue by Calebe94** [qutebrowser/qutebrowser#5541]
**Version info**:

qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.5

CPython: 3.8.3
PyQt: 5.15.0

sip: 4.19.23
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.3.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.1.1
Platform: Linux-5.6.0-2-amd64-x86_64-with-glibc2.29, 64bit
Linux distribution: Debian GNU/Linux bullseye/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/calebe94/.cache/qutebrowser
config: /home/calebe94/.config/qutebrowser
data: /home/calebe94/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Every time I try to open my qutebrowser, it get the crash message saying:
"qutebrowser was restarted after a fatal crash."

![](https://i.imgur.com/zaFW6R1.png)

But I can interact with this crash box, it closes after some seconds.

I've tried to launch qutebrowser from terminal and it gets the **segmentation fault** message:
```
[1]    395492 segmentation fault  qutebrowser
```
I've also tried to use ```--temp-basedir``` argument, but I get the same error:
```
[1]    396178 segmentation fault  qutebrowser --temp-basedir
```

I've already removed the ```~/.local/share/qutebrowser/webengine/Service Worker``` and the bug still persists.

I have also tried to install qutebrowser with the virtual environment method, and I still gets the same error.

**Comment by The-Compiler** [comment]
Can you please get a stacktrace, ideally with debug symbols? See https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc

**Comment by Calebe94** [comment]
Well, Ive got this on gdb log before crash:

[gdb_debug_log.txt](https://github.com/qutebrowser/qutebrowser/files/4819548/gdb_debug_log.txt)

And this is the stack trace:
[gdb.txt](https://github.com/qutebrowser/qutebrowser/files/4819545/gdb.txt)

**Comment by The-Compiler** [comment]
Do you get a crash when running `glxgears` as well?

**Comment by Calebe94** [comment]
Yes.
<img width="433" alt="2020-06-23_10-17" src="https://user-images.githubusercontent.com/16101480/85408323-bf462f80-b53a-11ea-92f5-331926dced4b.png">

**Comment by The-Compiler** [comment]
Definitely not a qutebrowser issue then - looks like there are various Debian bugs open already: https://www.mail-archive.com/search?q=iris_dri.so&l=debian-bugs-dist%40lists.debian.org - according to some of them, switching to the modesetting driver (removing `xserver-xorg-video-intel` and maybe adjusting X configuration) seems to help.

**Comment by Calebe94** [comment]
Just to be documented, I've followed [this](http://forums.debian.net/viewtopic.php?t=128974) instructions and now everything works fine.

Thank you so much @The-Compiler for helping me figure this out.

References:
* [xserver-xorg-video-intel driver on newer Intel graphics](http://forums.debian.net/viewtopic.php?t=128974)
