### ISSUE TITLE
Esc as functional input key

### ISSUE THREAD

**Issue by siggines** [qutebrowser/qutebrowser#5553]
Is there a way to use Esc as function key, for example to close an image preview on a website. Without entering normal mode.

For instance shift-esc to stay in insert mode but use the key. 

Sorry if this is already a feature that I don't know about.

**Comment by The-Compiler** [comment]
You can either use passthrough mode (ctrl-v), or do something like `:bind --mode=insert <Shift-Escape> fake-key <Escape>`
