### ISSUE TITLE
`set -t content.proxy` takes 2-5 seconds to apply

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#5557]
**Version info**:
qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.7.8
PyQt: 5.15.0

sip: 4.19.23
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: X.Org, 4.5 (Compatibility Profile) Mesa 20.1.1
Platform: Linux-5.7.6-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i5-3570K_CPU_@_3.40GHz-with-gentoo-2.7, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3.7
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

**Description**

`set -t content.proxy` doesn't apply immediately, but rather takes some seconds to finally work.  i think about 2-5 seconds.

the UI doesn't block, so it feels as if the setting is applied.  but when browsing, it turns out that it wasn't applied, and eventually site is visited with wrong proxy settings.

this delay, which is not indicated by the UI, can lead to leakage of personal data.

**Suggestion**

* remove the delay (if possible)
* make the UI block until the proxy change applies, or allow for certain visual cues to indicate that the proxy change is effective.

**Comment by The-Compiler** [comment]
That delay is coming from QtWebEngine or Chromium, and there's no way for qutebrowser to know when it has been applied. Something might change with #2492 when qutebrowser changes how proxy support is implemented, but other than that, there's little qutebrowser can do. I'll add a note to the docs, though.
