### ISSUE TITLE
Block auto refresh

### ISSUE THREAD

**Issue by lufte** [qutebrowser/qutebrowser#5562]
I'm wondering if it's possible to block auto refresh/redirect techniques like `<meta http-equiv="refresh" content="5; url=http://example.com/">` or the `Refresh` HTTP header. Firefox has a setting for this, `accessibility.blockautorefresh`, but I haven't been able to find an equivalent in Chromium (I haven't checked Webkit). 

In the case the web engines don't support this, is there a way for me to intercept the response, tamper the content, and let it go its way? A greasemonkey userscript would be easy, but they don't run if you have javascript disabled.

**Comment by The-Compiler** [comment]
The only place I can imagine being relevant is `WebEnginePage.acceptNavigationRequest` which gets handled in `_on_navigation_request` in `browser/browsertab.py` (and the backend-specific `browser/webengine/webenginetab.py` / `browser/webkit/webkittab.py`).

Trying with http://www.isthe.com/chongo/tech/comp/cgi/index.html, I get:

```
09:17:28 DEBUG    webview    browsertab:_on_navigation_request:1039 navigation request: url http://www.isthe.com/chongo/tech/comp/cgi/cgidemo.html, type Type.redirect, is_main_frame True
```

But I'm not sure what other types of redirects this will include - also see #4534.

There's no way to tamper with the response other than JS. However, I think you should be able to use `@qute-js-world user` in the greasemonkey header to run it in a custom JS world which works even if JS is turned off for the page. I haven't tested that though, and I have to admit it's largely undocumented.

**Comment by lufte** [comment]
> The only place I can imagine being relevant is `WebEnginePage.acceptNavigationRequest` which gets handled in `_on_navigation_request` in `browser/browsertab.py` (and the backend-specific `browser/webengine/webenginetab.py` / `browser/webkit/webkittab.py`).

Awesome, that worked. Thanks!
 
> Trying with http://www.isthe.com/chongo/tech/comp/cgi/index.html, I get:
> 
> ```
> 09:17:28 DEBUG    webview    browsertab:_on_navigation_request:1039 navigation request: url http://www.isthe.com/chongo/tech/comp/cgi/cgidemo.html, type Type.redirect, is_main_frame True
> ```

In my case `navigation_type` is `'other'`, which definitely makes it impossible to add a setting to block these types of redirects. But anyway, a bit of hacking in `config.py` was enough to to block them in this particular site at least. I'll leave the code in case someone wants to do something similar.

```python
from qutebrowser.browser.browsertab import AbstractTab
AbstractTab._old_on_navigation_request = AbstractTab._on_navigation_request
def new_on_navigation_request(self, navigation):
    self._old_on_navigation_request(navigation)
    if navigation.url.toString().startswith(PROBLEMATIC_URL):
        navigation.accepted = False
AbstractTab._on_navigation_request = new_on_navigation_request
```
