### ISSUE TITLE
Statusbar error on start

### ISSUE THREAD

**Issue by ykonstant1** [qutebrowser/qutebrowser#5565]
**Version info**:
The package comes from the arch linux main repo.  Details:

```
qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0
```

**Does the bug happen if you start with `--temp-basedir`?**:

No.

**Description**
When I run qutebrowser, I get the message:
```set: NoOption error: No option statusbar.hide```

**How to reproduce**

I had the previous version of Qutebrowser with the ```statusbar.hide``` option set via the console; when it updated to the new version, the setting somehow remained and it throws an error every time I open qb.

Now I did set the new statusbar option (again via the console) and I get the status bar settings that I like, but the error message persists.  I do not know how to "unset" the old variable that no longer exists.

**Comment by The-Compiler** [comment]
Can you do `:report` so I can take a look at the logs?

**Comment by ykonstant1** [comment]
I did a report, scanned its contents and realized there was no error; I was the one who had a bad setting: I had aliased qutebrowser with ```qutebrowser -s statusbar.hide=true``` in my ```.zshrc``` and had forgotten about it.  So the new version was passed an unknown option and complained.

**Comment by The-Compiler** [comment]
Ah, that explains it! I'd recommend setting that via `:set` or a `config.py` instead, see the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).
