### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by Unknow0059** [qutebrowser/qutebrowser#5568]
**Version info**:
1.13 version. The latest one. Can't check, cuz you know, it doesn't start, so flags don't work.
I updated from 1.12 to see if the issue would disappear, but it did not.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Does not start.
In ProcessHacker, qutebrowser shows up in the log as a program that was started but is then closed immediately.
![image](https://user-images.githubusercontent.com/25656892/86517454-76765c80-bdff-11ea-9e35-8a3828d703ab.png)
I've attached the Process Monitor log file ([Logfile.zip](https://github.com/qutebrowser/qutebrowser/files/4873439/Logfile.zip)), it includes the point at which qutebrowser is first mentioned and the point at which it is last mentioned.
I've had a similar issue with [another GitHub program recently](https://github.com/hydrusnetwork/hydrus/issues/244), but for that, changing the version of pyinstaller fixed it.

Months ago I used to be able to start qutebrowser; I stopped using it when it no longer did.

"Everything" is a program to find files quickly, and as far as I know, does nothing to them that File Explorer wouldn't do.
"Core" is a piece of software installed by an internet banking website used by another user on this PC whose executable and service I cannot terminate.

OS: Windows 10 Pro 1909 10.0.18363.900 64-bit

**How to reproduce**
1. Run qutebrowser.exe

**Comment by toofar** [comment]
Can you try using this to get log output from qutebrowser?: https://github.com/qutebrowser/qutebrowser/issues/5244#issuecomment-652900376
So extract that .com file into the same folder as the qutebrowser binary, drag the .com into a cmd.exe window and add `-T --debug` on the end. Maybe it'll print out a reason.

**Comment by Unknow0059** [comment]
@toofar 
![image](https://user-images.githubusercontent.com/25656892/86522495-05519c00-be35-11ea-8046-f2df4b940b0c.png)
I had to download the file by using wget because my chromium-based browser did not allow me to download it.

**Comment by bitraid** [comment]
It's a false positive - I'll look into it. Out of 72 AV engines in VirusTotal, 4 (including Microsoft) "think" it's some kind of trojan: [link](https://www.virustotal.com/gui/file/f7998c04494e5c51a01ddb5186a6d237b35e556e28f7cda3f01f199ac2cae34e/detection)
It's very easy to compile the source if you don't trust the binary: just download [fasm](https://flatassembler.net/) and run `fasm conwrap.asm qutebrowser.com`

**Comment by Unknow0059** [comment]
@bitraid I compiled directly into the qutebrowser dir, because it was still being recognized as a virus.
And I can't run it anyway, because of that.
![image](https://user-images.githubusercontent.com/25656892/86529344-65bcf980-be86-11ea-8e4b-bab569b212ae.png)

**Comment by bitraid** [comment]
Yes, you have to add an exception. Also, the name must be `qutebrowser.com` and not `conwrap.exe`.

**Comment by Unknow0059** [comment]
> Yes, you have to add an exception. Also, the name must be `qutebrowser.com` and not `conwrap.exe`.

I recompiled with the correct name before replying and it had made no difference.
I can't exclude the file from Windows Defender because it fails to open the file because ""it has a virus".

**Comment by bitraid** [comment]
https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security

**Comment by Unknow0059** [comment]
You did not believe my description. Here is evidence:
![animation](https://user-images.githubusercontent.com/25656892/86529858-8e46f280-be8a-11ea-9b8b-16c99de21f25.gif)

**Comment by bitraid** [comment]
Add the whole directory. Then compile in it.

**Comment by Unknow0059** [comment]
![image](https://user-images.githubusercontent.com/25656892/86530172-db2bc880-be8c-11ea-96f1-e4bf750eab64.png)
> Maybe it'll print out a reason.
Unfortunately nothing came out of it.

**Comment by bitraid** [comment]
Can you run `echo %errorlevel%` right after `qutebrowser.com`, and see what number it returns?

**Comment by Unknow0059** [comment]
> Can you run `echo %errorlevel%` right after `qutebrowser.com`, and see what number it returns?

It returned `9009`.

**Comment by bitraid** [comment]
That’s strange. From what I see from your log, qutebrowser doesn’t get the chance to do anything. The process exits right after `ntdll.dll` and nothing else is loaded. Are you able to run an older version?

**Comment by bitraid** [comment]
>I've attached the Process Monitor log file (Logfile.zip), it includes the point at which qutebrowser is first mentioned and the point at which it is last mentioned.

So it's not the full log of  `qutbrowser.exe` process?

**Comment by Unknow0059** [comment]
> Are you able to run an older version?

I'm gonna try a version older than 1.12 and 1.13.
> Is it not the full log of the qutebrowser.exe process?

Included is the point at which the process is first mentioned, and at which it is last mentioned. 
Everything else is not at all related to `qutebrowser.exe`, because it either hadn't started yet, or had already exited. Thus I did not include it in the log.
The last point at which it is mentioned is in the path of core.exe.
(...)
I have tried to run version 1.10.2. The exact same thing happened - it exited immediately after `ntdll.dll`.

**Comment by bitraid** [comment]
Before capturing a log with ProcessMonitor, you should first add a filter where you set: "Process Name" "is" "qutebrowser.exe" "then" "include". Make sure the default exclusion list is selected - this way only qutebrowser will be captured. Save and post the whole log - don't select individual items.

**Comment by The-Compiler** [comment]
I built a build with PyInstaller's debug logging enabled - hopefully that'll print something interesting to tell us what's going on. Could you give that a try, @Unknow0059? https://qutebrowser.org/tmp/debug

**Comment by Unknow0059** [comment]
qutebrowser started fine in the debug build.
I can confirm that the normal build still does not start.
This is the log, but I suspect it's nominal: 
[qtblog.txt](https://github.com/qutebrowser/qutebrowser/files/4879388/qtblog.txt)

**Comment by The-Compiler** [comment]
There might have been some changes in PyInstaller in the meantime - qutebrowser is currently using the PyInstaller development branch, since it needs some Qt fixes in there which haven't made it into a PyInstaller release yet...

I just uploaded regular non-debug builds to https://qutebrowser.org/tmp/debug/ - do those work as well?

**Comment by Unknow0059** [comment]
Neither non-debug build worked.

**Comment by The-Compiler** [comment]
Huh, that is weird. So the debug builds worked, but the non-debug ones don't start at all, correct? I'm a bit out of ideas at this point...

**Comment by bitraid** [comment]
@Unknow0059 If that's all there is in your log, then most probably `C:\Program Files\Diebold\Warsaw\core.exe` (Diebold Nixdorf - Protection Module) is killing qutebrowser for the affected builds.

**Comment by bitraid** [comment]
You could [use Winows Sandbox](https://www.windowscentral.com/how-use-windows-sandbox-windows-10-may-2019-update) (if your cpu supports virtualization) and run qutebrowser from there, to figure this out without removing that software.

**Comment by Unknow0059** [comment]
> You could use Winows Sandbox
qutebrowser's newest version (1.13) started in Sandbox normally.

**Comment by bitraid** [comment]
> qutebrowser's newest version (1.13) started in Sandbox normally.

Can you also try with that banking software installed?

**Comment by Unknow0059** [comment]
Cannot. It seems it automatically installs itself after installing the parent banking software, plus a restart. Couldn't find any extra setup files.
Windows Sandbox does not support restarts.

**Comment by Unknow0059** [comment]
Cannot. It seems it automatically installs itself after installing the parent banking software, plus a restart. Couldn't find any extra setup files.
Windows Sandbox does not support restarts.
I removed the parent software plus the one where core.exe comes from.
I can now start qutebrowser normally.

**Comment by Unknow0059** [comment]
Cannot. It seems it automatically installs itself after installing the parent banking software, plus a restart. Couldn't find any extra setup files. Also Windows Sandbox does not support restarts.
(...) 
I removed the parent software plus the one where core.exe comes from.
I can now start qutebrowser normally.

**Comment by The-Compiler** [comment]
Thanks @bitraid for helping to debug this, and @Unknow0059 for testing all those things!
