### ISSUE TITLE
Devtools `Esc` keypresses ignored

### ISSUE THREAD

**Issue by mdtusz** [qutebrowser/qutebrowser#5575]
**Version info**:

qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Description**

When opening a "docked" instance of devtools (i.e. in the same window frame), the escape keypress escapes from insert mode and leaves focus, so cannot be used for toggling the devtools console. When opened non-docked (i.e. in a separate window usng `:wIw`), things behave as expected.  

**How to reproduce**

1. Open a new window to a page.
2. Open the devtools with `:wIj` (or any other docked variant)
3. Click on the devtools to give focus and enter insert mode.
4. Press `Esc`. The first press will leave insert mode.
5. Press `Esc` again. Nothing happens, as we are already in normal mode for the whole window. 

Trying to enter passthrough mode `<Ctrl+V>` does not seem to work on the devtools pane either to avoid exiting insert mode.

**Comment by The-Compiler** [comment]
I wasn't aware of this keybinding in Chromium. I guess the best you can do at the moment if you want to use it is binding a different key to `leave-mode` in normal mode, or indeed use passthrough mode for the devtools.

In the long run, it might be possible to use commands such as `:fake-key` for the devtools, or have an entirely different keyboard mode for them - see #1504 for that.

> Trying to enter passthrough mode `<Ctrl+V>` does not seem to work on the devtools pane either to avoid exiting insert mode.

Works fine for me. Maybe what's happening for you is that clicking the devtools goes to insert mode again? I fixed that in 64d3c04d4dee8130787ce8dc795485310beed181 a couple of days ago.

**Comment by mdtusz** [comment]
Ah you're right - the passthrough mode does seem to work - I was entering back into insert mode when I clicked.
That will do the trick for the time being.

Thanks and sorry for the false alarm!
