### ISSUE TITLE
Dead keys do not work in insert mode

### ISSUE THREAD

**Issue by leephillips** [qutebrowser/qutebrowser#5579]
**Version info**:
qutebrowser v1.13.0
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.4

CPython: 3.7.5
PyQt: 5.12.3

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 5.1.2
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
(On Ubuntu 19.10) When entering text in text fields on all websites, the compose key (for entering accents, etc.) has no effect; the dead-greek key (for entering Greek letters) has no effect; the control key (for copy, paste, etc.) has no effect. Only the Shift key works. This all works as expected in every other browser and application, including all terminal programs. I tried the QtWebkit backend as well, and experienced the same problem.

**How to reproduce**

Enter text in any text field on any website, for example the search box on DDG. While in insert mode, use the compose key or dead-greek key to enter characters. The result is the same as if the keys are inoperative.

**Comment by The-Compiler** [comment]
Can you try with another application using QtWebEngine, e.g. KDE Falkon / QupZilla? This is likely a Qt bug which has been fixed in later Qt versions.

**Comment by leephillips** [comment]
I installed Falkon and tried: and you are right, it has exactly the same problem. Mt Qt is the latest available in my repository, so I guess I have to try to install a later version from whereever it's maintained?
Thank you very much for your super-fast explanation. And for qutebrowser, which is beautiful.

**Comment by leephillips** [comment]
Guess this is not really a qutebrowser issue

**Comment by The-Compiler** [comment]
That's how Ubuntu works I'm afraid - you won't get any (non-critical) updates unless you upgrade to the next Ubuntu release (i.e. 20.04 in your case). As an alternative, you could [install qutebrowser via virtualenv](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#tox), but that'll mean you don't get any support for proprietary codecs like h264/mp4.
