### ISSUE TITLE
qute-lastpass lists passwords with domain name contains the domain as a substring

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#5581]
**Version info**:

Latest master.

**Does the bug happen if you start with `--temp-basedir`?**:

Likely.

**Description**

When I use the `qute-lastpass` userscript with the `-m` option, if the domain name is short (for example `ab`), I might get password suggestions from other unrelated sites too (such as `zzzabzzz`, it only happens to contain `ab` as a substring)

Possible patch: add `\b` around the domain in the domain regex.

(*by the way, the `.*` are unnecessary and can be removed*)

**Comment by The-Compiler** [comment]
cc @welps :wink:

**Comment by user202729** [comment]
Other notes:

* Currently the regex is not escaped correctly. `.` in site name can match anything.
* I've just noticed that the search is matched against the "name", not the URL as I expected (what's the URL field used for if not matched against?...) -- but (I think) this is a problem with the LastPass CLI.

**Comment by welps** [comment]
I'll take a look at the first issue. The second is behavior from `lpass show` as you thought.

Sent from Nine
________________________________
