### ISSUE TITLE
Default binding for tab-focus

### ISSUE THREAD

**Issue by perrin4869** [qutebrowser/qutebrowser#5585]
By default, `T` is bound to `tab-focus`, which seems like a useless binding, since it just moves you to the next tab, much like `tab-next`. It almost seems like the real intent of `T` was to be bound to `set-cmd-text -s :tab-focus `, since this allows for navigating the tabs quickly. Am I correct, or did I misunderstand the `tab-focus` command?

**Comment by The-Compiler** [comment]
`:tab-focus` can be used with a count, so e.g. `5T` takes you to the 5th tab.

**Comment by perrin4869** [comment]
Oh, got it! Thanks!
