### ISSUE TITLE
SETTINGS invalid number of concurrent streams

### ISSUE THREAD

**Issue by daniel-Jones** [qutebrowser/qutebrowser#5588]
**Version info**:
qutebrowser v1.12.0
Git commit: 
Backend: new QtWebKit (WebKit 602.1)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When accessing https://www.atlassian.com/ (only website come across for now) a qutebrowser error page is shown saying >SETTINGS invalid number of concurrent streams

Terminal gives output:
```
08:51:57 ERROR: connection error: SETTINGS invalid number of concurrent streams
08:51:57 WARNING: stream 1 finished with error: "SETTINGS invalid number of concurrent streams"
08:51:57 ERROR: Error while loading https://www.atlassian.com/: SETTINGS invalid number of concurrent streams
```
website works within another browser.

**How to reproduce**

https://www.atlassian.com/

**Comment by The-Compiler** [comment]
This is an upstream bug in Qt - would be good to have a reproducer outside of QtWebKit though. I'll see if I can cook something up.

**Comment by nightshiba** [comment]
I'm facing the same behavior with https://slovnik.seznam.cz/ using GoldenDict.
```
SETTINGS invalid number of concurrent streams
QtNetwork Error 399
```

**Comment by The-Compiler** [comment]
I've tried reproducing this with a couple of Qt examples (`http`, `downloadmanager`, `download`) and those work fine. I'm afraid I don't have the time to find a minimal reproducer and report this to Qt, but it seems clear that this isn't a qutebrowser bug.

**Comment by lubagov** [comment]
https://bugreports.qt.io/browse/QTBUG-94470

**Comment by RitikDutta** [comment]
yes its a bug, maybe it will be fixed in next update.
until then you can manually install widgets or addons by:
https://store.kde.org
download and install widgets/addons from local file

**Comment by The-Compiler** [comment]
@RitikDutta This doesn't seem to have anything to do with qutebrowser?

**Comment by RitikDutta** [comment]
No, its just an alternative method to get addons.
