### ISSUE TITLE
The browser creates the `.pki/nssdb` directory every time it's run. 

### ISSUE THREAD

**Issue by appetrosyan** [qutebrowser/qutebrowser#5589]
Hi. This is a sort-of duplicate of the #5082 , however, with a bit more digging I've come across the following. 

Chromium fixed that bug, qutebrowser didn't. 

Other QtWebEngine based browsers (i.e. webmacs) don't create the directory. 

**Steps to reproduce**:
connect to any webhost via `https`. 

**expected behaviour**:
no `pki` directory being created. 

**actual behaviour**:
`.pki/nssdb/` being created and populated. 

I suggest closing this issue, reopening #5082, and looking into the configuration for chromium used in Qutebrowser, as they have definitely fixed the issue.

**Comment by The-Compiler** [comment]
The underlying [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1038587) is still open, so this is still a Chromium issue. I just tried with `HOME=/tmp/tmphome webmacs` and I see a `/tmp/tmphome/.pki/nssdb/` as well.
