### ISSUE TITLE
Certain sites take way too long to load

### ISSUE THREAD

**Issue by unmd101** [qutebrowser/qutebrowser#5591]
**Version info**:

qutebrowser v1.13.0
Git commit:
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0
[full version info](https://paste.the-compiler.org/view/4ccd61e9)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Some sites hang with blank white page and only after 5-10 minutes they successfully load. Also, can't find anything unusual in logs and the bug is reproducible with both webengine and webkit backends.

**How to reproduce**

Affected sites: [example1](https://inosmi.ru/), [example2](miped.ru/f/)

**Comment by The-Compiler** [comment]
Works fine here. Can you reproduce with other QtWebEngine based browsers such as KDE Falkon? What about Chromium?

**Comment by unmd101** [comment]
> Works fine here. Can you reproduce with other QtWebEngine based browsers such as KDE Falkon? What about Chromium?
Yes, just tried to reproduce it with Chromium, got the same behavior.

**Comment by The-Compiler** [comment]
That's some issue with your system or internet connection then - I don't have any idea what's happening exactly, though. You might need to use something like Wireshark or mitmproxy to see what's going on.

**Comment by unmd101** [comment]
> That's some issue with your system or internet connection then - I don't have any idea what's happening exactly, though. You might need to use something like Wireshark or mitmproxy to see what's going on.

Strange enough, but I've managed to fix these stutters by disabling javascript on these sites. Anyway, thanks for help.
