### ISSUE TITLE
Translating pages

### ISSUE THREAD

**Issue by AckslD** [qutebrowser/qutebrowser#5592]
Has there been any efforts in supporting translations of pages, perhaps through a [userscript](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc)?

**Comment by The-Compiler** [comment]
Not that I know of (other than the `dict.cc` example at the bottom of that page). Shouldn't be too hard to write one, though.

**Comment by AckslD** [comment]
Alright thanks, I might try to make something

**Comment by AckslD** [comment]
@The-Compiler FYI, I made a userscript for translation using Google translate which you can find here https://github.com/AckslD/Qute-Translate

**Comment by mschilli87** [comment]
@AckslD: Thanks a lot. Give me a ping if somebody adds a more ethical service as I'd like to use it. I am too busy (as always) to give it a shot myself, so I have no right to complain. :wink:

**Comment by AckslD** [comment]
@mschilli87 I could perhaps look into it, did you have a more ethical service in mind :smiley: ?

**Comment by mschilli87** [comment]
@AckslD: Not really. I know deepl.com but never checked them so far. Other alternatives I tried were like Google with a different company and worse performance. :disappointed:

**Comment by AckslD** [comment]
@mschilli87 deepl.com does not seem to translate whole pages as far as I can tell unfortunately

**Comment by The-Compiler** [comment]
Thanks! I added it to the [list of userscripts](https://github.com/qutebrowser/qutebrowser/tree/master/misc/userscripts).

**Comment by JohnBardoe** [comment]
@The-Compiler made another one. now with a JS popup in the bottom right corner!
https://github.com/JohnBardoe/qute-translate-popup

**Comment by bitraid** [comment]
I've been using a simple key binding to translate pages:

```python
config.bind('xt', 'open https://translate.google.com/translate?hl=en&sl=auto&tl=en&u={url}')
```

I also set a search engine URL, so I can translate text by pasting it as a query in command line:

```python
c.url.searchengines = {
...
    'gt'     : 'https://translate.google.com/?hl=en&sl=auto&tl=en&text={}&op=translate',
...
}
```

**Comment by The-Compiler** [comment]
@JohnBardoe Neat! Added to the [list of known userscripts](https://github.com/qutebrowser/qutebrowser/tree/main/misc/userscripts#others) in a52f37878756aa660fb66b7a25c2b56a75e63e35.

You might want to add a screenshot to the readme, screenshots are great! :wink:

**Comment by JohnBardoe** [comment]
@The-Compiler good idea! made a gif
