### ISSUE TITLE
No longer able to detach web inspector into a separate window

### ISSUE THREAD

**Issue by ddevault** [qutebrowser/qutebrowser#5593]
**Version info**:

<details>
<pre>
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: unknown (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.32.3
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: wayland
OpenGL: X.Org, 4.6 (Compatibility Profile) Mesa 20.1.3
Platform: Linux-5.5.13-arch2-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/sircmpwn/.cache/qutebrowser
config: /home/sircmpwn/.config/qutebrowser
data: /home/sircmpwn/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/sircmpwn/.config/qutebrowser/config.py has been loaded
Uptime: 0:35:49
</pre>
</details>

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

I might just be blindly missing the option, but I used to rely on the web inspector being opened in a separate window. In the most recent update, it seems to have forgotten my preference and I can't find the option to change it.

**How to reproduce**

`:devtools`

**Comment by The-Compiler** [comment]
`:devtools ` (with a space) gives you a completion with available positions, and `:devtools window` (or `wIw`) will show them in a separate window (also see the [changelog](https://github.com/qutebrowser/qutebrowser/blob/master/doc/changelog.asciidoc#added-1) explaining those changes in more detail)).

**Comment by wedens** [comment]
`:devtools window`. It lists the options after you type `:devtools `.

**Comment by ddevault** [comment]
Thanks!
