### ISSUE TITLE
Can't write in other language!

### ISSUE THREAD

**Issue by darrSonik** [qutebrowser/qutebrowser#5596]
**Version info**:
qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I can't write in other languages while using this browser. For example, if I switch my input method to Bangla, it still uses the English keyboard layout. I'm using ibus for managing input methods.

**How to reproduce**
Affected sites: Every site.

**Comment by mschilli87** [comment]
A workaround might be using and external editor (Ctrl+E by default) for the time being.

**Comment by The-Compiler** [comment]
I doubt this is a qutebrowser issue. Would indeed be good to know if the same happens in Falkon. Are you sure you have ibus configured correctly for Qt applications?

**Comment by darrSonik** [comment]
> I doubt this is a qutebrowser issue. Would indeed be good to know if the same happens in Falkon. Are you sure you have ibus configured correctly for Qt applications?

Since every other applications (Qt and GTK) I've used so far worked fine without exporting the environment variables / configuring ibus, I didn't bother to export the variables. After seeing your reply, I did so and yes, it solved the problem.
Thanks!



> A workaround might be using and external editor (Ctrl+E by default) for the time being.
> 
> _**edit:** Also: Can you try if KDE Falkon behaves differently?_

No need to use the workaround. And Falcon brings lots of dependency, I'm reluctant to try that for now! Sorry!

**Comment by thangisme** [comment]
Same issue here. I've tried `Ctrl - E` but it said that "Error while spawning editor: execvp: no such file or directory".
I'm using Arch

**Comment by The-Compiler** [comment]
@thangisme Please open a separate issue with the necessary information and more details on what exactly you're inputting how.
