### ISSUE TITLE
Overflowing conten

### ISSUE THREAD

**Issue by bjoern-tantau** [qutebrowser/qutebrowser#5597]
**Version info**:

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

**How to reproduce**

**Comment by bjoern-tantau** [comment]
Sorry, accidently hit enter.

**Comment by mschilli87** [comment]
@bjoern-tantau: That's one of the may advantages of using Ctrl+E to spawn vim for editing form fields. :wink:
