### ISSUE TITLE
Overflowing content with rounded corners is upside down and mirrored

### ISSUE THREAD

**Issue by bjoern-tantau** [qutebrowser/qutebrowser#5598]
It's hard to type this, because it is triggered by github's entry page. So I'll try to attach most relevant information.
Since a few days every overflowing content that has rounded corners gets turned upside down and mirrored. This makes it especially hard to type in longer texts in almost every textarea.
I'm on Wayland, using a Pinephone on Debian Bullseye (testing) so thag might not affect so many people.
As I type this I suspect a workaround might be a user stylesheet disabling rounded corners. I will try that and report back.

![20200718_10h10m47s_grim](https://user-images.githubusercontent.com/8307357/87848558-c108d600-c8e1-11ea-94d9-dbdab351b339.png)

Test file:
```
<textarea style="border-radius: 10px"></textarea>
<iframe style="border-radius: 10px" src="http://www.example.com"></iframe>
```

Versions:
```
qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.4
PyQt: 5.15.0

sip: 4.19.23
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.3.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.32.3
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: wayland
OpenGL: None
Platform: Linux-5.7-pinephone-aarch64-with-glibc2.29, 64bit
Linux distribution: Debian GNU/Linux bullseye/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/aarch64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/bjoern/.cache/qutebrowser
config: /home/bjoern/.config/qutebrowser
data: /home/bjoern/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded```

**Comment by bjoern-tantau** [comment]
Yep, adding a user-stylesheet with
```
* {
  border-radius: 0 !important;
}
```
works as a workaround.

**Comment by mschilli87** [comment]
Is this qutebrowser specific or can you reproduce this with KDE falkon as well?

**Comment by bjoern-tantau** [comment]
Nope, can't reproduce in Falkon.

**Comment by bjoern-tantau** [comment]
But I could reproduce it in admbrowser. So I guess the bug lies in PyQt, right?

**Comment by The-Compiler** [comment]
I don't see how this could be a PyQt bug, PyQt is a relatively thin wrapper over Qt. Are you sure you're using the same Qt version in Falkon?

**Comment by bjoern-tantau** [comment]
I'm a little confused by the output of `qutebrowser --version`. It reports version 5.14.2 for qt but 5.15.0 for PyQt. Falkon reports using 5.14.2. So I guess that in Debian different qt versions are used for python and "normal".

**Comment by The-Compiler** [comment]
Qt and PyQt versions are independent of each other (even though their releases are roughly synchronized). Thus, that means Debian ships Qt 5.14.2 (which both Falkon and qutebrowser use), but ships a newer version of the PyQt wrapper (which uses the older Qt version).

Just to make sure, can you confirm that http://httpbin.org/user-agent shows "Chrome/77.0.3865.129" in both cases?

**Comment by bjoern-tantau** [comment]
Yes, both are showing the same Chrome version. 77.0.3865.129

**Comment by The-Compiler** [comment]
Are you sure both cases are actually using Wayland rendering and not XWayland? i.e. do you have something like `QT_QPA_PLATFORM=wayland` set in your environment for both? I really can't see anything in qutebrowser which could cause this to happen...

**Comment by bjoern-tantau** [comment]
Yes, it is set to wayland.

But a recent updatr apparently setup openGL. And with that the error is gone. It is gone from admbrowser as well.

But now I experience many other glitches. Is there a way to disable openGL in qutebrowser?

**Comment by The-Compiler** [comment]
You can play with the `qt.force_software_rendering` setting, though you'll probably take a performance hit. Closing this now as it doesn't seem like a qutebrowser issue.
