### ISSUE TITLE
Copy on selection interferes with pasting

### ISSUE THREAD

**Issue by arbitrary-dev** [qutebrowser/qutebrowser#5600]
**Version info**:
```
qutebrowser v1.8.3
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
```

**How to reproduce**
1. Copy some text to the clipboard
2. Select some text to replace in browser, in some textarea
3. Paste
4. Observe that the text you recently selected is pasted instead of the one that was in the clipboard

**Comment by The-Compiler** [comment]
Are you running some kind of clipboard manager which synchronizes primary selection and clipboard?

**Comment by arbitrary-dev** [comment]
Hmm, I guess I've set up Vim to use PRIMARY on copy, and Webkit overrides it on selection. So I'd then suggest adding a settings option to disable PRIMARY in Qutebrowser, if it's possible)

**Comment by The-Compiler** [comment]
Nope, that's coming from the underlying QtWebEngine without any way for qutebrowser to influence it. You'd likely see the same with a lot of other applications as well.
