### ISSUE TITLE
Vim ctrl+o execute one command, return to insert/passthrough mode

### ISSUE THREAD

**Issue by Jumblemuddle** [qutebrowser/qutebrowser#5612]
When in insert mode in vim, `ctrl+o` (`:help i_CTRL-O`) can be used to execute a single command and then return to insert mode.
I'd like to be able to bind `ctrl+o` to do this in Qutebrowser when in insert or passthrough mode. I often find myself wanting to scroll the page or switch tabs while in insert mode and then returning to passthrough mode immediately after.

**Comment by The-Compiler** [comment]
You can already do this with a oneliner in `config.py`:

```python
c.bindings.commands['insert'] = {'<Ctrl-O>' + key: command for key, command in c.bindings.default['normal'].items()}
```

Given that this seems to be a quite niche thing, I don't think it makes sense to add something like it by default.

**Comment by Jumblemuddle** [comment]
Thanks for pointing out that this can be done for a few keys manually.

Ideally this could be set up to support *any* key that's pressed after `ctrl+o`, however I can see why that's a niche use case and likely a pain to properly test.

**Comment by The-Compiler** [comment]
With that oneliner, that would already work with any of the bound keys, no?

**Comment by Jumblemuddle** [comment]
It would... I'd quickly read it and thought it was pseudo code showing that it could be done for a single key. I now see that it's looping through all the normal mode bindings.
I think this is exactly what I want. Thanks! :)
