### ISSUE TITLE
Tensorflow doc page triggers repeated loadStarted/loadFinished signals with JS

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5617]
**Version info**:
cee5d0b0d, Qt 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
https://www.tensorflow.org/guide/keras/rnn triggers repeated signals (see `--debug`) somehow, causing the statusbar to "blink" because the progress bar is shown/hidden. Probably an upstream bug?

**Comment by amacfie** [comment]
Does it still happen for you? It doesn't for me.

**Comment by The-Compiler** [comment]
Nope, can't seem to reproduce this anymore, even with Qt 5.15.0.
