### ISSUE TITLE
Qutebrowser freezes

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#5619]
**Version info**:

qutebrowser v1.13.1
Git commit: da585f2b5 on master (2020-07-18 11:39:00 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

Platform: Linux-5.7.9-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)

**Does the bug happen if you start with `--temp-basedir`?**:

I haven't tried `--temp-basedir` since the bug only occurs once every hour or several hours.

**Description**

After a while of usage (an hour? a couple hours?), Qutebrowser will eventually freeze up. My system as a whole is still fine, which makes this bug different from #5294 or #5178. It's only Qb that freezes.

By "freeze" I mean one of two things: in some cases, when I move away from the workspace with Qb (for example, to a workspace with a fullscreen terminal) and then back to the workspace with Qb, the Qb window does not redraw (I still see only the terminal from the previous workspace); in other cases, the Qb window shows back up, but it's totally locked up. In either case, I can't click anything, keybindings don't work, etc.

I have to manually `pkill -KILL qutebrowser` and restart. It tends to remember all my tabs, except sometimes the most recently opened one(s).

**How to reproduce**

Unfortunately I haven't figured out how to reproduce the bug, but I *think* it's connected to opening a new tab/website, because it seems to happen most often when I try to run `:open` or `:open -t`.

It also just happened when I was opening feeds from newsboat using `open_url_in_instance.sh`: I was in my workspace with newboat opening 10-12 different feeds, but when I moved back to Qb, only the first few had opened and then Qb was frozen.

Sorry that I don't have any more information. Is anyone else experiencing this bug? It's been happening for at least a couple of weeks now.

**Comment by The-Compiler** [comment]
Intel graphics with `xf86-video-intel` installed? If so, can you try to uninstall that (i.e. use the modesetting driver) and see if it stillh appens?

**Comment by brianbuccola** [comment]
Yes, I've just uninstalled `xf86-video-intel` and will report back today whether any freezing occurs. Thanks!

**Comment by brianbuccola** [comment]
Quick update: uninstalling `xf86-video-intel` seems to have solved it! No freezing all day. Vielen Dank!

**Comment by The-Compiler** [comment]
FWIW the Arch wiki also recommends using the modesetting driver because of those kinds of bugs. Glad to hear that resolved it, closing this now as I don't think there is anything qutebrowser can do here.
