### ISSUE TITLE
ERR_FAILED when loading websites

### ISSUE THREAD

**Issue by user-b** [qutebrowser/qutebrowser#5627]
**Version info**:
qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.7

The bug happens with --temp-basedir

After rebuilding nixos (this updated qutebrowser I suppose) qutebrowser can't visit remote websites:

```
This site can’t be reached
The webpage at https://duckduckgo.com/?q=pp might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED
```

If I run qutebrowser with `-l debug`, when I try to visit a non local page this error occurs:

```
ERROR webview webenginetab:_error_page_workaraound_1594 Load error: ERR_FAILED
```

I can visit local pages and I have no issues with curl/firefox after this update.

**Comment by The-Compiler** [comment]
This is unlikely to be a qutebrowser issue, that line is just where loading errors coming from the underlying Chromium are printed. Could you try with another browser based on QtWebEngine such as KDE Falkon?

**Comment by user-b** [comment]
Thanks. Neither Falkon (v3.1.0 with QtWebEngine 5.12.7) or google-crome have this issue.

**Comment by user-b** [comment]
Same version of Qutebrowser on the previous generation. And it works fine. Any idea where to start looking? Doesn't seems to be a problem of qutebrowser indeed.

**Comment by The-Compiler** [comment]
No clue. If you start with `--debug-flag chromium` you'll see Chromium's log, but it's a *lot* of noise and usually not much information when things actually go wrong...

Taking the freedom to ping some NixOS people who worked on its qutebrowser package recently - @petabyteboy @rnhmjoj @dotlambda do you have any idea what could be going on here?

**Comment by dotlambda** [comment]
This is probably due to a recent nss update in Nixpkgs. See https://github.com/NixOS/nixpkgs/issues/93955.

**Comment by The-Compiler** [comment]
Yep, that's definitely it - closing this then, as there's nothing qutebrowser can do. Thanks!
