### ISSUE TITLE
Can't use qutebrowser with Tor

### ISSUE THREAD

**Issue by Unser395** [qutebrowser/qutebrowser#5635]
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Hello,

I've tried to launch qutebrowser with the instructions given in the faq (launch tor browser and type ":set content.proxy socks://localhost:9050/" ), but I can't access any websites when I do this. I just get a ERR_PROXY_CONNECTION_FAILED error.

What am I missing ?
Thanks for the help !

**Comment by The-Compiler** [comment]
It doesn't say to launch tor browser. It says to launch Tor itself, which is a daemon listening for proxy connections.

**Comment by Unser395** [comment]
Thank you very much, it's ok now !
Have a nice day
