### ISSUE TITLE
CLI: Add `private-window` target 

### ISSUE THREAD

**Issue by emanuele6** [qutebrowser/qutebrowser#5639]
To open a link in a new `qutebrowser` window from CLI, you can use the following command:
```shell
qutebrowser --target window example.org
```

To open a link a new private window, you need to use:
```shell
# --nowindow is needed because, if qutebrowser isn't running,
# `qutebrowser ':open -p <link>'` will open two windows: one normal, one private
qutebrowser --nowindow ':open -p example.org'
```

It is a bit incovenient; there should be a target for `private-window` in my opinion.

---------------------------------------------
It would also be nice if `qutebrowser --target private-window` (omitting the url) would open a new private window.
This behaviour could also be used for the other targets: `qutebrowser --target tab` currently opens a new window instead of a new tab. 

`qutebrowser --nowindow ':open -p'` can be used to open a new private window, but if there is already a `qutebrowser` window open, it causes my window manager to mark the desktop in which the already-open window is in as urgent (if that is not the focused desktop). (probably `qutebrowser` requests it because it executed a command.)

`qutebrowser --nowindow ':open -w example.org'` also makes the desktop urgent, while `qutebrowser --target window example.org` doesn't. This is why I think a target for private windows is useful.

**Comment by emanuele6** [comment]
> `qutebrowser --nowindow ':open -w example.org'` also makes the desktop urgent, while `qutebrowser --target window example.org` doesn't. This is why I think a target for private windows is useful.

video: https://youtu.be/D615fOJzDxM

**Comment by The-Compiler** [comment]
This is already implemented in git master.

**Comment by emanuele6** [comment]
@The-Compiler Oh, ok. Thank you!

Can you tell me the syntax?

Is it literally `qutebrowser --target private-window <url>`?

**Comment by emanuele6** [comment]
@The-Compiler, does `qutebrowser --target private-window` (omitting the url) open a private window though?

**Comment by The-Compiler** [comment]
> @The-Compiler, does `qutebrowser --target private-window` (omitting the url) open a private window though?

It does for me! Doesn't it for you?

**Comment by emanuele6** [comment]
No, I just asked because I don't know much python and I don't know how to run the git version of `qutebrowser`.

Thank you for answering.

**Comment by mschilli87** [comment]
@emanuele6 
> No, I just asked because I don't know how to run the git version of qutebrowser.

It is documented [here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-qutebrowser-with-virtualenv).

**Comment by emanuele6** [comment]
> It is documented [here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-qutebrowser-with-virtualenv).

Yeah, I read that file right after posting that comment and I figured it out, thank you anyway.
