### ISSUE TITLE
 Use the same hint for links which lead to the same place

### ISSUE THREAD

**Issue by PaperMountainStudio** [qutebrowser/qutebrowser#5641]
Using the same hint for links which have the same location would decrease the amount of hints. This is especially useful on webpages with many links.

# Current behaviour
```
<a href="https://github.com/">github</a>
<a href="https://github.com/">secret place</a>
<a href="https://github.com/">link</a>
```
this produces 3 hints - `a`, `s` and `d`

# Suggested behaviour
produce only one hint and display it 3 times - only hint `a`

# Potential problems
Links like `#` could be used with javascript to provide different functionality on different links even when the href is similar. Are other links used like this too?

**Comment by The-Compiler** [comment]
See #71
