### ISSUE TITLE
whats.new crashes renderer process

### ISSUE THREAD

**Issue by jeLee6gi** [qutebrowser/qutebrowser#5645]
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.5
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: unknown (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.32.3
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.1.4
Platform: Linux-5.7.11-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
the renderer process crashes while trying to load the google service under

whats.new
https://whats.new
http://whats.new

the page loads fine when navigating to

www.whats.new
https://www.whats.new
http://www.whats.new

**How to reproduce**
navigate to whats.new

**Comment by The-Compiler** [comment]
Reported upstream: [[QTBUG-85863] Renderer process crash in blink::CSSMathExpressionNode::ParseClamp on whats.new - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-85863)

**Comment by jeLee6gi** [comment]
Thank you!
