### ISSUE TITLE
how to config proxy server by command?

### ISSUE THREAD

**Issue by zxf-thingsmatrix** [qutebrowser/qutebrowser#5647]
how to config proxy server by command?

**Comment by mschilli87** [comment]
Can you elaborate? There is `:set content.proxy <proxy>` to define a proxy from within qutebrowser (made persistant via `autoconfig.yaml`) but I'm not if that is what you are looking for.

**Comment by zxf-thingsmatrix** [comment]
thanks!

> 
> 
> Can you elaborate? There is `:set content.proxy <proxy>` to define a proxy from within qutebrowser (made persistant via `autoconfig.yaml`) but I'm not if that is what you are looking for.

thanks!

**Comment by mschilli87** [comment]
@zxf-thingsmatrix: For the future, opening qute://settings/ in qutebrowser might help you to better understand available options and their current values.
