### ISSUE TITLE
Is there a way to view pdf with pdf.js in dark mode?

### ISSUE THREAD

**Issue by danielfalbo** [qutebrowser/qutebrowser#5648]
I mean, with the real pdf's colors inverted, like we can achieve with zathura and other pdf viewers. Example:
![Screenshot 2020-08-05 at 16 37 01](https://user-images.githubusercontent.com/39460524/89425980-ec8d1c80-d739-11ea-9348-d372bf137202.png)

**Comment by The-Compiler** [comment]
Doesn't look like it, see https://github.com/mozilla/pdf.js/issues/2071

**Comment by danielfalbo** [comment]
Yeah thank you! I will follow that issue

**Comment by shivaprsd** [comment]
Hi, if you are using pre-built viewer from PDF.js, you might want to have a look at https://github.com/shivaprsd/doq (disclaimer: I am the author).

**Comment by rehman-talha** [comment]
> 

Hello Shiv, I have zero coding experience and I loved your dark mode live demo. Could you please help me install this extension on chrome desktop browser? thanks!

**Comment by The-Compiler** [comment]
@rehman-talha This really isn't the right place to ask for support for installing Chrome extensions. I suggest you take a look at the [docs of the project](https://github.com/shivaprsd/doq#usage), and if those don't help, open an issue there.

**Comment by The-Compiler** [comment]
@rehman-talha If you enter "GitHub how to open issue" into the search engine of your choice, chances are you'll end up at the relevant GitHub documentation: [Creating an issue - GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue)...
