### ISSUE TITLE
Promote `config` module into its own python package

### ISSUE THREAD

**Issue by alejandrogallo** [qutebrowser/qutebrowser#5659]
Hi!

I quite like the way you manage the configuration.
I was thinking if you could consider writing a package out of it
in order for othe people to use the same kind of configuration.

Me personally I would be interested in using it in [papis](https://github.com/papis/papis).
In particular, the way you use context manager for managing per url configurations would be akin
to how we provide configuration settings on a per library basis.

Just a thought.
Thanks for this great project.
Ale

**Comment by The-Compiler** [comment]
I have no plans to do this, sorry. It'd make things harder for qutebrowser maintenance, and lots of things in there are specific to qutebrowser.
