### ISSUE TITLE
Per-domain keybinding

### ISSUE THREAD

**Issue by darrSonik** [qutebrowser/qutebrowser#5661]
Hello!
I've been known about qutebrowser for some time, used and ditched (it crashed often). Then I gave it a try couple of weeks ago and now it's my primary browser.

I wish if I'd be able bind some hotkeys specific to a webpage or domain. Some websites that offer own hotkeys (such as Google Meet offers Control+D to toggle mute and Control+E to toggle video) can be sent to website by using passthrough mode or binding keys with `fake-key`.

I would really like to use `fake-key` on per-domain basis. Would you implement it if possible?

**Comment by The-Compiler** [comment]
See #3636 and #4664
