### ISSUE TITLE
`:debug-keytester`: opening, closing and reopening the keytester window makes the browser crash.

### ISSUE THREAD

**Issue by emanuele6** [qutebrowser/qutebrowser#5676]
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
opening `:debug-keytester`, closing it and then re-opening crashes the browser.

**How to reproduce**
* launch `qutebrowser`:
  ```sh
  qutebrowser --temp-basedir
  ```
* run `:debug-keytester`;
* close the keytester window;
* run again `:debug-keytester` → the browser will crash.

-------------------
crashlog: https://paste.the-compiler.org/view/2a47db91

**Comment by The-Compiler** [comment]
Already fixed in 1ccc22da44f7c78b5c395db832e86ede231691f5
