### ISSUE TITLE
FR: Add `private-window` target to `:hint` command.

### ISSUE THREAD

**Issue by emanuele6** [qutebrowser/qutebrowser#5679]
Add a new target called `private-window` (or `private` or whatever) to the `:hint` command. This target will open the selected link in a new private window.

It's a bit silly that one has to use an userscript to open a link (selected with hints) in a new private window: 
```vim
:hint links userscript open_in_new_private_window
```
```sh
#!/bin/sh
# open_in_new_private_window

echo ":open -p $QUTE_URL" >> "$QUTE_FIFO"
```
Especially since there are already targets to open links in a new window (`window`), in a new tab (`tab`), &c.

Since `private-window` has been added as a target for qutebrowser's CLI, can it also be added as a target for the `:hint` command?

**Comment by emanuele6** [comment]
I didn't know about the `run` target: I guess that..
```vim
:hint links run open -p {hint-url}
```
..can also be used instead of the userscript.

But still, since `window` has a dedicated target, shouldn't this also have a dedicated target?

```vim
:hint links window
```
```vim
:hint links run open -w {hint-url}
```

**Comment by The-Compiler** [comment]
Those two aren't equivalent: The first simulates a Shift-Alt-Click, while the latter opens a window via a qutebrowser command. Thus, `:hint links window` will work on e.g. Javascript click handlers opening a new link, while the `run` variant will not.

There's no good way for qutebrowser to do the same with private windows, and I don't think it makes sense to duplicate what `:hint links run open -p {hint-url}` does.
