### ISSUE TITLE
AltGr not working on nordic keyboard with chars such as @£$

### ISSUE THREAD

**Issue by JacobSandin** [qutebrowser/qutebrowser#5683]
**Version info**:
qutebrowser v1.13.1
Git commit: a99f61071 on HEAD (2020-07-17 17:00:38 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
No, have not tested that; should I?

**Description**
I am using a nordic layout keyboard, and I am not able to use the chars wich are activated by AltGr. Such as @ £ $.
I know about the Windows issues where it can sometimes happen and I also know about the Language that sometimes
can change for a program. I have verified that it at the same time works in other programs and that my language do not
change from swedish when I use the qutebrowser.

**How to reproduce**
As I downloaded it today, I would guess that it is just to run the latest version with a nordic keyboard layout and trying
out for instance AltGr+2 wich should result in @ .  I'm having this on any site so not a specific.

However there can ofcorse be some trick to geting it working, I did see you had AltGr issues a while back, but I think it
might still have value as a bug, considering that a new user such as myself would expect their keyboard to work out
of the box so to say.

Kind regards,
Jacob

**Comment by The-Compiler** [comment]
Can you check whether `:set qt.force_platform windows:altgr` and `:restart` fixes things?

**Comment by JacobSandin** [comment]
It does the trick, thanx I can now login with my email :) You might still consider this to be working by default though :) 

BTW: I realy do like the browser :) so much faster than using mouse.

**Comment by The-Compiler** [comment]
This is a bug in Qt 5.15.0 which is fixed in Qt 5.15.1 already (see #5399 for details) - thus, this will work as soon as that's out and I release a new qutebrowser release with it (late August / early September).
