### ISSUE TITLE
Clicking on the inspector puts the main window into insert mode

### ISSUE THREAD

**Issue by ddevault** [qutebrowser/qutebrowser#5687]
**Version info**:
<details><pre>
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.5
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: unknown (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.32.3
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: wayland
OpenGL: X.Org, 4.6 (Compatibility Profile) Mesa 20.1.6
Platform: Linux-5.8.1-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/sircmpwn/.cache/qutebrowser
config: /home/sircmpwn/.config/qutebrowser
data: /home/sircmpwn/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/sircmpwn/.config/qutebrowser/config.py has been loaded
Uptime: 1:43:13
</pre></details>

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**How to reproduce**

1. Open web inspector
2. Ensure main window is in normal mode
3. Click anything on the web inspector

**Comment by The-Compiler** [comment]
Right - this makes sense for a docked inspector, but not so much for a windowed one. Working on a fix.
