### ISSUE TITLE
qute-pass script gopass mode broken

### ISSUE THREAD

**Issue by aleprovencio** [qutebrowser/qutebrowser#5690]
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
`gopass` latest version (1.10.0) broke this script because it will return a deprecation message if called without arguments.

**How to reproduce**
Run the script on the login form of a domain known from the store and the password if filled with the message `DEPRECATION WARNING: Use gopass show` instead of the password itself.

**Comment by The-Compiler** [comment]
@bascht Do you want to take a look?

**Comment by bascht** [comment]
@The-Compiler Sure, see PR. :-) 

Looks like it's a quick fix, as even `pass` can be called via `pass show […]` – I tested it with 
- pass v1.7.3
- gopass v1.9.2
- gopass v1.10.1
