### ISSUE TITLE
System dialog does not pop up when joining a zoom.us webconference

### ISSUE THREAD

**Issue by glostis** [qutebrowser/qutebrowser#5693]
Hi,

Thanks for the amazing browser! I've installed it a few days ago, customized it, and I now really enjoy using it!

**Version info**:
```
qutebrowser v1.13.1
Git commit: a99f61071 on HEAD (2020-07-17 17:00:38 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

When I open [zoom.us](https://zoom.us) web conference links, I land on a page where a system dialog normally pops up where I can "Open xdg-open" which opens the Ubuntu Zoom client that I have installed.

See the screenshot below taken on Google Chrome showing that page:

![Screenshot from 2020-08-28 15-33-44](https://user-images.githubusercontent.com/25295717/91566931-a431da80-e944-11ea-92ec-f3754f368acc.png)

In qutebrowser, the system dialog never shows up, and instead the tab indicator and the URL in the status bar become red:

![Screenshot from 2020-08-28 15-28-38](https://user-images.githubusercontent.com/25295717/91567101-e0653b00-e944-11ea-97c0-f6853d0ca26e.png)

I can work around the problem by manually clicking on the "launch meeting" link which then successfully opens the Zoom client, but that's not ideal.

**How to reproduce**

This issue can easily be reproduced by navigating to [zoom.us/test](https://zoom.us/test) and then clicking on "Join".

Does this issue happen because Qt WebEngine and/or qutebrowser does not support "system dialogs", or am I just missing a setting that would solve the problem?

Thanks!

**Comment by mschilli87** [comment]
@glostis: Can you reproduce this behaviour with KDE Falkon?

All I can do for now is to confirm the behaviour you see in qutebrowser.

**Comment by glostis** [comment]
Hi @mschilli87, thanks for looking into this!

In KDE Falkon, there is also a bug, but the behavior is slightly different (worse than Qutebrowser, actually).
When I click on "Join", the "When system dialog prompts" page appears very briefly (<1s) but no system dialog pops up, and I am then redirected to a zoommtg://zoom.us/... URL which is the URL protocol that is supposed to be handled by the Zoom client, but this does not open the Zoom client.

See attached screen recording:

![falkon-zoomus](https://user-images.githubusercontent.com/25295717/91589781-9dae5d80-e95a-11ea-9fb4-540836bc19f1.gif)

**Comment by The-Compiler** [comment]
This is indeed a limitation of QtWebEngine - by default, external URLs can only be opened after an user interaction (like clicking a link). See the related Qt issue: [[QTBUG-84108] Add an "ask" UnknownUrlSchemePolicy - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-84108)

You should be able to do something like `:set -u zoom.us content.unknown_url_scheme_policy allow-all` to always allow zoom.us to open those links, though.

**Comment by glostis** [comment]
Thanks @The-Compiler, the solution you suggested works like a charm!
