### ISSUE TITLE
Why does Alt+9 not focus on the ninth tab?

### ISSUE THREAD

**Issue by mschilli87** [qutebrowser/qutebrowser#5694]
Unlike most other browser users I know personally, I tend to use bookmarks over open tabs to get back to something later.
Thus, I usually have less than 10 tabs open. Sometimes however, even I 'need' more. Right now, for example, I have 11 tabs open.

Because of that, I got used to switching tabs via `Alt+[number]` instead of `[count]T` to save a keypress.
As long as I have 9 tabs or less, all is fine.
But once I hit the 10 tab mark, I can't switch to the ninth tab anymore via Alt+9 since this key combination now switches to the tenth tab.

The reason is the that by default `<alt-1>` to `<alt-8>` are bound to `tab-focus 1` to `tab-focus 8` but `<alt-9>` is bound to `tab-focus -1`. I can change this in my local config (and likely will) but I was wondering what was the reasoning behind this decision.
I find it very irritating.
My suggestion would be binding `<alt-9>` to `tab-focus 9` and assign `tab-focus -1` instead to `<alt-0>`: There is no zeroth tab, so Alt+0 can't mean the same as Alt+1 to Alt+9 the previous keys. If I had to guess, I would maybe assume to represent `tab-focus 10` based on 0 following 9 on the number row, but switching to the last tab instead makes sense (to me) for *this* key.

So please just let me know if I should change my local configuration or prepare a PR. :wink:

**Comment by The-Compiler** [comment]
The main reasoning behind it is that pretty much all other browsers (Chrome, Firefox, ...) do the same. I think it makes sense for qutebrowser to be consistent here, so that'd not something I'd like to change in the defaults.

**Comment by mschilli87** [comment]
That's a very good reason!
