### ISSUE TITLE
If  "tabs.tabs_are_windows" is set "tab-close" should map to "close"

### ISSUE THREAD

**Issue by markstos** [qutebrowser/qutebrowser#5695]
If "tabs.tabs_are_windows" is set, it's likely because a window manager is managing the windows as tabs. In these this case, it would be natural for "d" or "<Ctrl> w" to close the window. Instead, they do nothing.  I confirmed that this workaround works:

     :bind <Ctrl-w> close
     :bind d close

Thanks!

**Comment by The-Compiler** [comment]
You can also do `:set tabs.last_close close` to get the same effect. Agreed it'd probably make sense to do that automatically with `tabs_are_windows` set.

**Comment by markstos** [comment]
Also if "tabs_are_windows" is set, "Open Link in New Tab" could be removed from the context menu, if that's feasible.

**Comment by mschilli87** [comment]
@markstos: AFAIK, qutebrowser does not touch the context menu at all so far, See https://github.com/qutebrowser/qutebrowser/issues/349 for other suggestions in this regard. Once this is done, your suggestion might be feasible.

**Comment by C0DK** [comment]
I'm working on a potential fix, however i have to figure out how to run all the magnificant tests locally first hehe. Haven't worked with qt software systems before.

**Comment by The-Compiler** [comment]
@C0DK See the [contribution docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/contributing.asciidoc) - you should be able to run something like `tox -e py38-pyqt515` for example. Or feel free to push a draft PR and let the CI run the tests.

**Comment by C0DK** [comment]
@The-Compiler do you have time to look at the PR? I don't normally use BDD, so I don't really know how to deduce the actual test from output

**Comment by markstos** [comment]
Thanks!
