### ISSUE TITLE
Autofoucs / steal focus on search field on page load !!

### ISSUE THREAD

**Issue by tami5** [qutebrowser/qutebrowser#5702]
**Version info**:

qutebrowser v1.13.1
Git commit:
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.5
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.1.5
Platform: Linux-5.7.12-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
I've search for hours for an option to disable this annoying behavior. Basicly it happens when I search in github and other sites. I search for something, then try to navigate with `j` but doesn't work, then after switch focus with `tab` jk works.

I've gotten to the habit of pressing tab each time a got to the next pages. which is very painful.
**How to reproduce**

- Search on github,
- wait to page load, 
- try to go down a page with `j`

**Comment by The-Compiler** [comment]
I can't reproduce this based on your instructions - how exactly are you searching on GitHub? Does the input field still have focus after the page load?

When I go to https://github.com/search, enter a search term and press enter, on the newly loaded page the search input isn't focused, and I can use `j` just fine to scroll down.

**Comment by tami5** [comment]
Oh, Sorry about that, for this to reproduce minimize the winodw vertical to the point that the search appers the top. https://imgur.com/kGl4oTs 

This is not unique to github, as it happens other websties, when the input appers at the top like that style.

**Comment by The-Compiler** [comment]
This is because the search input has the focus after the page load, and hjkl simulates cursor keypresses - you'll see the same when using the cursor keys in e.g. Chromium as well. That being said, #3691 will likely help once I get around to taking a look at that.
