### ISSUE TITLE
Where should I set $PATH environment so qutebrowser can see it? (mpv / youtube-dl issue)

### ISSUE THREAD

**Issue by tobip** [qutebrowser/qutebrowser#5712]
**Version info**:
```
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0
```

**Description**
I try to `:spawn mpv <youtube-url>` which doesn't work because it can't find `youtube-dl` which is located in `/home/username/.local/bin/youtube-dl` in my case.

I add the `/home/username/.local/bin` to my path in `~/.bashrc` which seems to have no effect on quetbrowsers environment.

Can you tell me how or where to set my `$PATH` to make this work?

**Comment by The-Compiler** [comment]
Depends a bit on details like your desktop environment / login manager / distribution - but usually something like `~/.profile` - either case, same like with any other GUI application. Note that it'll require a re-login most likely.

**Comment by tobip** [comment]
I could solve it by creating the file `/etc/profile.d/qutebrowser.sh` containing this line:
`export PATH=$PATH:/home/my_username/.local/bin`

Then after logging out and back in to my system it worked.
