### ISSUE TITLE
Scroll wheel dropping steps

### ISSUE THREAD

**Issue by NCrustand** [qutebrowser/qutebrowser#5718]
**Version info**:
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Mouse scroll wheel skips steps when scrolling. Always the first 1 to 4 or so "clicks" of the scroll wheel is ignored by qutebrowser and it doesn't start scrolling immediately. It also skips a step here and there after scrolling some distance. After having scrolled a little the scroll is now "warmed up" for a few seconds an don't required extra scrolling before working, but after not scrolling for a few seconds the start scrolling delay comes back.

Issue exists in both webkit and webengine, scrolling works fine in firefox and other applications. I also confirmed with xev that the OS does indeed receive all the scrolling  "clicks".

**How to reproduce**
Open a page too big to fit on screen and try to scroll with scroll wheel. The first few scrolling steps are ignored and also random scrolling steps are dropped randomly in the middle of scrolling.

**Comment by NCrustand** [comment]
I don't know if this is relevant, but when started from a terminal I get the following warning over and over when the problem is happening. Also I noticed that it might be worse on websites with a lot of images.
```
libpng warning: Skipped (ignored) a chunk between APNG chunks
```

**Comment by The-Compiler** [comment]
Works fine for me, and this is the first time I hear about this. Anything special about your setup/configuration?

Can you try with a newer Qt/qutebrowser version, e.g. via a [virtualenv install](https://qutebrowser.org/doc/install.html#tox)? What about other projects using QtWebEngine such as KDE Falkon?

**Comment by NCrustand** [comment]
Tried running the latest version of qutebrowser cloned from master branch, same problem. Falkon browser on the other hand works flawlessly and the warning messages mentioned above doesn't show up either. Seems likely there is a connection with those warning messages.

I run Ubuntu with i3wm in VMWare on a Windows 10 host, but not too sure it is relevant as scrolling works perfectly in any other application, both on the host and guest.

**Comment by The-Compiler** [comment]
That warning only should be shown on pages with APNG images, and should probably be reported as an Ubuntu bug, see #5473. I'd expect it to show up with Falkon as well though.

What do you mean with "Tried running the latest version of qutebrowser cloned from master branch" exactly - did you also install PyQt/Qt in a virtualenv like mentioned above? Can you show the full `:version` output for both setups please?

**Comment by NCrustand** [comment]
Is there an option somewhere to disable/enable hardware acceleration or something similar that I could test?

**Comment by The-Compiler** [comment]
There's the `qt.force_software_rendering` setting - note it requires a `:restart`.

**Comment by NCrustand** [comment]
No, just ran the downloaded qutebrowser. Not sure how to do the virtualenv thing.
```
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8

CPython: 3.8.2
PyQt: 5.14.1

sip: 4.19.21
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform: Linux-5.4.0-47-generic-x86_64-with-glibc2.29, 64bit
Linux distribution: Ubuntu 20.04.1 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/lars/.cache/qutebrowser
config: /home/lars/.config/qutebrowser
data: /home/lars/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 1:37:42
```

```
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v1.13.1
Git commit: da3d793fd on master (2020-09-14 18:42:43 +0200)
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8

CPython: 3.8.2
PyQt: 5.14.1

sip: 4.19.21
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: VMware, Inc., 3.3 (Compatibility Profile) Mesa 20.0.8
Platform: Linux-5.4.0-47-generic-x86_64-with-glibc2.29, 64bit
Linux distribution: Ubuntu 20.04.1 LTS (ubuntu)
Frozen: False
Imported from /home/lars/build/qutebrowser/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /tmp/qutebrowser-basedir-x7oy10ju/cache
config: /tmp/qutebrowser-basedir-x7oy10ju/config
data: /tmp/qutebrowser-basedir-x7oy10ju/data
runtime: /tmp/qutebrowser-basedir-x7oy10ju/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:06
```

**Comment by The-Compiler** [comment]
Please see the [instructions](https://qutebrowser.org/doc/install.html#tox) I've linked above. I suspect Ubuntu's build of Qt/PyQt is to blame somehow, similar to #5473.

**Comment by NCrustand** [comment]
Okay, I installed in virtualenv as described in the link. It feels as if it might have helped a little, but it still misses the first 1 scroll step when starting to scroll, and also misses randomly a step occasionally, but feels as if it works a little better. Also the warning messages about APNG has disappeared when using virtualenv version.
Problem still persist, but feels like it is probably a slightly better.

**Comment by NCrustand** [comment]
Also, I noticed now that it also affects scrolling with j/k keys.

**Comment by The-Compiler** [comment]
Hmm, what if you run something like `.venv/bin/python3  scripts/testbrowser/testbrowser_webengine.py somewebsite.org` inside the qutebrowser repository?

**Comment by NCrustand** [comment]
Same result in the testbrowser

**Comment by The-Compiler** [comment]
Not much qutebrowser can do about it then, as the testbrowser is [as minimal as it gets](https://github.com/qutebrowser/qutebrowser/blob/v1.13.1/scripts/testbrowser/testbrowser_webengine.py#L40-L51). Closing this, as it looks like an issue on your system, or perhaps PyQt/Qt somehow.

I don't know what else I could suggest, sorry. I wouldn't expect the issue to be in PyQt as it's just a relatively thin wrapper over Qt, but if it doesn't happen in Falkon, Qt shouldn't be the issue either (if Falkon is using the same Qt install/version).

You might want to report a bug against Ubuntu's PyQt package to find out more. The APNG warning also seems like a bug in their QtWebEngine package, but again I don't understand why you wouldn't get those messages in Falkon.

**Comment by NCrustand** [comment]
Okay, after a little more testing I have figured out that I have the same problem in both Ubuntu and Arch, running under both VMWare and Virtualbox. On the host running Windows qutebrowser works fine. So I am a little confused as to where I should report the bug, especially since you ruled out both PyQt and Qt.

**Comment by The-Compiler** [comment]
Can you test the C++ testbrowser as well? If you install `qt5-qmake-bin` and `libqt5webengine5` (under Ubuntu), I *think* you should be able to change to the `scripts/testbrowser/cpp/webengine/` folder in the repository and run `qmake`, `make` and `./testbrowser somewebsite.org`. If you can't get it to build with Ubuntu, might be easier to do so with Arch.

**Comment by NCrustand** [comment]
Yup, same problem there as well. Even tried using chromium now, and the problem is there also. So this problem is definitely not a qutebrowser bug, but I still can't figure out what is the culprit though.

**Comment by The-Compiler** [comment]
Strange that it wouldn't show up in Falkon. No idea where the culprit is either...

You might want to try open a [bug against Chromium](https://bugs.chromium.org/p/chromium/issues/entry), they might have some better way to debug this kind of thing.

**Comment by NCrustand** [comment]
Okay, thanks for all your help. I will try filing a bug against Chromium, and maybe Qt/PyQt and hope they are able to figure it out.

And, I really love qutebrowser btw, keep up the good work!

**Comment by The-Compiler** [comment]
I don't think there's much Qt/PyQt will do if the bug is upstream in Chromium. Please link the Chromium bug here when you open one though, as I'm curious what they'll say!

**Comment by NCrustand** [comment]
Here is the Chromium bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1128405

**Comment by NCrustand** [comment]
FYI I noticed that the problem _is_ actually present in Falkon also after all
