### ISSUE TITLE
redirecting .html file get stuck in cache, reload (of target page) with 404 doesn't clear

### ISSUE THREAD

**Issue by greg-minshall** [qutebrowser/qutebrowser#5722]
**Version info**:

qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:

no.

**Description**

it seems as if a **redirecting** .html file gets stuck in the cache, and that doing a `reload` that results in a `404` (because of a configuration change on the server) doesn't clear the files from the cache. after enough time, it appears the cache entry for the redirecting .html file, at least, is cleared.

if this is indeed a bug, and if it seems to be from qtwebengine, and if you'd like me to try reporting it upstream, please let me know and i'll attempt to do so.

**How to reproduce**

1. site `a.example.com` (for example) is configured such that `qutebrowser a.example.com` opens `a.example.com/index.html`.

2. the first version of `index.html` redirects to a file `bar.html` (see below for contents of this version of `index.html`).

3.  in *my* case, `bar.html` actually then loads a .gz file, and then presents that.  i suspect this is immaterial.  (but, who knows.)

4.  launch qutebrowser (`--target-window`), "opening in existing window", see the contents as presented by `bar.html`.

5.  quit that particular qutebrowser window.

6.  remove `bar.html` [and the associated .gz file].  restart the webserver on `a.example.com`.

7.  replace `index.html` with a typical index.html, a `"hello, world"` one, say.

8.  launch qutebrowser as in `4`.  one sees (presumably via the cache) the previous contents.  and, `yank url` shows `a.example.com/foo.html`.

9.  `reload`.  see a `404`.  `yank url` shows `a.example.com/foo.html`.

10.  `reload`.  same results as `9`.

11.  quit that particular qutebrowser window.

12.  again, launch qutebrowser as in `8`.  results as in `8`.  now in a loop, `8--11`.  (so, seems as if all three files -- the first version of `index.html`, `bar.html`, and the .gz file -- are being served from the local cache.)

13.  launch some other browser (or, run qutebrowser with `--temp-basedir`), see `hello, world`.

14.  wait "a long time".  reload as in `8`, see `hello, world`.

first version of `index.html` (presumably the comment isn't of import, but, again, who knows).
````
<!-- https://gitlab.com/antora/antora/issues/191 -->
<!DOCTYPE html>
<meta charset="utf-8">minshall.gitlab.io/covid-19/world.html
<script>location="world.html"</script>
<meta http-equiv="refresh" content="0; url=world.html">
<meta name="robots" content="noindex">
<title>Redirect Notice</title>
<h1>Redirect Notice</h1>
<p>The page you requested has been relocated to <a href="world.html">world.html</a>.</p>
````

**Comment by The-Compiler** [comment]
Thanks for the detailed reproduction step! I haven't had a chance to give them a try yet, but this might be expected behavior - could you check if you see the same behavior in Chromium or Google Chrome?

**Comment by greg-minshall** [comment]
thanks.  below is a .zip file for your testing "pleasure".  you need to have node.js installed.  i used the code to test what i have at hand.  all browsers i have, when one switches from `redirect` to `not redirect`, give some approximation of a 404 on `bar.html` when reloading the page.

if you then ask specifically for `foo.html`, firefox on linux and qutebrowser "remember" the redirect from the previous version of foo.html, and give 404 for bar.html.  suckless surf on linux, as well as safari and firefox on the ipad (i think they share the same backend?), detect the new, non-redirecting, index.html, and display that.

setup instructions (more or less).
- unzip the file
- `http-server . -p 9001 -c -1 &`
- `node cachetest.js &`
(port `9001` is where we look for `foo.html`, `bar.html`; 9000 is where we can switch from `redirect` to `not redirect`.  not the best UI... :)

then, to set to redirect:
- `qutebrowser --target window http://localhost:9000/redirect`

and, to see to *not* redirect:
- `qutebrowser --target window http://localhost:9000/notredirect`

to access `foo.html`:
- `qutebrowser --target window http://localhost:9001/foo.html`

*then*, the test is simple
- set to redirect
- access `foo.html` -- get the contents of `bar.html`
- set to *not* redirect
- access `foo.html`.  if you still see `bar.html`, hit reload.  you should see a 404.

now, you are probably stuck.  hth.  sorry for the verbosity.

[caching-bug.zip](https://github.com/qutebrowser/qutebrowser/files/5251221/caching-bug.zip)

**Comment by The-Compiler** [comment]
Thanks for the detailed and easy reproducer! :+1:

I see the exactly same behavior in Chromium, so you'd need to [report it there](https://bugs.chromium.org/p/chromium/issues/list). I don't think there's anything qutebrowser or QtWebEngine can do about this.
