### ISSUE TITLE
The default apparmor profile causes a segfault

### ISSUE THREAD

**Issue by PaperMountainStudio** [qutebrowser/qutebrowser#5729]
**Version info**:

qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1 (compiled 5.15.0)

(Void Linux)

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When using the apparmor profile in enforce mode, qutebrowser segfaults.

**How to reproduce**

Install the default qutebrowser apparmor profile, enable apparmor and run:

```
%: sudo aa-enforce qutebrowser
Setting /usr/bin/qutebrowser to enforce mode.
Warning: profile qutebrowser represents multiple programs
%: qutebrowser
12:27:16 WARNING: EGL not available
[0918/122717.093837:ERROR:resource_bundle.cc(921)] Failed to load /usr/share/qt5/resources/qtwebengine_resources.pak
Some features may not be available.
[0918/122717.093892:ERROR:resource_bundle.cc(921)] Failed to load /usr/share/qt5/resources/qtwebengine_resources_100p.pak
Some features may not be available.
[0918/122717.093920:ERROR:resource_bundle.cc(921)] Failed to load /usr/share/qt5/resources/qtwebengine_resources_200p.pak
Some features may not be available.
[0918/122717.095185:ERROR:resource_bundle_qt.cpp(123)] failed to load locale.pak
LaunchProcess: failed to execvp:
/usr/lib/qt5/libexec/QtWebEngineProcess
[12650:12662:0918/122717.109661:ERROR:file_path_watcher_linux.cc(71)] Failed to read /proc/sys/fs/inotify/max_user_watches
[12650:12650:0918/122717.111713:ERROR:extension_system_qt.cpp(122)] Failed to parse extension manifest.
zsh: segmentation fault  qutebrowser
```

After some tweaking of the profile adding these rules:
```
/usr/share/qt5/resources/* r,
/dev/shm/.org.chromium.Chromium.* rw,
/usr/lib/qt5/libexec/QtWebEngineProcess ux,
/etc/mime.types r,
/proc/sys/fs/inotify/max_user_watches r,
```

it still fails, but in a different place:
```
%: qutebrowser
12:10:59 WARNING: EGL not available
[0918/121100.213215:ERROR:resource_bundle_qt.cpp(123)] failed to load locale.pak
LaunchProcess: failed to execvp:
/usr/lib/qt5/libexec/QtWebEngineProcess
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:01 ERROR: Renderer process did not start
12:11:01 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
12:11:02 ERROR: Renderer process did not start
12:11:02 ERROR: Failed to save autosave session: Commit failed!: '/home/michal/.local/share/qutebrowser/sessions/_autosave.yml'
```

**Comment by The-Compiler** [comment]
I'm not very familiar with AppArmor - what is "the default qutebrowser apparmor profile" exactly?

**Comment by PaperMountainStudio** [comment]
The default apparmor profile is a part of this repository: [misc/apparmor/usr.bin.qutebrowser](https://github.com/qutebrowser/qutebrowser/blob/81b3ef937ebf202670c1561429552874ed51d32a/misc/apparmor/usr.bin.qutebrowser)

**Comment by The-Compiler** [comment]
Ah. I don't think that's ever been updated since the QtWebEngine switch in 2017 with v1.0.0. I don't think @claudehohl who originally wrote it is still using qutebrowser with AppArmor.

Unless you or someone else steps up to update it, I'm most likely just going to delete it because I won't be able to maintain it.

**Comment by GbGp** [comment]
It's a bit difficult to write a generic apparmor profile for a browser: a "proper" configuration can be heavily system specific and you always end up allowing too much stuff. If there is some interest in shipping one with qutebrowser I can try to cleanup mine's and share it.

**Comment by The-Compiler** [comment]
I'd say having something nice as a starting point in `misc/apparmor/` would still be worthwhile, so that people who want to use Apparmor with qutebrowser don't need to start with a blank canvas. So a PR for that would be much appreciated, @GbGp!
