### ISSUE TITLE
MacOs'`DefaultKeyBindings.dict` is not working in qutebrowser

### ISSUE THREAD

**Issue by Granitosaurus** [qutebrowser/qutebrowser#5734]
**Version info**:

```
qutebrowser v1.13.1
Git commit: a99f61071 on HEAD (2020-07-17 17:00:38 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.7.7
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: 2.4.456 (bundled)
sqlite: 3.31.1
QtNetwork SSL: Secure Transport, macOS 10.15

Style: QMacStyle
Platform plugin: cocoa
OpenGL: ATI Technologies Inc., 2.1 ATI-3.10.16
Platform: Darwin-19.6.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.15.6, x86_64

Paths:
auto config: /Users/dex/Library/Preferences/qutebrowser
cache: /Users/dex/Library/Caches/qutebrowser
config: /Users/dex/.qutebrowser
data: /Users/dex/Library/Application Support/qutebrowser
runtime: /private/var/folders/_6/r3sdsdrd4xv6c3dphvysrrsc0000gn/T/qutebrowser

Autoconfig loaded: no
Config.py: /Users/dex/.qutebrowser/config.py has been loaded
Uptime: 0:01:34
```

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

On Macos keybindings can be defined in `~/Library/KeyBindings/DefaultKeyBinding.dict` file, however qutebrowser does not honor this file for some reason.

Related issue with other popular application (Jetbrain IDES): https://youtrack.jetbrains.com/issue/IDEA-127470
Seems like only system keybinds are being read `/System/Library/Frameworks/AppKit.framework/Versions/C/Resources/StandardKeyBinding.dict` and the user ones are ignored for some reason.

**How to reproduce**
save this to `~/Library/KeyBindings/DefaultKeyBinding.dict`:
```
{"§" = {
  "q" = ("insertText:", "qutebrowser");
};}
```
and restart qutebrowser(or any other app). Pressing `§q` in succession should insert `qutebrowser` string however `§q` is inserted.

**Comment by The-Compiler** [comment]
See [[QTBUG-393] Mac OS X: Qt does not provide basic emacs bindings like native Cocoa controls - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-393)

**Comment by Granitosaurus** [comment]
ah, seems like QT upstream doesn't really care about this bug :(
