### ISSUE TITLE
Not loading saved sessions properly: all tabs are loaded as "about:blank"

### ISSUE THREAD

**Issue by sanjayankur31** [qutebrowser/qutebrowser#5738]
**Version info**:
Using --temp-basedir:

```
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v1.13.1
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.14.2

CPython: 3.9.0rc2
PyQt: 5.15.0

sip: 4.19.24
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.3.200 (/home/asinha/.local/share/qutebrowser/pdfjs/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g FIPS  21 Apr 2020

Style: Adwaita::Style
Platform plugin: wayland
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 20.2.0-rc4
Platform: Linux-5.8.10-300.fc33.x86_64-x86_64-with-glibc2.32, 64bit
Linux distribution: Fedora 33 (Workstation Edition Prerelease) (fedora)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /tmp/qutebrowser-basedir-_g33zj3y/cache
config: /tmp/qutebrowser-basedir-_g33zj3y/config
data: /tmp/qutebrowser-basedir-_g33zj3y/data
runtime: /tmp/qutebrowser-basedir-_g33zj3y/runtime

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:03
```

**Does the bug happen if you start with `--temp-basedir`?**:
It's session related, so I can't test it with --temp-basedir.

**Description**
Qutebrowser isn't correctly loading a saved session.  When I start qutebrowser, there are as many tabs as there were on closing, but all the tabs are now "about:blank", and trying to go "back" results in a crash (the crash reporter has reported a couple off issues about this already)

**How to reproduce**
Always reproducible: 

- start qutebrowser
- open a few tabs
- save the session: `:session-save test-session`
- close qutebrowser
- start qutebrowser with saved session: `qutebrowser -r test-session`
- all tabs are "about:blank".

**Comment by The-Compiler** [comment]
This is due to #5359 - qutebrowser has a workaround, but that checks for the Qt version while it should actually check for the QtWebEngine version. You mix Qt 5.14.2 with QtWebEngine 5.15, thus the workaround isn't applied when it should be.

**Comment by sanjayankur31** [comment]
Thanks. The versions were messy because the rpmfusion build of qt-webengine-freeworld (with the proprietary codecs enabled) hasn't come through yet. I've removed that for the time being so I get the right qt bits, and that seems to work now. I got the warning message and everything:

```
qutebrowser v1.13.1
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.9.0rc2
PyQt: 5.15.0

sip: 4.19.24
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.3.200 (/home/asinha/.local/share/qutebrowser/pdfjs/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g FIPS  21 Apr 2020
```

I'll close this issue, since it's already known and my "workaround" fixes it for Fedora.

**Comment by The-Compiler** [comment]
I still think the workaround should check for the QtWebEngine rather than the Qt version, so I'm reopening this.
