### ISSUE TITLE
Plans for v2.0.0 release

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5749]
I originally wanted to release qutebrowser v2.0.0 when Qt 6.1 is out (#5395) around May/June 2021. However, it's becoming more and more clear that this isn't really realistic: pip 21 in January 2021 will drop Python 3.5 support, at which point (if not before) this will become quite a pain to maintain.

Thus, I'd like to release qutebrowser v2.0.0 before the end of the year. I might need to remove some things from the [v2.0.0 milestone](https://github.com/qutebrowser/qutebrowser/milestone/42) to meet that goal, and it might mean that there's a rather quick v3.0.0 somewhen mid-2021 with possibly more (smaller) breaking changes.

Comments welcome!

**Comment by rien333** [comment]
Looking at the v2 milestone list, it seems that there is a lot of fairly important maintenance work to be done. These improvements to the core of qutebrowser might kind of clash with rolling out extension support, given that extensions 1. seem to require significant code overhauls  2. create a lot of "busyness" in areas outside the core of qutebrowser. 

I, for one, wouldn't really mind waiting for extension support a while longer. There's enough worthwhile pull request open right now, some of which even seem slightly more essential  than extension support (and most likely more manageable). Also note that the most popular browser extensions are generally adblockers, which https://github.com/qutebrowser/qutebrowser/pull/5317 will probably solve.  I would much rather see some of the current open pull request be incorporated in qutebrowser v2, as well as  a continuing focus on stability and support for changes/new features in Qt.

But I do kind of wonder what the community looks forward to most, perhaps  a survey will be of help somehow?

**Comment by The-Compiler** [comment]
Right. I would like to have #5317 in a v2.0 as well, but possibly even earlier. The only reason I see for that to be in a v2.0 is marketing, which isn't a strong enough reason to delay it any more if it's ready and the rest of v2.0 isn't yet.

> But I do kind of wonder what the community looks forward to most, perhaps a survey will be of help somehow?

I believe my goals (merging PRs and stuff on the [roadmap](https://github.com/qutebrowser/qutebrowser/projects/5) aligns well enough with the communities' - and a lot of stuff (especially things in the v2 milestone) is just things that might not seem very appealing to outside users, but need to be done sooner rather than later because otherwise the maintenance cost will increase more and more.

**Comment by zabbal** [comment]
Sounds great. Perhaps having v3 milestone would make it easier to see the bigger picture?

**Comment by The-Compiler** [comment]
@zabbal Agreed! I'll open one as soon as I start working on the v2.0 milestone and have a better picture of which changes are simple enough for that and which will take a bit longer and be postponed.

**Comment by pinusc** [comment]
@The-Compiler would it be reasonable to aim to merge my #4602 by v3.0.0? Development / review of that pr has been stale, but I'll have more time to finish up the work and would be a pretty big change for v3. 
Definitely not for v2.0.0 if you want to release that by the end of the year... but I'd like it to be merged eventually!

**Comment by The-Compiler** [comment]
@pinusc I don't see a reason why it would need to wait for v3.0.0 FWIW - even if rather big, it could as well be an addition in v2.x somewhere (e.g. per-domain settings were added in v1.2 or so as well).

**Comment by The-Compiler** [comment]
I'm now planning to release v2.0.0 ASAP (tomorrow maybe?) in the hope of still [getting it into the next Debian Stable](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980847).

**Comment by The-Compiler** [comment]
v2.0.0 [is out now](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2021-January/000090.html) :tada:
