### ISSUE TITLE
:nolog command to increase security for some userscripts.

### ISSUE THREAD

**Issue by MrPixelized** [qutebrowser/qutebrowser#5762]
### Feature
A `:nolog` command, which would take any other command and suppress the logging of its actions. For example:

`:nolog open github.com` would open the github.com page without creating entries in `qute://log`.

### Use case
I think this would be excellent for the autofill-login-form userscripts, such as `qute-pass` and `qute-lastpass`. They send `:fake-key` commands containing sensitive login data, which is then logged in plaintext in the qute logs. This command could do a lot to add security to those scripts.

**Comment by The-Compiler** [comment]
This isn't realistic with how everything works asynchronously - see #5289 and #5286.
