### ISSUE TITLE
Exclude from history by URL pattern

### ISSUE THREAD

**Issue by amacfie** [qutebrowser/qutebrowser#5763]
Perhaps it would be possible to set a list of URL patterns which are never saved in the browsing history. Ideally they would be skipped by `:back` and `:forward` and `:undo`. Maybe there'd be a global setting for how much history to save which could take a URL pattern to be overridden for some domains/pages. Or maybe there would be an "auto-sanitize" setting where certain domains/pages are always `:sanitized` after closing.

The following Firefox extension does this:
https://addons.mozilla.org/en-US/firefox/addon/history-autodelete/

Use case: certain pages aren't useful in the browsing history and just add noise.

**Comment by The-Compiler** [comment]
See `completion.web_history.exclude` - this only affects the completion (and not `:history` or `:back` / `:forward` / `:undo`) but should suffice for your described use-case I'm assuming.

**Comment by amacfie** [comment]
@The-Compiler No my use case involves :history or :back / :forward / :undo as I mentioned.

**Comment by The-Compiler** [comment]
I'd still rather not add another way to do a very similar thing - this will have to wait until there's a way to auto-`:sanitize` things (#58).

**Comment by andrewcarlotti** [comment]
There are two unrelated things there. Writing to history and writing to completion history are handled by qutebrowser itself at the same point in the codebase. Filtering history on the history page using the same patterns could be handled by adding a checkbox to the history page to enable that filtering. (I've been thinking about adding various filtering options to the history page for a while; if I do, I will try to remember this point.)

`:back` and `:forward` are handled completely separately from the above - I think they essentially call the back and forward methods on a QWebEngineView, so changing their behaviour would require some rather messy manipulation of the tab history in QWebEngineView.history

Finally, I'm not sure when or why you would intend to exclude things from `:undo`. Would you base it upon the url that was loaded before the tab was closed, or a check of all the urls in the tab history? And similarly for reopening windows, would you check all the tabs, or just the one that was last focussed? I think a better way to exclude certain tabs or windows from the `:undo` command would be to add a 'forget' argument to the close command, which would prevent it being added to the undo list.
