### ISSUE TITLE
Error while spawning editor: execvp: No such file or directory

### ISSUE THREAD

**Issue by 12-Seconds** [qutebrowser/qutebrowser#5788]
**Version info**:

qutebrowser v1.13.1
Git commit: a99f61071 on HEAD (2020-07-17 17:00:38 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Running `:edit-url` gives the error `Error while spawning editor: execvp: No such file or directory`

**How to reproduce**

Run `:edit-url`

**Comment by The-Compiler** [comment]
The default `editor.command` setting is set to `gvim`. You probably don't have that installed. Either install it or set it to the editor of your choice.
