### ISSUE TITLE
Search color setting

### ISSUE THREAD

**Issue by palb91** [qutebrowser/qutebrowser#5798]
Hello,
Would it be possible to expose a setting to change the color of all search matches ?
Currently it's black on yellow, it's easily readable on a colored background but sometimes hard on a white background.
Once I validate the search text, I can `search-next` or `search-prev`, but sometimes I just want to see the results without going through each of them to find the one I want.
Thanks.

**Comment by The-Compiler** [comment]
Unfortunately not - those colors are hardcoded inside the underlying Chromium.

**Comment by palb91** [comment]
Ok, thanks for your responsiveness!
I suspected something like that :cry:
