### ISSUE TITLE
Consider alpha channel in utils.interpolate_color

### ISSUE THREAD

**Issue by hajdamak** [qutebrowser/qutebrowser#5799]
Setting this option in following way, alpha channel value is ignored.
c.colors.tabs.indicator.stop = "rgba(0, 255, 0, 0.8)"

**Comment by The-Compiler** [comment]
This happens because `utils.interpolate_color` currently ignores the alpha value - marking this as easy because it should be a good first issue for new contributors!

**Comment by duthades** [comment]
Hello! I would like to work on this issue, If that's okay. :)

**Comment by The-Compiler** [comment]
@duthades Absolutely, please go ahead and feel free to ask if you get stuck somewhere!

**Comment by duthades** [comment]
> To fix this, it would need to also pass the different alpha values to _get_color_percentage, and that would also interpolate that value. Also, a test should be added to the respective unit tests.

@The-Compiler Test for each colorspace (RGBA, HSVA, HSLA) is needed or just one case (RGBA) is alright?

**Comment by The-Compiler** [comment]
@duthades If you write a test which only verifies that the alpha component has the correct value (as we have tests for the others already anyways), you should be able to do something like in `test_0_100` - i.e., add a `@pytest.mark.parametrize('colorspace', [QColor.Rgb, QColor.Hsv, QColor.Hsl])` to have one test testing all of them at once. Relevant docs: [Parametrizing tests — pytest documentation](https://docs.pytest.org/en/stable/example/parametrize.html)
