### ISSUE TITLE
Play button on YouTube is working but not drawn

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#5801]
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
The play button on YouTube is not visible. It works just fine, however.

**How to reproduce**
[![missing-play-button.png](https://i.postimg.cc/k4C6tRS0/missing-play-button.png)](https://postimg.cc/qtmMPRjw)

**Comment by The-Compiler** [comment]
See [[QTBUG-87604] No YouTube play button - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-87604)
