### ISSUE TITLE
"Add folder to workspace" in devtools in qutebrowser

### ISSUE THREAD

**Issue by kenho811** [qutebrowser/qutebrowser#5802]
**Version info**: qutebrowser v1.13.1
Git commit: ba39bdcdd on master (2020-10-12 21:08:55 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

**Does the bug happen if you start with `--temp-basedir`?**:
I have yet to try it. Does it make any difference to start qutebrowser this way?

**Description**
Hi all. I started to use qutebrowser a few weeks ago and have definitely been enjoying my experience so far. It is amazing that one can do almost everything without a mouse in the qutebrowser!

Still, I got a problem recently and could not get it solved. Perhaps it is not a bug at all, but as I am quite new to github as well (or in the world of developers in general!), I will just label this as bug for now!

I wanted to use the devtools in qutebrowser (version 1.13.1) for web design. I was following the instructions on chrome devtools to learn how to "add folder to workspace". However, as I fired up devtools, switched to the sources panel, then clicked Filesystem where the label "+ add folder to workspace" was located, nothing really happened. No pop ups or whatsoever.

As a workaround, I downloaded google-chrome for debian buster (my operating system). I went to chrome devtools and did the same as mentioned above. The difference was that this time something got popped up and I was allowed to choose a folder as workspace. 

Would configuring qutebrowser solve this problem? Nautilus is the file manager in my OS(the default). I would love to keep using qutebrowser for its amazing functionalities. Please enlighten me on this issue! Many thanks!

**How to reproduce**

(a) Open qutebrowser.
(b) Fire up devtools either in the command line by typing :devtools or via keyboard shortkeys wi.
(c) Go to the sources panel.
(d) Click Filesystem.
(e) Click "+ Add folder to workspace"
(f) NOTHING HAPPENS!

**Comment by The-Compiler** [comment]
The devtools are coming from the underlying QtWebEngine library and some functionality is indeed missing (also e.g. the "device mode" icon in the top left corner).

I added it to the related upstream bug: [[QTBUG-85171] Missing features in inspector/devtools - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-85171)
