### ISSUE TITLE
Make alpha channel optional

### ISSUE THREAD

**Issue by jpalus** [qutebrowser/qutebrowser#5805]
With qutebrowser 1.14.0 enabling alpha channel I have noticed two regressions:
* my custom user script for opening pattern matched bookmarks using dmenu stopped working -- I'm using window embedding with -w but that apparently does not work with windows having alpha channel: https://lists.suckless.org/dev/1903/33310.html
* performance on my Pinebook Pro became considerably worse

Would it be possible to make it optional?

**Comment by The-Compiler** [comment]
Hehe, I suspected issues like this when merging the related PR: https://github.com/qutebrowser/qutebrowser/pull/5546#issuecomment-650106265

After nobody complained after this being in the git master for almost four months I hoped it'd be okay, turns out I was wrong :smile: 

Can you elaborate on the performance bit? What exactly is impacted how?

Finally, could you check which one of the two lines added in https://github.com/qutebrowser/qutebrowser/pull/5546/files is causing those issues by commenting them out one by one?

**Comment by The-Compiler** [comment]
I can reproduce the dmenu issue, for that commenting out `self.setAttribute(Qt.WA_TranslucentBackground)` is enough - would be good to know whether it solves your performance issues as well.

Then the question is *how* to make it optional - either by introducing a new setting, or by automatically making it transparent whenever the tabbar or statusbar color contains an alpha channel.

@zorbulator do you have an opinion on that? Are there any UI elements other than the tabbar/statusbar which require the window to be transparent?

**Comment by jpalus** [comment]
As a general rule I do prefer using official releases -- I'm not really one of those guys who pull everything from git :)

As for performance issue I can see how things are being repainted in block in stuff as simple as opening bottom menu with 'o', not to mention scrolling pages. This might be just as well problem with early stages of 'panfrost' driver but anyway performance is much better without alpha channel.

Checked it and confirmed that performance degradation is also caused by `self.setAttribute(Qt.WA_TranslucentBackground)`

**Comment by zorbulator** [comment]
It technically is possible to make the webpage itself transparent but that causes a bug that breaks hints so I think it would be mostly safe to assume that only the tabs and status bar would be transparent but I still think it might be better as a separate setting just to give the user more control.

**Comment by sudo-nice** [comment]
I'm not sure the alpha channel is the culprit here, but I've also noticed that 1.14 is slower than 1.13.1. Namely, sometimes it takes about a second to draw hints on the page, so I had to rollback to the previous version:

qutebrowser v1.13.1
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Comment by The-Compiler** [comment]
@sudo-nice Can you please find out whether it's indeed the transparency by upgrading to v1.14.0 again and commenting out the `self.setAttribute(Qt.WA_TranslucentBackground)` line added in #5546? If there is another performance regression, it'd be good to know about it before releasing v1.14.1.

**Comment by sudo-nice** [comment]
@The-Compiler I've commented out the line as you said, and it looks like the problem has gone.

**Comment by The-Compiler** [comment]
Thanks for the confirmation! I guess it's time for a soon-ish v1.14.1 then...

**Comment by sudo-nice** [comment]
@The-Compiler Unfortunately, I still have the issue with some rare sites, so the alpha channel might be irrelevant in my case. I'm going to open another issue once I gather the info.
