### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#582]
qutebrowser should be packaged for Debian - if not as an official package, at least as an unofficial one.

I didn't have time for that so far, and the future of QtWebKit/QtWebEngine on Debian is [unknown](http://lists.alioth.debian.org/pipermail/pkg-kde-talk/2014-October/001970.html) - still opening an issue to track this.

Maybe using [fpm](https://github.com/jordansissel/fpm) to do so (or at least to get started) is a good idea?

/cc @xtaran

**Comment by The-Compiler** [comment]
There are also some other tools we should take a look at to make things easier (maybe as an unofficial package until someone steps up to do a clean/real one):

- [dh-virtualenv](https://github.com/spotify/dh-virtualenv)
- [py2deb](https://pypi.python.org/pypi/py2deb/)
- [stdeb](https://pypi.python.org/pypi/stdeb)

**Comment by V155** [comment]
Im working on that.

**Comment by mati75** [comment]
I prepare source for Debian: https://github.com/mati75/qutebrowser

Now it based on depends python-pygep2: https://github.com/mati75/python-pygep2 which is not avaitable in repository yet. 

Both source should be build by gbp from debian's devscripts package.

lintian (debian packages check tool) return for source now:

`P: qutebrowser: image-file-in-usr-lib usr/lib/python3/dist-packages/qutebrowser/html/doc/img/cheatsheet-big.png
N: 
N:    This package installs a pixmap or a bitmap within /usr/lib. According to
N:    the Filesystem Hierarchy Standard, architecture-independent files should
N:    be placed within /usr/share instead.
N:    
N:    Severity: pedantic, Certainty: certain
N:    
N:    Check: files, Type: binary, udeb
N: 
P: qutebrowser: image-file-in-usr-lib usr/lib/python3/dist-packages/qutebrowser/html/doc/img/cheatsheet-small.png
P: qutebrowser: image-file-in-usr-lib usr/lib/python3/dist-packages/qutebrowser/img/broken_qutebrowser_logo.png
I: qutebrowser: desktop-entry-lacks-keywords-entry usr/share/applications/qutebrowser.desktop
N: 
N:    This .desktop file does either not contain a "Keywords" entry or it does
N:    not contain any keywords not already present in the "Name" or
N:    "GenericName" entries.
N:    
N:    .desktop files are organized in key/value pairs (similar to .ini files).
N:    "Keywords" is the name of the entry/key in the .desktop file containing
N:    keywords relevant for this .desktop file.
N:    
N:    The desktop-file-validate tool in the desktop-file-utils package is
N:    useful for checking the syntax of desktop entries.
N:    
N:    Refer to
N:    https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html,
N:    https://bugs.debian.org/693918, and
N:    https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords for
N:    details.
N:    
N:    Severity: wishlist, Certainty: certain
N:    
N:    Check: menu-format, Type: binary
N: 
`

**Comment by The-Compiler** [comment]
@mati75 Thank you! However I'm still working with @V155 to get a Debian package upstream and will soon upload the packages to the download page in the meantime.

If you're curious, you can find the packages here:

- [qutebrowser](http://git.the-compiler.org/qutebrowser-debian/)
- [pypeg2](http://git.the-compiler.org/python3-pypeg2-debian/)

**Comment by V155** [comment]
@mati75  I have the source for the pypeg2 and qutebrowser package ready to create the ITP and if there are no argumenst against pushing the packages to the official repos they will be pushed perhaps in a few weeks.

**Comment by mati75** [comment]
@The-Compiler thanks for links
@V155 I can't find ITP or RFS bugs, why I create by own sources.

**Comment by V155** [comment]
@mati75 Im sry. Wanted to wait for the ITP til I think that the packaging is done.

**Comment by xtaran** [comment]
@V155: One of the ideas of the ITP is to tell people that someone is working on a package.

@mati75: I wonder if it would be helpful for a qutebrowser package, if you and @V155 join forces and you co-maintain that package (given @V155 is fine with that).

**Comment by mati75** [comment]
@xtaran True, if @V155 needs I can help.

**Comment by V155** [comment]
@xtaran Good Suggestion, I will contact @mati75

**Comment by V155** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832159

**Comment by xtaran** [comment]
I've just sponsored the initial upload of @fiete201's pypeg2 package to Debian. It's the last missing dependency for qutebrowser in Debian. The upload is now [waiting in the NEW queue](https://ftp-master.debian.org/new.html) for review by the Debian FTP Masters.

**Comment by The-Compiler** [comment]
And now the qutebrowser package itself is also [in the NEW queue](https://ftp-master.debian.org//new/qutebrowser_0.11.0-1.html) - thanks a lot to @fiete201 for packaging it, and @xtaran for sponsoring it (and all the great help and suggestions)!

**Comment by xtaran** [comment]
And [the (python3-)pypeg2 package](https://packages.qa.debian.org/p/pypeg2.html) is in the meanwhile already available in Debian Testing.

**Comment by xtaran** [comment]
[qutebrowser has been accepted into Debian Unstable](https://packages.qa.debian.org/q/qutebrowser/news/20171121T090015Z.html) a few days ago, so I think this issue can be closed now.

**Comment by The-Compiler** [comment]
I'd rather wait until v1.0.x is up and the docs are adjusted to point out it's in the repos on Debian Unstable before doing that 😄

**Comment by The-Compiler** [comment]
v1.0.4 landed in Debian Testing and I adjusted the docs accordingly, so this can finally be considered done! 🎉
