### ISSUE TITLE
Windows Defender Win32/Zpevdo.B false-positive

### ISSUE THREAD

**Issue by welblaud** [qutebrowser/qutebrowser#5823]
A week ago, I installed qutebrowser on a couple of machines. One of them runs Win 10. Today, the antivirus reported and blocked the whole show with: **Trojan:Win32/Zpevdo.B** report (for qutebrowser.exe). I downloaded the installer directly from here.

Could anyone explain this, please? Would it be possible the app was somehow infected during meantime?

**Comment by The-Compiler** [comment]
Which antivirus exactly? The most likely explanation is a false-positive.

**Comment by emanuele6** [comment]
I found this issue on `stride`'s github repo: windows defender was detecting the same trojan https://github.com/stride3d/stride/issues/285

**Comment by welblaud** [comment]
I confirm, the same, it was Defender.

**Comment by weslem** [comment]
I received the initial notice from Windows Defender for the 64-bit Windows standalone. Using virustotal.com on the main executable, it reports multiple systems detect a trojan. Here are [the results for my run](https://www.virustotal.com/gui/file/8792dc5bd5ace6ca9c28efe33345a1ded1004b0186c1553bd9a1ce9d39bf9bbc/detection).

**Comment by The-Compiler** [comment]
Here's a more recent issue in another project: https://github.com/cedrozor/myrtille/issues/233

There likely isn't much qutebrowser can do about it FWIW. Not the first time virus scanners go haywire either: #4269

**Comment by lostfile1** [comment]
lol i was about to file the same issue just a moment ago

**Comment by The-Compiler** [comment]
Looks like this has been fixed on Microsoft's side. No issues in my VM, and less false-positives now:

![image](https://user-images.githubusercontent.com/625793/97580699-f26e6300-19f3-11eb-82b3-d10c711a26d3.png)

I submitted it as a false-positive to McAfee. I've never heard of those other scanners, so I'm not going to care about them unless someone complains.
