### ISSUE TITLE
ERR_CACHE_MISS when I do view-source after I submitted a form

### ISSUE THREAD

**Issue by tobip** [qutebrowser/qutebrowser#5824]
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1
*edit: link to [full version info](https://paste.the-compiler.org/view/628fa990)*

**Does the bug happen if you start with `--temp-basedir`?**:
Not as much. With `--temp-basedir` following notification appears, allowing me to reload the page and then I can see the source:
![form_submission_temp-dir](https://user-images.githubusercontent.com/3918330/96617533-0d5e1a80-1304-11eb-95c8-673d594b1242.png)

**Description**
When I want to view the source of a web page after I just submitted a form, it shows an `ERR_CACHE_MISS` error. I can reload that page, but it will continue showing this error and it is not possible to see the page source.
![form_submission](https://user-images.githubusercontent.com/3918330/96618505-52368100-1305-11eb-9e5b-f43086cd186f.png)
 At the same time, the actual content of the html source file is written in the url bar. That means, the url bar looks like `data:text/html;charset=UTF-8[...]`.

**How to reproduce**
1. Go to a web site that has a form.
2. Enter data, submit form, wait for next page to load.
3. Type `:view-source` in qutebrowser
4. Error page appears

I experienced, that with `--temp-basedir` it is possible to reload the page and see the source code. After this I went through both my `config.py` and `autoconfig.yml` but couldn't find anything that seemed to be related to that error in my eyes.
Maybe you have a hint for me what to do...

**Comment by The-Compiler** [comment]
This is due to #3918 - the qutebrowser error page (rather than chromium's one) is only used if Javascript is disabled for the page in question, and you'll need to use `:back` rather than `:reload` to get away from it.

**Comment by tobip** [comment]
Thanks for clarification.
Is there a way to enable Javascript for this kind of error pages, to make qutebrowser use chromium's error page, while keeping Javascript globally deactivated?

**Comment by The-Compiler** [comment]
At least there wasn't when I last checked, otherwise I wouldn't have implemented the workaround with the custom error page :wink:
