### ISSUE TITLE
:config-cycle -p -t colors.webpage.darkmode.enabled has no effect

### ISSUE THREAD

**Issue by imrufbd** [qutebrowser/qutebrowser#5826]
**Version info**:
qutebrowser v1.14.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

With 'c.colors.webpage.darkmode.enabled = False' in config.py ':config-cycle -p -t colors.webpage.darkmode.enabled' changes the value to true and vice versa but the webpage doesn't changes to darkmode.

**How to reproduce**

1. add in ~/.config/qutebrowser/config.py
c.colors.webpage.darkmode.enabled = False
2. open qutebrowser
3. run command
:config-cycle -p -t colors.webpage.darkmode.enabled
4. reload or go to webpage in current or new tab.

**Comment by The-Compiler** [comment]
All darkmode settings require a restart of qutebrowser, as they are passed as commandline flags to the underlying Chromium.

**Comment by AckslD** [comment]
@The-Compiler Is there any way you see that can prevent darkmode settings to require a restart? I really like it but in some cases it just doesn't work that well, for example there has been times when my phone couldn't read a QR-code on a website in darkmode (I've disabled pictures btw). It would be very convenient to just be able to switch darkmode off temporarily and then back again in these cases.

**Comment by The-Compiler** [comment]
@AckslD No. For this to happen, it needs to happen [in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=952419) first, and then be [exposed via QtWebEngine](https://bugreports.qt.io/browse/QTBUG-84484).

Right now, qutebrowser controls the underlying dark mode by passing commandline arguments to Chromium, which can only happen during startup.

**Comment by The-Compiler** [comment]
Actually, there is a small remaining hope to do this via (possibly injected) HTML or CSS features, see #5542 - but so far I wasn't able to create a document which bypasses Chromium's (or qutebrowser's) dark mode. If someone can spot a mistake in there and/or tell me why it's not working, that'd be a great start.

**Comment by AckslD** [comment]
@The-Compiler I see, thanks for the reply!
