### ISSUE TITLE
CPU lockup after Wayland(sway) DPMS screen poweroff

### ISSUE THREAD

**Issue by weslem** [qutebrowser/qutebrowser#5828]
**Version info**:
qutebrowser v1.14.0
Git commit:
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.6
PyQt: 5.15.1

[Full Version paste](https://paste.the-compiler.org/view/d6aa9238)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

After my monitor is turned off via DPMS, exisitng qutebrowser windows become unresponsive. The main python process appears to be spinning with 100% CPU usage. `strace` shows the process repeatedly re-loading font files, in a pattern similar to Qt startup. The last `vdebug` log line is:

```
INFO     qt-qt.qpa.wayland Unknown module:none:0 Creating a fake screen in order for Qt not to crash
```

**How to reproduce**

1. Run qutebrowser under a Wayland session (reporter is using Sway).
2. Turn off the monitor via DPMS, then turn on the monitor (example shell command in sway: `swaymsg "output * dpms off"; sleep 20; swaymsg "output * dpms on";`).
3. Attempt to use the existing qutebrowser. Observe 100% CPU usage via top. Attempt to interact, without change. Observe lack of re-rendering by resizing the window.

**Comment by The-Compiler** [comment]
See [[QTBUG-84161] Qt GUI application disappear or crash when no screens are available on Wayland - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-84161) and #5631.
