### ISSUE TITLE
Incremental search

### ISSUE THREAD

**Issue by bcb** [qutebrowser/qutebrowser#584]
While searching with `/`, the results only appear after hitting enter. Better to highlight as you type, as in luakit.

**Comment by bcb** [comment]
Not a feature of luakit.

**Comment by NoSuck** [comment]
Incremental searching is useful.  It's also a standard feature for web browsers.  Regardless of what luakit has, I consider this feature request important.

**Comment by bcb** [comment]
Ok, reopened.

**Comment by NoSuck** [comment]
Thank you!  Here's hoping others feel the same way.

**Comment by isene** [comment]
+1

On Sat, Mar 28, 2015 at 03:30:42AM -0700, NoSuck scribed:
> Thank you! Here's hoping others feel the same way.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
     "Sometimes experts use their experience not to explore the future, 
                      but merely to protect the past."
                              (Michael Hewitt-Gleeson)

Geir Isene                 |    /"\    ASCII Ribbon Campaign     
http://isene.com           |    \ /    Respect for open standards
http://isene.me            |     X     No HTML/RTF in email      
+47-4550 2470              |    / \    No MS Word docs in email

**Comment by The-Compiler** [comment]
I was about to say this isn't possible because QtWebKit handles the searching - but actually it should be possible by invoking [QWebView::findText](http://doc.qt.io/qt-5/qwebview.html#findText) multiple times, i.e. once with each typed character.

However, the command input needs some way (e.g. a signal) to inform the `TabbedBrowser` a new partial search term was typed, so that can start a search.

**Comment by mgraham** [comment]
+1

**Comment by robcsi** [comment]
+1. Definetly a must-have.

**Comment by The-Compiler** [comment]
@robcsi https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments :wink:

**Comment by kovetskiy** [comment]
any progress of this issue?

**Comment by The-Compiler** [comment]
No. Nobody picked this up so far as far as I'm aware.

**Comment by The-Compiler** [comment]
Thanks to @jupart in #3201, there's now incremental search! 🎉
