### ISSUE TITLE
Document possibility to use {0} placeholder

### ISSUE THREAD

**Issue by jpalus** [qutebrowser/qutebrowser#5844]
Today I wanted to create new searchengine which uses searched term twice in url:
```
https://src.fedoraproject.org/rpms/{}/blob/master/f/{}.spec
```
That however results in qutebrowser error. After looking into code it turns out searchengine url uses standard Python mechanism for formatting strings so it explains error but also points to a fix -- {0} should be used instead of {}. Would it be possible to include it in documentation?

**Comment by The-Compiler** [comment]
Note that the docs already mention `{semiquoted}` as an alias to `{}` and it's possible to repeat that - though I'm fine with making that a bit more explicit or also mentioning `{0}`. Do you want to open a PR by any chance? This would need to be changed in `config/configdata.yml`.
