### ISSUE TITLE
Login sessions not saving?

### ISSUE THREAD

**Issue by tjohnston-cd** [qutebrowser/qutebrowser#5847]
**Version info**:
```
Version info
qutebrowser v1.4.1
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.6.10
Qt: 5.12.7
PyQt: 5.13.1

sip: 4.19.19
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.2.0
yaml: 5.1.2
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.3.18-lp152.47-default-x86_64-with-glibc2.3.4, 64bit
Linux distribution: openSUSE Leap 15.2 (unknown)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5
OS Version: 
```

**Does the bug happen if you start with `--temp-basedir`?**:
Not sure. Will try this later today.

**Description**
I've been running qutebrowser for years (via the package in various distributions - Solus, Void, Arch). Recently, I reinstalled with OpenSUSE Leap 15.2.

Ever since doing this, my qutebrowser doesn't seem to persist any login sessions. Every time I restart the browser, I need to re-log into websites where I had logged in and ticked the usual "stay logged in" box. It also doesn't seem to keep my [duckduckgo settings](https://duckduckgo.com/settings) (page theme, centered layout etc).

My file ownership is correct (e.g. I own everything in my homedir). I haven't tried running with `--temp-basedir` as mentioned in the issue template, but I'll see if that affects the issue later today.

My `config.py` is pretty simple:
```
config.source('qutewal.py')             <<<<<< used to get colours from pywal
c.zoom.default = "75%"
c.auto_save.session = True
c.qt.highdpi = True
c.downloads.location.directory = "A PATH IN MY HOMEDIR"
c.url.default_page = "about:blank"
```

**How to reproduce**
Not sure. I can't tell if this is something about the qutebrowser package in OpenSUSE, or something else..

Any ideas? I'm not sure if this qualifies as a bug, or just a misconfiguration of some kind..

**Comment by The-Compiler** [comment]
First thing to try would probably be a newer qutebrowser - 1.4.1 is ancient (July 2018) and I'm not sure how well it plays with Qt 5.12.7 (which is much newer, January 2020).

**Comment by tjohnston-cd** [comment]
Aha - right. I just updated to the OBS package mentioned [here](https://qutebrowser.org/INSTALL.html#_on_opensuse), so now I'm on 1.14.0

The issue seems to still be with me. I'll fiddle with this a bit..

```
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v1.14.0
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.7

CPython: 3.6.10
PyQt: 5.13.1

sip: 4.19.19
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.2.0
yaml: 5.1.2
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.13.2
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 19.3.4
Platform: Linux-5.3.18-lp152.47-default-x86_64-with-glibc2.3.4, 64bit
Linux distribution: openSUSE Leap 15.2 (unknown)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5
OS Version: 
```

**Comment by The-Compiler** [comment]
Can you take a look at `:config-diff` to ensure you don't have anything unexpected set sonewhere?

**Comment by tjohnston-cd** [comment]
Here's what it shows. The middle section comes from the qutewal config. I'll try taking this apart in a moment.

Side note - it occurred to me that `--temp-basedir` probably isn't valid for testing this..

```
auto_save.session = true

colors.completion.category.bg = #090605
colors.completion.category.border.bottom = #090605
colors.completion.category.border.top = #090605
colors.completion.category.fg = #e2e1de
colors.completion.even.bg = #090605
colors.completion.fg = #e2e1de
colors.completion.item.selected.bg = #CDB597
colors.completion.item.selected.border.bottom = #090605
colors.completion.item.selected.border.top = #090605
colors.completion.item.selected.fg = #e2e1de
colors.completion.match.fg = #817F81
colors.completion.odd.bg = #090605
colors.completion.scrollbar.bg = #090605
colors.completion.scrollbar.fg = #e2e1de
colors.downloads.bar.bg = #090605
colors.downloads.error.bg = #CDB597
colors.downloads.error.fg = #e2e1de
colors.downloads.stop.bg = #DDC9AA
colors.downloads.system.bg = none
colors.hints.bg = #817F81
colors.hints.fg = #090605
colors.hints.match.fg = #ABA094
colors.keyhint.bg = #090605
colors.keyhint.fg = #e2e1de
colors.keyhint.suffix.fg = #817F81
colors.messages.error.bg = #CDB597
colors.messages.error.border = #CDB597
colors.messages.error.fg = #e2e1de
colors.messages.info.bg = #ABA094
colors.messages.info.border = #ABA094
colors.messages.info.fg = #e2e1de
colors.messages.warning.bg = #A68D69
colors.messages.warning.border = #A68D69
colors.messages.warning.fg = #e2e1de
colors.prompts.bg = #090605
colors.prompts.border = 1px solid #090605
colors.prompts.fg = #e2e1de
colors.prompts.selected.bg = #CDB597
colors.statusbar.caret.bg = #DDC9AA
colors.statusbar.caret.fg = #e2e1de
colors.statusbar.caret.selection.bg = #DDC9AA
colors.statusbar.caret.selection.fg = #e2e1de
colors.statusbar.command.bg = #090605
colors.statusbar.command.fg = #e2e1de
colors.statusbar.command.private.bg = #090605
colors.statusbar.command.private.fg = #e2e1de
colors.statusbar.insert.bg = #C8A365
colors.statusbar.insert.fg = #090605
colors.statusbar.normal.bg = #090605
colors.statusbar.normal.fg = #e2e1de
colors.statusbar.passthrough.bg = #ABA094
colors.statusbar.passthrough.fg = #e2e1de
colors.statusbar.private.bg = #090605
colors.statusbar.private.fg = #e2e1de
colors.statusbar.progress.bg = #e2e1de
colors.statusbar.url.error.fg = #CDB597
colors.statusbar.url.fg = #e2e1de
colors.statusbar.url.hover.fg = #ABA094
colors.statusbar.url.success.http.fg = #e2e1de
colors.statusbar.url.success.https.fg = #C8A365
colors.statusbar.url.warn.fg = #A68D69
colors.tabs.bar.bg = #090605
colors.tabs.even.bg = #090605
colors.tabs.even.fg = #e2e1de
colors.tabs.indicator.error = #CDB597
colors.tabs.indicator.system = none
colors.tabs.odd.bg = #090605
colors.tabs.odd.fg = #e2e1de
colors.tabs.selected.even.bg = #ABA094
colors.tabs.selected.even.fg = #e2e1de
colors.tabs.selected.odd.bg = #ABA094
colors.tabs.selected.odd.fg = #e2e1de
colors.webpage.bg = #e2e1de

downloads.location.directory = /home/path..
qt.highdpi = true
url.default_page = about:blank
zoom.default = 75%
```

**Comment by tjohnston-cd** [comment]
Looks like it behaves the same with my entire `config.py` commented out.

Is it possible something in my homedir is cursed? (`.cache` etc)

**Comment by The-Compiler** [comment]
The cookie database is in `~/.local/share/qutebrowser/webengine/Cookies`, maybe there's something wrong with it not causing cookies to be saved - but that seems odd.

You can probably test by using `--basedir path/to/some/folder` rather than `--temp-basedir`. Make sure you wait ~1min after the cookies are set, as older PyQt versions don't save them immediately and closing qutebrowser before they are flushed causes them to be lost. I *think* with PyQt 5.13.1 this shouldn't be the case, but I'm not entirely sure if the required functionality was added in 5.13.1 or .2.

**Comment by tjohnston-cd** [comment]
Aha..clearing that Cookies file out seemed to help.

I noticed it hadn't been written in a couple weeks (since I switched to OpenSUSE and brought over most of my homedir).

I really doubt this is a qutebrowser bug - probably something I've caused with my migration. 
Closing for now, but let me know if I should dig into the old sqlite db/journal for anything.

Thanks!

**Comment by The-Compiler** [comment]
Ah - the underlying Chromium doesn't really support downgrades for its data files. My guess would thus be that you used a newer QtWebEngine (and thus a newer underlying Chromium) before, and that file somehow didn't work correctly anymore after downgrading to Qt 5.12.
