### ISSUE TITLE
ZeroDivisionError when using PgUp/PgDown in completion

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5848]
I noticed crash reports due to a ZeroDevisionError in the completion PgUp/PgDown code added in v1.14.0.

Will edit this with more information later, this is mainly as a note to myself because it's a regression I'd like to fix before v1.14.1 is released.

**Comment by The-Compiler** [comment]
Reproducible with enough history when holding PgDown until arriving at the bottom of the displayed/loaded history (or pressing pgup, pgdown, pgdown):

```
18:03:27 DEBUG    commands   command:run:542 command called: completion-item-focus ['next-page']
18:03:27 DEBUG    commands   command:run:556 Calling qutebrowser.completion.completionwidget.CompletionView.completion_item_focus(<qutebrowser.completion.completionwidget.CompletionView>, 'next-page', False)
18:03:27 ERROR    misc       crashsignal:_handle_early_exits:245 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/eventfilter.py", line 105, in eventFilter
    return handler(typing.cast(QKeyEvent, event))
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/eventfilter.py", line 75, in _handle_key_event
    return man.handle_event(event)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/modeman.py", line 462, in handle_event
    return handler(cast(QKeyEvent, event))
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/modeman.py", line 283, in _handle_keypress
    match = parser.handle(event, dry_run=dry_run)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/basekeyparser.py", line 326, in handle
    self.execute(result.command, count)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/modeparsers.py", line 68, in execute
    self._commandrunner.run(cmdstr, count)
  File "/usr/lib/python3.8/site-packages/qutebrowser/commands/runners.py", line 373, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.8/site-packages/qutebrowser/commands/command.py", line 558, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.8/site-packages/qutebrowser/completion/completionwidget.py", line 322, in completion_item_focus
    idx = indices[which]()
  File "/usr/lib/python3.8/site-packages/qutebrowser/completion/completionwidget.py", line 319, in <lambda>
    'next-page': lambda: self._next_page(upwards=False),
  File "/usr/lib/python3.8/site-packages/qutebrowser/completion/completionwidget.py", line 227, in _next_page
    page_length = self.height() // element_height
ZeroDivisionError: integer division or modulo by zero
```

**Comment by The-Compiler** [comment]
So what's happening is this:

- PgUp selects the last displayed item
- PgDown goes down, selects an item which is actually invisible (as something probably called `fetchMore` on the model internally while scrolling down, but the view didn't adjust?)
- Thus, when we press PgDown a second time, `viewRect` is an invalid `QRect`, thus `element_height` is 0.

So I thought I could adjust the condition added in 32fa1ff1e990e08110dfc7fe41b57d82bbdf2c6d by @rcorre (for #2841), so that it checks for `>=` rather than `==`. However, this didn't work, and the adjustment isn't actually needed! Given that PgUp/PgDown always land on the last element before going down more, something must be wrong.

Then I found out that even #2841 regressed with the upgrade from Qt 5.10 to 5.11 - and indeed this issue isn't reproducible with Qt 5.11 either!

My first guess would be this from the [changelog](https://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.11.0/?h=v5.11.0#n252):

> [[QTBUG-48725](https://bugreports.qt.io/browse/QTBUG-48725)] QTreeView now calls canFetchMore() and fetchMore() when the bottom of the QTreeView is scrolled to.

Relevant change: [Call canFetchMore/fetchMore when scrolled to the bottom of the view (I2b214568) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/177556)

So Qt already should handle this for us, and it does - but the new items don't actually appear, similarly to what @rcorre already said in 32fa1ff1e990e08110dfc7fe41b57d82bbdf2c6d:

> Calling fetchMore directly will not update the view

A possible workaround would be:

```diff
diff --git i/qutebrowser/completion/completionwidget.py w/qutebrowser/completion/completionwidget.py
index 1f5304b61..86de688a0 100644
--- i/qutebrowser/completion/completionwidget.py
+++ w/qutebrowser/completion/completionwidget.py
@@ -331,7 +331,8 @@ def completion_item_focus(self, which, history=False):
             QItemSelectionModel.Rows)
 
         # if the last item is focused, try to fetch more
-        if idx.row() == self.model().rowCount(idx.parent()) - 1:
+        next_idx = self.indexBelow(idx)
+        if not self.visualRect(next_idx).isValid():
             self.expandAll()
 
         count = self.model().count()

```

but that still leaves us with the question why our views don't update correctly when the underlying model fetched more data... @rcorre do you have any idea why that could be?

**Comment by rcorre** [comment]
I don't have an idea off the top of my head, unfortunately :(
