### ISSUE TITLE
Open .mhtml by symlink pointing to file w/o extension (git-annex)

### ISSUE THREAD

**Issue by amerlyq** [qutebrowser/qutebrowser#5858]
**Version info**:
https://paste.the-compiler.org/view/ef1982ee

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Incorrect MIME inference when accessing extensionless local file through symlink.
I suspect the same problem appears for other formats, for which MIME is hard to infer reliably without extension.

* OK -- when opening .mht file directly e.g. xdg-open.
* OK -- when opening .mht file by anything named symlink to .mht (even extensionless symlink -- through `file://...` in browser)
* BAD -- if original file had no extension BUT symlink has.

Usecase: I recently migrated my 15+ years collection of .mhtml webpages into git-annex to sync between PC, keep partial checkouts and track archived copies. Now all "locked" files are represented as symlinks pointing to readonly files:
```bash
$ readlink testpage.mhtml
../../../../.git/annex/objects/a6c/SHA256-s1428402--465f8c7ef2d242495963b34d48b914411edeef69162e6dce9a8fe129438ed0e8/SHA256-s1428402--465f8c7ef2d242495963b34d48b914411edeef69162e6dce9a8fe129438ed0e8
``` 
My current workaround is to copy dereferenced files before opening them in browser (to prevent frequent "git annex lock/unlock" modifying git-annex branch history):
```
cp -Lt /tmp/qute -- *.mht
```

**How to reproduce**
Hint: last one does not work
```bash
qutebrowser --temp-basedir -- example.com ':later 3000 download --mhtml --dest=/tmp/ex.mht'
cp /tmp/ex.mht /tmp/ex
ln -s /tmp/ex.mht /tmp/sym.mht
ln -s /tmp/ex.mht /tmp/sym
ln -s /tmp/ex /tmp/noext.mht
qutebrowser --temp-basedir -- /tmp/sym.mht /tmp/sym /tmp/noext.mht
```

**Possible variants of mitigation**

0) stop resolving symlinks before opening
1) fix MIME detector to search line "Content-Type: multipart/related;" somewhere in file header to treat it as .mht or text/rfc822 by content only
2) use symlink's own extension in case resolved path don't have any extension (to reuse default MIME detection mechanics by file extension)
3) artificially add .mhtml extension from (2) to paths fed to webengine, but providing content from original location
4) copy resolved file into temp dir and add extension from (2) to it there (if webengine suffers from severe limitations)

**Comment by The-Compiler** [comment]
This is the same behavior as Chromium - all qutebrowser does is passing a file-URL to QtWebEngine/Chromium.

Chromium intentionally doesn't use mime-sniffing there as a security measure, see [777737 - Security: Google Chrome renders text file as HTML under file:// protocol - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=777737).

While 4 would be possible, I don't think it's a good idea to add a hack to qutebrowser to circumvent a security-related change in Chromium.

**Comment by amerlyq** [comment]
Issue 777737 above is about MIME detection and does not mention symlinks at all.
Still, as qutebrowser simply passes file-URL to Chromium, there is nothing we can do to circument this gracefully.
So, I suppose it's the chromium bug after all -- they decided to consult only **passed file-URL extension** and they failed to do exactly so due to needlessly dereferencing file beforehand and therefore *modifying* passed file-URL (which they weren't supposed to do at all).
Too many apps mistreat symlinks, who cares if there is one more.
