### ISSUE TITLE
completion.web_history.exclude doesn't work when set from config.py

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5868]
See Reddit: [completion.web_history.exclude isn't working or am I not setting it up correctly? : qutebrowser](https://www.reddit.com/r/qutebrowser/comments/jnzwb0/completionweb_historyexclude_isnt_working_or_am_i/)

In  qutebrowser/browser/history.py we do:

```
 194   │     @config.change_filter('completion.web_history.exclude')
 195   │     def _on_config_changed(self):
 196   │         self.metainfo['force_rebuild'] = True
```

but that change filter won't be run when `config.py` is initially loaded...

I guess a proper fix for this would need to store the exclude patterns (or a hash of them) in the database so we know we need to regenerate whenever they changed.

**Comment by mamg22** [comment]
I have been testing a few solutions to this and I think I have something that works and doesn't break anything else, I'll be submitting a pull request in a while.
