### ISSUE TITLE
Use proxy when private browsing

### ISSUE THREAD

**Issue by tamis-laan** [qutebrowser/qutebrowser#5875]
Not sure if this is possible or able to be hacked in but it would be cool to use a proxy or tor proxy when qutebrowser is in private browser mode!

**Comment by The-Compiler** [comment]
Unfortunately not - a proxy can only be set globally.

**Comment by tamis-laan** [comment]
Hey, why close it? It's a feature request :-)

**Comment by The-Compiler** [comment]
Because the underlying API in QtWebEngine (and Chromium, I suspect) means it's not possible to implement it.

**Comment by tamis-laan** [comment]
Ah I see, and it's not possible to build in a switch, like proxy on proxy off? And maybe trigger the proxy when a private tab is open?

**Comment by The-Compiler** [comment]
You can already toggle the proxy on/off by changing the setting (e.g. via `:config-cycle`) - but that will affect all windows, not just the private one.

**Comment by tamis-laan** [comment]
And it is not possible to create a new instance of qutebrowser when starting a new window in private mode. Meaning you don't a have a private window but a private instance of qutebrowser? Would this also not be more private?

**Comment by The-Compiler** [comment]
You can do that by launching a second qutebrowser with `--temp-basedir` and use e.g. `--set content.proxy ...`  to have a different proxy in there. I'd rather not do that by default though, as it also affects a lot of other things (for example, you won't have access to history completion, or your normal config).

**Comment by tamis-laan** [comment]
Hm... in the brave browser which is based on chromium you can actually open a private tor window, so I would suspect it would also be possible with qutebrowser ^_^

**Comment by tamis-laan** [comment]
Is there some way to indicate proxy mode is on? Can I put custom text in the status bar for example?

**Comment by The-Compiler** [comment]
> Hm... in the brave browser which is based on chromium you can actually open a private tor window, so I would suspect it would also be possible with qutebrowser ^_^

I took a quick look at the Tor integration in [brave-core](https://github.com/brave/brave-core) - they add ~5000 lines of code to Chromium for that:

```
─[florian@aragog]──[~/tmp/brave-core]──[20-11-10]──[16:48]──[1 job]──[git/master]────┄
$ find  ./components/services/tor ./components/tor ./browser/tor -type f | grep -v LICENSE | xargs tokei                             
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 C Header               19         1092          744          103          245
 C++                    20         3802         2904          447          451
===============================================================================
 Total                  39         4894         3648          550          696
===============================================================================

─[florian@aragog]──[~/tmp/brave-core]──[20-11-10]──[16:48]──[1 job]──[git/master]────┄
$ find  ./components/services/tor ./components/tor ./browser/tor -type f | grep -v LICENSE | xargs cat | wc -l
5134
```

And that's just counting the files inside `tor/` folders, not any integration code outside of those, so it's safe to say there'll be more than that. It does seem to integrate the Tor client directly with Chromium, not just launch a SOCKS proxy or something along those lines.

Thus, one would need to port that integration to QtWebEngine and contributed there - given that it seems like quite a bit of complexity to maintain for an use case most of Qt's users won't care about, I think it's safe to say that it's very unrealistic that it would be accepted.

**Comment by The-Compiler** [comment]
Quick addendum: There *does* seem to be a [proxy_config_service_tor.cc](https://github.com/brave/brave-core/blob/master/net/proxy_resolution/proxy_config_service_tor.cc) in Brave, which defines a "traffic annotation":

```cc
constexpr NetworkTrafficAnnotationTag kTorProxyTrafficAnnotation =
    DefineNetworkTrafficAnnotation("proxy_config_tor", R"(
      semantics {
        sender: "Proxy Config Tor"
        description:
          "Establishing a connection through the tor proxy server"
        trigger:
          "Whenever a network request is made from a tor profile."
        data:
          "Proxy configuration."
        destination: OTHER
        destination_other:
          "The proxy server specified in the configuration."
      }
      policy {
        cookies_allowed: NO
        setting: "This feature cannot be disabled by settings."
        policy_exception_justification: "Not implemented."
      })");
```

I don't really understand how it's used though, and I can't really comment on whether QtWebEngine could do the same for incognito profiles (probably in [proxy_config_service_qt.cpp](https://github.com/qt/qtwebengine/blob/dev/src/core/net/proxy_config_service_qt.cpp)).

But my main point still stands - someone will need to implement this in QtWebEngine - it's not going to be me, and so far there aren't many qutebrowser users/developers who contribute to QtWebEngine. I'll also not open a feature request, given that I have many other feature requests open which I find much more important. Also FWIW, the API for this doesn't really exist at all in QtWebEngine so far, all it does is using the application-wide Qt proxy if set. So this would definitely be a rather big change to something which is already a bit of a mess now (see #2492).
