### ISSUE TITLE
Improvements to hints

### ISSUE THREAD

**Issue by recallthis** [qutebrowser/qutebrowser#5876]
Just some ideas to make hinting easier.

1. Only choose hint letters for links that are actually visible on the page
If there are 26 links on the page, all hints should use single letters (A-Z).

2. Highlight each box around the hinted links with thin borders
This makes it faster to select a link as less ambiguity and visual noise.

**Comment by The-Compiler** [comment]
1. is already done. For 2, see https://github.com/qutebrowser/qutebrowser/issues/2836#issuecomment-701348624
