### ISSUE TITLE
Remove optional cssutils dependency

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5878]
qutebrowser depends on [cssutils](https://cthedot.de/cssutils/) - after being on life support for a while (thanks to @Kingdread for continuing to maintain it during that time), it looks like its repository is now gone after Bitbucket removed Mercurial support: https://bitbucket.org/cthedot/cssutils/

It's only needed for better MHTML download support on QtWebKit, which is something very niche, so I doubt anyone will care if we remove support for it. Thus, we should remove it.

This could be a good first contribution if someone wants to take it - essentially, search for `cssutils` in the repository and remove everything related to it (code, tests, documentation, requirements, etc.)

**Comment by duthades** [comment]
Hi @The-Compiler, I would like to contribute to this issue.

**Comment by The-Compiler** [comment]
Yay, please go ahead!

Something I didn't consider before: I'm not sure how well you can test those changes locally. Running the relevant tests in `tests/unit/browser/webkit/test_mhtml.py` will require having QtWebKit installed, which can be a bit of a problem depending on your system - what OS/distribution are you using?

FWIW it's still a possibility to do those changes "blindly" though, and run the tests you can locally, or keep an eye on GitHub Actions where they'll all run - I can then finish the rest if you get stuck.

**Comment by duthades** [comment]
I use ubuntu 18.04.

**Comment by eli-schwartz** [comment]
Randomly noticed this in the release notes...

FWIW, if you still actually wanted this you could use the css-parser fork. https://github.com/ebook-utils/css-parser

It's actively maintained by the calibre and Sigil developers, as both projects rely on it for important functionality. It should be pretty functional simply by restoring deleted code and sed'ing imports from cssutils to css_parser.
