### ISSUE TITLE
qt.environ setting

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5899]
Sometimes it can be useful to set environment variables for qutebrowser only. This can be done in `config.py` already, but having a setting would make things a bit easier (also to test via `--temp-basedir -s`.

In the config, this would be of `type: Dict` with `keytype: String` and `valtype: String`, as well as `restart: true` set (perhaps also `none_ok: true` so that `None` can be used as a value to remove a previously set variable).

Then qutebrowser would apply those in `qutebrowser/config/qtargs.py` or so, similar to how other settings (e.g. `config.val.qt.force_platform`) are already mapped to environment variables

**Comment by StutiV** [comment]
Hello @The-Compiler , can you assign me this issue? I'd like to contribute and am just starting out with open source.

**Comment by The-Compiler** [comment]
@StutiV Sure, please go ahead and don't hesitate to ask if you get stuck somewhere! :+1:

**Comment by StutiV** [comment]
@The-Compiler can you elaborate the issue a bit? It'd be really helpful. Thank you!

**Comment by The-Compiler** [comment]
So, the aim of this is to be able to set [environment variables](https://en.wikipedia.org/wiki/Environment_variable) via the qutebrowser config. For example, if you run this (on Linux/macOS, see the Wikipedia article for Windows):

```con
QT_SCALE_FACTOR=4 qutebrowser --temp-basedir
```

you should be able to start qutebrowser with a much bigger user interface.

The idea is now that this can be specified via the qutebrowser configuration instead, which you can test using something like:

```con
qutebrowser --temp-basedir -s qt.environ '{"QT_SCALE_FACTOR": "4"}'
```

(once this is actually implemented).

To implement it, roughly those steps are needed:

1) Add a new setting to `qutebrowser/config/configdata.yml` (see my notes above and e.g. the `qt.args` setting for some inspiration)
2) Handle the setting in `qutebrowser/config/qtargs.py`, probably best in `init_envvars`.
3) In `tests/unit/config/test_qtargs.py`, adjust the parametrization for the `test_env_vars` function to add a test for the new `qt.environ` setting
4) Finally, also handle the case where a value has been set to `None`/`null` in the config, so that a user can set that to *remove* an existing environment variable - for example:

```con
QT_SCALE_FACTOR=4 qutebrowser --temp-basedir -s qt.environ '{"QT_SCALE_FACTOR": null}'
```

should result in qutebrowser *not* scaling up the UI.
5) Add another test or two for that - make sure you cover both the cases where the variable is already set (so there's something to delete) and where it isn't set - you can use pytest's [monkeypatch](https://docs.pytest.org/en/stable/monkeypatch.html) to do so.

**Comment by The-Compiler** [comment]
@StutiV Did you intend to unassign yourself?

**Comment by t-ens** [comment]
Is this still being worked on by @StutiV ? I'll give implementing it a shot if not.

**Comment by The-Compiler** [comment]
I have no idea, but since they unassigned themselves and didn't answer anymore, I guess not... Please go ahead!

**Comment by t-ens** [comment]
I have no idea whether I did the test in an appropriate way or not since I have no experience with this so if not please give me a bit more detail on what I should be doing for this part.
