### ISSUE TITLE
Navigate up strips html percent encoding

### ISSUE THREAD

**Issue by DatGizmo** [qutebrowser/qutebrowser#5908]
**Version info**:
qutebrowser v1.14.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.7.9
PyQt: 5.15.1

sip: 4.19.24
colorama: 0.4.4
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.2
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 20.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.1
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
The navigate up command strips percent encoding, in my case %2F, from the url.
I stripped the domain name from the url as it is a company internal url.
"https://<domain>/blue/organizations/jenkins/buran%2Fsewe%2Fsdk-nrf/detail/PR-2/67/pipeline/"
The "%2F" are used to represent the folder structure from Jenkins.
When i use 'navigate up' the url looks as follows.
"https://<domain>/blue/organizations/jenkins/buran/sewe/sdk-nrf/detail/PR-2/67/"

**Comment by The-Compiler** [comment]
Thanks for the report! This was an easy one to fix :slightly_smiling_face:

**Comment by DatGizmo** [comment]
Nice, thanks for the quick fix
