### ISSUE TITLE
Unable to use JavaScript to detect Caps lock status

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#5925]
**Version info**:
qutebrowser v1.14.0
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2 (compiled 5.15.1)

CPython: 3.8.6
PyQt: 5.15.1

sip: 5.4.0
colorama: 0.4.4
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.2
yaml: 5.3.1
cssutils: no
attr: 20.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.6.347 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1h  22 Sep 2020

**Does the bug happen if you start with `--temp-basedir`?**:
Yes it does.

**Description**
Some websites take habit (for the sake of User Experience) to put a javascript snippet to detect the "Caps Lock" modifier in password fields.

This kind of check does not work on Qutebrowser

**How to reproduce**
1. Navigate to: https://www.w3schools.com/howto/howto_js_detect_capslock.asp
2. Click on the input box
3. Press the Caps lock button (eventually start typing)

Expected result: A box with red text should appear, telling us that the caps lock key is active

Actual Result: No such box appears.

**Comment by The-Compiler** [comment]
This is a QtWebEngine bug - I reported it upstream: [[QTBUG-89001] event.getModifierState("CapsLock") does not work - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-89001)

**Comment by The-Compiler** [comment]
There was a fix merged: [Forward modifier flags for lock keys (I9f336313) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/324578)

So this should be fixed in whatever the next QtWebEngine release is - from what it looks, there will be a 5.15.3 at some point.

**Comment by Penaz91** [comment]
I will keep an eye on it, thanks a ton.
