### ISSUE TITLE
<Ctrl-w> keybinding insert mode

### ISSUE THREAD

**Issue by pspiagicw** [qutebrowser/qutebrowser#5926]
## Feature Needed
Way to bind Ctrl-w to delete previous mode in insert mode of qutebrowser.
## Request
It is very common to use the vim keybinding Ctrl-w for delete the previous word.It is available in qutebroser in the command mode.But in insert mode it is unavailable.I tried using :bind command but was confused on how to represent 'delete previous word' as a command to bind to.If you introduce this feature It would make life a lot easier.

**Comment by toofar** [comment]
See here for some inspiration https://github.com/qutebrowser/qutebrowser/issues/68#issuecomment-418676863

**Comment by pspiagicw** [comment]
Just what I wanted.Thank You. You just made my day! . Thank You Again.

**Comment by The-Compiler** [comment]
Closing this as a duplicate.
