### ISSUE TITLE
Enabling/disabling a proxy is not applied right away

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#5930]
**Version info**:
<details>
  <summary>Details</summary>

qutebrowser v1.14.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.6
PyQt: 5.15.2

sip: 5.4.0
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.1
yaml: 5.3.1
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 18.3.6
Platform: Linux-4.19.0-12-amd64-x86_64-with-glibc2.29, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

</details>

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**How to reproduce**

0. Have Tor installed and running on your system.
1. Run `qutebrowser --temp-basedir`.
2. Execute `set content.proxy socks://localhost:9050/`.
3. Open `https://www.myip.com/` in the current tab.
Here, the site opens directly, not trough the proxy.
4. Press <kbd>g</kbd><kbd>o</kbd><kbd>Enter</kbd> to open the page once again.
Now, you can see it goes through the proxy.
5. Ok, let's disable the proxy: `set content.proxy system`.
6. Press <kbd>g</kbd><kbd>o</kbd><kbd>Enter</kbd> again, to retrieve the page with no proxy.
Still, the page indicates, it goes through the proxy.
7. Press <kbd>g</kbd><kbd>o</kbd><kbd>Enter</kbd> once again.
Finally, the page opens directly.

It might be unrelated, but while running this test, qutebrowser gave me about 20 lines like the below one:
```
[21031:21047:1203/084609.478893:ERROR:database.cc(1584)] Cookie sqlite error 1032, errno 0: attempt to write a readonly database, sql: INSERT INTO cookies (creation_utc, host_key, name, value, encrypted_value, path, expires_utc, is_secure, is_httponly, samesite, last_access_utc, has_expires, is_persistent, priority,source_scheme) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```

**Comment by The-Compiler** [comment]
See #5557
