### ISSUE TITLE
Trying install I get alert at the finish of download

### ISSUE THREAD

**Issue by jazei-AR** [qutebrowser/qutebrowser#5938]
![SnapShot_201205_062447](https://user-images.githubusercontent.com/72522918/101238942-805bfe80-36c2-11eb-8bb9-af430f6c692d.jpg)
and details go to https://support.google.com/chrome/answer/6261569?visit_id=637427565054665794-1741149495&p=ib_download_blocked&hl=es&rd=1

**Comment by The-Compiler** [comment]
No problems here. Two questions:

- What does the message say in English?
- What operating system and Chrome version?

**Comment by jazei-AR** [comment]
> No problems here. Two questions:
> 
> * What does the message say in English?
> * What operating system and Chrome version?
english; This file is not usually downloaded and can be dangerous
win 7 professi.... 64 bit but 4 GB RAM so I use only 32 bit bowsers in this case is SlimJet a chromium Versión 28.0.3.0 (basado en Chromium 85.0.4183.69) (Build oficial) (32 bits)

**Comment by The-Compiler** [comment]
From https://bugs.chromium.org/p/chromium/issues/detail?id=498136:

> If Google Safe Browsing hasn't seen a particular binary before, or if it's very new, Chrome will warn that it may be dangerous. In these cases the warnings are lifted automatically if the content was verified to be benign after scanning.

So it looks like we'll just have to wait. Not much I can do about it.

**Comment by jazei-AR** [comment]
ok I trust you I'll download it now REgards

**Comment by jazei-AR** [comment]
I could not install browser:
![SnapShot_201205_073932](https://user-images.githubusercontent.com/72522918/101240289-201e8a00-36cd-11eb-82eb-b765ee3fe8a8.jpg)
I don't use 64 bit browsers because I only have 4 GB RAM

**Comment by The-Compiler** [comment]
> I don't use 64 bit browsers because I only have 4 GB RAM

I don't see how those two things are connected. What's the downside of using a 64bit version if you're on a 64bit windows?
