### ISSUE TITLE
Particular website uses 100% CPU

### ISSUE THREAD

**Issue by klaasg** [qutebrowser/qutebrowser#5941]
**Version info**:
```
qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
```
**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When I browse to [this webpage](https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols), a process uses up 100% of a core.

**How to reproduce**
```
$ qutebrowser -T https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols &
$ top
```
Almost always the cpu usage of a `QtWebEngineProc`-process gets to 100%. Closing the tab of this website or closing qutebrowser brings back the CPU usage immediately.

I think you'd be able to reproduce this, but if not you can give me instructions on how to track down the cause of this issue.

I'm sorry if there is already an issue with a similar problem, I looked but did not find any.

**Comment by The-Compiler** [comment]
I can reproduce, but this looks like a Qt bug - reported upstream: [[QTBUG-89196] QtWebEngineProcess uses 100% CPU on list of LaTeX symbols - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-89196)
