### ISSUE TITLE
Show :set-cmd-text bindings in completion?

### ISSUE THREAD

**Issue by zdmgmail** [qutebrowser/qutebrowser#5942]
**Version info**:

```
qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
```

**Description**

![bind](https://user-images.githubusercontent.com/50515839/101276782-4423bd80-37ea-11eb-91e9-e277d375f659.png)

use `:bind` , I can see bookmark-load shortcut : gb
but why this not show when I press `: bookmark` in pic

new use qutebrowser, seems show shortcut on command line very convient

**Comment by The-Compiler** [comment]
This is because `gb` doesn't actually run `bookmark-load` - it is bound to `set-cmd-text -s :bookmark-load` which inserts `:bookmark-load` into the commandline input.

It might make sense to show those keybindings as well, though - @rcorre what do you think?

**Comment by rcorre** [comment]
I think it would be useful, but I'm not sure how to approach it. Some ideas:

- Any `set-command-text` command be shows as a shortcut based on the first word in the command
- Hardcode shortcuts for default bindings like `o` and `M`
- Change the behavior of commands like `open` to behave like `set-cmd-text :open ` if they receive no args

**Comment by The-Compiler** [comment]
> * Any `set-command-text` command be shows as a shortcut based on the first word in the command

Either that, or maybe be a bit more restrictive and only show them if it's an exact match? This would e.g. show `o` for `:open`, but not `go`, `O`, `gO`, `xo`, `xO`, `wo`, `wO`, ... - I think showing all variants might be a bit too noisy/overwhelming.

> * Hardcode shortcuts for default bindings like `o` and `M`

I'd prefer this to also work if bindings are changed.

> * Change the behavior of commands like `open` to behave like `set-cmd-text :open ` if they receive no args

Early versions of qutebrowser used to do that, but it's rather confusing, so I'd not want to go back to that.
