### ISSUE TITLE
Requirement for setuptools on runtime

### ISSUE THREAD

**Issue by steils** [qutebrowser/qutebrowser#5943]
It's written in README and in some other places (qutebrowser/misc/earlyinit.py, scripts/*, ...) that `setuptools` are required for runtime, not only build time. If so, could you please add it to `install_requires`? (Otherwise could you say that this package is not required for runtime?)

See also: https://bugs.gentoo.org/750050

**Comment by eli-schwartz** [comment]
It doesn't depend on setuptools, only on pkg_resources.

Depending on your version of python, the generated entry points might also depend on pkg_resources regardless of explicit use.

The explicit use of pkg_resources is being phased out anyway.

**Comment by The-Compiler** [comment]
If I remember correctly, `pkg_resources` was a bit special, at least back when I introduced it in 2014 - some distributions packaged it separately from setuptools, so `setuptools` in `install_requires` might cause trouble there.

I have no idea whether this is still the case - but given that the next release is most likely to be v2.0.0 which won't depend on `pkg_resources` anymore (#4467), I think it's fine to leave this as-is.

**Comment by eli-schwartz** [comment]
Debian hasn't changed and still does that.

And unfortunately, this isn't very compatible with the fact that pkg_resources doesn't provide its own egg-info/dist-info for python's install_requires to consume.
