### ISSUE TITLE
multi copy mode

### ISSUE THREAD

**Issue by zdmgmail** [qutebrowser/qutebrowser#5952]
when I use chrome vim plugin: surfingkeys

`ya` can copy link,  and I often press `yma` to copy multi links(each link in a line) then paste in my file

Could you implement this? 

(It also has mult copy text but I never use )

**Comment by toofar** [comment]
You can, not sure if you are asking for both or just the later. For just copying a link there is already a [default binding](https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/img/cheatsheet-big.png) for this, `;y`. For "multi links" you can use rapid hinting mode. So `:bind yma hint --rapid links yank-clipboard` then `yma` like you are used to (assuming `ym` isn't already bound). Or `config.bind('yma', 'hint --rapid links yank-clipboard')` if you use a config.py.

**Comment by zdmgmail** [comment]
> You can, not sure if you are asking for both or just the later. For just copying a link there is already a [default binding](https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/img/cheatsheet-big.png) for this, `;y`. For "multi links" you can use rapid hinting mode. So `:bind yma hint --rapid links yank-clipboard` then `yma` like you are used to (assuming `ym` isn't already bound). Or `config.bind('yma', 'hint --rapid links yank-clipboard')` if you use a config.py.

thanks, solved. and should use `config.bind('yma', 'hint --rapid links yank')` ? yank-clipboard get error

**Comment by toofar** [comment]
Ah yes, I use yank-primary so I translated that, but badly apparently.
