### ISSUE TITLE
Cheatsheet i18n (keyboard layout)

### ISSUE THREAD

**Issue by Das-Sams** [qutebrowser/qutebrowser#5953]
Hi,
I'd like to internationalize the cheatsheet to German and maybe Swissgerman keyboard layout. Can I get the original GIMP, latex, scribus, inkscape or whatever file to do so. I only find the png here.
BTW, it looks nice.

**Comment by The-Compiler** [comment]
It's here: https://github.com/qutebrowser/qutebrowser/blob/master/misc/cheatsheet.svg

I really wish someone would write some kind of script to generate this kind of cheatsheet though... I'd rather not have to update multiple files when new keybindings are added. Then again, not sure how often that happens nowadays.
