### ISSUE TITLE
Search result nav direction does not change when searching for the same string again

### ISSUE THREAD

**Issue by gadanidis** [qutebrowser/qutebrowser#5962]
**Version info**:

qutebrowser v1.14.0
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

No, because the bug only occurs when `search.incremental` is false, but it is true by default. Changing just this setting to be false causes the issue to occur.

**Description**

When performing a forward search, using `/`, then searching for the exact same string backward, using `?`, pressing `n` to go to the next result continues to move forward instead of moving backward. The reverse also happens if you start with `?` and then switch to `/`. This only happens when `search.incremental` is set to false.

**How to reproduce**
1. Set `search.incremental` to be false
2. Open a webpage and press `/` to search for a string that appears more than once on that page (e.g., search `qute` on https://github.com/qutebrowser/qutebrowser).
3. Press `n` several times to confirm that the result navigation direction is forwards.
4. Press `?` and enter the same string.
5. Press `n`, and you should see that the result navigation direction does not change to backwards, but continues forwards.

**Comment by The-Compiler** [comment]
Thanks for the report - I can reproduce with `qutebrowser --debug --temp-basedir -s search.incremental false https://github.com/qutebrowser/qutebrowser` and the steps above.
