### ISSUE TITLE
Support for bindings that start with '<'?

### ISSUE THREAD

**Issue by ccressent** [qutebrowser/qutebrowser#5965]
**Version info**:
```
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0
```

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

I am trying to bind the `<<` key sequence to the `tab-move -` command, but all it does is bind `<`. That is, a single press of `<` moves my tab to the left by one.

**How to reproduce**

Try `:bind << tab-move -` and then press `<` once to see your tab move left.
Here is the relevant part of my config.py that achieves the same:
```
c.bindings.commands["normal"] = {
    "T": "set-cmd-text -s :buffer",

    "gt": "tab-next",
    "gT": "tab-prev",

    "<<": "tab-move -",
    ">>": "tab-move +",

    ",m": "hint links spawn umpv {hint-url}",
    ",M": "hint --rapid links spawn umpv {hint-url}"
}
```

My hunch is that there is some conflict with the fact that in bindings, `<` and `>` are used to denote modifier keys, e.g.: `<Alt-m>`.  I've tried various combinations to try and "escape" my `<`, but most of them either do not work or outright crash qutebrowser upon config sourcing. I recall having tried:

- `<<<`: still, a single `<` moves the tab left
- `<<><<>`: crashes qutebrowser because the key sequence cannot be parsed

As you can see in my config above, `>>` on the other hand is not a problem. I've tried `config.bind('<<', 'tab-move -')` as an alternative but I got the some results.

My questions thus are:
- Is this intended?
- Is there a way to create the binding I want?

**Comment by toofar** [comment]
Looks like this here? https://github.com/qutebrowser/qutebrowser/pull/4578

**Comment by The-Compiler** [comment]
Merging this into #3736, as (like @toofar mentioned) this should be fixed by #4578 as well. Right now, using `<Greater><Greater>` and `<Less><Less>`  should already give you the bindings you want.

**Comment by ccressent** [comment]
@The-Compiler
I've tried `<Greater><Greater>` as a replacement for `>>` and that works. `<Less><Less>` doesn't work as a replacement for `<<` though: it behaves as a single `<`. I've also tried `<Lesser><Lesser>` just in case, but that crashes Qutebrowser.

**Comment by The-Compiler** [comment]
Gnah, there are definitely a few bugs lurking there... I added a comment to #3736. As for the crash, that's most likely #3580 if you're doing this via `config.py`.
