### ISSUE TITLE
Jarring reflow when page-load completes if zoom.default!=100%

### ISSUE THREAD

**Issue by a-m-joseph** [qutebrowser/qutebrowser#5979]
**Version info**:
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v1.14.1
Git commit: 05817d062 on heads/v1.14.1 (2020-12-21 18:15:36 -0800)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.2
PyQt: 5.15.0

sip: 4.19.23
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.3.1
cssutils: no
attr: 20.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform plugin: wayland
OpenGL: X.Org, 4.5 (Compatibility Profile) Mesa 19.1.6
Platform: Linux-5.3.5+-x86_64-with-glibc2.29, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Jarring reflow when page-load completes if zoom.default!=100%.  Page is loaded with zoom=100%, then the zoom level suddenly changes to the configured default on completion of pageload.  This is very annoying and also causes erroneous mouse clicks because elements are jumping around underneath the mouse cursor.  See my PR for code to fix this.

**How to reproduce**
Set zoom.default to something other than 100% and load a webpage.  A heavyweight page on a high-latency connection will make the bug more obvious.

**Comment by a-m-joseph** [comment]
PR is 5980

**Comment by The-Compiler** [comment]
There's no way around this as far as I'm aware - Chromium/QtWebEngine set the page zoom somewhere during the load, so if we set it before the page is loaded fully, that's too early.
