### ISSUE TITLE
Secondary Font Option

### ISSUE THREAD

**Issue by keeganjk** [qutebrowser/qutebrowser#5983]
Would it be possible to add in an option to use as a secondary font option, to take the place of fonts not supported by the main font? In my terminal, `st`, I have it set so that I have one "main" font, an emoji font, and a CJK font—these secondary fonts display characters unavailable in the main font. Whenever I try to use CJK fonts in qutebrowser's interface, for example, it looks very unfitting.

**Comment by The-Compiler** [comment]
Website rendering is done via the underlying Chromium, and the existing `fonts.web.*` settings is all we can do. There might be some way to do this via fontconfig, but I have no idea how - if you find something that works with Chromium, chances are it'll work with qutebrowser as well.
