### ISSUE TITLE
Custom headers set in the configuration can't be overridden through JS (for XHR)

### ISSUE THREAD

**Issue by pacien** [qutebrowser/qutebrowser#5998]
**Version info**:

qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.8.6
PyQt: 5.15.2

sip: 4.19.24
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.2
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 20.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: no
pdf.js: 2.6.347 (/nix/store/ysdvxa0qdkvd48fd3zswpmyspblzbhvw-pdfjs-2.6.347/build/pdf.js)
sqlite: 3.34.0
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

**Does the bug happen if you start with `--temp-basedir`?**:

No (the bug is linked to the configuration).

**Description**

I suspect that setting a custom header value in the qutebrowser configuraton breaks request header overrides from JavaScript code instead of just setting a default value. This breaks XHR in some cases.

**How to reproduce**

To reduce fingerprinting, I've set a more common HTTP-Accept header (taken from the [Arch wiki]) in my qutebrowser configuration:

```python
c.content.headers.custom['accept'] = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
```

[Arch wiki]: https://wiki.archlinux.org/index.php/Qutebrowser#Set_a_common_HTTP_ACCEPT_header

This however seems to break some particular XHR calls on some websites such as GitHub and prevents the issue assignees dropdown from showing for example. The DevTools show that the associated request now has the Accept header forced to the value set above instead of `*/*` or `application/json` when no header is specified in the configuration.

**Comment by The-Compiler** [comment]
There's unfortunately no way for qutebrowser to know if something else in the network stack has already set the header. It can however detect when a network request has been made via XHR - I think it wouldn't be a good idea to turn off all header customization in that case, but [given that](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader):

> If no `Accept` header has been set [...], an `Accept` header with the type "`*/*`" is sent with the request when `send()` is called.

I guess it'd make sense to special-case the `accept` header here and not override it at all for XHR requests.
