### ISSUE TITLE
Decouple TabbedBrowser from TabWidget

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#600]
Currently `TabbedBrowser` subclasses `TabWidget` which is a pain sometimes. We should instead decouple those, and use composition instead of inheritance.

**Comment by ff2000** [comment]
How important is the tabbar to you? Is it important to keep a TabWidget as central part for "multi-buffer vim-like" browser?
The alternative would be to use QStackedWidget (which QTabWidget also uses internally) for a flat representation or directly implement a custom Widget with a tree structure as store (to implement fancy stuff like "tab grouping" etc. The top nodes of the tree could be windows - that way ":buffer" could also show windows ;))

(Just some random thoughts coming up when reading "refactoring" ;))

**Comment by The-Compiler** [comment]
Hmm - I definitely still want a tab bar - and currently using `QTabWidget` does that job very well, so I'm not sure what benefits using a custom bar and a `QStackedWidget` would give us.

The idea with a buffer tree might be worth a shot - but I'm trying to ignore completion issues until I refactored the completion (see #74). ;)

**Comment by jberglinds** [comment]
We'll take a look at this one, @The-Compiler.
Thank you for taking the time to look into stuff for us.
