### ISSUE TITLE
[readability-js] [help wanted]  ABP Adblocking breaks some images

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#6000]
**Version info**:

```
qutebrowser v1.14.1
Git commit: 6c2f15576 on master (2020-12-30 22:09:25 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2
```

``` shellsession
$ yay -Si python-adblock
Repository      : community
Name            : python-adblock
Version         : 0.4.0-1
Description     : Brave's adblock library in Python
Architecture    : x86_64
URL             : https://github.com/ArniDagur/python-adblock
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

I've come across a problem in the [readability-js userscript](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/readability-js), where, for whatever reason, some images are not rendered in readability's html output. So far, I haven't been able to discover a pattern to which images do and do not load.  

I've narrowed the problem down to having the recently added ABP-based adblocking method enabled (ping @ArniDagur). To wit: it doesn't occur when adblocking is off altogether, when only host blocking is on, and the HTML produced by the readability userscript does actually render normally in other browsers (e.g. firefox). Furthermore, the problem has only emerged very recently, without any clear to change to e.g. the underlying readability library used by the userscript.  Here is a link to a [HTML file produced by the readability-js userscript](https://gist.githubusercontent.com/rien333/6d948963434582f53939e98fd16e0dce/raw/e6655600301fa74f08f56088a9973707c8e71cd4/wiki%2520readability), if somebody wants to look at where the problem may lie.

---

To provide a visual example:

![2020-12-31-1609425380](https://user-images.githubusercontent.com/10417027/103414384-019d9880-4b7e-11eb-9ddb-c13de1ef0e58.jpg)

Previously, mathematical formula were shown at the broken image location, now  only the image's `alt` is displayed. As you may notice, there are other images on the page that do in fact load (not shown here)

---

For reference, here is how the html renders after running `:set content.blocking.method hosts`:

![2020-12-31-1609425566](https://user-images.githubusercontent.com/10417027/103414495-88527580-4b7e-11eb-894d-4d31c5e8593a.jpg)

---

**How to reproduce**
1. Make sure the new adblocking method is enabled.
2. Go to some [wikipedia page](https://en.wikipedia.org/wiki/Frequency_(statistics)#relative_frequency) or [this article](https://www.newyorker.com/magazine/2007/04/16/the-interpreter-2).
3. Run the readability-js script (`spawn --userscript readability-js`).
4. Various images won't be shown (but they will be if you open the "readable" html in an other browser by copying over the URL, or if you switch adblocking methods, and then reload)

**Comment by The-Compiler** [comment]
The logs say:

```
15:58:47 DEBUG    network    braveadblock:filter_request:190 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/add78d8608ad86e54951b8c8bd6c8d8416533d20 blocked by ad blocker.
15:58:47 DEBUG    network    braveadblock:filter_request:190 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/57f87f905ba5a4d8c691ccaecd65fc47bd007ba4 blocked by ad blocker.
15:58:47 DEBUG    network    braveadblock:filter_request:190 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/61bca88bb54862d881e92de20c5fa6a4c5626df1 blocked by ad blocker.
15:58:47 DEBUG    network    braveadblock:filter_request:190 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/65da883ca3d16b461e46c94777b0d9c4aa010e79 blocked by ad blocker.
15:58:47 DEBUG    network    braveadblock:filter_request:190 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/44d8ec988668e8333cabe9572c0f9d1fc65ec7cc blocked by ad blocker.
```

No idea why those would be blocked, though... @ArniDagur do you have any idea what's going on there?

**Comment by rien333** [comment]
So weird! (though the log matches my observations) Note that these urls render fine outside of the readability-js userscript (e.g. you can open the URL in a new tab). I've also noted that a lot of the images that fail to render are quite innocent (e.g. wikimedia stuff).

**Comment by The-Compiler** [comment]
If I run `python3 -m http.server` and access `http://localhost:8000/wiki.html` rather than loading it via a `file://` URL, it works fine as well.

I suppose either there is some rule somewhere preventing those requests from `file://` URLs, or something isn't handling `file://` URLs properly at all.

**Comment by ArniDagur** [comment]
I can reproduce this issue as well. Adding the source url and request type to the log message shows nothing unexpected:
```
18:03:27 DEBUG    network    braveadblock:filter_request:180 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/57f87f905ba5a4d8c691ccaecd65fc47bd007ba4 blocked by ad blocker from file:///home/arni/src/qutebrowser/reproc.html with resource type ResourceType.image
18:03:27 DEBUG    network    braveadblock:filter_request:180 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/61bca88bb54862d881e92de20c5fa6a4c5626df1 blocked by ad blocker from file:///home/arni/src/qutebrowser/reproc.html with resource type ResourceType.image
18:03:27 DEBUG    network    braveadblock:filter_request:180 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/65da883ca3d16b461e46c94777b0d9c4aa010e79 blocked by ad blocker from file:///home/arni/src/qutebrowser/reproc.html with resource type ResourceType.image
18:03:27 DEBUG    network    braveadblock:filter_request:180 Request to https://wikimedia.org/api/rest_v1/media/math/render/svg/44d8ec988668e8333cabe9572c0f9d1fc65ec7cc blocked by ad blocker from file:///home/arni/src/qutebrowser/reproc.html with resource type ResourceType.image
```
My gut tells me this issue has the same root cause as https://github.com/brave/adblock-rust/issues/146. I'll investigate further.

**Comment by The-Compiler** [comment]
@ArniDagur While you're at it, a PR to add those to the log message permanently might be a good idea? Thanks for taking a look! :+1:

**Comment by ArniDagur** [comment]
When the source URL (`file:///home/arni/src/qutebrowser/reproc.html`) is parsed, an error is returned due to the schema not being supported
```
        match scheme_type {
            SchemeType::File => {
                // println!("Parse file - not supported");
                Err(ParseError::FileUrlNotSupported)
            }
...
```
The error above is handled by setting the `source_hostname` and `source_domain` to empty strings.
```
            if let Some(parsed_source) = Request::parse_url(&source_url) {
                // ...
            } else {
                Ok(Request::from_detailed_parameters(
                    request_type,
                    &parsed_url.url,
                    parsed_url.schema(),
                    parsed_url.hostname(),
                    "",  // Notice this
                    "",  // Notice this
                    None,
                    parsed_url.hostname_pos.1
                ))
            }
```
We know from https://github.com/brave/adblock-rust/issues/146 there is a bug w.r.t. handling an empty string source url, so it's most likely the same issue.

For now I suggest turning
```
        if first_party_url is None or not first_party_url.isValid():
            return False
```
into
```
        if first_party_url is None or not first_party_url.isValid() or first_party_url.scheme() not in ("http", "https"):
            return False
```

**Comment by The-Compiler** [comment]
@ArniDagur Looks like the Brave library has three different kinds of URLs it supports:

```rs

impl SchemeType {
    pub fn is_special(self) -> bool {
        !matches!(self, SchemeType::NotSpecial)
    }

    pub fn from(s: &str) -> Self {
        match s {
            "http" | "https" | "ws" | "wss" | "ftp" | "gopher" => SchemeType::SpecialNotFile,
            "file" => SchemeType::File,
            _ => SchemeType::NotSpecial,
        }
    }
}
```

and it only rejects file URLs:

```rs
    fn parse_with_scheme(mut self, input: Input) -> ParseResult<Hostname> {
        let scheme_end = self.serialization.len();
        let scheme_type = SchemeType::from(&self.serialization);
        self.serialization.push(':');
        match scheme_type {
            SchemeType::File => {
                // println!("Parse file - not supported");
                Err(ParseError::FileUrlNotSupported)
            }
            SchemeType::SpecialNotFile => {
                // println!("Parse special, not file");
                // special relative or authority state
                let (_, remaining) = input.count_matching(|c| matches!(c, '/' | '\\'));
                // special authority slashes state
                // println!("Parse after double slash {}", remaining.chars.as_str());
                self.after_double_slash(remaining, scheme_type, scheme_end)
            }
            SchemeType::NotSpecial => {
                // println!("Parse non special {}", &self.serialization);
                self.parse_non_special(input, scheme_type, scheme_end)
            }
        }
    }
```

so I assume a `or first_party_url.scheme() == "file"` check would be better, so it doesn't affect any of the other handling?

**Comment by ArniDagur** [comment]
You're right. I was under the impression you couldn't "visit" any of the other schemes, but I was wrong. Try visiting ftp://ftp.adobe.com/ for example.
