### ISSUE TITLE
Control Plus is not bindable

### ISSUE THREAD

**Issue by IsaacElenbaas** [qutebrowser/qutebrowser#6003]
**Version info**:
qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Description**
`<Ctrl-->` and `<Ctrl+->` both work to bind control minus, but `<Ctrl-+>`, `<Ctrl++>`, and `<Ctrl-Plus>` do not work for control plus. The first two bind properly, as though they should work (doesn't say the key combo doesn't exist), but pressing it does nothing.

**Comment by The-Compiler** [comment]
If the key you're pressing requires pressing shift, you will need to specify that in your keybinding, i.e. `<Ctrl-Shift-+>` - see #3770.
