### ISSUE TITLE
Adopting qute-keepassxc userscript

### ISSUE THREAD

**Issue by ususdei** [qutebrowser/qutebrowser#6017]
Hi,

I am the author of [qute-keepassxc](https://github.com/ususdei/qute-keepassxc) - a userscript to fetch login credentials from an open KeepassXC database via its native browser extension API.

Installing and updating this userscript as a separate git clone is not really conveniant as one of its user pointed out recently (ususdei/qute-keepassxc#7).
I think the most comfortable way to use this script were as part of `qutebrowser` itself.

So this issue is mainly an upfront question on whether you would be willing to adopt and maintain my script as part of qutebrowser or if that required any significant changes first?
If so, I would gladly prepare a PR against qutebrowser next.

Thanks!

**Comment by The-Compiler** [comment]
Feel free to contribute it to `misc/userscripts/` - not much will change about the maintenance, though. I typically won't maintain userscripts in there, but I'd happily tag you if there are issues/PRs related to it.

**Comment by ususdei** [comment]
That would be great, so I can continue its maintenance there.

Let me clean up a few things then I will follow up with a PR within the next few days.

**Comment by The-Compiler** [comment]
@ususdei Any update on this?

**Comment by ususdei** [comment]
I tried to add some TOTP support to it last weekend, but it doesn't feel quiet usable yet.
Thus I just now submitted the script as it is now.
TOTP support might then follow later on.
