### ISSUE TITLE
Make content.canvas_reading configurable per site

### ISSUE THREAD

**Issue by cy8aer** [qutebrowser/qutebrowser#6018]
It would be nice to have `content.canvas_reading` configurable by site. This would allow to globaly disable canvas reading but make it available for sites which really need it (e.g. Matrix Element).

**Comment by The-Compiler** [comment]
This isn't possible at the moment, see [[QTBUG-84486] Add setting attribute to disable reading from canvas - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-84486) and #5439.
