### ISSUE TITLE
Switch from attrs to dataclasses?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6023]
Aaand another one potentially for v2.0.0...

We use [attrs](https://www.attrs.org/en/stable/), but only a rather small subset of its features (also see #5014). However, Python 3.7 has [dataclasses](https://docs.python.org/3/library/dataclasses.html) which, for our use-case, are probably pretty much a drop-in replacement.

For Python 3.6, there's a [backport on PyPI](https://pypi.org/project/dataclasses/) which we can use - that dependency would then only be required for Python 3.6 and can be dropped entirely when we drop support for Python 3.6 at some point in the future.

**Comment by m-zat** [comment]
Hi Florian,

I started working on this few days ago and already modified some files, if you want I can open a PR with what I have done and then you can start from that.
What do you think?

For the moment I refactored these files:
```
	modified:   qutebrowser/browser/webengine/interceptor.py
	modified:   qutebrowser/commands/command.py
	modified:   qutebrowser/commands/runners.py
	modified:   qutebrowser/completion/completer.py
	modified:   qutebrowser/config/configdata.py
	modified:   qutebrowser/config/configexc.py
	modified:   qutebrowser/config/configtypes.py
	modified:   qutebrowser/config/websettings.py
	modified:   qutebrowser/extensions/interceptors.py
	modified:   qutebrowser/extensions/loader.py
	modified:   qutebrowser/keyinput/basekeyparser.py
	modified:   qutebrowser/keyinput/keyutils.py
	modified:   qutebrowser/keyinput/modeman.py
	modified:   qutebrowser/mainwindow/prompt.py
	modified:   qutebrowser/mainwindow/tabbedbrowser.py
	modified:   qutebrowser/mainwindow/tabwidget.py
	modified:   qutebrowser/mainwindow/windowundo.py
	modified:   qutebrowser/utils/usertypes.py
	modified:   qutebrowser/utils/version.py
```

**Comment by The-Compiler** [comment]
I've also started working on this in the `dataclass` branch and I think I'm almost finished - so I suppose finishing the work there will be easier. This is exactly why the contribution guidelines say to comment on an issue before starting work on it :wink:

**Comment by m-zat** [comment]
No problem, it was still a useful exercise :)

**Comment by The-Compiler** [comment]
@m-zat Mind pushing your branch to your repository (unless it's already there and I missed it) as well? It might still be useful to diff it to my changes to make sure I didn't miss anything :slightly_smiling_face:

**Comment by m-zat** [comment]
@The-Compiler, just pushed to my master branch. These pass mypy but I did not run pytest.

**Comment by The-Compiler** [comment]
Thank you! Glad to hear it was a good exercise and not just lost time :slightly_smiling_face: I hope you don't mind a bit of feedback - I saw two issues while comparing it with my changes:

- With dataclasses, every attribute will need a type annotation, otherwise Python will complain. This is actually the part of this which probably takes the most time and requires the most knowledge of the codebase (even I am unsure about a couple of remaining items).
- Mutable default values are a problem - if you have e.g. `... = attr.ib(default=attr.Factory(dict))`, that should become `... = dataclasses.field(default_factory=list)`. Otherwise, Python complains because all instances of the class would share the same value. The docs have some more information: https://docs.python.org/3/library/dataclasses.html#mutable-default-values
