### ISSUE TITLE
[Feature Request] Chromecast Support

### ISSUE THREAD

**Issue by ozgurgulsuna** [qutebrowser/qutebrowser#6024]
Chromecast is widely used upon many devices these days. For linux users there is not any casting application (mkchromecast, castnow, catt...) that works properly, without delay, lag etc. Now that Qutebrowser integrates Webengine support throught QtWebengine, the program seems more robust than ever. Also, it feels like it is a true replacement to Chromium for people who really want VIM like customizable and light browser to use.

As discussed on an issue over at the qutebrowser repository [2], integrating chromecast support as well as it is done on chromium would require QtWebengine's support. More precisely, casting a tab's content doesn't seem feasible without QtWebengine integrating chromecast streaming code. I really think that this would be a great addition to the QtWebengine project as many use cases are easily imaginable.

Is there any plan to integrate chromecast support in the near future? Otherwise, please consider it.

Regards,

**Comment by The-Compiler** [comment]
I'm a bit confused by the issue - this *is* the qutebrowser repository.

However, there already is a feature request open over in the QtWebEngine bug tracker: [[QTBUG-61352] [Feature Request] chromecast support - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-61352)

**Comment by The-Compiler** [comment]
Wait... You just copied the text from that issue to here? That... really won't help.
