### ISSUE TITLE
Allow blocking new tab for target=_blank

### ISSUE THREAD

**Issue by Arteneko** [qutebrowser/qutebrowser#6026]
Some websites abuse usage of `target=_blank`.

It would be very useful to have a setting allowing to ignore said property and instead open the link in the current context (keeping the usual behaviour of middle click opening in a new tab, obviously).

**Comment by The-Compiler** [comment]
You can use `;f` (`:hint all tab-fg`) to force opening tabs in the foreground. For normal links being opened, there's no way for qutebrowser to tell apart the user opening in a new tab or `target=_blank` doing so (see #3231).

Perhaps there's a way to modify those links via a Greasemonkey script - but if so, you can do that without any changes needed in qutebrowser.

**Comment by arza-zara** [comment]
You can also do `:bind f hint all current`.
