### ISSUE TITLE
qutebrowser crashes whole system

### ISSUE THREAD

**Issue by user-b** [qutebrowser/qutebrowser#6027]
**Version info**:
I had this problem for more than a year, using stable qutebrowser from nixpkgs (currently 1.13.1). Switching now to unstable (1.14.1) didn't solved it.

qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Description**
Qutebrowser crashes too often, screen goes black and there is nothing I can do except pressing the reset button. Then I have filesystem errors on boot and last time I couldn't even boot anymore until repairing partitions. 

It only happens when using qutebrowser, often with many tabs (60 - 80 which is standard for me) and/or when visiting webstores and/or blogs full of crap. There is no single website I can blame. If all my tabs are simple sofware related sites (reddit, github, docs, stackoverflow..) nothing bad happens. But when I start to search junk to buy on bloated sites (full of ads and js I assume) often it crashes and it's very predictable it will happen.

I don't know if it's a bug. I can live with it but I think I was regularly using 60+ tabs on firefox on windows with only 6gb of ram many years ago without any problems so I assume it's a bug. Hardware temperatures are normal when it happens. Also I didn't had this problem with older versions of qutebrowser.

I tried to follow [these](https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc#crashes-which-can-not-be-reproduced) instructions. 

/proc/sys/kernel/core_pattern: `|/nix/store/lqv1qn0r19kzc9hhibj8k667049196wr-systemd-246.6/lib/systemd/systemd-coredump %P %u %g %s %t %c %h`

```
$ coredumpctl gdb $(readlink -f $(which python3))
Cannot access memory at address 0x7fc203698188
Cannot access memory at address 0x7fc203698180
Failed to read a valid object file image from memory.
--Type <RET> for more, q to quit, c to continue without paging--

(gdb) set logging overwrite on
(gdb) set logging on
Copying output to gdb.txt.
Copying debug output to gdb.txt.
(gdb) bt
#0  0x00007fc2032c95ba in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fc175ff8328
(gdb) quit

```

```
$ cat gdb.txt
#0  0x00007fc2032c95ba in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fc175ff8328
Undefined command: "".  Try "help".
Undefined command: "".  Try "help".
Undefined command: "".  Try "help".
Undefined command: "Copying".  Try "help".
Undefined command: "Copying".  Try "help".
Undefined command: "".  Try "help".
Undefined command: "Backtrace".  Try "help".
Undefined command: "".  Try "help".

```

**Comment by The-Compiler** [comment]
I highly doubt this is a bug in qutebrowser. If anything, it'd be a bug in the underlying library (QtWebEngine), but even that is unlikely. The most likely explanations I can think of are a bug in your graphic driver (#5178) or perhaps faulty RAM.

A couple of things you could try:

- Use Chromium for a while and see if it happens there
- Use KDE Falkon (another QtWebEngine-based browser) for a while and see if it happens there
- SSH in from another machine, start `dmesg -w` and hope you'll see something in there before the freeze happens

FWIW I'm going to convert this to a discussion as soon as GitHub restores that feature (it was pulled temporarily because of some kind of critical bug), as I don't think there's anything qutebrowser can do here.

**Comment by user-b** [comment]
Thanks, using `config.set('qt.force_software_rendering', 'software-opengl')` as you said in [#5178](https://github.com/qutebrowser/qutebrowser/issues/5178) apparently solved it.

**Comment by user-b** [comment]
Hello. I don't know if this issue should be kept open. I kinda got used to it so it's not that much of a problem if there is nothing to do about it.

In the end, the problem persists. When using software rendering, the system just slows down dramatically and eventually (sometimes, not that often) it hangs completely without crashing, in those situations previously mentioned involving having much tabs, suddenly opening a bunch of new tabs and browsing comercial sites / blogs full of crap. The problem behind those hangs/crashes seems to be that qutebrowser takes all the memory available (16gb + 8gb sw) in both cases. I have no idea and I'm not blaming anybody but I assume it's not normal as puting this kind of load was fine with only 6gb many years ago with other browsers.

Maybe related to #5586 ? Should I report this bug elsewere?

Thanks again.

**Comment by user-b** [comment]
Hello. I don't know if this issue should be kept open. I kinda got used to it so it's not that much of a problem if there is nothing to do about it.

In the end, the problem persists. When using software rendering, the system just slows down dramatically and eventually (sometimes, not that often) it hangs completely without crashing, in those situations previously mentioned involving having much tabs, suddenly opening a bunch of new tabs and browsing comercial sites / blogs full of crap. The problem behind those hangs/crashes seems to be that qutebrowser takes all the memory available (16gb + 8gb sw) in both cases. I have no idea and I'm not blaming anybody but I assume it's not normal as puting this kind of load was fine with only 6gb many years ago with other browsers.

Maybe related to #5586 ? Should I report this bug elsewere?

Thanks again.

**Comment by The-Compiler** [comment]
That's likely unrelated - see #1476, especially https://github.com/qutebrowser/qutebrowser/issues/1476#issuecomment-733019169
