### ISSUE TITLE
cannot paste content in cryptpad

### ISSUE THREAD

**Issue by parisni** [qutebrowser/qutebrowser#6029]
**Version info**:

```
qutebrowser v1.14.1
Git commit: 2e65f731b on master (2020-12-04 21:13:36 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
I cannot paste content within the textarea of the online cryptpad

**How to reproduce**

go on this url https://cryptpad.fr/code/#/2/code/edit/gs6knAkQeKumfiyGGPgVc2KT/

and try to paste something into the text-area : this will raise an error “element is not editable” unless you use right click copy/paste

**Comment by The-Compiler** [comment]
Works fine here. How exactly are you pasting?

**Comment by parisni** [comment]
hey !

I am pasting this way:

```python
config.bind('<Ctrl+y>', 'insert-text {clipboard}', mode='insert')
```

**Comment by The-Compiler** [comment]
This is essentially the same issue as #2545 I think. You should have better luck if you use a way which doesn't involve `:insert-text`: Either `:fake-key <Ctrl+v>` or `:debug-webaction Paste` (semi-public at the moment, also see #6037).
