### ISSUE TITLE
Cannot map ; to : (semicolon to colon)

### ISSUE THREAD

**Issue by adityadesaha** [qutebrowser/qutebrowser#6031]
I want to map ; to : in normal mode, so that I can go to the commands quickly. In my config.py I tried doing
```
c.bindings.key_mappings= {
        ";":":",
}

```

But this does not work. why?

**Comment by The-Compiler** [comment]
Because there are existing bindings starting with `;` which will take precedence - you will need to unbind those for this to work.

**Comment by arza-zara** [comment]
Or `config.bind(';', 'set-cmd-text :')`.
