### ISSUE TITLE
Error while opening https://www.tradingview.com

### ISSUE THREAD

**Issue by rhysday** [qutebrowser/qutebrowser#6032]
**Version info**:
qutebrowser v1.14.1
Git commit: 4a7406fe3 on master (2021-01-05 19:50:48 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Unable to load page
Error while opening https://www.tradingview.com/
Renderer process was killed

**How to reproduce**
Visit https://www.tradingview.com

**Comment by The-Compiler** [comment]
Does it work with `--temp-basedir --qt-flag disable-features=InstalledApp`?

**Comment by rhysday** [comment]
Yes, that does work. 
What do I have to add in my config to keep this fix?

**Comment by The-Compiler** [comment]
Duplicate of #5997

**Comment by The-Compiler** [comment]
I'll push a workaround shortly - in the meantime, you can `disable-features=InstalledApp` to the `qt.args` setting, e.g. via `:config-list-add qt.args disable-features=InstalledApp`.

**Comment by rhysday** [comment]
In qutebrowser I typed:
:config-list-add qt.args disable-features=InstalledApp
Hit enter
Not sure if I'm doing this right? Trading View still doesn't load

**Comment by rhysday** [comment]
Is there something I can add to my config.py instead?

**Comment by The-Compiler** [comment]
Sure, `c.qt.args = ["disable-features=InstalledApp"]` - also see the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).

**Comment by rajendrasp** [comment]
I do not know if it is okay to ask here on a closed thread but it is a follow up. I am also getting this crash for tradingview.com. and I have a GUI PyQt5 app in which I am using a QWebEngineView to render tradingview website in a layout. So @The-Compiler , you mention the solution to add it config.py but I do not have that file. How do I resolve this crash? And it is resolved yet in latest PyQt5?

**Comment by The-Compiler** [comment]
@rajendrasp This isn't really the right place to get support for QtWebEngine outside of qutebrowser, even less so if you comment on multiple duplicate issues about the same topic...
