### ISSUE TITLE
problem to create a repository

### ISSUE THREAD

**Issue by Laura-ddr** [qutebrowser/qutebrowser#6033]
hello everyone, I'm coming back to you for a problem I've been having for some time, I can't create a repository it doesn't accept the name I give it "Something went wrong" signalled in red... In spite of the use of the inspiration they propose me I can't find the solution :(

I hope you'll be able to answer it...
good day to all

**Comment by The-Compiler** [comment]
Hey! This is the issue tracker of a [specific project](https://www.qutebrowser.org). You probably want to post to the [GitHub community](https://github.community/) or [contact GitHub support](https://support.github.com/contact) instead.
