### ISSUE TITLE
v1.14 window freezes

### ISSUE THREAD

**Issue by moorchegue** [qutebrowser/qutebrowser#6036]
**Version info**:
```
qutebrowser v1.14.1
Git commit:
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.4
yaml: 5.3.1
cssutils: no
attr: 20.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.34.0
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.3.2
Platform: Linux-5.10.5-arch1-1-x86_64-with-glibc2.32, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Does the bug happen if you start with `--temp-basedir`?**:
Hard to say, it takes some time to catch this and it's difficult to browse normally without all the custom settings long enough to reproduce this. Intuitively speaking it probably does.

**Description**
Ever since the upgrade to 1.14.1 (or possibly even since 1.14.0) qutebrowser started freezing up at random moments. Most frequently it happens when I switch between apps or virtual screens. When I switch back the qutebrowser window doesn't render its content, instead whatever was displayed on the screen before the switch is stuck there like a screenshot.

Most of the time there's no reaction to any hotkeys, but every once in a while it reacts to the first key press (I tried `J` / `K` for `tab-prev` / `tab-next` and observed change in the window title bar and corresponding log output in `--debug` mode), after that it freezes completely. No error messages or any other relevant information seems to be recurring in `--debug` mode.

It feels like some underlying renderer problem. It might be worth to mention that there was a couple of `qt5-webengine` upgrades (5.15.1-3 -> 5.15.2-1 -> 5.15.2-2 -> 5.15.2-3) in the same period of time (last month or so). I also checked that this doesn't happen with Chromium or Firefox on my computer.

**How to reproduce**
Hard to reproduce reliably as it happens unexpectedly after minutes to hours of browsing. Possible trigger is windows switching, but it's not always the case and could be coincidental.

This feels like a tricky bug to catch, so please let me know if there's anything I can do debug this on my side or provide any additional information.

**Comment by The-Compiler** [comment]
This is very unlikely to be a qutebrowser issue - it's probably either an issue in the underlying QtWebEngine (still unlikely), or graphic driver (most likely, unfortunately).

You seem to be on Intel graphics - is this with `xf86-video-intel` installed? If so, can you try to uninstall that (i.e. use the modesetting driver) and see if it still happens?

**Comment by moorchegue** [comment]
You're right. I downgraded `xf86-video-intel` and things got back to normal.

Any idea why only qutebrowser was affected by this?

**Comment by The-Compiler** [comment]
Unless you have a good reason to install `xf86-video-intel`, I'd recommend not doing so at all, as that driver is quite buggy. See e.g. the note here: https://wiki.archlinux.org/index.php/Intel_graphics#Installation

It's very unlikely to only affect qutebrowser. You'd see the same with any other QtWebEngine-based browser such as KDE Falkon. I think some of those issues stem from QtWebEngine using multithreaded OpenGL (as far as I understand, so that Chromium can render things, but Qt can display them).

Alternatively, you can play with the `qt.force_software_rendering` setting, but it'll come with a performance penalty attached.

**Comment by moorchegue** [comment]
Gotcha, thanks for the tips!
