### ISSUE TITLE
Use classes for the sql database

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6039]
Right now, we have a global SQL database (the one we get from `QSqlDatabase.database()`) and everything in `sql.py` acts on that.

This caused me some confusion and pain when working on #6019, most notably in `TestRebuild` - as it effectively isn't really possible to create a second database to test things. Also, I've always found it kinda weird to have `sql.Query` and `sql.SqlTable` magically act on some kind of (hidden) singleton.

Finally, with #6019 I've had to add a `_db_user_version` global because there's no real "database" object I could attach it to.

I feel like we should have a `sql.Database` object instead, which then:

- Has a `.query(...)` method to get a `Query` object associated to that database
- Has a `.table(...)` method to get a `Table` object associated to that database
- Has a `._user_version` attribute storing its user version and a corresponding `user_version_changed` method
- Takes care of creating the underlying Qt database in its `__init__` rather than a global `sql.init()`

Then, we could have a `db` attribute in `WebHistory` instead. For the (rare) case that we need to access it from outside that module, we can do `history.web_history.db.query(...)` which seems like much more natural than just magically creating a `sql.Query` object.

@rcorre What do you think? It seems much cleaner to me and also would make it easy to create a second database for testing (so that we can simulate the "old" database a user has on disk, and the "new" database we're migrating to).

**Comment by rcorre** [comment]
Sounds good to me!
