### ISSUE TITLE
Popups not scaled if output is scaled and translated (Wayland HiDPI)

### ISSUE THREAD

**Issue by edrex** [qutebrowser/qutebrowser#6043]
This is a qtwebengine bug that also happens with Falkon, but reporting here to track. 

Env: wlroots-based wayland compositors (possibly others, haven't tested)

Description: Popups such as in [bug-tests/select.html](https://qutebrowser.org/bug-tests/select.html) aren't scaled correctly with the output if both:

- output is scaled (2x)
- output is positioned away from origin

Screenshots at original report: ifreund/river#195.

**Version info**:
qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Comment by The-Compiler** [comment]
> This is a qtwebengine bug that also happens with Falkon, but reporting here to track.

Can you elaborate? There's nothing qutebrowser can do here, and I probably can't easily reproduce this myself - so why not report it in Qt's bugtracker instead? :slightly_smiling_face:

**Comment by edrex** [comment]
Well.. I like to have to have a closed issue downstream so there's something to link through, and while I wanted to make sure I reported up, filing a JIRA issue felt like too much last night. I figured you would nag me if I reported here (maintainer abuse)

just being honest :)

**Comment by edrex** [comment]
[[QTBUG-90364] Select popups not scaled when HiDPI scaled output is offset - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-90364)
