### ISSUE TITLE
mode-enter command missing, enter-mode is available on current master version

### ISSUE THREAD

**Issue by DatGizmo** [qutebrowser/qutebrowser#6053]
**Version info**:
qutebrowser v1.14.1
Git commit: 222f1f19a on HEAD (2021-01-20 20:06:19 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.8.6
PyQt: 5.15.2

sip: 4.19.24
colorama: 0.4.4
jinja2: 2.11.2
pygments: 2.7.4
yaml: 5.4
adblock: 0.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
I'm running the current master commit version to test the python-adblock so I don't know if this is related.
The qute-pass script was complaining that 'There is no command mode-enter'.
But in the command list I still find 'enter-mode'

**Comment by rien333** [comment]
Yeah, that setting got renamed for the upcoming 2.0 release. See the [changelog](https://github.com/qutebrowser/qutebrowser/blob/master/doc/changelog.asciidoc) (search for "renamed commands").

Major releases (2.0, 3.0, etc.) sometimes introduce breaking changes like this (see semantic versioning).

You should probably close this, as this isn't really an issue but a documented change.

**Comment by DatGizmo** [comment]
Ok, I figured out what was wrong... I feel so stupid now.
I updated qutebrowser to the latest master commit, but didn't restart.
Meaning the browser still had "enter-mode" but the scripts underneath where already changed to "mode-enter"
Sorry for filling an unnecessary bug report -_-

**Comment by The-Compiler** [comment]
No worries!
