### ISSUE TITLE
Scrolling on tagesschau.de stutters

### ISSUE THREAD

**Issue by schuppentier** [qutebrowser/qutebrowser#6054]
**Version info**:
```
qutebrowser v1.14.1
Git commit: 917b42c84 on master (2020-12-23 11:40:14 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.4
yaml: 5.3.1
adblock: 0.4.0
attr: 20.3.0
importlib_resources: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.6.347 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.34.0
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 20.3.3
Platform: Linux-5.10.8-zen1-1-zen-x86_64-with-glibc2.32, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/dstengele/.cache/qutebrowser
config: /home/dstengele/.config/qutebrowser
data: /home/dstengele/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/dstengele/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:37
```

**Does the bug happen if you start with `--temp-basedir`?**
Yes, the behaviour is exactly the same.

**Description**
When opening tagesschau.de and scrolling, the scrolling stutters. This seems to be related to the background image set via CSS. When disabling the two background properties the background image is not shown anymore and scrolling works fine.

The CSS rules are:
```
body.tagesschau {
    background: #015999 url(../img/tagesschau/background/base.jpg) repeat-x fixed top;
}
body.tagesschau {
    background: #08335e url(../img/tagesschau/background/base.jpg) repeat-x fixed top;
}
```

**How to reproduce**
Open tagesschau.de and scroll the page.

**Comment by The-Compiler** [comment]
This doesn't seem to be specific to qutebrowser - I reported it upstream: [[QTBUG-90543] Bad scrolling performance on tagesschau.de - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-90543)

**Comment by The-Compiler** [comment]
Looks like they can't reproduce it - even I'm not entirely sure if I can, it's rather subtle. I wonder if this is specific to AMD graphics perhaps?

**Comment by The-Compiler** [comment]
Looks like they can't reproduce it - even I'm not entirely sure if I can, it's rather subtle. I wonder if this is specific to AMD graphics perhaps?

**Comment by schuppentier** [comment]
Welp, it also looks like the website is being relaunched in a new design today: https://blog.tagesschau.de/2021/01/26/willkommen-bei-der-neuen-tagesschau-de/

Talk about great timing... :D

**Comment by The-Compiler** [comment]
Argh, damn! I'm going to close the Qt bug then, no point in them putting more time into this I'm guessing...

Let me know if you can reproduce this on a different website though.
