### ISSUE TITLE
Virus scanner false-positives with v2.0.x

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6081]
Here we go again (see #4269)....

[v2.0.0](https://www.virustotal.com/gui/file/e9da9077e793cde92bd6bc101659fec8238a74149b14c06dc4b1810141f8cd50/detection), [v2.0.1](https://www.virustotal.com/gui/file/1f1be4d41a03d059dd87583cabcd8d93b2631c117bff3dcb988f91f268c8787d/detection)

![image](https://user-images.githubusercontent.com/625793/106177917-6bb75680-6199-11eb-9059-325bbe05e4ab.png)

Those are all false-positives as far as I can tell. Probably I'll need to submit another couple of appeals to AV vendors. If anyone wants to help with a rather boring task, that'd be most welcome.

**Comment by kuspoes** [comment]
I have sent a false positive request to Bitdefender (and Emsisoft which uses Bitdefender technology to scan files)

**Comment by kmorihiro** [comment]
I sent a false positive request to Symantec and it was verified. The detection has now been removed from Symantec products.

**Comment by The-Compiler** [comment]
@kuspoes @kmorihiro Great, thank you so much! Let's hope this also helps for the v2.0.2 release...

If anyone else is seeing this with another antivirus vendor, I'd love if you could do this as well, rather than me having to submit it everywhere.

**Comment by The-Compiler** [comment]
Microsoft should hopefully be fixed as well according to [a Reddit comment](https://www.reddit.com/r/qutebrowser/comments/l8oxda/windows_10_immediately_removes_qutebrowser_even/gli3iep?utm_source=share&utm_medium=web2x&context=3) (thanks to u/awepow!)

**Comment by bitraid** [comment]
I found out that adding a PE checksum to `qutebrowser.exe`,  the number of false positives for v2.02 goes down from [31](https://www.virustotal.com/gui/file/cb416f27e5dead44499a7e4d7e35c49697bfea262b28308a7a4f5eb7579670ef/detection) to [7](https://www.virustotal.com/gui/file/6ff31f225fc3a7386aea976ca27c457eb35b9788d7fb0737abec3abda7cbe353/detection). Similarly v2.0 goes down to [6](https://www.virustotal.com/gui/file/484840b3821f039bc32e773fc8da2506c75d6476066cbfe72b109fbcdd611b58/detection) from [29](https://www.virustotal.com/gui/file/484840b3821f039bc32e773fc8da2506c75d6476066cbfe72b109fbcdd611b58/detection) and v2.1 goes down to [8](https://www.virustotal.com/gui/file/bb2aab3cf8a401d619a0d47177fd6e394dadc3089bf26b4cd85c846504ddd46d/detection) from [15](https://www.virustotal.com/gui/file/1f1be4d41a03d059dd87583cabcd8d93b2631c117bff3dcb988f91f268c8787d/detection).

An open source tool to update the checksum: https://gist.github.com/jay/d662cc9615f3e1ffc75e4ae9485da685
The binary: [FixPEChecksum.exe.gz](https://github.com/qutebrowser/qutebrowser/files/6004945/FixPEChecksum.exe.gz)


Maybe this should be forwarded to Pyinstaller, as I think it would  benefit more programs with the same issue. AFAIK Pyintaller
does not write a checksum to the executable (has value 0).

**Comment by Zhnafany** [comment]
![image](https://user-images.githubusercontent.com/311738/108564534-f1976f00-730b-11eb-8986-4c4e8c19d4eb.png)

**Comment by The-Compiler** [comment]
@bitraid Oh, that's certainly interesting! I'm splitting this to #6194.

@Zhnafany Awesome, thank you!

**Comment by The-Compiler** [comment]
I've now regenerated and pushed v2.0.2.post1 releases for Windows with the fixed checksum. Now [Microsoft does detect it as malware again](https://www.virustotal.com/gui/file/0719dfad4c25385b9490cda2e9fb8e4f9770076f715b8c5fb0be9db661be5ece/detection)...

Argh. This is all so random. :cry: 

I've submitted another false-positive report to Microsoft. Perhaps this at least improves the situation for other scanners.

**Comment by bitraid** [comment]
Maybe Pyinstaller should modify slightly its boot loader for Windows. I found out that a very small change at the beginning of the binary code of `runw.exe`, brings down the number of false positives from [13](https://www.virustotal.com/gui/file/749666ba5af516692ff3716000b992cbcf2857e825c9c1d94fac7ac8ba11759e/detection) to [2](https://www.virustotal.com/gui/file/c9b1afe4698a82c98499f67aa9734b2a13cd97a7b09e346d092279eace376cf3/detection), without even fixing the checksum. Applying the change to the programs that use it, gives similar results (for `qutebrowser-2.0.2.post1-x64` it brings down the number to [3](https://www.virustotal.com/gui/file/754fd9519be117fc747f2c51043e7743e4b1da3fc5f73ea4a583a052006baa8e/detection) from [6](https://www.virustotal.com/gui/file/0719dfad4c25385b9490cda2e9fb8e4f9770076f715b8c5fb0be9db661be5ece/detection)). For my test I just increased the value of `rsp` to hold one more local variable on the stack:
```asm
40 53                   push    rbx
48 83 EC 20             sub     rsp, 20h  ; Change to 30h by modifying the byte at offset 405h
E8 AD 94 00 00          call    14000A4B8
48 8B D8                mov     rbx, rax
E8 9D 94 00 00          call    14000A4B0
48 8B 13                mov     rdx, [rbx]
8B 08                   mov     ecx, [rax]
E8 73 43 00 00          call    140005390
48 8B D8                mov     rbx, rax
E8 8B 94 00 00          call    14000A4B0
48 8B D3                mov     rdx, rbx
8B 08                   mov     ecx, [rax]
48 83 C4 20             add     rsp, 20h  ; Change to 30h by modifying the byte at offset 42Dh
5B                      pop     rbx
```
But maybe it is just hopeless, and any change will be flagged again as soon as malware starts using it.

**Comment by The-Compiler** [comment]
@bitraid It looks like after fixing the checksum, [they're now down to 0](https://www.virustotal.com/gui/file/46ca75e577bd26439175d69f6f260d4687953c8e0f1933c9383e2b4de2bef583/detection). But like you've seen yourself, we might as well just throw some dice to get the same results, so I doubt that change will actually improve anything in the long run.
