### ISSUE TITLE
config.load_autoconfig(False) after config.source doesn't work

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6099]
Running `python3 -m qutebrowser --temp-basedir --config-py config.py` with this `config.py`:

```python3
config.source('second.py')
config.load_autoconfig(False)
```

and an empty `second.py` results in the *"Your config.py should call either `config.load_autoconfig()` (to load settings configured via the GUI) or `config.load_autoconfig(False)` (to not do so)"* error.

Moving the `config.load_autoconfig(False)` above the `config.source()` call seems to help.

cc @Jan-PieterBaert

**Comment by Jan-PieterBaert** [comment]
This seems to be because the error is thrown after the `config.py` is read (in the `finalize` function line 630 of `qutebrowser/config/configfiles.py`)
Do you have any idea where the error should be thrown otherwise

**Comment by The-Compiler** [comment]
Hmm, perhaps the `warn_autoconfig` attribute should be on the `ConfigAPI` object directly (rather than `self._config` - it doesn't seem to be used anywhere else)?

Then, `read_config_py` could have an argument (say, `warn_autoconfig=False`) which it gets from `ConfigAPI.source` and passes through to the new `ConfigAPI` constructor, which could then set `self._warn_autoconfig` accordingly.

**Comment by The-Compiler** [comment]
@Jan-PieterBaert @jacksmaran (If your :eyes: reaction means "taking a look"), how are things going here? I want to release v2.0.2 soon (probably tomorrow), so unless you have a fix for this in the works already, I'll probably take over here.

**Comment by The-Compiler** [comment]
I actually couldn't resist working on a fix for this so that everything is ready for a v2.0.2 :sweat_smile: I hope you don't mind if this lead to some duplicated work.

**Comment by Jan-PieterBaert** [comment]
I haven't started on this issue yet because I didn't have much time, so no problem for fixing it, I'm happy to see it fixed :)
