### ISSUE TITLE
render process crashed

### ISSUE THREAD

**Issue by lapingenieur** [qutebrowser/qutebrowser#6103]
## Version info :
```
qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
```
**The bug happens with `--temp-basedir` too**

**The bug happens even if deleted the cache directory**

## Description :

I get the error `Render process crashed` when I try to open several sites, by example [google translate](translate.google.com), [duckduckgo](duckduckgo.com), [google](google.com)

I happens when there's a searching/text box to type in (but if it's inactive, nothing happens like if I don't type anything into duckduckgo's searchbox)

I use manjaro but I have used the qutebrowser since the last update without getting any error (surely not an upgrade problem).

**Comment by The-Compiler** [comment]
Anything interesting on stdout when this happens? Can you try to reproduce with another QtWebEngine-based browser such as KDE Falkon as well?

**Comment by rr559** [comment]
Completely

**Comment by lapingenieur** [comment]
Falkon also crashed after the same actions, qutebrowser's debugging output for this error is

```
ERROR    webview    tabbedbrowser:show_error_page:956 Renderer process crashed
```

**Comment by The-Compiler** [comment]
Do you get anything above that?

**Comment by lapingenieur** [comment]
[This](https://asciinema.org/a/yw1Ct7YHAOXt7c7PJOQ26AnGo) is the whole debugging output, error occurs at 20:44:66, after 20:44:51 it's only me closing the qutebrowser.

**Comment by lapingenieur** [comment]
The bug disapeared now, maybe after an update (there were several updates since I opened this issue)

**Comment by The-Compiler** [comment]
Glad to hear - thanks for the follow-up!
