### ISSUE TITLE
Ranger file picker does not work

### ISSUE THREAD

**Issue by emanrdesu** [qutebrowser/qutebrowser#6107]
**Version info**:

qutebrowser v2.0.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
**Does the bug happen if you start with `--temp-basedir`?**:
No
**Description**
I set fileselect.handler to "external" and it chooses ranger, but when I choose a file, nothing is chosen. A file named "{}" remains on my home directory though.
**How to reproduce**
`:set fileselect.handler external`
I did  use urxvtc instead of xterm, but I don't think that matters.

Also, wouldn't it be better to support file pickers who print to stdout instead of printing to a specific file???
I'm also confused about the need for '{}', and what '{file}' even means. I changed the {} to {file} and it just created a file literally named '{file}'
It seems this feature is centered around ranger, but what if I desire to use something like sxiv or dmenu? both of these print to stdout, and I'd love for it to be supported.

Unrelated, but due to the python-adblock support, I'm inclined to donate. Do you have a monero address?

**Comment by The-Compiler** [comment]
Can you please show the exact command you set?

**Comment by The-Compiler** [comment]
FWIW I've tried with `:set fileselect.single_file.command '["urxvt", "-e", "ranger", "--choosefile={}"]'` which seems like what you describe, but I can't reproduce this (on [this demo page](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file)).

> I'm also confused about the need for '{}', and what '{file}' even means. I changed the {} to {file} and it just created a file literally named '{file}'

Where are you getting `{file}` from? I didn't check in the code, but I think it's only defined for `editor.command` (which takes multiple different placeholders).

> Also, wouldn't it be better to support file pickers who print to stdout instead of printing to a specific file???

Seems like a good idea to support that as well (probably if `{}` isn't contained in the commandline). @AckslD is this something you'd like to work on?

> Unrelated, but due to the python-adblock support, I'm inclined to donate. Do you have a monero address?

See the [readme](https://github.com/qutebrowser/qutebrowser#donating) for details - I don't have Monero set up at the moment, but I could do so if that's what you prefer.

However, if @ArniDagur happens to accept donations via Monero, I'd prefer the donation going to him instead - he has done the bulk of the work on the new adblocker.

**Comment by ArniDagur** [comment]
> However, if @ArniDagur happens to accept donations via Monero, I'd prefer the donation going to him instead - he has done the bulk of the work on the new adblocker.

I appreciate the thought, but I don't accept donations. Thank you :)

**Comment by AckslD** [comment]
> Seems like a good idea to support that as well (probably if {} isn't contained in the commandline). @AckslD is this something you'd like to work on?

@The-Compiler I agree that it would be nice to support as well. I can take a look at this. Should there be a separate issue for that?

**Comment by emanrdesu** [comment]
> Can you please show the exact command you set?
`:set fileselect.multiple_files.command ["urxvtc", "-e", "ranger", "--choosefiles={}"]`
`:set fileselect.single_file.command ["urxvtc", "-e", "ranger", "--choosefile={}"]`

>where are you getting {file} from
If you change any of the above's choosefile part like so
`--choosefile=/tmp/fileselect`
A error message appears with the following
_"Invalid value '['urxvtc', '-e', 'ranger', '--choosefile=/tmp/fileselect']' - needs to contain a {}-placeholder or a {file}-placeholder."_

So I changed it to {file} instead, but it was the same as {}.
Might the problem be my shell, somehow?
I use zsh, which I know handles some characters differently than bash.

Also, the {} and {file} files remaining on my home are from when I manually ran "ranger --choosefile={}", so ignore that, the issue that files aren't selected remains.
I did check /tmp and there's a bunch of qutebrowser-fileselect files

> I don't have Monero set up at the moment, but I could do so if that's what you prefer.
Should be easy, please set one up.

**Comment by The-Compiler** [comment]
The problem is that you're using `urxvtc` rather than `urxvt`. That exits immediately, so qutebrowser will read the file back immediately.

(FWIW this is also a good example why it's good to be specific about changes rather than vaguely describing them :wink:)

I'll open a separate issue regarding Monero and will get back to you next week, as I'm busy giving a pytest training for the next couple of days.

**Comment by Andonome** [comment]
I've replicated this on urxvt-9.31_1, with 

```
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.7

CPython: 3.11.2
PyQt: 5.15.9
```

It's working fine with plain `urxvt` though, so not really an issue. Maybe there could just be a warning?
