### ISSUE TITLE
`:open` can't find previous history even though `:history` lists all

### ISSUE THREAD

**Issue by crides** [qutebrowser/qutebrowser#6111]
**Version info**:
qutebrowser v2.0.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
No, cuz there's no history

**Description**
Just updated to version 2 from version 1, and when I type in the prompt of `:open` my history before the update doesn't show up in the auto complete, however the ones after does. Using `:history` I can see all of my history. Quick/bookmarks don't get affected.

**How to reproduce**

**Comment by The-Compiler** [comment]
That's odd. What does this say?

```
sqlite3 ~/.local/share/qutebrowser/history.sqlite 'select count(*) from CompletionHistory; select count(*) from History; select * from CompletionMetaInfo'
```

**Comment by crides** [comment]
```
211
63973
excluded_patterns|
```

It seems like the last one is just "`excluded_patterns`" without any values.

**Comment by The-Compiler** [comment]
I'll follow up with how to fix this tomorrow (not on my laptop anymore). Could this by any chance be caused by the first start of qutebrowser v2.0 being interrupted?

**Comment by crides** [comment]
I'm not sure if it's caused by that, but on startup of version 2 it did crash. I don't know the reason for the crash, and following restarts are all fine.

**Comment by The-Compiler** [comment]
You can trigger the rebuild again by running `sqlite3 ~/.local/share/qutebrowser/history.sqlite 'pragma user_version = 0'` to fix this (maybe create a backup first just to be sure).

I'll also look into fixing this by triggering the rebuild again if it was interrupted.
