### ISSUE TITLE
hints.leave_on_load is True, in contrary to what the changelog stated

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#6115]
**Version info**:
qutebrowser v2.0.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
`hints.leave_on_load` is not `False` by default, as it was stated in the changelog for the 2.0 release.
![scr](https://i.imgur.com/ha8eHEN.png)

**Comment by The-Compiler** [comment]
Argh. Looks like I got confused and accidentally toggled the default for `input.insert_mode.leave_on_load` instead of `hints.leave_on_load`... :man_facepalming:
