### ISSUE TITLE
Get rid of browser.inspector.create

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6121]
The local imports in `browser.inspector.create` are problematic, e.g. because an old qutebrowser instance could import new files after an upgrade.

Instead, `AbstractTabPrivate` in `browsertab.py` should have an abstract `_init_inspector` method or so, which then is implemented in `WebKitTab` and `WebEngineTab`.

**Comment by jbenge1** [comment]
Assuming this is still open, I can take a whack at it
