### ISSUE TITLE
Support FIDO2 user verification

### ISSUE THREAD

**Issue by maximbaz** [qutebrowser/qutebrowser#6131]
Go to https://webauthn.io/

Put any username, click on "Advanced settings" and set "User verification" to "Required".

Now click "Register".

In Chromium, a popup shows up asking for PIN of YubiKey (I'm using YubiKey 5C Nano), after I enter the correct PIN and touch the device, I will see "Registration is successful".

In qutebrowser, it doesn't ask for PIN and therefore registration cannot be completed.

I don't know if it partially needs to be implemented in Qt WebEngine, but at the very least we need qutebrowser to show the dialog asking for a PIN.

**Comment by The-Compiler** [comment]
There's nothing qutebrowser can do here before there's an API from QtWebEngine. At the moment, even normal U2F seems to work for some people but not others, see #3043 and [[QTBUG-54720] FIDO U2F support - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-54720) - given that the latter is closed for Qt 5.15.1, you might want to report this as a feature request to QtWebEngine instead.

**Comment by maximbaz** [comment]
I will be happy to open a feature request for QtWebEngine, could you please help me understand how this is currently integrated with qutebrowser? FIDO2 / WebAuthn seems to work in general (for example on https://webauthn.io), and if I search in QtWebEngine it also seems to be supporting it (for example, here's a patch that [enabled it](https://codereview.qt-project.org/c/qt/qtwebengine/+/308273) that I found in the issue you linked). So I assumed that what is missing is only a support in qutebrowser for a dialog UI to actually ask for the PIN 🤔 Do we already use some APIs from QtWebEngine for U2F / FIDO2 / WebAuthn? I'm just trying to understand what exactly needs to be asked from them 🙂 

Yes I know that on some websites even regular U2F doesn't work, for various reasons, but in general it works, again for example on https://webauthn.io.

**Comment by maximbaz** [comment]
In fact I created this issue because I started investigating why U2F doesn't work on one particular website in qutebrowser, but works in Chromium, and this turned out to be one of the two reasons 🙂 The second one I didn't nail down precisely yet, therefore didn't report anywhere.

**Comment by The-Compiler** [comment]
There's currently no code for FIDO U2F in qutebrowser at all, and (as far as I know) no API in QtWebEngine for it. It's all handled internally by the underlying QtWebEngine/Chromium.

**Comment by maximbaz** [comment]
Thank you, this helped, it's good to know that there is no code in qutebrowser to deal with U2F / FIDO2.

For reference, it does seem like QtWebEngine supports most of the use-cases, at this point it's useful to investigate some specific websites where things don't work as expected (or work only in Chromium).

For example, I started looking into this because FIDO2 login doesn't work in mailcow, and this resulted in these two reports:

https://bugreports.qt.io/browse/QTBUG-90938
https://bugreports.qt.io/browse/QTBUG-90941

I also know that U2F login doesn't work in gitea, this is due to the fact that they use an older U2F library instead of WebAuthn API, the tracking issue is:

https://github.com/go-gitea/gitea/issues/6892

**Comment by The-Compiler** [comment]
Looks like someone started working on getting this into QtWebEngine: [Support FIDO2 user verification (I6367791e) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/481489)

**Comment by The-Compiler** [comment]
Good news, the change above has now landed and will be in Qt 6.6 (scheduled for September).

**Comment by therealr5** [comment]
I'm currently running qutebrowser `v3.1.0` on top of qtwebengine `6.6.1` but the pin entry dialog still doesn't appear :(
Is qutebrowser missing some support for it or is there anything else required from my side to get it to work?

**Comment by The-Compiler** [comment]
@therealr5 I was wrong above, the change above only landed in Qt 6.7. Likely qutebrowser will still need to actually implement the API for things to work, see #7743.

**Comment by baest** [comment]
Hi @The-Compiler Shouldn't this issue be opened again. AFAIK it still doesn't work that if the yubikey requires a pin-code, no pin-code entry dialog appears. I understand that qutebrowser need to implement some API, but is there a issue for tracking that?

Right now I'm sadly forced into using another browser since many corporate pages is behind yubikey auth.

**Comment by The-Compiler** [comment]
See the comment right above yours...

**Comment by baest** [comment]
I have seen that comment, but since that API hasn't been implemented yet wouldn't it make sense to have an issue to track that it was implemented?

**Comment by The-Compiler** [comment]
> Likely qutebrowser will still need to actually implement the API for things to work, see #7743.

...which is an open issue tracking what APIs are new in Qt 6.7 and not implemented in qutebrowser yet.
