### ISSUE TITLE
FAQ about content.javascript.can_access_clipboard?

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#6137]
Not really a feature request, but I've just discovered `set content.javascript.can_access_clipboard true` to make some web buttons work (like the one to copy a repo url to the clipboard or primary selection).

Should such a thing be mentioned in the FAQs?

If so, I can do a PR, but what is the technical name of those "buttons"?

**Comment by The-Compiler** [comment]
Sure, why not - it's certainly a bit surprising. Such an entry should also point out that you can set it for a specific domain, e.g. `:set -u github.com content.javascript.can_access_clipboard true`. I don't know of a proper name for those, I'd just call them "copy to clipboard buttons".
