### ISSUE TITLE
qutebrowser 14:11:12 CRITICAL: Could not find QtWebEngineProcess Abgebrochen

### ISSUE THREAD

**Issue by freddii** [qutebrowser/qutebrowser#6138]
**Version info**:
2.0.1-3 (from debian bullseye repo)

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Qutebrowser does not even start.

**How to reproduce**
i wrote in terminal "qutebrowser" and it did not start. I only got this error:
[freddii:~] $ qutebrowser
14:14:13 CRITICAL: Could not find QtWebEngineProcess
Abgebrochen

It would be sad if a non working qutebrowser would make it into bullseye.

**Comment by fiete201** [comment]
Hi freddii,

can you please show the output of `dpkg -l | grep qutebrowser`?

```
 fiete@yavin  ~  dpkg -l | grep qutebrowser
ii  qutebrowser                                   2.0.2-1                                all          Keyboard-driven, vim-like browser based on PyQt5
ii  qutebrowser-qtwebengine                       2.0.2-1                                all          QtWebEngine backend dependency package for qutebrowser
```

I'm curious if you got webengine installed.

Maybe you can also try with 2.0.2-1 (currently in unstable, will move to testing in some days)

Best regards
fiete

**Comment by freddii** [comment]
[freddii:~] $ dpkg -l | grep qutebrowser
ii  qutebrowser                                                 2.0.1-3                                            all          Keyboard-driven, vim-like browser based on PyQt5
ii  qutebrowser-qtwebengine                                     2.0.1-3                                            all          QtWebEngine backend dependency package for qutebrowser

**Comment by The-Compiler** [comment]
Do you have a `/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess` (part of the `libqt5webenginecore5` package)? What does `env | grep QT` say?

**Comment by freddii** [comment]
```
 [freddii:~] $ ls -l /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess
-rwxr-xr-x 1 root root 14408 11. Dez 09:32 /usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess
 [freddii:~] $ env | grep QT
QT_ACCESSIBILITY=1
QT_QPA_PLATFORMTHEME=gtk2
QT_IM_MODULE=ibus
```

**Comment by The-Compiler** [comment]
I have no idea what's going on there - could you check whether you see the same issue with another QtWebEngine-based browser such as Falkon?

**Comment by freddii** [comment]
falkon works.

**Comment by The-Compiler** [comment]
That's weird. Can you try the [testbrowser_webengine.py](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/testbrowser/testbrowser_webengine.py) script please?

**Comment by freddii** [comment]
⌁ [freddii:~/Desktop] $ python3 testbrowser_webengine.py 
Could not find QtWebEngineProcess
Abgebrochen

**Comment by The-Compiler** [comment]
This clearly isn't an issue with qutebrowser then. Given that Falkon works but this PyQt5 script doesn't, I'd recommend opening a bug against the `python3-pyqt5.qtwebengine` package (if you do, please link it here!).

**Comment by freddii** [comment]
installed it on a fresh debian testing.
working there.
seams to be a local problem with my system.

**Comment by The-Compiler** [comment]
Thanks for the clarification! You might also want to look at `python3 -c "import PyQt5.QtWebEngine; print(PyQt5.QtWebEngine.__file__)"` - perhaps you're actually running a PyQt5 installed via pip or something.

**Comment by freddii** [comment]
yes. maybe i destroyed something some time ago with a pip installation.
``
[freddii:~] $ python3 -c "import PyQt5.QtWebEngine; print(PyQt5.QtWebEngine.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/freddii/.local/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
```

**Comment by sethhan** [comment]
I also get; 
CRITICAL: Could not find QtWebEngineProcess
when staring qutebrowser, and this is because I have the ".local/lib/python3.9/" which I is added and needed by "argos-translate"
//nukpana
