### ISSUE TITLE
SVG favicon support

### ISSUE THREAD

**Issue by 1ace** [qutebrowser/qutebrowser#6142]
I'm not sure if SVG favicons are supposed to be working; this is either a bug report or a feature request ^^

**Comment by The-Compiler** [comment]
Works fine for me on http://dahlström.net/svg/favicon/favicon.html - what qutebrowser/Qt version are you on (see `:version`)? Can you reproduce with `--temp-basedir`?

**Comment by The-Compiler** [comment]
@1ace Any update on this?

**Comment by OliverLew** [comment]
Can confirm the test webpage failed for me (also with `--temp-basedir`). Here is the version info:
```
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.7.4
yaml: 5.3.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 20.3.4
Platform: Linux-5.10.15-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by arza-zara** [comment]
Works for me with an almost identical setup:
```
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.0
yaml: 5.3.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.7.570 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: X.Org, 3.0 Mesa 20.3.4
Platform: Linux-5.6.2-arch1-2-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-3zxzng3o/cache
config: /tmp/qutebrowser-basedir-3zxzng3o/config
data: /tmp/qutebrowser-basedir-3zxzng3o/data
runtime: /tmp/qutebrowser-basedir-3zxzng3o/runtime
system data: /usr/share/qutebrowser
```
Fails with Qt 5.14 and older.

**Comment by The-Compiler** [comment]
Works for me as well, with almost the same setup too:

```
qutebrowser v2.0.2
Git commit: 27488328f on master (2021-02-15 19:49:55 +0100)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.0
yaml: 5.3.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.7.570 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

Style: QStyleSheetStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 20.3.4
Platform: Linux-5.10.7-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

What exactly does happen for you, @OliverLew? Anything interesting in the `:devtools` console?

**Comment by OliverLew** [comment]
I don't know where to look. I could only notice a sadface icon (which is png) in the tab, there is nothing special *to me* in the devtools page.

**Comment by The-Compiler** [comment]
If you go to the "console" tab, is there any output there at all? If you go to the "network" tab, what requests do you see? Here are mine:

![image](https://user-images.githubusercontent.com/625793/108070689-17e7b100-7065-11eb-9949-aefc06dacaad.png)

![image](https://user-images.githubusercontent.com/625793/108070726-22a24600-7065-11eb-90af-4f87f319aa69.png)

**Comment by OliverLew** [comment]
The same.
I tested again in my VM, and the svg favicon is loading. So I don't know for now what is causing the problem in the host OS.

**Comment by The-Compiler** [comment]
If you [open the SVG file directly](http://xn--dahlstrm-t4a.net/svg/favicon/happyface.svg), does it get displayed?

Can you test if you can reproduce this in another QtWebEngine-based browser such as KDE Falkon (`falkon` in the repos)?

**Comment by OliverLew** [comment]
I had tried on my host machine already, the icon files do load and display correctly.

`falkon` shows svg in the favicon.

**Comment by The-Compiler** [comment]
All qutebrowser does is displaying [the icon it gets from QtWebEngine](https://doc.qt.io/qt-5.15/qwebengineview.html#icon-prop), everything else happens inside QtWebEngine/Chromium.

Interestingly, it seems to depend on the size of the tab bar somehow! With the default font size I get:

![image](https://user-images.githubusercontent.com/625793/108076665-f8a05200-706b-11eb-8966-3681919ddf23.png)

but when I bump up the size in `fonts.tabs.unselected` to 20pt, I get:

![image](https://user-images.githubusercontent.com/625793/108076745-0c4bb880-706c-11eb-8612-1e12144a1911.png)

I'm assuming you have something (slightly bigger font, HighDPI-scaling, ...) which causes this to happen?

When I do

```diff
diff --git i/qutebrowser/mainwindow/tabwidget.py w/qutebrowser/mainwindow/tabwidget.py
index 4041de2c9..4de0bba91 100644
--- i/qutebrowser/mainwindow/tabwidget.py
+++ w/qutebrowser/mainwindow/tabwidget.py
@@ -332,6 +332,7 @@ def update_tab_favicon(self, tab: QWidget) -> None:
         idx = self.indexOf(tab)
 
         icon = tab.icon() if tab.data.should_show_icon() else QIcon()
+        print(icon.availableSizes())
         self.setTabIcon(idx, icon)
 
         if config.val.tabs.tabs_are_windows:

```

I get

```
[PyQt5.QtCore.QSize(16, 16), PyQt5.QtCore.QSize(120, 119)]
```

with 120x119 being the dimensions of the PNG... so it looks like Qt prefers the PNG as soon as the tab bar is bigger than 16px...

**Comment by OliverLew** [comment]
That might be the cause.
I reproduced your steps to change the tab's font size in my VM, which works fine before.
And in my host machine, I have a larger dpi setting in my xresources: `Xft.dpi: 144`. Changing the dpi in my VM to 144 leads to the svg favicon not loading, and vise versa, changing the dpi in my host machine to 96 'fixed' it.
Maybe the issue author had similar settings that causes this.

**Comment by The-Compiler** [comment]
So, the SVG file indeed does specify `height="16"` and `width="16"`, and the [whatwg HTML spec](https://html.spec.whatwg.org/#rel-icon) doesn't say much about *how* an appropriate icon should be selected.

I think Qt's behavior here makes some sense (in general, not necessarily in this specific instance). Of course it'd be nice if Qt would use the scalable icon again when going to a size *bigger* than the PNG, but even Chromium fails at this, by apparently converting the SVG to a raster graphic and then (lossily) scaling that one up:

![image](https://user-images.githubusercontent.com/625793/108079169-cba16e80-706e-11eb-816e-81953f14df0f.png)

Either way - there's nothing qutebrowser can do about this, and as long as Chromium's support for it is also rather buggy, I'm a bit hesitant to report this to QtWebEngine - even more so since it's not really clear what the proper behavior really should be.

Thanks for all the testing, @OliverLew!
