### ISSUE TITLE
Cannot download PDFs from https://projecteuclid.org/

### ISSUE THREAD

**Issue by ticki** [qutebrowser/qutebrowser#6152]
**Version info**:
qutebrowser v2.0.0
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
If you attempt to download any paper on Project Euclid, you will find that instead of downloading
the PDF (as Firefox correctly does), it opens a bunch of XML files and not any PDFs.

**How to reproduce**
For example, try to download: https://projecteuclid.org/euclid.pja/1195522459

**Comment by The-Compiler** [comment]
See [[QTBUG-78114] [REG 5.13] PDF files are downloaded twice - can't download project euclid files - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-78114).

I actually wonder whether this upcoming change for QtWebEngine 5.15.3 will fix it, but I haven't tried yet: [Show PDF viewer in a guest view (Ib1591fbd) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/332797)
