### ISSUE TITLE
Follow Links by Search

### ISSUE THREAD

**Issue by benedikt-bartscher** [qutebrowser/qutebrowser#6153]
Is there any way to follow links by typing your search query?

My imagination of such a feature:
If there is only one match left, qutebrowser could automatically follow it. If there are multiple matches and you wanna end your search query there could be some shortcut or end character (for example /) to present the user with the usual follow mode but only with Links containing the search query.

**Comment by The-Compiler** [comment]
You can press enter to follow the link under the currently active search match. With `hints.mode = numbers`, you can also type a link's text to filter down hints.
