### ISSUE TITLE
WinDefender: Win32/Ymacco.AACB

### ISSUE THREAD

**Issue by dead-dreams** [qutebrowser/qutebrowser#6154]
**Version info**:
qutebrowser v2.0.2
Git commit: f11cdd0bf on HEAD (2021-02-04 10:19:33 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Bug happens well before the program is startable.

**Description**
Windows immediately flags qutebrowser as a severe trojan, and removes the main executable after a 10-15 second time window. I see a couple other situations where qutebrowser is marked as a false positive, and I'm here to add another to that list unfortunately. 

Windows Version: 10.0.19041 Build 19041
![falsepositive](https://user-images.githubusercontent.com/75540648/107707179-7c82c480-6c8f-11eb-9a33-0850d0fad429.png)

**How to reproduce**
Attempt to install or extract qutebrowser v2.0.2 onto a Windows 10 machine of the specified version.

**Comment by Thanood** [comment]
I've had the same problem. :smiley:

**Comment by The-Compiler** [comment]
See #6081 - if you want to help, please [submit a report](https://www.microsoft.com/en-us/wdsi/filesubmission) to Microsoft, as it's a lot of work to do this for all affected vendors...

**Comment by dead-dreams** [comment]
I have submitted the executable to Microsoft. I apologize for the unnecessary ticket, I did not see #6081, but thank you for the quick response. Hope these false positives can get worked out!

**Comment by The-Compiler** [comment]
Great, thank you!

**Comment by dead-dreams** [comment]
Final update from my end, Microsoft has removed the false detection for the v2.0.2 version of `qutebrowser.exe` in Windows Defender security intelligence version `1.331.1207.0`.
