### ISSUE TITLE
Much higher memory footprint after upgrading from v1.11.1 to v1.14.1 

### ISSUE THREAD

**Issue by livnev** [qutebrowser/qutebrowser#6158]
**Version info**:

qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

Apologies in advance for the vague report. After having upgraded from v1.11.1 to v1.14.1 I've noticed that qutebrower seems to be using a lot more memory for my typical workload of having 10-20 tabs open. I haven't been able to pin it down to specific tabs yet but since it seems that there were significant changes in this version I wanted to first ask if an increase in memory footprint was expected. It is often starting to swap noticeably with less than 20 tabs open on my laptop with 8GB of ram, which did not usually happen before. The `QtWebEngineProcess` processes are consuming most of the RAM.  

**How to reproduce**

Opening 10-20 tabs in 1 or 2 windows. From what I can tell the memory footprint seems to be variable and often goes down when closing some tabs. Happy to investigate more if this is unexpected.

**Comment by The-Compiler** [comment]
I assume you also upgraded Qt, not just qutebrowser? This is unlikely to be affected by any change in qutebrowser itself, the QtWebEngineProcesses are coming from the underlying QtWebEngine/Chromium.

**Comment by livnev** [comment]
> I assume you also upgraded Qt, not just qutebrowser? This is unlikely to be affected by any change in qutebrowser itself, the QtWebEngineProcesses are coming from the underlying QtWebEngine/Chromium.

Yes, I also upgraded from Qt 5.12.7 to 5.15.2.

**Comment by The-Compiler** [comment]
Yup, see e.g. https://github.com/qutebrowser/qutebrowser/issues/1476#issuecomment-732954976 - unfortunately I don't think there's much qutebrowser can do about it.

**Comment by livnev** [comment]
@The-Compiler Thanks for the link. I've updated the issue title for the sake of future readers.

**Comment by The-Compiler** [comment]
Thank you! As I mentioned in https://github.com/qutebrowser/qutebrowser/issues/1476#issuecomment-733019169, it'd be very interesting to know whether it's qtbase, QtWebEngine or PyQt to blame - so if that's something you'd want to experiment with, that'd likely be the first step towards (maybe...) finding the culprit.
