### ISSUE TITLE
Trojan detected by Windows Defender on Windows

### ISSUE THREAD

**Issue by yifan19** [qutebrowser/qutebrowser#6160]
**Version info**:
version 2.0.2

**Description**
Windows Defender:  Trojan:Win32/Ymacco.AACB 
when downloading the binary version for windows64

might just be it going crazy over nothing...
**How to reproduce**
install on a windows64 installer version from the release link on github

**Comment by yifan19** [comment]
oops duplicated, sorry im blind

**Comment by The-Compiler** [comment]
Yup, see #6081 - if you can [report this to Microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission) that'd help a lot, I'm a bit tired of doing that for every bigger release...
