### ISSUE TITLE
Mouse mode

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6169]
Hello, 
i was thinking about creating a fork with mouse mode implemented. Where you use hjkl to navigate a dot within the browser and use something like JK for right click and left click. Maybe some other keys to create larger jumps with the mouse.  There are many situations with menus where I find myself using "f" several times in a row and in these situations I feel like a mouse mode would be very useful. 

I dont think it should control the real mouse, instead I think its better that a simulated mouse is created within the browser

**Comment by The-Compiler** [comment]
FWIW there is [keynav](https://www.semicomplete.com/projects/keynav/) which does this (in a more efficient way) on a global level. If you prefer to move the mouse "normally" but with keys, I'm sure there are applications which can do this globally as well. I don't think it makes much sense to replicate that functionality inside qutebrowser.

**Comment by The-Compiler** [comment]
I added this to the extension ideas in #30 - I don't think this is something that should be in the core, given that suitable alternatives exist already.
