### ISSUE TITLE
Pdf download / pdfjs opens additional empty tab on certain pages

### ISSUE THREAD

**Issue by baldrianbandit** [qutebrowser/qutebrowser#6172]
5.10.14-arch1-1
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

Description:
With content.pdfjs disabled, downloading pdf files from certain sites opens an additional empty tab. With content.pdfs enabled, first an empty tab and then the tab containing pdfjs is opened.

Steps to reproduce:
1) qutebrowser --temp-basedir https://www.ti.com/product/LM2936
2) click on "LM2936 [...] datasheet"

Respectively:
1) qutebrowser --set content.pdfjs true --temp-basedir https://www.ti.com/product/LM2936
2) click on "LM2936 [...] datasheet"

**Comment by The-Compiler** [comment]
See #4588 and #1078

**Comment by dennis0324** [comment]
6.5.6-arch2-1
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.3, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.3 (compiled 6.5.2)

Description:
It has not been fixed for my case.

Steps to reproduce:
same as above
![image](https://github.com/qutebrowser/qutebrowser/assets/50710829/5f5bf9bf-0d9f-42f6-825f-8c437959a236)


Respectively:
same as above
![image](https://github.com/qutebrowser/qutebrowser/assets/50710829/0f0f7993-f128-4b0a-8da2-2816bd70374d)
