### ISSUE TITLE
Dark Background

### ISSUE THREAD

**Issue by Henry-Ta** [qutebrowser/qutebrowser#6181]
**Version info**:

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
Some sites display with a dark background . It happens with some specific websites.
**How to reproduce**

This happens randomly, for example : indeed

**Comment by The-Compiler** [comment]
Please be more specific, there's little I can do with almost no information. At the very least, fill out the missing information in the issue template, and ideally share a screenshot as well.

**Comment by Henry-Ta** [comment]
Hi, please find my image below. It happens with some specific websites. And it doesn't happenn with other browser like Chromium.
![Fri 19 Feb 2021 10:28:48 AM PST](https://user-images.githubusercontent.com/59848305/108546175-9cbd0f80-729d-11eb-8d96-ca4d56bc4ea5.jpg)

**Comment by The-Compiler** [comment]
What about your version information and the question regarding `--temp-basedir`?

**Comment by Henry-Ta** [comment]
Version: 2.0.2

Running with --temp-basedir doesn't show the issue.

**Comment by The-Compiler** [comment]
I'm guessing this is the `colors.webpage.bg` setting then? That's working as intended.
