### ISSUE TITLE
Consistent hints

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6182]
It would be great if the hints from "f" would be consistent over elements. For example if you use f, then go to some site and go back and use "f" again, the elements keep their letter combination that they had before. There are quite a few times when I misclick a hint, go back and the hint is different. Or when I want to click on several things on a page and the hints get shuffled every time.

This is just a suggestion though I understand that its probably very hard to implement and would probably be buggy and slow

**Comment by The-Compiler** [comment]
See #5298
