### ISSUE TITLE
open in new tab by default if current tab is pinned.

### ISSUE THREAD

**Issue by blueForestIcarus** [qutebrowser/qutebrowser#6184]
If the current tab is pinned, then using ':open' gives a message 'tab is pinned'
It would be useful to have an option to make 'open' default to opening new tab when the current tab is pinned, rather than throwing an error.

**Comment by The-Compiler** [comment]
I guess that makes sense. I'm not even sure if it needs to be an option, I'd be fine with making it the default.

**Comment by pspiagicw** [comment]
Can I try to work on it if anybody else is not.I was thinking I could start contributing from this issue.

**Comment by The-Compiler** [comment]
@pspiagicw Please go ahead! The relevant code is in `openurl` in `qutebrowser/browser/commands.py`.
