### ISSUE TITLE
categories for bookmarks and quickmarks

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6188]
It might be cool if one could create categories for ones bookmarks, like "work", "school", "programing" etc. You could use different colors for different categories, also you could just use etc "b work" to get a list of all quickmarks related to work. Maybe "CTRL+SHIFT+B" to create advanced quickmark

**Comment by The-Compiler** [comment]
See #882 / #3885 which adds tags for bookmarks.
