### ISSUE TITLE
Book page shows blank page

### ISSUE THREAD

**Issue by genomorro** [qutebrowser/qutebrowser#6190]
**Version info**:
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
I was looking for a book in the official repository of my university and when I tried view the book, qutebrowser didn't show anything, only a blank page. The page's source code says:

> We're sorry but the Reader doesn't work properly without JavaScript enabled. Please enable it to continue.

JavaScript is enabled but the page doesn't work. You can see this screenshot:

![image](https://user-images.githubusercontent.com/625793/108677763-6c1de580-74ea-11eb-8f27-6007dacb33bf.png)

I couldn't find other pages with the same issue, I don't know if the problem comes from the service but firefox is working with this page. I disabled the adblocker but the problem persist.

**How to reproduce**
The direct link is: https://unam-bibliotecasdigitales-com.pbidi.unam.mx:2443/read/9786076227701/index
1. Follow the direct link
2. Log in
3. Follow again the direct link

If you are looking reproduce this issue the page will ask for credentials. I can share it if it's necessary (email).

**Comment by The-Compiler** [comment]
JavaScript isn't the problem here. What you're seeing is just the [noscript tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) in the page's source code, i.e. the text which would be shown if there was no JavaScript support.

Could you take a look at `:devtools` please, especially the console? Are there any error messages there?

**Comment by genomorro** [comment]
Sure, I found these messages.

```
Expression
not available
﻿
app.js:15 TypeError: Cannot read property 'getVoices' of undefined
    at t.value (app.js:41)
    at new t (app.js:41)
    at a.init (app.js:41)
    at a.created (app.js:41)
    at ne (app.js:15)
    at Nn (app.js:15)
    at a.t._init (app.js:15)
    at new a (app.js:15)
    at sn (app.js:15)
    at init (app.js:15)
﻿```
I will read the JS file.

**Comment by The-Compiler** [comment]
I can see the same with https://reader.readonline.com.mx/index (mentioned in the source code you screenshotted and publicly accessible).

It looks like QtWebEngine disabled the Web Speech API - I've opened a report upstream to clarify: [[QTBUG-91285] Speech synthesis API missing - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-91285)
