### ISSUE TITLE
regex in web search

### ISSUE THREAD

**Issue by skrshe** [qutebrowser/qutebrowser#6192]
mirror vim's ability to use regex in search

I keep going to search for a match at the beginning of a line with `^` or fuzz a match with `.`

**Comment by The-Compiler** [comment]
This isn't implemented by the underlying Chromium, see [687552 - FEATURE add 'case sensitive' options to the find in page dialog - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=687552) (which also talks about regex search) and [225324 - Regular expression support for Find in page - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=225324).

It could be implemented if we implement our own custom searching in JavaScript, see #5652.

**Comment by skrshe** [comment]
@The-Compiler sorry for duplicate issues, I didnt search hard enough
