### ISSUE TITLE
Unraid does not display docker templates in qutebrowser (but does in other browsers)

### ISSUE THREAD

**Issue by Moosatronic** [qutebrowser/qutebrowser#6206]
**Version info**:
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
(running Arch Linux)

**Does the bug happen if you start with `--temp-basedir`?**:
not entirely sure how to test that

**Description**

Unraid is a linux based home-server OS that comes with Docker functionality. To make docker configuration simple the os uses a docker manager, Dockerman, which allows users to edit their containers from within the local Unraid configuration website. Moreover, when you install a new docker container from Unraid's community applications repository, dockerman will populate the container with a template file containing the necessary configuration fields that you can then edit within the browser itself. 

After switching to qutebrowser I noticed that for whatever reason, qutebrowser will not render the individualized settings for whatever reason. I disabled adblocking and the issue still persisted so it must be something else. I've included an image showing how the configuration is supposed to look, as opposed to how it looks like in chromium. 

**How to reproduce**

 to reproduce you need to create an unraid virtual machine, install the community plugin at  https://forums.unraid.net/topic/38582-plug-in-community-applications/ and see if when installing any dockers the configuration appears for you.

here's images of the configuation working in chromium (ver. 88.0.4324.182) and in qutebrowser with no configuration showing.
![chromiumdocker](https://user-images.githubusercontent.com/35278709/108928513-85fd1c80-75ff-11eb-8609-7d9fc141df56.png)
![docker problem](https://user-images.githubusercontent.com/35278709/108928515-8695b300-75ff-11eb-9dd4-359cef350d22.png)

**Comment by toofar** [comment]
1. are there any errors in the :devtools console?
2. how does it look in KDE Falkon?

**Comment by The-Compiler** [comment]
As for testing with `--temp-basedir`: Start `qutebrowser --temp-basedir` (to get a fresh instance without any state or configuration) and see if it happens there too.

**Comment by Moosatronic** [comment]
There is in fact an error, i've included a screenshot that shows the error and the code in the source 
 where the error was caught. 

![dockerissuequtebrowser](https://user-images.githubusercontent.com/35278709/109047459-23edf700-7693-11eb-89e4-c9c5495ccdff.png)

**Comment by Moosatronic** [comment]
also ironically using --temp-basedir results in two errors rather than just one. 


![tempbasedirerror](https://user-images.githubusercontent.com/35278709/109047851-96f76d80-7693-11eb-8832-70c9d830ffe6.png)

**Comment by Moosatronic** [comment]
let me know if there's additional info you require or if you would prefer base code/text as opposed to pictures, I just assume pictures make the errors easier to parse.

**Comment by The-Compiler** [comment]
I can reproduce by doing `"foo[bar".replaceAll("[", "<")` in the `:devtools` console - it works correctly with QtWebEngine 5.15.3 (not released yet) which is based on a Chromium version which supports it, but breaks with 5.15.2 (where we use our polyfill, see 28a694e17c9b41e9b5585926091f5b70fedf558c).

**Comment by The-Compiler** [comment]
I have a fix for this ready, but one last question out of curiosity: If you start with `--temp-basedir -s content.site_specific_quirks false`, does it break with a different error, or does it work?

**Comment by Moosatronic** [comment]
there are no errors and it works fine if I start qutebrowser with `--temp-basedir -s content.site_specific_quirks false`.

**Comment by The-Compiler** [comment]
Damn, okay. Thanks for testing! Our workaround for #6047 probably causes more issues than it solves then. Still waiting for a release after https://github.com/nextcloud/calendar/pull/2822 so it can be dropped again...

**Comment by The-Compiler** [comment]
If you need a workaround before the next release, you can drop this into `greasemonkey/` in qutebrowser's data directory (see `:version`):

```js

"use strict";

// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
function escapeRegExp(string) {
    return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Based on: https://vanillajstoolkit.com/polyfills/stringreplaceall/
/**
 * String.prototype.replaceAll() polyfill
 * https://gomakethings.com/how-to-replace-a-section-of-a-string-with-another-one-with-vanilla-js/
 * @author Chris Ferdinandi
 * @license MIT
 */
String.prototype.replaceAll = function(str, newStr) {
    // If a regex pattern
    if (Object.prototype.toString.call(str) === "[object RegExp]") {
        return this.replace(str, newStr);
    }

    // If a string
    return this.replace(new RegExp(escapeRegExp(str), "g"), newStr);
};
```

Note that you should remove it again as soon as you upgrade to QtWebEngine 5.15.3 or as soon as #6208 gets done, however.

**Comment by Moosatronic** [comment]
okay thanks for the fix! i'll be sure to watch for #6208 and 5.15.3.

**Comment by Moosatronic** [comment]
well the fix doesn't work for me. I put the code into a ".js" file in the greasemonkey folder of the data directory and reloaded the browser and even ran greasemonkey-reload and its done nothing. I guess i'll just have to wait for the fix then.

**Comment by The-Compiler** [comment]
Ah, sorry for not mentioning that - it will need to be named `.user.js`.

**Comment by Moosatronic** [comment]
i believe i called it .user.js and then tried .js and both didn't work for me but i'll check again just in case I made a mistake. So any script with the extension .user.js in the greasemonkey folder will start when starting qutebrowser then? Sorry for the support for the newbie.

**Comment by Moosatronic** [comment]
yeah still doesn't work unfortunately. I don't get it.

**Comment by The-Compiler** [comment]
Hm, odd. It worked for me when I tried earlier. If you start with `--debug --logfilter js,greasemonkey`, what does that say?

**Comment by Moosatronic** [comment]
![Screenshot_20210226_172934](https://user-images.githubusercontent.com/35278709/109369041-42e9b600-7858-11eb-8ef0-17398791f3f0.png)

im getting the impression that maybe i made a mistake in making the script but i dunno.
