### ISSUE TITLE
Qutebrowser crashes instantly upon attempting to log into any Google service

### ISSUE THREAD

**Issue by mattheusroxas** [qutebrowser/qutebrowser#6221]
**Version info**:
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
No

**Description**
If you assay to log into any site that has Google intergration (eg, YouTube, Google Docs) Qutebrowser commits self die.

I'm assuming because the bug has no effect when I run Qutebrowser with `--temp-basedir` this might be some kind of configuration error, yet I don't see anything in my configuration that would indicate this.

**How to reproduce**
Try to log in

**Applies to**
Every single website that utilizes a Google login

**Configuration file**
https://gitlab.com/mattheusroxas/mattifiles/-/blob/master/.config/qutebrowser/config.py

**Comment by The-Compiler** [comment]
If you go to the data directory listed in `:version` and rename `webengine/Service Worker` in there, does that change anything?

**Comment by mattheusroxas** [comment]
I don't have any file called `Service Worker` in `webengine/`.

**Comment by The-Compiler** [comment]
Huh, I'd expect it to be there, but okay. What happens if you move your `config.py` away?

**Comment by mattheusroxas** [comment]
It works just fine, it's very strange.

**Comment by The-Compiler** [comment]
Okay, so you'll need to find out what in your `config.py` is causing this. My bet would be:

```python
c.qt.args += [
    "enable-gpu-rasterization",
    "enable-features=WebRTCPipeWireCapturer",
    "enable-experimental-web-platform-features",
    "blink-settings=preferredColorScheme=1",
]
```

**Comment by mattheusroxas** [comment]
Yep that's it. Thanks for the help and I'm sorry if I wasted any of your time, originally most of my config was copied from this really old one, never thought to remove that part.

**Comment by mattheusroxas** [comment]
There is something weird that might be a bug, I already took away that block so it's not that, the Google login says `"This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."`
And won't let me log in.

**Comment by mattheusroxas** [comment]
Not very sure, but I wanted to put that there just in case.

**Comment by The-Compiler** [comment]
qutebrowser has a workaround for that, but you disabled it with `c.content.site_specific_quirks = False`.

**Comment by mattheusroxas** [comment]
Ah I see, I should probably read the docs properly soon. Qutebrower is amazing I really love how it's striving to be different while also providing quality. I wish you the best of luck with it and thanks for being so helpful and responsive! You're one of the best developers out there.

**Comment by The-Compiler** [comment]
I still think the original issue is a QtWebEngine bug though, so I reported it upstream: [[QTBUG-91490] [REG 5.14 -> 5.15] Segfault / "Check failed: ptr_." related to bluetooth with --enable-experimental-web-platform-features - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-91490)

Thanks for the nice words - much appreciated! :smiley:
