### ISSUE TITLE
Thumbnails/image previews in nextcloud photo page do not load in qutebrowser other browser OK

### ISSUE THREAD

**Issue by croyleje** [qutebrowser/qutebrowser#6227]
**Version info**:

qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.3

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.0
yaml: 5.3.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1j  16 Feb 2021

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 20.3.4
Platform: Linux-5.11.2-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When viewing photo previews / thumbnails page in nextcloud they do not load in qutebrowser if you vew the page in chromium or firefox the image previews load.  Did not know where else to report this according to nextcloud it is not on there end.  I would try to debug myself but I have no idea where to start.   (Please note there was a reported issue with this and nextcloud but that has been resolved and I have personally confirmed the page works fine on firefox and chromium.

**How to reproduce**

Log in to a nextcloud page and click on photos tab.  If you do not have access to a nextcloud server let me know I am happy to give you access to my personally hosted server and my page for testing.  I can also get logs from the server or run commands on the server if need be let me know.

**Comment by The-Compiler** [comment]
Will take a closer look tomorrow, but do you have a link to the Nextcloud issue? Also, anything interesting in the `:devtools` console?

**Comment by croyleje** [comment]
Hello I have checked the devtools console nothing that appears useful to me but while doing so I did figure something out if you zoom in to 125% or more and then reload the page they do load up. My personal nextcloud instance is located at https://www.nxtcld.info/ (https://link.getmailspring.com/link/744011CE-19B4-4DA2-AA1E-BE4D941AB0E6@getmailspring.com/0?redirect=https%3A%2F%2Fwww.nxtcld.info%2F&recipient=cmVwbHkrQU41NkFERDNURFE1WVFUR1E3RlRNWEY2SktVR0pFVkJOSEhEQloyVlA0QHJlcGx5LmdpdGh1Yi5jb20%3D) and the photos page is loacted at https://nxtcld.info/apps/photos/ (https://link.getmailspring.com/link/744011CE-19B4-4DA2-AA1E-BE4D941AB0E6@getmailspring.com/1?redirect=https%3A%2F%2Fnxtcld.info%2Fapps%2Fphotos%2F&recipient=cmVwbHkrQU41NkFERDNURFE1WVFUR1E3RlRNWEY2SktVR0pFVkJOSEhEQloyVlA0QHJlcGx5LmdpdGh1Yi5jb20%3D) I have also setup a default account and login for you so you can login the credentials are below. (In case your concerned this is just a default account with some stock photos there is no personal information accessible from this account)

USERNAME: qute
PASSWORD: qutebrowser

If you need any logs or anything from the server let me know.
Thank you,
Jason Croyle

PS: If you don't mind when your finished please let me know so I can delete this account from the server.

**Comment by croyleje** [comment]
I checked the devtools and there doesn't look like there is anything interesting there I did notice while doing this if you zoom into 125% or more then reload the page the thumbnails do load.  I have created a login and password for you I attempted to send it here but was unaware the credentials would be viewable to everyone if you want to contact be directly I will send you the login, password and url just let me know what I can do to help.

**Comment by The-Compiler** [comment]
No issues here, with Nextcloud 20.0.8:

![image](https://user-images.githubusercontent.com/625793/109777223-c3ffcf00-7c03-11eb-8fe2-66e95e822c79.png)


I assume we're talking about the same thing? Can you show a screenshot how things looks for you?

Maybe it's specific to your Nextcloud instance somehow, in which case it'd indeed help to get access to yours. You can reach me at mail@qutebrowser.org - also, note that email notifications were sent out for your previous post, so if those credentials are still valid, you might want to change them ASAP.

**Comment by croyleje** [comment]
Hello sorry took so long to get back to you Ill dig into this a little more over weekend but the more I look it appears it has something to do with there responsive web page anything above 125% zoom they load fine below that you just get a spinning loading icon sorry to bother you.

**Comment by croyleje** [comment]
You can close this issue and sorry to have wasted your time I have tried multiple ways to try and figure out a way to repeatedly reproduce this but just can't make my other laptop do it.  This only happens on my desktop and only with qutebrowser set to 100% zoom I have figured out a work around by simply increasing the zoom to 125% it all works .  If there is anyway for me to supply you with logs or anything let me know I will do what I can but from all logs I have checked I see nothing of any use.

**Comment by The-Compiler** [comment]
Looks like the errors are unrelated: https://github.com/nextcloud/photos/issues/224
The issue you're seeing seems a lot like this one: https://github.com/nextcloud/photos/pull/686

Closing this as it indeed doesn't seem like a qutebrowser issue - no worries though!
