### ISSUE TITLE
Sort history by times searched

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6237]
It would be nice to have (at least an option) to give historic suggestions based on how many times one have visited a site instead of simply which one was last visited. Often when one searches for say github, a stock exchange or a social media account, you want to go to the same page every time. However if lets say I visit qutebrowser on github 95% of the time and then visit another project once, I still feel like qutebrowser should be on top of the suggestions. Either have an optional to search by number of historic searches only or, preferably, have a combinatoin of the two, so the algorithm takes both amount of searches and time relevance into account when ranking suggestions

**Comment by The-Compiler** [comment]
See #601 and #5481.
