### ISSUE TITLE
typing.get_type_hints and "if TYPE_CHECKING:" imports

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6246]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/config/configfiles.py", line 889, in read_config_py
    exec(code, module.__dict__)
  File "/home/user/.config/qutebrowser/jmatrix/jmatrix/integrations/qutebrowser.py", line 82, in <module>
    def jmatrix_edit_config(self: 'configcommands.ConfigCommands', no_source: bool = False) -> None:
  File "/usr/lib/python3.9/site-packages/qutebrowser/api/cmdutils.py", line 153, in __call__
    cmd = command.Command(
  File "/usr/lib/python3.9/site-packages/qutebrowser/commands/command.py", line 129, in __init__
    self._type_hints = typing.get_type_hints(handler)
  File "/usr/lib/python3.9/typing.py", line 1449, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/usr/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'configcommands' is not defined
```

since [jmatrix](https://gitlab.com/jgkamat/jmatrix/-/blob/master/jmatrix/integrations/qutebrowser.py) does:

```python
MYPY = False
if MYPY:
	from qutebrowser.config import configcommands
```

and

```python
@cmdutils.register(instance='config-commands')
def jmatrix_edit_config(self: 'configcommands.ConfigCommands', no_source: bool = False) -> None:
```

which is an ugly hack, but a string annotation with an import like that could also occur elsewhere...

Will need to check if this is something qutebrowser can fix in a sensible way... It could of course ignore `self` types entirely.

Probably happens since 41dc2913097a6e028237289c6ac8607668156c7d.

Minimal reproducer of the same issue:

```python
import typing

if typing.TYPE_CHECKING:
    import collections

def fun(a: 'collections.defaultdict'):
    pass

print(typing.get_type_hints(fun))
```

**Comment by Keyhenge** [comment]
I was able to temporarily fix it by adding `self: str = 'configcommands.ConfigCommands'`, though I'm not knowledgable enough about python to know the broader implications of that/whether that would continue to work on 3.10.

**Comment by jgkamat** [comment]
Florian Bruhin writes:

> Alternatively, jmatrix could drop the string annotation for `self` entirely, 
> or switch it to a non-string annotation (if possible, but I guess it leads 
> to circular imports?). @jgkamat is this something you'd be willing to do?

Sure, I've dropped that annotation. The annotation was a string because of 
circular imports, and was needed because I was using strict types. However, it 
seems like mypy does not support hard-defining types like it did before 
(solving the magic appearance of 'c' and 'config') anyway, so I just removed 
the annotation for now. That said, I don't understand why any annotations 
would cause a qutebrowser crash.

That said, I won't be able to see if it works on that version anyway, as newer 
versions of qutebrowser don't launch at all on my machine anymore.

**Comment by The-Compiler** [comment]
> so I just removed the annotation for now.

Thanks! I'm closing this then, as I don't think there's anything qutebrowser can do to fix this (at least not without breaking Python 3.10 support again).

> That said, I don't understand why any annotations would cause a qutebrowser crash.

Because qutebrowser inspects type annotations to convert command arguments (e.g. if you annotate something as `int`, it will take care of validating that the user has passed an int and actually pass a converted int to the command handler). It has done so long before mypy was a thing (a811f8cb07d87282e02a3f4777149a66bf72f22b in 2014. Originally it also supported things like `horizontal: {'flag': 'x'} = False` ) and later adjusted its usage (via the `@cmdutils.argument` decorator) so that type annotations are typing-compatible, but they are still used by qutebrowser.

In your case, however, evaluating the type at runtime causes a `NameError` because of the conditional import - in this special case we could ignore it (as `self` is being annotated), but in other cases we'd likely need the real value anyways (as qutebrowser passes the argument to the command handler), so in the general case, there's nothing we can do about this.
