### ISSUE TITLE
Persistent localStorage support

### ISSUE THREAD

**Issue by nemya9066** [qutebrowser/qutebrowser#6247]
**Version info**:
qutebrowser v2.0.2
Git commit:
Backend: QtWebEngine (Chromium 87.0.4280.144)
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.3

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: no
yaml: 5.3.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1j  16 Feb 2021

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
localStorage is supported in qutebrowser but it's not persistent meaning everytime the browser is closed the storage is cleared. I'm aware of the content.local_storage and content.persistent_storage options and I've set both to True in my config.py.

**How to reproduce**
Create a simple html page and add this script to it:
`let name = localStorage.getItem('name')
if(name == null){
	console.log("VALUE WAS NOT SAVED")
	localStorage.setItem('name', 'nemya')
	name = localStorage.getItem('name')
}
console.log('the name is ',name')
`
the "VALUE WAS NOT SAVED" log will run the first time you start the page and everytime the browser is restarted.
If you run the page in firefox or chromium the storage is persistent and the log only show the very first time.

**Comment by The-Compiler** [comment]
Your example is full of syntax errors, and the storage works as expected with the [MDN example](https://mdn.github.io/dom-examples/web-storage/). Can you please provide a full, working example?

**Comment by nemya9066** [comment]
Well can't quite remember what I was doing that day for having problem with this but yeah everything work as expected.
I don't work with javascript at my job I just wanted to use the Api to create a greasemonkey script to remember any change I do to a video playbackRate and set any new video to that speed like what an addon I used in firefox did for me. 
Sorry to bother you and sorry for not putting semi colons :)
