### ISSUE TITLE
Can't close devtools with cross top

### ISSUE THREAD

**Issue by Geordinateur** [qutebrowser/qutebrowser#6266]
Hi, when i want to close my devtools with a cross, im going to "INSERT MODE".

**Comment by The-Compiler** [comment]
That was easy to fix :slightly_smiling_face: 

FWIW you can already use `wi` (`:devtools`) to toggle the devtools.

**Comment by Geordinateur** [comment]
Yes i used this option, but i use my mouse sometimes and now its great.
Thank you very much for your works

**Comment by Geordinateur** [comment]
It works but I will always "INSERT MODE"
