### ISSUE TITLE
Apostrophes are escaped in hint widgets

### ISSUE THREAD

**Issue by nichobi** [qutebrowser/qutebrowser#6267]
**Version info**:

qutebrowser v2.0.2
Git commit: 22a3fd479 on master (2021-03-11 08:35:59 +0100)
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
In the initial hint key widgets, apostrophes are escaped.
![image](https://user-images.githubusercontent.com/23172481/110925822-f1472e00-8323-11eb-98e6-b0b871d48e6a.png)
Weirdly, this goes away after the first key has been pressed, upon which it displays normally.
![image](https://user-images.githubusercontent.com/23172481/110925870-fefcb380-8323-11eb-8a7c-04ffa7c8f6ba.png)

**How to reproduce**

`:set hints.chars "asdfghjkl'"`
Enter hint mode on site with more than a few links, [duckduckgo](https://start.duckduckgo.com/) works with the menu open.

**Comment by The-Compiler** [comment]
That was easy to fix :slightly_smiling_face:

**Comment by nichobi** [comment]
Wow, that was quick! Thank you!
