### ISSUE TITLE
--config-py should not require config.load_autoconfig

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6272]
It's often used for testing things, so I don't think it makes sense to warn about a missing `config.load_autoconfig` there.

@Jan-PieterBaert @xaverdh What do you think? If you agree, is this something you'd like to work on?

**Comment by Jan-PieterBaert** [comment]
I think it might be useful to have an option like `--dont-warm-autoconfig` and then `--config-py` automatically enables that option

**Comment by The-Compiler** [comment]
Not sure if such an option really is needed/helpful - how/when would you use it?

**Comment by Jan-PieterBaert** [comment]
if you can't or don't want to edit the config.py file but you don't want to get the warning, might be a very rare case though

**Comment by The-Compiler** [comment]
If you use a `config.py` in `~/.config/qutebrowser`, I think it's fine to assume you can (and want) to edit it, as you created it in the first place. If you use a `config.py` in another location, you're going to so with `--config-py` anyways. Thus I'd prefer just disabling the warning when that flag is given.

**Comment by Jan-PieterBaert** [comment]
Sounds reasonable enough to me
