### ISSUE TITLE
ttf-google-fonts needed for proper rendering of some fonts on some websites

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#6275]
**Version info**:

qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Not sure whether this is a bug or not. Just an observation I want to report.

On my system (Arch Linux), I need the ttf-google-fonts package installed in order to render some of the fonts properly in several websites.

Without it, the fonts aren't horrible, but they are different than they are on, for instance, Chrome. In short, Chrome does not require ttf-google-fonts installed, but qutebrowser does for the proper rendering of some of the fonts on some web pages.

Because nothing is horrendous, I would have probably never noticed if I hadn't had the ttf-google-fonts package installed for years and just decided to uninstall it. The change is then obvious as many pages now look weirdly unfamiliar.

Even if not horrendous, it is clearly less neat and I will re-install the google fonts on my system, despite their large size, to return to nicer looking pages on those sites.

**How to reproduce**

Example of page affected: https://aur.archlinux.org/packages/?O=0&K=qutebrowser

The font that looks different is the font used in the "Search Criteria" box. Other fonts on the page look normal.

**Comment by prosoitos** [comment]
Note that it is very possible that it is something that I didn't set right in my fontconfig or similar... so I am far from sure whether this will be reproducible...

**Comment by The-Compiler** [comment]
I don't have `ttf-google-fonts` installed (though that package doesn't exist at all, do you mean `ttf-google-fonts-git`?) and the page looks fine for me:

![image](https://user-images.githubusercontent.com/625793/111172046-c66c0c80-85a5-11eb-9a90-506523e7274f.png)

**Comment by prosoitos** [comment]
Yes, I meant `ttf-google-fonts-git`. OK. Thanks. As I feared, I guess it is something in my fontconfig I guess 😑 

I will try to explore that. I guess you could close this if it is not reproducible.

**Comment by The-Compiler** [comment]
Closing this then - in any case, the rendering entirely comes from the underlying QtWebEngine/Chromium, other than passing the `fonts.web.*` settings to QtWebEngine there's no involvement from qutebrowser there.

If you find out more, let me know, though!
