### ISSUE TITLE
Missing hints on some clickable elements (menu expansion) on some websites

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#6278]
**Version info**:
qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Hints do not appear on some clickable elements of some websites, requiring a mouse to use them. Note that those elements are not weird marginal ones but key ones necessary to use the sites. Those elements are menu expansion and probably of a different nature than regular hyperlinks, hence why they aren't detected as clickable.

**How to reproduce**
Example website: https://docs.julialang.org/en/v1/

Hints are not showing on "Manual" and all other sections below, making it necessary to use the mouse to navigate that site.

**Comment by Soundtoxin** [comment]
I have a similar issue of clickable stuff not getting hinted in the Pleroma UI. I hope it's similar enough to post here.

Two different instances showing the same post to show it's not just a single website.
https://weeaboo.space/notice/A59YJbkDsMjSCVkpBA
https://kawen.space/notice/A59YJsYrgJw0YDlqL2

The reply, repeat, favorite, add reaction, and menu buttons below the post don't get hinted.

**Comment by The-Compiler** [comment]
I added those to #178. Note you can customize the `hints.selectors` setting (also for a certain page) to include those manually. For the Julia docs, `c.hints.selectors['all'].append('label.tocitem')` in `config.py` seems to work. For Pleroma, `c.hints.selectors['all'].append('i.button-icon')` gives them hints, but those aren't actually clickable.

**Comment by prosoitos** [comment]
Great. Thanks! and sorry I missed the already opened issue. I did look, but not hard enough I guess 😣

**Comment by Soundtoxin** [comment]
Fixed the rest of the Pleroma buttons mentioned at https://github.com/qutebrowser/qutebrowser/issues/178#issuecomment-799611256 with `c.hints.selectors['all'] += ['i.button-icon','i.btn-default','i.new-icon','i.icon-smile','i.icon-mail-alt','i.icon-lock','i.icon-lock-open-alt','i.icon-globe']
` 
(and all appear to be clickable when you're actually logged in, FYI)
![2021-03-15-135012_grim](https://user-images.githubusercontent.com/3146494/111205662-77b67680-8595-11eb-9203-4646d47b3202.png)
