### ISSUE TITLE
Smooth scroll not working when scrolling by a custom amount on macOS?

### ISSUE THREAD

**Issue by Gira-X** [qutebrowser/qutebrowser#6281]
**Version info**:
https://paste.the-compiler.org/view/4b04fb53

**Does the bug happen if you start with `--temp-basedir`?**:
No, because smooth scrolling is disabled.

**Description**

In those cases  smooth scroll works:

- hitting Space (scrolls down a page)
- `fake-key <alt-down>` (scrolls down a page) and `fake-key <alt-up>` (scrolls up a page)
- `fake-key <Home>` and `fake-key <End>` (for bottom and top) work, same as `scroll top` and `scroll bottom`

---

Personally I highly dislike that those keys scroll a full page, so I wanted to implement a way to scroll by half a page.

But no matter which commands I throw at qutebrowser, it just scrolls without the smooth scroll. I tried:

- `scroll-page 0 0.6`
- Repeating `scroll` but that did not work at all (see https://github.com/qutebrowser/qutebrowser/issues/6280)
- `scroll-px 0 300`

And the other scroll commands (like `scroll-to-perc`) which all also don't have the smooth scroll. The commands work, but without smooth scroll.

**Comment by Gira-X** [comment]
I also noticed that in Browsers like Firefox, hitting Down or Up immediately smooth scrolls.

But hitting Down or Up a single time in qutebrowser has no smooth scroll. Same when invoking `scroll up` or `scroll down`.

There seems to be a smooth scroll when Up or Down is held, but compared to Firefox it still feels rather clunky because there is a sudden stop initially plus the scroll performance looks really bad for me. Nothing compared to the butter-smooth Firefox.

Is there a way to improve the smooth scrolling here as well?

**Comment by andrewcarlotti** [comment]
> Personally I highly dislike that those keys scroll a full page, so I wanted to implement a way to scroll by half a page.
`Ctrl+D` and `Ctrl+U` (or the Mac equivalents) should already do this.

**Comment by Gira-X** [comment]
> Ctrl+D and Ctrl+U (or the Mac equivalents) should already do this, but they don't seem to use smooth scrolling.

That indeed works for scrolling a half page, thanks! But they also don't have smooth scrolling apparently :(

I just really like the smooth scrolling of the major browsers, like Firefox, and would love to have this in qutebrowser as well.

I'll probably make a video later how the scroll behaves for me.

---

By the way, I also tried to get smooth scrolling via [Hammerspoon](https://www.hammerspoon.org/) like this, but it also does not work: 

```lua
hs.eventtap.scrollWheel({0, 36}, {}, "line")
```

**Comment by The-Compiler** [comment]
I suspect you're seeing various different issues here. In your video, how exactly are you scrolling?

**Comment by Gira-X** [comment]
In the left side in Firefox via Vimium via those keys:

```
map c scrollUp
map t scrollDown
```

On the right in qutebrowser I did another test with `--temp-basedir` and enabled smooth scroll. Scrolling via `j` and `k`then behaves the exact same as shown in the video above where I am using `scroll up` and `scroll down`.

**Comment by The-Compiler** [comment]
Currently the smooth scrolling behavior (i.e. when smooth scrolling is enabled and when it is not) is entirely coming from the underlying QtWebEngine/Chromium - I suspect #3691 (which uses JS to scroll instead of Qt's API) will fix this as well, so I don't think there's any value in reporting this upstream. Merging this part into #2889.

As for scrolling by holding a key down, see #4768.

**Comment by Gira-X** [comment]
Your last comment gave me the idea to just bind my scroll keys to `jseval` and it actually works out quite well!

Now it would be even more amazing when one could customize the duration of the `scrollBy` calls, but this is already a huge improvement for me because I am now able to smooth scroll with any custom amount :)

```
config.bind("c", "jseval -q window.scrollBy({top: -60, left: 0, behavior: 'smooth'});")
config.bind("t", "jseval -q window.scrollBy({top: 60, left: 0, behavior: 'smooth'});")
config.bind("w", "jseval -q window.scrollBy({top: 300, left: 0, behavior: 'smooth'});")
config.bind("v", "jseval -q window.scrollBy({top: -300, left: 0, behavior: 'smooth'});")
```
