### ISSUE TITLE
Jupyter notebook is opening with blank screen in qutebrowser

### ISSUE THREAD

**Issue by logicalbhanu** [qutebrowser/qutebrowser#6285]
**Version info**:

qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8

CPython: 3.8.5
PyQt: 5.14.1

sip: 4.19.21
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: Qt5CTProxyStyle
Platform: Linux-5.4.0-66-generic-x86_64-with-glibc2.29, 64bit
Linux distribution: Linux Mint 20.1 (linuxmint)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/bhanu/.cache/qutebrowser
config: /home/bhanu/.config/qutebrowser
data: /home/bhanu/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:16
**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
I am unable to use the jupyter(since from the time I have installed qutebrowser) notebook in qutebrowser, it gets open with a white screen only.
my jupyter notebook is working fine in other browsers.
below is the terminal output that I am getting after starting jupyter, it is the same as with other browsers.
(Applied_AI) bhanu@bhanu-laptop:~/repositories/Applied_AI$ jupyter lab
[I 2021-03-15 16:03:57.163 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-03-15 16:03:59.329 ServerApp] nbclassic | extension was successfully linked.
[I 2021-03-15 16:03:59.597 LabApp] JupyterLab extension loaded from /home/bhanu/.local/share/virtualenvs/Applied_AI-UzvVV4vu/lib/python3.7/site-packages/jupyterlab
[I 2021-03-15 16:03:59.598 LabApp] JupyterLab application directory is /home/bhanu/.local/share/virtualenvs/Applied_AI-UzvVV4vu/share/jupyter/lab
[I 2021-03-15 16:03:59.633 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-03-15 16:03:59.696 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-03-15 16:03:59.696 ServerApp] Serving notebooks from local directory: /home/bhanu/repositories/Applied_AI
[I 2021-03-15 16:03:59.697 ServerApp] Jupyter Server 1.1.3 is running at:
[I 2021-03-15 16:03:59.697 ServerApp] http://localhost:8888/lab?token=725637a335c36a82be55328510f242ccbb653b84ea55bf30
[I 2021-03-15 16:03:59.697 ServerApp]  or http://127.0.0.1:8888/lab?token=725637a335c36a82be55328510f242ccbb653b84ea55bf30
[I 2021-03-15 16:03:59.697 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-03-15 16:03:59.775 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/bhanu/.local/share/jupyter/runtime/jpserver-11193-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=725637a335c36a82be55328510f242ccbb653b84ea55bf30
     or http://127.0.0.1:8888/lab?token=725637a335c36a82be55328510f242ccbb653b84ea55bf30
16:04:00 INFO: Run :adblock-update to get adblock lists.

**How to reproduce**
just by opening the jupyter notebook with qutebrowser.

**Comment by The-Compiler** [comment]
No issues here. Note however that qutebrowser v1.10.1 is over a year old.

Can you please try with `--temp-basedir`?

**Comment by logicalbhanu** [comment]
> No issues here. Note however that qutebrowser v1.10.1 is over a year old.
> 
> Can you please try with `--temp-basedir`?

updating the qutebrowser solves my problem, thanks.
