### ISSUE TITLE
Screen Sharing with Google Meet Does not Work

### ISSUE THREAD

**Issue by RohithRajesh** [qutebrowser/qutebrowser#6286]
Hi!
I really like the keyboard driven and minimalistic nature of qutebrowser. However, screen sharing with google meet simply does not work on the browser. I checked online and don't think there is a solution yet. Will be very helpful if it can be patched.

**Comment by The-Compiler** [comment]
See [[QTBUG-85731] Screen sharing does not work on Google Meet - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-85731)
