### ISSUE TITLE
Is there a way to persist the zoom for each URL individually?

### ISSUE THREAD

**Issue by Gira-X** [qutebrowser/qutebrowser#6299]
Firefox has this implemented and I would love to also see this in qutebrowser.

In my config I am using: `c.zoom.default = 133` which is great for most pages, although I have to adjust it in some pages. But the next time I browse to the same URL, my custom zoom is lost.

Not sure if one can already script this somehow into qutebrowser that another command is invoked after `zoom-in` or `zoom-out` to persist the current zoom level on the file system and then read from it when one browses to the same URL initially.

**Comment by The-Compiler** [comment]
Not yet - see #2869, #3636 and #3782.
