### ISSUE TITLE
Missing force_rebuild key in database

### ISSUE THREAD

**Issue by i-am-very-smart** [qutebrowser/qutebrowser#6302]
**Version info**:
qutebrowser v2.1.0
Git commit:
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.4

sip: 5.4.0
colorama: no
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.3.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.35.1
QtNetwork SSL: OpenSSL 1.1.1j  16 Feb 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 20.3.4
Platform: Linux-5.11.6-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/me/.cache/qutebrowser
config: /home/me/.config/qutebrowser
data: /home/me/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Does the bug happen if you start with `--temp-basedir`?**: No.

**Description**
starting qutebrowser gives the error message:
```
> qutebrowser
17:57:38 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.1.0', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 218, in main
    return app.run(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 129, in run
    init(args=args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 158, in init
    _init_modules(args=args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 487, in _init_modules
    history.init(objects.qapp)
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/history.py", line 465, in init
    web_history = WebHistory(progress=progress, parent=parent)
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/history.py", line 167, in __init__
    rebuild_completion = self.metainfo['force_rebuild']
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/history.py", line 118, in __getitem__
    return query.run(key=key).value()
  File "/usr/lib/python3.9/site-packages/qutebrowser/misc/sql.py", line 314, in value
    raise BugError("No result for single-result query")
qutebrowser.misc.sql.BugError: No result for single-result query
17:57:38 ERROR: Error while getting history: 'command-history'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/misc/crashsignal.py", line 214, in _get_exception_info
    cmd_history = objreg.get('command-history')[-5:]
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/objreg.py", line 247, in get
    return reg[name]
  File "/usr/lib/python3.9/collections/__init__.py", line 1058, in __getitem__
    raise KeyError(key)
KeyError: 'command-history'
Xlib: sequence lost (0x101c2 > 0x1c4) in reply type 0x0!
Xlib: sequence lost (0x101c9 > 0x1cb) in reply type 0x0!
Xlib: sequence lost (0x101d0 > 0x1d2) in reply type 0x0!
Xlib: sequence lost (0x101fe > 0x200) in reply type 0x0!
Xlib: sequence lost (0x10205 > 0x207) in reply type 0x0!
Xlib: sequence lost (0x1020c > 0x20e) in reply type 0x0!
```
this is for the qutebrowser on arch repo
i have try the development package qutebrowser-git on AUR already and same issue
i have also try to remove qutebrowser and install again

**How to reproduce** just start qutebrowser with command line

**Comment by The-Compiler** [comment]
What does this say?

```
sqlite3 ~/.local/share/qutebrowser/history.sqlite 'PRAGMA user_version; select * from CompletionMetaInfo'
```

I've also seen a related [crash report](https://crashes.qutebrowser.org/view/84e3d915) yesterday (not publicly accessible) - given that the username was `me` there too, I'm guessing that was you as well?

**Comment by i-am-very-smart** [comment]
```
> sqlite3 ~/.local/share/qutebrowser/history.sqlite 'PRAGMA user_version; select * from CompletionMetaInfo'
4
excluded_patterns|
```
i think the crash report yesterday is me

**Comment by The-Compiler** [comment]
Relevant change: 2b47bd01dbc15a02911989a190e2ef956aeedf27

There, the `force_rebuild` key was (re-)added and the version was bumped to 4. That change should have caused a change in your database adding the `force_rebuild` key, but for some reason the version is set to 4, without that key being present.

A couple of questions:

- Did you ever change the database manually in any way?
- Did you recently have a crash while starting qutebrowser (especially after an upgrade) or had to kill it?
- Did you recently downgrade to an older version, or otherwise switch back/forth between different versions?

**Comment by i-am-very-smart** [comment]
- i no try change database manually
- i think so. no remember clearly
- No. i just keep update from arch repo. i only try the AUR qutebrowser-git after i get this crash

**Comment by The-Compiler** [comment]
I'd recommend the following:

- Make sure qutebrowser is closed
- Take a backup of `~/.local/share/qutebrowser/history.sqlite`
- Run `sqlite3 ~/.local/share/qutebrowser/history.sqlite 'PRAGMA user_version=0'`
- Open qutebrowser again, it should rebuild the history database which will fix this

I'll look into making qutebrowser recover from such situations though.

**Comment by i-am-very-smart** [comment]
it work now
should i close issue?

**Comment by The-Compiler** [comment]
Glad to hear! Please leave it open for now - qutebrowser should try to recover from this automatically.
