### ISSUE TITLE
xdotool work with insert mode but not normal mode.

### ISSUE THREAD

**Issue by nemya9066** [qutebrowser/qutebrowser#6304]
**Version info**:
qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: no
yaml: 5.4.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.35.2
QtNetwork SSL: OpenSSL 1.1.1j  16 Feb 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 20.3.4
Platform: Linux-5.11.6-137-tkg-pds-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/nemya/.cache/qutebrowser
config: /home/nemya/.config/qutebrowser
data: /home/nemya/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/nemya/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:21

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I wan't to use xdotool to automatically refresh qutebrowser whenever I save an html document in vim by sending the 'r' key.
If I'm in insert mode and send a key to qutebrowser with xdotool qutebrowser receive the key correctly and whatever I send is added to the input but If Im not in insert mode nothing happen.
I wanna note that I used xdotool from another terminal (qutebrowser not in focus).

**How to reproduce**
Go to google.com and select the input tag, from another terminal execute this command:
xdotool search --classname qutebrowser key r
the letter 'r' should be added if you get out of insert mode with escape and redo the command above the page is not refreshed as should happen if qutebrowser received 'r' in normal mode.

**Comment by The-Compiler** [comment]
qutebrowser doesn't support getting key input without having keyboard focus, I don't think there's a way to fix that.

However, for your use case, just use `qutebrowser :reload` instead.

**Comment by nemya9066** [comment]
Oh didn't know that you can send command to qutebrowser this way thanks for the tip.
