### ISSUE TITLE
Delete all browsing data on exit

### ISSUE THREAD

**Issue by omernaveedxyz** [qutebrowser/qutebrowser#6313]
Basically Brave's option to clear (history, cookies, cache, sign-in data, etc) on exiting the browser. Currently have history disabled, but would like to be automatically be signed-out of all my accounts when I exit my current session. Would also like to be able to wipe cookies and such on exit, but that is secondary to being signed-out of my accounts.

![2021-03-2100:48:27](https://user-images.githubusercontent.com/72642828/111895234-397ae600-89df-11eb-8001-3d442167c919.png)

**Comment by arza-zara** [comment]
You can disable saving cookies with `:set content.cookies.store false` – that normally logs you out. #58 covers also this so I'm closing.

**Comment by The-Compiler** [comment]
Also see the `content.private_browsing` setting FWIW.
