### ISSUE TITLE
Quickly switch between tabs

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6319]
It would be nice to have a command that let you search through all the tabs you currently have up. In the same format as when you search for bookmarks, but instead the main part of the url of all your tabs shows. So If i quickly want to switch to my youtube tab, but dont know where it is, dont know exactly which number to use "T" or just dont want to tab all the way there, i can simply type (the keybinding) then "y" "enter", to go to youtube. 

I think quickly navigating between tabs is more important when using the keyboard. In regular browsers its not that annoying to drag your cursor a few more cm to get to the tab you want, but in qutebrowser you have to "K" repeatadly until you get to the tab, and then you cannot use "tab-last focused" to get back. Also many users have their tabs hidden while not switching so its even more difficult to know where they all are and its very difficult to use "T"

**Comment by The-Compiler** [comment]
`gt` / `:tab-select` (`:buffer` in older versions) is exactly that.

**Comment by chris-aeviator** [comment]
also `alt + [tabnr 1-9]` works for me
