### ISSUE TITLE
tab-select doesn't "un-minimize" window, at least on XOrg/KDE Plasma

### ISSUE THREAD

**Issue by jamespharvey20** [qutebrowser/qutebrowser#6321]
**Version info**:
qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
At least on an updated Arch running XOrg and KDE Plasma, if I tab-select a tab whose window is minimized, when I hit enter in tab-select, it doesn't bring the window back and give it focus.  It just does nothing.

I believe some programs maintain a flag that is set when a window is minimized, and when trying to focus another one of the program's windows, check if that flag is set and then use XMapWindow() to "un-minimize" it before setting focus to it.

**How to reproduce**
1. Minimize a tab
2. In another window, tab-select it and hit enter

**Comment by The-Compiler** [comment]
I haven't had the chance to take a closer look yet, but could you try if this changes anything?

```diff
diff --git i/qutebrowser/browser/commands.py w/qutebrowser/browser/commands.py
index 87c8113f0..23e42d66d 100644
--- i/qutebrowser/browser/commands.py
+++ w/qutebrowser/browser/commands.py
@@ -952,8 +952,7 @@ def tab_select(self, index=None, count=None):
         tabbed_browser, tab = self._resolve_tab_index(index)
 
         window = tabbed_browser.widget.window()
-        window.activateWindow()
-        window.raise_()
+        mainwindow.raise_window(window)
         tabbed_browser.widget.setCurrentWidget(tab)
 
     @cmdutils.register(instance='command-dispatcher', scope='window')

```

(If you'd rather not mess with your qutebrowser installation, I can give it a try over the next couple of days - though I typically use a tiling WM)

**Comment by jamespharvey20** [comment]
Your patch appears to work, thanks!  I've been able to tab-select to windows that are minimized, and it brings them back to give them focus, and I can still tab-select to windows that are already on the screen.

**Comment by The-Compiler** [comment]
Yay, thanks for the feedback!
