### ISSUE TITLE
No sound on mac os big sur

### ISSUE THREAD

**Issue by bimawa** [qutebrowser/qutebrowser#6322]
**Version info**:
qutebrowser v2.1.0
Git commit: f75032d76 on v2.1.x (2021-03-12 13:32:32 +0100)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Just no sound.

**How to reproduce**

Open youtube.com and no sound on any videos.

**Comment by The-Compiler** [comment]
This is very unlikely to be a qutebrowser issue, as playing sound is handled by the underlying QtWebEngine/Chromium code entirely.

Unfortunately I don't know another QtWebEngine browser to test with, but could you verify you do get sound with Google Chrome? Also, if macOS has some kind audio settings/mixer (possibly per-application?), make sure to double-check there as well.

**Comment by bimawa** [comment]
Yep, in other browsers all good. 
I sad too (

**Comment by bimawa** [comment]
Yes its something with my macbook. After reboot,  all ok.
