### ISSUE TITLE
qutebrowser does not start, segfault

### ISSUE THREAD

**Issue by webeule** [qutebrowser/qutebrowser#6331]
**Version info**:
I cannot do :version as qutebrowser does not start:
`qutebrowser --version
Fatal Python error: Segmentation fault

Current thread 0x00007f4a6d34a740 (most recent call first):
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 346 in init_user_agent
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/version.py", line 690 in qtwebengine_versions
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/version.py", line 718 in _backend
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/version.py", line 750 in version_info
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 105 in run
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 218 in main
  File "/usr/bin/qutebrowser", line 33 in <module>
Segmentation fault (core dumped)
`
pacman returns: qutebrowser 2.1.0-1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
qutebrowser start terminates with a segmentation fault. It is the same with webkit and webengine backend. It happens directly after this output:
INFO: Run :adblock-update to get adblock lists.

I am using Arch linux (5.11.9-arch1-1).

**How to reproduce**
At every start of qutebrowser.

**Comment by The-Compiler** [comment]
Can you show the logs when you run with `--debug`, as well as the full output of `qutebrowser --version --debug-flag avoid-chromium-init` please?

**Comment by webeule** [comment]
qutebrowser --debug
21:11:14 DEBUG    init       earlyinit:init_log:266 Log initialized.
21:11:15 DEBUG    init       app:run:86 Main process PID: 3052
21:11:15 DEBUG    init       app:run:88 Initializing directories...
21:11:15 DEBUG    init       standarddir:init:338 Base directory: None
21:11:15 DEBUG    misc       standarddir:_writable_location:261 writable location for ConfigLocation: /home/olli/.config
21:11:15 DEBUG    misc       standarddir:_writable_location:261 writable location for AppDataLocation: /home/olli/.local/share
21:11:15 DEBUG    misc       standarddir:_writable_location:261 writable location for CacheLocation: /home/olli/.cache
21:11:15 DEBUG    misc       standarddir:_writable_location:261 writable location for DownloadLocation: /home/olli/Downloads
21:11:15 DEBUG    misc       standarddir:_writable_location:261 writable location for RuntimeLocation: /run/user/1000
21:11:15 DEBUG    init       app:run:92 Initializing config...
21:11:15 DEBUG    config     config:_set_value:318 Config option changed: backend = webengine
21:11:15 DEBUG    init       app:run:95 Initializing application...
21:11:15 DEBUG    misc       elf:parse_webenginecore:324 Got versions from ELF: Versions(webengine='5.15.3', chromium='87.0.4280.144')
21:11:15 DEBUG    init       darkmode:settings:379 Darkmode variant: qt_515_3
21:11:15 DEBUG    init       app:__init__:557 Commandline args: ['--debug']
21:11:15 DEBUG    init       app:__init__:558 Parsed: Namespace(basedir=None, config_py=None, version=False, temp_settings=[], session=None, override_restore=False, target=None, backend=None, desktop_file_name='org.qutebrowser.qutebrowser', json_args=None, temp_basedir_restarted=False, enable_webengine_inspector=False, loglevel=None, logfilter=None, loglines=2000, debug=True, json_logging=False, color=True, force_color=False, nowindow=False, temp_basedir=False, no_err_windows=False, qt_arg=None, qt_flag=None, debug_flags=[], command=[], url=[])
21:11:15 DEBUG    init       app:__init__:559 Qt arguments: ['--enable-features=WebRTCPipeWireCapturer,OverlayScrollbar,ReducedReferrerGranularity']
21:11:15 DEBUG    init       app:__init__:564 Initializing application...
21:11:15 DEBUG    ipc        ipc:send_to_running_instance:465 Connecting to /run/user/1000/qutebrowser/ipc-b5335523585b8431e1e61a4855b246c5
21:11:15 DEBUG    ipc        ipc:send_to_running_instance:495 No existing instance present (error 0)
21:11:15 DEBUG    init       ipc:send_or_listen:525 Starting IPC server...
21:11:15 DEBUG    ipc        ipc:__init__:210 Not calling setSocketOptions
21:11:15 DEBUG    ipc        ipc:listen:221 Listening as /run/user/1000/qutebrowser/ipc-b5335523585b8431e1e61a4855b246c5
21:11:15 DEBUG    init       app:init:145 Starting init...
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.adblockcommands
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.braveadblock
21:11:15 DEBUG    extensions loader:_load_component:159 Running init hook 'init'
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.caretcommands
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.hostblock
21:11:15 DEBUG    extensions loader:_load_component:159 Running init hook 'init'
21:11:15 DEBUG    network    hostblock:_should_be_used:79 Configured adblock method auto, adblock library usable: False
21:11:15 INFO     message    message:info:82 Run :adblock-update to get adblock lists.
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.misccommands
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.readlinecommands
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.scrollcommands
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.utils.blockutils
21:11:15 DEBUG    extensions loader:_load_component:151 Importing qutebrowser.components.zoomcommands
21:11:15 DEBUG    init       app:_init_modules:454 Initializing logging from config...
21:11:15 DEBUG    init       log:init_from_config:543 --debug flag overrides log configs
21:11:15 DEBUG    init       app:_init_modules:458 Initializing save manager...
21:11:15 DEBUG    init       app:_init_modules:464 Checking backend requirements...
21:11:15 DEBUG    init       app:_init_modules:467 Initializing prompts...
21:11:15 DEBUG    init       app:_init_modules:470 Initializing network...
21:11:15 DEBUG    init       app:_init_modules:473 Initializing proxy...
21:11:15 DEBUG    init       app:_init_modules:477 Initializing downloads...
21:11:15 DEBUG    init       app:_init_modules:483 Initializing SQL...
21:11:15 DEBUG    sql        sql:run:278 pragma user_version
21:11:15 DEBUG    init       app:_init_modules:486 Initializing web history...
21:11:15 DEBUG    sql        sql:run:278 SELECT value FROM CompletionMetaInfo WHERE key = :key
21:11:15 DEBUG    sql        sql:run:282     {':key': 'force_rebuild'}
21:11:15 DEBUG    sql        sql:run:278 SELECT value FROM CompletionMetaInfo WHERE key = :key
21:11:15 DEBUG    sql        sql:run:282     {':key': 'excluded_patterns'}
21:11:15 DEBUG    init       debug:__exit__:302 Initializing sql/history took 0.007459 seconds.
21:11:15 DEBUG    init       app:_init_modules:494 Initializing command history...
21:11:15 DEBUG    init       app:_init_modules:497 Initializing websettings...
21:11:15 DEBUG    init       webenginesettings:init:477 Initializing qute://* handler...
21:11:15 DEBUG    init       webenginesettings:init:481 Initializing request interceptor...
21:11:15 DEBUG    init       webenginesettings:init:486 Initializing QtWebEngine downloads...
Segmentation fault (core dumped)

**Comment by webeule** [comment]
qutebrowser --version --debug-flag avoid-chromium-init
Fatal Python error: Segmentation fault

Current thread 0x00007f331ffd5740 (most recent call first):
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/version.py", line 774 in version_info
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 105 in run
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 218 in main
  File "/usr/bin/qutebrowser", line 33 in <module>
Segmentation fault (core dumped)

**Comment by The-Compiler** [comment]
Looks like it segfaults when trying to initialize QtWebEngine, and when avoiding that, segfaults while getting OpenGL info.

Did you recently upgrade your graphic drivers? If so, try a reboot. Can you check if you can reproduce the same issue with e.g. KDE Falkon and/or Chromium?

**Comment by webeule** [comment]
Chromium just starts. I am currently using it to write this post...
I also guess that it has something to do with my graphics card and OpenGL as I am running on an old HP 6715b laptop with a RS690M Radeon Express card. I am using the xf86-video-ati driver.

**Comment by The-Compiler** [comment]
Does starting with `--temp-basedir -s qt.force_software_rendering chromium` change anything? If not, can you try `qt-quick` or `software-opengl` in place of `chromium`?

**Comment by webeule** [comment]
Hey it starts when I use (the other does not work):
--temp-basedir -s qt.force_software_rendering software-opengl

**Comment by webeule** [comment]
But it consumes to much CPU... :-(

**Comment by The-Compiler** [comment]
What does `glxinfo -B` say? (part of `mesa-demos`)

**Comment by webeule** [comment]
What is `qtdiag`?
Yes, glxinfo also segfaults:

glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org R300 Project (0x1002)
    Device: ATI RS690 (0x791f)
    Version: 20.3.4
    Accelerated: yes
    Video memory: 128MB
    Unified memory: no
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: X.Org R300 Project
OpenGL renderer string: ATI RS690
OpenGL version string: 2.1 Mesa 20.3.4
OpenGL shading language version string: 1.20
Segmentation fault (core dumped)

**Comment by The-Compiler** [comment]
Clearly an issue with your system (probably graphics driver) then - nothing qutebrowser can do about it I'm afraid.

**Comment by webeule** [comment]
Today I got some updates from Arch. The mesa package also has been update.
Afterwards qutebrowser started and is working!!!

Thanks a lot for your support!!!
