### ISSUE TITLE
devtools orientation

### ISSUE THREAD

**Issue by tamis-laan** [qutebrowser/qutebrowser#6333]
When setting the orientation of the `:devtools` in the configuration menu to horizontal, it doesn't work. The orientation remains vrtical :-/

**Comment by The-Compiler** [comment]
This setting isn't exposed in any way by QtWebEngine, so qutebrowser can't honour it. However, you can do `:devtools bottom` (`wIj`) instead.

**Comment by The-Compiler** [comment]
Wait, do you mean the "panel layout" switch? That does work properly, but that won't change anything about where the devtools are displayed (not in Chromium either).

**Comment by tamis-laan** [comment]
Yeah I would expect panel layout when set to horizontal would move the devtools panel to its horizontal mode. This doesn't work, however `:devtools bottom` as you said does work. And now devtools remembers this so when I use `:devtools` next time it starts in horizontal mode.

**Comment by The-Compiler** [comment]
That's not what the setting does in Chromium either - it changes the layout of the panels in the devtools:

![image](https://user-images.githubusercontent.com/625793/112638137-33519300-8e3f-11eb-9f9e-27dfa7e39889.png)

![image](https://user-images.githubusercontent.com/625793/112638166-3f3d5500-8e3f-11eb-9a8f-89869e66b6a6.png)

**Comment by tamis-laan** [comment]
I see! thanks for the heads up :)
