### ISSUE TITLE
Virtual Camera output isn't detected

### ISSUE THREAD

**Issue by riazufila** [qutebrowser/qutebrowser#6346]
**Version info**:
qutebrowser v2.0.1
Git commit: 66b0469aa on master (2021-01-28 17:44:07 +0100)
Backend: QtWebEngine (Chromium 87.0.4280.144)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Recently, OBS released version 26.1.x where native virtual camera output feature is made available to Linux users. However, activating the virtual camera didn't change the choices for webcam devices in qutebrowser. However, Firefox detects the virtual device.

**How to reproduce**

1. Install OBS in Linux.
2. Install v4l2loopback-dkms.
3. Start OBS and start Virtual Camera output.
4. Go to any sites that uses webcams like Google Meet.
5. Try to change the camera device it defaults to in-built camera. However, there is still no other virtual camera output.

**Comment by toofar** [comment]
Is
> Try to change the camera device.

because it default to your real webcam of because it defaults to nothing? Because maybe it is the switching that is broken and if there is only the loopback one it'll work? It used to work for me on team, jitsi and slack with https://github.com/CatxFish/obs-v4l2sink before it was merged upstream (Qt 5.14).

Can you try with jitsi meet and see if it works there?

**Comment by riazufila** [comment]
> Can you try with jitsi meet and see if it works there?

The same result happened with Jitsi as well. Only the in-built camera is present.

> It used to work for me on team, jitsi and slack with https://github.com/CatxFish/obs-v4l2sink before it was merged upstream (Qt 5.14).

Using this also yield the same result for me before OBS 26.1.x.

**Comment by riazufila** [comment]
> modprobe v4l2loopback exclusive_caps=1

It worked! I needed that option it seems. Thank you.

**Comment by evilcatlawyer** [comment]
I'm having the same issue right now but the fix listed does not work for me.
