### ISSUE TITLE
Hint mode - allow bindings of any non-hint character

### ISSUE THREAD

**Issue by mgraham** [qutebrowser/qutebrowser#635]
This is a very minor issue/request.

In hint mode it appears that you can't bind numbers and punctuation, even though these can't appear in hints.  It would be great to be able to map these.  For instance, I would like to be able to enter rapid-hint mode with the semi-colon:

```
leave-mode;;hint -r links tab-bg
    ;
```

**Comment by The-Compiler** [comment]
This should be rather easy to do once #319 is done.
