### ISSUE TITLE
Cannot download PDF from Dropbox link

### ISSUE THREAD

**Issue by SoopaKhell** [qutebrowser/qutebrowser#6358]
**Version info**:

qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.4

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

When downloading a PDF from [this](https://www.dropbox.com/s/c682q88keqycp6s/grumbach_laboratories_of_democratic_backsliding.pdf?raw=1
) Dropbox link, QtWebEngine throws an error:

"Download error: The server does not have the requested data"

![yess](https://user-images.githubusercontent.com/11081492/113595519-1d925980-9607-11eb-8bed-209f72889d40.png)

**How to reproduce**

1. Try to download the PDF at this link: https://www.dropbox.com/s/c682q88keqycp6s/grumbach_laboratories_of_democratic_backsliding.pdf?raw=1
2. Give it a filename and save it.
3. Observe the aforementioned error.

**Other notes:**

- Originally I encountered this problem on an installation from my package manger. The problem persists after installing directly from this repo.
- Removing the `?raw=1` on the URL does make the PDF accessible (and downloadable, although less directly) through Dropbox's site.
- Possibly (?) related to #6152, which itself seems to be related to [this QtWebEngine bug](https://bugreports.qt.io/browse/QTBUG-78114).

**Comment by The-Compiler** [comment]
> Possibly (?) related to #6152, which itself seems to be related to this QtWebEngine bug.

Yep, it's that exact issue, and fixed by the [QtWebEngine fix](https://codereview.qt-project.org/c/qt/qtwebengine/+/335189).
