### ISSUE TITLE
colors.webpage.darkmode.threshold.text has no effect

### ISSUE THREAD

**Issue by bzbug** [qutebrowser/qutebrowser#6359]
**Version info**:
qutebrowser v2.0.0
Git commit: 5ac9e3c23 on master (2021-01-28 10:04:39 +0100)
Backend: QtWebEngine (Chromium 87.0.4280.144)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Wouldn't know, since darkmode settings require restart.

**Description/How to reproduce**
There's a background of color `#111` and text of color `#444`, which is still readable and suits for people who prefer low-contrast dark themes. With the Dark Mode enabled, the background stays the same, but the text is inverted. I tried setting `colors.webpage.darkmode.threshold.text` to `0`, `256`, `67` (`#444` in RGB would be `rgb(68, 68, 68)`, so I figured, the value of `67` would for sure put the threshold below the brightness level of this color), `30`, `10`, `150`, nothing changed, the text was still being inverted. I also tried changing the algorithm, tinkering with contrast setting - to the same result.

This wasn't happening until recent change involving Dark Mode, it wasn't even enabled on some pages with this kind of dark theme, so I did not have this problem before. But now it creates good Dark Mode for pages which didn't have it in the first place and screws up the already existing dark theme for other pages.

**Comment by The-Compiler** [comment]
Does the "Backend" line look different when you start with `--version` vs. running `--version --debug-flag avoid-chromium-init`?

**Comment by The-Compiler** [comment]
Also FWIW I can't reproduce. With:

```
<html>
<head>
<style>
body {
    color: #444;
    background-color: #111;
}
</style>
</head>
<body>Hello World</body>
</html>
```

the text is inverted with `qutebrowser --temp-basedir -s colors.webpage.darkmode.enabled true` but isn't with `qutebrowser --temp-basedir -s colors.webpage.darkmode.threshold.text 67 -s colors.webpage.darkmode.enabled true`.

**Comment by bzbug** [comment]
> Does the "Backend" line look different when you start with `--version` vs. running `--version --debug-flag avoid-chromium-init`?

Yes:

`--version` -> Backend: QtWebEngine (Chromium 87.0.4280.144)
`--version --debug-flag avoid-chromium-init` -> Backend: QtWebEngine (Chromium avoided)

&nbsp;
> `qutebrowser --temp-basedir -s colors.webpage.darkmode.threshold.text 67 -s colors.webpage.darkmode.enabled true`

Tried this just now and the text's still being inverted.

**Comment by The-Compiler** [comment]
What OS/distribution is this on? Can you try with a newer qutebrowser version perhaps?

**Comment by bzbug** [comment]
Everything works with `v2.1.1`. Sorry.
