### ISSUE TITLE
MacOS system proxy not detected

### ISSUE THREAD

**Issue by nakrule** [qutebrowser/qutebrowser#6362]
**Version info**:
qutebrowser v2.0.2
Git commit: f11cdd0bf on HEAD (2021-02-04 10:19:33 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

My proxy settings are auto configured with a `pac` file received when I connect to my company network. QuteBrowser do not apply theses settings with `content.proxy system`. When configuring manually the proxy, it then work.

**How to reproduce**
Connect to a network with proxy configuration received by DHCP (option 252, ie a link to a PAC file).

**Comment by The-Compiler** [comment]
See #2492 - this will probably be supported via QtWebEngine if that's taken care of. If not, there's nothing qutebrowser can do about it.
