### ISSUE TITLE
Zoom.us: "Unable to detect a camera or microphone. Please check your device and try again."

### ISSUE THREAD

**Issue by lukmi15** [qutebrowser/qutebrowser#6373]
**Version info**:
qutebrowser v2.1.1
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When trying to join a Zoom call, no microphone or video is detected

**How to reproduce**
```
rm -rf ~/.config/qutebrowser/ ~/.cache/qutebrowser/ ~/.local/share/qutebrowser/ #To make sure this is not because of having selected "always no" when this page asks for permissions
qutebrowser --temp-basedir
```

- Navigate to [the Zoom.us test page](https://zoom.us/test)
- Join the test meeting
- Select "Join from browser"
- It will say "Unable to detect a camera or microphone. Please check your device and try again.", qutebrowser does not ask for permissions

**Comment by The-Compiler** [comment]
Works fine for me. Can you try with Chromium and/or [KDE Falkon](https://www.falkon.org/) (ideally both)?

**Comment by lukmi15** [comment]
Works on Chromium and Falkon
I know that it has worked for me on qutebrowser before but I don't know why it stopped working. Maybe I accidentially chose to never allow access to microphone and camera? But I removed all qutebrowser files from my file system and reinstalled qutebrowser and it still doesn't work.

**Comment by The-Compiler** [comment]
With `--temp-basedir`, qutebrowser ignores all existing data, so removing anything isn't required. Could you reproduce this (with `--temp-basedir` and then do `:report` so I can take a look at the logs?

**Comment by lukmi15** [comment]
I have no idea why, but now it works, even with my old config... :|

**Comment by The-Compiler** [comment]
Closing this then, as it's very unlikely this is qutebrowser's fault. The only thing it does is showing the dialog (just as other permission dialogs as well), everything else is handled by the underlying QtWebEngine/Chromium.
