### ISSUE TITLE
Make F5 still work in Passthrough mode

### ISSUE THREAD

**Issue by BurnyBoi** [qutebrowser/qutebrowser#6378]
As far as I know, F5 is not a key that can be inputted into the webpage any way, so for convenience sake it would be nice if it still worked to reload the page while in passthrough mode.

**Comment by The-Compiler** [comment]
I don't see what would be different about F-keys - websites can definitely handle them, see e.g. [this demo](https://wangchujiang.com/hotkeys/).

The premise of passthrough mode is that it has no default bindings at all (other than a way to leave the mode), so I don't think F5 deserves an exception in any way.

You can bind it yourself though: `:bind --mode passhtrough <F5> reload`
