### ISSUE TITLE
Add error messages for keychains in special-only sections

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#639]
Right now when someone tries to bind, say, `b` in insert mode, that works just fine and gives us this warning when parsing the config:

```
basekeyparser:read_config:339 Ignoring keychain 'x' in mode 'insert' because keychains are not supported there.
```

Instead we should disallow binding that entirely...

**Comment by nicktelford** [comment]
Is there something preventing keychains from being bound in insert mode? I'm probably not alone in wishing I could bind `jj` to exit insert mode (i.e. enter normal mode). This is a really common idiom in VIM.

**Comment by The-Compiler** [comment]
Well, yes - the current code doesn't allow for it, that's why it doesn't work :wink:

Currently, any key pressed while in insert mode is directly passed through to the engine, without qutebrowser handling it at all. That'd need to change.
