### ISSUE TITLE
Hints are not generated for gerrit code review powered pages

### ISSUE THREAD

**Issue by Pi03k** [qutebrowser/qutebrowser#6391]
---
Hints are not generated for gerrit code review powered pages
---

**Version info**:
qutebrowser v2.1.1
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: 0.4.3
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.7.570 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.35.4
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 460.67
Platform: Linux-5.11.12-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
In Gerrit code review powered pages there are no hints generated. They work for chromium's vimium plugin.

qutebrowser
![gerrit no hints](https://user-images.githubusercontent.com/1756537/114686805-6935b900-9d13-11eb-9c9d-1bf699b7e6cd.png)
chromium + vimium
![vimium gerrit hints](https://user-images.githubusercontent.com/1756537/114686823-6d61d680-9d13-11eb-8fe8-f5986f44b7ae.png)

**How to reproduce**
1. Visit gerrit powered page. e.g. https://chromium-review.googlesource.com/q/status:open+-is:wip
2. Press 'f' to generate hints.
3. Look at the bottom of the window. It says ''No elements found'

**Comment by The-Compiler** [comment]
Looks like it uses a [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) for essentially the entire page. Since qutebrowser can only run JS with the same permission the page can, unfortunately it's unable to access those elements (also see [this comment](https://bugreports.qt.io/browse/QTBUG-61676?focusedCommentId=550468&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-550468) I made in a related QtWebEngine issue).

**Comment by The-Compiler** [comment]
After taking a closer look, I think qutebrowser could actually access those elements, as the Shadow DOM is [marked as open](https://blog.revillweb.com/open-vs-closed-shadow-dom-9f3d7427d1af?gi=517cca36714b) - sorry, I wasn't aware of that! I added a comment here: https://github.com/qutebrowser/qutebrowser/issues/3569#issuecomment-822374249
