### ISSUE TITLE
Set custom title/class for window and don't open in existing instance

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [qutebrowser/qutebrowser#6397]
Is it possible to set a custom title/class for a qutebrowser instance? And also tell qutebrowser to not open in an existing instance when launched from a terminal?

## The actual feature request

I use dwm and have some rules to set the size and position of a window base on the name/title of that window. This has worked very well for all programs that allow setting custom title/name/class for the window, but I haven't find this option for qutebrowser. Enabling custom name/class can be very useful for users of tiling window managers.

## Help needed: avoid opening in existing instance

So, I have tried the following workaround: since qutebrowser doesn't seem to support custom name/title (I didn't find an option with `qutebrowser --help` or in the official docs), I try using the following command my window manager:

`{ "st", "-n",  "customname",  "-e", "qutebrowser", "https://example.com"}`  

`st` is simple terminal and allows custom names with option `-n`. Since I use dwm's swallow patch, after `st` executes qutebrowser command the terminal is swallowed (qutebrowser's window is shown over the original terminal window), this way I got the behavior I want.

However, if qutebrowser is already opened elsewhere, then `st` will launch qutebrowser in the existing window, and I don't want that. If I can found a way to avoid qutebrowser opening in an existing window then I will be able to achieve the intended behavior with my window manager.

**Comment by The-Compiler** [comment]
If you use a different `--basedir`, that will open a new instance (but with separate data, config, etc. - those aren't shared between instances, except if you use `--config-py`). You can use `--qt-arg name foobar` to set `WM_CLASS`, see point 19 in the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc). You could also configure the title via the `window.title_format` setting.

**Comment by AndreSouzaAbreu** [comment]
Thanks, your answer almost solve my problem. There is one thing remaining: opening a new instance with separate data is not good for my purposa because I wanted to open telegram, and since the data is separated, qutebrowser won't use the cookies used for authentication. Also, since --basedir uses diferent data, config, I won't be able to use my custom config unless I duplicate it and put on another dir.

Is possible to user --basedir but use the same dir for storing data? At least that way I'd be able to have access to the cookies

**Comment by The-Compiler** [comment]
No - having two different instances accessing the same data isn't supported by the underlying Chromium (and I don't think it'll ever be - Chromium itself acts in the same way as qutebrowser does).

You can just log in again and use `--config-py` (assuming you have a `config.py`), no?

**Comment by AndreSouzaAbreu** [comment]
Yes, it is possible to just log in again (although it is not convenient to log in every time I open the window). And setting WM_CLASS affects all windows, so this is not the ideal.

To avoid this, I guess the best workaround for now is to use the title `Telegram Web - qutebrowser` in my dwm rules, so that I can match this window  (however, this is not a perfect solution because it will matches any window with this title. So, if I'm using qutebrowser normally and go to telegram it will match the window and change its position. But I wanted the rule to apply only to the window that I launched using dwm's config).

Anyway, thanks for the answer. I still hope in the future it will possible to set those options (like WM_CLASS) per window, and not globally.

**Comment by The-Compiler** [comment]
> Yes, it is possible to just log in again (although it is not convenient to log in every time I open the window).

Why would you need to do that?

> I still hope in the future it will possible to set those options (like WM_CLASS) per window, and not globally.

`WM_CLASS` not being settable for individual windows is a Qt limitation. As for `window.title_format`, see #2314.

**Comment by AndreSouzaAbreu** [comment]
> Why would you need to do that?
You're right, I dont need to do that. I made a little confusion
>As for window.title_format, see #2314.
thank you
