### ISSUE TITLE
adblock not working in youtube 

### ISSUE THREAD

**Issue by ranjithshegde** [qutebrowser/qutebrowser#6399]
**Version info**:

https://paste.the-compiler.org/view/35161519

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Adblock works everywhere except for youtube
I have adblock installed from pip, configured correctly, it works on all sites. except for youtube, both the in-video ads and the ad banners on the side of the video player are present

**How to reproduce**
 
enable adblock (either form config.py or from :set), install pip install adblock, open youtube with a video.

**Comment by The-Compiler** [comment]
Do you get static ads or video ads on YouTube?

**Comment by ranjithshegde** [comment]
banner ads on the side + video ads within video.

**Comment by The-Compiler** [comment]
Cosmetic filtering isn't implemented yet (only network request blocking), but I'd expect videos to be blocked by that. I can't double-check right now though. Can you reproduce when starting with `--temp-basedir` and then running `:adblock-update` first?

**Comment by ranjithshegde** [comment]
with the --temp-basedir its fairly inconsistant. On about 3 vidoes I simply got a "Skip ad" prompt without the ad video actually playing, But it did play the ad on one of them

**Comment by The-Compiler** [comment]
Well, I just tried with `--temp-basedir`, and I can't reproduce. I rarely get static ads (with a "skip" button), and never get video ads.

Not much I can do without a clear way to reproduce, I'm afraid. Perhaps @ArniDagur has an idea what's going on?

**Comment by ArniDagur** [comment]
I do get static ads with a skip button, but I don't recall getting a video ad. Perhaps the set of block lists is empty, or `:adblock-update` was not run?

**Comment by ranjithshegde** [comment]
@ArniDagur Thank you for your response

I do run adblock-update fairly regularly. Tried it again, still the same.
When you say block list is empty, where would I check to verify that?

**Comment by The-Compiler** [comment]
What is `content.blocking.adblock.lists` set to? Could you reproduce this (ideally with `--temp-basedir`) and do `:report` so I can take a look at the logs?

**Comment by ranjithshegde** [comment]
> What is content.blocking.adblock.lists set to?

content.blocking.adblock.lists (Current: ["https://easylist.to/easylist/easylist.txt", "https://easylist.to/easylist/easyprivacy.txt"])

> Could you reproduce this (ideally with --temp-basedir) and do :report so I can take a look at the logs?

Will reproduce in a bit and file the report

**Comment by ranjithshegde** [comment]
Here is the report 
[report.txt](https://github.com/qutebrowser/qutebrowser/files/6415888/report.txt)
this is when a video ad was played on youtube, along with side banners

**Comment by The-Compiler** [comment]
Hm. I'm afraid I can't see anything out of the ordinary in that log, and even when visiting that exact video, all I get are overlay ads.

From what I can see in the logs though, the adblocker *does* seem to be set up and working correctly in general. Not much I can do without a way to reproduce I guess...

**Comment by ranjithshegde** [comment]
It has somehow fixed itself. wonder why!
I will close this for now, and reopen if it recures a I know a method to reproduce

**Comment by The-Compiler** [comment]
Also see #6460.
