### ISSUE TITLE
2.2 never exits page loading logic on "Infinite auto-updating timeline" pages

### ISSUE THREAD

**Issue by trysdyn** [qutebrowser/qutebrowser#6404]
**Version info**:
```
qutebrowser v2.2.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.3
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.35.4
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 21.0.2
Platform: Linux-5.11.13-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/trysdyn/.cache/qutebrowser
config: /home/trysdyn/.config/qutebrowser
data: /home/trysdyn/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/trysdyn/.config/qutebrowser/config.py has been loaded
Uptime: 0:43:43
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Visiting a website that follows an "Infinite auto-updating timeline" workflow such as Twitter (When logged in) causes Qute to remain within its page loading logic indefinitely. Specifically the titlebar for the window will display the prefix "[0%]" forever and the default statusbar will display the URI of the page indented left about 200px to make room for a loading progress bar that never fills.

This did not occur prior to 2.2. I cannot replicate on Windows, just my Linux box. This is using Arch packaging on a fresh install as I just switched Distros (mostly to get 2.2 in official mainline; I like Qutebrowser that much :))

**How to reproduce**
1. Visit a site that uses an "Infinite auto-updating timeline" approach
    * Twitter works if you have an account logged in. Just open twitter.com
    * If you don't have a twitter account, a public site that uses this logic is needed. Try https://tailswish.industries
2. Witness the window title keeps [0%] indefinitely and a zero-fill progress bar remains in the statusbar forever

**Comment by toofar** [comment]
Pretty sure this is https://github.com/qutebrowser/qutebrowser/issues/6276 so closing as a duplicate. There has been unfortunate changes around these signals with several Qt releases but it looks like someone upstream is working on a comprehensive fix so that'll be good.
