### ISSUE TITLE
Page for Google Play does not display correctly.

### ISSUE THREAD

**Issue by jtgd** [qutebrowser/qutebrowser#6409]
**Version info**:
qutebrowser v2.2.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Don't know.

**Description**
Top of page for Google Play does not display correctly.

**How to reproduce**
Go to https://play.google.com/store  (I assume you should be logged in to google)

In other browsers the top contains: Play logo, "Google Play", search box, ...

In qutebrowser this does not appear, making it impossible to search for apps.

**Comment by The-Compiler** [comment]
Looks fine for me, even with Qt 5.12:

![image](https://user-images.githubusercontent.com/625793/115222947-90252e00-a10b-11eb-930b-b3de089b9c83.png)

Please try with `--temp-basedir`. There's a reason the issue template asks for it :wink:

**Comment by jtgd** [comment]
Correct. It does not happen with --temp-basedir.

What does that mean then? Is it something in my config?  What could it be?

**Comment by The-Compiler** [comment]
Most likely. Can you show your `:config-diff` please? I suspect `content.*`, especially `content.headers.*`.

**Comment by jtgd** [comment]
aliases = {"q": "quit", "w": "session-save", "wq": "quit --save"}
auto_save.interval = 30000
auto_save.session = true
bindings.commands = {"insert": {"<Ctrl+PgDown>": "tab-next", "<Ctrl+PgUp>": "tab-prev", "<Ctrl+Shift+p>": "spawn --userscript type_pw", "<Ctrl+Shift+u>": "spawn --userscript type_un", "<Ctrl+d>": "tab-close"}, "normal": {",M": "hint links spawn mpv {hint-url}", ",m": "spawn mpv {url}", ";D": "hint images download", "<Alt+r>": "restart", "<Ctrl+1>": "tab-focus 1", "<Ctrl+2>": "tab-focus 2", "<Ctrl+3>": "tab-focus 3", "<Ctrl+4>": "tab-focus 4", "<Ctrl+5>": "tab-focus 5", "<Ctrl+6>": "tab-focus 6", "<Ctrl+7>": "tab-focus 7", "<Ctrl+8>": "tab-focus 8", "<Ctrl+9>": "tab-focus 9", "<Ctrl+Del>": "tab-close", "<Ctrl+d>": "tab-close", "<Ctrl+f>": "set-cmd-text --space :search ", "<Ctrl+q>": "quit --save", "<Ctrl+r>": "reload -f", "<F7>": "hint links userscript queueLink", "<F8>": "spawn --userscript queueLink", "<F9>": "spawn --userscript urlPopHere", "<PgDown>": "scroll-page 0 0.5", "<PgUp>": "scroll-page 0 -0.5", "<Shift+F7>": "hint -r links userscript queueLink", "<Shift+F8>": "spawn --userscript openEww {url}", "<Shift+F9>": "spawn --userscript urlPop", "<Shift+Right>": "navigate next", "<Space>": "scroll-page 0 0.8", "AF": "open -t https://www.facebook.com/Maher/posts ;; open -t https://www.facebook.com/hateLBM/posts ;; open -t https://www.facebook.com/Hannans-You-Cant-Make-This-Crap-Up-Blog-186426388733066/posts ;; open -t https://www.facebook.com/pg/middleageriot/posts/ ;; open -t https://www.facebook.com/jfugelsang ;; open -t https://www.facebook.com/TheGoodLordAbove/posts ;; open -t https://www.facebook.com/LOLGOP/posts ;; open -t https://www.facebook.com/OccupyDemocrats/posts ;; open -t https://www.facebook.com/groups/347259489998335 ;; open -t https://www.facebook.com/groups/472674142924069/", "AN": "open -t medium.com ;; open -t politico.com ;; open -t https://www.pewresearch.org/ ;; open -t https://bigthink.com/ ;; open -t https://www.howtogeek.com/ ;; open -t https://www.vox.com/recode ;; open -t https://www.reuters.com/ ;; open -t https://www.msnbc.com/ ;; open -t https://www.politifact.com/ ;; open -t https://axios.com/ ", "AT": "open -t https://twitter.com/JohnFugelsang ;; open -t https://twitter.com/middleageriot ;; open -t https://twitter.com/fermatslibrary ;; open -t https://twitter.com/robreiner ;; open -t https://twitter.com/stevebenen ;; open -t https://twitter.com/StephenKing ;; open -t https://twitter.com/nixcraft ;; open -t https://twitter.com/ProjectLincoln", "E": "spawn --userscript openEww {url}", "J": "tab-prev", "K": "tab-next", "M": "quickmark-save", "SS": "session-load standard", "Sb": "open -t qute://bookmarks#bookmarks", "Sh": "open -t qute://history", "Sq": "open -t qute://bookmarks", "Ss": "open -t qute://settings", "UI": "spawn --userscript urlPop", "UO": "spawn --userscript urlPush", "V": "spawn --detach vlc -f {url}", "Y": "spawn --detach mpv {url}", "e": "spawn --userscript bmPage", "gd": "set-cmd-text -s :bookmark-del", "gl": "tab-move -", "gr": "tab-move +", "m": "bookmark-add", "s": "hint images download"}, "yesno": {"<Alt+Shift+y>": "prompt-yank --sel", "<Alt+y>": "prompt-yank", "<Escape>": "mode-leave", "<Return>": "prompt-accept", "N": "prompt-accept --save no", "Y": "prompt-accept --save yes", "n": "prompt-accept no", "y": "prompt-accept yes"}}
colors.tabs.bar.bg = black
colors.tabs.even.bg = black
colors.tabs.even.fg = white
colors.tabs.odd.bg = black
colors.tabs.odd.fg = white
colors.tabs.pinned.even.bg = black
colors.tabs.pinned.even.fg = white
colors.tabs.pinned.odd.bg = black
colors.tabs.pinned.odd.fg = white
colors.tabs.pinned.selected.even.bg = #26C
colors.tabs.pinned.selected.even.fg = white
colors.tabs.pinned.selected.odd.bg = #26C
colors.tabs.pinned.selected.odd.fg = white
colors.tabs.selected.even.bg = #26C
colors.tabs.selected.even.fg = white
colors.tabs.selected.odd.bg = #26C
colors.tabs.selected.odd.fg = white
colors.webpage.bg = white
colors.webpage.darkmode.algorithm = lightness-hsl
colors.webpage.darkmode.contrast = 0.0
colors.webpage.darkmode.enabled = false
colors.webpage.darkmode.grayscale.all = false
colors.webpage.darkmode.policy.images = smart
colors.webpage.darkmode.policy.page = smart
colors.webpage.darkmode.threshold.background = 205
colors.webpage.darkmode.threshold.text = 10
colors.webpage.preferred_color_scheme = dark
completion.cmd_history_max_items = 100
content.autoplay = false
content.fullscreen.window = true
content.headers.user_agent = Chrome/91 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/91.0.4455.2 Safari/537.36
content.javascript.can_open_tabs_automatically = true
https://messages.google.com: content.notifications.enabled = true
content.notifications.enabled = true
content.notifications.presenter = herbe
https://calendar.google.com?cid=%25s: content.register_protocol_handler = false
https://mail.google.com?extsrc=mailto&url=%25s: content.register_protocol_handler = true
downloads.remove_finished = 30
editor.command = ["emacsclient", "{file}"]
fonts.hints = bold 14pt monospace
fonts.prompts = 12pt sans-serif
fonts.web.family.fixed = "16pt DejaVu Sans Mono"
fonts.web.family.sans_serif = "16pt DejaVu Sans Mono"
fonts.web.family.serif = "16pt DejaVu Sans Mono"
fonts.web.family.standard = "16pt DejaVu Sans Mono"
fonts.web.size.default_fixed = 16
fonts.web.size.minimum = 16
fonts.web.size.minimum_logical = 16
hints.chars = acdefhkwourtv/;=
hints.next_regexes = ["\\bNext story\\b", "\\bnext\\b", "\\bmore\\b", "\\bnewer\\b", "\\b[>\u2192\u226b]\\b", "\\b(>>|\u00bb)\\b", "\\bcontinue\\b"]
input.insert_mode.auto_enter = true
input.insert_mode.auto_leave = true
input.insert_mode.auto_load = true
input.insert_mode.plugins = true
messages.timeout = 3000
new_instance_open_target = tab
scrolling.bar = always
search.incremental = true
session.default_name = default
session.lazy_restore = true
spellcheck.languages = ["en-US"]
tabs.last_close = close
tabs.new_position.related = last
tabs.position = left
tabs.select_on_remove = next
tabs.width = 10%
url.default_page = file:///home/jay/MyHomePage.html
url.incdec_segments = ["path", "query", "anchor"]
url.open_base_url = true
url.searchengines = {"DEFAULT": "https://duckduckgo.com/?q={}", "am": "https://www.amazon.com/s?k={}", "ar": "https://www.archlinux.org/packages/?q={}", "au": "https://aur.archlinux.org/packages/?K={}", "aw": "https://wiki.archlinux.org/?search={}", "d": "https://www.thefreedictionary.com/{}", "g": "https://google.com/?search={}", "gm": "https://www.google.com/maps/place/{}", "nf": "https://www.netflix.com/search?q={}", "nm": "http://www.imdb.com/find?s=nm&q={}zz", "nzbf": "https://nzbfinder.ws/search?id={}", "os": "https://www.opensubtitles.org/en/search2/sublanguageid-eng/moviename-{}", "tt": "http://www.imdb.com/find?s=tt&q={}", "wp": "https://en.wikipedia.org/wiki/{}", "yt": "https://www.youtube.com/results?search_query={}"}
url.start_pages = file:///home/jay/MyHomePage.html

**Comment by jtgd** [comment]
aliases = {"q": "quit", "w": "session-save", "wq": "quit --save"}
auto_save.interval = 30000
auto_save.session = true
bindings.commands = {"insert": {"<Ctrl+PgDown>": "tab-next", "<Ctrl+PgUp>": "tab-prev", "<Ctrl+Shift+p>": "spawn --userscript type_pw", "<Ctrl+Shift+u>": "spawn --userscript type_un", "<Ctrl+d>": "tab-close"}, "normal": {",M": "hint links spawn mpv {hint-url}", ",m": "spawn mpv {url}", ";D": "hint images download", "<Alt+r>": "restart", "<Ctrl+1>": "tab-focus 1", "<Ctrl+2>": "tab-focus 2", "<Ctrl+3>": "tab-focus 3", "<Ctrl+4>": "tab-focus 4", "<Ctrl+5>": "tab-focus 5", "<Ctrl+6>": "tab-focus 6", "<Ctrl+7>": "tab-focus 7", "<Ctrl+8>": "tab-focus 8", "<Ctrl+9>": "tab-focus 9", "<Ctrl+Del>": "tab-close", "<Ctrl+d>": "tab-close", "<Ctrl+f>": "set-cmd-text --space :search ", "<Ctrl+q>": "quit --save", "<Ctrl+r>": "reload -f", "<F7>": "hint links userscript queueLink", "<F8>": "spawn --userscript queueLink", "<F9>": "spawn --userscript urlPopHere", "<PgDown>": "scroll-page 0 0.5", "<PgUp>": "scroll-page 0 -0.5", "<Shift+F7>": "hint -r links userscript queueLink", "<Shift+F8>": "spawn --userscript openEww {url}", "<Shift+F9>": "spawn --userscript urlPop", "<Shift+Right>": "navigate next", "<Space>": "scroll-page 0 0.8", "E": "spawn --userscript openEww {url}", "J": "tab-prev", "K": "tab-next", "M": "quickmark-save", "SS": "session-load standard", "Sb": "open -t qute://bookmarks#bookmarks", "Sh": "open -t qute://history", "Sq": "open -t qute://bookmarks", "Ss": "open -t qute://settings", "UI": "spawn --userscript urlPop", "UO": "spawn --userscript urlPush", "V": "spawn --detach vlc -f {url}", "Y": "spawn --detach mpv {url}", "e": "spawn --userscript bmPage", "gd": "set-cmd-text -s :bookmark-del", "gl": "tab-move -", "gr": "tab-move +", "m": "bookmark-add", "s": "hint images download"}, "yesno": {"<Alt+Shift+y>": "prompt-yank --sel", "<Alt+y>": "prompt-yank", "<Escape>": "mode-leave", "<Return>": "prompt-accept", "N": "prompt-accept --save no", "Y": "prompt-accept --save yes", "n": "prompt-accept no", "y": "prompt-accept yes"}}
colors.tabs.bar.bg = black
colors.tabs.even.bg = black
colors.tabs.even.fg = white
colors.tabs.odd.bg = black
colors.tabs.odd.fg = white
colors.tabs.pinned.even.bg = black
colors.tabs.pinned.even.fg = white
colors.tabs.pinned.odd.bg = black
colors.tabs.pinned.odd.fg = white
colors.tabs.pinned.selected.even.bg = #26C
colors.tabs.pinned.selected.even.fg = white
colors.tabs.pinned.selected.odd.bg = #26C
colors.tabs.pinned.selected.odd.fg = white
colors.tabs.selected.even.bg = #26C
colors.tabs.selected.even.fg = white
colors.tabs.selected.odd.bg = #26C
colors.tabs.selected.odd.fg = white
colors.webpage.bg = white
colors.webpage.darkmode.algorithm = lightness-hsl
colors.webpage.darkmode.contrast = 0.0
colors.webpage.darkmode.enabled = false
colors.webpage.darkmode.grayscale.all = false
colors.webpage.darkmode.policy.images = smart
colors.webpage.darkmode.policy.page = smart
colors.webpage.darkmode.threshold.background = 205
colors.webpage.darkmode.threshold.text = 10
colors.webpage.preferred_color_scheme = dark
completion.cmd_history_max_items = 100
content.autoplay = false
content.fullscreen.window = true
content.headers.user_agent = Chrome/91 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/91.0.4455.2 Safari/537.36
content.javascript.can_open_tabs_automatically = true
https://messages.google.com: content.notifications.enabled = true
content.notifications.enabled = true
content.notifications.presenter = herbe
https://calendar.google.com?cid=%25s: content.register_protocol_handler = false
https://mail.google.com?extsrc=mailto&url=%25s: content.register_protocol_handler = true
downloads.remove_finished = 30
editor.command = ["emacsclient", "{file}"]
fonts.hints = bold 14pt monospace
fonts.prompts = 12pt sans-serif
fonts.web.family.fixed = "16pt DejaVu Sans Mono"
fonts.web.family.sans_serif = "16pt DejaVu Sans Mono"
fonts.web.family.serif = "16pt DejaVu Sans Mono"
fonts.web.family.standard = "16pt DejaVu Sans Mono"
fonts.web.size.default_fixed = 16
fonts.web.size.minimum = 16
fonts.web.size.minimum_logical = 16
hints.chars = acdefhkwourtv/;=
hints.next_regexes = ["\\bNext story\\b", "\\bnext\\b", "\\bmore\\b", "\\bnewer\\b", "\\b[>\u2192\u226b]\\b", "\\b(>>|\u00bb)\\b", "\\bcontinue\\b"]
input.insert_mode.auto_enter = true
input.insert_mode.auto_leave = true
input.insert_mode.auto_load = true
input.insert_mode.plugins = true
messages.timeout = 3000
new_instance_open_target = tab
scrolling.bar = always
search.incremental = true
session.default_name = default
session.lazy_restore = true
spellcheck.languages = ["en-US"]
tabs.last_close = close
tabs.new_position.related = last
tabs.position = left
tabs.select_on_remove = next
tabs.width = 10%
url.default_page = file:///home/jay/MyHomePage.html
url.incdec_segments = ["path", "query", "anchor"]
url.open_base_url = true
url.searchengines = {"DEFAULT": "https://duckduckgo.com/?q={}", "am": "https://www.amazon.com/s?k={}", "ar": "https://www.archlinux.org/packages/?q={}", "au": "https://aur.archlinux.org/packages/?K={}", "aw": "https://wiki.archlinux.org/?search={}", "d": "https://www.thefreedictionary.com/{}", "g": "https://google.com/?search={}", "gm": "https://www.google.com/maps/place/{}", "nf": "https://www.netflix.com/search?q={}", "nm": "http://www.imdb.com/find?s=nm&q={}zz", "nzbf": "https://nzbfinder.ws/search?id={}", "os": "https://www.opensubtitles.org/en/search2/sublanguageid-eng/moviename-{}", "tt": "http://www.imdb.com/find?s=tt&q={}", "wp": "https://en.wikipedia.org/wiki/{}", "yt": "https://www.youtube.com/results?search_query={}"}
url.start_pages = file:///home/jay/MyHomePage.html

**Comment by The-Compiler** [comment]
It's your fake user agent causing this.

**Comment by jtgd** [comment]
I think before I modified that it was like Chrome 87 and I was on a website that complained, "this website only works with at least Chrome 90" and chromium-dev was 91.

What is the better way to deal with that problem, where it complains about the version?

(deleting that line from my config did fix the problem)

**Comment by The-Compiler** [comment]
Use the default user agent, and only [override it](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#per-domain-settings) for certain domains rather than globally.

**Comment by jtgd** [comment]
Understood. Thank you for the link.
