### ISSUE TITLE
can't kill qutebrowser

### ISSUE THREAD

**Issue by suddenlyfleck** [qutebrowser/qutebrowser#6428]
If i kill a process, I expect something like this:
```
(base) mf@ryzn:~$ sudo killall pcmanfm && sudo killall pcmanf
pcmanfm: no process found
```
i.e. you can't kill the same process twice.

But right now I can do:

```
sudo killall qutebrowser && sudo killall qutebrowser
(base) mf@ryzn:~$ 
```

problem is: The process is not killed, even after a minute.

Happens in bash, happens in fish.

I will restart my computer now, because I need a browser, e.g. for filling out the below information. 

brb...

**Version info**:
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.2

sip: 5.4.0
colorama: no
jinja2: 2.11.3
pygments: no
yaml: 5.3.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 460.67
Platform: Linux-5.10.0-6-amd64-x86_64-with-glibc2.31, 64bit
Linux distribution: Debian GNU/Linux bullseye/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/mf/.cache/qutebrowser
config: /home/mf/.config/qutebrowser
data: /home/mf/.local/share/qutebrowser
runtime: /run/user/1001/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/mf/.config/qutebrowser/config.py has been loaded
Uptime: 0:03:32
**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

**How to reproduce**
sorry, no info.

**Comment by The-Compiler** [comment]
A `SIGTERM` (which is sent by `kill` by default) is a request to a process to clean up and then terminate cleanly. This doesn't happen immediately, so your example with `killall` isn't very useful.

I can even reproduce the same scenario in your second example with pcmanfm, by clicking around a bit. You're essentially producing a race condition there, if the second `kill` runs before pcmanfm is done cleaning up, it will not show "no process found".

So unless you can show some log output about what happens after killing, there's nothing to do here. I'm assuming you rebooted already, so is this something you can still reproduce?

**Comment by suddenlyfleck** [comment]
Thanks for your input.

Problem is: 
The process is not even killed after minutes.

I'm not sure whether this might ab an operating system thing or a qutebrowser thing but I think I'd start here.

How do you suggest I'd stop all qutebrowser activity on my system?

**Comment by The-Compiler** [comment]
Well, qutebrowser should quit gracefully after a first SIGTERM. If it doesn't, it tries harder after a second and third SIGTERM.

So this is something which is happening more often then?

**Comment by suddenlyfleck** [comment]
I can't be sure but I think I have experienced this more than once. I think I am at the third time.

I'm, howver, not willing to bet more than 20bucks on such a statement, so ... ;)

**Comment by The-Compiler** [comment]
You could for example replace `qutebrowser` with a wrapper script (e.g. `/usr/local/bin/qutebrowser`) which does:

```
#!/bin/bash
qutebrowser --debug "$@" &> ~/qb-logs/$$.log
```

which means it'll collect logfiles for all invocations. Then when you can't kill it, you can find out its pid using `pgrep` and look at what's happening in the respective log file.

(Normally you could also use `:report` to view/submit the in-RAM logs, but I'm not sure if that works if qutebrowser is in some kind of hanging state)

**Comment by The-Compiler** [comment]
@suddenlyfleck Any updates?

**Comment by suddenlyfleck** [comment]
I'm loging, but haven't had a further comparable incident since.

If I get something tangible, I'll post it here.

Thanks for asking :)

**Comment by The-Compiler** [comment]
Alright, closing this for now then - let me know if you find out more, though!
