### ISSUE TITLE
AttributeError: module 'adblock' has no attribute 'Engine'

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6436]
Got this [crash report](https://crashes.qutebrowser.org/view/7f1cfe38) with qutebrowser 2.2.1:

```pytb
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.2.1', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 220, in main
    return app.run(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 122, in run
    init(args=args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 155, in init
    loader.load_components()
  File "/usr/lib/python3.9/site-packages/qutebrowser/extensions/loader.py", line 86, in load_components
    _load_component(info, skip_hooks=skip_hooks)
  File "/usr/lib/python3.9/site-packages/qutebrowser/extensions/loader.py", line 161, in _load_component
    mod_info.init_hook(_get_init_context())
  File "/usr/lib/python3.9/site-packages/qutebrowser/components/braveadblock.py", line 304, in init
    ad_blocker = BraveAdBlocker(
  File "/usr/lib/python3.9/site-packages/qutebrowser/components/braveadblock.py", line 134, in __init__
    self._engine = adblock.Engine(adblock.FilterSet())
AttributeError: module 'adblock' has no attribute 'Engine'
```

@ArniDagur any idea what's going on there? Unfortunately the log doesn't show the `adblock` version, but with 0a9da570085b198fbcba6238a54c49757a8a962e we should ensure it's new enough?

**Comment by ArniDagur** [comment]
Is this an automated crash report of some kind? i.e. it was not manually reported on GitHub or IRC? Ever since the [first commit](https://github.com/ArniDagur/python-adblock/commit/129bfc10146973ce8a33fcd383c56c4f8071a492#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R81), `Engine` has been a class which is a part of the library. The thing that comes to mind is that there is something wrong with the imports? It's hard to say.

**Comment by The-Compiler** [comment]
Yeah, exactly, it's using the automated crash reporter. The version information just shows "adblock: yes" (i.e. no `__version__` attribute), so possibly someone ended up with an adblock.py being imported which isn't part of your project.

Since there's no contact information and I haven't seen this happen for anyone else, let's close this and not worry about it too much. Thanks for the quick response!

**Comment by The-Compiler** [comment]
Got reports from two more users about this (note to self: [first](https://crashes.qutebrowser.org/view/ad7fd79e), [second](https://crashes.qutebrowser.org/view/a772cb4e)).

Still no idea what's going on and no contact information I'm afraid. They're all on Archlinux derivatives (Manjaro, Artix Linux, Archcraft). I wonder if the Archlinux AUR has something that provides an `adblock.py`, but no idea how to find out what.

**Comment by The-Compiler** [comment]
I added some debug logging in 3950aafe8a93bd979f2a62f8f768bd166326617c which will hopefully help find out what's happening the next time someone reports this.
