### ISSUE TITLE
A way to disable the title bar on macOS.

### ISSUE THREAD

**Issue by Raghav-Dixit** [qutebrowser/qutebrowser#6438]
The title bar on top of the window in OSX takes away from the minimalism of the browser. Same request as #3199 (I just wanted to bring it up again. If there was a setting to remove this, it would be nice. I am fine with the close, minimize, and maximize buttons going because I use the keyboard shortcuts for those anyway.

**Comment by The-Compiler** [comment]
That option exists (which is why #3199 was closed): `window.hide_decoration`. You might run into #4067, however.
