### ISSUE TITLE
Extending the autoplay block ?

### ISSUE THREAD

**Issue by Lembrun** [qutebrowser/qutebrowser#6439]
The autoplay block is not working for everything.

This is blocked in firefox, but not qutebrowser and falkon

[Example video](https://static.fsf.org/nosvn/videos/fight-to-repair/source-files/fight-to-repair.720p.mp4)

Would it be possible to block the above with some javascript, like detect that the url ends with an mp4,webm... and pause the video ?

(See IRC log of 01/05 , 20:00 - 22:00 for the full discussion)

**Comment by The-Compiler** [comment]
Sounds like autocmds would potentially help here, but I don't think we should hack more stuff into the autoplay setting (which is handled by the underlying Chromium)
