### ISSUE TITLE
macOs Force Dark Mode

### ISSUE THREAD

**Issue by apexatoll** [qutebrowser/qutebrowser#6440]
**Version info**:
```
qutebrowser v2.1.0
Git commit: f75032d76 on v2.1.x (2021-03-12 13:32:32 +0100)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.3

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: 2.6.347 (bundled)
sqlite: 3.33.0
QtNetwork SSL: Secure Transport, macOS Mojave (10.14)

Style: QMacStyle
Platform plugin: cocoa
OpenGL: None
Platform: macOS-10.14.6-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.14.6, x86_64`
**Does the bug happen if you start with `--temp-basedir`?**:
```

I updated earlier today to the latest qutebrowser from 1.14.1 in an attempt to rebuild qt with codec support - I didn't end up doing this, but now am unable to revert the UI toolbar to dark mode on macOs 10.14.6

I have tried explicitly setting NSRequiresAquaSystemAppearance in Info.plist, downgrading to the previous version I was on and copying over a copy of qutebrowser from another machine where this was not a problem, but the UI bar is still grey

**Comment by The-Compiler** [comment]
Try v2.2.0 which does set NSRequiresAquaSystemAppearance?

**Comment by apexatoll** [comment]
Still no luck on 2.2.1 - I have tried changing the permissions of the Info.plist file as well

**Comment by The-Compiler** [comment]
Well, no idea then, but I assume this is a problem on your side. Try  a clean install without any modifications please.

**Comment by apexatoll** [comment]
There must have been some conflicting config settings - resetting the global NS string, updating and logging out and in fixed it

For anyone who runs into similar issues 
```
defaults delete -g NSRequiresAquaSystemAppearance

defaults write org.qt-project.Qt.QtWebEngineCore NSRequiresAquaSystemAppearance -bool NO
```

**Comment by The-Compiler** [comment]
Thanks for the update - closing this then!
