### ISSUE TITLE
:greasemonkey-reload - enable redownloading @required files

### ISSUE THREAD

**Issue by hseg** [qutebrowser/qutebrowser#6457]
As it stands, the cached versions in `$XDG_DATA_HOME/qutebrowser/greasemonkey/requires` don't get updated when running `:greasemonkey-update`.
One possible design: add a `--all` switch that would force redownloading those files as well.

**Comment by toofar** [comment]
There's a --force option that'll try to re-fetch everything

**Comment by hseg** [comment]
So it does. Didn't show up in command completion, so I didn't know to look for it.
Sorry for the noise.

On May 12, 2021 10:59:18 AM GMT+03:00, toofar ***@***.***> wrote:
>There's a --force option that'll try to re-fetch everything
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qutebrowser/qutebrowser/issues/6457#issuecomment-839553166
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
There's no completion for flags right now, but `:help :greasemonkey-reload` will show it.
