### ISSUE TITLE
Greasemonkey scripts: Local file improvements

### ISSUE THREAD

**Issue by hseg** [qutebrowser/qutebrowser#6458]
- [ ] "Cache" local files using symlinks
- [ ] Accept relative `@requires` directives, without requiring the use of the `file://` protocol

**Comment by The-Compiler** [comment]
What do you mean with *"Cache" local files using symlinks*?

**Comment by hseg** [comment]
When you ***@***.***` a local file, instead of copying it into `required`, qb could just symlink it. That way, you don't get the confusing semantics of "I changed it, why isn't it picking it up?". Though otoh, that's the standard greasemonkey versioning semantics, so feel free to ignore this if I'm being ridiculous.

On May 12, 2021 1:49:02 PM GMT+03:00, Florian Bruhin ***@***.***> wrote:
>What do you mean with *"Cache" local files using symlinks*?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qutebrowser/qutebrowser/issues/6458#issuecomment-839673135
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
There's no real reason the file needs to be in the greasemonkey directory - instead of symlinking (or copying) it, qutebrowser might as well just read it from its original location instead.

**Comment by hseg** [comment]
Well, it's an added complexity. Otoh, symlinking isn't easy on windows. I'm fine closing this part as WONTFIX - I'm asking for an unnecessary semantics break.
Do want  ***@***.***` to support protocolless local paths. For relative paths,  `file://` confuses me

On May 12, 2021 3:09:40 PM GMT+03:00, Florian Bruhin ***@***.***> wrote:
>There's no real reason the file needs to be in the greasemonkey directory - instead of symlinking (or copying) it, qutebrowser might as well just read it from its original location instead.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qutebrowser/qutebrowser/issues/6458#issuecomment-839718926
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by The-Compiler** [comment]
Merging this into #3238.
