### ISSUE TITLE
Brave adblock not working

### ISSUE THREAD

**Issue by fine2006** [qutebrowser/qutebrowser#6460]
**Version info**:

qutebrowser v2.2.1
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2
**Does the bug happen if you start with `--temp-basedir`?**:
No
**Description**
The brave style adblock is not working, python-adblock library is installed, yet the ads on youtube are showing up, while websites are still detecting the  presence of an adblock, probably the host-based one.
**How to reproduce**

I can't really tell

**Comment by The-Compiler** [comment]
A couple of questions:

- What does the `adblock: ...` line say in `:version`?
- What does `:set content.blocking.method` say?
- Did you run `:adblock-update` recently?
- You say you can't reproduce with `--temp-basedir`? So the ads are blocked there?
- What kind of ads do you get exactly?

**Comment by rezaarifandee** [comment]
I experienced this too today. This happens both with jblock or the brave addon.

Weird thing is, running with `--temp-basedir` seems to solves the issue (it still sometimes show video ads on youtube but it's rare). I checked the log with `:report` and there are logs that tells me that brave adblocker detects and blocks the ad just fine.

Also, i updated qutebrowser today (to version 2.2.1), I'm reverting to version 2.1.1 right now, will report back.

**Comment by The-Compiler** [comment]
Looks like this isn't qutebrowser-specific:

https://www.reddit.com/r/uBlockOrigin/comments/nai0nq/ads_showing_up_on_youtube_now

https://www.reddit.com/r/uBlockOrigin/comments/n6gjui/youtube_ads_are_back

https://www.reddit.com/r/uBlockOrigin/comments/n7kdzc/youtube_ads_not_being_blocked

I don't think there's anything we can do about that.

**Comment by rezaarifandee** [comment]
Glad to know, bunch of thanks!

**Comment by fine2006** [comment]
> A couple of questions:
> 
> 1. What does the `adblock: ...` line say in `:version`?
> 2. What does `:set content.blocking.method` say?
> 3. Did you run `:adblock-update` recently?
> 4. You say you can't reproduce with `--temp-basedir`? So the ads are blocked there?
> 5. What kind of ads do you get exactly?

1. 0.4.4
2. Auto
3. Just now
4. Yes, the ads weren't coming up in temp-basedir
5. Video ads, in-site ads, basically everything on youtube.

**Comment by m040601** [comment]
I too seem to be having this problem.


> What kind of ads do you get exactly?

In my case, I noticed it not in youtube, but in adblock failure to load and parse an extra adblock list and use it effectively.

This is a list to block **social media icons** which is the only extra things I added to the defaults.

`["https://easylist.to/easylist/easylist.txt", "https://easylist.to/easylist/easyprivacy.txt", "https://secure.fanboy.co.nz/fanboy-annoyance.txt"]`

This fanboy-annoyance list is responsible for sharing those **"share with ... facebook twitter "** etc buttons

> What does the adblock: ... line say in :version?

adblock: 0.4.4
> What does :set content.blocking.method say?

auto
> Did you run :adblock-update recently?

of course

I've tested this over and over, comparing qutebrowser and firefox, both my standard installation and fresh not customized ones.


> reproduce with --temp-basedir? So the ads are blocked there?

I made extensive use of
`qutebrowser -T --debug --logfilter network`
to follow in real time on the terminal whats happening


```
qutebrowser v2.2.1
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.0
pygments: no
yaml: 5.4.1
adblock: 0.4.4
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: X.Org, 3.0 Mesa 21.1.0
Platform: Linux-5.12.4-arch1-2-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-06_x0ntu/cache
config: /tmp/qutebrowser-basedir-06_x0ntu/config
data: /tmp/qutebrowser-basedir-06_x0ntu/data
runtime: /tmp/qutebrowser-basedir-06_x0ntu/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
```

**Comment by The-Compiler** [comment]
@m040601 this seems unrelated - not much I can say without a link to an affected page, but I'm guessing it's because cosmetic filtering isn't implemented so far, see #5754.

**Comment by m040601** [comment]
> @m040601 this seems unrelated -

Yeap. Sorry, I just noticed your reply now, after I deleted my own post and opened a new issue.

**Comment by fine2006** [comment]
@The-Compiler The adblocker is not working currently, while issues in almost every other adblock have been solved.

**Comment by The-Compiler** [comment]
@fine2006: Looks like pure network-based rules (which are the only ones supported by qutebrowser so far) aren't enough anymore to block ads with how they're served on YouTube now. I opened #6480 for this.

**Comment by midischwarz12** [comment]
Odd, up until the beginning of this year around spring, youtube video adblock did work. But now, even after running `:adblock-update`, it no longer works. Note - all other static adblocking still works.

I have recently tried to this again on a clean VM with qutebrowser (v3.5.1) and brave python-adblock (0.6.0), and I'm still witnessing the same behavior of receiving youtube video ads.

This may (???) be relevant considering that the adblock wrapper needs an update: https://github.com/ArniDagur/python-adblock/issues/94
