### ISSUE TITLE
Named userscripts

### ISSUE THREAD

**Issue by tdehaeze** [qutebrowser/qutebrowser#6463]
Hi,

I use a lot of userscripts and I think they are so great to add useful functionality in a simple way.

However, I tend to not remember the key bindings for them (I use a comma as a first letter to all my custom bindings) and when they display, it is difficult to see which one does what (see picture below).

![qutebrowser_userscripts](https://user-images.githubusercontent.com/10817626/118154108-f5242900-b416-11eb-8504-0537211973b4.png)

Therefore, I think it would be great if there was a way to give a name to the script that will be displayed instead of the full command. This could be configured like so:

``` python
config.bind(",a", "command", title="This does that.")
```
What do you think?

Cheers

**Comment by The-Compiler** [comment]
You can already do this by [adding an alias](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/settings.asciidoc#aliases) for those commands.

**Comment by tdehaeze** [comment]
Awesome!
Thanks a lot.

Here is how my config looks like now:
``` python
c.aliases['DisplayName'] = 'spawn --userscript ~/.config/qutebrowser/userscripts/script.sh'
config.bind(',r', 'DisplayName')
```
