### ISSUE TITLE
API-MS-WIN-CORE-PATH dll are missing

### ISSUE THREAD

**Issue by dridk** [qutebrowser/qutebrowser#6476]
Version 2.2.2 

Cannot Run Qutebrowser from Windows 7. 
Some dll are missing. 

![image](https://user-images.githubusercontent.com/1911063/119496324-ac983400-bd63-11eb-8a0b-bcf506aef70d.png)

Note: 
When I deploy a PySide2 application on windows with PyInstaller, I get all the "API-MS-xxx.dll" in my bundle and the application run well.

**Comment by The-Compiler** [comment]
See https://github.com/qutebrowser/qutebrowser/issues/2788#issuecomment-391837179 - given that Windows 7 is out of support (and this probably isn't even a fully updated Windows 7), I think it's safe to assume for qutebrowser that those files are present system-wide.

cc @bitraid

**Comment by bitraid** [comment]
This file (`api-ms-win-core-path-l1-1-0.dll`) is only for Windows 8 and later, so even with a fully updated Windows 7, you'll still get this error. It is a requirement of Python 3.9 that qutebrowser uses for the release version 2.0.0 and after.

**Comment by The-Compiler** [comment]
Right, thanks @bitraid for the clarification and the PR!

Things might still work on Windows 7 if you build a custom release (using `tox -e build-release`) with Python 3.8 instead (Qt 5.15 still [seems to support](https://doc.qt.io/qt-5.15/supported-platforms.html) Windows 7). But this isn't officially supported, and I don't think it's reasonable to build the releases with Python 3.8 (and thus not including various [performance improvements](https://docs.python.org/3/whatsnew/3.9.html) and such from Python 3.9) to continue supporting a Windows version which [has been EOL](https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information) for almost 1.5 years now.

**Comment by rundekugel** [comment]
This might help:
https://github.com/nalexandru/api-ms-win-core-path-HACK
It's a dll compatible to Win7 tested with Blender
