### ISSUE TITLE
Vifm not opening as file picker

### ISSUE THREAD

**Issue by wgmayer0** [qutebrowser/qutebrowser#6486]
I have the following configuration in my Qutebrowser settings:

`fileselect.folder.command (Current: ["xterm", "-e", "vifm", "--choosedir={}"])
Command (and arguments) to use for selecting a single folder in forms. The command should write the selected folder path to the specified file or stdout.
The following placeholders are defined:
* `{}`: Filename of the file to be written to. If not contained in any argument, the
standard output of the command is read instead.

￼
fileselect.handler (Current: external)
Handler for selecting file(s) in forms. If `external`, then the commands specified by `fileselect.single_file.command` and `fileselect.multiple_files.command` are used to select one or multiple files respectively.

￼
fileselect.multiple_files.command (Current: ["xterm", "-e", "vifm", "--choosefiles={}"])
Command (and arguments) to use for selecting multiple files in forms. The command should write the selected file paths to the specified file or to stdout, separated by newlines.
The following placeholders are defined:
* `{}`: Filename of the file to be written to. If not contained in any argument, the
standard output of the command is read instead.

￼
fileselect.single_file.command (Current: ["xterm", "-e", "vifm", "--choosefile={}"])
Command (and arguments) to use for selecting a single file in forms. The command should write the selected file path to the specified file or stdout.
The following placeholders are defined:
* `{}`: Filename of the file to be written to. If not contained in any argument, the
standard output of the command is read instead.￼`

I am running Xmonad as my window manager and I am unable to open a file picker terminal of Vifm. Instead the screen blinks for a second and then nothing happens.

Any ideas?

**Comment by The-Compiler** [comment]
vifm uses `--choose-file` and `--choose-files`. Consider using the values in the `:set` completion.

**Comment by wgmayer0** [comment]
Thank you! And thank you for adding this feature - it's a huge time saver!
