### ISSUE TITLE
Scroll Position Is Lost with Xmonad

### ISSUE THREAD

**Issue by wgmayer0** [qutebrowser/qutebrowser#6495]
**Version info**:

qutebrowser v2.2.2
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: no
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QStyleSheetStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.1.1
Platform: Linux-5.10.39-1-lts-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/wgm/.cache/qutebrowser
config: /home/wgm/.config/qutebrowser
data: /home/wgm/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/wgm/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:28

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Qutebrowser loses the scroll position of a page when using Xmonad in fullscreen and switching back to Qutebrowser.

I tested this in Firefox and found that the scroll position remains. 

**How to reproduce**

Install Xmonad
Run Xmonad on default settings
Start a Qutebrowser instance
Go to a webpage that can scroll
Scroll down on the webpage and note where the scroll is
Start an instance of ANY application
Make that application the focused application on the left side of the screen 
Press mod key + h to move the focused application into full screen
Switch back to the Qutebrowser instance by pressing mod key + shift + k or j
Notice that the position has been lost and now the window is scrolled to the top

**Comment by The-Compiler** [comment]
Can you check whether `:bind <Tab> nop` changes anything?

**Comment by wgmayer0** [comment]
> Can you check whether `:bind <Tab> nop` changes anything?

Nope - same behavior

**Comment by wgmayer0** [comment]
Were you able to recreate this by chance?

**Comment by wgmayer0** [comment]
Closed on accident I have not solved this yet

**Comment by The-Compiler** [comment]
I have this a quick try, but don't really understand your reproduction instructions. You say:

> Press mod key + h to move the focused application into full screen

But Mod+h with the Xmonad default bindings just moves the split to the left - i.e. makes the application on the left smaller and qutebrowser on the right bigger.

**Comment by wgmayer0** [comment]
Ok yeah sorry That step should be mod + l. Once the left side application takes up the full screen then use mod h to show Qutebrowser again and you see that the scroll position is reset to the top of the page again

**Comment by The-Compiler** [comment]
Works fine for me on https://heise.de. You might need to be more specific than "Go to a webpage that can scroll" if that works for you too.

Also, could you try to reproduce with either Chromium or KDE Falkon (or ideally both)?

**Comment by wgmayer0** [comment]
What about trying a YouTube.com search then scrolling midway through the page

I’ll try this on chrome/KDE Fallon

**Comment by wgmayer0** [comment]
Yes I do have the issue on Chromium so I’m guessing this is a WebKit issue and not resolvable

**Comment by The-Compiler** [comment]
Not WebKit, but Chromium and/or Blink (their fork of WebKit). But indeed, nothing qutebrowser can do about it.

I don't know Xmonad, but it might have a way to fullscreen a window without affecting the size of other windows.

**Comment by wgmayer0** [comment]
Copy that! I’ll look into it. Thanks for your help!
