### ISSUE TITLE
Too many crashes

### ISSUE THREAD

**Issue by python-clojure** [qutebrowser/qutebrowser#6502]
I have installed the latest version of qutebrowser. There are too many crashes. I open the browser, it loads the start page, then quits itself. After the crash, I can't even type a single line in the crash report. It quits. It is being very frequent. It has been happening in previous versions as well but not like this. I was able to use it for at least 30 minutes. But now it is very frequent

OS: Windows 10 (20H2) (stable)
Python version: 3.9.5

Installed using the installer (not as standalone software)
Installed yesterday

No changes have been done to the system nor have I installed any Windows updates. I have only been using VSCode, IntelliJ Idea Ultimate, Brave browser, explorer, VLC, Zoom all day long. No other app was neither opened nor installed.

Python version remains the same as the version before the installation i.e. the version 3.9.5 was installed before the installation of the latest version of qutebrowser.

No changes to the installation directory of qutebrowser were done. It was not even opened.

I tried reinstalling the same latest version of qutebrowser but no luck.

Please resolve this issue. I can't even stay on the browser for more than a minute. It crashes so frequently.

**Comment by The-Compiler** [comment]
Does setting `qt.workarounds.remove_service_workers` and restarting change anything?

**Comment by markstos** [comment]
@python-clojure Could you keep a memory monitor utility open while launching and running `qutebrowser` to confirm there is not memory pressure when `qutebrowser` crashes?

**Comment by python-clojure** [comment]
> Does setting `qt.workarounds.remove_service_workers` and restarting change anything?

This worked. Thanks a lot. Could you please say why this worked though?

**Comment by The-Compiler** [comment]
It's a bug in QtWebEngine (most likely) and/or Chromium, which causes crashes when data is read from a corrupt service worker cache directory (e.g. after an unclean shutdown). See #5634.
