### ISSUE TITLE
Coupled activity status in picom

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6506]
qutebrowser v2.2.2
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

Used with temp-dir aswell as picom default config

When you have several windows of qutebrowser open, picom will linked their activity status. So for example the inactive-opacity of all qutebrowser windows gets linked so if you focus one of them, all get opaque and if you focus neither of them they all become opacity. Only the focused qutebrowser window should get opaque.

### Reproduce
Use default picom config and default qutebrowser config. Open a new qutebrowser page with gD, and open another program to test the focus. This does not happen if you open two instances of qutebrowser from two different terminals. 
I havent been able to see if you open several instances of qutebrowser with say dmenu in temp-dir, but with my config it still has the same problem when opening with dmenu.

**Comment by The-Compiler** [comment]
With the default picom config, there's no distinction between active/inactive windows, right?

I've just tried with `picom --config /dev/null -i 0.5` (making inactive windows clearly opaque), and can't reproduce:

![image](https://user-images.githubusercontent.com/625793/120462458-416de380-c39b-11eb-87d1-4e57db4948ad.png)

What version of picom are you using, with what window manager? Can you check if you can reproduce with Chromium and/or KDE Falkon?

**Comment by premell** [comment]
Hmm so apparently I cannot reproduce it when using "picom --config /dev/null -i 0.5". I used the default config, which can be found in "/etc/xdg/picom.conf.example".  

> With the default picom config, there's no distinction between active/inactive windows, right?
Yes there is, the default config have
`inactive-opacity = 0.8`

**Comment by The-Compiler** [comment]
I can reproduce with `/usr/share/doc/picom/picom.conf.example` on Arch. However, I can reproduce the same issue with Falkon, Firefox and Gedit (text editor), so this doesn't seem to be a qutebrowser thing at all.

**Comment by crypticC0der** [comment]
the issue is `detect-client-leader = true;`
in your picom config
it was in mine for a while and i only just noticed that it was the culprit
