### ISSUE TITLE
Vim mode in text-area

### ISSUE THREAD

**Issue by python-clojure** [qutebrowser/qutebrowser#6515]
There is an extension for Brave(Chrome) calles [wasavi](https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe) which enables vim mode in text-area. So, is it possible to emulate vim in any of the text areas inside this browser?

**Comment by The-Compiler** [comment]
Duplicate of #827

**Comment by python-clojure** [comment]
Oh sorry for that. Thanks anyway.
