### ISSUE TITLE
Tab Groups

### ISSUE THREAD

**Issue by JackofSpades707** [qutebrowser/qutebrowser#6521]
You may be interested in taking #5671 a step further and doing something like this.
![image](https://user-images.githubusercontent.com/17239750/120927241-04ed0100-c695-11eb-8992-343fb79f1679.png)
![image](https://user-images.githubusercontent.com/17239750/120927253-1504e080-c695-11eb-9f0b-d3a21fa49bf6.png)

I'm not sure what this would look like in its best implementation with a focus on keyboard-driven control, but I absolutely love this feature

Browser: Chrome

**Comment by The-Compiler** [comment]
#5671 is entirely unrelated, but see #49.
