### ISSUE TITLE
Right click / context menu sometimes stops working / showing up

### ISSUE THREAD

**Issue by andys8** [qutebrowser/qutebrowser#6524]
**Version info**:

```
qutebrowser v2.2.1
Git commit:
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4
```

**Description**

Sometimes the right click stops working and doesn't show the context menu anymore.

**How to reproduce**

I don't know and I'm already sorry for creating a ticket without a clear idea, how this could be dealt with. It just happens sometimes that the right click with the mouse isn't working anymore in qutebrowser. I'm not sure if there is any chance where this is an issue with the OS (arch/manjaro) or the window manager (Xmonad). Right click is still working at the same time in other GUI programs. It doesn't happen after closing and starting qutebrowser again.

Is there a way where I could help debug this? I thought about a screencast showing the issue, but it would not be very helpful.

**Comment by andys8** [comment]
I'm closing this one again. I haven't found a clear way how to reproduce it, but I think it still might be more likely to be caused by Xmonad an this part of the configuration

```haskell
myManageHook = composeAll
  [ resource =? "desktop_window" --> doIgnore
  , className =? "Chromium-browser" --> doShift (show WorkspaceWWW)
  , className =? "Code" --> doShift (show WorkspaceWork)
  , className =? "Rambox" --> doShift (show WorkspaceChat)
  , className =? "Screenruler" --> doFloat
  , className =? "Slack" --> doShift (show WorkspaceChat)
  , className =? "Zenity" --> doFloat
  , className =? "jetbrains-idea" --> doShift (show WorkspaceWork)
  , className =? "jetbrains-idea-ce" --> doShift (show WorkspaceWork)
  , className =? "qutebrowser" --> doShift (show WorkspaceWWW)
  , title =? "Battery Warning" --> doFloat
  ]
```

**Comment by The-Compiler** [comment]
Pretty sure this isn't a qutebrowser issue, the context menu is entirely handled by the underlying Qt.

Might be this? [[QTBUG-93561] Wrong context menu position when attaching external screen - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-93561)

**Comment by andys8** [comment]
The link issue could be the reason. I've also a setup with two monitors with different screensizes and un-/connecting the second monitor quite often. Thanks for the hint. It's unresolved, but I'll follow the ticket then.
