### ISSUE TITLE
Possible issue with D-Bus method call handling

### ISSUE THREAD

**Issue by AckslD** [qutebrowser/qutebrowser#6525]
**Version info**:
qutebrowser v2.2.1
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 3.0.0
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.4.4
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: 2.8.335 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.1.0
Platform: Linux-5.12.4-arch1-2-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:
Not applicable

**Description**
I'm having issues with opening links through the evolution mail client.

When clicking links in emails or links in the app itself (for example the evolution website in the about window) I just get a new window of qutebrowser at my starting page and not the page of the link.

Normally links open in the existing running qutebrowser session. For example if I do:
```
xdg-open https://wiki.gnome.org/Apps/Evolution/
```
the page opens correctly in the current session.

I asked in the email list of evolution [here](https://mail.gnome.org/archives/evolution-list/2021-June/msg00018.html) and got a response that:

> Hi,that feels really odd. Evolution relies on gtk+ with this, namely on
> gtk_show_uri(), which does all the magics behind. Looking there, the
> main part just calls g_app_info_launch_default_for_uri(), which comes
> from glib; it searches for the default scheme handler and, well,
> launches it. If I understand the glib code correctly, then it calls
> a D-Bus method `Open` on an `org.freedesktop.Application` interface for
> the scheme handler. I'd guess that your browser has a bug in the D-Bus
> method call handling, but it's truly a wild guess.

Could it be an issue with qutebrowsers D-Bus handling?

**How to reproduce**
See above

**Comment by The-Compiler** [comment]
Works fine for me. Could you run `dbus-monitor` and check what you see when clicking the link? I get this:

```
signal time=1623083579.742273 sender=:1.984 -> destination=(null destination) serial=278 path=/org/gtk/gio/DesktopAppInfo; interface=org.gtk.gio.DesktopAppInfo; member=Launched
   array of bytes "/usr/share/applications/org.qutebrowser.qutebrowser.desktop" + \0
   string ""
   int64 50476
   array [
      string "http://wiki.gnome.org/Apps/Evolution/"
   ]
   array [
      dict entry(
         string "startup-id"
         variant             string "evolution-49093-aragog-qutebrowser-6_TIME18545325"
      )
      dict entry(
         string "origin-prgname"
         variant             array of bytes "evolution" + \0
      )
      dict entry(
         string "origin-pid"
         variant             int64 49093
      )
   ]
```

as well as three unrelated `ca.desrt.dconf.Writer` calls. In other words, no `Open` call on `org.freedesktop.Application` at all.

**Comment by The-Compiler** [comment]
Why do you have a custom `/home/axel/.local/share/applications/qutebrowser.desktop` (rather than the system-wide `/usr/share/applications/org.qutebrowser.qutebrowser.desktop`) and what are its contents?

**Comment by AckslD** [comment]
Woops, yep that's indeed the issue. I think I added that a long time ago when I couldn't find the correct qutebrowser desktop file. Sorry about that and thanks a lot for the help!
