### ISSUE TITLE
Shortcut for fullscreen 

### ISSUE THREAD

**Issue by the-anonymous-raven** [qutebrowser/qutebrowser#6527]
Unlike other browsers where pressing 'f' on a playing video turns it into fullscreen, the same isn't possible on qutebrowser's normal mode because of the mapping of 'f' to other function.
If possible, I request you to have a shortcut for the fullscreen mode.
It is pretty handy rather than going through the links and finding which one is the fullscreen mode(which sometimes isn't visible when video loses focus).

**Comment by The-Compiler** [comment]
I don't think there's an universal way for a browser to tell the website to fullscreen an element. There's `:fullscreen` (`<F11>`) but that likely won't do what you want. However, you can press `f` in insert mode.
