### ISSUE TITLE
png cheatsheet without bottom-down cut

### ISSUE THREAD

**Issue by OrionRandD** [qutebrowser/qutebrowser#6529]
I need a cheatsheet without the bottom-down cut as this one
qute://help/img/cheatsheet-big.png
Also, if you have moved to liberachat IRC,
This one needs to be updated.
Thx.

**Comment by The-Compiler** [comment]
What's a "bottom-down cut"?

The cheatsheet was updated in 7961cf73553847ea265a388b736fffac77dae66a already.

**Comment by OrionRandD** [comment]
On Tue, Jun 08, 2021 at 07:36:35AM -0700, Florian Bruhin wrote:
>    What's a "bottom-down cut"?

In the png cheatsheet the words are cut in the down right corner and it
is not possible to see what is written there...

**Comment by The-Compiler** [comment]
Can you show a screenshot? I don't see anything cut off in https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/img/cheatsheet-big.png.

**Comment by OrionRandD** [comment]
On Tue, Jun 08, 2021 at 07:36:35AM -0700, Florian Bruhin wrote:
>    What's a "bottom-down cut"?
> 

thx
