### ISSUE TITLE
Reduced motion support

### ISSUE THREAD

**Issue by Arteneko** [qutebrowser/qutebrowser#6530]
On a linux system (arch-linux latest, GTK-3 configured with `gtk-enable-animations=0`, firefox properly handling it), motion reduction doesn't seem to be handled by qutebrowser.

Is there an undocumented setting or a TODO for this?

**Comment by The-Compiler** [comment]
I can't test right now, but does starting with `--temp-basedir --qt-flag force-prefers-reduced-motion` help?

**Comment by Arteneko** [comment]
It did by going through the CLI indeed.

I used the flag in the configuration setting `qt.args` to keep it between reboots in my main profile, and it does the trick well.

But, would it be thinkable to have a dedicated explicit setting for that ? It would make enabling this kind of accessibility feature more user-friendly (especially the "finding it" part.)

**Comment by The-Compiler** [comment]
After digging into the code a bit, it looks like reading of the GTK system-wide preference is tied closely to Chromium's GTK UI, which is why it doesn't work in QtWebEngine.

I added a setting since it was straightforward to do so, based on the commandline argument. With the test I found out that reading the system-wide preference on Windows works actually, because that's implemented directly in the more low-level animation layer for whatever reason :smile:

**Comment by webknjaz** [comment]
I think this stopped working over time: running `qutebrowser --target=private-window --temp-basedir --qt-flag=force-prefers-reduced-animation https://webkit.org/blog-files/prefers-reduced-motion/prm.htm` doesn't result in stopped animations and reports "no preference or unsupported".

FTR, I haven't been able to make it work in Chrome through the CLI flag or the user-level configs for all GTK versions and KDE/Qt either — only enabling emulation via DevTools has effect, which doesn't persist for obvious reasons.

**Comment by The-Compiler** [comment]
This never worked because the flag was always named `--force-prefers-reduced-motion`.  I'd suggest you use the `content.prefers_reduced_motion` setting in qutebrowser (which [has automated tests](https://github.com/qutebrowser/qutebrowser/blob/7e3df43463d16815e8d29fee1b11489de688dee9/tests/end2end/test_invocations.py#L837-L857)) instead of hand-rolling things.

**Comment by webknjaz** [comment]
Oh, you're right, thanks!
Looks like this was the case of situational blindness on my part: it seems like I re-typed the CLI flag from https://stackoverflow.com/a/79465803/595220 incorrectly and then kept copying the wrong name to my other experiments (despite checking https://github.com/qutebrowser/qutebrowser/commit/96149c7e28e41a2d65464fee81b364b3f2474e64#diff-5af78548acae464212bdfca95aaf44505b28a631ed754e56f5600b32400b6b9fR339).

`qutebrowser --target=private-window --temp-basedir --qt-flag=force-prefers-reduced-motion https://webkit.org/blog-files/prefers-reduced-motion/prm.htm` does indeed work as it should.

And this correction helped my fix the Chrome command too, which confirmed that it does indeed work there as well: `google-chrome-stable --data-dir=/tmp/xxx --incognito --force-prefers-reduced-motion https://webkit.org/blog-files/prefers-reduced-motion/prm.htm`.

---

On a related note, GTK-4 needs a `gsettings get org.gnome.desktop.interface enable-animations
false` and it can be checked with `gsettings get org.gnome.desktop.interface enable-animations` or from Python (which allows having callbacks and getting the setting updates immediately):
```pycon
Python 3.13.9 (main, Dec 16 2025, 09:13:08) [GCC 14.3.1 20250801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi import require_version
>>> from gi.repository import Gio
>>> require_version('Gio', '2.0')
>>> ui_settings = Gio.Settings.new('org.gnome.desktop.interface')
>>> color_scheme = ui_settings.get_value('color-scheme').get_string()
>>> animations_enabled = ui_settings.get_value('enable-animations').get_boolean()
>>> print(f'{animations_enabled=} {color_scheme=}')
animations_enabled=False color_scheme='prefer-dark'
>>>
```

Not sure if it's feasible but it should be possible to detect this at least at startup.

For KDE, the setting to look for is in the config:
```ini
# ~/.config/kdeglobals
[KDE]
# Animation speed Instant should trigger `prefers-reduced-motion` in CSS
AnimationDurationFactor=0
```

```console
$ kreadconfig6 --key AnimationDurationFactor                 
0
```

I don't have KDE bindings to test locally but https://gist.github.com/raphant/991d33b11877ab177dbf6ab8e72d10b3 suggests it should be possible to do so (although calling this CLI or reading with configparser seems more straightforward).
