### ISSUE TITLE
Sign-in to google freezes indefinitely when 2FA (using security key) is enabled

### ISSUE THREAD

**Issue by EnderCrypt** [qutebrowser/qutebrowser#6544]
**Version info**:
qutebrowser v2.2.2
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
when attempting to sign in to Google.com, with 2FA authentication enable (specifically "Security Key") google will automatically assume you want to sign in using it (every time, without asking you) and attempt it

on other browsers (in my case i tested on Brave browser) you'll get a popup saying something probably along the lines of "_this device does not support security key login_" and google will proceed to let you choose which 2FA method to use

on QuteBrowser no popup appears, and the login screen stays "loading" (pictured below) forever with no way of telling it to abort
![Untitled](https://user-images.githubusercontent.com/5500996/121790703-3d836200-cbe2-11eb-9ce5-35c051f1538a.png)

interestingly, out of about 20-30 tries, the login did actually succeed in failing once, and let me choose another method of authentication, this was on _--temp-basedir_ however repeated tests have not been successful at making this happen again

**How to reproduce**
1. sign in to google.com (do this on another device and browser, not qutebrowser)
2. enable 2FA if not already on
3. enable "security key" (NOTICE: there does **NOT** seem to be a way of disabling this once you enabled it, so please keep that in mind, perhaps use a throwaway account if possible)
4. open QuteBrowser and navigate to google.com
5. attempt to login

**Comment by The-Compiler** [comment]
Could you please try with another QtWebEngine browser such as KDE Falkon?

**Comment by EnderCrypt** [comment]
unlike on QuteBrowser, on KDE Falkon, the moment i typed my email and pressed enter i get 

**Couldn’t sign you in**
_This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en)
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in._

are there any known workarounds?

**Comment by The-Compiler** [comment]
Ah, sorry, I forgot about that...

Please go to Preferences > Other > User Agent Manager > Add, and for the domain `accounts.google.com` set the user agent to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.144 Safari/537.36 Edg/87.0.4280.144`.

It's a stupid check from Google's side, qutebrowser has an equivalent workaround built in.

**Comment by EnderCrypt** [comment]
oh yes, i was able to start the login process now
Falkon seems to suffer from the same issue as QuteBrowser with "Complete sign-in using your security key" being shown indefinetly

small update regarding qutebrowser: i did actually succesfully login to google using qutebrowser, its just i had to repeat the login attempt multiple times and with some luck, after 10-20 minutes it _might_ cancel the security key login attempt and allow me to choose authentication method

**Comment by The-Compiler** [comment]
It's a shot in the dark, but can you check whether setting the UA to `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0` instead changes anything?

If not, I'm afraid there's likely little that can be done - it's clearly not a qutebrowser issue, and both QtWebEngine and Google probably aren't going to care much about it (the former because Google blocks QtWebEngine from logging in outright because Google, and the latter... well... because Google).

**Comment by EnderCrypt** [comment]
the login process starts successfully with either of these useragents is set, its just the security key part still fails

**Comment by The-Compiler** [comment]
Nothing I qutebrowser can do about it then I'm afraid. Looks like some sort of problem on Google's side to me, or perhaps in QtWebEngine - but given that the login doesn't work at all without workarounds, I doubt reporting it there will change anything. Sorry I don't have a better answer :disappointed:

**Comment by lsmith130** [comment]
For anyone else finding this thread, I was able to get the Google 2-Step Verification page to stop spinning by just touching my security key. This reliably made it fail immediately and give me the option to use another 2FA method like a security key on another device.
