### ISSUE TITLE
Microsoft Teams meeting links don't open the meeting in Teams

### ISSUE THREAD

**Issue by robcsi** [qutebrowser/qutebrowser#6546]
**Version info**:
qutebrowser v2.2.3
Git commit: 
Backend: QtWebEngine 5.15.4, Chromium 87.0.4280.144
Qt: 5.15.2

**Description**
When clicking on Teams meeting links in MS Outlook in the browser, the links don't go to open the Teams application to join the meeting. This works fine in other browsers: Firefox, Chrome, etc.

**How to reproduce**
Open Outlook in the browser and click on a meeting link, or copy a meeting link to QuteBrowser, or press the 'Open your Teams app' after the meeting link has been clicked.
Nothing happens, the Teams app is not started with connection to the meeting.

**Comment by The-Compiler** [comment]
You'll need to do something like `:set -u teams.microsoft.com content.unknown_url_scheme_policy allow-all` so that the website is allowed to open external applications.

IIRC Chrome will open a dialog window asking for confirmation in that case - unfortunately, QtWebEngine doesn't support doing so.
