### ISSUE TITLE
Searching for word takes you to top of page

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6550]
qutebrowser v2.2.3
Git commit:
Backend: QtWebEngine 5.15.4, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

A few months ago I reported an error where searching for a term would take you to the top of the page. However at the time I was unable to triangulate the problem. I think I found it now though, when using `statusbar.show global: always`, the search works as intended. However when you use `statusbar.show global: in-mode` it takes you to the top of the page instead, even if a match is found. 

I tested with this page https://en.wikipedia.org/wiki/CD_Projekt and searched for "Categories"

**Comment by The-Compiler** [comment]
I assume this isn't actually related to the search, but also happens when you press `:` and esc?

**Comment by premell** [comment]
I just noticed it while using the search but yes, using escape and pressing `:` also reproduces the problem. But are you able to reproduce the problem? So it is something with `statusbar.show global: in-mode`?

**Comment by The-Compiler** [comment]
Indeed, see #2236
