### ISSUE TITLE
When tab-give a pinned tab, have it be pinned in the new window.

### ISSUE THREAD

**Issue by ImmanuelHaffner** [qutebrowser/qutebrowser#6553]
It's allowed to `tab-give` a pinned tab. However, the tab will not be pinned in the window receiving the tab.  Is this intended behavior?  I favor to keep the tab pinned even after a `tab-give`.

**Comment by The-Compiler** [comment]
I don't think it's intended - there are various things which aren't being preserved right now, unfortunately. I'm merging this into #5404, as the two are very similar.
