### ISSUE TITLE
Odd resizing issue on Sway

### ISSUE THREAD

**Issue by TJTorola** [qutebrowser/qutebrowser#6556]
**Version info**:
qutebrowser v2.2.3
Git commit: 
Backend: QtWebEngine 5.15.4, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: no
jinja2: 3.0.1
pygments: no
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 21.1.2
Platform: Linux-5.12.11-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/tjtorola/.cache/qutebrowser
config: /home/tjtorola/.config/qutebrowser
data: /home/tjtorola/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:21

**Does the bug happen if you start with `--temp-basedir`?**: No

**Description**
Qutebrowser's window slides out of view in a particular case when using it in Sway.

**How to reproduce**
Open Qutebrowser in sway
Put the window into stack mode
Open some other application in the stack
Close that application

After doing that, the content of sway is transformed down a bit, to the point that I cannot read what is being typed as input.

Not entirely sure if this is an issue with qutebrowser or sway, but I haven't been able to repro it with any other applications.

**Comment by The-Compiler** [comment]
Could you try with another QtWebEngine-based browser, such as [KDE Falkon](https://www.falkon.org/)?

**Comment by TJTorola** [comment]
Nice yeah, same issue with Falkon

**Comment by The-Compiler** [comment]
I can reproduce this with any Qt application, e.g. Wireshark, Virtualbox, Telegram-Desktop, Zeal, etc.

So probably a bug in either sway or Qt's Wayland integration - the closest I could find is this: https://github.com/swaywm/sway/issues/4604

**Comment by TJTorola** [comment]
Ok, thanks for looking into it. I'll start an issue over there.
