### ISSUE TITLE
`qute-bitwarden` hard-codes call to `rofi -dmenu` instead of using the specified `--dmenu-invocation`

### ISSUE THREAD

**Issue by 1ace** [qutebrowser/qutebrowser#6558]
**Version info**:

```
qutebrowser v2.2.3
Git commit: 
Backend: QtWebEngine 5.15.4, Chromium 87.0.4280.144
Qt: 5.15.2
```
But as linked below, this is still the case in `master` at the time of writing this (fc5aae8a718d449f337137d2820bfe0914903168).

**Does the bug happen if you start with `--temp-basedir`?**:
Yes, this is unrelated.

**Description**

The `qute-bitwarden` userscript [hard-codes a call to `rofi -dmenu`](https://github.com/qutebrowser/qutebrowser/blob/fc5aae8a718d449f337137d2820bfe0914903168/misc/userscripts/qute-bitwarden#L103) instead of using [the `--dmenu-invocation` argument specified](https://github.com/qutebrowser/qutebrowser/blob/fc5aae8a718d449f337137d2820bfe0914903168/misc/userscripts/qute-bitwarden#L63). This results in the script crashing when `rofi` is unavailable, which likely common on wayland systems.

**How to reproduce**

Just look at the code? :stuck_out_tongue_winking_eye:
https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-bitwarden#L103

More seriously, running the script on a system without `rofi` installed will trigger the crash, and once the code is fixed, passing `--dmenu-invocation 'wofi --dmenu'` for instance on a system with `wofi` (the wayland rewrite of the x11 `rofi`) installed will no longer crash.

**Workaround**
For now, my workaround is to edit the script and hard-code `wofi` and its flags instead (in particular, long options take two `--` dashes instead of just one like `rofi` does), but I have to re-do every time there's a `qutebrowser` update and it's annoying :sweat_smile:

**Comment by The-Compiler** [comment]
cc @JonnyHaystack @typerslow

**Comment by JonnyHaystack** [comment]
Hmm, can't remember if there was a specific reason why I did that.. I guess it might as well be the changed to the usual way

**Comment by The-Compiler** [comment]
@1ace or @JonnyHaystack, do you want to open a PR for this by any chance? :slightly_smiling_face:

**Comment by carlosgarciafm** [comment]
Do you mind if I open a PR myself?

**Comment by The-Compiler** [comment]
@carlosgarciafm please go ahead!
