### ISSUE TITLE
Spoilers not working in dark mode

### ISSUE THREAD

**Issue by keeganjk** [qutebrowser/qutebrowser#6565]
I currently use the `lightness-hsl` dark mode algorithm with qutebrowser—I find this one to work the best and be most reliable. However, spoiler tags which are intended to hide information seem to not work—whereas there is supposed to be by default some black text with a black background which will only toggle the text color to something readable upon interfacing with it, it will display rather with a black background and a readable white text (at least, this is my understanding of how it works).

Here is an image of what a sample "spoiler" may look like on my qutebrowser configuration:
![2021-06-20_11-58-31](https://user-images.githubusercontent.com/24554125/122680863-6d70cd80-d1bf-11eb-8a79-9fa32bc53c82.png)

And this is what it looks like on Chromium:
![2021-06-20_12-00-21](https://user-images.githubusercontent.com/24554125/122680867-706bbe00-d1bf-11eb-826c-b7bfdb598756.png)

(If it is important, the code being used for this particular spoiler is the following:

```css
.spoiler, .spoiler2{ 
  color: black; 
  background-color:black;
}

.spoiler:hover{
  color: white;
  }

.spoiler2:hover { 
  background-color:white; 
  }
```

```html
<span class="spoiler" >test</span>

<p>Then when hovered over</p>

<span class="spoiler2"> other test </span>
```

)

I think the ideal solution to this would be to check whether the CSS foreground and backgrounds are the same in dark modes, and if so, adjust them to the same value, rather than trying to change one and not the other or otherwise changing them in a way that makes it readable whereas it would not previously have been.

**Comment by The-Compiler** [comment]
The underlying dark mode is coming from Chromium. You should be able to disable it in CSS using the [`color-scheme` selector](https://web.dev/color-scheme/) I think.
