### ISSUE TITLE
Deduplicate subdomains from host-blocking lists?

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6570]
> We could even optimize blocked hosts list (after download) in a way that we exclude hosts which are already blocked by some other line. e.g remove `foo.bar.example.com`, because it's already blocked by `bar.example.com`. Tho, I think that this optimization wouldn't help that much in performance and just creates additional maintenance burden.

_Originally posted by @4nd3r in https://github.com/qutebrowser/qutebrowser/discussions/6340#discussioncomment-558488_

Potential follow up to #6372, would be interesting to see what the performance gains would really be with a real block list.

**Comment by 4nd3r** [comment]
Did "quick" test, which removed 26324 of 80472 hosts in Steven Black's list.

But it took 394 seconds to reduce the list by ~32% (on i7-6700K @ 4.2GHz), so bit slow 😞 Probably can be done much faster.

Optimizer itself is simple:

```python
import time

hosts = []
handle = open('/home/ander/.local/share/qutebrowser/blocked-hosts', 'r')
for line in handle:
    hosts.append(line.strip())
handle.close()
hosts_before = len(hosts)
time_start = time.time()
host_counter = 0
for host in hosts:
    host_counter += 1
    subs = [h for h in hosts if h.endswith(f'.{host}')]
    if not subs:
        continue
    for sub in subs:
        hosts.remove(sub)
        hosts_after = len(hosts)
        hosts_removed = hosts_before - hosts_after
        print(f'[{host_counter}/{hosts_removed}/{hosts_after}/{hosts_before}] {sub} matched by {host}')
time_total = round(time.time() - time_start)
print(f'\n{hosts_removed} of {hosts_before} hosts removed in {time_total} seconds')
```

Questions are:
* How big is current performance impact of checking every request?
* Do we gain anything by this kind of optimization?

I'll try to do some measuring.

**Comment by The-Compiler** [comment]
Yeah, I'm pretty sure there's a lot of room to make the optimization faster - your code iterates over every host for every host, so its runtime is going to grow quadratic (`O(n²)`) with the number of hosts.

The simplest possibly faster approach coming to mind is:

- Add all hosts to a set
- Iterate over all hosts, in the set
  - For every host, use `widen_hostnames` again
  - If any of the widened hostnames is in the set, add it to a second one
- Remove all hosts in the second set from the first

I bet there's an even faster way using tries or so, but maybe this would suffice already, and not be too complex.

**Comment by 4nd3r** [comment]
Thanks for the tips, I did a quick hack...

```python
from typing import Iterable

def widened_hostnames(hostname: str) -> Iterable[str]:
    """A generator for widening string hostnames.

    Ex: a.c.foo -> [a.c.foo, c.foo, foo]"""
    while hostname:
        yield hostname
        hostname = hostname.partition(".")[-1]

hosts = set()
handle = open('/home/ander/.local/share/qutebrowser/blocked-hosts', 'r')
for line in handle:
    hosts.add(line.strip())
handle.close()
before = len(hosts)
found = set()
for host in hosts:
    for h in widened_hostnames(host):
        if h != host and h in hosts:
            found.add(host)
optimized = hosts - found
after = len(optimized)
removed = before - after
print(f'{removed} of {before} hosts removed')
```

Takes about 0,1 seconds and removes 31623 of 80472 hosts. More than my original quick hack, but that's not important right now.

Okay, we can make this optimization fast enough. Good.

Now let's imagine we have webpage, that makes 1844 requests:

```
ander@limukas:~/.../qutebrowser-hostblocking-perf$ python3 optimize.py 
80472 blocked hosts: 314 of 1844 URLs blocked in 0.005 seconds
48849 blocked hosts: 314 of 1844 URLs blocked in 0.005 seconds
```

What about 18440 requests per single webpage? This might happen, right?

```
ander@limukas:~/.../qutebrowser-hostblocking-perf$ python3 optimize.py 
80472 blocked hosts: 3140 of 18440 URLs blocked in 0.051 seconds
48849 blocked hosts: 3140 of 18440 URLs blocked in 0.053 seconds
```

1844 URLs were logged from 15 most visited sites from my history and then I just iterated over them using original and deduplicated host-blocking list. For checking I used something similar what happens inside `_is_blocked`, but simplified:

```python
def is_blocked(url, blocked_hosts):
    host = url.host()
    return any(hostname in blocked_hosts for hostname in widened_hostnames(host))
```

 So, in the end, looks like there is no point deduplicating host-blocking lists.

**Comment by The-Compiler** [comment]
Right, probably not worth the trouble if those numbers are this similar. Another thing I'd be curious about before dismissing it entirely is memory usage. Could you install [Pympler](https://pythonhosted.org/Pympler/index.html) and the output of `asizeof.asizeof(hosts)` vs. `asizeof.asizeof(optimized)` if you don't mind?

**Comment by 4nd3r** [comment]
9985680 and 5552576 bytes.

**Comment by The-Compiler** [comment]
So that's 9.5 MB vs. 5.3 MB... Given that there's a glaring memory leak somewhere anyways (#1476), probably not a significant reduction either.

So, I'd say let's not do this. Thanks for having a look though!
