### ISSUE TITLE
vim and qutebrowser not working after update

### ISSUE THREAD

**Issue by Das-Sams** [qutebrowser/qutebrowser#6579]
I had a strange issue. After an update on my gentoo linux qutebrowser didn't render anything in it's window and my favourite editor vim did not work in xterms as long as qutebrowser was running. Deleting ~/.local/share/webkit solved the issue for me.
My actual versions are:
www-client/qutebrowser 2.2.2
dev-qt/qtwebengine 5.15.2_p20210421
app-editors/vim 8.2.0814-r100

**Comment by The-Compiler** [comment]
I doubt this is an issue with qutebrowser - it's probably something with the underlying QtWebEngine/Chromium or your system (or QtWebKit if you're using that). Since you can't reproduce it anymore now, there's nothing that can be done either way.

**Comment by Das-Sams** [comment]
I just wanted to post my solution in case someone else runs into this error as this might take some time to find out.
