### ISSUE TITLE
colors.webpage.preferred_color_scheme = "dark" doesn't always invert text colors.

### ISSUE THREAD

**Issue by smartlitchi** [qutebrowser/qutebrowser#6585]
**Version info**:
qutebrowser v2.3.0
Git commit:
Backend: QtWebEngine 5.15.5, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
It does with ``qutebrowser --temp-basedir --set colors.webpage.preferred_color_scheme "dark"``

**Description**
On certain webpages, forcing dark mode with ``colors.webpage.preferred_color_scheme = 'dark'`` only inverts the background and not the text, making the whole page illegible.

Here is an example : 

![image](https://user-images.githubusercontent.com/56811153/124693882-76acaa80-dee0-11eb-9dd1-719bab234cc3.png)

**How to reproduce**

[Link to the affected website](https://brianbuccola.com/how-to-build-and-install-st-suckless-simple-terminal-from-source-on-arch-linux/)

**Comment by The-Compiler** [comment]
Setting `colors.webpage.preferred_color_scheme` doesn't invert anything - it only asks the web page for a dark style, via the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media query.

For the website you linked to, there's no such dark style sheet served by the page, so here's what I get with `qutebrowser --temp-basedir --set colors.webpage.preferred_color_scheme "dark" https://brianbuccola.com/how-to-build-and-install-st-suckless-simple-terminal-from-source-on-arch-linux/`:

![image](https://user-images.githubusercontent.com/625793/124715735-97d2c280-df03-11eb-942b-1b01ed8327ae.png)

**Comment by smartlitchi** [comment]
I know what is happening, I built qt5-webengine from source to solve this issue #2912 and it put a dark background by default
