### ISSUE TITLE
Can't watch videos in Facebook

### ISSUE THREAD

**Issue by darrSonik** [qutebrowser/qutebrowser#6586]
**Version info**:
qutebrowser v2.3.0
Git commit: a55355eaa on HEAD (2021-06-28 17:29:52 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2
[Full Info - from the button in qute://version](https://paste.the-compiler.org/view/025e5a1f) 

**Does the bug happen if you start with `--temp-basedir`?**:
Yes. In fact, I deleted the folders for qutebrowser in `%APPDATA%/Local` and `%APPDATA%/Roaming` and reinstalled qutebrowser so that I get fresh start, yet the problem persists.

**Description:**
I can't watch videos in Facebook, other browsers are working fine. I installed qutebrowser using [chocolatey](https://chocolatey.org/).
I can watch YouTube videos via qutebrowser, but in Facebook, I keep getting "Sorry, we're having trouble playing this video."
Screenshot is given below:
![image](https://user-images.githubusercontent.com/34137568/124792338-bcb04f80-df6e-11eb-9d2a-ccec5c99e7c0.png)

I also have an Arch box and qutebrowser is working fine there. The problem exists only in Windows I guess.

**My System:**
Windows 10 Home Edition
Ryzen 5 3500U with Radeon Vega Mobile Gfx
16GB RAM
DirectX 12

**Comment by gadefox** [comment]
@The-Compiler : I upgrated Qt5 to Qt6 today and I suddenly can't open facebook videos. Any idea??

[qute://version](https://bpa.st/CD7ZE)
