### ISSUE TITLE
qute-keepass: UnboundLocalError: local variable 'kp' referenced before assignment

### ISSUE THREAD

**Issue by PRESFIL** [qutebrowser/qutebrowser#6592]
**Version info**:

```
qutebrowser v2.2.3
Git commit: 
Backend: QtWebEngine 5.15.4, Chromium 87.0.4280.144
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:

Extensions are disabled in this state.

**Description**

```
Standard error
There was an error opening the DB: 
Traceback (most recent call last):
  File "/usr/share/qutebrowser/userscripts/qute-keepass", line 261, in <module>
    sys.exit(run(arguments))
  File "/usr/share/qutebrowser/userscripts/qute-keepass", line 212, in run
    candidates = find_candidates(args, url_host)
  File "/usr/share/qutebrowser/userscripts/qute-keepass", line 182, in find_candidates
    return kp.find_entries(url="{}{}{}".format(".*", host, ".*"), regex=True)
UnboundLocalError: local variable 'kp' referenced before assignment
```

**How to reproduce**

1. Set cursor to input field
2. Switch to insert mode
3. Hit <C-i>
4. Enter password for keepass database
5. Wait

**Comment by The-Compiler** [comment]
Looks like the script didn't exit properly when `pykeepass` failed to open the database. It does now, though the issue with opening the database will probably still persist. Looks like there's no information from `pykeepass` about why this is happening...

If you remove the entire `try: ... except Exception as e: ...` block around `kp = pykeepass.PyKeePass(file_path, password=pw, keyfile=kf)` and replace it by just that line (dedented by one), that might tell you more about what's going wrong.

**Comment by PRESFIL** [comment]
Oh, that was fast. Thank you.

p.s. I couldn't reproduce it the second time, but I will know what to do
if I succeed. In general, pykeepass works very slowly (perhaps because without caching)...
