### ISSUE TITLE
qutebrowser does not save json file as json file

### ISSUE THREAD

**Issue by rohshall** [qutebrowser/qutebrowser#6602]
**Version info**:

qutebrowser v2.3.0
Git commit: a55355eaa on HEAD (2021-06-28 17:29:52 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.4
PyQt: 5.15.3

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.4.4
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: 2.8.335 (bundled)
sqlite: 3.33.0
QtNetwork SSL: Secure Transport, macOS 11.4

Style: QMacStyle
Platform plugin: cocoa
OpenGL: None
Platform: macOS-11.4-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 11.4, x86_64

Paths:
auto config: /Users/swadnerkar/Library/Preferences/qutebrowser
cache: /Users/swadnerkar/Library/Caches/qutebrowser
config: /Users/swadnerkar/.qutebrowser
data: /Users/swadnerkar/Library/Application Support/qutebrowser
runtime: /private/var/folders/4p/4j492myj55vfnt7z2z8sf22m0000gn/T/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 6 days, 3:35:31
**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When I save the json file from internet like: https://raw.githubusercontent.com/ljharb/json-file-plus/main/package.json
It says it is saving the json file, but it saves it as mhtml file: ~/Downloads/package.mhtml
**How to reproduce**
Just try saving any JSON file like: https://raw.githubusercontent.com/ljharb/json-file-plus/main/package.json

**Comment by toofar** [comment]
How are you downloading it? I'm assuming it is by opening the page in qutebrowser and running `:download`? That saves a proper json file for me. (Running `:download -m` yields an mhtml file as expected.)
Maybe a Mac problem but the logic to do just that is in qute (behind the -m|--mhtml flag for :download) so probably something else going on.

**Comment by ykahveci** [comment]
I think you right clicked the page and selected "Save page", correct?
That is the equivalent to the ":download -m" command which will download anything as a .mhtml file.

You can try manually typing in the ":download" command or just pressing the default key combination "gd" which will just download the current file in its default format. (Thus it will download an image as an image, a normal website as an html, a pdf as a pdf, etc.)

**Comment by rohshall** [comment]
Yes, you are right. I should have used `:download`. Closing it.

**Comment by rohshall** [comment]
Yes, you are right. I should have used `:download`. Closing it.
