### ISSUE TITLE
make hints.next_regexes also match <img alt="x"> text

### ISSUE THREAD

**Issue by xalexalex** [qutebrowser/qutebrowser#6631]
I'm coming across websites using images as `prev` and `next` links, such as [this](https://www.webpathology.com/image.asp?n=2&Case=763).

`hints.next_regexes` could also match the `alt` attribute of the `img` tag, which is usually set correctly (`<img alt="next">` in this case)

**Comment by The-Compiler** [comment]
Duplicate of #1434
