### ISSUE TITLE
Embedded Video playback from certain sites doesn't work on MacOS Big Sur

### ISSUE THREAD

**Issue by hunsakerbn** [qutebrowser/qutebrowser#6637]
**Version info**:

OS: MacOS 11.4
qutebrowser v2.3.0
Git commit: a55355eaa on HEAD (2021-06-28 17:29:52 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.4
PyQt: 5.15.3

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

I noticed this when trying to view our organization's videos posted on microsoft stream.  When clicking the play button, all I get is a spinning circle that doesn't ever seem to timeout.  It works fine on Linux/qutebrowser, but not on MacOS. The videos play correctly using Firefox, Safari and Chrome.

**How to reproduce**

I was unable to find a 'public' video on microsoft stream, but the video in the following link might illustrate the problem, although it gives me the following error in the video playback window (which is different behavior than described above): 

  The video playback was aborted due to a corruption problem or because the video used features your browser did not support (0x20400003)

The embedded video in the link illustrates the problem.

[example video](https://techcommunity.microsoft.com/t5/microsoft-stream-archive/welcome-to-microsoft-stream-s-blog/ba-p/285020)

**Comment by The-Compiler** [comment]
Prebuilt releases come without proprietary codec support. You'd unfortunately need to build Qt from source to get them.
