### ISSUE TITLE
Crash with segfault

### ISSUE THREAD

**Issue by algor512** [qutebrowser/qutebrowser#6642]
**Version info**:
qutebrowser v2.3.1
Git commit: ddcd11ff4 on master (2021-08-10 22:01:15 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

**Does the bug happen if you start with `--temp-basedir`?**:
No.

Crash with segfault when open some sites (vk.com feed, reddit).
It started to crash after I added `config.set('content.notifications.enabled', False)` in my config.py and disabled hinting in `.config/fontconfig/fonts.conf ` (but I don't know if it is related).

**How to reproduce**
Unfortunately, I cannot copy exact url since it crashes too fast (see gif). Maybe it is [https://www.reddit.com/r/qutebrowser/comments/lj52mc/keyboard_download_open_and_clear/](https://www.reddit.com/r/qutebrowser/comments/lj52mc/keyboard_download_open_and_clear/).

gif:
![qutebrowser_crash](https://user-images.githubusercontent.com/446041/129461836-5fef295a-9576-4397-a7fd-698c8755894d.gif)

debug log:
[debug_log.txt](https://github.com/qutebrowser/qutebrowser/files/6987277/debug_log.txt)

**Comment by toofar** [comment]
I assume the hinting config change is causing it to choke on the title of the google search box for some reason.
```
webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<input class="gLFyf gsfi" jsaction="paste:puy29d;" maxlength="2048" name="q" type="text" aria-autocomplete="both" aria-haspopup="false" autocapitalize="off" autocomplete="off" autocorrect="off" autofocus="" role="combobox" spellcheck="false" title="Поиск" value="" aria-label="Найти" data-ved="0ahUKEwjiivXfzrHyAhWFQvEDHQl3BWYQ39UDCAQ">'>
```
> title="Поиск"

Probably if you launch it with a less localized page (for example `qutebrowser about:blank`) it won't crash right away. I don't know anything about the interaction of webengine and fontconfig. You could try removing the custom font settings from you config.py to see if it is specific to them.

**Comment by algor512** [comment]
> You could try removing the custom font settings from you config.py to see if it is specific to them.
I tried, it doesn't help.

I removed qutebrowser venv directory and reinstalled it, now it seems it works well.

**Comment by The-Compiler** [comment]
This looks like an issue in one of the underlying libraries (Qt/QtWebEngine). nothing that can be done about it if you can't reproduce it anymore.
