### ISSUE TITLE
Pages behavior while showing statusbar

### ISSUE THREAD

**Issue by SamuelFe** [qutebrowser/qutebrowser#6647]
**I think a nice thing to have (I would like very much) is the option to make the status bar behave like it's overlaying the pages.**

The problem is: pages, *such as YouTube and Google*, adjusts it's own layout when status bar is changed from "not showing" to "showing" and vice-versa. It would be really good if showing the status bar were seamless by the web pages.

**Comment by The-Compiler** [comment]
See #1593 and also #5480.
