### ISSUE TITLE
Could you support show page num on statusbar.widgets

### ISSUE THREAD

**Issue by zdmgmail** [qutebrowser/qutebrowser#6653]
I hope show current page num and total page num , may be better than show Percentage, could you support this?

**Comment by The-Compiler** [comment]
What do you mean with "page num" exactly? How many screens full of content there are left?

**Comment by zdmgmail** [comment]
> What do you mean with "page num" exactly? How many screens full of content there are left?

just like read a book, current page num and total page num

**Comment by The-Compiler** [comment]
This isn't possible in the general sense. qutebrowser doesn't really know how much text is on the page, and usually text isn't laid out strictly linearly either. Maybe it'd be possible with some heuristics, but then this wouldn't be in the core, as it's quite complex and a niche thing (see #30).
