### ISSUE TITLE
RedHat help pages Crash

### ISSUE THREAD

**Issue by fridokus** [qutebrowser/qutebrowser#6654]
**Version info**:
qutebrowser v2.3.1
Git commit: 65af6b212 on master (2021-08-23 11:23:44 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
no

**Description**
Crash when I visit [`this page`](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_the_desktop_environment_in_rhel_8/accessing-the-desktop-remotely_using-the-desktop-environment-in-rhel-8)

**Comment by The-Compiler** [comment]
What does "crash" mean exactly? What happens precisely?

**Comment by fridokus** [comment]
This happen
![Screenshot from 2021-08-25 12-28-06](https://user-images.githubusercontent.com/16291842/130774631-144010f4-9d6b-4815-ad9f-9f223e374861.png)

**Comment by The-Compiler** [comment]
Does setting `qt.workarounds.remove_service_workers` followed by `:restart` help?

**Comment by fridokus** [comment]
No, same error still (status 139)

![Screenshot from 2021-08-25 15-34-00](https://user-images.githubusercontent.com/16291842/130800185-66b77fa2-7c52-46d6-aa00-de097ce9b324.png)

**Comment by fridokus** [comment]
But I have another issue where qutebrowser randomly crashes after a while, maybe this can help with that issue ;)

**Comment by The-Compiler** [comment]
Note that a renderer process crash and a browser crash are two different things. Either way, it's unlikely there's anything qutebrowser can do, as those happen in the underlying QtWebEngine/Chromium.

Given that it works fine with `--temp-basedir`, it must be related to something in your config, data or cache directories. Could you please move those away one by one to find out which one is to blame?

**Comment by The-Compiler** [comment]
@fridokus Any update on this? Note that the renderer process crashes are coming from the underlying QtWebEngine/Chromium, so there's likely little qutebrowser can do.

**Comment by fridokus** [comment]
I managed to wipe the computer where this happened so I'll close this until, or if,  I encounter this again
