### ISSUE TITLE
Some sites does not work properly with qutebrowser controls.

### ISSUE THREAD

**Issue by vacuumbeef** [qutebrowser/qutebrowser#6660]
**Version info**:
qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.5, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
Hello, on some sites it is imposible to use it with keyboard in qutebrowser. I was experiencing it for a long time and I thought maybe I can report it and sooner or later it will be fixed.

**How to reproduce**
1) https://nplus1.ru/ - I can't use keyboard until I press tab.
2) https://piped.kavin.rocks/watch?v=_OJKp4c5OLs - overall it works as it should, but on video pages controls are intercept by video player, so keys like j,k controls volume of the player.

**Comment by The-Compiler** [comment]
1. is an issue with the page. You can't scroll with the keyboard in Firefox or Chromium either until you click the page (or press tab).
2. is expected, as hjkl fake cursor key presses.

There are some ideas about an alternative approach to handle scrolling in #4715 which will fix this once I get around to picking it up again - also see #1354.
