### ISSUE TITLE
Gallup pages not displayed correctly

### ISSUE THREAD

**Issue by intuser** [qutebrowser/qutebrowser#6671]
If I visit for exampe https://news.gallup.com/poll/6424/Nutrition-Food.aspx only the first 5 entries (all starting with "How often do you") are displayed correctly.

All entries starting with the sixth one are mangled and unreadable. That's not the case with other browsers like firefox.

**Comment by The-Compiler** [comment]
Works fine here. Can you show a screenshot?

Also, please provide the information from the bug template: Can you reproduce with `--temp-basedir`? What's your `:version` info?

**Comment by intuser** [comment]
We can close the issue. I can't reproduce it with `--temp-basedir`. The site needs javascript to display correctly. Sorry.
