### ISSUE TITLE
archive.org searchbar is not recognised as an input.

### ISSUE THREAD

**Issue by emanuele6** [qutebrowser/qutebrowser#6685]
[**Version info**](https://paste.the-compiler.org/view/57c9fe74):
qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.6, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
The searchbar on the top right on archive.org is not recognised as an input:
* **INPUT MODE** is not entered automatically with `input.insert_mode.auto_enter` set to true;
* The `gi` binding says "No elements found.".

**How to reproduce**
https://archive.org/details/art_of_war_librivox/art_of_war_01-02_sun_tzu.mp3

**Comment by The-Compiler** [comment]
It's because it's in a shadow root, see #3569.
