### ISSUE TITLE
tmp file edited with external editor does not update the in-browser textbox

### ISSUE THREAD

**Issue by francisco-simoes** [qutebrowser/qutebrowser#6707]
In order to use neovim instead of gvim I added the following line to my `config.py`:
`c.editor.command = ['xfce4-terminal', '-x', 'nvim', '{}']`

Pressing `C-e` when in a textbox and insert mode correctly opens a neovim window. But after I save and quit with `:wq` the textbox in the browser remains empty. I suspect this is not the desired behaviour.

**Comment by The-Compiler** [comment]
qutebrowser stops watching the file for changes when the invoked process exits. It looks like xfce4-termnal forks by default and exits immediately, but according to [its manpage](https://manpages.ubuntu.com/manpages/xenial/man1/xfce4-terminal.1.html), you can tell it not to:

> `-H`, `--hold`
> Causes the terminal to be kept around after the child command has terminated

**Comment by francisco-simoes** [comment]
Thanks for your response. However, using `c.editor.command = ['xfce4-terminal', '--hold', '-x', 'nvim', '{}']` also did not work. Same behaviour as before.

**Comment by The-Compiler** [comment]
Works fine for me. Can you reproduce with `qutebrowser --temp-basedir -s editor.command "['xfce4-terminal', '--hold', '-x', 'nvim', '{}']"`?

**Comment by francisco-simoes** [comment]
Yes, still same behaviour. And by the way when I open the editor with something already written in the textbox, that pre-written text does not show up in nvim.

**Comment by The-Compiler** [comment]
What text box are you trying with?

**Comment by francisco-simoes** [comment]
The duckduckgo one, in my homescreen. Also if I don't write anything in my config and thus use `gvim` by default then it works.

**Comment by The-Compiler** [comment]
Weird, no idea then. Could you please reproduce via the `--temp-basedir` command above and then run `:report` so I can take a look at the logs?

**Comment by francisco-simoes** [comment]
Done.

**Comment by The-Compiler** [comment]
The logs show that indeed the editor process is exiting immediately:

```
17:49:22 DEBUG    procs      guiprocess:start:346 Starting process.
17:49:22 DEBUG    procs      guiprocess:_pre_start:340 Executing: xfce4-terminal --hold -x nvim /tmp/qutebrowser-editor-8e_2gmo7
17:49:22 DEBUG    procs      guiprocess:_on_started:330 Process started.
17:49:22 DEBUG    procs      guiprocess:_on_finished:298 Process finished with code 0, status 0.
17:49:22 DEBUG    procs      editor:_on_proc_closed:107 Editor closed
17:49:22 DEBUG    procs      editor:_on_file_changed:177 Read back: test text
```

What happens if you run `xfce4-terminal --hold -x nvim` from an existing terminal? Do you instantly get a prompt again (before exiting nvim)?

**Comment by francisco-simoes** [comment]
If I do what you said, write something and then exit nvim, then I get a pop up saying `The child process exited normally with status 0.`, and after I close it I am just left with a black terminal window, but a useless one (no prompt, just a black square).

**Comment by The-Compiler** [comment]
Ah, right, `--hold` doesn't actually seem to do what I thought it did. The question still stands though: What happens if you run `xfce4-terminal -x nvim` from an existing terminal, do you get a prompt back immediately (you shouldn't!)? Here's what I get:

![image](https://user-images.githubusercontent.com/625793/134952039-c49af42e-f4cb-4081-a6f0-6cac231d0bf5.png)

I suppose that error message might explain why you see a different behaviour, though. Could you try with `--disable-server` rather than `--hold`?
![image](https://user-images.githubusercontent.com/625793/134952174-de3dba92-c8a2-4ab1-a266-e7cbbc33e96c.png)

**Comment by francisco-simoes** [comment]
Ah I see what you mean. I do get a new prompt immediately:
![image](https://user-images.githubusercontent.com/60178634/134952553-c7827886-f605-476d-a288-8f5712257523.png)

**Comment by francisco-simoes** [comment]
With `--disable-server` I do not get a prompt immediately. Only after I close nvim.

And indeed using `c.editor.command = ['xfce4-terminal', '--disable-server', '-x', 'nvim', '{}']` works fine! Thank you!

**Comment by The-Compiler** [comment]
Right, so qutebrowser's behavior is correct there - from its perspective, you did quit the editor without editing anything, and there's no way (to my knowledge) it can tell the difference between the editor closing and your terminal "quitting" immediately.

Great to hear that `--disable-server` helps!

**Comment by giodamelio** [comment]
For anyone finding this thread while searching how to do this with Weztem + Neovim, let me save you a few minutes of tinkering

    editor.command = ["wezterm", "start", "--always-new-process", "--", "nvim", "-c", "normal {line}G{column0}l", "{file}"]
