### ISSUE TITLE
Copy to clipboard buttons do not copy to clipboard

### ISSUE THREAD

**Issue by mcastorina** [qutebrowser/qutebrowser#6719]
**Version info**:

```
qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.6, based on Chromium 87.0.4280.144
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
"Copy to clipboard" buttons don't copy to clipboard or appear to register as an event when clicked. I have noticed this on GitHub and Exercism.

**How to reproduce**
1. Navigate to a github URL like https://github.com/qutebrowser/qutebrowser/blob/master/setup.py#L25
2. Click on the ellipsis next to a line
3. Click "Copy line" or "Copy permalink"
4. Notice the contents of the clipboard remains unchanged

**Comment by toofar** [comment]
Works for me, you probably need to set `content.javascript.can_access_clipboard` to true (webengine doesn't support it as a requestable permission). Note that you can set it per domain, eg `:set -u github.com content.javascript.can_access_clipboard true`

**Comment by mcastorina** [comment]
Awesome, thank you so much! That did the trick and I'm really happy it can be set per domain :)

**Comment by e-dong** [comment]
fyi this field got renamed in v3.0.0
https://github.com/qutebrowser/qutebrowser/blob/b070cf45dbed27771578d98f3f4129d1f52a28f3/doc/changelog.asciidoc#changed

**Comment by boresk** [comment]
Is such a feature a big risk? Can it read clipboard content? 

On other browsers, this seems to always be working out of the box, do the same risk apply to these browsers?

**Comment by The-Compiler** [comment]
> Is such a feature a big risk? Can it read clipboard content?

Yes and yes, from the docs:

> - access: Allow reading from and writing to the clipboard.
> - access-paste: Allow accessing the clipboard and pasting clipboard content.

---

> On other browsers, this seems to always be working out of the box, do the same risk apply to these browsers?

No, this is because QtWebEngine [exposes clipboard access in a weird/inconsistent way](https://bugreports.qt.io/browse/QTBUG-77450). It looks like this [is going to change](https://codereview.qt-project.org/c/qt/qtwebengine/+/526977) with Qt 6.8.
