### ISSUE TITLE
Trouble with video playback in Invidious.

### ISSUE THREAD

**Issue by Arcane-Cube** [qutebrowser/qutebrowser#6721]
**Version info**:

qutebrowser v2.3.1
Git commit: 55bfe82b0 on HEAD (2021-07-28 14:33:55 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2
**Does the bug happen if you start with `--temp-basedir`?**:
Yes.
**Description**
Videos on Youtube play just fine but no video plays on Invidious.
**How to reproduce**

https://invidious.kavin.rocks/feed/popular

**Comment by The-Compiler** [comment]
Works for me. How did y ou install Qt and qutebrowser? Could you show your full `:version` information?

**Comment by emanuele6** [comment]
I can reproduce it.
Here is my `:version`: https://paste.the-compiler.org/view/b6f5cf44

**Comment by Arcane-Cube** [comment]
> Works for me. How did you install Qt and qutebrowser? Could you show your full `:version` information?

`qutebrowser v2.3.1
Git commit: 55bfe82b0 on HEAD (2021-07-28 14:33:55 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.6
PyQt: 5.15.3

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.4.4
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: 2.9.359 (bundled)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QWindowsVistaStyle
Platform plugin: windows
OpenGL: Intel, 4.3.0 - Build 20.19.15.4531
Platform: Windows-10-10.0.19042-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.19042, SP0, Multiprocessor Free

Paths:
cache: C:\Users\CoobOnWindows\AppData\Local\qutebrowser\cache
config: C:\Users\CoobOnWindows\AppData\Roaming\qutebrowser\config
data: C:\Users\CoobOnWindows\AppData\Roaming\qutebrowser\data
runtime: C:\Users\CoobOnWindows\AppData\Local\Temp\qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 3:05:12`

Just went and grabbed the Windows 64-bit installer and installed Qute from there.

**Comment by The-Compiler** [comment]
The Windows and macOS releases come without proprietary codecs. This unfortunately isn't going to change, as distributing them would require a license as well as recompiling QtWebEngine from sources for every Qt release (which is a major pain).

**Comment by foxTr0t1178** [comment]
I'm having this propblem

**Comment by toofar** [comment]
@foxTr0t1178 there's been no change. The windows builds still don't support proprietary codecs. Generally the recommendation would be to use mpv (there are some userscripts to make that nicer which may or may not work on windows) or use a different browser for that site.
