### ISSUE TITLE
Using scrollwheel to navigate between tabs is not working correctly in libinput 1.2.0

### ISSUE THREAD

**Issue by johnhamelink** [qutebrowser/qutebrowser#6722]
**Version info**:

```
❯ qutebrowser --version
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.3.1
Git commit: 5b28fba7c on master (2021-08-17 12:12:02 +0200)
Backend: QtWebEngine 5.15.6, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.7
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.10.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.10.377 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.36.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 470.74
Platform: Linux-5.14.8-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/john/.cache/qutebrowser
config: /home/john/.config/qutebrowser
data: /home/john/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/john/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
❯ 
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

A number of users are noticing changes to how the scroll wheel works on ratcheted scrollwheels such as the Logitech MX Master 2S since the upgrade of libinput 1.2.0:

- https://github.com/PixlOne/logiops/issues/271
- https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/issues/39
- https://gitlab.freedesktop.org/libinput/libinput/-/issues/675

According to the libinput people, the issue is with the scroll implementation on the application side. [This comment seems like it may help the most](https://gitlab.freedesktop.org/libinput/libinput/-/issues/675#note_1079582).

**How to reproduce**

- Upgrade to libinput 1.2.0
- Open multiple tabs in qutebrowser (the more tabs the more dramatic the effect)
- Use the scrollwheel to scroll between tabs

**Comment by The-Compiler** [comment]
The tab switching on scrolling is handled by Qt, not qutebrowser itself. I suspect this change already fixed things: [High resolution wheel-event support from libinput (Ie30281de) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/360677)

**Comment by johnhamelink** [comment]
@The-Compiler thanks for the explanation - for those unfamiliar with how the Qt framework works such as myself, does this means that we need to wait for a Qt update, or do we need to wait for a Qutebrowser update which contains a Qt update in it?

**Comment by The-Compiler** [comment]
It looks like you'd need to wait for Qt 6.3 [scheduled for](https://wiki.qt.io/Qt_6.3_Release) March 2022. Also for Qt 6 support in qutebrowser, though I suppose that will hopefully arrive sooner.

I'm a bit confused about this being classified as a new feature rather than a bug fix there, though. Maybe there's more to this. Reopening for now - but it'd be great if you could test with another Qt application using tabs (KDE Falkon comes to mind).

**Comment by johnhamelink** [comment]
Hi @The-Compiler, apologies for such a late reply - I'm not long out of hospital and had to catch up with life!

> but it'd be great if you could test with another Qt application using tabs (KDE Falkon comes to mind).

I can confirm that when I use KDE Falkon, the tab switching works just as expected, with the tab switching on Qutebrowser acting as I described before.

**Comment by johnhamelink** [comment]
Hi there,

This issue is now resolved on my machine with the introduction of a new Xorg Option:

https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/issues/39#note_1274611

I think this can be closed now.
