### ISSUE TITLE
`hint links download` fails to process some types of links.

### ISSUE THREAD

**Issue by crocket** [qutebrowser/qutebrowser#6730]
**Version info**:
qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

If I try to download some links with `;d`, qutebrowser says

> Error transferring url - server replied: Not Found

Selecting the links with `f` works.

**How to reproduce**

* Visit https://archive.org/download/nointro.gba
* Try to select `Super Mario Advance 2 - Super Mario World + Mario Brothers (Japan).7z` with `;d`

**Comment by toofar** [comment]
I think this is the same as https://github.com/qutebrowser/qutebrowser/issues/739 (see https://github.com/qutebrowser/qutebrowser/issues/5700) as there is a `<base>` element on that page and if you go to https://archive.org/download/nointro.gba/ (so with a slash on the end) and do the same thing it works fine.

So closing as a duplicate.

**Comment by crocket** [comment]
Do the same thing? What thing?

**Comment by The-Compiler** [comment]
That thing:



> * Try to select `Super Mario Advance 2 - Super Mario World + Mario Brothers (Japan).7z` with `;d`

**Comment by crocket** [comment]
Ah, I didn't notice the slash at the end.
