### ISSUE TITLE
Other metadata in editor.command

### ISSUE THREAD

**Issue by AckslD** [qutebrowser/qutebrowser#6733]
Along with `{file}`, `{line}`, `{column}`, `{line0}` and `{column0}` would it be possible to have some other data available for `editor.command` such as for example `{url}` and maybe some other metadata dependent on where you're editing.

What I would like to use this for is to define a command where I can have some rules which sets the filetype I'm editing. Such as if I'm for example on github/gitlab I would perhaps run something like
```
alacritty -e nvim {file} -c 'normal {line}G{column0}l' -c 'set filetype=markdown'
```
or similar.

**Comment by The-Compiler** [comment]
Such information is not always available (or at least not in the way you'd expect) - for example, `editor.command` can also be used via `:config-edit` or `:edit-command`.

Can you think of other use-cases for this? If not, I think #2727 would be a more universal solution to the problem described.
