### ISSUE TITLE
QB damaged and can't be opened

### ISSUE THREAD

**Issue by redmeades** [qutebrowser/qutebrowser#6771]
**Version info**: Downloaded 2.4.0 release

**Does the bug happen if you start with `--temp-basedir`?**: Yes.

**Description**

On Apple M1, macOS 11.6

Launching app fails to load. It shows the dialog: "qutebrowser.app" is damaged and can't be opened.

**How to reproduce**

* acquire qutebrowser - brew installation (cask) or downloading from github release (both tested)
* if github release, mount image, install in /Applications
* double-click qutebrowser icon
* or via console launch /Applications/qutebrowser.app/Contents/MacOS/qutebrowser --temp-basedir

<img width="261" alt="Screen Shot 2021-10-26 at 1 19 58 pm" src="https://user-images.githubusercontent.com/4978837/138797715-4cfdca77-7b45-4dfd-8cb0-485d08714ba1.png">

**Comment by andrey-semakin** [comment]
I had the same issue and the `xattr` solution helped.

My configuration: macOS 11.6 (20G165), 1,4 GHz Quad-Core Intel Core i5. So, it's not something M1-specific.

**Comment by toomsie** [comment]
It works, but does it compromise security or impose limitations.

**Comment by johnnypea** [comment]
Worked for me. Thanks. 🙇

Apple M1 Max
macOS Monterey 12.3.1

**Comment by The-Compiler** [comment]
How do things look with the recent v2.5.0 release? Same message still?

**Comment by angelus2014** [comment]
> How do things look with the recent v2.5.0 release? Same message still?

 I can't say yet as 2.5.0 hasn't hit Homebrew yet. I will check as soon as it's available for upgrade.


---
With regards,

Angelo Machils

**Comment by The-Compiler** [comment]
PR here from what it looks like: https://github.com/Homebrew/homebrew-cask/pull/121321

**Comment by angelus2014** [comment]
Checked again and it's available now. But again the message appears that the application is damaged. The xattr-thingie still works though.

**Comment by redmeades** [comment]
Hi, just updated via Homebrew and seeing the same issue.

xattr process worked.

**Comment by The-Compiler** [comment]
Just noticed this in the PyInstaller output:

```
52200 INFO: Signing the BUNDLE...
61116 WARNING: Error while signing the bundle: codesign command (['codesign', '-s', '-', '--force', '--all-architectures', '--timestamp', '--deep', '/Users/florian/proj/qutebrowser/dist/qutebrowser.app']) failed with error code 1!
output: /Users/florian/proj/qutebrowser/dist/qutebrowser.app: replacing existing signature
/Users/florian/proj/qutebrowser/dist/qutebrowser.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Users/florian/proj/qutebrowser/dist/qutebrowser.app/Contents/MacOS/PyQt5/Qt5/qml/QtQml/Models.2
 
61120 WARNING: You will need to sign the bundle manually!
```

I suppose that might have something to do with it.

**Comment by The-Compiler** [comment]
Trying again now with Qt 6, the "Signing the BUNDLE" step completes (not sure if that's Qt 6 or a newer PyInstaller). However, note that we also do some custom patching of the `.app` *after* PyInstaller was running. That's probably not going to help.

**Comment by The-Compiler** [comment]
Huh, suddenly I seem to be seeing this with v2.5.1 as well on macOS 10.14.6, with an error message which is... rude :rofl: 

![image](https://user-images.githubusercontent.com/625793/174023062-9bdfbb9d-a1a0-4e2f-9623-f95d37367bdc.png)

I opened #7251 and #7252 to get rid of our custom app patching. Maybe that will help.

**Comment by The-Compiler** [comment]
Turns out we probably can't get rid of the patching entirely, but I think I *might* have figured something out (involving... even more patching!).

Here are two builds I'd like some feedback on - they are based on the current `master`, and while nothing big about data formats should have changed (I think?), make sure to backup your data and config folders from `:version` just to be sure.

- [qutebrowser-9771-unsigned.dmg](https://qutebrowser.org/tmp/qutebrowser-9771-unsigned.dmg): With no `Info.plist` modifications done outside of PyInstaller (#7251)
- [qutebrowser-9771-signed.dmg](https://qutebrowser.org/tmp/qutebrowser-9771-signed.dmg): With some additional magic (660e776a15c02f5577d7aca075bb0e3f8b142831) so that `codesign` is happy with the `.app`

Could someone (or. ideally, various people!) please try those out and report back whether the latter, or even both, get rid of that issue finally?

**Comment by angelus2014** [comment]
Hello,

On 16/06/22 01:00PM, Florian Bruhin wrote:
>Turns out we probably can't get rid of the patching entirely, but I think I *might* have figured something out (involving... even more patching!).
>
>Here are two builds I'd like some feedback on - they are based on the current `master`, and while nothing big about data formats should have changed (I think?), make sure to backup your data and config folders from `:version` just to be sure.
>
>- [qutebrowser-9771-unsigned.dmg](https://qutebrowser.org/tmp/qutebrowser-9771-unsigned.dmg): With no `Info.plist` modifications done outside of PyInstaller (#7251)
>- [qutebrowser-9771-signed.dmg](https://qutebrowser.org/tmp/qutebrowser-9771-signed.dmg): With some additional magic (660e776a15c02f5577d7aca075bb0e3f8b142831) so that `codesign` is happy with the `.app`

I just tried both:
Git commit: 611a6d5cb-dirty on master (2022-06-16 19:47:27 +0200)
Git commit: 611a6d5cb-dirty on master (2022-06-16 19:47:27 +0200)

And they both start without any warning/error.

I tried them on an M1 Mini, OS v12.4


-- 
With regards,

Angelo Machils

**Comment by The-Compiler** [comment]
Amazing, thanks! Just backported the relevant commits to v2.5.x, so this should finally be fixed with the v2.5.2 release.

**Comment by scott56gps** [comment]
I just downloaded the latter file on my machine (clicked on link and started download through my browser) and got 
"qutebrowser can't be opened because Apple cannot check it for malicious software."

System:
MacBook Pro
MacOS Monterey 12.4
Intel

**Comment by The-Compiler** [comment]
@scott56gps That's good, because it means at least this issue is gone. See #5020 for that, though I'm not exactly keen at paying 100$ per year to Apple to fix it.

See e.g. [Safely open apps on your Mac - Apple Support](https://support.apple.com/en-us/HT202491) about what you can do to override it, though.
