### ISSUE TITLE
crash (Windows fatal exception: access violation)

### ISSUE THREAD

**Issue by 3xploiton3** [qutebrowser/qutebrowser#6786]
**Version info**:

qutebrowser v2.4.0
Git commit: 36ffff2f6 on HEAD (2021-10-21 18:50:06 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.7
PyQt: 5.15.5

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.2
pygments: 2.10.0
yaml: 6.0
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.10.377 (bundled)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QWindowsVistaStyle
Platform plugin: windows
OpenGL: Intel, 4.6.0 - Build 27.20.100.8681
Platform: Windows-10-10.0.17763-SP0, 64bit

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
crash after open facebook.com

**How to reproduce**

<details> 
  <summary>logs</summary>
   ==== Fault log ====
Windows fatal exception: access violation

Thread 0x00000f24 (most recent call first):
  File "qutebrowser\app.py", line 140 in qt_mainloop
  File "qutebrowser\app.py", line 130 in run
  File "qutebrowser\qutebrowser.py", line 245 in main
  File "qutebrowser\__main__.py", line 29 in <module>

==== Timestamps ====
Launch: Thu Oct 28 19:39:16 2021
Crash: Thu Oct 28 19:39:18 2021

==== Version info ====
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.4.0
Git commit: 36ffff2f6 on HEAD (2021-10-21 18:50:06 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.7
PyQt: 5.15.5

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.2
pygments: 2.10.0
yaml: 6.0
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.10.377 (bundled)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QWindowsVistaStyle
Platform plugin: windows
OpenGL: Intel, 4.6.0 - Build 27.20.100.8681
Platform: Windows-10-10.0.17763-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt5/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt5
OS Version: 10, 10.0.17763, SP0, Multiprocessor Free

Paths:
cache: C:\Users\Windows10-LTSC\AppData\Local\qutebrowser\cache
config: C:\Users\Windows10-LTSC\AppData\Roaming\qutebrowser\config
data: C:\Users\Windows10-LTSC\AppData\Roaming\qutebrowser\data
runtime: C:\Users\Windows10-LTSC\AppData\Local\Temp\qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:01

==== Config ====
bindings.commands = {"normal": {",m": "spawn mpv {www.youtube.com}"}}
https://www.alibaba.com: content.notifications.enabled = false
https://www.detik.com: content.notifications.enabled = false

==== Environment ====
PATH = C:\Program Files\qutebrowser;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\WireGuard\;C:\Program Files\Calibre2\;c:\EnsiklopediHadits\;c:\Python27\;c:\Python27\scripts\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\mpv.install\tools;C:\Users\Windows10-LTSC\AppData\Local\JSONBuddy;C:\Users\Windows10-LTSC\miniconda3;C:\Users\Windows10-LTSC\miniconda3\Library\mingw-w64\bin;C:\Users\Windows10-LTSC\miniconda3\Library\usr\bin;C:\Users\Windows10-LTSC\miniconda3\Library\bin;C:\Users\Windows10-LTSC\miniconda3\Scripts;C:\Users\Windows10-LTSC\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap;C:\Users\Windows10-LTSC\.dotnet\tools;C:\Users\Windows10-LTSC\AppData\Roaming\npm;%PyCharm Community Edition%;C:\Users\Windows10-LTSC\AppData\Local\Programs\Microsoft VS Code\bin;C:\ProgramData\Miniconda3\Library\bin\conda.bat;C:\ProgramData\Miniconda3\Scripts\conda.exe;C:\ProgramData\Miniconda3\condabin\conda.bat;C:\Users\Windows10-LTSC\Anaconda3\Library\bin;C:\Program Files\JetBrains\PyCharm 2020.3.2\bin;C:\Users\Windows10-LTSC\AppData\Local\Programs\EmEditor;C:\Users\Windows10-LTSC\.dotnet\tools
QT_PLUGIN_PATH = C:\Program Files\qutebrowser\PyQt5\Qt5\plugins

==== History ====
ResultRow(url='https://www.facebook.com/', title='Facebook', atime=1635424751, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=facebook.com&ia=web', title='facebook.com at DuckDuckGo', atime=1635424746, redirect=0)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/issues/6475', title='Qutebrowser crashes when logging into Google account [macOS 11] · Issue #6475 · qutebrowser/qutebrowser', atime=1635424736, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=online+job&iar=videos&iax=videos&ia=videos&iai=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DEufU0UW6NAA', title='online job at DuckDuckGo', atime=1635424735, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635424733, redirect=0)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/issues/6475', title='Qutebrowser crashes when logging into Google account [macOS 11] · Issue #6475 · qutebrowser/qutebrowser', atime=1635418672, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635418670, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=online+job&iar=videos&iax=videos&ia=videos&iai=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DEufU0UW6NAA', title='online job at DuckDuckGo', atime=1635418670, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=upwork&ia=web', title='upwork at DuckDuckGo', atime=1635418654, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635418647, redirect=0)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/issues', title='Issues · qutebrowser/qutebrowser', atime=1635418473, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635418445, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=online+job&iar=videos&iax=videos&ia=videos&iai=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dm9aILER0aDk', title='online job at DuckDuckGo', atime=1635418445, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=social+content+job&ia=web', title='social content job at DuckDuckGo', atime=1635418426, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635418420, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=online+job&iar=videos', title='online job at DuckDuckGo', atime=1635418322, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=how+money&iar=videos', title='how money at DuckDuckGo', atime=1635418309, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=video&ia=web', title='video at DuckDuckGo', atime=1635418260, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=facebook.com&ia=web', title='facebook.com at DuckDuckGo', atime=1635418225, redirect=0)
ResultRow(url='https://www.facebook.com/', title='Facebook', atime=1635399150, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=facebook.com&ia=web', title='facebook.com at DuckDuckGo', atime=1635399146, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635399005, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=facebook', title='facebook at DuckDuckGo', atime=1635398932, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635398902, redirect=0)
ResultRow(url='https://www.youtube.com/results?search_query=qutebrowser', title='qutebrowser - YouTube', atime=1635342624, redirect=0)
ResultRow(url='http://youtube.com/qutebrowser', title='404 Not Found', atime=1635342616, redirect=1)
ResultRow(url='https://www.youtube.com/qutebrowser', title='404 Not Found', atime=1635342616, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635342576, redirect=0)
ResultRow(url='https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv', title='mpv/umpv at master · mpv-player/mpv', atime=1635342126, redirect=0)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc', title='qutebrowser/faq.asciidoc at master · qutebrowser/qutebrowser', atime=1635342076, redirect=0)
ResultRow(url='https://chocolatey.org/packages/mpv', title='Chocolatey Software | mpv 2020.12.06', atime=1635342052, redirect=1)
ResultRow(url='https://community.chocolatey.org/packages/mpv', title='Chocolatey Software | mpv 2020.12.06', atime=1635342052, redirect=0)
ResultRow(url='https://mpv.io/installation', title='mpv.io | Installation', atime=1635342038, redirect=1)
ResultRow(url='https://mpv.io/installation/', title='mpv.io | Installation', atime=1635342038, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=mpv&ia=web', title='', atime=1635342030, redirect=1)
ResultRow(url='https://mpv.io/', title='', atime=1635342030, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=mpv&ia=web', title='mpv at DuckDuckGo', atime=1635342028, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635342023, redirect=0)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/issues', title='Issues · qutebrowser/qutebrowser', atime=1635341675, redirect=0)
ResultRow(url='https://music.youtube.com/watch?v=U3ASj1L6_sY&list=PL4fGSI1pDJn5QPpj0R4vVgRWk8sSq549G', title='YouTube Music', atime=1635341671, redirect=0)
ResultRow(url='https://www.google.com/?gws_rd=ssl', title='Google', atime=1635341663, redirect=0)
ResultRow(url='https://accounts.google.com/signin/v2/challenge/pwd?hl=id&passive=true&continue=https%3A%2F%2Fwww.google.com%2F%3Fgws_rd%3Dssl&ec=GAZAmgQ&flowName=GlifWebSignIn&flowEntry=ServiceLogin&cid=1&navigationDirection=forward&TL=AM3QAYZmsT_FoDMAs52dXwdrFJUmb6ZaliBakqRNVDy2vrevZW1_mARdMtwaQaq0', title='Masuk - Akun Google', atime=1635341643, redirect=0)
ResultRow(url='https://accounts.google.com/signin/v2/identifier?hl=id&passive=true&continue=https%3A%2F%2Fwww.google.com%2F%3Fgws_rd%3Dssl&ec=GAZAmgQ&flowName=GlifWebSignIn&flowEntry=ServiceLogin', title='Masuk - Akun Google', atime=1635341632, redirect=0)
ResultRow(url='https://www.google.com/?gws_rd=ssl', title='Google', atime=1635341630, redirect=0)
ResultRow(url='http://speedtest.net/', title='Speedtest by Ookla - The Global Broadband Speed Test', atime=1635341398, redirect=1)
ResultRow(url='https://www.speedtest.net/', title='Speedtest by Ookla - The Global Broadband Speed Test', atime=1635341398, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635341384, redirect=0)
ResultRow(url='https://github.com/dudik/blockit', title="dudik/blockit: WebKitGTK adblock extension with Brave's Rust-based adblock engine for backend.", atime=1635341294, redirect=0)
ResultRow(url='https://arnidagur.github.io/python-adblock/docs/adblock/index.html', title='adblock - Rust', atime=1635341265, redirect=0)
ResultRow(url='https://arnidagur.github.io/python-adblock/docs/adblock/struct.FilterSet.html', title='adblock::FilterSet - Rust', atime=1635341259, redirect=0)
ResultRow(url='https://arnidagur.github.io/python-adblock/docs/adblock/index.html', title='adblock - Rust', atime=1635341251, redirect=0)
ResultRow(url='https://www.youtube.com/', title='YouTube', atime=1635340953, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635340939, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=python-adblock&ia=images', title='adblock · PyPI', atime=1635340909, redirect=1)
ResultRow(url='https://pypi.org/project/adblock/', title='adblock · PyPI', atime=1635340909, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=python-adblock', title='python-adblock at DuckDuckGo', atime=1635340903, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=1&ia=web', title='1 at DuckDuckGo', atime=1635340786, redirect=0)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/issues/6480', title='adblock: Support cosmetic filtering (element hiding) and scriptlets · Issue #6480 · qutebrowser/qutebrowser', atime=1635340786, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635340781, redirect=0)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/blob/master/doc/img/hints.png', title='qutebrowser/hints.png at master · qutebrowser/qutebrowser', atime=1635340685, redirect=0)
ResultRow(url='https://github.com/session', title='`insert mode` not entered automatically with option `input.insert_mode.auto_enter = True` when entering Facebook writable areas · Issue #3794 · qutebrowser/qutebrowser', atime=1635340632, redirect=1)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/issues/3794', title='`insert mode` not entered automatically with option `input.insert_mode.auto_enter = True` when entering Facebook writable areas · Issue #3794 · qutebrowser/qutebrowser', atime=1635340632, redirect=0)
ResultRow(url='https://github.com/session', title='Sign in to GitHub · GitHub', atime=1635340615, redirect=0)
ResultRow(url='https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fqutebrowser%2Fqutebrowser%2Fissues%2F3794', title='Sign in to GitHub · GitHub', atime=1635340606, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=video+facebook+qutebrowser&ia=web', title='`insert mode` not entered automatically with option `input.insert_mode.auto_enter = True` when entering Facebook writable areas · Issue #3794 · qutebrowser/qutebrowser · GitHub', atime=1635340434, redirect=1)
ResultRow(url='https://github.com/qutebrowser/qutebrowser/issues/3794', title='`insert mode` not entered automatically with option `input.insert_mode.auto_enter = True` when entering Facebook writable areas · Issue #3794 · qutebrowser/qutebrowser · GitHub', atime=1635340434, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=video+facebook+qutebrowser&ia=web', title='video facebook qutebrowser at DuckDuckGo', atime=1635340414, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=irc+online&ia=web', title='KiwiIRC - The webIRC client', atime=1635340296, redirect=1)
ResultRow(url='https://kiwiirc.com/', title='KiwiIRC - The webIRC client', atime=1635340296, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=irc+online&ia=web', title='irc online at DuckDuckGo', atime=1635340252, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=video+facebook+qutebrowser&ia=web', title='How I met the qutebrowser – GEEK PEEK', atime=1635340235, redirect=1)
ResultRow(url='https://thebeautifullmind.com/2020/04/25/how-i-met-the-qutebrowser/', title='How I met the qutebrowser – GEEK PEEK', atime=1635340235, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=irc&ia=web', title='irc at DuckDuckGo', atime=1635340228, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635340221, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=video+facebook+qutebrowser&ia=web', title='video facebook qutebrowser at DuckDuckGo', atime=1635340155, redirect=0)
ResultRow(url='https://music.youtube.com/search?q=stay', title='YouTube Music', atime=1635340124, redirect=0)
ResultRow(url='https://qutebrowser.org/img/cheatsheet-big.png', title='cheatsheet-big.png (3342×2060)', atime=1635339929, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=qutebrowser+keyboard', title='qutebrowser keyboard at DuckDuckGo', atime=1635339897, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635339887, redirect=0)
ResultRow(url='https://music.youtube.com/', title='YouTube Music', atime=1635339715, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635339681, redirect=0)
ResultRow(url='https://www.facebook.com/', title='Facebook', atime=1635339147, redirect=0)
ResultRow(url='https://www.facebook.com/checkpoint/?next', title='Facebook', atime=1635339059, redirect=0)
ResultRow(url='https://www.facebook.com/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjM1MzM4OTc3LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D', title='Log in to Facebook', atime=1635339008, redirect=0)
ResultRow(url='https://www.facebook.com/', title='Facebook – log in or sign up', atime=1635338982, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=opencatalog&ia=web', title='opencatalog at DuckDuckGo', atime=1635338963, redirect=0)
ResultRow(url='https://mind.1688.com/a/tianda/tmb4lip53y/pha?spm=a260k.dacugeneral.home2019daculanding.2.6633436ctuBT4Z&pha=true&wh_act_nativebar=0-1&disableNav=YES&__existtitle__=1&__hide__bottom__bar=true&_wvUseWKWebView=true&__webview_options__=fullscreen%3DYES&traceId=212bb49816353388801001410ec502', title='找工厂商人节主会场', atime=1635338928, redirect=1)
ResultRow(url='https://sale.1688.com/sale/dacu/commonnew/1028srjcs1014333Uw.html?__pageId__=230196&cms_id=230196&wh_pha=true&__existtitle__=1&spm=a260k.dacugeneral.home2019daculanding.2.6633436ctuBT4Z&__existtitle__=1&__hide__bottom__bar=true&_wvUseWKWebView=true&__webview_options__=fullscreen%3DYES&traceId=212bb49816353388801001410ec502&__existtitle__=1', title='找工厂商人节主会场', atime=1635338928, redirect=0)
ResultRow(url='https://mind.1688.com/a/tianda/tmb4lip53y/pha?spm=a260k.dacugeneral.home2019daculanding.2.6633436ctuBT4Z&pha=true&wh_act_nativebar=0-1&disableNav=YES&__existtitle__=1&__hide__bottom__bar=true&_wvUseWKWebView=true&__webview_options__=fullscreen%3DYES&traceId=212bb49816353388801001410ec502', title='【主会场】6月狂欢节', atime=1635338911, redirect=0)
ResultRow(url='https://www.caexpo.org/?spm=a260k.dacugeneral.home2019scene.d8.6633436ctuBT4Z&channel=1688', title='中国—东盟博览会 | China-ASEAN Expo', atime=1635338910, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=1688&ia=web', title='阿里巴巴1688.com - 全球领先的采购批发平台,批发网', atime=1635338889, redirect=1)
ResultRow(url='https://www.1688.com/', title='阿里巴巴1688.com - 全球领先的采购批发平台,批发网', atime=1635338889, redirect=0)
ResultRow(url='https://duckduckgo.com/?q=1688&ia=web', title='1688 at DuckDuckGo', atime=1635338875, redirect=0)
ResultRow(url='https://start.duckduckgo.com/', title='DuckDuckGo — Privacy, simplified.', atime=1635338813, redirect=0)
ResultRow(url='http://amazon.com/', title='Amazon.com. Spend less. Smile more.', atime=1635338807, redirect=1)
ResultRow(url='https://www.amazon.com/', title='Amazon.com. Spend less. Smile more.', atime=1635338807, redirect=0)
ResultRow(url='http://alibaba.com/', title="Alibaba.com: Manufacturers, Suppliers, Exporters & Importers from the world's largest online B2B marketplace", atime=1635338787, redirect=1)
ResultRow(url='https://www.alibaba.com/?__redirected__=1', title="Alibaba.com: Manufacturers, Suppliers, Exporters & Importers from the world's largest online B2B marketplace", atime=1635338787, redirect=0)
ResultRow(url='https://www.tokopedia.com/p/fashion-pria/tas/tas-selempang', title='Jual Tas Selempang Pria Nyaman - Harga Murah | Tokopedia® - Harga Terbaik | Tokopedia', atime=1635338707, redirect=1)
ResultRow(url='https://www.tokopedia.com/p/fashion-pria/tas-pria/tas-selempang-pria', title='Jual Tas Selempang Pria Nyaman - Harga Murah | Tokopedia® - Harga Terbaik | Tokopedia', atime=1635338707, redirect=0)
</details>

**Comment by The-Compiler** [comment]
@3xploiton3 any update?

**Comment by 3xploiton3** [comment]
I tried 
qt.workarounds.remove_service_workers

Set to true

No crash but its like incognito mode, all tab gone when i quit window

**Comment by The-Compiler** [comment]
That's the default behaviour (unless there is a crash). You need to quit with `:wq` or set `auto_save.session` to save the session.
