### ISSUE TITLE
Pulseaudio improvements

### ISSUE THREAD

**Issue by blueForestIcarus** [qutebrowser/qutebrowser#6790]
I have two suggestions for improving pulseaudio workflow.
The first is that, since each tab producing audio gets its own pulseaudio sink, the names of the pulseaudio sinks could be made specific to the tab (perhaps the title of the page). This way if I have multible yt videos open it would be easier to adjust the correct volume. 

The second suggestion (perhaps this behavior would be enabled with an option) is that for Audio and Video elements, the volume control uses the pulse mixer, meaning that changes to the volume in youtube would change the volume of the sink in pulseaudio. This would remove the redundant volume control, and allow all volumes to be controlled with pavucontrol.

Admitably, I am uncertain if either of these are feasible.

**Comment by The-Compiler** [comment]
They are both out of qutebrowser's control, since the interaction with Pulseaudio is entirely done by the underlying Chromium.

For the former, a hack might be possible (but unlikely), see #5914.
