### ISSUE TITLE
[Feature] Ignoring keyboard layout for all motions

### ISSUE THREAD

**Issue by Rassska** [qutebrowser/qutebrowser#6797]
Hi, there! 
Is it possible to scroll some web-pages on another keyboard layout, let's say not using English, but with the same keystroke?

I use Vimium extension for Google Chrome and it's fine with that. Whenever I press `f` there it automatically shows all possible links on the page and doesn't matter what keyboard layout I use. 

Can we do the same or we already have that option?

Thanks!

**Comment by The-Compiler** [comment]
Duplicate of #5963
