### ISSUE TITLE
QtWebEngine 5.15.7: Access to <something> at <somewhere> from origin 'file://' has been blocked by CORS policy

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#6800]
**Version info**:
https://paste.the-compiler.org/view/05fafde8

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
I've been doing some web development, with `file:///home/enrico/path/to/index.html` open in a tab for weeks, so that I just needed to refresh to reflect the changes I make to source files (HTML/JS/CSS/...). My site tries to access a few things from the web. For instance, I have this piece of HTML to use google fonts.
```
<head>
  ...
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap');
  </style>
  ...
</head>
```
A few hours ago I've restarted qutebrowser and the console throws errors such as:
<code>
Access to font at 'https://fonts.gstatic.com/s/lato/v20/S6uyw4BMUTPHjx4wXg.woff2' from origin 'file://' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
GET https://fonts.gstatic.com/s/lato/v20/S6uyw4BMUTPHjx4wXg.woff2 net::ERR_FAILED
</code>

The issue doesn't affect the GitHub page on which I'm serving the site, [here](https://aster89.github.io). As I can see (e.g. [here](https://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local)), it looks like a common/known issue. However it just popped up yesterday for me, whereas everything was fine in the last few weeks.

Furthermore, Chromium doesn't suffer from it (on the local `file:///`), hence I'm posting this as a bug.

**How to reproduce**
Well, I guess downloading the repo I linked above and opening the `index.html` local file could reproduce it.

**Comment by The-Compiler** [comment]
What was your QtWebEngine version before yesterday? I guess /var/log/pacman.log should tell you.

**Comment by Aster89** [comment]
Here's the output of `grep -i 'qt.*web' /var/log/pacman.log | tail`:
```
[2021-04-18T20:28:12+0100] [ALPM] upgraded qt5-webengine (5.15.3-3 -> 5.15.3-4)
[2021-05-06T19:56:47+0100] [ALPM] upgraded qt5-webengine (5.15.3-4 -> 5.15.3-5)
[2021-06-03T17:06:07+0100] [ALPM] upgraded qt5-webengine (5.15.3-5 -> 5.15.4-3)
[2021-06-25T06:00:33+0100] [ALPM] upgraded qt5-webengine (5.15.4-3 -> 5.15.5-1)
[2021-09-09T09:46:23+0100] [ALPM] upgraded qt5-webengine (5.15.5-1 -> 5.15.6-1)
[2021-09-22T05:54:37+0100] [ALPM] upgraded qt5-webengine (5.15.6-1 -> 5.15.6-2)
[2021-10-18T10:27:17+0100] [ALPM] upgraded qt5-webengine (5.15.6-2 -> 5.15.6-4)
[2021-10-20T11:43:04+0100] [ALPM] upgraded python-pyqt5-webengine (5.15.4-1 -> 5.15.5-1)
[2021-10-22T17:59:15+0100] [ALPM] upgraded qt5-webengine (5.15.6-4 -> 5.15.6-5)
[2021-10-30T06:28:40+0100] [ALPM] upgraded qt5-webengine (5.15.6-5 -> 5.15.7-1)
```
Does this answer the question?

**Comment by The-Compiler** [comment]
It does indeed:

> [2021-10-30T06:28:40+0100] [ALPM] upgraded qt5-webengine (5.15.6-5 -> 5.15.7-1)

and it looks like QtWebEngine 5.15.7 contains this change:

[Block CORS from local URLs when remote access is not enabled (I0e0a1530) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/376369)

Does setting `content.local_content_can_access_remote_urls` to true help?

**Comment by Aster89** [comment]
Yes it does, thanks! And given the name of the option, I don't need to ask what it does :smile:
