### ISSUE TITLE
Version 2.4.0 is "damaged" according on MacOS

### ISSUE THREAD

**Issue by brukberhane** [qutebrowser/qutebrowser#6801]
**Version info**:
v2.4.0

**Does the bug happen if you start with `--temp-basedir`?**: no

**Description**
Latest version of qutebrowser (v2.4.0) keeps throwing an error saying that the application is damaged upon trying to open it.
**How to reproduce**
 Opened the application and got this error: 
![image](https://user-images.githubusercontent.com/20716815/140017400-eba0c5a2-f141-4a93-b451-d3c8a6a2e1b7.png)

**Comment by The-Compiler** [comment]
Duplicate of #6771
