### ISSUE TITLE
Clicking a link with the middle mouse button makes Qutebrowser stay on the current tab but clicking "open link in new tab" doesn't

### ISSUE THREAD

**Issue by spagootie** [qutebrowser/qutebrowser#6811]
It's a bit inconsistent, and other browsers stay on the current tab when selecting "open in new tab".

**Comment by mschilli87** [comment]
IIRC the difference is that one is triggering `open -t <link-target>` (open in new tab) while the other triggers `open -b <link-target>` (open in new background tab). Do you suggest re-binding one of them? If so which one and why? What do other browsers do?

**Comment by The-Compiler** [comment]
The context menu is currently coming from Qt entirely, and the QtWebEngine API is rather limited on the information we get about an opened link with the built in context menu. See #3231 and #349.
