### ISSUE TITLE
Accents do not work

### ISSUE THREAD

**Issue by viniciusmiradouro** [qutebrowser/qutebrowser#6815]
**Version info**:
qutebrowser v2.4.0
Git commit: 1f641c8c4 on master (2021-11-08 10:00:44 +0100)
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

I'm not able to type any accented letters, like 'é', 'ã' or even standalone accents like '~' in any textbox. I can only copy and paste them. Everywhere else in my system i can type them just fine.

**How to reproduce**

I don't really know. It worked just fine until I reinstalled arch. Maybe some other package did something to my keyboard?

**Comment by The-Compiler** [comment]
Can you type them in command mode (i.e. after `~`)? What about other browsers based on QtWebEngine, such as KDE Falkon?

**Comment by viniciusmiradouro** [comment]
No, I can't type them in command mode. I tried doing the same on KDE falkon and it didn't work as well. Maybe it has something to do with the engine. On firefox it works normally.

**Comment by The-Compiler** [comment]
When you say that it works anywhere else, did you try another Qt application?

**Comment by viniciusmiradouro** [comment]
No, I didn't. So, yeah, not strictly anywhere else. But in my terminal and other aplications it works normaly.

**Comment by The-Compiler** [comment]
Well, can you try? It sounds like some setup issue on your system related to Qt applications, maybe related to IME if you set one up.

**Comment by viniciusmiradouro** [comment]
I tried qbittorrent and the accents didn't work as well. Yes, I'm using an IME but, even when I disable it, the accents don't work on Qt apps. I'll try completely reinstalling arch to see if it solves the problem somehow.

**Comment by The-Compiler** [comment]
Make sure you have Qt configured for the IME as well, e.g. by setting `QT_IM_MODULE` and `XMODIFIERS`. See e.g. [Input method - ArchWiki](https://wiki.archlinux.org/title/Input_method) for more details.

Closing this as it doesn't look like a qutebrowser issue.

**Comment by viniciusmiradouro** [comment]
Found the solution. In the `locale.conf` file I had set `LANG=en_US.UTF8` instead of `LANG=en_US.UTF-8`. Dumb error. Well, Qt can generate the compose table now. Everything is working fine.
