### ISSUE TITLE
Netflix: Browser is no longer supported.

### ISSUE THREAD

**Issue by Waples** [qutebrowser/qutebrowser#6816]
**Version info**:

```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.7
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: 0.4.3
jinja2: 3.0.2
pygments: 2.7.3
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.36.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 21.2.4
Platform: Linux-5.14.16-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
Netflix doesn't seem to be working anymore.
Browsing on Netflix works fine, also the preview playback runs fine aswel. But whenever you actually wanna watch something, you get the error from the image below.

I do have widevine installed.

![1636455819-2021-11-09-shot](https://user-images.githubusercontent.com/25055666/140913384-d2702d78-65dd-46a5-912f-47e7623f4ea5.png)

**How to reproduce**

Try to watch something on netflix.

**Comment by The-Compiler** [comment]
Could be! A few questions since I don't have access to a Netflix account to test right now:

- Is it reproducible with `qutebrowser --temp-basedir`?
- Does `--temp-basedir -s content.headers.user_agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"` change anything?
- Any messages in the `:devtools` console?

Also, if you're adventurous, you could try with the `qt6-test` branch:

- Clone the git repo, e.g. via `git clone https://github.com/qutebrowser/qutebrowser.git`
- `cd qutebrowser`
- Check out the branch using `git checkout qt6-test`
- Create a new separate environment via `python3 scripts/mkvenv.py --venv-dir .venv-qt6`
- Run `.venv-qt6/bin/qutebrowser --temp-basedir` and verify via `:version` that you're indeed on Qt 6
- Try to reproduce

**Comment by rien333** [comment]
Works for me btw, I think I have about the same version of everything as you.

**Comment by Waples** [comment]
`:devtools` console, doesn't show anything readable to me.
![1636547901-2021-11-10-shot](https://user-images.githubusercontent.com/25055666/141114521-28a7e816-1602-42f4-9ac6-5afc6cb4341c.png)

I'll try it later today with `--temp-basedir` and I'll will try out the `qt-6` branch, just for good measure.

**Comment by mschilli87** [comment]
I can also watch videos on a similar version:

```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.7
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.2
pygments: 2.10.0
yaml: 6.0
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: nouveau, 4.3 (Compatibility Profile) Mesa 21.1.7
Platform: Linux-5.10.76-gentoo-r1-x86_64-Intel-R-_Core-TM-_i5-2520M_CPU_@_2.50GHz-with-glibc2.33, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3.9
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5
```

My useragent is set to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36`.

Note though that according to their [compatibility list](https://help.netflix.com/en/node/23742) 'Chrome (88 or later)' is supported.
So maybe they are just rolling out that check and it depends on the server you happen to connect to.

Let me know if I can be of any help further narrowing this down.

**Comment by rien333** [comment]
> Note though that according to their compatibility list 'Chrome (88 or later)' is supported.
So maybe they are just rolling out that check and it depends on the server you happen to connect to.


I don't see the problem regardless of whether I run qtwebengine based on chromium 87 or 88, but aside from waiting on qt6 compatibility, its somewhat "easy" to build qtwebengine based on chromium 88 (which I've been doing in secret, because 1) why not 2) I need to build qtwebengine from source for other reasons). 

If you change [this line](https://github.com/archlinux/svntogit-packages/blob/master/qt5-webengine/repos/extra-x86_64/PKGBUILD#L35) from the PKGBUILD to `git submodule set-branch --branch 88-based src/3rdparty` you should get a perfectly stable 'chromium 88'-based build (note that no one recommends this though, its just that the team was once working on 88 support, and then switch most efforts to qt6).

If OP want to dig deep, this is something you could try, but you'll probably be just wasting your time.

**Comment by The-Compiler** [comment]
@rien333 Oh, the `88-based` thing is actually quite interesting, I had no idea! Note, however, that the 87-based branch [is still receiving security backports](https://github.com/qt/qtwebengine-chromium/commits/87-based) while the 88-based one [seems abandoned](https://github.com/qt/qtwebengine-chromium/commits/88-based), so I'd really only recommend this if you need a feature from Chromium 88.

**Comment by Waples** [comment]
I did a test with the `qt6` branch, with `--temp-basedir`, then I get another error.

![1636645611-2021-11-11-shot](https://user-images.githubusercontent.com/25055666/141327352-65574483-8283-4c86-b6e0-9054a25f749d.png)

**Comment by Waples** [comment]
I'm gonna install that pkg when I get off work, then I'll do a rerun of testing with the `qt6` branch.

**Comment by The-Compiler** [comment]
@Waples if you're still at work, you might want to take a break at some point :wink: (no worries, I just couldn't resist)

**Comment by Waples** [comment]
What can I say, I'm a busy boy 😅

**Comment by Narice** [comment]
Any updates on this?
I think I'm having the same problem :sweat_smile:

**Comment by The-Compiler** [comment]
Not from my side so far. Hard to say what the server is actually checking for. Might or might not be resolved with Qt 6 support, but that will still take a bit to arrive.

**Comment by rien333** [comment]
> Hard to say what the server is actually checking for. 

Yes: I still don't have the problem. Perhaps try connecting to netflix using something like `tor` (see e.g. https://tonisagrista.com/blog/2020/tor-qutebrowser/), and see if its a location based thing?

**Comment by Waples** [comment]
@The-Compiler I've tried it again, already had `python-pyqt6-webengine` (system-wide) installed it seems. Still no bueno though, cannot get the widevine working with `--temp-basedir` in the virtualenv. Unless you have an idea how..

@rien333 A location based issue would be hilarious, since it works perfectly fine in Chromium/Firefox/Midori..

**Comment by Waples** [comment]
@Narice Are also still having this issue or did you find a fix?

**Comment by Waples** [comment]
@The-Compiler No idea if this has anything to do with it, but the maintainer for [chromium-widevine (AUR)](https://aur.archlinux.org/packages/chromium-widevine/) states that `>= Chromium 83` installs the component itself. Is `qutebrowser` still dependend on this?

**Comment by Narice** [comment]
> @Narice Are also still having this issue or did you find a fix?

No, I had to use firefox :sweat_smile:

**Comment by dottdottdott** [comment]
I don't think that the useragend is important, it might be a widevine error (version to old?).  
My user agent is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3203.0 Safari/537.36`  
And my other libs are also not the most recent:  
```qutebrowser v2.4.0
Git commit: b500d4028 on master (2021-12-06 08:29:52 +0100)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
jinja2: 3.0.0a1
pygments: 2.7.1
yaml: 5.3.1
adblock: 0.5.1
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 20.3.5
Platform: Linux-5.10.0-9-amd64-x86_64-with-glibc2.31, 64bit
Linux distribution: Debian GNU/Linux 11 (bullseye) (debian)
Frozen: False
Imported from /usr/local/lib/python3.9/dist-packages/qutebrowser-2.4.0-py3.9.egg/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5```  

What widevine version are you using and how?  
For me this works well (pointing to a chrome installation):  
```qt.args:
    global:
     - widevine-path=/opt/google/chrome/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so```

**Comment by Waples** [comment]
@dottdottdott I have this version of `chromium-widevine`:
```aur/chromium-widevine 1:4.10.2391.0-1 (+419 1.57) (Installed: 1:4.10.1610.0-1```

I'll try to set the widevine-path with `qt.args`, that's empty for me atm

**Comment by Waples** [comment]
@dottdottdott also tried your with `c.qt.args = ['widevine-path=/usr/lib/chromium/libwidevinecdm.so']` but that ain't working either.. :/

**Comment by The-Compiler** [comment]
FWIW I don't see how that could make a difference, given that path [is one of the defaults being searched](https://github.com/qt/qtwebengine/blob/v5.15.7-lts/src/core/content_client_qt.cpp#L361).

**Comment by Waples** [comment]
Any ideas about further triage @The-Compiler  ? I'm a bit stumped.

**Comment by dottdottdott** [comment]
@Waples I'm running widevine 4.10.2391, your version is not that old (~9 Months i think), but maybe try to update to the current one.
@The-Compiler I just tried to remove the qt.args to double check and widevine does not work for me without the widevine-path set in the config.

**Comment by Waples** [comment]
@dottdottdott ```$  yay -Qi chromium-widevine
Name            : chromium-widevine
Version         : 1:4.10.2391.0-1
```
I have the same version as you, still doesn't work. I tried again with another useragent, also doesn't work..

**Comment by WouterSpekkink** [comment]
I ran into the same issue. Shortly after coming across this discussion, I found the following: https://bbs.archlinux.org/viewtopic.php?id=231358

Installing qt5-webengine-widevine from the AUR fixed it for me.

**Comment by rien333** [comment]
> Installing qt5-webengine-widevine from the AUR fixed it for me.

Fun — I use `aur/chromium-widevine` and it works fine for me (even though I just noticed that `qt.args = [ppapi-widevine-path=...]` has been pointing to a non-existent file for months).

 I think there's no difference between the two packages even, except the location where they install the .so file, and that the webengine "specific" version is a bit older.

**Comment by Waples** [comment]
> I ran into the same issue. Shortly after coming across this discussion, I found the following: https://bbs.archlinux.org/viewtopic.php?id=231358
> 
> Installing qt5-webengine-widevine from the AUR fixed it for me.

Yep just tested this, now it's working for me aswel @WouterSpekkink, thanks!

Let's see how long it lasts with the upcoming QT6

**Comment by Waples** [comment]
@The-Compiler i'll close this for now, since Installing qt5-webengine-widevine from the AUR fixed it for me.

But a good to know

**Comment by Narice** [comment]
code for nixos using home-manager:
```nix
    programs = {
      qutebrowser = {
        enable = true;
        settings = {
          qt.args = ["widevine-path=${pkgs.vivaldi-widevine}/share/google/chrome/WidevineCdm/_platform_specific/linux_x64/libwidevinecdm.so"];
        };
      };
    };
```
This is using the  `vivaldi-widevine` package on nixpkgs.
