### ISSUE TITLE
test_real_git test fails with different core.abbrev

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#6825]
**Version info**:
N/A (git!)

**Does the bug happen if you start with `--temp-basedir`?**:
N/A (no running required)

**Description**
TestGitStrSubprocess.test_real_git fails when core.abbrev (globally I assume) is set to anything other than the default (7).
```
        ret = version._git_str_subprocess(str(git_repo))
>       assert ret == f'6e4b65a on {branch_name} (1970-01-01 01:00:00 +0100)'
E       AssertionError: assert equals failed
E         '6e4b65a529c0 on master (1970-01-01 01:00:00 +0100)'  '6e4b65a on master (1970-01-01 01:00:00 +0100)'
```
because the reported sha is longer than the hardcoded one

**How to reproduce**
```
git config --global core.abbrev 12
python3 -m pytest tests/unit/utils/test_version.py
```
Maybe you can skip the global bit, not sure

**Comment by The-Compiler** [comment]
This test might actually cause more issues than it's worth - but since this one was easy to fix, I did so. Thanks for the report!
