### ISSUE TITLE
Yank URL and keep ignored parameters

### ISSUE THREAD

**Issue by achilleas-k** [qutebrowser/qutebrowser#6830]
The `url.yank_ignored_parameters` setting is one of my favourite features.  It saves me so much time from cleaning URLs when I paste them to people.  I have one issue that some websites use `ref` as a legitimate parameter, so I have to remove it from the ignored list.  It would be awesome if there was a `yank` command argument that ignores the ignored parameter list, a sort of `yank raw-url`.

Is it possible to script that with the current features somehow, or does it require adding a whole new feature for it?

Thanks!

**Comment by arza-zara** [comment]
You can bypass it with `yank inline {url}`. I wonder if that's enough.

**Comment by achilleas-k** [comment]
Oh yeah, that totally works.  Thank you!!
