### ISSUE TITLE
Missing sanitize option to clear cookies 

### ISSUE THREAD

**Issue by antisocrates** [qutebrowser/qutebrowser#6837]
I am using qutebrowser exclusively, and one feature I am missing which makes it unbearable is an option to clear all cookies, cache, browsing history, search history, site settings etc.

Even a basic feature that deletes everything without time range options would suffice.

Thanks

**Comment by figos33** [comment]
I am missing this feature as well. Hope the devs add it fast (along with a slightly better adblock similar to ublock origin)

**Comment by The-Compiler** [comment]
Duplicate of #58
