### ISSUE TITLE
Allow for numpad Enter to be pressed

### ISSUE THREAD

**Issue by manoelpqueiroz** [qutebrowser/qutebrowser#6841]
I'm not sure if the numpad Enter already has an "alias" inside Qutebrowser (just like the key binding [cheat sheet](https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/img/cheatsheet-big.png), a cheat sheet for available keys for remapping would be nice, but even Vim is lacking in this domain to be fair).

Essentially, is there a notation for the numpad Enter so that `c.bindings.key_mappings` could make <kbd>Enter</kbd> be mapped to <kbd>Numpad-Enter</kbd>?

**Comment by The-Compiler** [comment]
See https://doc.qt.io/qt-5/qt.html#Key-enum - `Enter` is numpad enter, while the other one is `Return`.

**Comment by manoelpqueiroz** [comment]
Perfect, thanks for bothering with such a trivial thing, @The-Compiler, keep up the good work with this phenomenal browser!
