### ISSUE TITLE
icu, qt5-webengine and qt5-base updates break qutebrowser

### ISSUE THREAD

**Issue by ctty11** [qutebrowser/qutebrowser#6842]
This is the latest version, 2.4.0 on Obarun/Arch. Sorry, can't the full version info since qb doesn't launch.

```
~/.local/share/qutebrowser » cat state                                                                                                                 1
[general]
qt_version = 5.15.2
qtwe_version = 5.15.7
version = 2.4.0
serviceworker_workaround = 514
session-warning-shown = 1
quickstart-done = 1
contact-info = 

[inspector]
```

Today's updates, specifically, icu, qt5-webengine and qt5-base break qutebrowser. The browser is looking for old versions. Maybe time to make another release? :)

**Comment by The-Compiler** [comment]
This is very likely to be an issue on your system, and not in qutebrowser. What exactly does "break" mean?

**Comment by ctty11** [comment]
Later update on qt5-base (5.15.2+kde+r259-2) fixed the problem. Never mind.
