### ISSUE TITLE
Renderer process crashed on Airbnb.com

### ISSUE THREAD

**Issue by sudoforge** [qutebrowser/qutebrowser#6851]
**Version info**:
```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

```
➜ qutebrowser --temp-basedir https://www.airbnb.com/s/San-Francisco--CA--United-States/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_dates%5B%5D=december&flexible_trip_dates%5B%5D=january&flexible_trip_lengths%5B%5D=weekend_trip&date_picker_type=calendar&query=San Francisco%2C CA%2C United States&place_id=ChIJIQBpAG2ahYAR_6128GcTUEo&checkin=2021-12-01&checkout=2021-12-31&adults=1
11:54:45 ERROR: Renderer process crashed (status 139)
```

**Description**

I am unable to load and/or interact with any page on Airbnb containing search results or a unit location. Specifically, the page appears to load (partially or fully), but within 0-2s, the renderer process crashes.

**How to reproduce**

Run the following command in a terminal.

```
qutebrowser --temp-basedir https://www.airbnb.com/s/San-Francisco--CA--United-States/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_dates%5B%5D=december&flexible_trip_dates%5B%5D=january&flexible_trip_lengths%5B%5D=weekend_trip&date_picker_type=calendar&query=San Francisco%2C CA%2C United States&place_id=ChIJIQBpAG2ahYAR_6128GcTUEo&checkin=2021-12-01&checkout=2021-12-31&adults=1
```

---

Please note that the search URL provided was created for this issue; the same issue occurs with absolutely any other search terms, or on a direct link to a location's page.

---

Because it may be useful to know for debugging purposes:

```
➜ uname -srvm
Linux 5.15.4-arch1-1 #1 SMP PREEMPT Sun, 21 Nov 2021 21:34:33 +0000 x86_64
```

**Comment by sudoforge** [comment]
Various bits of debugging that may or may not be useful:

* With `qt.workarounds.remove_service_workers` set to true, the issue persists.
* The process has unbound resource caps, and my machine is not anywhere near hitting a resource cap
* This has been happening for some number of weeks, maybe a couple of months. I apologize that I didn't take a note when it first started happening; this isn't a high priority issue for me.

**Comment by sudoforge** [comment]
![20211127T122522674](https://user-images.githubusercontent.com/3893293/143719974-2583a882-5c78-4e27-9b63-b2d67f109cc6.png)

Interestingly, I do notice core spikes (topped at ~80% on first load) that lead to the renderer process crashing. Overall CPU and memory utilization for `QtWebEngineProc` and `Qutebrowser` goes up a bit, but nowhere near the available resources on my machine.

**Comment by toofar** [comment]
Well I can reproduce easily enough. And it doesn't happen with javascript disabled! But the site doesn't really work like that. Seems to work fine on Qt6 ;) Maybe it is calling some half implemented fancy new JS API.

Here's a stack trace from 5.15.6, says something about CSS but not sure if it is useful.
<details><summary>collapsed stack trace</summary>

<code><pre>
#0 0x7f7e1d89a90d base::debug::CollectStackTrace()
#1 0x7f7e1d6d5479 base::debug::StackTrace::StackTrace()
#2 0x7f7e1d6d5430 base::debug::StackTrace::StackTrace()
#3 0x7f7e1d899529 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#4 0x7f7e15abbef0 (/usr/lib/x86_64-linux-gnu/libc-2.32.so+0x3ceef)
#5 0x7f7e1beab746 WTF::AtomicStringHash::GetHash()
#6 0x7f7e24bd8726 WTF::HashTable<>::insert<>()
#7 0x7f7e24bd8888 WTF::HashMap<>::Set<>()
#8 0x7f7e24bd4594 blink::PropertyRegistry::DeclareProperty()
#9 0x7f7e24bd4856 blink::PropertyRegistration::DeclareProperty()
#10 0x7f7e24c21f05 blink::StyleEngine::AddPropertyRules()
#11 0x7f7e24c21f4d blink::StyleEngine::AddPropertyRulesFromSheets()
#12 0x7f7e24c25887 blink::StyleEngine::ApplyRuleSetChanges()
#13 0x7f7e24c3ca7b blink::TreeScopeStyleSheetCollection::ApplyActiveStyleSheetChanges()
#14 0x7f7e24b51301 blink::DocumentStyleSheetCollection::UpdateActiveStyleSheets()
#15 0x7f7e24c25e7c blink::StyleEngine::UpdateActiveStyleSheets()
#16 0x7f7e24c2609e blink::StyleEngine::UpdateActiveStyle()
#17 0x7f7e20a618ae blink::Document::UpdateStyleAndLayoutTree()
#18 0x7f7e20c46a77 blink::LocalFrameView::UpdateStyleAndLayoutIfNeededRecursive()
#19 0x7f7e20c4747a blink::LocalFrameView::RunStyleAndLayoutLifecyclePhases()
#20 0x7f7e20c48a1a blink::LocalFrameView::UpdateLifecyclePhasesInternal()
#21 0x7f7e20c490da blink::LocalFrameView::UpdateLifecyclePhases()
#22 0x7f7e20c49201 blink::LocalFrameView::UpdateAllLifecyclePhases()
#23 0x7f7e21251080 blink::PageAnimator::UpdateAllLifecyclePhases()
#24 0x7f7e20bc7a9d blink::WebViewImpl::UpdateLifecycle()
#25 0x7f7e207f8e31 blink::WidgetBase::UpdateVisualState()
#26 0x7f7e1f95d356 cc::LayerTreeHost::RequestMainFrameUpdate()
#27 0x7f7e1fa029ac cc::ProxyMain::BeginMainFrame()
#28 0x7f7e1fa314dd base::internal::FunctorTraits<>::Invoke<>()
#29 0x7f7e1fa2abfa base::internal::InvokeHelper<>::MakeItSo<>()
#30 0x7f7e1fa22a99 _ZN4base8internal7InvokerINS0_9BindStateIMN2cc9ProxyMainEFvSt10unique_ptrINS3_28BeginMainFrameAndCommitStateESt14default_deleteIS6_EEEJNS_7WeakPtrIS4_EES9_EEEFvvEE7RunImplISB_St5tupleIJSD_S9_EEJLm0ELm1EEEEvOT_OT0_St16integer_sequenceImJXspT1_EEE
#31 0x7f7e1fa19e2d base::internal::Invoker<>::RunOnce()
#32 0x7f7e16b86d56 _ZNO4base12OnceCallbackIFvvEE3RunEv
#33 0x7f7e1d7c3def base::TaskAnnotator::RunTask()
#34 0x7f7e1d7ef584 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#35 0x7f7e1d7eeda6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#36 0x7f7e1d71163f base::MessagePumpDefault::Run()
#37 0x7f7e1d7efdb5 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#38 0x7f7e1d77b4c6 base::RunLoop::Run()
#39 0x7f7e21a5dac0 content::RendererMain()
#40 0x7f7e1c8d86d4 content::RunZygote()
#41 0x7f7e1c8d890d content::RunOtherNamedProcessTypeMain()
#42 0x7f7e1c8d92cb content::ContentMainRunnerImpl::Run()
#43 0x7f7e1c8d4ef4 content::RunContentProcess()
#44 0x7f7e1c8d500e content::ContentMain()
#45 0x7f7e16c1eed8 QtWebEngineCore::processMain()
#46 0x564f0b7be3f7 main
</pre></code>
</details>

**Comment by The-Compiler** [comment]
Thanks for the stacktrace, @toofar! Looks a lot like this: [1134550 - Reloading page crashes on applying @property changes - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1134550&q=blink%3A%3APropertyRegistry%3A%3ADeclareProperty&can=1)

I backported the fix to QtWebEngine: [[Backport] Copy 'name_' member during StyleRuleProperty::Copy (Ib2d5cf64) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/383624)

**Comment by The-Compiler** [comment]
Well, looks like nobody responded to my request for someone testing it over at Qt's codereview, so I submitted it now. Missed Qt 5.15.8 unfortunately, but I guess it'll be in .9 then.
