### ISSUE TITLE
Qutebrowser goes back into normal mode after page has been loaded

### ISSUE THREAD

**Issue by tamis-laan** [qutebrowser/qutebrowser#6854]
In all versions of qutebrowser so far when you open a new tab, for example `:open -t youtube.com` the tab goes into normal mode after the page has been loaded.

This is very annoying because when you browse to for example youtube, go into insert mode and start typing your search query, qutebrowser jumps back into normal mode during typing causing you to type commands instead of characters destroying half the stuff on screen. 

Although I have adjusted my behavior to this quirk it would be so nice it didn't happen.

**Comment by The-Compiler** [comment]
This is intended, but configurable via `input.insert_mode.leave_on_load`.

**Comment by tamis-laan** [comment]
> This is intended, but configurable via `input.insert_mode.leave_on_load`.

That is strange because when I open a new tab it opens in normal mode. The config `input.insert_mode.leave_on_load` implies a tab opens in insert mode and we want to leave it in insert mode...

Also might I ask what is the purpose of changing modes after the page is loaded?
