### ISSUE TITLE
Binding function keys doesn't work anymore

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#6859]
**Version info**:

qutebrowser v2.4.0
Git commit: 5e6bae398 on master (2021-12-03 15:58:48 +0100)
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

Yes, actually.

**Description**

I have the following two bindings:
```
:bind F4 macro-record m 
:bind F5 macro-run m 
```

Neither of them doesn't seem do what I tell them anymore, and <kbd>F5</kbd> just reloads the page.

If I run `:bind F5`, this returns `INFO: F5 is bound to 'macro-run m' in normal mode`.  My function keys seem to function normal otherwhise.

**How to reproduce**

```
:bind F4 macro-record m 
:bind F5 macro-run m 
```

Should do it?

**Comment by The-Compiler** [comment]
Those bindings never worked in the way you describe - they bind the keychains `F4` and `F5` (shadowed by `F` by default).

You want `<F4>` and `<F5>`, like with other special keys.
