### ISSUE TITLE
Not all hints shown on certain websites

### ISSUE THREAD

**Issue by ArbitRandomUser** [qutebrowser/qutebrowser#6864]
**Version info**:

qutebrowser v2.4.0
Git commit: a4213a4bb on master (2021-11-26 16:25:22 +0100)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes 

**Description**
not all the links on the side panel get hints on certain websites like 
https://learnopengl.com/
![hints](https://user-images.githubusercontent.com/58146965/144722357-306149b1-3aa2-4656-a073-167682e90eaf.png)

**How to reproduce**

https://learnopengl.com/

**Comment by The-Compiler** [comment]
Added to #178. Looks like the website uses `span` tags with a JS click handler, and does't mark them in a way qutebrowser could easily detect that they are elements an user can interact with.
