### ISSUE TITLE
Websites flicker on Wayland unless QT_WEBENGINE_DISABLE_WAYLAND_WORKAROUND is set

### ISSUE THREAD

**Issue by phrxmd** [qutebrowser/qutebrowser#6868]
**Version info**:
qutebrowser v2.4.0
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

This is with KDE Plasma 5.23.4 on Wayland on OpenSUSE TW.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Websites flicker white at irregular intervals if `QT_WEBENGINE_DISABLE_WAYLAND_WORKAROUND` is not set. 
It seems to be more frequent with JS-heavy sites (?)

**How to reproduce**
1. Open `mail.google.com` (click through to the login screen if Google shows you their ToS)
2. The login screen will flicker irregularly, e.g. sometimes when moving the mouse or pressing a key.

The flicker disappears when setting `QT_WEBENGINE_DISABLE_WAYLAND_WORKAROUND=1`.

**Comment by The-Compiler** [comment]
I doubt there is anything qutebrowser can do about this. Can you try with another browser based on QtWebEngine, such as KDE Falkon?

**Comment by phrxmd** [comment]
Indeed it happens in Falkon as well. Looks like an upstream issue.

We can close this here and leave it for documentation. What would be the best way to report this?

**Comment by The-Compiler** [comment]
`QT_WEBENGINE_DISABLE_WAYLAND_WORKAROUND` is nowhere to be found in the QtWebEngine codebase. It looks like it's coming from [some OpenSUSE patching](https://build.opensuse.org/package/view_file/KDE:Qt:5.15/libqt5-qtwebengine/disable-gpu-when-using-nouveau-boo-1005323.diff?expand=1). So you will need to report it to them I guess.

**Comment by The-Compiler** [comment]
Oh, though I suppose you would see the same issue with that set (i.e. disabling the workaround), but starting qutebrowser with `-{ qt.force_software_rendering chromium`. If that is the case, that would point to an issue with either QtWebEngine or Chromium. Next I would try then is reproducing in Chromium with `--disable-gpu`.
