### ISSUE TITLE
Keyhint widget is too small after recent qt5-base update

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6869]
[Via Reddit](https://www.reddit.com/r/qutebrowser/comments/rapdxk/small_bug_with_the_binding_hint_window/):

After upgrading from qt5-base-5.15.2+kde+**r260**-1 to [qt5-base-5.15.2+kde+**r262**-1](https://github.com/archlinux/svntogit-packages/commit/2fc59566650e3f569280e2da3c81c4ca99c5645e#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a), the keyhint widget size is wrong:

![image](https://user-images.githubusercontent.com/625793/145035072-8e3f4252-1453-4097-a873-2b57da181c79.png)

There were only two changes in the KDE Qt repository between the two versions: [Two fixes for table layouts (!85) · Merge requests · Qt Project / qt / qtbase · GitLab](https://invent.kde.org/qt/qt/qtbase/-/merge_requests/85)

Upstream changes:

- [Don't shrink a column when it spans multiple columns (Ic27dbdb1) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/382996)
- [Don't let text table cells shrink below their minimum width (Idf4ad015) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/383119)

Relevant bugs:

- [[QTBUG-91691] [REG: 5.15.0->5.15.1] QTextDocument tables with colspan collapses the starting column to minimum size - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-91691)
- [[QTBUG-95240] QTextTabel: column width changes when merging other rows - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-95240)
- [[QTBUG-86671] Table cells overlap with image and relative width - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-86671)
- [[QTBUG-97463] Showing Large image in QTextBrowser table overlaps - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-97463)

Our code:

[qutebrowser/keyhintwidget.py at master · qutebrowser/qutebrowser](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/misc/keyhintwidget.py)

cc @rcorre

**Comment by The-Compiler** [comment]
This seems enough to reproduce it:

```python
from PyQt5.QtWidgets import QApplication, QLabel, QWidget

app = QApplication([])

window = QWidget()

label = QLabel(window)
label.setText("<table><tr><td>hello</td><td>world</td></tr></table>")

window.show()
app.exec()
```

**Comment by rien333** [comment]
Fixed in Arch Linux's `qt5-base` 5.15.2+kde+r263-1 release. Think its this commit: https://github.com/archlinux/svntogit-packages/commit/841fb9ed8ecb8653d2105fbe123c50a2f56dbe7c#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a

**Comment by The-Compiler** [comment]
Yup, nothing for us left to do there!

**Comment by The-Compiler** [comment]
Someone reported in IRC that Fedora now apparently ships a Qt with this bug in? Not sure how that happened, but maybe worth another look then...

**Comment by mikecanann-upkeep** [comment]
I do not have that issue on a couple different machines running Fedora.

**Comment by The-Compiler** [comment]
Thanks for the update - I suppose Fedora has upgraded to something where this is fixed quite some while ago.
