### ISSUE TITLE
cursor/edit bindings for 'command' mode not implemented yet?

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [qutebrowser/qutebrowser#6870]
hi, I wasn't sure whether to file as a bug or feature request for
something that hadn't been implemented yet.

Essentially, I just want to be able to cursor/edit as I do in emacs,
and in other modes in qutebrowser ('insert' and 'normal' mode work).

The first 4 would be great; I can live without the rest, though having
everything would be best.

```
c.bindings.commands['command'] = {
    '<Ctrl-f>': 'fake-key <Right>',
    '<Ctrl-b>': 'fake-key <Left>',
    '<Ctrl-a>': 'fake-key <Home>',
    '<Ctrl-e>': 'fake-key <End>',
    '<Alt-f>': 'fake-key <Ctrl-Right>',
    '<Alt-b>': 'fake-key <Ctrl-Left>',
    '<Alt-d>': 'fake-key <Ctrl-Delete>',
    '<Ctrl-d>': 'fake-key <Delete>',
    '<Alt-backspace>': 'fake-key <Ctrl-Backspace>',
    '<Ctrl-w>': 'fake-key <Ctrl-backspace>',
}
```

Thanks! I <3 qutebrowser so much!

**Comment by The-Compiler** [comment]
I don't follow. Those bindings are already implemented, see `:bind` (though using the appropriate `rl-*` commands, not `fake-key`).

**Comment by tinglycraniumplacidly** [comment]
I'm an idiot. thanks for clarifying. found the relevant commands
https://www.ii.com/qutebrowser-configpy/
eg. `config.bind('<Alt-B>', 'rl-backward-word', mode='command')`

**Comment by The-Compiler** [comment]
Note that's a default binding already as well. Unless you're explicitly removing all default bindings, you don't need to bind it.

As for your earlier bindings: `fake-key` sends a key to the website. `fake-key -g` (global) might have worked, but the `rl-*` commands are much less of a hack.
