### ISSUE TITLE
Not reproducing videos on GDrive and pop-up about using a soon to be incompatible Chrome Version

### ISSUE THREAD

**Issue by Hello-Helo** [qutebrowser/qutebrowser#6872]
Recently I am having some problems watching some videos from Google Drive. I am able to download some but others I can not. I noticed a pop-up on GDrive saying "You are using an old version of Google Chrome that soon will be incompatible" (I am translating so in english it might be different) and i feel they may be related, but i don't have the knowledge to be sure. 

**Version info**:

```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.9
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.10.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 21.2.5
Platform: Linux-5.10.83-1-lts-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/hellohelo/.cache/qutebrowser
config: /home/hellohelo/.config/qutebrowser
data: /home/hellohelo/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/hellohelo/.config/qutebrowser/config.py has been loaded
Uptime: 6:24:06
```

**Does the bug happen if you start with `--temp-basedir`?**:

The videos won't reproduce as well but the pop-up is not there.

**How to reproduce**

Try to reproduce any video on Google Drive.

**Comment by The-Compiler** [comment]
What does "Recently I am having some problems watching some videos from Google Drive. I am able to download some but others I can not." or "reproduce any video" mean exactly?

As for the popup, nothing we can do immediately, but we'll support a newer QtWebEngine (and thus a newer Chromium) with Qt 6, see #5395.

**Comment by Hello-Helo** [comment]
Sorry for not been so specific. I am having remote lectures and they are made available as videos on GDrive shared drive, in the last few weeks, everytime I try watch the lectures, the video apears to be loading indefinitely. I have already waited for more then an hour and it does not appear to be the internet because videos on other plataforms loads without any issue. It happens to every video on the GDrive. 

Thank you for the information about the pop-up!

**Comment by The-Compiler** [comment]
Do you see anything in the `:devtools` console when it happens? I'm not sure I understood above: Does the video issue happen with `--temp-basedir` too or not?

**Comment by The-Compiler** [comment]
@Hello-Helo any update on this?

**Comment by Hello-Helo** [comment]
The problem is not ocurring anymore, I don't remember exactaly what happened to fix but this is no longer relevant. Thank you for the attention
