### ISSUE TITLE
No picture in picture mode available?

### ISSUE THREAD

**Issue by MoritzISE** [qutebrowser/qutebrowser#6873]
i wanted to use youtube in picture in picture mode, but i didn't see the feature in the icon row on youtube, does anyone have a solution for this problem?

**Comment by The-Compiler** [comment]
QtWebEngine doesn't support it - see [[QTBUG-82390] Support "picture in picture" mode for videos - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-82390)
