### ISSUE TITLE
using command ":open -w" from terminal opens 2 windows

### ISSUE THREAD

**Issue by LamprosPitsillos** [qutebrowser/qutebrowser#6874]
**Version info**:
```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.9
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.10.0
yaml: 6.0
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.11.338 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021
```
**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

https://user-images.githubusercontent.com/61395246/145490301-e1e7aaa8-b6a5-4f60-b162-14b4cdcb5c0c.mp4

If you call qutebrowser with `:open -w anything` it will open a default window to then open another window with the query you gave it. This doesn't happen if there is an active instance of qutebrowser.

**How to reproduce**
Have no instance of Qutebrowser running
Run in the terminal `:open -w anything`

**Comment by toofar** [comment]
Try `--target window` instead (see `qutebrowser --help`).

**Comment by The-Compiler** [comment]
This is intended. You're opening qutebrowser (thus opening a new window), and then telling it to open another window. It's the same thing as if you'd run that command from qutebrowser's command line.
