### ISSUE TITLE
Having issues when login into mega.io (MEGAsync)

### ISSUE THREAD

**Issue by imalightbulb** [qutebrowser/qutebrowser#6877]
**Version info**:

idk if it means the following text, please notify me if extra info is required
```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
Nope

**Description**
1. Login into MEGAsync (enter email and password)
2. Loading
3. The following pop-up occurs
![image](https://user-images.githubusercontent.com/66677431/145496622-d27ad318-43ae-48a5-9ee2-f1a10b1f6201.png)

4. Choose either option, the screen stucks at the loading page (which dosent happen when start qutebrowser with `--temp-basedir`)
![image](https://user-images.githubusercontent.com/66677431/145496693-0dd2f184-3874-44df-8da1-87da29f68093.png)

**How to reproduce**

The steps to reproduce the issue is stated in the description, link for the website: https://mega.nz

**Comment by toofar** [comment]
> IndexedDB corruption
> doesn't happen in temp basedir

huh, I guess it might be corrupted. I'm not sure if that means:

1. whole DB needs to go
2. stuff that mega is reading successfully is not what it expects
3. something else

For (2) you can probably open :devtools and go Application. IndexedDb while on that site and clear whatever is there then reload (I guess, I don't think I've ever used a site that used indexeddb)

For (1) the DB is probably in data/webengine somewhere and you could delete it while qute was closed

**Comment by imalightbulb** [comment]
Thanks @toofar, it worked after following this:

> For (2) you can probably open :devtools and go Application. IndexedDb while on that site and clear whatever is there then reload (I guess, I don't think I've ever used a site that used indexeddb)
