### ISSUE TITLE
Feature request: generate QR code of current URL

### ISSUE THREAD

**Issue by tidux** [qutebrowser/qutebrowser#6889]
One of the more popular features of Firefox and Chrome is their ability to send a tab to a mobile device.  The way they do this is via a centralized cloud sync service, which is obviously well out of scope, but generating a QR code of the page URL for someone to scan with their phone would do 80% of the job with a tiny fraction of the effort.  The key "Q" appears to be unbound by default in Qutebrowser, so it could be bound to pop up a dialogue (like the download dialogue) with the URL QR code, with Esc to clear the popup.

**Comment by toofar** [comment]
We probably could add that to the core if there was enough interest. For now there is userscripts like https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qr
That one writes to a file and opens it in qutebrowser but you can also make one that pipes into display if you want a floating window (eg `qrencode -o - -s 9 "$1" | display`).

**Comment by The-Compiler** [comment]
Yep, I don't really see a reason for this to built in, especially because we don't have anything capable of generating QR codes in the code or dependencies so far.
