### ISSUE TITLE
Problem loading PyQt5 after this mornings update. 

### ISSUE THREAD

**Issue by TillDiem** [qutebrowser/qutebrowser#6891]
**Version info**:
Most current version in the AUR. Can't post the `qutebrowser :version` output, since qutebrowser won't start. Same for qutebrowser -version. 

**Does the bug happen if you start with `--temp-basedir`?**:
Yes. 

**Description**
After an update of all the packages to python 3.10 this morning via paru, qutebrowser won't start. 
Instead, it spits out the attached error message. 
I removed and reinstalled qutebrowser from the AUR, the problem still persists. 
I installed qutebrowser using makepkg, the error still persists. 
The current python version is `Python 3.10.1`. 
The problem persists both with `python-pyqt5-webengine 5.15.5-3` and `python-pyqt6-webengine 6.2.1-2`. 
Both are installed via the AUR. 

The error message point to:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qutebrowser/misc/earlyinit.py", line 137, in check_pyqt
    importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

**How to reproduce**
Install qutebrowser from the AUR with an update to python 3.10. 

![pic-selected-211214-1027-35](https://user-images.githubusercontent.com/65651721/145972326-f1f1058f-4c69-44ff-811b-521a916d092b.png)

**Comment by The-Compiler** [comment]
If you install PyQt from the AUR, you are responsible for rebuilding it on a Python version upgrade.

**Comment by TillDiem** [comment]
I installed PyQt from the AUR to check if this problem persists. 
Initially, I just installed qutebrowser from the AUR, which broke.
