### ISSUE TITLE
add command to yank domain/host only

### ISSUE THREAD

**Issue by benedikt-bartscher** [qutebrowser/qutebrowser#6899]
I often need to yank the domain of the current opened page in qutebrowser. I am aware of `:yank domain` but according to the documentation it yanks more than the domain part:
"domain: The current scheme, domain, and port number."

Example: Go to https://www.google.com/search?q=test and execute `:yank domain` or type the shortcut yd. You end up having https://www.google.com in your clipboard.

I can imagine multiple ways to implement this:
- Add the command  `:yank base_url`  to replace `:yank domain` which now only returns the domain part (this would force all users to change their current config)
- Add the command  `:yank host` which only returns the domain part
- Allow to pass input to `:yank`. For example `:yank --input {url:host}`

**Comment by The-Compiler** [comment]
> * Allow to pass input to `:yank`. For example `:yank --input {url:host}`

`:yank inline` lets you do exactly that - see e.g. the default `ym` binding, which is bound to `yank inline [{title}]({url})`.

**Comment by benedikt-bartscher** [comment]
Thank you so much for your incredible fast response time and for this great piece of software!
