### ISSUE TITLE
qute:///help/stacktrace.html page borked/missing

### ISSUE THREAD

**Issue by Theory-of-Everything** [qutebrowser/qutebrowser#6900]
**Version info**:

This is the first block from running :version
```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.10.1
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: no
jinja2: 3.0.3
pygments: no
yaml: 5.4.1
adblock: 0.5.1
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.11.338 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 2.1 Mesa 21.3.1
Platform: Linux-5.15.10-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/theorytoe/.cache/qutebrowser
config: /home/theorytoe/.config/qutebrowser
data: /home/theorytoe/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/theorytoe/.config/qutebrowser/config.py has been loaded
Uptime: 2:04:50
```

I am currently running Arch on a Thinkpad T400 (2008/2009 model)
This is also a fresh install (Just about 2 days ago), so everything on this system is fresh packages/libraries.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes, This issue occurs when passing in the `--temp-basedir` flag/option

**Description**
The `qute:///help/stacktrace.html` is missing/borked. I have no actual segfault reports, I was just poking around the help page around and found this issue.
Regardless of how I run qutebrowser, this issue always happens.
The page does not load, and I get this particular error code: `ERR_FILE_NOT_FOUND`

As another note: this issue also occurs on my other pc as well, so I would assume that is is a qutebrowser issue and not something off with my system. (if you want those specs to I can follow up)

**How to reproduce**

- run `:help`
- follow the link "Reporting Segfaults" (or page `qute:///help.stacktrace.html`)
- page missing (error: `ERR_FILE_NOT_FOUND`)

**Comment by The-Compiler** [comment]
Note that both `qute:///help/stacktrace.html` and `qute:///help.stacktrace.html` are indeed incorrect - but indeed even the correct link (`qute:///help.stacktrace.html`) does not work. Neither does the "installing qutebrowser" one.

**Comment by Theory-of-Everything** [comment]
oops, I just realized that `qute:///help` (triple slash) probably was a typo on my end.

Regardless, those links don't work, along with the "Installing qutebrowser" link you mentioned. (On both systems too)
I haven't installed qutebrowser from Arch's Aur, so I don't think it would be a packaging issue. It could be though, so I may try it on a few other distros just to see.
