### ISSUE TITLE
default text color if unset

### ISSUE THREAD

**Issue by binex-dsk** [qutebrowser/qutebrowser#6902]
like "colors.webpage.bg", but for text

Sometimes a page will have no set background color but also no set text color. I have my "colors.webpage.bg" set to #000000. However, the text color itself also defaults to black, making it invisible unless I turn on my CSS stylesheet which changes the text to gray. So I'd like to have a setting, named something like "colors.webpage.text" which sets the default text color, so that I could also default it to white/gray like I do in my CSS stylesheet.

**Comment by The-Compiler** [comment]
No such setting exists in QtWebEngine (and, to my knowledge, in Chromium), so the only way to override this is via a CSS stylesheet indeed.
