### ISSUE TITLE
Add (optional and variable) delay to audio indicator in tab title

### ISSUE THREAD

**Issue by alrasch** [qutebrowser/qutebrowser#6904]
**Problem**

If a tab is playing audio that often has short silences (for instance someone speaking, and their audio setup is good and noiseless), then the `[A]` audio indicator in the tab title will toggle very often, and shift the title back and forth very rapidly. This causes an annoying "flicker" in the user's peripheral vision.

**Proposed solution**

Allow the user to set an optional variable delay on removing `[A]` from the tab title.

Example: `:set tabs.audio_indicator.delay 3` to set a 3-second delay on removing `[A]` when there's a silence.

Alternatively it could be measured in milliseconds.

**Comment by The-Compiler** [comment]
See #6750.

Such a 2s delay used to be hardcoded in the underlying Chromium earlier, and AFAIK nobody did mind about it not being configurable. Do you think there really is a need for it to be? cc @lyeoh

**Comment by alrasch** [comment]
I think avoiding the constant toggling is a QoL feature for sure. A high priority one? Of course not. Just a wishlist item.

**Comment by The-Compiler** [comment]
The 2s delay as implemented in git master already does that.

**Comment by alrasch** [comment]
Oh my bad, I missed the link to #6750.

Yeah, if there's a 2 second delay already, making it variable is just nitpicking. Closing this issue. Thanks for the feedback!
