### ISSUE TITLE
Discord bug microphone

### ISSUE THREAD

**Issue by MoritzISE** [qutebrowser/qutebrowser#6911]
when I open up discord in the browser, I'm able to see everything, but when I want to activate my microphone to talk, nothing happens, I tried it in firefox, there it works just fine.

**Comment by The-Compiler** [comment]
What Qt version, backend and qutebrowser version? Can you reproduce with `--temp-basedir`?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by MoritzISE** [comment]
the same error occurred when I opened qutebrowser --temp-basedir 
after clicking Y for allowing the microphone access, there is no more interaction betewwn me and the unmute button, I can click and nothing happens.
I use arch linux


qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.10.1
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.10.0
yaml: 5.4.1
adblock: 0.5.1
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.12.313 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1m  14 Dec 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 21.3.2
Platform: Linux-5.15.10-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/moritz/.cache/qutebrowser
config: /home/moritz/.config/qutebrowser
data: /home/moritz/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/moritz/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00

**Comment by nkidis2cool** [comment]
What fixed this? I’m having same issues but not even working in Firefox. I’ve tried to override flatpak/flatseal, chown, and reinstall. But no avail.
