### ISSUE TITLE
Black new pages in dark mode

### ISSUE THREAD

**Issue by Andonome** [qutebrowser/qutebrowser#6912]
When in dark mode and opening a new page, the new page flashes white before it loads.

Specifically, I'm referring to:

> set colors.webpage.darkmode.enabled

I can get rid of this by setting the universal background colour to black, but this makes some pages unreadable. It'd be nicer to just have each new page display as black. In fact, I don't think light-mode readers would really object to new pages beginning as black, and rendering whatever they may be afterwards.

**Comment by The-Compiler** [comment]
This is coming from the underlying QtWebEngine/Chromium, there isn't really anything qutebrowser can do about it. For a possible workaround, see https://github.com/qutebrowser/qutebrowser/issues/5394#issuecomment-640583808.
