### ISSUE TITLE
Color depth issues on Wayland

### ISSUE THREAD

**Issue by kisik21** [qutebrowser/qutebrowser#6916]
**Version info**:
<details><summary>Click here to open</summary><pre><code>qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.3

CPython: 3.9.6
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: no
jinja2: 3.0.2
pygments: 2.10.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: 2.8.335 (/nix/store/z5n6n43w80lh2p2pfp694q38chlrmnl0-pdfjs-2.8.335/build/pdf.js)
sqlite: 3.36.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: Adwaita::Style
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 21.2.5
Platform: Linux-5.10.81-x86_64-with-glibc2.33, 64bit
Linux distribution: NixOS 22.05 (Quokka) (nixos)
Frozen: False
Imported from /nix/store/n2zhlvgbd6680igd6y1by4xp80zyv69x-qutebrowser-2.4.0/lib/python3.9/site-packages/qutebrowser
Using Python from /nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/bin/python3.9
Qt library executable path: /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3/libexec, data path: /nix/store/3qmcivc291ddcdvail2y0nl1l3vfpjwd-qtbase-5.15.3

Paths:
cache: /home/vika/.cache/qutebrowser
config: /home/vika/.config/qutebrowser
data: /home/vika/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /nix/store/n2zhlvgbd6680igd6y1by4xp80zyv69x-qutebrowser-2.4.0/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:03</code></pre></details>

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Qutebrowser on Wayland (i'm using Sway) seems to have troubles with color depth. This is specific to Qutebrowser, as Google Chrome (as a Chromium-based browser), Gwenview (as another Qt app) and Eye of Gnome (a GTK+ app) (all three on Wayland in the same Sway session, verified that Xwayland is not running) AND qutebrowser via XWayland do not have those color depth issue.

I'd blame it on Qt, but KDE's Gwenview looks fine with the same image I tested. The same seems to happen on `wayland-egl`.

**How to reproduce**
Launch qutebrowser on Sway on wayland. Try to view an image or a YouTube video. Observe color depth issues on gradients (is it called dithering?)

**Comment by The-Compiler** [comment]
Do you have a screenshot? Is this the same as #5528?

**Comment by kisik21** [comment]
Yes, and the problem was in fact solved by enabling windowdecorations using `QT_WAYLAND_DISABLE_WINDOWDECORATION=0`. Thanks for pointing it out. Closing.

**Comment by kisik21** [comment]
While this particular issue is closed, it looks like whoever had this issue last didn't report this to upstream and I couldn't find similar issues on the Qt bugtracker. Should I try registering on Qt bugtracker and reporting it myself?

**Comment by The-Compiler** [comment]
That'd be great! Please also post a link here once you reported it there.

**Comment by kisik21** [comment]
Done: https://bugreports.qt.io/browse/QTBUG-99473
