### ISSUE TITLE
Qutebrowser displays colored rectangles. Maybe another Sway/Wayland error?

### ISSUE THREAD

**Issue by Brixy** [qutebrowser/qutebrowser#6918]
```
qutebrowser v2.4.0
Git commit:
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

OS: Void Linux with Wayland and Sway window manager
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Hi folks.

Qutebrowser regularly displays the colored rectangles as attached. Occasionally these rectangles are black and often the browser view port is entirely white. All in all qutebrowser reacts kind of less responsive than it did.

These errors occur when a page is loaded, when you scroll down or resize a page. The display error will disappear when you scroll just a bit e.g. using `j` oder `k` keys.

The errors first appeared perhaps three weeks ago which is why I think it’s probably a Linux or Wayland or Sway error. Yet, I have not noticed that any other program is affected.

![sc](https://user-images.githubusercontent.com/1643010/147480003-05361355-b4ed-4398-a457-30ba237519ba.png)

**Comment by The-Compiler** [comment]
Intel graphics? Most likely a duplicate of #6879.

**Comment by Brixy** [comment]
Thanks a lot! I did not find the issue you referenced despite searching.

Yes, I use the `mesa`, so it’s probably related.

Closing here.
