### ISSUE TITLE
Jitsi can't hear participants joining after me

### ISSUE THREAD

**Issue by ura43** [qutebrowser/qutebrowser#6919]
**Version info**:
https://paste.the-compiler.org/view/1ee2dc74

**Does the bug happen if you start with `--temp-basedir`?**:
no

**Description**
In jitsi meet I can't hear participants joining after me, resulting in the slight annoyance of me having to leave and reenter meetings if I'm not the last one to join.

**How to reproduce**
Since the bug doesn't happen with `--temp-basedir` I suspect it is a sideeffect of [my configuration](https://github.com/ura43/dot/blob/main/dots/.config/qutebrowser/config.py
). 
The config file disregarding fonts, colors and additional keybindings contains the following:

```
config.load_autoconfig(True)

c.changelog_after_upgrade = 'patch'
c.completion.cmd_history_max_items = 0
c.completion.shrink = True
c.completion.timestamp_format = '%H:%M %d.%m'
c.completion.web_history.max_items = 1000
c.confirm_quit = ['downloads']
c.content.autoplay = False
c.content.canvas_reading = False
c.content.cookies.accept = 'all' #teams need 3rdparty cookies
c.content.cookies.store = False
c.content.fullscreen.overlay_timeout = 0
c.content.geolocation = False
c.content.mouse_lock = False
c.content.webrtc_ip_handling_policy = 'default-public-interface-only'
c.downloads.location.prompt = False
c.downloads.location.directory = "~/dl"
c.downloads.remove_finished = 1000
c.input.forward_unbound_keys = 'none'
c.input.insert_mode.auto_load = True #experimental
c.keyhint.delay = 0
c.new_instance_open_target = 'tab-bg-silent'
c.qt.low_end_device_mode = 'never'
c.scrolling.bar = 'never'
c.statusbar.widgets = ['keypress', 'scroll', 'progress'] #experimental
c.tabs.close_mouse_button = 'none'
c.tabs.indicator.width = 0
c.tabs.last_close = 'default-page'
c.tabs.new_position.related = 'last'
c.tabs.undo_stack_size = 10

c.url.default_page = 'https://start.duckduckgo.com/'
c.url.start_pages = ['https://start.duckduckgo.com']

```
I will close this issue if I don't find a solution in 7 days or no flaw in the configuration gets found.
I of course will comment what I believe to be the solution if I can solve this issue.
I might also open a bug at jitsi or qtwebengine if this might be an upstream problem.

**Comment by The-Compiler** [comment]
This is indeed very unlikely to be a qutebrowser issue. My bet would be on `c.content.autoplay`. If it's not that, probably one of the other `content.*` options.

**Comment by ura43** [comment]
It actually was `c.content.autoplay` :flushed:

**Comment by The-Compiler** [comment]
I'm guessing if you start a new Chromium instance with `--autoplay-policy=user-gesture-required`, you will see the same issue too. Might not be a bug though...
