### ISSUE TITLE
qutebrowser does not load webpages after startup, needs restart

### ISSUE THREAD

**Issue by balejk** [qutebrowser/qutebrowser#6926]
**Version info**:

```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.10.1
PyQt: 5.15.5

sip: 6.1.0.dev2104271705
colorama: no
jinja2: 3.0.3
pygments: no
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.3.2
Platform: Linux-5.15.12_1-x86_64-with-libc, 64bit
Linux distribution: void (void)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When I attempt to start `qutebrowser`, it shows a blank white screen instead of the webpage (components of UI are visible and responsive). Window title bar progress is stuck at 0 % (sometimes 10 %). Debugging output seems to indicate that it's stuck in `cur_load_started()` - last line of the output is
```
DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 0)
```
It is possible to call `:open`, but the only result is a change of the window title. Upon quitting, four processes remain running in the background - three times `/usr/lib/qt5/libexec/QtWebEngineProcess --type=zygote --application-name=qutebrowser --webengine-schemes=qute:lL;qrc:sLV --lang=en` (one of them additionally with the `--no-zygote-sandbox` flag) and once `/usr/bin/python3 /bin/qutebrowser` - the Qt ones exit upon SIGTERM, the qutebrowser one does not respond to anything but SIGKILL.

**How to reproduce**

Launch `qutebrowser`. Successful startup is seen maybe once in every three attempts.

I'm running Void Linux with musl libc and I suspect the problem might be related to that.

**Comment by The-Compiler** [comment]
I doubt this is something qutebrowser can fix, it sounds more like an issue with the underlying QtWebEngine. Could you check whether you can reproduce this with another browser using QtWebEngine, such as KDE Falkon?

**Comment by balejk** [comment]
I tried both Falkon and Otter Browser with QtWebEngine based Blink web engine backend, but I have been able to to get just one suspicious startup with Otter, otherwise these seem to work fine. But I agree that the problem likely stems from the backend. Do you have any ideas what else I could try? Or at least where to look for errors - I'm not quite sure what I would report to QtWebEngine developers now. I'm also a bit puzzled as to why there always remains one unresponsive qutebrowser process.

**Comment by The-Compiler** [comment]
No idea I'm afraid. Note that neither QtWebEngine nor the underlying Chromium support musl, so https://github.com/void-linux/void-packages/issues/34797 might indeed be the right place to report this (note that Void Linux has [a lot of custom patching](https://github.com/void-linux/void-packages/tree/master/srcpkgs/qt5-webengine/patches) for musl).

**Comment by balejk** [comment]
I understand, I'll follow the Void issue then. Thank you. Shall I leave this open or close it?

**Comment by The-Compiler** [comment]
I'd prefer closing this, as I really don't think there's anything qutebrowser can do here - sorry!
