### ISSUE TITLE
"not enough values to unpack" in notifications _get_server_info

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6931]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/webengine/notification.py", line 264, in present
    self._init_adapter()
  File "/usr/lib/python3.10/site-packages/qutebrowser/config/config.py", line 134, in meth_wrapper
    return func(wrapper_self)
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/webengine/notification.py", line 217, in _init_adapter
    self._adapter = candidate()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/webengine/notification.py", line 769, in __init__
    self._get_server_info()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/webengine/notification.py", line 855, in _get_server_info
    name, vendor, ver, spec_version = reply.arguments()
ValueError: not enough values to unpack (expected 4, got 1)
```

3 reports by 2 people so far:

- https://crashes.qutebrowser.org/view/5385c45c
- https://crashes.qutebrowser.org/view/4f282493
- https://crashes.qutebrowser.org/view/7aece3ff
- See https://crashes.qutebrowser.org/lists?search=not+enough+values+to+unpack

Not sure why, as we're checking the DBus signature before...

**Comment by The-Compiler** [comment]
Got another report for this by @joshzcold - finally someone I can ask some questions about this! :wink: 

- Can you reproduce this by going to the same website again?
- What WM/desktop environment are you on?
- What's the output of this? `dbus-send --dest=org.freedesktop.Notifications --print-reply /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation`

Thanks!

**Comment by joshzcold** [comment]
first time I hit "report" on a crash report and someone gets back to me lol.

**dbus output:**
```
method return time=1641496708.390270 sender=:1.2 -> destination=:1.57 serial=21 reply_serial=2
   string "dunst"
   string "knopwob"
   string "1.7.3 (2021-12-08)"
   string "1.2"
```
**WM:** dwm

I am currently on a different computer with the same setup (dwm, dunst, arch, .conf files, etc) and I can't reproduce on google calendar. When I get the chance ill give this another try on the computer that crashes.

**Comment by The-Compiler** [comment]
Hm, weird. I use dunst myself too and never had this issue myself.

**Comment by joshzcold** [comment]
Okay so just reproduced this problem on my machine that actually does crash. 
`dbus-send --dest=org.freedesktop.Notifications --print-reply /org/freedesktop/Notifications org.freedesktop.Notifications.GetServerInformation` 
basically just hangs. 
along with `notify-send` 

I assume this crash it tied to something along the lines of.
a notification daemon is registered on this machine, but isn't actually sending a message. 

So I would guess you need some error handling for when the notification sending just doesn't work because of the environment

**Comment by joshzcold** [comment]
![2022-01-07 12:34:01](https://user-images.githubusercontent.com/36175703/148597701-7389eab3-b07b-4f3d-9715-e7f96316f1ac.gif)

**Comment by joshzcold** [comment]
If I see this crash again and my notifications on dunst are working manually then ill report back

**Comment by The-Compiler** [comment]
Well, that's the weird thing: Just [before the line that crashes](https://github.com/qutebrowser/qutebrowser/blob/v2.4.0/qutebrowser/browser/webengine/notification.py#L854-L855), we call [`_verify_message`](https://github.com/qutebrowser/qutebrowser/blob/v2.4.0/qutebrowser/browser/webengine/notification.py#L887-L922) which ensures that the reply we got is, according to Qt, not an error and in the expected format...

After staring at the code a bit, I have an idea of what's happening:

- The error is probably `org.freedesktop.DBus.Error.NoReply`, which is one of our [expected errors](https://github.com/qutebrowser/qutebrowser/blob/v2.4.0/qutebrowser/browser/webengine/notification.py#L706-L718)
- We handle this by [emitting the `error` signal](https://github.com/qutebrowser/qutebrowser/blob/v2.4.0/qutebrowser/browser/webengine/notification.py#L902-L906)
- But if we're still initializing the notification adapter, that [gets ignored](https://github.com/qutebrowser/qutebrowser/blob/v2.4.0/qutebrowser/browser/webengine/notification.py#L406-L408)
- Thus, `_verify_message` [returns](https://github.com/qutebrowser/qutebrowser/blob/v2.4.0/qutebrowser/browser/webengine/notification.py#L906) (added [here](https://github.com/qutebrowser/qutebrowser/commit/356a170ce30e94e42534ecbded402af852c5a67d#diff-27420b97dd0a23b86a8e37b0f0eb3960fa75bd411e0e325234e14798d0686845R294)),
- `_get_server_info` [continues to run](https://github.com/qutebrowser/qutebrowser/blob/v2.4.0/qutebrowser/browser/webengine/notification.py#L855) and fails.

**Comment by The-Compiler** [comment]
Reproduced with:

`killall -SIGSTOP dunst && python3 -m qutebrowser --temp-basedir -s content.notifications.enabled true https://www.bennish.net/web-notifications.html ":later 2000 jseval -q --world main notify.authorize()" ":later 3000 jseval -q --world main notify.show()"`

I don't see `_on_adapter_error` being called at all, but other than that it seems spot-on.

**Comment by The-Compiler** [comment]
This now seems to manifest in a different way since 3a09126e2ea8280a0b0635be246eafa27377f5cc with v2.5.1:

```
20:48:43 ERROR    message    message:error:60 Notification error from libnotify adapter: Created too many similar notifications in quick succession
20:48:43 DEBUG    misc       notification:_drop_adapter:387 Dropping adapter libnotify
20:48:43 ERROR    misc       crashsignal:_handle_early_exits:241 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/webengine/notification.py", line 270, in present
    notification_id = self._adapter.present(
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/webengine/notification.py", line 1023, in present
    if notification_id <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
```

See https://crashes.qutebrowser.org/view/e961277d and https://crashes.qutebrowser.org/lists?search=not+supported+between+instances+of

I suppose we should instead still have `validate_args` raise an exception for known errors, but perhaps catch it somewhere different? Or maybe return a return value and make sure all callers actually read it...
