### ISSUE TITLE
quickmark-load (or bookmark-load) should select the first suggestion by default

### ISSUE THREAD

**Issue by dnaik42** [qutebrowser/qutebrowser#6935]
It would be much faster if, when I've typed the first few letters of a quickmark name after pressing b, instead of pressing tab and then enter, just pressing enter would open the first quickmark in the list. Pressing tab should cycle through the remaining suggestions in the list. Please add the option to implement this in either quickmarks or bookmarks.

**Comment by The-Compiler** [comment]
See #5358, #3877 and #711.
