### ISSUE TITLE
qb dont show text

### ISSUE THREAD

**Issue by flusq** [qutebrowser/qutebrowser#6942]
qb doesn't always show text. (github, google), but shows in ddg or youtube 
![image](https://user-images.githubusercontent.com/39746872/148304564-84aaf992-8971-4411-b09c-8bedb0285380.png)
![image](https://user-images.githubusercontent.com/39746872/148304569-bc986a5e-0b7d-474d-9be5-eb9a3aa86922.png)
![image](https://user-images.githubusercontent.com/39746872/148304580-eeb921e7-f210-4dff-ab97-41397e5363db.png)

info:
![image](https://user-images.githubusercontent.com/39746872/148304971-0a6fc39e-36e2-43aa-a65d-2bb91478d423.png)
use guix system. install qb from repos

**Comment by toofar** [comment]
Hmm, nothing jumps to mind.

The bug report template say

> Does the bug happen if you start with `--temp-basedir`?

Can you try and see if things look more normal when run like that? If so it is probably something to do with your config.

Otherwise, uh, try looking in the developer tools and seeing if you can spot any issue or any commonality between the invisible text?

**Comment by The-Compiler** [comment]
It's [an issue in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1164975) when being run with glibc 2.33.

The fix [landed in QtWebEngine](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/374232) back in October, but unfortunately, Guix apparently didn't update their QtWebEngine nor backport the patch so far: [qutebrowser 2.4.0 text rendering broken](https://issues.guix.gnu.org/52672). Note that it [doesn't only affect qutebrowser](https://issues.guix.gnu.org/52993), but anything using QtWebEngine.

As a workaround, you can add `disable-seccomp-filter-sandbox` to the `qt.args` setting, but note that doing so will disable one of Chromiums [security sandboxing layers](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux/sandboxing.md).
