### ISSUE TITLE
identical values in attribute “title”: tooltip does not move.

### ISSUE THREAD

**Issue by Booze-Operator** [qutebrowser/qutebrowser#6945]
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

Good afternoon.
When two elements on a (xhtml) page **share the value of a title attribute**, moving the mouse pointer from one to the other does not erase the first “tool-tip” (whatever you call it), nor show a new one over the later element. This appears to indicate that qutebrowser internally waits for the value to change before it will react as expected by creating a tool-tip over the element.

This is anything but important, but if you happen to see the code, PSE correct. The phenomenon is only showing where two such elements are close enough to each other to allow a direct movement of the mouse from one to the other... 

**Example**: The first two pictures on this page share a title-attribute, as well as the two in the middle (brume). Point the mouse at one of both, then move to the other.

https://www.uplawski.eu/france/Normandie

Thank you in advance (also: Thank you anyway).

**Comment by The-Compiler** [comment]
Those tooltips are coming from the underlying QtWebEngine - reported here: [[QTBUG-99632] title tooltips with same text as existing one don't show - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-99632)

**Comment by Booze-Operator** [comment]
TY.
