### ISSUE TITLE
 When closing a second instance of qutebrowser, the two instances get closed

### ISSUE THREAD

**Issue by mharig** [qutebrowser/qutebrowser#6963]
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
I do not know.

**Description**
When closing a second instance of qutebrowser, the two instances get closed. And the downloads canceled.

**How to reproduce**
1. Open a second instance of qutebrowser.
2. Close it with :q
->
All two instanced get closed.

**Comment by mschilli87** [comment]
I think this is the intended behaviour.
If I understand correctly, you are looking for `:close` instead.

If this is not what you wanted, please give some additional information on how *exactly* you '[o]pen a second instance of qutebrowser'.

**Comment by mharig** [comment]
Maybe it is intended, but in vi :q closes just the current window, and exits just if the current window is the last window.
:close does close the current window, only if it is not the last window.
So if you take vi as standard, this behaviour of qb is a violation of the principle of least surprise.

**Comment by The-Compiler** [comment]
By default, `:q` is an alias to `:close`:

![image](https://user-images.githubusercontent.com/625793/149655725-8d9f7488-79b2-40bb-a378-20705eaed9e1.png)

So if `:close` closes a window and `:q` quits qutebrowser for you, that seems to be something in your config. Can you please try with `--temp-basedir`? You can use `:open -w` there to open a new window.

If it works there, can you please show your `:config-diff`?

**Comment by mharig** [comment]
Cannot reproduce. Maybe I accidently typed :wq. But I am absolutely shure, that I didn't wanted to type this :-)
