### ISSUE TITLE
completion-item-del with tab-focus: ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6967]
From a crash report:

- Open the `:tab-focus` menu with `T`
- Select using the arrow keys, some tab from the list (not pressing enter, just hovering)
- Press Shift+Delete

and indeed:

```pytb
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/eventfilter.py", line 104, in eventFilter
    return handler(cast(QKeyEvent, event))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/eventfilter.py", line 74, in _handle_key_event
    return man.handle_event(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 468, in handle_event
    return handler(cast(QKeyEvent, event))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 289, in _handle_keypress
    match = parser.handle(event, dry_run=dry_run)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 323, in handle
    self.execute(result.command, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 76, in execute
    self._commandrunner.run(cmdstr, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 188, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 553, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/completionwidget.py", line 461, in completion_item_del
    self.model().delete_cur_item(index)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/models/completionmodel.py", line 230, in delete_cur_item
    cat.delete_func(data)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/models/miscmodels.py", line 116, in delete_tab
    win_id, tab_index = data[0].split('/')
ValueError: not enough values to unpack (expected 2, got 1)
```

This looks like it *should* be a good bugfix for new contributors: From what it looks like, in `qutebrowser/completion/models/miscmodels.py`, we use `delete_tab` as deletion function for both `tab-focus` (displays tabs from current window) and `tab-select` (displays all tabs].

For `tab-focus`, we pass `add_win_id=False` to the `_tabs` helper generating the completion, so that it doesn't prepend the window id:

```python
            tab_str = ("{}/{}".format(win_id, idx + 1) if add_win_id
                       else str(idx + 1))
```

but the `delete_tab` function assumes that there always is a slash:

```python
    def delete_tab(data):
        """Close the selected tab."""
        win_id, tab_index = data[0].split('/')
```

causing the crash. To fix this, we should probably:

- Pass the current `win_id` (from `info.win_id`) to `_tabs` in all places where it gets called
- Adjust `delete_tab` so that it uses that (instead of getting it from the text in the first completion column) if `add_win_id=False` is given
- Ideally, add a test testing for this, but I'm not sure how unit-testable that part of the code is currently

**Comment by mohite-abhi** [comment]
I did changes as you said, by adding current_win_id parameter in _tabs function and using it in in delete_tab and the exception seems to be solved in my local machine. But I don't know about the testing part, I ran test with tox and it is showing some failed and errors, what am i supposed to do now? should i commit and create a pr or something else?

here's the test error/failed message:

```
Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
=================================================== short test summary info ====================================================
FAILED tests/end2end/features/test_completion_bdd.py::test_deleting_an_open_tab_via_the_completion - end2end.fixtures.testpro...
FAILED tests/end2end/features/test_completion_bdd.py::test_go_to_tab_after_moving_a_tab - end2end.fixtures.testprocess.WaitFo...
FAILED tests/end2end/features/test_javascript_bdd.py::test_closing_a_js_window_twice_issue_906__qtwebengine - end2end.fixture...
FAILED tests/end2end/features/test_tabs_bdd.py::test_tabselect_with_a_matching_title - end2end.fixtures.testprocess.WaitForTi...
FAILED tests/end2end/features/test_tabs_bdd.py::test_tabselect_with_no_matching_title - end2end.fixtures.testprocess.WaitForT...
FAILED tests/end2end/features/test_tabs_bdd.py::test_tabselect_with_matching_title_and_two_windows - end2end.fixtures.testpro...
FAILED tests/end2end/features/test_tabs_bdd.py::test_tabselect_with_wrong_argument_ - end2end.fixtures.testprocess.WaitForTim...
FAILED tests/end2end/features/test_tabs_bdd.py::test_tabselect_with_wrong_argument__1 - end2end.fixtures.testprocess.WaitForT...
FAILED tests/end2end/features/test_tabs_bdd.py::test_tabselect_with_wrong_argument_0x - end2end.fixtures.testprocess.WaitForT...
FAILED tests/end2end/features/test_tabs_bdd.py::test_tabselect_with_wrong_argument_123 - end2end.fixtures.testprocess.WaitFor...
FAILED tests/unit/completion/test_models.py::test_tab_completion - TypeError: _tabs() missing 1 required keyword-only argumen...
FAILED tests/unit/completion/test_models.py::test_tab_completion_delete - TypeError: _tabs() missing 1 required keyword-only ...
FAILED tests/unit/completion/test_models.py::test_tab_completion_not_sorted - TypeError: _tabs() missing 1 required keyword-o...
FAILED tests/unit/completion/test_models.py::test_tab_completion_tabs_are_windows - TypeError: _tabs() missing 1 required key...
ERROR tests/end2end/features/test_completion_bdd.py::test_deleting_an_open_tab_via_the_completion - end2end.fixtures.testproc...
```

**Comment by The-Compiler** [comment]
@mohite-abhi please create a PR indeed, then we can take it from there - that way, we can see your code changes and the full test output.

**Comment by mohite-abhi** [comment]
On solving window id issue i have faced another issue with tab delete using tab-focus, tab-select. 
Suppose tab-select / tab-focus looks like this when i opened it:

1  some_site  some_url
2  other_site  other_url
3  third_site  third_url

When i delete tab 2, tab-focus / tab-select now looks like this

1  some_site  some_url
3  third_site  third_url

now with the current implementation i won't be able to delete tab 3 since there is no tab at that position in the window.

I have 2 solutions for this, 
1. pass index.row() in data to delete_func (this is easy) : in this i would be able to delete tab 3 without actually updating the indexes in the completion
2. Actually update the completion after every deletion (i can't figure out how to do this)

I am thinking about fixing this bug under issue #6967, but i can do that after opening another issue, as per advised.
