### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by Rick21-bit** [qutebrowser/qutebrowser#6971]
Ad block on qutebrowser is good till they are not. If plugin system were develop i myself will try making ad block for site like YouTube, besides the existing

**Comment by The-Compiler** [comment]
Duplicate of #30

**Comment by The-Compiler** [comment]
As for what's missing for YouTube adblocking, see #6480  - note that you can already use qutebrowser's Greasemonkey support to [run a script](https://github.com/qutebrowser/qutebrowser/issues/6480#issuecomment-872771282) which speeds the ads up and skip them, or spawn mpv from qutebrowser to watch videos, or use something like Invidious.
