### ISSUE TITLE
not changing cursor when exiting devtools and screencast is on

### ISSUE THREAD

**Issue by macmoritz** [qutebrowser/qutebrowser#6974]
While screencast (emulating mobile devices) in devtools is turned on, the cursor changes to an mobile like touch dot and the behaviour of the cursour changes to mobile (f.e. scrolling on drag).
This behaviour keeps applied and the cursor does not change back to computer style when exiting devtools.

**Version info**:
```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.2
```

**Comment by The-Compiler** [comment]
I can confirm. Merging this into #6693 as it's the same root cause.
