### ISSUE TITLE
Can't play media content

### ISSUE THREAD

**Issue by rdmc10** [qutebrowser/qutebrowser#6987]
**Version info**:
qutebrowser v2.4.0
Git commit:
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.10.2
PyQt: 5.15.5

sip: 6.3.0
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.11.2
yaml: 5.4.1
adblock: 0.5.1
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.12.313 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1m  14 Dec 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 495.46
Platform: Linux-5.16.4-zen1-1-zen-x86_64-with-glibc2.33, 64bit
Linux distribution: Artix Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /home/radu/.local/lib/python3.10/site-packages/PyQt5/Qt5/libexec, data path: /home/radu/.local/lib/python3.10/site-packages/PyQt5/Qt5

Paths:
cache: /home/radu/.cache/qutebrowser
config: /home/radu/.config/qutebrowser
data: /home/radu/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/radu/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I can't play media content in qutebrowser. I have tried odysee, twitch, sometimes youtube works(not all the time). I have installed 
pyqt5 webengine (tried both pip and pacman versions, also tried different versions of it and still didn't work).
This is the output in the terminal :
 [17470:20:0131/203043.252950:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[17470:1:0131/203043.253032:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
[17470:20:0131/203044.681079:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[17470:1:0131/203044.681502:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
[17470:20:0131/203044.724334:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[17470:1:0131/203044.737122:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}

I have searched for this issues and it seems like poeple had in in the past but I still haven't found a way to fix it, I don't know what could cause this.

**How to reproduce**

Trying to play media content results in these errors

**Comment by The-Compiler** [comment]
You are running with a prebuilt Qt installed via pip, as you can see in "Qt library executable path: /home/radu/.local/lib/python3.10/site-packages/PyQt5/Qt5/libexec". This comes without proprietary codec support. It will work correctly with a pacman-installed Qt, I guess you were still running with the pip-installed one or so. Make sure it's fully uninstalled and that path points to your system-wide pacman Qt install.

**Comment by rdmc10** [comment]
Well the thing is I don't know why it behaves like this. I installed qutebrowser through pacman, and I tried removing everything related to qt that I installed with pip, and now( even though I have the dependencies installed through pacman) I get this when I'm trying to run the browser: 
Fatal error: PyQt5.QtCore is required to run qutebrowser but could not be imported! Maybe it's not installed?

The error encountered was:
/home/radu/.local/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

Please search for the python3 version of PyQt5.QtCore in your distributions packages, or see https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc

If you installed a qutebrowser package for your distribution, please report this as a bug.

**Comment by rdmc10** [comment]
Ok, I found what was causing this. Uninstalling the pip version of pyqt5 didn't actually delete some files in my .local. I had to manually remove them in order for this to work! Thanks!

**Comment by The-Compiler** [comment]
So I'm assuming things are working now? :) FWIW I'd advice only using pip with [virtual environments](https://packaging.python.org/en/latest/tutorials/installing-packages/#creating-virtual-environments) (qutebrowser comes with a `mkvenv.py` helping with that). Mixing pip-installed and pacman-installed stuff without isolated environments leads to all kind of trouble.

**Comment by rdmc10** [comment]
Yes, it's working, everything seems perfect now, I had a lot of issues before. Thanks for the advice!
