### ISSUE TITLE
Avoid silently entering normal mode

### ISSUE THREAD

**Issue by jnitti** [qutebrowser/qutebrowser#6989]
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
Qutebrowser auto enters normal mode after entering insert mode in two annoying circumstances:
1. Loading a page and pressing 'i' to enter insert mode too early in the load cycle of a page will cause the page to re-renter normal mode silently. Appears to be auto-set to enter normal mode __again__ after a page has been fully loaded. A nice way to show this is to load youtube, press i, and start typing "doom" in the search bar and see if you either accidentally close the page, start opening a new link, or save youtube as a quicklink.
2. Pressing a button. I believe this is triggered because qutebrowser automatically enters normal mode if you click on anything that isn't a texbox.

**How to reproduce**
For (1), A nice way to show this is to load youtube, press i, and start typing "doom" in the search bar and see if you either accidentally close the page, start opening a new link, or save youtube as a quicklink. Otherwise any website will show this behavior, as long as you try to enter insert mode too early. 

For (2), I recommend going to Google Docs and entering insert mode after you've opened a document. Now, try to click on one of the options at the top of the page, like File/Edit/Insert etc. You will see that normal mode is automatically entered. This is ************incredibly************ frustrating to deal with in text-editing on Google Docs(or any website, for that matter) to the point I do not use qutebrowser anymore.

*Silently entering normal mode is also, from a user-perspective, incredibly jank and inconvenient.*

**Comment by The-Compiler** [comment]
You can customize this using `input.insert_mode.leave_on_load` (1) and `input.insert_mode.auto_leave` (2).
