### ISSUE TITLE
vim keybinding for moving through lists

### ISSUE THREAD

**Issue by mmahmoudian** [qutebrowser/qutebrowser#6990]
It would be nice to navigate through the list of commands (and possibly other lists) without needing to move hand to reach the arrow keys. Basically what I suggest is to move the yellow part in the following picture down or up using VIM keys. In Doom Emacs this is solved by using the <kbd>Ctrl</kbd>+<kbd>j</kbd> and <kbd>Ctrl</kbd>+<kbd>k</kbd>. I have checked and neither of these two are in use in qutebrowser: `qute://help/img/cheatsheet-big.png`

![image](https://user-images.githubusercontent.com/390889/152152565-28898e84-afd0-4293-9658-41998fc1f99b.png)

**Comment by The-Compiler** [comment]
You can use tab and shift-tab to do so. Ctrl-j is already used as alternative to the enter key (like in a shell), via `bindings.key_mappings` - however,. you can always remove it from there and bind it to `completion-item-focus prev` and `next` instead.
