### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by Carpetsmoker** [qutebrowser/qutebrowser#700]
I often use spell checking in my browser.

It should support multiple languages, but I would prefer that it's _not_ like `dwb` where you see both languages intermixed. This is very annoying if you use 3 languages.

**Comment by The-Compiler** [comment]
This is something which isn't normally doable using the QtWebKit APIs - however, there's the [QupZilla/qtwebkit-plugins](https://github.com/QupZilla/qtwebkit-plugins) repo, which can be used to build a `libqtwebkitplugins.so`.

After that's copied to `/usr/lib/qt/plugins/webkit` (at least here on Arch) I at least get underlined words in text fields.

Someone would have to look into more integration like QupZilla has (i.e. a right-click menu), but that's very low-priority for me.

**Comment by The-Compiler** [comment]
Quick follow-up - my train was going over the border before, so I was a bit in a hurry to send the comment before my connection was gone :laughing:

I don't know whether the kind of integration QupZilla has with the plugin would be possible with the PyQt APIs, it might not be possible at all.

It seems the plugin does multi-language, at least in the right-click menu in QupZilla you get checkboxes for languages.

Also, all that probably won't work when I add a QtWebEngine/Chromium backend to qutebrowser - I don't know what the plans are to add a spellcheck API there, or if it works out-of-the-box already.

Of course, pull requests regarding this would be welcome (and thanks for all the great other PRs!), but probably #349 (a custom context menu) would have to be done first.

**Comment by The-Compiler** [comment]
FWIW I now packaged `qtwebkit-plugins` in the Archlinux AUR: https://aur.archlinux.org/packages/qtwebkit-plugins-git/

**Comment by lahwaacz** [comment]
I've installed the package and still don't see any highlighting of misspelled words. Is there some configuration necessary?

**Comment by The-Compiler** [comment]
It should just work™. Someone else reported it didn't work for them in IRC as well, but I have no idea why...

When trying to reproduce I had some issues as well, but then I figured out it sometimes just takes a few seconds after typing a misspelled word until it gets highlighted.

If it doesn't work with e.g. Otter Browser either (the situation is different for QupZilla as that has a more sophisticated spell checking integrated), I'd suggest opening a bug at https://github.com/QupZilla/qtwebkit-plugins/issues

FWIW there's https://github.com/QupZilla/qtwebkit-plugins/issues/7 already open, but as said, it works fine for me...

**Comment by The-Compiler** [comment]
Can you see any `SpellCheck` output when you start with `--debug`? Do you have a dictionary like `hunspell-en` (on Arch) installed?

**Comment by lahwaacz** [comment]
We (me and `grep`) don't see any output related to spell-checking. Both `hunspell` and `hunspell-en` are installed.

**Comment by ids1024** [comment]
It doesn't seem to work for me either; I have Arch Linux with that AUR package installed, as well as hunspell-en.

**Comment by shioyama** [comment]
Same here doesn't work for me. I have `hunspell-en` installed.

**Comment by The-Compiler** [comment]
Do you see something interesting when you run `QT_DEBUG_PLUGINS=1 qutebrowser --temp-basedir  --debug --logfilter qt`? For me it's this:

```
16:18:08 WARNING  qt         Unknown module:none:0 Found metadata in lib /usr/lib/qt/plugins/webkit/libqtwebkitplugins.so, metadata=
{
    "IID": "org.qtwebkit.QtWebKit.QtWebKitPlugin",
    "MetaData": {
    },
    "className": "QtWebKitPlugin",
    "debug": false,
    "version": 329216
}
16:18:08 DEBUG    qt         Unknown module:none:0 loaded library "/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so"
```

**Comment by lahwaacz** [comment]
Yeah:

```
16:35:32 WARNING  qt         Unknown module:none:0 Found metadata in lib /usr/lib/qt/plugins/webkit/libqtwebkitplugins.so, metadata=
{
    "IID": "org.qtwebkit.QtWebKit.QtWebKitPlugin",
    "MetaData": {
    },
    "className": "QtWebKitPlugin",
    "debug": false,
    "version": 329216
}


  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.6.2', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 159, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 111, in run
    ret = qt_mainloop()
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 121, in qt_mainloop
    return qApp.exec_()
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/log.py", line 356, in qt_message_handler
    stack = ''.join(traceback.format_stack())

16:35:32 DEBUG    qt         Unknown module:none:0 loaded library "/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so"
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.6.2', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 159, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 111, in run
    ret = qt_mainloop()
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 121, in qt_mainloop
    return qApp.exec_()
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/log.py", line 356, in qt_message_handler
    stack = ''.join(traceback.format_stack())

16:35:32 WARNING  qt         Unknown module:none:0 QLibraryPrivate::loadPlugin failed on "/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so" : "Cannot load library /usr/lib/qt/plugins/webkit/libqtwebkitplugins.so: (/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so: undefined symbol: _ZTI16QWebSpellChecker)"
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.6.2', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 159, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 111, in run
    ret = qt_mainloop()
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 121, in qt_mainloop
    return qApp.exec_()
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/log.py", line 356, in qt_message_handler
    stack = ''.join(traceback.format_stack())
```

**Comment by The-Compiler** [comment]
Okay - the `QLibraryPrivate::loadPlugin failed on "/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so" : "Cannot load library /usr/lib/qt/plugins/webkit/libqtwebkitplugins.so: (/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so: undefined symbol: _ZTI16QWebSpellChecker)"` tells us what's going on, now I only have to find out why... :wink:

**Comment by lahwaacz** [comment]
If I remember correctly, you have some custom Qt builds for testing? The `_ZTI16QWebSpellChecker` symbol might be missing only in the Arch packages, or there is some missing (optional) dependency. You could try to [find out which file contains the symbol](http://stackoverflow.com/questions/1237575/how-do-i-find-out-what-all-symbols-are-exported-from-a-shared-object) :wink:

**Comment by The-Compiler** [comment]
I can only find that symbol in `/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so` which is the thing built by the package...

**Comment by ff2000** [comment]
On Sat, 04 Jun 2016 08:35:44 -0700, Florian Bruhin <notifications@github.com> wrote:
> I can only find that symbol in `/usr/lib/qt/plugins/webkit/libqtwebkitplugins.so` which is the thing built by the package...

QWebSpellChecker is just an interface (class with only pure virtual methods).
Probably there is something missing in the output. E.g. it cuts exactly after
the class name but before the mangled method name. readelf -Ws shows everything.

I currentl can't check myself because I have no QtWebKit (not even Qt) installed
and my laptop is too week to do so just to look at this issue :/ (Gentoo...)

**Comment by lahwaacz** [comment]
```
$ objdump -T /usr/lib/qt/plugins/webkit/libqtwebkitplugins.so | grep -i spellchecker
0000000000000000      D  *UND*	0000000000000000              _ZTI16QWebSpellChecker
0000000000000000      D  *UND*	0000000000000000              _ZN16QWebSpellChecker11qt_metacastEPKc
0000000000000000      D  *UND*	0000000000000000              _ZTV16QWebSpellChecker
0000000000000000      D  *UND*	0000000000000000              _ZN16QWebSpellChecker11qt_metacallEN11QMetaObject4CallEiPPv
0000000000000000      D  *UND*	0000000000000000              _ZN16QWebSpellChecker16staticMetaObjectE
0000000000006840 g    DF .text	0000000000000002  Base        _ZN10SpellCheck20checkGrammarOfStringERK7QStringR5QListIN16QWebSpellChecker13GrammarDetailEEPiS8_
```

From `objdump(1)`:

> Here the first number is the symbol's value (sometimes refered to as its
address).  The next field is actually a set of characters and spaces
indicating the flag bits that are set on the symbol.  These characters are
described below.  Next is the section with which the symbol is associated or
*ABS* if the section is absolute (ie not connected with any section), or
*UND* if the section is referenced in the file being dumped, but not defined
there.
...

If I'm reading this correctly, the symbol is only _used_ in the file, but not defined. Comparing with qupzilla's built-in spell-checker:

```
$ objdump -T /usr/lib/libQupZilla.so | grep -i spellchecker
00000000004a88f2 g    DF .text	0000000000000050  Base        _ZN16QWebSpellChecker11qt_metacastEPKc
00000000004a8942 g    DF .text	000000000000003f  Base        _ZN16QWebSpellChecker11qt_metacallEN11QMetaObject4CallEiPPv
00000000002619b2  w   DF .text	0000000000000032  Base        _ZN16QWebSpellCheckerC1Ev
0000000000831d50  w   DO .data.rel.ro	00000000000000c0  Base        _ZTV16QWebSpellChecker
00000000004a88aa g    DF .text	0000000000000048  Base        _ZNK16QWebSpellChecker10metaObjectEv
0000000000261816 g    DF .text	000000000000001b  Base        _ZN10SpellCheck20checkGrammarOfStringERK7QStringR5QListIN16QWebSpellChecker13GrammarDetailEEPiS8_
00000000002619b2  w   DF .text	0000000000000032  Base        _ZN16QWebSpellCheckerC2Ev
0000000000565a10  w   DO .rodata	0000000000000013  Base        _ZTS16QWebSpellChecker
00000000004a8a9e  w   DF .text	000000000000002b  Base        _ZN16QWebSpellCheckerD0Ev
0000000000831d20 g    DO .data.rel.ro	0000000000000030  Base        _ZN16QWebSpellChecker16staticMetaObjectE
00000000004a8a70  w   DF .text	000000000000002d  Base        _ZN16QWebSpellCheckerD1Ev
00000000004a8a70  w   DF .text	000000000000002d  Base        _ZN16QWebSpellCheckerD2Ev
0000000000832008  w   DO .data.rel.ro	0000000000000018  Base        _ZTI16QWebSpellChecker
```

so the symbol is correctly defined there. What does it look like on your side, @The-Compiler?

**Comment by lahwaacz** [comment]
The most notable difference between [qtwebkit-plugins-git](https://aur.archlinux.org/packages/qtwebkit-plugins-git/) and [qupzilla-qtwebkit-git](https://aur.archlinux.org/packages/qupzilla-qtwebkit-git/) PKGBUILDs is the `qmake-qt5 CONFIG+=debug` command in the latter. QupZilla works without debug too, but qtwebkit-plugins does not work even with debug (basically the same error, just stops on different missing symbol).

There are differences between the `spellcheck.{h,cpp}` files used by qtwebkit-plugins and QupZilla (see https://github.com/QupZilla/qtwebkit-plugins/issues/8), other than that I'm fairly clueless...

**Comment by The-Compiler** [comment]
I'd really expect `qmake` to be Qt5 on Arch always, `qmake --version` confirms that.

**Comment by The-Compiler** [comment]
Sorry - missed the comment above. It seems indeed for me the symbols are defined there, not just referenced:

```
$ objdump -CT /usr/lib/qt/plugins/webkit/libqtwebkitplugins.so | grep -i spellchecker
0000000000212790  w   DO .data.rel.ro	00000000000000c0  Base        vtable for QWebSpellChecker
000000000000ff00  w   DO .rodata	0000000000000013  Base        typeinfo name for QWebSpellChecker
000000000000cf90 g    DF .text	0000000000000018  Base        QWebSpellChecker::metaObject() const
0000000000212580  w   DO .data.rel.ro	0000000000000018  Base        typeinfo for QWebSpellChecker
000000000000d330 g    DF .text	000000000000005b  Base        QWebSpellChecker::qt_metacast(char const*)
000000000000d4b0 g    DF .text	0000000000000005  Base        QWebSpellChecker::qt_metacall(QMetaObject::Call, int, void**)
0000000000212860 g    DO .data.rel.ro	0000000000000030  Base        QWebSpellChecker::staticMetaObject
0000000000007d30 g    DF .text	0000000000000002  Base        SpellCheck::checkGrammarOfString(QString const&, QList<QWebSpellChecker::GrammarDetail>&, int*, int*)
```

And yeah, I'm using `qt5-*-debug` from my [`qt-debug` repo](https://github.com/The-Compiler/qutebrowser/blob/master/doc/stacktrace.asciidoc#archlinux). Not sure what in there would be different what'd cause `qtwebkit-plugins` to build incorrectly with Arch's normal Qt build...

**Comment by lahwaacz** [comment]
> I'd really expect qmake to be Qt5 on Arch always, qmake --version confirms that.

By default, yes. But in Arch, qmake is a symlink to qtchooser, which is configurable (see `qtchooser(1)`). Not that it matters to this issue though.

**Comment by raelgc** [comment]
Any lucky on this? :)

**Comment by The-Compiler** [comment]
@raelgc On what exactly?

**Comment by raelgc** [comment]
Make the highlighting of misspelled words works in qt5 using the QupZilla/qtwebkit-plugins. I have the same problem on [ScudCloud](https://github.com/raelgc/scudcloud/issues/254), but don't know how to solve it.

**Comment by pclewis** [comment]
I ran into this same `undefined symbol` error on NixOS trying to get notifications to work, and fixed it by adding the `qwebkitplatformplugin.h` file to the `HEADERS` in `src/src.pro` of [qtwebkit-plugins](https://github.com/QupZilla/qtwebkit-plugins). I don't understand Qt well enough to know if this is a correct or advisable fix, but it's working for me. Seems like it might be an include path issue.

For NixOS in `postPatch` steps in `qtwebkit-plugins/default.nix` I added
```.sh
sed -i "s,plugin.h,plugin.h ${qtwebkit.dev}/include/QtWebKit/qwebkitplatformplugin.h," src/src.pro  
```

**Comment by The-Compiler** [comment]
Maybe @nowrep can tell us more about whether this sounds like a good fix or not :wink:

**Comment by nowrep** [comment]
https://github.com/QupZilla/qtwebkit-plugins/commit/61648ba47090cbb37bf050e54e1445e02e23f1ea

**Comment by lahwaacz** [comment]
[QtWebEngine 5.8](https://wiki.qt.io/New_Features_in_Qt_5.8) is supposed to support "Spellchecking with Hunspell" - any chance to enable it in qutebrowser?

**Comment by Carpetsmoker** [comment]
Here's a basic example to use the WebEngine 5.8 API:

```
diff --git i/qutebrowser/browser/webengine/webenginesettings.py w/qutebrowser/browser/webengine/webenginesettings.py
index b029b4fd5..7aa208c70 100644
--- i/qutebrowser/browser/webengine/webenginesettings.py
+++ w/qutebrowser/browser/webengine/webenginesettings.py
@@ -278,6 +278,10 @@ MAPPINGS = {
     'ui': {
         'smooth-scrolling':
             Attribute(QWebEngineSettings.ScrollAnimatorEnabled),
+        'spell': ProfileSetter(getter='spellCheckEnabled',
+                               setter='setSpellCheckEnabled'),
+        'spell-languages': ProfileSetter(getter='spellCheckLanguages',
+                                         setter='setSpellCheckLanguages'),
     },
     'storage': {
         'local-storage':
diff --git i/qutebrowser/browser/webkit/webkitsettings.py w/qutebrowser/browser/webkit/webkitsettings.py
index caeef296f..c251ad5a0 100644
--- i/qutebrowser/browser/webkit/webkitsettings.py
+++ w/qutebrowser/browser/webkit/webkitsettings.py
@@ -230,6 +230,11 @@ MAPPINGS = {
         #   Attribute(QWebSettings.AcceleratedCompositingEnabled),
         #'tiled-backing-store':
         #   Attribute(QWebSettings.TiledBackingStoreEnabled),
+        # TODO: Give error; would be confusing otherwise.
+        # 'spell': ProfileSetter(getter='spellCheckEnabled',
+        #                        setter='setSpellCheckEnabled'),
+        # 'spell-languages': ProfileSetter(getter='spellCheckLanguages',
+        #                                  setter='setSpellCheckLanguages'),
     },
     'storage': {
         'offline-storage-database':
diff --git i/qutebrowser/config/configdata.py w/qutebrowser/config/configdata.py
index 1fbc22937..38f1a3ef2 100644
--- i/qutebrowser/config/configdata.py
+++ w/qutebrowser/config/configdata.py
@@ -418,6 +418,17 @@ def data(readonly=False):
              SettingValue(typ.Bool(), 'true'),
              "Show a filebrowser in upload/download prompts."),
 
+            # qwebengine_convert_dict /usr/share/hunspell/en_US.dic en_US.bdic
+            # https://doc.qt.io/qt-5/qml-qtwebengine-webengineprofile.html#spellCheckEnabled-prop
+            # http://doc.qt.io/qt-5/qtwebengine-webenginewidgets-spellchecker-example.html
+            ('spell',
+             SettingValue(typ.Bool(), 'true'),
+             "Enable spell checking; only works on QtWebEngine."),
+
+            ('spell-languages',
+             SettingValue(typ.List(typ.String(), none_ok=True), 'en_US'),
+             "Spell checking language; only works on QtWebEngine."),
+
             readonly=readonly
         )),
```

Since it uses its own dictionary format, you'll need to convert it from the Hunspell ones:

    $ qwebengine_convert_dict /usr/share/hunspell/en_US.dic en_US.bdic

Qutebrowser should do this automatically, or we should provide some repository with those compiled files at least for common languages.
There's also some other work to be done, such as making sure that QtWebKit users get a friendly error, showing a more friendly error when the dictionary doesn't exist, and writing some tests for it.

I'm *not* going to work on this for now, as there are other thing I'd prefer to do first, but anyone is free to take the above code and run with it :-)

Related links:

- https://doc.qt.io/qt-5/qml-qtwebengine-webengineprofile.html#spellCheckEnabled-prop
- http://doc.qt.io/qt-5/qtwebengine-webenginewidgets-spellchecker-example.html

**Comment by The-Compiler** [comment]
Thanks for getting the ball rolling, @Carpetsmoker!

As for "making sure that QtWebKit users get a friendly error": Simply don't use it in `webkitsettings.py` and `backends=[usertypes.Backend.QtWebEngine]` in `SettingValue` in `configdata.py`. This will also add a comment about it only working on QtWebEngine.

**Comment by elshize** [comment]
Hey, so I was thinking of pushing this thing forward. What do you think should be the proper way of handling dictionary conversion? An internal command, like "install-dict", that looks for dictionaries in hunspell directory? Where should we store the .bdic files?

**Comment by The-Compiler** [comment]
First of all: Note that I won't have the time to review any contributions until September because I'm busy with exams, and I'll also merge the new-config branch then - so if you work on something now, you might need to rebase it and solve conflicts then.

I'm not really sure what's feasible here. The best way would indeed be to have some command to convert dictionaries, but it's probably non-trivial to do that in Python (see QtWebEngine's [tool](https://github.com/qt/qtwebengine/blob/5.9/src/tools/qwebengine_convert_dict/main.cpp)).

Maybe we could just read Chromium's dicts which (on Linux) are in ``/.config/chromium/Dictionaries` by default?

**Comment by elshize** [comment]
About the review, that's totally fine, I'm quite busy myself so probably it will take me some time anyway. I just noticed this thing has been hanging here for a long time, so it's about time someone made it happen. Enabling spell check is straightforward enough, it's the dictionaries that are the issue.

I'll spend some time figuring out how to best approach it, and will get back to you.

**Comment by The-Compiler** [comment]
I just opened [QTBUG-62236](https://bugreports.qt.io/browse/QTBUG-62236) FWIW - I think QtWebEngine should handle this by loading Chromium's dictionaries.

Also, at least according to [the docs](https://doc.qt.io/qt-5/qtwebengine-features.html#spellchecker) the current paths where dictionaries are searched are very cumbersome, at least for typical system-wide qutebrowser/Qt installations on Linux...

FWIW I did a quick test and could get spell-checking to work in QtWebEngine with `sudo ln -s /home/florian/.config/chromium/Dictionaries /usr/bin/qtwebengine_dictionaries` and then this in `:debug-console`:

```python
>>> profile = QWebEngineProfile.defaultProfile()
>>> profile.setSpellCheckEnabled(True)
>>> profile.setSpellCheckLanguages(["en-US-7-1"])
```

Not sure what the `-7-1` means, but the file I had in `/home/florian/.config/chromium/Dictionaries` is `en-US-7-1.bdic`.

This is all less than optimal, but I guess the best we can do right now is to add an option to set the languages (or even figure them out by ourselves), and document what to do to get things working (create that symlink on Linux, not sure about macOS and Windows).

**Comment by parchd-1** [comment]
I know you will already have considered this, but I'll put it on the record: not everyone who would like to use spell-checking has or wants Chromium installed.

**Comment by The-Compiler** [comment]
Sure - you could still always download Hunspell dictionaries, merge them using QtWebEngine's convert_dict tool, and use that. But using Chromium's dictionaries would be a nice way to make it work "automatically".

**Comment by parchd-1** [comment]
True. Apparently (just been poking about) the dictionaries can also be found [here](https://src.chromium.org/viewvc/chrome/trunk/deps/third_party/hunspell_dictionaries/), so just grabbing a single dictionary is also possible.

**Comment by The-Compiler** [comment]
Ah, nice! This is before Chromium switched to git though. I think [this page](https://chromium.googlesource.com/chromium/deps/hunspell_dictionaries.git/+/master) is the most up-to-date source for them.

**Comment by parchd-1** [comment]
I thought the dates seemed a bit too old!

**Comment by The-Compiler** [comment]
So I couldn't resist and submitted a change to Qt adding a `QTWEBENGINE_DICTIONARIES_DIR` environment variable to customize the location to something more sane: https://codereview.qt-project.org/#/c/201422/

Hopefully will made it into Qt 5.10.

**Comment by michal-blippar** [comment]
That's a good catch with dictionaries in the repository. I think it makes the most sense to use these. I can work on a command installing it locally this weekend. Do you guys think we should maintain a list of possible languages to install? (then one could choose one from the list if not sure what the name is)

**Comment by The-Compiler** [comment]
A qutebrowser command for it won't work, as the dictionaries need to be in a location like `/usr/share/qt/qtwebengine_dictionaries`, and I don't want to encourage people to run qutebrowser as root.

However, a standalone commandline script would be very nice. It'd ideally get the file list from the repository (dunno if there's an API for the file list - the links at the bottom right get the commit only, or maybe using the GitHub mirror and API). Then it could offer a list of dictionaries to download, and download them to the right location.

With Qt 5.10, we can then revisit this and implement some logic to read Chromium's dictionaries if available.

**Comment by elshize** [comment]
(sorry, I used a different account for the post above by accident)
Right, I'll look into this.

**Comment by The-Compiler** [comment]
Quick update: Qt 5.10 [will have](https://github.com/qt/qtwebengine/commit/ff4b006a565f2a945903a131f46d637d8b77188e) a `QTWEBENGINE_DICTIONARIES_PATH` environment variable.

**Comment by elshize** [comment]
It's not exactly ready yet, but mostly working. I created a pull request in case someone has some time to take a look. I'll get back to it next or the following weekend.
