### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by Pound-Hash** [qutebrowser/qutebrowser#7005]
The [docs](https://www.qutebrowser.org/doc/help/configuring.html) provide [this link](https://gitlab.com/shaneyost/dots-popos-september-2020/-/blob/master/qutebrowser/config.py) to a theme by Shane Yost, but it's broken.

**Comment by The-Compiler** [comment]
Looks like their GitLab account was deleted, and so was [their Reddit account](https://www.reddit.com/r/qutebrowser/comments/iy26la/any_particular_place_i_should_be_sharing_themes/). Don't seem to be able to find it in any archive, so I suppose let's just get rid of it...
