### ISSUE TITLE
Ranger as filebrowser cant find terminfo database

### ISSUE THREAD

**Issue by tbsmn** [qutebrowser/qutebrowser#7013]
**Version info**:
qutebrowser v2.4.0
Git commit: 36ffff2f6 on HEAD (2021-10-21 18:50:06 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**: No

**Description**
When opening a filehandler I get the following Error:

```
Traceback (most recent call last):
  File "/Users/***/homebrew/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/Users/***/homebrew/lib/python3.9/site-packages/ranger/core/main.py", line 32, in main
    from ranger.container.settings import Settings
  File "/Users/***/homebrew/lib/python3.9/site-packages/ranger/container/settings.py", line 13, in <module>
    from ranger.gui.colorscheme import _colorscheme_name_to_class
  File "/Users/***/homebrew/lib/python3.9/site-packages/ranger/gui/colorscheme.py", line 33, in <module>
    from ranger.gui.color import get_color
  File "/Users/***/homebrew/lib/python3.9/site-packages/ranger/gui/color.py", line 74, in <module>
    curses.setupterm()
_curses.error: setupterm: could not find terminfo database
```

**How to reproduce**
I have the following setting in my `config.py`
```
c.fileselect.handler = 'external'
c.fileselect.single_file.command = ['ranger', '--choosefile={}']
c.fileselect.multiple_files.command = ['ranger', '--choosefile={}']
```
If I run the command `ranger --choosefile=/var/folders/q7/3thyh08j0dngjtdd55kts9p40000gp/T/qutebrowser-fileselect-qngsty44` in my terminal it works.

The `$TERM` and `$TERMINFO` variables are also set
```
> echo $TERM     
xterm-kitty

> echo $TERMINFO 
/Applications/kitty.app/Contents/Resources/kitty/terminfo
```

Any Idea what is causing this problem?

**Comment by The-Compiler** [comment]
You are telling qutebrowser to launch ranger without a terminal. See the completion for those settings for some possible values which launch ranger in a terminal.

**Comment by tbsmn** [comment]
Thank you for the fast reply.
I changed the command in the config to `c.fileselect.single_file.command = ['kitty', '-e', 'ranger', '--choosefiles', '{}']`.

Now i can select a file in ranger and the file with the filename is written to disc (`/var/folders/q7/3thyh08j0dngjtdd55kts9p40000gp/T/qutebrowser-fileselect-yeayq43b`) and ranger closes.

But the selected file is not read by qutebrowser.
Any tips what I could try?

**Comment by The-Compiler** [comment]
Could you try `kitty -e ranger --choosefiles test` from an existing shell prompt, and confirm that you only get the shell back (i.e. kitty closes) once you selected the file? This is the case for me on Linux, but judging from the file paths, you might be on macOS?

qutebrowser reads the file when the child process exited, so it's vital that the terminal process stays around until the file picker quits.

**Comment by tbsmn** [comment]
Thanks  I guess that's what is causing the problem. When running the command from an existing shell ranger quits but i need to exit the process with <ctrl-c>

But I have no idea what could be causing this. And yes I am on macOS

**Comment by The-Compiler** [comment]
No idea here either. Next thing I'd try is `kitty -e sleep 2` to see what happens with that.

**Comment by tbsmn** [comment]
Thanks, just gave it a try. Its basicly the same behavior the shell closes but i have manually exit it with  <ctrl-c>. Maybe there is somthing running in the backround preventing kitty to quit.

Any idea how to figure out what this could be?
