### ISSUE TITLE
Windows Build with MP4 Video Codec?

### ISSUE THREAD

**Issue by Sakooooo** [qutebrowser/qutebrowser#7019]
Would it be possible to add a build with a video codec? I would like to play mp4 files with qutebrowser, if not how could I add one myself?

**Comment by The-Compiler** [comment]
The Windows and macOS releases come without proprietary codecs. This unfortunately isn't going to change, as distributing them would require a license as well as recompiling QtWebEngine from sources for every Qt release (which is a major pain).

You can build Qt, QtWebEngine and PyQt from source, see their respective documentation for more information about that. See https://github.com/qutebrowser/qutebrowser/issues/5466#issuecomment-634028797 for a rough (Linux) overview. Be prepared for a lot of pain though, building things on Windows isn't fun, and building Chromium less so.

**Comment by Sakooooo** [comment]
darn, would there be any alternative to this? I go onto some websites (twitch, twitter and netflix) and I would like to have the media being played instead of it giving an error, though I am fine if there is no alternative to this

**Comment by The-Compiler** [comment]
Not that I'm aware of - either build everything from source, use another browser, or use another OS.

**Comment by Sakooooo** [comment]
alright thanks

**Comment by ManuGraiph** [comment]
Question, is there any plans on some workaround for this? I think this is a major feature in a browser; i love qb but sadly, the only thing keeping me from switching to it is this issue.

**Comment by The-Compiler** [comment]
I'm afraid not. The majority of qutebrowser users is not on Windows, and I don't have the bandwidth to take care of 1) acquiring licenses for all the codecs (possibly for a fee) and 2) building Qt/Chromium from source for every Qt release, especially on Windows where things like this are a real pain.

**Comment by mschilli87** [comment]
Just my 2ct, but I'd love to see the available energy and time of @The-Compiler to rather go to pretty much any other open issue or PR before ~wasting~ spending time on supporting a for-profit proprietary OS. Unless maybe Microsoft was paying for the extra efforts. :wink:

**Comment by Sakooooo** [comment]
> Just my 2ct, but I'd love to see the available energy and time of @The-Compiler to rather go to pretty much any other open issue or PR before ~wasting~ spending time on supporting a for-profit proprietary OS. Unless maybe Microsoft was paying for the extra efforts. :wink: 

your right maybe i should pick up linux again
