### ISSUE TITLE
Qutebrowser doesn't clear the memory after closing tabs

### ISSUE THREAD

**Issue by GasparVardanyan** [qutebrowser/qutebrowser#7020]
**Version info**: https://paste.the-compiler.org/view/66f4d5a2

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
I open qutebrowser, use for some time and I see that there's ~2G ram used by qutebrowser. I open a new blank page (open -t), close all of the other tabs and now qutebrowser uses ~1G of ram (not **cached**, but **used** in terms of the **free** command), but when I launch a new window (first window) of qutebrowser, it uses ~300MB ram. Seems qutebrowser doesn't clear memory after closing tabs.
Mightbe it's a feature, qutebrowser keeps data to use when undoing closed pages, but I want to have an option to disable that feature.

**Comment by The-Compiler** [comment]
see #1476 (and especially https://github.com/qutebrowser/qutebrowser/issues/1476#issuecomment-733019169).
