### ISSUE TITLE
Fuzzy matching for functions

### ISSUE THREAD

**Issue by vnckppl** [qutebrowser/qutebrowser#7030]
Similar to this issue: #6871 about fuzzy matching for bookmarks:

Would it be possible to fuzzy match commands. E.g., 

`:do cl`

would match 

`:download-clear`

**Comment by The-Compiler** [comment]
Just as #6871, I think this is covered by #6114 already - from the point of view of the completion code, there is no difference between bookmarks and commands, they both use the same underlying code.
