### ISSUE TITLE
Qutebrowser randomly crashing and causing segfault which crashes my window manager

### ISSUE THREAD

**Issue by jsilve24** [qutebrowser/qutebrowser#7031]
**Version info**:
https://paste.the-compiler.org/view/5fb69461

**Does the bug happen if you start with `--temp-basedir`?**:
Yes. Notably, my customization is very minimal here. 

**Description**

Text entry fields seem to be the worst offender but I really can't reproduce reliably. All of a sudden, and only when using qutebrowser, my computer crashes and I get bumped back to my display manager to login again. Seems to be qutebrowser crashing leading to a xorg issue that can't be handled well. 

Here is the last stacktrace I was able to capture (entering some text in qualtrics) but it also just happened again about 10 min ago when entering text on a different github issue. 
This is occuring about 2 times a day. 

Stack trace here:
https://pastebin.com/8G1md5p2

**How to reproduce**
I have not found a reliable way. 

**Other potentially Notable Features of my Setup**
Due to some screen flickering issues I ran this a while back that seemed to fix things:
sudo pacman -U /var/cache/pacman/pkg/mesa-21.2.5-1-x86_64.pkg.tar.zst

To try to debug these crashes: reading issue #5634 
I ran this yesterday:
` :set qt.workarounds.remove_service_workers true`
Unfortunately, the bug has already occured two more times today so clearly that didn't work.

**Comment by The-Compiler** [comment]
The stacktrace shows that the crash happens deep inside your graphics driver:

```
 Stack trace of thread 37472:
                #0  0x00007f8053665d22 raise (libc.so.6 + 0x3cd22)
                #1  0x00007f8053665da0 __restore_rt (libc.so.6 + 0x3cda0)
                #2  0x00007f802a510f31 n/a (iris_dri.so + 0x1ddf31)
                #3  0x00007f802b5f88af n/a (iris_dri.so + 0x12c58af)
                #4  0x00007f802a7344d0 n/a (iris_dri.so + 0x4014d0)
                #5  0x00007f802a56eadf n/a (iris_dri.so + 0x23badf)
                #6  0x00007f802a570597 n/a (iris_dri.so + 0x23d597)
                #7  0x00007f802a713d2d n/a (iris_dri.so + 0x3e0d2d)
                #8  0x00007f802a713e12 n/a (iris_dri.so + 0x3e0e12)
                #9  0x00007f8047a411d5 n/a (libQt5WebEngineCore.so.5 + 0x31071d5)
...
```

which also explains why your Xorg crashes too, I guess. I'm afraid there won't be anything qutebrowser could do about this.

**Comment by jsilve24** [comment]
For the first option (setting QTWEBENGINE_DISABLE_GPU_THREAD=1) you mean set that in .zshrc or something right?

Justin

**Comment by The-Compiler** [comment]
In `.zshrc`, it would only be read for shell sessions, and not when you start qutebrowser via the GUI somehow. Something like `~/.profile` would likely be more appropriate.

You should be able to verify that it works by checking `:debug-pyeval list(os.environ)` (you can search via e.g. `/THREAD` there as usual).
