### ISSUE TITLE
Prevent change of viewport height when status bar shows up

### ISSUE THREAD

**Issue by Brixy** [qutebrowser/qutebrowser#7039]
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
No

**Description**
When the statusbar becomes visible the view port height changes.

This may lead to notable jumps if websites use the [`vh`](https://caniuse.com/?search=vh) unit for margins or padding.

**How to reproduce**
- `:set statusbar.show in-mode`
- visit [moderncss.dev](https://moderncss.dev/)
- press `f` key so that the status bar shows up.

If have seen far more extreme examples which I cannot find any more.

**Comment by The-Compiler** [comment]
See #1593 and also #5480.
