### ISSUE TITLE
Idle inhibitor on wayland doesn't work (idle-inhibit protocol)

### ISSUE THREAD

**Issue by Gochkin** [qutebrowser/qutebrowser#7041]
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qutebrowser not activating idle inhibitor on wayland, nor through idle-inhibit wayland porotol (by wayland compositor) nor through systemd-inhibit. The result is that while watching videos on YouTube the computer enters idle states (lockscreen, screen turn off, sleep)

**How to reproduce**
Launch video on YouTube and wait.

Probably it's problem with Qt, but still It should be reported here as well.

**Comment by toofar** [comment]
I know nothing about wayland but have a look through this issue, you may be running into the same thing or be able to make use of one of the workaround there https://github.com/qutebrowser/qutebrowser/issues/5504

**Comment by The-Compiler** [comment]
Merging this into #5504. Even if it's a different underlying issue, this will need to be reported to and fixed in QtWebEngine, I don't think there is anything qutebrowser can do about this.
