### ISSUE TITLE
Qutebrowser broked after Qt updates

### ISSUE THREAD

**Issue by weebcyberpunk** [qutebrowser/qutebrowser#7055]
Cannot even launch Qutebrowser to find out the version.

Bug still happens with --temp-basedir and --nowindow.

Basically, after the update of some Qt packages on ArchLinux, qutebrowser cannot launch and gets the following error:

`21:49:45 CRITICAL: Cannot mix incompatible Qt library (5.15.2) with this library (5.15.3)
Fatal Python error: Aborted

Current thread 0x00007f275a12b740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 558 in __init__
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 95 in run
  File "/usr/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245 in main
  File "/usr/bin/qutebrowser", line 33 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, markupsafe._speedups, yaml._yaml, PyQt5.QtNetwork, PyQt5.QtQml, PyQt5.QtSql, PyQt
5.QtOpenGL, PyQt5.QtDBus, PyQt5.QtWebChannel, PyQt5.QtWebEngineCore, PyQt5.QtPrintSupport, PyQt5.QtWebEngineWidgets, PyQt5.QtWebEngine (total: 1
5)`

Of course, I downgraded the packages that were updated to the earlier version: `qt5-base`, `qt5-declarative`, `qt5-location`, `qt5-translations`
, `qt5-webchannel` and `qt5-webengine`.

After the downgrade, qutebrowser showed the following error, even with --temp-dir:

`Fatal error: PyQt5.QtCore is required to run qutebrowser but could not be imported! Maybe it's not installed?

The error encountered was:
libicui18n.so.68: cannot open shared object file: No such file or directory

Please search for the python3 version of PyQt5.QtCore in your distributions packages, or see https://github.com/qutebrowser/qutebrowser/blob/mas
ter/doc/install.asciidoc

If you installed a qutebrowser package for your distribution, please report this as a bug.`

Then, I downgraded `python-pyqt5` and `python-pyqt5-webengine` with no changes to the errors.

**Comment by mschilli87** [comment]
Looks to me like your are mixing incompatibe versions of Qt itseld and the PyQt library built on top of it that is used by qutebrowser. I don't use Arch (btw :wink:) so I don't know the package names but I assume (re-)installing the PyQt package(s) will fix the issue.

**Comment by yuandi42** [comment]
> 

I came across the same problems, but sad that reinstall `python qt5` and `python-pyqt5-webengine` make no change.

**Comment by mschilli87** [comment]
@yuandi42: Did you try `python-pyqt5` as well? The error message mentions `PyQt5.QtCore`. I doubt that would be provided by either `qt5` or `python-pyqt5-webengine` and certainly not by plain `python`.

**Comment by QMaury** [comment]
@mschilli87 
I've tried reinstalling `python-pyqt5` already. Didn't seem to do anything.

**Comment by mschilli87** [comment]
@QMaury: What versio of `python-pyqt5` are you trying to combine with what version of `qt5`?

**Comment by QMaury** [comment]
@mschilli87 `python-pyqt5-5.15.6-7` and `qt5-5.15.3-1`

**Comment by mschilli87** [comment]
I'm out of ideas then. But this looks more like an Arch issue than a qutebrowser one anyhow. So there are probably better support channels for this problem.

**Comment by The-Compiler** [comment]
This isn't about PyQt - a "Qt plugin" refers to something loaded by Qt, i.e. things like platform themes, etc.

I can see three reasons why this could happen:

- A partially upgraded system - [partial upgrades are unsupported](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported), so make sure your system is fully upgraded
- A Qt plugin from the AUR which needs a rebuild against the newer Qt version (with the AUR, you're probably responsible yourself for rebuilding)
- An Archlinux packaging bug.  Very unlikely.

Usually it's an AUR package, with the usual culprit being `qt5-styleplugins`. Once you rebuild that, it should work fine again, it did for me. If it's not that, you can use `find /usr/lib/qt/plugins/ -type f | xargs pacman -Qoq | sort | uniq` to find all packages installing Qt plugins (compare with `pacman -Qmq` to get all AUR packages); or you can export `QT_DEBUG_PLUGINS=1` to see what Qt actually loads.

None of that is specific to qutebrowser though, you will see the same issue when loading any other Qt application too.
