### ISSUE TITLE
Recurrent crashes on wayland

### ISSUE THREAD

**Issue by Superc3lll** [qutebrowser/qutebrowser#7057]
Basically I can't use qutebrowser for like an hour without a crash on wayland session. Doesn't happen under X11 as far as I can tell, but I don't want to have to switch to xorg to use a browser. 

The error: Fatal Python error: Segmentation fault
I'm using Arch with sway, 
qutebrowser: v2.4.0
Qt: 5.15.3
pyQt: 5.15.6

All other info is to be found in this log:
[qutelog.txt](https://github.com/qutebrowser/qutebrowser/files/8203560/qutelog.txt)

**Comment by toofar** [comment]
Hmm, not seeing anything interesting in there.
Can you launch from the terminal with --debug and see if there is anything interesting logged right before it crashes?

**Comment by Superc3lll** [comment]
> Hmm, not seeing anything interesting in there. Can you launch from the terminal with --debug and see if there is anything interesting logged right before it crashes?

Will do, I'll post back as soon as I get something.

**Comment by Superc3lll** [comment]
> > Hmm, not seeing anything interesting in there. Can you launch from the terminal with --debug and see if there is anything interesting logged right before it crashes?
> 
> --debug doesn't show anything interesting either, just the same error: core dumped: segmentation fault.

**Comment by Superc3lll** [comment]
> @Superc3lll If you run `coredumpctl`, are there entries for `qutebrowswer` or `python` in there?
Running coredumpctl shows that it's python. no mentien of qutebrowser, so I'm guessing it has to do with my python setup. But it's weird that it doesn't crash under X11. any suggestions on how  to approch this?

**Comment by Superc3lll** [comment]
@toofar this is tha last few lines of debug log before the latest crash:
`10:21:29 DEBUG    mouse      eventfilter:_mousepress_insertmode_cb:204 Clicked non-editable element!
10:21:29 DEBUG    modes      modeman:leave:424 Ignoring leave request for KeyMode.insert (reason click) as we're in mode KeyMode.normal
10:21:30 DEBUG    webview    webenginetab:_js_cb_single:752 Got element from JS: {'attributes': {'class': 'explicit-resolution'}, 'class_name': 'explicit-resolution', 'id': 24, 'is_content_editable': False, 'outer_xml': '<button class="explicit-resolution"><span>1280p</span></button>', 'rects': [{'bottom': 451, 'height': 30, 'left': 1124.5625, 'right': 1293.5625, 'top': 421, 'width': 169}], 'tag_name': 'BUTTON', 'text': '1280p', 'value': ''}
10:21:30 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<button class="explicit-resolution"><span>1280p</span></button>'>
10:21:30 DEBUG    mouse      eventfilter:_mousepress_insertmode_cb:204 Clicked non-editable element!
10:21:30 DEBUG    modes      modeman:leave:424 Ignoring leave request for KeyMode.insert (reason click) as we're in mode KeyMode.normal
10:21:31 DEBUG    webview    webenginetab:_js_cb_single:752 Got element from JS: {'attributes': {'class': 'explicit-resolution'}, 'class_name': 'explicit-resolution', 'id': 25, 'is_content_editable': False, 'outer_xml': '<button class="explicit-resolution"><span>640p</span></button>', 'rects': [{'bottom': 516, 'height': 30, 'left': 1124.5625, 'right': 1293.5625, 'top': 486, 'width': 169}], 'tag_name': 'BUTTON', 'text': '640p', 'value': ''}
10:21:31 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<button class="explicit-resolution"><span>640p</span></button>'>
10:21:31 DEBUG    mouse      eventfilter:_mousepress_insertmode_cb:204 Clicked non-editable element!
10:21:31 DEBUG    modes      modeman:leave:424 Ignoring leave request for KeyMode.insert (reason click) as we're in mode KeyMode.normal
10:21:33 DEBUG    webview    webenginetab:_js_cb_single:752 Got element from JS: {'attributes': {'class': 'font-bold mt-2 text-2xl break-words'}, 'class_name': 'font-bold mt-2 text-2xl break-words', 'id': 26, 'is_content_editable': False, 'outer_xml': '<div class="font-bold mt-2 text-2xl break-words">Apple makes my brain hurt…</div>', 'rects': [{'bottom': 676, 'height': 32, 'left': 13.4375, 'right': 1319.5625, 'top': 644, 'width': 1306.125}], 'tag_name': 'DIV', 'text': 'Apple makes my brain hurt…', 'value': ''}
10:21:33 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<div class="font-bold mt-2 text-2xl break-words">Apple makes my brain hurt…</div>'>
10:21:33 DEBUG    mouse      eventfilter:_mousepress_insertmode_cb:204 Clicked non-editable element!
10:21:33 DEBUG    modes      modeman:leave:424 Ignoring leave request for KeyMode.insert (reason click) as we're in mode KeyMode.normal
10:21:42 DEBUG    js         shared:javascript_log_message:156 [https://piped.kavin.rocks/assets/WatchVideo.20341362.js:14] Skipped segment at 29.773745
10:21:44 DEBUG    js         shared:javascript_log_message:156 [https://piped.kavin.rocks/assets/WatchVideo.20341362.js:14] Skipped segment at 47
10:23:38 DEBUG    ipc        ipc:update_atime:429 Touching /run/user/1000/qutebrowser/ipc-4e71237d9e65502305c5d164ec0e536e
zsh: segmentation fault (core dumped)  qutebrowser --debug`

I should add that it always seems to happen when I'm watching a video.

**Comment by markstos** [comment]
@Superc3lll: Some things that could help:

  - Provide a URL of a page of video that crashes the site if watched repeatedly
  - Read about how to use `coredumpctl`: https://fedoramagazine.org/file-better-bugs-coredumpctl/  You may need to install libraries with debug symbols, such as: https://github.com/qutebrowser/qt-debug-pkgbuild  Those entries in `coredumpctl` mention Python because Python is the process that runs qutebrowser.

**Comment by The-Compiler** [comment]
@Superc3lll Any update on this? Unfortunately my debug packages are out of date (and official Archlinux ones are close, but not working yet). However, even a stacktrace without any debugging symbols would help. Not much I can say without.

**Comment by Superc3lll** [comment]
@The-Compiler I've given up on sway & waylnad for the moment, and using X with dwm instead. No problems so far. I've tried dwl (dwm fork for wayland) but experienced some weird behavior; the cursor gets bigger when active on qutebrowser window and the key inputs (i.e typing something into google) are way too slow to the point of becoming unusable, but that may be dwl's fault as it is still young in developpement. So yeeah, just good old xorg for now.

**Comment by mschilli87** [comment]
Not sure if this is useful information but I am using qutebrowser in sway (under Gentoo) without any issues for close to two years and do not experience any such crashes.

**Comment by Superc3lll** [comment]
It's worth noting that since I replied to your post today, which is about 6 hours, give or take, I tought why not give sway one last shot to see if anything changed (since there's been some Qt updates recently), and no crashes so far. So fingers crossed.
