### ISSUE TITLE
no sound in spotify (all the rest sound ok)

### ISSUE THREAD

**Issue by verajosemanuel** [qutebrowser/qutebrowser#7060]
**Version info**:
qutebrowser v2.4.0
Git commit: 36ffff2f6 on HEAD (2021-10-21 18:50:06 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

Windows 10

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Spotify has no sound. Any other page has sound (youtube, ivoox, soundcloud...)

**How to reproduce**
1. open spotify web player at https://open.spotify.com
2. play any song
3. after several tries, Qutebrowser crashes just opening spotify web player, having to reinstall it

**Comment by The-Compiler** [comment]
Could you please show your full version information?

**Comment by verajosemanuel** [comment]
Sure!

`Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.4.0
Git commit: 36ffff2f6 on HEAD (2021-10-21 18:50:06 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.7
PyQt: 5.15.5

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.2
pygments: 2.10.0
yaml: 6.0
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.10.377 (bundled)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QWindowsVistaStyle
Platform plugin: windows
OpenGL: Intel, 4.6.0 - Build 27.20.100.8336
Platform: Windows-10-10.0.19042-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt5/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt5
OS Version: 10, 10.0.19042, SP0, Multiprocessor Free

Paths:
cache: C:\Users\joe\AppData\Local\qutebrowser\cache
config: C:\Users\joe\AppData\Roaming\qutebrowser\config
data: C:\Users\joe\AppData\Roaming\qutebrowser\data
runtime: C:\Users\joe\AppData\Local\Temp\qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:07`

**Comment by The-Compiler** [comment]
It looks like you have an install with a prebuilt Qt/PyQt. As mentioned in the [install docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc):

> The binary release ships with a QtWebEngine built without proprietary codec support. To get support for e.g. h264/mp4 videos, you’ll need to build QtWebEngine from source yourself with support for that enabled.
