### ISSUE TITLE
Pages saved with auto_save.session are lost if the pages don't finish loading after trying to restore and quitting

### ISSUE THREAD

**Issue by videla98** [qutebrowser/qutebrowser#7095]
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

CPython: 3.10.3
PyQt: 5.15.6

**Does the bug happen if you start with `--temp-basedir`?**:
auto_save.session is not enabled with --temp-basedir

**Description**
The tabs in the session will be lost if the pages don't finish loading (or get to a certain state, i'm not sure) before closing qutebrowser again. In the next reopen the tabs will be there but without any pages to load.
I sometimes click the wrong key on my keyboard and open the browser withouth meaning too. I then close it by reflex, because I wanted to do something else, and lose wathever I was doing before.

**How to reproduce**
Enable auto_save.session.
Open a few tabs and load a page in each one.
![2022-04-02-132419_1920x1080_scrot](https://user-images.githubusercontent.com/38320094/161392153-e4bb6852-b5d1-4987-9a45-c6df492cc7d1.png)
Close Qutebrowser.
Open qutebrowser and quit as soon as the tabs show up.
Next reopen:
![2022-04-02-132503_1920x1080_scrot](https://user-images.githubusercontent.com/38320094/161392161-0410e190-02c4-420d-ad62-8e8eb58f4987.png)

**Comment by The-Compiler** [comment]
This happens due to #5359 combined with #2176.
