### ISSUE TITLE
Qutebrowser 2.5.0 macOS build reported as damaged

### ISSUE THREAD

**Issue by acollign** [qutebrowser/qutebrowser#7107]
**Version info**:
- qutebrowser 2.5.0 released as part of DMG file at https://github.com/qutebrowser/qutebrowser/releases/tag/v2.5.0
- macOS Monterey Version 12.3 (21E230)

**Does the bug happen if you start with `--temp-basedir`?**: the binary is damaged and cannot be launched

**Description**
macOS reports "“qutebrowser.app” is damaged and can’t be opened. You should eject the disk image."

**How to reproduce**
- Download Qutebrowser 2.5.0 DMG at https://github.com/qutebrowser/qutebrowser/releases/tag/v2.5.0
- Open qutebrowser-2.5.0.dmg
- Launch qutebrowser

**Expected Result**
Qutebrowser happily opens up

Thanks guys for building such a great browser!

**Comment by The-Compiler** [comment]
Duplicate of #6771

**Comment by tigger04** [comment]
I have the same issue on MacOS 12.3.1
