### ISSUE TITLE
Windows installer: Base icon choices on previous install

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7109]
I don't like icons on my Desktop - every time I upgrade qutebrowser on Windows via the installer, it suggests placing an icon on the desktop, and I need to remember to deselect the option.

It'd be great if the installer could remember the previous choice (e.g. via the registry I suppose, or just checking if there is a qutebrowser icon on the desktop / startmenu right now, I suppose?), and then keep that selection.

cc @bitraid

**Comment by bitraid** [comment]
Yes, the new version already does that (on upgrades, it sets the selection according to the existence of the file). I'll start working on finishing it - it shouldn't take long.
