### ISSUE TITLE
Windows Installer Uses Wrong Color in Dark High-Contrast Theme

### ISSUE THREAD

**Issue by mentalisttraceur** [qutebrowser/qutebrowser#7112]
**Version info**:
```
qutebrowser v2.5.0
Git commit: 01a402dcf on HEAD (2022-04-01 16:59:20 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
N/A

**Description**
When a Windows user has a dark "high-contrast" theme configured, the installer has a weird mismatch of light and dark areas.

I'm not sure if Qutebrowser can do anything about this or if this is a deeper problem in something that Qutebrowser depends on.

So the result looks like this:
![Screenshot-2022-04-07 033308](https://user-images.githubusercontent.com/6531708/162115788-9a686ae6-84fd-4e33-9d4f-5bad60bf583d.png)
![Screenshot-2022-04-07 033451](https://user-images.githubusercontent.com/6531708/162115793-ed46546b-f400-422b-8981-48c89cb56c42.png)
![Screenshot-2022-04-07 033635](https://user-images.githubusercontent.com/6531708/162115841-9227184b-5692-4104-a78d-540f93d43d9d.png)
![Screenshot-2022-04-07 033709](https://user-images.githubusercontent.com/6531708/162115850-17ddee7b-26f7-4e9b-9d64-843d3be6a620.png)

**How to reproduce**
1. Use Windows 11 (10 should also work, not sure about earlier).
2. Set your theme to a dark high contrast theme (I think the high contrast themes built into Windows will do it, but if not then I think you can also create a new file with a `.theme` extension and paste the contents of the code block below into it with f.e. Notepad).
3. Run Qutebrowser 2.5.0 64-bit installer from this Github's releases page.

```
[Theme]
; High Contrast Black - IDS_THEME_DISPLAYNAME_HCBLACK
DisplayName=koztrast
ThemeId={99BB141C-B135-4B75-923E-569762A27CF8}

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55

[Control Panel\Colors]
ActiveTitle=63 63 63
Background=0 0 0
ButtonFace=0 0 0
ButtonText=170 170 170
GrayText=111 111 111
Hilight=95 95 95
HilightText=0 0 0
HotTrackingColor=130 0 0
InactiveTitle=23 23 23
InactiveTitleText=170 170 170
TitleText=170 170 170
Window=0 0 0
WindowText=170 170 170
Scrollbar=0 0 0
Menu=0 0 0
WindowFrame=63 63 63
MenuText=170 170 170
ActiveBorder=255 255 0
InactiveBorder=0 128 0
AppWorkspace=0 0 0
ButtonShadow=128 128 128
ButtonHilight=192 192 192
ButtonDkShadow=127 127 127
ButtonLight=127 127 127
InfoText=170 170 170
InfoWindow=0 0 0
ButtonAlternateFace=192 192 192
GradientActiveTitle=79 79 79
GradientInactiveTitle=0 128 0
MenuHilight=79 79 79
MenuBar=0 0 0

[Control Panel\Cursors]
Arrow=%SystemRoot%\cursors\aero_arrow.cur
Help=%SystemRoot%\cursors\aero_helpsel.cur
AppStarting=%SystemRoot%\cursors\aero_working.ani
Wait=%SystemRoot%\cursors\aero_busy.ani
NWPen=%SystemRoot%\cursors\aero_pen.cur
No=%SystemRoot%\cursors\aero_unavail.cur
SizeNS=%SystemRoot%\cursors\aero_ns.cur
SizeWE=%SystemRoot%\cursors\aero_ew.cur
Crosshair=
IBeam=
SizeNWSE=%SystemRoot%\cursors\aero_nwse.cur
SizeNESW=%SystemRoot%\cursors\aero_nesw.cur
SizeAll=%SystemRoot%\cursors\aero_move.cur
UpArrow=%SystemRoot%\cursors\aero_up.cur
DefaultValue=Windows Default
Hand=%SystemRoot%\cursors\aero_link.cur
Link=

[Control Panel\Desktop]
Wallpaper=
Pattern=
MultimonBackgrounds=0
PicturePosition=4

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\AeroLite.msstyles
ColorStyle=NormalColor
Size=NormalSize
HighContrast=3
ColorizationColor=0XC44C4A48
AutoColorization=0
AppMode=Light
SystemMode=Light
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=@mmres.dll,-800
```

**Comment by The-Compiler** [comment]
cc @bitraid

**Comment by bitraid** [comment]
I guess having dark theme support would make things look better. This is something I've already thought of adding to the new version. As a win32 app (in contrast to uwp), we have to detect whether the dark mode is enabled, manually change the colors of the controls, and also (depending on Windows version) call the appropriate API to set the window attributes. I'll give it a go and see how it looks.

**Comment by bitraid** [comment]
After finishing the dark skin, I tested the theme and realized that this is not a dark mode theme (I should have been more observant):
>```
>AppMode=Light
>SystemMode=Light
>```

The issue comes from something different: The MUI 2 interface of NSIS has its color values hardcoded. This is an easy two-lines fix.

**Comment by mentalisttraceur** [comment]
@bitraid yep, I think Windows' high-contrast themes always report themselves as "Light", even though visually they are dark, unless you go out of your way to change it by dumping a .theme file and editing those fields.

So that's actually representative of the information you'd get from a normal high-contrast user, and that's why I left it alone: I figured existing code that handles high-contrast correctly might be relying on that to work correctly.

Of course, work towards a proper dark theme is also extremely valuable! The only reason I am using a high contrast theme (with the contrast manually dialed back down) is that it gets me a more consistent dark theme than the actual dark theme.
