### ISSUE TITLE
Unable to load Github page

### ISSUE THREAD

**Issue by huyhoang8398** [qutebrowser/qutebrowser#7114]
**Version info**:
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
After login from the github page, it unable to load

**How to reproduce**

1. Launch qutebrowser
2. Open https://github.com/
3. Login
4. Unable to load content as the image below
![image](https://user-images.githubusercontent.com/25379882/162206129-4caafa64-b05f-4d16-b5a5-c2c3f3093e93.png)

**Comment by The-Compiler** [comment]
You are using an old version of qutebrowser (February 2020) with an even older Qt (based on a Chromium from 2018). Chances are this is just not supported by GitHub anymore, and you will need to upgrade.
