### ISSUE TITLE
Qutebrowser is showing the wrong content

### ISSUE THREAD

**Issue by CanadianJeff** [qutebrowser/qutebrowser#7115]
![image1](https://usercontent.irccloud-cdn.com/file/4L1cld2v/image.png)
![image2](https://usercontent.irccloud-cdn.com/file/mwxlKsFZ/NTFYCHPvuh.png)

https://www.ssllabs.com/ssltest/analyze.html?d=worldofsimps.com

the website has an A Rating on SSLLABS

**Comment by EliteTK** [comment]
www vs non-www, this is a webserver configuration problem and nothing to do with qutebrowser

**Comment by CanadianJeff** [comment]
ah I need to fix this closing the issue
