### ISSUE TITLE
Renderer process crash when middle-clicking XDA link

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7118]
I'm also having this problem when opening [this link](https://forum.xda-developers.com/t/recovery-root-twrp-3-3-1-1-galaxy-j6-j610f-fn-g-ds.3875150/) with middle-click from duckduckgo search (or from 'Preview' of this comment).
This is the version info: http://sprunge.us/oZSegk
And this is a screenshot: https://postimg.cc/WhnCgYQx

I run qutebrowser with the **-T** flag.

I run qutebrowser on a fresh ArchLinux install. This is the packages list (with versions) I have installed: http://sprunge.us/tViayw (might be useful).

All of my tabs get crashed, but I can undo them and they work. This error doesn't happen when I open the link with the :open command, but always happens when I open the link with middle click.

_Originally posted by @GasparVardanyan in https://github.com/qutebrowser/qutebrowser/issues/6953#issuecomment-1093361480_

**Comment by piperfw** [comment]
Middle-clicking the link results in a rendered process crash for me also.

I noticed experienced problems with this crash on several pages - not necessarily acccessed via middle-click - since upgrading qt5-webengine (5.15.8-10 -> 5.15.9-1) on my system, although perhaps that is a red-herring as my QtWebEngine version is [version is 5.15.5](https://paste.the-compiler.org/view/ef544f53), matching yours.

Example of page that reliably crashes for me: https://www.britishcycling.org.uk/events/details/253518/PORTSMOUTH-EASTER-CIRCUITS

**Comment by GasparVardanyan** [comment]
@piperfw doses [this link](https://forum.xda-developers.com/t/recovery-root-twrp-3-3-1-1-galaxy-j6-j610f-fn-g-ds.3875150/) crash for you? The link you've shared doesn't crash for me.

**Comment by piperfw** [comment]
@GasparVardanyan it does, is there another known cause for this issue?

**Comment by GasparVardanyan** [comment]
no ((

**Comment by GasparVardanyan** [comment]
no ((

**Comment by piperfw** [comment]
Downgrading `qt5-webengine (5.15.9-1 => 5.15.8-10)` fixed the issue on my system.

Attached is the log (with  `5.15.9-1`) when the crash occurs from the link Gaspar provides.
[renderer_crash.log](https://github.com/qutebrowser/qutebrowser/files/8461907/renderer_crash.log)

**Comment by merdely** [comment]
Thank you, @piperfw .  I was having the same problem with https://www.home-assistant.io/blog/2022/04/06/release-20224/ and reverting qt5-webengine fixed it for me.

**Comment by martonbalazs** [comment]
While most of the examples above won't crash for me, the Britishcycling link does. Here are a few more (cycling-related ;-) ) pages that do crash: https://www.cyclebristolctc.org.uk/rideinfo https://www.discoverclevedon.co.uk/event/the-clifton-clevedon-charity-cycle-ride

The error is always 'Renderer process crashed (status 133)' but other tabs keep running fine. 

qutebrowser v2.5.0
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

Perhaps this version doesn't like bikes. :-D

**Comment by isaachaller** [comment]
I'm having a similar issue with links to any thread on [forum.proxmox.com](forum.proxmox.com), except when the tab is already on that website. However, running `qutebrowser -T` does solve the issue.

**Comment by martonbalazs** [comment]
@isaachaller Thanks! After looking at what -T does, I have now stopped Qutebrowser, deleted my `.local/share/qutebrowser` folder altogether and can open just fine all the links listed as problemous above, including those that consistently failed for me before.

**Comment by The-Compiler** [comment]
For others reading this, please don't delete the "evidence" right away, as this makes it pretty much impossible to figure out what the culprit was.

**Comment by GasparVardanyan** [comment]
I have installed a lot of greasemonkey scripts in .local/share/qutebrowser/

**Comment by martonbalazs** [comment]
@The-Compiler I have a backup copy and I'm happy to provide "evidence" if you tell me what you need (although I have no idea what personal data is included in that directory).

**Comment by martonbalazs** [comment]
By the way those cycling sites above are now crashing again... so removing .local/share/qutebrowser every other day might not be the best workaround after all.

**Comment by brianbuccola** [comment]
I'm getting quite a number of "renderer process crashed" errors lately. Most consistently, when I do `:open !m`, which is supposed to open Google Maps via the DuckDuckGo `!m` [bang](https://duckduckgo.com/bang). Weirdly, `:open !w` (for Wikipedia) works fine, and so does `:open maps.google.com`, so it's a bit perplexing what's going on.

**Comment by The-Compiler** [comment]
For others who report this, please at least include:

- The first section of your `:version` information
- Whether you can reproduce using `--temp-basedir`
- The last few lines of the terminal output with `--debug`

A renderer process crash is just a symptom, but can be caused by many different things. I'm trying to make sense of it all before reporting this upstream (nothing qutebrowser itself can do about those, unless there is some workaround, but there rarely is).

@martonbalazs I'm mainly interested in whether only removing `webengine/Service Worker` there changes anything.

**Comment by brianbuccola** [comment]
I can tell you that for me, it does *not* happen using `--temp-basedir` (or private mode for that matter). (I'm referring to `:open !m` above.)

Here's what I think are the useful lines from `--debug` after running `:open !m` in my normal (non-private, non-`--temp-basedir`) session:

```
10:24:07 DEBUG    webview    browsertab:_set_load_status:1008 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://duckduckgo.com/?q=%21m'>: LoadStatus.success_https
10:24:07 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.success_https: 3>) (tab 0)
10:24:07 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(False) (tab 0)
10:24:07 DEBUG    modes      modeman:leave:424 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
10:24:07 DEBUG    modes      tabbedbrowser:_leave_modes_on_load:740 Ignoring leave_on_load request due to setting.
10:24:07 DEBUG    webview    browsertab:_set_load_status:1008 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://duckduckgo.com/?q=%21m'>: LoadStatus.error
10:24:07 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.error: 4>) (tab 0)
10:24:07 DEBUG    misc       eventfilter:eventFilter:53 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f1d8802c1f0> got new child <PyQt5.QtWidgets.QWidget object at 0x7f1d880777f0>, installing filter
10:24:07 DEBUG    webview    browsertab:_on_navigation_request:1066 navigation request: url data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…, type Type.typed, is_main_frame True
10:24:07 ERROR    webview    tabbedbrowser:show_error_page:968 Renderer process crashed (status 133)
10:24:07 DEBUG    webview    webenginetab:_store_match_data:152 Active search match: 0/0
10:24:07 DEBUG    webview    browsertab:_set_load_status:1008 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://duckduckgo.com/?q=%21m'>: LoadStatus.loading
10:24:07 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 0)
10:24:07 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 0)
10:24:07 DEBUG    misc       app:on_focus_object_changed:581 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f1d88077a30>
10:24:07 DEBUG    misc       app:on_focus_object_changed:581 Focus object changed: <PyQt5.QtCore.QObject object at 0x7f1d88077a30>
10:24:07 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_changed(PyQt5.QtCore.QUrl('data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf-8 sts%3D4 sw%3D4 et%3A%0A--%3E%0A%0A%3Chtml%3E%0A    %3Chead%3E%0A        %3Cmet…) (tab 0)
10:24:07 DEBUG    webview    tabbedbrowser:_on_title_changed:760 Changing title for idx 0 to 'about:blank'
10:24:07 DEBUG    webview    tabbedbrowser:_on_title_changed:760 Changing title for idx 0 to 'Error loading https://duckduckgo.com/?q=%21m'
10:24:07 DEBUG    webview    browsertab:_set_load_status:1008 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…'>: LoadStatus.success
```

I guess I could try wiping out (part of) my cache, but I'm not totally sure how to do that without losing useful cookies etc.

**Comment by The-Compiler** [comment]
@brianbuccola First thing I'd try is to also remove `webengine/Service Worker` in your data directory (see `:version`). There should not be any important persistent data in there.

**Comment by brianbuccola** [comment]
> remove `webengine/Service Worker` in your data directory

That worked! At least for `:open !m`. I'll keep an eye out for any other crashes (it's been happening on a number of other random webpages too). Future silence means it's all fixed. :+1:

**Comment by martonbalazs** [comment]
@The-Compiler 
Below, [1] = https://www.cyclebristolctc.org.uk/rideinfo

1. with --debug, opening [1] and crashing it (which happens quite predictably):
https://paste.the-compiler.org/view/67cb36d3


2. :version
https://paste.the-compiler.org/view/30f78be8


3. remove webengine/Service Worker:

After removing webengine/Service Worker: [1] loads fine 5 out of 5. I then went to maps.google.com (logged in), [1] worked once more (but slower) then consistently crashed from thereon (5 out of 5). I repeated this experiment twice, removing webengine/Service Worker sorts it out until my first visit to maps.google.com, from where the first visit to [1] is a bit slower and second and further loadings of [1] crash reliably.


4. --temp-basedir
Exact same thing: no crash of [1] before I visit maps.google.com (not logged in), then one more loading of [1] is slower but ok then crashes on [1] consistently.


5a --debug when opening maps.google.com after having removed webengine/Service Worker:
https://paste.the-compiler.org/view/754fdf10


5b --debug, when opening [1] after maps.google.com (slow loading but no crash yet):
https://paste.the-compiler.org/view/deeed3a7


5c --debug, second opening of [1] and crash:
https://paste.the-compiler.org/view/9d005d37

Many thanks!

**Comment by brianbuccola** [comment]
(Since I said above that future silence means it's all fixed, I'm just commenting here to reiterate what @martonbalazs wrote above: it's only fixed temporarily; after running `:open !m` a few times, it starts crashing consistently again, until I remove `webengine/Service Worker` again.)

**Comment by The-Compiler** [comment]
Thanks to the reproducer by @martonbalazs, I reported this to a Qt developer now, who opened [[QTBUG-102961] Regression 5.15.8 -> 5.15.9 Renderer crash in certain Service Worker setups - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-102961).

As a workaround, setting `qt.workarounds.remove_service_workers` might make things more stable. I don't think there's much more we can do about it, I'm afraid.

**Comment by GasparVardanyan** [comment]
Thank you!

**Comment by martonbalazs** [comment]
Thanks a lot for your work with Qutebrowser!

**Comment by tinglycraniumplacidly** [comment]
> Thanks to the reproducer by @martonbalazs, I reported this to a Qt developer now, who opened [[QTBUG-102961] Regression 5.15.8 -> 5.15.9 Renderer crash in certain Service Worker setups - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-102961).
> 
> As a workaround, setting `qt.workarounds.remove_service_workers` might make things more stable. I don't think there's much more we can do about it, I'm afraid.

where do i set this?

**Comment by The-Compiler** [comment]
> where do i set this?

Same as any other qutebrowser setting (you don't necessarily need a `config.py`. See [the documentation](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).

**Comment by nicolink47** [comment]
Hi,
I have the same problem when i want to go on racedepartement.com and other sites.
This option `qt.workarounds.remove_service_workers` does not changing anything.

**Comment by The-Compiler** [comment]
@nicolink47 This website doesn't exist. Please open a new issue with the information asked for in the issue template.

**Comment by nicolink47** [comment]
Sorry i re-edit my post with the good url (a french error), but i will open a new issue.

**Comment by The-Compiler** [comment]
For searchability, this is for the crash that happens after `[714901:30:0510/152720.891574:FATAL:fetch_manager.cc(380)]`.

**Comment by YarekTyshchenko** [comment]
:( Crashes pretty consistently on `portal.azure.com`.
```
[122657:16:0223/083459.710855:FATAL:fetch_manager.cc(380)]
[122964:36:0223/083459.883164:FATAL:fetch_manager.cc(380)]
08:34:59 ERROR: Renderer process crashed (status 133)
08:35:00 ERROR: Renderer process crashed (status 133)
```
```
qutebrowser v2.5.0
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3

CPython: 3.10.6
PyQt: 5.15.6

adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
```

**Comment by YarekTyshchenko** [comment]
Think I answered my own question here. Looks like I need to upgrade Qt to at least `5.15.10`

**Comment by toofar** [comment]
@YarekTyshchenko 
> Installing qutebrowser from git didn't update QtWebEngine. Is this something I have to compile on my system separately to get latest?

Normally you would have a pre-built library available for your operating system (you can compile it yourself bit its a fair bit of work), if you are on 5.15.2 you must be on a pretty old system. If your operating system hasn't got a newer webengine, and you can't update your operating system you can either install [a virtualenv](https://qutebrowser.org/doc/install.html#tox) with the qutebrowser dependencies (including Qt, but without proprietary codec support) or install qutebrowser via [flatpak](https://github.com/flathub/org.qutebrowser.qutebrowser) (which I believe does have proprietary codecs).

**Comment by The-Compiler** [comment]
> if you are on 5.15.2 you must be on a pretty old system. 

This is (sadly) the last Qt 5.15 version that was available as a binary (and thus is available via virtualenv) before Qt pulled their [LTS releases are commercial only](https://www.qt.io/blog/commercial-lts-qt-5.15.3-released) move...

**Comment by YarekTyshchenko** [comment]
I'm on
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
Tried compiling latest qt but the build script just uses all the ram and gets killed, all 32GB of it, so seems broken.
Bit stuck now as git compiled Qutebrowser still has the issue (aside from also breaking userscripts (for pass), I assume they don't get installed into expected paths).

Shame about QT going closed source :( Sad news all around: I've been trying vimium for chrome, and its so buggy with keyboard, basically unusable.

**Comment by The-Compiler** [comment]
Please try a virtualenv install with Qt 6 binaries, see #7202 for instructions.

And no, Qt isn't going closed source (the [agreement between KDE and Qt prevents that](https://kde.org/community/whatiskde/kdefreeqtfoundation/)) - it's just that the long term releases do, and this happened at the worst time (just before Qt 6 came along).
