### ISSUE TITLE
Fatal error jinja2, dosen't open after update manjaro

### ISSUE THREAD

**Issue by pcampos119104** [qutebrowser/qutebrowser#7125]
**Version info**: Same error, dosen't run

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Error whem try to start, jinja is installed.
![image](https://user-images.githubusercontent.com/58258964/163552126-0658aea9-a7ea-4edc-8b5d-be1b496981ac.png)

**How to reproduce**

After update Qutebrowser in Manjaro package manager, just try to open.

**Comment by The-Compiler** [comment]
It sounds like you have an older version of Jinja installed which isn't coming from Manjaro's packages. What does `python3 -c "import jinja2; print(jinja2.__version__); print(jinja2.__file__)"` say?

**Comment by pcampos119104** [comment]
`python3 -c "import jinja2; print(jinja2.__version__); print(jinja2.__file__)"` gave me the same error, I dig more and in the end solved with `pip install markupsafe==2.0.1 `, now qutebrowser are starting. It was my mistake open the issue.
I love qutebrowser. Thanks @The-Compiler

**Comment by The-Compiler** [comment]
I would recommend never mixing pip-installed and pacman-installed packages. Check your `~/.local/share/python3.10/site-packages`, and anything there you should probably `pip uninstall` and install via pacman instead. Then use [virtual environments](https://packaging.python.org/en/latest/tutorials/installing-packages/#optionally-create-a-virtual-environment) if you need to install things via pip for a specific project.

**Comment by rsteube** [comment]
Had the same issue and can confirm that clearing the local packages `~/.local/lib/python3.x` fixed it.
