### ISSUE TITLE
teams.microsoft.com - unable to load page - Renderer process crashed (status 133)

### ISSUE THREAD

**Issue by rarcri** [qutebrowser/qutebrowser#7136]
**Version info**:

qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

**Does the bug happen if you start with `--temp-basedir`?**:
YES 

**Description**

**How to reproduce**

Just go to https://teams.microsoft.com/ login to your microsoft account and browse a little especially in the assignments tab.

** Other details **
If I use teams website for 1 minute it will crash at some point.
Recently they had an update to their website.
Their website is very heavy and bulky.
Before that I did not have any issues.

**Comment by The-Compiler** [comment]
I can't reproduce a crash, but for me, it starts to hang quite fast (i.e. the tab doesn't do anything anymore), but doesn't display a renderer process crash.

Can you show the full console output you get with `--temp-basedir`, and perhaps also the last couple of lines before the crash when you add `--debug`?

Either way, this is an upstream issue in QtWebEngine, and it seems to work fine with QtWebEngine 6.3 - see #5395 for the current state of qutebrowser supporting that. Likely qutebrowser can't do much about it.

**Comment by EmptyBucket** [comment]
Hello. I have the same problem but on a different site. This only happens if I'm logged into the site

https://user-images.githubusercontent.com/8377311/165072801-b8a9611a-1160-406b-a996-100b81918cc9.mp4

Debug output:
```
14:26:41 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 0)
[4737:23:0425/142641.986408:FATAL:fetch_manager.cc(380)]
14:26:42 DEBUG    modes      modeman:_handle_keypress:287 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
14:26:42 DEBUG    keyboard   basekeyparser:_debug_log:216 NormalKeyParser for mode normal: Got key: 0x1000001 / modifiers: 0x0 / text: '<Tab>' / dry_run False
14:26:42 DEBUG    keyboard   basekeyparser:_debug_log:216 NormalKeyParser for mode normal: Trying match without modifiers
14:26:42 DEBUG    keyboard   basekeyparser:_debug_log:216 NormalKeyParser for mode normal: Trying match with key_mappings
14:26:42 DEBUG    keyboard   basekeyparser:_debug_log:216 NormalKeyParser for mode normal: Giving up with '<Tab>', no matches
14:26:42 DEBUG    keyboard   basekeyparser:_debug_log:216 NormalKeyParser for mode normal: Clearing keystring (was: <Tab>).
14:26:42 DEBUG    modes      modeman:_handle_keypress:312 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f8f8839c820>)
14:26:42 DEBUG    modes      modeman:_handle_keyrelease:337 filter: False
14:26:42 DEBUG    misc       app:on_focus_object_changed:581 Focus object changed: <PyQt5.QtCore.QObject object at 0x7f8f8839caf0>
14:26:42 DEBUG    misc       app:on_focus_object_changed:581 Focus object changed: <qutebrowser.mainwindow.mainwindow.MainWindow>
14:26:42 DEBUG    misc       eventfilter:eventFilter:63 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f8fa0375120>: removed child <PyQt5.QtCore.QObject object at 0x7f8f8839c3a0>
14:26:42 DEBUG    webview    browsertab:_set_load_status:1008 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://www.google.com/search?q=tinkoff&source=hp&ei=_HZmYsWEkdwoOAefj-pwAk&iflsig=AHkEflsdiwFYma…'>: LoadStatus.success_https
14:26:42 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.success_https: 3>) (tab 0)
14:26:42 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(False) (tab 0)
14:26:42 DEBUG    modes      modeman:leave:424 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
14:26:42 DEBUG    modes      tabbedbrowser:_leave_modes_on_load:740 Ignoring leave_on_load request due to setting.
14:26:42 DEBUG    webview    browsertab:_set_load_status:1008 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://www.google.com/search?q=tinkoff&source=hp&ei=_HZmYsWEkdwoOAefj-pwAk&iflsig=AHkEflsdiwFYma…'>: LoadStatus.error
14:26:42 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.error: 4>) (tab 0)
14:26:42 DEBUG    misc       eventfilter:eventFilter:53 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f8fa0375120> got new child <PyQt5.QtWidgets.QWidget object at 0x7f8f8839c820>, installing filter
14:26:42 DEBUG    webview    browsertab:_on_navigation_request:1066 navigation request: url data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…, type Type.typed, is_main_frame True
14:26:42 ERROR    webview    tabbedbrowser:show_error_page:968 Renderer process crashed (status 133)
```

**[5379:17:0425/143725.473674:FATAL:fetch_manager.cc(380)]**

**Comment by The-Compiler** [comment]
@EmptyBucket Renderer process crashes are only a "symptom", but can be caused by various different issues. Please open a new issue if it's a different page, and include the information from the template.

**Comment by rarcri** [comment]
@The-Compiler  This is the output I get in terminal when running with --temp-basedir after 2 minutes on the https://teams.microsoft.com
 
[43942:43:0429/163207.212543:FATAL:fetch_manager.cc(380)]
16:32:29 ERROR: Renderer process crashed (status 133)

**Comment by The-Compiler** [comment]
@rarcri @EmptyBucket Both of your crashes seem to be the same as discussed in #7118. See https://github.com/qutebrowser/qutebrowser/issues/7118#issuecomment-1111951853 for the upstream bug and a possible workaround.
