### ISSUE TITLE
[Bug] Qutebrowser ignores "content.cookies.accept" setting in config.py

### ISSUE THREAD

**Issue by ZachIndigo** [qutebrowser/qutebrowser#7145]
**Version info**:

```
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.6.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.38.2
QtNetwork SSL: OpenSSL 1.1.1n  15 Mar 2022

Style: QStyleSheetStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.0.2
Platform: Linux-5.17.4-artix1-1-x86_64-with-glibc2.35, 64bit
Linux distribution: Artix Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/zach/.cache/qutebrowser
config: /home/zach/.config/qutebrowser
data: /home/zach/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/zach/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:11
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qutebrowser ignores qhenever I set the cookie preference in the config.py; it only works with autoconfig.yml

**How to reproduce**

Add line `config.set('content.cookies.accept', 'no-3rdparty', 'https://*')`

I changed the last part from the original, to http://*, https://*, and neither these, nor the original devtools://*, nor a generic *, would get loaded by qutebrowser; it always set the cookie policy to all. I can change it after the fact, which it will then set in autoconfig.yml, which is loaded the next time I open qutebrowser, but I wanted to just use config.py

**Comment by The-Compiler** [comment]
How do you test this? How did you reproduce this with `--temp-basedir`? How do you load `autoconfig.yml` in your `config.py`?

**Comment by ZachIndigo** [comment]
I tested this by typing ":set cookies", at which point the option shows up and says "all" instead of "no-3rdparty".

I use `--temp-basedir` frequently because I have multiple profiles; I did the same test for all of them, with the same results, until there was an `autoconfig.yml`.

I load the `autoconfig.yml` at the very beginning of the config files. For each profile, the config file is basically:

```
config.load_autoconfig()
c.window.title_format = '{perc}{current_title}{title_sep} qutebrowser (browser)'
config.source('/home/zach/.config/qutebrowser/config.py')
```

And the file `/home/zach/.config/qutebrowser/config.py` calls `config.load_autoconfig(True)` second, after adding the `jmatrix` plugin, and before every other config change I make.

**Comment by The-Compiler** [comment]
The completion for `:set` only shows the global value, not any site-specific overrides.

**Comment by ZachIndigo** [comment]
Ok, I guess I misunderstood what that setting did then. Sorry. How do I set it globally in config.py?

**Comment by mschilli87** [comment]
@ZachIndigo 
> How do I set it globally in config.py?

```python
config.set('content.cookies.accept', 'no-3rdparty')
```

?

**Comment by The-Compiler** [comment]
Yup - if you don't want to override the setting for a specific URL pattern only, then don't pass a URL pattern :wink:

Any idea where the misunderstanding came from, though?

**Comment by ZachIndigo** [comment]
I've been modifying the config file I generated sometime last year, I guess I just misunderstood what the original command did.

**Comment by The-Compiler** [comment]
I opened #7148 to track also showing the current page's value in the `:set` completion.
