### ISSUE TITLE
QtWebEngine 5.15.9: Renderer process crash on GMail

### ISSUE THREAD

**Issue by Dieterbe** [qutebrowser/qutebrowser#7147]
**Version info**:
```
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.6.1
colorama: no
jinja2: 3.0.3
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.13.216 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.38.2
QtNetwork SSL: OpenSSL 1.1.1n  15 Mar 2022
```
i have 2 gmail accounts, i've been using them both in gmail just fine.
but today, for some reason only https://mail.google.com/mail/data/u/0 worked whereas changing the user (by clicking the avatar) would give me this:
```
Unable to load page
Error while opening https://mail.google.com/mail/data/u/1/
Renderer process crashed (status 133)



Try again
```
when i refreshed the page, it kept showing a similar error, but it seemed to cycle between the URL's that it was erroring for, sometimes it was the gmail url, sometimes it was data://blahblah i think.

Even more strangely, i then tried to manually
`:open https://mail.google.com/mail/data/u/0` (which worked like before)
and also `:open https://mail.google.com/mail/data/u/1` which suddenly also started working.

so somehow, by manually copying the url in and opening it in a new tab, it works?

i don't know how to reproduce it, though.

**Comment by autophagy** [comment]
I've also been experiencing a similar issue with the renderer process crashing (status 133) on various Google pages on the same version qutebrowser version as @Dieterbe, such as Calendar and Google Cloud documentation pages. Not sure if that's just co-incidental.

**Comment by The-Compiler** [comment]
There's usually not much qutebrowser can do about renderer process crashes (coming from QtWebEngine), especially without a way to reproduce them. If someone can reproduce them, it would be good to know if there's any terminal output, and whether it happens with `--temp-basedir` too.

Judging from the QtWebEngine version, I suspect this is the same as [[QTBUG-102961] Regression 5.15.8 -> 5.15.9 Renderer crash in certain Service Worker setups - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-102961).

As a workaround, setting `qt.workarounds.remove_service_workers` might make things more stable.

**Comment by autophagy** [comment]
@The-Compiler For me at least, `qt.workarounds.remove_service_workers = True` has stopped the consistent renderer crashes. Thanks for the heads up :slightly_smiling_face:

**Comment by adigitoleo** [comment]
Just another data point. Also had this issue on the gmail sign in page and a few other places. Issue did not persist when using a temp basedir, and things were fine the first time after clearing cache, but the crash resumed later. Removing service workers has stopped the crash for me also. Will wait on the upstream fix.
