### ISSUE TITLE
Show current page's setting values in `:set` completion

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7148]
Context: https://github.com/qutebrowser/qutebrowser/issues/7145#issuecomment-1110386712

Via `CompletionInfo.cur_tab`, the settings completion should be able to get the value for the current page, and display that alongside the global value in the completion.

Not sure how well this will work with hardcoded column widths though, see #693.

**Comment by toofar** [comment]
Also mentioned in https://github.com/qutebrowser/qutebrowser/issues/6922 (or at least my comment, kinda?)

**Comment by The-Compiler** [comment]
Ah, correct, I forgot about that one. Let's close this as a duplicate then, thanks!
