### ISSUE TITLE
Impossible selecting path.ext files/dirs from within path dir

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#7150]
**Version info**:
https://paste.the-compiler.org/view/98876d35

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When the current folder is, say `xyz`, and the string <code>xyz<i>c</i></code> (with _`c`_ being any character, apparently) matches the beginning of sibling files/directories' names, those files/dirs are not selectable by writing `../xyz` and hitting <kbd>DownArrow</kbd>/<kbd>UpArrow</kbd>, because when one is selected, the <code>../xyz<i>c</i></code> prefix is stripped off.

**How to reproduce**
See the gif:
![qutebrowser-filechooser](https://user-images.githubusercontent.com/20521900/166093943-5ad9a741-3936-4fe0-b88b-72eb5f18a875.gif)

**Comment by The-Compiler** [comment]
The dialog is coming from Qt. I opened a bug there: [[QTBUG-103016] QFileDialog wrongly strips filename prefix when accessing parent dir - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-103016)
