### ISSUE TITLE
:help broken when installing from pip

### ISSUE THREAD

**Issue by jamesob** [qutebrowser/qutebrowser#7155]
**Version info**:

https://paste.the-compiler.org/view/cce6b708

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

The command `:help` shows a 404ish page that says "Your file was not found". The debug logs show the following:

```
12:10:48 DEBUG    network    webenginequtescheme:requestStarted:95 Got request for qute://help/index.html
12:10:48 DEBUG    misc       qutescheme:data_for_url:141 url: qute://help/index.html, path: /index.html, host help
12:10:48 ERROR    network    webenginequtescheme:requestStarted:112 SchemeOSError while handling qute://* URL: [Errno 2] No such file or directory: '/home/james/.local/venv/lib/python3.10/site-packages/qutebrowser/html/doc/index.html'
```

When I investigate the directory named, I see there is no `html/doc` directory:

```
% tree ~/.local/venv/lib/python3.10/site-packages/qutebrowser/html/
/home/james/.local/venv/lib/python3.10/site-packages/qutebrowser/html/
├── back.html
├── base.html
├── bindings.html
├── bookmarks.html
├── dirbrowser.html
├── error.html
├── history.html
├── license.html
├── log.html
├── no_pdfjs.html
├── pre.html
├── process.html
├── settings.html
├── styled.html
├── tabs.html
├── version.html
├── warning-sessions.html
└── warning-webkit.html
```

Maybe there is some error with `setup.py` that does not capture the `html/doc` folder when packaging? 

**How to reproduce**

Install from pip, run `:help`.

**Comment by jamesob** [comment]
I was able to fix this by cloning source locally, running `./scripts/asciidoc2html.py`, and then running `pip install -e .`.

**Comment by jamesob** [comment]
Ah, I may have `pip install .`'d from the local git repo without having run `./scripts/asciidoc2html.py`.

**Comment by jamesob** [comment]
I was going to say maybe the docs need an update, but I guess I just missed this: https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#building-the-docs

**Comment by The-Compiler** [comment]
Note I'd recommend using the described mkvenv.py installation.
