### ISSUE TITLE
Add zoom (+/-) keybindings to ":help"/quickstart page

### ISSUE THREAD

**Issue by mborus** [qutebrowser/qutebrowser#7156]
Hi, just a short feedback.

It would be very helpful, if the ":help" quickstart page could include the zoom command (+/-)
in the list of "Basic keybindings to get you started".

This is because the text on the page is rather small. It's quite hard to read the other key bindings (without
fetching glasses), so knowing the zoom command from the start would make the first contact with qutebrowser 
much nicer.

**Comment by The-Compiler** [comment]
Seems like a good idea! I'm usually hesitant about adding new information there (there's only so much we can include before people stop reading), but your explanation makes total sense.
