### ISSUE TITLE
Hitting g and f with little interleaving time causes both to be processed

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#7161]
[**Version info**:](https://paste.the-compiler.org/view/f8d22edc)

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
From normal mode, <kbd>g</kbd><kbd>f</kbd> is view source, and <kbd>f</kbd><kbd>g</kbd> is "show hints and press `g`". If you press them together or without much time between the two, both sequences will be prcessed, meaning that hints will show up, and also list of incomplete commands on the bottom left (does it have a name?) will show up.

This is obviously something that mostly happens when hitting the 2 keys by mistake.

**How to reproduce**
Press <kbd>g</kbd> and <kbd>f</kbd> as simultaneously as possible.

**Comment by The-Compiler** [comment]
Reproduced, but I'm afraid I'm closing this as a wontfix - entering hint mode is asynchronous (JS has to be run to discover whether there are any elements to hint), and until that finishes, you are still in normal mode. Hint mode could be entered immediately instead, but that doesn't seem worth the trouble (having to leave hint mode immediately again if there are no matches, configuring bindings after already entering hint mode, etc.).
