### ISSUE TITLE
Insert mode is still automatically turned on in devtools even if input.insert_mode.auto_enter is false

### ISSUE THREAD

**Issue by Rehpotsirhc-z** [qutebrowser/qutebrowser#7165]
**Version info**:

qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

**Does the bug happen if you start with `--temp-basedir`?**:
input.insert_mode.auto_enter is true by default so the bug does not happen

**Description**
When I set input.insert_mode.auto_enter to false, websites do not go into insert mode automatically which is the correct behavior. Devtools still goes into insert mode when I click on the console though. 

**How to reproduce**
`:set input.insert_mode.auto_enter false`
Do `wi` to open devtools and click on console. Insert mode will still automatically enable.

**Comment by The-Compiler** [comment]
I suppose it indeed makes sense to not do this when the setting is set to `false` - fixed!
