### ISSUE TITLE
error while spawning editor! execvp: No such file or directory

### ISSUE THREAD

**Issue by foxTr0t1178** [qutebrowser/qutebrowser#7182]
this error is dispayed when I try to run :config-edit, I've checked the directory, there's both a config.py file and an autoconfig.yaml file, I can't seem to use the :spawn command either

**Comment by The-Compiler** [comment]
What's your `:version`? Can you reproduce with `--temp-basedir`? (There's a reason for the issue template asking you about those things...)

What does "can't use `:spawn`" mean precisely? Does, say, `:spawn ls` fail in the same way? If not, what command does actually fail? Could you show `--debug` output?

**Comment by foxTr0t1178** [comment]
v1.10.1
The following error is displayed when ":config-edit" is run 
"ERROR: while spawning editor: execvp: no such file or directory"
I can reproduce the error in --temp-basedir

The :spawn command does not display a terminal unless I run ":spawn st"

**Comment by The-Compiler** [comment]
Well, I'm guessing you configured an `editor.command` which does not exist. Not much more I can say without more information...

**Comment by foxTr0t1178** [comment]
Can I paste the config file here? I can't find any resources to fix this

**Comment by The-Compiler** [comment]
Sure - ideally with a `--debug` log (as mentioned above) too...

**Comment by foxTr0t1178** [comment]
[text.txt](https://github.com/qutebrowser/qutebrowser/files/8690697/text.txt)

**Comment by The-Compiler** [comment]
You will need to set `editor.command` if you don't have `gvim` (the default) installed.

**Comment by foxTr0t1178** [comment]
so I have the line 
c.editor.command = ['usr/local/bin/vim' , '-e', '{}']

**Comment by The-Compiler** [comment]
There's a slash missing at the beginning of that path.

**Comment by foxTr0t1178** [comment]
alright, I fixed that, but same results

**Comment by The-Compiler** [comment]
What does `ls -l /usr/local/bin/vim` say then?

**Comment by foxTr0t1178** [comment]
Ah, it says it doesn't exist

**Comment by The-Compiler** [comment]
Well then... set `editor.command` to something that does exist :wink: (note you will need to include a terminal for terminal editors)

**Comment by foxTr0t1178** [comment]
I rewrote it as `c.editor.command = ['st', 'usr/bin/vim', '-e', '{}'] and that seemed to work, thank you

**Comment by foxTr0t1178** [comment]
before I go, is the `spawn:` command supposed to summon a terminal to execute the command? In your example `spawn:ls` it didn't seem to bring up and error this time, but it didn't seem to do anything.

**Comment by The-Compiler** [comment]
No, it won't open a terminal. My example was just with a command which should always exist, since you said "can't use spawn" without much detail.
