### ISSUE TITLE
Cannot watch videos on Invidious, Youtube functions normally

### ISSUE THREAD

**Issue by foxTr0t1178** [qutebrowser/qutebrowser#7185]
**Version info**:
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.8.10
PyQt: 5.15.6

sip: 6.5.1
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform: Linux-5.13.0-37-generic-x86_64-with-glibc2.29, 64bit
Linux distribution: Ubuntu 20.04.4 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /home/thomas/.local/lib/python3.8/site-packages/PyQt5/Qt5/libexec, data path: /home/thomas/.local/lib/python3.8/site-packages/PyQt5/Qt5

Paths:
cache: /home/thomas/.cache/qutebrowser
config: /home/thomas/.config/qutebrowser
data: /home/thomas/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/thomas/.config/qutebrowser/config.py has been loaded
Uptime: 0:04:46

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
Cannot play videos from Invidious, displays "No compatible source was found for this media."
**How to reproduce**
 https://vid.puffyan.us/watch?v=G-mLyrHonvU

**Comment by toofar** [comment]
The QtWebEngine binary from pypi isn't built with proprietary codecs. You can use the qutebrowser that ships with your distro if you can stand the oldness. Otherwise try the flatpak for qutebrowser (I [think](https://github.com/flathub/io.qt.qtwebengine.BaseApp/blob/branch/5.15-21.08/io.qt.qtwebengine.BaseApp.json#L29) that has them). Or upgrade your ubuntu version!.
