### ISSUE TITLE
Show Chromium security patch version in :version

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7187]
With QtWebEngine 6.3 (and PyQtWebEngine 6.3.1 I think), we have a [`qWebEngineChromiumSecurityPatchVersion()`](https://doc-snapshots.qt.io/qt6-6.3/qtwebenginecoreglobal-h.html#qWebEngineChromiumSecurityPatchVersion). For older versions, we can always infer it from the QtWebEngine patch version and store known mappings.

We should show that as part of `:version`, i.e. extend "Backend: QtWebEngine 6.3, based on Chromium 94.0.4606.126" accordingly.

**Comment by tinywrkb** [comment]
[Seems to be hardcoded](https://invent.kde.org/qt/qt/qtwebengine/-/blob/e2c04460bfc5dcc70886770e0c53faab89b4b43e/src/core/web_engine_context.cpp#L921), so it will be wrong for the Flatpak app, as we build the latest commit in the relevant qtwebengine-chromium branch. Qt's devs are just too slow in tagging new qtwebengine releases, so there might already be a couple of backported security fixes in the qtwebengine-chromium branch, but without an updated qtwebengine release.
