### ISSUE TITLE
Datadome blocks Qutebrowser... again...

### ISSUE THREAD

**Issue by vincowl** [qutebrowser/qutebrowser#7190]
Seems to be back : cannot access the following site : [https://www.darty.com](https://www.darty.com)
Related to #5226 

Here is my config :
```
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.4 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.6.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: no
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.13.216 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022
```

**Comment by vincowl** [comment]
This [tip](https://github.com/qutebrowser/qutebrowser/issues/5226#issuecomment-585915592_) solved the problem. I added the following line to my `config.py`
```python
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://*.datadome.co/*')
```

**Comment by The-Compiler** [comment]
Works fine for me, with the same versions and no workaround.

Can you reproduce this with `--temp-basedir`? (There's a reason the issue template asks you about it, so I don't have to :wink:)

**Comment by The-Compiler** [comment]
@vincowl any update on this?

**Comment by The-Compiler** [comment]
They replied, telling me that:

> I analyzed your traffic and tried to adjust some signals/rules that led to the blocking decision. Things should be better now.

and at least clicking around on darty.com seems to work fine now. Accessing the link directly still leads to a block, however...
