### ISSUE TITLE
Web icons/emojis not rendering

### ISSUE THREAD

**Issue by jamesob** [qutebrowser/qutebrowser#7191]
**Version info**:

https://paste.the-compiler.org/view/d22e444a

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Icons or emojis aren't rendering as expected in qutebrowser. This may not be a bug, but I'm wondering what controls this or how I might be able to fix it.

Note the "**FILES**" row icons in the screenshots below:

In firefox:
![image](https://user-images.githubusercontent.com/73197/169042811-791e94be-8ec7-494f-a387-54bb908fa969.png)

In qutebrowser:
![image](https://user-images.githubusercontent.com/73197/169042868-c0184707-23e3-408d-b399-a65b5930bba0.png)

**Comment by The-Compiler** [comment]
Do you have an emoji font such as noto-emoji installed? Note that some of those don't show up in your Firefox screenshot either.

Also, could you please try reproducing this with another browser using Qt 5 and QtWebEngine such as KDE Falkon, and perhaps Chromium too?

**Comment by The-Compiler** [comment]
@jamesob any update on this?

**Comment by jamesob** [comment]
@The-Compiler confirmed this was also the case with Chromium - thanks for the suggestion. Still not sure how to fix, but that isn't the concern of this issue queue.
