### ISSUE TITLE
Cannot Connect WhatsApp for Web

### ISSUE THREAD

**Issue by rbugajewski** [qutebrowser/qutebrowser#7199]
**Version info**:
```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.3, based on Chromium 87.0.4280.144
Qt: 5.15.3

CPython: 3.9.12
PyQt: 5.15.2

sip: 4.19.25
colorama: no
jinja2: 3.0.3
pygments: no
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.2
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022
```
**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

You cannot connect WhatsApp for Web with an Android device by pointing the smartphone camera at the generated QR code inside qutebrowser.

**How to reproduce**

1. Go to https://web.whatsapp.com/ and open the corresponding view on the Android application that allows you to link a device.
2. Point the smartphone at the QR code.

**Alternative**
1. In addition to the above steps wait until the web page generates a new QR code without reloading the page.

**Expected Result**

Linking succeeds.

**Actual Results**
Nothing happens.

This is actually a very weird bug, and everything I tried did not solve the issue, but I’m also not aware how WhatsApp generates its QR codes.

**Comment by The-Compiler** [comment]
Can you try with another browser using Qt 5 and QtWebEngine, such as KDE Falkon? Could you also try out the `qt6-v2` branch? See https://github.com/qutebrowser/qutebrowser/issues/5395#issuecomment-1120213898 for some instructions.

**Comment by nperry** [comment]
I have been using whatsapp for web on ``master`` & ``qt6-v2`` branch for some time and I've never faced such issues. 

I have just reattempted linking on the below versions and linking was successful. 

```
qutebrowser v2.5.0
Git commit: d759fb898 on qt6-v2 (2022-05-19 18:14:22 +0200)
Backend: QtWebEngine 6.3, based on Chromium 94.0.4606.126
Qt: 6.3.0

CPython: 3.10.4
PyQt: 6.3.0

sip: no
colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: 2.14.305 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022
```

```
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.4 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.6.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.14.305 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022
```

**Comment by rbugajewski** [comment]
Thanks for the helpful feedback, I already tried to upgrade yesterday in the evening (but still with Qt 5), and had the same issues. No wonder, same backend, same issue. So in the next step I’ll try the newer branch.

For full disclosure, this was the version that also didn’t work:

```
qutebrowser v2.5.0
Git commit: 14bcdc86a-dirty on master (2022-05-23 09:38:21 +0200)
Backend: QtWebEngine 5.15.3, based on Chromium 87.0.4280.144
Qt: 5.15.3

CPython: 3.9.12
PyQt: 5.15.2

sip: 4.19.25
colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.2
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022
```

**Comment by rbugajewski** [comment]
I can confirm that the WhatsApp linking works with the following version:

```
qutebrowser v2.5.0
Git commit: d759fb898-dirty on qt6-v2 (2022-05-19 18:14:22 +0200)
Backend: QtWebEngine 6.3, based on Chromium 94.0.4606.126
Qt: 6.3.0

CPython: 3.9.12
PyQt: 6.3.0

sip: no
colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.2
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022
```

After I made sure that everything works with `--temp-basedir`, I migrated the Qt5 data to the newer version, and then linking broke again. I turned off dark mode which didn’t help, then I turned off the ad blocker, and then the linking was successful. I could turn on the global dark mode and ad blocker again after a successful linking, and the web version still works. _Note:_ `--temp-basedir` didn’t work with the Qt5 version from my initial post.

**Comment by Bonoolu** [comment]
dunno if this is relevant, but i will just write it here in case it becomes relevant at later time:
whatsapp web recently made some changes
webassembly is now required for whatsapp web to work

**Comment by mibli** [comment]
I have noticed this to fail with dark version of whatsapp web. When turned back to light version it worked properly. And I've tried clearing cache and everything before that... with no success.
