### ISSUE TITLE
Some CSS rules are not applied on mullvad servers page.

### ISSUE THREAD

**Issue by crocket** [qutebrowser/qutebrowser#7201]
**Version info**:
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.3, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

https://mullvad.net/servers

qutebrowser

![2022-05-26 04:42:15](https://user-images.githubusercontent.com/748856/170417629-18477161-17c6-458c-9cc5-cb3c6f34e786.png)

Librewolf and firefox and brave and google chrome

![2022-05-26 04:42:31](https://user-images.githubusercontent.com/748856/170417699-d41b5aa5-db1f-4f2b-a819-fe1b6cb40da6.png)

**Comment by toofar** [comment]
The links are the proper color on Qt6. So probably it'll be fixed in qutebrowser 3.0

**Comment by The-Compiler** [comment]
Yup. Looks like something in their (weirdly complex) CSS isn't applying properly with Chromium 87. Looks the same in KDE Falkon, and I don't think there's anything we can do about it.
