### ISSUE TITLE
[qt6] Misaligned tab title  

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#7205]
**Version info**:
qutebrowser v2.5.0
Git commit: 64e8c7132 on makepkg (2022-05-26 14:37:27 +0200)
Backend: QtWebEngine 6.3, based on Chromium 94.0.4606.126
Qt: 6.3.0

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Setting `tabs.title.alignment` to `center` causes titles that don't fit the available width to be slightly offset to the left. This only happens when they're the focused tab. Non-focused tabs always display fine, as do tabs that don't get ellipsis because they fit in the tab box. 

I hope the attached screenshot suffices to illustrate the issue. Note how the text of the third tab and the favicon overlap. The issue also occurs with `tabs.title.format` settings different from the ones I used here.

![2022-05-27-1653669978](https://user-images.githubusercontent.com/10417027/170743227-8c0c53a5-c33d-4c65-acc2-a3725cc75b20.jpg)

**How to reproduce**

Setting `tabs.title.alignment` to `center` should do it.

**Comment by The-Compiler** [comment]
Reproduced. No idea why it would happen off-hand.

**Comment by toofar** [comment]
@rien333 if you are in a position to test the latest qt6-v2 branch, it looks like the fix for #7313 resolves this to :pray:.

**Comment by rien333** [comment]
Lovely, will update!

**Comment by rien333** [comment]
Indeed, this is fixed! Thanks for all your work as of late!
