### ISSUE TITLE
The `colors.hints` config setting lacks a `border` field

### ISSUE THREAD

**Issue by JanMaslo2** [qutebrowser/qutebrowser#7207]
Unlike other elements hints cannot have their border colors changed as there doesn't appear to be such config setting, leaving bright yellow ones regardless of the selected `colors.hints.bg`.

**Comment by rien333** [comment]
Fortunately, this is not true. The setting is named `hints.border`, and you can set it to e.g. `1px solid #CDDDFA`  for 1 pixel wide grayish border.

Next time you can't find a setting, press <kbd>ss</kbd> and then just type a keyword like "border". This should get you there.
