### ISSUE TITLE
Group commands dealing with commands/commandline

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7214]
I kinda want to rename `set-cmd-text`, `repeat`, `repeat-command` (needs new name?), `later`, `edit-command` (maybe) and `run-with-count` to have a consistent naming scheme, also see #7213.

- `cmd-set-text`
- `cmd-repeat`
- `cmd-repeat-last` (?)
- `cmd-later`
- `cmd-edit`
- `cmd-run-with-count`
- `cmd-if-count`
- ...

Technically this mixes commands for the command line (`set-text`, `edit`) and commands which take another commannd (`later`, `repeat`, `run-with-count`, etc.), but I feel like they are close enough to each other to group them from an user perspective.

**Comment by pylbrecht** [comment]
I will start digging into this.

@The-Compiler, if you have any additional directions, let me know!

**Comment by pylbrecht** [comment]
Just leaving this here for reference: 8976e6850317881ed1aebed55a273e73c17a50bd.
