### ISSUE TITLE
Hold MMB to scroll anywhere and mouse scrolling speed improvement

### ISSUE THREAD

**Issue by anverb** [qutebrowser/qutebrowser#7215]
There was an extension for Firefox, called "ScrollAnywhere" (https://addons.mozilla.org/en-US/firefox/addon/scroll_anywhere/) which allows you to drag the page by holding and moving MMB, which is really helpful. 
Is there any chance to see this in Qutebrowser?

Also, how can I increase the regular mouse scrolling speed, which is really slow here?
Thanks.

**Comment by The-Compiler** [comment]
That sounds like something suitable for a future extension, but too exotic to have added to the core. I added it as an idea to #30.

As for mouse scrolling speed, that's handled by the underlying Qt. I don't believe there is a way for qutebrowser to override it, you might want to check your system settings.

**Comment by The-Compiler** [comment]
I just happened to find this while looking for something else: [Chromium slow scroll speed - ArchWiki](https://wiki.archlinux.org/title/chromium#Chromium_slow_scroll_speed). The solutions mentioned there might help as well in your case.
