### ISSUE TITLE
Feedly is suddenly broken (not displaying RSS feeds)

### ISSUE THREAD

**Issue by JonathanReeve** [qutebrowser/qutebrowser#7218]
**Version info**:

qutebrowser v2.5.0
Git commit:
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.3

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
RSS feeds on Feedly (feedly.com) have stopped displaying. This problem only seems to occur on Qutebrowser.    

**How to reproduce**

- Go to feedly.com, and load [an RSS feed like this one](https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Fnews.ycombinator.com%2Frss)
- Notice that the feed doesn't display—it's just blank. 

I've attached a screenshot of the issue, along with the web inspector panel open, just in case any of those errors are relevant. 

![screenshot](https://user-images.githubusercontent.com/1843676/171042353-19bc0738-dab9-4fc7-a26e-7b882f6030b9.png)

**Comment by The-Compiler** [comment]
It works fine on the `qt6-v2` branch (see #7202) with a newer QtWebEngine. I've tried to debug this a few days ago, but unfortunately got nowhere, so I'm afraid there isn't much we can do until that's in.
