### ISSUE TITLE
Fatal error: PyQt5.QtCore is required to fun qutebrowser but could not be imported on Fedora 35 

### ISSUE THREAD

**Issue by jason123santa** [qutebrowser/qutebrowser#7225]
**Version info**:
latest on Fedora 35 I can't view the version because I can't launch qutebrowser
**Does the bug happen if you start with `--temp-basedir`?**:
yes it does 

**Description**
I installed qutebrowser on fedora 35 and its giving me this error: 
Fatal error: PyQt5.QtCore is required to fun qutebrowser but could not be imported 

I have pyqt5 installed and even removed the version from pip and only have the system package installed 

**How to reproduce**
install the qutebrowser on fedora and launch it

**Comment by The-Compiler** [comment]
This is most likely an issue with your setup and not qutebrowser. Can you show the full error message?

**Comment by jason123santa** [comment]
![error](http://0x0.st/oMzD.png)

**Comment by The-Compiler** [comment]
How did you install qutebrowser? How are you launching it? Is the python3-qt5 package installed?

**Comment by jason123santa** [comment]
I installed qutebrowser from the fedora package manager dnf. I am launching it from the .desktop file and python3-qt5 is installed

**Comment by The-Compiler** [comment]
What do `which qutebrowser`, `head $(which qutebrowser)` and `python3 -c "from PyQt5 import QtCore"` say?

**Comment by jason123santa** [comment]
`/usr/bin/qutebrowser`

```
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'qutebrowser==2.4.0','gui_scripts','qutebrowser'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'qutebrowser==2.4.0'

try:
    from importlib.metadata import distribution
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'QtCore' from 'PyQt5' (unknown location)
```

**Comment by The-Compiler** [comment]
Do you have a `/lib64/python3.10/site-packages/PyQt5/QtCore.abi3.so`?

**Comment by jason123santa** [comment]
I don't seem to have that file

**Comment by The-Compiler** [comment]
Well, then you don't seem to have the `python3-qt5-base` package properly installed, because that file [is part of it](https://packages.fedoraproject.org/pkgs/python-qt5/python3-qt5-base/fedora-35.html#files).

I'm guessing you deleted part of it when you

> and even removed the version from pip

I'd strongly recommend to never run pip as root, and use virtualenvs instead.

**Comment by jason123santa** [comment]
I think the issue was that I removed the package with pip. I just reinstalled python3-qt5-base and it works now. Was trying to reinstall the packages but could not figure out what one to reinstall. Thanks for the help
