### ISSUE TITLE
Changing web font size doen't do anything

### ISSUE THREAD

**Issue by robcsi** [qutebrowser/qutebrowser#7233]
**Version info**:
qutebrowser v2.5.1
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.4 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.6.1
colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022

**Does the bug happen if you start with `--temp-basedir`?**:
No, it works correctly, except the sites mentioned below.

**Description**
When changing ":set fonts.web.size.default" to some smaller or larger value, fonts on the web don't change. Sites where font size doesn't change: Github, Youtube, Twitter.
**How to reproduce**

**Comment by rien333** [comment]
I think this is to be expected? Websites can use their own font-related settings, so the value of `fonts.web.size.default` tends to be overriden, except on websites that are more or less "plain text", or use your systems default font (most wiki's are an example of this).

Even looking around at github, I see a lot of different font sizes (perhaps even different fonts?), so I can see how the design of the website would break if you would set an universal font size.

**Comment by robcsi** [comment]
Great then, I'm closing the issue...

**Comment by The-Compiler** [comment]
That's indeed how that setting works, I believe - FWIW, all qutebrowser does is passing that value on [to QtWebEngine](https://doc.qt.io/qt-6/qwebenginesettings.html#setFontSize), which in turn then simply passes it on to Chromium.
