### ISSUE TITLE
Messages get rendered as Qt rich text

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7246]
![image](https://user-images.githubusercontent.com/625793/173598408-e1ade057-4af4-4f56-b4f0-2c0bd320c350.png)

![image](https://user-images.githubusercontent.com/625793/173598424-0e640422-58ca-4641-9857-8226d6ed1fa8.png)

![image](https://user-images.githubusercontent.com/625793/173598439-aebb713d-c622-4cc1-a3d8-1d867b906e39.png)

...whoopsie! Thanks to @emanuele6 for the report (via IRC), I'm surprised nobody noticed so far.

Not security relevant from what I can see, as this is just [Qt Rich text](https://doc.qt.io/qt-5/richtext-html-subset.html).

I'm working on a fix. First intended to just drop it entirely, but there is actually one place where we rely on it (`content.notifications.presenter = messages`), so I'm now working on making it optional (though off by default).

Not planning to backport the fix to v2.5.x (this is also a behavior change), though I suppose we could introduce a simpler fix there, which just escapes the search texts at least.

**Comment by emanuele6** [comment]
\o/
