### ISSUE TITLE
Set up Liberapay for donations

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7264]
For people outside of Europe, IBAN bank transfers usually aren't an option to donate. While GitHub Sponsors allows for one-time payments via credit card, there are people who cannot or don't want to use their billing information on GitHub.

[Liberapay](https://liberapay.com/) seems great from what I've seen so far, so I should probably set up an account there.

**Comment by The-Compiler** [comment]
I set this up somewhat secretly while waiting for the first payout to happen, to confirm that it is working as expected.

I can confirm everything seems to work fine, so here's a link: https://liberapay.com/The-Compiler/ - note that with the other donation methods (GitHub Sponsors, SEPA transactions) I will get a bigger cut, however, as Liberapay incurs payment fees via Paypal/Stripe.

Probably time to write a proper announcement for this soon, and add it to the README!

**Comment by mschilli87** [comment]
@The-Compiler:
> ...and add it to the README

You might also want to adjust the [SponsorsFAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc#sponsors) since they do not even mention the SEPA option.
Personally I would be very happy to not send my donations via Microsoft and I will switch for sure. Can you calculate how much more I'd have to send via Liberapay/SEPA for you to get the same cut as you get via GitHub Sponsors now?

**Comment by The-Compiler** [comment]
GitHub sponsors pays out in CHF with a very reasonable conversion rate, and takes zero fees. So when paying via that, you probably end up costing Microsoft a tiny bit of money :laughing: It's mostly my preferred option for two reasons:

- When I get money in USD/EUR, I prefer to keep them in their currency and use them for expenses I pay in EUR/USD. However, I  obviously pay most of my expenses in CHF.
- It's a non-trivial overhead for bookkeeping purposes, since those are all individual monthly transactions, rather than one lump sum via GitHub.

But if you prefer a SEPA transfer, that's certainly an option, see [the README](https://github.com/qutebrowser/qutebrowser#donating) for details. If you pay it via your bank directly, neither of us pays any fees, with the main difference that I get it to my EUR instead of my CHF account.

Apparently, Liberapay handles SEPA via Stripe, which [seems to take](https://stripe.com/en-ch/pricing/local-payment-methods) 0.5% for SEPA transfers, and 0.40 CHF per SEPA Direct Debit transaction. It's very reasonable compared to around 2.4% for Credit Cards and 5%+ for PayPal, but still, no reason to involve an extra service there really.

**Comment by benjaminbhollon** [comment]
Considering setting up a donation myself once I shut down an extra VPS I'd been paying for—as someone outside Europe I do prefer Liberapay to GitHub Sponsors, but I'll reconsider given your reasons for preferring Sponsors.

Thanks for making Liberapay an option, though! That's a big deal for some people.

**Comment by The-Compiler** [comment]
Given that GitHub Sponsors recently announced they're [stopping to take payments via PayPal](https://github.blog/changelog/2023-01-23-github-sponsors-will-stop-supporting-paypal/), and that affecting around 30-40% of the donations made, it's long overdue to get the word out about Liberapay!

I just added it to the README and wrote an announcement for it: [GitHub Sponsors dropping PayPal, alternative ways to donate, and the current state of things : qutebrowser](https://www.reddit.com/r/qutebrowser/comments/10kvwub/github_sponsors_dropping_paypal_alternative_ways/).

Thanks for all the support! :heart:
