### ISSUE TITLE
Darkmode does not work on Artix Linux

### ISSUE THREAD

**Issue by Commodoriann** [qutebrowser/qutebrowser#7265]
**Version info**:
qutebrowser v2.5.1
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.4 (compiled 5.15.2)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Setting color.webpage.darkmode.enabled to "True" does not appear to do anything. 

**How to reproduce**
1. Install Artix Linux
2. Install Qutebrowser
3. Change "colors.webpage.darkmode.enabled" to "True"
4. See that even after a restart it does not work.

Oddly enough darkmode does seem to work on another box I have with Artix installed, so it could be another issue. Just for reference, here is the rest of pertinant information from my version:
CPython: 3.10.5
PyQt: 5.15.6

sip: 6.6.1
colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.14.305 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022

Style: QGtkStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.1.1
Platform: Linux-5.18.2-artix1-1-x86_64-with-glibc2.35, 64bit
Linux distribution: Artix Linux (arch)
Frozen: False

I have also tried with other versions of Qutebrowser available from the AUR, still doesn't work. Here is what the rest of my "colors.webpage.darkmode*" settings look like:
"colors.webpage.darkmode.algorithm" = "brightness-rgb"
"colors.webpage.darkmode.contrast"   = "0.0"
"colors.webpage.darkmode.enabled"   = "True"
"colors.webpage.darkmode.greyscale.all" = "False"
"colors.webpage.darkmode.greyscale.images" = "0.0"
"colors.webpage.darkmode.policy.images" = "smart"
"colors.webpage.darkmode.policy.page" = "smart"
"colors.webpage.darkmode.threshold.background" = "0"
"colors.webpage.darkmode.threshold.text" = "256"

Let me know what other things I might need to include.

**Comment by The-Compiler** [comment]
Could you please run with `--temp-basedir -s colors.webpage.darkmode.enabled true`  and:

1) verify that it indeed does not work there either
2) run `:report` so I can take a look at the debug log?

**Comment by Commodoriann** [comment]
Should have that report now. Did not work with those flags.

**Comment by The-Compiler** [comment]
```
09:18:26 WARNING  init       qtargs:_warn_qtwe_flags_envvar:384 You have QTWEBENGINE_CHROMIUM_FLAGS='-blink-settings=darkModeEnabled=true -enable-features=OverlayScrollbar,OverlayScrollbarFlashAfterAnyScrollUpdate,OverlayScrollbarFlashWhenMouseEnter' set in your environment. This is currently unsupported and interferes with qutebrowser's own flag handling (including workarounds for certain crashes). Consider using the qt.args qutebrowser setting instead.
```

Does it work if you `unset QTWEBENGINE_CHROMIUM_FLAGS`?

**Comment by Commodoriann** [comment]
Unfortunately no. I also discovered some other QT flags in my env that I also unset and that did not fix the issue. They are as follows:
QT_QPA_PLATFORMTHEME
QT_STYLE_OVERRIDE

**Comment by The-Compiler** [comment]
That's weird. Mind sending another report without those set?

**Comment by Commodoriann** [comment]
Now seems to work with the --temp-basedir flag set
