### ISSUE TITLE
Renderer process crashed (status 159)

### ISSUE THREAD

**Issue by iCodeCoolStuff** [qutebrowser/qutebrowser#7270]
**Version info**:
`         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.5.1
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.10.5
PyQt: 5.15.6

sip: 6.6.2
colorama: no
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022

Style: QFusionStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.1.1
Platform: Linux-5.17.3-arch1-1-x86_64-with-glibc2.35, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /home/user/.local/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /home/user/.local/lib/python3.10/site-packages/PyQt5/Qt5/libexec, data path: /home/user/.local/lib/python3.10/site-packages/PyQt5/Qt5

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
When starting, duckduckgo.com does not load.
`14:09:45 ERROR: Renderer process crashed (status 159)
14:09:45 ERROR: Renderer process crashed (status 159)
14:09:46 ERROR: Renderer process crashed (status 159)
14:09:46 ERROR: Renderer process crashed (status 159)`
**How to reproduce**
Run qutebrowser in the terminal

**Comment by The-Compiler** [comment]
You are using an older QtWebEngine installed from PyQt binary packages. Those aren't compatible with newer glibc versions. Given that you are on Archlinux, you might want to uninstall the manually installed copies in `~/.local/share` and use the Qt provided by Arch instead.

**Comment by emanuele6** [comment]
~~`~/.local/share`~~`~/.local/lib`
