### ISSUE TITLE
"Search result vanished" with search-next and no result

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7275]
When doing `/thisdoesnotexist` and then pressing `n`, "Search result vanished..." gets displayed. We probably shouldn't allow using `search-next` with no search result at all?

Regression introduced in e15bda307e42c288b926f578e7bf8c610e4767af.

**Comment by Hi-Angel** [comment]
FTR: from experiencing that message for 1.5 months of using the QT6 branch I've impression the problem is purely cosmetic. I.e. it doesn't seem to have any other effect than displaying that odd message.

**Comment by The-Compiler** [comment]
That's accurate - but it's still confusing and a regression, and should be easy to fix.

**Comment by The-Compiler** [comment]
Moving this back to v3.0.0 - should be an easy fix, so I'd rather get it done instead of confusing people with a regression.

**Comment by pylbrecht** [comment]
I will give this a try on the weekend.
