### ISSUE TITLE
Google Translate Discrepancy with QtWebEngine

### ISSUE THREAD

**Issue by eclipsed-ninja** [qutebrowser/qutebrowser#7284]
### Translation in Firefox
![firefox](https://user-images.githubusercontent.com/9157531/175486438-72924faf-4e71-4520-a86f-4524df2b1567.png)
### Translation in Qutebrowser
![qutebrowser](https://user-images.githubusercontent.com/9157531/175486443-f2815afe-aa73-4f96-80be-ac5de495c81b.png)
**Version info**:

qutebrowser v2.5.2
Git commit: 52d98ad9a on master (2022-06-22 16:02:57 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
-

**Description**
Google translation seems to be providing different translation for QtWebEngine, I've attached two images highlighting the difference.

I'm working on a project of my own and the discussions on https://github.com/qutebrowser/qutebrowser/issues/5182 were very helpful in fixing the google login issue. So far I have tried 
* Changing User Agents (Firefox latest, firefox v90, No Agents, IE, Edge, Chrome)
* Added Accept-Language Header (en-US,en;q=0.5)
* Logging into the google account (doesn't seem to change anything), played around with empty profiles, lived-in profiles (did a lot of searches etc, so the browser history / cache / cookie collection is good)

But the translation difference remains the same, I thought it would be good idea to ask the dev community here as you've pretty much paved the way for any Qt - browser project.

Also please let me know if there is any License restriction if I use the information / code shared here on my own project along with doing a similar PR for Qutebrowser.

**How to reproduce**

Translate the following text and you should be able to see the difference
```
그러나 SPC 측정 체계와 DBL 측정 체계는 모두 기업이 만들이낸 ‘과거’ 사회적 가치를 ‘사후 측정’하는 만큼 기업이 ‘미래’에 만들이낼 수 있는 사회적 가치를 ‘사전 추정’하는 것은 어려웠습니다
```

**Comment by rien333** [comment]
What are the two browsers in your screenshots?

**Comment by eclipsed-ninja** [comment]
@rien333 Ah sorry I missed it, I've just edited the issue.

**Comment by eclipsed-ninja** [comment]
I checked and titles on the images are correct, this is weird. My app (Qt6-QML) and qutebrowser show the same translation which is different from what's shown on firefox or chrome.

I just tried your language header and user agent strings but didn't work for me. Clueless as to what might be the issue here.

**Comment by toofar** [comment]
I see the same difference, how bizarre:
Chromium 101.0.4951.64: "However, as both the SPC measurement system ..."
Qutebrowser Backend: QtWebEngine 6.3, based on Chromium 94.0.4606.126: "However, it was difficult for companies ..."

**Comment by rien333** [comment]
Okay, actually I can reproduce both translations in qutebrowser (QtWebEngine 6.3, based on Chromium 94.0.4606.12). Maybe google is just being weird?

This is the search results main page (i.e. google.com):
![2022-06-25-1656141371](https://user-images.githubusercontent.com/10417027/175763058-e52c0b53-50a9-4338-9516-09cea4908a43.jpg)

This is [translate.google.nl](translate.google.nl):
![2022-06-25-1656141524](https://user-images.githubusercontent.com/10417027/175763099-6057b83a-3f28-4051-ae84-694095bc2eef.jpg)

**Comment by leo848** [comment]
Google's code is proprietary, so why is this an issue with qutebrowser?    
I don't see that they guarantee the same translations based on one input anywhere so it could be based on anything (including the user agent, random cookies, the availability of browser APIs, your window size, the time, how many people visit their sites etc.), just any arbitrary data. 

If the issue is that the translation in qutebrowser is _worse_ for your specific purpose, you should probably use another translation engine. There are several available, I would personally recommend [DeepL](https://deepl.com). It's unfortunately not FOSS either, but at least it doesn't give me different results in different browsers / on different devices.

**Comment by RudraveerMandal** [comment]
Yes its never fixed. Google translate is notorious for being shit when used to translate from/to non-european languages. I dont even get the same translation a second later

**Comment by The-Compiler** [comment]
While this is indeed very curious (and I can reproduce), this is indeed not something qutebrowser can or should "fix". We have no idea what makes Google Translate behave that way, and it seems futile to try and find out.
