### ISSUE TITLE
Setting for completion item padding

### ISSUE THREAD

**Issue by evan-leigh** [qutebrowser/qutebrowser#7291]
I'd be nice to have the option for padding between completion items, personally I think it can get crowded and hard to read when there are too many options.

![2022-07-02-screenshot_001](https://user-images.githubusercontent.com/51345945/176998287-de8f704e-7ea2-4d2c-86ce-a6b70fa55782.png)

something like `c.completion_items.padding`

**Comment by The-Compiler** [comment]
Seems like a reasonable addition, and indeed doesn't exist yet. It would probably be a great first-time contribution for someone! Note that there is already a `completion.*` category in the settings, so this should probably be named `completion.item_padding` or so rather.

This should be possible by changing the stylesheet in `qutebrowser/completion/completionwidget.py` by adding `QTreeView:item { padding: ... }` based on a new config option, which needs to be declared in `qutebrowser/config/configdata.yml` - see existing `Padding` settings there for some inspiration, and e.g. the `HintLabel` style sheet in `qutebrowser/mainwindow/mainwindow.py` for some inspiration around implementing it.

Here's a quick test by hardcoding it to 10px:

![image](https://user-images.githubusercontent.com/625793/176998704-b0cc372c-cbe5-4e30-82a7-ba4459bf0135.png)

**Comment by evan-leigh** [comment]
#7292  thanks for the pointers 😃
