### ISSUE TITLE
Render local PDFs

### ISSUE THREAD

**Issue by zstg** [qutebrowser/qutebrowser#7295]
Is there a way to render local PDF files using `pdf.js` , like how Firefox does it ?

The pdf preview (using pdf.js ) is quite good

**Comment by mhmdanas** [comment]
You can just pass the path of the PDF file to `:open`, as in e.g. `open ~/Downloads/foo.pdf`. Maybe you can also make PDF files open in Qutebrowser by default, but that'll probably depend on your OS.

**Comment by zstg** [comment]
Thanks a lot @mhmdanas !
I was wondering why the `file:///` protocol didn't work - Qutebrowser doesn't need it after all !

**Comment by mhmdanas** [comment]
@zstg Qutebrowser does support `file://`, what path were you trying to pass to `:open`?

Also, to clarfy, the protocol is `file://`, not `file:///`. The third slash is a part of the path itself, not the protocol.

**Comment by mhmdanas** [comment]
You just copy the full path of the file, and then run `:open file://PATH`, where you replace `PATH` with the full path of the file.

Also, I would advise you to keep this issue closed, as this is not a Qutebrowser bug, and we can communicate just fine with the issue closed.
