### ISSUE TITLE
Use dependabot to keep github actions up to date

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#7299]
Apparently you can have dependabot bump github action references on a schedule (eg actions/checkout@v2 -> actions/checkout@v3). I don't know if it also picks up things like the node-version from setup-node like was included in https://github.com/qutebrowser/qutebrowser/commit/47ef35fb311cdf20#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR49 but it might be useful?

docs: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by The-Compiler** [comment]
We've done that before, but it was buggy in weird ways - see the commit message of fa5e04fdaf8af9230c4cd9c386c5d8e0307655ca which reverted it.

Then again, it's almost been two years, so I suppose we could give it another try. It should at least:

- *Not* run on forks (that was the number 1 complaint causing me to pull the plug, as it annoyed contributors and packagers and such)
- Either have a way to only pin the major version, or if minor and patch are pinned as well, update *all* actions reliably
- Ideally come with a way to batch the update into a weekly PR or something (especially if it updates for every patch version). This is probably my main gripe with Dependabot - I've been watching https://github.com/dependabot/dependabot-core/issues/1190 / https://github.com/github/roadmap/issues/148 for a long time, but so far, not much has happened.

**Comment by The-Compiler** [comment]
Another possibility would probably be to find (or write) a CLI tool or Python library which we could invoke as part of our existing dependency update workflow?

Also see [Dependabot's implementation](https://github.com/dependabot/dependabot-core/tree/main/github_actions/lib/dependabot/github_actions) (Ruby), and [GitHub Actions Version Updater · Actions · GitHub Marketplace](https://github.com/marketplace/actions/github-actions-version-updater) ([written in Python](https://github.com/saadmk11/github-actions-version-updater/blob/main/main.py)).

Or to avoid the "not invented here" syndrome, I suppose we could just run that action weekly, but I'm a bit cautious about using third-party actions, especially if they need elevated permissions like in this case.

**Comment by The-Compiler** [comment]
Just introduced this into another project, and it seems to correctly stick to the existing version pinning convention (e.g. only major version) nowadays. Let's give it a try, if we're lucky the forks issue is solved as well nowadays (pretty sure that was a bug!).

I just reintroduced it, will keep it around unless we run into issues or someone complains.

**Comment by The-Compiler** [comment]
Oh, looks like they fixed the fork issue today, actually! https://github.blog/changelog/2022-11-07-dependabot-pull-requests-off-by-default-for-forks/
