### ISSUE TITLE
cannot save HAR file from devtools

### ISSUE THREAD

**Issue by jacobhenn** [qutebrowser/qutebrowser#7319]
**Version info**:

qutebrowser v2.5.1
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.4 (compiled 5.15.2)

**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

the chromium devtools has an option in the right-click menu for an HTTP request (under the "Network" tab) called "Save all as HAR with content". nothing happens when i click this. expected behavior would be for it to open the regular file download prompt and let me choose where to save the HAR file.

i'm not sure that Qutebrowser is the one at fault here, but it seems like the most likely culprit.

**How to reproduce**

1. go to a website that will exchange a lot of requests (like `google.com`).
2. open the devtools and go to the "Network" tab.
3. in the lower table, right-click on the name of one of the requests and select "Save all as HAR with content". if you don't see any requests, set the request type to "All" and reload.
4. nothing happens.

**Comment by The-Compiler** [comment]
I added a comment here: [[QTBUG-85171] Missing features in inspector/devtools - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-85171)
