### ISSUE TITLE
Same hint for same links

### ISSUE THREAD

**Issue by julianbuettner** [qutebrowser/qutebrowser#7322]
When typing `f` tp follow a hint, all hrefs on the site are assigned a one or two letter combination.

However, if two links lead to the exactly same URL, it get's assigned two different letter combinations.  
This can be tested on the bookmark site, where name and URL both are linked, but have different letter combinations.

Assigning the same combination twice would have the following advantages:  
- Seeing directly that two links lead to the same page
- Lower likelihood of needing a two letter combination

**Comment by toofar** [comment]
You are not the first one with that idea! https://github.com/qutebrowser/qutebrowser/pull/5287

**Comment by The-Compiler** [comment]
This is already discussed in #71, so I'm closing this as a duplicate.
