### ISSUE TITLE
Enabling dark mode while the browser is running.

### ISSUE THREAD

**Issue by matt-bsd** [qutebrowser/qutebrowser#7323]
**Version info**:
``qutebrowser v2.5.1
Git commit:
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.5 (compiled 5.15.2)``

**Does the bug happen if you start with `--temp-basedir`?**:
Well, this is not applicable, because when I start with --temp-basedir, there is no way to edit the config file, set a dark mode and then doing :config-source.

**Description and How to reproduce**
My qutebrowser is running and downloading some large file, while I am reading something. I can't read that properly because dark mode is on. I can't change the config and restart qutebrowser, because that would destroy my download which is already running for an hour. So I try to change the config file by commenting this line:

``config.set("colors.webpage.darkmode.enabled", True)``

save, quit, do :config-source, reload page, try to run another qutebrowser instance, which only says:
``17:54:24 INFO: Opening in existing instance``

And nothing happens

So I also tried to do this:

``config.set("colors.webpage.darkmode.enabled", False)``

save, quit, do :config-source

Nothing happens. 

It works when I actually kill this instance of qutebrowser and start "anew". 
Shouldn't it work also with :config-source ?

**Comment by The-Compiler** [comment]
That setting needs a restart (see `:help colors.webpage.darkmode.enabled`). It's unclear if there is a good way around that, see #5542 for some more context.
