### ISSUE TITLE
PDF.js "... is not a function" error

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [qutebrowser/qutebrowser#7335]
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.5 (compiled 5.15.4)

CPython: 3.10.5
PyQt: 5.15.7

sip: 6.6.2
colorama: 0.4.5
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: 0.6.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: 2.14.305 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.39.1
QtNetwork SSL: OpenSSL 1.1.1q  5 Jul 2022

Style: Breeze::Style
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.1.4
Platform: Linux-5.18.16-arch1-1-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:10

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
After the update of `pdf.js`, the pdf viewer functionality seems broken now.

![](https://i.imgur.com/ZQQjCo3.png)

The error message says the member `at` is not a function, and the `require` function could not be found.
I'm guessing that it might be related to this PR since I can open pdf files normally when I downgrade to the previous version of `pdf.js`  (2.14.305).
https://github.com/mozilla/pdf.js/pull/15008

**How to reproduce**
Use qutebrowser to open some pdf file with pdf.js 2.15.349 (the latest version in ArchLinux community repo).

**Comment by m-falconi** [comment]
I can confirm the issue, I am on the same architecture (Arch Linux) as the OP.

**Comment by emanuele6** [comment]
This has also been happening to me, I tried writing a greasemonkey userscript to inject a [Array.prototype.at](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) implementation i wrote as a temporary fix:
```javascript
// ==UserScript==
// @name        fix array prototype pdfjs
// @include     qute://pdfjs/*
// @run-at document-start
// ==/UserScript==

Array.prototype.at = function(i) {
    if (i < 0)
        i += this.length
    if (i < this.length)
        return this[i]
}
```
..but then there is also this error about [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) missing, which is way more involved to implement
![file](https://user-images.githubusercontent.com/20175435/183086784-dd376210-2a46-4e96-81ca-3cd9a730703c.png)

These functions are relatively new; according to MDN, Chrome supports:
* `Array.prototype.at` since version 92 (July 2021)
* `structuredClone` since version 98 (February 2022)

`Qt5`'s `QtWebEngine` probably doesn't support them yet.

**Comment by The-Compiler** [comment]
Here is a complete polyfill, based on the `Array.at` one qutebrowser had in 726d5e614b1f80c339084eba7d1c240bf467fa9b, and the `structuredClone` fallback PDF.js itself had until https://github.com/mozilla/pdf.js/commit/7cc761a8c0ff12217ff8478bdb5a2fce3a07833a. With that, PDFs are displayed again for me, albeit without offloading work to service workers (because we can't inject scripts there, sadly).

<details>

```js
// ==UserScript==
// @name        pdfjs polyfill
// @include     qute://pdfjs/*
// @run-at      document-start
// ==/UserScript==

// https://github.com/tc39/proposal-relative-indexing-method#polyfill
// https://github.com/qutebrowser/qutebrowser/commit/726d5e614b1f80c339084eba7d1c240bf467fa9b
(function() {
    function at(idx) {
        // ToInteger() abstract op
        let n = Math.trunc(idx) || 0;
        // Allow negative indexing from the end
        if (n < 0) {
            n += this.length;
        }
        // OOB access is guaranteed to return undefined
        if (n < 0 || n >= this.length) {
            return undefined;
        }
        // Otherwise, this is just normal property access
        return this[n];
    }

    const TypedArray = Reflect.getPrototypeOf(Int8Array);
    for (const type of [Array, String, TypedArray]) {
        Object.defineProperty(
            type.prototype,
            "at",
            {
                "value": at,
                "writable": true,
                "enumerable": false,
                "configurable": true,
            }
        );
    }
})();

// We can't patch Array.at for Workers, so we just pretend we don't support
// them, as PDF.js works without them too.
unsafeWindow.Worker = undefined;

// https://github.com/mozilla/pdf.js/commit/7cc761a8c0ff12217ff8478bdb5a2fce3a07833a
unsafeWindow.structuredClone = function(object, transfers) {
  // https://youmightnotneed.com/lodash
  const isArrayBuffer = value => value.toString() === '[object ArrayBuffer]'

  // Trying to perform a structured clone close to the spec, including
  // transfers.
  function fallbackCloneValue(value) {
    if (
      typeof value === "function" ||
      typeof value === "symbol" ||
      value instanceof URL
    ) {
      throw new Error(
        `LoopbackPort.postMessage - cannot clone: ${value?.toString()}`
      );
    }

    if (typeof value !== "object" || value === null) {
      return value;
    }
    if (cloned.has(value)) {
      // already cloned the object
      return cloned.get(value);
    }
    let buffer, result;
    if ((buffer = value.buffer) && isArrayBuffer(buffer)) {
      // We found object with ArrayBuffer (typed array).
      if (transfers?.includes(buffer)) {
        result = new value.constructor(
          buffer,
          value.byteOffset,
          value.byteLength
        );
      } else {
        result = new value.constructor(value);
      }
      cloned.set(value, result);
      return result;
    }
    if (value instanceof Map) {
      result = new Map();
      cloned.set(value, result); // Adding to cache now for cyclic references.
      for (const [key, val] of value) {
        result.set(key, fallbackCloneValue(val));
      }
      return result;
    }
    if (value instanceof Set) {
      result = new Set();
      cloned.set(value, result); // Adding to cache now for cyclic references.
      for (const val of value) {
        result.add(fallbackCloneValue(val));
      }
      return result;
    }
    result = Array.isArray(value) ? [] : Object.create(null);
    cloned.set(value, result); // Adding to cache now for cyclic references.
    // Cloning all value and object properties, however ignoring properties
    // defined via getter.
    for (const i in value) {
      let desc,
        p = value;
      while (!(desc = Object.getOwnPropertyDescriptor(p, i))) {
        p = Object.getPrototypeOf(p);
      }
      if (typeof desc.value === "undefined") {
        continue;
      }
      if (typeof desc.value === "function" && !value.hasOwnProperty?.(i)) {
        continue;
      }
      result[i] = fallbackCloneValue(desc.value);
    }
    return result;
  }

  const cloned = new WeakMap();
  return fallbackCloneValue(object);
}
```

</details>

I'm however a bit lukewarm about actually shipping that with qutebrowser - it's rather hacky, and PDF.js provides a [legacy build](https://github.com/mozilla/pdf.js#building-pdfjs) which does work fine with Qt 5 still (also, the normal build works fine with Qt 6 too).

I've been talking to @Foxboron in IRC about just making Archlinux' `community/pdfjs` ship the legacy build (or have a second package doing so), but I'm not sure I managed to convince them that's a good idea (hell, I'm not even convinced myself!).

**Comment by jsilve24** [comment]
I am also having this issue. Following along.

**Comment by Foxboron** [comment]
>I've been talking to @Foxboron in IRC about just making Archlinux' community/pdfjs ship the legacy build (or have a second package doing so), but I'm not sure I managed to convince them that's a good idea (hell, I'm not even convinced myself!).

More packages! I dislike this :) I'm contemplating just doing an epoch downgrade.

**Comment by mlmatlock** [comment]
Jumping onboard the pdf.js v2.15.349 train.
```
 qutebrowser v2.5.2
Git commit: 21c82b029 on master (2022-08-22 15:19:29 +0200)
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.5 (compiled 5.15.4)

CPython: 3.10.6
PyQt: 5.15.7

sip: 6.6.2
colorama: 0.4.5
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: 0.6.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: 2.15.349 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.39.2
QtNetwork SSL: OpenSSL 1.1.1q  5 Jul 2022

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.1.6
Platform: Linux-5.19.3-arch1-1-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/merell/.cache/qutebrowser
config: /home/merell/.config/qutebrowser
data: /home/merell/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/merell/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
```
Same behavior with `--temp-basedir`.

For me, pdf.js stopped displaying *any* pdf file (either online or local).  Until I installed the -git version from the AUR, there were no messages, just the blank pdf.js display.

When I installed the -git version, I got some error messages:

```
10:34:01 ERROR message message:error:78

JS: [qute://pdfjs/build/pdf.js:4905] Uncaught TypeError: key.split(...).at is not a function

10:34:01 ERROR message message:error:78

JS: [qute://pdfjs/web/viewer.js:3715] Uncaught ReferenceError: require is not defined

10:34:01 ERROR message message:error:78

JS: [qute://pdfjs/web/viewer.html?filename=tmpdx434rm4_labs.pdf&file=&source=file:///home/merell/Downloads/labs.pdf:469] Uncaught TypeError: Cannot read property 'set' of undefined
```
Attempt at remote file had same errors, except for the source:

```
10:49:32 ERROR message message:error:78

JS: [qute://pdfjs/web/viewer.html?filename=tmp6p22fvqp_SRX800-Spec-Sheet.pdf&file=&source=https://www.lotek.com/wp-content/uploads/2017/10/SRX800-Spec-Sheet.pdf:469] Uncaught TypeError: Cannot read property 'set' of undefined
```




Like OP, downgrading to v2.14.305 restores functionality.

**Comment by The-Compiler** [comment]
I looked at the current situation, and anything older than QtWebEngine 6.3 nowadays seems to throw a syntax error, which is not something we can polyfill anyways. For 6.3 to 6.7 we have a polyfill, and for 6.8+ it looks like currently things work natively.
