### ISSUE TITLE
Notifications with DESKTOP_FILE_NAME

### ISSUE THREAD

**Issue by palb91** [qutebrowser/qutebrowser#7338]
Hello!
Notifications use "qutebrowser" as application name, it is hardcoded in `browser/webengine/notification.py`.
I have some qutebrowser instances for which I specify the DESKTOP_FILE_NAME and I'd like to use this setting instead of "qutebrowser" with my notification daemon.
The notification daemon is `mako`, it allows to set settings per criteria, and I'd like to set a different style per window.

**version**
https://paste.the-compiler.org/view/4f8f3f65

**Comment by palb91** [comment]
I like to propose a PR for this, but I did not find a way to get the value. It is store somehow in app.py with `app.setDesktopFileName`, then how can I reuse this value?

**Comment by toofar** [comment]
You should be able to access the current QApplication as `qutebrowser.misc.objects.qapp` from anywhere within the codebase.

**Comment by palb91** [comment]
Ah ! Thanks, I'll try that !

**Comment by palb91** [comment]
No relevant
