### ISSUE TITLE
Page not scrolled to search result

### ISSUE THREAD

**Issue by jpalus** [qutebrowser/qutebrowser#7367]
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.4

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Sometimes `qutebrowser` does not scroll page to show search result even though indicator on the right shows matches. Note that this appears to happen only if incremental search is disabled.

**How to reproduce**
1. Disable `search.incremental`: `set search.incremental false`
2. Go to https://qutebrowser.org/
3. Search backwards for `pdf` found at the bottom of the page so it scrolls down: `?pdf`
4. Search forward for `gui` found at the top: `/gui`

**Comment by The-Compiler** [comment]
Seems to happen in Chromium as well:

![image](https://user-images.githubusercontent.com/625793/186758912-07c48720-5590-49db-bae5-9abe7d14d536.png)

So most likely a Chromium issue which neither we nor QtWebEngine can do much about.

**Comment by The-Compiler** [comment]
I did a quick test with incremental disabled in KDE Falkon:

```diff
diff --git i/src/lib/webtab/searchtoolbar.cpp w/src/lib/webtab/searchtoolbar.cpp
index 8bdf59825..8eccb237a 100644
--- i/src/lib/webtab/searchtoolbar.cpp
+++ w/src/lib/webtab/searchtoolbar.cpp
@@ -42,7 +42,7 @@ SearchToolBar::SearchToolBar(WebView* view, QWidget* parent)
     connect(view->page(), &QWebEnginePage::findTextFinished, this, &SearchToolBar::showSearchResults);
 
     connect(ui->closeButton, SIGNAL(clicked()), this, SLOT(close()));
-    connect(ui->lineEdit, &QLineEdit::textEdited, this, &SearchToolBar::findNext);
+    //connect(ui->lineEdit, &QLineEdit::textEdited, this, &SearchToolBar::findNext);
     connect(ui->next, &QAbstractButton::clicked, this, &SearchToolBar::findNext);
     connect(ui->previous, &QAbstractButton::clicked, this, &SearchToolBar::findPrevious);
     connect(ui->caseSensitive, &QAbstractButton::clicked, this, &SearchToolBar::caseSensitivityChanged);

```

and can see the same behavior there. Given that it happens in Chromium as well, I suppose there isn't much use about reporting this to QtWebEngine - and in Chromium it's only really an edge case (if you type fast enough), so I don't think it'll go very far if I report this there either. Sorry!
