### ISSUE TITLE
Unify `{indicators}` and make them more flexible

### ISSUE THREAD

**Issue by bzbug** [qutebrowser/qutebrowser#7383]
# Problem

Indicators like `{audio}` in tabbar behave and look differently and because of that they kind of enforce a certain look on the user. For instante, the `{audio}` indicator has `[]` brackets around it and you can't remove those, the indicator also has built-in space _after_ it, which ruins its placement at the end of the tabs when using vertical tabbar (when doing that, the extra space enforces a minimum right padding for the vertical tabs and if you try to lessen the width of the tabbar with `tabs.width` so that the extra space would disappear behind the right border of each tab, the extra space and the `]` symbol of the `{audio}` indicator _both_ disappear and get replaced with a `...`). Also, `{relative_index}` doesn't obey padding set via `{relative_index: >3}` for the currently focused tab; for all other tabs the padding seems to work, but for the currently chosen it doesn't. Also, `{relative_index}` has a built-in space before it for all tabs except for the focused one. If you do something like `|{relative_index}`, there will be space between `|` and `{relative_index}` and you can't remove it. Widgets for statusbar also have `[]` brackets built-in, so I can't replace them with my own formatting that's more intuitive for me and thus makes the widgets way more useful. You cannot move favicons to the right of the tabs when you have a right-aligned vertical tabbar, it'd make more sense from my perspective as a user to also have a `{favicon}` variable that you could place wherever you want. You also cannot (or I don't know how to do it) customize alternative values. For instance, suppose you want the `{audio}` indicator to show `M` (muted) when the tab's muted, `A` (audio) when there's sound in the tab and `S` (silent) when the tab's not muted but is silent. You can't do that now as far as I know, but if we had primitive conditionals for `{var}`s, we'd be able to do this: `{audio?audio!S: ^3}` (`{condition?true_action!else_action}`: show `{audio}` indicator which can either display `M` or `A` if the indicator has something to display, otherwise show `S`, so when a tab is not muted but is silent, the indicator has nothing to display and our `S` will be chosen; also pad the whole thing to the width of 3 symbols and center-align it). It'd also be very nice if we could change the indicator's looks (like what to display instead of `M` when the tab's muted and what to display instead of `A` when there's sound), it's also not very convenient for some people (me) to have hardcoded symbols with certain meaning, it's like, it seems like the info is there and I should be able to easily locate the tab that has audio playing, but I can't because it just looks non-intuitive, my eyes pass right past it and I don't even notice. This list is not exhaustive, these are only the problems that I've noticed, there might be similar issues with other indicators (like trailing spaces).

## Screenshots:

1. The second number `43` that is to the right of the `|` symbol (this one: `|43`) is `{relative_index: >3}`, so it should be displayed with the same padding that corresponding numbers of the tabs above and below are displayed, but instead it it's displayed with no space at all before it. The 43d tab is the current one (focused/selected).
![180x65_ 04 09 2022 22:23](https://user-images.githubusercontent.com/28236673/188328049-a9f14e7c-b30d-4179-a3e4-3cc2197cf760.png)

2. Also note the different left and right padding for the tabs in the screenshot above. The right padding is bigger and I cannot lessen it because of the mentioned extra space in the `{audio}` indicator. This is the minimum tabbar width I found for the indicator to be properly displayed, making it even one pixel less results in `[M...` at the end instead of `[M]` without the extra space.

3. **Find The Tab With Sound** game. You have: **3 days**. Your brain will melt because of the sound in: **5 minutes**. Good luck.

![163x494_ 04 09 2022 22:47](https://user-images.githubusercontent.com/28236673/188328935-54c46da8-428a-472a-a0d0-7e391b2a8a77.png)

# Suggestion

1. Unify all the `{indicators}` and widgets so that they would not have additional built-in decorations and the user could decide how to decorate the indicators in the more intuitive way for him so that he could easily find what he needs and quickly comprehend what he's seeing. This includes trailing whitespace and `%` sign for the `{perc}` indicator (the user could easily add it to the raw version of the page perc, is it really necessary to have a separate `{variable}` for one particular styling option of the same thing when there's already a raw version which allows for different styles and decorations?).
2. Introduce simple conditionals so that the user could not only add the mentioned pseudo indicator for the unmuted but silent tabs, but also decorate the indicators properly. For example, if some indicator or a widget can either be present or not present, but the user wants to frame it in `{}`, he can't do that right now because, when the indicator isn't present, the empty `{}` frame will remain in its place. With conditionals, you could show the frame if the indicator has something to display and hide them when it hasn't.
3. Add a `{favicon}` variable so that the user could place it wherever he likes.
4. Add an option for custom values for the indicators. For instance, values for `{audio}` indicator for when the tab's muted, when it has audio and when it's silent.
5. And, as a separate thing from my wish list, I'd really like an option to replace progress bars for when the page is loading with something dynamic but in ASCII. For example, `[===>   ]` bar would be nice in statusbar. It's just the "beautiful" version doesn't match well with the ASCII and CMD spirit of the browser, imo. Having an ASCII progress bar (better even by default, with an option so switch back to the "beautiful" one) would make it more consistent with the rest of the browser.

**Comment by toofar** [comment]
Some comments:

* maybe you could have a look at https://github.com/qutebrowser/qutebrowser/issues/1578 and maybe if you have time sketch out how you could see it working, or not working, for you?
* for the audio indicators see https://github.com/qutebrowser/qutebrowser/pull/4089 for a hack to change them
* regarding your first screenshot with the index numbers not lined up, I believe that is on purpose with `relative_index`, see https://github.com/qutebrowser/qutebrowser/pull/6619, have you tried with `aligned_index` instead? (ref https://qutebrowser.org/doc/help/settings.html#tabs.title.format)

**Comment by bzbug** [comment]
@toofar,

1. Sorry, but what exactly do you mean? How I see it working to solve this particular problem? Or what? I mean, as far as I can tell it fixes the issue, but this issue's already mentioned there, do they need me there commenting the obvious? If they do, I will, I'm just not sure how things are done.
2. Thank you for the hack for audio indicators, will be using for now, until `jinja` is introduced.
3. Not sure why you're askng, `{aligned_index}` is absolute index, isn't it? The problem is, I need both the absolute and the relative and I need the both numbers to be aligned normally. No special treatment for the focused tab. I think the special treatment shouldn't even be there in the first place, it enforces a particular alignment where one isn't expected or wanted by the user. It should just be a value available for user-defined alignment. Yes, it would be nice to distinguish somehow between the focused tab and unfocused ones, but not at the expense of alignment working. Especially when there's already a `color` option for the focused tab to single it out visually. What should I do, post the request to remove the special alignment in the issue you've mentioned (in #6619) or leave it here and people will find it when they see the issue is mentioned here?

**Comment by The-Compiler** [comment]
Let's merge this into #1578 - I think that'll be the right way forward, and is both easier and more powerful than implementing our own mini-language.
