### ISSUE TITLE
Fullscreen state is not properly reflected in _NET_WM_STATE window flags

### ISSUE THREAD

**Issue by nicktelford** [qutebrowser/qutebrowser#7386]
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.5 (compiled 5.15.4)

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
Setting `content.fullscreen.window` to `false` permanently sets `_NET_WM_STATE = _NET_WM_STATE_FULLSCREEN`, toggling fullscreen with `:fullscreen` has no effect.

Setting `content.fullscreen.window` to `true` permanently sets `_NET_WM_STATE = ""`, toggling fullscreen with `:fullscreen` has no effect.

Note: changing the value of `content.fullscreen.window` needs a restart for it to change `_NET_WM_STATE`.

**Expected behaviour**
* `:fullscreen` should toggle `_NET_WM_STATE` between `_NET_WM_STATE_FULLSCREEN` and no-value, when `content.fullscreen.window == false`.
* `:fullscreen` should not change `_NET_WM_STATE` when `content.fullscreen.window == true`.

**How to reproduce**
* Set `content.fullscreen.window` in `qute://settings/`
* Toggle fullscreen with `:fullscreen`
* Use `xprop | grep _NET_WM_STATE` (click on the qutebrowser window after running command) to verify the value of the window state flag.

**Comment by nicktelford** [comment]
On further testing, it looks like the `:fullscreen` toggle is working, but `_NET_WM_STATE` is only updating after qutebrowser is restarted.

**Comment by The-Compiler** [comment]
No worries, thanks for the follow-up! Now you got me curious though, what WM and what bug?
