### ISSUE TITLE
Statusbar widgets not disappearing

### ISSUE THREAD

**Issue by tomiesz** [qutebrowser/qutebrowser#7389]
**Version info**:
https://paste.the-compiler.org/view/7ec6a777

**Description**
History and progress statusbar widgets dont get hidden properly after changing the config. 

**How to reproduce**
Change the config in the browser (i used :set), and remove history or progress. They will show up regardless, ignoring the layout. This "fixes" itself on browser restart.

**Source**
Seems like due to the fact that these particular widgets update their visibility based on signals, changing their visibility status doesn't have the desired effect as it gets immidiately reverted. 

**Fix**
A workaround would be to handle them separately in the _clear_widgets function, and disable them instead of setting them to hidden. 

   
 ```python
    def _clear_widgets(self):
        """Clear widgets before redrawing them."""
        # Start with widgets hidden and show them when needed
        for widget in [self.url, self.percentage,
                       self.backforward, self.tabindex,
                       self.keystring, self.prog, self.clock, *self._text_widgets]:
            assert isinstance(widget, QWidget)
            widget.hide()
            """These widgets manage their own visibility and if only set to
            invisible, they will flip it back"""
            if widget in [self.backforward, self.prog]:
                widget.enabled=False
            self._hbox.removeWidget(widget)
        self._text_widgets.clear()
```

**Comment by The-Compiler** [comment]
cc @Nicholas42 who has refactored the statusbar some months ago - I haven't had the time to check, but I wonder if this is perhaps a regression introduced there.

**Comment by tomiesz** [comment]
Looks like the code looked roughly the same in that regard ever since [f51ac8a](https://github.com/qutebrowser/qutebrowser/commit/f51ac8ab6e7ffdc95a3e8ac91098764f79302a15) - which is where the status bar configurability was added. 
We are already managing progress and history in a separate way in the_draw_widgets due to this reason it seems.
```
                # Do not call .show() for these widgets. They are not always shown, and
                # dynamically show/hide themselves in their on_tab_changed() methods.
 ```

**Comment by The-Compiler** [comment]
f51ac8a looks entirely unrelated. Also, I can't actually reproduce this with `qutebrowser --temp-basedir  ":open example.org" ":later 1000 open qutebrowser.org" ":later 4000 set statusbar.widgets \"['keypress', 'url', 'scroll', 'tabs', 'progress']\""`. The back/forward widget disappears as expected.

**Comment by Nicholas42** [comment]
I can reproduce it with 

```
qutebrowser --temp-basedir ":open example.org" ":later 1000 open qutebrowser.org" ":later 4000 set statusbar.widgets \"['keypress', 'url', 'scroll', 'tabs', 'progress']\"" ":later 6000 back" ":later 8000 forward"
```

It is a bit hard to see, but you have a weird line in the scroll widget. I can't directly say what the problem is, but I wouldn't be surprised if t has to do with them managing their own visibility. But I won't be able to look at that for at least a week.

**Comment by The-Compiler** [comment]
Yep, something seems off there indeed, as if the widget was still around but not part of the statusbar:

![image](https://user-images.githubusercontent.com/625793/189196916-b07b5427-6a07-4e7c-b2c2-9d4ddb3a682e.png)

I won't be able to look at this for at least a week either, as I'll be away until next Thursday.

**Comment by toofar** [comment]
Thanks for spotting, and for the fix.
