### ISSUE TITLE
Divide HTTPS websites into three major categories instead of two

### ISSUE THREAD

**Issue by bzbug** [qutebrowser/qutebrowser#7393]
# Problem
There are currently two categories of HTTPS websites that are understood by QB: secure HTTPS websites and websites which are insecure in one way or another (like, rare HTTP websites or HTTPS websites with invalid certs). So basically, either a website IS secure or it isn't. This is how the user sees it.

The problem is, there are reverse-proxy services which are kind of in the middle. Technically, you have secure connection with them, but from the user perspective, you think you have secure connection to the original website, not the reverse-proxy. This means that the users think that, when they visit `example.com`, the only party they have to trust is the original website, `example.com`, not the reverse-proxy it uses. But in reality the users' traffic is decrypted by the reverse-proxy before it even reaches the intended (from the user perspective) destination of the original website and before the passwords get hashed. And reverse-proxies work in such a way so that the user doesn't know he is trusting his passwords to a third party before he reaches the website and reads its Privacy Policy. So basically, the user is deceived by this chain of `Reverse-Proxy+Original Website` and his private data are shared with a third party before he even agrees to anything.

One could say, the user always has the option of removing corresponding certificates and CAs from his computer's trusted base and use the browser's mechanism of handling the invalid certs, but herein lay two intertwined problems:

1. Reverse-proxy certs are more of their own cert type, the issue with them is different than just with plain invalid certs, and the user would want an ability to handle reverse-proxies differently or to at least see a different warning or a different prompt for them.
2. Reverse-proxies are everywhere, hence the necessity of a separate prompt/warning - so that the choice wouldn't just be to either block them all and treat them as invalid certs or allow them all and trust them blindly.

# Suggestion

Is it technically possible to create an HTTPS-Warning type for websites with its separate prompt? Or does it fully depend on the user's machine's handling of certificates and the problem should be resolved there instead of the browser? And if it is technically possible to implement it in QB, but better to do it system-wide, maybe still implement it in QB to help the world with the reverse-proxy MitM problem and make the browser a little more secure that way in practice, even if it's not ideal, so that at least the end users could easily defend themselves against reverse-proxy leaks and such and be more aware this problem even exists and their connection isn't quite as direct as they think?

**Comment by The-Compiler** [comment]
We don't have that kind of information in the QtWebEngine API - but even if we had, this seems like an unsolvable problem, for various reasons:

- It's non-trivial (if possible at all) to find out what's a reverse proxy and what is not (also, I'm assuming you mean third-party reverse proxies only?)
- For e.g. Cloudflare, it's possible to [upload your own certificate](https://developers.cloudflare.com/ssl/edge-certificates/custom-certificates/)
- You need to trust third-parties anyways - at least as soon as you're using a web application using third-party code (no matter where that code is shipped from).
