### ISSUE TITLE
Qt 6: Blank rectangles (mainly with AMD graphics?)

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7398]
Some people (including me) sometimes seem to get blank rectangles over pages with Qt 6. No idea why that happens so far.

See https://github.com/qutebrowser/qutebrowser/issues/5395#issuecomment-1086914421 and https://github.com/qutebrowser/qutebrowser/issues/7202#issuecomment-1245301468.

**Comment by ionenwks** [comment]
Unsure if it's the same thing, but ftr with NVIDIA (1070, xorg, 515.65.31 drivers) and Qt 6.3.1 I sometime see white rectangles flash by (e.g. I see these at the bottom when maximizing a media player) and then return to normal. It hardly been a bother given its temporary nature though.

**Comment by Bonoolu** [comment]
someone recommended setting these chromium flags:
--disable-gpu-driver-bug-workarounds
--enable-gpu-rasterization
Source: [forum.qt.io/topic/135869/](https://forum.qt.io/topic/135869/pyside6-qtwebengine-throwing-error-attempt-to-read-from-an-uninitialized-sharedimage/2)

**Comment by ionenwks** [comment]
> i have set these chromium flags 9 days ago, i no longer have blank rectangles showing up.

Just to report, tried these as well given it was starting to annoy me a bit more than before (wrt earlier comment), and flags are working as advertised with nvidia too for me. Not seeing ill effects so far (or at least, not on Xorg), albeit unsure if it'd be safe as a default for all.

**Comment by benjaminbhollon** [comment]
Hmm, I occasionally get them on sites that are heavy with JS, especially with media playing, (most recently I noticed it on YouTube) but they're white rectangles. Not sure if that's related.

**Comment by The-Compiler** [comment]
"blank" means white, so it sounds like you're seeing the same issue. What QtWebEngine version is this on (see `:version`)?

**Comment by benjaminbhollon** [comment]
Backend: QtWebEngine 6.3.1, based on Chromium 94.0.4606.126 (from api)

I'm using the flathub-beta version.

**Comment by benjaminbhollon** [comment]
Got it again on pinafore.social, viewing a poll.

**Comment by Bonoolu** [comment]
> Got it again on pinafore.social, viewing a poll.

Do these settings help?

1. open qutebrowser
2. execute this command to set the settings:
:set qt.args '["disable-gpu-driver-bug-workarounds", "enable-gpu-rasterization"]'
3. execute this command to save the settings:
:config-write-py -f

**Comment by The-Compiler** [comment]
> execute this command to save the settings: `:config-write-py -f`

That's both unnecessary (if you don't have a config.py yet), and dangerous (if you have a config.py already, because it'll be overwritten).

**Comment by benjaminbhollon** [comment]
> Do these settings help?

I'm not noticing issues with that on, but then I haven't yet found a site that always has the rectangles, so I'm not sure if this is helping or if I just haven't run across the issue. I'll keep an eye out.
