### ISSUE TITLE
`insert_mode.leave_on_load = False` ineffective with qt6

### ISSUE THREAD

**Issue by nrdxp** [qutebrowser/qutebrowser#7404]
**Version info**:
```
qutebrowser v2.5.2
Git commit: 5e11e6c7d413cf5c77056ba871a545aae1cfd66a
Backend: QtWebEngine 6.3.1, based on Chromium 94.0.4606.126 (from override)
Qt: 6.3.1
```

**Description**
When typing in a text box that simultaneously changes the site url, such as a search box on many sites, qutebrowser leaves insert mode. This has been reported before and closed in a previous version, but I was asked to open a new issue: https://github.com/qutebrowser/qutebrowser/issues/3596#issuecomment-1251448150

It would seem logical that `insert_mode.leave_on_load` set to `False` should fix this behavior, and indeed this was the reported solution in the previous issue, but unfortunately that doesn't work for me.

**How to reproduce**
* Build qutebrowser from the [qt6-v2](https://github.com/qutebrowser/qutebrowser/tree/qt6-v2) branch. 
> If one has access to the the Nix package manager, you can build the exact package I am using with `nix build github:nrdxp/nrdos/locked#qutebrowser`, this also includes a wrapper that calls qutebrowser with my same configuration as well.
* Ensure `insert_mode.leave_on_load` is set the `False` in your configuration, or set it dynamically from prompt mode
* Go to https://doc.rust-lang.org/stable/book
* Type something in the search box and notice how qutebrowser keeps exiting insert mode, making it difficult to type

**Comment by The-Compiler** [comment]
This works fine for me on Qt 6 no matter what the value of `insert_mode.leave_on_load` is (i.e., even with it set to true!).

Related commit: 0ace4a5fee8994fbce55edb6617ec150d7fa2b1e

A couple of questions:

- Can you reproduce it with `qutebrowser --temp-basedir -s input.insert_mode.leave_on_load false https://doc.rust-lang.org/stable/book` too?
- Your version info says "QtWebEngine 6.3.1, based on Chromium 94.0.4606.126 (from override)" - IIRC that is via NixOS setting `QUTE_QTWEBENGINE_VERSION_OVERRIDE` in the environment. Could you double-check that's in fact correct?
- Could you run `:report` after reproducing this (ideally with `--temp-basedir`) so I can take a look at the logs?
- Can you reproduce with Qt 5 on the master branch as well?

**Comment by nrdxp** [comment]
Thanks for the help.
* If I just run the command you pasted then I still experience the issue (it picks up my default config from my wrapper, using the -C flag), but if I also add `-C f.py` where f.py is an empty config then it works. So I suppose something in [my config](https://github.com/nrdxp/nrdos/blob/master/cells/display/packages/qutebrowser/config.py) is a miss.
* Yes this is correct, for now I have built the derivation myself (there have been 3 PR attempts to package pyqt6 in nixpkgs, hopefully the latest will soon be merged), so I'm using a fork for now.
* Sure, I'll attach: [report.log](https://github.com/qutebrowser/qutebrowser/files/9609399/report.log)
* haven't tried yet, I'm gonna see if I can determine what in my configuration is causing this first

**Comment by The-Compiler** [comment]
My bet is `input.mode_override` being set to `"normal"`:

> Mode to change to when focusing on a tab/URL changes.

**Comment by nrdxp** [comment]
I narrowed it down to `c.input.mode_override = "normal"`. After reviewing the docs on that, it makes sense, since it takes affect on url changes. So this is user error, not a bug. My apologies for the false positive, and thanks again for thelp :pray:

**Comment by The-Compiler** [comment]
Hehe, looks like I was half a second or so faster :wink:

Glad you found the culprit - yep, that's something you'd usually set with an URL pattern rather than globally, to e.g. automatically enter passthrough mode when loading a certain site.
