### ISSUE TITLE
Could not find the Qt platform plugin "xcb" in ""

### ISSUE THREAD

**Issue by ThanosApollo** [qutebrowser/qutebrowser#7414]
**Version info**:

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
I updated my system(Arch Linux), now qutebrowser fails to start, 
erorr message : 
```
20:22:07 WARNING: Could not find the Qt platform plugin "xcb" in ""
20:22:07 CRITICAL: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Fatal Python error: Aborted

Current thread 0x00007f93a5624740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 558 in __init__
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 95 in run
  File "/usr/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245 in main
  File "/usr/bin/qutebrowser", line 33 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, markupsafe._speedups, yaml._yaml, PyQt5.QtNetwork, PyQt5.QtQml, PyQt5.QtSql, PyQt5.QtOpenGL, PyQt5.QtDBus, PyQt5.QtWebChannel, PyQt5.QtWebEngineCore, PyQt5.QtPrintSupport, PyQt5.QtWebEngineWidgets, PyQt5.QtWebEngine (total: 15)
zsh: IOT instruction (core dumped)  qutebrowser
```
I uninstall qutebrowser and reinstalled, along with `qt5-base qt5-styleplugins pyqt pyqt5` but to no avail, the rest of my qt5 apps work fine(vlc, virtualbox etc. just qutebrowser gives me this error).
**How to reproduce**
Not sure, I just updated my system and now qutebrowser fails to start

**Minor update**
I installed `qutebrowser-qt6-git` and now everything works fine, i will mark it as solved and leave it here for anyone that might face the same issue

**Comment by The-Compiler** [comment]
FWIW that looks like an issue in your (Py)Qt5 installation. You might want to `export QT_DEBUG_PLUGINS=1` if you need to debug it anyways, as it might affect other applications too.
