### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by SuzunaMinami** [qutebrowser/qutebrowser#7420]
**Version info**:
```
qutebrowser v2.5.2
Git commit: f911ffd55 on v2.5.x (2022-06-22 16:04:52 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2
```

**Description**
The copy to clipboard button doesn't actually work in Qutebrowser. For example, see the below image
![image](https://user-images.githubusercontent.com/49131888/193455552-b671d6e8-0355-42aa-b881-fb77485e8218.png)

The copy button when clicked actually doesn't reflect the content in the clipboard. This happens for both clicking and follow link actions

**How to reproduce**
Go to any GitHub website, click on `Code` and click on copy button

**Comment by The-Compiler** [comment]
It's disabled by default - see point 22 in [the FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc).
