### ISSUE TITLE
QuteBrowser and QtWebengine: look like any normal browser.

### ISSUE THREAD

**Issue by LightCannon** [qutebrowser/qutebrowser#7423]
**Version info**:

Using latest release

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
The problem is that Cloudflare service is not allowing any QtWebEngine-based browser to pass. Visiting https://dash.cloudflare.com/login and clicking verify when appears get me in infinite failure of verification. 

I believe that the issue that the internal web engine is not sending (or having) the client hints which should be available using "navigator.userAgentData". userAgentData is available for normal browsers (you can check from chrome dev tools) while if I attach a debugger and try navigator.userAgentData, I get empty fields. Setting just http useragent and http headers seems not enough.

So the question is, How can modify the userAgentData for the underlying QtWebEngine so that it returns values as normal working browser.
I'm aware of the useragent "cloudflare 503 workaround" which works, but not with everything.

**How to reproduce**
 https://dash.cloudflare.com/login

**Comment by The-Compiler** [comment]
That's a problem with Cloudflare, not qutebrowser - see #7208.

For the empty `userAgentData`, I opened a bug upstream: [[QTBUG-107260] navigator.userAgentData support - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-107260). We could possibly override it by injecting JS, see #6464.

That's what you could possibly do as well, using qutebrowser's greasemonkey support to patch (or replace) the attribute.

**Comment by LightCannon** [comment]
How can I inject JS to execute before any request is sent? What I need is having these overridden values ready before any request is done, so when website requires them, they be already present. I prefer if there is a way using the WebEngine api itself. So any help or direction is highly appreciated.
