### ISSUE TITLE
consistently crashes on github login using qt 6.4

### ISSUE THREAD

**Issue by nrdxp** [qutebrowser/qutebrowser#7424]
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 6.4, based on Chromium 98.0.4758.90 (from override)
Qt: 6.4.0
built from latest qt6-v2 branch and nixos/nixpkgs#194833

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Every time I successfully login to github, qutebrowser crashes with a segfault. I captured it on the cli and pasted the results.

**How to reproduce**
build the package from the above PR, or from qt6-v2 with qt6 6.4 as the backend.
Go to github
login
on successful login the browser will crash
[seg.log](https://github.com/qutebrowser/qutebrowser/files/9729804/seg.log)

This happened enough times that I got temporarily locked out of my github account for logging in to many times. I have to fill out this issue from Chromium since I still can't use it on qutebrowser as I normally do.

cc @LunNova, in case you notice anything obious on the Nix side.

**Comment by toofar** [comment]
I'm gonna assume this is the same as #7422 and close as a duplicate (and upstream issue).
Not sure if there is a new tag upstream since it was only fixed recently but the patch is pretty small!

> This happened enough times that I got temporarily locked out of my github account

:sob:

**Comment by nrdxp** [comment]
@toofar, thank you. After applying the patch I can confirm that that was the issue.
