### ISSUE TITLE
There's no search_match value for statusbar.widgets

### ISSUE THREAD

**Issue by Pound-Hash** [qutebrowser/qutebrowser#7438]
**Version info**:
```
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.6
```

**Description**
The docs say that `search_match` is a possible value for the setting `statusbar.widgets` (indeed, that it's a default), but this value doesn't take.

**How to reproduce**
Enter a value of `["search_match"]` in the setting for `statusbar.widgets`. Receive error.

**Comment by The-Compiler** [comment]
That addition didn't make it into a release yet. I'd recommend you use `:help` to view the docs, as you'll get the docs for the version you are running.
