### ISSUE TITLE
Unable to Create Context

### ISSUE THREAD

**Issue by Moncheeta** [qutebrowser/qutebrowser#7440]
**Version info**: 
```
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.5

CPython: 3.10.6
PyQt: 5.15.7

sip: 6.6.2
colorama: no
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: 0.6.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: 2.14.305 (/nix/store/9jbpp3148y5vhykmq0rmdwlpk7xq7ng8-source/build/pdf.js)
sqlite: 3.39.2
QtNetwork SSL: OpenSSL 1.1.1q  5 Jul 2022

Style: QFusionStyle
Platform plugin: wayland
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 515.65.01
Platform: Linux-5.19.8-x86_64-with-glibc2.35, 64bit
Linux distribution: NixOS 22.11 (Raccoon) (nixos)
Frozen: False
Imported from /nix/store/6fg3p79j30g7s68i26qgz37kap8z819n-qutebrowser-2.5.2/lib/python3.10/site-packages/qutebrowser
Using Python from /nix/store/c1vb2z3c64i0sd92iz7fv0lb720qcvhb-python3-3.10.6/bin/python3.10
Qt library executable path: /nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5/libexec, data path: /nix/store/dmj5kndgbkr2p159wsjw15551da5r70p-qtbase-5.15.5

Paths:
cache: /home/moncheeta/.cache/qutebrowser
config: /home/moncheeta/.config/qutebrowser
data: /home/moncheeta/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /nix/store/6fg3p79j30g7s68i26qgz37kap8z819n-qutebrowser-2.5.2/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/moncheeta/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:37
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
After starting my wayland desktop environment, I launch qutebrowser and this is qutebrowser's output from the terminal.
``
[2668:2703:1017/133354.002615:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT
[2668:2703:1017/133354.002630:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
[2668:2703:1017/133354.002634:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[2668:2703:1017/133354.002639:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
``
Those 4 log messages print repetitively until I force quit the application.

**How to reproduce**
1. Open qutebrowser from the terminal(to see the log messages) on a wayland desktop environment.

**Comment by Moncheeta** [comment]
I have switched from x11 to wayland, but that is it. I forgot to mention that I have a GTX 1650 Super graphics card, since that might be related to the issue. 

I have also tried KDE Falkon, but running it resulted in the same output in the terminal. Now that I have thought about it, could it just be an issue regarding with QT applications on wayland?

**Comment by toofar** [comment]
Do you have anything still in the `qt.args` setting left over from when you where on X11. I'm seeing a few similar (but not quite the same) errors related to hardware acceleration on Wayland (eg https://bugs.chromium.org/p/chromium/issues/detail?id=1125485).
There's a couple like this but nothing with a solution (beyond using XWayland): https://github.com/jellyfin/jellyfin-media-player/issues/165 and https://old.reddit.com/r/Calibre/comments/xqwah0/error_running_ebookviewer_on_ubuntu_2204/

Maybe ask on IRC if anyone else is running with the nvidia proprietary codecs (I'm assuming you are) and pure wayland.

**Comment by Moncheeta** [comment]
I have been experimenting around and I have found out that I have to use software rendering. The browser will not print any errors if you set ``force_software_rendering`` to ``chromium`` or ``qt-quick``. Having the option set to ``none`` or ``software-opengl`` with continue to print out the error messages.

**Comment by Nagefire** [comment]
I'm seeing similar errors, but the messages stop as soon as I open a second window and qutebrowser works normally. Can anyone else confirm this behavior?

**Comment by JMTK** [comment]
FWIW, this ended up being a red herring for me and I just needed to ensure that my `.Xauthority` was in the `~/` of the **user I was currently running as** when I was ssh'd and running these commands
