### ISSUE TITLE
Issue with Certificates erroring out behind PiHole DNS

### ISSUE THREAD

**Issue by LinuxMeow** [qutebrowser/qutebrowser#7462]
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.11, based on Chromium 87.0.4280.144
Qt: 5.15.7 (compiled 5.15.6)

CPython: 3.10.8
PyQt: 5.15.7

sip: 6.6.2
colorama: no
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.39.4
QtNetwork SSL: OpenSSL 1.1.1q  5 Jul 2022

Style: QFusionStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.2.1
Platform: Linux-6.0.6-arch1-1-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/nonroot/.cache/qutebrowser
config: /home/nonroot/.config/qutebrowser
data: /home/nonroot/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/nonroot/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00

**Does the bug happen if you start with `--temp-basedir`?**:
- Yes the bug occurs.

**Description**
There is an issue when using qutebrowser with network set to use pihole as dns resolver.

Websites continue throwing invalid certificate popups constantly, and upon further inspection I realised that each error was trying to obtain certificate which is in pihole block list.

It is normal to not be able to get valid certificate from domains blocked by pihole cause requests to blocked domain where certificate is are never sent out of the local network. But at least some work around is needed cause this problem doesn't appear in other browsers. qutebrowser becomes absolutely unusable when every 5 seconds you need to deal with certificate error popup.

**How to reproduce**
By using qutebrowser on a network that is using pihole as the only dns server on the network configured, then visiting some of the domains that are indirectly blocked. Adding few lists from [https://firebog.net/](https://firebog.net/) to pihole to increase chance of hitting the blocked domain.

Error was not reproduced by going to blocked domain itself. But the page was trying to pull certificate from a blocked one.

Example:

- Page visited: [https://duckduckgo.com](https://duckduckgo.com)
- Error:

![image](https://user-images.githubusercontent.com/50368002/199786849-9b29dfed-b70c-4f65-9722-3bfeadd6bff9.png)

I am aware that I can edit config.py with the thing mentioned in the popup itself but I don't know how smart that is. Cause there might be cases where the error is legitimate, can cause unencrypted browsing without any warning being shown.

**Comment by The-Compiler** [comment]
Contrary to other browsers, qutebrowser will warn you when subresources of a page can't be loaded. If you want to silently block those loads silently like other browsers do, setting the setting to `ask-block-thirdparty` is indeed the right thing to do. Like the setting name says, this blocks those requests, so no "unencrypted browsing without any warning being shown" will happen.

**Comment by LinuxMeow** [comment]
I was not aware of that I apologise. Thank you for quick response as well.
