### ISSUE TITLE
Add Tor Onion-Location Header & Meta Tag Support

### ISSUE THREAD

**Issue by hendursaga** [qutebrowser/qutebrowser#7476]
In the Tor Browser Bundle and other browsers like Brave, if the admin configures the web server to add a Onion-Location HTTP header, you have the option to redirect to the onion version of the site. In case the hosting site can't / won't add a non-standard header like that, there's also the option to add a tag. [See the full spec](https://gitweb.torproject.org/tor-browser-spec.git/plain/proposals/100-onion-location-header.txt) for more details there.

**Comment by The-Compiler** [comment]
qutebrowser doesn't have a way to access response headers: https://bugreports.qt.io/browse/QTBUG-61071

Perhaps you could do something in JS via its Greasemonkey support.
