### ISSUE TITLE
Problems with substack profile pages

### ISSUE THREAD

**Issue by intuser** [qutebrowser/qutebrowser#7480]
**Version info**:

qutebrowser v2.5.2
Git commit: d1e653115 on master (2022-07-12 17:29:57 +0200)
Backend: QtWebEngine 5.12.8, based on Chromium 69.0.3497.128
Qt: 5.12.8

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

If I visit the profile page of a substack  under the substack.com address I don't see the posts section: Either the section is simply missing or I see the heading or the section and below a eternally spinning wheel.

If I visit the website of the substack I see a page which invites me to subscribe but offers a link saying: "Let me read it first >". Clicking on that link doesn't effect anything.

**How to reproduce**

Visit https://substack.com/profile/253367-alison-roman  -- results in a webpage either without the "Posts" section or a spinning wheel below the section header.

Visit https://anewsletter.alisoneroman.com/ -- results in a webpage with a non working link "Let me read it first >"

**Comment by toofar** [comment]
Are you seeing any javascript errors in the console in :devtools? Both those use cases work fine for me in webengine 5.15.10 and 6.3.3.

**Comment by intuser** [comment]
In the console of :deftools I see the following error:

"Failed to load resource: net::ER0R_BLOCKED_BY_CLIENT reader2.bundle.js:1 Uncaught SyntaxError: Unexpected token ?"

**Comment by intuser** [comment]
That's visiting https://substack.com/profile/253367-alison-roman

**Comment by The-Compiler** [comment]
This is due to you using Qt 5.12, which is based on an older Chromium 69, apparently too old to understand the JS code used by that website. Works fine in qutebrowser with Qt 5.15. Nothing qutebrowser can do to fix this with older Qt versions, I'm afraid.

**Comment by jkozak** [comment]
I get essentially the same problem (ERR_BLOCKED_BY_CLIENT for beacon.min.js and two other js files) showing the above symptoms with this version:

```
qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

CPython: 3.12.4
PyQt: 6.7.0.dev2404081550

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.7.12
pdf.js: 4.2.67 (/nix/store/0zyi17008m7aj74w6lr1skachnqjyzrx-source/build/pdf.mjs)
sqlite: 3.45.3
QtNetwork SSL: OpenSSL 3.0.14 4 Jun 2024

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 24.1.2
Platform: Linux-6.6.41-x86_64-with-glibc2.39, 64bit
Linux distribution: NixOS 24.11 (Vicuna) (nixos)
Frozen: False
Imported from /nix/store/dvlvqqbyhw5nabi5n9wgy8ax6drvnbzc-qutebrowser-3.2.1/lib/python3.12/site-packages/qutebrowser
Using Python from /nix/store/m22r7gsvm4w3ib3y2jcsnx0l7mis050q-python3-3.12.4-env/bin/python3.12
Qt library executable path: /nix/store/52di98lwpsnbwdkyls2ccfh2jv9rs45f-qtbase-6.7.2/libexec, data path: /nix/store/52di98lwpsnbwdkyls2ccfh2jv9rs45f-qtbase-6.7.2

Paths:
cache: /home/jk/.cache/qutebrowser
config: /home/jk/.config/qutebrowser
data: /home/jk/.local/share/qutebrowser
runtime: /run/user/2001/qutebrowser
system data: /nix/store/dvlvqqbyhw5nabi5n9wgy8ax6drvnbzc-qutebrowser-3.2.1/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/jk/.config/qutebrowser/config.py has been loaded
Uptime: 3 days, 18:02:17
```
