### ISSUE TITLE
dictcli.py cannot list/download spellcheck dictionaries

### ISSUE THREAD

**Issue by 6b6279** [qutebrowser/qutebrowser#7481]
**Version info**:
https://paste.the-compiler.org/view/7daa72da

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
`dictcli.py` fails to download spellcheck dictionaries off Google’s hunspell repository. This is due to the fact that the active branch of the repository was recently renamed to `main`, but `dictcli.py`  looks for the `master` branch.

**How to reproduce**
1. Execute `/usr/share/qutebrowser/scripts/dictcli.py list`. The Python script crashes with `HTTPError` "404: Not Found".

**Comment by The-Compiler** [comment]
Indeed, thanks for the detailed report!
