### ISSUE TITLE
Green video with VP9 encoded from GIFs

### ISSUE THREAD

**Issue by Jaegrqualm** [qutebrowser/qutebrowser#7483]
**Version info**:
qutebrowser v2.5.2
Git commit: 1417ffa51 on makepkg (2022-11-19 16:01:12 +0100)
Backend: QtWebEngine 5.15.11, based on Chromium 87.0.4280.144
Qt: 5.15.6

CPython: 3.10.8
PyQt: 5.15.7

sip: 6.6.2
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: 0.6.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: yes
objc: no
pdf.js: no
sqlite: 3.39.4
QtNetwork SSL: OpenSSL 1.1.1q  5 Jul 2022

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.2.1
Platform: Linux-6.0.2-arch1-1-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 0:06:30

**Does the bug happen if you start with `--temp-basedir`?**:
 No

**Description**
Video that is mostly green. Only seems to happen with VP9 video converted from GIFs. Screenshot: 
![image](https://user-images.githubusercontent.com/13362074/202885116-5e023e55-71cb-44b0-94c6-a61a3af7b834.png)
**How to reproduce**
Load this webm:
[noitavp9.webm](https://user-images.githubusercontent.com/13362074/202885158-ca56410d-48dc-4468-bfe4-656994ecbd17.webm)
the same webm, encoded with VP8:
[noitavp8.webm](https://user-images.githubusercontent.com/13362074/202885163-0ced175f-1f67-4d08-a21d-c1235b2254fd.webm)

Comparing against a different gif in VP9:
[koburavp9.webm](https://user-images.githubusercontent.com/13362074/202885278-692400ad-509c-4cfd-9a73-38216be7a50b.webm)
(the first time I loaded this one, I don't think it was green. very strange.)

VP8:
[koburavp8.webm](https://user-images.githubusercontent.com/13362074/202885285-19f1b590-4802-4b4c-8982-3c04d30ad9ab.webm)

Random VP9 videos work.

The command used to encode all of them:
`ffmpeg -i "input.gif" -vf "scale=1280:-1:flags=neighbor,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -c:v libvpx-vp9 -b:v 2M output.webm`

the source GIFs
Noita:
(can't post it, no one wants to host a GIF over 20MB)
space cobra:
![kobura  sound=a pomf cat%2Fjsbdjs m4a](https://user-images.githubusercontent.com/13362074/202885224-d8e6102b-8a5a-4145-841e-b4cfc56fc02e.gif)

I haven't the slightest clue what in my config could be causing this. I believe I've been using and modifying the same configs for quite a few years now.

**Comment by The-Compiler** [comment]
Looks fine to me. It's indeed weird that it wouldn't happen to you with `--temp-basedir`. Could you share your `:config-diff` please?

**Comment by Jaegrqualm** [comment]
Ahh, I believe I have it figured out. At some point I had been messing around with eGPUs and had enabled ` qt.force_software_rendering = chromium` to try and fix compatability with an Nvidia GPU. I couldn't tell you anymore if the same issue happens *with* an nvidia GPU, since that card has since died.

In any event, case closed, thank you.

**Comment by Jaegrqualm** [comment]
Ah, I suppose you could leave this open until it's figured out where the issue is with the software rendering, but I'll leave that up to you.

**Comment by The-Compiler** [comment]
I can reproduce this with software rendering indeed, but only on Qt 5, not on Qt 6. So I'm assuming this is a bug which got fixed in QtWebEngine/Chromium in the meantime!
