### ISSUE TITLE
With QT 6, Slack Huddle feature reliably triggers "Renderer process crashed (status 139)"

### ISSUE THREAD

**Issue by markstos** [qutebrowser/qutebrowser#7490]
**Version info**:

qutebrowser v2.5.2
Git commit: ca667d642 on makepkg (2022-11-20 16:15:06 +1300)
Backend: QtWebEngine 6.4.1, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.1 (compiled 6.4.0)

CPython: 3.10.8
PyQt: 6.4.0

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.0.279 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.40.0
QtNetwork SSL: OpenSSL 3.0.7 1 Nov 2022

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.2.3
Platform: Linux-6.0.8-arch1-1-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/mark/.cache/qutebrowser
config: /home/mark/.config/qutebrowser
data: /home/mark/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Slack has a  "Huddles" feature that reliably crashes the browser with "Renderer process crashed (status 139)". This worked before, but broke just a few days ago on Arch Linux, during regular updates. 

Logs show:

```
11:59:09 WARNING: Resource type ResourceTypeWebSocket not found in RequestInterceptor dict.
[67991:67991:1123/115939.760436:ERROR:pulse_util.cc(345)] pa_operation is nullptr.
11:59:42 ERROR: Renderer process crashed (status 139)
```

**How to reproduce**

In the Slack web app, try to start or join a huddle. I believe this may be available on free plans.

**Comment by The-Compiler** [comment]
Reported upstream: [[QTBUG-108901] [REG 6.4.0 -> 6.4.1] Renderer process crash when starting slack huddle - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-108901)

**Comment by alexhraber** [comment]
FYI I'm seeing these exact 139's when going to gmail and youtube, among other sites. I've also passed a message over to that Qt tracker ticket linked above.

Long time user, love the project. <3

**Comment by alexhraber** [comment]
cc @The-Compiler (just in case you don't get updates for closed issues)

**Comment by toofar** [comment]
@alexhraber it's likely something to do with your setup, as those sites are working fine for other people. Things to try:

* start from a terminal with `--temp-basedir` and see if it still crashes
    * if not then try moving your webengine cache folder out of the way and see if that fixes your main instance
* run with `-s qt.chromium.process_model single-process` so that it will crash the whole browser when a tab crashes and collect a stack trace as explained here: https://qutebrowser.org/doc/stacktrace.html

**Comment by The-Compiler** [comment]
I do get updates for closed issues, but whatever you're seeing there is unrelated to both this issue, and the Qt issue you commented on. Please try what @toofar suggested, and then consider opening a new issue (if reproducible with `--temp-basedir`) or a new discussion (if not).
