### ISSUE TITLE
Under Ubuntu 22.04 no longer possible to copy to clipboard by highlighting

### ISSUE THREAD

**Issue by intuser** [qutebrowser/qutebrowser#7492]
**Version info**:
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

Under Ubuntu 20.04 I could copy text from qutebrowser to the clipboard by simply highlighting it. Moving to 22.04 this is no longer possible: Only using additionally Crtl+C works. I use diodon (gnome) with "Use primary selection" selected.

At least one other program has a very similar problem (libreoffic). Other programs (like firefox) work well. I also tried gpaste. But if I enable "Synchronize clipboard with primary selection" every intermediate step is put into the clipboard. (Example: Highlighting "Then" I would have "T", "Th", "The", and "Then" in the clipboard. Clearly not what I want.)

**How to reproduce**

Using qutebrowser under Ubuntu 22.04 visit any webpage. Highlight some text. Nothing is put into the diodon clipboard. Use gpaste without "Synchronize clipboard with primary selection" enabled: Nothing is put into the clipboard. Enable the last option: Every intermediate step of the process of hightlighting is put into the clipboard.

**Comment by The-Compiler** [comment]
This doesn't sound like a qutebrowser issue. Can you try with another browser based on QtWebEngine, such as KDE Falkon?

**Comment by intuser** [comment]
I tested KDE Falkon and it has the same problem. Would this indicate, that it is possibly a QtWebEngine issue and would a bug report there be helpful?

**Comment by The-Compiler** [comment]
The next thing I'd try is e.g. the UI of qutebrowser (e.g. the command bar). If it happens there too, that'd point to a generic Qt thing, not QtWebEngine. Or perhaps something Gnome specific? Or something on your system? I have no idea.
