### ISSUE TITLE
Request redirect not working for Twitter

### ISSUE THREAD

**Issue by BanchouBoo** [qutebrowser/qutebrowser#7496]
**Version info**:
http://p.cmpl.cc/d5139792

**Does the bug happen if you start with `--temp-basedir`?**:
Not applicable; `config.py` required

**Description**:
I have the following block of code in my `config.py`

```python
import os
import re
from qutebrowser.api import interceptor

twitter_regex = re.compile('https://twitter.com/.+/status/.+')
fandom_regex = re.compile('https://.+.fandom.com/wiki/.*')
def intercept(request: interceptor.Request):
    if request.request_url.hasQuery() and twitter_regex.match(request.request_url.url()) != None:
        new_url = request.request_url
        new_url.setQuery(None)
        try:
            request.redirect(new_url)
        except:
            pass
        os.system('notify-send "' + request.request_url.url() + '"')
    elif fandom_regex.match(request.request_url.url()) != None:
        new_url = request.request_url
        new_url.setHost(new_url.host().replace("fandom.com", "breezewiki.com"))
        try:
            request.redirect(new_url)
        except:
            pass
# clear out so it's not double-registered when reloading config.py
interceptor.interceptors._interceptors.clear()
interceptor.register(intercept)
```

The second redirect for fandom works fine, but the one for twitter does not. the `os.system` call is triggered and it shows the proper url with the query stripped. I also tried redirecting it to a completely new domain (nitter.net) just to see if maybe there was a problem with redirecting on the same domain or same page but that also didn't do anything.

**How to reproduce**:
Using the above code, load a tweet that has a query in the url (e.g. https://twitter.com/rileypneville/status/1595331637822115840?t=ZB3Qk8tFU-nppSi2ZB2qvA&s=19)

**Comment by The-Compiler** [comment]
What if you remove the `except: pass`? Note that this isn't a public/supporter API in any case.

**Comment by BanchouBoo** [comment]
Same results

**Comment by The-Compiler** [comment]
Works fine for me. Can you please try with `--temp-basedir --config-py c.py` with `c.py` being exactly the file above?

**Comment by BanchouBoo** [comment]
Trying that did work. This also made me experiment a bit more. It also works with my full config if I open in a private window so I tried logging out but that didn't fix it. In any case, this is clearly some problem with my specific setup so I'll close the issue, but if you have any ideas that could help me narrow it down I'd still like to hear them.

**Comment by The-Compiler** [comment]
If removing the `except: pass` doesn't raise an error, I'm afraid I have no idea what the culprit would be. All qutebrowser does is telling QtWebEngine to do the redirect, which in turn passes it to the underlying Chromium I believe.

**Comment by BanchouBoo** [comment]
Alright, thanks for trying.
