### ISSUE TITLE
Qb always crashes at google login page

### ISSUE THREAD

**Issue by jcguu95** [qutebrowser/qutebrowser#7503]
**Version info**:
```
qutebrowser v2.5.2
Git commit: 951a14a66 on HEAD (2022-06-22 15:30:51 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.5.1
colorama: 0.4.4
jinja2: 3.1.1
pygments: 2.11.2
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.14.305 (bundled)
sqlite: 3.33.0
QtNetwork SSL: Secure Transport, macOS 10.16

Style: QMacStyle
Platform plugin: cocoa
OpenGL: None
Platform: macOS-10.16-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt5/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt5
OS Version: 10.16, x86_64

Paths:
auto config: /Users/jin/Library/Preferences/qutebrowser
cache: /Users/jin/Library/Caches/qutebrowser
config: /Users/jin/.qutebrowser
data: /Users/jin/Library/Application Support/qutebrowser
runtime: /private/var/folders/_r/7t23dmhd0vx04btf5sx151tw0000gn/T/qutebrowser

Autoconfig loaded: no
Config.py: /Users/jin/.qutebrowser/config.py has been loaded
Uptime: 0:00:52
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

One of my google account expired and started to ask me login
again in qutebrowser. However, whenever the google login page is
brought up, qb crashes (100% reproducible for several times).

This happens with `--temp-basedir` too.

With qutebrowser launched from the terminal, I capture the error
messages from stderr between the moment I attempted to go to
google login page and the moment it crashes:

```
objc[61249]: Class QMacAutoReleasePoolTracker is implemented in both /Applications/qutebrowser.app/Contents/MacOS/QtCore (0x112b32198) and /Applications/qutebrowser.app/Contents/Resources/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x10cb77198). One of the two will be used. Which one is undefined.
objc[61249]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Applications/qutebrowser.app/Contents/MacOS/QtCore (0x112b32210) and /Applications/qutebrowser.app/Contents/Resources/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x10cb77210). One of the two will be used. Which one is undefined.
objc[61249]: Class KeyValueObserver is implemented in both /Applications/qutebrowser.app/Contents/MacOS/QtCore (0x112b32238) and /Applications/qutebrowser.app/Contents/Resources/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x10cb77238). One of the two will be used. Which one is undefined.
objc[61249]: Class RunLoopModeTracker is implemented in both /Applications/qutebrowser.app/Contents/MacOS/QtCore (0x112b32288) and /Applications/qutebrowser.app/Contents/Resources/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x10cb77288). One of the two will be used. Which one is undefined.
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
2022-12-01 17:35:53.704 qutebrowser[61235:10024413] -[IOBluetoothDeviceInquiry initWithDelegate:] -  0x60000792d130
/opt/homebrew/bin/qutebrowser: line 2: 61235 Abort trap: 6           '/Applications/qutebrowser.app/Contents/MacOS/qutebrowser' "$@"
```

**How to reproduce**

1. Launch qb.
2. Get to google log in page.
3. Qb crashes.

**Comment by The-Compiler** [comment]
Works fine here, though I can only test on macOS 10.14.

Could you try with the [release .dmg](https://github.com/qutebrowser/qutebrowser/releases/tag/v2.5.2) opened manually rather than installing via brew (or brew cask)?

**Comment by jcguu95** [comment]
Thanks for reaching out. Actually, I just found a very weird work-around. 

Another [issue](https://github.com/qutebrowser/qutebrowser/issues/7334) I raised is still unsolved. My workaround for that is to always launch qutebrowser from my terminal, explicitly with `$ qutebrowser`. With this approach, that issue _never_ showed up again.

However, the side-effect is the issue in this thread. I just found that if I don't launch qb explicit from my terminal, opening a google login page doesn't cause any problem.

**Comment by The-Compiler** [comment]
This is macOS killing qutebrowser because your Terminal does not have Bluetooth permissions (why does Google log-in need those? Ask Google...) - see #6475 and [Chromium Docs - Debugging Chromium on macOS: System Permission Prompts; Transparency, Consent, and Control (TCC)
](https://chromium.googlesource.com/chromium/src/+/main/docs/mac/debugging.md#system-permission-prompts_transparency_consent_and-control-tcc)
