### ISSUE TITLE
Smooth scrolling seems to not work on MacOS Monterey 12.5.1

### ISSUE THREAD

**Issue by augustebaum** [qutebrowser/qutebrowser#7514]
**Version info**:

qutebrowser v2.5.2
Git commit: 951a14a66 on HEAD (2022-06-22 15:30:51 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
No -- then I get the behaviour described in #6840.
This is most likely due to my custom `j` and `k` commands:
```
"j": "scroll-px 0 50",
"k": "scroll-px 0 -50",
```

**Description**
Setting or unsetting the `scrolling.smooth` option does nothing; the scrolling is always non-smooth.

**How to reproduce**

See the following screen capture. Sorry about the poor quality, GitHub wouldn't allow any better...

https://user-images.githubusercontent.com/52001167/206727004-d53a00d4-db5d-4684-a57f-9dcd49b5e9bb.mov

**Comment by The-Compiler** [comment]
This is [expected](https://qutebrowser.org/doc/help/settings.html#scrolling.smooth), and not something macOS-specific:

> Note smooth scrolling does not work with the `:scroll-px` command.

All we do is passing the setting to the underlying QtWebEngine, which in turn passes it to Chromium - so this is something which would need to be changed there.

Maybe doing scrolling via JS (#3691) will help, but other than that, there's nothing we can do about this.
