### ISSUE TITLE
Amazon prime video says a later version of google chrome is required

### ISSUE THREAD

**Issue by vikasrawal** [qutebrowser/qutebrowser#7517]
**Version info**:

qutebrowser v2.5.2
Git commit: f396c6fe6 on master (2022-12-06 17:06:56 +0100)
Backend: QtWebEngine 5.15.11, based on Chromium 87.0.4280.144
Qt: 5.15.6

CPython: 3.10.8
PyQt: 5.15.7

sip: 6.6.2
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: yes
objc: no
pdf.js: no
sqlite: 3.39.4
QtNetwork SSL: OpenSSL 1.1.1q  5 Jul 2022

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

When I try to play any video on primevideo.com, I get a message "A later version of Google Chrome is required for Prime Video..."

This is a new problem apparently because the website has stop supporting earlier versions of Google Chrome.

Is there a possibility that qutebrowser will be upgraded in near future?

**How to reproduce**

https://www.primevideo.com

**Comment by The-Compiler** [comment]
A newer QtWebEngine will come with a newer Chromium - we're in a special situation right now, since there will be no more Chromium updates in Qt 5.15, but we're still working on finishing support for Qt 6. See #7202.
