### ISSUE TITLE
Qt6: mouse scrolling doesn't work after suspend until qb is restarted

### ISSUE THREAD

**Issue by twouters** [qutebrowser/qutebrowser#7523]
**Version info**:
qutebrowser v2.5.2
Git commit: 0941c59c3 on makepkg (2022-12-13 09:43:08 +0100)
Backend: QtWebEngine 6.4.1, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.1 (compiled 6.4.0)

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Mouse scrolling breaks after suspend.

Note: this is a bug in QT, I guess this report is more of an FYI. See https://bugreports.qt.io/browse/QTBUG-56214

**How to reproduce**
Use qutebrowser qt6-v2 branch with a bluetooth mouse or a usb mouse indirectly connected (dock / monitor / whatever) and suspend your machine. After resuming it's probably no longer possible to scroll using your mouse wheel until you restart qutebrowser with e.g. `:restart`.

**Comment by The-Compiler** [comment]
Ah, I had that happen to me as well (mentioned in #7202), but never got around to digging into it. Great to hear it's known and hopefully getting fixed in Qt... Thanks for the pointers!

Closing this though, as it doesn't seem that there's anything qutebrowser could do about it.

**Comment by The-Compiler** [comment]
Looks like there is finally a fix for this in Qt: https://codereview.qt-project.org/c/qt/qtbase/+/467903

**Comment by crashr** [comment]
Strange. This happened to me yesterday after a bumpy upgrade from Ubuntu 22.04 to 24.04, a 

```
./scripts/mkvenv.py --pyqt-type=link
```

and installation of the following packages:

```
$ apt policy python3-pyqt6 python3-pyqt6.qtqml python3-pyqt6.qtwebengine 2>/dev/null| grep -B1 Installed
python3-pyqt6:
  Installed: 6.6.1-2build4
--
python3-pyqt6.qtqml:
  Installed: 6.6.1-2build4
--
python3-pyqt6.qtwebengine:
  Installed: 6.6.0-1build2
```

Today I wanted to make a quick note of this here, but suddenly the problem is gone.
