### ISSUE TITLE
Private reporting of a security vulnerability

### ISSUE THREAD

**Issue by Sim4n6** [qutebrowser/qutebrowser#7524]
Dear qutebrowser team,

I may have identified a security vulnerability in the codebase of the latest version of qutebrowser and I would like to report it privately. Could you please opt-in to the Github private reporting [feature](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability).

Kind consideration
@Sim4n6

**Comment by Sim4n6** [comment]
![image](https://user-images.githubusercontent.com/13036531/207326782-21e6e70e-aa2b-4744-9901-f48778279032.png)

**Comment by The-Compiler** [comment]
Done. Note that you could also just have sent an email though, as outlined in the [security policy](https://github.com/qutebrowser/qutebrowser/security/policy).

**Comment by Sim4n6** [comment]
perfect

**Comment by Sim4n6** [comment]
It is a false positive. Sorry about that.

**Comment by The-Compiler** [comment]
No worries, thanks for reaching out! Mind sharing the details anyways? I'd be happy to take a closer look to ensure there's indeed nothing to worry about.

**Comment by Sim4n6** [comment]
Quickly ... 

```python3
        version = 'v' + target_version
        suffix = "-legacy" if legacy else ""
        url = ('https://github.com/mozilla/pdf.js/releases/download/'
               f'{version}/pdfjs-{target_version}{suffix}-dist.zip')

    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          '..', '..'))
    target_path = os.path.join('qutebrowser', '3rdparty', 'pdfjs')
    print(f"=> Downloading pdf.js {version}{' (legacy)' if legacy else ''}")
    try:
        (archive_path, _headers) = urllib.request.urlretrieve(url)
    except urllib.error.HTTPError as error:
        print("Could not retrieve pdfjs {}: {}".format(version, error))
        return
    if os.path.isdir(target_path):
        print("Removing old version in {}".format(target_path))
        shutil.rmtree(target_path)
    os.makedirs(target_path)
    print("Extracting new version")
    shutil.unpack_archive(archive_path, target_path, 'zip')
```
shutil.unpack_archive() is vulnerable to a recent TarSlip. Which becomes something to worry about if the tarball is retrieved from a remote location. However, in here first it is a zip archive and the URL is hardcoded.

Happy to help but it is a false positive. You know.
@Sim4n6

**Comment by The-Compiler** [comment]
Agreed - we'll need to trust the source of that anyways, we'd have bigger problems if there was anything malicious there.

Thanks for having a look though, and if nothing else, we got the GitHub reporting enabled and [better security reporting guidelines](https://github.com/qutebrowser/qutebrowser/commit/9bf258c8f8fa2c255be92535a64fd356146d8482) out of it :+1:

**Comment by Sim4n6** [comment]
Thx
