### ISSUE TITLE
Unable to login on SOGo instances

### ISSUE THREAD

**Issue by wiegandm** [qutebrowser/qutebrowser#7542]
**Version info**:

qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.6

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

With recent versions of the SOGo groupware web interface, logging in with qutebrowser no longer works. Instead, the user is returned to the login page. This occurs both with PyQt5 as stated above, but also with the `qt6-v2` branch. This does not occur in Chromium or any other browser I have tried.

**How to reproduce**

1. Open https://demo.sogo.nu/SOGo/ in qutebrowser
2. Use one of the demo accounts mentioned on https://www.sogo.nu/ (e.g. `sogo1`) with the password `sogo`

**Expected behavior**: After displaying a "Welcome sogo1" message, the user should see the SOGo groupware web interface, opened on the "Mail" component.
**Actual behavior**: After displaying a "Welcome sogo1" message, the user is returned to the login page with the URL `https://demo.sogo.nu/SOGo/so/sogo1`.

**Comment by The-Compiler** [comment]
Works fine for me on Qt 6 (though not Qt 5) - most likely this isn't a qutebrowser issue though.

Can you please try with `--temp-basedir` on `qt6-v2` and show your `:version` info from there too?

**Comment by The-Compiler** [comment]
Ah, it works with Qt 6.4 only.

I can reproduce with the corresponding Chromium versions too. Running `python tools/bisect-builds.py -a linux64 -g 102.0.5005.61 -b 94.0.4606.71 --use-local-cache --verify-range -- --no-first-run --user-data-dir=/tmp 'https://demo.sogo.nu/SOGo/'` leads to:

> You are probably looking for a change made after 918171 (known bad), but no later than 918207 (first known good).
> CHANGELOG URL:
>  https://chromium.googlesource.com/chromium/src/+log/1c0ac6189b74ca9c7d5d37dfbf2c356be62290d9..5b6162074fcd66782c51ee8024ce7d8fbf814899

So something on that website requires a corresponding Chromium version and doesn't work properly with older ones. Nothing qutebrowser can do about that, I'm afraid.

**Comment by The-Compiler** [comment]
I got curious and found the exact culprit, it's this: [Implement cookie size checks from RFC - Pt. 1 (I3b4b6156) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/3104225)

Notably:

>    Chrome previously would reject the cookie line if it was greater
>    than 4096 characters. This has been replaced with a check that the
>    sum of the cookie name length and the cookie value length is not
>    greater than 4096, and that no attribute value has a length greater
>    than 1024.

And indeed, even with the current Chromium version, starting Chromium with `--disable-feature=ExtraCookieValidityChecks` to fall back to the old behavior causes the exact same issue.

**Comment by The-Compiler** [comment]
The value sent by the server is:

```
0xHIGHFLYxSOGo=[4053 bytes]; path=/SOGo/; secure; HttpOnly
```

I'm guessing what Chromium shows you there is the length of key + value, because `4053 + len("0xHIGHFLYxSOGo")` is exactly 4067. However, with the added `len("; path=/SOGo/; secure; HttpOnly")`, that's a total of 4098, thus too much for the old calculation (entire cookie line < 4096), but happens to fit with the new calculation (value length < 4096).
