### ISSUE TITLE
Some completions don't refresh correctly when opened

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#755]
a545b919f7f8b4383319c710ad948dca251e76ad added history loading after qutebrowser is already running, which works fine except a minor issue I don't know how to solve properly yet (and probably will look at after the completion cleanup in #74).

When the completion is opened (e.g. via `o`) after qutebrowser just started (and is still reading history from disk), the new items don't show up in the completion - they only show up when closing it and doing `o` again.

---

The tab completion (`:buffer`) also doesn't update correctly when a new window is opened while the completion is open. From #1444:

> When opening a new window while you already the tab completion open on one window a category is added for the new window but new rows in that category aren't picked up. Interesting if you open a third window then close the second window the completion display is now correct... I can see that the model is being updated correctly but I am not sure why that isn't propagating to the view. Not sure whether it is worth looking into (further) either.

**Comment by The-Compiler** [comment]
@rcorre #2295 will probably fix this, right?

**Comment by rcorre** [comment]
All history entries will be visible right from the start (in theory).
However, completions won't update in real-time while the menu is open, so `:buffer` will only show windows/tabs that were open at the time you opened the completion.

**Comment by The-Compiler** [comment]
As discussed elsewhere (I think), I think it's fine to not support that.
