### ISSUE TITLE
Userscripts: pass root window ID as environment variable

### ISSUE THREAD

**Issue by SuperDuperDeou** [qutebrowser/qutebrowser#7550]
It's not like you can right now, but it's way harder than it needs to be. If, for example, I want to embed a Dmenu window inside of Qutebrowser, I have to do something like this:

```
echo "foo" | dmenu -e "$(xdotool search --pid "$(ps -o ppid -p $$ --no-headers)" | sort -n | head -n 1 )"
```

Which is not very pretty.

**Comment by The-Compiler** [comment]
Seems like a good idea! Merging this into #937 however.
