### ISSUE TITLE
`:where` pseudo-selector is not supported

### ISSUE THREAD

**Issue by phenax** [qutebrowser/qutebrowser#7555]
**Version info**:
```
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.11, based on Chromium 87.0.4280.144
Qt: 5.15.7
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
Any css that uses `:where` pseudoselector ([mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/:where)) does not work. I'm guessing this might be an upstream issue but unsure exactly where to report this.

**How to reproduce**
- Most basic case: https://jsfiddle.net/vpjh3gf7/1/
- Real world example: https://docs.astro.build/en/getting-started/

**Comment by The-Compiler** [comment]
It was added in Chromium 88, so it's indeed not going to work with Qt 5.15 which is based on Chromium 87. It does however already work fine on the `qt6-v2` branch, see #7202.
