### ISSUE TITLE
Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by sharils** [qutebrowser/qutebrowser#7558]
Hello,

When I was browsing to http://wiki.c2.com/, it doesn't show the content and the developer console has `Uncaught SyntaxError: Unexpected reserved word`.

So I created the following minimised html snippet to replicate this error.
```
<script type=module>await 1</script>
```

Please let me know what else I should provide to replicate this error.

Thanks!

Here is my :version https://paste.the-compiler.org/view/4834dced

**Comment by toofar** [comment]
For me on `QtWebEngine 5.15.11, based on Chromium 87.0.4280.144` it also says `This site uses features not available in older browsers.`  on the web page and has a spinner.

Works fine on Qt6 `QtWebEngine 6.3.3, based on Chromium 94.0.4606.126`.

Not sure which versions of chrome started supporting this. I think this is the relevant MDN page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
So probably chome 91 based on that.

I'm not sure if there is anything you could do to polyfill this.

**Comment by The-Compiler** [comment]
Sounds like this one for me: [JavaScript operator: await: Use at module top level | Can I use... Support tables for HTML5, CSS3, etc](https://caniuse.com/mdn-javascript_operators_await_top_level)

Which got supported in Chromium 89. Nothing we can do to polyfill this unfortunately - indeed it works fine on Qt 6 though, see #7202 for details and how to try it.
