### ISSUE TITLE
Qutebrowser hangs trying to load Gitea websites

### ISSUE THREAD

**Issue by DavidRV00** [qutebrowser/qutebrowser#7560]
**Version info**:

qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.12, based on Chromium 87.0.4280.144
Qt: 5.15.8 (compiled 5.15.7)

**Does the bug happen if you start with `--temp-basedir`?**:
No it doesn't (but I have no idea what configuration issue could be causing this).

**Description**
Attempting to load a Gitea webpage (for example https://gitea.artixlinux.org/explore/repos ) results in the page loading stopping at ~80%, and the page freezes (ie doesn't allow clicking on any links or other page elements).

Opening htop shows qutebrowser and QtWebEngineProcess taking huge amounts of CPU while trying to load the page (although I have tried out another qtwebengine browser, falkon, and it does not do this).

I've also tried this on two different computers, both running artix linux, one of them a pretty fresh install.

I assume this issue is probably not specific to gitea but to some element of its UI architecture, but I'm not sure what.

**How to reproduce**

Open a gitea webpage (for example https://gitea.artixlinux.org/explore/repos ).

**Comment by The-Compiler** [comment]
Can you show your `:config-diff` please?

**Comment by DavidRV00** [comment]
Sure:

```
auto_save.interval = 300
bindings.commands = {"normal": {",B": "spawn --userscript qute-buku", ",M": "spawn mpv {url}", ",O": "spawn --userscript qute-bukuopen -t", ",R": "spawn getrss-youtube {url}", ",m": "spawn umpv {url}", ",o": "spawn --userscript qute-bukuopen", ",q": "spawn umpv-ctrl loadfile {url} append", ";M": "hint links spawn mpv {hint-url}", ";R": "hint links spawn getrss-youtube {hint-url}", ";m": "hint links spawn umpv {hint-url}", ";q": "hint links spawn umpv-ctrl loadfile {hint-url} append", ";s": "spawn passmenu -b ;; hint inputs", "xb": "config-cycle statusbar.show always never"}}
colors.hints.bg = #5f87d7
colors.hints.match.fg = #dfdfdf
colors.statusbar.caret.fg = #162023
colors.statusbar.insert.bg = #162023
colors.statusbar.insert.fg = #ee1033
colors.statusbar.normal.bg = #162023
colors.statusbar.normal.fg = #ffffff
colors.statusbar.url.fg = #5f87d7
colors.statusbar.url.success.https.fg = #5f87d7
colors.tabs.bar.bg = #162023
colors.tabs.even.bg = #162023
colors.tabs.even.fg = #dfdfdf
colors.tabs.indicator.start = #ffffff
colors.tabs.indicator.stop = #080808
colors.tabs.odd.bg = #162023
colors.tabs.odd.fg = #dfdfdf
colors.tabs.pinned.even.bg = #162023
colors.tabs.pinned.even.fg = #dfdfdf
colors.tabs.pinned.odd.bg = #162023
colors.tabs.pinned.odd.fg = #dfdfdf
colors.tabs.pinned.selected.even.bg = #5f87d7
colors.tabs.pinned.selected.even.fg = #161616
colors.tabs.pinned.selected.odd.bg = #5f87d7
colors.tabs.pinned.selected.odd.fg = #161616
colors.tabs.selected.even.bg = #5f87d7
colors.tabs.selected.even.fg = #161616
colors.tabs.selected.odd.bg = #5f87d7
colors.tabs.selected.odd.fg = #161616
colors.webpage.bg = #162023
colors.webpage.darkmode.enabled = true
editor.command = ["terminal", "-e", "nvim", "{}"]
fonts.statusbar = 10pt Ubuntu Mono
fonts.tabs.selected = 10pt Ubuntu Mono
fonts.tabs.unselected = 10pt Ubuntu Mono
hints.border = 1px solid #CDDDFA
input.insert_mode.auto_enter = true
input.insert_mode.auto_load = true
input.insert_mode.plugins = true
scrolling.smooth = true
search.incremental = false
statusbar.show = always
tabs.last_close = close
tabs.max_width = 200
tabs.mousewheel_switching = false
tabs.new_position.unrelated = next
tabs.padding = {"bottom": 1, "left": 5, "right": 5, "top": 1}
tabs.pinned.frozen = false
tabs.position = top
tabs.select_on_remove = last-used
tabs.show = multiple
tabs.title.format = {index}: {current_title}
url.default_page = ~/.config/qutebrowser/start.html
url.open_base_url = true
url.searchengines = {"!amazon": "https://smile.amazon.com/s?k={}", "!ebay": "https://www.ebay.com/sch/i.html?_nkw={}", "!google": "https://google.com/search?hl=en&q={}", "!maps": "https://maps.google.com/maps/search/{}", "!omaps": "https://www.openstreetmap.org/search?query={}", "!startpage": "https://startpage.com/do/search?query={}", "!thepiratebay": "https://thepiratebay.org/search.php?q={}", "!youtube": "https://www.youtube.com/results?search_query={}", "DEFAULT": "https://searx.be/search?q={}"}
url.start_pages = ~/.config/qutebrowser/start.html
```

**Comment by DavidRV00** [comment]
Little update:

I've tried copying my full config.py into a fresh basedir, and running from that basedir with `qutebrowser --basedir`. Doing this allows the gitea page to load; no hanging. So it seems like it's not necessarily caused by a configuration issue.

**Comment by The-Compiler** [comment]
Sorry for the radio silence, this one must have slipped through the cracks!

I don't think this is a qutebrowser issue - the QtWebEngine process is pretty much entirely under the control of the underlying QtWebEngine/Chromium.

What I'd suggest is that you start with copying the contents of `~/.local/share/qutebrowser` into `data/` in the basedir, and `~/.cache/qutebrowser` into `cache/`. That should reproduce the issue again. Then, you can try deleting folders in there until the issue goes away. My guess would be that the culprit is something in `data/webengine/`, which would further confirm that this isn't something qutebrowser can fix.

**Comment by DavidRV00** [comment]
Thanks for pointing me to those debugging steps!

I figured it out. It turned out I was doing something dumb in one of my greasemonkey scripts, so it's not Qutebrowser's fault nor QtWebEngine, luckily.

Thanks again; closing.
