### ISSUE TITLE
qutebrowser cannot play live videos

### ISSUE THREAD

**Issue by retrotechie** [qutebrowser/qutebrowser#7561]
**Version info**

qutebrowser v2.5.2
Git commit: 951a14a66 on HEAD (2022-06-22 15:30:51 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.5.1
colorama: 0.4.4
jinja2: 3.1.1
pygments: 2.11.2
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.14.305 (bundled)
sqlite: 3.33.0
QtNetwork SSL: Secure Transport, macOS 10.16

Style: QMacStyle
Platform plugin: cocoa
OpenGL: None
Platform: macOS-10.16-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt5/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt5
OS Version: 10.16, x86_64

Paths:
auto config: /Users/retrotechie/Library/Preferences/qutebrowser
cache: /Users/retrotechie/Library/Caches/qutebrowser
config: /Users/retrotechie/.qutebrowser
data: /Users/retrotechie/Library/Application Support/qutebrowser
runtime: /private/var/folders/44/gkhvgcys4651zns3_n64qrn40000gn/T/qutebrowser

Autoconfig loaded: no
Config.py: /Users/retrotechie/.qutebrowser/config.py has been loaded
Uptime: 0:04:06

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I realize qutebrowser cannot play live videos from Youtube or Stories on Facebook/Instagram. Specifically, live videos on Youtube are completely blank with **Your browser can't play this video**. In terms of Stories on Facebook/Instagram, most of them are blank but some are playable.  

**How to reproduce**
Open any live video on Youtube or follow this [link](https://www.youtube.com/watch?v=jfKfPfyJRdk)

**Comment by The-Compiler** [comment]
macOS binary releases come without proprietary codec support, since Qt binary releases don't include those. Also see #4127.

**Comment by Zik42** [comment]
Still exists... Any guideline on how to fix it?

**Comment by The-Compiler** [comment]
See the comment right above yours...

**Comment by Zik42** [comment]
I asked about guideline on how to compile qutebrowser with Qt on mac (arch 64) with proprietary code support.

**Comment by mschilli87** [comment]
The INSTALL file has information how to build from source and how to link to system wide libraries incl. PyQt. How to build PyQt with proprietory codec support on a proprietary operating system is something I wouldn't expect the qutebrowser devs to support me with for free but the support team of the propietory operating sytems I payed a lot of money. Or at least the PyQt support forums and not the qutebrowser issue tracker. Depending on your Macbook you might jsut be able to install Linux on it and follow the instructions provided for that OS. 😉

**Comment by Zik42** [comment]
Thank you for being so kind to answer, with good manners! I just wanted a way to use this awesome software, on my device. I don't know what I need to do, so it can play all videos on MacM1, so for now I will switch to other browser. 🙌

**Comment by mschilli87** [comment]
I use qutebrowser on Mac as well. I use the mpv userscript to open videos in mpv which I installed via homebrew and it can play all videos I need to, including youtube livestreams. Maybe that's a workaround for you as well. I just doubt that the qutebrowser devs without proper access to a Mac themselves will be able to help you. Maybe you can conince apple to give free access to their hardware for people developing 'awesome software' for their system for free. 🤷🏻
