### ISSUE TITLE
CSS doesn't load on some websites

### ISSUE THREAD

**Issue by azurelmao** [qutebrowser/qutebrowser#7564]
**Version info**:

qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.
**Description**
Either none or only some CSS loads on certain websites. I'm not sure if it has something to do on my end or if those websites are broken on qute.
On wikiless,
![image](https://user-images.githubusercontent.com/58854399/215107613-1feac5c0-299f-4651-bb6d-752cac03d098.png)
and on quiltmc.
![image](https://user-images.githubusercontent.com/58854399/215107917-b2bc022f-12f9-4dfc-b9f0-fb66f9c39d33.png)

**How to reproduce**

https://wikiless.tiekoetter.com/wiki/Bunchgrass
https://quiltmc.org/en/

**Comment by The-Compiler** [comment]
The tiekoetter.com one is a server-side issue:

> Bunchgrass:1 Refused to apply style from 'https://wikiless.tiekoetter.com/w/load.php?lang=en&modules=site.styles&only=styles&skin=vector-2022' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

It looks the same in Firefox and Chromium too.

The quiltmc.org one I can reproduce on the old v2.0.2 version you use, but it works fine with the latest v2.5.2 release. It looks like cc3b6fce7b40271eb2cb9bb5246f6c43673aa331 fixes it.
