### ISSUE TITLE
Hangs on notion.so login page

### ISSUE THREAD

**Issue by SG-phimeca** [qutebrowser/qutebrowser#7571]
Version:
qutebrowser v2.5.2
Git commit: 7b53f6481 on master (2023-01-27 09:27:52 +0100)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.15
PyQt: 5.15.7

The bug happens if I start with `--temp-basedir`.

Qutebrowser hangs (white page, loading animation) when trying to access https://www.notion.so/login.

I noticed it today [2023-01-30 Mon] morning without update on my computer.
Maybe notion.so did change something in their login page.

**Comment by The-Compiler** [comment]
This happens due to `Uncaught SyntaxError: Unexpected token '='`.

There isn't anything qutebrowser can do about this - you'll need to use a newer Qt 5.15 based on Chromium 87, or Qt 6 (see #7202).
