### ISSUE TITLE
darkmode does the opposite of what it should.

### ISSUE THREAD

**Issue by laalsaas** [qutebrowser/qutebrowser#7580]
**Version info**:

qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.11, based on Chromium 87.0.4280.144
Qt: 5.15.8

**Does the bug happen if you start with `--temp-basedir`?**:
Obviously not, since that implies that `webpage.darkmode.enabled` is set to false, and a restart is required to apply this setting

**Description**
On the website [pwn.college](https://pwn.college), the darkmode makes the page bright, while it is per default dark

**How to reproduce**

1. set `webpage.darkmode.enabled` to true.
2. restart qutebrowser
3. visit [pwn.college](https://pwn.college)
4. get eye cancer. (grey font on white background)
5. for comparison, visit the site with another brower or without dark mode.

**Comment by The-Compiler** [comment]
The dark mode is implemented by the underling Chromium - and it does seem to work fine already on the Qt 6 branch based on a newer Chromium (#7202).

As an aside, you can test options like this via `--temp-basedir -s colors.webpage.darkmode.enabled true`.

Out of curiosity, I [bisected](https://www.chromium.org/developers/bisect-builds-py/) this in Chromium via `python tools/bisect-builds.py -a linux64 -g 90.0.4430.85 -b 87.0.4280.141 --use-local-cache --verify-range -- --no-first-run --user-data-dir=/tmp --disable-seccomp-filter-sandbox --blink-settings=forceDarkModeEnabled=true 'pwn.college'` and got to:

> You are probably looking for a change made after 842365 (known bad), but no later than 842368 (first known good).
>
> CHANGELOG URL:
> https://chromium.googlesource.com/chromium/src/+log/dfd8c905e402c4ed8b37f27f8f5a2f441f9efced..c26ac5255d348693f9edc689335e8e0335bdf9b5

So apparently this was the fix: [[DarkMode] Do not invert shader-based images (2622989) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/2622989)

**Comment by gildasio** [comment]
Just to add a point: Almost same happens with https://manpages.debian.org/, in this case the page is default light, but darkmode changes font color but background. As I can see, the issue heve is when it inherit styles from body (background-image for manpages.debian.org, background for pwn.college).

But, never mind, installing qutebrowser-qt6-git made the trick. :)
