### ISSUE TITLE
Wayland crashes when qutebrowser is run

### ISSUE THREAD

**Issue by simonhughxyz** [qutebrowser/qutebrowser#7587]
**Version info**:

qutebrowser v2.5.2
Git commit:
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.7 (co    mpiled 5.15.5)

**Does the bug happen if you start with `--temp-basedir`?**:
No, but it never happened before and I have not changed my configs.

**Description**
When I run qutebrowser with wayland, my entire wayland session crashes, it does not happen with chromium.

`qutebrowser --debug` gives this  error/warning:
```
11:17:33 WARNING  qt-qt.qpa.wayland Unknown module:none:0 Wayland does not support QWindow::requestActivate()
  File "/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.5.2', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.11/site-packages/qutebrowser/qutebrowser.py", line 245, in main
    return app.run(args)
  File "/usr/lib/python3.11/site-packages/qutebrowser/app.py", line 130, in run
    ret = qt_mainloop()
  File "/usr/lib/python3.11/site-packages/qutebrowser/app.py", line 140, in qt_mainloop
    return objects.qapp.exec()
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/log.py", line 515, in qt_message_handler
    stack: Optional[str] = ''.join(traceback.format_stack())

11:17:34 WARNING  qt         Unknown module:none:0 The Wayland connection broke. Did the Wayland compositor die?
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/log.py", line 515, in qt_message_handler
    stack: Optional[str] = ''.join(traceback.format_stack())
```

**How to reproduce**

Run qutebrowser under wayland

**Comment by toofar** [comment]
Seems it might be fixed on Qt6.3?: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/288#issuecomment-1213468422
Assuming that warning is related to the crash. Are there any error logs from wayland?

I wonder why its only showing up now? I'll ask on IRC if anyone is actually running pure wayland successfully these days.

**Comment by simonhughxyz** [comment]
Using `qutebrowser -R` and not restoring my session somehow fixed the problem, no idea why this happened but everything works now.

Maybe you are right and it will be fixed by Qt6.3, if it happens again i'll post another issue, but for now I will close it.

Also, no there are no relevant logs from wayland.
