### ISSUE TITLE
switching between tabs

### ISSUE THREAD

**Issue by azinsharaf** [qutebrowser/qutebrowser#7589]
**Version info**:
qutebrowser v2.5.2
Git commit: 951a14a66 on HEAD (2022-06-22 15:30:51 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2 

**Does the bug happen if you start with `--temp-basedir`?**:
No, It works fine.

**Description**
it seems qutenroswer doesn't recognizes the tabs and can't switch betwene them. See the sample url below:

**How to reproduce**

[link](https://astronvim.github.io/#%EF%B8%8F-installation)
click on tabs Linux, Windows, Docker)

**Comment by toofar** [comment]
I'm afraid you are going to going to have to provide some more details as I don't think I can reproduce this. I can switch between those tabs (which changes the content in the center column) just fine, using both mouse clicks and the default hint binding of `f`.

> click on tabs

Are you clicking with the mouse or via hints? If via hints is it adding the hint boxes? If yes the activiating the hints isn't having an effect can you set `logging.level.console` to debug, activate a hint and look for the `webelem:click` line and the next few after it?

> Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
> Qt: 5.15.2

Please check the console of the developer tools (default binding `wi`) and see if there are any errors there. It's entirely possible that whatever the site is doing is using features too new for your backend.

Also can you please tell me what operating system (and release) you are on that has such an old Qt version?

**Comment by The-Compiler** [comment]
Works fine here too. Not much more I can say without any response to @toofar's questions either, but I'm assuming this is an issue in your config (e.g. JS disabled).

**Comment by azinsharaf** [comment]
@toofar @The-Compiler 
sorry for late reply. It works fine now. Not sure what the issue was.
