### ISSUE TITLE
rewatch.com videos do not play

### ISSUE THREAD

**Issue by mokshadharma** [qutebrowser/qutebrowser#7590]
**Version info**:

qutebrowser v2.5.2
Git commit: 951a14a66 on HEAD (2022-06-22 15:30:51 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

When clicking on the play button on videos hosted on rewatch.com, the videos do not play, but just show a spinning circle on a black background (see screenshot below).

**How to reproduce**

- Open a video on https://rewatch.com/
- Click the play button

**Additional context**

Screenshot of the rewatch page and devtools console, with sensitive information redacted:

<img width="1917" alt="Screenshot 2023-02-26 at 7 06 46 AM" src="https://user-images.githubusercontent.com/118926161/221411797-91b09fe9-fbc7-4742-ae49-da230b55bba9.png">

I have tried adding the following to `config.py`, typing `:config-source` in qutebrowser, and reloading the page, and it didn't help.

```python
with config.pattern('*://assets.rewatch.com/') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99999.0.3578.98 Safari/537.36'
with config.pattern('*://assets.rewatch.com/*') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99999.0.3578.98 Safari/537.36'
with config.pattern('*://*.rewatch.com/') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99999.0.3578.98 Safari/537.36'
with config.pattern('*://*.rewatch.com/*') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99999.0.3578.98 Safari/537.36'
```

I also tried the following, without success:

```python
with config.pattern('*://assets.rewatch.com/') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0'
with config.pattern('*://assets.rewatch.com/*') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0'
with config.pattern('*://*.rewatch.com/') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0'
with config.pattern('*://*.rewatch.com/*') as p:
    p.content.headers.user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0'
```

In both cases the devtools console still shows an "unsupported browser" error.

**Comment by The-Compiler** [comment]
Based on your QtWebEngine version, I'm assuming you have a Qt installed from PyQt binaries (e.g. Windows/macOS releases, or virtualenv install). Those come without proprietary codec support.
