### ISSUE TITLE
Qt 6: Window frozen until input events

### ISSUE THREAD

**Issue by llyyr** [qutebrowser/qutebrowser#7594]
**Version info**:
qutebrowser v2.5.2
Backend: QtWebEngine 6.4.2, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.2
 
CPython: 3.10.9
PyQt: 6.4.2
 
sip: no
colorama: no
jinja2: 3.1.2
pygments: 2.14.0
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: no
sqlite: 3.41.0
QtNetwork SSL: OpenSSL 3.0.8 7 Feb 2023
 
Style: Qt6CTProxyStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 23.1.0-devel-git-44202519
Platform: Linux-6.1.12-1-default-x86_64-with-glibc2.37, 64bit
Linux distribution: openSUSE Tumbleweed (opensuse)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt6/libexec, data path: /usr/share/qt6
 
Paths:
cache: /home/llyyr/.cache/qutebrowser
config: /home/llyyr/.config/qutebrowser
data: /home/llyyr/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
 
Autoconfig loaded: no
Config.py: /home/llyyr/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:21

**Does the bug happen if you start with `--temp-basedir`?**:
Yes 

**Description**
Same as #7543 and #7532, but mine wasn't fixed by Mesa upgrade. I've tried 23.0.0 and also building from the main branch. I also have sway/wlroots built from git as well

**How to reproduce**
n/a

**Comment by The-Compiler** [comment]
#7532 was closed as an upstream bug - same applies here, I'm afraid there is nothing qutebrowser can do about this. If nothing else helps, I suppose you could play around with the `qt.force_software_rendering` option.
