### ISSUE TITLE
js: Logical assignment operators are not supported

### ISSUE THREAD

**Issue by Dragosarus** [qutebrowser/qutebrowser#7601]
**Version info**:
qutebrowser v2.5.3
Git commit: 2fe78b764 on HEAD (2023-02-17 11:12:46 +0100)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
[Logical assignment operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment) currently do not appear to be supported. 
For example, after setting `x = false`, `x ||= true` should set `x` to `true`, but instead gives the error `Uncaught SyntaxError: Unexpected token '='`. Same goes for the other logical assignment operators `&&=` and `??=`.

**How to reproduce**
(optional: run through the :devtools console)
1. :jseval x = false
2. :jseval x ||= true
`x` should now be `true`, but remains `false` due to the error described above.

**Comment by The-Compiler** [comment]
See #7202 - JS syntax is implemented by the underlying QtWebEngine/Chromium, not qutebrowser.

**Comment by The-Compiler** [comment]
Ah, note that they would also work fine on a newer QtWebEngine 5.15 which is based on Chromium 87 rather than 83. This is however not available when installing Qt from the official Qt binaries (rather than e.g. via a Linux distribution).
