### ISSUE TITLE
Icon CDNs not displaying

### ISSUE THREAD

**Issue by blank1-Dev** [qutebrowser/qutebrowser#7613]
**Version info**:
Qutebrowser v2.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
See the attatched screenshot. I am trying to include icon CDN's into my project, however qutebrowser fails to display them. I have tried Feather icons with no success, as well asIon icons with no sucess either. Both chromium and firefox, however, are able to display it fine.

**How to reproduce**
With an HTML file:

<button><ion-icon name="send-sharp"></ion-icon></button>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

You can try other icon packs too and see if they are affected too. Feather Icons CDN also failed for me.

**Screenshot - Chromium, Qutebrowser, and a bit of code.**
![icon-cdn](https://user-images.githubusercontent.com/118031177/224601308-895155b7-b3c9-4335-b4d1-c2e5db74e795.png)

**Comment by toofar** [comment]
1. please check the developer tools for any errors
2. given the /home/blank/search/index.html URL in the screenshot are you opening it from a file in qutebrowser too? There was something a while back about webengine fixing a security issue on file:// tabs but their fix was overly restrictive (when compared to other browsers).
    * try, in a terminal, going to /home/blank/search/ and starting a little web server, like `python3 -m http.server 1234` then opening the page on `http://localhost:1234/index.html` and see if that works better
    * or just grab the CDN file and put save it to a local file and refer to it there

**Comment by blank1-Dev** [comment]
1.
Qutebrowser dev tools: Failed to load resource: net::ERR_NETWORK_ACCESS_DENIE
Firefox dev tools: no errors
Chromium dev tools: no errors

2.
The web server allowed it to work. Im wondering if there is a way to turn off or exclude a site/file from this restriction?

**Comment by toofar** [comment]
Check what your Qt version is (in `:version`) but for now I'm assuming its already fixed in a newer version: [[QTBUG-103778] [REG 5.15 -> 6.2] ERR_NETWORK_ACCESS_DENIED when clicking link from local page - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-103778) (also #7194)

**Comment by blank1-Dev** [comment]
Confirming that the Qt version I am running is 6.2.4 .. which is a version where this issue is supposed to be fixed.

**Comment by toofar** [comment]
Ah, sorry I didn't read the upstream issue correctly. That one was about *following* a link (and we last discussed that in https://github.com/qutebrowser/qutebrowser/issues/7206).

For your case you'll want to set the `content.local_content_can_access_remote_urls` option to true. Note that you can do that for select paths if you want via URL patterns. Eg `set -u file:///home/blank/search/* content.local_content_can_access_remote_urls true`

**Comment by blank1-Dev** [comment]
@toofar Solved! probably missed it in the documentation when skimming through, oops. Thanks!
