### ISSUE TITLE
WEBM videos using vorbis audiocodec no longer play sound

### ISSUE THREAD

**Issue by zupatisc** [qutebrowser/qutebrowser#7643]
**Version info**:
qutebrowser v2.5.3
Git commit: 
Backend: QtWebEngine 5.15.13, based on Chromium 87.0.4280.144
Qt: 5.15.8

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Some media using the WEBM container no longer plays audio, after a recent update. I downloaded one that produces audio in qutebrowser and one that doesn't and the only difference I could find between them using ffmpeg's `ffprobe` is that the video that does not produce audio uses the vorbis audiocodec, webm's using the opus codec play as expected.

**How to reproduce**
Open a WEBM that uses the vorbis codec for the audio track. I can provide the examples if needed, I just don't know where to upload them.

**Comment by The-Compiler** [comment]
This is very unlikely to be a qutebrowser issue. I'm almost certain you'll see the same issue with any other browser using QtWebEngine in the same version, e.g. KDE Falkon. Could you give that a try please?

**Comment by zupatisc** [comment]
Yes you are correct, while Ungoogled Chromium and Brave play with sound, Falkon and Qutebrowser do not.

**Comment by The-Compiler** [comment]
Maybe try how things look with Qt 6 (#7202) - but this is all handled by the underlying QtWebEngine/Chromium, there is nothing qutebrowser will be able to do here.
