### ISSUE TITLE
Possible to support higher Chrome versions?

### ISSUE THREAD

**Issue by evesdropper** [qutebrowser/qutebrowser#7649]
I switched to primarily using qutebrowser, and I have enjoyed it so far. However, it seems like the Chrome version, even on the latest release, is pretty old, and there are places where sites/platforms I use daily are about to be not supported/not supported. Here's a list of a few examples:

- Google Drive and products similar: about to be unsupported
![image](https://user-images.githubusercontent.com/82856360/230179382-6b4761e6-bac1-4933-9eaa-3d70fcb687ab.png)
- Canvas: not supported
- Banking Website: not supported
- Website for work: not supported - "Your browser does not support modern CSS Selector. There are compatibility issues. Please use modern browsers (such as Chrome, Firefox, etc.)"
![image](https://user-images.githubusercontent.com/82856360/230179837-57968772-9b24-4973-9a49-16903b88b2dc.png)

Is there any plan to replace qutebrowser with a newer version of Chrome? Thanks!

**Comment by The-Compiler** [comment]
Chromium 87 is the highest Chromium available for Qt 5. There is work ongoing for Qt 6 support and you can already try it out, see #7202 - personally I'm running that with Chromium 102 and soon 108.

**Comment by evesdropper** [comment]
Something interesting: I ended up getting the error again after setting my user agent based on the Archwiki settings (`Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0`); however, setting the user agent to a newer version not only bypasses the problems which don't allow me to use certain websites but also get rid of the warnings telling me my browser will soon be unsupported :laughing:

Will also take a look on Ubuntu and see if I can reproduce such results; then I can main qutebrowser there as well.

**Comment by The-Compiler** [comment]
If anything, set the user agent to a newer Chromium - setting it to Firefox will most likely just break other stuff. But anyways, I'd really recommend using Qt 6 instead.
