### ISSUE TITLE
darkmode does not work properly - even using qt6

### ISSUE THREAD

**Issue by gildasio** [qutebrowser/qutebrowser#7652]
**Version info**:

qutebrowser v2.5.4
Git commit: 04dad0c78-dirty on master (2023-04-04 08:33:38 +0200)
Backend: QtWebEngine 6.4.3, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.3 (compiled 6.4.2)

**Does the bug happen if you start with `--temp-basedir`?**:

If using `qutebrowser --temp-basedir -s colors.webpage.darkmode.enabled true`, yes, it happen.

**Description**

It happens with https://unix.stackexchange.com/.

It is similar to #7580 , but even happen using qt6. When using qt5 it works fine for this website.

**How to reproduce**

1. Set `webpage.darkmode.enabled` true or run `qutebrowser --temp-basedir -s colors.webpage.darkmode.enabled true`
2. Access https://unix.stackexchange.com/
3. Note the light background

**Comment by The-Compiler** [comment]
Same happens in Chromium with chrome://flags/#enable-force-dark enabled - so not a qutebrowser issue.
