### ISSUE TITLE
Yank Link to Clipboard from Page

### ISSUE THREAD

**Issue by naortega** [qutebrowser/qutebrowser#7664]
It'd be nice to have a feature where links can be yanked without having to follow them. The old VimFX plugin (for Firefox) had this feature where if you used the keybind `yf` it would label all the links on the page (just as it would if you were to try _following_ a link with `f`), and then when you selected a link, instead of following it, it would yank it to your clipboard. This way it saves time from having to right-click on the link and then click on the "Copy link address" option.

**Comment by The-Compiler** [comment]
`hint links yank` (`;y`) does exactly that.
