### ISSUE TITLE
Toggle dark mode without restart

### ISSUE THREAD

**Issue by omgold** [qutebrowser/qutebrowser#7668]
Currently it is possible to change the config setting for dark mode with the command

`config-cycle colors.webpage.darkmode.enabled`

but the change is not applied instantaneously, only after a reboot. I would find that quite useful, as some web pages just don't work nicely with dark mode. Thus I would like to disable it temporarily.

**Comment by The-Compiler** [comment]
Dark mode is passed to the underlying Chromium as a command-line flag, so this isn't possible until/unless QtWebEngine [offers an option](https://bugreports.qt.io/browse/QTBUG-84484) to change it at runtime.

**Comment by ejiek** [comment]
There is a change from a month ago that adds `ForceDarkMode` - https://github.com/qt/qtwebengine/commit/bd8572420779a916969fc2286e04269616348f71

Unfortunately, I can't understand if it's changeable at runtime =\

**Comment by The-Compiler** [comment]
@ejiek I believe it will be! Also see https://github.com/qutebrowser/qutebrowser/issues/7743#issuecomment-1659850951.

Note this will only be released with Qt 6.7, which is [planned for](https://wiki.qt.io/Qt_6.7_Release) March 2024.

**Comment by Kamyil** [comment]
So... feature will not be implemented? :(

**Comment by The-Compiler** [comment]
It [already is](https://github.com/qutebrowser/qutebrowser/pull/8182).

**Comment by Kamyil** [comment]
Sorry, nevermind. Works great! Fantastic job!
