### ISSUE TITLE
Qt 6.5: userscripts not injected on page load, sometimes

### ISSUE THREAD

**Issue by rperce** [qutebrowser/qutebrowser#7669]
**Version info**:
```
qutebrowser v2.5.4
Git commit: 294e73660-dirty on master (2023-03-19 13:23:18 +1300)
Backend: QtWebEngine 6.5, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.0
```
https://paste.the-compiler.org/view/02aceffa

**Does the bug happen if you start with `--temp-basedir`?**:
Flakily! I did it once and was _not_ able to replicate—the script ran every time—but then did it again with what I _think_ were the same steps (`qutebrowser --debug --logfilter greasemonkey,js --temp-basedir`, `:version`, copy the example script below to the data dir, `:greasemonkey-reload`, `:o https://www.google.com/`) and I _was_ able to replicate the bug. I can try more times if you want?

**Description**

**Replicata**
1. Load a page for which you have a greasemonkey script defined. This script can be a useful example:
```
// ==UserScript==
// @name Demonstrata
// @include https://www.google.com/
// @version 0.0.1
// ==/UserScript==

console.log("example script loaded");
```
2. Open the browser console.
3. Run `:greasemonkey-reload`
4. Reload the page with `r`.
5. Observe the log showing up in the console.
6. Reload the page with `r` again.

**Expectata**
The log continues to show up.

**Resultata**
The log does _not_ show up on any subsequent reload. The first reload after `:greasemonkey-reload` works, but nothing else seems to.

This result appears to be a little flaky, at least in `--temp-basedir`: in my main instance, I can repeat this process as often as I want, and always exactly the first load after a `:greasemonkey-reload` loads the script, and all subsequent reloads fail, until the next time I `:greasemonkey-reload`. In `--temp-basedir` instances, it seems like at some point the `:greasemonkey-reload` "sticks", and subsequent page refreshes _do_ load the script forever. In my first `--temp-basedir`, it was the first `:greasemonkey-reload`; on my second instance, it was either the second or third `:greasemonkey-reload`.

This issue was alluded to by [this comment](https://github.com/qutebrowser/qutebrowser/issues/7624#issuecomment-1501052020) on #7624 and it doesn't look like any of other comments there or opened issues covered this—but by all means, if I've missed it and this is a duplicate, feel free to point me elsewhere!

**Comment by The-Compiler** [comment]
This is almost certainly the same underlying issue as #7662.

**Comment by The-Compiler** [comment]
Just had this happen too, at the same time with hints breaking, so assuming it's indeed a duplicate.
