### ISSUE TITLE
Copy button not working on IEEE Xplore

### ISSUE THREAD

**Issue by f380cedric** [qutebrowser/qutebrowser#7682]
**Version info**:
qutebrowser v2.5.3
Git commit: 
Backend: QtWebEngine 5.15.13, based on Chromium 87.0.4280.144
Qt: 5.15.8
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
Copy button does not work on [IEEE Xplore](https://ieeexplore.ieee.org/).
It should copy the text but instead returns an error (`navigator.permissions.query("clipboad-write")` returns `"denied"`).
AFAIR, it used to work.
It works on falkon and chromium.
**How to reproduce**
 - Take a paper from the front page (e.g. https://ieeexplore.ieee.org/document/9942691)
 - Click on "Cite This" button, then "Copy"

**Comment by The-Compiler** [comment]
Works after a `:set -u ieeexplore.ieee.org content.javascript.clipboard access`, see point 22 in [the FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc).

Falkon globally sets this to `true` by default, contrary to [what QtWebEngine does](https://doc.qt.io/qt-5/qwebenginesettings.html#WebAttribute-enum). Given that this includes reading from the clipboard as well, I consider that a security risk, and qutebrowser disables it by default. Sadly, QtWebEngine does not offer more fine-grained permission control.

**Comment by f380cedric** [comment]
Yeah, I got bitten (again) by the sentence in the setting saying:

> With QtWebEngine, writing the clipboard as response to a user interaction is always allowed.

and since, from my naive POV, clicking on a button falls into the "a user interaction" category...
Sorry for the noise!

**Comment by The-Compiler** [comment]
Agreed on that - unfortunately, QtWebEngine/Chromium does not seem to agree... Not sure if that's an upstream bug, or if the website is doing something weird.
