### ISSUE TITLE
`url.yank_ignored_parameters` only works for `:yank` but not for `hint links yank`

### ISSUE THREAD

**Issue by amalgame21** [qutebrowser/qutebrowser#7693]
`url.yank_ignored_parameters` only works for `:yank` (`yy`) but not for `:hint links yank`
It would be greate if it can also be supported. Thanks!

**Comment by The-Compiler** [comment]
Agreed it makes sense to support them for both!

The code for `:yank` is here:

https://github.com/qutebrowser/qutebrowser/blob/bb302db71d6092a2492e3784669592fdc734be0e/qutebrowser/browser/commands.py#L716-L735

and the code for `hint links yank` here:

https://github.com/qutebrowser/qutebrowser/blob/bb302db71d6092a2492e3784669592fdc734be0e/qutebrowser/browser/hints.py#L250-L275

I suppose it would be good to unify the two a bit, e.g. via a new utility function in `qutebrowser/utils/urlutils.py` to get the text to yank for a given QUrl.

**Comment by amalgame21** [comment]
I just come up with an ugly bash awk userscript to temporarily achieve this:
```bash
#!/usr/bin/env sh

URL_STRIPPED=$(echo $QUTE_URL |awk 'BEGIN{
    FS="?"
}
{
    x=SUBSEP
    strip_param="^pp=" x "^ref=" x "^utm_source=" x "^utm_medium=" x "^utm_campaign=" x "^utm_term=" x "^utm_content=" x "^smid=" x "^smtyp=" x "^fbclid=" x "^fb_news_token=" x "^__hsfp=" x "^__hssc=" x "^__hstc=" x "^__s=" x "^_hsenc=" x "^_openstat=" x "^dclid=" x "^fbclid=" x "^gbraid=" x "^gclid=" x "^hsCtaTracking=" x "^igshid=" x "^mc_eid=" x "^ml_subscriber=" x "^ml_subscriber_hash=" x "^msclkid=" x "^oft_c=" x "^oft_ck=" x "^oft_d=" x "^oft_id=" x "^oft_ids=" x "^oft_k=" x "^oft_lk=" x "^oft_sk=" x "^oly_anon_id=" x "^oly_enc_id=" x "^rb_clickid=" x "^s_cid=" x "^ttclid=" x  "^twclid=" x "^vero_conv=" x "^vero_id=" x "^wbraid=" x "^wickedid=" x "^yclid="
    index_strip=split(strip_param, arr_strip, x)

    if (length($2) != 0){
        #declare array of query param in URL
        n=split($2,arr_query,/&/)

        for (i=1;i<=n;i++){
            for (j=1;j<=index_strip;j++){
                if ( arr_query[i] ~ arr_strip[j] ){
                    arr_query[i,0]=1
                }
            }
        }

        result = $1"?"
        for (i = 1; i <= n; i++)
            if (arr_query[i,0] == 0)
            result = result "" arr_query[i]
        print result
    }
    else
        print $1
}') 
echo $URL_STRIPPED | xclip -selection clipboard -r

echo ":message-info \"Yanked stripped URL to clipboard: $URL_STRIPPED\"" >> $QUTE_FIFO

```

Hope this function can be integrated in qutebrowser soon!

**Comment by amalgame21** [comment]
It would be great if it also apply to `:hint all`, or provide a switch to do that to open URLs with ignored parameter on new tab by hint, thanks!
