### ISSUE TITLE
Javascript Clipboard access broke

### ISSUE THREAD

**Issue by VuiMuich** [qutebrowser/qutebrowser#7695]
**Version info**:
qutebrowser v2.5.4
Git commit: bb302db71-dirty on master (2023-05-08 17:21:20 +1200)
Backend: QtWebEngine 6.5, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.0

**Does the bug happen if you start with `--temp-basedir`?**:
> not tested

**Description**
since installing an update via the `aur/qutebrowser-qt6-git` package yesterday copying to clipboard via javascript buttons seems to be broken, even though `c.content.javascript.clipboard = "access"` (or `access-paste`) is configured.

**How to reproduce**
Easiest example is the `clone repo` menu on github:
![2023-05-09-105817_422x340_scrot](https://user-images.githubusercontent.com/4779365/237047083-d31733d4-743c-4624-934b-9e6a6b7cf4d0.png)
I also tried to `:set -u github.com content.javascript.clipboard access` (or `access-paste`) with no luck.

Am I missing some change or is this really broken?

**Comment by The-Compiler** [comment]
I also noticed some trouble with this recently, but haven't looked into it in more detail yet. It might be a Qt 6.5 regression...

**Comment by VuiMuich** [comment]
Thanks, at least I am not to dumb to read change logs 😅

**Comment by toofar** [comment]
I tried to debug this today but gave up and raised an issue upstream: https://bugreports.qt.io/browse/QTBUG-113579
Hopefully they can reproduce it.

As an aside, there was some discussion recently on IRC over the confusing setting descriptions around this.
They currently read:
* none: Disable access to clipboard.
* access: Allow reading from and writing to the clipboard.
* access-paste: Allow accessing the clipboard and pasting clipboard content

After some brief testing around this I don't think `access` allows the website to read the clipboard, only write to it. I think having the mixed terminology in there makes it worse. The `none` and `access-paste` options use "access" and "paste" terminology but the `access` setting mentions "read" and "write".
IMO the meaning of "access" and "paste" are not very clear and I would propose changing them to "Allows the website to write to (and read from) the clipboard".
Although it might be worth trying to squeeze something in there about the "user interaction" stuff. For example if you set it to "none" and use the code block copy buttons on this page they still work fine: https://web.dev/async-clipboard/

**Comment by toofar** [comment]
The upstream fix has landed and applies cleanly to 6.5.1 (and probably 6.5.0 but I haven't tested that). It'll be in 6.6 and 6.5.2.
I'm not sure what we can do in the meantime. It might be possible to "polyfill" the copy action to use whatever the code blocks on that web.dev site are using to bypass the permission API (probably it's just something that is more unambiguously tied to a user action).

**Comment by tblancher** [comment]
This appears to be fixed for me, as of QtWebEngine 6.5.2.

**Comment by The-Compiler** [comment]
Yep, fixed upstream!
