### ISSUE TITLE
Weird layout of PDF in PDF.js viewer

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#7701]
**Version info**:

https://paste.the-compiler.org/view/e220235c

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When I open any PDF (e.g. https://www.unicode.org/notes/tn23/Muller-Slides.pdf) via PDF.js, I get something like this
![mess](https://github.com/qutebrowser/qutebrowser/assets/20521900/7806c80b-f954-4c8c-bfbc-e7bb56f6b843)
Where the grey misaligned text repeats the expected text. Furthermore, the grey imposter text in the one which is selectable, not the original.

I'm not sure whether it's a bug in qutebrowser or PDF.js. I guess since I reproduced with `--temp-basedir` I can be sure it's nothing on my end (beside the wrong version of something being installed).

**How to reproduce**

Since a few days (weeks?), it happens when I open a file.

**Comment by WouterSpekkink** [comment]
I experience the same problem. The buttons in the top menu are also hidden in my case.

**Comment by Aster89** [comment]
> I experience the same problem. The buttons in the top menu are also hidden in my case.

Yes, indeed. They're actually there, as you can reach them via <kbd>f</kbd> or mouse.

**Comment by The-Compiler** [comment]
Seems to work fine with either Qt 6, or `--qt-flag enable-experimental-web-platform-features`. Merging this into #7202 and #7639.
