### ISSUE TITLE
Possibility to define user bindings for input mode (bindings.command['input'])

### ISSUE THREAD

**Issue by gadefox** [qutebrowser/qutebrowser#7707]
..or please where can I find default bindings in the code, so I can add `Ins` key for leaving the input mode. Ta

**Comment by emanuele6** [comment]
```
:bind -m insert <Ins> mode-leave
```

**Comment by gadefox** [comment]
Thanks, anyway, what's the difference between `bindings.commands` and `bindings.default`? `bindings.key_mappings` is clear enough..

**Comment by The-Compiler** [comment]
Both settings are merged when reading. The split exists so that the most common use-case (adding some custom bindings) can be done without having to redefine all default bindings, even without a `config.py`.
