### ISSUE TITLE
Option 'Always' in 'Permission request' doesn't work

### ISSUE THREAD

**Issue by gadefox** [qutebrowser/qutebrowser#7708]
**Version info**:
[link](https://paste.the-compiler.org/view/7c14f877)

**Description**
Well, I assume the option `Always` means "always `yes`" and `Never` means "never `no`" :), but unfortunately the same question `Allow the website at ... to open all mailto links` is displayed every time I launch the `qute` browser.

**How to reproduce**
`gmail`

**Comment by The-Compiler** [comment]
You have a `config.py` but are not loading `autoconfig.yml` from it: https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#configpy-autoconfig
