### ISSUE TITLE
port number support for qute-pass

### ISSUE THREAD

**Issue by ralsina** [qutebrowser/qutebrowser#7709]
I have a number of self-hosted services which all have the same hostname and whose URLs differ only by port number.

In chrome, the auth info for these all get saved (and then imported into pass) in entries like "pinky.local:8080"

OTOH, qute-pass ignores the port number so it always looks them all up as "pinky.local"

I have a local patch to support this by just adding `urlparse(arguments.url).netloc` to the target list.

Happy to do a PR if this looks like a useful change, and thanks for the great project!

**Comment by The-Compiler** [comment]
I don't use the qute-pass script myself, but that seems to make sense, so please go ahead!

**Comment by ralsina** [comment]
Thanks, will do later today
