### ISSUE TITLE
In-browser dictionary

### ISSUE THREAD

**Issue by patrickaldis** [qutebrowser/qutebrowser#7710]
It would be amazing to have functionality similar to [this](https://addons.mozilla.org/en-US/firefox/addon/english-popup-dictionary/), where the definition for a highlighted word is displayed in-browser.

After looking through the documentation [here](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/commands.asciidoc), I couldn't find mention of a command that did this. 

Is this a feature that might be developed? Maybe not as a mouse triggered pop-up, but implemented to be more keyboard friendly

**Comment by The-Compiler** [comment]
This could be done as an [userscript](https://github.com/qutebrowser/qutebrowser/tree/master/misc/userscripts) (also see [yomichad](https://github.com/potamides/yomichad)); or in the future via an extension API (#30). I don't think this is generally useful enough to have it built into the core.
