### ISSUE TITLE
[FR] Add WebSerial API compatibility

### ISSUE THREAD

**Issue by pinarruiz** [qutebrowser/qutebrowser#7720]
Implement the [WebSerial API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API).

Currently, as per [caniuse.com](https://caniuse.com/web-serial), only Chrome, Edge and Opera Support this feature:

![image](https://github.com/qutebrowser/qutebrowser/assets/37040888/16ace136-3f92-425a-8e96-a7309b14fca4)

[Specification](https://wicg.github.io/serial/)

**Comment by The-Compiler** [comment]
Opened an upstream issue: [[QTBUG-136784] WebSerial / WebUSB support - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-136784)
