### ISSUE TITLE
Unable to log into Amazon.com

### ISSUE THREAD

**Issue by tblancher** [qutebrowser/qutebrowser#7724]
**Version info**:
qutebrowser v2.5.4
Git commit: bb302db71-dirty on makepkg (2023-05-08 17:21:20 +1200)
Backend: QtWebEngine 6.5.1, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.1 (compiled 6.5.0)

**Does the bug happen if you start with `--temp-basedir`?**:
No, Amazon accepts my password and shows me logged in.

**Description**
With my usual basedir, I can't log into amazon.com, the Amazon web store.  If I use --temp-basedir, I can log in, but I lose my other cookies for everything else.  If I set a separate directory with --basedir, I can also log in (but then I lose all my other cookies).

If I clear out cookies related to amazon.com, either by deleting them in `:devtools`, or loading the `webengine/Cookies` sqlite3 database, and removing anything with `host_key LIKE '%amazon%'`, Amazon seems to think cookies are disabled by qutebrowser (it tells me to enable cookies after accepting my email address).  I definitely have `content.cookies.accept = all` in `:config-diff`, so I'm not sure what Amazon is looking for.

I've even tried setting a --basedir, and exporting the Amazon cookies in Cookies to an .sql file (with INSERT statements), and loading them into my normal basedir Cookies file, and it recognized my account (doesn't prompt me to enter my email address or phone number), but when I enter the password I get no error, it just brings me back to the password prompt.  Admittedly, importing the .sql wasn't 100 percent successful, some (not all) of the INSERT statements failed due to failing to satisfy some constraints.  I'll need to see if I can fix that, and get them all imported in.

In `:devtools` I do see an error related to service_worker.js, but it doesn't appear to be too descriptive.  I'm not very well versed in navigating `:devtools`, so any guidance on how to export any troubleshooting logs would be helpful, then I can attach them to this issue.

**How to reproduce**
The site is https://www.amazon.com, when you click on the Sign In button in the top right, it generates a session-specific GET URL, then has you log in.  If I have the persistent Amazon cookies, it recognizes my account, and doesn't prompt me for a username (email address or phone number), it just keeps re-prompting me for my password (no error message, just returns to the password prompt when pressing `Submit`).  If i clear all cookies related to Amazon, it gives me the error that cookies aren't enabled when I submit my email address.  

Since this seems to be specific to the state my normal basedir is in, I'm not really sure how reproduceable this will be.  Worst case scenario I clear all my cookies, and log back into everything, including Amazon, but that seems like a very heavy-handed way to deal with this.

**Comment by The-Compiler** [comment]
Can you please show your `:config-diff`?

**Comment by tblancher** [comment]
Here's my complete `:config-diff`.  Seems there isn't a select-all command, so I had to highlight everything with my trackpoint:

```
auto_save.session = true
backend = webengine
bindings.commands = {"normal": {"<Alt+j>": "tab-focus", "gc": "spawn --userscript qute-bitwarden --password-prompt-invocation /home/trey/bin/qutebrowser-bitwarden-prompt.sh --auto-lock 0", "gl": "spawn --userscript qute-bitwarden --password-prompt-invocation /home/trey/bin/qutebrowser-bitwarden-prompt.sh --auto-lock 86400", "gp": "spawn --userscript qute-bitwarden --password-prompt-invocation /home/trey/bin/qutebrowser-bitwarden-prompt.sh -w --auto-lock 86400"}}
colors.statusbar.normal.bg = #282828
colors.statusbar.normal.fg = #ffd7af
colors.statusbar.url.fg = #ffd7af
colors.statusbar.url.success.http.fg = #ffd7af
colors.tabs.bar.bg = #282828
colors.tabs.even.bg = #333333
colors.tabs.even.fg = #ffd7af
colors.tabs.odd.bg = #444444
colors.tabs.odd.fg = #ffd7af
colors.tabs.pinned.even.bg = #333333
colors.tabs.pinned.even.fg = #ffd7af
colors.tabs.pinned.odd.bg = #282828
colors.tabs.pinned.odd.fg = #ffd7af
colors.tabs.pinned.selected.even.bg = #cccccc
colors.tabs.pinned.selected.even.fg = #000000
colors.tabs.pinned.selected.odd.bg = #cccccc
colors.tabs.pinned.selected.odd.fg = #000000
colors.tabs.selected.even.bg = #cccccc
colors.tabs.selected.even.fg = #000000
colors.tabs.selected.odd.bg = #cccccc
colors.tabs.selected.odd.fg = #000000
colors.webpage.darkmode.enabled = true
colors.webpage.darkmode.policy.images = smart
colors.webpage.darkmode.threshold.background = 205
colors.webpage.darkmode.threshold.text = 150
colors.webpage.preferred_color_scheme = dark
completion.cmd_history_max_items = -1
completion.open_categories = ["searchengines", "quickmarks", "bookmarks", "history", "filesystem"]
completion.quick = true
content.cookies.accept = all
https://order.firehousesubs.com: content.geolocation = true
https://www.aetna.com: content.geolocation = true
https://www.google.com: content.geolocation = true
https://www.neworleanssaints.com: content.geolocation = false
https://www.tracfone.com: content.geolocation = false
content.headers.user_agent = Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version}(KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}https://web.whatsapp.com/
https://forum.ghost.org: content.headers.user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
https://calendar.google.com: content.notifications.enabled = true
https://messages.google.com: content.notifications.enabled = true
https://www.youtube.com: content.notifications.enabled = false
https://calendar.google.com?cid=%25s: content.register_protocol_handler = true
https://mail.google.com?extsrc=mailto&url=%25s: content.register_protocol_handler = false
editor.command = ["alacritty", "--command", "vim", "{file}", "-c", "normal {line0}G{column0}l"]
fonts.default_family = Iosevka Term
new_instance_open_target = tab
tabs.pinned.shrink = false
tabs.position = left
tabs.title.format = {audio}{aligned_index}:  {current_title}
tabs.title.format_pinned = {audio}{aligned_index}:  {current_title}
url.auto_search = naive
url.default_page = about:blank
url.searchengines = {"DEFAULT": "https://google.com/search?q={semiquoted}"}
url.start_pages = about:blank
```

**Comment by The-Compiler** [comment]
If this line is correct:

```
content.headers.user_agent = Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version}(KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}https://web.whatsapp.com/
```

then that's a very strange user agent to set - but even without the `https://web.whatsapp.com/` this is almost guaranteed to break things. Please unset that, make sure it is indeed unset (e.g. via http://httpbin.org/user-agent) and try again.

As for selecting text: Going to insert mode (`i`) and Ctrl-A will work, and so will using visual mode (`v`, `gg`, `v`, `G`)

**Comment by tblancher** [comment]
I commented that user agent string out of my _config.py_, and now I can log into Amazon!  I wonder if that has been the source of having weird behavior on other sites.  

Thanks so much!
