### ISSUE TITLE
Kinetic Scrolling

### ISSUE THREAD

**Issue by patrickaldis** [qutebrowser/qutebrowser#7725]
It would be great to have kinetic scrolling like chrome or firefox (i.e. the viewport carries on moving with the momentum of the scroll). Currently the screen just stops abruptly after a swipe, the kinetic scrolling seems more natural.

It looks like Qt offers a lot of help with this - https://doc.qt.io/qt-6/qscroller.html

Is this something that would be considered implementing?

**Comment by The-Compiler** [comment]
Scrolling the webpage is handled by QtWebEngine and not qutebrowser, and I was under the impression that this already worked. What's your `:version` info? Does `--temp-basedir` change anything?

**Comment by patrickaldis** [comment]
Unfourtunately that didn't seem to do anything
Heres my version info: https://paste.the-compiler.org/view/ba77c7ce

I'm running on NixOS on Sway, but I've tested on GNOME too and have the same issue

**Comment by The-Compiler** [comment]
Can you test with a different QtWebEngine version easily, e.g. Qt 5.15, 6.4 or 6.5.1?

**Comment by patrickaldis** [comment]
Running on QtWebEngine 5.15.4 I have the same problem.

Heres the version info: https://paste.the-compiler.org/view/f5e2f65f

**Comment by patrickaldis** [comment]
Is this issue specific to my configuration? I know you mentioned earlier that you thought this already worked

**Comment by The-Compiler** [comment]
I don't know - I remember it working when I had a touch screen, but that's years back at this point. Right now I have neither a touchscreen nor a touchpad to test with. For what it's worth, this would be something that QtWebEngine should take care of, and I wasn't able to find any upstream reports.

**Comment by patrickaldis** [comment]
I hadn't even thought about testing out my touchscreen untill now, but actually the smooth scrolling works fine on the touchscreen, its just the touchpad that has this problem. I made a video to showcase:

https://github.com/qutebrowser/qutebrowser/assets/46719614/0a03064a-7734-4c42-bee6-16b3b8bcd63e

The touchpad is totally standard though, I'm using the libinput driver on wayland - I don't think this is a system specific issue?

**Comment by The-Compiler** [comment]
See [763791 - Please support libinput kinetic scrolling. - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=763791), which links to: [Reenable and fix kinetic scrolling in ozone/wayland (3955901) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/3955901)

Which seems to be included in Chromium 109, but Qt 6.5 is based on Chromium 108. Thus, I suspect this will start working on Qt 6.6, currently [planned for](https://wiki.qt.io/Qt_6.6_Release) September.

Nothing qutebrowser itself can do here, and it already looks like this is fixed upstream, so I'm closing this.
