### ISSUE TITLE
Click event does not exist

### ISSUE THREAD

**Issue by TheHardew** [qutebrowser/qutebrowser#7734]
**Version info**:

```
qutebrowser v2.5.4
Git commit: a71c25c2a-dirty on makepkg (2023-06-05 13:02:42 +0200)
Backend: QtWebEngine 6.5.1, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.0

CPython: 3.11.3
PyQt: 6.5.0

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
pdf.js: 3.6.172 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.8 7 Feb 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 23.0.3
Platform: Linux-6.3.3-zen1-1.1-zen-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /tmp/qutebrowser-basedir-uewak8p7/cache
config: /tmp/qutebrowser-basedir-uewak8p7/config
data: /tmp/qutebrowser-basedir-uewak8p7/data
runtime: /tmp/qutebrowser-basedir-uewak8p7/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:10
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

Go to: https://www.matecdev.com/posts/julia-for-loops.html
On the left hand side there is a sidebar with contents. Some of the sections have an arrow to display the subsections.
Clicking on them (either mouse or keyboard) does not do anything. In the developer tools, the associated button does not even have a click() event listener.

Works correctly in firefox and chrome.

**How to reproduce**
Go to: https://www.matecdev.com/posts/julia-for-loops.html
Press on one of the arrows in the sidebar, e.g. on the 3rd section, "Basic Variable Types"

**Comment by The-Compiler** [comment]
The page loads the Google ads script async:

```html
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7401022168140885" crossorigin="anonymous"></script>
```

which [means that](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attributes) it might or might not have run completely at the time the failing script is run (which seems to falsely rely on it being run already).

It looks like in qutebrowser it's more likely that it hasn't completed yet, but in the end it's a race condition either way.

**Comment by mdmaas** [comment]
> Google ads script

Oh, thanks a lot! 

I knew something was fishy about the toggle button, but I had no idea it could be related to the google script (I don't know what astro is doing here -- as the code for the toggle button should be unrelated to the google script -- or a lot about debugging js!). 

I think making the google script on the header load sync fixes this, so thanks again!

**Comment by TheHardew** [comment]
@mdmaas works!
