### ISSUE TITLE
qutebrowser's hint mode doesn't show all clickable parts in a website

### ISSUE THREAD

**Issue by Pedro-V** [qutebrowser/qutebrowser#7738]
**Version info**:

```
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.14, based on Chromium 87.0.4280.144
Qt: 5.15.9 (compiled 5.15.8)
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

In some websites, the hint mode doesn't show all clickable elements. Take for example the below screenshot for changing DuckDuckGo.com appearence from Light Theme to Dark Theme (or its URL style).

The page's elements associated with these settings aren't "hinted" at.

![image](https://github.com/qutebrowser/qutebrowser/assets/50002503/e9e5983b-b6c4-4533-bf4a-ecd6790b2229)

Take the same website, but with Tridactyl inside Firefox:

![image](https://github.com/qutebrowser/qutebrowser/assets/50002503/f01c75e6-b4da-49e1-966a-fcc59198eb37)

**How to reproduce**

1. Go to [https://duckduckgo.com/settings#appearance](https://duckduckgo.com/settings#appearance)
2. Hit `f`
3. Try to change the theme to Dark (or any other) inside hint mode, or changing the URL style

**Comment by The-Compiler** [comment]
Added to #178
