### ISSUE TITLE
About mouse disable 

### ISSUE THREAD

**Issue by codedsprit** [qutebrowser/qutebrowser#7747]
Hii,
I wonder Is there any command that can disable mouse navigation. If yes how can I use that.

**Comment by The-Compiler** [comment]
What kind of mouse navigation exactly, and why?

**Comment by codedsprit** [comment]
Please correct me if I'm mistaken, but I would like to disable the right-click function for certain reasons.

**Comment by The-Compiler** [comment]
The `input.mouse.rocker_gestures` setting might do what you want as a side effect. Can't really say more with so little information.
