### ISSUE TITLE
Type hints for 'config' and 'c' objects passed to config.py

### ISSUE THREAD

**Issue by svermeulen** [qutebrowser/qutebrowser#7750]
It would be great if we could distribute type hints so that users can get autocomplete and better error checking in their `config.py` on the `config` and `c` objects.

To start it could look like this `qutebrowser.pyi` file:

    from typing import Optional, Any, Literal
    from enum import Enum

    class ConfigApi:
        def get(self, name: str, pattern: Optional[str] = None) -> Any:
            """Get a setting value from the config, optionally with a pattern."""
            ...

        def set(self, name: str, value: Any, pattern: Optional[str] = None) -> None:
            """Set a setting value in the config, optionally with a pattern."""
            ...
        
        def unbind(self, key: str, mode: str = 'normal') -> None:
            """Unbind a key from a command, with an optional key mode."""
            ...

        def bind(self, key: str, command: Optional[str], mode: str = 'normal') -> None:
            """Bind a key to a command, with an optional key mode."""
            ...

        def source(self, filename: str) -> None:
            """Read the given config file from disk."""
            ...

        def load_autoconfig(self, load_config: bool = True) -> None:
            ...

    class ConfigContainer:
        class Search:
            ignore_case:Literal["always", "never", "smart"]

        search:Search

        # todo

**Comment by svermeulen** [comment]
I'm slowly filling this out so I can contribute it back if that would be useful

**Comment by alkim0** [comment]
As per #7098, I suggest `str | None` instead of `Optional[str]` and `object` instead of `Any`.

**Comment by The-Compiler** [comment]
@svermeulen `ConfigAPI` already [has type hints](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/config/configfiles.py#L762-L800), and if you define it as [suggested in the docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#avoiding-flake8-errors), you'll get autocompletion for it.

As for `c`, as cool as autocompletion for qutebrowser options would be, I really don't think it's worth the effort to painfully duplicate all the information in `configdata.yml` for this. Perhaps this is something that could be done to get rid of `configdata.yml` entirely (see #2777), but it will need some more careful consideration first.

@alkim0 Note that this would need `from __future__ import annotations` to work with all supported Python versions, as this feature [was only added in Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#pep-604-new-type-union-operator). I'm unsure at the moment if that change works in qutebrowser without breaking things, or if it requires more changes (as qutebrowser itself also uses type annotations for commands).

Also, `object` and `Any` are not the same thing - see [The `Any` type](https://docs.python.org/3/library/typing.html#the-any-type) and [`Any` vs. `object`](https://mypy.readthedocs.io/en/latest/dynamic_typing.html#any-vs-object).

**Comment by RobertCraigie** [comment]
Hey! I just opened a [PR](https://github.com/qutebrowser/qutebrowser/pull/8351) adding support for auto-generating the types so there shouldn't be any maintenance burden :)
