### ISSUE TITLE
Small bitmap fonts are not drawn correctly with the Qt6 backend.

### ISSUE THREAD

**Issue by DarkDefender** [qutebrowser/qutebrowser#7762]
**Version info**:
```
qutebrowser v2.5.4
Git commit: 772c39cea-dirty on HEAD (2023-06-29 10:30:55 +0200)
Backend: QtWebEngine 6.5.1, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.1

CPython: 3.11.4
PyQt: 6.5.1

Qt wrapper: PyQt6 (via default)
```

**Does the bug happen if you start with `--temp-basedir`?**:
No, it defaults to other fonts then, so there are no artifacts.

**Description**
If a bitmap font with a size less than 10pt is used, weird artifacts appears at the top of the font drawing

**How to reproduce**
Install and use a bitmap font, for example Terminus. Set the tabline to use `'8pt "Terminus"'`. Notice that there is now weird dot patterns at the top of the area where fonts are drawn.
![screenshot](https://github.com/qutebrowser/qutebrowser/assets/312503/07f81da2-f550-4c9f-8069-cd47121be799)

It also seems like the top of the drawn characters are cut off. For example the square brackets are not fully drawn:
![screenshot](https://github.com/qutebrowser/qutebrowser/assets/312503/392b66da-2807-4665-a8cd-2d8740f39004)

I did not have this issue with the Qt5 backend, so I'm guessing this might be a Qt6 issue, but I'm not sure.

**Comment by The-Compiler** [comment]
Already tracked in #7663 - but indeed most likely an upstream issue.
