### ISSUE TITLE
Render problem trying to open Azure Portal'

### ISSUE THREAD

**Issue by Msouza91** [qutebrowser/qutebrowser#7765]
**Version info**:
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3

CPython: 3.10.6
PyQt: 5.15.6

sip: 6.5.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.11.2
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.2
QtNetwork SSL: OpenSSL 3.0.2 15 Mar 2022

**Does the bug happen if you start with `--temp-basedir`?**:
No

**Description**
I used to access this site through qutebrowser without issues, after a few weeks one day I refreshed the page after a session expired to try and log back in, now I get the same error everytime I try to open the website.
![2023-07-03-101657_1891x1027_scrot](https://github.com/qutebrowser/qutebrowser/assets/19522556/a4228507-d581-4324-8a09-b03d52803ddc)

**How to reproduce**

portal.azure.com 
Log in, leave the website open for the time configured by the admin of the domain to invalidate a session (in my case was around 12 hours) when prompted to Refresh and log back in get the error everytime trying opening the address.

**Comment by The-Compiler** [comment]
Renderer process crashes are issues in the underlying QtWebEngine/Chromium - might be fixed with Qt 6 already (#7202), but in any case, nothing qutebrowser can do about this.
