### ISSUE TITLE
Run package building on CI with warnings turned into errors

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7773]
In order to catch issues like #7627 earlier, we should run `python -m build` on CI with `PYTHONWARNINGS=error` set (or, if we figure that's too noisy, perhaps `PYTHONWARNINGS=error,default::DeprecationWarning`).

For consistency, this should probably be an environment in `tox.ini` which then gets run in `.github/workflows/ci.yml` like the others.

@pylbrecht Wanna take a look at this once your other two PRs are done? This isn't strictly required for 3.0.0, but it's nicely on-topic with what you did in #7627.

**Comment by pylbrecht** [comment]
> @pylbrecht Wanna take a look at this once your other two PRs are done? This isn't strictly required for 3.0.0, but it's nicely on-topic with what you did in #7627.

Sure! Feel free to assign me (it's easier to track my TODOs that way).
