### ISSUE TITLE
WebGL not disabled, even when "content.webgl.enabled" is "false" (according to CreepJS)

### ISSUE THREAD

**Issue by iloveyumyumshrimpnoodles** [qutebrowser/qutebrowser#7777]
**Version info**:
```
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.7

CPython: 3.11.4
PyQt: 5.15.9

sip: 6.7.9
colorama: no
jinja2: 3.1.2
pygments: no
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 1.1.1t  7 Feb 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 23.1.3
Platform: Linux-6.3.12_1-x86_64-with-libc, 64bit
Linux distribution: Void Linux (void)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/void/.cache/qutebrowser
config: /home/void/.config/qutebrowser
data: /home/void/.local/share/qutebrowser
runtime: /tmp/runtime-void/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/void/.config/qutebrowser/config.py has been loaded
Uptime: 0:15:17
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Setting `content.webgl.enabled` to `false` does not disable WebGL, according to https://abrahamjuliot.github.io/creepjs/

**How to reproduce**
1. Set `content.webgl.enabled` to `true`.
2. Visit https://abrahamjuliot.github.io/creepjs/
3. Scroll down, and check the `WebGL` box, next to `Screen`
4. Set `content.webgl.enabled` to `false`.
5. Reload page
6. Scroll down, and check the `WebGL` box, next to `Screen`

Value looks the same

**Images**
![example](https://github.com/qutebrowser/qutebrowser/assets/125209101/ccd865b2-8cf7-4792-be56-8c7b5da269f8)
what librewolf with WebGL disabled shows:
![librewolf](https://github.com/qutebrowser/qutebrowser/assets/125209101/25220390-11c1-4587-9db1-e10fa55258f9)

**Comment by iloveyumyumshrimpnoodles** [comment]
Then how is CreepJS accessing that information?

**Comment by iloveyumyumshrimpnoodles** [comment]
So that's it? No response?

**Comment by The-Compiler** [comment]
With that attitude, definitely not. Go take that somewhere else, or ideally, nowhere.

**Comment by iloveyumyumshrimpnoodles** [comment]
Well, seeing as its quite a problem that even when you disable something, its left enabled (and can be accessed by some sites) that it should be fixed, no?

**Comment by iloveyumyumshrimpnoodles** [comment]
Alright well it seems like you're not willing to fix this issue.

I'll be uninstalling QuteBrowser then, as I don't even want to imagine what other options which I set to False are still working, and accessible to sites.

Have a good day.
