### ISSUE TITLE
Configure which keys the find prompt uses

### ISSUE THREAD

**Issue by oku32** [qutebrowser/qutebrowser#7779]
I've noticed that the find prompt uses keys that are found on the home row and inner-columns of a standard QWERTY keyboard, minus the semicolon, so `ASDFG HJKL`.

I'm not sure if this is currently possible, at least I couldn't seem to find any documentation, but would it possible to add the ability to configure which keys are used in favour of non-QWERTY layouts?

For example, I currently use the [Aptmak](https://github.com/Apsu/aptmak) layout, which puts `RSTHK XNAIO` on the home row and inner-columns, so being able to set these would be great!

**Comment by The-Compiler** [comment]
They're called "hints", and the `hints.chars` setting does exactly this.
