### ISSUE TITLE
Some Websites having long URL(s) leave no space for other objects to be clearly seen so maybe add this feature to qute to allow trimming of long websites

### ISSUE THREAD

**Issue by Coder-Takshil** [qutebrowser/qutebrowser#7786]
**Version info**:

- qutebrowser v2.5.4
- Git commit: 3b04cb1d9 on master (2023-07-13 09:27:19 +0200)
- Backend: QtWebEngine 5.15.14, based on Chromium 87.0.4280.144
- Qt: 5.15.10 (compiled 5.15.8)
- 
- CPython: 3.11.3
- PyQt: 5.15.9
 
- Qt wrapper: PyQt5 (via default)
 
- sip: 6.7.9
- colorama: 0.4.6
- jinja2: 3.1.2
- pygments: 2.15.1
- yaml: 6.0
- adblock: 0.6.0
- objc: no
- PyQt5.QtWebEngineWidgets: yes
- PyQt5.QtWebEngine: 5.15.6
- PyQt5.QtWebKitWidgets: no
- pdf.js: 3.7.107 (/usr/share/pdf.js/build/pdf.js)
- sqlite: 3.42.0
- QtNetwork SSL: OpenSSL 3.1.1 30 May 2023

- Style: Qt5CTProxyStyle
- Platform plugin: xcb
- OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.1.3
- Platform: Linux-6.4.3-zen1-1-zen-x86_64-with-glibc2.37, 64bit
- Linux distribution: Garuda Linux (arch)
- Frozen: False
- Imported from /usr/lib/python3.11/site-packages/qutebrowser
- Using Python from /usr/sbin/python3
- Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
 
- Paths:
- cache: ~/.cache/qutebrowser
- config: ~/.config/qutebrowser
- data: ~/.local/share/qutebrowser
- runtime: /run/user/1000/qutebrowser
- system data: /usr/share/qutebrowser
 
- Autoconfig loaded: no
- Config.py: ~/.config/qutebrowser/config.py has been loaded
- Uptime: 21:36:07

**Does the bug happen if you start with `--temp-basedir`?**:
Yeah ofc...
**Description**

![Feature : ](https://github.com/qutebrowser/qutebrowser/assets/84800625/00141f09-b8d4-462a-9287-db165de5418d)
the yanked url was : 
''**https://www.google.com/search?q=qutebrowser+config&sxsrf=AB5stBhizpHtY9vDKbQWJG2N_7_JWKT_FA%3A1689850521759&source=hp&ei=mRK5ZICsLI6l1e8PxvWE2A4&iflsig=AD69kcEAAAAAZLkgqf25eL5qjOEH8SPNw-h5361RHuVu&oq=qut&gs_lp=Egdnd3Mtd2l6IgNxdXQqAggAMgcQIxiKBRgnMgQQIxgnMgcQIxiKBRgnMggQABiKBRiRAjIKEAAYgAQYFBiHAjILEAAYigUYsQMYkQIyCxAuGIAEGLEDGIMBMgsQABiABBixAxiDATIIEAAYgAQYsQMyCBAAGIAEGLEDSMJuUABYomFwA3gAkAEAmAGgAaABpwWqAQMwLjW4AQPIAQD4AQGoAgrCAgsQABiKBRixAxiDAcICCxAuGIoFGLEDGIMBwgIHECMY6gIYJ8ICERAuGIAEGLEDGIMBGMcBGNEDwgIOEAAYigUYsQMYgwEYkQLCAgsQLhiABBjHARivAcICBRAAGIAEwgILEC4YgAQYxwEY0QM&sclient=gws-wiz**''

so this URL is way much bigger so maybe qute can shorten it like : ''**https://www.google.com/search?q=qutebrowser+config**'' : which also give me the same search result and the ahead part is pain so just remove it yeah advanced devs can leave it on as they may need it for debugging , but it would be good to have it cut short...

Ik ur doing a great job by just making qute from vimb [ this one is way worse ]... but it would be good to have this trim feature...
Thanks in advance @The-Compiler 

and i also dont know if this exists and if it does can u tell it to me?

**How to reproduce**

Any Google or [Cannot trim this url  ...]

**Comment by The-Compiler** [comment]
I'm confused on what the issue is - you say "leave no space for other objects to be clearly seen", yet everything that should be visible is visible in your screenshot?

**Comment by toofar** [comment]
It is also not clear to me what this issue is about. Maybe you can whip up some before and after sketches for us?

If you are asking for a feature that elides part of the page URL in the status bar I'm not sure if I'm keen for that at this time. Some effort has been put into making the URL in the status bar something that users can trust (eg the meaning of green/yellow/white and the handling of punycode). I can understand that having a config option to make it look "cleaner" would be nice in some cases but it would be a bit of work to implement that information hiding in a way that didn't cause more user confusion or mistrust.

**Comment by Coder-Takshil** [comment]
> I'm confused on what the issue is - you say "leave no space for other objects to be clearly seen", yet everything that should be visible is visible in your screenshot?



> It is also not clear to me what this issue is about. Maybe you can whip up some before and after sketches for us?
> 
> If you are asking for a feature that elides part of the page URL in the status bar I'm not sure if I'm keen for that at this time. Some effort has been put into making the URL in the status bar something that users can trust (eg the meaning of green/yellow/white and the handling of punycode). I can understand that having a config option to make it look "cleaner" would be nice in some cases but it would be a bit of work to implement that information hiding in a way that didn't cause more user confusion or mistrust.

Thank you for the quich response @The-Compiler and team...
Uh sorry for the previous confusion [i hope i aint acting like chatGPT 😆]...

I meant that um... see the yanked url i pasted [ da big one ], i want it to be trimmed like the small one i pasted... while both of them do the same thing but the other one is too long and un-humanly-readable, i cannot make shit out of the big one so the small one which will do the same job would be preferrable... as far as @The-Compiler is concerned, ig u didnt see the ss properly... cant you see that whole url thing ate my whole statusbar and it kinda looks crappy...
Thanks in adv.

**Comment by Coder-Takshil** [comment]
Uh sorry by mistake i closed it...

**Comment by Coder-Takshil** [comment]
> > I'm confused on what the issue is - you say "leave no space for other objects to be clearly seen", yet everything that should be visible is visible in your screenshot?
> 
> > It is also not clear to me what this issue is about. Maybe you can whip up some before and after sketches for us?
> > If you are asking for a feature that elides part of the page URL in the status bar I'm not sure if I'm keen for that at this time. Some effort has been put into making the URL in the status bar something that users can trust (eg the meaning of green/yellow/white and the handling of punycode). I can understand that having a config option to make it look "cleaner" would be nice in some cases but it would be a bit of work to implement that information hiding in a way that didn't cause more user confusion or mistrust.
> 
> Thank you for the quich response @The-Compiler and team... Uh sorry for the previous confusion [i hope i aint acting like chatGPT laughing]...
> 
> I meant that um... see the yanked url i pasted [ da big one ], i want it to be trimmed like the small one i pasted... while both of them do the same thing but the other one is too long and un-humanly-readable, i cannot make shit out of the big one so the small one which will do the same job would be preferrable... as far as @The-Compiler is concerned, ig u didnt see the ss properly... cant you see that whole url thing ate my whole statusbar and it kinda looks crappy... Thanks in adv.

 pls answer ...

**Comment by The-Compiler** [comment]
> I meant that um... see the yanked url i pasted [ da big one ], i want it to be trimmed like the small one i pasted... while both of them do the same thing but the other one is too long and un-humanly-readable, i cannot make shit out of the big one so the small one which will do the same job would be preferrable...

You can set `url.yank_ignored_parameters` accordingly. qutebrowser has no way to know on its own which parts of an URL are relevant/useful, and which are not. It's not settable per-domain yet, I added a comment to #3636 about that.

> as far as @The-Compiler is concerned, ig u didnt see the ss properly... cant you see that whole url thing ate my whole statusbar and it kinda looks crappy...

I sure can see it, but if you just dump a screenshot but then describe a different problem (regarding yank), the reason I'm confused isn't that I can't see things :wink:

I don't think this is a problem that needs solving. There is value in being able to see the URL parameters - and as explained above, there is no way for qutebrowser to know what's relevant and what is not.

> pls answer ...

This behavior isn't appropriate at all. If you need an answer to qutebrowser questions in a guaranteed <24h, go buy a support contract or something :upside_down_face:. Outside of that, consider that people have a real life and do things other than staring at an issue tracker all day.

**Comment by Coder-Takshil** [comment]
> I sure can see it, but if you just dump a screenshot but then describe a different problem (regarding yank), the reason I'm confused isn't that I can't see things wink
> 
> > pls answer ...
> 
> This behavior isn't appropriate at all. If you need an answer to qutebrowser questions in a guaranteed <24h, go buy a support contract or something upside_down_face. Outside of that, consider that people have a real life and do things other than staring at an issue tracker all day.
 
hey bro, sorry 😭 by "pls answer" i meant the first comment came out a few hours later by two of u devs and then the next one didnt came for until a day i by mistakenly closed the issue so i thought u might not b getting these comments so i just sent that to b sure... i didnt really mean it 
b/w kudos for qutebrowser its bcome my fav daily driver...

**Comment by Coder-Takshil** [comment]
b/w the userscript qute-pass failed for me like : 
Status : Userscript exited with status 3.
Standard Error : Failed to match username, target: path, error: Pattern did not match target

i made the userscript password_fill work for me but it was only successful for a few sites like : hoyoverse.com, google.com fontstruct.com id.unity.com 
and unsuccessful for others like : www.reddit.com www.twitch.tv hoyolab.com spotify.com

so what do i do...

**Comment by The-Compiler** [comment]
No clue off-hand, I never used either of those. As before, please open a [discussion](https://github.com/qutebrowser/qutebrowser/discussions) or use any of the other [support channels](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/index.asciidoc#getting-help) and someone might be able to answer.
