### ISSUE TITLE
Webpage font rendering problem

### ISSUE THREAD

**Issue by dantearaujo1** [qutebrowser/qutebrowser#7800]
**Version info**:
qutebrowser v2.5.4
Git commit: 62fef9d9e on master (2023-07-22 20:08:26 +0200)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2 (compiled 6.5.1)

**Does the bug happen if you start with `--temp-basedir`?**:
No, it works correctly

**Description**
WebPage fonts rendering awkard 

**How to reproduce**
Open qutebrowser without --temp-basedir

![image](https://github.com/qutebrowser/qutebrowser/assets/21104508/fa3c3e37-9e40-4b25-8179-1f120b1bac1a)

This is when using with --temp-basedir

![image](https://github.com/qutebrowser/qutebrowser/assets/21104508/0cbb9198-c8f6-454e-a5b1-6c1abdfa354f)

**Comment by The-Compiler** [comment]
Can you show your `:config-diff` please? Is the `:version` information the same in both cases?

**Comment by dantearaujo1** [comment]
# CONFIG-DIFF
`aliases = {"ge": "open -t https://wiki.archlinux.org/index.php/Forum_Etiquette", "gp": "open -t http://127.0.0.1:4000", "gu": "open -t https://github.com/dantearaujo1", "q": "close", "qa": "quit", "w": "session-save", "wq": "quit --save", "wqa": "quit --save"}
bindings.commands = {"normal": {",ko": "jseval (function () {   var i, elements = document.querySelectorAll(\"body *\");  for (i = 0; i < elements.length; i++) {    var pos = getComputedStyle(elements[i]).position;    if (pos === \"fixed\" || pos == \"sticky\") {      elements[i].parentNode.removeChild(elements[i]);    }  }})();", ",s": "spawn --userscript ~/.config/qutebrowser/userscripts/qute-1password/qute_1pass.py fill_credentials", ",u": "spawn --userscript ~/.config/qutebrowser/userscripts/qute-1password/qute_1pass.py login", ",ya": "yank inline {url:pretty}[{title}]", ",ym": "yank inline [{title}]({url:pretty})", ";T": "hint userscript all translate --text", ";t": "hint userscript link translate", "<Ctrl+->": "zoom-out", "<Ctrl+3>": "hint code userscript code_select.py", "<Ctrl+=>": "zoom-in", "<Ctrl+Shift+t>": "spawn --userscript translate --text", "<Ctrl+t>": "spawn --userscript translate"}}
colors.completion.category.bg = #171D22
colors.completion.category.border.bottom = #0F110C
colors.completion.category.border.top = #0F110C
colors.completion.category.fg = #539AFC
colors.completion.even.bg = #1D252C
colors.completion.fg = #a0b3c5
colors.completion.item.selected.bg = #10151C
colors.completion.item.selected.border.bottom = #10151C
colors.completion.item.selected.border.top = #10151C
colors.completion.item.selected.fg = #70E1E8
colors.completion.item.selected.match.fg = #D98E48
colors.completion.match.fg = #EBBF83
colors.completion.odd.bg = #171D22
colors.completion.scrollbar.bg = #1D252C
colors.completion.scrollbar.fg = #a0b3c5
colors.contextmenu.disabled.bg = #171D22
colors.contextmenu.disabled.fg = #56697a
colors.contextmenu.menu.bg = #1D252C
colors.contextmenu.menu.fg = #a0b3c5
colors.contextmenu.selected.bg = #10151C
colors.contextmenu.selected.fg = #a0b3c5
colors.downloads.bar.bg = #1D252C
colors.downloads.error.fg = #d95468
colors.downloads.start.bg = #539AFC
colors.downloads.start.fg = #1D252C
colors.downloads.stop.bg = #008b94
colors.downloads.stop.fg = #1D252C
colors.hints.bg = #EBBF83
colors.hints.fg = #1D252C
colors.hints.match.fg = #a0b3c5
colors.keyhint.bg = #1D252C
colors.keyhint.fg = #a0b3c5
colors.keyhint.suffix.fg = #EBBF83
colors.messages.error.bg = #1D252C
colors.messages.error.border = #d95468
colors.messages.error.fg = #d95468
colors.messages.info.bg = #1D252C
colors.messages.info.border = #70E1E8
colors.messages.info.fg = #70E1E8
colors.messages.warning.bg = #1D252C
colors.messages.warning.border = #D98E48
colors.messages.warning.fg = #D98E48
colors.prompts.bg = #1D252C
colors.prompts.border = #1D252C
colors.prompts.fg = #a0b3c5
colors.prompts.selected.bg = #10151C
colors.prompts.selected.fg = #a0b3c5
colors.statusbar.caret.bg = #b62d65
colors.statusbar.caret.fg = #1D252C
colors.statusbar.caret.selection.bg = #539AFC
colors.statusbar.caret.selection.fg = #1D252C
colors.statusbar.command.bg = #1D252C
colors.statusbar.command.fg = #a0b3c5
colors.statusbar.command.private.bg = #1D252C
colors.statusbar.command.private.fg = #a0b3c5
colors.statusbar.insert.bg = #539AFC
colors.statusbar.insert.fg = #1D252C
colors.statusbar.normal.bg = #1D252C
colors.statusbar.normal.fg = #8BD49C
colors.statusbar.passthrough.bg = #008b94
colors.statusbar.passthrough.fg = #1D252C
colors.statusbar.private.bg = #171D22
colors.statusbar.private.fg = #1D252C
colors.statusbar.progress.bg = #539AFC
colors.statusbar.url.error.fg = #d95468
colors.statusbar.url.fg = #a0b3c5
colors.statusbar.url.hover.fg = #70E1E8
colors.statusbar.url.success.http.fg = #a0b3c5
colors.statusbar.url.success.https.fg = #8BD49C
colors.statusbar.url.warn.fg = #e27e8d
colors.tabs.bar.bg = #1D252C
colors.tabs.even.bg = #10151C
colors.tabs.even.fg = #a0b3c5
colors.tabs.indicator.error = #d95468
colors.tabs.indicator.start = #539AFC
colors.tabs.indicator.stop = #008b94
colors.tabs.odd.bg = #10151C
colors.tabs.odd.fg = #a0b3c5
colors.tabs.pinned.even.bg = #10151C
colors.tabs.pinned.even.fg = #a0b3c5
colors.tabs.pinned.odd.bg = #10151C
colors.tabs.pinned.odd.fg = #a0b3c5
colors.tabs.pinned.selected.even.bg = #41505e
colors.tabs.pinned.selected.even.fg = #a0b3c5
colors.tabs.pinned.selected.odd.bg = #41505e
colors.tabs.pinned.selected.odd.fg = #a0b3c5
colors.tabs.selected.even.bg = #41505e
colors.tabs.selected.even.fg = #a0b3c5
colors.tabs.selected.odd.bg = #41505e
colors.tabs.selected.odd.fg = #a0b3c5
https://meet.google.com: content.desktop_capture = true
https://vdo.ninja: content.desktop_capture = true
https://www.estrategiaconcursos.com.br: content.geolocation = false
https://www.speedtest.net: content.geolocation = true
https://meet.google.com: content.media.audio_capture = true
https://vdo.ninja: content.media.audio_capture = true
https://meet.google.com: content.media.audio_video_capture = true
https://vdo.ninja: content.media.audio_video_capture = true
https://meet.google.com: content.media.video_capture = true
https://vdo.ninja: content.media.video_capture = true
https://webcamtests.com: content.media.video_capture = true
https://meet.google.com: content.notifications.enabled = true
https://www.estrategiaconcursos.com.br: content.notifications.enabled = false
https://www.kabum.com.br: content.notifications.enabled = true
https://www.reddit.com: content.notifications.enabled = true
https://www.tiktok.com: content.notifications.enabled = true
https://www.vunesp.com.br: content.notifications.enabled = false
content.pdfjs = true
https://outlook.live.com?mailtouri=%25s: content.register_protocol_handler = true
hints.selectors = {"all": ["a", "area", "textarea", "select", "input:not([type=\"hidden\"])", "button", "frame", "iframe", "img", "link", "summary", "[contenteditable]:not([contenteditable=\"false\"])", "[onclick]", "[onmousedown]", "[role=\"link\"]", "[role=\"option\"]", "[role=\"button\"]", "[role=\"tab\"]", "[role=\"checkbox\"]", "[role=\"menuitem\"]", "[role=\"menuitemcheckbox\"]", "[role=\"menuitemradio\"]", "[role=\"treeitem\"]", "[aria-haspopup]", "[ng-click]", "[ngClick]", "[data-ng-click]", "[x-ng-click]", "[tabindex]:not([tabindex=\"-1\"])"], "code": [":not(pre) > code", "pre"], "images": ["img"], "inputs": ["input[type=\"text\"]", "input[type=\"date\"]", "input[type=\"datetime-local\"]", "input[type=\"email\"]", "input[type=\"month\"]", "input[type=\"number\"]", "input[type=\"password\"]", "input[type=\"search\"]", "input[type=\"tel\"]", "input[type=\"time\"]", "input[type=\"url\"]", "input[type=\"week\"]", "input:not([type])", "[contenteditable]:not([contenteditable=\"false\"])", "textarea"], "links": ["a[href]", "area[href]", "link[href]", "[role=\"link\"][href]"], "media": ["audio", "img", "video"], "url": ["[src]", "[href]"]}
tabs.background = true
url.searchengines = {"DEFAULT": "https://duckduckgo.com/?q={}", "a": "https://wiki.archlinux.org/?search={}", "ab": "https://bugs.archlinux.org/?project=5&string={}", "ap": "https://www.archlinux.org/packages/?sort=&q={}", "g": "http://www.google.com/search?hl=en&source=hp&ie=ISO-8859-l&q={}", "gh": "https://github.com/search?q={}&type=Code", "w": "https://en.wikipedia.org/w/index.php?search={}", "yt": "https://www.youtube.com/results?search_query={}"}`

And Yeah, :version information are the same in both cases

**Comment by dantearaujo1** [comment]
Yeah, :version information are the same in both cases! 

[config-diff.txt](https://github.com/qutebrowser/qutebrowser/files/12148929/config-diff.txt)
