### ISSUE TITLE
qtwebengine 6 macOS scrolling 

### ISSUE THREAD

**Issue by tomoakley** [qutebrowser/qutebrowser#7810]
**Version info**:
qutebrowser v2.5.4
Git commit: 6d84462d6-dirty on main (2023-07-25 11:00:33 +0200)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.10.0
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0.1
adblock: 0.6.0
objc: 9.2
PyQt6.QtWebEngineCore: 6.5.0
pdf.js: 3.8.162 (bundled)
sqlite: 3.42.0
QtNetwork SSL: Secure Transport, macOS Ventura (13.4)

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Scrolling in Qutebrowser when using qtwebengine 6 (not built from source) in macOS feels weird; when using a trackpad and 2 finger scrolling on another browser (or any native macOS app), you can scroll using inertia scrolling and then quickly stop the scroll by putting two fingers back on the trackpad. On Qutebrowser with qtwebengine 5 this worked and scrolling felt pretty normal (i.e compared to other macOS apps) but on 6 it feels wrong.

Fully appreciate this could well be a Qt issue but wasn't sure where to post an issue for that.

**How to reproduce**
Any website where scrolling is neccesary, and a Mac computer with a trackpad (probably also reproducible with a Magic Mouse but I don't have one to try).

**Comment by The-Compiler** [comment]
I'm afraid I won't be able to reproduce this, so I can't really say more based on only "feels wrong" :wink:

By any chance, is this what you're seeing? https://bugreports.qt.io/secure/attachment/71525/brokenwebivew.mov.mp4

From here: [[QTBUG-67716] Weird animation on WebView (WebEngine) on macOS when dragging pass boundaries - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-67716)

Fixed in Qt 6.6 apparently: [Improve rubber-banding in QT WebEngine Pages (Ida0ca19d) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/476530)

**Comment by tomoakley** [comment]
> I'm afraid I won't be able to reproduce this, so I can't really say more based on only "feels wrong" 😉
> 
> By any chance, is this what you're seeing? https://bugreports.qt.io/secure/attachment/71525/brokenwebivew.mov.mp4
> 
> From here: [[QTBUG-67716] Weird animation on WebView (WebEngine) on macOS when dragging pass boundaries - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-67716)
> 
> Fixed in Qt 6.6 apparently: [Improve rubber-banding in QT WebEngine Pages (Ida0ca19d) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/476530)

haha no worries! it's difficult to describe. But whereas on qt5, putting two fingers back on the trackpad when the inertial scroll is still moving stops the scroll event, on qt6, the interial scroll continues until it runs out of momentum.

I could try to do a screen recording of this in both qt5 and qt6, and then also record my fingers and put the screen recording and video of my finders side by side to show what I mean. I'm away tomorrow and it's late in the UK but I will try and do this on Friday or Saturday.

It's not exactly what those videos show although I think I can reproduce that. It might be related though.

It's a very minor issue and definetely shoudln't block any releases of Qutebrowser with qt6. But just wanted to flag it. In any case, most of my scrolling is with j/k and other keys but sometimes I use the trackpad as well.

**Comment by The-Compiler** [comment]
That change sets a "momentum phase" based on what happened on the Qt side of things, so I'm assuming it's the same issue and will be fixed by that change. In either case, this is most definitely an upstream bug, as mouse scrolling is handled by Qt and not qutebrowser.

**Comment by tomoakley** [comment]
> That change sets a "momentum phase" based on what happened on the Qt side of things, so I'm assuming it's the same issue and will be fixed by that change. In either case, this is most definitely an upstream bug, as mouse scrolling is handled by Qt and not qutebrowser.

Thanks, that's fair!
