### ISSUE TITLE
QT6: Bookmarks are not working, if opened via key strokes

### ISSUE THREAD

**Issue by c0dehu1k** [qutebrowser/qutebrowser#7815]
**Version info**:
qutebrowser v2.5.4
Git commit: 5344163f4 on main (2023-08-02 21:29:48 +1200)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.10.6
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: no
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.2 15 Mar 2022

**Does the bug happen if you start with `--temp-basedir`?**:
Not able to test this, using --temp-basedir doesnot show my bookmarks

**Description**
I have saved those bookmarks with old QB with qt5
open :bookmark-list
press f 
and type key combination to go to a particular link.

**How to reproduce**
I have saved those bookmarks with old QB with qt5
open :bookmark-list
press f 
and type key combination to go to a particular link.

SCreenshot
https://ibb.co/tCyVcW6

**Note: If I click on the bookmark link, it opens up.**

**Comment by The-Compiler** [comment]
Reproduced, results in a `ERR_NETWORK_ACCESS_DENIED`.

Reproducer: `qutebrowser --temp-basedir ":bookmark-add qutebrowser.org qutebrowser" qute://bookmarks ":later 500 hint --first"`

Relevant logs:

```
22:13:43 DEBUG    modes      modeman:leave:428 Leaving mode KeyMode.hint (reason: followed)
[...]
22:13:43 DEBUG    webelem    webelem:click:407 Clicking <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<a href="http://qutebrowser.org">qutebrowser</a>'> with click_target ClickTarget.normal, force_event False
22:13:43 DEBUG    webelem    webelem:click:416 Clicking via JS click()
22:13:43 DEBUG    webview    browsertab:_on_navigation_request:1151 navigation request: url http://qutebrowser.org/, type Type.link_clicked, is_main_frame True
[...]
22:13:43 DEBUG    webview    browsertab:_set_load_status:1093 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='http://qutebrowser.org/'>: LoadStatus.error
22:13:43 DEBUG    signals    signalfilter:_filter_signals:72 emitting: cur_load_status_changed(<LoadStatus.error: 4>) (tab 0)
22:13:43 ERROR    webview    webenginetab:_error_page_workaround:1525 Load error: ERR_NETWORK_ACCESS_DENIED
```

Works fine with `-s content.local_content_can_access_remote_urls true`.

We might need to change this logic:

https://github.com/qutebrowser/qutebrowser/blob/5344163f4ad025d8b76bac85c4f4bb9992dbd175/qutebrowser/browser/webelem.py#L414-L425

specifically here:

https://github.com/qutebrowser/qutebrowser/blob/5344163f4ad025d8b76bac85c4f4bb9992dbd175/qutebrowser/browser/webengine/webengineelem.py#L209-L216

to always require user interaction on `qute://` pages.

**Comment by The-Compiler** [comment]
Also see #7790

**Comment by The-Compiler** [comment]
Still broken when going back with `H` and then forward again with `L`. Might need a workaround similar to #7790 until we can do #7220.

Not sure if this is serious enough for v3.0.0, but maybe the fix is trivial.
