### ISSUE TITLE
No side menus on facebook

### ISSUE THREAD

**Issue by maccagnan** [qutebrowser/qutebrowser#7816]
qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
Devuan Chimaera.
Does the bug happen if you start with `--temp-basedir`?:yes

In Facebook, Qutebrowser no longer displays any side menus or pull down menus.  This behavior started about a week ago. I tested the same Facebook page with Firefox, and it behaves normally, whereas the same error happens in Falkon, so it might well be QtWebEngine related.

**Comment by The-Compiler** [comment]
If it happens in Falkon too, it's indeed a QtWebEngine issue. Your QtWebEngine is quite old - I'd suggest trying with a newer Qt 5.15 or with Qt 6 and qutebrowser from git main. In any case, there's nothing qutebrowser can do here.
