### ISSUE TITLE
"Kiosk" like option for qutebrowser

### ISSUE THREAD

**Issue by Linuxer3228** [qutebrowser/qutebrowser#7817]
So Firefox has the "--kiosk" command line argument which launches a window that looks like this
![firefoxkiosk](https://github.com/qutebrowser/qutebrowser/assets/140357834/5e79153c-3a04-4b82-9e0b-2a37f306438c)
I've done some digging and I don't believe there is anything like this in qutebrowser,  and I think it would be quite useful :) Apologies if this is already possible

**Comment by The-Compiler** [comment]
```
:set tabs.show never
:set statusbar.show never
```

should get you there.
