### ISSUE TITLE
With linux X11 custom keybord layout `HOME` and `END` keys trigger despite being remapped

### ISSUE THREAD

**Issue by VuiMuich** [qutebrowser/qutebrowser#7822]
**Version info**:
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 6.5.1, based on Chromium 108.0.5359.220 (from override)
Qt: 6.5.1

[Full version info](https://bpa.st/Y5IQ)

**Does the bug happen if you start with `--temp-basedir`?**:
not tested as I don't suppose to make a difference for this bug

**Description**
May Laptop (Lenovo Carbon X1 Gen2) has very oddly `Home` and `End` keys where usually the `Caps Lock` would be.
As I also use a custom xkb map which is based on the German Neo layout (see below) I have rebound these keys to `ISO_Level3_Switch`.

Now **the bug** is, that in `qutebrowser` both actions trigger the `Home`/`End` scrolling to the tob/bottom or moving the cursor *AND* the layer switch;  it happens in qt5 and qt6.
So far `qutebrowser` is the only app where this happens to me, I tried `librewolf` and `ungoogled-chromium` just to reference some other browsers.

**Expected Behaviour**
`qutebrowser` should respect the system remap of keysyms, except otherwise configured explicitly.

**How to reproduce**
Here is a snippet of the xkb symbols file (for the full layout please refer to https://www.maximilian-schillinger.de/konfiguration.html, just note that the method described there is not recommended and the custom layout should be put in `/usr/share/X11/xkb/symbols/custom` instead):
```
xkb_symbols "vou" {

    include "de(neo_base)"

    name[Group1]= "German (VOU)";

    include "shift(both_capslock)"
    include "level3(caps_switch)"
    // use quote key (a-umlaut on German keyboards) as Mod3 switch
    // include "level3(quote_switch)"
    include "level5(lsgt_switch_lock)"
    include "level5(ralt_switch_lock)"

    // actual layout omitted as it should not be relevant

    // This is the `Ä` key on a QUERTZ keyboard
    key <AC11> { type[Group1]="ONE_LEVEL", symbols[Group1] = [ ISO_Level3_Shift ] };

    // The following two lines are only for the Lenovo X1 carbon Gen 2, as it places `Home` and `End` in the spot of `Caps_Lock`
    key <END>  { type[Group1]="ONE_LEVEL", symbols[Group1] = [ ISO_Level3_Shift ] };
    key <HOME> { type[Group1]="ONE_LEVEL", symbols[Group1] = [ ISO_Level3_Shift ] };
};
```
I think another minimal layout to reproduce this issue might be this (copied from https://nixos.org/manual/nixos/stable/#custom-xkb-layouts):
```
xkb_symbols "qutebrowser-bug"
{
  include "us(basic)"            // includes the base US keys, you might want to replace this with your usually used layout
  include "level3(ralt_switch)"  // configures right alt as a third level switch

  // This is the `Ä` key on a QUERTZ keyboard
  key <AC11> { type[Group1]="ONE_LEVEL", symbols[Group1] = [ ISO_Level3_Shift ] };

  // The following two lines are only for the Lenovo X1 carbon Gen 2, as it places `Home` and `End` in the spot of `Caps_Lock`
  key <END>  { type[Group1]="ONE_LEVEL", symbols[Group1] = [ ISO_Level3_Shift ] };
  key <HOME> { type[Group1]="ONE_LEVEL", symbols[Group1] = [ ISO_Level3_Shift ] };

  key <LatA> { [ a, A, Greek_alpha ] };
  key <LatB> { [ b, B, Greek_beta  ] };
  key <LatG> { [ g, G, Greek_gamma ] };
  key <LatD> { [ d, D, Greek_delta ] };
  key <LatZ> { [ z, Z, Greek_zeta  ] };
};
```
After putting this in `/usr/share/X11/xkb/symbols/custom` you should be able to set this layout with `setxkbmap custom qutebrowse-bug`.

For further reference this is the output of `xev -events keyboard` (key seqence `Ä` `End` `Home` `CTRL-C`):
```
✦ >>> nix-shell -p xorg.xev --run 'xev -events keyboard'
Outer window is 0x6e00001, inner window is 0x6e00002

KeymapNotify event, serial 24, synthetic NO, window 0x0,
    keys:  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

KeyPress event, serial 25, synthetic NO, window 0x6e00001,
    root 0x40d, subw 0x0, time 22560001, (-559,823), root:(724,881),
    state 0x0, keycode 48 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x6e00001,
    root 0x40d, subw 0x0, time 22560081, (-559,823), root:(724,881),
    state 0x80, keycode 48 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x6e00001,
    root 0x40d, subw 0x0, time 22566367, (-559,823), root:(724,881),
    state 0x0, keycode 110 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 48
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x6e00001,
    root 0x40d, subw 0x0, time 22566509, (-559,823), root:(724,881),
    state 0x80, keycode 110 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 48
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x6e00001,
    root 0x40d, subw 0x0, time 22567271, (-559,823), root:(724,881),
    state 0x0, keycode 115 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 48
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x6e00001,
    root 0x40d, subw 0x0, time 22567405, (-559,823), root:(724,881),
    state 0x80, keycode 115 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 48
    XLookupString gives 0 bytes:
    XFilterEvent returns: False
^C
```

**Comment by VuiMuich** [comment]
Ok, I can reproduce with both `--temp-basedir` and with the nix package `libsForQt5.falkon` which installs Falkon version 23.04.1 with QTWebEngine-Version 5.15.13 (NixOS 23.05 Stoat).
So I guess this needs to be reported upstream at QT.
Would you mind giving me a pointer where to report this exactly?

**Comment by The-Compiler** [comment]
https://bugreports.qt.io/ is where the Qt bugtracker lives at.

Does it reproduce in the UI (e.g. the command input in qutebrowser) too? If so, "GUI: Basic Input System (keyboard, mouse, touch)" would likely be the right component to use, otherwise (if only inside web contents), "WebEngine".

**Comment by VuiMuich** [comment]
No, the command input is unaffected.
I didn't find a browser that comes with QtWebKit anymore - at least not by default for a quick test.

I'll have a look if there is a related issue at qt.io – there is a lot when searching for `xkb` :grimacing:

**Comment by VuiMuich** [comment]
For reference: [QTBUG-115844](https://bugreports.qt.io/browse/QTBUG-115844)

**Comment by VuiMuich** [comment]
So, I just saw this was resolved upstream for gt6.5.3 and qt6.7.x last week. Now I am trying to figure out how I could use 6.5.3 in my nixos install...

**Comment by The-Compiler** [comment]
> So, I just saw this was resolved upstream for gt-6.5.3 and qt-6.7.x last week.

And 6.6 as well!

> ~Now I am trying to figure out how I could use 6.5.3 in my nixos install...~ Looks like it really is unfeasible to build qtwebengine on my machine, so I guess the waiting game continues 😓

For what it's worth, 6.5.3 [is scheduled](https://wiki.qt.io/Qt_6.5_Release) for September 5th, so hopefully in 1-2 weeks you'll have the fixed version!

**Comment by VuiMuich** [comment]
🤔 I See only this
> Fix Version/s:
> 6.5.3, 6.7.0 FF

Of course it would make sense, that 6.5.3 changes would be in 6.6 as well but I know to few of the qt project to deduct anything.

**Comment by The-Compiler** [comment]
Ah, weird. I was looking at the [6.6 cherry pick](https://codereview.qt-project.org/c/qt/qtwebengine/+/497483) which was merged. Not sure why the bot didn't update the field in the bug tracker.

**Comment by VuiMuich** [comment]
Ah, I see.
