### ISSUE TITLE
Qutebrowser does not recognize mousewheel scroll

### ISSUE THREAD

**Issue by Lugrol** [qutebrowser/qutebrowser#7825]
**Version info**:
qutebrowser v2.5.4
Git commit: 89b911050 on main (2023-08-08 17:16:47 +0200)
Backend: QtWebEngine 6.3.2, based on Chromium 94.0.4606.126 (from api)
Qt: 6.3.2 (compiled 6.3.1)

**Config-diff**:
bindings.commands = {"normal": {",M": "spawn --detach mpv --fullscreen {url}", ",ff": "spawn --detach firefox {url}", ",m": "hint links spawn --detach mpv --fullscreen {hint-url}", ",qr": "spawn --detach qr {url}", "cl": "clear-messages", "yl": "hint links yank"}}
completion.show = auto
editor.command = ["konsole", "--qwindowgeometry", "500x300+50+50", "-e", "vim", "{}"]
statusbar.show = in-mode
tabs.show = switching
window.hide_decoration = true

**Does the bug happen if you start with `--temp-basedir`?**:
no...

**Description**
When I try to scroll the page, or use the wheel scroll in any way, qutebrowser does not recognize the input.
This screenshot from [onlinemictest](https://www.onlinemictest.com/mouse-test) ilustrates it. The first one is from `qutebrowser`, the second one is from `qutebrowser --temp-basedir`.
![from qutebrowser](https://github.com/qutebrowser/qutebrowser/assets/138042003/2b881d74-093a-44d0-bf2b-d59988109b65)
![from qutebrowser --temp-basedir](https://github.com/qutebrowser/qutebrowser/assets/138042003/800d504b-0f5f-4a1f-ba17-68996ff2cf5f)

**How to reproduce**
I would love to answer this, but do not know the nature of the issue...

**Comment by ethanalker** [comment]
FYI, your link to onlinemictest.com is mispelled. It should be [https://www.onlinemictest.com/mouse-test/](https://www.onlinemictest.com/mouse-test/).

Also, it may be helpful to include your qutebrowser configuration to help diagnose the issue. Working with `--temp-basedir` implies something in your configuration is causing the issue.

**Comment by The-Compiler** [comment]
Works fine for me. Did you do the "Point your mouse cursor at the mouse illustration" part in both cases?

Can you please indeed show your `:config-diff`, and also make sure that the `:version` info is the same in both cases?

**Comment by Lugrol** [comment]
Thanks for the attention, everyone.
Thanks @ethanalker for the correction.
Thanks @The-Compiler for pointing out how could I improve my report.

I did point the mouse cursor at the mouse illustration, it wasn't working on any site. After some testing, quiting and re-opening, it started working again. Sorry for the inconvenience.

**Comment by pjht** [comment]
I've been having the same issue myself for months actually. Scroll works fine when qutebrowser first starts, but will eventually break. Even the scrollbar on the side doesn't work, though I can still scroll with the keyboard.

Here's my version info if it helps:
qutebrowser v3.2.0
Git commit: 
Backend: QtWebEngine 6.7.1
  based on Chromium 118.0.5993.220
  with security patches up to 124.0.6367.202 (plus any distribution patches)
  (source: api)
Qt: 6.7.1

**Comment by The-Compiler** [comment]
@pjht Scrolling via mouse or scroll bar is all handled by the underlying QtWebEngine/Chromium, there isn't really anything qutebrowser can do here. Given that nobody mentioned this so far, it sounds like an issue with your setup, but I have no idea what the issue would be unfortunately.

**Comment by pjht** [comment]
I mean isn't this the exact problem that the original user reported? Qutebrowser failing to see mouse scroll? The time requirement of it for me even explains how a restart fixed it. Lugrol probably just had their browser open long enough to trigger it.

**Comment by The-Compiler** [comment]
It could be indeed - but given the original issue is almost a year old with a Qt that's almost 2 years old, it might as well be a totally different issue that just shows up in the same way.
