### ISSUE TITLE
javascript error in view_in_mpv userscript.

### ISSUE THREAD

**Issue by GasparVardanyan** [qutebrowser/qutebrowser#7838]
**Version info**:
```
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.14, based on Chromium 87.0.4280.144
Qt: 5.15.10 (compiled 5.15.8)
```

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**

When I run:
```
:spawn --userscript view_in_mpv
```
in qutebrowser when I'm on a youtube video, mpv opens the video, on video (in qb) appears this text:
```
Opening page with: mpv --force-window --no-terminal --keep-open=yes --ytdl

In order to restore this particular video [click here](javascript: restore_video(this, 0)).
```
but clicking the button 'click here' I get:
```
Uncaught ReferenceError: restore_video is not defined
    at HTMLAnchorElement.onclick
```
in console.

**How to reproduce**
Open any youtube video, run:
```
:spawn --userscript view_in_mpv
```
, open console and the press the 'click here' button.

**Comment by toofar** [comment]
Strange that no-one else has pointed that out before. Could you try changing the [jseval line](https://github.com/qutebrowser/qutebrowser/blob/7961cf7/misc/userscripts/view_in_mpv#L140) like so:

```diff
@@ -137,7 +136,7 @@
 printjs() {
     js | sed 's,//.*$,,' | tr '\n' ' '
 }
-echo "jseval -q $(printjs)" >> "$QUTE_FIFO"
+echo "jseval -q -w main $(printjs)" >> "$QUTE_FIFO"

 msg info "Opening $QUTE_URL with mpv"
 "${video_command[@]}" "$@" "$QUTE_URL"
 ```
 
 Eg `-w main` in there. That makes it work for me.

**Comment by toofar** [comment]
Fix seemed pretty clear to me once I looked at it, so I've pushed a fix. Although I'm not sure the "replacement" logic is working quite as intended on webengine.
Tested on Qt6, Qt5 and webkit (where youtube barely works).

**Comment by GasparVardanyan** [comment]
Thank you, works, but now running the script multiple times creates multiple info bars on video, even if I use the 'click here' button every time: https://i.imgur.com/ivmO9yM.png

**Comment by toofar** [comment]
Running the script twice without reloading the page just doesn't seem to be supported. It has objects that it stores videos and "replacement" objects in and it doesn't save them to some global place and account for them when being re-run, it just scans everything anew and overwrites any old references. So if anything from a previous run hasn't been reset already it'll just stay that way.
