### ISSUE TITLE
greasemonkey not redirecting region banned URLs

### ISSUE THREAD

**Issue by mortezadadgar** [qutebrowser/qutebrowser#7840]
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

**How to reproduce**
1. living in a restricted country which youtube is not accessible
2. create ~/.config/qutebrowser/greasemonkey/redicrects.js
3. add following script:
```
// ==UserScript==
// @name           Youtube redirector
// @namespace      Me
// @match          https://youtube.com/*
// @run-at         document-start
// ==/UserScript==

location.href = location.href.replace("https://youtube.com/*", "https://inv.pistasjis.net/feed/popular");
alert("hi invidious!");
```
4. not receiving dialog

**Comment by bitraid** [comment]
This should work:
```js
// ==UserScript==
// @name           Youtube redirector
// @namespace      Me
// @match          https://*.youtube.com/*
// @run-at         document-start
// ==/UserScript==

top.location.hostname = "inv.pistasjis.net";
alert("hi invidious!");
```

**Comment by The-Compiler** [comment]
The problem is the filename: Greasemonkey scripts should be named `*.user.js`. We should probably document that somewhere though, and maybe also show a warning or something.

**Comment by mortezadadgar** [comment]
> This should work:
> 
> ```js
> // ==UserScript==
> // @name           Youtube redirector
> // @namespace      Me
> // @match          https://*.youtube.com/*
> // @run-at         document-start
> // ==/UserScript==
> 
> top.location.hostname = "inv.pistasjis.net";
> alert("hi invidious!");
> ```

sadly not

> The problem is the filename: Greasemonkey scripts should be named `*.user.js`. We should probably document that somewhere though, and maybe also show a warning or something.

without user.js scripts works as well for instance:
```
// ==UserScript==
// @name           Test redirector
// @namespace      Me
// @match          https://www.google.com/*
// @run-at         document-start
// ==/UserScript==

location.href = location.href.replace("https://www.google.com", "https://duckduckgo.com");
```

in my point of view the problem is that timed out requests do not trigger greasemonkey scripts so it won't match any urls

**Comment by bitraid** [comment]
You might try this: https://codeberg.org/mister_monster/qutebrowser-url-mutator

**Comment by bitraid** [comment]
@The-Compiler I think the `user.js` suffix is only needed for the firefox add-on, so it can recognize and install the script when its URL is clicked.

**Comment by The-Compiler** [comment]
My bad. I thought we required that suffix as well, but apparently not.

**Comment by The-Compiler** [comment]
@mortezadadgar Can you be more specific about what happens with @bitraid's userscript above, and what exactly you are doing? Your original one is broken because it uses `@match https://youtube.com/*` while visiting that redirects to `www.youtube.com` instead. I don't think there is a qutebrowser bug here.

**Comment by mortezadadgar** [comment]
> @mortezadadgar Can you be more specific about what happens with @bitraid's userscript above, and what exactly you are doing? Your original one is broken because it uses `@match https://youtube.com/*` while visiting that redirects to `www.youtube.com` instead. I don't think there is a qutebrowser bug here.

that script seems to work but I don't see why a greasemonkey won't?
I tested @toofar script which match https://*.youtube.com/* and still I don't see anything being redirected, well as I said before qutebrowser doesn't see a single request successfully being send to youtube as it's not accessible in my region (greasemoneky run after first request with status 200 received?)

**Comment by The-Compiler** [comment]
Can you please reproduce this and run `:report` so I can take a look at the debug logs? If it's blocked in a way that no youtube.com page ever loads, then yes, a greasemokey script running on youtube.com also won't run.

**Comment by mortezadadgar** [comment]
reported the issue with my name

**Comment by The-Compiler** [comment]
```
load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://www.youtube.com/index'&gt;: LoadStatus.error
Load error: ERR_CONNECTION_TIMED_OUT
```

So yeah, the page never even loads in the first place, and thus no Greasemonkey script runs on it.
