### ISSUE TITLE
Add support for `.M4A` audio file playback

### ISSUE THREAD

**Issue by zedkaido** [qutebrowser/qutebrowser#7844]
Currently `.M4A` files go straight to the download page, whereas `.MP3` files can be played. I suppose that is because there is no support for playing `.M4A` in `<audio>` elements as of now.

Sample (.MP3) link: https://music.zedkaido.com/can-can-offenbach-is-in-the-house.mp3
Sample (.M4A) link: https://music.zedkaido.com/can-can-offenbach-is-in-the-house.m4a 

It would be awesome if we could add support for `.M4A` audio playback 🙂

**Comment by toofar** [comment]
Seems to work for me on both Qt5 and Qt6. Maybe one of MPEG-4 or AAC are one of those proprietary codecs.
Where did you get your webengine from? Looks like you forgot to fill in the requested version info in the issue template! A lot of places that distribute webengine (like PyQt via PyPI) don't compile it with proprietary codecs included.

**Comment by The-Compiler** [comment]
Indeed I can reproduce this with Qt binaries in a virtualenv. This is not going to change - you'll need to make sure you have a Qt with proprietary codecs available and it'll work fine there.
