### ISSUE TITLE
With `PyQt6`, the navigation context menu does not have any icon

### ISSUE THREAD

**Issue by emanuele6** [qutebrowser/qutebrowser#7855]
**Version info**:
```
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2
```
With `QUTE_QT_WRAPPER=PyQt5`:
```
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 5.15.14, based on Chromium 87.0.4280.144
Qt: 5.15.10 (compiled 5.15.8)
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**

When using `PyQt6` (default for `qutebrowser v3.0.0`) as `QUTE_QT_WRAPPER`, the default context menu does not have icons for its actions. With `PyQt5` (default in previous versions of `qutebrowser`), the menu had icons for the `Forward`, `Back`, and `Refresh` actions.

**How to reproduce**
|`QUTE_QT_WRAPPER=PyQt5 qutebrowser -T` | `QUTE_QT_WRAPPER=PyQt6 qutebrowser -T` |
| --------------------- | ---------------------- |
| ![pyqt5](https://github.com/qutebrowser/qutebrowser/assets/20175435/a131b407-4519-4384-b978-78be74bcd6b7) | ![pyqt6](https://github.com/qutebrowser/qutebrowser/assets/20175435/a14e65a4-8b34-4ba9-bac9-01fca4542b1b) |

**Comment by The-Compiler** [comment]
Reported upstream: [[QTBUG-119722] [REG 5 → 6] Default context menu is missing icons - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-119722)
