### ISSUE TITLE
Blurry on Wayland when using multiple screens with different scaling value

### ISSUE THREAD

**Issue by stacyharper** [qutebrowser/qutebrowser#7857]
Qutebrowser --version : https://paste.sr.ht/~stacyharper/c54344ce5dd335b1b18fe42f080c70fa31cc4d97

swaymsg -t get_outputs : https://paste.sr.ht/~stacyharper/a7cbe15ebfa63666511213210f87a1fd15d7eb00

Hey there,

Sometime I got a setup with two screen with multiple scaling value. New qutebrowser surface on my screen with 1.4 scaling are blurry at first. Then when I move my mouse over the second screen (with 1.0 scaling), the window is refreshed, and the blur problem is fixed. This is particularly annoying because I use tabs_are_windows, so every new tab is blurry.

**Comment by The-Compiler** [comment]
Nothing qutebrowser will be able to do about this, most likely you'll see this in any Qt application.

According to the comments here, this should work better with Qt 6.6 ([scheduled for September](https://wiki.qt.io/Qt_6.6_Release)): [[QTBUG-101656] Delayed rescaling when moving from 1x scale monitor to higher scale monitor - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-101656)
