### ISSUE TITLE
Handler-based API?

### ISSUE THREAD

**Issue by Eolien55** [qutebrowser/qutebrowser#7860]
Could a handler-based API be considered for Qutebrowser, like in LuaKit?

If you don't know, LuaKit uses a set of handlers to implement many features. You can register a handler for `navigation-request`, which will be triggered everytime LuaKit tries to access a URL. You can do a lot of things, like: redirecting by editing the url if it matches a certain pattern (as per #5476), handle another protocol (gemini, gopher, spartan, etc.), convert Markdown to HTML, etc. It's a very simple, but very powerful mechanism.

Also, the library API (all commands, search-engines, chrome:-pages, etc.) can be modified as the user wishes. I.e., since in Lua everything is a dictionary, the user can replace parts of the API to better suit their needs. For example, I could replace the `{}` placeholders in searchengines by modifying the Lua code responsible for handling those, and replace them with numbered placeholders (`{1}`, `{2}`, etc.), so I could have a search-engine wikipedia `https://{1}.wikipedia.org/wiki/{2-}`, and use it like `en Linux` for the english-language Linux page, `eo Linux` for the Esperanto-language one, and so on and so forth.

Maybe this isn't strictly applicable, because the OOP model of Lua and Python are very different, and I believe classes (not objects) are read-only, for the user at least.

So:
- Could such an API be considered?
- Would it be compatible with other goals of Qutebrowser? (maybe YAML config is incompatible with such an API?)
- Is it technically possible?

**Comment by The-Compiler** [comment]
As for the handler thing, that just sounds like pretty much any kind of extension API - see #30 and #35. 

Code monkeypatching things in qutebrowser would in theory be possible (even on classes). Some projects even already do this with a `config.py`, but it will definitely be discouraged.
