### ISSUE TITLE
`QtWebEngineProcess`s continue running after exiting qutebrowser due to detached subprocess

### ISSUE THREAD

**Issue by balejk** [qutebrowser/qutebrowser#7861]
**Version info**:

```
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.4
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 3.2.146 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 1.1.1t  7 Feb 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Mesa, 4.3 (Compatibility Profile) Mesa 23.1.3
Platform: Linux-6.4.11_1-x86_64-with-libc, 64bit
Linux distribution: Void Linux (void)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /tmp/qutebrowser-basedir-ob3q_92c/cache
config: /tmp/qutebrowser-basedir-ob3q_92c/config
data: /tmp/qutebrowser-basedir-ob3q_92c/data
runtime: /tmp/qutebrowser-basedir-ob3q_92c/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:03
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

When running a subprocess via `spawn --detach` and closing `qutebrowser`, several `QtWebEngineProcess`s continue running, until the subprocess terminates. This probably shouldn't be the case, if the process was really fully detached.

**How to reproduce**

1. Start `qutebrowser --temp-basedir`.
2. Open a webpage containing video links.
3. Issue `:hint links spawn --detach mpv {hint-url}` (`mpv` required).
4. Close `qutebrowser`.
5. Investigate running process (e. g. using `htop`) and observe a few instances of `QtWebEngineProcess` running:
```
├─ QtWebEngineProcess --type=zygote --no-zygote-sandbox --application-name=qutebrowser --webengine-schemes=qute:lL;qrc:sV --lang=en
├─ QtWebEngineProcess --type=zygote --application-name=qutebrowser --webengine-schemes=qute:lL;qrc:sV --lang=en
│  └─ QtWebEngineProcess --type=zygote --application-name=qutebrowser --webengine-schemes=qute:lL;qrc:sV --lang=en
├─ mpv https://www.youtube.com/watch?v=N79au5Xq65s
```
6. Quit the subprocess and observe the Qt processes exit.

**Comment by balejk** [comment]
Additional information: the subprocess doesn't mind if the Qt processes are killed.

Also, the number of running Qt processes doesn't seem to depend on the number of subprocesses (if I run `mpv` twice as described above, still there are only 3 Qt processes). In this case, they seem to exit with the termination of the last subprocess.

**Comment by The-Compiler** [comment]
Those are Chromium's [Zygote processes](https://chromium.googlesource.com/chromium/src/+/master/docs/linux/zygote.md):

> A zygote process is one that listens for spawn requests from a main process and forks itself in response. Generally they are used because forking a process after some expensive setup has been performed can save time and share extra memory pages.

and

> Instead, we exec the prototypical renderer at the beginning of the browser execution. When we need more renderers, we signal this prototypical process (the zygote) to fork itself.

Not sure what causes them to stick around when there is a subprocess. This smells like a bug somewhere in QProcess/QtWebEngine/Chromium rather than something qutebrowser does wrong. Or it might even just be an unfortunate interaction somewhere with how those things work.

**Comment by The-Compiler** [comment]
Reproduced with a minimal example:

```cpp
#include <QtWidgets/QApplication>
#include <QtWebEngineWidgets/QWebEngineView>
#include <QtCore/QProcess>
#include <QtCore/QTimer>

int main(int argc, char *argv[]) {
    QApplication app(argc, argv);
    QWebEngineView view;
    view.load(QUrl("https://qt.io"));
    view.show();

    QProcess::startDetached("qtcreator");
    QTimer::singleShot(5000, &app, &QApplication::quit);
    return app.exec();
}
```

and reported upstream: [[QTBUG-116856] Using `QProcess::startDetached()` keeps Zygote processes around after application quits - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-116856)
