### ISSUE TITLE
QB doesn't start anymore and prevents the PC from shutting down when tried.

### ISSUE THREAD

**Issue by magnetophon** [qutebrowser/qutebrowser#7869]
**Version info**:
qutebrowser v3.0.0
Git commit:
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.10.12
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 3.9.179 (/nix/store/wina0bcmiw1z921hb4hijfr18ajh2sy6-source/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.10 1 Aug 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.1.5
Platform: Linux-6.1.46-x86_64-with-glibc2.37, 64bit
Linux distribution: NixOS 23.11 (Tapir) (nixos)
Frozen: False
Imported from /nix/store/zr5g1863b0dri5s422c5azsaxgsv872n-qutebrowser-3.0.0/lib/python3.10/site-packages/qutebrowser
Using Python from /nix/store/wlxpsdzfvdanfzh704qmgyzb42qvy4fr-python3-3.10.12/bin/python3
Qt library executable path: /nix/store/vdj63pdmwss2vvxliris26wnmr8ydyhi-qtbase-6.5.2/libexec, data path: /nix/store/vdj63pdmwss2vvxliris26wnmr8ydyhi-qtbase-6.5.2

Paths:
cache: /home/bart/.cache/qutebrowser
config: /home/bart/.config/qutebrowser
data: /home/bart/.local/share/qutebrowser
runtime: /run/user/1001/qutebrowser
system data: /nix/store/zr5g1863b0dri5s422c5azsaxgsv872n-qutebrowser-3.0.0/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/bart/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I was using QB and it hung up on me. 
I was not able to ``kill``, ``xklil``l or ``kill`` -9 it, not even as root.
When I rebooted, in the console, I got some messages about QB related processes still running.
When the OS was done waiting and had killed them forcefully, I got messages about filesystems not able to unmount.
After about 10 minutes I gave up and forcefully rebooted using the power switch.

Now, when I try to run QB, it hangs at startup and when I try to shut down the PC, QB prevents it.
when I boot / reboot without using QB, all is good.

**How to reproduce**
Unknown.

**Comment by The-Compiler** [comment]
Huh, weird. So what happens when you run `qutebrowser --temp-basedir` in a terminal? It just hangs with no window showing up and no output?

What gets shown when you start it with `--debug`? What gets printed when you `kill -USR1` it once it hangs?

**Comment by The-Compiler** [comment]
Looks like it runs just fine according to the debug logs at least... What does the log say with `--temp-basedir --debug` then? Any change there when sending a SIGUSR1?

**Comment by magnetophon** [comment]
In the meantime I have found out that there seems to be a hardware problem that caused this. 

Closing for now, I’ll reopen if needed. 

Thanks for the quick replies and sorry for the noise.

**Comment by The-Compiler** [comment]
No worries and thanks for the update!
