### ISSUE TITLE
Cannot insert-text starting with a dash

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#7875]
**Version info**:

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

The command `:insert-text -foo` fails with `ERROR: insert-text: The following arguments are required: text`. It seems to interpret the dash as a flag, but I can't find a way to escape it. `:insert-text '-foo'` and `:insert-text \-foo` interpret the quotes/backslashes literally.

**How to reproduce**

Open https://start.duckduckgo.com/, focus the input box, type `:insert-text -foo`.

**Comment by The-Compiler** [comment]
Like with a shell: `:insert-text -- -foo` :wink:

**Comment by rcorre** [comment]
Argh seems obvious in retrospect. Thanks!
