### ISSUE TITLE
Drag and drop not working in Hyperland

### ISSUE THREAD

**Issue by LamprosPitsillos** [qutebrowser/qutebrowser#7878]
https://github.com/hyprwm/Hyprland/issues/3136#issue-1877874938
Since this is a cross post , all the data are in the first post.
TLDR:
Drag and drop doesn't work on my Hyprland system.

**Comment by The-Compiler** [comment]
See bee8430 / #7827. Should work fine once Qt 6.5.2 is released, [planned for](https://lists.qt-project.org/pipermail/releasing/2023-August/002993.html) September 19th. If it still doesn't work then, please comment and I'll reopen, but chances are things will be fine with that.

**Comment by dr-carlos** [comment]
> See [bee8430](https://github.com/qutebrowser/qutebrowser/commit/bee84309c5b5e34b9e57e5bfc15766c345dcadc7) / #7827. Should work fine once Qt 6.5.2 is released, [planned for](https://lists.qt-project.org/pipermail/releasing/2023-August/002993.html) September 19th. If it still doesn't work then, please comment and I'll reopen, but chances are things will be fine with that.

Running Qtile on Arch Linux with latest Qt6 version 6.5.2 and still having this issue.
Let me know if you need more diagnostic info or if I should make a new issue.

**Comment by The-Compiler** [comment]
My bad, that was a typo - Qt 6.5.3 is what I meant.
