### ISSUE TITLE
Is there now a way to add a custom external file chooser in the download filename prompt menu? #feature request

### ISSUE THREAD

**Issue by Twix53791** [qutebrowser/qutebrowser#7883]
Hi, I am posting this issue because I am a bit lost about this question. My confused mind believes it has seen than the possibility of picking an external program to set the location where download files was now built-in qutebrowser. But maybe I am confusing with the filepicker setting?

Actually, on my computer, I have coded a small hack to add the possibility of downloading files with ranger from qutebrowser, and I am wondering if this is now useless as qutebrowser offers now this possibility or if I need to make a pull request to push this fonctionnality... 

Thanks for clearing my mind!

**Comment by The-Compiler** [comment]
From the [changelog](https://github.com/qutebrowser/qutebrowser/blob/main/doc/changelog.asciidoc):

> New `:prompt-fileselect-external` command which can be used to spawn an external file selector (`fileselect.folder.command`) from download filename prompts (bound to <Alt+e> by default).

So configure that, and then press Alt+e in the file select prompt:

![image](https://github.com/qutebrowser/qutebrowser/assets/625793/1d27d131-9fa2-43f4-a9db-7736faec4e7c)

**Comment by Twix53791** [comment]
You are such fast @The-Compiler ! During the elapsed time, from my previous post, me too also I found my answer looking at the qutebrowser code. BUT I am not satisfied! I appreciate this new option (thank you if you did this adding!), but having only the possibility to choose a directory is not enough for me. Many times, we _rename_ the files we download. Personaly I need this possibility. So I propose to add a new (another one, I know...) config option, `c.fileselect.download.command`, to having the possiblity for users to write they own custom scripts, for example a script allowing both to set a directory or a file. I think it works now without changing anything than adding this new option, as the `def prompt_fileselect_external` doesn't check if its return value `self.prompt_accept(folders[0])` is a directory or a file. So I am doing a pull request... ;)
