### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by mentalisttraceur** [qutebrowser/qutebrowser#7906]
I'd really love an Android port. I'm hoping we can use this issue to eventually start/coordinate any efforts in that direction.

Wouldn't need much by way of interface changes - just need a way to bring up the keyboard (in a raw mode rather than normal text input mode, like how Termux does, so that autocomplete/autocorrect/etc doesn't get confused... maybe also add a little customizable bar for modifier+special keys that most keyboards don't have, again Termux is a good example).

Beyond that, one thing I would really love to have on a mobile port is a way to programmatically tell it to open/close tabs from other apps, and query the list of open tabs (I'm going to want to drive Qutebrowser ll with commands from Termux). I don't care if the control scheme is Android intents, a local socket, a directory on shared storage that's written to and watched for changes (like in my idea for a bring-your-own-sync foundation ([qutebrowser-extensions#33](https://github.com/qutebrowser/qutebrowser-extensions/issues/33)) - anything.

Is there willingness? What's needed to make that happen? What kind of help would you like/need? etc.

**Comment by The-Compiler** [comment]
QtWebEngine [isn't available for Android](https://doc.qt.io/qt-6/qtwebengine-platform-notes.html), PyQt/Python generally is a bit of a pain on Android too, and I'll definitely lack the bandwidth to maintain anything of that scale. Sorry, but this one is going to be a hard no.

**Comment by romanovj** [comment]
termux have:

1)pyqt5/x11,now 5.15.9 aarch64
  Comprehensive Python Bindings for Qt v5

2)python-pyqtwebengine/x11,now 5.15.6 aarch64
  Python Bindings for the Qt WebEngine Framework
