### ISSUE TITLE
No output when using openweathermap API

### ISSUE THREAD

**Issue by chelmi00** [qutebrowser/qutebrowser#7909]
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
I copied and modified a webpage to use as home page on Qutebrowser, however on the API part no output appears. On the other hand, I have tried it on edge and epiphany and both show it no problem. I haven't tried any other APIs, but I would believe they won't work too.

**How to reproduce**
Can't attach html or css, but I will leave what I had written: Just open the homepage.html and under the watch something like "clear sky - 21.5°C" (which is the API call) should appear, however my output (only on Qutebrowser) is " - ".

**Things I've tried**
:set content.javascript.enabled true
:set content.local_storage true
:set content.cookies.accept all

**Expected**
![epiphany](https://github.com/qutebrowser/qutebrowser/assets/80181207/7bc9d31f-8067-4a64-8212-b61eda15dbb9)
**Obtained**
![qutebrowser](https://github.com/qutebrowser/qutebrowser/assets/80181207/e838f55e-5f1f-478e-82ef-64ab6ec57cbe)

**Comment by The-Compiler** [comment]
You'll need to set `content.local_content_can_access_remote_urls` if you want to allow that. Alternatively, host the page online somewhere.

**Comment by chelmi00** [comment]
Wow, that was easier than I thought. Thanks mate

**Comment by The-Compiler** [comment]
Good to hear that was the culprit! For what it's worth, the console in `:devtools` can help with investigating issues like this.
