### ISSUE TITLE
On restart after "renderer process was killed", reload killed tabs

### ISSUE THREAD

**Issue by krobelus** [qutebrowser/qutebrowser#7912]
When QtWebEngine falls victim to the OOM killer, its tabs will be converted to a `data:text/html;...` URL stating

> Unable to load page
> Renderer process was killed (status 9)
>
> Try again

This typically happens to many tabs. I'm not sure what's the best way to hit "Try again" on all of them but it seems intuitive that `:restart` should do that? Probably the `data:text/html` URL shouldn't leak to the user although it's a nice little detail

**Comment by The-Compiler** [comment]
I don't think we should be doing this automatically, as it opens up the door to cascading failures. See #267 for having a `:foreach` / `:tabdo` command, and #3918 as for keeping the page's URL. With that, something like a `:tabdo reload` would solve this nicely.
