### ISSUE TITLE
colors.webpage.bg "color" flashes "color" but then goes to white

### ISSUE THREAD

**Issue by zstreeter** [qutebrowser/qutebrowser#7918]
**Version info**:

qutebrowser v3.0.0
Git commit: b070cf45d on main (2023-09-11 12:27:24 +0200)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.5
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: no
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.10 1 Aug 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
Platform: Linux-6.2.0-32-generic-x86_64-with-glibc2.35, 64bit
Linux distribution: Ubuntu 22.04.3 LTS (ubuntu)
Frozen: False
Imported from /home/zstreet/software/qutebrowser/qutebrowser
Using Python from /home/zstreet/software/qutebrowser/.venv/bin/python3
Qt library executable path: /home/zstreet/software/qutebrowser/.venv/lib/python3.11/site-packages/PyQt6/Qt6/libexec, data path: /home/zstreet/software/qutebrowser/.venv/lib/python3.11/site-packages/PyQt6/Qt6
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
When I start qutebrowser, I see the color I'm setting for the webpage.bg flashes but then it just goes to white. All the other color settings seems to be the correct color scheme.
**How to reproduce**

`qutebrowser --temp-basedir -s colors.webpage.bg "#ff0000"`
This should produce a red webpage but it just flashes red and then goes to white, at least that's what I'm seeing.

**Comment by The-Compiler** [comment]
The given color is only used as long as the website doesn't specify one itself. You'll see it being used if you e.g. open `about:blank`.

**Comment by zstreeter** [comment]
Apologies for my ignorance, I don't know what `about:blank` is. Is there anything you can point me to for guidance? I'd appreciate it.

**Comment by The-Compiler** [comment]
`about:blank` is a blank page (in any browser), i.e. `:open about:blank`. And yep, it sounds like `content.user_stylesheets` is what you want.
