### ISSUE TITLE
Can't pass cloudflare turnstile

### ISSUE THREAD

**Issue by Juliaria08** [qutebrowser/qutebrowser#7931]
**Version info**: https://bpa.st/RRCQ

**Does the bug happen if you start with `--temp-basedir`?**: No

**Description**
Can't pass cloudflare turnstile captcha (hidden)

**How to reproduce**

https://kagi.com/fastgpt?query=What%27s+data%3F
Trying to press Answer is impossible, checking console reveals the website is reloading in the background.

**Comment by The-Compiler** [comment]
Duplicate of #7208
