### ISSUE TITLE
Qutebrowser not open in  Opensuse Leap 15.5

### ISSUE THREAD

**Issue by kureshio** [qutebrowser/qutebrowser#7932]
**Version info**:
2.5.4

**Does the bug happen if you start with `--temp-basedir`?*Yes*:

**Description**
When starting it shows this error in python. I am using Opensuse Leap 15.5

**Comment by toofar** [comment]
> it shows this error in python

You forgot to attach the error!

**Comment by The-Compiler** [comment]
Looks like OpenSUSE's packaging of qutebrowser is known broken: [1175293 – qutebrowser doesn't start](https://bugzilla.opensuse.org/show_bug.cgi?id=1175293)

Nothing we can do about that. If it's not that, please add some more details and I can reopen if needed.
