### ISSUE TITLE
a list for all hints on the page

### ISSUE THREAD

**Issue by aboettger-tuhh** [qutebrowser/qutebrowser#7940]
It would be great if in addition to displaying the hints on a page, I could also have a list from which I could select the hints directly. The browser nyxt offers this feature and it was a great experience.

**Comment by toofar** [comment]
Is that like this screenshot? I think this would be implemented as a completion widget for the hints in our stack (assuming there wasn't some complexity that required a new widget type).

That does look useful. Our hint filtering is "invisible" at the moment and providing some extra context could be interesting to help prevent things like selecting hints that don't necessarily do what you want, and maybe to help with https://github.com/qutebrowser/qutebrowser/issues/71

![image](https://github.com/qutebrowser/qutebrowser/assets/7419144/ab4beb34-814b-4a22-8a9a-f30e0552525f)

**Comment by aboettger-tuhh** [comment]
yes, that's it
