### ISSUE TITLE
flex gap does not work as expected

### ISSUE THREAD

**Issue by nashuarone** [qutebrowser/qutebrowser#7944]
**Version info**:
QtWebEngine 5.15.10, webview based on Chromium 87.0.4280.144

**Does the bug happen if you start with `--temp-basedir`?**: ---

**Description**
doesn't work gap between items when display flex (supported from chromium 84+ version),
but grid gap is ok.

**How to reproduce**
```
<body>
        <div class="flex-container">
	        <div class="item">Item 1</div>
	        <div class="item">Item 2</div>
	        <div class="item">Item 3</div>
        </div>
</body>
```

```
.flex-container {
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.item {
	width: 100px;
	height: 100px;
}
```
Please help =(

**Comment by The-Compiler** [comment]
CSS is handled by the underlying Chromium, nothing qutebrowser can do about things like this. If it works in Chromium, chances are it will work in a more recent Qt 6 as well.

**Comment by nashuarone** [comment]
Thanks (
I forgot to say that it works everywhere except at mac os

**Comment by The-Compiler** [comment]
"webview throw QtWebEngine"? Are you even using qutebrowser at all?
