### ISSUE TITLE
[Feature] Allow Privacy Pass extension

### ISSUE THREAD

**Issue by Juliaria08** [qutebrowser/qutebrowser#7945]
I propose we incorporate into qutebrowser some extension that would support [PrivacyPass](https://privacypass.github.io/), this might make it easier to access websites under CloudFlare.
[PrivacyPass](https://privacypass.github.io/)

**Comment by The-Compiler** [comment]
Added to #30. That being said, this most likely won't be possible without getting some sort of WebExtension support from QtWebEngine first.

**Comment by Juliaria08** [comment]
Thanks
