### ISSUE TITLE
Full-Screen Mode Issue: Screen Glitches and Functionality Impaired

### ISSUE THREAD

**Issue by adnanleroi** [qutebrowser/qutebrowser#7959]
I am experiencing a significant issue with qutebrowser's full-screen mode. When I press F11 to switch to full-screen mode, the screen glitches, and I am unable to use the full-screen mode properly. This issue has persisted across multiple sessions and is impacting my browsing experience. 
Version: v2.5.3

**Comment by The-Compiler** [comment]
Please fill out the information from the issue template:

- What Qt version, and backend? (see `:version`)
- Can you reproduce this with `--temp-basedir`?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

Some more questions:

- What OS / desktop environment is this on?
- Can you show a screenshot?

**Comment by The-Compiler** [comment]
@adnanleroi bump?

**Comment by The-Compiler** [comment]
Closing due to no response.

**Comment by BartSte** [comment]
Hey @The-Compiler, I experienced the same issue @adnanleroi. I'll try to give you the info:

- I experienced it only on Windows. On my linux machine all is well.
- I'll try to get a screenshot and run --temp-basedir later.

Here's all the `:version` info:
```
qutebrowser v3.0.2
Backend: QtWebEngine 6.5.3, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.3

CPython: 3.11.6
PyQt: 6.5.3

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.12
pdf.js: 3.11.174 (bundled)
sqlite: 3.43.1
QtNetwork SSL: OpenSSL 3.0.8 7 Feb 2023

Style: QWindowsVistaStyle
Platform plugin: windows
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 529.08
Platform: Windows-10-10.0.22621-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\_internal\qutebrowser
Using Python from C:\Program Files\qutebrowser\qutebrowser.exe
Qt library executable path: C:\Program Files\qutebrowser\_internal\PyQt6\Qt6\bin, data path: C:\Program Files\qutebrowser\_internal\PyQt6\Qt6
OS Version: 10, 10.0.22621, SP0, Multiprocessor Free

Paths:
cache: C:\Users\foo\AppData\Local\qutebrowser\cache
config: C:\Users\foo\AppData\Roaming\qutebrowser\config
data: C:\Users\foo\AppData\Roaming\qutebrowser\data
runtime: C:\Users\foo\AppData\Local\Temp\qutebrowser

Autoconfig loaded: yes
Config.py: C:\Users\foo\AppData\Roaming\qutebrowser\config\config.py has been loaded
Uptime: 0:25:18
```

**Comment by BartSte** [comment]
It seems to happen a lot at gitlab.com.

![Untitled](https://github.com/qutebrowser/qutebrowser/assets/62509788/f5034663-0bf6-46f6-b7c2-cce62339349e)

**Comment by BartSte** [comment]
When running with --temp-basedir I cannot reproduce the issue... That is a good thing I guess?

**Comment by mschilli87** [comment]
I'd suggest looking into `:config-diff` (in a normal sessions, without `--temp-basedir`) next, to see if you set any option that looks suspicious.

**Comment by BartSte** [comment]
Nothing supicious I guess.

```
aliases = {"q": "close", "qa": "quit", "w": "session-save", "wq": "quit --save", "wqa": "quit --save"}
auto_save.session = false
bindings.commands = {"caret": {"<Down>": "move-to-next-line", "<Left>": "move-to-prev-char", "<Right>": "move-to-next-char", "<Up>": "move-to-prev-line"}}
bindings.key_mappings = {"<Ctrl+c>": "<Escape>", "<Ctrl+t>": "<Escape>"}
changelog_after_upgrade = minor
colors.webpage.bg = white
colors.webpage.preferred_color_scheme = dark
completion.cmd_history_max_items = 500
confirm_quit = ["multiple-tabs", "downloads"]
content.autoplay = false
content.blocking.enabled = true
content.cache.appcache = true
content.javascript.clipboard = access
https://www.youtube.com: content.notifications.enabled = false
downloads.remove_finished = 50
editor.command = ["Alacritty", "-e", "nvim", "{file}", "-c", "\"normal {line}G{column0}l\""]
editor.encoding = utf-8
editor.remove_file = true
fonts.default_family = JetBrains Mono
fonts.default_size = 12pt
fonts.hints = JetBrains Mono Extra Bold
fonts.keyhint = 14pt JetBrains Mono Extra Bold
hints.chars = arstgmneiozxcdvkhwfpbjluy
hints.leave_on_load = true
hints.scatter = false
hints.uppercase = true
input.insert_mode.auto_enter = true
input.insert_mode.auto_leave = true
input.insert_mode.auto_load = false
input.insert_mode.leave_on_load = true
input.links_included_in_focus_chain = true
keyhint.delay = 0
qt.workarounds.remove_service_workers = true
scrolling.bar = never
spellcheck.languages = 
url.default_page = about:blank
url.searchengines = {"DEFAULT": "https://www.google.com/search?q={}"}
url.start_pages = about:blank
window.hide_decoration = false
```

**Comment by The-Compiler** [comment]
Hmm, agreed... What happens when you start with `--temp-basedir -s colors.webpage.preferred_color_scheme dark` and reproduce there? Also can you show your `:open chrome://gpu` in the instance where you can reproduce?

**Comment by BartSte** [comment]
Here's my chrome://gpu -> [gpu.pdf](https://github.com/qutebrowser/qutebrowser/files/13348916/gpu.pdf)

I must say that this issue is hard to reproduce consistently. It did not happen again the last couple of hours... I also could not reproduce it with `--temp-basedir -s colors.webpage.preferred_color_scheme dark`.

**Comment by adnanleroi** [comment]
> * --temp-basedir
Yeah, here's the result:
`qutebrowser v2.5.3
Git commit: 
Backend: QtWebEngine 5.15.13, based on Chromium 87.0.4280.144
Qt: 5.15.8
Platform: Linux-6.1.0-13-686-pae-i686-with-glibc2.36, 32bit
Linux distribution: Debian GNU/Linux 12 (bookworm) (debian)`
Sorry I couldn't make a screenshot but It looks the same as 
![image](https://github.com/qutebrowser/qutebrowser/assets/75162534/198b1c54-9909-4d14-86e9-4022198f0b5f)

**Comment by Zarcotech** [comment]
I don't think fixing the --temp-basedir will fix the issue.
