### ISSUE TITLE
Implement Encrypted Client Hello

### ISSUE THREAD

**Issue by Juliaria08** [qutebrowser/qutebrowser#7963]
https://support.mozilla.org/en-US/kb/understand-encrypted-client-hello
https://chromestatus.com/feature/6196703843581952
[ECH Test](https://tls-ech.dev/)

**Comment by The-Compiler** [comment]
This is handled by QtWebEngine/Chromium and should just work once those are upgraded.

**Comment by Juliaria08** [comment]
Ah, thanks for the information.

**Comment by Juliaria08** [comment]
I guess then there would be no option to enable/disable the function I guess.

**Comment by The-Compiler** [comment]
If Qt exposes something, it'll land in the respective "new features in Qt 6.X" issue. If Chromium exposes it via a command line flag, you could already supply that via `qt.args` (though we could also easily add a new setting for it too).

**Comment by Juliaria08** [comment]
Ah, Ok. Thanks.
