### ISSUE TITLE
Weird misalignment caused by pseudo-element

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#7968]
**Version info**:
https://bpa.st/PXFA

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
A strange misalignment seems to occur.

**How to reproduce**
It's not easy to explain, but all the details, plus a runnable snippet, are [here](https://stackoverflow.com/questions/77297732/how-to-prevent-a-span-from-altering-the-distance-between-its-two-neighboring-spa).

---

[Here](https://jsfiddle.net/Enrico89/q8gs270p/1/)'s snippet where the issue is more visible, given the fact that in "r." the "." is supposed to go under the curl of the "r". If you open it in qutebrowser and chromium, you'll get two different behaviors. **Make sure, in qutebrowser, to check and then uncheck the checkbox**, so you see how weird the behavior is.

**Comment by Aster89** [comment]
[This](https://jsfiddle.net/Enrico89/839t417o/2/) happens on Chromium too, though...

**Comment by The-Compiler** [comment]
It's unclear to me what exactly is going on. But I see the exact same behavior with the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py).

I definitely do see weird behavior (original position not being the same as after toggling) with Chromium even with your second example - though I'm not going to experiment much more at this point, as I need to edit all your examples to avoid the checkbox being hidden under the text and thus not clickable.

In either case, this seems like a Chromium issue.
