### ISSUE TITLE
Ignoring Error Messages (On the GUI)

### ISSUE THREAD

**Issue by ramon-alpal** [qutebrowser/qutebrowser#7970]
Good day,

Is there a way to not display, on qutebrowser, error messages? for example: those generated by executing `:message-error test`.

# Usecase

I have the following "wrapper launcher script", in POSIX /bin/sh, for qutebrowser:

    setsid -f tabbed -f /bin/sh -c \
      "export XEMBED=\"\$0\"; fembed \"qutebrowser --target window -- \
      ':set content.javascript.enabled false' ':session-load -c darkmode' \
      ':clear-messages' ':session-delete darkmode' \
      \\\"${@:-$WWW_HOME}\\\"\"" \
    >/dev/null 2>&1

And these two bindings on qutebrowser:

    :bind f set colors.webpage.darkmode.enabled true ;; session-save -o darkmode ;; quit
    :bind F set colors.webpage.darkmode.enabled false ;; session-save -o darkmode ;; quit

For it to be able to, when changing to the darkmode: save the current session, quit, and start again on the "just saved" session - all automatically (all to overcome the problem of requiring a restart when changing to the darkmode).

The problem is that, when executing it, in the fist execution, it will display an error message, on qutebrowser, saying "that it doesn't exist the "darkmode" session".

# Tags

error messages notifications

not display suppress ignore silence mute stop hush

# Notes

- This problem could be also solvable with a script that checks if the session exists - but I don't know how to make it.  Is, each session, saved, in a dedicated file? and also, the file, is deleted when the session is deleted?

- I haven't explain what my "wrapper launcher script" and my "Usecase" with what should be necessary depth to replicate my setup, but it's impertinent to the problem I am presenting today (ask me if you want it though).

Anyways, thanks in advance!

Salute,  
Ramon

**Comment by The-Compiler** [comment]
There isn't a generic way to do this, and I don't think one should exist. Hiding *all* error messages seems like a great recipe for more trouble.

For many commands, a flag of some sorts exists to ignore error messages. Not for `:session-load` though, and I agree your script should just check whether the session exists first. They are files in the data directory (under `sessions`), the path of which you will find in `:version`.

**Comment by ramon-alpal** [comment]
# Userscript that Checks If the Session Exists

> > - This problem could be also solvable with a script that checks if the session exists - but I don't know how to make it. Is, each session, saved, in a dedicated file? and also, the file, is deleted when the session is deleted?

> I agree your script should just check whether the session exists first. They are files in the data directory (under `sessions`), the path of which you will find in `:version`.

I've made the following POSIX /bin/sh userscript as a solution to the problem:

    #!/bin/sh
    # on-launch - hook of qutebrowser On Launch
    
    XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
    { [ -f "$XDG_DATA_HOME"/qutebrowser/sessions/darkmode* ] && printf '%s\n'\
        'session-load --clear darkmode'\
        'session-delete darkmode'
      printf '%s\n'\
        'set content.javascript.enabled false'\
        'set colors.webpage.darkmode.enabled false'
    } >>"$QUTE_FIFO"
    exit 0

And launched qutebrowser as following:

    qutebrowser --target window --\
      ':spawn --userscript /usr/local/share/qutebrowser/userscripts/on-launch'\
      "${@:-$WWW_HOME}"

But, when qutebrowser is executing the userscript, provided as an argument, it returns an error:

    No WebView available yet!

Resulting in this solution being unviable - for the time being.  Maybe, in the future, `hooks` will be added to qutebrowser, so userscripts run correctly: on start and on other events.

# Not Display, On Qutebrowser, Error Messages; and the Solution

> > Is there a way to not display, on qutebrowser, error messages? for example: those generated by executing `:message-error test`.

> There isn't a generic way to do this, and I don't think one should exist. Hiding _all_ error messages seems like a great recipe for more trouble.
> 
> For many commands, a flag of some sorts exists to ignore error messages. Not for `:session-load` though

There is a way you can do it, by setting `messages.timeout` to 1:

    :set messages.timeout 1

Witch will fix the problem - but it may be possible that it will appear and disappear instantly.

And I think that it has a place.  Think about how, when writing shell scripts, you put `>/dev/null 2>&1` to the end, when executing a program, to ignore all the output it generates, and `setsid -f` to forked; instead of having to look at each program to use their particular options to do the same.

# Notes

- Now that I think about it, you can do what I was trying to do in "Userscript that Checks If the Session Exists", with a wrapper script, that launches qutebrowser with different options.  But I'll still leave the comment like it is, for it's still relevant.

Thanks again! and keep working in qutebrowser, it's the greatest browser!
