### ISSUE TITLE
Two finger scrolling on a touchpad triggers a secondary zoom occasionally

### ISSUE THREAD

**Issue by nozpheratu** [qutebrowser/qutebrowser#7975]
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.3, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.3

CPython: 3.10.12
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 3.9.179 (/nix/store/wina0bcmiw1z921hb4hijfr18ajh2sy6-source/build/pdf.js)
sqlite: 3.43.1
QtNetwork SSL: OpenSSL 3.0.10 1 Aug 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.2 (Compatibility Profile) Mesa 23.0.3
Platform: Linux-6.1.56-x86_64-with-glibc2.37, 64bit
Linux distribution: NixOS 23.05 (Stoat) (nixos)

**Does the bug happen if you start with `--temp-basedir`?**:
No

**Description**
When scrolling with two fingers on a touchpad I will occasionally notice web pages tend to zoom in in a fashion that is completely separate from the in-browser zoom level (i.e., changing my zoom will not undo the zoom). Tabs with the secondary zoom will retain the zoom when closed. Restarting the browser with :restart will resolve the issue. New clean tabs (not cloned) will not have this secondary zoom.

**How to reproduce**
 I'm not entirely sure what specific touchpad interactions cause it, but I definitely notice it when scrolling up and down a lot, it will only occur occasionally, but I must be scrolling for it to happen. I am not clicking on anything else on the keyboard, and I've ruled out any stuck keyboard keys. This started happening after the PyQt6 upgrade.

**Comment by The-Compiler** [comment]
See #7663 - as mentioned there, there's unfortunately not really anything qutebrowser can do here, short of completely blocking pinch to zoom maybe.
