### ISSUE TITLE
Some Session Tabs corrupt on SIGKILL/SIGTERM

### ISSUE THREAD

**Issue by markuspeitl** [qutebrowser/qutebrowser#7981]
**Version info**:
```
qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.10.12
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.16.1
yaml: 5.4.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: no
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.2 15 Mar 2022

Style: QFusionStyle
Platform plugin: xcb
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 525.125.06
Platform: Linux-5.15.0-43-generic-x86_64-with-glibc2.35, 64bit
Linux distribution: Ubuntu 22.04.3 LTS (ubuntu)
Frozen: False
Imported from /home/pmarkus/.local/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /home/pmarkus/.local/lib/python3.10/site-packages/PyQt6/Qt6/libexec, data path: /home/pmarkus/.local/lib/python3.10/site-packages/PyQt6/Qt6

Paths:
cache: /home/pmarkus/.cache/qutebrowser
config: /home/pmarkus/.config/qutebrowser
data: /home/pmarkus/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/pmarkus/.config/qutebrowser/config.py has been loaded
```

**Does the bug happen if you start with `--temp-basedir`?**:
\-

**Description**
When quitting qutebrowser through non default means, before some of the tabs are loaded,
this corrupts those tabs in the **_autosave.yml** and the **default.yml** sessions (if autosave is enabled).

The autosave interval is 15000msec so it should not be that the session is saved while qutebrowser terminates.
``c.auto_save.interval = 15000``

**How to reproduce**
1. Have session ``c.auto_save.session = True`` enabled (I am assuming this would not happen without this, as the corrupted session would never be written to disk)
2. Open qutebrowser
3. Open a few different tabs (i think the issue happens more with pages that take longer to load)
4. Write session and exit ``:wqa`` 
5. Open qutebrowser (Now everything should still be fine)
6. And immediately kill the process ``killall qutebrowser`` or "alt+f4" or terminating the process by sending SIGTERM to the parent shell
7. Open qutebrowser again and now some of the tabs show a dash **-** and the urls are empty, the history lists of those tabs in **_autosave.yml** and in **default.yml** are now empty as well.

**Comment by The-Compiler** [comment]
This happens due to https://github.com/qutebrowser/qutebrowser/issues/5359 combined with https://github.com/qutebrowser/qutebrowser/issues/2176.

**Comment by markuspeitl** [comment]
Thanks for clarifying :thumbsup:
