### ISSUE TITLE
Mouse doesn't work on external monitors

### ISSUE THREAD

**Issue by OmegaLambda1998** [qutebrowser/qutebrowser#8007]
**Version info**:
qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.6, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.0
https://bpa.st/BAEQ

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I'm on an Arch Linux, wayland laptop (sway). I have two external monitors connected. If I open qutebrowser on my laptop screen, the mouse works perfectfly fine, however on one monitor the mouse does nothing (no scrolling, and none of the mouse buttons work). On the other, the mouse seems to only be able to click at the bottom of the screen, no matter where the cursor actually is.
`swaymsg -t get_outputs` gives the following:
<details> 
  <summary>swaymsg -t get_outputs </summary>

   ```
Output eDP-1 'LG Display 0x0608 Unknown'
  Current mode: 1920x1080 @ 60.020 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 8
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.020 Hz
    1920x1080 @ 47.999 Hz

Output DP-2 'Apple Computer Inc Cinema HD CY6460G0UG1' (focused)
  Current mode: 2560x1600 @ 59.860 Hz
  Position: -320,-1600
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1280x800 @ 59.910 Hz
    2560x1600 @ 59.860 Hz

Output HDMI-A-1 'Dell Inc. DELL 2209WA H728H05H1P5L'
  Current mode: 1680x1050 @ 59.954 Hz
  Position: 2240,-1600
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: 270
  Workspace: 11
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1680x1050 @ 59.954 Hz
    1280x1024 @ 75.025 Hz
    1280x1024 @ 60.020 Hz
    1152x864 @ 75.000 Hz
    1024x768 @ 75.029 Hz
    1024x768 @ 60.004 Hz
    800x600 @ 75.000 Hz
    800x600 @ 60.317 Hz
    640x480 @ 75.000 Hz
    640x480 @ 59.940 Hz
    720x400 @ 70.082 Hz
   ```

</details>

--temp-basedir has the same issue. 

Happy to provide whatever other details are necessary

**Comment by OmegaLambda1998** [comment]
As always, I solved it just after posting the issue. qutebrowser was using qt6, but I didn't have qt6-wayland installed. Installing that fixed everything

**Comment by mschilli87** [comment]
@OmegaLambda1998: You should be able to close the issue then. 😉

**Comment by OmegaLambda1998** [comment]
Whoops, pressed the wrong comment button!
