### ISSUE TITLE
pdf previews from online outlook are not loaded correctly

### ISSUE THREAD

**Issue by leybodv** [qutebrowser/qutebrowser#8008]
**Version info**:

qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.6, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.0

CPython: 3.11.6
PyQt: 6.6.0

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.6.0
PyQt6.sip: 6.7.12
pdf.js: no
sqlite: 3.44.1
QtNetwork SSL: OpenSSL 3.1.4 24 Oct 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.2
Platform: Linux-6.6.2-arch1-1-x86_64-with-glibc2.38, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/d/.cache/qutebrowser
config: /home/d/.config/qutebrowser
data: /home/d/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 1:45:35

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
I use online microsoft outlook, and when I try to open pdf attached to an email I see this:
![pdf-preview-issue](https://github.com/qutebrowser/qutebrowser/assets/72412227/4ecdc411-8778-4993-a466-dc4a094e0f95)

However everything works in firefox:
![pdf-preview-issue_firefox](https://github.com/qutebrowser/qutebrowser/assets/72412227/d2034a02-24de-459a-912e-80837cc43eff)

**How to reproduce**

Open attached pdf file in preview mode in online microsoft outlook.

**Comment by The-Compiler** [comment]
Works for me.

How do things look with `--temp-basedir -s qt.workarounds.disable_accelerated_2d_canvas always`?

**Comment by leybodv** [comment]
> Works for me.
> 
> How do things look with `--temp-basedir -s qt.workarounds.disable_accelerated_2d_canvas always`?

 It works! What is the magic here?

**Comment by The-Compiler** [comment]
It's some sort of bug in Qt on Intel graphics only. We thought it would be fixed in Qt 6.6, but evidently that's not the case - see #7489.
