### ISSUE TITLE
Slow on Wayland & Nvidia

### ISSUE THREAD

**Issue by Seres67** [qutebrowser/qutebrowser#8013]
**Version info**:
qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

CPython: 3.11.6
PyQt: 6.6.0

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.6.0
PyQt6.sip: 6.7.12
pdf.js: no
sqlite: 3.44.2
QtNetwork SSL: OpenSSL 3.1.4 24 Oct 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: OpenGL ES
Platform: Linux-6.6.3-arch1-1-x86_64-with-glibc2.38, 64bit
Linux distribution: EndeavourOS (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

**Does the bug happen if you start with `--temp-basedir`?**:
yes
**Description**
The browser is *extremely* slow, and I have no clue why. firefox runs fine, testbrowser has the same issue.
i'm running hyprland on wayland, with nvidia-dkms (latest)
**How to reproduce**
run the browser, everything is super slow

**Comment by Seres67** [comment]
Sorry for bothering, I thought that it was an issue with qutebrowser as I can't reproduce it on any other browser.
I'll open an issue later, if building with a newer QtWebEngine doesn't change anything.
There's no `qt6-v2` branch but I read that it was merged in main, should I build main?

**Comment by The-Compiler** [comment]
If you can reproduce it in the testbrowser, then it can't be a qutebrowser specific issue.

Sorry for the `qt6-v2` part. That's outdated indeed, and was just in the GitHub comment template I use to respond to upstream issues like this quickly. Fixed it.

**Comment by Seres67** [comment]
I've opened a bug report [here](https://bugreports.qt.io/browse/QTBUG-119658)!
