### ISSUE TITLE
Screen flashing / diagonally tearing on Google Apps

### ISSUE THREAD

**Issue by contrick64** [qutebrowser/qutebrowser#8017]
**Version info**:
```
qutebrowser v3.0.2
Backend: QtWebEngine 6.5.3, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.3
```

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
When browsing some sites (i've noticed it frequently on Google apps, unsure if there are others, will update if I encounter it). The content of the page flashes and shows the background color, often in odd diagonal or checkered patterns.

https://github.com/qutebrowser/qutebrowser/assets/64382883/9e39103c-2c25-4ba4-bf1d-e0bb92d791ae

**How to reproduce**
Visit a Google app site, use as usual? Unsure if there's something about my specific setup, it shouldn't be too far off from a standard Windows 10 Pro install.

**Comment by The-Compiler** [comment]
This is unlikely to be a qutebrowser specific issue. You don't happen to have Python set up on your system (or are okay with setting it up), or alternatively have Qt Creator running, so that you could try some isolated examples?

**Comment by contrick64** [comment]
I do have python set up, would be happy to try isolated examples with a little guidance!

**Comment by The-Compiler** [comment]
Glad to hear! Could you please:

- Clone the qutebrowser repo via `git clone https://github.com/qutebrowser/qutebrowser.git` (or [download a zip](https://github.com/qutebrowser/qutebrowser.git))
- Run `py scripts/mkvenv.py` which will create a [virtual environment](https://chriswarrick.com/blog/2018/09/04/python-virtual-environments/) which everything needed
- Run `.venv\Scripts\python -m qutebrowser --temp-basedir` and verify that the bug still appears in that configuration
- Run `.venv\Scripts\python scripts\testbrowser\testbrowser_webengine.py https://mail.google.com` and then see if you can reproduce it there?

**Comment by contrick64** [comment]
On running `mkenv.py` I got the following:
```
==================== Running Qt smoke test ====================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "path/to/repoOlib/qutebrowser_repo/qutebrowser/qt/widgets.py", line 24, in <module>
    from PyQt6.QtWidgets import *
ImportError: libxkbcommon.so.0: cannot open shared object file: No such file or directory

Smoke test failed with status 1. You might find additional information in the debug output above.
```

**Comment by The-Compiler** [comment]
Sounds like you're trying to run this in WSL or something? It should be run in a Windows shell (say e.g. Powershell) so it uses Windows binaries for PyQt.
