### ISSUE TITLE
Macro: search followed by "Enter" only follows a link on the second replay

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#8021]
**Version info**:

```
qutebrowser v3.0.2
Git commit:
Backend: QtWebEngine 6.6, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.0
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

When you use a macro to automate following a link with specific name, it only works on the second replay. On the first macro replay Qutebrowser puts a caret over a link, and then the second one follows the link. Even though all of that should happen inside a single replay.

**How to reproduce**

1. Open `qutebrowser --temp-basedir https://github.com/qutebrowser/qutebrowser/commits`
2. Type <kbd>/Older</kbd> <kbd>Enter</kbd> *(this saves the search for `Older`)*
3. Press <kbd>qq</kbd> <kbd>n</kbd> <kbd>Enter</kbd> <kbd>q</kbd> *(this records a macro where you find the `Older` link in the page and follow it)*
4. Press <kbd>@q</kbd> *(this should make Qutebrowser go to the `Older` link and follow it)*

**Expected**

Qutebrowser switches to the next page by following `Older`

**Actual**

Qutebrowser simply goes to the `Older` link but does not follow it

**Comment by The-Compiler** [comment]
This is the same underlying issue as #3007: Currently there is no notation of a command being "done" in qutebrowser, and lots of things happen async behind the scenes in Qt/Chromium. Thus, the `selection-follow` command (`<Enter>`) gets run before the search actually has been done.

This can also be seen with:

```
qutebrowser --debug --temp-basedir https://github.com/qutebrowser/qutebrowser/commits ":cmd-later 2000 search Older" ":cmd-later 2100 selection-follow"
```

Where this works, but setting the delay for the second command to `2000` too shows the same behavior you describe.
