### ISSUE TITLE
cant play X/Twitter videos. 

### ISSUE THREAD

**Issue by harshtohai** [qutebrowser/qutebrowser#8043]
There's an bug while trying to load twitter videos. I shows Media could not be played.

INFO:
https://bpa.st/I3GQ 
![image](https://github.com/qutebrowser/qutebrowser/assets/130650529/ee27cf6b-5e3e-4618-a027-11e8a9d625f9)

**Comment by The-Compiler** [comment]
Windows binaries come without proprietary codec support - unfortunately the only way to change that is to build QtWebEngine/Chromium from source.

**Comment by harshtohai** [comment]
Ooooo OK.
