### ISSUE TITLE
Verifying Odysee-Account stuck in "Resolving"-Loop

### ISSUE THREAD

**Issue by andmars** [qutebrowser/qutebrowser#8044]
qutebrowser v3.1.0
Git commit: 
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

CPython: 3.11.6
PyQt: 6.6.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: no
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.6.0
PyQt6.sip: 6.7.12
pdf.js: no
sqlite: 3.44.2
QtNetwork SSL: OpenSSL 3.2.0 23 Nov 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: OpenGL ES
Platform: Linux-6.6.7-arch1-1-x86_64-with-glibc2.38, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/andreas/.cache/qutebrowser
config: /home/andreas/.config/qutebrowser
data: /home/andreas/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/andreas/.config/qutebrowser/config.py has been loaded
Uptime: 0:44:05

**Description**
When trying to sign up to Odysee and clicking the link in the E-Mail verification the new tab is stuck in a "Resolving"-Loop. Does work in Firefox.

**How to reproduce**
Sign up for an Odysee-Account:
https://odysee.com/$/signup
![20231220_09h16m52s_grim](https://github.com/qutebrowser/qutebrowser/assets/11244488/30e0c99c-977a-4a81-b43a-c33c99ab2cf7)

**Comment by The-Compiler** [comment]
Works for me. A few questions:

- Can you reproduce with `--temp-basedir`? (there's a reason the issue template asks this :wink:)
- Anything interesting in the `:devtools` console?
- Can you show your `:config-diff`?

**Comment by andmars** [comment]
**Does the bug happen if you start with `--temp-basedir`?**:
yes

**:devtools**
don't know if this is important:
![20231220_12h26m39s_grim](https://github.com/qutebrowser/qutebrowser/assets/11244488/5d35206a-38a0-4332-9a91-cf4c3270ead6)

**:config-diff**:
[config-diff.txt](https://github.com/qutebrowser/qutebrowser/files/13726698/config-diff.txt)

**Comment by The-Compiler** [comment]
Likely there isn't really anything that qutebrowser can do here. What happens inside web contents is pretty much handled by the underlying QtWebEngine, but given I can't reproduce this, I can't say much more.

Can you try running the [testbrowser_webengine.py](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py) script and see if it reproduces there as well?

When you try with `--temp-basedir` or with Firefox, do you use `http://127.0.0.1:8118` as proxy too?
