### ISSUE TITLE
Incorrect sample rate with pipewire

### ISSUE THREAD

**Issue by pzant** [qutebrowser/qutebrowser#8047]
**Version info**:
qutebrowser v3.0.2
Git commit:
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

CPython: 3.11.6
PyQt: 6.6.0

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
qutebrowser plays audio at the highest possible sampling rate although the audio track has a lower rate.

**How to reproduce**
Open YouTube in qutebrowser on a system with pipewire-pulse and open `pw-top`.
In my case the rate is 192000 and it should be 48000.

**Comment by The-Compiler** [comment]
Looks to be a Chromium bug: [1385272 - Audio is resampled with Chromium (or Chromium-based) applications - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1385272)
