### ISSUE TITLE
qutebrowser internal pages should respect `colors.webpage.preferred_color_scheme`

### ISSUE THREAD

**Issue by amano-kenji** [qutebrowser/qutebrowser#8054]
I have
```
config.set("colors.webpage.preferred_color_scheme", "dark")
```
However, about:blank page is very white and hurts my eyes really.

Firefox's about:blank respects dark mode settings.

I wanted to use dark mode, but it breaks some websites. There is no URL pattern for dark mode.

`:help` and `:set` also flash white color on my eyes.

**Comment by The-Compiler** [comment]
This is coming from the underlying Chromium, not much qutebrowser can do about it. What's causing `about:blank` to be opened?

As for `:help` and `:set`, see #7116.

**Comment by amano-kenji** [comment]
I had
```
# Page settings
config.set("url.default_page", "about:blank")
config.set("url.start_pages", "about:blank")
```
Now, I have
```
# Page settings
config.set("url.default_page", "~/.config/qutebrowser/blank.html")
config.set("url.start_pages", "~/.config/qutebrowser/blank.html")
```
`blank.html` is an HTML file I wrote. It is dark.

**Comment by The-Compiler** [comment]
Makes sense. I don't really think there's much more we can do here. We could add a `qute:blank` or whatever, but I don't really see a good way to make people aware it exists.
