### ISSUE TITLE
Transparency based off brightness level?

### ISSUE THREAD

**Issue by AnotherRandomGitHubAccount** [qutebrowser/qutebrowser#8066]
I understand that implementing transparency in a webengine is a complex task that WILL break EVERYTHING. but I was wondering if it will be possible to create a brightness-based transparency thing, like if something passes a certain threshold, it could be made to have a certain level of transparency.

**Comment by The-Compiler** [comment]
I believe all possibilities QtWebEngine gives us here are already exposed by `window.transparent` and possibly `content.user_stylesheets`.
