### ISSUE TITLE
error 1010 on cloudflare

### ISSUE THREAD

**Issue by maccagnan** [qutebrowser/qutebrowser#8100]
qtwebengine5-dev-tools 5.15.13+dfsg-1~deb12u1
qutebrowser 2.5.3-1         
qutebrowser-qtwebengine 2.5.3-1 

All of a sudden, when trying to connect to https://fmoviesz.to/, I get this error: 

Error 1010 Ray ID: 853985445a0b7d1f • 2024-02-11 03:31:43 UTC
Access denied
What happened?
The owner of this website (fmoviesz.to) has banned your access based on your browser's signature (853985445a0b7d1f-ua60).

Was this page helpful? Yes No
Cloudflare Ray ID: 853985445a0b7d1f • Your IP: Click to reveal • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

any workaround?

**Comment by toofar** [comment]
Can you try with a temp basedir please? Eg from a terminal: `qutebrowser -T https://fmoviesz.to/`

It's loading fine for me in a temp basedir with Qt WebEngine 5.15.15, and on may main Qt 6.7 instance. So it could be something to do with your settings (like a custom user agent header).

**Comment by maccagnan** [comment]
qutebrowser -T https://fmoviesz.to/

worked.
Thanks but, could you explain what am I doing wrong?
I didn't change qutebrowser configuration and, when i got the error, even tried with a fresh install.

**Comment by toofar** [comment]
> Thanks but, could you explain what am I doing wrong?

I'm afraid not, I don't know what the cause is. But since it works in other situations it seems like it's related to your setup.

You can check qute://configdiff/ to see any config you have changed.
Beyond that I would look at clearing cookies, local storage and service workers via the developer tools (bound to `wi`).

**Comment by maccagnan** [comment]
Thanks,
My problem is now that if I start quetbrowser with the -T option it works with cloudflare, but I get the usual 'browser not allowed' erro when i try to login on google.
I tried to change the user agentbut no dice. 
If I load qutebrowser with my old configuration, it's the other way around, google works but not cloudflare based websites.
I checked qute://configdiff/ but still couldn't find what determines the behavior.

**Comment by toofar** [comment]
> qtwebengine5-dev-tools 5.15.13+dfsg-1~deb12u1

It could just be the [old webengine version](https://wiki.qt.io/Qt_5.15_Release) you are using.
You might have to try installing in a virtualenv as explained here: https://qutebrowser.org/doc/install.html#_installing_dependencies_including_qt

You'll get a newer Qt version in that (so it won't use your system one), the only downside is that it won't have proprietary video codecs (eg patent encumbered ones). Also I guess it won't show up in desktop application menus etc I guess?

**Comment by The-Compiler** [comment]
Can you show your `:config-diff` with the affected version?

**Comment by maccagnan** [comment]
Here's the :config-diff of the version I use that doesn't work with cloudflare

https://www.coppel.com: content.geolocation = true
https://www.google.com: content.geolocation = true
https://www.guitarcenter.com: content.geolocation = true
https://www.homedepot.com.mx: content.geolocation = true
content.headers.user_agent = "Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0"/
content.javascript.can_access_clipboard = true
content.javascript.can_open_tabs_automatically = true
content.javascript.modal_dialog = true
https://ww1.m4uhd.tv: content.notifications.enabled = true
https://www.facebook.com: content.notifications.enabled = true
https://www.reddit.com: content.notifications.enabled = true
https://www.watzatsong.com: content.notifications.enabled = true
https://www.youtube.com: content.notifications.enabled = true
https://mail.google.com?extsrc=mailto&url=%25s: content.register_protocol_handler = true
https://outlook.live.com?mailtouri=%25s: content.register_protocol_handler = true
downloads.location.directory = /home/mac/downloads
session.default_name = none
session.lazy_restore = false
spellcheck.languages = 
url.auto_search = naive
url.default_page = about:blank
url.searchengines = {"DEFAULT": "https://google.com/search?q={}"}
url.start_pages = about:blank

**Comment by The-Compiler** [comment]
> content.headers.user_agent = "Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0"

Don't do that. Pretending that you are Firefox with a browser that's actually Chromium breaks various websites (and will also make you quite uniquely fingerprintable).

**Comment by The-Compiler** [comment]
Don't set it globally. Should be enough to just set it for `accounts.google.com` as per #5182, though I'm not sure why the default workaround built into qutebrowser 2.3.1 isn't working for you. Also see #7427.

**Comment by maccagnan** [comment]
I'll try that. Thanks for the support. Awesome job with Qutebrowser, it's by far my favorite browser.
