### ISSUE TITLE
Mac Password Manager support (Bitwarden)

### ISSUE THREAD

**Issue by reedjosh** [qutebrowser/qutebrowser#8103]
I'm stuck on a Mac for work purposes.

`rofi` and `keyctl` are basically no goes.

I know it's all userscripts, and I spent a good deal of time fighting the Bitwarden one.

This is really more of a question.

For Mac, I can't find any good rofi replacements. There is a chooser gui app, but it doesn't support password entry as it shows the password while typing.

`keyctl` could potentially be replaced by the inbuilt keyring program using the `security` cli, but AFAICT the timeout mechanism there is keyring based. Either one would need to create a new keyring everytime with a lock and generated password, or no timeout mechanism would be available.

1). Could we build something like rofi into qutebrowser? Is there maybe already mechanisms to do so I'm just not aware of? A normal browser plugin would use the browser's inbuilt dialog AFAICT.
     
2). Do you happen to know of any other timout mechanisms for session keys? Can we try to move from linux only tools to cross-platform compatible tools?

Thanks, and I love qutebrowser!

**Comment by The-Compiler** [comment]
See #6144, and #902 for what would be needed first to make a prompt inside qutebrowser a possibility. But at this point, a proper extension API (#30) is probably a better idea.
