### ISSUE TITLE
Custom clickable widgets

### ISSUE THREAD

**Issue by cf8** [qutebrowser/qutebrowser#8104]
I was thinking it would be really cool if we could define some custom widgets for StatusBar (or even TabBar). 
Similar to how there is currently a custom text status bar widget:
```
c.statusbar.widgets = [ "text: Some text"]
```
But with a way to define left/middle/right click actions for it.

Common use case may be a simple "new tab" button, which will open a clean new tab on left click and url from clipboard on middle click.

I know that qutebrowser UI is keyboard-centric (and i love it), but sometimes things like that could be really handy.

Not to mention, you could potentially make all sorts of useful widgets with proper support.

**Comment by The-Compiler** [comment]
This is already mentioned in #30 as a possible use-case for a future extension API.
