### ISSUE TITLE
Allow reloading config with HUP signal

### ISSUE THREAD

**Issue by tarneaux** [qutebrowser/qutebrowser#8108]
## Description

When sending the HUP signal to Qutebrowser, it should reload the config file(s) just like when running `:config-source`.

## Use cases

- Automatically reloading qutebrowser when changing a Home-manager configuration on Nix systems
- Automatically reloading qutebrowser after changing its settings from a script, to change font size and zoom when connecting a new display for example.

## Current alternatives

If you are the user running Qb, run `qutebrowser :config-source` which will run the command (side-effect: it will also focus the Qutebrowser window like when opening a web page).

**Comment by toofar** [comment]
I think that sounds harmless enough. Regarding the caveat to the "current alternative" about the window being raised, I wanted to link the issue about that, but all I could find was this one (which was apparently fixed at one point!): https://github.com/qutebrowser/qutebrowser/issues/1328

**Comment by tarneaux** [comment]
@toofar, I think you meant #5094, which is referenced in `app.py` in a FIXME comment.

**Comment by toofar** [comment]
Yep, good spotting, thank you. I've re-opened it, looks like it got closed by accident.
