### ISSUE TITLE
Implement the ability to hide Qt context-menu icons

### ISSUE THREAD

**Issue by apsinthium** [qutebrowser/qutebrowser#8111]
The icons look out-dated and don't match the minimalist style of qutebrowser. Please consider offering the ability to hide these icons with a command or in the _Settings_ menu.

![20240221_21h13m17s_grim](https://github.com/qutebrowser/qutebrowser/assets/142288368/de5c5994-bb12-460a-99ab-b19ff95715a1)
Goodbye Windows XP icons!

**Comment by The-Compiler** [comment]
As mentioned in IRC, the context menu isn't coming from qutebrowser itself - see #349
