### ISSUE TITLE
Allow pattern matching of space separated words to be unordered

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#8120]
Say I do `:open`.

Then I type `one two three`.

If there's, say, a quickmark (but also URL, bookmark, ...) with name `OneTwoThree`, that will be matched, but if there is something like `three two one`, that will not be matched.

It would be nice if the space separated words I write after `:open` would be matched irrespective of the order.

I think it would only improve user experience for somebody, but not worsen it for a sensible number of people.

Notice that FZF has this approach.

**Comment by The-Compiler** [comment]
This is already the case, see #7955.
