### ISSUE TITLE
`colors.webpage.darkmode.policy.images` set to `never` seems to not affect svg pictures

### ISSUE THREAD

**Issue by joaonunatings** [qutebrowser/qutebrowser#8130]
**Version info**:
https://bpa.st/SUMA

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
The `colors.webpage.darkmode.policy.images` setting is not applied to SVG pictures. The picture is written with code but it's [defined as an image format](https://en.wikipedia.org/wiki/SVG), so I don't see why this should not be applied.

**How to reproduce**
Take [this](https://cloud.google.com/static/load-balancing/images/internal-https-forwarding-rule.svg) image as an example.

- Before setting `colors.webpage.darkmode.enabled` to `true` the image should show like this:
![image](https://github.com/qutebrowser/qutebrowser/assets/8835595/a5af97b4-e971-4a04-b3ba-a12c6cae4d1b)

- After setting `colors.webpage.darkmode.enabled` to `true` atleast the text color inside the boxes is inverted:
![image](https://github.com/qutebrowser/qutebrowser/assets/8835595/4e74a6c0-7481-4ee8-a2c8-25883498ed5a)

- After setting `colors.webpage.darkmode.policy.images` to `never` the text color inside the boxes is still inverted.

**Comment by The-Compiler** [comment]
Dark mode is implemented by the underlying Chromium, and this also reproduces with:

```
chromium --blink-settings=forceDarkModeEnabled=true --dark-mode-settings=ImagePolicy=1 https://cloud.google.com/static/load-balancing/images/internal-https-forwarding-rule.svg
```

so unfortunately there isn't anything qutebrowser can do.

See also: [Some SVG or PNG images are unreadable with chrome://flags/#enable-force-dark [40718592] - Chromium](https://issues.chromium.org/issues/40718592)
