### ISSUE TITLE
add text highlighting feature

### ISSUE THREAD

**Issue by Butek1** [qutebrowser/qutebrowser#8131]
Follow the link to see a sample of work
https://youtu.be/ewGxMsA0IIg

**Comment by The-Compiler** [comment]
That's caret mode (`v`).

**Comment by Butek1** [comment]
> That's caret mode (`v`).

This is a convenient backlit caret mode for quickly moving to the desired sentence or paragraph; in qutebrowser you have to move the cursor for a long time

**Comment by The-Compiler** [comment]
See #1453 and #521 - but note you can already `/search` and then enter caret mode.

**Comment by Butek1** [comment]
> See #1453 and #521 - but note you can already `/search` and then enter caret mode.

loock at different ways highlight and speed 
https://youtu.be/NV6Z94QWE4w
