### ISSUE TITLE
A human readable time format for the history... to use fzf to search history!

### ISSUE THREAD

**Issue by Twix53791** [qutebrowser/qutebrowser#8141]
Hi,

I am just leaving here a small stone in case of oneday, some of the devs of qutebrowser think about redesigning the database history.

I wrote [a small plugin](https://github.com/Twix53791/qute-plugin-fzfhistory/) to display the browser history with fzf in a pop up window.
It is fast and practicable. Very fast. But to reach this speed, it needs to have minimal operations to make. The problem is that the qutebrowser history database store the time in an epoch time format. It is not practical to search for a date: a year, a month, a day... And rebuilding the time in a human readable format from the epoch time in the plugin obviously slows it a lot, especially when the history contains thousands of urls.

So, I made a patch modifying history.py file in qutebrowser, adding to the table 'CompletionHistory' of history.sqlite the column 'human_time', which stote the time in a format "%Y %B %d %H:%M:%S". So you can limit the scope of the history display by year, then month, then day, then the time...

Here the diff:  
```diff
--- history.save	2024-03-24 17:01:53.708398238 +0100
+++ history.py	2024-03-24 22:05:44.213982198 +0100
@@ -134,10 +134,11 @@
 
     def __init__(self, database: sql.Database,
                  parent: Optional[QObject] = None) -> None:
-        super().__init__(database, "CompletionHistory", ['url', 'title', 'last_atime'],
+        super().__init__(database, "CompletionHistory", ['url', 'title', 'last_atime', 'human_time'],
                          constraints={'url': 'PRIMARY KEY',
                                       'title': 'NOT NULL',
-                                      'last_atime': 'NOT NULL'},
+                                      'last_atime': 'NOT NULL',
+                                      'human_time': 'NOT NULL'},
                          parent=parent)
         self.create_index('CompletionHistoryAtimeIndex', 'last_atime')
 
@@ -410,6 +411,7 @@
             return
 
         atime = int(atime) if (atime is not None) else int(time.time())
+        htime = os.popen("date '+%Y %B %d %H:%M:%S'").read().strip()
 
         with self._handle_sql_errors():
             self.insert({'url': self._format_url(url),
@@ -423,7 +425,8 @@
             self.completion.insert({
                 'url': self._format_completion_url(url),
                 'title': title,
-                'last_atime': atime
+                'last_atime': atime,
+                'human_time': htime
             }, replace=True)
 
     def _format_url(self, url):

```

The problem with this modification is than it breaks if the history database already exist, because the column 'human_time' doesn't exist. I tried a bit to find a way letting qutebrowser to add the column if it doesn't exist, but it seems complicated. So, it is not possible to implement the change in qutebrowser without broking the config of everyone or making important changes in sql.py. That's why I made a patch, and a plugin.

For those interested, I also made a patch for tabbedbrowser.py recording the last 100 closed tabs in a file in the same format, with a human readable time format, to use it also with fzf.

```diff
@@ -8,6 +8,7 @@
 import functools
 import weakref
 import datetime
+import shutil
 import dataclasses
 from typing import (
     Any, Deque, List, Mapping, MutableMapping, MutableSequence, Optional, Tuple)
@@ -19,7 +20,7 @@
 from qutebrowser.keyinput import modeman
 from qutebrowser.mainwindow import tabwidget, mainwindow
 from qutebrowser.browser import signalfilter, browsertab, history
-from qutebrowser.utils import (log, usertypes, utils, qtutils,
+from qutebrowser.utils import (standarddir, log, usertypes, utils, qtutils,
                                urlutils, message, jinja, version)
 from qutebrowser.misc import quitter, objects
 
@@ -519,6 +520,23 @@
                 else:
                     self.undo_stack[-1].append(entry)
 
+                # Patch closed-tabs-history for qute-plugin-fzfhistory
+                closed_history=standarddir.data() + "/closed-tabs-history"
+                tmp_ch="/tmp/qute_closed_history_tmp"
+                url_str = tab.url().toDisplayString() + "\n"
+                now=datetime.datetime.now().strftime("%Y %B %d %H:%M:%S")
+
+                with open(closed_history, 'r') as chf:
+                    with open(tmp_ch, "w") as tmpf:
+                        # If the url already saved, delete the old entry
+                        for line in (chf.readlines() [-99:]):
+                            if url_str not in line:
+                                tmpf.write(line)
+                        # Append the file with the current closed tab data
+                        tmpf.write(now + "|" + tab.title() + "|" + url_str)
+
+                shutil.copy(tmp_ch, closed_history)
+
         tab.private_api.shutdown()
         self.widget.removeTab(idx)
```

**Comment by Earnestly** [comment]
Why does this need to change the database? You should be using whatever strptime format you desire given `last_atime` from the unix epoch when generating completion entries for your tooling.

**Comment by Twix53791** [comment]
Well, if you find a way to be as fast as sqlite3 reading the database, I am hearing... Currently, my script takes 0.2 sec to display the list of a 10 000 lines history in fzf, but the history is growing fast, in a coupe of years, i will have much more entries. Before that, I had wrote a script maintaining a separate database, updated every time I launch the fzfhistory program from the qutebrowser database, but I don't launch my history often, so it was updating several hundreds of entries sometimes, and it was slow. CLI program loose all their benefits when they are slow. Whithout the lighting speed of sqlite3+fzf, rather use the native qutebrowser feature...

**Comment by The-Compiler** [comment]
The history database format is an implementation detail. If external tools can work with it, that's nice, but this isn't guaranteed. As such, I don't think it's reasonable to add data to it that only caters to external tools.

**Comment by toofar** [comment]
@Twix53791 you can use sqlite to convert the unix time in the DB to a string format. Eg `select datetime(last_atime, 'unixepoch') from CompletionHistory`.
In my case doing `time sqlite3 history.sqlite "select datetime(last_atime, 'unixepoch') from CompletionHistory" | wc -l` for a 300k table I'm seeing 100ms for `datetime(...)` vs 60ms for just the plain column.

**Comment by Twix53791** [comment]
Thanks a lot @toofar ! I did'nt know this possibility, its amazing! No need so to change the database history format...
