### ISSUE TITLE
Status bar widget: battery indicator

### ISSUE THREAD

**Issue by patrick-kidger** [qutebrowser/qutebrowser#8155]
I'm here to record a feature request: it'd be awesome (at least for me) to have a statusbar widget that displays the current battery percentage.

Lmk if this is of interest -- if so then I may take a crack at a PR for this (e.g. I've found [the statusbar folder](https://github.com/qutebrowser/qutebrowser/tree/main/qutebrowser/mainwindow/statusbar) without too much difficulty) so I imagine this shouldn't be too tricky.

Whilst I'm here, let me also thank you for your efforts for putting qutebrowser together. I'm a big fan!

**Comment by The-Compiler** [comment]
See #30 - outside of that, I don't think this is something that should be in qutebrowser itself.

**Comment by toofar** [comment]
If you are brave you can update the text statusbar widget from a userscript, including in a userscript that stays running a loop in the background, example here that relies on you having a autoconfig.yml: https://github.com/qutebrowser/qutebrowser/pull/6374#issuecomment-817044882

**Comment by patrick-kidger** [comment]
Interesting!

It has occurred to me that I might also be able to put something in `config.py` that reachs in to the qutebrowser internals and monkey-patches the existing clock widget -- to also check battery level. I've not tried that yet though.

If I get a bit of time I can give it a go and report back :)

**Comment by patrick-kidger** [comment]
For anyone else coming across this -- indeed, it's possible to monkey-patch this into the clock width from `config.py`. 

It's fairly specific to my setup, but here's my implementation:

```python
import sys

# Do a platform check as I'm not sure how caching works on Windows.
if sys.platform in {"darwin", "linux"}:
    import datetime
    import math
    import importlib.util
    import pathlib
    import subprocess
    from qutebrowser.mainwindow.statusbar.clock import Clock
    
    # Note for readers on GitHub: you may wish to put this cache somewhere else, e.g. not with my name in. :)
    qutebrowser_path = pathlib.Path.home() / ".cache" / "patrickkidger" / "qutebrowser"
    qutebrowser_path.mkdir(parents=True, exist_ok=True)
    psutil_path = qutebrowser_path / "psutil"
    if not psutil_path.exists():
        def _run(cmd):
            result = subprocess.run(cmd, capture_output=True, cwd=qutebrowser_path)
            if result.returncode != 0:
                raise RuntimeError(f"\ncmd: {cmd}\nreturncode: {result.returncode}\nstdout: {result.stdout.decode().strip()}\nstderr: {result.stderr.decode().strip()}")
            return result
            
        if sys.platform == "darwin":
            # Note that we download the x64 version even when running on an ARM Mac.
            _run(["/opt/homebrew/bin/wget", "https://files.pythonhosted.org/packages/e7/e3/07ae864a636d70a8a6f58da27cb1179192f1140d5d1da10886ade9405797/psutil-5.9.8-cp36-abi3-macosx_10_9_x86_64.whl"])
            _run(["unzip", "psutil-5.9.8-cp36-abi3-macosx_10_9_x86_64.whl"])
        else:
            # TODO: go to https://pypi.org/project/psutil/#files and grab the relevant file for Linux.
            raise NotImplementedError

    sys.path.append(str(qutebrowser_path))
    import psutil

    def _show_time(self):
        battery = psutil.sensors_battery()
        if battery.power_plugged:
            direction = "↑"
        else:
            direction = "↓"
        width = 7
        full = math.floor(width * (battery.percent / 100))
        empty = width - full
        blocks = "◼" * full + "◻" * empty
        clock = datetime.datetime.now().strftime(self.format)
        self.setText(f"{direction} {blocks} {battery.percent}%  {clock}")

    Clock._show_time = _show_time
```
