### ISSUE TITLE
Feature Request: Multiple row tabs when it exceed a certain amount of tab.

### ISSUE THREAD

**Issue by amalgame21** [qutebrowser/qutebrowser#8161]
When using `tabs.position top` and open a lot of tabs, the title and even the tab number become `...`, so they become meaningless.
I think it is a good idea to have a setting to open a new row of tabs to the next row when the tab number exceed a certain value, to make
And the max number of tab per row should also be configurable. 
What I mean is just like the `download` display system, when it exceed some amount of download item, it will display in a new row.
Thank you very much!

**Comment by The-Compiler** [comment]
Probably not possible as long as we're letting Qt draw the tab bar - thus merging this into #5308.
