### ISSUE TITLE
nyxt like and vieb like  good features

### ISSUE THREAD

**Issue by a-amr** [qutebrowser/qutebrowser#8171]
Hi, there are two things that I think are missing from qutebrowser that would make the experience a lot better:

YouTube watching like Vieb browser: This means that if you're in fullscreen video mode, you're always in insert mode. This way, YouTube bindings would work as normal, making it more intuitive. I always hit "i" to go into insert mode, but if I'm already in insert mode, it switches to the YouTube mini-player, which is not ideal.

Nyxt-like commands: This means having normal and insert modes inside the command prompt itself. This would make it more intuitive to choose one of the recommended menu options.

**Comment by mschilli87** [comment]
@a-amr: Instead of insert mode, you could use passthrough-mode to avoid you miniplayer issue.

**Comment by The-Compiler** [comment]
I'm not really convinced by the former - but in any case, it sounds like autocmds (#35) would allow for this kind of thing.

As for the latter, see #7698.
