### ISSUE TITLE
Qt 6.7: Overlay scrollbar not working anymore

### ISSUE THREAD

**Issue by horanmustaplot** [qutebrowser/qutebrowser#8204]
**Version info**:
qutebrowser v3.1.0
Git commit: 
Backend: QtWebEngine 6.7, based on Chromium 118.0.5993.220 (from api)
Qt: 6.7.0

**Does the bug happen if you start with `--temp-basedir`?**:
YES

**Description**
![image](https://github.com/qutebrowser/qutebrowser/assets/152083466/8dd4df3c-4c77-427d-9151-e9c7bc37796d)

Also I'm getting this annoying side bar, that i wasn't get when there's no errors.

![image](https://github.com/qutebrowser/qutebrowser/assets/152083466/7c405f83-03e0-40fe-ac05-27e4d6334071)

**Comment by The-Compiler** [comment]
The errors are unrelated and harmless - they'll be gone in Qt 6.7.1: [Fix error message when dictionary not found (553597) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/553597)

The scrollbar issue is something I can reproduce. Also happens with `QTWEBENGINE_CHROMIUM_FLAGS=--enable-features=OverlayScrollbar` but works fine in Chromium 124 with the same argument. So it sounds like something changed in QtWebEngine. Will need to look into it some more, but chances are we can't do much about it.

**Comment by The-Compiler** [comment]
From QtWebEngine IRC:

> \<kachehla\> hmm, seems the feature list doesn't get initialized in the renderer process properly

**Comment by The-Compiler** [comment]
Upstream fix: [Ensure Chromium features are propagated to child processes (563373) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/563373)

Doesn't look like something we could work around in qutebrowser, so closing this.
