### ISSUE TITLE
Drop macOS 11 Big Sur - no longer supported by GitHub actions

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#8207]
GitHub will be removing their macos-11 images at the end of June: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/

Since we switched to building releases via GitHub actions for the 3.0.0 release that means we won't be able to provide releases for that macOS version anymore. That's based on the assumption that you can't run builds targeted at newer releases on older ones, which from past discussions of dropping macOS versions is how I understand it.

The supported runner images are listed here: https://github.com/actions/runner-images?tab=readme-ov-file#available-images

So unless anyone has a different plan the work required for this is:

1. in ci.yaml replace `macos-12` with `macos-13`
2. replace any `macos-11` tags in the workflow files with `macos-12`
3. (optional) consider adding a `macos-14` CI job, although since that uses apple silicon it might be a bit more complicated and should be spun out to a separate ticket if so (see https://github.com/qutebrowser/qutebrowser/issues/6478 for some related discussions)
4. make sure all the non-flaky tests pass
5. run the nightly CI job on your branch and make sure the application starts on mac and basic functionality works

Previous issues about dropping macOS versions for reference (which was back when releases where built on a rented bare metal device): https://github.com/qutebrowser/qutebrowser/issues/5115 and https://github.com/qutebrowser/qutebrowser/issues/7092

:question:  One question I have is regarding the upcoming 3.2.0 release. If we are going to be unable to build patch releases for it after a month, should we try to switch to macos-12 ahead of this release?

Edit: looks like ubuntu-24.04 is available too, maybe we can add a CI job for that too while we are in yaml land

**Comment by The-Compiler** [comment]
Sounds good to me. Thanks for keeping track of this, wasn't on my radar so far!

I'd say let's keep it in for 3.2.0. It sounds like we should get a 3.2.1 in in time. After GitHub drops it, we might as well just make the next release 3.3.0. I'd rather have a 3.3.0 with only minor changes (and then dropping macOS 11 there) rather than dropping it for 3.2.0 already.

**Comment by The-Compiler** [comment]
Done in b78fc5765abebffa2fd3ef94b012c6e5f422c9c0 as the removal is tomorrow. Still leaving this open to test whether things actually work fine with the new macos-12 based release. Probably going to give it a spin tomorrow.

**Comment by toofar** [comment]
FWIW I installed the qutebrowser-nightly-2024-06-27-b78fc57-macos-intel build from [last night's](https://github.com/qutebrowser/qutebrowser/actions/runs/9703202216) run and it seems to install fine on the macos11 install I use for testing.
![image](https://github.com/qutebrowser/qutebrowser/assets/7419144/505ba019-5aef-49ed-b164-b3735db56ff1)

**Comment by The-Compiler** [comment]
Yup, looks to be working fine! :tada: Thanks for testing.
