### ISSUE TITLE
Youtube fullscreen doesn't work with Wayland (Ubuntu 24.04)

### ISSUE THREAD

**Issue by intuser** [qutebrowser/qutebrowser#8215]
**Version info**:
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.16, based on Chromium 87.0.4280.144
Qt: 5.15.13

CPython: 3.12.3
PyQt: 5.15.10

sip: 6.7.12
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.17.2
yaml: 6.0.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.45.1
QtNetwork SSL: OpenSSL 3.0.13 30 Jan 2024

Style: QFusionStyle
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 24.0.5-1ubuntu1
Platform: Linux-6.8.0-31-generic-x86_64-with-glibc2.39, 64bit
Linux distribution: Ubuntu 24.04 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /tmp/qutebrowser-basedir-38nnu3qo/cache
config: /tmp/qutebrowser-basedir-38nnu3qo/config
data: /tmp/qutebrowser-basedir-38nnu3qo/data
runtime: /tmp/qutebrowser-basedir-38nnu3qo/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:12

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

If I try to play a youtube video in fullscreen I either get a blurry and irregular playback or mostly just a white page. Sound seems okay.

**How to reproduce**

Works for all youtube videos I tested, one example: https://www.youtube.com/watch?v=JH3T6YwwU9s

Start Ubuntu 24.04 using the Wayland display server. Start watching a youtube video. Switch to fullscreen. Blurred or mostly white screen. (Theater mode is no problem. I also tested it with firefox, there seems to be no problem.)

**Comment by intuser** [comment]
I switched to a newer version of qutebrowser. The problem doesn't reappear with this version:

qutebrowser v3.1.0
Git commit: af2d15117 on main (2024-06-01 14:09:53 +0200)
Backend: QtWebEngine 6.4.2
  based on Chromium 102.0.5005.177
  with security patches up to 108.0.5359.94 (plus any distribution patches)
  (source: api)
Qt: 6.4.2

**Comment by The-Compiler** [comment]
This is all handled by Qt/QtWebEngine, so looks like it got fixed there in the meantime.
