### ISSUE TITLE
Feature Request: Picture-In-Picture mode for video players

### ISSUE THREAD

**Issue by reidiens** [qutebrowser/qutebrowser#8218]
I'd like to request a picture-in-picture setting for video players, where the video would pop out into its own movable resizeable window. It's probably a big ask, but it would be amazing for productivity and general quality-of-use.

**Comment by The-Compiler** [comment]
This is something QtWebEngine would need to handle, not qutebrowser: [[QTBUG-82390] Support "picture in picture" mode for videos - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-82390)

Depending on the video in question you might be able to play it externally with e.g. mpv and yt-dlp.

**Comment by reidiens** [comment]
ah i wasnt aware of that. thanks for the quick reply
