### ISSUE TITLE
Query state of webpage in userscript?

### ISSUE THREAD

**Issue by OmegaLambda1998** [qutebrowser/qutebrowser#8231]
Is it possible to query the state of the current webpage throughout the running of a userscript? I.e, If I send a command via FIFO, can I ask qutebrowser what mode, url, etc... it's changed to?

Can you say "do this, then wait for this, then do this"

**Comment by OmegaLambda1998** [comment]
Something similar to https://github.com/richardpenman/browsercookie would be awesome

**Comment by The-Compiler** [comment]
See #30 and #902.

As for reading cookies, #5500 might allow us to store them in a more readable format, but in theory you could already use projects that extract chromium cookies (there are a couple). I'm not sure if/when QtWebEngine/Chromium writes cookies to disk, though.
