### ISSUE TITLE
Webkit docker tests timing out

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#8247]
The CI job that runs the tests against pyqt webkit has been timing out for a few days now. The tests all pass like normal but the job hangs when it should be exiting: https://github.com/qutebrowser/qutebrowser/actions/runs/9702937399/job/26779937474#step:5:373

The environment these tests run in is a bit of a frankenarch, it's based on an archlinux container but it installs old python and pyqt5 packages [from the archives](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/dev/ci/docker/Dockerfile.j2#L40), since arch no longer ships Qt5 and webkit isn't included in Qt6. So it was just a matter of time until that arrangement broke.

This breakage is a little odd though, so maybe there is some low effort way we can get it working again?

I think I've narrowed the reproducer down to a combination of a) the python version being installed in the container b) pytest-bdd c) hypothesis 6.103.4+.

I've tried to reproduce the issue on `python:3.10-slim-bookworm` and it doesn't hang there. Is it something to do with the 10.10 build specifically that we are using in that container?

Here's a minimal dockerfile:

```dockerfile
FROM archlinux:latest

RUN pacman-key --init && pacman-key --populate
RUN pacman -Sy --noconfirm archlinux-keyring

# Recent python - doesn't hang
#RUN pacman -Su --noconfirm python python-pip
#RUN python3 -m pip install --break-system-packages pytest hypothesis pytest-bdd

# Old python - hangs
RUN pacman -U --noconfirm https://archive.archlinux.org/packages/p/python/python-3.10.10-1-x86_64.pkg.tar.zst
RUN python3 -m ensurepip
RUN python3 -m pip install pytest hypothesis pytest-bdd

# Old hypothesis - doesn't hang
#RUN python3 -m pip install hypothesis==6.103.3
```

If you save that as a file called `Dockerfile-webkithang` you can build that into a container image like `docker build --tag 'webkithang' - < Dockerfile-webkithang` and then reproduce the hang like `docker run -it webkithang timeout 5 python3 -m pytest asdf ; [ $? -eq 124 ] && echo "command timed out"`.
The `timeout ...  ; [ $? -eq 124 ] && echo "command timed out"` is because when it hangs when invoked like this you can't kill the docker command with ctrl-c or ctrl-\\, you have to kill the container from another terminal. But if you just do `docker run -it webkithang bash` and then run `python3 -m pytest asdf` in there you'll be able to see how it hangs and you can kill it with ctrl-c.
The "asdf" argument to pytest is just to stop it crawling the whole filesystem. The issue reproduces with real tests of course, but they aren't necessary, so here I'm not using any.

The only change in hypothesis between the working 6.103.3 and the hanging 6.103.4 version is this change to move some caches into thread local storage: https://github.com/HypothesisWorks/hypothesis/pull/4013/files
It seems pretty innocuous, and since I can't reproduce the issue on 3.10.14 it's probably something a little more esoteric than a bug in that change. Super weird though.

Some ideas about how we could deal with this:
1. pin hypothesis
    * for how long? Doesn't seem like a good idea. I guess we could do it just for webkit
2. switch webkit tests to a different base container
    * debian is still [packaging webkit](https://tracker.debian.org/pkg/qtwebkit-opensource-src), not sure how long that's going to last but they don't seem [in a hurry](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069574) to remove it
    * I just tested with the qute 2.5.4 version (which is still the one packaged in debian) and it can't load duckduckgo (JS error) and crashes on youtube. Woohoo! At least we know no-one is using it. It'll probably still run the tests though
3. try more to find out what the issue is and report that upstream or figure out some local workaround
    * since we know it has something to do with thread local storage, and pytest-bdd somehow, we should be able to figure it out. Not feeling particularly motivated to though
4. Drop webkit support https://github.com/qutebrowser/qutebrowser/issues/4039
    * I think it's pretty clear there's not going to be a qtwebkit with the same level of stability and support as webengine again. There's been a few attempts at it over the last few years but I don't think any of them have picked up steam
    * Not sure how big this task is, if it's just deleting stuff and identifying gaps in test coverage we need to address over time it shouldn't be too much work (although certainly non-trivial)
    * There is [some concern](https://github.com/qutebrowser/qutebrowser/issues/4039#issuecomment-779703250) that only have one backend again will weaken the abstractions we have currently, but while I empathise with that that it's an, ahem, abstract concern. And I feel like the concrete concerns of not being able to actually support the second backend has a bit more weight to it. And we can always re-architect when we add in a new backend! Potentially designing for extensions and what would make sense to extensions authors would help with that anyway.
    * Also, I really want to get back to working on tree tab support so I'm personally motivated to take a lower effort approach for now.

I guess what I'm leaning toward after all that is to pin hypothesis for webkit and set ourselves the goal of being webkit free by Christmas. I feel like having a date for when we are going to drop it makes it a bit easier to add workarounds for it and not invest in properly fixing every little issue that comes up.

**Comment by The-Compiler** [comment]
Reproduced locally with:

```
$ pyenv install --verbose 3.10.10
$ pyenv shell 3.10.10
$ pyenv exec python -m venv .venv
$ .venv/bin/pip install hypothesis pytest-bdd
$ .venv/bin/pytest asdf
```

With Python 3.10.11, it works fine.

Seems to be hanging in:

```
#0  0x00007ffff78a348b in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff78af278 in ?? () from /usr/lib/libc.so.6
#2  0x00007ffff7c1daf6 in PyThread_acquire_lock_timed (lock=0x5555555592a0, microseconds=-1, intr_flag=intr_flag@entry=0) at Python/thread_pthread.h:486
#3  0x00007ffff7c1dd2c in PyThread_acquire_lock (lock=<optimized out>, waitflag=<optimized out>) at Python/thread_pthread.h:752
#4  0x00007ffff7c7cf70 in local_clear (self=self@entry=0x7ffff584c9f0) at ./Modules/_threadmodule.c:861
#5  0x00007ffff7c7d0a5 in local_dealloc (self=0x7ffff584c9f0) at ./Modules/_threadmodule.c:893
#6  0x00007ffff7b28273 in _Py_DECREF (op=<optimized out>) at ./Include/object.h:500
#7  clear_slots (type=<optimized out>, self=<optimized out>) at Objects/typeobject.c:1267
#8  subtype_dealloc (self=<LRUReusedCache at remote 0x7ffff5852640>) at Objects/typeobject.c:1427
#9  0x00007ffff7afc22d in _Py_DECREF (op=<optimized out>) at ./Include/object.h:500
#10 _Py_XDECREF (op=<optimized out>) at ./Include/object.h:567
#11 free_keys_object (keys=0x7ffff585cdf0) at Objects/dictobject.c:628
#12 0x00007ffff7afd358 in dictkeys_decref (dk=0x7ffff585cdf0) at Objects/dictobject.c:337
#13 dict_dealloc (mp=0x7ffff58ebd00) at Objects/dictobject.c:2076
#14 0x00007ffff7b00c11 in _PyDict_DelItem_KnownHash (op=Python Exception <class 'gdb.error'>: There is no member named dk_log2_size.
, key=key@entry=<weakref.ReferenceType at remote 0x7ffff58f1080>, hash=8796082245303) at Objects/dictobject.c:1719
#15 0x00007ffff7b00c9b in PyDict_DelItem (op=<optimized out>, key=key@entry=<weakref.ReferenceType at remote 0x7ffff58f1080>) at Objects/dictobject.c:1685
#16 0x00007ffff7c7ce25 in _localdummy_destroyed (localweakref=<optimized out>, dummyweakref=<weakref.ReferenceType at remote 0x7ffff58f1080>) at ./Modules/_threadmodule.c:1057
#17 0x00007ffff7b0f14a in cfunction_vectorcall_O (func=<built-in method _localdummy_destroyed of weakref.ReferenceType object at remote 0x7ffff58f0fe0>, args=0x7fffffffc3b8, nargsf=<optimized out>, kwnames=<optimized out>)
    at Objects/methodobject.c:516
#18 0x00007ffff7b86164 in _PyObject_VectorcallTstate (nargsf=9223372036854775809, kwnames=0x0, tstate=0x555555576c30, callable=<built-in method _localdummy_destroyed of weakref.ReferenceType object at remote 0x7ffff58f0fe0>, 
    args=0x7fffffffc3b8) at ./Include/cpython/abstract.h:114
#19 PyObject_CallOneArg (func=<built-in method _localdummy_destroyed of weakref.ReferenceType object at remote 0x7ffff58f0fe0>, arg=<optimized out>) at ./Include/cpython/abstract.h:184
#20 handle_callback (ref=<optimized out>, callback=<built-in method _localdummy_destroyed of weakref.ReferenceType object at remote 0x7ffff58f0fe0>) at Objects/weakrefobject.c:952
#21 0x00007ffff7b89bc3 in PyObject_ClearWeakRefs (object=object@entry=<_thread._localdummy at remote 0x7ffff5b8eb70>) at Objects/weakrefobject.c:998
#22 0x00007ffff7c7d055 in localdummy_dealloc (self=0x7ffff5b8eb70) at ./Modules/_threadmodule.c:676
#23 0x00007ffff7afc22d in _Py_DECREF (op=<optimized out>) at ./Include/object.h:500
#24 _Py_XDECREF (op=<optimized out>) at ./Include/object.h:567
#25 free_keys_object (keys=0x555555a509b0) at Objects/dictobject.c:628
#26 0x00007ffff7afd358 in dictkeys_decref (dk=0x555555a509b0) at Objects/dictobject.c:337
#27 dict_dealloc (mp=0x7ffff65b56c0) at Objects/dictobject.c:2076
#28 0x00007ffff7c0c825 in _Py_DECREF (op=<optimized out>) at ./Include/object.h:500
#29 PyThreadState_Clear (tstate=tstate@entry=0x555555576c30) at Python/pystate.c:848
#30 0x00007ffff7c0c8e8 in interpreter_clear (interp=0x55555555adb0, tstate=0x555555576c30) at Python/pystate.c:298
#31 0x00007ffff7c0cecc in _PyInterpreterState_Clear (tstate=<optimized out>) at Python/pystate.c:361
#32 0x00007ffff7c0597b in finalize_interp_clear (tstate=tstate@entry=0x555555576c30) at Python/pylifecycle.c:1665
#33 0x00007ffff7c09437 in Py_FinalizeEx () at Python/pylifecycle.c:1843
#34 Py_FinalizeEx () at Python/pylifecycle.c:1703
#35 0x00007ffff7c304dd in Py_RunMain () at Modules/main.c:668
#36 0x00007ffff7c30fb6 in pymain_main (args=0x7fffffffc6a0) at Modules/main.c:696
#37 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:720
#38 0x00007ffff7839c88 in ?? () from /usr/lib/libc.so.6
#39 0x00007ffff7839d4c in __libc_start_main () from /usr/lib/libc.so.6
#40 0x0000555555555075 in _start ()
```

Might be this CPython bug, from looking at its changelog?

- https://github.com/python/cpython/issues/102126

Funnily enough, that was tied to another Hypothesis change with another pytest plugin (pytest-httpserver):

- https://github.com/HypothesisWorks/hypothesis/issues/3585

**Comment by The-Compiler** [comment]
In b241b0360bc053b21b51677aca8d55b7937fc322 and 4d2361288d5fcbc5d9ff05faae46139f0cbfae9e I pushed a change to build an up to date Python 3.10 from sources instead.

It [increases the build time](https://github.com/qutebrowser/qutebrowser/actions/workflows/docker.yml) for the docker images from 3 to 18 minutes, but I suppose there could be worse since they are running overnight only.

Will write more about your alternative considerations above later, I started a Qt debug build and want to send this before the OOM killer kicks in.

**Comment by toofar** [comment]
Ah, build a newer python patch version, of course! Pretty impressive that it's a one-liner on arch too! I looked to see if there was a 3.10.10 version on docker or deadsnakes and didn't see one, didn't think of compiling it myself. I guess that's why I'm not called the compiler ;)

Thanks for picking this up and spending so much time on it! It's a relief to be able to focus on something else on my todo list today.

> Will write more about your alternative considerations above later

:eyes:
