### ISSUE TITLE
QtWebEngine includes a hidden extension, available only to `*.google.com` domains

### ISSUE THREAD

**Issue by illfygli** [qutebrowser/qutebrowser#8257]
**Version info**:

qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
It came to my attention that [Chrome includes a hidden extension](https://simonwillison.net/2024/Jul/9/hangout_servicesthunkjs/), which gives Google domains exclusive access to additional system information.

This extension appears to also be included in qutebrowser.

**How to reproduce**

Open `google.com` and enter the following in the JS console:
```
chrome.runtime.sendMessage(
  "nkeimhogjdpnpccoofpliimaahmaaome",
  { method: "cpu.getInfo" },
  (response) => {
    console.log(JSON.stringify(response, null, 2));
  },
);
```
You will get some output. On a non-google domain, you will instead get a `TypeError`.

This comes from Chromium via QtWebEngine, but I'm not sure how to write a patch to disable or remove it. Would be happy to do so with guidance.

**Comment by The-Compiler** [comment]
See [[QTBUG-118452] Allow disabling builtin extensions at runtime - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-118452). Surely it'll already be possible to disable it via a patch in some way or another, but I've never tried.

We [have an elaborate hack](https://github.com/qutebrowser/qutebrowser/blob/main/qutebrowser/misc/pakjoy.py) around repackaging Chromium resource files at startup, which disables the Hangout extension (which might be what's allowing this as well?). However it only does that on Qt versions affected by critical bugs with it (6.6.0 and 6.5.0 - 6.5.3 with dark mode).

We could probably add a setting that would allow to trigger that hack on any Qt version.

**Comment by The-Compiler** [comment]
Related Brave issues:

- https://github.com/brave/brave-browser/issues/39660
- https://github.com/brave/brave-browser/issues/39664
- https://github.com/brave/brave-core/pull/24583

We should probably give that a try with out workaround, and if's indeed not required at all, ask QtWebEngine to remove the extension completely...

Some people there claim that Google Meet actually works great without the extension enabled at all?

**Comment by illfygli** [comment]
That sounds good. Hopefully it can just be removed.

I can try it with the "elaborate hack". :)

If QtWebEngine folks don't want to remove it, I can add the setting.

**Comment by illfygli** [comment]
I can confirm that these things work on Google Meet, with the extention disabled:

- Microphone audio
- Webcam video
- Desktop screen-sharing

I verified that `chrome.runtime === undefined` in this session.
