### ISSUE TITLE
Launch qutebrowser in a new session/instance.

### ISSUE THREAD

**Issue by ZiWenWangCS** [qutebrowser/qutebrowser#8261]
**Version info**:

Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2 (compiled 6.7.1)

**Does the bug happen if you start with `--temp-basedir`?**: 
No.

I think a potential fix is to check the envrionment variable ``$DISPLAY`` and launch qutebrowser accrodingly. 

**Description**
Launch qutebrowser in a new session/instance.
**How to reproduce**

This can be reproduced by two tty.
On tty1 launch qutebrowser. Then on the second tty, launch it again and qutebrowser will go into the first tty.

**Comment by toofar** [comment]
You can use the -B|--basedir argument to point qutebrowser to a specific folder that it will use to isolate it's data, this is how we support running multiple separate browser instances/profiles.
If you want to auto-select a specific basedir based on the current display environment I think that's up to you/the community to write a wrapper script to launch qutebrowser (end eg set that script as your default browser and put it before qutebrowser in your path). Unless more people vote for a display-aware feature I'm not sure that's something we want to bother putting effort into in the core.
