### ISSUE TITLE
Everything looks clunky

### ISSUE THREAD

**Issue by yogo1212** [qutebrowser/qutebrowser#8270]
**Version info**:

```
qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

CPython: 3.12.4
PyQt: 6.7.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: no
yaml: 6.0.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: no
sqlite: 3.46.0
QtNetwork SSL: OpenSSL 3.3.1 4 Jun 2024

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 24.1.4-arch1.2
Platform: Linux-6.9.10-arch1-1-x86_64-with-glibc2.39, 64bit
Linux distribution: EndeavourOS (arch)
Frozen: False
Imported from /usr/lib/python3.12/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6
```

**Does the bug happen if you start with `--temp-basedir`?**:

I've already started editing this issue with qutebrowser and don't want to restart right now.
It'll be in a comment.

EDIT: the issue is also present with `--temp-basedir`

**Description**

Pretty much everything - including fonts, SVG images, and borders - looks as if rendered without anti-aliasing.

![2024-07-23T09:47:42,473390191+02:00](https://github.com/user-attachments/assets/d7565f83-5f81-4779-8be6-bbb957db09d1)

**How to reproduce**

Load web page, for instance [this issue](https://github.com/qutebrowser/qutebrowser/issues/1648).

**Comment by yogo1212** [comment]
Doesn't happen with otter

**Comment by The-Compiler** [comment]
Duplicate of #8135

**Comment by yogo1212** [comment]
I've seen the issue title but disregarded it for its 'blurriness' - to me, this is the opposite of blurriness :smile: 
Also, I wasn't aware that I had any fractional scaling going on with this run-of-the-mill Toshiba laptop from 2012.
Now I do!

My bad!
And thanks :+1:
