### ISSUE TITLE
crash when no outputs remains?

### ISSUE THREAD

**Issue by stacyharper** [qutebrowser/qutebrowser#8273]
**Version info**:

```
qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

CPython: 3.12.3
PyQt: 6.7.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: 4.0.379 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.46.0
QtNetwork SSL: OpenSSL 3.3.1 4 Jun 2024

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 24.1.4
Platform: Linux-6.6.43-0-lts-x86_64-with, 64bit
Linux distribution: Alpine Linux edge (alpine)
Frozen: False
Imported from /usr/lib/python3.12/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /home/willow/.cache/qutebrowser
config: /home/willow/.config/qutebrowser
data: /home/willow/.local/share/qutebrowser
runtime: /run/user-1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/willow/.config/qutebrowser/config.py has been loaded
Uptime: 0:01:04
```

**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

From some releases, my qutebrowser windows are crashed when I come back to my work-station. I lock my Sway session with swaylock, and it shutdown the screen outputs after some seconds. My screens blinks a bit when I type my passphrase. Then I have to re-run qutebrowser again, and encounter the crashed report modal. 

**How to reproduce**

- start qutebrowser
- shut down the output, by example with this command `swayidle -w timeout 10 "swaymsg -- output '*' power false" resume "swaymsg -- output '*' power true"`.
- wait 10s, and wait for all external monitor to shutdown
- click on something to wake the screens up

Here the output from the command: `gdb -ex r --args $(readlink -f $(which python3)) -m qutebrowser --debug --temp-basedir`

[gdb.txt](https://github.com/user-attachments/files/16455790/gdb.txt)

**Comment by The-Compiler** [comment]
Relevant part of the stacktrace:

```cpp
#0  0x00007ffff45c3040 in QPlatformScreen::screen() const () at /usr/lib/libQt6Gui.so.6
#1  0x00007fffdfa5a187 in QtWaylandClient::QWaylandWindow::handleScreensChanged() () at /usr/lib/qt6/plugins/platforms/../../..//libQt6WaylandClient.so.6
#2  0x00007ffff65b3e39 in ??? () at /usr/lib/libQt6Core.so.6
#3  0x00007ffff65b3e39 in ??? () at /usr/lib/libQt6Core.so.6
#4  0x00007ffff45a2533 in QGuiApplication::screenAdded(QScreen*) () at /usr/lib/libQt6Gui.so.6
#5  0x00007fffdfa2face in QtWaylandClient::QWaylandDisplay::handleScreenInitialized(QtWaylandClient::QWaylandScreen*) () at /usr/lib/qt6/plugins/platforms/../../..//libQt6WaylandClient.so.6
#6  0x00007fffdfa51364 in QtWaylandClient::QWaylandScreen::maybeInitialize() () at /usr/lib/qt6/plugins/platforms/../../..//libQt6WaylandClient.so.6
#7  0x00007ffff4090f0a in ??? () at /usr/lib/libffi.so.8
#8  0x00007ffff409070f in ??? () at /usr/lib/libffi.so.8
#9  0x00007ffff4090aed in ffi_call () at /usr/lib/libffi.so.8
#10 0x00007ffff418343a in ??? () at /usr/lib/libwayland-client.so.0
#11 0x00007ffff418390d in ??? () at /usr/lib/libwayland-client.so.0
#12 0x00007ffff4183c4d in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#13 0x00007fffdfa260e6 in QtWaylandClient::QWaylandDisplay::flushRequests() () at /usr/lib/qt6/plugins/platforms/../../..//libQt6WaylandClient.so.6
#14 0x00007ffff65b43ca in ??? () at /usr/lib/libQt6Core.so.6
#15 0x00007ffff679600d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#16 0x00007ffff656a81c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#17 0x00007ffff6562bd5 in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
```

Oddly I can't find much in Qt's bugtracker, other than old Qt 5 bugs - but this sounds like something qutebrowser can't do much about. Can you try if you can reproduce it with e.g. the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py), or possibly any other application using Qt 6?

**Comment by stacyharper** [comment]
Yes I reproduce this with Falkon and with the testbrowser script

**Comment by The-Compiler** [comment]
Sounds like an issue between Qt and/or your setup then - not much qutebrowser can do here. Since it doesn't sound like something you can easily reproduce, I'd recommend you report this to the [Qt bugtracker](https://bugreports.qt.io/) yourself instead - it'd be great if you could link it here afterwards though!

**Comment by migrgh** [comment]
Same behaviour here. It is enough to turn my screen off and on again the produce the crash.

One thing i notice in log are:

`Dec 31 13:29:36 linux qutebrowser[1273]: 13:29:36 INFO: Creating a Ofake screen in order for Qt not to crash`
