### ISSUE TITLE
copy button on website generate : write permission denied

### ISSUE THREAD

**Issue by maxigit** [qutebrowser/qutebrowser#8279]
**Version info**:

qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
Copy button on website (for example clone url on github) doesn't copy anything to the clipboard  but generate 

    Uncaught (in promise) DOMException: Write permission denied.

in the console
**How to reproduce**
Go to github , [qutebrowser](https://github.com/qutebrowser/qutebrowser) main page for example and press the copy (two rectangles icon) in <> Code / local / Clone panel.

**Comment by The-Compiler** [comment]
See 22. in the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/main/doc/faq.asciidoc).

**Comment by maxigit** [comment]
Sorry about that, missed it in the FAQ.
Thank you very much for your prompt response.
