### ISSUE TITLE
Key_CapsLock stops key parsing

### ISSUE THREAD

**Issue by matthiakl** [qutebrowser/qutebrowser#8285]
**Version info**:

qutebrowser v3.2.1
Git commit:
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I cannot use any key combinations with lower then upper case letters (e.g. "gC", "pW").
Directly when I press the Shift key, the command parser aborts. The key tester shows that the detected key for Shift is <Shift+CapsLock> and it does not wait for an actual letter.

**How to reproduce**

I think it happens since updating to Plasma 6 and might be related to my unusual keyboard layout.
Changing the layout to qwertz still gives the same result, but CapsLock is not working at all.
OS: Arch Linux
Desktop: KDE Plasma 6/Wayland
Keyboard layout: neo2

**Log**
Full log from `qutebrowser --temp-basedir -D log-sensitive-keys` attached.
[qutebrowser.log](https://github.com/user-attachments/files/16687800/qutebrowser.log)
```
08:36:18 DEBUG    modes      modeman:_handle_keypress:276 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Got key: <qutebrowser.keyinput.keyutils.KeyInfo key='Key_P' modifiers='NoModifier' text='p'> (dry_run False)
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: No match for 'p' (added p)
08:36:18 DEBUG    modes      modeman:_handle_keypress:309 match: SequenceMatch.PartialMatch, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False, dry_run: False --> filter: True (focused: <PyQt6.QtWidgets.QWidget object at 0x780583fb3e30, className='QQuickWidget'>)
08:36:18 DEBUG    modes      modeman:_handle_keyrelease:334 filter: True
08:36:18 DEBUG    modes      modeman:_handle_keypress:276 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Got key: <qutebrowser.keyinput.keyutils.KeyInfo key='Key_CapsLock' modifiers='ShiftModifier' text='<Shift+CapsLock>'> (dry_run True)
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Trying match without modifiers
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Trying match with key_mappings
08:36:18 DEBUG    modes      modeman:_handle_keypress:309 match: SequenceMatch.NoMatch, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt6.QtWidgets.QWidget object at 0x780583fb3e30, className='QQuickWidget'>)
08:36:18 DEBUG    modes      modeman:_handle_keypress:276 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Got key: <qutebrowser.keyinput.keyutils.KeyInfo key='Key_CapsLock' modifiers='ShiftModifier' text='<Shift+CapsLock>'> (dry_run True)
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Trying match without modifiers
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Trying match with key_mappings
08:36:18 DEBUG    modes      modeman:_handle_keypress:309 match: SequenceMatch.NoMatch, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt6.QtWidgets.QWidget object at 0x780583fb3e30, className='QQuickWidget'>)
08:36:18 DEBUG    modes      modeman:_handle_keypress:276 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Got key: <qutebrowser.keyinput.keyutils.KeyInfo key='Key_CapsLock' modifiers='ShiftModifier' text='<Shift+CapsLock>'> (dry_run False)
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Trying match without modifiers
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Trying match with key_mappings
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Giving up with 'p<Shift+CapsLock>', no matches
08:36:18 DEBUG    keyboard   basekeyparser:_debug_log:202 NormalKeyParser for mode normal: Clearing keystring (was: p<Shift+CapsLock>).
```

**Comment by The-Compiler** [comment]
Thanks for the detailed bug report!

This seems relevant: [[QTBUG-26484] QtEvent::key() wrongly returns Qt::Key_CapsLock instead of Qt::Key_Shift on key up event (German Neo keyboard layout) - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-26484)

According to that bug, Qt's behavior is correct. Could you also show the output of [wev](https://archlinux.org/packages/extra/x86_64/wev/)?

**Comment by matthiakl** [comment]
Here it is:
<details title="wev log">
<pre>
[06:         wl_seat] capabilities: pointer keyboard
[06:         wl_seat] name:
[10:    xdg_toplevel] configure: width: 0; height: 0
[09:     xdg_surface] configure: serial: 28704
[14:     wl_keyboard] repeat_info: rate: 25 keys/sec; delay: 600 ms
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 81094
[14:     wl_keyboard] enter: serial: 28708; surface: 3
'                     sym: Return       (65293), utf8: '
[14:     wl_keyboard] modifiers: serial: 0; group: 0
depressed: 00000000
latched: 00000000
locked: 00000000
[11:  wl_data_device] data_offer: id: 4278190080
[4278190080:   wl_data_offer] offer: mime_type: text/plain
[4278190080:   wl_data_offer] offer: mime_type: application/x-kde-onlyReplaceEmpty
[4278190080:   wl_data_offer] offer: mime_type: text/plain;charset=utf-8
[11:  wl_data_device] selection: id: 4278190080
[10:    xdg_toplevel] configure: width: 640; height: 480
activated
[09:     xdg_surface] configure: serial: 28711
[14:     wl_keyboard] key: serial: 28713; time: 15137025; key: 36; state: 0 (released)
sym: Return       (65293), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
depressed: 00000001: Shift
latched: 00000000
locked: 00000000
[14:     wl_keyboard] key: serial: 28717; time: 15138350; key: 50; state: 1 (pressed)
sym: Caps_Lock    (65509), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
depressed: 00000000
latched: 00000000
locked: 00000000
[14:     wl_keyboard] key: serial: 28721; time: 15139174; key: 50; state: 0 (released)
sym: Shift_L      (65505), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
depressed: 00000080: Mod5
latched: 00000000
locked: 00000000
[14:     wl_keyboard] key: serial: 28725; time: 15140019; key: 66; state: 1 (pressed)
sym: ISO_Level3_Shift (65027), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
depressed: 00000000
latched: 00000000
locked: 00000000
[14:     wl_keyboard] key: serial: 28729; time: 15141548; key: 66; state: 0 (released)
sym: ISO_Level3_Shift (65027), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
depressed: 00000001: Shift
latched: 00000000
locked: 00000000
[14:     wl_keyboard] key: serial: 28733; time: 15158220; key: 50; state: 1 (pressed)
sym: Caps_Lock    (65509), utf8: ''
[14:     wl_keyboard] key: serial: 28734; time: 15158774; key: 27; state: 1 (pressed)
sym: C            (67), utf8: 'C'
[14:     wl_keyboard] key: serial: 28735; time: 15159351; key: 27; state: 0 (released)
sym: C            (67), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
depressed: 00000000
latched: 00000000
locked: 00000000
[14:     wl_keyboard] key: serial: 28739; time: 15159844; key: 50; state: 0 (released)
sym: Shift_L      (65505), utf8: ''
</pre>
</details>
Interestingly it reports Caps_Lock on key down but Shift_L on key up.
When I press the actual Caps Lock key it is correctly detected as ISO_Level3_Shift up/down.
So I guess the application cannot do much about it?

**Comment by The-Compiler** [comment]
Yes, that looks like a bug of some sorts in the keyboard layout to me. Maybe there is a way to make the qutebrowser part of things ignore it as a special case, but I'm somewhat lukewarm on this, as it'd be a Neo-specific hack.

**Comment by achilleas-k** [comment]
I have this same issue on two machines, with different distributions (Arch and Fedora 40) and keyboard layouts.  I'll post some debug details later, but I wanted to bring it up since I just came across this now.

**Comment by matthiakl** [comment]
@achilleas-k which DE do you have? I posted this also to KDE, but still unsure what the root cause is.
See https://bugs.kde.org/show_bug.cgi?id=492726

**Comment by achilleas-k** [comment]
KDE on both instances.  The keyboard layout is "gb" on both but it also happens when I switch to my secondary layout which is "gr".

**Comment by matthiakl** [comment]
Does not happen anymore with latest Qt/Plasma update.
