### ISSUE TITLE
Progressive Web App (PWA) support

### ISSUE THREAD

**Issue by crueter** [qutebrowser/qutebrowser#8288]
I have no idea if this would be possible given QtWebEngine's limitations, but having PWAs be done through qutebrowser with all of its keyboard-driven magic would be a great feature to have.

**Comment by The-Compiler** [comment]
Nope, QtWebEngine doesn't expose any APIs for this. Given that I have no personal interest in this, and I'd assume most qutebrowser users don't (PWAs have been around for 5 years or so, but I believe this is the first time this comes up), I'd suggest you instead open a QtWebEngine issue upstream to see what they say about it.

If/once QtWebEngine has APIs for this kind of thing this can be revisited, but until then, nothing actionable for qutebrowser here I'm afraid.
