### ISSUE TITLE
exiting insert mode after enter on search bar

### ISSUE THREAD

**Issue by Combowombo** [qutebrowser/qutebrowser#8306]
Hi I have found previous versions of this problem in other tickets, for example here:

https://www.reddit.com/r/qutebrowser/comments/m9vw0l/how_to_exit_insert_mode_after_pressing_enter/

:set input.insert_mode.leave_on_load true 
^ this command works fine for most sites

the problem is that for certain sites like youtube, seekingalpha, or github, i believe the developers of the webpage aren't actually refreshing the page on search causing insert mode to stay on.

**Comment by The-Compiler** [comment]
Your description is correct - as far as I'm aware, there's nothing qutebrowser can do here, other than possibly using IME to track whether an editable field is focused. This is tracked in #2471 already.
