### ISSUE TITLE
Update to libjxl 0.11

### ISSUE THREAD

**Issue by rabaimorp** [qutebrowser/qutebrowser#8315]
**Version info**:
qutebrowser v3.2.1
Git commit: b73aadb73 on main (2024-09-27 18:24:50 +1200)
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

CPython: 3.12.6
PyQt: 6.7.1

**Description**
Qutebrowser is still looking for libxjl 0.10 even after the update.
Creating a symbolic link from libxjl 0.10 to 0.11(and libjxl_threads also) fixed it, so I guess it just has to be updated what the browser is looking for.

**How to reproduce**
Try to launch brower on an up to date system like Arch Linux (with libjxl 0.11). Get error because qutebrowser is still looking for libxjl 0.10.

**Comment by rabaimorp** [comment]
I've updated to the latest commit, issue still present

**Comment by The-Compiler** [comment]
qutebrowser is Python code and does not use libjxl itself at all. This is an issue on your system, possibly a partial system upgrade - but not much more I can say without any actual error message.

**Comment by The-Compiler** [comment]
That's what I'm saying: qutebrowser does not directly depend on libjxl. It looks like QtWebEngine does, and yours seems to be outdated:

```
$ ldd /usr/lib/libQt6WebEngineCore.so | grep jxl
	libjxl.so.0.11 => /usr/lib/libjxl.so.0.11 (0x0000706307e00000)
	libjxl_threads.so.0.11 => /usr/lib/libjxl_threads.so.0.11 (0x000070630dab3000)
	libjxl_cms.so.0.11 => /usr/lib/libjxl_cms.so.0.11 (0x00007062fa272000)

$ pacman -Qo /usr/lib/libQt6WebEngineCore.so
/usr/lib/libQt6WebEngineCore.so is owned by qt6-webengine 6.7.2-3
```

This isn't a qutebrowser issue, it's your system being broken in some way. Any other application using QtWebEngine will fail in the exact same way.

**Comment by rabaimorp** [comment]
Isn't that supposed to be upgraded with the rest of my system? I did not do any partial updates just a full "pacman -Syu" Now I have no idea how to fix this

**Comment by The-Compiler** [comment]
For starters, run the commands above and show the output. Showing your `/etc/pacman.conf` and `/etc/pacman.d/mirrorlist` might be good too.

**Comment by rabaimorp** [comment]
```
$ ldd /usr/lib/libQt6WebEngineCore.so | grep jxl
	libjxl.so.0.10 => not found
	libjxl_threads.so.0.10 => not found
$ pacman -Qo /usr/lib/libQt6WebEngineCore.so
/usr/lib/libQt6WebEngineCore.so is owned by qt6-webengine 6.7.2-3
$ cat /etc/pacman.d/mirrorlist
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector @/etc/xdg/reflector/reflector.conf
# When:       2024-06-27 12:08:26 UTC
# From:       https://archlinux.org/mirrors/status/json/
# Retrieved:  2024-06-27 12:07:45 UTC
# Last Check: 2024-06-27 11:41:42 UTC

Server = https://mirror.f4st.host/archlinux/$repo/os/$arch
Server = https://mirror.cyberbits.eu/archlinux/$repo/os/$arch
Server = https://mirror.osbeck.com/archlinux/$repo/os/$arch
Server = https://mirror.moson.org/arch/$repo/os/$arch
Server = https://archmirror.it/repos/$repo/os/$arch
Server = https://packages.oth-regensburg.de/archlinux/$repo/os/$arch
Server = https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch
Server = https://mirror.telepoint.bg/archlinux/$repo/os/$arch
Server = https://arch.phinau.de/$repo/os/$arch
Server = https://mirror.ubrco.de/archlinux/$repo/os/$arch
Server = https://mirror.theo546.fr/archlinux/$repo/os/$arch
Server = https://pkg.fef.moe/archlinux/$repo/os/$arch
Server = https://archlinux.thaller.ws/$repo/os/$arch
Server = https://md.mirrors.hacktegic.com/archlinux/$repo/os/$arch
Server = https://london.mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirror.sunred.org/archlinux/$repo/os/$arch
Server = https://ftp.sh.cvut.cz/arch/$repo/os/$arch
Server = https://arch.mirror.constant.com/$repo/os/$arch
Server = https://america.mirror.pkgbuild.com/$repo/os/$arch
Server = https://asia.mirror.pkgbuild.com/$repo/os/$arch
```
My pacman.conf has nothing special, just the standard repos and multilib (no testing). I also don't have any package set to IgnorePkg

**Comment by The-Compiler** [comment]
You seem to have the same version as I installed, but with different dependencies... that makes no sense at all. Maybe try `paccheck qt6-webengine` (part of `pacutils`) and if it complains, reinstall that package.

**Comment by rabaimorp** [comment]
$ paccheck qt6-webengine
qt6-webengine: all dependencies satisfied
qt6-webengine: all files match database

**Comment by The-Compiler** [comment]
I'm out of ideas then. Maybe try generating a new mirrorlist and then reinstalling the package.
