### ISSUE TITLE
Permission answers not saved?

### ISSUE THREAD

**Issue by rperce** [qutebrowser/qutebrowser#832]
Might just be user error, but it seems that on close, sites for which I've enabled desktop notifications (like slack or gmail) forget that they're allowed to make desktop notifications: when I open back up and reopen those sites, they ask for notification permissions again.

**Comment by The-Compiler** [comment]
This is a missing feature - this information currently isn't saved.

I plan to look at this after per-domain settings (#27) are implemented, as then it should be very easy.

**Comment by rperce** [comment]
Stellar! I'm in no hugh rush :+1: :)

**Comment by hicolour** [comment]
For some reason this issue was not so annoying and started to be around date when #4063 was raised, does anyone have idea abot any workaround?

**Comment by toofar** [comment]
There are various permission settings that take the values "true/false/ask". By default they are "ask". All of them support url patterns now so if you want to keep it at the default for all sites except a few which you want to allow or deny automatically you can do something like `:set -u https://some-trusted-site/* content.register_protocol_handler true`.

The options that support an "ask" value are:
```
content.desktop_capture
content.geolocation
content.media_capture
content.notifications
content.persistent_storage
content.register_protocol_handler
content.ssl_strict
```

**Comment by WorMzy** [comment]
Is it possible to handle per-site permissions in config.py, or do you have to use autoconfig.yml?

**Comment by The-Compiler** [comment]
@WorMzy See [the relevant docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc#per-domain-settings).

**Comment by WorMzy** [comment]
Perfect, thanks!

**Comment by mrpewpew** [comment]
Permission answers are still not saved for me (qutebrowser v1.7.0). The autoconfig.yml records my choices per site as intended but get overwritten everytime qb restarts so I have to answer to permission popups again

**Comment by The-Compiler** [comment]
@mrpewpew Maybe you have `auto_save.interval` set to something non-default?

**Comment by snuffop** [comment]
I had been plagued with this annoyance for a while too  Knowing it was a PEBKAC  but the Including of the autoconfig file.  and Saving before quit of the browser.. fixed the entire issue for me.

**Comment by Masacaai** [comment]
```
> qutebrowser --version

qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.4
yaml: 5.3.1
cssutils: no
attr: 20.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.0
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.3.2
Platform: Linux-5.10.6-arch1-1-x86_64-with-glibc2.32, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00

```

I'm still facing the same issue. I need to manually enable permissions for every site I visit.
I need to enable permissions for Microsoft Teams, Gmail, Reddit, etc.
I've setup config.py so that it loads settings from autoconfig.yml
And I've also configured qutebrowser to auto-reload previous session.

**Comment by The-Compiler** [comment]
@Masacaai What do you mean with "manually enable permissions" exactly? Do you get a dialog from qutebrowser asking for permission (despite answering always/never), or do you mean that you'll have to click something on the website again?

If it's the latter, see #5233.
