### ISSUE TITLE
Qutebrowser color issue

### ISSUE THREAD

**Issue by rendi12345678** [qutebrowser/qutebrowser#8320]
![screenshot-20241004-141005Z-all](https://github.com/user-attachments/assets/e679df71-d304-4db1-808e-f83872793128)
Help!!

**Comment by The-Compiler** [comment]
That's just how Chromium's dark mode renders the page (also, the questions in the issue template aren't there for just ignoring them all and posting zero context instead...).

**Comment by rendi12345678** [comment]
> That's just how Chromium's dark mode renders the page (also, the questions in the issue template aren't there for just ignoring them all and posting zero context instead...).
thanks for reviewed my issue, i am sorry i am not fulfilledthe template i was lazy :)
