### ISSUE TITLE
Some fonts display only "đ"

### ISSUE THREAD

**Issue by aksarkar** [qutebrowser/qutebrowser#8322]
**Version info**:
https://bpa.st/VMN7C

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

All characters on some websites are displayed as "đ", for example 
![this one](https://github.com/user-attachments/assets/c7f7095f-7459-4e48-8399-a43e663c6dd7)

**How to reproduce**
qutebrowser --temp-basedir https://scottaaronson.blog/

**Comment by The-Compiler** [comment]
This definitely is one of the more weird bug reports I've ever seen! :thinking: 

What does the `:devtools` show for you as rendered font for that text?

![image](https://github.com/user-attachments/assets/199678f4-c0ee-49b9-bcaf-d22f4fcb3f4f)

Can you reproduce if you run the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py) with that webpage? Have you tried in other browsers, especially Chromium?

**Comment by aksarkar** [comment]
Rendered font is Lucida Grande.

This appears to be some kind of problem with that specific font and something else in my OS setup, because if I remove it from the available fonts this bug goes away.
