### ISSUE TITLE
Video Codecs not working - except for webp

### ISSUE THREAD

**Issue by blucybrb14de** [qutebrowser/qutebrowser#8324]
Hello,

For some apparent reason, it would appear that my video codecs, besides youtube videos for qutebrowser are not currently working.

[inxi-output.log](https://github.com/user-attachments/files/17275805/inxi-output.log)

``` qutebrowser v3.2.1
Git commit: 0b0eb46b5-dirty on HEAD (2024-10-05 12:03:35 +1300)
Backend: QtWebEngine 6.7.3
  based on Chromium 118.0.5993.220
  with security patches up to 129.0.6668.58 (plus any distribution patches)
  (source: api)
Qt: 6.7.3

CPython: 3.12.6
PyQt: 6.7.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: 4.6.82 (/usr/share/pdf.js/build/pdf.mjs)
sqlite: 3.46.1
QtNetwork SSL: LibreSSL 3.9.2

Style: Qt6CTProxyStyle
Platform plugin: wayland
OpenGL: OpenGL ES
Platform: Linux-6.10.10-cachyos-6.10.10-Netrunner-Edition-x86_64-13th_Gen_Intel-R-_Core-TM-_i7-13800H-with-glibc2.40, 64bit
Linux distribution: Gentoo Linux (gentoo)
Frozen: False
Imported from /usr/lib/python3.12/site-packages/qutebrowser
Using Python from /usr/bin/python3.12
Qt library executable path: /usr/lib64/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /home/kyle/.cache/qutebrowser
config: /home/kyle/.config/qutebrowser
data: /home/kyle/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/kyle/.config/qutebrowser/config.py has been loaded
Uptime: 0:09:27
```

**Description**

When I attempt to watch videos on odysee, invidious, or other sites the media does not appear to load. Could be a distribution related issue, however my use flags should be correct ?

``` 
Linux-BattleStation# cat qutebrowser
www-client/qutebrowser widevine

# required by dev-python/PyQtWebEngine-5.15.6-r1::gentoo
# required by www-client/qutebrowser-3.1.0-r1::gentoo[-qt6,python_single_target_python3_12]
# required by @selected
# required by @world (argument)
>=dev-qt/qtwebengine-6.7.1 widgets geolocation bindist
# required by dev-python/PyQtWebEngine-5.15.6-r1::gentoo
# required by www-client/qutebrowser-3.1.0-r1::gentoo[python_single_target_python3_12,-qt6]
# required by qutebrowser (argument)
>=dev-python/PyQt5-5.15.10-r1 sql webchannel
# required by www-client/qutebrowser-3.2.0::gentoo[python_single_target_python3_12]
# required by @selected
# required by @world (argument)
>=dev-python/PyQt6-6.7.0 qml webchannel multimedia

## Media Codec support
dev-qt/qtmultimedia gstreamer

media-plugins/gst-plugins-meta vpx ffmpeg
media-video/ffmpeg libaom libv4l v4l fdk x265 openh264 dav1d vpx vl4 chromium

```

Does the bug happen if you start with --temp-basedir?:
Yes

**How to reproduce**

https://invidious.privacyredirect.com/watch?v=njX2bu-_Vw4 - does not load, with ```No compatible source found for this media.```

I tried testing with invidious, as well as a media codecs site, at: http://ott.dolby.com/codec_test/index.html,

 the following codecs seems to be working:
![media-codecs](https://github.com/user-attachments/assets/ef10e429-1534-470e-b77d-49bf99e7daad)

<br>

Please, let me know if I'm missing something, or if there's something I could do to remedy this, much appreciated.

**Comment by The-Compiler** [comment]
https://github.com/qutebrowser/qutebrowser/blob/main/doc/install.asciidoc#on-gentoo

> To be able to play videos with proprietary codecs with QtWebEngine, you will need to turn off the `bindist` flag for `dev-qt/qtwebengine`.

Also see [qutebrowser - Gentoo wiki](https://wiki.gentoo.org/wiki/Qutebrowser#Proprietary_Codecs)
