### ISSUE TITLE
qutebrowser with Chromium Embedded Framework (CEF)

### ISSUE THREAD

**Issue by pakwin9133** [qutebrowser/qutebrowser#8328]
Hi @The-Compiler , 

Thanks for creating qutebrowser which is great for vim lover like me. I usually use qutebrowser to open some vscode-based online IDE.  In general, it works very well. However, its performance in some cases, like scrolling in a code editor, may be as good as some other web browsers. I did some studies on that. It seems the root cause is more at the qtwebengine. I did some benchmarking by using speedometer 3.0.  qtwebengine is not performing as good as CEF. 

I also found that you had considered to support CEF with qutebrowser in some online discussion. Will you re-consider it again ??

**Comment by The-Compiler** [comment]
I'm afraid not. There were various reasons why it seemed like a poor fit (availability of public builds, integration with Qt, and I think somewhat outdated/incomplete Python wrappers).
