### ISSUE TITLE
Fix test_existing_dict spellcheck test on 6.8

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#8330]
**Version info**:
On the main branch, right now!

**Does the bug happen if you start with `--temp-basedir`?**:
N/A

**Description**

This test is failing on Qt6.8, currently in the "unstable" test suite via the arch kde-unstable repo: https://github.com/qutebrowser/qutebrowser/blob/4d2aa13db3e55e908ebd3951a499f337cb317d7e/tests/unit/browser/webengine/test_webenginesettings.py#L136

![image](https://github.com/user-attachments/assets/59349508-bd37-476c-895f-077c3fbfe526)

No-one is actively focusing on fixing this right now, so in an effort to keep the CI reports useful (ideally any red on the CI should be because of a change you made in your PR) I'll comment out the failing line and put this issue in the milestone for the next release. Hopefully that'll be a reminder for us to revisit it and decide what to do. (Maybe move it to an end2end test?)

It's failing because WebEngine added a new check before enabling spell checking that the detected dictionary directory exists. But the dictionary directory is searched once when WebEngine is first initialized and then cached in a static variable and there is no way for us to change it. Which makes it very difficult to use in unit tests. More rambling in this comment: https://github.com/qutebrowser/qutebrowser/issues/8242#issuecomment-2333609589

**How to reproduce**
Uncomment the live above and run multiple spell check test at once. On Qt6.8. Eg

    docker run -it -v $PWD:/work:ro -w /work -e QUTE_TESTS_BACKEND=webengine -e DISPLAY=:27 -v /tmp/.X11-unix:/tmp/.X11-unix -e TOX_WORK_DIR="/home/user/.tox" -e HYPOTHESIS_EXAMPLES_DIR="/home/user/.hypothesis/examples" -e VIRTUALENV_SYSTEM_SITE_PACKAGES=True qutebrowser/ci:archlinux-webengine-unstable-qt6 tox -e py -- tests/unit/browser/webengine/test_webenginesettings.py

**Comment by The-Compiler** [comment]
Somewhat related, looks like `tox -e py312 -- tests/end2end/features/test_editor_bdd.py -v  -x` also fails [on CI](https://github.com/qutebrowser/qutebrowser/actions/runs/12206003801/job/34054558088#step:6:104) (as well as locally with `tox -e py312 -- tests/end2end/features/test_editor_bdd.py -v -x`) due to:

```
22:20:49.320 INFO     destroy    app:qt_mainloop:126 SIGINT/SIGTERM received, shutting down!
22:20:49.320 INFO     destroy    app:qt_mainloop:126 Do the same again to forcefully quit.
22:20:49.320 DEBUG    destroy    quitter:shutdown:221 Shutting down with status 143, session None...
22:20:49.321 DEBUG    prompt     prompt:shutdown:121 Shutting down with loops []
22:20:49.321 DEBUG    destroy    quitter:shutdown:235 Deferring shutdown stage 2
22:20:49.321 DEBUG    destroy    quitter:_shutdown_2:241 Stage 2 of shutting down...
22:20:49.321 DEBUG    destroy    mainwindow:closeEvent:711 Wiping private data before closing last private window
22:20:49.323 DEBUG    config     webenginesettings:set_dictionary_language:349 Found dicts: []
IGNORED: The following paths were searched for Qt WebEngine dictionaries:
INVALID:   /tmp/qutebrowser-basedir-onb10edu/data/qtwebengine_dictionaries
INVALID: but could not find it.
INVALID: Spellchecking can not be enabled.
```

and I've seen that when running qutebrowser interactively too.

Seems to come from here:

```python
(Pdb) bt
  <frozen runpy>(198)_run_module_as_main()
  <frozen runpy>(88)_run_code()
  /home/florian/proj/qutebrowser/git/qutebrowser/__main__.py(15)<module>()
-> sys.exit(qutebrowser.qutebrowser.main())
  /home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py(232)main()
-> return app.run(args)
  /home/florian/proj/qutebrowser/git/qutebrowser/app.py(109)run()
-> init(args=args)
  /home/florian/proj/qutebrowser/git/qutebrowser/app.py(146)init()
-> _init_modules(args=args)
  /home/florian/proj/qutebrowser/git/qutebrowser/app.py(486)_init_modules()
-> websettings.init(args)
  /home/florian/proj/qutebrowser/git/qutebrowser/config/websettings.py(228)init()
-> webenginesettings.init()
  /home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginesettings.py(610)init()
-> _init_default_profile()
  /home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginesettings.py(458)_init_default_profile()
-> _init_profile(default_profile)
  /home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginesettings.py(393)_init_profile()
-> profile.setter.init_profile()  # type: ignore[attr-defined]
  /home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginesettings.py(287)init_profile()
-> self.set_dictionary_language()
> /home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginesettings.py(352)set_dictionary_language()->None
-> self._profile.setSpellCheckEnabled(bool(filenames))
```

Weirdly enough, it seems like Qt shouts at us even when *disabling* spell checking?!

```python
(Pdb) self._profile.setSpellCheckEnabled(False)
22:26:13 WARNING: The following paths were searched for Qt WebEngine dictionaries:
  /tmp/qutebrowser-basedir-ihwbg1c5/data/qtwebengine_dictionaries
but could not find it.
Spellchecking can not be enabled.
```

**Comment by The-Compiler** [comment]
We can always just avoid calling that if unneeded:

```diff
diff --git i/qutebrowser/browser/webengine/webenginesettings.py w/qutebrowser/browser/webengine/webenginesettings.py
index 39bd2d661..f85ccb051 100644
--- i/qutebrowser/browser/webengine/webenginesettings.py
+++ w/qutebrowser/browser/webengine/webenginesettings.py
@@ -348,7 +348,10 @@ class ProfileSetter:
 
         log.config.debug("Found dicts: {}".format(filenames))
         self._profile.setSpellCheckLanguages(filenames)
-        self._profile.setSpellCheckEnabled(bool(filenames))
+
+        should_enable = bool(filenames)
+        if should_enable and self._profile.isSpellCheckEnabled() != should_enable:
+            self._profile.setSpellCheckEnabled(should_enable)
 
     def disable_persistent_permissions_policy(self):
         """Disable webengine's permission persistence."""

```

but still seems weird, might warrant a Qt bug. Haven't looked into the tests issue from the OP yet.

**Comment by The-Compiler** [comment]
Qt issue for the logging: [[QTBUG-131969] "Spellchecking can not be enabled" error logged when disabling spell checking - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-131969), and warning avoided in 3cfefd121cbddc65c28bdf659acc2dc9b5b3ee40.


As for the original issue: The intention of the test was whether we are enabling/disabling spell checking properly based on the configured dictionaries - but nothing (including QtWebEngine) seems to enforce that they actually exist, it's only that QtWebEngine now started enforcing that a (possibly empty) dictionary directory exists.

I pushed db8e508530e8a198599dd7d98cbbc1f34de67bba which takes care of actually setting up such a directory for the tests, which seems to make things work just fine again.

**Comment by The-Compiler** [comment]
Ugh, I thought the static variable was only set when using `[is|set]SpellCheckEnabled()`, but apparently something during QWebEngineProfile initialization already does that earlier? Didn't catch that locally as I wasn't running the full testsuite, only the part I thought was relevant :see_no_evil:  Hopefully with 960d9aaaa5a496312095acf1e6cf35a0bf0573bb things are looking better now.

**Comment by The-Compiler** [comment]
Qt fix for the bogus error message:

- [Do not warn needlessly about missing dictionaries directory (612755) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/612755)

Cherry-pick to 6.9 still open and 6.8 still missing, so remains to be seen where exactly this will be fixed.
