### ISSUE TITLE
Prefer pdf-js legacy build

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#8332]
We use Mozilla's PDF.js for rendering PDFs in the browser. They have [two builds](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support), one targeted at the very latest browser versions, one wrapped in polyfills and meant to be more widely usable.

Recently they seemed to have upped the pace with which they adopt new browser features, and since QtWebEngine has more of a stable release model (feature releases every X months, backport security and bug fixes in the meantime) we occasionally run into issues where new PDF.js versions don't work with the latest QtWebEngine version and we have to add polyfills. It doesn't make much sense for us to be adding polyfillls when upstream is already doing it!

This issue involves:
1. Switch to pulling down the legacy PDF.js release in `scripts/dev/build_release.py`
2. Switch our CI pipelines that are installing PDF.js via `update_3rdparty.py` to use the legacy build - apart from the unstable ones
3. Recommend to packagers that they switch over to depending on the legacy build if possible

Questions:
1. how to recommend to packagers that they might want to switch over? Just update the install docs? Do we need to do any outreach?

Previous discussion:  https://github.com/qutebrowser/qutebrowser/pull/8321#discussion_r1791777520
Related open issues: https://github.com/qutebrowser/qutebrowser/issues/7335 and https://github.com/qutebrowser/qutebrowser/issues/7135

**Comment by The-Compiler** [comment]
Also see

- #7721
