### ISSUE TITLE
"Text not found on page" should not use WARN log level

### ISSUE THREAD

**Issue by pohzipohzi** [qutebrowser/qutebrowser#8338]
**Version info**:
```
qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.8
  based on Chromium 122.0.6261.171
  with security patches up to 129.0.6668.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.0
```

**Description**
When searching for text that does not exist, we get a warning log eg

```
09:27:57 WARNING: Text 'sd' not found on page!
09:27:57 WARNING: Text 'sdf' not found on page!
```

Since this is an expected behavior I feel the log level could have been INFO instead

**How to reproduce**
Do `/sdfjkl` on almost any page

**Comment by toofar** [comment]
I'm pretty sure these messages are intentionally at the warning level. The argument is that they are only expected if you intentionally type a search term that isn't on the page. Otherwise getting a search result is the expected behaviour. If that makes sense?

**Comment by pohzipohzi** [comment]
thanks for the reply :)

> The argument is that they are only expected if you intentionally type a search term that isn't on the page

I don't usually know if search terms exist when I'm searching for them, so I wouldn't view it as intentionally typing a search term that isn't on the page

in my experience, WARN is usually reserved for potential oddities (eg. file not found, falling back to xxx), which doesn't feel like the appropriate level for this "search term not found" message

**Comment by The-Compiler** [comment]
This was discussed at length in #8338 (where it was changed from error to warning), I don't think there's anything to gain by rehashing that discussion again for something so minor.
