### ISSUE TITLE
Cannot copy links to github comments ("Unhandled feature permission 8")

### ISSUE THREAD

**Issue by krobelus** [qutebrowser/qutebrowser#8349]
EDIT: Nevermind, it looks like this is because of a stale state file in my ~/.local/share/qutebrowser. Will delta-debug.

Unfortunately github seems to be requiring the `ClipboardReadWrite` permission which we don't have yet.

```
$ qutebrowser --temp-basedir https://github.com/qutebrowser/qutebrowser/issues/8346 # click the three dots and copy link
09:58:55 ERROR: Unhandled feature permission 8
```

Permission 8 is ClipboardReadWrite, which is added (along LocalFontsAccess) in unreleased pyqt6-webengine development sources.

```
%If (QtWebEngine_6_8_0 -)
        ClipboardReadWrite,
%End
```

I'm not yet sure how we want to implement this since `content.javascript.clipboard` works differently.

I'm using this workaround:

```diff
diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index 04ed7c409..82e383c22 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -950,6 +950,10 @@ class _WebEnginePermissions(QObject):
             deny_permission()
             return
 
+        if permission_str == "8":
+            grant_permission()
+            return
+
         if feature not in self._options:
             log.webview.error("Unhandled feature permission {}".format(
                 permission_str))
```

**Comment by krobelus** [comment]
Found it, somehow I had

```
$ cat ~/.local/share/qutebrowser/webengine/permissions.json
{"ClipboardReadWrite":{"https://github.com/":false}}⏎ 
```

No idea how it got here. Deleting it fixes the problem.

**Comment by toofar** [comment]
You're seeing a combination of:

* https://github.com/qutebrowser/qutebrowser/pull/8348, and
* https://github.com/qutebrowser/qutebrowser/issues/8297

Although I did forget about the new enum value.

I'm assuming you are on archlinux and :version shows you have QtWebEngine 6.8.0 but PyQt 6.7.x. Until the new PyQt releases then for users with those versions they won't see permissions prompts as often and our current clipboard permission setting will only work if you set it to `access-paste`.

**Comment by VuiMuich** [comment]
> You're seeing a combination of:
> 
> * [Disable WebEngine 6.8's permission grant persistence feature #8348](https://github.com/qutebrowser/qutebrowser/pull/8348), and
> * [Support "ask" options for `content.javascript.clipboard` (Qt 6.8) #8297](https://github.com/qutebrowser/qutebrowser/issues/8297)
> 
> Although I did forget about the new enum value.
> 
> I'm assuming you are on archlinux and :version shows you have QtWebEngine 6.8.0 but PyQt 6.7.x. Until the new PyQt releases then for users with those versions they won't see permissions prompts as often and our current clipboard permission setting will only work if you set it to `access-paste`.

So tl;dr change `content.javascript.clipboard = "access";` to `content.javascript.clipboard = "access-paste";` and it works again, right?

**Comment by The-Compiler** [comment]
Should be working fine with v3.4.0.
