### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by sainishwanth** [qutebrowser/qutebrowser#8350]
**Version info**:

https://bpa.st/P747A
**Does the bug happen if you start with `--temp-basedir`?**:
No
**Description**
#### Full Error Log
```sh
nobara :: ~ » qutebrowser
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==3.2.0', 'gui_scripts', 'qutebrowser')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/qutebrowser.py", line 232, in main
    return app.run(args)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/app.py", line 77, in run
    configinit.early_init(args)
  File "/usr/lib/python3.12/site-packages/qutebrowser/config/configinit.py", line 60, in early_init
    configfiles.read_autoconfig()
  File "/usr/lib/python3.12/site-packages/qutebrowser/config/configfiles.py", line 1007, in read_autoconfig
    config.instance.read_yaml()
  File "/usr/lib/python3.12/site-packages/qutebrowser/config/config.py", line 346, in read_yaml
    self._yaml.load()
  File "/usr/lib/python3.12/site-packages/qutebrowser/config/configfiles.py", line 355, in load
    migrations.migrate()
  File "/usr/lib/python3.12/site-packages/qutebrowser/config/configfiles.py", line 480, in migrate
    self._migrate_renamed_bool(
  File "/usr/lib/python3.12/site-packages/qutebrowser/config/configfiles.py", line 612, in _migrate_renamed_bool
    for scope, val in self._settings[old_name].items():
```

#### How it Occurred
It was running fine, last thing i did was try to install return-youtube-dislike plugin using greasemonkey with the following [guide](https://www.reddit.com/r/qutebrowser/comments/rlzet6/return_youtube_dislikes_again/)

I restarted the app for it to take effect but it wouldn't launch anymore, though I'm not entirely sure if the bug was caused by this. I tried to remove the script, clean re installed qutebrowser by wiping all the configs, etc but the issue persists.

I have tried to re-install via both my package manager (dnf) and pipx.

**How to reproduce**

* Open Qutebrowser

**Comment by sainishwanth** [comment]
Fixed it temporarily by encompassing the loop in a try-except (pass) block (in the file where the error occurs) 
/usr/lib/python3.12/site-packages/qutebrowser/config/configfiles.py
```py
def _migrate_renamed_bool(self, old_name: str,
                              new_name: str,
                              true_value: str,
                              false_value: str,
                              ask_value: str = None) -> None:
        if old_name not in self._settings:
            return

        self._settings[new_name] = {}
        try:
            for scope, val in self._settings[old_name].items():
                if val == 'ask':
                    assert ask_value is not None
                    new_value = ask_value
                elif val:
                    new_value = true_value
                else:
                    new_value = false_value
                self._settings[new_name][scope] = new_value
        except:
            pass
```

Not exactly sure what is the function doing tho, and not sure what is being affected, so some help to fix it properly would be appreciated.

**Comment by The-Compiler** [comment]
The error occurs when migrating the old `content.javascript.can_access_clipboard` setting in `autoconfig.yml` to the new `content.javascript.clipboard` setting.

Can you please show `~/.config/qutebrowser/autoconfig.yml`, especially that setting value? Though I'm not quite sure what happens by just ignoring the exception (it certainly isn't the right thing to do). It might be that the "evidence" is now already lost.

**Comment by The-Compiler** [comment]
The setting got renamed/changed in v3.0.0, so I'm assuming you were running v2.x before? I can reproduce by having

```yaml
config_version: 2
settings:
  content.javascript.can_access_clipboard: null
```

in `autoconfig.yml` - but the question isn't why the code is crashing (while some validation would be nice, it's not the actual culprit). The question is why a `null` value for this setting (not a valid value, and never was AFAIK) made it into your config file in the first place...

**Comment by sainishwanth** [comment]
Oh I'm sorry. That fixes the setting. I had an issue with copy to clipboard so followed [this](https://github.com/qutebrowser/qutebrowser/issues/8350) suggesstion, didn't realise it was deprecated.

Thanks a lot!
