### ISSUE TITLE
`content.javascript.clipboard` access no longer works in v3.3.1

### ISSUE THREAD

**Issue by stooj** [qutebrowser/qutebrowser#8356]
**Version info**:

```
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.8
  based on Chromium 122.0.6261.171
  with security patches up to 129.0.6668.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.0
```

**Does the bug happen if you start with `--temp-basedir`?**: no. (It's the default behavior, but should be configurable via config)

**Description**

Sites on my clipboard-access list no longer have access to the clipboard.

I have an option set in my config to allow GitHub js access to my clipboard:

```python
with config.pattern('*://github.com') as p:
    p.content.javascript.clipboard = 'access'
```

If I try to use js to copy something from GitHub.com, I get the following error:

```
14:17:34 DEBUG    js         shared:javascript_log_message:190 [https://github.com/qutebrowser/qutebrowser:0] Uncaught (in promise) NotAllowedError: Failed to execute 'writeText' on 'Clipboard': Write permission denied.
```

**How to reproduce**

1. Allow a website to access the clipboard using the config code above
2. Go to that website and try to use a javascript "copy-to-clipboard" function
3. Nothing is copied to the clipboard.

An easy thing to test on is the "copy github repo address" when you click on the "< > Code" button.

I've confirmed the configuration works with v3.2.1, but is broken in v3.3.1:

- Broken: https://bpa.st/5DV74
- Works: https://bpa.st/64QUK

Thanks for an amazing project :heart:

**Comment by The-Compiler** [comment]
The culprit here is Qt 6.7 vs. 6.8, not qutebrowser v3.2.1 vs. v3.3.1. See #8349 (which was closed when you opened this, but has some more context what's happening, so I reopened it).

Thanks for the detailed report and the nice words, much appreciated!
