### ISSUE TITLE
upload local file to server from form data

### ISSUE THREAD

**Issue by Roboxkin** [qutebrowser/qutebrowser#8360]
Hello!
Please add the ability to upload files via html tag <input type="file" />
Thank you!

**Comment by toofar** [comment]
Could you please provide an example of a site that isn't working for you? Uploading files in general works fine, for example via: https://litterbox.catbox.moe/

**Comment by Roboxkin** [comment]
> Could you please provide an example of a site that isn't working for you? Uploading files in general works fine, for example via: https://litterbox.catbox.moe/

Thank you very much for your answer!

I read the instructions, but as far as I understood, you can only manipulate files using js, but as far as I know, js cannot access local files.
Please! Write an example of code to send a local file to the server.
Thanks

```python
my_file = r"D:\1.png"
```
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Upload</title>
</head>
<body>
    <h1>Upload a File</h1>
    <form action="/upload" method="post" enctype="multipart/form-data">
        <label for="file">Choose a file:</label>
        <input type="file" id="file" name="file">
        <br><br>
        <input type="submit" value="Upload">
    </form>
</body>
</html>
```

**Comment by The-Compiler** [comment]
Your example seems to work fine in qutebrowser and opens a file upload dialog. What happens for you then?

**Comment by Roboxkin** [comment]
> Ваш пример отлично работает в qutebrowser и открывает диалог загрузки файлов. Что же тогда с тобой происходит?

Please share the commands you used to send the file.
Thanks

**Comment by The-Compiler** [comment]
It sounds like you think qutebrowser is a browser automation framework or something? Because... it just isn't.
