### ISSUE TITLE
Unknown error while getting elements (Youtube account switcher)

### ISSUE THREAD

**Issue by ayn2op** [qutebrowser/qutebrowser#8361]
**Version info**:
qutebrowser v3.3.1
Backend: QtWebEngine 6.7.3
  based on Chromium 118.0.5993.220
  with security patches up to 129.0.6668.58 (plus any distribution patches)
  (source: api)
Qt: 6.7.3 (compiled 6.7.1)

CPython: 3.12.7
PyQt: 6.7.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: 10.3.1
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: 4.7.76 (bundled)
sqlite: 3.46.1
QtNetwork SSL: OpenSSL 3.0.15 3 Sep 2024

Style: QMacStyle
Platform plugin: cocoa
OpenGL: Apple, 2.1 Metal - 89.3
Platform: macOS-15.1-arm64-arm-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/Frameworks/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/Frameworks/PyQt6/Qt6/libexec, data path: /Applications/qutebrowser.app/Contents/Frameworks/PyQt6/Qt6
OS Version: 15.1, arm64

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**: when `f` is pressed while the YouTube account selector modal is shown, qutebrowser is unable to find elements and displays "Unknown error while getting elements"

<img width="1280" alt="Screenshot 2024-10-29 at 12 23 01 PM" src="https://github.com/user-attachments/assets/2b6ef638-8b57-41b4-87be-55ad485f549d">

**Comment by The-Compiler** [comment]
Hmmm... I tried creating a channel with my old Google account to reproduce this, but with no success, all I get is this:

![image](https://github.com/user-attachments/assets/98e9dddd-a672-4ca7-a88f-ac5c283c350b)

How do you get to that switcher? Do you have two Youtube channels somehow associated with the same Google Account? But trying to create a new channel in my existing account claims to create a new Google account?!

![image](https://github.com/user-attachments/assets/146cd4b8-a2d8-4f46-a8ff-791b783bc4ef)

---

So I might not be able to reproduce this... What do you see in the `:devtools` console after the error shows up?

**Comment by ayn2op** [comment]
Try using incognito mode... I tried reproducing this behavior with Vimium on Chrome and Brave Browser, looks like Vimium does not detect the elements too. Furthermore, looks like YouTube uses custom elements to render the account switcher:

```html
<ytd-account-item-renderer class="style-scope ytd-account-item-section-renderer" thumbnail-size="40"><!--css-build:shady--><!--css-build:shady--><tp-yt-paper-icon-item class="style-scope ytd-account-item-renderer" style-target="host" role="option" tabindex="0" aria-disabled="false"><!--css-build:shady--><div id="contentIcon" class="content-icon style-scope tp-yt-paper-icon-item">
  <yt-img-shadow slot="item-icon" item-icon="" class="style-scope ytd-account-item-renderer no-transition" style="background-color: transparent;" loaded=""><!--css-build:shady--><!--css-build:shady--><img id="img" draggable="false" class="style-scope yt-img-shadow" alt="" height="40" width="40" src="https://yt3.ggpht.com/ytc/AIdro_l3nJvIvDJE5NT0ZX9d32J0hCL3tJDR1AdCbUx8qMFwIn1j60kCPuW6QfBFjZOjjh96Tw=s108-c-k-c0x00ffffff-no-rj"></yt-img-shadow>
</div>

  
  <tp-yt-paper-item-body two-line="" class="style-scope ytd-account-item-renderer"><!--css-build:shady-->
    <yt-formatted-string id="channel-title" class="style-scope ytd-account-item-renderer">CHANNEL 1</yt-formatted-string>
    <yt-formatted-string respect-lang-dir="" secondary="" class="style-scope ytd-account-item-renderer" is-empty="function(){var e=Ba.apply(0,arguments);a.loggingStatus.currentExternalCall=b;a.loggingStatus.bypassProxyController=!0;var g,k=((g=a.is)!=null?g:a.tagName).toLowerCase();My(k,b,&quot;PROPERTY_ACCESS_CALL_EXTERNAL&quot;);var m;g=(m=c!=null?c:d[b])==null?void 0:m.call.apply(m,[d].concat(la(e)));a.loggingStatus.currentExternalCall=void 0;a.loggingStatus.bypassProxyController=!1;return g}" dir="auto" style="text-align: left;"><!--css-build:shady--><!--css-build:shady--><yt-attributed-string class="style-scope yt-formatted-string"></yt-attributed-string></yt-formatted-string>
    <yt-formatted-string secondary="" class="style-scope ytd-account-item-renderer">No subscribers</yt-formatted-string>
  
</tp-yt-paper-item-body>
  <yt-icon id="selected" icon="yt-icons:check" class="style-scope ytd-account-item-renderer" hidden=""><!--css-build:shady--><!--css-build:shady--><span class="yt-icon-shape style-scope yt-icon yt-spec-icon-shape"><div style="width: 100%; height: 100%; display: block; fill: currentcolor;"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" focusable="false" aria-hidden="true" style="pointer-events: none; display: inherit; width: 100%; height: 100%;"><path d="m9 18.7-5.4-5.4.7-.7L9 17.3 20.6 5.6l.7.7L9 18.7z"></path></svg></div></span></yt-icon>
  <yt-icon id="studio-redirect" icon="yt-icons:open_in_new" class="style-scope ytd-account-item-renderer" aria-label="" hidden=""><!--css-build:shady--><!--css-build:shady--><span class="yt-icon-shape style-scope yt-icon yt-spec-icon-shape"><div style="width: 100%; height: 100%; display: block; fill: currentcolor;"><svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24" focusable="false" aria-hidden="true" style="pointer-events: none; display: inherit; width: 100%; height: 100%;"><path d="M21 21H3V3h9v1H4v16h16v-8h1v9zM15 3v1h4.32l-8.03 8.03.71.71 8-8V9h1V3h-6z"></path></svg></div></span></yt-icon>
  <tp-yt-paper-tooltip for="studio-redirect" position="left" class="style-scope ytd-account-item-renderer" role="tooltip" tabindex="-1" hidden=""><!--css-build:shady--><div id="tooltip" class="hidden style-scope tp-yt-paper-tooltip" style-target="tooltip">

</div>
</tp-yt-paper-tooltip>

</tp-yt-paper-icon-item>
</ytd-account-item-renderer>
```

Preview:

<img width="1280" alt="Screenshot 2024-10-29 at 5 26 26 PM" src="https://github.com/user-attachments/assets/9d177a57-9597-48ff-ba8d-5102124cac93">

**Comment by The-Compiler** [comment]
I'm mainly interested in the error output in the "Console" tab of the devtools.

**Comment by The-Compiler** [comment]
@ayn2op any updates?

**Comment by ayn2op** [comment]
> @ayn2op any updates?

So looks like it is working after I deleted the cache and reinstalled `qutebrowser`.
