### ISSUE TITLE
feat: vim like normal / visual mode in text forms

### ISSUE THREAD

**Issue by midirhee12** [qutebrowser/qutebrowser#8362]
It would be nice if you could use vim like movement from even within text forms.

**Comment by The-Compiler** [comment]
Duplicate of #827

**Comment by The-Compiler** [comment]
Also note that you can already spawn vim (or another editor of your choice) with ctrl-e too.

**Comment by midirhee12** [comment]
WOOPs. Sorry! My bad. I should have searched the issues more thoroughly
