### ISSUE TITLE
**`:fullscreen --leave`** does not work

### ISSUE THREAD

**Issue by poslat-pismo** [qutebrowser/qutebrowser#8372]
**Version info**:
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 5.15.18
  based on Chromium 87.0.4280.144
  (source: UA)
Qt: 5.15.15 (compiled 5.15.14)

CPython: 3.12.7
PyQt: 5.15.11

Qt wrapper: PyQt5 (via QUTE_QT_WRAPPER)

**Does the bug happen if you start with `--temp-basedir`?**:
YES

**Description**
**`:fullscreen --leave`** does not work, but **`:fullscreen --enter`** does work as expected

**Comment by The-Compiler** [comment]
As documented in `:help :fullscreen`, `--leave` leaves fullscreen mode when it's been entered by the page (e.g. fullscreening a video).
