### ISSUE TITLE
edit-text does not work with overleaf, no element focused

### ISSUE THREAD

**Issue by mostafatouny** [qutebrowser/qutebrowser#8375]
**Version info**:
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.8
  based on Chromium 122.0.6261.171
  with security patches up to 129.0.6668.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.0

**Does the bug happen if you start with `--temp-basedir`?**:
irrelevant.

**Description**
[edit-text](https://qutebrowser.org/doc/help/commands.html#edit-text) works perfectly with me, except on [overleaf](https://www.overleaf.com/) where I get error message: `No element focused!`. Overleaf is a killer application.
Also, in normal mode, if I click on a text input, mode is switched to insert. But in overleaf, it does not. So I think the problem is overleaf text editor is not recognized as an input field.

**How to reproduce**
launch any overleaf project, and in the text editor, use `edit-text` or `Ctrl-e` in insert mode.

**Comment by The-Compiler** [comment]
The editor gets recognized just fine for me (though `edit-text` doesn't recognize the text, but that's #2215).

I'm on the same version as you are, so... can you reproduce that too `--temp-basedir` or is the behavior different? Believe it or not, there's a reason the issue template asks for it.

**Comment by mostafatouny** [comment]
> The editor gets recognized just fine for me (though `edit-text` doesn't recognize the text, but that's #2215).
> 
> I'm on the same version as you are, so... can you reproduce that too `--temp-basedir` or is the behavior different? Believe it or not, there's a reason the issue template asks for it.

You are right. with `--temp-basedir` the text editor of overleaf is recognized and it immediately switches to insert mode. For edit-text in overleaf, I get: `Editor failed to start: `gvim` it does not exist or isn't executable`.

In #2215 I see ProtonMail is reported not to work. With text mode of email composition, my default choice, It works perfectly.

So is there any hope to run edit-text on overleaf?

**Comment by The-Compiler** [comment]
See #2215 for that.
