### ISSUE TITLE
auto_save.session = false NOT WORK

### ISSUE THREAD

**Issue by superiums** [qutebrowser/qutebrowser#8376]
**Version info**:
3.31
**Does the bug happen if you start with `--temp-basedir`?**:
No
**Description**
with `auto_save.session = false`,
the session was saved and reloaded while next startup,

but i would not to save it.
**How to reproduce**

**Comment by The-Compiler** [comment]
Not much I can say if your problem description is "NOT WORK"... Works just fine for me and countless others.

My best bet would be that you'er either not quitting qutebrowser properly (making it think it crashed), or you're quitting it in a way that tells it to explicitly save its session (e.g. `:wq`).

**Comment by superiums** [comment]
sorry for my poor knowledge and english.
yes, it is. it's because my shutdown command via wm let qutebrowser think it was crashed.
if quit with  `:q` then it works.

then the problem is : could qutebrowser understand the quit command sended by window manager ? and not think it as crashed ? this was possible, just like geany done.

**Comment by The-Compiler** [comment]
It does handle a normal quit via window close just fine. Either you or your WM does something strange. What's your WM and how exactly are you closing it?

**Comment by superiums** [comment]
Thank you very much.
yes, it is. it handles quit ok.
after a lot test, i found it works. the former problem may dues to my wm or sth else. i'm tringy to reproduce the problem, but failed.
