### ISSUE TITLE
404 Bad Request error if clicking duckduckgo url in same page

### ISSUE THREAD

**Issue by Aman1337g** [qutebrowser/qutebrowser#8383]
**Version info**:

https://bpa.st/BSPQ

**Does the bug occur when using `--temp-basedir`?**
No.

#### **Description**
When performing a search using the `:open` command in qutebrowser, the search results load correctly in DuckDuckGo. However, clicking on any link from the search results leads to a **404 Bad Request nginx** error. Notably, opening the same link in a new tab using **Shift+F** works as expected.

#### **Steps to Reproduce**
1. Perform a search in qutebrowser using the `:open` command (e.g., `:open configuring qutebrowser`).
2. Click on any link from the search results.
3. Observe the error: **404 Bad Request nginx**.
4. Alternatively, open the same link in a new tab using **Shift+F**, where it functions correctly.

**Comment by The-Compiler** [comment]
Works fine here. What link are you opening exactly, and what error do you see exactly? Can you show a screenshot? 404 is not "bad request", so I doubt that's what you're actually getting.

Given that it doesn't happen with `--temp-basedir`, it might be an issue with your config. Can you show your `:config-diff` please?

**Comment by Aman1337g** [comment]
Thank you for your reply. Here are the additional details you requested:

### Issue Recap:
1. **Behavior**:
   - **Performing any Search**: Using `:open {any query}` in DuckDuckGo works, and the search results load correctly.
   - **Clicking Links**: Clicking on any link in the search results leads to a **404 Bad Request (nginx)** error.
   - **Opening in New Tab**: Opening the same link in a new tab using `Shift+F` works as expected.

2. **Observations**:
   - The issue **does not occur** when running `qutebrowser` with `--temp-basedir`.

---

### Requested Information:

1.  **Exact Error Screenshot**:

![image](https://github.com/user-attachments/assets/9152af69-a481-43a7-82fd-c157ed5f50d3)

It does not match a typical HTTP `Bad Request` error message but instead seems related to a miscommunication during link navigation.

2. **Configuration Diff**:
   Here is my configuration diff output from `:config-diff`:
```
bindings.commands = {"caret": {"<Space>": null}, "command": {"<Ctrl+j>": "completion-item-focus next", "<Ctrl+k>": "completion-item-focus prev"}, "normal": {"<Alt+d>": "tab-clone", "<Alt+t>": "config-cycle colors.webpage.darkmode.enabled false true", "<Ctrl+Shift+f>": "fullscreen", "<Space>d": "print --pdf ~/Desktop/{title}.pdf", "<Space>jd": ":set content.javascript.enabled false", "<Space>je": ":set content.javascript.enabled true", "<Space>p": "hint links spawn mpv --fs {hint-url}", "<Space>rr": "reload", "<Space>sd": "cmd-set-text -s :session-delete", "<Space>sl": "cmd-set-text -s :session-load", "<Space>ss": "cmd-set-text -s :session-save", "au": "adblock-update", "ce": "config-edit", "cs": "config-source", "gC": null, "r": null, "se": "jseval (function () {   var i, elements = document.querySelectorAll(\"body *\");  for (i = 0; i < elements.length; i++) {    var pos = getComputedStyle(elements[i]).position;    if (pos === \"fixed\" || pos == \"sticky\") {      elements[i].parentNode.removeChild(elements[i]);    }  }})();", "user-stylesheet": "~/.config/qutebrowser/custom.css", "xb": "config-cycle statusbar.show always never", "xt": "config-cycle tabs.show always never", "xx": "config-cycle statusbar.show always never;; config-cycle tabs.show always never", "z": "open https://www.youtube.com/"}}
colors.webpage.darkmode.enabled = true
content.blocking.method = both
content.cookies.accept = no-3rdparty
content.geolocation = false
content.headers.do_not_track = true
content.headers.referer = same-domain
content.headers.user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36
content.javascript.clipboard = access-paste
content.javascript.enabled = false
https://duckduckgo.com/: content.javascript.enabled = true
https://www.youtube.com/: content.javascript.enabled = true
https://github.com/*: content.javascript.enabled = true
https://www.skool.com/*: content.javascript.enabled = true
https://www.geeksforgeeks.org/*: content.javascript.enabled = true
http://localhost:*: content.javascript.enabled = true
content.media.audio_capture = false
content.media.audio_video_capture = false
content.pdfjs = true
content.tls.certificate_errors = ask-block-thirdparty
content.user_stylesheets = ~/.config/qutebrowser/custom.css
content.webgl = false
content.webrtc_ip_handling_policy = disable-non-proxied-udp
editor.command = ["kitty", "--class", "nvim-editor", "/opt/nvim-linux64/bin/nvim", "{}"]
fonts.default_family = JetBrainsMono Nerd Font
fonts.default_size = 10pt
fonts.tabs.selected = 10pt JetBrainsMono Nerd Font
fonts.tabs.unselected = 10pt JetBrainsMono Nerd Font
fonts.web.family.fixed = JetBrainsMono Nerd Font
fonts.web.family.sans_serif = JetBrainsMono Nerd Font
fonts.web.family.serif = JetBrainsMono Nerd Font
fonts.web.family.standard = JetBrainsMono Nerd Font
fonts.web.size.default = 16
fonts.web.size.default_fixed = 14
qt.workarounds.disable_hangouts_extension = true
statusbar.show = never
statusbar.widgets = ["keypress", "search_match", "url", "scroll", "history", "tabs", "progress"]
tabs.show = never
window.hide_decoration = true
 ```
---

Please let me know if there’s anything else I can provide to help debug this further. I appreciate your support and time!

**Comment by The-Compiler** [comment]
Try unsetting `content.headers.user_agent` - why would you set it to something like this globally in the first place?

**Comment by Aman1337g** [comment]
Thank you for the suggestion! Unsetting `content.headers.user_agent` resolved the issue, and links from DuckDuckGo search results are now opening correctly.

Thank you for the clarification! The reason I set the user agent like that was to reduce the amount of information sites could gather about my browser, aiming to minimize my online footprint. I was experimenting with ways to improve privacy and emulate something akin to Brave browser's approach, where fingerprinting results on tools like [Cover Your Tracks](https://coveryourtracks.eff.org) show a "randomized fingerprint."

![image](https://github.com/user-attachments/assets/96f1463c-7864-482a-a6f7-8763cb74d668)

Do you have any insights or tips on how to achieve this level of fingerprint randomization in qutebrowser? Or perhaps tricks to effectively minimize the browser's fingerprint while maintaining functionality? I’d love to know if there’s a way to incorporate this feature or if there are other strategies you’d recommend.   :sweat_smile:

**Comment by The-Compiler** [comment]
As you have just observed, such a setting makes you *more* fingerprintable if anything, as there will be very few browsers that claim to be Safari but don't act like it.

Unless you're constantly using a VPN or something, the whole point is moot anyways, as your IP probably makes for a nice fingerprint.
