### ISSUE TITLE
USB camera is not available in Zoom with QT6.8

### ISSUE THREAD

**Issue by DenisSperansky** [qutebrowser/qutebrowser#8386]
I saw that full support of qt6.8 is coming in 3.4 but still decided to create this ticket. Feel free to close it if the issue is known.

**Version info**:
```
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.8
  based on Chromium 122.0.6261.171
  with security patches up to 129.0.6668.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.0

CPython: 3.12.7
PyQt: 6.8.0.dev2410211537

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: 4.8.69 (/usr/share/pdf.js/build/pdf.mjs)
sqlite: 3.46.1
QtNetwork SSL: OpenSSL 3.4.0 22 Oct 2024
```

**Does the bug happen if you start with `--temp-basedir`?**:
TBA

**Description**
In zoom call there is no USB camera in video settings/video menu. If I downgrade all qt6 related packages to 7.3.0 the camera appears everywhere as it always was.

**How to reproduce**
Launch zoom meeting, open video settings, observe only internal laptop camera and USB one is missing.

**Comment by The-Compiler** [comment]
> I saw that full support of qt6.8 is coming in 3.4 but still decided to create this ticket.

This doesn't seem to be related to Qt 6.8, I can reproduce with older versions too.

> **Does the bug happen if you start with `--temp-basedir`?**:
> TBA

For what it's worth, while I could thankfully reproduce this easily, just ignoring parts of an issue template is quite frustrating for the person you're asking to spend time on investigating your issue...

Reported upstream: [[QTBUG-131326] Zoom does not detect multiple webcams - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-131326)

**Comment by DenisSperansky** [comment]
> just ignoring parts of an issue template is quite frustrating for the person you're asking to spend time on investigating your issue...

Sorry, I wanted to add it when I'm back at my desk where I can test it.
