### ISSUE TITLE
Hints border is missing the colors prefix

### ISSUE THREAD

**Issue by lrustand** [qutebrowser/qutebrowser#8393]
All settings related to colors of UI elements share the same prefix `color.*`, but `hints.border` does not. I feel like this is some sort of oversight that has happened during a reorganization of settings or something like that? This makes it easy to miss the setting, since all the other color settings are grouped together and clearly marked as being color settings, but this one is hidden away from the others.

**Comment by The-Compiler** [comment]
The setting sets the whole border CSS property (including width and stroke), so it's not just purely a color.

**Comment by lrustand** [comment]
Then could you please consider splitting it up and moving the color part of it to the others? Or at least make an alias or something? I'm making an emacs package to sync the qutebrowser theme with the emacs theme, and since all the options share a prefix I can write it only once inside a loop instead of almost 100 times, but because of this one single setting I will have to write the whole prefix for every single one of them.

**Comment by The-Compiler** [comment]
I don't think this is worth the churn for everyone else just to make your script easier. Surely you'll find a way to run a for loop and then run a single thing after that.

**Comment by lrustand** [comment]
I'm not saying that at all, I just tried to give you one example why the current way it is is bad. I would obviously not demand that things would be changed solely for my use case. But the way it is grouped now is objectively bad, since ALL color settings are in one place, except not this one. This makes it hard for ANYONE that wants to customize their color scheme.
