### ISSUE TITLE
Renderer process crashed (status -2147483645)

### ISSUE THREAD

**Issue by PLGGitHub1** [qutebrowser/qutebrowser#8394]
**Version info**:
https://bpa.st/B7RQ
**Does the bug happen if you start with `--temp-basedir`?**:
No
**Description**
This is the most annoying error I've seen.
**How to reproduce**
1. Go to a website
2. Do something or wait

**Comment by The-Compiler** [comment]
Nothing I can do with so little information, and an error description of "This is the most annoying error I've seen." doesn't exactly motivate me to dig deeper either. Renderer processes are from the underlying QtWebEngine library, so there isn't much qutebrowser can do, this is probably something on your system.
