### ISSUE TITLE
Jira is not working properrly

### ISSUE THREAD

**Issue by sasugo** [qutebrowser/qutebrowser#8399]
**Version info**:
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

I'm trying to work with Jira in qutebrowser, but there's a problem running some scripts
![image](https://github.com/user-attachments/assets/b0ba68d8-9cd2-482d-a9ec-503a210da6a8)

And I'm getting this in the console 
```
jira-frontend-bifros…-spa.21804dc9.js:56 Uncaught SyntaxError: Unexpected token '{'
```

**How to reproduce**
Just go to Jira and go to a scrum board

**Comment by The-Compiler** [comment]
Your qutebrowser/Qt versions are too old for the JS being used there. Notably, Chromium 87 is from early 2021. You'll need to upgrade to something more recent.

**Comment by sasugo** [comment]
Thank you for taking the time to answer, I'll update my Chromium.
