### ISSUE TITLE
[RFE] allow to pass URL to external editor

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#8402]
`edit-text` that launches external editor for the focused text field is a great feature.

Lately though, I've been finding myself more and more often in situations, where I need to edit text on sites with different markup support *(Github — Markdown, Redmine — Textile, Bitrix — BBCode)*. At some point I decided to just use Markdown and convert upon saving to whatever underlying representation is *(by Pandoc or other means)*. There's a problem though: due to Qutebrowser lacking a way to provide editor with URL information, I can't make editor autoconvert Markdown to the necessary representation. So I have to do that manually.

### Suggestions

`c.editor.command` already provides a `{}` to pass the filename. We can either:

1. Encode the domain name in the filename.
2. Add another variable, say `{url}` that would get replaced with domain name.

**Comment by The-Compiler** [comment]
See #2727, which seems like a simpler and more general-purpose solution to the same problem.

**Comment by Hi-Angel** [comment]
> See #2727, which seems like a simpler and more general-purpose solution to the same problem.

I am confused: the issue you referenced is about filename extension, but isn't it supposed to be global and not per site?

**Comment by Hi-Angel** [comment]
Oh, okay, I guess I didn't realize what the description implies.

I've seen this issue *(from the search)* before creating my own, but due to the issue description being written as if it continues some other dialog, I got confused and just dismissed it. And the title alone mentions nothing about being "per-domain".

I think it might be useful to at least add the word "per-domain" to the title.

Thank you!
