### ISSUE TITLE
GCC-11 Not Found

### ISSUE THREAD

**Issue by krionical** [qutebrowser/qutebrowser#8410]
In trying to build qutebrowser, I get the following error:

gcc-11 -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/user/Software/qutebrowser/.venv/include -I/home/linuxbrew/.linuxbrew/opt/python@3.13/include/python3.13 -c sip_array.c -o build/temp.linux-x86_64-cpython-313/sip_array.o
      error: command 'gcc-11' failed: No such file or directory

This is true, since I'm using gcc-13. Is there a workaround?

**Comment by krionical** [comment]
Well, it was from the script: python3 scripts/mkvenv.py --pyqt-version auto

Sourced from here: https://qutebrowser.org/doc/install.html#tox

**Comment by The-Compiler** [comment]
That normally shouldn't need to build anything from source. Can you show the full command you've run and the full output?

**Comment by krionical** [comment]
```
 python3 scripts/mkvenv.py

==================== Creating virtual environment ====================
$ python3 -m venv .venv

==================== Upgrading initial packages ====================
venv$ pip install -U pip
Requirement already satisfied: pip in ./.venv/lib/python3.13/site-packages (24.3.1)
venv$ pip install -U setuptools wheel
Collecting setuptools
  Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting wheel
  Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-75.6.0 wheel-0.45.1

==================== Installing PyQt from binary ====================
No proprietary codec support will be available in qutebrowser.
venv$ pip install -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt --only-binary PyQt5,PyQtWebEngine,PyQt6,PyQt6-WebEngine
Collecting PyQt6==6.7.1 (from -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt (line 3))
  Using cached PyQt6-6.7.1-1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Collecting PyQt6-Qt6==6.7.3 (from -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt (line 4))
  Using cached PyQt6_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl.metadata (534 bytes)
Collecting PyQt6-WebEngine==6.7.0 (from -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt (line 5))
  Using cached PyQt6_WebEngine-6.7.0-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (1.8 kB)
Collecting PyQt6-WebEngine-Qt6==6.7.3 (from -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt (line 6))
  Using cached PyQt6_WebEngine_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl.metadata (627 bytes)
Collecting PyQt6-WebEngineSubwheel-Qt6==6.7.3 (from -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt (line 7))
  Using cached PyQt6_WebEngineSubwheel_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl.metadata (582 bytes)
Collecting PyQt6_sip==13.8.0 (from -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt (line 8))
  Using cached PyQt6_sip-13.8.0.tar.gz (92 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Using cached PyQt6-6.7.1-1-cp38-abi3-manylinux_2_28_x86_64.whl (8.2 MB)
Using cached PyQt6_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl (74.4 MB)
Using cached PyQt6_WebEngine-6.7.0-cp38-abi3-manylinux_2_28_x86_64.whl (268 kB)
Using cached PyQt6_WebEngine_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl (26.1 MB)
Using cached PyQt6_WebEngineSubwheel_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl (76.1 MB)
Building wheels for collected packages: PyQt6_sip
  Building wheel for PyQt6_sip (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for PyQt6_sip (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'PyQt6.sip' extension
      creating build/temp.linux-x86_64-cpython-313
      gcc-11 -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/home/Software/qutebrowser/.venv/include -I/home/linuxbrew/.linuxbrew/opt/python@3.13/include/python3.13 -c sip_array.c -o build/temp.linux-x86_64-cpython-313/sip_array.o
      error: command 'gcc-11' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyQt6_sip
Failed to build PyQt6_sip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (PyQt6_sip)
Subprocess failed, exiting
```

This is now a moot issue as I installed the flatpak as I noticed it was available. However, it might be a problem for someone else down the line.

**Comment by The-Compiler** [comment]
Flatpak gives you a heavily outdated version of both qutebrowser and QtWebEngine (based on a Chromium from early 2021 or so). Lots of things will break, and you'll miss out on tons of security fixes.

I don't understand why pip is trying to build things from source for you. It evidently picks `PyQt6_WebEngine_Qt6-6.7.3-py3-none-manylinux_2_28_x86_64.whl` but apparently not one of the [available PyQt6-sip wheels](https://pypi.org/project/PyQt6-sip/#files) (e.g. `
PyQt6_sip-13.9.0-cp313-cp313-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`).

What OS/system is this on, and what Python version are you using? The only explanation that would make sense is that you're maybe on an EOL Python (3.8 or older)?

**Comment by krionical** [comment]
Yeah, I've used qutebrowser in the past and got hung up as updates made the version I had antiquated. I'm using MX but uname -a puts it this way: 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux

python version shows 
 
python3 --version
Python 3.13.1

**Comment by The-Compiler** [comment]
What does `/home/Software/qutebrowser/.venv/bin/pip --version` say?

And what happens if you run this? `/home/Software/qutebrowser/.venv/bin/pip install -r /home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt --only-binary PyQt5,PyQtWebEngine,PyQt6,PyQt6-WebEngine,PyQt6_sip`

**Comment by krionical** [comment]
It says: 

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/Software/qutebrowser/misc/requirements/requirements-pyqt-6.txt'`

Checking that directory it's statement is correct:

```

README.md                            requirements-pyqt-6.4.txt-raw
requirements-check-manifest.txt      requirements-pyqt-6.5.txt
requirements-check-manifest.txt-raw  requirements-pyqt-6.5.txt-raw
requirements-dev.txt                 requirements-pyqt-6.6.txt
requirements-dev.txt-raw             requirements-pyqt-6.6.txt-raw
requirements-docs.txt                requirements-pyqt-6.7.txt
requirements-docs.txt-raw            requirements-pyqt-6.7.txt-raw
requirements-flake8.txt              requirements-pyqt-6.txt
requirements-flake8.txt-raw          requirements-pyqt-6.txt-raw
requirements-mypy.txt                requirements-pyqt.txt
requirements-mypy.txt-raw            requirements-pyqt.txt-raw
requirements-pyinstaller.txt         requirements-pyroma.txt
requirements-pyinstaller.txt-raw     requirements-pyroma.txt-raw
requirements-pylint.txt              requirements-qutebrowser.txt-raw
requirements-pylint.txt-raw          requirements-sphinx.txt
requirements-pyqt-5.15.2.txt         requirements-sphinx.txt-raw
requirements-pyqt-5.15.2.txt-raw     requirements-tests-bleeding.txt
requirements-pyqt-5.15.txt           requirements-tests.txt
requirements-pyqt-5.15.txt-raw       requirements-tests.txt-raw
requirements-pyqt-5.txt              requirements-tox.txt
requirements-pyqt-5.txt-raw          requirements-tox.txt-raw
requirements-pyqt-6.2.txt            requirements-vulture.txt
requirements-pyqt-6.2.txt-raw        requirements-vulture.txt-raw
requirements-pyqt-6.3.txt            requirements-yamllint.txt
requirements-pyqt-6.3.txt-raw        requirements-yamllint.txt-raw
requirements-pyqt-6.4.txt
```

**Comment by The-Compiler** [comment]
Ah, finally reproduced now with a `python3.13 -m venv .venv-test3 && .venv-test3/bin/pip install --no-cache --only-binary PyQt6_sip PyQt6_sip==13.8.0`.

We're pinning to 13.8.0 currently (13.9.0 came out last Friday), which doesn't have a wheel for Python 3.13, and thus then indeed builds things from source - but since I already had a .whl binary cached, I couldn't see that without also adding `--no-cache`.

A new dependency upgrade will run in a few hours, so this should be fixed tomorrow or so once that's merged. As a workaround, you should be able to edit `misc/requirements/requirements-pyqt-6.txt` locally to require `PyQt6_sip==13.9.0` in the meantime.

**Comment by krionical** [comment]
Hey, that did it! Nifty adblock updates! Things have changed some since last I ran this browser. Thanks for sticking with me through the troubleshooting!

**Comment by The-Compiler** [comment]
#8413 is now in, so you should be able to:

- Run `git status` / `git diff` to make sure you have no changes other than the version adjustment
- `git reset --hard HEAD` to reset all your local changes
- `git pull` to update
