### ISSUE TITLE
Custom math font

### ISSUE THREAD

**Issue by gracen-writes-code** [qutebrowser/qutebrowser#8411]
I've been using qutebrowser for a few weeks now, and I'm overally incredibly pleased with the configurability offered. However, I have noticed that there's no option to set the math font (i.e. the font defaulted to by `font-family: math`) to anything other than Latin Modern Math. I'd greatly appreciate it if a configuration field (`fonts.web.family.math`) could be added to configure this. Thanks!

**Comment by The-Compiler** [comment]
This isn't exposed by QtWebEngine. I opened [[QTBUG-131975] Add MathFont to QWebEngineSettings::FontFamily - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-131975) - once it's added (maybe for Qt 6.9?) it should make it into the "Interesting changes in Qt 6.X" issues, e.g. #8355. Until then, nothing qutebrowser can do unfortunately.

**Comment by gracen-writes-code** [comment]
Ah, that's unfortunate. Thanks for taking the time to file that issue, though!

**Comment by The-Compiler** [comment]
[Add MathFont to QWebEngineSettings::FontFamily (617462) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/617462)

Unfortunately the Qt 6.9 feature freeze passed already, so (assuming it's merged at some point in the next months), uthis will probably be in Qt 6.10, which I'd expect some time around September/October.
