### ISSUE TITLE
Crash on Instagram with Windows

### ISSUE THREAD

**Issue by ProxyPlay** [qutebrowser/qutebrowser#8412]
**Version info**:

qutebrowser v3.3.1
Backend: QtWebEngine 6.7.3
  based on Chromium 118.0.5993.220
  with security patches up to 129.0.6668.58 (plus any distribution patches)
  (source: api)
Qt: 6.7.3 (compiled 6.7.1)

CPython: 3.12.7
PyQt: 6.7.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: 4.7.76 (bundled)
sqlite: 3.46.1
QtNetwork SSL: OpenSSL 3.0.5 5 Jul 2022

Style: QWindows11Style
Platform plugin: windows
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 566.14
Platform: Windows-11-10.0.26100-SP0, 64bit
Frozen: True
Imported from C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\qutebrowser
Using Python from C:\Users\PC\AppData\Local\Programs\qutebrowser\qutebrowser.exe
Qt library executable path: C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\PyQt6\Qt6\bin, data path: C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\PyQt6\Qt6
OS Version: 11, 10.0.26100, SP0, Multiprocessor Free

Paths:
cache: C:\Users\PC\AppData\Local\qutebrowser\cache
config: C:\Users\PC\AppData\Roaming\qutebrowser\config
data: C:\Users\PC\AppData\Roaming\qutebrowser\data
runtime: C:\Users\PC\AppData\Local\Temp\qutebrowser

Autoconfig loaded: no
Config.py: C:\Users\PC\AppData\Roaming\qutebrowser\config\config.py has been loaded
Uptime: 0:00:46

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
When open Instagram and reload page, or change tabs, qutebrowser crushing.
**How to reproduce**

instagram.com

Log:
==== Fault log ====
Windows fatal exception: access violation

Current thread 0x00001ec0 (most recent call first):
  File "qutebrowser\app.py", line 125 in qt_mainloop
  File "qutebrowser\app.py", line 115 in run
  File "qutebrowser\qutebrowser.py", line 232 in main
  File "qutebrowser\__main__.py", line 15 in <module>

==== Timestamps ====
Launch: Mon Dec  9 00:58:16 2024
Crash: Mon Dec  9 00:58:19 2024

==== Version info ====
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v3.3.1
Backend: QtWebEngine 6.7.3
  based on Chromium 118.0.5993.220
  with security patches up to 129.0.6668.58 (plus any distribution patches)
  (source: api)
Qt: 6.7.3 (compiled 6.7.1)

CPython: 3.12.7
PyQt: 6.7.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: 4.7.76 (bundled)
sqlite: 3.46.1
QtNetwork SSL: OpenSSL 3.0.5 5 Jul 2022

Style: QWindows11Style
Platform plugin: windows
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 566.14
Platform: Windows-11-10.0.26100-SP0, 64bit
Frozen: True
Imported from C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\qutebrowser
Using Python from C:\Users\PC\AppData\Local\Programs\qutebrowser\qutebrowser.exe
Qt library executable path: C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\PyQt6\Qt6\bin, data path: C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\PyQt6\Qt6
OS Version: 11, 10.0.26100, SP0, Multiprocessor Free

Paths:
cache: C:\Users\PC\AppData\Local\qutebrowser\cache
config: C:\Users\PC\AppData\Roaming\qutebrowser\config
data: C:\Users\PC\AppData\Roaming\qutebrowser\data
runtime: C:\Users\PC\AppData\Local\Temp\qutebrowser

Autoconfig loaded: no
Config.py: C:\Users\PC\AppData\Roaming\qutebrowser\config\config.py has been loaded
Uptime: 0:00:02

==== Config ====
bindings.commands = {"normal": {",m": "spawn mpv {url}", "D": "set downloads.location.prompt true ;;  hint images download ;; set downloads.location.prompt false"}}
colors.webpage.darkmode.enabled = true
content.autoplay = false
content.persistent_storage = true
downloads.location.directory = C:\Users\PC\Downloads
downloads.location.prompt = false
downloads.location.suggestion = filename

==== Environment ====
PATH = C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\PyQt6\Qt6\bin;C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Users\PC\AppData\Local\Programs\Python\Python313\Scripts\;C:\Users\PC\AppData\Local\Programs\Python\Python313\;C:\Users\PC\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\PC\AppData\Local\Programs\Python\Python310\;C:\Users\PC\AppData\Local\Microsoft\WindowsApps;C:\Users\PC\AppData\Local\Microsoft\WinGet\Links;C:\Program Files\mpv-x86_64-20241103-git-42ff6f9;;C:\Users\PC\AppData\Roaming\Programs\Zero Install
QTWEBENGINE_DICTIONARIES_PATH = C:\Users\PC\AppData\Roaming\qutebrowser\data\qtwebengine_dictionaries
QT_PLUGIN_PATH = C:\Users\PC\AppData\Local\Programs\qutebrowser\_internal\PyQt6\Qt6\plugins

**Comment by The-Compiler** [comment]
Looks like this happened in QtWebEngine, there's unfortunately not much qutebrowser can do about that. I also cannot reproduce, works just fine for me.

I'd suggest waiting for PyQt 6.8 / qutebrowser v3.4.0 which should be released hopefully this week, and hoping that that will fix things.

You did actually try with `--temp-basedir` I assume? Because the output above looks like without that.

**Comment by ProxyPlay** [comment]
> Looks like this happened in QtWebEngine, there's unfortunately not much qutebrowser can do about that. I also cannot reproduce, works just fine for me.
> 
> I'd suggest waiting for PyQt 6.8 / qutebrowser v3.4.0 which should be released hopefully this week, and hoping that that will fix things.
> 
> You did actually try with `--temp-basedir` I assume? Because the output above looks like without that.

Hi, I don't know how to save the crash log when I run Instagram in qutebrowser with --temp-basedir, but the result is the same, my browser just crashes.

**Comment by The-Compiler** [comment]
qutebrowser v3.4.0 with Qt 6.8 is now out, can you please retry with that?

**Comment by ProxyPlay** [comment]
> qutebrowser v3.4.0 with Qt 6.8 is now out, can you please retry with that?

Same issue when scroll feed have this error in log:

==== Fault log ====
Windows fatal exception: access violation

Current thread 0x0000795c (most recent call first):
  File "qutebrowser\app.py", line 126 in qt_mainloop
  File "qutebrowser\app.py", line 116 in run
  File "qutebrowser\qutebrowser.py", line 232 in main
  File "qutebrowser\__main__.py", line 15 in <module>

If I update the feed, then I have this:

==== Fault log ====
Windows fatal exception: access violation

Current thread 0x0000795c (most recent call first):
  File "qutebrowser\app.py", line 126 in qt_mainloop
  File "qutebrowser\app.py", line 116 in run
  File "qutebrowser\qutebrowser.py", line 232 in main
  File "qutebrowser\__main__.py", line 15 in <module>

**Comment by ProxyPlay** [comment]
> qutebrowser v3.4.0 with Qt 6.8 is now out, can you please retry with that?

Same issue when scroll feed have this error in log:

==== Fault log ====
Windows fatal exception: access violation

Current thread 0x0000795c (most recent call first):
  File "qutebrowser\app.py", line 126 in qt_mainloop
  File "qutebrowser\app.py", line 116 in run
  File "qutebrowser\qutebrowser.py", line 232 in main
  File "qutebrowser\__main__.py", line 15 in <module>

If I update the feed, then I have this:

==== Fault log ====
Windows fatal exception: access violation

Current thread 0x0000795c (most recent call first):
  File "qutebrowser\app.py", line 126 in qt_mainloop
  File "qutebrowser\app.py", line 116 in run
  File "qutebrowser\qutebrowser.py", line 232 in main
  File "qutebrowser\__main__.py", line 15 in <module>
