### ISSUE TITLE
[BUG] Notification sounds not playing

### ISSUE THREAD

**Issue by pinarruiz** [qutebrowser/qutebrowser#8415]
**Version info**:
```
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.8
  based on Chromium 122.0.6261.171
  with security patches up to 129.0.6668.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.0

CPython: 3.12.7
PyQt: 6.8.0.dev2410141303

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.8.6
pdf.js: 4.2.67 (/nix/store/0zyi17008m7aj74w6lr1skachnqjyzrx-source/build/pdf.mjs)
sqlite: 3.46.1
QtNetwork SSL: OpenSSL 3.3.2 3 Sep 2024

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 24.2.6
Platform: Linux-6.6.63-x86_64-with-glibc2.40, 64bit
Linux distribution: NixOS 24.11 (Vicuna) (nixos)
Frozen: False
Imported from /nix/store/bn6nspkvw5ibcc02s69spxb8pnfwyx1z-qutebrowser-3.3.1/lib/python3.12/site-packages/qutebrowser
Using Python from /nix/store/g06lkc754bvcxzz2jcs9rnf189wd8ln1-python3-3.12.7-env/bin/python3.12
Qt library executable path: /nix/store/9prg7kzx3689q4ki17c6g1bwk4wj6wz2-qtbase-6.8.0/libexec, data path: /nix/store/9prg7kzx3689q4ki17c6g1bwk4wj6wz2-qtbase-6.8.0

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1001/qutebrowser
system data: /nix/store/bn6nspkvw5ibcc02s69spxb8pnfwyx1z-qutebrowser-3.3.1/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 0:01:38
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

Notification sound not playing on google chat. At the start i thought it was dunst, my notification daemon, but i tried another browser (firefox) and it worked flawlessly, so i guess the issue is here. Other sounds like YouTube videos play without any issues, so i have no clue where this is really coming from, but since the issue seems to be with the browser i decided to first open an issue here.

I have no idea if other notifications also will not show, if anyone suggest a way of testing notifications, please let me know.

**How to reproduce**
Open google chat (from the gmail app), allow notifications and test notifications.
![image](https://github.com/user-attachments/assets/483c2c53-7a66-465b-8258-291b20313006)

Thanks for any suggestions, and if any more information is needed i will provide it.

**Comment by pinarruiz** [comment]
To add a bit more context, I am on NixOs and recently updated to 24.11. This made me update qutebrowser from `3.2.1` to `3.3.1`

**Comment by The-Compiler** [comment]
It's just an MP3 being played by the website according to chrome://media-internals. Works just fine for me. This looks like an issue on your side, not something in qutebrowser. Steps I'd take to debug this:

- Look at `chrome://media-internals` and check what it has to say about the notification sound
- Try with another MP3, e.g. on http://hpr.dogphilosophy.net/test/
- If that also doesn't play, check if you have proprietary codecs enabled for QtWebEngine, apparently that's [optional in NixOS](https://github.com/NixOS/nixpkgs/blob/323a11c6750483e5272e6a41bf9aad540987fa4e/pkgs/development/libraries/qt-6/modules/qtwebengine.nix#L171-L172)
- If you do, open a packaging bug against NixOS I suppose.

**Comment by pinarruiz** [comment]
Thanks for the pointer i was lost :smile:
