### ISSUE TITLE
Cannot display equation in Quarto-compiled HTML

### ISSUE THREAD

**Issue by raffaem** [qutebrowser/qutebrowser#8428]
**Version info**:

```
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.8.1
  based on Chromium 122.0.6261.171
  with security patches up to 131.0.6778.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.1
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

Consider the following Quarto document:

```
---
title: "Title"
format: 
  html: default
---

# Section 1

This is Einstein's equation: $E=mc^2$
```

Compile it to HTML.

Qutebrowser is unable to render the equation:

![Screenshot_20241219_070638](https://github.com/user-attachments/assets/c0ff3065-5d3e-47ac-98a1-2f73026bef5a)

Firefox can:

![Screenshot_20241219_070651](https://github.com/user-attachments/assets/e8d1ecd9-7ff5-4d73-9fbb-8aee34e284ab)

Here is the Quarto source file and the compiled HTML:
[source.zip](https://github.com/user-attachments/files/18193314/source.zip)

**How to reproduce**

Open the HTML file in the attached zip file

**Comment by The-Compiler** [comment]
Works fine after setting `content.local_content_can_access_remote_urls` to true (or when not loading from a local file).

Also see #7220.

**Comment by raffaem** [comment]
It works, thanks!

For those coming here from Google (and a reminder to myself), you need this line:
```
c.content.local_content_can_access_remote_urls = True
```
in your `~/.config/qutebrowser/config.py` file.
