### ISSUE TITLE
Websites taking too long to respond, ERR_TIMED_OUT

### ISSUE THREAD

**Issue by mostafatouny** [qutebrowser/qutebrowser#8431]
**Version info**:
qutebrowser v3.3.1
Git commit:
Backend: QtWebEngine 6.8
based on Chromium 122.0.6261.171
with security patches up to 129.0.6668.70 (plus any distribution patches)
(source: api)
Qt: 6.8.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Websites [Aljazeera](https://www.aljazeera.com/opinions/2024/12/18/an-open-letter-from-mathematicians-against-the-genocide-in-gaza) and [Proton Calendar](https://calendar.proton.me/) take too long to respond, resulting in `Load error: ERR_TIMED_OUT`. The problem persists with a different internet provider.

![Screenshot_2024-12-20_14-13-50](https://github.com/user-attachments/assets/d115b502-f36b-4859-bd64-56cba3d1b1fa)

The two websites worked with Chromium, Version 130.0.6723.69 (Official Build) Arch Linux (64-bit).

**How to reproduce**
Launch any page of [Aljazeera](https://www.aljazeera.com/opinions/2024/12/18/an-open-letter-from-mathematicians-against-the-genocide-in-gaza) or [Proton Calendar](https://calendar.proton.me/).

**Comment by mostafatouny** [comment]
Thank you @The-Compiler for the quick response.

The same problem happens with the script

![Screenshot_2024-12-20_14-27-07](https://github.com/user-attachments/assets/60c5f6d2-b5ff-498d-b9e6-2d7d3c407902)

The two websites worked with [Croxy Proxy](https://www.croxyproxy.com/) in qutebrowser, though.

**Comment by The-Compiler** [comment]
Evidently not a qutebrowser issue then, but something on your side... Weird that it works in Chromium though. Could you show a screenshot of the network tab in `:devtools` and also of the equivalent in Chromium (Ctrl-Shift-I)?

**Comment by The-Compiler** [comment]
Or if you don't mind sharing some data (i.e. you don't log in and don't mind showing your IP and such), it would be even better if you could save a .har archive from both:

![image](https://github.com/user-attachments/assets/88bd3dd3-d396-4ec9-b1b5-c5a44405cb30)

and then share them here, or to `mail@qutebrowser.org`. I can't promise I'll find the time to take a closer look, but you certainly got me curious.

**Comment by mostafatouny** [comment]
I added `.json` to be able to upload the files on Github here.

[chromium_www.aljazeera.com.har.json](https://github.com/user-attachments/files/18210971/chromium_www.aljazeera.com.har.json)
[chromium_calendar.proton.me.har.json](https://github.com/user-attachments/files/18210977/chromium_calendar.proton.me.har.json)
[qutebrowser_www.aljazeera.com.har.json](https://github.com/user-attachments/files/18210979/qutebrowser_www.aljazeera.com.har.json)
[qutebrowser_calendar.proton.me.har.json](https://github.com/user-attachments/files/18210980/qutebrowser_calendar.proton.me.har.json)

Thank you for your time.

**Comment by mostafatouny** [comment]
I ticketed _Preserve Log_. No matter how many times I refresh or wait, I don't see anything.

![Screenshot_2024-12-20_15-31-25](https://github.com/user-attachments/assets/7be087d6-a27c-438b-a4bb-c60d8ff50ee5)

**Comment by mostafatouny** [comment]
A second trial brought this:

![Screenshot_2024-12-20_15-34-27](https://github.com/user-attachments/assets/30b8c3a6-9026-48c8-820b-70df0858233a)

[qutebrowser_www.aljazeera.com.har.json](https://github.com/user-attachments/files/18211275/qutebrowser_www.aljazeera.com.har.json)

**Comment by mostafatouny** [comment]
A third trial with calendar.proton.me

![Screenshot_2024-12-20_15-38-45](https://github.com/user-attachments/assets/a109db9c-6980-4a8d-aeac-275ef0c2c338)

[qutebrowser_calendar.proton.me.har.json](https://github.com/user-attachments/files/18211326/qutebrowser_calendar.proton.me.har.json)

**Comment by The-Compiler** [comment]
Meh, looks like the interesting parts to debug something like this are missing from the HAR archives... If you close the detail view, right-click the column headers, and display "Protocol" and "Remote Address", do you see any differences between Chromium and qutebrowser?

**Comment by mostafatouny** [comment]
I see difference but no notable clue, that explains the problem.

Chromium on calendar.proton.me

![Screenshot_2024-12-20_16-24-37](https://github.com/user-attachments/assets/f661c16d-6c44-4c86-ad3c-fd9210f5eee0)

Chromium on www.aljazeera.com

![Screenshot_2024-12-20_16-26-04](https://github.com/user-attachments/assets/09d5b919-bf90-4a8e-8d04-2573b39195a7)

Qutebrowser on calendar.proton.me then www.aljazeera.com

![Screenshot_2024-12-20_16-21-31](https://github.com/user-attachments/assets/61382d4c-2c4a-4c3e-98f8-d393b3203f0b)

**Comment by The-Compiler** [comment]
I'm out of ideas at this point unfortunately. Maybe `curl -v --http2 https://calendar.proton.me` with/without `--http2` can tell you more (just in case it happens to be reproducible there for some reason). If not, you'd probably need to fire up Wireshark and/or something like [mitmproxy](https://mitmproxy.org/) to find out what actually goes wrong there on protocol level.

In any case, this isn't a qutebrowser issue, so I'll close this. I'd normally recommend reporting this to QtWebEngine instead, but given that I can't reproduce and it seems like something network-related on your end, I'm not sure if that would lead anywhere. In any case, please let me know if you find out anything new, because I'm definitely curious what's going on there!
