### ISSUE TITLE
libva error: /usr/lib/dri/nvidia_drv_video.so init failed

### ISSUE THREAD

**Issue by rabaimorp** [qutebrowser/qutebrowser#8436]
**Version info**:

qutebrowser v3.4.0
Git commit: 1bcb536a4 on main (2024-12-14 22:28:12 +0100)
Backend: QtWebEngine 6.8.1
  based on Chromium 122.0.6261.171
  with security patches up to 131.0.6778.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.1

CPython: 3.13.1
PyQt: 6.8.0

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.5
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.8.0
PyQt6.sip: 6.9.1
pdf.js: no
sqlite: 3.47.2
QtNetwork SSL: OpenSSL 3.4.0 22 Oct 2024

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.
**Description**
After I updated my Arch Linux system with a simple "pacman -Syu" and rebooted qutebrowser wouldn't start. So I updated qutebrowser to the latest git version with "yay -S qutebrowser" cleanbuild. Now it works but I get an error I didn't used to get:

```
12:06:02 WARNING: Error while loading geometry.
12:06:02 WARNING: Error while loading geometry.
libva error: /usr/lib/dri/nvidia_drv_video.so init failed
```
and than it starts.
**How to reproduce**

Start the qutebrowser from the terminal normally, on an updated arch linux system with the proprietary nvidia drivers.

**Comment by The-Compiler** [comment]
That error doesn't originate from qutebrowser, so there's nothing it could do about it. Sounds like something that might need to be fixed in said graphic driver or somesuch.

**Comment by rabaimorp** [comment]
> That error doesn't originate from qutebrowser, so there's nothing it could do about it. Sounds like something that might need to be fixed in said graphic driver or somesuch.

You are right, I apologize. The issue was on my end, caused by an outdated enviroment variable I was yet to remove. I'll do more research next time if I have an issue, to make sure its not caused by something else.
