### ISSUE TITLE
crash loading https://solarcrew.nl/

### ISSUE THREAD

**Issue by mvhulten** [qutebrowser/qutebrowser#8439]
**Version info**:
```
qutebrowser v3.3.1
Git commit: 
Backend: QtWebEngine 6.7.3
  based on Chromium 118.0.5993.220
  with security patches up to 129.0.6668.58 (plus any distribution patches)
  (source: api)
Qt: 6.7.3

CPython: 3.12.8
PyQt: 6.7.1
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description and how to reproduce**
qutebrowser process ends when loading <https://solarcrew.nl/>:

```console
$ qutebrowser --temp-basedir https://solarcrew.nl/
16:41:01 WARNING: Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/local/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/local/lib/qt6/libexec/qtwebengine_dictionaries'
[91421:1332388096:1226/164106.643782:ERROR:render_process_host_impl.cc(3736)] Request for unknown Channel-associated interface: content.mojom.RenderMessageFilter
Trace/BPT trap (core dumped)
```

**Comment by The-Compiler** [comment]
That looks like an issue coming from Chromium/QtWebEngine, probably there isn't much qutebrowser can do. However I can't reproduce, even on the same version of Qt. What OS/distribution is this on?

**Comment by mvhulten** [comment]
This is on OpenBSD current, amd64.

```
OpenBSD 7.6-current (GENERIC.MP) #488: Tue Dec 24 20:22:05 MST 2024
```

I'm sorry, I forgot to mention this basic information.

**Comment by The-Compiler** [comment]
Can you reproduce if you run the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py) with something like `python3 testbrowser_webengine.py https://solarcrew.nl/` as well?

**Comment by The-Compiler** [comment]
OpenBSD has [over 1000 patches](https://github.com/openbsd/ports/tree/master/x11/qt6/qtwebengine/patches) on top of QtWebEngine, and the error message is:

`[91421:1332388096:1226/164106.643782:ERROR:render_process_host_impl.cc(3736)] Request for unknown Channel-associated interface: content.mojom.RenderMessageFilter`

which is something [patched out](https://github.com/openbsd/ports/blob/c4066baad0ed4785d322b17cbc6d0a6f95095547/x11/qt6/qtwebengine/patches/patch-src_3rdparty_chromium_content_browser_renderer_host_render_process_host_impl_cc#L44-L49) by OpenBSD:

```diff
+#if 0 // XXX
   scoped_refptr<RenderMessageFilter> render_message_filter =
       base::MakeRefCounted<RenderMessageFilter>(
           GetID(), GetBrowserContext(), widget_helper_.get(), media_internals);
   AddFilter(render_message_filter.get());
+#endif
```

so you probably should report this there instead.
