### ISSUE TITLE
Error initializing SQL: Database is too new for this qutebrowser version (database version 1.0, but 0.x is supported)

### ISSUE THREAD

**Issue by l29ah** [qutebrowser/qutebrowser#8441]
**Version info**:

qutebrowser v3.4.0
Git commit: 1bcb536a4-dirty on HEAD (2024-12-14 22:28:12 +0100)
Backend: QtWebEngine 6.8.1
  based on Chromium 122.0.6261.171
  with security patches up to 131.0.6778.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.1

**Does the bug happen if you start with `--temp-basedir`?**:
no

**Description**
The error dialog saying `Error initializing SQL: Database is too new for this qutebrowser version (database version 1.0, but 0.x is supported)` pops up at start. `20:36:00 ERROR: Fatal exception:` is printed in the console. Pressing OK in the dialog terminates qutebrowser.

**How to reproduce**

run qutebrowser

**Comment by The-Compiler** [comment]
This sounds like a self-made problem to me, the current git main has always had set the user version to 0:

https://github.com/qutebrowser/qutebrowser/blob/1bcb536a44351ea5d2a0eec6d51a247a97555118/qutebrowser/misc/sql.py#L184

The error gets raised if your `~/.local/share/qutebrowser/history.sqlite` has a higher user version (1 in your case) set:

https://github.com/qutebrowser/qutebrowser/blob/1bcb536a44351ea5d2a0eec6d51a247a97555118/qutebrowser/misc/sql.py#L201-L207

The only reasons why this could happen is:

- You modified the database file somehow outside of qutebrowser
- You're using local changes (as possibly hinted by the `-dirty` in your version number) that change the user version
- You were using an unmerged PR that changed the user version (#5481 would be my best guess?), but stopped using that

In any case, you'll need to figure out how to downgrade the database file yourself, there isn't really much qutebrowser can do here (other than automatically downgrading the data, but I'd rather not go down that rabbit hole).
