### ISSUE TITLE
URL does not update correctly on some pages (reload via JS)

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#870]
Recently (since GitHub also made some design changes?) sometimes navigating on GitHub won't update the URL in the statusbar, causing the wrong URL to be copied as well for example.

**Comment by The-Compiler** [comment]
I really can't say when this happens... I just know it's annoying. :-1:

**Comment by The-Compiler** [comment]
This happens consistently when clicking on the uploader for a YouTube video, or other navigation actions on YouTube.

**Comment by Earnestly** [comment]
This happens quite rarely on google search results.  Perhaps its worth noting Javascript is usually disabled on my end?

**Comment by Carpetsmoker** [comment]
I seem to be unable to reproduce this issue on GitHub, YouTube, or Google using the latest qutebrowser and QtWebKit Reloaded.

**Comment by The-Compiler** [comment]
I also haven't seen this in a while.
