### ISSUE TITLE
Convert qutebrowser.config.configdata to YAML

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#891]
Editing `configdata` is cumbersome because it stores a lot of data in code. After the config revolution, it should be a YAML file instead.

See [DumpingYAML](http://pyyaml.org/wiki/PyYAMLDocumentation#DumpingYAML) in the PyYAML docs on how to create custom representations for config types.

**Comment by acogneau** [comment]
Since this is not a separate issue from the rest of the config revolution: maybe it's best to create a new branch?

**Comment by The-Compiler** [comment]
To clarify: This will have no impact on users on its own - it's just the way the internal default config (and allowed types, etc.) is stored. Nonetheless, I'll probably work on this together with the rest of the config revolution.

**Comment by The-Compiler** [comment]
Since we now need to have conditionals and stuff (to only have QtWebEngine support with a given Qt version), this doesn't seem like a good idea anymore.

**Comment by The-Compiler** [comment]
Done in the new config.
