### ISSUE TITLE
Problem with IBus input

### ISSUE THREAD

**Issue by bchretien** [qutebrowser/qutebrowser#914]
While trying to write in qutebrowser with IBus + Japanese (Anthy) enabled, all I get is the keys I type without any IBus processing. However, IBus works as expected on the rest of my system (Vim, Firefox, etc.).

IBus was launched with:

``` sh
export XMODIFIERS="@im=ibus"
export XIM=ibus
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
ibus-daemon --xim&
```

This was tested on Arch Linux, with the current master branch.

Yet, #835 seems to imply that IBus is/was working (and this issue is fairly recent), so maybe something is wrong with my qutebrowser configuration, but I wouldn't know what.

**Comment by The-Compiler** [comment]
I'm not familiar with complex input methods at all I'm afraid, so I can't help much...

The only thing I found is [QTBUG-40541](https://bugreports.qt.io/browse/QTBUG-40541), but that seems to be a different issue, right?

Does it work in other Qt 5 applications (say, Otter Browser)? Does it work differently in the commandline and on webpage form fields?

Maybe @ongy or @nosuck can say more?

**Comment by bchretien** [comment]
I tested in qcachegrind/qpdfview/otter-browser and it works as expected.

The bug you linked may be related, it's hard to say. They do get non-ascii characters, while I don't, but I'm not using the same input method as they do. Basically here's what's supposed to happen:

* I type `kyou`, `きょう` is displayed and underlined,
* I hit space repeatedly, IBus suggests different kanji candidates,
* I choose `今日` and hit enter.

In qutebrowser, all I get is `kyou` as plain text.

The behavior I described is the same for both the command line and webpage form fields, and the same is expected for both.

**Comment by The-Compiler** [comment]
Thanks for the explanation! This might be related to how qutebrowser filters all keys with an event filter to process them according to the current mode.

I'll play with it later today when I'm back on Archlinux - but I'm not sure if there's a good way to fix this while preserving qutebrowser's input model :worried:

**Comment by NoSuck** [comment]
I run the same distro and software and have yet to encounter any problems with IBus involving qutebrowser.  Here is what I use to start the daemon:

```shell
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx```

**Comment by bchretien** [comment]
@NoSuck thanks for the feedback! This is indeed working with these exports, so the culprit is `export QT_IM_MODULE=xim`. I can't remember why I needed this, so I guess I'll fallback to the default for now.

**Comment by NoSuck** [comment]
Glad to hear it!  Feel free to tag me for future IBus/Anthy/Japanese issues.

**Comment by hshin23** [comment]
@NoSuck @bchretien 
Did you guys get it to work? I wasn't caring too much about exporting the variables up until now (because it was working fine all along), but when I tried exports in `.bashrc`, `.xprofile`, and also `.xinitrc`, the variables do not get exported when I test with `echo $VARIABLE`... 

So I killed ibus and retried by typing in all the exports and then finally running `ibus-daemon -drx` but this still doesn't let me type in a different language on qutebrowser. Any help would be great!

**Comment by Ongy** [comment]
Afaik you need the variables set on the application taking the input, not the daemon.
My setup (in .xinitrc) is:

    export GTK_IM_MODULE="ibus"
    export XMODIFIERS="@im=ibus"
    export QT_IM_MODULE="ibus"
    export XMODIFIER="@im=ibus"
    export DefaultIMModule="ibus"
    ibus-daemon --xim &

But I really don't know which export qutebrowser uses, I guess the QT_ one.

**Comment by hshin23** [comment]
@Ongy Well, I fixed the issue by editting `/etc/X11/xinit/xinitrc`... Although it bugs me why this works when I'm not on root...

**Comment by The-Compiler** [comment]
Is this still an issue nowadays?

**Comment by NoSuck** [comment]
Pssh, no.  (It never was.)

**Comment by The-Compiler** [comment]
Given that ibus seems to work fine for several people, I'm closing this.

**Comment by keeganjk** [comment]
I am having an issue with ibus and qutebrowser, it works fine in Firefox and my terminal, but not qutebrowser.

**Comment by The-Compiler** [comment]
@keeganjk Not much anyone can say with so little information.

**Comment by keeganjk** [comment]
@The-Compiler If I try to switch ibus inputs, it just does not change. When I try typing, it still looks the same. Using other applications, like chromium and my terminal, it works without fail.

https://user-images.githubusercontent.com/24554125/102829900-17f56880-43b6-11eb-917a-c86e8e172132.mp4

**Comment by The-Compiler** [comment]
@keeganjk Did you set environment variables correctly? In particular, are `QT_IM_MODULE=ibus` and `XMODIFIERS=@im=ibus` set? Have you tried other Qt applications such as KDE Falkon?

**Comment by keeganjk** [comment]
@The-Compiler I just tried to set those and close/reopen `qutebrowser` but it still does not work properly.

**Comment by keeganjk** [comment]
I have also installed `ibus-qt` and put 
```
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
export XIM_PROGRAM=/usr/bin/ibus-daemon
```
into `~/.xprofile`, the issue still occurs.

**Comment by The-Compiler** [comment]
If you run `:report` in qutebrowser (and mention this issue) I might be able to see something in the logs - but I still suspect this is some misconfiguration in your system. Like I said above, it'd be interesting to see how things look in other Qt(WebEngine) applications.

**Comment by keeganjk** [comment]
@The-Compiler I have sent the logs over

**Comment by The-Compiler** [comment]
Above you said you have `QT_IM_MODULE=ibus` set, yet your log says `QT_IM_MODULE = xim`.

**Comment by keeganjk** [comment]
That's odd, it seems that the environmental variable is set and readable in my terminal. Does qutebrowser read any files for this? Is there anything that would be changing it?

**Comment by The-Compiler** [comment]
Only its `config.py`. Note that if you set it in your `.bashrc` or similar, that value will only affect shells but not graphical applications.

**Comment by keeganjk** [comment]
> that value will only affect shells but not graphical applications.

I did not know that. I've been using `.zshenv` for environmental variables. Is there something else I need to use to set them for graphical environments, or some way in which I am supposed to "load" `.xprofile`?

**Comment by keeganjk** [comment]
I have just sourced `.xprofile` in `.xinitrc` with
```
# Make sure this is before the 'exec' command or it won't be sourced.
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile
```
but the log file still says `QT_IM_MODULE = xim`

**Comment by The-Compiler** [comment]
Not much more I can say here - nothing of this is qutebrowser-specific. I still suspect other Qt applications will be affected as well FWIW.

**Comment by keeganjk** [comment]
I have fixed the issue, it turns out I had `export QT_IM_MODULE=xim` in my `xinitrc`. Changing this to `export QT_IM_MODULE=ibus` solved the issue.
