### ISSUE TITLE
Make it possible to hide completion categories without values

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#960]

**Comment by Ape** [comment]
I really don't use bookmarks or quickmarks, so I only use completion from history. I'd really like to hide the category headers. Hiding the categories without values would be a good way to do this. In addition, if there is only one category with values, I would like to hide its header, too.

**Comment by The-Compiler** [comment]
I think this can be closed with #3279 in - thanks @rcorre!

**Comment by The-Compiler** [comment]
Reopened as the commit was reverted.

**Comment by rcorre** [comment]
Depends on #3016
