### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#999]
My goal for qutebrowser is to have (near-)100% test coverage at some point.
# Short-time TODO for #666
- BDD tests for:
  - [x] urlmarks
  - [x] external editor
  - [x] `:spawn` and userscripts
  - [ ] adblocking
  - [x] downloads
  - [x] hints
  - [x] various prompts (webpage auth, proxy auth?, wrong SSL cert, etc.)
  - [x] insert mode (e.g. when clicking an editable element, etc.)
  - [x] remaining tests for searching (#1050, #874, #638, #507, #940)
# Modules without 100% coverage
- [ ] app _(hard)_
- [ ] qutebrowser _(hard)_
- browser
  - [ ] adblock
  - [x] cache _(easy)_
  - [ ] commands _(hard)_
  - [x] cookies
  - [ ] downloads _(hard)_
  - [ ] downloadview
  - [ ] hints _(hard)_
  - [x] history _(easy)_ (partial abandoned PR at #1049)
  - [x] http
  - [ ] mhtml
  - [ ] pdfjs
  - [x] inspector _(easy)_
  - network
    - [ ] networkmanager _(hard)_
    - [x] networkreply
    - [x] pastebin
    - [ ] proxy _(easy)_
    - [ ] qutescheme
    - [x] schemehandler
  - [ ] urlmarks
  - [x] rfc6266
  - [x] signalfilter
  - [x] tabhistory
  - [x] webelem
  - _webpage/webview will be refactored soon-ish (#724), so integration-style tests might make more sense here. Probably not a good thing to work on if you're a contributor._
  - [ ] webpage
  - [ ] webview
- commands
  - [x] argparser
  - [x] cmdexc
  - [x] cmdutils
  - [ ] command
  - [ ] runners
  - [ ] userscripts
- completion
  - _There will be a completion refactoring soon-ish (#74), so integration-style tests might make more sense here. Probably not a good thing to work on if you're a contributor._
  - [ ] completer
  - [ ] completiondelegate
  - [ ] completionwidget
  - models
    - [x] base
    - [ ] configmodel
    - [ ] instances
    - [ ] miscmodels
    - [x] sortfilter
    - [ ] urlmodel
- config
  - _There will be a [config revolution](https://github.com/The-Compiler/qutebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+milestone%3A%22config+revolution%22+) soon-ish, so integration-style tests might make more sense here. Probably not a good thing to work on if you're a contributor._
  - [ ] config
  - [x] configdata
  - [x] configexc
  - [x] configtypes
  - [ ] ini
  - [ ] keyconf
  - [ ] sections
  - [x] style
  - [x] textwrapper
  - [ ] value
  - [ ] websettings
- keyinput
  - [x] basekeyparser
  - [ ] keyparser _(easy)_
  - [ ] modeman _(easy-ish)_
  - [ ] modeparsers _(easy-ish)_
- mainwindow
  - [ ] mainwindow _(hard)_
  - statusbar
    - [x] keystring
    - [x] percentage
    - [x] progress
    - [x] tabindex
    - [ ] text _(easy)_
    - [x] textbase
    - [x] url _(easy)_
    - [x] prompt
    - [ ] prompter
    - [ ] command
    - The statusbar things below will be refactored soon-ish (#368), so integration-style tests might make more sense here. Probably not a good thing to work on if you're a contributor.*
    - [ ] bar
  - [ ] tabbedbrowser _(hard)_
  - [ ] tabwidget _(hard)_
- misc
  - [x] autoupdate
  - [x] checkpyver
  - [x] cmdhistory
  - [ ] consolewidget _(hard)_
  - [ ] crashdialog _(hard, needs some refactoring for GUI/logic first)_
  - [ ] crashsignal _(hard)_
  - [ ] earlyinit _(hard)_
  - [x] editor
  - [x] guiprocess
  - [ ] httpclient _(hard, probably needs some local server)_
  - [x] ipc
  - [ ] lineparser
  - [ ] miscwidgets
  - [x] msgbox
  - [x] readline
  - [ ] savemanager
  - [ ] sessions
  - [x] split
  - [ ] utilcmds
- utils
  - [x] debug
  - [ ] docutils
  - [x] error
  - [x] jinja
  - [ ] log
  - [ ] message
  - [ ] objreg
  - [x] qtutils
  - [x] standarddir
  - [x] urlutils
  - [x] usertypes
  - [x] utils
  - [x] version

---

I'd also like a bdd-style test (check `tests/integration/features`) for every command where it makes sense:
- [ ] `adblock-update`
- [x] `back`
- [x] `bind`
- [x] `bookmark-add`
- [x] `bookmark-del`
- [x] `bookmark-load`
- [x] `clear-keychain`
- [ ] `close`
- [x] `command-accept`
- [ ] `command-history-next`
- [ ] `command-history-prev`
- [ ] `completion-item-del`
- [ ] `completion-item-next`
- [ ] `completion-item-prev`
- [ ] `debug-all-objects`
- [ ] `debug-cache-stats`
- [x] `debug-console`
- [ ] `debug-crash`
- [x] `debug-pyeval`
- [ ] `debug-trace`
- [x] `debug-webaction`
- [x] `download`
- [x] `download-cancel`
- [x] `download-clear`
- [x] `download-delete`
- [x] `download-open`
- [x] `download-remove`
- [x] `download-retry`
- [x] `drop-selection`
- [ ] `enter-mode`
- [x] `fake-key`
- [x] `follow-hint`
- [x] `follow-selected`
- [x] `forward`
- [ ] `fullscreen`
- [x] `help`
- [ ] `hint`
- [x] `home`
- [x] `inspector`
- [x] `jseval`
- [ ] `later`
- [ ] `leave-mode`
- [x] `message-error`
- [x] `message-info`
- [x] `message-warning`
- [x] `move-to-end-of-document`
- [x] `move-to-end-of-line`
- [x] `move-to-end-of-next-block`
- [x] `move-to-end-of-prev-block`
- [x] `move-to-end-of-word`
- [x] `move-to-next-char`
- [x] `move-to-next-line`
- [x] `move-to-next-word`
- [x] `move-to-prev-char`
- [x] `move-to-prev-line`
- [x] `move-to-prev-word`
- [x] `move-to-start-of-document`
- [x] `move-to-start-of-line`
- [x] `move-to-start-of-next-block`
- [x] `move-to-start-of-prev-block`
- [x] `navigate`
- [x] `open`
- [ ] `open-editor`
- [x] `paste`
- [x] ~~`print`~~
- [x] `prompt-accept`
- [x] `prompt-no`
- [x] `prompt-yes`
- [ ] `q`
- [x] `quickmark-add`
- [x] `quickmark-del`
- [x] `quickmark-load`
- [x] `quickmark-save`
- [ ] `quit`
- [x] `reload`
- [ ] `repeat`
- [ ] `report`
- [ ] `restart`
- [x] ~~`rl-backward-char`~~
- [x] `rl-backward-delete-char`
- [x] ~~`rl-backward-word`~~
- [x] ~~`rl-beginning-of-line`~~
- [x] ~~`rl-delete-char`~~
- [x] ~~`rl-end-of-line`~~
- [x] ~~`rl-forward-char`~~
- [x] ~~`rl-forward-word`~~
- [x] ~~`rl-kill-line`~~
- [x] ~~`rl-kill-word`~~
- [x] ~~`rl-unix-line-discard`~~
- [x] ~~`rl-unix-word-rubout`~~
- [x] ~~`rl-yank`~~
- [ ] `save`
- [x] `scroll`
- [x] `scroll-page`
- [x] `scroll-perc`
- [x] `scroll-px`
- [x] `search`
- [x] `search-next`
- [x] `search-prev`
- [x] `session-delete`
- [x] `session-load`
- [x] `session-save`
- [x] `set`
- [x] `set-cmd-text`
- [x] `spawn`
- [x] `stop`
- [x] `tab-clone`
- [x] `tab-close`
- [x] `tab-detach`
- [x] `tab-focus`
- [x] `tab-move`
- [x] `tab-next`
- [x] `tab-only`
- [x] `tab-prev`
- [x] `toggle-selection`
- [x] `unbind`
- [x] `undo`
- [x] `view-source`
- [ ] `w`
- [ ] `wq`
- [x] `yank`
- [x] `yank-selected`
- [x] `zoom`
- [x] `zoom-in`
- [x] `zoom-out`

---

And for settings (color/font settings removed):
- general
  - [x] ignore-case
  - [x] wrap-search
  - [ ] startpage
  - [x] default-page
  - [ ] auto-search
  - [ ] auto-save-config
  - [ ] auto-save-interval
  - [ ] editor
  - [ ] editor-encoding
  - [ ] private-browsing
  - [x] developer-extras
  - [ ] print-element-backgrounds
  - [ ] xss-auditing
  - [ ] site-specific-quirks
  - [ ] default-encoding
  - [ ] new-instance-open-target
  - [ ] log-javascript-console
  - [ ] save-session
  - [ ] session-default-name
  - [x] url-incdec-segments
- ui
  - [x] zoom-levels
  - [x] default-zoom
  - [ ] downloads-position
  - [ ] message-timeout
  - [ ] message-unfocused
  - [ ] confirm-quit
  - [ ] display-statusbar-messages
  - [ ] zoom-text-only
  - [ ] frame-flattening
  - [ ] user-stylesheet
  - [ ] css-media-type
  - [ ] smooth-scrolling
  - [ ] remove-finished-downloads
  - [ ] hide-statusbar
  - [ ] statusbar-padding
  - [ ] window-title-format
  - [ ] hide-mouse-cursor
  - [ ] modal-js-dialog
  - [ ] hide-wayland-decoration
- network
  - [x] do-not-track
  - [x] accept-language
  - [ ] referer-header
  - [ ] user-agent
  - [ ] proxy
  - [ ] proxy-dns-requests
  - [ ] ssl-strict
  - [ ] dns-prefetch
- completion
  - [ ] auto-open
  - [x] download-path-suggestion
  - [ ] timestamp-format
  - [ ] show
  - [ ] height
  - [ ] cmd-history-max-items
  - [ ] web-history-max-items
  - [ ] quick-complete
  - [ ] shrink
  - [x] ~~scrollbar-width~~
  - [x] ~~scrollbar-padding~~
- input
  - [ ] timeout
  - [ ] partial-timeout
  - [ ] insert-mode-on-plugins
  - [x] auto-leave-insert-mode
  - [x] auto-insert-mode
  - [x] forward-unbound-keys
  - [ ] spatial-navigation
  - [ ] links-included-in-focus-chain
  - [ ] rocker-gestures
  - [ ] mouse-zoom-divider
- tabs
  - [x] background-tabs
  - [x] select-on-remove
  - [x] new-tab-position
  - [x] new-tab-position-explicit
  - [x] last-close
  - [ ] show
  - [ ] show-switching-delay
  - [x] wrap
  - [ ] movable
  - [ ] close-mouse-button
  - [ ] position
  - [ ] show-favicons
  - [ ] width
  - [ ] indicator-width
  - [ ] tabs-are-windows
  - [x] ~~title-alignment~~
  - [ ] title-format
  - [ ] mousewheel-tab-switching
  - [ ] padding
  - [ ] indicator-padding
- storage
  - [ ] download-directory
  - [ ] prompt-download-directory
  - [ ] remember-download-directory
  - [ ] maximum-pages-in-cache
  - [ ] object-cache-capacities
  - [ ] offline-storage-default-quota
  - [ ] offline-web-application-cache-quota
  - [ ] offline-storage-database
  - [ ] offline-web-application-storage
  - [ ] local-storage
  - [ ] cache-size
- content
  - [ ] allow-images
  - [ ] allow-javascript
  - [ ] allow-plugins
  - [x] pdfjs-enabled
  - [ ] webgl
  - [ ] css-regions
  - [ ] hyperlink-auditing
  - [ ] geolocation
  - [ ] notifications
  - [ ] javascript-can-open-windows
  - [ ] javascript-can-close-windows
  - [ ] javascript-can-access-clipboard
  - [ ] ignore-javascript-prompt
  - [ ] ignore-javascript-alert
  - [ ] local-content-can-access-remote-urls
  - [ ] local-content-can-access-file-urls
  - [ ] cookies-accept
  - [ ] cookies-store
  - [ ] host-block-lists
  - [ ] host-blocking-enabled
  - [ ] host-blocking-whitelist
- hints
  - [ ] border
  - [ ] opacity
  - [ ] mode
  - [ ] chars
  - [ ] min-chars
  - [ ] scatter
  - [ ] uppercase
  - [ ] auto-follow
  - [ ] next-regexes
  - [ ] prev-regexes
- searchengines
- aliases

---

Many of those are quite easy to get into and ideal for contributors who want to start learning how to write tests, which is why I marked this issue as easy.

A possibly more up-to-date list can be found in [check_coverage.py](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/dev/check_coverage.py#L43)

Things which already have existing tests are probably easiest to get started with - to find out which those are:
- Check the [buildbot](http://qutebrowser.org:8010/waterfall)
- Click "coverage xx%" in the Archlinux column
- Sort by coverage %

**Comment by neeasade** [comment]
FYI to future contributors, I'm working on keyinput ->keyparser tests.

**Comment by lamarpavel** [comment]
I'm working on browser->cache atm.

**Comment by mjbeaton** [comment]
Hi!

I'm looking to make my first commit and this looks like a simple enough way to get there...  Any pointers?  Which is the best test to start with?

Thanks in advance :)

**Comment by The-Compiler** [comment]
Hey, and welcome!

There are basically two kinds of tests - unittests which are written in Python (with a todo-list per file above), and end-to-end tests which are [written like this](https://github.com/The-Compiler/qutebrowser/blob/master/tests/integration/features/set.feature), with a todo-list per command/setting above.

So first of all, you'd need to decide what you'd rather write - a unittest based on Python/pytest, or an end-to-end test.

For the unit tests, there are some files marked *easy* above, which are the ones I think should be quite straightforward to write unittests for. The [pytest docs](http://pytest.org/latest/contents.html) will probably be helpful.

For the end-to-end/BDD tests, find a qutebrowser feature which sounds easy enough to test with the current test harness (start qutebrowser, send commands, parse log output). For example, `:repeat` will probably be relatively easy to test, as you can just e.g. call `:repeat 3 message-info test` and then check if it was actually logged three times (by e.g. doing `Then the message "test" should be shown` three times).

I hope that helped a bit, in the end it's hard to say what would be easiest to pick. Feel free to drop by in the IRC channel (`#qutebrowser` on Freenode, [webchat](https://webchat.freenode.net/?channels=#qutebrowser) too) if you need help!

**Comment by mjbeaton** [comment]
Thanks mate i'll take a look at a unit test for keyinput:  keyparser and see how it goes!

**Comment by phansch** [comment]
Started working on BDD tests for `tabs -> background-tabs`  and `tabs -> new-tab-position`

**Comment by sebastian-frysztak** [comment]
I wanted to implement some tests, but it seems that this list is out of date.
Some tests are already implemented:
- [DNT and Accept-Language](https://github.com/The-Compiler/qutebrowser/blob/master/tests/end2end/features/misc.feature#L425)
- [downloads](https://github.com/The-Compiler/qutebrowser/blob/master/tests/end2end/features/downloads.feature)

Also, would you have any suggestions which tests are needed and not too difficult to implement?

**Comment by The-Compiler** [comment]
Thanks! I updated the obvious ones, but unfortunately keeping this list accurate and up-to-date is quite difficult :wink:

Note the goal for the ones at the top is 100% unittest coverage, so for some modules there are *some* tests, but not all functionality is tested.

As for suggestions what to work on: Maybe an easy thing to start with are end2end (BDD) tests for `:command-history-next` and `:command-history-prev`? It should be relatively easy to write a test (e.g. in `misc.feature`) which runs a command where we notice when it's been run twice (say, `:message-info`), runs it again via `:set-cmd-text :` (equivalent to pressing `:`) , `:command-history-prev` (`Ctrl-P`) and `:command-accept` (`Enter`) and then checks the message was shown twice (just doing `Then ... should be logged` twice should work).

**Comment by The-Compiler** [comment]
I'm going to close this - qutebrowser's testsuite is doing okay now with 81% coverage - while there's still a lot to do, it's very difficult to keep the list above up-to-date with a fast-moving target like qutebrowser.

For anyone wondering what still needs tests, I suggest you look at [codecov](https://codecov.io/gh/qutebrowser/qutebrowser/tree/master/qutebrowser), or more precisely at any file there which doesn't have 100% coverage yet.

If anyone wants to contribute tests but doesn't know how to start, simply contact me (via  github.com@the-compiler.org or a comment here) and I'll be happy to help you getting started.
